### PR TITLE
ddl: fix concurrent column type changes(with changing data) that cause schema and data inconsistencies (#31051)

### LINKED ISSUE #31048: Concurrent Column Type Change would cause inconsistent schema and data
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
create table test(a int, b int);
insert into test values (1, 1);
alter table test change column b b double; /* in session 1 */
alter table test change column b b double; /* in session 2 */
select * from test;
```

### 2. What did you expect to see? (Required)
No error

### 3. What did you see instead (Required)
``` SQL
mysql> select * from test;
ERROR 1105 (HY000): insufficient bytes to decode value
```
### 4. What is your TiDB version? (Required)
5.1 5.2 5.3 master

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #31051 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/31071
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/31071:release-5.3-4ca3b02c90b7
```

---

### What problem does this PR solve?

Issue Number: close #31048

Problem Summary:

For column type changes, the column ID is changed if it is lossy.

If both sessions perform lossy column type changes((like modify column c int -> char)) simultaneously

1. Connection1: execute DDL1, it will change column ID (ID :1-> ID :2)

2. Connection2: execute DDL2. After DDL1 enters the DDL job queue and is not executed, then DDL2 enters the job queue.

3. After DDL1 is executed successfully, DDL2 considers that the column is not lossy(char -> char), so it does not change the column ID, which is the old id:1. So id:1 overwrites id:2.

After DDL2 is completed, the column ID is still the original id:1 instead of the correct id:2.

Because the column ID was changed incorrectly, the schema could not match the data, resulting in decode failure when reading data.

### What is changed and how it works?
In step 3, we check that the ID of the modified column is the same as the ID of the original column.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix concurrent column type changes(with changing data) that cause schema and data inconsistencies.
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Comment by guo-shaoge** [comment]
/run-check_dev
/run-mysql-test

@zimulala please remember to merge this pr. A new version is about to release. Thanks!

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
