### PR TITLE
dumpling: fix tidb lock consistency and check tikv problem (#29448)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #29448 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/29502
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/29502:release-5.3-651e910911df
```

---

### What problem does this PR solve?
 
Issue Number: close https://github.com/pingcap/tidb/issues/29411

Problem Summary:
1. dumpling may dump inconsistent data when dumping tidb using consistency lock but tidb `enable-table-lock` is false.
2. dumpling check whether tidb has tikv may face a privilege problem. Using `select @@tidb_config` can avoid this problem.

### What is changed and how it works?
Use `SELECT @@tidb_config` to solve these problems.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by lichunzhu — APPROVED** [review]

**Comment by lance6716** [comment]
seems conflict

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
