### PR TITLE
Issue 19371 - Prepare statement with @Var (uppercase in var name fix) (#19373)

### LINKED ISSUE #19371: PREPARE stmt FROM @UpperCaseVar
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

mysql> set @v := 'select count(*) from information_schema.tables';
Query OK, 0 rows affected (0.00 sec)

mysql> prepare stmt from @V;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 4 near "NULL"

The problem occurs whenever there is an uppercase letter in the variable name in the prepare statement.

Proposed fix.

```
diff --git a/planner/core/planbuilder.go b/planner/core/planbuilder.go
index fe9393e..ea0b980 100644
--- a/planner/core/planbuilder.go
+++ b/planner/core/planbuilder.go
@@ -869,7 +869,7 @@ func (b *PlanBuilder) buildPrepare(x *ast.PrepareStmt) Plan {
                Name: x.Name,
        }
        if x.SQLVar != nil {
-               if v, ok := b.ctx.GetSessionVars().Users[x.SQLVar.Name]; ok {
+               if v, ok := b.ctx.GetSessionVars().Users[strings.ToLower(x.SQLVar.Name)]; ok {
                        p.SQLText = v.GetString()
                } else {
                        p.SQLText = "NULL"
```

### 2. What did you expect to see? (Required)

mysql> prepare stmt from @v;
Query OK, 0 rows affected (0.00 sec)

### 3. What did you see instead (Required)

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 4 near "NULL"

### 4. What is your TiDB version? (Required)

4.0.4

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19373 to release-3.0

---

### What problem does this PR solve?

Issue Number: close #19371 

Problem Summary:

### What is changed and how it works?

What's Changed:

Fixed the above issue. It is one line fix.

                Name: x.Name,
        }
        if x.SQLVar != nil {
-               if v, ok := b.ctx.GetSessionVars().Users[x.SQLVar.Name]; ok {
+               if v, ok := b.ctx.GetSessionVars().Users[strings.ToLower(x.SQLVar.Name)]; ok {
                        p.SQLText = v.GetString()
                } else {
                        p.SQLText = "NULL"

How it Works:

Variables are lowercased when inserted into the map. All lookups should also convert to lowercase before lookup.

### Check List 
Tests

Tests added.
"make dev" test passed

Side effects

No significant performance regression expected.

### Release note 

Fix issue 19371 - PREPARE statement FROM @Var (where Var contains uppercase characters fail)

### CODE REVIEW

**Comment by bb7133** [comment]
PTAL @XuHuaiyu @SunRunAway

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Pull request merged**
