### PR TITLE
executor: fix pipelined window invalid memory address

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/30326

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
executor: fix pipelined window invalid memory address
```

### CODE REVIEW

**Review by ichn-hu — APPROVED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Comment by XuHuaiyu** [comment]
Do we need to cherrypick this PR to release branches?

**Pull request merged**
