### PR TITLE
server: add build not race flag

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

 add build not race flag

relation with #29535 

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
@LittleFall @tisonkun  PTAL

**Review by tisonkun — APPROVED** [review]

**Comment by tiancaiamao** [comment]
>  relation with #29535

I don't know the relation and why this change ... can you explain it a bit more? @hawkingrei

**Comment by hawkingrei** [comment]
When ```make race```, This file need to use ```function``` from the file with ```build !race```. It will lead to fail to build.

**Comment by hawkingrei** [comment]
> > relation with #29535
> 
> I don't know the relation and why this change ... can you explain it a bit more? @hawkingrei

When ```make race```, This file needs to use a function from the file with ```build !race``` It will lead to fail to build.

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
