### PR TITLE
*: Add support "show open tables"

### PR DESCRIPTION
**Pull request by july2993**
### What problem does this PR solve? 
fix https://github.com/pingcap/tidb/issues/10070

relate parser pr: https://github.com/pingcap/parser/pull/291
### What is changed and how it works?
TiDB has no concept like mysql's "table cache" and "open table"
For simplicity, we just return an empty result with the same structure
as MySQL's SHOW OPEN TABLES

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
build and run "show open tables" using mysql client

 Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Comment by morgo** [comment]
LGTM

**Comment by july2993** [comment]
can anyone help approve and merge it?

**Comment by morgo** [comment]
@july2993 I have approved it.

**Pull request merged**
