### PR TITLE
auth: fix iterations decode error in hashCrypt

### LINKED ISSUE #43576: caching_sha2_password iterations handling error
### 1. Minimal reproduce step (Required)

In MySQL the default number of rounds is 5000. The MySQL server being tested has been configured with 10000 rounds using the [caching_sha2_password_digest_rounds](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_caching_sha2_password_digest_rounds) server system variable.

A hash with 10000 iterations gets retrieved that starts like this:

`$A$00A$...` instead of `$A$010$...`

### 2. What did you expect to see? 

The number of iterations should be decoded in hexadecimal not decimal

### related info

https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_caching_sha2_password_digest_rounds

https://github.com/hashcat/hashcat/issues/3049

### PR DESCRIPTION
**Pull request by asjdf**
### What problem does this PR solve?

Issue Number: close #43576

Problem Summary:

### What is changed and how it works?

Fix iterations decode error in hashCrypt when using caching_sha2_password and tidb_sm3_password.
The number of iterations is decoded in hexadecimal instead of decimal.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Improve the compatibility with MySQL, but will break backward compatibility if caching-sha2-password-digest-rounds >= 10000 
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
@asjdf  Please fix the linter.

```
parser/auth/caching_sha2.go:173:2: avoid allocations with (*bytes.Buffer).WriteString (mirror)
```

**Comment by asjdf** [comment]
I am very sorry that I did some wrong conflict handling when merging.

**Review by hawkingrei — APPROVED** [review]

**Comment by asjdf** [comment]
/assign @hawkingrei 

Thanks for your review ❤, could you help me merge this pull request?

**Pull request merged**
