### PR TITLE
*: Refactor runaway related code

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Refactor runaway related code

1. Take the concept of the syncer out of the domain and put it into the manager, the domain only interacts with the manager.
2. Refine runaway code in domain/runaway, e.g. put loops in manager instead of domain
3. Moved runaway code to pkg/resourcegroup (can move the ResourceGroup-related code later).
4. table operations of runaway have been put together with the record, and are called by manager/checker/syncer.

Issue Number: Ref #54434

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by nolouch — COMMENTED** [review]
overall lgtm.

**Comment by HuSharp** [comment]
@glorv @JmPotato PTAL, thx~

**Review by glorv — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Comment by HuSharp** [comment]
@XuHuaiyu PTAL, thx~

**Review by XuHuaiyu — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Review by yudongusa — APPROVED** [review]
LGTM

**Pull request merged**
