### PR TITLE
executer: fix data race

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### What is changed and how it works?

fix data race

```
WARNING: DATA RACE
Write at 0x00c0019fb580 by goroutine 76:
  github.com/pingcap/tidb/executor.ResetContextOfStmt()
      /go/tidb/executor/executor.go:1854 +0x1192
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      /go/tidb/session/session.go:1534 +0x204
  github.com/pingcap/tidb/testkit.(*TestKit).Exec()
      /go/tidb/testkit/testkit.go:145 +0x2dc
  github.com/pingcap/tidb/testkit.(*TestKit).MustQuery()
      /go/tidb/testkit/testkit.go:90 +0x176
  github.com/pingcap/tidb/table/tables_test.TestCacheTablePointGet()
      /go/tidb/table/tables/cache_test.go:329 +0x315
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202

Previous read at 0x00c0019fb580 by goroutine 144:
  github.com/pingcap/tidb/executor.(*executorBuilder).getCacheTable.func1()
      /go/tidb/executor/builder.go:4709 +0xbc
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]
A temporary workaround ... the real fix still need some work.

**Pull request merged**
