### PR TITLE
types: remove some unreachable codes.

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Remove some unreachable codes.

### What is changed and how it works?

1. if fsp == len(s), then index must be -1.
But if index is -1, fsp would be 0.
So it's impossible to reach these codes.
2. Since Tp it string, it can't be isTemporalColumn.
### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
 'None'

### CODE REVIEW

**Review by zimulala — APPROVED** [review]

**Review by xiongjiwei — APPROVED** [review]

**Comment by wjhuang2016** [comment]
@ti-chi-bot

**Pull request merged**
