### PR TITLE
tidb: read plan.PlanCacheEnabled only once

### PR DESCRIPTION
**Pull request by zz-jason**
fix http://45.249.247.133:8080/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/1338/pipeline

```txt
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8c9696]



goroutine 181 [running]:

github.com/pingcap/tidb/util/kvcache.(*ShardedLRUCache).Put(0xc42196c990, 0x0, 0x0, 0x10b4260, 0xc420da4510)

	/home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/kvcache/sharded_lru.go:53 +0x26

github.com/pingcap/tidb.(*session).Execute(0xc42017a000, 0x7f88b88c7490, 0xc420014110, 0xc421b2e580, 0x73, 0x0, 0x0, 0x0, 0x0, 0x0)

	/home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session.go:811 +0xe05

github.com/pingcap/tidb/ddl/util.LoadDeleteRanges(0x1b3f300, 0xc42017a000, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)

	/home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/util/util.go:48 +0x1e0

github.com/pingcap/tidb/ddl.(*delRange).doDelRangeWork(0xc4209a4a80, 0x0, 0x0)

	/home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/delete_range.go:137 +0x242

github.com/pingcap/tidb/ddl.(*delRange).startEmulator(0xc4209a4a80)

	/home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/delete_range.go:121 +0xaf

created by github.com/pingcap/tidb/ddl.(*delRange).start

	/home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/delete_range.go:99 +0x74

```

### CODE REVIEW

**Comment by zz-jason** [comment]
@coocood @winkyao PTAL

**Comment by coocood** [comment]
How about to use a local variable to store `GlobalPlanCache`?

**Comment by winkyao** [comment]
why this pr solve the problem?

**Comment by zz-jason** [comment]
@winkyao yes

**Comment by zz-jason** [comment]
@winkyao http://internal.pingcap.net/jira/browse/TIDB-18

**Comment by zz-jason** [comment]
@winkyao @coocood PTAL

**Pull request merged**
