### PR TITLE
executor: remove Next() function for TopNExec

### PR DESCRIPTION
**Pull request by hsqlu**

### CODE REVIEW

**Comment by shenli** [comment]
@hsqlu Thanks for your contribution!

**Comment by hsqlu** [comment]
to #5985

**Comment by hsqlu** [comment]
@zz-jason How to troubleshoot and fix the failed sqllogic-test？

**Comment by zz-jason** [comment]
@hsqlu sqllogic-test failure is irrelevant to this PR, we're fixing it.

**Pull request merged**
