### PR TITLE
parser: update cznic/parser&y to new 1.0.2/1.0.1

### LINKED ISSUE #29410: `make parser_yacc` fails due to junk bytes at the end of generated files
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`make parser_yacc`

### 2. What did you expect to see? (Required)

test all passes

### 3. What did you see instead (Required)

`make parser_yacc` fails on the `diff` stage. Output too large to put here.

### 4. What is your TiDB version? (Required)

master branch, commit 731902de583687d7a7ad9a69b0038d16fd445741
go version 1.17.2
macOS monterey 12.0.1

The cause of the `diff` failure is due to there are two more invalid utf8 bytes `\xef\xbf` at the end of the generated go files. So https://github.com/pingcap/tidb/blob/731902de583687d7a7ad9a69b0038d16fd445741/parser/goyacc/main.go#L270 fails to format the generated file. The parser structure gets a `Tail`:
```
· Tail: &parser.Tail{
· · Value: "\n\xef\xbf",
· · Token: parser.y:13724:1: MARK "%%", Comments: [],
· }  
```
Don't know where the two bytes comes. The y files don't have the bytes at the end.

### PR DESCRIPTION
**Pull request by zhangyangyu**
### What problem does this PR solve?

Issue Number: close #29410 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Comment by hawkingrei** [comment]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by zhangyangyu** [comment]
Thanks @hawkingrei @xhebox @kennytm for your reviews!

**Pull request merged**
