### PR TITLE
dumpling: add `OWNERS` file

### LINKED ISSUE #47843: add `OWNERS` file for `dumpling` folder

### PR DESCRIPTION
**Pull request by wuhuizuo**
### What problem does this PR solve?

Issue Number: close #47843

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [x] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

/label needs-cherry-pick-release-7.5

### CODE REVIEW

**Comment by wuhuizuo** [comment]
/cc  @Benjamin2037 @gmhdbjd @lichunzhu  @okJiang

PTAL

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by okJiang — APPROVED** [review]

**Pull request merged**
