### PR TITLE
parser: make the prepared statement like expression support escape issue#32246

### LINKED ISSUE #32246: TiDB is not allowing Prepared statement parameter as argument to ESCAPE
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t1;
create table t1 (a varchar(10), key(a));
insert into t1 values ('a'), ('a\\b');
prepare stmt1 from 'select * from t1 where a like \'a\\%\' escape ?';
set @esc='#';
execute stmt1 using @esc;  
deallocate prepare stmt1;

```

### 2. What did you expect to see? (Required)
```sql
mysql> prepare stmt1 from 'select * from t1 where a like \'a\\%\' escape ?';
Query OK, 0 rows affected (0.00 sec)
Statement prepared
```
### 3. What did you see instead (Required)
```sql
mysql> prepare stmt1 from 'select * from t1 where a like \'a\\%\' escape ?';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 44 near "?" 
mysql> set @esc='#';
Query OK, 0 rows affected (0.00 sec)
```
### 4. What is your TiDB version? (Required)

```sql
| Release Version: v5.5.0-alpha-182-gad9430039
Edition: Community
Git Commit Hash: ad9430039f54bb9af78d44831c176bc5eafcbba0
Git Branch: master
UTC Build Time: 2022-02-04 18:58:58
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by fanrenhoo**
Signed-off-by: fanrenhoo <fanrenhoo@sina.com>

### What problem does this PR solve?

Issue Number: close #32246

Problem Summary: the prepared statement did not support escape to have a paramenter marker ?, parser will treat it as wrong syntax as normal sql

### What is changed and how it works?
I added the paramMarker for "select...PatternLike" in parser.y to support "ESCAPE paramMarker", so if in the prepared statement, now we can write "escape ?", that mean the escape character can also be parameterized in "select...PatternLike" 
prepared statement.
Add also add a test case for this

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
drop table if exists t1;
create table t1 (a varchar(10), key(a));
prepare stmt1 from 'select * from t1 where a like 'a\%' escape ?';
Query OK, 0 rows affected (0.00 sec)

also add test cases

- [ ] No code

Side effects
no
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation
no
- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Make the prepared statement support escape character be parameterized for "select patternlikeexpr"(issue 32246). previously the prepared statement "escape ?", , parser will treat it as wrong syntax as normal sql, now the escape character can also be parameterized in prepared statement for "select patternlikeexpr".
```

### CODE REVIEW

**Comment by fanrenhoo** [comment]
@xiongjiwei @xuyifangreeneyes Hi, I tranfer the PR #32246 to this new one, to merge the fix based on the newest master because the old PR fall back master too long time. Please check, THKS

**Comment by xiongjiwei** [comment]
no, please do not create it again, we left some comments on that one, also there are some communications.

you can use rebase to follow up on the newest master

**Comment by fanrenhoo** [comment]
> no, please do not create it again, we left some comments on that one, also there are some communications.
> 
> you can use rebase to follow up on the newest master

OK. I reopened the previous one and rebase to recommit. actually I tried rebase before, but weirdly found very old versions always back. So this time I rebase and revised carefully to make sure same with newest fix. THKS.

**Pull request closed without merging**
