### PR TITLE
util/timeutil: fix get tz at mojave

### PR DESCRIPTION
**Pull request by zhexuany**
### What problem does this PR solve? 
After upgrading to macOs Mojave, soft link of `/etc/localtime` had been changed from `/var/db/timezone/tz/2018e.1.0/zoneinfo/Asia/Shanghai` to `/usr/share/zoneinfo.default/Asia/Shanghai`. A test case failed and this PR addresses this.

### What is changed and how it works?
`inferTZNameFromFileName` is using `zoneinfo` to locate the IANA timezone name. This PR addresses that issue by adding one more logic, which is using `zoneinfo.default` to locate the IANA timezone name first. If nothing can be got, then fall back to using `zoneinfo`. 

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by imtbkcat** [comment]
Does it affect macOS High Sierra after this pr merge?

**Comment by zhexuany** [comment]
Nope. Since it falls back to using `zoneinfo` to extract the IANA timezone name.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
