### PR TITLE
Add length check to prevent index out of range

### PR DESCRIPTION
**Pull request by blacktear23**
This PR is #4863 fix.

### CODE REVIEW

**Comment by coocood** [comment]
@lamxTyler PTAL

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@blacktear23 Could you cherry-pick this to release-1.0?

**Comment by blacktear23** [comment]
@shenli cherry-pick it to release-1.0 ? Branch? How to do this? Do I have permission to push this branch?

**Comment by blacktear23** [comment]
@shenli release-1.0 branch's code not have factor calculation feature, seems we don't need cherry-pick this.

**Comment by shenli** [comment]
OK

**Pull request merged**
