### PR TITLE
mocktikv: change pessimistic lock return value skip op_lock in mocktikv

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve? 

Force reading value doing point get a pessimistic lock, the `op_lock` record should be skipped, or the wrong value is returned, there may be error like
```
ERROR 8021 (HY000): inconsistent extra index unq_j, handle 1 not found in table
```

### What is changed and how it works?

Add get value after `checkConflict`  operation

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

Release note

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@coocood @tiancaiamao @jackysp PTAL

**Comment by coocood** [comment]
LGTM

**Pull request merged**
