### PR TITLE
session,store: make TestAsyncRollBackNoWait run faster to boost CI

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

`TestAsyncRollBackNoWait` slows our CI.

Before:
```
PASS: pessimistic_test.go:485: testPessimisticSuite.TestAsyncRollBackNoWait	5.070s
```
After:
```
PASS: pessimistic_test.go:485: testPessimisticSuite.TestAsyncRollBackNoWait	0.220s
```
### What is changed and how it works?

Reduce `time.Sleep`

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @coocood @cfzjywxk

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
PTAL @coocood @cfzjywxk

**Comment by cfzjywxk** [comment]
LGTM

**Pull request merged**
