### PR TITLE
*: update go.mod for sysutil (#21373)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21373 to release-4.0

---

Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

As the title said.

This is for below issues:

* https://github.com/pingcap/sysutil/pull/24
* https://github.com/pingcap/sysutil/pull/25
* https://github.com/pingcap/sysutil/pull/22

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

- N/A

### Release note 

- N/A

### CODE REVIEW

**Comment by crazycs520** [comment]
@breeswish @wjhuang2016 PTAL

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by breeswish — APPROVED** [review]

**Review by SunRunAway — APPROVED** [review]

**Pull request merged**
