### PR TITLE
*: fix unstable test caused by TestRandomPanicAggConsume

### LINKED ISSUE #30029: CI unstable test `TestAdminCleanupIndexMore` oom failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_coverage/detail/tidb_ghpr_coverage/1289/pipeline
```sql
2021-11-22T14:53:08.571Z] [2021/11/22 22:52:35.859 +08:00] [INFO] [ddl_worker.go:715] ["[ddl] run DDL job"] [worker="worker 637, tp general"] [job="ID:54, Type:create table, State:none, SchemaState:queueing, SchemaID:3, TableID:53, RowCount:0, ArgLen:0, start time: 2021-11-22 22:52:35.858 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2021-11-22T14:53:08.571Z] --- FAIL: TestAdminCleanupIndexMore (1.12s)
[2021-11-22T14:53:08.571Z]     testkit.go:91: 
[2021-11-22T14:53:08.571Z]         	Error Trace:	testkit.go:91
[2021-11-22T14:53:08.571Z]         	            				admin_test.go:759
[2021-11-22T14:53:08.571Z]         	Error:      	Received unexpected error:
[2021-11-22T14:53:08.571Z]         	            	failpoint panic: ERROR 1105 (HY000): Out Of Memory Quota![conn_id=1]
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1
[2021-11-22T14:53:08.571Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_coverage/go/src/github.com/pingcap/tidb/executor/adapter.go:345
[2021-11-22T14:53:08.571Z]         	            	runtime.gopanic
[2021-11-22T14:53:08.571Z]         	            		/usr/local/go/src/runtime/panic.go:965
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/tidb/executor.closeBaseExecutor
[2021-11-22T14:53:08.571Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_coverage/go/src/github.com/pingcap/tidb/executor/aggregate.go:357
[2021-11-22T14:53:08.571Z]         	            	runtime.gopanic
[2021-11-22T14:53:08.571Z]         	            		/usr/local/go/src/runtime/panic.go:965
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/failpoint.actPanic
[2021-11-22T14:53:08.571Z]         	            		/nfs/cache/mod/github.com/pingcap/failpoint@v0.0.0-20210316064728-7acb0f0a3dfd/terms.go:343
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/failpoint.(*term).do
[2021-11-22T14:53:08.571Z]         	            		/nfs/cache/mod/github.com/pingcap/failpoint@v0.0.0-20210316064728-7acb0f0a3dfd/terms.go:310
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/failpoint.(*terms).eval
[2021-11-22T14:53:08.571Z]         	            		/nfs/cache/mod/github.com/pingcap/failpoint@v0.0.0-20210316064728-7acb0f0a3dfd/terms.go:115
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/failpoint.(*Failpoint).Eval
[2021-11-22T14:53:08.571Z]         	            		/nfs/cache/mod/github.com/pingcap/failpoint@v0.0.0-20210316064728-7acb0f0a3dfd/failpoint.go:109
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/failpoint.(*Failpoints).Eval
[2021-11-22T14:53:08.571Z]         	            		/nfs/cache/mod/github.com/pingcap/failpoint@v0.0.0-20210316064728-7acb0f0a3dfd/failpoints.go:212
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/failpoint.Eval
[2021-11-22T14:53:08.571Z]         	            		/nfs/cache/mod/github.com/pingcap/failpoint@v0.0.0-20210316064728-7acb0f0a3dfd/failpoints.go:273
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/tidb/executor.(*StreamAggExec).Open
[2021-11-22T14:53:08.571Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_coverage/go/src/github.com/pingcap/tidb/executor/aggregate.go:1265
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/tidb/executor.(*ExecStmt).Exec
[2021-11-22T14:53:08.571Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_coverage/go/src/github.com/pingcap/tidb/executor/adapter.go:387
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/tidb/session.runStmt
[2021-11-22T14:53:08.571Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_coverage/go/src/github.com/pingcap/tidb/session/session.go:1698
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/tidb/session.(*session).ExecuteStmt
[2021-11-22T14:53:08.571Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_coverage/go/src/github.com/pingcap/tidb/session/session.go:1582
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/tidb/testkit.(*TestKit).Exec
[2021-11-22T14:53:08.571Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_coverage/go/src/github.com/pingcap/tidb/testkit/testkit.go:145
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/tidb/testkit.(*TestKit).MustQuery
[2021-11-22T14:53:08.571Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_coverage/go/src/github.com/pingcap/tidb/testkit/testkit.go:90
[2021-11-22T14:53:08.571Z]         	            	github.com/pingcap/tidb/executor_test.TestAdminCleanupIndexMore
[2021-11-22T14:53:08.571Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_coverage/go/src/github.com/pingcap/tidb/executor/admin_test.go:759
[2021-11-22T14:53:08.571Z]         	            	testing.tRunner
[2021-11-22T14:53:08.571Z]         	            		/usr/local/go/src/testing/testing.go:1193
[2021-11-22T14:53:08.571Z]         	            	runtime.goexit
[2021-11-22T14:53:08.571Z]         	            		/usr/local/go/src/runtime/asm_amd64.s:1371
[2021-11-22T14:53:08.571Z]         	Test:       	TestAdminCleanupIndexMore
[2021-11-22T14:53:08.571Z]         	Messages:   	sql:SELECT COUNT(*) FROM admin_test USE INDEX(), args:[]
[2021-11-22T14:53:08.571Z] [2021/11/22 22:52:35.860 +08:00] [INFO] [ddl_worker.go:313] ["[ddl] add DDL jobs"] ["batch count"=1] [jobs="ID:48, Type:create table, State:none, SchemaState:queueing, SchemaID:3, TableID:47, RowCount:0, ArgLen:1, start time: 2021-11-22 22:52:35.858 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0; "]
```

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #30029

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]
LGTM

**Review by tisonkun — APPROVED** [review]

**Comment by hawkingrei** [comment]
PTAL

/cc @3pointer @kennytm

**Comment by tiancaiamao** [comment]
I met it and simply change [here](https://github.com/pingcap/tidb/pull/29152/files#diff-84f95c069914cbb74760467d14969da31016d05a1cfcc5272cea7e75552f97b9L1477) to workaround

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
