### PR TITLE
tikv: fix wrong backoff metric label

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Problem Summary: ref https://github.com/pingcap/tidb/issues/30779

there some backoff metric labels are displayed as "type", it's confusing to user.

### What is changed and how it works?

What's Changed, How it Works:

fix label value for two miss types

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by lysu** [comment]
it only affects release-5.0 and release-4.0, it is better to cherry-pick them to help user watch monitor

**Review by jackysp — COMMENTED** [review]
LGTM

**Review by zimulala — APPROVED** [review]
LGTM

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
