### PR TITLE
tikv/gc_worker: cherry-pick "export gc concurrency (#6325)" to release-2.0

### PR DESCRIPTION
**Pull request by MyonKeminta**
## What have you changed? (mandatory)

cherry-pick "export gc concurrency (#6325)" (commit 2e18696) to branch release-2.0

This supports invoking concurrent GC on TiKV with ticlient.

## What are the type of the changes (mandatory)?

- New feature (non-breaking change which adds functionality)

## How has this PR been tested (mandatory)?

None

## Does this PR affect documentation (docs/docs-cn) update? (optional)

None

## Refer to a related PR or issue link (optional)

#6325

### CODE REVIEW

**Comment by shenli** [comment]
@MyonKeminta Please run the CI.

**Comment by zz-jason** [comment]
@MyonKeminta can we merge this PR now?

**Comment by MyonKeminta** [comment]
@zz-jason yes

**Pull request merged**
