### PR TITLE
session: return an error when a non-transactional DML partially fails

### PR DESCRIPTION
**Pull request by ekexium**
Signed-off-by: ekexium <ekexium@gmail.com>

### What problem does this PR solve?

Issue Number: ref #33485

Problem Summary:

### What is changed and how it works?

Previously we return a recordset containing errors when some jobs failed. That would misguide applications.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Add a system variable `tidb_nontransactional_ignore_error`
```

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]
LGTM. But it's better to add a simple test.

**Comment by ekexium** [comment]
Hold this PR for now... We may not handle errors in this way.

**Comment by ekexium** [comment]
Reviews are welcomed now.

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
