### PR TITLE
planner: let apply be paralleled though there's order property can be used

### LINKED ISSUE #34237: Parallel Apply cannot be chosen when there's order property on its outer child
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t (a int, b int, index idx(a));
set @@tidb_enable_parallel_apply = 'on';
select t1.b from t t1 where t1.b > (select max(b) from t t2 where t1.a > t2.a) order by t1.a;
```

### 2. What did you expect to see? (Required)

Executed successfully and apply operator is paralleled.

### 3. What did you see instead (Required)

```
show warnings;
```

```
+---------+------+------------------------------------------------------+
| Level   | Code | Message                                              |
+---------+------+------------------------------------------------------+
| Warning | 1105 | Some apply operators can not be executed in parallel |
+---------+------+------------------------------------------------------+
1 row in set (0.02 sec)
```

### 4. What is your TiDB version? (Required)

current master

### PR DESCRIPTION
**Pull request by winoros**
… used

### What problem does this PR solve?

Issue Number: close #34237 

Problem Summary:

We need to make the apply operator can be paralleled as much as possible.

### What is changed and how it works?

Reject the order property for now. We will improve it later.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by winoros** [comment]
Only pick it to the 5.4 and 6.0 first.

**Review by Reminiscent — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
