### PR TITLE
parser: add traffic capture/replay statements in the parser

### LINKED ISSUE #57807: Support traffic statements in parser
Support SQL to capture and replay traffic using TiProxy. This is a parser issue.

```sql
TRAFFIC CAPTURE TO "/tmp/traffic" DURATION="1h" ENCRYPTION_METHOD="aes256-ctr" COMPRESS=false
TRAFFIC REPLAY FROM "/tmp/traffic" USER="u1" PASSWORD="123456" SPEED=1.0
CANCEL TRAFFIC JOBS
SHOW TRAFFIC JOBS
```

Refer to similar statements:

```sql
PLAN REPLAYER DUMP EXPLAIN select * from t;
PLAN REPLAYER LOAD 'file_name';
PLAN REPLAYER CAPTURE 'sql_digest' '*';
SELECT * FROM mysql.plan_replayer_task;    # query plan replayer tasks

BACKUP DATABASE `test` TO 's3://backup/' COMPRESSION_LEVEL=3 ENCRYPTION_METHOD='aes256';
SHOW BACKUPS;
RESTORE DATABASE * FROM 's3://backup/'  CONCURRENCY = 64 CHECKSUM = FALSE;
SHOW RESTORES;
KILL 5857102839209263511;   # kill backup/restore job
SHOW BR JOB 1;
CANCEL BR JOB 1;

IMPORT INTO t FROM '/path/to/file.csv' WITH SKIP_ROWS=1 THREAD=10;
SHOW IMPORT JOBS;
CANCEL IMPORT JOB 1;

ADMIN CANCEL DDLS;
ADMIN SHOW DDL JOBS;

SET @@global.tidb_ttl_job_enable = OFF;     # cancel all ttl jobs
SELECT * FROM mysql.tidb_ttl_table_status;    # query ttl jobs
```

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

Issue Number: close #57807

Problem Summary:
Support SQL to capture and replay traffic using TiProxy. This is a parser PR.

```sql
TRAFFIC CAPTURE TO "/tmp/traffic" DURATION="1h" ENCRYPTION_METHOD="aes256-ctr" COMPRESS=false
TRAFFIC REPLAY FROM "/tmp/traffic" USER="u1" PASSWORD="123456" SPEED=1.0 READ_ONLY=true
CANCEL TRAFFIC JOBS
SHOW TRAFFIC JOBS
```

Refer to similar statements:

```sql
PLAN REPLAYER DUMP EXPLAIN select * from t;
PLAN REPLAYER LOAD 'file_name';
PLAN REPLAYER CAPTURE 'sql_digest' '*';
SELECT * FROM mysql.plan_replayer_task;    # query plan replayer tasks

BACKUP DATABASE `test` TO 's3://backup/' COMPRESSION_LEVEL=3 ENCRYPTION_METHOD='aes256';
SHOW BACKUPS;
RESTORE DATABASE * FROM 's3://backup/'  CONCURRENCY = 64 CHECKSUM = FALSE;
SHOW RESTORES;
KILL 5857102839209263511;   # kill backup/restore job
SHOW BR JOB 1;
CANCEL BR JOB 1;

IMPORT INTO t FROM '/path/to/file.csv' WITH SKIP_ROWS=1 THREAD=10;
SHOW IMPORT JOBS;
CANCEL IMPORT JOB 1;

ADMIN CANCEL DDLS;
ADMIN SHOW DDL JOBS;

SET @@global.tidb_ttl_job_enable = OFF;     # cancel all ttl jobs
SELECT * FROM mysql.tidb_ttl_table_status;    # query ttl jobs
```

### What changed and how does it work?
- Add the grammar above in the parser. All the tokens are notKeywordToken.
- Add `COMPRESS()` to `FunctionCallNonKeyword` because the name conflicts.
- Define `TrafficStmt`. `CANCEL TRAFFIC JOBS` and `SHOW TRAFFIC JOBS` are also `TrafficStmt`, the same as `BRIEStmt`, to keep all traffic-related codes together.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [x] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by djshow832** [comment]
@benmeadowcroft, @bb7133 PTAL

**Review by xhebox — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by yudongusa — APPROVED** [review]

**Pull request merged**
