### PR TITLE
go.mod: change github.com/uber-go/atomic to go.uber.org/atomic

### PR DESCRIPTION
**Pull request by liubog2008**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

Del github.com/uber-go/atomic, See https://github.com/uber-go/atomic#legacy-import-path

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by liubog2008** [comment]
@leiysky @ichn-hu

**Comment by dveeden** [comment]
There is more reference to the old name left:
```
$ git grep 'uber-go/atomic'
tests/globalkilltest/go.sum:github.com/uber-go/atomic v1.3.2/go.mod h1:/Ct5t2lcmbJ4OSe/waGBoaVvVqtO0bmtfVNex1PFV8g=
```

**Comment by liubog2008** [comment]
Does I need to update `tests/globalkilltest/go.mod` in this PR? @dveeden

**Comment by liubog2008** [comment]
It seems that `tests/globalkilltest` should not be an individual go module?

**Review by dveeden — APPROVED** [review]

**Review by leiysky — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
cc @bb7133 @morgo could you do the final check and decide whether we merge this PR?

**Review by morgo — APPROVED** [review]

**Pull request merged**
