### PR TITLE
planner: Support cluster_log message column DNF predicates push-down

### LINKED ISSUE #15069: UCP: Support cluster_log message column DNF predicates push-down
## Description

The table `cluster_log` doesn't support push-down column `message` DNF predicates to the lowest level `clusterLogRetriever`. So `select * from cluster_log where message like '%123%' or message like '%xxx%'` cannot push the filter to the remote node. This scenario will impact performance.

We can refactor the `ClusterLogTableExtractor` and extract the DNF predicates, those predicates can be a filter like the regular expression `123|xxx`

## Score

* 180

## Mentor(s)

* @lonng

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go
* Planner

## Learning Materials

Reference: https://github.com/pingcap/tidb/blob/998e5b79f96b5842c514908a11b58336a97c050f/planner/core/memtable_predicate_extractor.go

### PR DESCRIPTION
**Pull request by SeaRise**
UCP #15069 

### What problem does this PR solve? 
fix #15069 

### Check List

Tests
 - Unit test

Code changes

 - Has exported function/method change

### CODE REVIEW

**Comment by SeaRise** [comment]
In issue is 180 points, why sre-bot reply 80 points?

**Comment by SeaRise** [comment]
@lonng PTAL

**Comment by lonng** [comment]
@SeaRise Thank you for your interest in this issue, it's better to add some tests in cluster_log_test.go. 
Can you support DNF for log level?

The point of this issue is 180.

**Comment by SeaRise** [comment]
@lonng 
log level had support DNF.I add a test for DNF of log level.
where is the `cluster_log_test.go`? I can not find it any where.

**Comment by lonng** [comment]
@SeaRise Sorry the file has been change name to `executor/memtable_reader_test.go`.  You can reference the `TestTiDBClusterLog` to add some more tests.

**Comment by SeaRise** [comment]
@lonng 
I had add a test In `executor/memtable_reader_test.go`.
Should I add more tests?

**Comment by lonng** [comment]
@crazycs520 PTAL

**Comment by SeaRise** [comment]
Thank you for your review.

**Pull request merged**
