### PR TITLE
planner: support plan cache for cluster index (#18716)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #18716 to release-4.0

---

### What problem does this PR solve?

Problem Summary: as title says.

### What is changed and how it works?

How it Works: make rebuild ranges support cluster index

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- none

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
@lzmhhh123 do we need this PR in release 4.0?

**Comment by lzmhhh123** [comment]
> @lzmhhh123 do we need this PR in release 4.0?

This PR fix some bugs about plan cache with point get. It’s different with the master branch PR.

**Comment by coocood** [comment]
LGTM

**Review by zz-jason — APPROVED** [review]
LGTM

**Pull request merged**
