### PR TITLE
planner: fix the unstable test `TestFixControl45132`

### LINKED ISSUE #46663: Unstable test TestFixControl45132
## Bug Report
CI: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/32027/pipeline/

```
[2023/09/05 12:13:40.125 +08:00] [INFO] [analyze.go:627] ["analyze table `test`.`t` has finished"] [partition=] ["job info"="analyze table all columns with 256 buckets, 500 topn, 1 samplerate"] ["start time"=2023/09/05 12:13:39.960 +08:00] ["end time"=2023/09/05 12:13:40.123 +08:00] [cost=163.387722ms] ["sample rate reason"="use min(1, 110000/10000) as the sample-rate=1"]
    result.go:49: 
        	Error Trace:	testkit/result.go:49
        	            				planner/core/casetest/integration_test.go:1597
        	Error:      	Not equal: 
        	            	expected: "[TableReader_7 128.00 root  data:Selection_6]\n[└─Selection_6 128.00 cop[tikv]  eq(test.t.a, 2)]\n[  └─TableFullScan_5 12928.00 cop[tikv] table:t keep order:false]\n"

        	            	actual  : "[TableReader_7 119.00 root  data:Selection_6]\n[└─Selection_6 119.00 cop[tikv]  eq(test.t.a, 2)]\n[  └─TableFullScan_5 12065.00 cop[tikv] table:t keep order:false]\n"
        	            	

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual

        	            	@@ -1,4 +1,4 @@
        	            	-[TableReader_7 128.00 root  data:Selection_6]
        	            	-[└─Selection_6 128.00 cop[tikv]  eq(test.t.a, 2)]
        	            	-[  └─TableFullScan_5 12928.00 cop[tikv] table:t keep order:false]
        	            	+[TableReader_7 119.00 root  data:Selection_6]
        	            	+[└─Selection_6 119.00 cop[tikv]  eq(test.t.a, 2)]
        	            	+[  └─TableFullScan_5 12065.00 cop[tikv] table:t keep order:false]
        	            

        	Test:       	TestFixControl45132
        	Messages:   	sql:explain select * from t where a=2, args:[]
```

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #46663

Problem Summary: planner: fix the unstable test `TestFixControl45132`

### What is changed and how it works?

planner: fix the unstable test `TestFixControl45132`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Comment by purelind** [comment]
Wait for this PR  https://github.com/pingcap/tidb/pull/46712  to be merged first.

**Comment by wuhuizuo** [comment]
still has flaky runs.

latest: https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33129/

/reopen

**Pull request merged**
