### PR TITLE
Makefile, telemetry: fix typo

### LINKED ISSUE #32844: fix type
## Enhancement
fix typo

### PR DESCRIPTION
**Pull request by vector233**
Signed-off-by: huangxr <huangxr.me@gmail.com>

### What problem does this PR solve?

Issue Number: close #32844

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by vector233** [comment]
/cc @3AceShowHand 
Jenkins job failed. how to solve it?

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
