### PR TITLE
executor, types: update tests for the description format of type year

### PR DESCRIPTION
**Pull request by spongedu**
### What problem does this PR solve? 
https://github.com/pingcap/parser/pull/200 fixes issue #9188 , this pr fixes related tests in `TiDB`

### What is changed and how it works?
Fix related tests
Note that the modification in `go.mod` should be reverted after https://github.com/pingcap/parser/pull/200 is merged.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Please update branch, rest looks good to me

**Comment by tiancaiamao** [comment]
Please resolve conflict @spongedu

**Comment by spongedu** [comment]
@crazycs520 @zimulala @tiancaiamao  It seems that this PR and https://github.com/pingcap/parser/pull/200 depends on each other. There seems be a deadlock.....

**Comment by spongedu** [comment]
@zz-jason All the failed cases are on go mod replacement.

**Comment by tiancaiamao** [comment]
Parser is merged, please update go.mod @spongedu

**Pull request merged**
