### PR TITLE
server: optimize com_field_list, make use database faster.

### PR DESCRIPTION
**Pull request by winkyao**
Some mysql client will send "COM_FIELD_LIST" command to fetch all tables columns info when we run `mysql -h 127.0.0.1 -P 4000 -u root -Dsbtest1` , but In TiDB, we handle "COM_FIELD_LIST" with below code:

```
// FieldList implements QueryCtx FieldList method.
func (tc *TiDBContext) FieldList(table string) (columns []*ColumnInfo, err error) {
	rs, err := tc.Execute(goctx.Background(), "SELECT * FROM `"+table+"` LIMIT 0")
	if len(rs) > 0 {
		defer terror.Call(rs[0].Close)
	}
	if err != nil {
		return nil, errors.Trace(err)
	}
	columns = rs[0].Columns()
	return columns, nil
}
```
Even though we use limit 0, but we also send this sql to tikv, so there is some network round trip here.

In my local machine, I use test with a database with 1000 tables, I got below results:

```
mysql> SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'sbtest1';
+----------+
| COUNT(*) |
+----------+
|     1000 |
+----------+
1 row in set (0.01 sec)
```

I run `mysql -h 127.0.0.1 -P 4000 -u root -Dsbtest1` use master branch and got:

```
mysql> [wink@localhost tidb]$ time ./expect.sh
spawn mysql -h 127.0.0.1 -P 4000 -u root -Dsbtest1
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.1-TiDB-v1.1.0-alpha-444-g90d653c-dirty MySQL Community Server (Apache License 2.0)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
real    0m0.914s
user    0m0.003s
sys     0m0.003s
```

about 0.914s, and use this pr:

```
[wink@localhost tidb]$ time ./expect.sh
spawn mysql -h 127.0.0.1 -P 4000 -u root -Dsbtest1
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 5
Server version: 5.7.1-TiDB-v1.1.0-alpha-445-g22b227a-dirty MySQL Community Server (Apache License 2.0)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
real    0m0.143s
user    0m0.000s
sys     0m0.006s
```
0.143s,  about 84.3% improvement, the tidb and tikv is deployed in the same machine, if we deploy a real cluster, perhaps we will have more obvious improvement. But I think this already illustrates the problem.

### CODE REVIEW

**Comment by winkyao** [comment]
@shenli @coocood PTAL

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
