### PR TITLE
planner: Fix panic for SET CONFIG...=DEFAULT

### LINKED ISSUE #35745: SET CONFIG ... =DEFAULT results in panic
### 1. Minimal reproduce step (Required)

```
sql> SET CONFIG TIKV `raftstore.max-peer-down-duration`='11m';
Query OK, 0 rows affected (0.0144 sec)

sql> SET CONFIG TIKV `raftstore.max-peer-down-duration`=DEFAULT;
ERROR: 1105 (HY000): runtime error: invalid memory address or nil pointer dereference

sql> SELECT TIDB_VERSION()\G
ERROR: 2013 (HY000): Lost connection to MySQL server during query
The global session got disconnected..
Attempting to reconnect to 'mysql://root@localhost:4000/test'..
The global session was successfully reconnected.
```

### 2. What did you expect to see? (Required)

Setting the config to the default value or an error that this is not possible (and the reason why)

### 3. What did you see instead (Required)

panic

### 4. What is your TiDB version? (Required)

```
sql> SELECT TIDB_VERSION()\G
*************************** 1. row ***************************
TIDB_VERSION(): Release Version: v6.2.0-alpha
Edition: Community
Git Commit Hash: 383d1c8e70221470acf4ba55b40377b7a8e34c7c
Git Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time: 2022-06-25 14:31:34
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
Store: tikv
1 row in set (0.0006 sec)
```

```
tiup playground --tiflash 0 --without-monitor nightly
...
Start pd instance:v6.2.0-alpha-nightly-20220626
Start tikv instance:v6.2.0-alpha-nightly-20220626
Start tidb instance:v6.2.0-alpha-nightly-20220626
...
```

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #35745 

Problem Summary: 

Something like ``SET CONFIG TIKV `raftstore.max-peer-down-duration`=DEFAULT;`` would cause TiDB to panic

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by dveeden** [comment]
I think it would be good to keep this syntax and then later on implement the functionality to something similar to `SET GLOBAL ... = DEFAULT`

**Review by xhebox — COMMENTED** [review]
Can we add a test case using `recover`?

**Review by mjonss — APPROVED** [review]
LGTM

**Comment by mjonss** [comment]
@dveeden please add a test as well :)

**Comment by dveeden** [comment]
PTAL @bb7133 @xhebox

**Review by xhebox — APPROVED** [review]

**Pull request merged**
