### PR TITLE
*: changing the master/slave language

### PR DESCRIPTION
**Pull request by bopopescu**
For diversity reasons, it would be nice to try to avoid 'master' and 'slave' terminology in this repository which can be associated to slavery. The master-slave terminology could be problematic for people in several countries which has the history of slavery like Romania, USA and many others. Thank you for considering the proposal. Let me know if any changes in the PR are needed, I would be happy to implement them.

### CODE REVIEW

**Comment by nullnotnil** [comment]
Thank you for the PR! I agree that this language needs to be changed, but what might need to be determined is what the replacement terms are.

The MySQL team [has communicated](https://mysqlhighavailability.com/mysql-terminology-updates/) that they will be switching to source/replica.

TiDB aims for compatibility on error messages (as well as error codes), so we may have to wait on some of the errors for the MySQL team to make the first move. The documentation can be updated now however.

**Comment by SunRunAway** [comment]
Hi, I've filed another PR to clean the existing improper terminology as much as possible. The others have some compatibe issues and we may wait for https://mysqlhighavailability.com/mysql-terminology-updates/.

**Comment by Xevion** [comment]
I'd just like to note that the account that made this request is a bot account - they will not respond to comments, and I would seriously consider rejecting this PR, regardless of your views on the matter,
Personally, I think Master/Slave are often far more superior terms, and I don't think _normal_ people find them divisive or offensive either. I also believe that the implementations they reference are far better than the alternatives commonly presented. Please, don't entertain this silly bot account.

**Comment by nullnotnil** [comment]
Sorry, I am locking this thread. TiDB is an inclusive project, and we are committed to removing the master/slave terminology wherever we can. In this case, however, we will need to [wait for MySQL](https://mysqlhighavailability.com/mysql-terminology-updates/) before making followup changes.

**Comment by zz-jason** [comment]
I'm going to close this PR since it hasn't been updated for a long time. feel free to reopen if you want to continue with it. thank you for your contribution.

**Pull request closed without merging**
