### PR TITLE
session: add resource group name in stmt context

### LINKED ISSUE #49318: Improve the observability of resource control
### System table  
- [x] show RU consumption in statement level in the `statement_summary`, `statements_summary_history` table @glorv 
        https://github.com/tidbcloud/tidb-cse/pull/678
- [x] (option) show RU in `mysql.request_unit_by_group` https://github.com/pingcap/tidb/pull/49873 @glorv
- [ ] (option) show RU in the new table `information_schema.resource_group_stats` ??

### Log: 
- [x] Slow Log https://github.com/pingcap/tidb/issues/42892 @glorv 
- [x] Trace Log https://github.com/tikv/pd/issues/7509 @nolouch 

### Metrics @bufferflies 
To check the service quality:   https://github.com/pingcap/tidb/pull/50086

- [x] QPS & TPS by resource groups
- [x] P99/P95 by resource groups
- [x] DML latency by resource groups
- [x] command by resource groups
- [x] Failed command by resource groups
- [x] Connection Count by resource groups 

### Dashboard @nolouch 
- [x] add ru supports in the dashboard `statement` page  https://github.com/pingcap/tidb-dashboard/pull/1639
- [x] https://github.com/pingcap/tidb-dashboard/pull/1642
- [x] https://github.com/pingcap/tidb-dashboard/pull/1646
- [x] https://github.com/pingcap/tidb-dashboard/pull/1647

### TiFlash
- [ ] https://github.com/pingcap/tidb/issues/48168

### Runtime 
- [x] Introduce a session `variable ru_by_last_statement` https://github.com/pingcap/tidb/pull/49769 @nolouch 

### Docs

- [x] https://github.com/pingcap/docs-cn/pull/15935

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #49318

Problem Summary:

### What changed and how does it work?

In the current implementation, in order to support statement level hint [/* +RESOURCE_GROUP(name) */](https://docs.pingcap.com/tidb/dev/optimizer-hints#resource_groupresource_group_name) to execute a statement under specific resource group, we change the ResourceGroupName in session ctx during optimization and change back after the statement. This is currently done in the function `session.ExecuteStmt`(with a defer block). This life time may not be long enough as we have other operations such as query slow-log, query duration metrics, statement summary that depend on statement resource group but is run after `session.ExecuteStmt` is finished.

So this PR add a new field `ResourceGroupName` in StmtCtx and the /* Resource_Group() */ hint will change this filed isstead of directly change session context and this value can last until the next statement. The PR changes all statement related operation to use this field.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by nolouch** [comment]
@windtalker could you please take a look?

**Review by XuHuaiyu — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Pull request merged**
