### PR TITLE
[logutil]: Fix `MaxDays` and `MaxBackups` not working for slow-query-logger (#27625)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #27625 to release-5.2
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/29921
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/29921:release-5.2-46de14d7a183
```

---

### What problem does this PR solve?

Fix `MaxDays` and `MaxBackups` not working for slow-query-logger

Issue Number: https://github.com/pingcap/tidb/issues/25716

Problem Summary:

`MaxDays` and `MaxBackups` not working for slow-query-logger. This may causes unexpected disk usage.

### What is changed and how it works?

Tests 

_**It seems that code related to log-file-lifecycle-control is not covered by any test case yet ?**_

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
Fix `MaxDays` and `MaxBackups` not working for slow log.
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Comment by VelocityLight** [comment]
This pull request is closed because it's related version has closed automatic cherry-picking.
If it's still needed, you can reopen it or just regenerate it using bot,
see:
- https://prow.tidb.io/command-help#cherrypick
- https://book.prow.tidb.net/#/plugins/cherrypicker

You can find more details at:
- https://internals.tidb.io/t/topic/785

**Pull request closed without merging**
