### PR TITLE
executor: specially handle empty input for apply's outer child aggregate (#20544)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20544 and https://github.com/pingcap/tidb/pull/21902 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/13749

Problem Summary:

Wrong query result for Apply operator when its outer child is an aggregate, and the input for the aggregate is empty.

### What is changed and how it works?

What's Changed:

If the input for any aggregate in the outer executor tree is empty, we believe this outer row has no match in the apply, since inner child of apply can only reference columns from base outer tables(i.e, aggregate result cannot be referenced in the subquery). Exceptions are cases where outer child contains Join / Union executors, we specially handle them.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- Fix incorrect result for some queries containing dependent subquery and aggregate functions.

### CODE REVIEW

**Comment by lzmhhh123** [comment]
@eurekaka Please fix the test.

**Comment by qw4990** [comment]
PTAL @eurekaka  Please resolve conflicts.

**Comment by eurekaka** [comment]
should be merged with https://github.com/pingcap/tidb-test/pull/1138

**Review by winoros — COMMENTED** [review]
lgtm

**Review by qw4990 — APPROVED** [review]
LGTM

**Pull request merged**
