### PR TITLE
planner/core: add a range check against the display width of BIT columns

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve? 

#11923 

This is a supplement for pingcap/parser#530

### What is changed and how it works?

Add a range check against the display width of BIT columns. For example, 
```sql
create table t (a bit(65));

(1439, "Display width out of range for column 'a' (max = 64)")
```

The test is not ready because the parser will complain. After pingcap/parser#530 merged, I will add some tests for it.

### Check List 

Tests 

 - Manual test

Release note

- fix the range check against the display width of BIT columns.

### CODE REVIEW

**Comment by wjhuang2016** [comment]
LGTM

**Comment by cyliu0** [comment]
@tangenta Do we need to cherry pick this one to release branches like release-3.1, release-3.0, release-2.1?

**Comment by tangenta** [comment]
@cyliu0 I will do the work later.

**Pull request merged**
