### PR TITLE
*: move new api out of session package (#22591)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #22591 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/22656
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/22656:release-4.0-4e471d7cb1b9
```

---

### What problem does this PR solve?

Problem Summary: EscapeSQL may be used in other packages. But the session package involves many cyclic importing problems. Also, parentheses around string slice are removed to allow more dynamic usage.

**UPDATE**: see the comment https://github.com/pingcap/tidb/pull/22591#issuecomment-769559690.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Comment by morgo** [comment]
Looks like there is an error:
```
[2021-03-02T02:45:35.486Z] # github.com/pingcap/tidb/session
[2021-03-02T02:45:35.486Z] session/session.go:1154:8: invalid argument stmtNodes (type ast.StmtNode) for len
[2021-03-02T02:45:35.486Z] session/session.go:1158:41: invalid operation: stmtNodes[0] (type ast.StmtNode does not support indexing)
```

**Comment by xhebox** [comment]
> Looks like there is an error:

Should have been fixed. I modified the API to return one single node before the refactor of `ExecRestrictedSQL`.

**Pull request merged**
