### PR TITLE
*: fix oom action cancel bug

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
set config.OOMAction = "cancel"
before this PR:
```sql
create table t1(a int primary key, b double);
insert into t1 values(3,2);

test> select sum(a) from t1 group by b;
+--------+
| sum(a) |
+--------+
| 3      |
+--------+
1 row in set
test> set @@tidb_mem_quota_query=1;
Query OK, 0 rows affected
test> select sum(a) from t1 group by b;
+--------+
| sum(a) |
+--------+
0 rows in set
```

After This PR:

```sql 
test> select sum(a) from t1 group by b;
+--------+
| sum(a) |
+--------+
| 3      |
+--------+
1 row in set
Time: 0.006s
test> set @@tidb_mem_quota_query=1;
Query OK, 0 rows affected
Time: 0.001s
test> select sum(a) from t1 group by b;
(1105, u'Out Of Memory Quota![conn_id=1]')
```

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by crazycs520** [comment]
@zz-jason @tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Comment by zz-jason** [comment]
needs to be cherry-picked to release-2.1 and release-3.0

**Pull request merged**
