### PR TITLE
add db2 fetch first grammer support

### PR DESCRIPTION
**Pull request by AndrewDi**
### What problem does this PR solve? 
Add db2 grammer ‘fetch first n rows only' support ref [fetch-first-clause](https://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0059212.html)

### What is changed and how it works?
Add 'fetch first n rows only' decode as 'limit n'

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by gregwebs** [comment]
@AndrewDi thanks for sharing your work! I am curious what the use case for this is. It seems that DB2 does now [support LIMIT](https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/IBM%20i%20Technology%20Updates/page/OFFSET%20and%20LIMIT).

I am also curious what the utility is of adding this by itself? I assume a lot more changes would be needed for DB2 support and we would want to understand the full specification of what those are.

**Comment by AndrewDi** [comment]
@gregwebs **LIMIT clause only support on DB2 for I** , I think we should considered **DB2 for LUW** platform compatibility, IMO **fetch first clause** would be the most common grammar in DB2 programming, such as data paging\fetch data in limited size, because DB2 for LUW didn't support limit clause, so **fetch first clause** would be the only way to do such things.

**Comment by coocood** [comment]
@AndrewDi 
I think a better solution is to parse and rewrite DB2 SQL to MySQL compatible SQL in an external module, for example, a proxy.

Mix two system syntax in a single parser makes it unmaintainable.

**Comment by gregwebs** [comment]
I think that should be possible with Apache Calcite.

**Comment by gregwebs** [comment]
@AndrewDi thanks for pointing out the different platforms. We would need to understand the use case this PR satisfies assuming there is a lot more work that needs to be done for DB2 support. If you are developing all those changes, perhaps you can maintain a db2 branch in your repo.

**Comment by AndrewDi** [comment]
> @AndrewDi thanks for pointing out the different platforms. We would need to understand the use case this PR satisfies assuming there is a lot more work that needs to be done for DB2 support. If you are developing all those changes, perhaps you can maintain a db2 branch in your repo.

Thanks to your advise, I would to discuss with the other members, and close this PR for now.

**Pull request closed without merging**
