### PR TITLE
expression: fix issue that `period_diff` is not compatible with MySQL 8.0

### LINKED ISSUE #10382: Function `period_diff ` is not compatible with MySQL 8.0
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Function `period_diff` is not compatible with MySQL 8.0

2. What did you expect to see?
MySQL 8.0:
```
mysql> SELECT PERIOD_diff(-00013,1);
ERROR 1210 (HY000): Incorrect arguments to period_diff
```


3. What did you see instead?
TiDB
```
mysql>  SELECT PERIOD_diff(-00013,1);
+-----------------------+
| PERIOD_diff(-00013,1) |
+-----------------------+
|   2213609288845122194 |
+-----------------------+
1 row in set (0.00 sec)
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
mysql> select tidb_version();
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                                             |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.0-beta.1-218-g2f7241138-dirty
Git Commit Hash: 2f7241138adfc434f4b199ecae68fb83ad33b36b
Git Branch: myfeature-perioddiff
UTC Build Time: 2019-05-07 03:36:21
GoVersion: go version go1.11.4 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by mantuliu**
### What problem does this PR solve? 
fix  #10382 

### What is changed and how it works?
add validPeriod. the method come from #10380 .
@qw4990 I used your 'validPeriod' method ,but change a little.

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by qw4990** [comment]
Thanks for your contribution.
But it seems this PR has conflict with #10380, so please wait #10380 to be merged.

**Comment by qw4990** [comment]
@mantuliu #10380 has been merged into `master`, so please `git rebase` your PR and fix conflicts, PTAL~

**Comment by qw4990** [comment]
PTAL~ @mantuliu

**Comment by mantuliu** [comment]
@qw4990 take a look.thanks.
PTAL~

**Comment by qw4990** [comment]
@mantuliu It seems there are some CI problems not caused by your PR.
Please `git rebase` this PR to the newest master branch and `/run-all-tests` again to try to fix them.

**Comment by qw4990** [comment]
@mantuliu Thanks for your contribution.
Could you please cherry-pick this PR to branch `release-2.1`?

**Comment by mantuliu** [comment]
@qw4990 ok，I will cherry-pick this PR to branch release-2.1.

**Comment by mantuliu** [comment]
@qw4990 Please cherry-pick #10380 firstly,thanks.

**Comment by qw4990** [comment]
> @qw4990 Please cherry-pick #10380 firstly,thanks.

It's in progress #10430 and waited to merge.

**Pull request merged**
