### PR TITLE
*: update pingcap/log to fix audit plugin build in 2.1

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

current release 2.1 branch load audit plugin will fail with

```
2019/12/25 14:14:44.149 terror.go:329: [fatal] plugin.Open("/home/robi/Code/go/src/github.com/pingcap/enterprise-plugin/audit/audit-1"): plugin was built with a different version of package github.com/pingcap/log
github.com/pingcap/errors.AddStack
	/home/robi/Code/go/pkg/mod/github.com/pingcap/errors@v0.11.4/errors.go:174
github.com/pingcap/errors.Trace
	/home/robi/Code/go/pkg/mod/github.com/pingcap/errors@v0.11.4/juju_adaptor.go:15
github.com/pingcap/tidb/plugin.loadManifestByGoPlugin
	/home/robi/Code/go/src/github.com/pingcap/tidb/plugin/plugin.go:342
github.com/pingcap/tidb/plugin.loadOne
	/home/robi/Code/go/src/github.com/pingcap/tidb/plugin/plugin.go:319
github.com/pingcap/tidb/plugin.Load
	/home/robi/Code/go/src/github.com/pingcap/tidb/plugin/plugin.go:179
github.com/pingcap/tidb/session.BootstrapSession
	/home/robi/Code/go/src/github.com/pingcap/tidb/session/session.go:1235
main.createStoreAndDomain
	/home/robi/Code/go/src/github.com/pingcap/tidb/tidb-server/main.go:196
main.main
	/home/robi/Code/go/src/github.com/pingcap/tidb/tidb-server/main.go:162
runtime.main
	/home/robi/runtime/go13/src/runtime/proc.go:203
runtime.goexit
	/home/robi/runtime/go13/src/runtime/asm_amd64.s:1357
```

### What is changed and how it works?

audit plugin and release-3.0 have upgrade pingcap/log dependency, to make plugin can work with 2.1, we need upgrade log in 2.1 too

also cherry-pick conn_ip_example fix #10288 to 2.1

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

```
build and load plugin
```

Code changes

 - n/a

Side effects

 - n/a

Related changes

 - in 2.1

Release note

 - update pingcap/log to fix audit plugin build in 2.1

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/14218)

### CODE REVIEW

**Comment by lysu** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
/run-unit-test
May the force be with you!

**Comment by bb7133** [comment]
Hi @lysu why this is closed?

**Pull request closed without merging**
