### PR TITLE
ddl: fix none info of `alter table placement`

### LINKED ISSUE #29915: alter table placement policy ddl job_type is none
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
set global tidb_enable_alter_placement=1;
create table t001(a int);
create placement policy x followers=4;
alter table t001 placement policy x;
admin show ddl jobs;
```
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
job_type display usage message
### 3. What did you see instead (Required)
job_type message is none
```sql
mysql> create placement policy x followers=4;
Query OK, 0 rows affected (0.10 sec)

mysql> alter table t001 placement policy x;
Query OK, 0 rows affected (0.10 sec)

mysql> admin show ddl jobs;
+--------+----------+------------+-------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+--------+
| JOB_ID | DB_NAME  | TABLE_NAME | JOB_TYPE                | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | START_TIME          | END_TIME            | STATE  |
+--------+----------+------------+-------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+--------+
|     86 | test     | t001       | none                    | public       |         1 |       82 |         0 | 2021-11-18 17:20:08 | 2021-11-18 17:20:08 | synced |
|     85 | x        |            | create placement policy | public       |        12 |        0 |         0 | 2021-11-18 17:20:03 | 2021-11-18 17:20:03 | synced |
|     83 | test     | t001       | create table            | public       |         1 |       82 |         0 | 2021-11-18 17:19:44 | 2021-11-18 17:19:44 | synced |
+--------+----------+------------+-------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+--------+
10 rows in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)
```sql
mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.3.0
Edition: Community
Git Commit Hash: c83f032b04a40b3148dff712392dd924ae064132
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-16 11:55:42
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

```
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: close #29915

Problem Summary:
the lack of string()

### What is changed and how it works?
fix alter talbe placement and other missing alter string info.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by mjonss — COMMENTED** [review]
Would it be possible to add a test to cover these? Maybe something similar to `TestAdminShowDDLJobs` ?

**Comment by sylzd** [comment]
> Would it be possible to add a test to cover these? Maybe something similar to `TestAdminShowDDLJobs` ?

okay~ Added! I thought unit test `TestString` is enough.🤣

**Review by lcwangchao — APPROVED** [review]

**Review by mjonss — APPROVED** [review]
LGTM

**Pull request merged**
