### PR TITLE
store/tikv: enlarge default committer-concurrency to avoid queuing (#23720)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23720 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23776
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23776:release-5.0-f64856bba055
```

---

Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/22516

Problem Summary:

The default committer-concurrency(16) is too small. It results in queuing in TiDB if a transaction has more than 16 requests.

### What is changed and how it works?

What's Changed:

Enlarge the default value to 128. Committer concurrency is introduced in v4.0 to reduce pressure(server is busy) on TiKV. However, I have met several times the performance is bad due to queuing in TiDB. I prefer enlarging the default value to making TiKV less pressure.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

### Release note 

- No release note

### CODE REVIEW

**Comment by cfzjywxk** [comment]
LGTM

**Review by youjiali1995 — APPROVED** [review]

**Comment by cfzjywxk** [comment]
@zhouqiang-cl 
Brother Qiang, need the approve flag from you~

**Pull request merged**
