### PR TITLE
expression: Support Sqrt, Ceil, Floor and CastIntAsReal push down to TiFlash

### PR DESCRIPTION
**Pull request by chAngeZhaoZhanBo**
### What problem does this PR solve?
Related to https://github.com/pingcap/tics/issues/1901
Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:
Add Floor, Ceil, Sqrt and CastIntAsReal(for pushing down a sqrt for an int)  into scalarExprSupportedByFlash list

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
Use tiflash/integrated/ops or algernon to run a tidb-server and use explain query to make sure corresponding expression is pushed down

Side effects

### Release note 
- Pushdown sqrt, ceil, floor and CastIntAsReal to tiflash

### CODE REVIEW

**Review by jackysp — APPROVED** [review]
LGTM

**Review by LittleFall — APPROVED** [review]
lgtm, could you add some tests in TestExprPushDownToFlash?

**Review by zanmato1984 — APPROVED** [review]
LGTM

**Comment by LittleFall** [comment]
> /merge

chabuduodel

**Comment by LittleFall** [comment]
> /chabuduodel

so effectively

**Pull request merged**
