### PR TITLE
types,*: remove the dependency `stmtctx` from `types` package.

### LINKED ISSUE #48080: Remove `stmtctx` from `types` package
After doing the refractor in https://github.com/pingcap/tidb/issues/47355, we can (at least try to) remove the dependency `stmtctx` from `types` package and see what's left.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #48080

Problem Summary:

This PR removes the dependency `stmtctx` from `types` packages.

### What is changed and how it works?

1. The `stmtctx` dependency is removed from `types` package.
2. The `types/context` has been merged with `types`. The existing alias is removed.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Like other refractor, this PR is covered by existing tests.

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

**Review by lcwangchao — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
The deadlock is not related with current PR. I've recorded them in an issue: https://github.com/pingcap/tidb/issues/48178

/retest

**Pull request merged**
