### PR TITLE
types: support sql_mode ALLOW_INVALID_DATES (#9027)

### PR DESCRIPTION
**Pull request by bobotu**
Cherry pick #9027 to release 2.1, needs https://github.com/pingcap/parser/pull/185

### CODE REVIEW

**Comment by bobotu** [comment]
PTAL @jackysp

**Comment by jackysp** [comment]
PTAL @gregwebs

**Comment by gregwebs** [comment]
Thank you! If possible, the replace directive should point to this repository (but a different git version).

**Comment by lysu** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
