### PR TITLE
br: fix unstable s3 test

### LINKED ISSUE #33644: br: unstable test `br_s3`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`/run-integration-br-test` in any PR.

### 2. What did you expect to see? (Required)

The test passed.

### 3. What did you see instead (Required)

The case `br-s3` doesn't pass, because:

`curl` exit with 0 even it met a 503 HTTP CODE. At this condition, mc would fail soon and so did the test.

### 4. What is your TiDB version? (Required)

Current master, however it doesn't matter.

### PR DESCRIPTION
**Pull request by YuJuncen**
Signed-off-by: Yu Juncen <yu745514916@live.com>

### What problem does this PR solve?

Issue Number: close #33644

Problem Summary:

The test case `br_s3` is unstable. The reason would probably be that `curl` exit with `0` even it met a 503 HTTP CODE. At this condition, `mc` would fail soon and so did the test.

### What is changed and how it works?

Test the status code instead of the exit code of curl.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Review by 3pointer — APPROVED** [review]

**Comment by YuJuncen** [comment]
`br_s3` started successfully.🤔

**Review by joccau — APPROVED** [review]
LGTM

**Pull request merged**
