### PR TITLE
DDL: Wrong Date type colunm's default value

### LINKED ISSUE #30358: Table definition for date filed is showing date and time in Tidb and mysql is only showing date
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t1;
create table t1 (da date default '1962-03-03 23:33:34', dt datetime default '1962-03-03');
show create table t1;
```

### 2. What did you expect to see? (Required)
```sql
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                           |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `da` date DEFAULT '1962-03-03',
  `dt` datetime DEFAULT '1962-03-03 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
```
### 3. What did you see instead (Required)
```sql
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                             |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `da` date DEFAULT '1962-03-03 23:33:34',
  `dt` datetime DEFAULT '1962-03-03 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
```
### 4. What is your TiDB version? (Required)
```sql
| Release Version: v5.4.0-alpha-264-g6efa36df6
Edition: Community
Git Commit Hash: 6efa36df6cff325106f67ecfe3d79816ba37ca6a
Git Branch: master
UTC Build Time: 2021-11-29 16:57:51
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by Benjamin2037**
### What problem does this PR solve?

Issue Number: close #30358

Problem Summary:

### What is changed and how it works?
The fix formats the deafult value that is inputed for create/alter a date type column.  If the input default value is datetime or timestamp kind string, it will be converted to date format string and stored.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
@Benjamin2037 Don't forget to sign CLA.

**Comment by Benjamin2037** [comment]
> /run-mysql-test



> @Benjamin2037 Don't forget to sign CLA.

Thanks for remind! Have signed CLA already.

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by Benjamin2037** [comment]
>

**Review by xhebox — APPROVED** [review]

**Comment by Benjamin2037** [comment]
> /run-mysql-test

I have run 'make dev'  , if that is enough or not?

**Pull request merged**
