### PR TITLE
expression: optimize BCE on the builtinFromUnixTime2ArgSig

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: ref #34669

Problem Summary:

Go is a memory safe language. In array/slice element indexing and subslice operations, Go runtime will check whether or not the involved indexes are out of range. If an index is out of range, a panic will be produced to prevent the invalid index from doing harm. This is called bounds check. Bounds checks make our code run safely, on the other hand, they also make our code run a little slower.

### What is changed and how it works?

```
make vectorized-bench VB_FILE=Time VB_FUNC=builtinFromUnixTime2ArgSig 
```

Before

```go
goos: darwin
goarch: amd64
pkg: github.com/pingcap/tidb/expression
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkVectorizedBuiltinTimeFuncGenerated
BenchmarkVectorizedBuiltinTimeFuncGenerated-16    	1000000000	         0.3045 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinTimeFunc
BenchmarkVectorizedBuiltinTimeFunc-16             	1000000000	         0.06184 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/pingcap/tidb/expression	7.986s
```

After

```
goos: darwin
goarch: amd64
pkg: github.com/pingcap/tidb/expression
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkVectorizedBuiltinTimeFuncGenerated
BenchmarkVectorizedBuiltinTimeFuncGenerated-16          1000000000               0.2601 ns/op          0 B/op          0 allocs/op
BenchmarkVectorizedBuiltinTimeFunc
BenchmarkVectorizedBuiltinTimeFunc-16                   1000000000               0.05196 ns/op         0 B/op          0 allocs/op
PASS
ok      github.com/pingcap/tidb/expression      5.989s
```

**17% performance improvement**

### Check List

Tests 

- [x] Unit test
- [x] Integration test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by ngaut** [comment]
Good catch.

**Comment by hawkingrei** [comment]
update benchmark report

```
benchmark                                          old ns/op     new ns/op     delta
BenchmarkVectorizedBuiltinTimeFuncGenerated-16     0.18          0.19          +3.19%
BenchmarkVectorizedBuiltinTimeFuncGenerated-16     0.19          0.19          +0.85%
BenchmarkVectorizedBuiltinTimeFuncGenerated-16     0.18          0.19          +6.57%
BenchmarkVectorizedBuiltinTimeFuncGenerated-16     0.19          0.19          +1.15%
BenchmarkVectorizedBuiltinTimeFuncGenerated-16     0.19          0.19          +3.52%
BenchmarkVectorizedBuiltinTimeFuncGenerated-16     0.20          0.19          -1.28%
BenchmarkVectorizedBuiltinTimeFuncGenerated-16     0.18          0.20          +7.12%
BenchmarkVectorizedBuiltinTimeFuncGenerated-16     0.19          0.19          -0.57%
BenchmarkVectorizedBuiltinTimeFuncGenerated-16     0.20          0.20          +1.53%
BenchmarkVectorizedBuiltinTimeFuncGenerated-16     0.20          0.20          -0.55%
BenchmarkVectorizedBuiltinTimeFunc-16              0.04          0.04          +1.83%
BenchmarkVectorizedBuiltinTimeFunc-16              0.04          0.04          +14.12%
BenchmarkVectorizedBuiltinTimeFunc-16              0.04          0.04          +16.38%
BenchmarkVectorizedBuiltinTimeFunc-16              0.04          0.04          -2.64%
BenchmarkVectorizedBuiltinTimeFunc-16              0.04          0.04          -0.41%
BenchmarkVectorizedBuiltinTimeFunc-16              0.04          0.04          -13.60%
BenchmarkVectorizedBuiltinTimeFunc-16              0.04          0.04          +0.05%
BenchmarkVectorizedBuiltinTimeFunc-16              0.04          0.04          +13.30%
BenchmarkVectorizedBuiltinTimeFunc-16              0.04          0.04          +3.00%
BenchmarkVectorizedBuiltinTimeFunc-16              0.04          0.04          +0.79%
```

**Review by xhebox — COMMENTED** [review]
It does improve the perf, but it is also ugly. I don't think we should merge this.

We should consider some alternatives, .e.g. moving some logic into column, instead in the expression package. Then BCE could be eliminated while the outer package does not have many assumptions on the internal implementation.

@hawkingrei What do you think about?

**Comment by hawkingrei** [comment]
> It does improve the perf, but it is also ugly. I don't think we should merge this.
> 
> We should consider some alternatives, .e.g. moving some logic into column, instead in the expression package. Then BCE could be eliminated while the outer package does not have many assumptions on the internal implementation.
> 
> @hawkingrei What do you think about?

I think it is a test to show the possibility that we can optimize BCE to get some performance improvement. but it is really ugly. I think we can improve golang SSA to make the Golang compiler optimize BCE. but it is a hard task.

**Comment by xhebox** [comment]
> I think it is a test to show the possibility that we can optimize BCE to get some performance improvement. but it is really ugly.

You could put the benchmark and the one line core change into your issue. Thus this PR could be closed. I am cleaning some stale PRs and issues.

> I think we can improve golang SSA to make the Golang compiler optimize BCE. but it is a hard task.

I doubt if it is possible. Golang is not good at inlining, or they don't make much effort. It will be very difficult to optimize BCE across functions.

**Comment by xhebox** [comment]
> You could put the benchmark and the one line core change into your issue. Thus this PR could be closed. I am cleaning some stale PRs and issues.

Closing. Put the example into the tracking issue.

**Pull request closed without merging**
