### PR TITLE
bindinfo: physically delete previous binding when recreating a binding

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/21288

Problem Summary:

Unexpected binding cache if there are concurrent CREATE BINDING on multiple tidb instances.

### What is changed and how it works?

What's Changed:

Physically delete previous bindings when recreating a binding, instead of marking them as deleted.

How it Works:

Logical delete may cause unexpected binding caches if there are concurrent CREATE BINDING on multiple tidb instances, because the record with `using` status is not guaranteed to have larger update_time than those records with `deleted` status.

Since recreation would always insert a new binding with same fingerprint, this recreation can be synchronized to other tidb instances successfully.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test: use the reproduction program provided in the issue, the binding cache is correct after applying this PR.

Side effects

N/A

### Release note 

- physically delete previous binding when recreating a binding

### CODE REVIEW

**Review by Reminiscent — COMMENTED** [review]
LGTM

**Review by qw4990 — DISMISSED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]
LGTM

**Comment by qw4990** [comment]
PTAL @lzmhhh123

**Pull request merged**
