### PR TITLE
planner: check required order property for enforced stream aggregation

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/17325

Problem Summary:

Wrong result for enforced stream aggregation when order is required.

### What is changed and how it works?

What's Changed:

Check if the enforced stream aggregation can satisfy the required order property.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 
- Fix wrong result order for enforced stream aggregation.

### CODE REVIEW

**Comment by SunRunAway** [comment]
CI failed because of https://github.com/pingcap/tidb/issues/17146

**Comment by SunRunAway** [comment]
Is this bug affected with v3.0? @eurekaka

**Comment by eurekaka** [comment]
> Is this bug affected with v3.0? @eurekaka

No.

**Pull request merged**
