### PR TITLE
test: fix `TestDDLSchedulingMultiTimes` and `TestConcurrentDDLSwitch` timeout

### PR DESCRIPTION
**Pull request by xiongjiwei**
Signed-off-by: xiongjiwei <xiongjiwei1996@outlook.com>

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by wjhuang2016 — COMMENTED** [review]
TestConcurrentDDLSwitch timeouts too.

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
