### PR TITLE
types: fix Datum's value of field `decimal` ,`length` when its set with `MyDecimal`

### PR DESCRIPTION
**Pull request by spongedu**

### CODE REVIEW

**Comment by breeswish** [comment]
LGTM

**Comment by shenli** [comment]
@coocood @tiancaiamao PTAL

**Comment by coocood** [comment]
@spongedu 
There is failed test, when we use a decimal index.
The reason may be that the decimal prec and length affects the index codec.

**Comment by spongedu** [comment]
@coocood yep. I'm looking into the failed case. The reason is as you mentioned, `EncodeDecimal` encodes `prec` and `length` into `[]byte`, which is ok without this pr because these two fields are not manually 
is the following line necessary (`util/codec/decimal.go`, line 31) ?

**Comment by coocood** [comment]
@spongedu 
Yes, it is, without `length` and `prec`, the encoded value will not be memory comparable.

**Comment by zz-jason** [comment]
@spongedu any update ?

**Comment by coocood** [comment]
@spongedu 
I think the right way to do it is to explicitly set Datum length and decimal by the caller.
Internally set them may not be what we needed.

**Comment by coocood** [comment]
@spongedu 
I'll close this PR because it breaks the test.

**Pull request closed without merging**
