### PR TITLE
*: upgrade go1.20.5

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: ref #44476

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by mjonss — APPROVED** [review]
Should other files containing older go version >= 1.20 also be updated?
```
build/image/base:ENV GOLANG_VERSION 1.20.1
tests/globalkilltest/Dockerfile:ENV GOLANG_VERSION 1.20.3
```

**Comment by hawkingrei** [comment]
> Should other files containing older go version >= 1.20 also be updated?
> 
> ```
> build/image/base:ENV GOLANG_VERSION 1.20.1
> tests/globalkilltest/Dockerfile:ENV GOLANG_VERSION 1.20.3
> ```

I have updated it.

**Comment by hawkingrei** [comment]
@bb7133 PTAL

**Comment by hawkingrei** [comment]
@XuHuaiyu PTAL

**Comment by hawkingrei** [comment]
@bb7133  PTAL

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
