### PR TITLE
executor: support Chunk for ExecuteExec

### PR DESCRIPTION
**Pull request by zz-jason**
to #5261

### CODE REVIEW

**Comment by coocood** [comment]
We should support this last.
The prepared statement may not support Chunk yet.

**Comment by shenli** [comment]
The PR for [prepared executor](https://github.com/pingcap/tidb/pull/5408) is already merged. Could we go on with this PR now? @coocood

**Comment by coocood** [comment]
@shenli 
No, the statement to be executed may not support Chunk.

**Comment by zz-jason** [comment]
@coocood @XuHuaiyu PTAL

**Comment by coocood** [comment]
LGTM

**Pull request merged**
