### PR TITLE
ddl: fix a bug that 'flashback table' does not handle mysql.gc_delete_range correctly

### LINKED ISSUE #37386: when do flashback table. The mysql.gc_delete_range table is not emptied.After gc the data will gone.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
# tiup  playground v6.2.0  --host 0.0.0.0
# mysql -uroot -P4000 -h xx.xx.xx.xx
mysql> create database a;
mysql> use a;
mysql> create table t(id int);
mysql> insert into t values(1),(2),(3);
mysql> drop table t;
mysql> flashback table t;
mysql> select * from mysql.gc_delete_range;
```

### 2. What did you expect to see? (Required)
 mysql.delete range is empty. The data of flashback table will not be lost.
### 3. What did you see instead (Required)
mysql.delete range is not empty. The data is gone after gc .
### 4. What is your TiDB version? (Required)
```
mysql> select  tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.2.0
Edition: Community
Git Commit Hash: daf2b17cdfe30c02ce282361009fb5bdb05f2b0e
Git Branch: heads/refs/tags/v6.2.0
UTC Build Time: 2022-08-22 13:47:05
GoVersion: go1.18.5
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
1 row in set (0.00 sec)

mysql> 
```

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #37386

Problem Summary:

### What is changed and how it works?

@crazycs520 regard the `element_id` of `mysql.gc_delete_range` as table ID mistakenly...
So the constructed SQL from deleting the `gc_delete_range` record is wrong.

`element_id` is not table id, it's just an ID to distinguish multiple records within a job.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)

unistore doesn't implement the `flashback table` utilities, so I can't write the unit test.
I verified that #37386 is solved after this change.
And also, 

```
create table pt (id int) partition by hash(id) partitions 5;
drop table pt;
flashback table pt;
```

```
create table a (id int);
create table b (id int);
drop table a,b;
flashback table b;
```

```
truncate table b;
flashback table b;
```

Check the gc_delete_range is correct in each step.

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix a bug that 'flashback table' does not handle `mysql.gc_delete_range` correctly, this bug make the 'flashback table' feature almost unavailable.
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Comment by crazycs520** [comment]
In the code version of https://github.com/pingcap/tidb/pull/13109, the `element_id` of `mysql.gc_delete_range` really is use to store the `table_ID` or `index_id`, so the issue https://github.com/pingcap/tidb/issues/37386 won't exist in the old version.

**Comment by tiancaiamao** [comment]
After discuss with @crazycs520 , it's not him who misunderstand the `element id` and `table id`
At that time, the semantic is indeed `table id`...

Later, https://github.com/pingcap/tidb/pull/33726/ try to fix another bug, and change the `element id`, and then introduce this bug.

**Pull request merged**
