### PR TITLE
sessionctx: fix issue #32222

### LINKED ISSUE #32222: slow query log DB field doesn't store the lowercase database name
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> use TeST;
Database changed

mysql> select sleep(1);
+----------+
| sleep(1) |
+----------+
|        0 |
+----------+
1 row in set (1.10 sec)

mysql> select SCHEMA_NAME from INFORMATION_SCHEMA.CLUSTER_STATEMENTS_SUMMARY_HISTORY order by LAST_SEEN desc limit 1\G
*************************** 1. row ***************************
SCHEMA_NAME: test
1 row in set (0.05 sec)

mysql> select DB from INFORMATION_SCHEMA.CLUSTER_SLOW_QUERY order by Time desc limit 1\G
*************************** 1. row ***************************
DB: TeST
1 row in set (0.05 sec)
```

### 2. What did you expect to see? (Required)

We expect to see the DB field value of the slow query log should be `test`.

### 3. What did you see instead (Required)

We see the DB field value as `TeST`.

### 4. What is your TiDB version? (Required)

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.3.0
Edition: Community
Git Commit Hash: 4a1b2e9fe5b5afb1068c56de47adb07098d768d6
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-24 13:32:39
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.19 sec)
```

I didn't try master branch, but I think it should exist the same issue.

### PR DESCRIPTION
**Pull request by LemonHX**
Signed-off-by: lemonhx <lemonhx@lemonhx.tech>

### What problem does this PR solve?

Issue Number: close #32222

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by crazycs520 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Comment by LemonHX** [comment]
@hawkingrei

**Comment by LemonHX** [comment]
@morgo @bb7133

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
