### PR TITLE
br: add pprof package back

### PR DESCRIPTION
**Pull request by joccau**
Signed-off-by: joccau <zak.zhao@pingcap.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/32638

Problem Summary: Fail to run CI because of without `pprof` package`pprof` for HTTP handler

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Comment by kennytm** [comment]
@joccau remove irrelevant `may-affect-` labels in #32638

**Review by fengou1 — APPROVED** [review]

**Pull request merged**
