### PR TITLE
*: revert 38302 for release 6.5

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #39922

Problem Summary:
Revert https://github.com/pingcap/tidb/pull/38302 for release 6.5.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by mjonss — APPROVED** [review]
LGTM

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by Defined2014** [comment]
Seems `TestAlterModifyColumnOnPartitionedTableFail` test failed. @wjhuang2016

**Pull request merged**
