### PR TITLE
*: remove `kv.BypassLatch` option and enable latch scheduler by default

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

1. `kv.BypassLatch` was introduced to handle the fake transaction conflicting problem
in the old implementation. After [redesign of the latch scheduler](https://github.com/pingcap/tidb/pull/7711), it's not needed any more.

2. Enable latch scheduler by default makes CI to run it, we can fix bugs and make this feature
more stable.

### What is changed and how it works?

Set `Capacity` to 2048000 cost about 96M memory.
The old value 10240000 cost more than 700M, which I think is too large.

### Check List 

Tests 

 - No code

Side effects

There is a small performance penalty, less than 5%, users are free to disable it.

@shenli

### CODE REVIEW

**Comment by ngaut** [comment]
Can we enable latch and import data to TiDB?

**Comment by tiancaiamao** [comment]
Sure! @ngaut

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
