### PR TITLE
executor,util: Improve logging for ADMIN CHECK TABLE

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: ref #40921

Problem Summary:

There is no good progress reporting for `ADMIN CHECK TABLE` and `ADMIN CHECK INDEX`

### What is changed and how it works?

Show the progress of the tasks every 1000 chunks (1_000_000 rows)

Alternatives:
- Show progress in `ADMIN SHOW DDL JOBS`. This would be useful but is a bigger change
- Report the progress in a information_schema table. 
- Report the progress to prometheus/grafana
- Show the progress every x minutes instead of every x chunks

Some of these alternatives can be implemented in addition to this PR.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Logging for `ADMIN CHECK TABLE` and `ADMIN CHECK INDEX` has been improved to show the progress of the operation
```

### CODE REVIEW

**Comment by dveeden** [comment]
The current output is a bit confusing as there are multiple lines even when considering the different workers.
```
[2023/04/27 11:53:44.452 +02:00] [INFO] [admin.go:101] ["check indices count"] [table=orders] [tblCnt=345671] [index=o_all_local] [idxCnt=345671]
[2023/04/27 11:53:45.384 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=4] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:45.611 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=0] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:45.854 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=1] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:46.104 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=2] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:46.385 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=3] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:46.645 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=4] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:46.835 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=0] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:46.838 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=1] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:46.865 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=2] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:46.978 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=3] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:47.004 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=4] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:47.123 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=0] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:47.143 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=2] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:47.150 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=1] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:47.250 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=3] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:47.261 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=4] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:47.301 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=0] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:47.344 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=2] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:47.350 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=1] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:47.378 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=4] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
[2023/04/27 11:53:47.384 +02:00] [INFO] [distsql.go:1377] ["Comparing index with table data"] [conn=2199023255955] [table=orders] [index=o_all_local] [workerID=3] [chunkSize=1024] [chunksDone=0] [rowsDone=0]
```

**Comment by ekexium** [comment]
Is the chunk size a constant? Is it possible to produce too many noisy logs? IMO "Show the progress every x minutes instead of every x chunks" might be better as it is more robust against chunk size and worker speed. 

BTW it would be great if we can show the estimated percentage of work finished.

**Comment by dveeden** [comment]
This PR doesn't really work anymore with the FastCheckTable improvements. Also as noted before it would be better to have this shown in the same way as various DDL jobs.

**Pull request closed without merging**
