### PR TITLE
lightning: fix missing configurable keyspace name

### LINKED ISSUE #43684: lightnning: miss keyspace config
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. config `keysapce name`
2. start tidb cluster with configurable `keyspace name`
3. import data

### 2. What did you expect to see? (Required)
success

### 3. What did you see instead (Required)
fail

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by zeminzhou**
### What problem does this PR solve?

Issue Number: close #43684

Problem Summary:

### What is changed and how it works?

fix missing configurable keyspace name

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lichunzhu — APPROVED** [review]

**Review by lance6716 — COMMENTED** [review]
Can you add an integration test for this feature, or do we already have one?

**Comment by zeminzhou** [comment]
> Can you add an integration test for this feature, or do we already have one?

I perfected the relevant tests, PTAL~

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
