### PR TITLE
variable: fix setting tidb_enable_tso_follower_proxy with TSO service

### LINKED ISSUE #51194: (pd-microservices) after enable pd microservice, "set global tidb_enable_tso_follower_proxy = 1" will be stuck
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

config tidb cluster as following.
```
    - name: tc
      type: TIDB_CLUSTER
      spec:
        pd:
          baseImage: hub-new.pingcap.net/qa/pd
          version: master
          config: |
            [dashboard]
            internal-proxy = true        
          limits:
            cpu: 500m
            memory: 1Gi
            storage: 1500Gi
          mode: ms
          replicas: 1
          requests:
            cpu: 151m
            memory: 600Mi
            storage: 1500Gi
          service:
            type: NodePort
        pdms:
          - baseImage: hub-new.pingcap.net/qa/pd
            config: |
              [log.file]
              filename = "/var/lib/pd/tso/tso.log"         
            limits:
              cpu: 2000m
              memory: 2Gi
              storage: 10Gi
            name: tso
            replicas: 2
            requests:
              cpu: 2000m
              memory: 2Gi
              storage: 10Gi
            storageVolumes:
              - mountPath: /var/lib/pd/tso
                name: log
                storageClassName: local-path
                storageSize: 10Gi
            version: master
          - baseImage: hub-new.pingcap.net/qa/pd
            config: |
              [log.file]
              filename = "/var/lib/pd/scheduling/scheduling.log"          
            limits:
              cpu: 2000m
              memory: 2Gi
              storage: 20Gi
            name: scheduling
            replicas: 2
            requests:
              cpu: 2000m
              memory: 2Gi
              storage: 20Gi
            storageVolumes:
              - mountPath: /var/lib/pd/scheduling
                name: log
                storageClassName: local-path
                storageSize: 20Gi
            version: master
```
run following set in sql
```
set global tidb_enable_tso_follower_proxy = 1
```

### 2. What did you expect to see? (Required)
Return failed.

### 3. What did you see instead (Required)
stuck more than 1 hours.

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: close #51194.

Problem Summary:

Fix the problem that setting `tidb_enable_tso_follower_proxy` with TSO service will cause stuck.

### What changed and how does it work?

Return the error after setting `tidb_enable_tso_follower_proxy`.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)

With TSO service:

```shell
mysql> select @@tidb_enable_tso_follower_proxy;
+----------------------------------+
| @@tidb_enable_tso_follower_proxy |
+----------------------------------+
|                                0 |
+----------------------------------+
1 row in set (0.00 sec)

mysql> set global tidb_enable_tso_follower_proxy = 1;
ERROR 1105 (HY000): [pd] tso follower proxy is only supported in PD service mode
mysql> select @@tidb_enable_tso_follower_proxy;
+----------------------------------+
| @@tidb_enable_tso_follower_proxy |
+----------------------------------+
|                                0 |
+----------------------------------+
1 row in set (0.00 sec)

mysql> set global tidb_enable_tso_follower_proxy = 0;
ERROR 1105 (HY000): [pd] tso follower proxy is only supported in PD service mode
mysql> select @@tidb_enable_tso_follower_proxy;
+----------------------------------+
| @@tidb_enable_tso_follower_proxy |
+----------------------------------+
|                                0 |
+----------------------------------+
1 row in set (0.00 sec)

mysql> set global tidb_tso_client_batch_max_wait_time = 1;
Query OK, 0 rows affected (0.01 sec)

mysql> select @@tidb_tso_client_batch_max_wait_time;
+---------------------------------------+
| @@tidb_tso_client_batch_max_wait_time |
+---------------------------------------+
| 1                                     |
+---------------------------------------+
1 row in set (0.00 sec)

mysql> set global tidb_tso_client_batch_max_wait_time = 0;
Query OK, 0 rows affected (0.02 sec)

mysql> select @@tidb_tso_client_batch_max_wait_time;
+---------------------------------------+
| @@tidb_tso_client_batch_max_wait_time |
+---------------------------------------+
| 0                                     |
+---------------------------------------+
1 row in set (0.00 sec)
```

With PD:

```shell
mysql> select @@tidb_enable_tso_follower_proxy;
+----------------------------------+
| @@tidb_enable_tso_follower_proxy |
+----------------------------------+
|                                0 |
+----------------------------------+
1 row in set (0.00 sec)

mysql> set global tidb_enable_tso_follower_proxy = 1;
Query OK, 0 rows affected (0.02 sec)

mysql> select @@tidb_enable_tso_follower_proxy;
+----------------------------------+
| @@tidb_enable_tso_follower_proxy |
+----------------------------------+
|                                1 |
+----------------------------------+
1 row in set (0.00 sec)

mysql> set global tidb_enable_tso_follower_proxy = 0;
Query OK, 0 rows affected (0.02 sec)

mysql> select @@tidb_enable_tso_follower_proxy;
+----------------------------------+
| @@tidb_enable_tso_follower_proxy |
+----------------------------------+
|                                0 |
+----------------------------------+
1 row in set (0.00 sec)

mysql> set global tidb_tso_client_batch_max_wait_time = 1;
Query OK, 0 rows affected (0.01 sec)

mysql> select @@tidb_tso_client_batch_max_wait_time;
+---------------------------------------+
| @@tidb_tso_client_batch_max_wait_time |
+---------------------------------------+
| 1                                     |
+---------------------------------------+
1 row in set (0.00 sec)

mysql> set global tidb_tso_client_batch_max_wait_time = 0;
Query OK, 0 rows affected (0.02 sec)

mysql> select @@tidb_tso_client_batch_max_wait_time;
+---------------------------------------+
| @@tidb_tso_client_batch_max_wait_time |
+---------------------------------------+
| 0                                     |
+---------------------------------------+
1 row in set (0.00 sec)
```

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the problem that setting `tidb_enable_tso_follower_proxy` with TSO service will cause stuck.
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by lhy1024** [comment]
Do it need to be picked to release-7.5?

**Comment by JmPotato** [comment]
> Does it need to be picked to release-7.5?

No, PD supports the microservice mode starting from v8.0.0.

**Pull request merged**
