### PR TITLE
plan: make explain result more readable

### PR DESCRIPTION
**Pull request by winoros**
## What have you changed? (mandatory)

Previous, for double read case. second read is in front of the first read. like this:
```
+--------------------------+------+-----------------------------------------------------------------+-------+
| id                       | task | operator info                                                   | count |
+--------------------------+------+-----------------------------------------------------------------+-------+
| Limit_9                  | root | offset:0, count:1                                               | 1.00  |
| └─IndexLookUp_17         | root | index:Selection_14, table:Limit_16                              | 1.00  |
|   ├─Selection_14         | cop  | gt(test.t.b, 1)                                                 | 3.00  |
|   │ └─IndexScan_12       | cop  | table:t, index:a, b, range:(1 +inf,+inf +inf], keep order:false | 9.00  |
|   └─Limit_16             | cop  | offset:0, count:1                                               | 1.00  |
|     └─Selection_15       | cop  | gt(test.t.c, 1)                                                 | 1.00  |
|       └─TableScan_13     | cop  | table:t, keep order:false                                       | 3.00  |
+--------------------------+------+-----------------------------------------------------------------+-------+
```

Now we change the order:
```
+----------------------------+------+-----------------------------------------------------------------+-------+
| id                         | task | operator info                                                   | count |
+----------------------------+------+-----------------------------------------------------------------+-------+
| Limit_9                    | root | offset:0, count:1                                               | 1.00  |
| └─IndexLookUp_17           | root | index:Selection_14, table:Limit_16                              | 1.00  |
|   ├─Limit_16               | cop  | offset:0, count:1                                               | 1.00  |
|   │ └─Selection_15         | cop  | gt(test.t.c, 1)                                                 | 1.00  |
|   │   └─TableScan_13       | cop  | table:t, keep order:false                                       | 3.00  |
|   └─Selection_14           | cop  | gt(test.t.b, 1)                                                 | 3.00  |
|     └─IndexScan_12         | cop  | table:t, index:a, b, range:(1 +inf,+inf +inf], keep order:false | 9.00  |
+----------------------------+------+-----------------------------------------------------------------+-------+
```

We can read it more easily.

## What are the type of the changes (mandatory)?

The currently defined types are listed below, please pick one of the types for this PR by removing the others:
- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested (mandatory)?

existing tests.

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
For readable, I think put tableReader first may be better.
It would be more friendly to the common users.

**Comment by winoros** [comment]
@zz-jason For a subtree, its execution timeline is from bottom to top, just like the row count is decreasing from bottom to top. So the cop task should also work like this.

**Comment by zz-jason** [comment]
@winoros If so, a better idea is to print the whole tree from bottom to top recursively, not just the `IndexLookupReader`

**Comment by winoros** [comment]
@zz-jason For now, the tree's structure is from top to bottom. The execution logic is from bottom to top. For a subtree. If planA is below than planB, means planA is sub plan of B and it executes earlier than B.
Only double read case not follow this rule.

**Comment by zz-jason** [comment]
@winoros The tree structure can not represent the execution pipeline. For example Hash Join will start both outer and inner child at the same time. When we looking at the plan tree printed, we loop from top to bottom, and for `IndexLookupReader`, this means `IndexReader` comes firstly.

**Pull request closed without merging**
