### PR TITLE
planner: push aggregation operators down to projection by default

### LINKED ISSUE #22072: push aggregation operators down to projection and union by default
## Development Task
```
mysql> explain select sum(col1) from ( select (case when a=1 then 1 else 0 end) as col1 from t ) a;
+-----------------------------+----------+-----------+---------------+------------------------------------------------+
| id                          | estRows  | task      | access object | operator info                                  |
+-----------------------------+----------+-----------+---------------+------------------------------------------------+
| HashAgg_6                   | 1.00     | root      |               | funcs:sum(Column#6)->Column#4                  |
| └─Projection_14             | 10000.00 | root      |               | cast(Column#3, decimal(22,0) BINARY)->Column#6 |
|   └─Projection_8            | 10000.00 | root      |               | case(eq(test.t.a, 1), 1, 0)->Column#3          |
|     └─TableReader_10        | 10000.00 | root      |               | data:TableFullScan_9                           |
|       └─TableFullScan_9     | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo                 |
+-----------------------------+----------+-----------+---------------+------------------------------------------------+
5 rows in set (0.00 sec)
mysql> set @@tidb_opt_agg_push_down=1;
Query OK, 0 rows affected (0.00 sec)
mysql> explain select sum(col1) from ( select (case when a=1 then 1 else 0 end) as col1 from t ) a;
+----------------------------+----------+-----------+---------------+--------------------------------------------------+
| id                         | estRows  | task      | access object | operator info                                    |
+----------------------------+----------+-----------+---------------+--------------------------------------------------+
| StreamAgg_17               | 1.00     | root      |               | funcs:sum(Column#7)->Column#4                    |
| └─TableReader_18           | 1.00     | root      |               | data:StreamAgg_9                                 |
|   └─StreamAgg_9            | 1.00     | cop[tikv] |               | funcs:sum(case(eq(test.t.a, 1), 1, 0))->Column#7 |
|     └─TableFullScan_16     | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo                   |
+----------------------------+----------+-----------+---------------+--------------------------------------------------+
4 rows in set (0.00 sec)
```

Whether aggregation operators are pushed down to projection and union is controlled by a variable `tidb_opt_agg_push_down`.
This rule always leads to a better plan, so we can enable this rule by default.

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #22072  

Problem Summary:

### What is changed and how it works?

What's Changed:
push aggregation operators down to projection and union by default
How it Works:
remove the check of `AllowAggPushDown`

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- No release note

### CODE REVIEW

**Comment by TszKitLo40** [comment]
PTAL @qw4990

**Comment by winoros** [comment]
Please fix the tests.
And this pr only dealt with `Projection`. Also I think we don't need consider `UnionAll` in this case.

A simple case is that
- The union's sub child's NDV is large and their distribution is almost the same, we don't need to push it down.

**Comment by TszKitLo40** [comment]
> Please fix the tests.
> And this pr only dealt with `Projection`. Also I think we don't need consider `UnionAll` in this case.
> 
> A simple case is that
> 
> * The union's sub child's NDV is large and their distribution is almost the same, we don't need to push it down.

ok, I have done this, PTAL

**Review by winoros — COMMENTED** [review]
lgtm

**Comment by TszKitLo40** [comment]
@qw4990 PTAL

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
