### PR TITLE
executor: do not set priority when tidb_force_priority is set

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve? 
It is not suitable to set statements priority by stats, especially when `tidb_force_priority` is set.

### What is changed and how it works?
Do not set priority by stats.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Related changes

 - Need to cherry-pick to the release branch

Release note

 - Write release note for bug-fix or new feature.

### CODE REVIEW

**Comment by jackysp** [comment]
I'll add some tests for it.

**Comment by tiancaiamao** [comment]
I think the priority session variable will overwrite other settings unconditionally?

https://github.com/pingcap/tidb/blob/c3396ac5eb8362addd8789b5f86a33c5c9db8af9/distsql/request_builder.go#L162

**Comment by jackysp** [comment]
Yes, but the priority in the session context will be reset when building the executor.
https://github.com/pingcap/tidb/blob/ebed3d606c5286265282c3440547413a0fa01a82/executor/adapter.go#L708 @tiancaiamao

**Comment by coocood** [comment]
LGTM

**Pull request merged**
