### PR TITLE
statistics: fix bug when update stats delta

### PR DESCRIPTION
**Pull request by lamxTyler**
When the delta is less than  0, the origin update to the unsigned stats_meta.count will cause an error.
PTAL @hanfei1991 @winoros

### CODE REVIEW

**Comment by hanfei1991** [comment]
any different between + - a and - a?

**Comment by lamxTyler** [comment]
@hanfei1991 Seems like the bug is not here. It should be ok.

**Comment by lamxTyler** [comment]
According to @XuHuaiyu @zz-jason, the current behavior is decided to keep, so when the field is unsigned, + (-a) will cause an error, but the -a will not.

**Comment by hanfei1991** [comment]
LGTM

**Pull request merged**
