### PR TITLE
disttask: fix upgrade

### LINKED ISSUE #47299: `tidb_global_task_history` not create for upgrade tidb
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a cluster version before #47179 , 
2. upgrade cluster to the nightly 
3. check `mysql.tidb_global_task_history`

### 2. What did you expect to see? (Required)
`mysql.tidb_global_task_history` was created
### 3. What did you see instead (Required)
`mysql.tidb_global_task_history` not created
you can see the ` upgradeToVer176` not add to `bootstrapVersion` list
### 4. What is your TiDB version? (Required)
nightly(aba8342b7fb4d61639)

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: ref #47311 close #47299

Problem Summary:

### What is changed and how it works?
Forget to call upgradeToVer176

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
/hold

need to test https://github.com/pingcap/tidb/pull/47318 before we fix the problem 😂

**Comment by easonn7** [comment]
/approve

There is no sysvar change.

**Comment by lance6716** [comment]
/unhold

I'll test my PR after manually change related code

**Pull request merged**
