### PR TITLE
sessionctx/varsutil: fix format str in sysvar error msg

### PR DESCRIPTION
**Pull request by andelf**
`UnknownSystemVar` contains unused format placeholder for the variable name.

```go
UnknownSystemVar  = terror.ClassVariable.New(CodeUnknownSystemVar, "unknown system variable '%s'")
```

This fixes:

```
MySQL [test]> SELECT @@whatever_not_a_variable_in_system;
ERROR 1193 (HY000): unknown system variable '%!s(MISSING)'
```

### CODE REVIEW

**Comment by hanfei1991** [comment]
LGTM

**Comment by hanfei1991** [comment]
@andelf please sign the CLA

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@andelf Please sign the CLA.

**Pull request merged**
