### PR TITLE
README: Add sqlc to the list of parser users

### PR DESCRIPTION
**Pull request by Jille**
Issue Number: close https://github.com/pingcap/tidb/issues/44931

# Release notes

```release-note
None
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Comment by Defined2014** [comment]
> [CLA assistant check](https://cla.pingcap.net/pingcap/tidb?pullRequest=44930) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.pingcap.net/pingcap/tidb?pullRequest=44930) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.pingcap.net/check/pingcap/tidb?pullRequest=44930) it.

@Jille Please sign the license.

**Review by hawkingrei — APPROVED** [review]

**Comment by Jille** [comment]
Signed! I missed it in the flood of comments :)

**Pull request merged**
