### PR TITLE
parser: fix the result of `cast (0x10 as binary(2))`.

### PR DESCRIPTION
**Pull request by coocood**
For cast as binary with length, the result string is padded to the length.
We only don't do padding for `mysql.TypeVarString`, so change the type to `mysql.TypeString` if length is specified.

### CODE REVIEW

**Comment by coocood** [comment]
@XuHuaiyu @tiancaiamao @zimulala PTAL

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by zz-jason** [comment]
@coocood plz resolve conflicts.

**Pull request merged**
