### PR TITLE
stats: limit the length of sample values (#7931)

### PR DESCRIPTION
**Pull request by lamxTyler**
### What problem does this PR solve? 

Cherry-pick #7931 
### What is changed and how it works?

Cherry-pick #7931 
### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

- None

Related changes

 - None

### CODE REVIEW

**Comment by zz-jason** [comment]
LGTM

**Comment by zz-jason** [comment]
@lamxTyler should we also cherry pick it to release-2.0?

**Comment by lamxTyler** [comment]
@zz-jason Yes.

**Comment by zz-jason** [comment]
/run-integration-common-test tikv=release-2.1 pd=release-2.1
/run-integration-compatibility-test tikv=release-2.1 pd=release-2.1
/run-integration-ddl-test tikv=release-2.1 pd=release-2.1

**Pull request merged**
