### PR TITLE
cmd: move ddltest from tidb-test

### PR DESCRIPTION
**Pull request by zimulala**
Cherry-pick #9052 and #10542 to v2.1
Related to pingcap/tidb-test#853

### CODE REVIEW

**Comment by zimulala** [comment]
/run-integration-ddl-test tidb-test=pr/853 tikv=release-2.1 pd=release-2.1

**Comment by zimulala** [comment]
/run-all-tests tidb-test=pr/853 tikv=release-2.1 pd=release-2.1

**Comment by zimulala** [comment]
PTAL @tiancaiamao @bb7133

**Comment by mahjonp** [comment]
/run-all-tests tidb-test=pr/853 tikv=release-2.1 pd=release-2.1

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
