### PR TITLE
ddl: quickly process the next job after processing the cancelled DDL job (#24146)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #24146 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/24254
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/24254:release-5.0-6344f7a02e42
```

---

### What problem does this PR solve?

When the owner and the receiving DDL TiDB are on the same TiDB, quickly process the next job after processing the canceled DDL job.

### What is changed and how it works?

- When the DDL job is "JobStateRollbackDone", we notify the receiving DDL TiDB to process the finished job.

- Add a log after the DDL JOB fails.

What's Changed:

How it Works:

This optimization also enables faster testing.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

This optimization also enables faster testing.

Before this PR:
Executing `go test` takes **196.455s** in the DDL package.

After this PR:
Executing `go test` takes **134.877s** in the DDL package.

### Release note 

- When the owner and the receiving DDL TiDB are on the same TiDB, quickly process the next job after processing the canceled DDL job.

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @xhebox @AilinKid

**Comment by djshow832** [comment]
It's not very urgent, so we don't merge it into 5.0.

**Pull request closed without merging**
