### PR TITLE
codec: Don't convert set or enum datum to float64

### PR DESCRIPTION
**Pull request by ekexium**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/32302

Problem Summary:

Missing part of #32308 

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by MyonKeminta — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
/merge

**Pull request merged**
