### PR TITLE
types: fix a bug in decimal modulo operation

### PR DESCRIPTION
**Pull request by bb7133**
## What have you changed? (mandatory)

Fixed a bug in decimal modulo operation(`doDivMod` in types/mydecimal.go):

(Before this PR):
```
mysql> select 0.0000000001 mod 1.0;
+----------------------+
| 0.0000000001 mod 1.0 |
+----------------------+
|         0.1000000000 |
+----------------------+
1 row in set (0.00 sec)
```
(After this PR):
```
mysql> select 0.0000000001 mod 1.0;
+----------------------+
| 0.0000000001 mod 1.0 |
+----------------------+
|         0.0000000001 |
+----------------------+
1 row in set (0.00 sec)
```

## What is the type of the changes? (mandatory)

Bug fix

## How has this PR been tested? (mandatory)

Added 1 UT case

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

## Does this PR need to be added to the release notes? (mandatory)

No

## Refer to a related PR or issue link (optional)

Corresponding bug-fix at TiKV side: https://github.com/pingcap/tikv/pull/3336

### CODE REVIEW

**Comment by shenli** [comment]
@bb7133 Thanks!

**Comment by shenli** [comment]
@coocood PTAL

**Comment by coocood** [comment]
LGTM
@bb7133 
Thank you

**Pull request merged**
