### PR TITLE
statistics: fix some unstable tests in global stats (#23502)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23502 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/24033
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/24033:release-5.0-b1b375e7ef0e
```

---

### What problem does this PR solve?

Fix some unstable tests in global stats.
You can see these unstable tests in [here](https://dashboard.pingcap.net/dashboard/37).

### What is changed and how it works?
* Let the test TestDropPartitionStats execute linearly
* fix some mistakes in `testMergeTopN`

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Comment by lysu** [comment]
@zhouqiang-cl maybe need a label, this PR fix release-5.0 test unstable problem too

**Comment by lysu** [comment]
@qw4990 ptal

**Review by qw4990 — APPROVED** [review]

**Comment by Reminiscent** [comment]
The unstable test has been skipped via https://github.com/pingcap/tidb/pull/24003. So close this PR.

**Pull request closed without merging**
