### PR TITLE
planner: split test data from test cases in cbo_test.go

### LINKED ISSUE #15549: UCP: move execution plan test in `planner/core/cbo_test.go` from code to file
## Description

The execution plan test in this file is written in code. Which has poor usability: **It's hard to modify test result in code by hand**.

Instead, we can move this test to file. Like what we did in other places. As the title said, this issue is focused on regenerating all the UTs in **`./planner/core/cbo_test.go`**

Take what we did in `planner/core/point_get_plan_test.go` as an example:

`testPointGetSuite` uses the file located in `./planner/core/testdata/` for input and outputs:
- input: `./planner/core/testdata/point_get_plan_in.json`
- output: `./planner/core/testdata/point_get_plan_out.json`

he input and output file is specified in `testPointGetSuite.SetUpSuite()`:
```go
 45 func (s *testPointGetSuite) SetUpSuite(c *C) {
 46     testleak.BeforeTest()
 47     store, dom, err := newStoreWithBootstrap()
 48     c.Assert(err, IsNil)
 49     s.store = store
 50     s.dom = dom
 51     s.testData, err = testutil.LoadTestSuiteData("testdata", "point_get_plan")
 52     c.Assert(err, IsNil)
 53 }
```

Then, you can take `TestCBOPointGet` as an example. The test code is simple, it defines the data structure for storing input and outputs, run the input sql, compares the execution result with the expected result defined in `./planner/core/testdata/point_get_plan_out.json`:

```go
314 func (s *testPointGetSuite) TestCBOPointGet(c *C) {
315     tk := testkit.NewTestKit(c, s.store)
316     tk.MustExec("use test")
317     tk.MustExec("drop table if exists t")
318     tk.MustExec("create table t (a varchar(20), b int, c int, d int, primary key(a), unique key(b, c))")
319     tk.MustExec("insert into t values('1',4,4,1), ('2',3,3,2), ('3',2,2,3), ('4',1,1,4)")
320
321     var input []string
322     var output []struct {
323         SQL  string
324         Plan []string
325         Res  []string
326     }
327     s.testData.GetTestCases(c, &input, &output)
328     for i, sql := range input {
329         plan := tk.MustQuery("explain " + sql)
330         res := tk.MustQuery(sql)
331         s.testData.OnRecord(func() {
332             output[i].SQL = sql
333             output[i].Plan = s.testData.ConvertRowsToStrings(plan.Rows())
334             output[i].Res = s.testData.ConvertRowsToStrings(res.Rows())
335         })
336         plan.Check(testkit.Rows(output[i].Plan...))
337         res.Check(testkit.Rows(output[i].Res...))
338     }
339 }
```

in `./planner/core/testdata/point_get_plan_in.json`, it records the input sql for that test:
```json
  {
    "name": "TestCBOPointGet",
    "cases": [
      "select * from t where t.a in ('1','2','4') and t.a+1=2 order by t.a desc",
      "select b, c from t where t.b = 2 and t.c = 2 and t.b+1=3",
      "select * from t where t.a = '1' and t.b = 4",
      "select * from t where t.a in ('1','3') and t.d = 3",
      "select * from t t1 join t t2 on t1.a = t2.a where t1.a = '4' and (t2.b, t2.c) in ((1,1),(2,2))",
      "select * from t where (t.b, t.c) in ((2,2), (3,3), (4,4)) order by t.b, t.c"
    ]
  }
```

in `./planner/core/testdata/point_get_plan_out.json`, it records the expected output for that test:
```json
    "Cases": [
      {
        "SQL": "select * from t where t.a in ('1','2','4') and t.a+1=2 order by t.a desc",
        "Plan": [
          "Selection_12 2.40 root eq(plus(cast(test.t.a), 1), 2)",
          "└─Batch_Point_Get_11 2.40 root table:t, index:a, keep order:true, desc:true"
        ],
        "Res": [
          "1 4 4 1"
        ]
      },
      {
        "SQL": "select b, c from t where t.b = 2 and t.c = 2 and t.b+1=3",
        "Plan": [
          "Selection_6 0.80 root eq(plus(test.t.b, 1), 3)",
          "└─Point_Get_5 1.00 root table:t, index:b c"
        ],
        "Res": [
          "2 2"
        ]
      },
	...
}
```

You can generate expected result in `planner/core/testdata/point_get_plan_out.json` with a command line:

```
cd planner/core
go test -record -check.f=TestCBOPointGet
```

## Score

* 50

## Mentor(s)

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang Unittest

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

### PR DESCRIPTION
**Pull request by piotrrzysko**
Signed-off-by: Piotr Rzysko <piotr.rzysko@gmail.com>

### What problem does this PR solve?

Issue Number: close #15549

### What is changed and how it works?

What's Changed: Splitted test data from test cases in  `planner/core/cbo_test.go`.

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Comment by piotrrzysko** [comment]
@eurekaka would you mind taking a look at this PR?

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]

**Comment by qw4990** [comment]
Sorry for our late reply. This PR seems good to me, but please resolve conflicts. @piotrrzysko

**Comment by piotrrzysko** [comment]
Thanks for the review. I resolved conflicts. 

/assign @qw4990

**Review by eurekaka — APPROVED** [review]
/lgtm

**Pull request merged**
