### PR TITLE
github: remove `needs-more-info` mechanism

### LINKED ISSUE #32076: Disable `needs-more-info` mechanism for cherry-pick
## Enhancement

After https://github.com/pingcap/community/pull/625, new cherry-pick mechanism is in use and the former `needs-more-info` is of little use.

### PR DESCRIPTION
**Pull request by zhangyangyu**
### What problem does this PR solve?

Issue Number: close #32076 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by jebter — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
/merge

@zhangyangyu Please remember remove the unused label also.

**Comment by zhangyangyu** [comment]
> Please remember remove the unused label also.

Definitely. I've consulted @jebter and ensure the label could be safely removed.

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
