### PR TITLE
tikv: add size limit to batch get cache (#21015)

### LINKED ISSUE #19560: Unbounded memory usage of `BatchGet`'s cache
## Bug Report

The internal cache used by `BatchGet` need a size limit, it is OK to randomly discard some entry in it.

### 1. Minimal reproduce step (Required)
Start a transaction, do a lot of batch get.

### 2. What did you expect to see? (Required)
Low memory usage.

### 3. What did you see instead (Required)
Unbounded memory usage.

图片

### 4. What is your TiDB version? (Required)
v4.0, master

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21015 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #19560 

The internal cache used by `BatchGet` need a size limit, it is OK to randomly discard some entry in it.

### What is changed and how it works?
Add a size limit which equals to default `TxnTotalSizeLimit`. We can delete some entry from it randomly when the limit is exceeded.

### Release note 

- No release note.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Please resolve conflicts

**Review by jackysp — COMMENTED** [review]
LGTM

**Comment by jackysp** [comment]
PTAL @tiancaiamao @lysu @cfzjywxk

**Comment by cfzjywxk** [comment]
LGTM

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
