### PR TITLE
driver: convert ErrQueryInterrupted to actual error types

### PR DESCRIPTION
**Pull request by ekexium**
### What problem does this PR solve?

Issue Number: ref #49643

Problem Summary:

When a kill signal is sent to client, and client interrupts. The error returned is a ErrQueryInterrupted. TiDB needs to convert it into concrete types.

### Check List

Tests 

- [x] Unit test TestIndexJoin31494 as described in https://github.com/pingcap/tidb/pull/50465#issuecomment-1895301809
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zyguan — APPROVED** [review]
LGTM, https://github.com/tikv/client-go/pull/1124 need be merged firstly.

**Review by zyguan — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
