### PR TITLE
*: add tests/globalkilltest/go.sum file into git to remove noise

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs <chen.two.cs@gmail.com>

### What problem does this PR solve?

After I run `make test`, a new file `tests/globalkilltest/go.sum` will appear. This PR just add this file into git.

```shell
▶ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        tests/globalkilltest/go.sum

nothing added to commit but untracked files present (use "git add" to track)

```

### What is changed and how it works?

N/A

### Related changes

- N/A

### Check List 

Tests 

- No code

Side effects

- N/A

### Release note 

- N/A

### CODE REVIEW

**Review by AilinKid — COMMENTED** [review]
may go mod tidy for it

**Review by wjhuang2016 — APPROVED** [review]

**Comment by crazycs520** [comment]
> may `go mod tidy` for it

`go mod tidy` has been executed.

**Review by AilinKid — COMMENTED** [review]
/lgtm

**Pull request merged**
