### PR TITLE
Lightning: add retry if transaction failed while fetching task metas

### PR DESCRIPTION
**Pull request by mittalrishabh**
### What problem does this PR solve?

Issue Number: #53042

Problem Summary:
The transaction may encounter an error message stating "Error 1205: Lock wait timeout exceeded; try restarting transaction". This error can cause the import job to fail. The import job does not always start from the checkpoint, as it depends on the stage at which the failure occurred. If the transaction fails after the import/ingestion is completed, the job will not start from the checkpoint. As a result, the entire bulk load job needs to be restarted, which is a costly operation and can potentially violate our SLOs.
### What changed and how does it work?
Add retry with back off if transaction fails. It is going to retry up to 5 times with maxbackoff of 30 seconds and baseline backoff of 1 second.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by guoshouyan** [comment]
Hi, I check the issue @mittalrishabh is reporting, I think we already have a retry mechanism [here](https://github.com/pingcap/tidb/blob/master/lightning/pkg/importer/meta_manager.go#L666), all we need to do is to add the `ErrLockWaitTimeout` to [here](https://github.com/pingcap/tidb/blob/master/pkg/lightning/common/retry.go#L126) so the error can be retried. What do you think @lance6716

**Comment by lance6716** [comment]
> Hi, I check the issue @mittalrishabh is reporting, I think we already have a retry mechanism [here](https://github.com/pingcap/tidb/blob/master/lightning/pkg/importer/meta_manager.go#L666), all we need to do is to add the `ErrLockWaitTimeout` to [here](https://github.com/pingcap/tidb/blob/master/pkg/lightning/common/retry.go#L126) so the error can be retried. What do you think @lance6716

Yes I think make `ErrLockWaitTimeout` a retryable error is easier.

**Comment by lance6716** [comment]
replaced by https://github.com/pingcap/tidb/pull/55670

**Pull request closed without merging**
