### PR TITLE
mocktikv: move split test into mockstore

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?
Split test involves a lot SQL related dependency.

Part of https://github.com/pingcap/tidb/issues/22513

### What is changed and how it works?
What's Changed:
- move it out of store/tikv.

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]

**Review by Yisaer — COMMENTED** [review]
/lgtm

**Review by Yisaer — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by youjiali1995 — APPROVED** [review]
/lgtm

**Pull request merged**
