### PR TITLE
br: add more information in the error when user starts another restore task but doesn't clean the cluster

### LINKED ISSUE #44160: br: add more information in the error when user starts another restore task and doesn't clean the cluster
## Enhancement
before:
```
Detail BR log in /tmp/br.log.2023-05-25T11.34.52+0800 
Error: databases ddl_test existed in restored cluster, please drop them before execute PiTR: [BR:Restore:ErrDatabasesAlreadyExisted]databases already existed in restored cluster
```
after
```
Detail BR log in /tmp/br.log.2023-05-25T11.37.13+0800 
Error: The current restore task is regarded as a new task, last task info: [start-ts=441462819686449156] [restored-ts=441485796493230080] [skip-snapshot-restore=true]. If you ensure that no changes have been made to the cluster since the last execution, you can adjust the `start-ts` or `restored-ts` to continue with the previous execution. Otherwise, if you want to restore from scratch, please clean the cluster at first: databases ddl_test existed in restored cluster, please drop them before execute PiTR: [BR:Restore:ErrDatabasesAlreadyExisted]databases already existed in restored cluster
```

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #44160 

Problem Summary:
when users start another restore task but don't clean the cluster, the error information make them confused.
### What is changed and how it works?
add more information in the error when user starts another restore task and doesn't clean the cluster
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

before:
```
Detail BR log in /tmp/br.log.2023-05-25T11.34.52+0800 
Error: databases ddl_test existed in restored cluster, please drop them before execute PiTR: [BR:Restore:ErrDatabasesAlreadyExisted]databases already existed in restored cluster
```
after
```
Detail BR log in /tmp/br.log.2023-05-25T11.37.13+0800 
Error: The current restore task is regarded as a new task, last task info: [start-ts=441462819686449156] [restored-ts=441485796493230080] [skip-snapshot-restore=true]. If you ensure that no changes have been made to the cluster since the last execution, you can adjust the `start-ts` or `restored-ts` to continue with the previous execution. Otherwise, if you want to restore from scratch, please clean the cluster at first: databases ddl_test existed in restored cluster, please drop them before execute PiTR: [BR:Restore:ErrDatabasesAlreadyExisted]databases already existed in restored cluster
```

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by lance6716** [comment]
I think PM should check the message returned to user and give one LGTM @Leavrth

**Review by benmaoer — APPROVED** [review]
LGTM

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
