### PR TITLE
Added link to TiDB community Slack

### PR DESCRIPTION
**Pull request by ceohockey60**
Added link to TiDB community Slack channel

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Comment by ceohockey60** [comment]
PTAL @morgo @kolbe

**Comment by morgo** [comment]
@ceohockey60 just to confirm, this link doesn't depend on any infrastructure that may need to change etc?

**Comment by kolbe** [comment]
LGTM!

@morgo this is a URL that forwards to a link hosted by Slack. It's different than the thing I'd set up. I think hosting our own little invite tool might be a good idea in the future, but this lets us get started really quickly w/o needing to find a place to host the invite app. We can change where the URL goes later if we change course.

**Comment by kennytm** [comment]
/run-integration-common-test

(just a test)

**Pull request merged**
