### PR TITLE
ddl:  modify default unique index name

### LINKED ISSUE #39080: The name of the generated unique key is not consistent with mysql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE `Test` (
    `id` INTEGER PRIMARY KEY,
    `authorId` INTEGER AUTO_INCREMENT UNIQUE
);
```

### 2. What did you expect to see? (Required)

The unique key name generated by MySQL is `authorId`.

```deff
MySQL root@127.0.0.1:test2> show create table `Test2`\G
***************************[ 1. row ]***************************
Table        | Test2
Create Table | CREATE TABLE `Test2` (
  `id` int(11) NOT NULL,
  `authorId` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE KEY `authorId` (`authorId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```

### 3. What did you see instead (Required)

The unique key name generated by TiDB is `authorid`.

```
metadata_for_mysql_should_work> show create table `Test`\G
***************************[ 1. row ]***************************
Table        | Test
Create Table | CREATE TABLE `Test` (
  `id` int(11) NOT NULL,
  `authorId` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `authorid` (`authorId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
1 row in set
Time: 0.003s
```

### 4. What is your TiDB version? (Required)

```
metadata_for_mysql_should_work> select tidb_version()\G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v6.3.0
Edition: Community
Git Commit Hash: ecd67531f1721d3e49eb15a202ac7c0ae02291ec
Git Branch: heads/refs/tags/v6.3.0
UTC Build Time: 2022-09-23 14:21:08
GoVersion: go1.19.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
1 row in set
Time: 0.002s
```

### PR DESCRIPTION
**Pull request by wxbty**
### What problem does this PR solve?

Make the default name of the unique index consistent with mysql

Issue Number: close #39080 

Problem Summary:

### Check List

Tests 

- [ ] Unit test  TestIssue39080
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
```
run test [alter_table_PK] err: sql:SHOW INDEX FROM t1;: failed to run query
"SHOW INDEX FROM t1;"
 around line 52,
we need(340):
SHOW INDEX FROM t1;
Table	Non_unique	Key_name	Seq_in_index	Column_name	Collation	Cardinality	Sub_part	Packed	Null	Index_type	CommentIndex_comment	Visible	Expression	Clustered
t1	0	PRIMARY	1	Host	A	0	NULL	NULL		BTREE			YES	NULL	NO
t1	0	PRIMARY	2	User	A	0	NULL	NULL		BTREE			YES	NULL	NO
t1	1	host_2	1	Host	A	0	NULL	NULL		BTREE			YES	NULL	NO

but got(340):
SHOW INDEX FROM t1;
Table	Non_unique	Key_name	Seq_in_index	Column_name	Collation	Cardinality	Sub_part	Packed	Null	Index_type	CommentIndex_comment	Visible	Expression	Clustered
t1	0	PRIMARY	1	Host	A	0	NULL	NULL		BTREE			YES	NULL	NO
t1	0	PRIMARY	2	User	A	0	NULL	NULL		BTREE			YES	NULL	NO
t1	1	Host_2	1	Host	A	0	NULL	NULL		BTREE			YES	NULL	NO
```

one of our internal test is failed, PTAL @xhebox

**Comment by xhebox** [comment]
> ```
> run test [alter_table_PK] err: sql:SHOW INDEX FROM t1;: failed to run query
> "SHOW INDEX FROM t1;"
>  around line 52,
> we need(340):
> SHOW INDEX FROM t1;
> Table	Non_unique	Key_name	Seq_in_index	Column_name	Collation	Cardinality	Sub_part	Packed	Null	Index_type	CommentIndex_comment	Visible	Expression	Clustered
> t1	0	PRIMARY	1	Host	A	0	NULL	NULL		BTREE			YES	NULL	NO
> t1	0	PRIMARY	2	User	A	0	NULL	NULL		BTREE			YES	NULL	NO
> t1	1	host_2	1	Host	A	0	NULL	NULL		BTREE			YES	NULL	NO
> 
> but got(340):
> SHOW INDEX FROM t1;
> Table	Non_unique	Key_name	Seq_in_index	Column_name	Collation	Cardinality	Sub_part	Packed	Null	Index_type	CommentIndex_comment	Visible	Expression	Clustered
> t1	0	PRIMARY	1	Host	A	0	NULL	NULL		BTREE			YES	NULL	NO
> t1	0	PRIMARY	2	User	A	0	NULL	NULL		BTREE			YES	NULL	NO
> t1	1	Host_2	1	Host	A	0	NULL	NULL		BTREE			YES	NULL	NO
> ```
> 
> one of our internal test is failed, PTAL @xhebox

Okay... Let me fix it.

**Pull request merged**
