### PR TITLE
sessionctx: remove query cache

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve? 

This removes query cache variables https://github.com/pingcap/tidb/issues/9156

It is important to assist a user debugging, since they might "enable query cache in TiDB", and not be able to explain why query performance has not improved.  They might falsely believe it works.

MySQL 8.0 removes query cache, and it should be quite safe to remove these variables from TiDB without a compatibility mode.

### What is changed and how it works?

The unused sysvars are removed.

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)

Code changes

 - Has exported variable/fields change

Side effects

 - Breaking backward compatibility (for strange apps.  Not expected to cause issues.)

Related changes

 - Need to be included in the release note (only needs minor mention: improved compatibility with 8.0).

### CODE REVIEW

**Comment by morgo** [comment]
@jackysp PTAL

**Comment by morgo** [comment]
One of the tidb regression tests requires the server to identify as > 8.0, otherwise it complains that query cache doesn't exist.

**Comment by morgo** [comment]
I will add DNM until we merge https://github.com/pingcap/parser/pull/207 or update the test.

**Comment by jackysp** [comment]
I'll update the test cases. It seems to need a lot of work.

**Comment by zz-jason** [comment]
@jackysp Is there someone working on https://github.com/pingcap/tidb/issues/9141?

**Comment by jackysp** [comment]
No one is working on #9141 now, @zz-jason

**Comment by zz-jason** [comment]
How about closing this PR and repoen it when https://github.com/pingcap/tidb/issues/9141 is fixed?

**Comment by jackysp** [comment]
OK!

**Pull request closed without merging**
