### PR TITLE
expression/expression: add pushdown functions

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tics/issues/2334

Problem Summary: add pushdown functions

### What is changed and how it works?

What's Changed: add ascii, coalesce, length, position, trim pushdown functions

### Check List 

Tests 

- [x] Unit test
- [x] Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by zanmato1984** [comment]
Part of https://github.com/pingcap/tics/issues/2424

**Review by zanmato1984 — APPROVED** [review]
LGTM

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
