### PR TITLE
expression: implement least/greatest for string function pushdown 

### LINKED ISSUE #41189: Implement least/greatest for string function push down to TiFlash
## Enhancement
Support least/greatest function for string type push down to TiFlash
ref https://github.com/pingcap/tiflash/issues/6660

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: close #41189 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by LittleFall — APPROVED** [review]

**Review by SeaRise — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Comment by hawkingrei** [comment]
/hold

CI is too busy.

**Pull request merged**
