### PR TITLE
ddl, store: move the ddl dependency from tikv pkg.

### PR DESCRIPTION
**Pull request by hanfei1991**
create a ddl/util package to abstract some delete range interface.

### CODE REVIEW

**Comment by coocood** [comment]
How about move `delete_range.go` and `gc_worker.go` out of `tikv` package?

**Comment by shenli** [comment]
LGTM

**Comment by coocood** [comment]
Maybe `sqlexec` is a better package to move?
Delete range itself is not ddl operation.

**Comment by shenli** [comment]
@coocood This will introduce too many dependency for the `sqlexec` package.

**Pull request merged**
