### PR TITLE
server: Fix EOF handling in prepared statements

### LINKED ISSUE #36937: server: hanged cursor fetch for the prepared statement in JDBC connectors
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

The following code:

```
  import java.sql.Date;
  import java.sql.Time;
  import java.sql.Timestamp;
  import java.sql.ResultSet;
  import java.sql.SQLException;
  import java.math.BigDecimal;
  import java.lang.*;

  class TestJDBC {
      public static void test(String url) throws Exception {
          Connection conn = DriverManager.getConnection(url);
          DatabaseMetaData meta = conn.getMetaData();
          System.out.println("URL:" + url);
          System.out.println("Driver version: " + meta.getDriverVersion());
          System.out.println("Server version: " + meta.getDatabaseProductVersion());

          Statement s = conn.createStatement();
          s.executeUpdate("DROP TABLE IF EXISTS testRowFetch");
          s.executeUpdate("CREATE TABLE testRowFetch(field1 int)");
          s.executeUpdate("INSERT INTO testRowFetch VALUES (1)");

          Connection fetchConn = null;
          try {
              fetchConn = DriverManager.getConnection(url + "&useCursorFetch=true");
              PreparedStatement fetchStmt = fetchConn.prepareStatement("SELECT field1 FROM testRowFetch WHERE field1=1");
              fetchStmt.setFetchSize(10);
              ResultSet rs = fetchStmt.executeQuery();
          } finally {
              if (fetchConn != null) {
                  fetchConn.close();
              }
          }
      }

     public static void main(String[] args) throws Exception {
          System.setProperty( "oracle.jdbc.Trace", Boolean.TRUE.toString() );
          Class.forName("com.mysql.jdbc.Driver").newInstance();
          test("jdbc:mysql://localhost:4000/test?user=root&password=");
      }
  }
```

### 2. What did you expect to see? (Required)
The code runs successfully.

### 3. What did you see instead (Required)
It hangs at:
```
ResultSet rs = fetchStmt.executeQuery();
```
### 4. What is your TiDB version? (Required)
Latest master code: 42f594144293c5983ede20be01aa120ba95fb65b

```
Driver version: mysql-connector-java-8.0.29 (Revision: dd61577595edad45c398af508cf91ad26fc4144f)
Server version: 5.7.25-TiDB-v6.2.0-alpha-632-g42f594144
```
It is confirmed that this is caused by #34753

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #36937

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below): verified by the post-commit CI system and #36937
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by dveeden** [comment]
`writeColumnInfo()` is writing the EOF if mysql.ClientDeprecateEOF is not used and not writing anything if that flag is set. Simply switching the type of packet here doesn't work as often there should not be an OK at all if the flag is set.

**Comment by dveeden** [comment]
PTAL @bb7133

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]

**Pull request merged**
