### PR TITLE
stmts: Fix Issue #345

### PR DESCRIPTION
**Pull request by shenli**
When update multiple tables, extract target columns and corresponding
assignment list for each table.
See: https://github.com/pingcap/tidb/issues/345

### CODE REVIEW

**Comment by siddontang** [comment]
Maybe we should check alias name first here https://github.com/pingcap/tidb/blob/shenli/issue-345/stmt/stmts/update.go#L95

how about the result for following case? 
```
mysql> create table t1 (c int);
Query OK, 0 rows affected (0.02 sec)

mysql> create table t2 (c int);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t1 values (1);
Query OK, 1 row affected (0.02 sec)

mysql> insert into t2 values (2);
Query OK, 1 row affected (0.01 sec)

mysql> update t1 as a, t2 as t1 set a.c = 2, t1.c = 1;
Query OK, 2 rows affected (0.02 sec)
Rows matched: 2  Changed: 2  Warnings: 0

mysql> select * from t1;
+------+
| c    |
+------+
|    2 |
+------+
1 row in set (0.01 sec)

mysql> select * from t2;
+------+
| c    |
+------+
|    1 |
+------+
1 row in set (0.00 sec)
```

**Comment by shenli** [comment]
PTAL @siddontang

**Comment by siddontang** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
