### PR TITLE
local: split job again when dynamic region

### LINKED ISSUE #42484: lightning performance regression when TiKV use dynamic region
## Enhancement
generate ~10GB data, start a tiup playground and run a import. If the playground enables dymanic region(partioned-raft-kv), the time cost is 4m10s. If the playground uses default configuration, the time cost is 1m49s

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #42484

Problem Summary:

### What is changed and how it works?

When the estimated size of a job is larger than 2*96MB, try to split it into multiple jobs whose size is around 96MB

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

The 10GB data import task costs same time as TiKV turn off partioned-raft-kv

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by gozssky** [comment]
Does performance improve after split job again?

**Comment by lance6716** [comment]
> Does performance improve after split job again?

My test case is quite simple: tiup playground (1 replica) with 10GB data, so performance is not improved. Further DDL test should be able to cover disk quota & TiKV side compaction, region isolation, etc

**Comment by gozssky** [comment]
> > Does performance improve after split job again?
> 
> My test case is quite simple: tiup playground (1 replica) with 10GB data, so performance is not improved. Further DDL test should be able to cover disk quota & TiKV side compaction, region isolation, etc

So what's the benefit of this PR?

**Comment by lance6716** [comment]
> > > Does performance improve after split job again?
> > 
> > 
> > My test case is quite simple: tiup playground (1 replica) with 10GB data, so performance is not improved. Further DDL test should be able to cover disk quota & TiKV side compaction, region isolation, etc
> 
> So what's the benefit of this PR?

Sorry I think you mean "after split job again, the multi-rocksdb version has higher performance than single-rocksdb version"

This PR fix https://github.com/pingcap/tidb/issues/42484

**Comment by gozssky** [comment]
After this PR, I understand that multi-rocksdb version should have no performance regression compared to the single rocksdb version, right?

**Comment by lance6716** [comment]
> After this PR, I understand that multi-rocksdb version should have no performance regression compared to the single rocksdb version, right?

At least no performance regression. In future DDL add index tests we might find some performance improvement.

**Review by gozssky — APPROVED** [review]

**Review by glorv — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
/hold

need to check CI

**Comment by lance6716** [comment]
reason is the TiKV version checking is wrong

```
["TiKV version doesn't support duplicate resolution. The resolution algorithm will fall back to 'none'"]
```

**Pull request merged**
