### PR TITLE
planner: support push down broadcast cartesian join to TiFlash (#25049)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25049 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25106
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25106:release-5.0-d3de5479a06a
```

---

### What problem does this PR solve?

Issue Number: close pingcap/tics#1938 

Problem Summary:

Currently, TiFlash does not support cartesian join, so TiDB will not push down cartesian join to TiFlash.
### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

After pingcap/tics#2041 TiFlash will support cartesian join, so in TiDB, it will push down a broadcast cartesian join to TiFlash.
### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- support push down broadcast cartesian join to TiFlash

### CODE REVIEW

**Comment by bb7133** [comment]
@windtalker Please resolve the conflicts

**Review by hanfei1991 — APPROVED** [review]

**Review by fzhedu — APPROVED** [review]
/LGTM

**Pull request merged**
