### PR TITLE
util/testkit/testkit.go: fix typo

### PR DESCRIPTION
**Pull request by eddievim**
What problem does this PR solve?

Problem Summary:

Fix typo in `util/testkit/testkit.go:263` `containGloabl` -> `containGlobal`

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by kennytm** [comment]
CLA still not passed https://github.com/pingcap/tidb/pull/30638#issuecomment-991393537.

**Pull request merged**
