### PR TITLE
txn: bump up dependency of client-go to enable pessimistic lock region rollback

### LINKED ISSUE #50731: txn: lock wait should not consider expired pessimistic locks
## Enhancement
If a pessimistic transaction encounters residual pessimistic locks, it might wait for each lock until the lock timeout expires before attempting to resolve it. Currently, we haven't checked the time-to-live (TTL) of the lock or whether the request carries expiration information.
The https://docs.pingcap.com/tidb/stable/tikv-configuration-file#wait-for-lock-timeout is `1s` by default, which means the lock resolve would happen only after the `1s` interval. In cases that the transaction coordinator for example the tidb-server crashes, resolving and cleaning the left locks may take a lot of time nearly one lock per `1s`.

An improvement in this case is to check the lock TTL first before starts to wait for the lock. If the lock already expires, it's not needed to wait for the lock release and start resolving immediately.

## Design
Introduce a scan phase for pessimistic rollback in TiKV, where for pessimistic rollback requests without a specified key, scan all locks associated with the corresponding transaction and perform pessimistic rollback. The kv client can send pessimistic rollback requests without specifying a key. 

Related issue: https://github.com/tikv/tikv/issues/16158

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve?

Issue Number: close #50731

Problem Summary: 
Introduce pessimistic lock region rollback to speed up expired lock cleaning. The tikv related issue is https://github.com/tikv/tikv/issues/16158.

From the debugging test, 
```
CREATE TABLE t1 (id BIGINT NOT NULL PRIMARY KEY auto_increment, pad1 BLOB, pad2 BLOB, pad3 BLOB, int_col INT NOT NULL DEFAULT 0);
INSERT INTO t1 SELECT NULL, RANDOM_BYTES(1024), RANDOM_BYTES(1024), RANDOM_BYTES(1024), 0 FROM dual;
INSERT INTO t1 SELECT NULL, RANDOM_BYTES(1024), RANDOM_BYTES(1024), RANDOM_BYTES(1024), 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT NULL, RANDOM_BYTES(1024), RANDOM_BYTES(1024), RANDOM_BYTES(1024), 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT NULL, RANDOM_BYTES(1024), RANDOM_BYTES(1024), RANDOM_BYTES(1024), 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
-- session 1
begin;
update t1 set t1.pad1 = RANDOM_BYTES(1024) where id < 3000;  
-- kill tidb-server, the pessimistic locks are left
-- reconnect to the tidb-server and execute the same statement again
begin
update t1 set t1.pad1 = RANDOM_BYTES(1024) where id < 3000; 
```

The second `update` execution duration after reconnect:

|vanilla  |  region pessimistic rollback |
| ------------- | ------------- |
| 1 min 5.12 sec  | 10.37 sec  |

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [x] Performance regression: Consumes more CPU
- [x] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by cfzjywxk** [comment]
Why the CI could not download the latest client-go repo..

**Review by MyonKeminta — APPROVED** [review]

**Pull request merged**
