### PR TITLE
ddl: validate fsp for datetime/timestamp if they are used as defaultvalue of datetime/timestamp columns

### PR DESCRIPTION
**Pull request by spongedu**
### What problem does this PR solve? 
As is described in [MySQL Reference](https://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html) and https://github.com/pingcap/parser/issues/186:
```
If a TIMESTAMP or DATETIME column definition includes an explicit fractional seconds precision value anywhere, the same value must be used throughout the column definition.
```
> mysql> create table tbl_so_q23671222_1( ts timestamp(3) default now() );
> ERROR 1067 (42000): Invalid default value for 'ts'
> mysql> create table tbl_so_q23671222_1( ts timestamp(3) default now(3) );
> Query OK, 0 rows affected (0.59 sec)
> mysql> create table tbl_so_q23671222_2( ts timestamp(3) default current_timestamp );
> ERROR 1067 (42000): Invalid default value for 'ts'
> mysql> create table tbl_so_q23671222_2( ts timestamp(3) default current_timestamp(3) );
> Query OK, 0 rows affected (0.38 sec)

These checks are missing now in TiDB. This PR fixes this.

### What is changed and how it works?
Add related check in `ddl_api.go`

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

This pr depends on https://github.com/pingcap/parser/pull/211

### CODE REVIEW

**Comment by tiancaiamao** [comment]
CI fails @spongedu

**Comment by winkyao** [comment]
@spongedu please fix ci.

**Comment by spongedu** [comment]
@winkyao @tiancaiamao  PTAL :) It seems that the test cases need update.

**Comment by tiancaiamao** [comment]
LGTM

**Comment by tiancaiamao** [comment]
@zimulala

**Comment by spongedu** [comment]
conflicts resolved. PTAL :) ~ @zimulala @tiancaiamao

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
