### PR TITLE
*: update errcheck and remove vendor in release 2.0 (#9114)

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve? 
Cherry-pick #9114 to release 2.0.

### CODE REVIEW

**Comment by jackysp** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by zyguan** [comment]
/run-all-tests tidb-test=pr/729 tikv=release-2.0 pd=release-2.0

**Comment by zyguan** [comment]
/run-all-tests tidb-test=pr/729 tikv=release-2.0 pd=release-2.0

**Comment by tiancaiamao** [comment]
Should we generate the `parser.go` and add it to the repo? @jackysp

**Comment by zyguan** [comment]
/run-all-tests tidb-test=pr/729 tikv=release-2.0 pd=release-2.0

**Comment by jackysp** [comment]
I think it is better to use the same way as branch 2.1 and master if possible @tiancaiamao . 
@zyguan is working on it, and it seems be solved.

**Comment by zyguan** [comment]
@jackysp @tiancaiamao We indeed use the same jenkins pipeline to build & test master, release-2.1 as well as release-2.0. However in release-2.0, parser.go should be generated manually, which is not friendly to go module. The current workaround is to patch go.mod in build.sh or test.sh.

**Comment by jackysp** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
