### PR TITLE
statistics: fix the correlation estimation for version 2

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Problem Summary:

Correlation calculation is wrong in version 2. Sometimes the analyze may report error directly.

### What is changed and how it works?

What's Changed:

Calculate it as it should be and add tests.

### Check List 

Tests 

- Unit test

### Release note 

- `No release note`

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
/LGTM

**Review by time-and-fate — COMMENTED** [review]
/lgtm

**Comment by hi-rustin** [comment]
@ti-chi-bot help me

**Comment by hi-rustin** [comment]
@ti-chi-bot Thanks! God bless our CI system.

**Pull request merged**
