### PR TITLE
bindinfo: use new sql apis (#22653)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #22653 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/22733
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/22733:release-4.0-745729fd9182
```

---

### What problem does this PR solve?

Part of pingcap/tidb-test#1152

### What is changed and how it works?

What's Changed:

This updates the bindinfo package to use the new SQL APIs.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- None

### Release note 

- No release note

### CODE REVIEW

**Review by AilinKid — COMMENTED** [review]
PTAL @morgo

**Comment by morgo** [comment]
This depends on https://github.com/pingcap/tidb/pull/22548 merging first

**Comment by morgo** [comment]
This is now ready for review

**Comment by morgo** [comment]
@tiancaiamao @xhebox do you mind if I ask for your LGTM again? I've changed the label.

**Review by xhebox — APPROVED** [review]
/lgtm

**Pull request merged**
