### PR TITLE
server: Combined fix for authentication issues

### LINKED ISSUE #29709: Auth failed for `u1@127.%`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

This is a bug introduced by https://github.com/pingcap/tidb/pull/24991.

### 1. Minimal reproduce step (Required)

```
mysql -h127.1 -uroot -P4000
mysql> create user u1@'127.%';
Query OK, 0 rows affected (0.00 sec)
```

```
mysql -h127.1 -uu1 -P4000
ERROR 2000 (HY000): Unknown MySQL error
```

### 2. What did you expect to see? (Required)

In MySQL and older TiDB versions, `u1` can log in as usual.

### 3. What did you see instead (Required)

```
mysql -h127.1 -uu1 -P4000
ERROR 2000 (HY000): Unknown MySQL error
```

In TiDB log:
```
[2021/11/12 09:58:37.805 +08:00] [WARN] [conn.go:712] ["failed to check the user authplugin"] [conn=5] [error="Failed to get user record"]
[2021/11/12 09:58:37.806 +08:00] [ERROR] [conn.go:757] ["authSha packet read failed"] [conn=5] [error=EOF]
[2021/11/12 09:58:37.806 +08:00] [ERROR] [terror.go:307] ["encountered error"] [error=EOF] 
```

### 4. What is your TiDB version? (Required)

```
Release Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### LINKED ISSUE #29725: tidb returns 'Unknown auth plugin' when some old clients to connect
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a tidb cluster
2. use mysql 5.1 client to connect the tidb
3. the client Connect success to v5.2.2, but can't connect to v5.3.0

related  #27855 #27931

### 2. What did you expect to see? (Required)

```sql
╭─tidb@localhost ~/tiup-cluster-config
╰─$ mysql --version                                                                                                                                                                    1 ↵
mysql  Ver 14.14 Distrib 5.1.73, for pc-linux-gnu (i686) using readline 5.1
╭─tidb@localhost ~/tiup-cluster-config
╰─$ mysql -u root -h 172.16.4.131 -P 4100
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 7
Server version: 5.7.25-TiDB-v5.2.2 TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible

Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```
### 3. What did you see instead (Required)
```sql
╭─tidb@localhost ~/pingcap/tidb ‹master*›
╰─$ mysql --version                                                                                                                                                                    1 ↵
mysql  Ver 14.14 Distrib 5.1.73, for pc-linux-gnu (i686) using readline 5.1
╭─tidb@localhost ~/pingcap/tidb ‹master*›
╰─$ mysql -u root -h 172.16.4.131 -P 4100
ERROR 1105 (HY000): Unknown auth plugin
```
### 4. What is your TiDB version? (Required)
release-5.3(bdc9987370d6d393cb8)

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number:

- close #29725

Problem Summary:

Combined fix for multiple authentication issues

Contains fixes from:

- #29732

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

```release-note
- Compatibility with MySQL 5.1 clients has been improved
```

### CODE REVIEW

**Comment by dveeden** [comment]
Tested with https://github.com/dveeden/tidb_client_test 

```
[dvaneeden@dve-carbon tidb_client_test]$ ./tidb_client_test 
TiDB Client Test
Connected to:
	Release Version: v5.4.0-alpha-129-ga59d6cfed
	Edition: Community
	Git Commit Hash: a59d6cfeddb25011a17813949cb5c9f004c6266c
	Git Branch: auth_5_3
	UTC Build Time: 2021-11-16 07:49:13
	GoVersion: go1.16.8
	Race Enabled: false
	TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
	Check Table Before Drop: false
Clients:
	/home/dvaneeden/opt/mysql/5.1.73/bin/mysql
	/home/dvaneeden/opt/mysql/5.7.31/bin/mysql
	/home/dvaneeden/opt/mysql/5.7.36/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.22/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.25/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.26/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.27/bin/mysql
-----------------------------------------------
Testing with mysql_native_password as default authentication plugin
Testing /home/dvaneeden/opt/mysql/5.1.73/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/5.7.31/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/5.7.36/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.22/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.25/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.26/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.27/bin/mysql: success=8, failures=0
Testing with caching_sha2_password as default authentication plugin
Testing /home/dvaneeden/opt/mysql/5.1.73/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/5.7.31/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/5.7.36/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.22/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.25/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.26/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.27/bin/mysql: success=8, failures=0
```

**Comment by bb7133** [comment]
1. Is it possible to add more unit test cases in `TestHandleAuthPlugin`?
2. It would be great if https://github.com/dveeden/tidb_client_test can be integrated into the current TiDB CI, /cc @zhouqiang-cl is it easy to do that?

**Comment by dveeden** [comment]
@bb7133 @djshow832 PTAL

**Comment by bb7133** [comment]
The test failed(https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/48027/pipeline):

```
[2021-11-25T01:52:54.320Z] --- FAIL: TestAuthPlugin2 (0.67s)
[2021-11-25T01:52:54.320Z] panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[2021-11-25T01:52:54.320Z] 	panic: runtime error: invalid memory address or nil pointer dereference
[2021-11-25T01:52:54.320Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x370395f]
[2021-11-25T01:52:54.320Z] 
[2021-11-25T01:52:54.320Z] goroutine 519 [running]:
[2021-11-25T01:52:54.320Z] testing.tRunner.func1.2(0x3a44d20, 0x5beb590)
[2021-11-25T01:52:54.320Z] 	/usr/local/go/src/testing/testing.go:1143 +0x332
[2021-11-25T01:52:54.320Z] testing.tRunner.func1(0xc000682f00)
[2021-11-25T01:52:54.320Z] 	/usr/local/go/src/testing/testing.go:1146 +0x4b6
[2021-11-25T01:52:54.320Z] panic(0x3a44d20, 0x5beb590)
[2021-11-25T01:52:54.320Z] 	/usr/local/go/src/runtime/panic.go:965 +0x1b9
[2021-11-25T01:52:54.320Z] github.com/pingcap/tidb/server.(*packetIO).readPacket(0xc065f25700, 0x44225a0, 0xc0000520a8, 0x0, 0x0, 0x0)
[2021-11-25T01:52:54.320Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/server/packetio.go:113 +0x37f
[2021-11-25T01:52:54.320Z] github.com/pingcap/tidb/server.(*clientConn).readPacket(...)
[2021-11-25T01:52:54.320Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/server/conn.go:392
[2021-11-25T01:52:54.320Z] github.com/pingcap/tidb/server.(*clientConn).authSwitchRequest(0xc192957e30, 0x44225a0, 0xc0000520a8, 0x3edb6cf, 0x15, 0xc11b9e4240, 0x8, 0xc068db79e0, 0x27, 0xc048330401)
[2021-11-25T01:52:54.320Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/server/conn.go:236 +0x806
[2021-11-25T01:52:54.320Z] github.com/pingcap/tidb/server.(*clientConn).checkAuthPlugin(0xc192957e30, 0x44225a0, 0xc0000520a8, 0xc192957dd8, 0xc000f39c00, 0x0, 0x0, 0xc19020f8c0, 0xc01ece4d80)
[2021-11-25T01:52:54.320Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/server/conn.go:883 +0x4af
[2021-11-25T01:52:54.321Z] github.com/pingcap/tidb/server.TestAuthPlugin2(0xc000682f00)
[2021-11-25T01:52:54.321Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/server/conn_test.go:1158 +0x57d
[2021-11-25T01:52:54.321Z] testing.tRunner(0xc000682f00, 0x3fd4cb8)
[2021-11-25T01:52:54.321Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef
[2021-11-25T01:52:54.321Z] created by testing.(*T).Run
[2021-11-25T01:52:54.321Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
```

**Comment by djshow832** [comment]
I'm confused. Does it need to be cherry-picked to release-5.3?
https://github.com/pingcap/tidb/pull/29808 is already merged to release-5.3 but it seems to only fix a part of the problem?

**Comment by dveeden** [comment]
[client_test_results.md](https://github.com/pingcap/tidb/files/7607275/client_test_results.md)

**Comment by dveeden** [comment]
|   | auth_5_3 |   | release-5.3 |   | master |  
-- | -- | -- | -- | -- | -- | -- | --
Default auth method | Client version | success | failure | success | failure | success | failure
mysql_native_password | 5.1.73 | 8 | 0 | 8 | 0 | 4 | 4
  | 5.7.31 | 8 | 0 | 6 | 2 | 6 | 2
  | 5.7.36 | 8 | 0 | 6 | 2 | 6 | 2
  | 8.0.22 | 8 | 0 | 6 | 2 | 6 | 2
  | 8.0.25 | 8 | 0 | 6 | 2 | 6 | 2
  | 8.0.26 | 8 | 0 | 6 | 2 | 6 | 2
  | 8.0.27 | 8 | 0 | 6 | 2 | 6 | 2
caching_sha2_password | 5.1.73 | 8 | 0 | 8 | 0 | 4 | 4
  | 5.7.31 | 8 | 0 | 6 | 2 | 6 | 2
  | 5.7.36 | 8 | 0 | 6 | 2 | 6 | 2
  | 8.0.22 | 8 | 0 | 6 | 2 | 6 | 2
  | 8.0.25 | 8 | 0 | 6 | 2 | 6 | 2
  | 8.0.26 | 8 | 0 | 6 | 2 | 6 | 2
  | 8.0.27 | 8 | 0 | 6 | 2 | 6 | 2

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by bb7133** [comment]
PTAL @djshow832 @morgo

**Review by djshow832 — APPROVED** [review]

**Pull request merged**
