### PR TITLE
expression: uncomment pushdown for JSONUnquote expression

### LINKED ISSUE #24415: Enable pushdown for json_unquote
## Feature Request

**Is your feature request related to a problem? Please describe:**

For some reason, https://github.com/pingcap/tidb/pull/13837/commits/721782d9c11f739b5b38901427803581634498ec "forbid json unquote push down".

There's no indication of *why* it was necessary to forbid this or whether there is any feasible fix for the issue. We should address this limitation so that json_unquote can be pushed down.

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve?

Issue Number: close #24415 

Problem Summary:

### What is changed and how it works?

This PR tries to open the pushdown of `JSONUnquote` expression, by uncommenting it in the 'pushdown list'.

### Related changes

- Related doc to change: https://github.com/pingcap/docs/pull/5564
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test(the "`idc-jenkins-ci-tidb/integration-copr-test`"): https://github.com/tikv/copr-test/blob/master/push-down-test/sql/randgen/9_json.sql

### Release note 

- Enable the pushdown of builtin function `json_unquote()` to TiKV.

### CODE REVIEW

**Comment by kolbe** [comment]
Presumably there's some reason this was forbidden at some point, some kind of compatibility issue that caused problems?

**Comment by guo-shaoge** [comment]
Looks like we should update tidbtest first to make the case pass.

**Review by guo-shaoge — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]

**Pull request merged**
