### PR TITLE
executor: add more cases about dynamic-mode with union/DML/subquery

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: related to #24150  

Problem Summary: executor: add more cases about dynamic-mode with union/DML/subquery

### Check List 

Tests 

- Unit test

### Release note 

- executor: add more cases about dynamic-mode with union/DML/subquery

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
This PR has the same content with https://github.com/pingcap/tidb/pull/24714.
Conflicts in https://github.com/pingcap/tidb/pull/24714 are hard to resolve, so I create a new PR.

**Review by rebelice — APPROVED** [review]
/lgtm

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
