### PR TITLE
executor: convert json numeric value to float64 in hash

### LINKED ISSUE #38049: got incorrect result while join JSON and DOUBLE column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE `t` (
  `id` int(11) NOT NULL,
  `a` bigint(20) DEFAULT NULL,
  `b` char(20) DEFAULT NULL,
  `c` datetime DEFAULT NULL,
  `d` double DEFAULT NULL,
  `e` json DEFAULT NULL,
  `f` decimal(40,6) DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `a` (`a`),
  KEY `b` (`b`),
  KEY `c` (`c`),
  KEY `d` (`d`),
  KEY `f` (`f`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
insert into t(id, a, b, c, d, e, f) values(0, 2010, '2010-01-01 01:01:00', '2010-01-01 01:01:00', 2010.000000, '2010', 2010.000000);
insert into t(id, a, b, c, d, e, f) values(1, 2011, '2011-01-01 01:01:00', '2011-01-01 01:01:00', 2011.000000, '2011', 2011.000000);
insert into t(id, a, b, c, d, e, f) values(2, 2012, '2012-01-01 01:01:00', '2012-01-01 01:01:00', 2012.000000, '2012', 2012.000000);
select /*+inl_hash_join(t2)*/ t1.id, t2.id from t t1 join t t2 on t1.e = t2.d;
```

### 2. What did you expect to see? (Required)
```sql
MySQL > select /*+inl_hash_join(t2)*/ t1.id, t2.id from t t1 join t t2 on t1.e = t2.d;
+----+----+
| id | id |
+----+----+
| 0  | 0  |
| 1  | 1  |
| 2  | 2  |
+----+----+
```
### 3. What did you see instead (Required)
```sql
MySQL root@127.0.0.1:TICASE_1293_IKXHYY> select /*+inl_hash_join(t2)*/ t1.id, t2.id from t t1 join t t2 on t1.e = t2.d;
+----+----+
| id | id |
+----+----+

0 rows in set
Time: 0.010s
MySQL root@127.0.0.1:TICASE_1293_IKXHYY> select t1.id, t2.id from t t1 join t t2 on t1.e = t2.d;
+----+----+
| id | id |
+----+----+

0 rows in set
Time: 0.009s

```
### 4. What is your TiDB version? (Required)
```sql
tidb_version() | Release Version: v6.3.0-alpha-296-g6a906f795-dirty
Edition: Community
Git Commit Hash: 6a906f795459700ef3ea8c1d464b4fe1192e5991
Git Branch: release-6.3
UTC Build Time: 2022-09-21 09:55:10
GoVersion: go1.19
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
```

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #38049 

Problem Summary:

Use a specific hash value for json in the count distinct and hash join.

### What is changed and how it works?

Use the existing json hash value function to generate the hash key.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
Fix the issue that json numeric value equal comparison is not correct in hash join and count
```

### CODE REVIEW

**Review by xiongjiwei — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
@YangKeao PTAL
···
=== RUN   TestHashChunkColumns

    codec_test.go:1296: 

        	Error Trace:	/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/processwrapper-sandbox/3562/execroot/__main__/bazel-out/k8-fastbuild/bin/util/codec/codec_test_/codec_test.runfiles/__main__/util/codec/codec_test.go:1296

        	Error:      	Not equal: 

        	            	expected: 0x8c3f2a85b9734184

        	            	actual  : 0xd9e9cfeda5ca56a1

        	Test:       	TestHashChunkColumns

···

**Comment by hawkingrei** [comment]
@xiongjiwei PTAL

···
/bazel-out/k8-fastbuild/bin/executor/aggfuncs/aggfuncs_test_/aggfuncs_test.runfiles/__main__/executor/aggfuncs/func_count_test.go:155
        	Error:      	Not equal: 
        	            	expected: 9
        	            	actual  : 8
        	Test:       	TestMemCount/count_14
···

**Pull request merged**
