### PR TITLE
server,infoschema,util: Implement session_account_connect_attrs P_S table

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: ref #44341

Problem Summary:

Similar to https://github.com/pingcap/tidb/pull/44340

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Add `performance_schema.session_account_connect_attrs` table
```

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by bb7133** [comment]
PTAL @tiancaiamao

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
