### PR TITLE
*: fix issue of cast string as time is incompatible with MySQL

### LINKED ISSUE #34539: cast string as time behaviour is incompatible with MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
SELECT cast("0000-00-00" as TIME);
```

Related: https://github.com/go-sql-driver/mysql/pull/1331

### 2. What did you expect to see? (Required)

In MySQL 8.0

```sql
>SELECT cast("0000-00-00" as TIME);
+----------------------------+
| cast("0000-00-00" as TIME) |
+----------------------------+
| 00:00:00                   |
+----------------------------+
```

### 3. What did you see instead (Required)

In TiDB

```sql
>SELECT cast("0000-00-00" as TIME);
+----------------------------+
| cast("0000-00-00" as TIME) |
+----------------------------+
| <null>                     |
+----------------------------+
```

### 4. What is your TiDB version? (Required)

```sql
>select tidb_version()\G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v6.1.0-alpha-360-gab26a287dc
Edition: Community
Git Commit Hash: ab26a287dcbe4186d327cfcaa74bf945db83a338
Git Branch: master
UTC Build Time: 2022-05-10 08:32:31
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Issue Number: close #34539

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Comment by hawkingrei** [comment]
@crazycs520 mysql-test never passes. so can you check it ?

**Pull request merged**
