### PR TITLE
plan: fix a bug of index reader.

### PR DESCRIPTION
**Pull request by winoros**
Schema of `IndexReader`'s copTask is not same as the above root task.
This will make index of column wrong.

~~~I'll try to add a simple test in later commit.~~~
test is added in integration test.

PTAL @hanfei1991 @lamxTyler @XuHuaiyu

### CODE REVIEW

**Comment by hanfei1991** [comment]
fix #4878

**Comment by winoros** [comment]
integration-common-test tidb-test=yiding/issue4878

**Comment by winoros** [comment]
integration-common-test tidb-test=yiding/issue4878

**Comment by winoros** [comment]
test is added in integration test.

**Comment by winoros** [comment]
integration-common-test tidb-test=yiding/issue4878

**Comment by zz-jason** [comment]
LGTM

**Pull request merged**
