### PR TITLE
session: migrate test-infra to testify for `session/session_fail_test.go`

### LINKED ISSUE #28327: migrate test-infra to testify for `session/session_fail_test.go`

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #28327

Problem Summary:
migrate test-infra to testify for `session/session_fail_test.go`

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
migrate test-infra to testify for `session/session_fail_test.go`
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @hawkingrei @tisonkun 
PTAL

**Review by tisonkun — APPROVED** [review]
Great work! Thanks for overcoming `withTikv` config :)

**Comment by tisonkun** [comment]
/cc @morgo @djshow832 

You may take a look to ensure that we don't make non-trivial changes here.

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
