### PR TITLE
expression: rewrite "HashCode()" for "Column"

### LINKED ISSUE #4438: projection elimination spends so mach time in `Column.HashCode()`
a simple query with aggregation functions, do `Optimize()` 1000000 times:

### PR DESCRIPTION
**Pull request by zz-jason**
fix #4438

```go
package expression

import (
    "testing"

    "github.com/pingcap/tidb/util/codec"
    "github.com/pingcap/tidb/util/types"
)

func BenchmarkHashCodeNew(b *testing.B) {
    c1, c2 := 12, 100

    hashcode := []byte{}
    for i := 0; i < b.N; i++ {
        hashcode = make([]byte, 0, 16)
        hashcode = codec.EncodeInt(hashcode, int64(c1))
        hashcode = codec.EncodeInt(hashcode, int64(c2))
    }
}

func BenchmarkHashCodeOrigin(b *testing.B) {
    c1, c2 := 12, 100

    hashcode := []byte{}
    for i := 0; i < b.N; i++ {
        hashcode = []byte{}
        hashcode, _ = codec.EncodeValue(hashcode, types.NewIntDatum(int64(c1)), types.NewIntDatum(int64(c2)))
    }
}
```

```sh
$go test -bench=. -run=BenchmarkHashCode
BenchmarkHashCodeNew-8          50000000                30.5 ns/op
BenchmarkHashCodeOrigin-8       20000000                94.8 ns/op
PASS
ok      github.com/pingcap/tidb/expression      3.588s
```

### CODE REVIEW

**Comment by zz-jason** [comment]
a simple test:
```go
package expression

import (
        "encoding/binary"
        "fmt"
        "time"

        . "github.com/pingcap/check"
        "github.com/pingcap/tidb/util/codec"
        "github.com/pingcap/tidb/util/testleak"
        "github.com/pingcap/tidb/util/types"
)

func (s *testEvaluatorSuite) TestColumnHashCode(c *C) {
        defer testleak.AfterTest(c)()

        a, b := 12, 100

        hashcode := []byte{}

        start := time.Now()
        for i, round := 0, 1000000; i < round; i++ {
                hashcode = make([]byte, 2*binary.MaxVarintLen64)
                size1 := binary.PutVarint(hashcode, int64(a))
                size2 := binary.PutVarint(hashcode[size1:], int64(b))
                hashcode = hashcode[:size1+size2]
        }
        fmt.Printf("%vns\n", time.Now().Sub(start).Nanoseconds())
        fmt.Printf("%s: len=%v\n", hashcode, len(hashcode))

        start = time.Now()
        for i, round := 0, 1000000; i < round; i++ {
                hashcode = []byte{}
                hashcode, _ = codec.EncodeValue(hashcode, types.NewIntDatum(int64(a)), types.NewIntDatum(int64(b)))
        }
        fmt.Printf("%vns\n", time.Now().Sub(start).Nanoseconds())
        fmt.Printf("%s: len=%v\n", hashcode, len(hashcode))
}
```

```sh
$go test -check.f TestColumnHashCode
45537712ns
: len=3
108007950ns
: len=5
```

**Comment by shenli** [comment]
LGTM

**Comment by coocood** [comment]
change the type of `Column.hashcode` from `[]byte` to `[16]byte` may further import the performance.

**Comment by coocood** [comment]
Never mind, the `HashCode` method check nil `hashcode`, use an array can not check nil.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
