### PR TITLE
session: migrate test-infra to testify for isolation_test.go

### LINKED ISSUE #28324: migrate test-infra to testify for `session/isolation_test.go`

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #28324

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
@hawkingrei I actually think this test should not run with `withTikv` setting. I tend to think of it accidentally inherits `testSessionSuiteBase` and here is a PR to simply migrate tests.

**Review by disksing — APPROVED** [review]

**Pull request closed without merging**
