### PR TITLE
executor:  fix batchget overflow lock panic (#23774)

### LINKED ISSUE #23753: panic in 2pc pessimisticLockMutations
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `t1` (   `col_27` double DEFAULT '759.3040284831991',   `col_28` timestamp NOT NULL,   PRIMARY KEY (`col_28`) /*T![clustered_index] NONCLUSTERED */ ,   UNIQUE KEY `idx_19` (`col_28`) );
insert into t1(col_27, col_28) values(22, '2001-01-01 01:01:01');
begin pessimistic;
update t1 set col_27 = 'Alice' where col_28 in ( 949052690658455488 , 2766751491589624232 , 7802933885825354133 , 6855494379247880947 , 1920897000945502381 ) ;
```

### 2. What did you expect to see? (Required)

success

### 3. What did you see instead (Required)

paniced

```
"connection running loop panic"] [conn=5] [lastSQL="update t1 set col_27 = 'Alice' where col_28 in ( 949052690658455488 , 2766751491589624232 , 7802933885825354133 , 6855494379247880947 , 1920897000945502381 )"] [err="runtime error: invalid memory address or nil pointer dereference"] [stack="goroutine 552 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x10255d598, 0x1400fc107e0, 0x1400f832800)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/server/conn.go:734 +0xcc\npanic(0x10210d0c0, 0x103d816c0)\n\t/usr/local/go/src/runtime/panic.go:965 +0x14c\ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1(0x1401089f6b0, 0x1401050eb30, 0x1401050eb10)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/executor/adapter.go:301 +0x398\npanic(0x10210d0c0, 0x103d816c0)\n\t/usr/local/go/src/runtime/panic.go:965 +0x14c\ngithub.com/pingcap/tidb/store/tikv.(*memBufferMutations).GetKey(...)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:127\ngithub.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).primary(0x140109da3c0, 0x3ff0000000000000, 0x14000551e60, 0x0)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:430 +0x34\ngithub.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).doActionOnGroupMutations(0x140109da3c0, 0x1401093f800, 0x102550dd0, 0x140108b0540, 0x14010954a20, 0x1, 0x1, 0x0, 0x0)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:552 +0xc4\ngithub.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).doActionOnMutations(0x140109da3c0, 0x1401093f800, 0x102550dd0, 0x140108b0540, 0x102578728, 0x140109f2b40, 0x1020b4701, 0x140109f2b40)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:493 +0xdc\ngithub.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).pessimisticLockMutations(0x140109da3c0, 0x1401093f800, 0x140108b0540, 0x102578728, 0x140109f2b40, 0x1, 0x140003b7300)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/store/tikv/pessimistic.go:254 +0x58\ngithub.com/pingcap/tidb/store/tikv.(*KVTxn).LockKeys(0x140109f6000, 0x10255d598, 0x140109549c0, 0x140108b0540, 0x140109c0f30, 0x1, 0x1, 0x0, 0x0)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/store/tikv/txn.go:455 +0x448\ngithub.com/pingcap/tidb/store/driver/txn.(*tikvTxn).LockKeys(0x140109d07e0, 0x10255d598, 0x140109549c0, 0x140108b0540, 0x140109c0f30, 0x1, 0x1, 0x1021229e0, 0x10210a420)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/store/driver/txn/txn_driver.go:56 +0x5c\ngithub.com/pingcap/tidb/executor.doLockKeys(0x10255d598, 0x14010954570, 0x102598bc8, 0x1400fa99e00, 0x140108b0540, 0x140109c0f30, 0x1, 0x1, 0x0, 0x140109d09e0)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/executor/executor.go:999 +0x18c\ngithub.com/pingcap/tidb/executor.LockKeys(0x10255d598, 0x14010954570, 0x102598bc8, 0x1400fa99e00, 0xc350, 0x140109c0f30, 0x1, 0x1, 0x0, 0x0)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/executor/batch_point_get.go:407 +0xb8\ngithub.com/pingcap/tidb/executor.(*BatchPointGetExec).initialize(0x140009bf520, 0x10255d598, 0x14010954570, 0x0, 0x0)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/executor/batch_point_get.go:351 +0xae0\ngithub.com/pingcap/tidb/executor.(*BatchPointGetExec).Next(0x140009bf520, 0x10255d598, 0x14010954570, 0x140109ecbe0, 0x1401050e318, 0x1009e611c)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/executor/batch_point_get.go:160 +0x238\ngithub.com/pingcap/tidb/executor.Next(0x10255d598, 0x14010954570, 0x102561458, 0x140009bf520, 0x140109ecbe0, 0x0, 0x0)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/executor/executor.go:277 +0x230\ngithub.com/pingcap/tidb/executor.(*UpdateExec).updateRows(0x1401099f380, 0x10255d598, 0x14010954570, 0x0, 0x0, 0x114cfc200)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/executor/update.go:251 +0x5f8\ngithub.com/pingcap/tidb/executor.(*UpdateExec).Next(0x1401099f380, 0x10255d598, 0x14010954570, 0x140109ecb90, 0x14000581680, 0x1000fc4f8)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/executor/update.go:219 +0x5c\ngithub.com/pingcap/tidb/executor.Next(0x10255d598, 0x14010954570, 0x102562558, 0x1401099f380, 0x140109ecb90, 0x0, 0x0)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/executor/executor.go:277 +0x230\ngithub.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor(0x1401089f6b0, 0x10255d598, 0x14010954570, 0x102562558, 0x1401099f380, 0x0, 0x0, 0x0, 0x0)\n\t/Users/robi/Code/go/src/github.com/pingcap/tidb/executor/adapter.go:536 +0x240"]

```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23774 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23779
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23779:release-5.0-d0291c802a86
```

---

### What problem does this PR solve?

Issue Number: close #23753 

Problem Summary:

batch point get will lock not exist key.

overflow value be treated as "not exist key" in batch/point get, but overflow value can not build an invalid key, and it leads to NPE

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed, How it Works:

should not lock for overflow value's key

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- n/a

### Release note 

- Fix batch point lock maybe panic when condition value overflow 

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/23774)

### CODE REVIEW

**Comment by lysu** [comment]
@zhouqiang-cl  PTAL

**Comment by zhouqiang-cl** [comment]
@lysu Label added!!!

**Pull request merged**
