### PR TITLE
expression: refactor aggregate functions

### PR DESCRIPTION
**Pull request by zz-jason**
Thank you for working on TiDB! Please read TiDB's [CONTRIBUTING](https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md) document **BEFORE** filing this PR.

## What have you changed? (mandatory)

refactor the execution framework of aggregate functions, introduce the `AggEvaluator ` interface to do the actual aggregate work. We should implement this interface for every aggregate function.

## What are the type of the changes (mandatory)?

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested (mandatory)?

Not yet, still **WIP**

## Does this PR affect documentation (docs/docs-cn) update? (optional)

No

### CODE REVIEW

**Comment by shenli** [comment]
What is the benefit of this PR?

**Comment by zz-jason** [comment]
@shenli This was an experiment I did a long time ago, the performance gain is about 30% for `avg(decimal)`

**Comment by zz-jason** [comment]
Moreover, the memory consumption is less than the current implementation.

**Comment by zz-jason** [comment]
This is an old implementation, I'll close this and open another PR.

**Pull request closed without merging**
