### PR TITLE
planner/core: raise 'No database selected' error for grant statement

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

MySQL:

```
mysql> grant select on test1111 to test@"%" ;
ERROR 1046 (3D000): No database selected
```

TiDB:

```
mysql> grant select on test1111 to test@"%" ;
Query OK, 0 rows affected (0.05 sec)
```

### What is changed and how it works?

If no database is selected, grant privilege to table should raise an error.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @jackysp @lysu

**Comment by zz-jason** [comment]
@tiancaiamao should we cherry pick this PR to release 3.0 and release 3.1?

**Pull request merged**
