### PR TITLE
*: start replacing logger with zap logger (#9279)

### PR DESCRIPTION
**Pull request by zimulala**
check-pick #9279 to v2.1
Relate to pingcap/tidb-test#737

### CODE REVIEW

**Comment by zimulala** [comment]
/run-all-tests tidb-test=pr/737 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zz-jason** [comment]
@zimulala Please resolve conflicts.

**Comment by zimulala** [comment]
@zimulala test

**Comment by zimulala** [comment]
/run-all-tests tidb-test=pr/737 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zimulala** [comment]
/run-all-tests tidb-test=pr/737 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zimulala** [comment]
/run-all-tests tidb-test=pr/737 tidb-private-test=release-2.1 tikv=release-2.1

**Pull request merged**
