### PR TITLE
kvencoder: fix data race on plan.PreparedPlanCacheCapacity

### PR DESCRIPTION
**Pull request by winkyao**
before this, we will encounter data race:

```
==================

WARNING: DATA RACE

Write at 0x000002543068 by goroutine 129:

  github.com/pingcap/tidb/util/kvencoder.(*kvEncoder).initial()

      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/kvencoder/kv_encoder.go:229 +0xdb

  github.com/pingcap/tidb/util/kvencoder.New()

      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/kvencoder/kv_encoder.go:90 +0xb0

  github.com/pingcap/tidb/util/kvencoder.(*testKvEncoderSuite).TestSimpleKeyEncode()

      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/kvencoder/kv_encoder_test.go:461 +0x63

  runtime.call32()

      /usr/local/go/src/runtime/asm_amd64.s:573 +0x3a

  reflect.Value.Call()

      /usr/local/go/src/reflect/value.go:308 +0xc0

  github.com/pingcap/tidb/vendor/github.com/pingcap/check.(*suiteRunner).forkTest.func1()

      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/vendor/github.com/pingcap/check/check.go:798 +0x954

  github.com/pingcap/tidb/vendor/github.com/pingcap/check.(*suiteRunner).forkCall.func1()

      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/vendor/github.com/pingcap/check/check.go:692 +0x89



Previous read at 0x000002543068 by goroutine 36:

  github.com/pingcap/tidb/session.createSession()

      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1165 +0x4c3

  github.com/pingcap/tidb/session.createSessionFunc.func1()

      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:579 +0x5f

  github.com/pingcap/tidb/vendor/github.com/ngaut/pools.(*ResourcePool).get()

      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/vendor/github.com/ngaut/pools/resource_pool.go:119 +0x1ce

  github.com/pingcap/tidb/vendor/github.com/ngaut/pools.(*ResourcePool).Get()

      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/vendor/github.com/ngaut/pools/resource_pool.go:84 +0x41

  github.com/pingcap/tidb/session.(*session).ExecRestrictedSQL()

      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:542 +0x14f

  github.com/pingcap/tidb/statistics.(*Handle).Update()

      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle.go:108 +0x1c7

  github.com/pingcap/tidb/domain.(*Domain).updateStatsWorker()

      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/domain/domain.go:647 +0xdca

```

### CODE REVIEW

**Comment by winkyao** [comment]
kvencoder is not used by tidb-server instance, It is only used in lightning, so set plan.PreparedPlanCacheCapacity in package init func is ok.

**Comment by winkyao** [comment]
@XuHuaiyu @zz-jason PTAL

**Comment by XuHuaiyu** [comment]
ci failed @winkyao

**Comment by winkyao** [comment]
@XuHuaiyu fixed

**Comment by coocood** [comment]
@winkyao 
Can we just remove the lines that enable plan cache and let the user do it?

**Comment by winkyao** [comment]
@coocood Done

**Comment by coocood** [comment]
LGTM

**Pull request merged**
