### PR TITLE
*: Add `testfork.RunTest` to run multiple tests in one function

### LINKED ISSUE #35747: Add testfork.RunTest to run multiple test in one function
## Enhancement

see description in #35746

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #35747

### What is changed and how it works?

Some times we want to do a series of tests and all the them are similar except for some parameters. For example:

```
	for _, autocommit := range []bool{false, true} {
		for _, isolation := range []string{"READ-COMMITTED", "REPEATABLE-READ"} {
			t.Run("", func(t *testing.T) {
				tk := testkit.NewTestKit(t, store)
				tk.MustExec(fmt.Sprintf("set tx_isolation = '%s'", isolation)
				tk.MustExec(fmt.Sprintf("set autocommit=%d", autocommit))
				tk.MustExec("insert into t values(1, 2)")
				tk.MustQuery("select * from t where id=1").Check(testkit.Rows("1 2"))
			})
		}
	}

```

The above test will generate 4 sub tests and each of them will test one combination of `isolation` and `autcommit` settings. However, the implement is very elegant because the "for loops" are nested. When we have more and more parameters to composite, we will get a very deep syntax tree. 

This PR provide a new method `testfork.RunTest` to simplify the above cases, for example, the above test codes can be like this:

```
	testfork.RunTest(t, func(t *testfork.T) {
		tk := testkit.NewTestKit(t, store)
		isolation := testfork.PickEnum(t, "READ-COMMITTED", "REPEATABLE-READ")
		tk.MustExec(fmt.Sprintf("set tx_isolation = '%s'", isolation))
		autocommit := testfork.PickEnum(t, 1, 0)
		tk.MustExec(fmt.Sprintf("set autocommit=%d", autocommit))
		tk.MustExec("insert into t values(1, 2)")
		tk.MustQuery("select * from t where id=1").Check(testkit.Rows("1 2"))
	})
```

When we call `Pick` or `PickEnum` in a function, the test will "fork" to several sub tests according to the candidate values passed to it.  `Pick` or `PickEnum` can be called multiple times in a function, and it will "fork" multiple times if you do it.

It also support conditional fork, for example:

```
	testfork.RunTest(t, func(t *testfork.T) {
		tk := testkit.NewTestKit(t, store)
		if pessimistic := testfork.PickEnum(t, true, false); pessimistic {
			isolation := testfork.PickEnum(t, "READ-COMMITTED", "REPEATABLE-READ")
			tk.MustExec(fmt.Sprintf("set tx_isolation = '%s'", isolation))
		}

		autocommit := testfork.PickEnum(t, 1, 0)
		tk.MustExec(fmt.Sprintf("set autocommit=%d", autocommit))
		tk.MustExec("insert into t values(1, 2)")
		tk.MustQuery("select * from t where id=1").Check(testkit.Rows("1 2"))
	})
```

In the above demo `tx_siolation` will only be forked and set when `pessimistic` is true (it is also a forked value and can be different in different sub tests).

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]
You code make me think of a old joke: 
"what's the biggest hinder that prevent functional programming language from being popular?"
The answer is: 
"we don't get **enough** "clever" programmers. That's the biggest hinder and it's insoluble."
----------------------

The code itself is clever, but I can't claim this developing philosophy as wise.
Stupid simple code is the real wisdom for the averages.

**Comment by lcwangchao** [comment]
> ## You code make me think of a old joke:
> "what's the biggest hinder that prevent functional programming language from being popular?"
> The answer is:
> "we don't get **enough** "clever" programmers. That's the biggest hinder and it's insoluble."
> The code itself is clever, but I can't claim this developing philosophy as wise. Stupid simple code is the real wisdom for the averages.

I agree with you with some of the opinions. But I think the key point is "only use it when it is necessary". "Necessary" means it can reduce the implement complex a lot when use it. I don't think it's a good practice to apply the FP to the whole project, but they can work better in some certain cases for example: react UI. Whether to use it or not can be determined by the developer.

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
