### PR TITLE
ddl: fix error when batch create view

### LINKED ISSUE #31923: Fix BatchCreateTables for creating views
## Bug Report

Previously, `BatchCreateTables` assumes `createTableWithInfoJob` will only return one argument if it is creating tables. But it may return two arguments, if it is creating views.

https://github.com/pingcap/tidb/blob/b228c189cccd1096e7eaaa23e1ad6c8af59b880e/ddl/ddl_api.go#L2180-L2199

https://github.com/pingcap/tidb/blob/b228c189cccd1096e7eaaa23e1ad6c8af59b880e/ddl/ddl_api.go#L2054-L2064

### 1. Minimal reproduce step (Required)

This is an internal API for BR quick restore #27036, reproduce is kinda complex. And it it does needs to be cherry-picked to older version.

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Issue Number: close #31923

Problem Summary: Remove assertion to enable creating views(creating view will return a job with `len(job.Args) == 2`), refer the issue for details.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by fengou1 — APPROVED** [review]
The issue happen once in test-infra CI.

**Comment by fengou1** [comment]
//run-integration-br-tests

**Review by AilinKid — APPROVED** [review]
LGTM

**Pull request merged**
