### PR TITLE
*: remove bazel config

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close None

Problem Summary:

### Check List

Tests 

- [x] Manual test (add detailed scripts or steps below)
Run in CI

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by xhebox** [comment]
What is this PR for?

**Review by xhebox — APPROVED** [review]

**Comment by tisonkun** [comment]
So, what is this PR for?

**Comment by hawkingrei** [comment]
> So, what is this PR for?

remove the useless code. just boring.

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
@hawkingrei you can try to write some PR descriptions next times :)

**Comment by tisonkun** [comment]
@hawkingrei you can try to write some PR descriptions next times :)

**Comment by tisonkun** [comment]
@hawkingrei you can try to write some PR descriptions next times :)

**Comment by tisonkun** [comment]
@hawkingrei you can try to write some PR descriptions next times :)

**Pull request merged**
