### PR TITLE
planner: handle other-conditions from subqueries correctly when constructing IndexJoin (#25817)

### LINKED ISSUE #25799: The result of index join in associated subqueries is wrong
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
[1.txt](https://github.com/pingcap/tidb/files/6725119/1.txt)
download and source the 1.txt
```
select t1. `col_float_key_signed`,t1. `col_smallint_undef_signed`  from table_20_binary_undef as t1 where t1. `col_float_key_signed` not in (select `col_float_key_signed` from table_75_binary_undef as t2 where t1. `col_smallint_undef_signed` = t2. `col_tinyint_key_signed`) ;
```
The plan is
```
+------------------------------------+---------+-----------+----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                                 | estRows | task      | access object                                                  | operator info                                                                                                                                                                                                                                                                                                                                                                             |
+------------------------------------+---------+-----------+----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_8                       | 16.00   | root      |                                                                | rs2.table_20_binary_undef.col_float_key_signed, rs2.table_20_binary_undef.col_smallint_undef_signed                                                                                                                                                                                                                                                                                       |
| └─IndexJoin_12                     | 16.00   | root      |                                                                | anti semi join, inner:IndexLookUp_11, outer key:rs2.table_20_binary_undef.col_smallint_undef_signed, inner key:rs2.table_75_binary_undef.col_tinyint_key_signed, equal cond:eq(rs2.table_20_binary_undef.col_float_key_signed, rs2.table_75_binary_undef.col_float_key_signed), eq(rs2.table_20_binary_undef.col_smallint_undef_signed, rs2.table_75_binary_undef.col_tinyint_key_signed) |
|   ├─TableReader_22(Build)          | 20.00   | root      |                                                                | data:TableFullScan_21                                                                                                                                                                                                                                                                                                                                                                     |
|   │ └─TableFullScan_21             | 20.00   | cop[tikv] | table:t1                                                       | keep order:false, stats:pseudo                                                                                                                                                                                                                                                                                                                                                            |
|   └─IndexLookUp_11(Probe)          | 1.25    | root      |                                                                |                                                                                                                                                                                                                                                                                                                                                                                           |
|     ├─IndexRangeScan_9(Build)      | 1.25    | cop[tikv] | table:t2, index:col_tinyint_key_signed(col_tinyint_key_signed) | range: decided by [eq(rs2.table_75_binary_undef.col_tinyint_key_signed, rs2.table_20_binary_undef.col_smallint_undef_signed)], keep order:false, stats:pseudo                                                                                                                                                                                                                             |
|     └─TableRowIDScan_10(Probe)     | 1.25    | cop[tikv] | table:t2                                                       | keep order:false, stats:pseudo                                                                                                                                                                                                                                                                                                                                                            |
+------------------------------------+---------+-----------+----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### 2. What did you expect to see? (Required)
```
+----------------------+---------------------------+
| col_float_key_signed | col_smallint_undef_signed |
+----------------------+---------------------------+
|                   -1 |                      NULL |
|               12.991 |                       -37 |
|                    1 |                        39 |
+----------------------+---------------------------+
```
### 3. What did you see instead (Required)
```
+----------------------+---------------------------+
| col_float_key_signed | col_smallint_undef_signed |
+----------------------+---------------------------+
|                  -87 |                         1 |
|                   -1 |                      NULL |
|                    1 |                        -9 |
|               12.991 |                       -37 |
|                    1 |                        39 |
|                 NULL |                        -1 |
|               -9.183 |                         1 |
|                  -15 |                        -9 |
+----------------------+---------------------------+
```
### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
Release Version: v5.0.3
Edition: Community
Git Commit Hash: ad06648c4cc00136c7dc46dc6ba7068abf86ed45
Git Branch: heads/refs/tags/v5.0.3
UTC Build Time: 2021-06-25 10:00:40
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25817 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25819
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25819:release-5.1-a0b97b0c962d
```

---

### What problem does this PR solve?

Issue Number: close #25799 

Problem Summary: planner: handle other-conditions from subqueries correctly when constructing IndexJoin

### What is changed and how it works?

When constructing IndexJoin, TiDB extracts equal expressions from other-conditions and converts them into eq-conditions to build hash keys.

If these equal expressions are from some `[not] in` sub-queries, this conversation may lead to wrong results since `IndexJoin` cannot deal with NULL correctly in this case.

This PR skips this conversation for equal expressions from `[not] in` sub-queries.

### Check List 

Tests 

- Unit test

### Release note 

- planner: handle other-conditions from subqueries correctly when constructing IndexJoin

### CODE REVIEW

**Review by eurekaka — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Comment by qw4990** [comment]
@zhouqiang-cl

**Comment by qw4990** [comment]
Please help me approve this PR again @time-and-fate @winoros @eurekaka

**Pull request merged**
