### PR TITLE
expression: Fix incorrect pushdown function list.

### PR DESCRIPTION
**Pull request by LittleFall**
### What problem does this PR solve?

close https://github.com/pingcap/tics/issues/1642

Problem Summary:

https://github.com/pingcap/tidb/pull/23284 change the pushdown list from unified to separated but didn't keep them equal.

This pr fix it and https://github.com/pingcap/tics/issues/1642

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

For `ast.Substr, ast.Substring` in `TiFlash`, it only supports UTF8.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`: no need
- Need to cherry-pick to the release branch: need cherry-pick to https://github.com/pingcap/tidb/pull/23660, https://github.com/pingcap/tidb/pull/23661

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- No release note.

### CODE REVIEW

**Comment by leiysky** [comment]
https://github.com/pingcap/tidb/blob/c709217ff49a7bf13a785274abc9b6235bd4611b/expression/expr_to_pb_test.go#L604

@LittleFall  Maybe you should update this test.

**Review by lzmhhh123 — APPROVED** [review]

**Comment by windtalker** [comment]
lgtm

**Review by hanfei1991 — APPROVED** [review]

**Comment by LittleFall** [comment]
> @LittleFall: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

what a retrospection!

**Pull request merged**
