### PR TITLE
executor: bind the func to memtableRetriever

### PR DESCRIPTION
**Pull request by Rustin-Liu**
Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>

### What problem does this PR solve? 

Bind the func to memtableRetriever.
### What is changed and how it works?
Bind the func to memtableRetriever.

### Check List 

Tests 

 - Unit test

Code changes

None

Side effects

None

Related changes

PR: #14704

Release note

None

### CODE REVIEW

**Comment by Rustin-Liu** [comment]
@sre-bot  /run-all-tests

**Comment by Rustin-Liu** [comment]
@zz-jason @SunRunAway  PTAL~

**Comment by Rustin-Liu** [comment]
@sre-bot  /run-all-tests

**Comment by Rustin-Liu** [comment]
@crazycs520  PTAL~

**Comment by Rustin-Liu** [comment]
@sre-bot /run-all-tests

**Comment by Rustin-Liu** [comment]
@sre-bot /run-all-tests

**Comment by Rustin-Liu** [comment]
@sre-bot /run-all-tests

**Comment by zz-jason** [comment]
@lonng @SunRunAway PTAL

**Comment by Rustin-Liu** [comment]
@sre-bot /auto-merge

**Pull request merged**
