### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by c4pt0r**
update go get command

### CODE REVIEW

**Comment by c4pt0r** [comment]
@ngaut @qiuyesuifeng 
LGTM

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Comment by zhouqiang-cl** [comment]
Bench result:
<table>
  <tr>
    <th></th>
    <th>oltp_read_only</th>
    <th>oltp_point_select</th>
    <th>oltp_write_only</th>
    <th>oltp_read_write</th>
  </tr>
  <tr>
<th>TPS</th>
    <th>3289.60</th>
    <th>81400.89</th>
    <th>4991.98</th>
    <th>993.43</th>
  </tr>
  <tr>
<th>LAT95</th>
    <th>106.75</th>
    <th>5.99</th>
    <th>87.56</th>
    <th>484.44</th>
  </tr>
</table>
<br/>
Bench topology:
<table>
  <tr>
    <th></th>
    <th>Count</th>
    <th>Type</th>
    <th>Version</th>
  <tr>
  <tr>
    <th>TiDB</th>
    <td>2</td>
    <td>c4.4xlarge</td>
    <td>95a3eb8</td>
  <tr>
  <tr>
    <th>TiKV</th>
    <td>3</td>
    <td>i3.2xlarge</td>
    <td>v3.0.0-rc.1</td>
  </tr>
  <tr>
    <th>PD</th>
    <td>3</td>
    <td>m5d.xlarge</td>
    <td>v3.0.0-rc.1</td>
  </tr>
</table>

**Comment by zhouqiang-cl** [comment]
test

**Comment by zhouqiang-cl** [comment]
test

**Comment by zhouqiang-cl** [comment]
test

**Comment by lucklove** [comment]
Ignore above three comments please.
Testing CI bot.

**Pull request merged**
