### PR TITLE
planner: do not eliminate group_concat in aggregate elimination (#9967)

### PR DESCRIPTION
**Pull request by XuHuaiyu**
cherry-pick #9967

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
/run-all-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
/run-all-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by XuHuaiyu** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
