### PR TITLE
lightning: fix auto_increment out-of-range error (#34146)

### LINKED ISSUE #27937: lighting: local backend import failed if data has largest number as bigint auto_increment column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Prepare test data, with biggest number (9223372036854775807) as bigint  auto_increment column.
[root@idc-4-30 ~]# cat /minio/tools_test_data/PK_AUTO_INCREMENT9096/new_data1.PK_AUTO_INCREMENT9096.000000000.csv
"COL1","COL2","COL4","COL3","COL5"
1,"鐚傆Ē榉牖纜径鉾抍镒获肾É鷓开纻緖扻鏶囮","8431-02-26 15:01:24",5737257244447821569,-1.20365e38
9223372036854775807,"多鵾嚟咕勓鞒轊嵵呮觧栽榨娅猋荪桍舉宰籕僸","0032-10-07 22:42:25",-6700431522805297345,-2.51818e38

[root@idc-4-30 ~]# cat /minio/tools_test_data/PK_AUTO_INCREMENT9096/new_data1.PK_AUTO_INCREMENT9096-schema.sql
/*!40101 SET NAMES binary*/;
CREATE TABLE `PK_AUTO_INCREMENT9096` (
  `COL1` bigint(20) NOT NULL AUTO_INCREMENT,
  `COL2` varchar(20) DEFAULT NULL,
  `COL4` datetime DEFAULT NULL,
  `COL3` bigint(20) DEFAULT NULL,
  `COL5` float DEFAULT NULL,
  PRIMARY KEY (`COL1`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

2, Import the data with local backend
[root@idc-4-30 ~]# tiup tidb-lightning --tidb-host=172.16.4.30 --tidb-port=4000 --check-requirements=false --backend=local --sorted-kv-dir=/home/sorted-kvs -d 's3://nfs/tools_test_data/PK_AUTO_INCREMENT9096/?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%2fminio.pingcap.net%3a9000&force-path-style=true' -config lightning_min.toml -log-file PK_AUTO_INCREMENT9096.log.6
Starting component `tidb-lightning`: /root/.tiup/components/tidb-lightning/v5.2.0/tidb-lightning --tidb-host=172.16.4.30 --tidb-port=4000 --check-requirements=false --backend=local --sorted-kv-dir=/home/sorted-kvs -d s3://nfs/tools_test_data/PK_AUTO_INCREMENT9096/?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%2fminio.pingcap.net%3a9000&force-path-style=true -config lightning_min.toml -log-file PK_AUTO_INCREMENT9096.log.6
Verbose debug logs will be written to PK_AUTO_INCREMENT9096.log.6
...
Error: restore table `new_data1`.`PK_AUTO_INCREMENT9096` failed: ALTER TABLE `new_data1`.`PK_AUTO_INCREMENT9096` AUTO_INCREMENT=-9223372036854775808: alter table auto_increment failed: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 64 near "-9223372036854775808"
tidb lightning encountered error:  restore table `new_data1`.`PK_AUTO_INCREMENT9096` failed: ALTER TABLE `new_data1`.`PK_AUTO_INCREMENT9096` AUTO_INCREMENT=-9223372036854775808: alter table auto_increment failed: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 64 near "-9223372036854775808"

### 2. What did you expect to see? (Required)
Import succeed

### 3. What did you see instead (Required)
Import failed with error: ALTER TABLE `new_data1`.`PK_AUTO_INCREMENT9096` AUTO_INCREMENT=-9223372036854775808

Note: import is OK for tidb backend.

### 4. What is your TiDB version? (Required)
TiDB: v5.0.0-nightly-20210908
[root@idc-4-30 ~]# tiup tidb-lightning -V
Starting component `tidb-lightning`: /root/.tiup/components/tidb-lightning/v5.2.0/tidb-lightning -V
Release Version: v5.2.0
Git Commit Hash: 05d2210647d6a1503a8d772477e43b14a024f609
Git Branch: heads/refs/tags/v5.2.0
Go Version: go1.16.4
UTC Build Time: 2021-08-27 05:56:11
Race Enabled: false

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #34146 to release-6.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/34336
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/34336:release-6.0-56179411707c
```

---

### What problem does this PR solve?

Issue Number: close #27937

Problem Summary:

### What is changed and how it works?
- Change `AlterAutoIncrement`'s parameter to `uint64` whose maximum is larger than `BIGINT`.
- Throw warning and return immediately while `incr` is larger than `math.MaxInt64` (i.e. maximum of `BIGINT`)

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by D3Hunter — APPROVED** [review]

**Comment by xhebox** [comment]
closed for DMR version

**Pull request closed without merging**
