### PR TITLE
*: update tikv/client-go | plugin=pr/151

### LINKED ISSUE #53540: tidb log print "connection running loop panic  [err="Trying to start aggressive locking while it's already started"] " when run tpcc and import into
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run tpcc and import into
[tidb.tar.gz](https://github.com/pingcap/tidb/files/15431000/tidb.tar.gz)

### 2. What did you expect to see? (Required)
no panic

### 3. What did you see instead (Required)
tidb log print “connection running loop panic

```
[2024/05/24 10:49:13.008 +08:00] [ERROR] [conn.go:1013] ["connection running loop panic"] [conn=2594177614] [session_alias=] [lastSQL=ROLLBACK] [err="Trying to start aggressive locking while it's already started"] [stack="github.com/pingcap/tidb/pkg/server.(*clientConn).Run.func1
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1016
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:914
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec.func1
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:452
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:914
github.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).StartAggressiveLocking
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20240516031922-38e0dca30c8c/txnkv/transaction/txn.go:919
github.com/pingcap/tidb/pkg/store/driver/txn.(*tikvTxn).StartFairLocking
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/store/driver/txn/txn_driver.go:422
github.com/pingcap/tidb/pkg/session.(*LazyTxn).StartFairLocking
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/txn.go:495
github.com/pingcap/tidb/pkg/sessiontxn/isolation.(*basePessimisticTxnContextProvider).OnPessimisticStmtStart
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/sessiontxn/isolation/base.go:683
github.com/pingcap/tidb/pkg/session.(*txnManager).OnPessimisticStmtStart
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/txnmanager.go:228
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handlePessimisticDML
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:998
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelay
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:791
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:559
github.com/pingcap/tidb/pkg/session.runStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:2285
github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:2146
github.com/pingcap/tidb/pkg/server.(*TiDBContext).ExecuteStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/driver_tidb.go:294
github.com/pingcap/tidb/pkg/server.(*clientConn).handleStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:2021
github.com/pingcap/tidb/pkg/server.(*clientConn).handleQuery
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1774
github.com/pingcap/tidb/pkg/server.(*clientConn).dispatch
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1348
github.com/pingcap/tidb/pkg/server.(*clientConn).Run
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1114
github.com/pingcap/tidb/pkg/server.(*Server).onConn
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/server.go:739"]
[2024/05/24 10:49:13.008 +08:00] [ERROR] [terror.go:324] ["encountered error"] [error="trying to rollback transaction when aggressive locking is pending"] [stack="github.com/pingcap/tidb/pkg/parser/terror.Log
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/parser/terror/terror.go:324
github.com/pingcap/tidb/pkg/session.(*session).RollbackTxn
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:941
github.com/pingcap/tidb/pkg/session.(*session).Close
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:2516
github.com/pingcap/tidb/pkg/server.(*TiDBContext).Close
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/driver_tidb.go:313
github.com/pingcap/tidb/pkg/server.closeConn.func1
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:400
sync.(*Once).doSlow
	/usr/local/go/src/sync/once.go:74
sync.(*Once).Do
	/usr/local/go/src/sync/once.go:65
github.com/pingcap/tidb/pkg/server.closeConn
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:380
github.com/pingcap/tidb/pkg/server.(*clientConn).Close
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:373
github.com/pingcap/tidb/pkg/server.(*clientConn).Run.func1
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1023
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:914
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec.func1
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:452
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:914
github.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).StartAggressiveLocking
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20240516031922-38e0dca30c8c/txnkv/transaction/txn.go:919
github.com/pingcap/tidb/pkg/store/driver/txn.(*tikvTxn).StartFairLocking
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/store/driver/txn/txn_driver.go:422
github.com/pingcap/tidb/pkg/session.(*LazyTxn).StartFairLocking
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/txn.go:495
github.com/pingcap/tidb/pkg/sessiontxn/isolation.(*basePessimisticTxnContextProvider).OnPessimisticStmtStart
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/sessiontxn/isolation/base.go:683
github.com/pingcap/tidb/pkg/session.(*txnManager).OnPessimisticStmtStart
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/txnmanager.go:228
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handlePessimisticDML
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:998
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelay
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:791
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:559
github.com/pingcap/tidb/pkg/session.runStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:2285
github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:2146
github.com/pingcap/tidb/pkg/server.(*TiDBContext).ExecuteStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/driver_tidb.go:294
github.com/pingcap/tidb/pkg/server.(*clientConn).handleStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:2021
github.com/pingcap/tidb/pkg/server.(*clientConn).handleQuery
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1774
github.com/pingcap/tidb/pkg/server.(*clientConn).dispatch
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1348
github.com/pingcap/tidb/pkg/server.(*clientConn).Run
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1114
github.com/pingcap/tidb/pkg/server.(*Server).onConn
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/server.go:739"]`
```

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v8.2.0-alpha
Edition: Community
Git Commit Hash: 3485857563aaeb040c0eab2057ce4a70dd3b6e2f
Git Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time: 2024-05-23 11:45:56
GoVersion: go1.21.10
Race Enabled: false

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #53540

Problem Summary:  update tikv/client-go.

Related PR:
- https://github.com/tikv/client-go/pull/1355
- https://github.com/tikv/client-go/pull/1265

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zyguan — APPROVED** [review]

**Review by MyonKeminta — APPROVED** [review]
~~Maybe you can add "close #53540"~~
Sorry I missed it.
LGTM

**Comment by MyonKeminta** [comment]
There seem to be some build failures.

**Review by hawkingrei — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Pull request merged**
