### PR TITLE
table: fix zero date in different sqlmode (#20206)

### LINKED ISSUE #19892: different behaviour of NO_ZERO_DATE with mysql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

The [`NO_ZERO_DATE`](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date) define as below:

> The NO_ZERO_DATE mode affects whether the server permits '0000-00-00' as a valid date. Its effect also depends on whether strict SQL mode is enabled.
> If this mode is not enabled, '0000-00-00' is permitted and inserts produce no warning.
>
>If this mode is enabled, '0000-00-00' is permitted and inserts produce a warning.
>
> If this mode and strict mode are enabled, '0000-00-00' is not permitted and inserts produce an error, unless IGNORE is given as well. For INSERT IGNORE and UPDATE IGNORE, '0000-00-00' is permitted and inserts produce a warning.

BUT, in TiDB's implemention, the SQL mode doesn't work.

### 1. Minimal reproduce step (Required)

```sql
create table dd(i datetime)
insert into dd('0000-00-00')
```

### 2. What did you expect to see? (Required)

in MySQL 8.0

```sql
mysql admin@127.0.0.1:app> create table dd(i datetime);
Query OK, 0 rows affected
Time: 0.114s

-- sql_mode to none
mysql admin@127.0.0.1:app> show variables like 'sql_mode';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| sql_mode      |       |
+---------------+-------+
1 row in set
Time: 0.031s
mysql admin@127.0.0.1:app> show global variables like 'sql_mode';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| sql_mode      |       |
+---------------+-------+

mysql admin@127.0.0.1:app> insert into dd values ('0000-00-00');
Query OK, 1 row affected
Time: 0.005s
mysql admin@127.0.0.1:app> show warnings;
+-------+------+---------+
| Level | Code | Message |
+-------+------+---------+
0 rows in set
Time: 0.021s


-- set to NO_ZERO_DATE
mysql admin@127.0.0.1:app> set sql_mode='NO_ZERO_DATE';
Query OK, 0 rows affected
Time: 0.002s
mysql admin@127.0.0.1:app> insert into dd values ('0000-00-00');
Query OK, 1 row affected
Time: 0.008s
mysql admin@127.0.0.1:app> show warnings;
+---------+------+--------------------------------------------+
| Level   | Code | Message                                    |
+---------+------+--------------------------------------------+
| Warning | 1264 | Out of range value for column 'i' at row 1 |
+---------+------+--------------------------------------------+
1 row in set
Time: 0.041s

-- set to NO_ZERO_DATE,STRICT_TRANS_TABLES
mysql admin@127.0.0.1:app> set sql_mode='NO_ZERO_DATE,STRICT_TRANS_TABLES';
Query OK, 0 rows affected
Time: 0.003s
mysql admin@127.0.0.1:app> insert into dd values ('0000-00-00');
(1292, "Incorrect datetime value: '0000-00-00' for column 'i' at row 1")
mysql admin@127.0.0.1:app> show warnings;
+-------+------+----------------------------------------------------------------+
| Level | Code | Message                                                        |
+-------+------+----------------------------------------------------------------+
| Error | 1292 | Incorrect datetime value: '0000-00-00' for column 'i' at row 1 |
+-------+------+----------------------------------------------------------------+
```

### 3. What did you see instead (Required)

```sql
mysql admin@127.0.0.1:app> create table dd(i datetime);
Query OK, 0 rows affected
Time: 0.114s

-- sql_mode to none
mysql admin@127.0.0.1:app> show variables like 'sql_mode';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| sql_mode      |       |
+---------------+-------+
1 row in set
Time: 0.031s
mysql admin@127.0.0.1:app> show global variables like 'sql_mode';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| sql_mode      |       |
+---------------+-------+

mysql admin@127.0.0.1:app> insert into dd values ('0000-00-00');
Query OK, 1 row affected
Time: 0.005s
mysql admin@127.0.0.1:app> show warnings;
+-------+------+---------+
| Level | Code | Message |
+-------+------+---------+
0 rows in set
Time: 0.021s

-- set to NO_ZERO_DATE
mysql admin@127.0.0.1:app> set sql_mode='NO_ZERO_DATE';
Query OK, 1 rows affected
Time: 0.002s
mysql admin@127.0.0.1:app> insert into dd values ('0000-00-00');
Query OK, 1 row affected
Time: 0.005s
mysql admin@127.0.0.1:app> show warnings;
+-------+------+---------+
| Level | Code | Message |
+-------+------+---------+
0 rows in set
Time: 0.021s

-- set to NO_ZERO_DATE,STRICT_TRANS_TABLES
mysql admin@127.0.0.1:app> set sql_mode='NO_ZERO_DATE,STRICT_TRANS_TABLES';
Query OK, 0 rows affected
Time: 0.003s
mysql admin@127.0.0.1:app> insert into dd values ('0000-00-00');
Query OK, 1 row affected
Time: 0.005s
mysql admin@127.0.0.1:app> show warnings;
+-------+------+---------+
| Level | Code | Message |
+-------+------+---------+
0 rows in set
Time: 0.021s
```

### 4. What is your TiDB version? (Required)

```sql
mysql root@127.0.0.1:(none)> select tidb_version() \G;
***************************[ 1. row ]***************************
tidb_version() | Release Version: v4.0.0-beta.2-1165-g726341146-dirty
Edition: Community
Git Commit Hash: 726341146b99485335a195b16a803b95e4875228
Git Branch: master
UTC Build Time: 2020-09-08 01:55:13
GoVersion: go1.14.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

1 row in set
Time: 0.009s
```

## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @qw4990

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20206 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #19892, #19634

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

- The same behavior of `NO_ZERO_DATE` and `NO_ZERO_IN_DATE` to MySQL's in INSERT/UPDATE statement

### CODE REVIEW

**Comment by wjhuang2016** [comment]
@9547 @lzmhhh123 PTAL

**Comment by 9547** [comment]
@wjhuang2016 Seems there exist some code conflicts after the cherry-pick, IMO, we should resolve those conflicts manually.

**Review by qw4990 — COMMENTED** [review]
LGTM

**Comment by qw4990** [comment]
/run-all-tests

**Comment by qw4990** [comment]
It seems this PR triggers some bugs about prepared-stmt:
```
INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`,`created_at`,`updated_at`,`billing_address_id`,`shipping_address_id`,`latitude`,`company_id`,`role`,`password_hash`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) [arguments: (1, 0, OrderPluckUser1, 0000-00-00, 2021-01-29 07:26:24.815707, 2021-01-29 07:26:24.815707, NULL, 0, 0, 0, , NULL)]"] [txn_mode=OPTIMISTIC] [err="[table:1366]Incorrect timestamp value: '0000-00-00' for column 'birthday' at row 1
github.com/pingcap/errors.AddStack
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174
github.com/pingcap/errors.(*Error).GenWithStackByArgs
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/normalize.go:156
github.com/pingcap/tidb/executor.(*InsertValues).handleErr
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/executor/insert_common.go:300
github.com/pingcap/tidb/executor.(*InsertValues).fastEvalRow
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/executor/insert_common.go:364
github.com/pingcap/tidb/executor.insertRows
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/executor/insert_common.go:232
github.com/pingcap/tidb/executor.(*InsertExec).Next
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/executor/insert.go:288
github.com/pingcap/tidb/executor.Next
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/executor/executor.go:262
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/executor/adapter.go:531
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/executor/adapter.go:413
github.com/pingcap/tidb/executor.(*ExecStmt).Exec
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/executor/adapter.go:366
github.com/pingcap/tidb/session.runStmt
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/session/tidb.go:308
github.com/pingcap/tidb/session.(*session).CommonExec
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/session/session.go:1313
github.com/pingcap/tidb/session.(*session).ExecutePreparedStmt
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/session/session.go:1431
github.com/pingcap/tidb/server.(*TiDBStatement).Execute
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/server/driver_tidb.go:77
github.com/pingcap/tidb/server.(*clientConn).handleStmtExecute
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/server/conn_stmt.go:189
github.com/pingcap/tidb/server.(*clientConn).dispatch
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/server/conn.go:1022
github.com/pingcap/tidb/server.(*clientConn).Run
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/server/conn.go:782
github.com/pingcap/tidb/server.(*Server).onConn
	/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/server/server.go:449
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`,`created_at`,`updated_at`,`billing_address_id`,`shipping_address_id`,`latitude`,`company_id`,`role`,`password_hash`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) [arguments: (1, 0, OrderPluckUser1, 0000-00-00, 2021-01-29 07:26:24.815707, 2021-01-29 07:26:24.815707, NULL, 0, 0, 0, , NULL)]
```

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
