### PR TITLE
helper: request another PD if one of them is unavailable (#35750)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #35750 to release-6.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/37781
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/37781:release-6.1-8097685436fd
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/35708.

Problem Summary:

`requestPD` should try the PD hosts one by one until the request is successful.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix an issue that TiDB cannot access `TIKV_REGION_STATUS` when one of the PD is down.
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]

**Comment by nolouch** [comment]
PTAL @JmPotato @Yisaer

**Comment by nolouch** [comment]
ref https://github.com/pingcap/tidb/issues/35708

**Review by JmPotato — APPROVED** [review]

**Review by AndreMouche — APPROVED** [review]
LGTM

**Pull request merged**
