### PR TITLE
executor: make show create table show index comments

### LINKED ISSUE #25509: Add comment doesn't take affect on index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
https://asktug.com/t/topic/93678

CREATE TABLE a (
name varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
alter table a add index idx_name(name) comment 'name-key';
show create table a;

### 2. What did you expect to see? (Required)

CREATE TABLE a (
name varchar(20) DEFAULT NULL,
KEY idx_name (name) comment 'name-key'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

### 3. What did you see instead (Required)

CREATE TABLE a (
name varchar(20) DEFAULT NULL,
KEY idx_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

### 4. What is your TiDB version? (Required)
v5.0

### PR DESCRIPTION
**Pull request by dveeden**
This is a fix for https://github.com/pingcap/tidb/issues/25509

### What problem does this PR solve?

Issue Number: close #25509

Problem Summary:

- `SHOW CREATE TABLE` doesn't show index comments

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- `SHOW CREATE TABLE` now shows comments on indexes

### CODE REVIEW

**Comment by dveeden** [comment]
Looks like this only affects `SHOW CREATE TABLE` and *not*:

- `show indexes from a`
- `select * from information_schema.TIDB_INDEXES WHERE TABLE_NAME='a'`

**Comment by dveeden** [comment]
Things to watch out for:

- multiline comments (containing `\n`)
- comments containing `'`

**Comment by dveeden** [comment]
Note that this could have user impact: Some companies compare `SHOW CREATE TABLE` against a previously recorded output and then filter out the `AUTO_INCREMENT<n>` etc to check against unapproved schema changes. This can be done as part of SOx compliance etc. With this fixed that output may not match anymore if there are column comments.

I do think affected users would still want this fix.

**Review by bb7133 — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by bb7133** [comment]
PTAL @pingcap/exec-reviewers

**Review by xiongjiwei — APPROVED** [review]

**Pull request merged**
