### PR TITLE
executor: Improve the performance of appending not fixed columns

### PR DESCRIPTION
**Pull request by mmyj**
### What problem does this PR solve?

Problem Summary:

Using a temporary variable can improve a little performance.

### What is changed and how it works?

How it Works:

Saving `dst.offsets[len(dst.offsets)-1]` in the `lastOffset` 

Tests 

- Unit test

Side effects

- Performance regression

2 string columns
```
name                   old time/op  new time/op  delta
Append/column-2-16     37.4ns ± 1%  37.2ns ± 0%   -0.67%  (p=0.001 n=10+10)
Append/column-8-16     93.6ns ± 1%  87.4ns ± 1%   -6.66%  (p=0.000 n=10+10)
Append/column-16-16     162ns ± 1%   154ns ± 1%   -5.18%  (p=0.000 n=10+10)
Append/column-100-16   1.00µs ± 1%  0.92µs ± 1%   -7.35%  (p=0.000 n=9+10)
Append/column-1000-16  10.2µs ± 0%   9.0µs ± 1%  -11.27%  (p=0.000 n=10+10)
Append/column-4000-16  39.0µs ± 1%  35.6µs ± 1%   -8.63%  (p=0.000 n=10+10)
```

[new.txt](https://github.com/pingcap/tidb/files/5518705/new.txt)
[old.txt](https://github.com/pingcap/tidb/files/5518707/old.txt)

8 string columns
```
name                   old time/op  new time/op  delta
Append/column-2-16      157ns ± 0%   157ns ± 1%    ~     (p=0.831 n=10+10)
Append/column-8-16      369ns ± 1%   358ns ± 1%  -2.82%  (p=0.000 n=10+10)
Append/column-16-16     657ns ± 1%   640ns ± 1%  -2.57%  (p=0.000 n=9+10)
Append/column-100-16   3.92µs ± 0%  3.60µs ± 1%  -8.23%  (p=0.000 n=10+10)
Append/column-1000-16  38.3µs ± 0%  35.2µs ± 1%  -8.08%  (p=0.000 n=10+10)
Append/column-4000-16   155µs ± 1%   142µs ± 1%  -8.46%  (p=0.000 n=10+10)
```
[new-8col.txt](https://github.com/pingcap/tidb/files/5518912/new-8col.txt)
[old-8col.txt](https://github.com/pingcap/tidb/files/5518914/old-8col.txt)

### Release note 

- Improving the performance of appending not fixed columns

### CODE REVIEW

**Comment by zz-jason** [comment]
@mmyj is this PR ready fore review?

**Comment by mmyj** [comment]
> @mmyj is this PR ready for review?

Yes!

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
