### PR TITLE
expression: implement vectorized evaluation for `builtinTruncateRealSig`

### PR DESCRIPTION
**Pull request by TennyZhuang**
PCP #12102 

### What problem does this PR solve? 

#12102 

### What is changed and how it works?

```
BenchmarkVectorizedBuiltinMathFunc/builtinTruncateRealSig-VecBuiltinFunc-8         	  122958	     13975 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinMathFunc/builtinTruncateRealSig-NonVecBuiltinFunc-8      	   27172	     46372 ns/op	       0 B/op	       0 allocs/op
PASS
```

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

Release note

 - vectorize `builtinTruncateRealSig`

### CODE REVIEW

**Comment by TennyZhuang** [comment]
@wshwsh12 

It seems that the panic is not caused by my PR.

I debug the code, and the code panic stack:

```
runtime error: invalid memory address or nil pointer dereference
goroutine 40 [running]:
runtime/debug.Stack(0x41, 0x0, 0x0)
	/usr/local/Cellar/go/1.13/libexec/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.13/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/pingcap/tidb/expression.(*testEvaluatorSerialSuites).TestPushDownSwitcher.func1()
	/Users/zhuangtianyi/go/src/github.com/pingcap/tidb/expression/expr_to_pb_test.go:427 +0x84
panic(0x558a440, 0x6ecc9c0)
	/usr/local/Cellar/go/1.13/libexec/src/runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb/expression.(*testEvaluatorSerialSuites).TestPushDownSwitcher(0xc00030f860, 0xc00041c000)
	/Users/zhuangtianyi/go/src/github.com/pingcap/tidb/expression/expr_to_pb_test.go:471 +0x81b
reflect.Value.call(0x56bfb20, 0xc00030f860, 0x1613, 0x57e8a3b, 0x4, 0xc000073f30, 0x1, 0x1, 0x6f52c00, 0xc0001ab5d0, ...)
	/usr/local/Cellar/go/1.13/libexec/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x56bfb20, 0xc00030f860, 0x1613, 0xc0001ab730, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13/libexec/src/reflect/value.go:321 +0xb4
github.com/pingcap/check.(*suiteRunner).forkTest.func1(0xc00041c000)
	/Users/zhuangtianyi/go/pkg/mod/github.com/pingcap/check@v0.0.0-20191107115940-caf2b9e6ccf4/check.go:836 +0x5e4
github.com/pingcap/check.(*suiteRunner).forkCall.func1(0xc000200780, 0xc00041c000, 0xc000414560)
	/Users/zhuangtianyi/go/pkg/mod/github.com/pingcap/check@v0.0.0-20191107115940-caf2b9e6ccf4/check.go:730 +0xa2
created by github.com/pingcap/check.(*suiteRunner).forkCall
	/Users/zhuangtianyi/go/pkg/mod/github.com/pingcap/check@v0.0.0-20191107115940-caf2b9e6ccf4/check.go:727 +0x233
PASS: expr_to_pb_test.go:423: testEvaluatorSerialSuites.TestPushDownSwitcher	0.002s
OK: 1 passed
PASS
ok  	github.com/pingcap/tidb/expression	0.028s
```

The related code is 

```go
	pbExprs := ExpressionsToPBList(sc, funcs, client)
	fmt.Println(sc)
	fmt.Println(funcs)
	fmt.Println(pbExprs)
	c.Assert(len(pbExprs), Equals, len(cases))
	for i, pbExpr := range pbExprs {
		c.Assert(pbExpr.Sig, Equals, cases[i].sig, Commentf("function: %s, sig: %v", cases[i].name, cases[i].sig))
	}
```

It seems that `ExpressionsToPBList` return some expr is nil, step into `pc.ExprToPB` and `pc.scalarFuncToPBExpr`, and add log, we can find the push down test failed.

```go
if !pc.canFuncBePushed(expr) {
		fmt.Println("cannot be pushed")
		return nil
	}
```

and the failed sig name is `bitand` and `bitor` .

**Comment by wshwsh12** [comment]
In test check_dev_2 , it gets the fail information. The function builtinTruncateDecimalSig test fails.
```

[2019-11-11T04:46:33.416Z] FAIL: builtin_math_vec_test.go:128: testEvaluatorSuite.TestVectorizedBuiltinMathEvalOneVec

[2019-11-11T04:46:33.416Z] 

[2019-11-11T04:46:33.416Z] builtin_math_vec_test.go:129:

[2019-11-11T04:46:33.416Z]     testVectorizedEvalOneVec(c, vecBuiltinMathCases)

[2019-11-11T04:46:33.416Z] bench_test.go:703:

[2019-11-11T04:46:33.416Z]     c.Assert(c1.GetDecimal(i), DeepEquals, c2.GetDecimal(i), commentf(i))

[2019-11-11T04:46:33.416Z] ... obtained *types.MyDecimal = &types.MyDecimal{digitsInt:5, digitsFrac:0, resultFrac:0, negative:true, wordBuf:[9]int32{22830, 0, 0, 0, 0, 0, 0, 0, 0}} ("-22830")

[2019-11-11T04:46:33.416Z] ... expected *types.MyDecimal = &types.MyDecimal{digitsInt:9, digitsFrac:0, resultFrac:0, negative:true, wordBuf:[9]int32{22830, 0, 0, 0, 0, 0, 0, 0, 0}} ("-22830")

[2019-11-11T04:46:33.416Z] ... func: truncate, case {retEvalType:2 childrenTypes:[2 0] childrenFieldTypes:[] geners:[]}, row: 3, rowData: [KindMysqlDecimal -22836.51837038447 KindInt64 482415128859956966]

[2019-11-11T04:46:33.416Z] 

[2019-11-11T04:46:33.416Z] 

[2019-11-11T04:46:33.416Z] ----------------------------------------------------------------------

[2019-11-11T04:46:33.416Z] FAIL: builtin_math_vec_test.go:132: testEvaluatorSuite.TestVectorizedBuiltinMathFunc

[2019-11-11T04:46:33.416Z] 

[2019-11-11T04:46:33.416Z] builtin_math_vec_test.go:133:

[2019-11-11T04:46:33.416Z]     testVectorizedBuiltinFunc(c, vecBuiltinMathCases)

[2019-11-11T04:46:33.416Z] bench_test.go:925:

[2019-11-11T04:46:33.416Z]     c.Assert(*val, Equals, d64s[i], commentf(i))

[2019-11-11T04:46:33.416Z] ... obtained types.MyDecimal = types.MyDecimal{digitsInt:9, digitsFrac:0, resultFrac:0, negative:false, wordBuf:[9]int32{65750, 0, 0, 0, 0, 0, 0, 0, 0}}

[2019-11-11T04:46:33.416Z] ... expected types.MyDecimal = types.MyDecimal{digitsInt:5, digitsFrac:0, resultFrac:0, negative:false, wordBuf:[9]int32{65750, 0, 0, 0, 0, 0, 0, 0, 0}}

[2019-11-11T04:46:33.416Z] ... func: builtinTruncateDecimalSig, case {retEvalType:2 childrenTypes:[2 0] childrenFieldTypes:[] geners:[]}, row: 0, rowData: [KindMysqlDecimal 65751.60245442681 KindInt64 8024523578360680140]
```

**Comment by TennyZhuang** [comment]
I find the bug.

```
// Round rounds the decimal to "frac" digits.
//
//    to			- result buffer. d == to is allowed
//    frac			- to what position after fraction point to round. can be negative!
//    roundMode		- round to nearest even or truncate
// 			ModeHalfEven rounds normally.
// 			Truncate just truncates the decimal.
//
```

Comment in `MyDecimal.Round` said that d == to is allowed, but if I update my code to use a new result variable instead of inplace Round, the bug is fixed.

**Comment by TennyZhuang** [comment]
@wshwsh12 PTAL

I fix this by use a new variable simply, I think the fix on `Round` method (or fix the comment) should be done in another PR.

**Comment by TennyZhuang** [comment]
@wshwsh12 PTAL, we have got 350 points in PCP and really hope the PR to be merged as soon as possible.

**Comment by TennyZhuang** [comment]
```
[2019-11-12T03:46:47.243Z] --- FAIL: TestSyncerSimple (0.92s)

[2019-11-12T03:46:47.243Z]     syncer_test.go:144: update self version failed context deadline exceeded

[2019-11-12T03:46:47.243Z]         github.com/pingcap/errors.AddStack

[2019-11-12T03:46:47.243Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/errors@v0.11.4/errors.go:174

[2019-11-12T03:46:47.243Z]         github.com/pingcap/errors.Trace

[2019-11-12T03:46:47.243Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/errors@v0.11.4/juju_adaptor.go:15

[2019-11-12T03:46:47.243Z]         github.com/pingcap/tidb/ddl/util.PutKVToEtcd

[2019-11-12T03:46:47.243Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/util/syncer.go:154

[2019-11-12T03:46:47.243Z]         github.com/pingcap/tidb/ddl/util.(*schemaVersionSyncer).UpdateSelfVersion

[2019-11-12T03:46:47.243Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/util/syncer.go:264

[2019-11-12T03:46:47.243Z]         github.com/pingcap/tidb/ddl/util_test.TestSyncerSimple

[2019-11-12T03:46:47.243Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/util/syncer_test.go:142

[2019-11-12T03:46:47.243Z]         testing.tRunner

[2019-11-12T03:46:47.243Z]         	/usr/local/go/src/testing/testing.go:909

[2019-11-12T03:46:47.243Z]         runtime.goexit

[2019-11-12T03:46:47.243Z]         	/usr/local/go/src/runtime/asm_amd64.s:1357
```

It seems something break in CI?

**Pull request merged**
