### PR TITLE
*: fix the issue of executing DDL after executing SQL failure in txn …

### PR DESCRIPTION
**Pull request by zimulala**
* ddl, executor: fix the issue of executing DDL after executing SQL failure in txn

### What problem does this PR solve? 
cherry-pick #8044 
Fix the issue of the following case:

- Execute the SQL of "begin";
- A SQL that will fail to execute;
- Execute DDL.

### CODE REVIEW

**Comment by zz-jason** [comment]
@zimulala There is a data race in "unit-test"

**Comment by zimulala** [comment]
@zz-jason 
It's an unstable test. This issue is not related to the current PR.
I will rerun this test.

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
