### PR TITLE
 table: check non-BMP characters and return error when the charset is utf8 and sql mode is strict mode

### PR DESCRIPTION
**Pull request by winkyao**
### What problem does this PR solve? 

Before this PR, TiDB don't handle the [non-BMP character](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane) when the charset is utf8. Run the sqls in mysql:

```
mysql> create table t1(a varchar(100) charset utf8);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values(x'f09f8c80');
ERROR 1366 (HY000): Incorrect string value: '\xF0\x9F\x8C\x80' for column 'a' at row 1
```

But in TiDB:

```
mysql> create table t1(a varchar(100) charset utf8);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values(x'f09f8c80');
Query OK, 1 row affected (0.00 sec)
```

### What is changed and how it works?

utf8 cannot handle the Unicode character length larger than 3.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8738)

### CODE REVIEW

**Comment by winkyao** [comment]
@kennytm PTAL

**Comment by shenli** [comment]
@tiancaiamao @jackysp @lysu PTAL

**Comment by winkyao** [comment]
@ciscoxll This PR will break back compability, I will not pick it to 2.0 and I'am considering to pick to 2.1

**Pull request merged**
