### PR TITLE
 types: fix incorrect order of set resultFrac

### LINKED ISSUE #7781: Precision of aggregation's result for exact value is wrong.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create table t(a int, b int);
insert into t values(1, 0), (2, 1), (2, 2);
select avg(b) from t group by a;
```

2. What did you expect to see?
The result should be `0.0000` and `1.500`.

3. What did you see instead?
It's `0` and `1.500`.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master with commit f387dfff09068f1bde478a287897a03e0dabcf6f.

### PR DESCRIPTION
**Pull request by Kingwl**
### What problem does this PR solve? 
fix #7781

and another pr https://github.com/pingcap/tidb/pull/7809

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by Kingwl** [comment]
```
mysql> select avg(`col_decimal_6_3_signed`) as a from `table20_int_autoinc` group by `col_decimal_10_4_unsigned`, `col_decimal_40_20_unsigned_key` order by a;
+-------------+
| a           |
+-------------+
|  -9.1820000 |
|  -5.0910000 |
|  -1.0000000 |
|  -1.0000000 |
|   0.0000000 |
|   0.0000000 |
|   0.0000000 |
|   0.0000000 |
|   0.1120000 |
|   0.1120000 |
|  12.9870000 |
|  12.9870000 |
|  12.9910000 |
| 296.3300000 |
+-------------+
14 rows in set (0.00 sec)
```

**Comment by Kingwl** [comment]
@winoros  PLAT

the result of `-1.000 decimal + 1.000 decimal` is `0 decimal` (`resultFrac` is 3)  
after the serialize and deserialize, the` resultFrac` is missing and reset to `zero` by `PrecisionAndFrac` in the encode/decode, 
that means`avg` has calculated the `0 decimal / n` with fracIncr 4, and the result is 0.0000


i'm not sure what is the expect behavior:

1. set the result of `-1.000 decimal + 1.000 decimal` is `0.000 decimal` ?
seems a huge break change
2. keep the decimal add/sub and  use `resultFrac` for `PrecisionAndFrac`?

**Comment by winoros** [comment]
@XuHuaiyu PTAL

**Comment by zz-jason** [comment]
@Kingwl Thanks for your contribution! Please fix the CI firstly. You can run `make test` to run all the unit tests.

**Comment by Kingwl** [comment]
@zz-jason 
I'm not sure what is the expected behavior (to add test case)  yet🤷🏻‍♂️

**Comment by zz-jason** [comment]
@Kingwl For now, TiDB is aimed to be compatible with MySQL 5.7, maybe you can take a look at the result of MySQL?

**Comment by zz-jason** [comment]
LGTM

**Comment by zz-jason** [comment]
@XuHuaiyu PTAL

**Comment by XuHuaiyu** [comment]
hi, @Kingwl 
It seems that the problem mentioned in that issue has been fixed in master branch.

**Comment by Kingwl** [comment]
@XuHuaiyu what problem?

**Comment by Kingwl** [comment]
any update?

**Comment by zz-jason** [comment]
@Kingwl I think @XuHuaiyu is talking about this issue: https://github.com/pingcap/tidb/issues/7781

**Comment by XuHuaiyu** [comment]
Sorry for late reply, what I mentioned before is #7781

**Comment by zz-jason** [comment]
@Kingwl Any update?

**Pull request closed without merging**
