### PR TITLE
telemetry: Block logs when referenced by other components outside tidb

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

This log info will be print on `stdout` when other components reference this pkg.

### What is changed and how it works?

Proposal: If this pkg is referenced by other components, variable `mysql.TiDBReleaseVersion` is `"None"`

What's Changed: add an if condition to block logs.

### Related changes

- Need to cherry-pick to the release branch

### Release note 

- No release note

### CODE REVIEW

**Comment by Leavrth** [comment]
@kaixu120811 PTAL

**Review by Little-Wallace — APPROVED** [review]
LGTM

**Review by lonng — COMMENTED** [review]
/lgtm

**Review by lonng — APPROVED** [review]

**Comment by sticnarf** [comment]
When I execute commands like `tidb-server -V`, `"Telemetry slow query stats initialized"` appears to my stdout. It appears not reasonable to me.

**Comment by Leavrth** [comment]
> When I execute commands like `tidb-server -V`, `"Telemetry slow query stats initialized"` appears to my stdout. It still appears not reasonable to me.

It seems `stdout` is default output stream for `pingcap/log`, and these info logs are print before logutil is initialized. I'm not sure whether this log info is necessary. @kaixu120811 @lysu

**Pull request merged**
