### PR TITLE
Remove ineffectual assignment to joinedRow

### PR DESCRIPTION
**Pull request by JackDrogon**
Remove ineffectual assignment to joinedRow.

### CODE REVIEW

**Comment by shenli** [comment]
@JackDrogon Thanks!

**Comment by zz-jason** [comment]
@JackDrogon It should not be removed, for **left outer semi join** and **anti left outer semi join**, we should output the outer row and a boolean value to indicate where there exists an inner row witch can be joined with the outer row(satisfy the join condition)

**Comment by JackDrogon** [comment]
@zz-jason joinedRow's value is replace by  the next line `joinedRow = append(outer, types.NewDatum(false))`, so `joinedRow = joinedRow[:len(outer)]` has no effect.

**Comment by zz-jason** [comment]
@JackDrogon I see. The correct way is:
```go
joinedRow = joinedRow[:len(outer)]		
joinedRow = append(joinedRow, types.NewDatum(true)) // or `false`
return append(resultBuffer, joinedRow), true, nil
```
this can avoid `runtime.growslice` on `outer`

**Comment by JackDrogon** [comment]
@zz-jason The code is `joinedRow = append(outer, types.NewDatum(false))`, not `joinedRow = append(joinedRow, types.NewDatum(true))`. So the code is changed to ` joinedRow = append(joinedRow[:len(outer)], types.NewDatum(true))`. I updated the code.

**Comment by JackDrogon** [comment]
I git cmmit --amed, so the ci may be failed.

**Pull request merged**
