### PR TITLE
*: Add `temp_table_size` support for local temporary table

### LINKED ISSUE #25928: Memory size does not exceed `temp_table_size`

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #25928 

Add `temp_table_size` support for local temporary table. `temp_table_size` should also limit the committed data in session.

### What is changed and how it works?

Create a new interface `variable.TemporaryTableData` to mange temporary table data. `SetTableKey` and `DeleteTableKey` will recompute size of table atomically

### Check List 

Tests 

- [x] Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

**Review by djshow832 — APPROVED** [review]
I have a concern: When a session has 800M data in the session data, and the user deletes all of the data in a new transaction, then it reports memory full because the deleted data occupies the transaction data. 
It looks weird to users. However, I have no better ideas...

**Pull request merged**
