### PR TITLE
ddl: fix the bug of maximum length limit of identifier #24288

### LINKED ISSUE #24288: Field length limit
When migrating from MySQL data, you can create a maximum of 21 Chinese characters when creating fields in Chinese.
Not fully compatible with MySQL.
Mysql supports Column creation with 64 characters
The official documentation says the maximum is 64 bits

image

image
image

### LINKED ISSUE #24377: When synchronizing data, the length of MySQL table name and field name is legal, but tidb is not
1. What did you do? If possible, provide a recipe for reproducing the error.

   MySQL synchronizes data to tidb, but the table name and field name are in Chinese

2. What did you expect to see?

   Even if the table name and field name are in Chinese, the synchronization is successful

3. What did you see instead?

   Identifier name '啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊' is too long

4. Versions of the cluster
   dm：v2.0.0
   tidb:  5.0

### PR DESCRIPTION
**Pull request by Al-assad**
### What problem does this PR solve?

Issue Number: fix #24288, fix #24377

Problem Summary: The maximum character length limit on identifier length does not apply to utf8 characters, such as Chinese characters. 
see: https://docs.pingcap.com/tidb/stable/tidb-limitations#limitations-on-identifier-length

### What is changed and how it works?

Change the length of the identifier string from `len()`  to `utf8.RunCountInString()` when checking the length of the schema, table, index, column identifier strings in DDL.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Comment by morgo** [comment]
@Al-assad can you add an integration test where you create a table with a column that is > mysql.MaxDatabaseNameLength bytes, but less than mysql.MaxDatabaseNameLength characters?

**Comment by Al-assad** [comment]
> @Al-assad can you add an integration test where you create a table with a column that is > mysql.MaxDatabaseNameLength bytes, but less than mysql.MaxDatabaseNameLength characters?

okay

**Comment by Al-assad** [comment]
> @Al-assad can you add an integration test where you create a table with a column that is > mysql.MaxDatabaseNameLength bytes, but less than mysql.MaxDatabaseNameLength characters?

I have added the appropriate test code to the `ddl/db_test.go `

**Review by xiongjiwei — APPROVED** [review]
/lgtm

**Review by tangenta — APPROVED** [review]

**Pull request merged**
