### PR TITLE
store/tikv: move mocktikv into tikv

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?
mocktikv is used by many unit tests inside store/tikv.

Part of https://github.com/pingcap/tidb/issues/22513

### What is changed and how it works?
What's Changed:
- move mocktikv into store/tikv

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Comment by tisonkun** [comment]
Hi @disksing , I'd like to know what is the difference between mocktikv and the [mock-tikv](https://github.com/tikv/mock-tikv) project. Shall we merge them later?

**Review by AndreMouche — APPROVED** [review]
LGTM

**Comment by disksing** [comment]
> Hi @disksing , I'd like to know what is the difference between mocktikv and the [mock-tikv](https://github.com/tikv/mock-tikv) project. Shall we merge them later?

The original mock-tikv was for the previous client-go (to avoid dependencies on TiDB). The mocktikv will then be moved out of the TiDB codebase along with store/tikv, so the two mock-tikv's will eventually be merged.

**Review by JmPotato — APPROVED** [review]

**Pull request merged**
