### PR TITLE
ddl: create linear hash partition and sub partition table as normal table

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Problem Summary:

We do not support `linear hash` partitioned table and `sub partition` option.
It's better to create the table as normal table, rather than ignore those option.

### What is changed and how it works?

Create as normal table in those cases.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

https://github.com/pingcap/automated-tests/pull/191

Side effects

- Breaking backward compatibility

The behavior slightly chage, but should not affect trouble the user too much.

### Release note 

- Prior to TiDB 4.0, create table with sub-partition or linear hash options are treated as partition table with the options ignored. Now those cases are created as normal tables.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @XuHuaiyu @imtbkcat @jackysp

**Comment by tiancaiamao** [comment]
/run-all-tests

@zimulala

**Comment by jackysp** [comment]
PTAL @zimulala

**Comment by tiancaiamao** [comment]
/rebuild

```
[2020-05-14T02:52:15.540Z] ----------------------------------------------------------------------
[2020-05-14T02:52:15.540Z] FAIL: executor_test.go:4247: testSplitTable.TestShowTableRegion
[2020-05-14T02:52:15.540Z] 
[2020-05-14T02:52:15.540Z] executor_test.go:4326:
[2020-05-14T02:52:15.540Z]     // Check the region start key.
[2020-05-14T02:52:15.540Z]     c.Assert(rows[0][1], Equals, fmt.Sprintf("t_%d_", tbl.Meta().ID))
[2020-05-14T02:52:15.540Z] ... obtained string = "t_45_5f728000000000001388"
[2020-05-14T02:52:15.540Z] ... expected string = "t_48_"
```

https://github.com/pingcap/tidb/issues/17189

**Comment by tiancaiamao** [comment]
/rebuild

```
[2020-05-14T03:08:25.027Z] ----------------------------------------------------------------------
[2020-05-14T03:08:25.027Z] FAIL: trackerrecorder_test.go:63: trackRecorderSuite.TestHeapProfileRecorder
[2020-05-14T03:08:25.027Z] 
[2020-05-14T03:08:25.027Z] trackerrecorder_test.go:77:
[2020-05-14T03:08:25.027Z]     // ensure that the consumed bytes is at least larger than 10000 * size of value
[2020-05-14T03:08:25.027Z]     c.Assert(int64(valueSize*10000), LessEqual, bytes
[2020-05-14T03:08:25.027Z] ... compare_one int64 = 160000
[2020-05-14T03:08:25.027Z] ... compare_two int64 = 0
```


https://github.com/pingcap/tidb/issues/17190

**Pull request merged**
