### PR TITLE
planner: disable non-prep plan cache by default

### LINKED ISSUE #36598: Support general plan cache
## Feature Request

**Is your feature request related to a problem? Please describe:**

TP queries can get lots of performance benefits from Plan Cache, but the current [TiDB Plan Cache](https://docs.pingcap.com/tidb/dev/sql-prepared-plan-cache) can only support [Prepare](https://docs.pingcap.com/tidb/dev/sql-statement-prepare)/[Execute](https://docs.pingcap.com/tidb/v5.0/sql-statement-execute) Statements. Most of our users are still using general queries to access TiDB instead of Prepare/Execute. So if Plan Cache can support general queries, these users can gain some performance benefits as well.

**Describe the feature you'd like:**

When we execute the general query, we can skip the parser and optimizer phase to directly get the physical plan from the plan cache. That can save more time for the TP queries.

**Teachability, Documentation, Adoption, Migration Strategy:**

The detail design will be posted later.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #36598

Problem Summary: planner: disable non-prep plan cache by default

### What is changed and how it works?

Non-Prep plan cache causes some extra memory usage, to make the default behavior more stable, disable this feature by default and let users turn on this feature manually if they need.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Comment by hawkingrei** [comment]
@easonn7 PTAL

**Comment by qw4990** [comment]
> /approve
> 
> Non-prepared plan cache is turned off by default, primarily to enhance stability. The plan is to consider enabling non-prepared plan cache by default once it becomes stable in the future.

Of course, in the past 2 sprints, we've solved some suboptimal plan issues and memory issues caused by the Plan Cache. We'll observe for a few sprints to make sure these issues have been thoroughly resolved, and once we think it's stable enough, we'll try to enable this feature agian.

**Review by XuHuaiyu — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by Defined2014 — APPROVED** [review]

**Comment by MimeLyc** [comment]
update

**Pull request merged**
