### PR TITLE
expression: support push down tikv supported functions

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/31846

### What is changed and how it works?

push following functions down to TiKV, they are already supported in TiKV accoriding to https://github.com/tikv/tikv/issues/5751

math:

* pi/round/truncate

string:

* bin, locate, unhex, lpad, rpad, ord
* trim, from_base64, to_base64, upper
* makeset, substringIndex, Instr, Quote, Oct
* find_in_set, repeat

### Check List

Tests 

- [x] Unit test
- [x] Integration test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by LittleFall — APPROVED** [review]

**Comment by LittleFall** [comment]
test failed on:
```
[2022-02-09T09:22:07.191Z] [2022/02/09 17:22:06.676 +08:00] [FATAL] [main.go:758] ["run test"] [test=explain_generate_column_substitute] [error="sql:desc format = 'brief' select count(upper(b)) from t use index() group by upper(b);: run \"desc format = 'brief' select count(upper(b)) from t use index() group by upper(b);\" at line 194 err, we need:
desc format = 'brief' select count(upper(b)) from t use index() group by upper(b);
id\testRows\ttask\taccess object\toperator info
HashAgg\t6.00\troot\t\tgroup by:Column#9, funcs:count(Column#8)->Column#7
└─Projection\t6.00\troot\t\tupper(test.t.b)->Column#8, upper(test.t.b)->Column#9
  └─TableReader\t6.00\troot\t\tdata:TableFullScan
    └─TableFullScan\t6.00\tcop[tikv]\ttable:t\tkeep order:false
    desc
but got:
desc format = 'brief' select count(upper(b)) from t use index() group by upper(b);
id\testRows\ttask\taccess object\toperator info
HashAgg\t6.00\troot\t\tgroup by:Column#11, funcs:count(Column#10)->Column#7
└─Projection\t6.00\troot\t\tupper(test.t.b)->Column#10, upper(test.t.b)->Column#11
  └─TableReader\t6.00\troot\t\tdata:TableFullScan
    └─TableFullScan\t6.00\tcop[tikv]\ttable:t\tkeep order:false
    
```

**Review by rebelice — APPROVED** [review]

**Pull request merged**
