### PR TITLE
Fix error result union scan with apply (#19245)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19245 to release-3.1

---

### What problem does this PR solve?

Issue Number: partially solved #19136  for version before 4.0

Problem Summary:

Apply executor would read UnionScan multiple times, so we need to reset some variables in the executor.

### What is changed and how it works?

What's Changed:

Implement Close for UnionScan.

### Related changes

- Need to cherry-pick to the 4.0, 3.0 and 3.1

### Check List 

Tests 

- Unit test

Side effects

No side effects.

### Release note 

- Fix error result of apply with union scan on 4.0, 3.0 and 3.1.

### CODE REVIEW

**Comment by ichn-hu** [comment]
@SunRunAway @wshwsh12 PTAL~~

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Comment by ichn-hu** [comment]
@SunRunAway PTAL

**Comment by ichn-hu** [comment]
This PR will block https://github.com/pingcap/tidb/pull/19469

**Review by SunRunAway — APPROVED** [review]

**Pull request merged**
