### PR TITLE
statistics: use swiss table to improve fmsketch

### LINKED ISSUE #47057: Optimize HashMap Implementation Using Swiss Table
## Enhancement

The current implementation of our HashMap in the Go project could benefit from significant optimization. One such improvement could be achieved by adopting a Swiss Table (also known as Swiss HashMap) approach.

Our current HashMap implementation, while functional, is not as efficient as it could be. There's unnecessary memory usage due to the handling of collisions and overall performance could be improved. Swiss Table, a variant of the hash table that uses a combination of open addressing and SIMD instructions, is known for its high load factor, good cache performance, and memory efficiency.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #47057

Problem Summary:

### What is changed and how it works?

fmsketch's hashmap is so big. it slows the copy speed and use many memory. we use swiss table to replace it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

before:

image

after:

image

more less usage of memory

before:

image

after:

image

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]
The changes look good to me. But I am still not sure if is it a good idea to introduce this dep.

cc: @qw4990 Do you have any thoughts about this?

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
