### PR TITLE
sessionctx: fix wrong `skipInit` for tidb_enable_paging

### PR DESCRIPTION
**Pull request by you06**
Signed-off-by: you06 <you1474600@gmail.com>

### What problem does this PR solve?

Issue Number: ref #30578

Problem Summary:

### What is changed and how it works?

#30536 introduced `tidb_enable_paging` which is the switch of coprocessor paging. This PR fixes the wrong `skipInit` of that sysvar.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by youjiali1995 — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

**Comment by you06** [comment]
@youjiali1995 can you help me merge this PR?

**Pull request merged**
