### PR TITLE
util: fix unstable test TestCheckCN

### LINKED ISSUE #36866: unstable test TestCheckCN
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2022-08-03T13:19:31.445Z]     security_test.go:141: 

[2022-08-03T13:19:31.445Z]         	Error Trace:	security_test.go:141

[2022-08-03T13:19:31.445Z]         	Error:      	Expect "Get "https://127.0.0.1:9292/": write tcp 127.0.0.1:60364->127.0.0.1:9292: write: connection reset by peer" to match ".*tls: bad certificate"

[2022-08-03T13:19:31.445Z]         	Test:       	TestCheckCN
```

https://prow.pingcap.net/view/gs/pingcapprow/logs/bazel_test_tidb/1560490278320607232#1:build-log.txt%3A142

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: ref #36866

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
Try 3 times without any flaky.

**Review by xhebox — APPROVED** [review]

**Comment by Defined2014** [comment]
Don't understand why it can avoid get error like https://github.com/pingcap/tidb/issues/36866

**Comment by hawkingrei** [comment]
> Don't understand why it can avoid get error like #36866, the error msg looks like the server are closed.

I also don't understand it so I just improve the code style and reference the issue to avoid closing it. it needs to test more times.

**Review by Defined2014 — APPROVED** [review]

**Pull request merged**
