### PR TITLE
*:Fix the bug of consistent plan but inconsistent plan digest (#20660)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20660 to release-4.0

---

Signed-off-by: jyz0309 <45495947@qq.com>

### What problem does this PR solve?

Problem Summary:
When the execution plan is the same, the number of plans displayed in tidb-dashboard may be inconsistent and more because of the partition table.
For example:
```
# Plan_digest: 37e378a2cb4384941179b1bb16525596bcde0775242e136aabceb385a437d6bc
select * from t3 where a<5;
```
```
# Plan_digest: 47507992976b9903d5d2e85b2a1973c2f249769e387576dc19ee8500fb8fd6d9
select * from t3 where a<20;
```
### What is changed and how it works?

What's Changed:
Move the Partition field from PointGetPlan AccessObject() function to OberatorInfo function. 

How it Works:
When tidb need to get the PointGetPlan digest, we can make `partition:?` by setting `normalized` true.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU

### Release note 
- Fix the bug of consistent PointGetPlan but inconsistent plan digest

### CODE REVIEW

**Comment by crazycs520** [comment]
@jyz0309  Please resolve the conflict.

**Review by eurekaka — COMMENTED** [review]
LGTM

**Review by crazycs520 — APPROVED** [review]
LGTM

**Pull request merged**
