### PR TITLE
Close PD client in tikv store and raw kv.

### PR DESCRIPTION
**Pull request by huachaohuang**

### CODE REVIEW

**Comment by shenli** [comment]
What's the benefit of this PR?

**Comment by huachaohuang** [comment]
For example, our benchbot test case will open `tikv.Driver` or `RawKVClient` on each run, if we don't close it, it will cause two problems:
1. The connection will be leaked on each run;
2. The unclosed client will keep printing error messages to the logs.

**Comment by huachaohuang** [comment]
PTAL @disksing @zimulala

**Comment by disksing** [comment]
LGTM.

**Comment by shenli** [comment]
LGTM

**Pull request merged**
