### PR TITLE
ddl: rename `setval` func for generated column 

### PR DESCRIPTION
**Pull request by AilinKid**
### What problem does this PR solve? 
`setval` is specialized for sequence function with `(tableName, num)` as parameters.
here `setval("string", num)` is a arbitrary function tested for generated column error. 
So we rename it here cleaning the way for sequence `setval` function.

### What is changed and how it works?
just rename `setval` in error generated column code test.

### Check List 

Tests 

 - Unit test
 - Integration test

Release note

 - rename `setval` func for generated column.

### CODE REVIEW

**Comment by Deardrops** [comment]
Wait, use `setval` or `setvalue`, both are OK in this test case?

**Comment by bb7133** [comment]
> Wait, use `setval` or `setvalue`, both are OK in this test case?

Why not?

**Comment by AilinKid** [comment]
> Wait, use `setval` or `setvalue`, both are OK in this test case?

because you haven't updated the newer parser (which is in review)

**Comment by Deardrops** [comment]
I mean, if both of them are OK, the changes in this PR is not neccessary.

**Comment by AilinKid** [comment]
> I mean, if both of them are OK, the changes in this PR is not necessary.

With newer parser, the setval("string", num) will fail, cause "" is not an identifier for  tableName.

**Pull request merged**
