### PR TITLE
expression: fix compatibility behaviors in time_format with MySQL (#21559)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21559 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/12206 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
1. Change the ErrType to ErrTruncatedWrongVal when convert number to duration.
2. Handle ErrTruncatedWrongVal in built function builtinCastIntAsDurationSig

How it Works:

### Related changes

- Need to cherry-pick to the release branch 3.0,4.0

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- fix compatibility behaviors in time_format with MySQL

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
LGTM

**Review by lzmhhh123 — APPROVED** [review]
LGTM

**Comment by qw4990** [comment]
Need to fix coprocessor first.

**Comment by qw4990** [comment]
/run-all-tests

**Pull request closed without merging**
