### PR TITLE
workflow: backport-x.y.z to fixes-x.y.z

### LINKED ISSUE #28114: Tag closed bug with fixes-x.y.z instead of backport-x.y.z
... which makes it clear that we are handling issues as well as fixes-x.y.0 on an unreleased version read reasonable.

### PR DESCRIPTION
**Pull request by tisonkun**
### What problem does this PR solve?

Issue Number: close #28114

### Release note

```release-note
None
```

### CODE REVIEW

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Review by jebter — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
/cc @bb7133 

Please take a look.

**Comment by tisonkun** [comment]
@jebter which labels of `fixes-x.y.z` should we create?

**Comment by jebter** [comment]
4.0.

> @jebter which labels of `fixes-x.y.z` should we create?
> 
> If we start from now one, we can use all current unreleased version:
> 
> * 3.0.?
> * 4.0.?
> * 5.0.?
> * 5.1.?
> * 5.2.?
> * 5.3.0

- 4.0.16
- 5.0.5
- 5.1.3
- 5.2.2
- 5.3.0

**Comment by bb7133** [comment]
LGTM

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
