### PR TITLE
executor: implement sequence view

### PR DESCRIPTION
**Pull request by AndrewDi**
### What problem does this PR solve? 
implement feature #15388 

### What is changed and how it works?
implement `sequences` view in `information_schema`;

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported variable/fields change

### CODE REVIEW

**Comment by AilinKid** [comment]
PTAL @crazycs520

**Comment by Deardrops** [comment]
@AndrewDi Please resolve conflicts before merge this PR

**Pull request merged**
