### PR TITLE
session: Adjust cop-tasks' information in slow log to let it can be parsed by `pt-query` correctly

### PR DESCRIPTION
**Pull request by qw4990**
cherry-pick for #10230.

### CODE REVIEW

**Comment by qw4990** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by qw4990** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by qw4990** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by crazycs520** [comment]
/run-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by qw4990** [comment]
/run-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by crazycs520** [comment]
@qw4990 Why this PR don't contain `Cop_proc_addr ` and `Cop_wait_addr `?

**Pull request merged**
