### PR TITLE
planner: fix join using

### LINKED ISSUE #20476: ERROR 1051 (42S02): Unknown table 't2'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
drop table if exists t1;
create table t1(a int);
select t1.*, t2.* from t1 join t1 t2 using(a);
```
### 2. What did you expect to see? (Required)
```
mysql> select t1.*, t2.* from t1 join t1 t2;
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> select t1.*, t2.* from t1 join t1 t2 using(a);
ERROR 1051 (42S02): Unknown table 't2'
```

### 4. What is your TiDB version? (Required)

master cd16de894b4bc523bc6b7dd6241ab6f0e608a6fb and release-4.0 c71000046cf1c5ade501cc2b14d3b130863f366d

### PR DESCRIPTION
**Pull request by b41sh**
### What problem does this PR solve?

Issue Number: close #20476 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:
use `redundantNames` to build `resultList` in `unfoldWildStar`

### Check List 

Tests 

- Unit test

### Release note 

- fix join using

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
@b41sh Is this PR ready to be reviewed?

**Comment by b41sh** [comment]
> @b41sh Is this PR ready to be reviewed?

@XuHuaiyu  I haven't finished it yet, it will take a while.

**Comment by b41sh** [comment]
@XuHuaiyu @qw4990  PTAL

**Comment by XuHuaiyu** [comment]
I found that this issue can also be fixed by https://github.com/pingcap/tidb/pull/20977

**Comment by b41sh** [comment]
> I found that this issue can also be fixed by #20977

ok, I close this PR.

**Pull request closed without merging**
