### PR TITLE
variable: make the default value of wait_timeout the same as MySQL

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:
The default value of wait_timeout is not the same as MySQL.

### What is changed and how it works?
Make it same. By default, idle connections on TiDB have not been automatically disconnected in the past, after this change, idle connections will be automatically disconnected after 8 hours. This is consistent with MySQL.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [x] Performance regression: Consumes more CPU (for the default value)
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

```release-note
Make the default value of wait_timeout the same as MySQL (8 hours).
```

### CODE REVIEW

**Review by bb7133 — COMMENTED** [review]
LGTM

**Review by bb7133 — APPROVED** [review]

**Review by wjhuang2016 — COMMENTED** [review]
What's the change of behavior? Please make it clear in the description.

**Comment by jackysp** [comment]
> What's the change of behavior? Please make it clear in the description.

Done.

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
