### PR TITLE
ddl: fix bug introduced by 19222

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Problem Summary: `physicalTableIDs` is not updated by `updateDroppingPartitionInfo`, thus `dropRuleBundles` becomes useless. How does it look like before #19222:

https://github.com/pingcap/tidb/blob/62190f376d90ea087464f0da0f4fa6207304c4cb/ddl/partition.go#L1003-L1015

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Start pd-server, tikv-server, tidb-server(PD is excepted to have newer version than a26d9cf), enable placement rules using pd-ctl.

1. `alter table t alter partition p0 add placement policy constraints='{"+zone=sh":1, "-zone=bj": 2}' role=voter replicas=4;`, excepts some new placement rules using pd-ctl config placement-rules show.
2. `alter table t drop partition p0;`, new rules are dropped.

- [ ] No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Comment by bb7133** [comment]
@xhebox thanks, but could you please add a link for the related issue?

**Comment by xhebox** [comment]
> 
> 
> @xhebox thanks, but could you please add a link for the related issue?

No, he directly talked to me on the lark. If we want one issue, I can create one.

**Review by zimulala — COMMENTED** [review]
Does this PR do tests？ If do manual tests, please update the PR’s conversation.

**Review by AilinKid — COMMENTED** [review]
/LGTM

**Review by AilinKid — APPROVED** [review]

**Comment by xhebox** [comment]
> 
> 
> Does this PR do tests？ If do manual tests, please update the PR’s conversation.

Updated, there is no unit test due to the lack of PD.

**Pull request merged**
