### PR TITLE
planner: fix {index,hash,merge} join on range suffix condition clustered index

### LINKED ISSUE #23289: Another issue when using index join with prefixed clustered index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set @@tidb_enable_clustered_index=1;
drop table if exists t1, t2;
create table t1  (c_int int, c_str varchar(40), primary key(c_int, c_str(4)), key(c_int), key(c_str));
create table t2  like t1 ;
insert into t1 values (1, 'nifty elion');
insert into t2 values (1, 'funny shaw');
select /*+ INL_JOIN(t1,t2) */  * from t1, t2 where t1.c_int = t2.c_int and t1.c_str >= t2.c_str;
```
similar issue: #23073 

### 2. What did you expect to see? (Required)

```
+-------+-------------+-------+------------+
| c_int | c_str       | c_int | c_str      |
+-------+-------------+-------+------------+
| 1     | nifty elion | 1     | funny shaw |
+-------+-------------+-------+------------+
```

### 3. What did you see instead (Required)

Empty set.

### 4. What is your TiDB version? (Required)

master (6d258c708a99e5c8ca9680fcdaae9edf680a85a2)

### PR DESCRIPTION
**Pull request by lysu**
Signed-off-by: lysu <sulifx@gmail.com>

### What problem does this PR solve?

Issue Number: close #23289 

Problem Summary:

miss pass `helper.lastColManager` in clustered index path.

so `a = 1 and b > 1` will miss `b >  1` condition and build wrong range

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed, How it Works:

 pass `helper.lastColManager` 

### Related changes

- n/a

### Check List 

Tests 

- n/a

Side effects

- n/a

### Release note 

- n/a

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/23294)

### CODE REVIEW

**Comment by lysu** [comment]
@coocood @lzmhhh123  PTAL

**Review by lzmhhh123 — APPROVED** [review]

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
