### PR TITLE
*: update parser to fix ODBC-styled literal

### LINKED ISSUE #25531: *: ODBC-styled datetime literal cannot be used in the expressions.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t(a datetime);
select * from t where a > {ts '2021-05-05 00:00:00.111'};
```

### 2. What did you expect to see? (Required)
The query runs successfully.

### 3. What did you see instead (Required)
```
tidb> select * from t where a > {ts '2021-05-05 00:00:00.111'};
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 29 near "ts '00:00:00.111'}" 
```
### 4. What is your TiDB version? (Required)
The error can be reproduced in all existing versions of TiDB.

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve?

Issue Number: close #25531 

Problem Summary:

### What is changed and how it works?

What's Changed: update parser to fix the issue.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test (see the parser PR: https://github.com/pingcap/parser/pull/1253)
- Manual test (see the related issue)

Side effects

- None

### Release note 

- Fix the issue that ODBC-styled literal(like `{d '2020-01-01'}`...) cannot be used as the expression.

### CODE REVIEW

**Comment by bb7133** [comment]
PTAL @pingcap/sql-infra-reviewers

**Review by wjhuang2016 — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
