### PR TITLE
executor: make IndexMergeReader support reading partition table directly

### LINKED ISSUE #24160: Support reading partition table for index merge reader
## Development Task
A subitem of https://github.com/pingcap/tidb/issues/24150.
To read partition tables, `IndexMergeReader` needs to be wrapped in another executor `PartitionTableExec`, since `PartitionTableExec` is not concurrent, so the performance is unacceptable.
To solve this problem, we decided to make `IndexMergeReader` support direct reading, which means it has the ability to read partition tables directly instead of being wrapped in another executor.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #24160 

Problem Summary: executor: make IndexMergeReader support reading partition table directly

### What is changed and how it works?
This PR makes `IndexMergeReader` support reading partition tables directly using the similar way with https://github.com/pingcap/tidb/pull/24197.

The picture below shows how we implement this feature:
1. build `KVReq` for each partition table separately;
2. let `IndexWorker` and `PKWorker` handle these `KVReqs` one by one;
3. delivery partition information to `MergeWorker` and `TableWorker` as well; 
image

### Check List 

Tests 

- Unit test

### Release note 

- executor: make IndexMergeReader support reading partition table directly

### CODE REVIEW

**Comment by qw4990** [comment]
Please help us review this PR at your convenience, @lysu @tiancaiamao 
Very appreciate your reviews 🧎 !

**Comment by qw4990** [comment]
PTAL @lysu

**Review by lysu — COMMENTED** [review]
/LGTM

**Pull request merged**
