### PR TITLE
Lightning: add retry if transaction failed while fetching task metas

### PR DESCRIPTION
**Pull request by guoshouyan**
updating this PR: https://github.com/pingcap/tidb/pull/53043

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by guoshouyan** [comment]
Hi @lance6716 , I'm trying to update this [PR](https://github.com/pingcap/tidb/pull/53043) and see if I can merge it, do you minding running the CI for it?

**Comment by guoshouyan** [comment]
Hi @lance6716 I try to add the ErrLockWaitTimeout as a retryable error as we spoke last time but it failed in the integration test. Could you help to shed some light on why it failed? From the log it's hard to tell why it failed
```

*************************** 1. row ***************************

count(i): 5000

  sum(i): 17502500

TEST FAILED: OUTPUT DOES NOT CONTAIN 'Row_count: 5000'

____________________________________

[Fri Aug 30 06:18:41 CST 2024] Executing SQL: SHOW STATS_META WHERE Table_name = 'tbl';

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

script returned exit code 1
```

**Comment by lance6716** [comment]
@guoshouyan The failure is not relevant to this PR. We are fixing it in master branch. The cause is we didn't run lightning CI for statistic module PR but the failure is related to statistic module.

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
Please sign CLA as the bot's instruction.

**Review by D3Hunter — APPROVED** [review]

**Comment by guoshouyan** [comment]
Hi @GMHDBJD , could you help to review this PR?

**Comment by lance6716** [comment]
> Hi @GMHDBJD , could you help to review this PR?

This PR has enough lgtm (+1). It's blocked by CI failure. I have triggered retest.

**Pull request merged**
