### PR TITLE
*: support Go1.11 module for release-2.1

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

As the title says...
It can't be cherry pick, so I rewrite

### What is changed and how it works?

- update Makefile
- vendor is still kept in this COMMIT, generated by 'go mod vendor'
- github.com/pkg/errors is changed to github.com/pingcap/errors
- github.com/pingcap/tidb-tools is updated
- github.com/pkg/errors is indirect from pd
- many files are deleted from vendor, maybe they are detected useless

Related changes

https://github.com/pingcap/tidb/issues/7922
https://github.com/pingcap/tidb/pull/8136
https://github.com/pingcap/tidb/pull/8054

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8432)

### CODE REVIEW

**Comment by tiancaiamao** [comment]
@zz-jason @winkyao

**Comment by zz-jason** [comment]
LGTM

**Pull request merged**
