### PR TITLE
expression: forbid binary string to be json key

### PR DESCRIPTION
**Pull request by xiongjiwei**
Signed-off-by: xiongjiwei <xiongjiwei1996@outlook.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/37509

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by YangKeao** [comment]
It should also fix https://github.com/pingcap/tidb/issues/25580?

**Comment by xiongjiwei** [comment]
> It should also fix #25580?

no, this pr aims to `json_object` and `json_objectagg`. I actually think #25580 is a MySQL bug, the behavior is inconsistent in MySQL. e.g.

```sql
mysql root@localhost:test> SELECT JSON_UNQUOTE(cast(CAST('ABCD' AS BINARY) as json));
+----------------------------------------------------+
| JSON_UNQUOTE(cast(CAST('ABCD' AS BINARY) as json)) |
+----------------------------------------------------+
| base64:type15:QUJDRA==                             |
+----------------------------------------------------+

mysql root@localhost:test> SELECT JSON_UNQUOTE(CAST('ABCD' AS BINARY));
(3144, "Cannot create a JSON value from a string with CHARACTER SET 'binary'.")
```

if use explicates cast, it runs successfully.

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]

**Review by CbcWestwolf — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
