### PR TITLE
sessionctx: add some information about the rewriting phase into the slow log

### LINKED ISSUE #17557: Add more information in slow logs to help analyze slow queries
## Development Task
Now information in slow logs(or `slow-query-table`) is not enough to analyze slow queries.
After discussing, we should add these useful information into it:
- [x] 1. time-consuming in the parse phase
- [x] 2. time-consuming for compiling the query
- [x] 3. time-consuming for rewriting the query (#17569)
- [x] 4. time-consuming for optimizing the query (#17869)
- [x] 5. time-consuming to wait for TSO (#17869)
- [x] 6. detailed execution information (like results of `explain analyze`)(#15008)(#17573)
- [x] 7. if this query hits the plan cache(#16197)
- [x] 8. if there are subqueries processed in the compile phase (#17569)
- [ ] 9. support [`ScanDetailV2`](https://github.com/pingcap/kvproto/pull/600)
- [x] 10. if this query use disk(#16883)

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: #17557 

Problem Summary: add some information about the rewriting phase into the slow log

### What is changed and how it works?

One step to resolve #17557.
Add three fields to slow logs:
1. Rewrite_time: the time cost to rewrite the query;
2. Preprocessed_subqueries: the number of pre-processed subqueries;
3. Preprocessed_subquery_time: the total time of pre-processing subqueries.

For example, in this query:
```
select * from t where a > (select min(a+sleep(1)) from t t2 where t2.a<5);
```
The subquery is not related with the outside query so it will be processed during the rewriting phase.
After this PR, you can see this information in its slow log:
```
# Rewrite_time: 3.00518165 Preproc_subqueries: 1 Preproc_subqueries_time: 3.004869107
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`: update the relative docs about the slow query.

### Check List 

Tests 

- Unit test

### Release note 
- Add some information about the rewriting phase into the slow log

### CODE REVIEW

**Comment by qw4990** [comment]
> LGTM,
> Remember to update the docs.

Ok, thx.

**Comment by breeswish** [comment]
#17557 need to be re-opened :)

**Pull request merged**
