### PR TITLE
conn: Send auth plugin name

### PR DESCRIPTION
**Pull request by breeswish**
Currently we only support auth_plugin mysql_native_password.

Fix https://github.com/pingcap/tidb/issues/4171

### CODE REVIEW

**Comment by breeswish** [comment]
@tiancaiamao PTAL~

**Comment by shenli** [comment]
Could you add a test case for this?

**Comment by breeswish** [comment]
@shenli Shall we use mysql client library to simulate connection, or just perform a unit test for this function? If we use mysql client library, we need to find ways to check whether ClientPluginAuth is really taking effect here.

**Comment by shenli** [comment]
Could you add a test case like this: https://github.com/pingcap/tidb/blob/master/server/conn_test.go#L25

**Comment by breeswish** [comment]
@shenli Done

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
