### PR TITLE
executor: hash join out of index panic when enum column value is zero

### LINKED ISSUE #23060: runtime error: index out of range [18446744073709551615] with length 2
### 1. Minimal reproduce step (Required)
```sql
drop table if exists t1;
set sql_mode='';
CREATE TABLE t1 (a enum('Yes', 'No') NOT NULL);
insert t1 values (0);
delete from alias using t1, t1 alias where t1.a = alias.a;
```

### 2. What did you expect to see? (Required)
No panic.

### 3. What did you see instead (Required)
Client output:
```
ERROR 1105 (HY000): runtime error: index out of range [18446744073709551615] with length 2
```
TiDB log:
```
[2021/03/01 19:43:20.401 +08:00] [ERROR] [misc.go:90] ["panic in the recoverable goroutine"] [r={}] ["stack trace"="github.com/pingcap/tidb/util.WithRecovery.func1
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/util/misc.go:92
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:679
runtime.goPanicIndexU
	/usr/local/go/src/runtime/panic.go:79
github.com/pingcap/tidb/util/codec.HashChunkSelected
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/util/codec/codec.go:574
github.com/pingcap/tidb/executor.(*hashRowContainer).PutChunkSelected
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/hash_table.go:181
github.com/pingcap/tidb/executor.(*hashRowContainer).PutChunk
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/hash_table.go:160
github.com/pingcap/tidb/executor.(*HashJoinExec).buildHashTableForList
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/join.go:763
github.com/pingcap/tidb/executor.(*HashJoinExec).fetchAndBuildHashTable
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/join.go:713
github.com/pingcap/tidb/executor.(*HashJoinExec).Next.func1
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/join.go:658
github.com/pingcap/tidb/util.WithRecovery
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/util/misc.go:95"]
[2021/03/01 19:43:20.401 +08:00] [INFO] [conn.go:809] ["command dispatched failed"] [conn=3] [connInfo="id:3, addr:127.0.0.1:37894 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="DELETE FROM alias USING t1, t1 alias WHERE t1.a = alias.a"] [txn_mode=PESSIMISTIC] [err="runtime error: index out of range [18446744073709551615] with length 2
github.com/pingcap/tidb/executor.(*HashJoinExec).handleFetchAndBuildHashTablePanic
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/join.go:683
github.com/pingcap/tidb/util.WithRecovery.func1
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/util/misc.go:87
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:679
runtime.goPanicIndexU
	/usr/local/go/src/runtime/panic.go:79
github.com/pingcap/tidb/util/codec.HashChunkSelected
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/util/codec/codec.go:574
github.com/pingcap/tidb/executor.(*hashRowContainer).PutChunkSelected
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/hash_table.go:181
github.com/pingcap/tidb/executor.(*hashRowContainer).PutChunk
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/hash_table.go:160
github.com/pingcap/tidb/executor.(*HashJoinExec).buildHashTableForList
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/join.go:763
github.com/pingcap/tidb/executor.(*HashJoinExec).fetchAndBuildHashTable
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/join.go:713
github.com/pingcap/tidb/executor.(*HashJoinExec).Next.func1
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/join.go:658
github.com/pingcap/tidb/util.WithRecovery
	/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/util/misc.go:95
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357"]
```

### 4. What is your TiDB version? (Required)
```yaml
Release Version: v4.0.0-beta.2-2209-gfebac515b
Edition: Community
Git Commit Hash: febac515b1369643216e1efc971a262615dc4794
Git Branch: master
UTC Build Time: 2021-03-01 03:47:27
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #23060 

Problem Summary:

    set sql_mode = '';
    drop table if exists t1;
    create table t1(c1 enum('a', 'b'));
    insert into t1 values('a');
    insert into t1 values(0);
    select /*+ hash_join(t_alias1, t_alias2)*/ * from t1 t_alias1 inner join t1 t_alias2 on t_alias1.c1 = t_alias2.c1;

Select query panic. When build hash table(in hash join operator), package codec use "0-1" as index to get string value of enum definition, which is -1. So it panics.
### What is changed and how it works?

What's Changed: use types.ParseEnumValue() instread, this function handle invalid enum value. Will use empty string if got invalid enum val.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test: executor.join_test.go:TestInvalidEnumVal

Side effects: no

### Release note 

- hash join out of index panic when enum column value is zero

### CODE REVIEW

**Comment by guo-shaoge** [comment]
@XuHuaiyu @wshwsh12

**Review by wshwsh12 — COMMENTED** [review]
/lgtm

**Review by AilinKid — COMMENTED** [review]
/LGTM

**Pull request merged**
