### PR TITLE
lightning: fix test lightning_checkpoint_chunks

### PR DESCRIPTION
**Pull request by gozssky**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/33502

Problem Summary:
https://github.com/pingcap/tidb/pull/33303 introduced a new method `RunOnceWithOptions` and Lightning calls this method to run task instead. However, `RunOnceWithOptions` missed the failpoint function. So test failed.

### What is changed and how it works?

Add taskID failpoint.

### Check List

Tests 

- [x] Integration test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
I just made a same PR :joy:

**Review by glorv — APPROVED** [review]

**Pull request merged**
