### PR TITLE
expression: handle maketime unsigned hour overflow(#10074)

### PR DESCRIPTION
**Pull request by AndrewDi**
cherry-pick #10074

### CODE REVIEW

**Comment by AndrewDi** [comment]
@qw4990 PTAL

**Comment by qw4990** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by qw4990** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by qw4990** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
