### PR TITLE
expression: fix flen for timestamp_add

### LINKED ISSUE #27540: `timestampadd` as expression index got wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create table t004(a date);
insert into t004 values ('2021-08-20');
select * from t004 where timestampadd(microsecond, 1, a) = timestampadd(microsecond, 1, '2021-08-20');
alter table t004 add index eidx ((timestampadd(microsecond, 1, a)));
select * from t004 where timestampadd(microsecond, 1, a) = timestampadd(microsecond, 1, '2021-08-20');
insert into t004 values ('2021-08-20');
```

### 2. What did you expect to see? (Required)
```sql
MySQL root@172.16.5.103:test> drop table t004;
Query OK, 0 rows affected
Time: 0.043s
MySQL root@172.16.5.103:test> create table t004(a date);
                          ->
Query OK, 0 rows affected
Time: 0.056s
MySQL root@172.16.5.103:test> insert into t004 values ('2021-08-20');
Query OK, 1 row affected
Time: 0.062s
MySQL root@172.16.5.103:test> select * from t004 where timestampadd(microsecond, 1, a) = timestampadd(microsecond, 1, '2021-08-20');
+------------+
| a          |
+------------+
| 2021-08-20 |
+------------+

1 row in set
Time: 0.071s
MySQL root@172.16.5.103:test> alter table t004 add index eidx ((timestampadd(microsecond, 1, a)));
Query OK, 0 rows affected
Time: 0.059s
MySQL root@172.16.5.103:test> select * from t004 use index (eidx) where timestampadd(microsecond, 1, a) = timestampadd(microsecond, 1, '2021-08-20');
+------------+
| a          |
+------------+
| 2021-08-20 |
+------------+

1 row in set
Time: 0.058s
MySQL root@172.16.5.103:test> insert into t004 values ('2021-08-20');
Query OK, 1 row affected
Time: 0.039s
MySQL root@172.16.5.103:test> select * from t004;
+------------+
| a          |
+------------+
| 2021-08-20 |
| 2021-08-20 |
+------------+

2 rows in set
Time: 0.044s
MySQL root@172.16.5.103:test> show extended columns from t004;
+----------------------------------+-------------+------+-----+---------+-------------------+
| Field                            | Type        | Null | Key | Default | Extra             |
+----------------------------------+-------------+------+-----+---------+-------------------+
| a                                | date        | YES  |     | <null>  |                   |
| 2608284158c2427597bb96e68cbc48f6 | datetime(6) | YES  | MUL | <null>  | VIRTUAL GENERATED |
| DB_ROW_ID                        |             | NO   |     | <null>  |                   |
| DB_TRX_ID                        |             | NO   |     | <null>  |                   |
| DB_ROLL_PTR                      |             | NO   |     | <null>  |                   |
+----------------------------------+-------------+------+-----+---------+-------------------+

```
### 3. What did you see instead (Required)
```sql
MySQL root@172.16.6.1:test> create table t004(a date);
Query OK, 0 rows affected
Time: 0.104s
MySQL root@172.16.6.1:test> insert into t004 values ('2021-08-20');
Query OK, 1 row affected
Time: 0.059s
MySQL root@172.16.6.1:test> select * from t004 where timestampadd(microsecond, 1, a) = timestampadd(microsecond, 1, '2021-08-20');
+------------+
| a          |
+------------+
| 2021-08-20 |
+------------+

1 row in set
Time: 0.047s
MySQL root@172.16.6.1:test> alter table t004 add index eidx ((timestampadd(microsecond, 1, a)));
Query OK, 0 rows affected
Time: 0.286s
MySQL root@172.16.6.1:test> select * from t004  use index (eidx) where timestampadd(microsecond, 1, a) = timestampadd(microsecond, 1, '2021-08-20');
+---+
| a |
+---+

0 rows in set
Time: 0.057s
MySQL root@172.16.6.1:test> insert into t004 values ('2021-08-20');
(1406, 'Data Too Long, field len 19, data len 26')
MySQL root@172.16.6.1:test> select * from t004;
+------------+
| a          |
+------------+
| 2021-08-20 |
+------------+

1 row in set
Time: 0.044s
MySQL root@172.16.6.1:test> show extended columns from t004;
+------------+----------+------+-----+---------+-------------------+
| Field      | Type     | Null | Key | Default | Extra             |
+------------+----------+------+-----+---------+-------------------+
| a          | date     | YES  |     | <null>  |                   |
| _V$_eidx_0 | char(19) | YES  | MUL | <null>  | VIRTUAL GENERATED |
+------------+----------+------+-----+---------+-------------------+

2 rows in set
Time: 0.049s
MySQL root@172.16.6.1:test>

```
### 4. What is your TiDB version? (Required)
```sql
tidb_version() | Release Version: v5.2.0
Edition: Community
Git Commit Hash: b2af0b80c85b7ad9d5d98aa5d0e9f28fda3b2ef6
Git Branch: heads/refs/tags/v5.2.0
UTC Build Time: 2021-08-23 14:27:49
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #27540

Problem Summary:
If the unit is microsecond, set flen to 26.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix flen for timestamp_add
```

### CODE REVIEW

**Comment by lcwangchao** [comment]
LGMT. But I'm not very  familiar with functions and expression index. Maybe you can find more reviewers to do it

**Review by xhebox — APPROVED** [review]
Though tests still fails, I don't think it is related.

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
