### PR TITLE
Prealloc / collides with package name

### PR DESCRIPTION
**Pull request by im-kulikov**

### CODE REVIEW

**Comment by shenli** [comment]
@im-kulikov Thanks!

**Comment by im-kulikov** [comment]
used:
- [prealloc](https://github.com/alexkohler/prealloc)
- [metalinter](https://github.com/alecthomas/gometalinter)

**Comment by im-kulikov** [comment]
@shenli I can check whole project

**Comment by shenli** [comment]
@im-kulikov Great!

**Comment by im-kulikov** [comment]
phew.. it was not so easy, as it turned out

**Comment by im-kulikov** [comment]
@shenli I'm ended

**Comment by coocood** [comment]
LGTM

@im-kulikov 
Good job!
Thank you!

**Comment by tiancaiamao** [comment]
LGTM
Please resolve conflicts.

**Comment by im-kulikov** [comment]
@coocood @tiancaiamao fixed

**Comment by im-kulikov** [comment]
Guys, thanks for fast review

**Comment by coocood** [comment]
@im-kulikov 
You are welcome.
It has to be fast or there would be many conflicts.

**Comment by im-kulikov** [comment]
@coocood yeah) refactoring is so hard 😂

**Pull request merged**
