### PR TITLE
statistics: pseudo table should not contain the hidden columns

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/29237

Problem Summary:

The pseudo table would contain the hidden columns before. The hidden column is used for the expression index, we don't collect the stats for it. So the statistics on this column are always empty. This may lead to wrong stats.

### What is changed and how it works?

When generate the pseudo table, we don't generate stats for the hidden columns.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test (the issue it fixed).
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by winoros** [comment]
The failed test is not related with the metioned issue.
https://ci.pingcap.net/job/tidb_ghpr_common_test/7234/display/redirect

**Comment by winoros** [comment]
> The failed test is not related with the metioned issue. [ci.pingcap.net/job/tidb_ghpr_common_test/7234/display/redirect](https://ci.pingcap.net/job/tidb_ghpr_common_test/7234/display/redirect)

https://ci.pingcap.net/job/tidb_ghpr_common_test/7240/display/redirect You can see the difference between the two tests

**Review by time-and-fate — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
