### PR TITLE
 executor: tiny clean up

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Tiny clean up the tracing related code

### What is changed and how it works?

Extract those code to from each executor to the Next function

### Check List 

Tests 

 - No code

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @zz-jason @coocood

**Comment by coocood** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Pull request merged**
