### PR TITLE
expression: Maintain separate scalar function pushdown lists for each engine instead of unified. (#23284)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23284 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23661
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23661:release-5.0-26c0e7261d70
```

---

### What problem does this PR solve?

Problem Summary:

Currently, if I want to push a function down to TiFlash, I need to:
1. add it in `expression.canFuncBePushed` (maybe already existed)
2. add it in `expression.scalarExprSupportedByFlash`.
3. consider whether to ban it in `expression.scalarExprSupportedByTiKV`
4. consider whether to ban it in `expression.scalarExprSupportedByTiDB`

After this pr, there won't maintain a unified list, I can just add it in `expression.scalarExprSupportedByFlash`.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`: no need.
- Need to cherry-pick to the release branch 4.0

### Check List 

Tests 

- Integration test

Side effects

### Release note 

- No release note

### CODE REVIEW

**Review by leiysky — APPROVED** [review]
LGTM

**Review by fzhedu — APPROVED** [review]
/LGTM

**Comment by LittleFall** [comment]
[2021-06-16T04:06:04.033Z] GitHub pull request #23661 of commit 2835af23ab5c2b9c0439839404b4afe3e2c8bcd5, no merge conflicts.

[2021-06-16T04:06:04.637Z] Setting status of 2835af23ab5c2b9c0439839404b4afe3e2c8bcd5 to PENDING with url https://ci.pingcap.net/job/tidb_ghpr_unit_test/5699/display/redirect and message: 'Jenkins job is running.'

[2021-06-16T04:06:04.637Z] Using context: idc-jenkins-ci-tidb/unit-test

[2021-06-16T04:06:07.511Z] Obtained jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy from git git@github.com:PingCAP-QE/ci.git

[2021-06-16T04:06:07.511Z] Running in Durability level: MAX_SURVIVABILITY

[2021-06-16T04:06:07.561Z] Setting status of 2835af23ab5c2b9c0439839404b4afe3e2c8bcd5 to FAILURE with url https://ci.pingcap.net/job/tidb_ghpr_unit_test/5699/display/redirect and message: 'Jenkins job failed.

[2021-06-16T04:06:07.561Z]  '

[2021-06-16T04:06:07.561Z] Using context: idc-jenkins-ci-tidb/unit-test

[2021-06-16T04:06:08.115Z] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

[2021-06-16T04:06:08.115Z] WorkflowScript: 425: expecting ')', found '=' @ line 425, column 37.

[2021-06-16T04:06:08.115Z]                if (currentBuild.result = "ABORTED") {

[2021-06-16T04:06:08.115Z]                                        ^

[2021-06-16T04:06:08.115Z] 

[2021-06-16T04:06:08.115Z] 1 error

[2021-06-16T04:06:08.115Z] 

[2021-06-16T04:06:08.115Z] 	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)

[2021-06-16T04:06:08.115Z] 	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:150)

[2021-06-16T04:06:08.115Z] 	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:120)

[2021-06-16T04:06:08.115Z] 	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:132)

[2021-06-16T04:06:08.115Z] 	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:350)

[2021-06-16T04:06:08.115Z] 	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:144)

[2021-06-16T04:06:08.115Z] 	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:110)

[2021-06-16T04:06:08.115Z] 	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:234)

[2021-06-16T04:06:08.115Z] 	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:168)

[2021-06-16T04:06:08.115Z] 	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:943)

[2021-06-16T04:06:08.115Z] 	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)

[2021-06-16T04:06:08.115Z] 	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)

[2021-06-16T04:06:08.115Z] 	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)

[2021-06-16T04:06:08.115Z] 	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)

[2021-06-16T04:06:08.115Z] 	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)

[2021-06-16T04:06:08.115Z] 	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)

[2021-06-16T04:06:08.115Z] 	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)

[2021-06-16T04:06:08.115Z] 	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)

[2021-06-16T04:06:08.115Z] 	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)

[2021-06-16T04:06:08.115Z] 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:571)

[2021-06-16T04:06:08.115Z] 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:523)

[2021-06-16T04:06:08.115Z] 	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:337)

[2021-06-16T04:06:08.115Z] 	at hudson.model.ResourceController.execute(ResourceController.java:97)

[2021-06-16T04:06:08.115Z] 	at hudson.model.Executor.run(Executor.java:429)

[2021-06-16T04:06:08.115Z] Finished: FAILURE

**Pull request merged**
