### PR TITLE
executor: fix autoid doesn't handle float, double type and tiny cleanup (#11110)

### PR DESCRIPTION
**Pull request by lzmhhh123**
Automated cherry pick of #11110 on release-3.0.
#11110: executor: fix autoid doesn't handle float, double type
executor: fix autoid doesn't handle float, double type
executor: handle update case of autoid bug(#11109), and
executor: fix gofmt
executor: fix autoid value of insert type and add more

### CODE REVIEW

**Comment by lzmhhh123** [comment]
/run-all-tests tikv=release-3.0 pd=release-3.0 tidb-test=release-3.0

**Comment by lzmhhh123** [comment]
/run-all-tests tikv=release-3.0 pd=release-3.0 tidb-test=release-3.0

**Comment by lzmhhh123** [comment]
/run-all-tests tikv=release-3.0 pd=release-3.0 tidb-test=release-3.0

**Comment by imtbkcat** [comment]
/run-all-tests tikv=release-3.0 pd=release-3.0 tidb-test=release-3.0

**Comment by imtbkcat** [comment]
/run-all-tests tikv=release-3.0 pd=release-3.0 tidb-test=release-3.0

**Pull request merged**
