### PR TITLE
sessionctx: fix the value of analyze_version when upgrading 4.x to 5.…

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/25422

Problem Summary:

Use the same way with https://github.com/pingcap/tidb/pull/30650

### What is changed and how it works?

When do upgrading, we first check whether the variable exists.
If not exist, we use the `1` which is the old behavior in 4.0 and before.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the unexpected value of `tidb_analyze_version` when upgrading from a version lower than 5.0
```

### CODE REVIEW

**Comment by winoros** [comment]
@bb7133 @cfzjywxk PTAL

**Review by guo-shaoge — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Pull request merged**
