### PR TITLE
infoschema: maintain the snapshotTS in the infocache (#25322)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25322 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25376
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25376:release-5.1-3ed698259d78
```

---

Signed-off-by: nolouch <nolouch@gmail.com>

### What problem does this PR solve?

Issue Number:  https://github.com/pingcap/tidb/issues/25303

Problem Summary: 
Infoschema cache is introduced by https://github.com/pingcap/tidb/pull/24285, which mainly used for stale read and history read. It let executor can get the corresponding history schema. But even if we have the cache, every request still needs to go to TiKV to obtain the schema version to confirm the corresponding schema. which leads one TiKV to have many `KV_Get`, This may let one TiKV who has the meta region's leader consume too much CPU and become a bottleneck. And intuitively, the request is unbalanced:
image

### What is changed and how it works?

- Cache the relative ts in the infocache. each schema has only corresponded `sanpshotTS`, which is the oldest ts we have used with the schema.
- Make the request can get the `Infoschema` directly with the specified timestamp.

### Check List 

Tests 

- Unit test

### Release note 

- None

### CODE REVIEW

**Comment by nolouch** [comment]
PTAL @xhebox @Yisaer

**Review by xhebox — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]

**Pull request merged**
