### PR TITLE
expression: fix compatibility behaviors in zero datetime with MySQL (#21220)

### LINKED ISSUE #9728: `dayofmonth` `month` `quarter` and `year` are not compatible with Mysql
## Description
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select year(0000-00-00),year("0000-00-00");
select dayofmonth(0000-00-00), dayofmonth("0000-00-00");
select month(0000-00-00), month("0000-00-00");
select quarter(0000-00-00), quarter("0000-00-00");
select extract(MONTH FROM 0000-00-00), extract(MONTH FROM "0000-00-00");
```

2. What did you expect to see?
In Mysql
```
mysql> select year(0000-00-00),year("0000-00-00");
+------------------+--------------------+
| year(0000-00-00) | year("0000-00-00") |
+------------------+--------------------+
|                0 |               NULL |
+------------------+--------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayofmonth(0000-00-00), dayofmonth("0000-00-00");
+------------------------+--------------------------+
| dayofmonth(0000-00-00) | dayofmonth("0000-00-00") |
+------------------------+--------------------------+
|                      0 |                     NULL |
+------------------------+--------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select month(0000-00-00), month("0000-00-00");
+-------------------+---------------------+
| month(0000-00-00) | month("0000-00-00") |
+-------------------+---------------------+
|                 0 |                NULL |
+-------------------+---------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select quarter(0000-00-00), quarter("0000-00-00");
+---------------------+-----------------------+
| quarter(0000-00-00) | quarter("0000-00-00") |
+---------------------+-----------------------+
|                   0 |                  NULL |
+---------------------+-----------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select extract(MONTH FROM 0000-00-00), extract(MONTH FROM "0000-00-00");
+--------------------------------+----------------------------------+
| extract(MONTH FROM 0000-00-00) | extract(MONTH FROM "0000-00-00") |
+--------------------------------+----------------------------------+
|                              0 |                             NULL |
+--------------------------------+----------------------------------+
1 row in set, 1 warning (0.00 sec)
```


3. What did you see instead?
In TiDB
```
mysql> select year(0000-00-00),year("0000-00-00");
+------------------+--------------------+
| year(0000-00-00) | year("0000-00-00") |
+------------------+--------------------+
|             NULL |               NULL |
+------------------+--------------------+
1 row in set, 2 warnings (0.00 sec)

mysql> select dayofmonth(0000-00-00), dayofmonth("0000-00-00");
+------------------------+--------------------------+
| dayofmonth(0000-00-00) | dayofmonth("0000-00-00") |
+------------------------+--------------------------+
|                   NULL |                     NULL |
+------------------------+--------------------------+
1 row in set, 2 warnings (0.00 sec)

mysql> select month(0000-00-00), month("0000-00-00");
+-------------------+---------------------+
| month(0000-00-00) | month("0000-00-00") |
+-------------------+---------------------+
|              NULL |                NULL |
+-------------------+---------------------+
1 row in set, 2 warnings (0.00 sec)

mysql> select quarter(0000-00-00), quarter("0000-00-00");
+---------------------+-----------------------+
| quarter(0000-00-00) | quarter("0000-00-00") |
+---------------------+-----------------------+
|                NULL |                  NULL |
+---------------------+-----------------------+
1 row in set, 2 warnings (0.00 sec)

mysql> select extract(MONTH FROM 0000-00-00), extract(MONTH FROM "0000-00-00");
ERROR 1292 (22007): invalid time format: '{0 0 0 0 0 0 0}'
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.0-beta-212-g0681b8125
Git Commit Hash: 0681b8125080045ee0d4747ce61923164c6f2dd1
Git Branch: master
UTC Build Time: 2019-03-14 04:39:19
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```




## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @SunRunAway

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21220 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #9728

### What is changed and how it works?

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- fix compatibility behaviors in zero datetime with MySQL.

### CODE REVIEW

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by ichn-hu — APPROVED** [review]
LGTM

**Comment by qw4990** [comment]
Please resolve conflicts; @lzmhhh123

**Review by qw4990 — APPROVED** [review]
LGTM

**Pull request merged**
