### PR TITLE
executor, util: reset offsets and nullBitMap for MutRow when setting new values (#30265)

### LINKED ISSUE #29947: TiDB produces different results for SELECT statement when using transaction
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

**Setup the environment:**

```
tidb/bin/tidb-server &
mysql -h "127.0.0.1" -u root -P 4000 -D testdb < mysql_bk.sql
```

_mysql_bk.sql:_ [mysql_bk.sql.txt](https://github.com/pingcap/tidb/files/7571924/mysql_bk.sql.txt)

**Testcase 1**
```
mysql -h "127.0.0.1" -u root -P 4000 -D testdb
mysql> delete from t_tir89b where t_tir89b.c_3pcik >= t_tir89b.c_sroc_c;
mysql> select * from (select count(*) over (partition by ref_0.c_0b6nxb order by ref_0.c_3pcik) as c0 from t_tir89b as ref_0) as subq_0 where subq_0.c0 <> 1;
```

**Testcase 2**
```
mysql -h "127.0.0.1" -u root -P 4000 -D testdb
mysql> start transaction;
mysql> delete from t_tir89b where t_tir89b.c_3pcik >= t_tir89b.c_sroc_c;
mysql> select * from (select count(*) over (partition by ref_0.c_0b6nxb order by ref_0.c_3pcik) as c0 from t_tir89b as ref_0) as subq_0 where subq_0.c0 <> 1;
mysql> commit;
```

### 2. What did you expect to see? (Required)

The outputs of SELECT statements in Testcase 1 and Testcase 2 are same. 

### 3. What did you see instead (Required)

**Output of SELECT statement in Testcase 1**
```
+----+
| c0 |
+----+
|  2 |
|  3 |
+----+
```

**Output of SELECT statement in Testcase 2**
```
Empty set (0.00 sec)
```

The output of Testcase 1 contains element 2 and 3, while the output of Testcase 2 (using transaction) is empty. So their results are different.

### 4. What is your TiDB version? (Required)

```
Release Version: v5.4.0-alpha-133-g20b9a4d8c
Edition: Community
Git Commit Hash: 20b9a4d8ca32449c5003963eb7d382633c3ed25e
Git Branch: master
UTC Build Time: 2021-11-17 08:53:20
GoVersion: go1.16
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #30265 to release-5.2
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/30391
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/30391:release-5.2-70d29735e636
```

---

### What problem does this PR solve?

Issue Number: close #29947 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test

Side effects

N/A

Documentation

N/A

### Release note

```release-note
Fix the problem that window function may return different results when using transaction or not.
```

### CODE REVIEW

**Review by wshwsh12 — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Comment by winoros** [comment]
@ti-chi-bot

**Pull request merged**
