### PR TITLE
expression: add json_arrayagg and json_objectagg

### PR DESCRIPTION
**Pull request by Kingwl**
### What problem does this PR solve? 
https://github.com/pingcap/tidb/issues/7623
https://github.com/pingcap/tidb/issues/7546

### What is changed and how it works?
add an aggr function

### Check List 

Tests 

 - Unit test

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/7824)

### CODE REVIEW

**Comment by shenli** [comment]
@Kingwl  Thanks!

**Comment by Kingwl** [comment]
@shenli could you give some help, please😂

**Comment by zz-jason** [comment]
@Kingwl What problem do you encountered?

**Comment by Kingwl** [comment]
where should I add the test?
or only 'integration_test'?

**Comment by zz-jason** [comment]
@Kingwl sure, it’s also the recommended way. 😄

**Comment by Kingwl** [comment]
and the https://github.com/pingcap/tipb/pull/105 has blocked this (and #7776) , could you take a look please?🙋🏻‍♂️

**Comment by Kingwl** [comment]
And something can not to be serialized to binary JSON (Decimal), are there any existed way to handle that?

**Comment by zz-jason** [comment]
@Kingwl Why decimal can not be serialized to binary json?

**Comment by Kingwl** [comment]
`json.CreateBinary` does not match that, maybe convert all value to `[]byte?`

**Comment by Kingwl** [comment]
another question:
what kind should decimal be in json? number ? or string?

**Comment by qw4990** [comment]
Hi, @Kingwl, could you please fix these CI problems and conflicts? Thanks~

**Comment by Kingwl** [comment]
sure

**Comment by qw4990** [comment]
PTAL~ @Kingwl

**Comment by zz-jason** [comment]
@Kingwl friendly ping, any update?

**Comment by Kingwl** [comment]
Sorry for the delay，I have no time to update with these recently. And the changes seem not completion, Sorry again.

**Pull request closed without merging**
