### PR TITLE
executor: query user and role, hostname should be lowercase

### LINKED ISSUE #28841: IT `role` failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2021-10-14T14:09:00.132Z] time="2021-10-14T22:08:59+08:00" level=error msg="1 tests failed\n"

[2021-10-14T14:09:00.132Z] time="2021-10-14T22:08:59+08:00" level=error msg="run test [role] err: sql:GRANT `engineering`@`US` TO `engineering`@`INDIA`;: run \"GRANT `engineering`@`US` TO `engineering`@`INDIA`;\" at line 59 err Error 3523: Unknown authorization ID `engineering`@`US`"

[2021-10-14T14:09:00.132Z] + echo 'tidb-server(PID: 435) stopped'

[2021-10-14T14:09:00.132Z] tidb-server(PID: 435) stopped

[2021-10-14T14:09:00.132Z] + kill -9 435

script returned exit code 1
```
ci: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_common_test/detail/tidb_ghpr_integration_common_test/7016/pipeline
pr: #28741

### PR DESCRIPTION
**Pull request by 7yyo**
### What problem does this PR solve?

Issue Number: close #28841 

Problem Summary:

When creating a new user, the `hostname` will be converted to lowercase. So when querying, also use lowercase.

### What is changed and how it works?

What's Changed:

Use lowercase `hostname` for query.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
Use lowercase `hostname` for query.
```

### CODE REVIEW

**Comment by morgo** [comment]
This difference is because MySQL uses a case insensitive collation, while
tidb uses binary.

**Comment by morgo** [comment]
Here is the definition from MySQL 8.0:
```sql
CREATE TABLE `user` (
  `Host` char(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '', <-- insensitive
  `User` char(32) COLLATE utf8_bin NOT NULL DEFAULT '', <-- sensitive
```

Versus TiDB:
```sql
  `Host` char(255) NOT NULL, <-- binary (tidb disables collations by default)
  `User` char(32) NOT NULL, <-- binary (tidb disables collations by default)
```

**Comment by 7yyo** [comment]
> Here is the definition from MySQL 8.0:
> 
> ```sql
> CREATE TABLE `user` (
>   `Host` char(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '', <-- insensitive
>   `User` char(32) COLLATE utf8_bin NOT NULL DEFAULT '', <-- sensitive
> ```
> 
> Versus TiDB:
> 
> ```sql
>   `Host` char(255) NOT NULL, <-- binary (tidb disables collations by default)
>   `User` char(32) NOT NULL, <-- binary (tidb disables collations by default)
> ```

OK, I understand, thank you!

**Comment by 7yyo** [comment]
@morgo PTAL , thank you. 

By the way, I think if the user uses uppercase to store the hostname, but can only query through lowercase, it will make the user a little confused

**Comment by 7yyo** [comment]
PTAL @morgo @djshow832

**Pull request merged**
