### PR TITLE
*: add a variable to force statement priority of TiDB server

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve? 
Add a variable to force statement priority of TiDB server. Fix https://github.com/pingcap/tidb/issues/7524 .

### What is changed and how it works?
Force the priority for each statement when tidb_force_priority is set to high/low/delayed priority.

### Check List 

Tests 

 - Unit test
 - Manual test
Watch the grafana of coprocess thread CPU usage when `set tidb_force_priority = "high_priority"/"low_priority"/"delayed"`

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Side effects

 - Increased code complexity

Related changes

 - Need to be included in the release note

PTAL @coocood @morgo

### CODE REVIEW

**Comment by morgo** [comment]
LGTM

**Comment by jackysp** [comment]
For analyze statement, it will set its own priority, for others, I have to say yes, @winoros .

**Comment by winoros** [comment]
Need we use different variable to control internal ones and external ones?

**Comment by jackysp** [comment]
I think we can skip the internal SQLs by its connection ID, when this variable is set.

**Pull request merged**
