### PR TITLE
*: fix LIKE expressions with _ following %

### PR DESCRIPTION
**Pull request by smola**
### What problem does this PR solve?

Problem Summary: TiDB assumes that pattern `%_` is equivalent to `%`, but that is not the case. The pattern `x%x` should match `xx`, `x%_x` should not. This issue is present in various code sections related to `LIKE` expressions. At least that I found:

1. `stringutil.CompilePattern` at `util/stringutil/string_util.go`
2. `stringutil.CompileLike2Regexp` at `util/stringutil/string_util.go`
3. `collate.compilePatternGeneralCI` at `util/collate/general_ci.go`

### What is changed and how it works?

- On `stringutil.CompilePattern`, `stringutil.CompileLike2Regexp` and `collate.compilePatternGeneralCI` just removed the few lines that converted `%_` to `%`.
- Added new unit tests. Although `memtable_reader_test.go` could use some more.

### Check List

- Unit tests

### Release note

* Fixed LIKE expressions when a single character (`_`) wildcard follows a multiple character wildcard (`%`).

### CODE REVIEW

**Comment by smola** [comment]
By the way, there is a possible optimization I did not include in the PR. While rewriting `%_ => %_` is not valid, recursively applying `%_ => _%` and `%% => %` is. If I got the matching algorithm right, this may improve matching performance.

**Comment by wjhuang2016** [comment]
> By the way, there is a possible optimization I did not include in the PR. While rewriting `%_ => %` is not valid, recursively applying `%_ => _%` and `%% => %` is. If I got the matching algorithm right, this may improve matching performance.

Yeah, it's a good optimization, could you implement it?

**Comment by SunRunAway** [comment]
Should this PR be cherry-picked to old releases? @wjhuang2016

**Comment by wjhuang2016** [comment]
> Should this PR be cherry-picked to old releases? @wjhuang2016

Yeah, also need to modify the code in TiKV.

**Pull request merged**
