### PR TITLE
parser: Fix undocumented password_func function | tidb-test=pr/2458

### LINKED ISSUE #58311: Undocumented password_func function
## Bug Report

Looks like `password_func()` should have been called `password()`, like in MySQL 5.7

### 1. Minimal reproduce step (Required)

```
SELECT PASSWORD_FUNC("abc");
```

### 2. What did you expect to see? (Required)

Error, function doesn't exist

### 3. What did you see instead (Required)

Resultset

### Related

- https://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html#function_password

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #58311 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
The undocumented `password_func` function was removed.
```

### CODE REVIEW

**Comment by Defined2014** [comment]
> This function is deprecated in MySQL 5.7 and is removed in MySQL 8.0.

Should we rename it to `password` or not.

**Review by Defined2014 — APPROVED** [review]

**Review by mjonss — APPROVED** [review]

**Review by D3Hunter — COMMENTED** [review]
our doc also contains `password_func`, see https://docs.pingcap.com/tidb/stable/sql-statement-show-builtins, this pr breaks this, but seems trivial

rest lgtm

**Comment by dveeden** [comment]
> our doc also contains `password_func`, see https://docs.pingcap.com/tidb/stable/sql-statement-show-builtins, this pr breaks this, but seems trivial
> 
> rest lgtm

I won't really call this documentation as it is just example output of `SHOW BUILTINS`. However this does mean that after this PR we need to update this page. I'll take care of that.

The output of `SHOW BUILTINS` also demonstrates an issue fixed by this PR:

With v8.4.0
```
mysql-8.0.11-TiDB-v8.4.0> pager grep password
PAGER set to 'grep password'
mysql-8.0.11-TiDB-v8.4.0> show builtins;
| old_password                |
| password_func               |
| validate_password_strength  |
303 rows in set (0.01 sec)

mysql-8.0.11-TiDB-v8.4.0> pager
Default pager wasn't set, using stdout.
mysql-8.0.11-TiDB-v8.4.0> SELECT old_password("abc");
ERROR 1305 (42000): FUNCTION OLD_PASSWORD does not exist
mysql-8.0.11-TiDB-v8.4.0> SELECT password_func("abc");
+-------------------------------------------+
| password_func("abc")                      |
+-------------------------------------------+
| *0D3CED9BEC10A777AEC23CCC353A8C08A633045E |
+-------------------------------------------+
1 row in set, 1 warning (0.01 sec)

mysql-8.0.11-TiDB-v8.4.0> SELECT password("abc");
+-------------------------------------------+
| password("abc")                           |
+-------------------------------------------+
| *0D3CED9BEC10A777AEC23CCC353A8C08A633045E |
+-------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql-8.0.11-TiDB-v8.4.0>
```

-  `OLD_PASSWORD()` is in the output of `SHOW BUILTINS`, while it shouldn't. This is fixed in #58327.
- `PASSWORD()` is not in the output of `SHOW BUILTINS`, while it should.
- `password_func()` is in the output, but otherwise undocumented (and not compatible with MySQL)

With this PR:
```
mysql-8.0.11-TiDB-v8.5.0-alpha-356-gdbd4eeaaf2> pager grep password
PAGER set to 'grep password'
mysql-8.0.11-TiDB-v8.5.0-alpha-356-gdbd4eeaaf2> show builtins;
| old_password                |
| password                    |
| validate_password_strength  |
303 rows in set (0.00 sec)

mysql-8.0.11-TiDB-v8.5.0-alpha-356-gdbd4eeaaf2> pager
Default pager wasn't set, using stdout.
```

**Comment by D3Hunter** [comment]
/hold

feel free to unhold after you discuss with frank

**Review by Frank945946 — APPROVED** [review]
Please update the corresponding documentation at the same time. The rest LGTM.

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
