### PR TITLE
table: InsertExec eliminate unnecessary CastValue.

### PR DESCRIPTION
**Pull request by winkyao**
run kvencoder bench, got:

master:
```
[direct] kv num = 24576000 / kv size = 2724864000
[direct] cost avg = 82.324 sec
```

this pr:
```
[direct] kv num = 24576000 / kv size = 2724864000
[direct] cost avg = 71.053 sec
```
  
13 % improvement

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by zimulala** [comment]
@winkyao 
Please fix CI.

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
