### PR TITLE
expression: fix panic in upper() and lower() func.

### LINKED ISSUE #32488: The function `upper` produces error for some special characters
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

With `new_collation_enabled` is `True`

```
create table t(a varchar(32)) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
insert into t values('ʞ');
select binary upper('ʞ');
select binary upper(a) from t;
select distinct upper(a) from t; 
```

### 2. What did you expect to see? (Required)

```
mysql> select binary upper('ʞ');
+----------------------------------------+
| binary upper('ʞ')                      |
+----------------------------------------+
| 0xEA9EB0                               |
+----------------------------------------+
1 row in set (0.03 sec)

mysql>  select binary upper(a) from t;
+----------------------------------+
| binary upper(a)                  |
+----------------------------------+
| 0xEA9EB0                         |
+----------------------------------+
1 row in set (0.03 sec)

mysql> select distinct upper(a) from t;
+----------+
| upper(a) |
+----------+
| Ʞ        |
+----------+
1 row in set (1.76 sec)
```

### 3. What did you see instead (Required)

```
mysql> select binary upper('ʞ');
+----------------------------------------+
| binary upper('ʞ')                      |
+----------------------------------------+
| 0xEA9EB0                               |
+----------------------------------------+
1 row in set (0.03 sec)

mysql>  select binary upper(a) from t;
+----------------------------------+
| binary upper(a)                  |
+----------------------------------+
| 0xEA9E                           |
+----------------------------------+
1 row in set (0.03 sec)

mysql> select distinct upper(a) from t;
ERROR 1105 (HY000): runtime error: index out of range [2] with length 2
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

master. But I think it effects all tidb versions

mysql> SELECT tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.16.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.03 sec)

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #32488

Problem Summary: `Columns.SetRaw` can't be used in upper() and lower(). Because the result of upper() and lower() may not same as before. 

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix panic in upper() and lower() func
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @lcwangchao @xiongjiwei @tangenta @zimulala 
PTAL

**Review by xiongjiwei — APPROVED** [review]

**Comment by lcwangchao** [comment]
I'm not very familiar with with those code related to functions. But the test case looks fine for me. @zimulala @tangenta PTAL

**Review by tangenta — APPROVED** [review]

**Pull request merged**
