### PR TITLE
server: close all connection directly when terminate tidb (#8692)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
cherry-pick #8692.

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8708)

### CODE REVIEW

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
