### PR TITLE
executor: avoid allocating a lot of memory at first in topn.

### PR DESCRIPTION
**Pull request by hanfei1991**
If we order by c1 limit int.max, topn will alloc a lot of memory for heap, which leads to oom. This pr fix it.

### CODE REVIEW

**Comment by shenli** [comment]
LGTM
But please add a unit test for this.

**Comment by hanfei1991** [comment]
I cannot reproduce it in unit test.

**Comment by shenli** [comment]
You can add a test "select * from t order by c limit int.Maxint64;"

**Comment by tiancaiamao** [comment]
why? @hanfei1991

**Comment by tiancaiamao** [comment]
fix https://github.com/pingcap/tidb/issues/3391

**Comment by shenli** [comment]
@hanfei1991 Any update?

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
