### PR TITLE
executor: remove Next function of IndexReaderExecutor

### PR DESCRIPTION
**Pull request by CocaLi**

### CODE REVIEW

**Comment by shenli** [comment]
@CocaLi Thanks!
Please fix the CI and sign the CLA.

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by zz-jason** [comment]
```sh
➜ unused github.com/pingcap/tidb/executor
executor/distsql.go:121:6: func decodeRawValues is unused (U1000)
executor/distsql.go:895:31: func (*tableResultHandler).next is unused (U1000)
```
please remove these unused fields and functions

**Pull request merged**
