### PR TITLE
statistics: GCStats should not wrongly remove record of an existing table

### LINKED ISSUE #57983: stats' gc process wrongly deletes the statistics of tables that are not analyzed in extreme situation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

like https://github.com/pingcap/tidb/issues/57901
Image
It directly uses the condition `no row in mysql.stats_histograms` without checking whether the table meta exists to decide the existence the of table.

But actually, due to poor cooperation with the DDL module. It's possible that we lost the records in mysql.stats_histograms for a table if there are plenty of DDLs executed in a row.

### 4. What is your TiDB version? (Required)

current master

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #57983 

Problem Summary:

When we try to delete the stats. We need to first ensure that the table is already deleted.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
修复统计信息垃圾回收时可能错误的删除统计信息记录的问题
Fix the issue that the stat' GC process may wrongly delete records of statistics.
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by Rustin170506 — CHANGES_REQUESTED** [review]
Thanks!

**Review by Rustin170506 — APPROVED** [review]
Thanks! :shipit:

Some nits.

/hold

**Review by hawkingrei — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
