### PR TITLE
ci: correct testing format

### PR DESCRIPTION
**Pull request by tisonkun**
### What problem does this PR solve?

testing format is like

```
--- PASS: TestSingle (0.26s)
```

cannot match "^PASS:"

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Please update here, it's already in the allow list, but seems our testing refactor cause the name changes:
https://github.com/pingcap/tidb/blob/master/tools/check/check-timeout.go#L74-L75

**Review by tiancaiamao — APPROVED** [review]

**Comment by tisonkun** [comment]
/cc @tangenta @xhebox 

PTAL.

**Review by tangenta — APPROVED** [review]

**Pull request merged**
