### PR TITLE
store/tikv: update max backoff.

### PR DESCRIPTION
**Pull request by disksing**
Based on the current tikv-server configuration, the leader election could last for more than 10 seconds. Therefore, max backoff need to be adjusted.

PTAL @coocood

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Comment by siddontang** [comment]
should use a smaller value.

**Comment by disksing** [comment]
PTAL @coocood @tiancaiamao @siddontang

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
