### PR TITLE
br: fix backup ci

### PR DESCRIPTION
**Pull request by Leavrth**
Signed-off-by: Leavrth <jianjun.liao@outlook.com>

### What problem does this PR solve?

Issue Number: ref #40404 #40898 

Problem Summary:
1. We need to use `autoIDAccess.SequenceValue().Get()` instead of `autoIDAccess.SequenceCycle().Get()`.
refer to 
https://github.com/pingcap/tidb/blob/48bc046fe1a92c5861ae11584f5a131debc471ff/meta/autoid/autoid.go#L1162-L1175
2. fix condition when fetch replica label
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

**Comment by wuhuizuo** [comment]
I think the title should be "br: fix backup client".

**Pull request merged**
