### PR TITLE
expression: give the function load_file an empty implement to support navicat premium to edit view

### PR DESCRIPTION
**Pull request by studiolee**
Signed-off-by: studiolee <1964773741@qq.com>

### What problem does this PR solve?

Problem Summary:
TiDB does not have function： load_file.
It leads to that navicat premium can't open view edit page.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: give en empty implement to load_file and add ut

How it Works: return empty string，navicat premium just need an empty result for load_file

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
Please add a release note, or a 'None' if it is not needed.
```

### CODE REVIEW

**Comment by kennytm** [comment]
according to the [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_load-file)

>  If the file does not exist or cannot be read because one of the preceding conditions is not satisfied, the function returns `NULL`. 

so always returning `NULL` is more appropriate than always returning `''`.

**Comment by studiolee** [comment]
> according to the [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_load-file)
> 
> > If the file does not exist or cannot be read because one of the preceding conditions is not satisfied, the function returns `NULL`.
> 
> so always returning `NULL` is more appropriate than always returning `''`.

According to Parser's definition，load_file belongs to string functions. So I implement it by interface function 'evalString'

But interface 'evalString' returns (string,  bool,  error) . So , returning nil will conflict with the interface definition.

**Comment by kennytm** [comment]
@studiolee Parser's categorization is not strict. Also, a string function *can* return NULL on non-NULL input:

```sql
mysql> select from_base64('aa');
+--------------------------------------+
| from_base64('aa')                    |
+--------------------------------------+
| NULL                                 |
+--------------------------------------+
1 row in set (0.04 sec)
```

**Comment by studiolee** [comment]
Some commit'sign is wrong。I will give a new pr later.

**Pull request closed without merging**
