### PR TITLE
*: remove useless parameter

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Problem Summary:
remove useless parameter

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by ngaut — APPROVED** [review]
LGTM

**Review by ichn-hu — APPROVED** [review]

**Comment by hawkingrei** [comment]
@XuHuaiyu PTAL

**Review by morgo — APPROVED** [review]

**Pull request merged**
