### PR TITLE
planner: fix incorrect results when using a prefix index with OR condition (#21251)

### LINKED ISSUE #21234: Incorrect results using a prefix index with OR condition
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t1 (id int unsigned not null auto_increment primary key, t text, index(t(8)));
insert into t1 (t) values (md5('a')),(md5('b'));
select * from t1 where t='0cc175b9c0f1b6a831c399e269772661' or t='92eb5ffee6ae2fec3ad71c777531578f';
```

### 2. What did you expect to see? (Required)

```
mysql> select * from t1;
+----+----------------------------------+
| id | t                                |
+----+----------------------------------+
|  1 | 0cc175b9c0f1b6a831c399e269772661 |
|  2 | 92eb5ffee6ae2fec3ad71c777531578f |
+----+----------------------------------+
2 rows in set (0.00 sec)

mysql> select /*+ IGNORE_INDEX(t1,t) */ * from t1 where t='0cc175b9c0f1b6a831c399e269772661' or t='92eb5ffee6ae2fec3ad71c777531578f';
+----+----------------------------------+
| id | t                                |
+----+----------------------------------+
|  1 | 0cc175b9c0f1b6a831c399e269772661 |
|  2 | 92eb5ffee6ae2fec3ad71c777531578f |
+----+----------------------------------+
2 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select * from t1 where t='0cc175b9c0f1b6a831c399e269772661' or t='92eb5ffee6ae2fec3ad71c777531578f';
Empty set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
tidb_version(): Release Version: v4.0.0-beta.2-1607-g93c3e6bec
Edition: Community
Git Commit Hash: 93c3e6becd5929cc37901d78d1f679cbc5d86342
Git Branch: HEAD
UTC Build Time: 2020-11-22 19:53:19
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21251 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #21234 

Problem Summary:
In the previous implementation, when we use a prefix index with OR condition, it will fail to Cut Datum By PrefixLen.

### What is changed and how it works?

When we use `detachDNFCondAndBuildRangeForIndex` function, we take prefix index into consideration.

### Check List 

Tests 

- Unit test
- Integration test
### Release note 

- fix incorrect results when using a prefix index with OR condition

### CODE REVIEW

**Review by winoros — COMMENTED** [review]
lgtm

**Comment by Reminiscent** [comment]
@SunRunAway @lzmhhh123 PTAL

**Review by lzmhhh123 — APPROVED** [review]
LGTM

**Comment by tiancaiamao** [comment]
```
[2020-11-26T05:54:31.229Z] ==================
[2020-11-26T05:54:31.229Z] WARNING: DATA RACE
[2020-11-26T05:54:31.229Z] Write at 0x00c000155afe by goroutine 138:
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/sessionctx/variable.(*SessionVars).SetSystemVar()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/sessionctx/variable/session.go:1357 +0x3d3d
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/sessionctx/variable.SetSessionSystemVar()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/sessionctx/variable/varsutil.go:228 +0x1b9
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/executor.(*SetExecutor).setSysVariable()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/set.go:187 +0x19e0
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/executor.(*SetExecutor).Next()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/set.go:108 +0x308
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/executor.Next()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:253 +0x27d
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:519 +0x38e
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:401 +0x254
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:354 +0x3f6
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/session.runStmt()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:308 +0x2f2
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/session.(*session).executeStatement()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1082 +0xd9
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/session.(*session).execute()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1194 +0xaa2
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/session.(*session).Execute()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1125 +0xee
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:151 +0x103
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:189 +0x91
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/infoschema_test.(*testTableSuite).TestStmtSummaryTable()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/infoschema/tables_test.go:900 +0xb2
[2020-11-26T05:54:31.229Z]   runtime.call32()
[2020-11-26T05:54:31.229Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a
[2020-11-26T05:54:31.229Z]   reflect.Value.Call()
[2020-11-26T05:54:31.229Z]       /usr/local/go/src/reflect/value.go:321 +0xd3
[2020-11-26T05:54:31.229Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa
[2020-11-26T05:54:31.229Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113
[2020-11-26T05:54:31.229Z] 
[2020-11-26T05:54:31.229Z] Previous read at 0x00c000155afe by goroutine 117:
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/executor.ResetContextOfStmt()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:1695 +0xb2c
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/session.(*session).execute()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1170 +0x7de
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/session.(*session).Execute()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1125 +0xee
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/session.execRestrictedSQL()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:836 +0x18f
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/session.(*session).ExecRestrictedSQLWithContext()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:779 +0x204
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/session.(*session).ExecRestrictedSQL()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:753 +0x92
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/bindinfo.(*BindHandle).Update()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/bindinfo/handle.go:137 +0x16c
[2020-11-26T05:54:31.229Z]   github.com/pingcap/tidb/domain.(*Domain).globalBindHandleWorkerLoop.func1()
[2020-11-26T05:54:31.229Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/domain/domain.go:931 +0x254
```

**Comment by Reminiscent** [comment]
@SunRunAway @lzmhhh123 PTAL. Please help merge. Thanks!

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
