### PR TITLE
server,store,util: escape internal SQL statement

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Manually back port some of the changes https://github.com/pingcap/tidb/pull/22621 to release-2.1

Problem Summary:

### What is changed and how it works?

What's Changed:

Escape SQL

How it Works:

### Check List 

Tests 

- No code

### Release note 

- No release note

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
Looks good to me

**Comment by tiancaiamao** [comment]
PTAL @morgo @xhebox

**Comment by xhebox** [comment]
I've got a LGTM. New changes LGTM. So I will just wait for new changes.

**Pull request merged**
