### PR TITLE
executor: disable password validation for `tidb_auth_token` users | tidb-test=pr/2136

### LINKED ISSUE #44098: Create user with `tidb_auth_token` should not validate password
## Bug Report

Password validation should not take effect towards to users with 'tidb_auth_token'

### 1. Minimal reproduce step (Required)

```sql
set global validate_password.enable = 1
create user u1 identified with 'tidb_auth_token'
```

### 2. What did you expect to see? (Required)

Succeed to create user

### 3. What did you see instead (Required)

> (1819, 'Your password does not satisfy the current policy requirements')

### 4. What is your TiDB version? (Required)

Master, v7.1, v6.5

### PR DESCRIPTION
**Pull request by CbcWestwolf**
### What problem does this PR solve?

Issue Number: close #44098

Problem Summary:

Password validation should only take effect for users that authenticate with a password, like `mysql_native_password`, `caching_sha2_password` and `tidb_sm3_password`

### What is changed and how it works?

Disable password validation for users without clear text password

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix a bug that validates passwords for users with `tidb_auth_token`
```

### CODE REVIEW

**Comment by CbcWestwolf** [comment]
/cc xhebox hawkingrei 
PTAL

**Review by xhebox — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
