### PR TITLE
statistics: remove the deltaMap when dump to stats_histograms fail

### LINKED ISSUE #32299: Slow query 'update mysql.stats_meta ...' caused by write conflict
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Found from a customer's environment.

In the TiDB dashboard, there are some slow query takes more than 10s

image

In the TiDB log, I found the slow query is caused by transaction conflict and retry ...

```
[2021/09/25 15:39:00.151 +08:00] [WARN] [session.go:691] [retrying] [schemaVersion=158] [retryCnt=0] [queryNum=0] [sql="insert into mysql.stats_histograms (table_id, is_index, hist_id, distinct_count, tot_col_size) values (128, 0, 17, 0, 46864),(128, 0, 7, 0, 778),(128, 0, 10, 0, 6360),(128, 0, 16, 0, 6224),(128, 0, 12, 0, 6224),(128, 0, 14, 0, 778),(128, 0, 2, 0, 7002),(128, 0, 18, 0, 4040),(128, 0, 15, 0, 6224),(128, 0, 9, 0, 166567),(128, 0, 19, 0, 11312),(128, 0, 8, 0, 72171),(128, 0, 13, 0, 6224),(128, 0, 1, 0, 3112),(128, 0, 6, 0, 478833),(128, 0, 3, 0, 778),(128, 0, 4, 0, 29172),(128, 0, 5, 0, 29172) on duplicate key update tot_col_size = tot_col_size + values(tot_col_size)"] [isPessimistic=false]
[2021/09/25 15:39:00.155 +08:00] [INFO] [2pc.go:1336] ["2PC clean up done"] [txnStartTS=427964639513149469]
```

This is a internal SQL, this kind of slow query is unexpected.

### 2. What did you expect to see? (Required)

No such slow query "update mysql.stats_meta ..." by transaction retry.

### 3. What did you see instead (Required)

Slow internal query "update mysql.stats_meta" takes 10s+

### 4. What is your TiDB version? (Required)

v4.0.10

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #32299

Problem Summary:

When the `dumpTableStatColSizeToKV` operation fail, it will not clean the map data.
And then in the next loop, it will retry the operation of `dumpTableStatColSizeToKV`, the fail again and again.

The retry of the failed operation cause transaction conflict and lead to the 10s+ "update mysql.stats_meta" slow query.

### What is changed and how it works?

Clean the data if `dumpTableStatColSizeToKV` fail, so not retry and transaction conflict avalanche.

### Check List

Tests 

It's really hard to test, because it's only observed in one customer's env and can't reproduce.
Under common situation, this bug should never happen.

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by ichn-hu — APPROVED** [review]
would be nicer to have a failpoint test

**Review by time-and-fate — APPROVED** [review]

**Comment by guo-shaoge** [comment]
@tiancaiamao Does v5.3 also need cherry pick. Looks like it's a small change?

**Pull request merged**
