### PR TITLE
admin: loop unwinding for CancelJobs

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: ref #31716

Problem Summary:

### What is changed and how it works?

Loop unwinding

### Check List

Tests 

use old test

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by xiongjiwei — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by tangenta** [comment]
```
fatal error: invalid g status
```

There must be some wrong usages about GC...

**Comment by hawkingrei** [comment]
> fatal error: invalid g status

it often happens #32690

**Pull request merged**
