### PR TITLE
expr: fix `unix_timestamp` range check

### LINKED ISSUE #32197: TiDB `unix_timestamp` returns wrong result if the input is out of range
## Bug Report

Please answer these questions before submitting your issue. Thanks!
According to MySQL [doc](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_unix-timestamp), if the input of `unix_timestamp` is out of range(not between '1970-01-01 00:00:01.000000' UTC and '2038-01-19 03:14:07.999999' UTC for MySQL before 8.0.28 and TiDB), it should return 0
### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```
mysql> set time_zone='UTC';
Query OK, 0 rows affected (0.00 sec)

mysql> select unix_timestamp('1970-01-01 00:00:00.000001');
+----------------------------------------------+
| unix_timestamp('1970-01-01 00:00:00.000001') |
+----------------------------------------------+
|                                     0.000001 |
+----------------------------------------------+
1 row in set (0.00 sec)

```
### 2. What did you expect to see? (Required)
```
mysql>  select unix_timestamp('1970-01-01 00:00:00.000001');
+----------------------------------------------+
| unix_timestamp('1970-01-01 00:00:00.000001') |
+----------------------------------------------+
|                                     0.000000 |
+----------------------------------------------+
1 row in set (0.01 sec)
```
### 3. What did you see instead (Required)
```
mysql>  select unix_timestamp('1970-01-01 00:00:00.000001');
+----------------------------------------------+
| unix_timestamp('1970-01-01 00:00:00.000001') |
+----------------------------------------------+
|                                     0.000001 |
+----------------------------------------------+
1 row in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)
<!-- Paste the output of SELECT tidb_version() -->
```
mysql> select tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.5.0-alpha-202-g077eb80f1
Edition: Community
Git Commit Hash: 077eb80f1317a54b1a73894d9f58cd6dfff19260
Git Branch: master
UTC Build Time: 2022-02-08 04:27:22
GoVersion: go1.17.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by likzn**
### What problem does this PR solve?

Issue Number: close #32197

Problem Summary: According to MySQL [doc](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_unix-timestamp), if the input of unix_timestamp is out of range(not between '1970-01-01 00:00:01.000000' UTC and '2038-01-19 03:14:07.999999' UTC for MySQL before 8.0.28 and TiDB), it should return 0. But now the `left edge` is not right.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — COMMENTED** [review]
I am in favor of not forbidding this, since it will be compatible with newer mysql. So I won't give LGTM.

**Comment by likzn** [comment]
What is `newer mysql`, has any ref about it? I find mysql doc in 8.0, the left edge is also `1970-01-01 00:00:01.000000`.

> Prior to MySQL 8.0.28, the valid range of argument values is the same as for the [TIMESTAMP](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) data type: '1970-01-01 00:00:01.000000' UTC to '2038-01-19 03:14:07.999999' UTC. This is also the case in MySQL 8.0.28 and later for 32-bit platforms. For MySQL 8.0.28 and later running on 64-bit platforms, the valid range of argument values for UNIX_TIMESTAMP() is '1970-01-01 00:00:01.000000' UTC to '3001-01-19 03:14:07.999999' UTC (corresponding to 32536771199.999999 seconds).

**Comment by xhebox** [comment]
> What is `newer mysql`, has any ref about it? I find mysql doc in 8.0, the left edge is also `1970-01-01 00:00:01.000000`.

I am concerning about the right edge, which is different. And for the left edge, yeah, I agree that your change is correct.

**Comment by likzn** [comment]
But i only change the left edge. The right edge is still original. And i think If we need to adapt to 64 bit machine like newer mysql, it might be a unified and further job

**Comment by xhebox** [comment]
> But i only change the left edge. The right edge is still original. And i think If we need to adapt to 64 bit machine like newer mysql, it might be a unified and further job

Maybe change `close #xxx` to `ref #xxx`. Since the original bug is not closed by the issue.

**Review by xhebox — APPROVED** [review]

**Comment by xhebox** [comment]
> But i only change the left edge. The right edge is still original. And i think If we need to adapt to 64 bit machine like newer mysql, it might be a unified and further job

After discussing with the author of the issue, he clarified that the issue is only to target the left edge, or low/bottom limit of the timestamp range. And the whole valid range should be another issue. So this PR will close the issue now, I've changed it back. @likzn

**Comment by likzn** [comment]
> > But i only change the left edge. The right edge is still original. And i think If we need to adapt to 64 bit machine like newer mysql, it might be a unified and further job
> 
> After discussing with the author of the issue, he clarified that the issue is only to target the left edge, or low/bottom limit of the timestamp range. And the whole valid range should be another issue. So this PR will close the issue now, I've changed it back. @likzn

Get it. (New avatar is nice hhh

**Review by tangenta — APPROVED** [review]

**Review by jackysp — APPROVED** [review]
LGTM

**Pull request merged**
