### PR TITLE
executor: migrate test-infra to testify for simple_test

### LINKED ISSUE #28614: migrate test-infra to testify for `simple_test.go`

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #28614

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
/merge

Although some lines like:

```go
_, err = tk.Exec(...)
require.NoError(t , err)
// or
_, err = tk.Exec(...)
require.Error(t , err)
```

can be simplify as:

```go
tk.MustExec(...)
// and
require.Error(tk.ExecToErr(...))
```

They're not a blocker for migration.

**Comment by hawkingrei** [comment]
It has some problem in test to fix.

**Pull request merged**
