### PR TITLE
store/driver/txn/error: fix improper error print message

### LINKED ISSUE #35289: Error message of duplicate primary key is not shown properly
## Enhancement

Actual:
```sql
mysql> CREATE TABLE t1 (a BINARY(16) PRIMARY KEY);
Query OK, 0 rows affected (0.02 sec)

mysql> INSERT INTO t1 VALUES (AES_ENCRYPT('a','a'));
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (AES_ENCRYPT('a','a'));
ERROR 1062 (23000): Duplicate entry '{ W]�u����.�٧t' for key 'PRIMARY'
```

Expected:
```sql
mysql> CREATE TABLE t1 (a BINARY(16) PRIMARY KEY);
Query OK, 0 rows affected (0.05 sec)

mysql> INSERT INTO t1 VALUES (AES_ENCRYPT('a','a'));
Query OK, 1 row affected (0.02 sec)

mysql> INSERT INTO t1 VALUES (AES_ENCRYPT('a','a'));
ERROR 1062 (23000): Duplicate entry '{ W]\xA1\x06u\x9D\xBD\xB1\xA3.\xE2\xD9\xA7t' for key 't1.PRIMARY'
```

### PR DESCRIPTION
**Pull request by rahulk789**
### What problem does this PR solve?
This PR solves the problem of displaying improper error messages whose strings have hex escape sequences which are inturn converted to UTF-8

Issue Number: close #35289 

Problem Summary:

### What is changed and how it works?
I have added a function named strconv.Quote in error.go file in order to print raw text message when an error occurs.
The concern I have is that the printed error message is displayed inside double quotes.

(This is my first contribution on github, so corrections are very much appreciated. I shall try my best to fix them. Thank you!)

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
CI message is a bit messy and long, you can search some pattern to find the error. For example, in https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/56515/pipeline you can click “显示完整日志” and go to https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_unit_test/runs/56515/nodes/59/steps/64/log/?start=0

Then search for "Error:' can find some errors, like

```
[2022-06-29T14:46:57.637Z] === RUN   TestSQLModeVar
[2022-06-29T14:46:57.637Z]     sysvar_test.go:308: 
[2022-06-29T14:46:57.637Z]         	Error Trace:	sysvar_test.go:308
[2022-06-29T14:46:57.637Z]         	Error:      	Not equal: 
[2022-06-29T14:46:57.637Z]         	            	expected: "ERROR 1231 (42000): Variable 'sql_mode' can't be set to the value of 'NONSENSE_OPTION'"
[2022-06-29T14:46:57.637Z]         	            	actual  : "ERROR 1231 (42000): \"Variable 'sql_mode' can't be set to the value of 'NONSENSE_OPTION'\""
[2022-06-29T14:46:57.637Z]         	            	
[2022-06-29T14:46:57.637Z]         	            	Diff:
[2022-06-29T14:46:57.637Z]         	            	--- Expected
[2022-06-29T14:46:57.637Z]         	            	+++ Actual
[2022-06-29T14:46:57.637Z]         	            	@@ -1 +1 @@
[2022-06-29T14:46:57.637Z]         	            	-ERROR 1231 (42000): Variable 'sql_mode' can't be set to the value of 'NONSENSE_OPTION'
[2022-06-29T14:46:57.637Z]         	            	+ERROR 1231 (42000): "Variable 'sql_mode' can't be set to the value of 'NONSENSE_OPTION'"
[2022-06-29T14:46:57.637Z]         	Test:       	TestSQLModeVar
[2022-06-29T14:46:57.637Z] --- FAIL: TestSQLModeVar (0.00s
```

And, don't forget to sign CLA

**Comment by tangenta** [comment]
@rahulk789 Using `strconv.Quote` may introduce the unexpected escaped character `\`. The problematic code is [here](https://github.com/pingcap/tidb/blob/2ef71689913081f99cae1ee1ce51a0e4a7341e13/store/driver/txn/error.go#L128-L139), we need to change the non-ASCII characters to `\x`-style before `strings.Join()`.

It is recommend to run & debug the issue's test case in your local environment :)

**Comment by rahulk789** [comment]
> @rahulk789 Using `strconv.Quote` may introduce the unexpected escaped character `\`. The problematic code is [here](https://github.com/pingcap/tidb/blob/2ef71689913081f99cae1ee1ce51a0e4a7341e13/store/driver/txn/error.go#L128-L139), we need to change the non-ASCII characters to `\x`-style before `strings.Join()`.
> 
> It is recommend to run & debug the issue's test case in your local environment :)

I am extremely sorry for the inconvenience caused.  I shall be opening a new PR.

**Comment by tangenta** [comment]
@rahulk789  You don't have to open another a PR. You can use `git push --force` to overwrite you current commits.

**Comment by rahulk789** [comment]
@tangenta I have replicated the issue locally. The function `strings.Join()` converts the `\x` characters in the raw string that my code creates, to unicode ones. So the question marks won't go away.

**Pull request closed without merging**
