### PR TITLE
ddl: support rename table for label rules

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/27019

### What is changed and how it works?

What's Changed:
- modify the `checkAndRenameTables` to get the old rules and update rules by using the new ones

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (E2E test in endless)
- [ ] No code

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [x] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by rleungx** [comment]
E2E tests can be found in https://github.com/pingcap/endless/pull/35/commits/b5e654654aab505b35af081e593b4ec0776f02fc

**Review by disksing — APPROVED** [review]

**Review by xhebox — APPROVED** [review]
LGTM, but need to complete tests and refactor as said in https://github.com/pingcap/tidb/pull/27102#pullrequestreview-742386183

**Pull request merged**
