### PR TITLE
ddl: support alter table partition attribute to add label rules 

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Closes https://github.com/pingcap/tidb/issues/26704

### What is changed and how it works?

This PR is going to support adding label rules for a partition through the following syntax:
```
ALTER TABLE t PARTITION p ATTRIBUTES="attr1,attr2"
```

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Documentation

- [x] Affects user behaviors
- [x] Contains syntax changes
- [ ] Contains variable changes
- [x] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by Yisaer — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]
/cc PTAL @morgo

**Review by morgo — APPROVED** [review]

**Pull request merged**
