### PR TITLE
table: fix error code different from mysql "error 1604 : locate partition failed"

### PR DESCRIPTION
**Pull request by ciscoxll**
### What problem does this PR solve? 
Cherry pick #9294

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by ciscoxll** [comment]
@crazycs520 PTAL.

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by ciscoxll** [comment]
Need to change mysql-test.

**Comment by ciscoxll** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1 tidb-test=pr/734

**Comment by jackysp** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1 tidb-test=pr/743

**Pull request merged**
