### PR TITLE
session: enable async commit in new clusters

### PR DESCRIPTION
**Pull request by sticnarf**
### What is changed and how it works?

This is some configuration adjustments for async commit.

We hope to enable async commit and 1PC by default for newly created TiDB 5.0 clusters.

And `SafeWindow` and `AllowedClockDrift` are made configurable, in case some users have very special requirements (like running a lot of `ADD INDEX` DDLs).

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

### Release note 

- Enable async commit in new clusters.

### CODE REVIEW

**Review by MyonKeminta — APPROVED** [review]

**Comment by sticnarf** [comment]
RACE: https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_unit_test/runs/67540/nodes/82/steps/339/log/?start=0
Seems not related to this PR.

**Pull request merged**
