### PR TITLE
*: fix staticcheck errors in folder types

### PR DESCRIPTION
**Pull request by hsqlu**
### What problem does this PR solve? 
#13456 
This pr fixed the staticcheck report errors under package types.

### Check List 

Tests 

 - No code

Code changes

### CODE REVIEW

**Comment by hsqlu** [comment]
@zhouqiang-cl @wjhuang2016 Can you please have a look at this pr? Thanks

**Comment by wjhuang2016** [comment]
Please describe the problem  you solved and so on in PR description

**Comment by hsqlu** [comment]
> Please describe the problem you solved and so on in PR description

Update. This related to issue #13736

**Comment by wjhuang2016** [comment]
Thanks, could you post the problem you solve(by screenshot or quote) next time so that we can find out easier why the code is updated or removed?

**Comment by hsqlu** [comment]
> Thanks, could you post the problem you solve(by screenshot or quote) next time so that we can find out easier why the code is updated or removed?

Ohhh. I see. Will do in the following PRs. Thanks

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
