### PR TITLE
plan: fix predicate push down for UnionScan

### PR DESCRIPTION
**Pull request by coocood**
### What problem does this PR solve? 
Cherry-pick https://github.com/pingcap/tidb/pull/7695

### What is changed and how it works?
The predicate push down for UnionScan plan returns retained predicates instead of nil.

If we return nil predicates, the parent Selection will be removed, but conditions in UnionScan is only used to evaluate dirty table added rows, the conditions that cannot be pushed down to coprocessor will be lost.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by coocood** [comment]
/run-all-tests tikv=release-2.0 tidb-test=release-2.0 pd=release-2.0

**Comment by shenli** [comment]
LGTM

**Comment by lysu** [comment]
/run-common-test tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0
/run-integration-common-test tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by coocood** [comment]
/run-all-tests tidb-test=pr/624 tikv=release-2.0 pd=release-2.0

**Pull request merged**
