### PR TITLE
executor: add placement policy name / direct placement to is.tables/partitions

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Related to #18030 and #26681.

Problem Summary:
Missing ways to get placement from tables and partitions in an easy way or machine readable.
I added two new columns to both information_schema.tables and information_schema.partitions:
TIDB_PLACEMENT_POLICY_NAME and TIDB_DIRECT_PLACEMENT, which are NULLable varchar.

TIDB_PLACEMENT_POLICY_NAME refers to the named placement policy, and can be expanded either with `SHOW PLACEMENT FOR POLICY <policy name>` or through information_schema.placement_rules (like `SELECT * FROM information_schema.tables t left join information_schema.placement_rules pr on t.TIDB_PLACEMENT_POLICY_NAME = pr.POLICY_NAME WHERE t.TABLE_NAME = 't'`

### What is changed and how it works?

What's Changed:
Two new columns in is.tables and is.partitions

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility - New columns in is.tables and is.partitions

### Release note 

```release-note
Added TIDB_PLACEMENT_POLICY_NAME and TIDB_DIRECT_PLACEMENT columns to information_schema tables `tables` and `partitions`
```

### CODE REVIEW

**Comment by morgo** [comment]
I like it. Please add tests :-)

**Comment by xhebox** [comment]
> I like it. Please add tests :-)

Do we need to record it in the RFC?

**Pull request merged**
