### PR TITLE
domain: 'load privilege failed' when autocommit is off

### LINKED ISSUE #26686: "load privilege failed" when autocommit is off
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

mysql> set global  autocommit = 0;

$ tiup cluster stop XXX

$ tiup cluster start XXX

wait some time, about 20 min,  when gc_safe_point > cluster start time.

### 3. What did you see instead (Required)

tidb log:

[2021/07/27 19:11:23.710 +08:00] [WARN] [cache.go:281] ["load mysql.user fail"] [error="[tikv:9006]GC life time is shorter than transaction duration, transaction starts at 2021-07-26 17:51:22.285 +0800 CST, GC safe point is 2021-07-27 18:09:14.735 +0800 CST"]
[2021/07/27 19:11:23.710 +08:00] [ERROR] [domain.go:892] ["load privilege failed"] [error="[privilege:8049]mysql.user"]

### 4. What is your TiDB version? (Required)

v4.0.11, infact v5.0.2, v5.2.0 all have the problems.

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #26686

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

set LoadPrivilegeLoop session autocommit on, even if global autocommit if off.

How it Works:

### Check List 

Tests 

- [ ] Unit test

- [ ] Manual test 

1. tiup cluster start XXXX
2.  mysql> set global autocommit = 0;
3. tiup cluster stop XXXX
4. tiup cluster start XXXX
5. wait 20 min
6. open tidb.log , no error like this occur:   load privilege failed

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

set  session varaible autocommit on for load privilege function.

### CODE REVIEW

**Comment by bb7133** [comment]
Hi @jiyfhust thanks for the contribution! BTW you can use the 'close' syntax to link your PR to the issue:

This PR close #26686

**Comment by jiyfhust** [comment]
> Hi @jiyfhust thanks for the contribution! BTW you can use the ['close' syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to link your PR to the issue:
> 
> This PR close #26686

thx， now i  have added it.

**Review by bb7133 — APPROVED** [review]

**Comment by bb7133** [comment]
LGTM

BTW, I think the other internal sessions(`se` .. `se7`) should be reviewed as well: https://github.com/pingcap/tidb/blob/404954f9bdafa79bb3c340c695ba3abfba074d7d/session/session.go#L2509-L2620

@jiyfhust , would you like to check those codes and if similar issues can be found? Thanks!

**Review by morgo — APPROVED** [review]

**Comment by jiyfhust** [comment]
> @jiyfhust , would you like to check those codes and if similar issues can be found? Thanks!

I am glad to do it, but the progress cannot be guaranteed.I can spend some time focusing on this.

**Pull request merged**
