### PR TITLE
planner/cascades: remove ColumnSubstitute in the rule PushSelDownAgg

### LINKED ISSUE #14590: planner/cascades: PushSelDownAgg paniced when substitute columns
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
mysql> set session tidb_enable_cascades_planner=1;
Query OK, 0 rows affected (0.01 sec)

mysql> select b, max(a) from t group by b having b > 10;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

2. What did you expect to see?

The predicate `b > 10` should be pushed down.

3. What did you see instead?
```
PANIC: integration_test.go:150: testIntegrationSuite.TestAggregation

... Panic: runtime error: index out of range [3] with length 2 (PC=0xDBF2E1)

/home/francis/App/go/src/runtime/panic.go:679
  in gopanic
/home/francis/App/go/src/runtime/panic.go:75
  in goPanicIndex
/home/francis/tidb/tidb/expression/util.go:213
  in ColumnSubstituteImpl
/home/francis/tidb/tidb/expression/util.go:229
  in ColumnSubstituteImpl
/home/francis/tidb/tidb/expression/util.go:200
  in ColumnSubstitute
transformation_rules.go:546
  in PushSelDownAggregation.OnTransform
optimize.go:190
  in Optimizer.findMoreEquiv
optimize.go:163
  in Optimizer.exploreGroup
optimize.go:157
  in Optimizer.exploreGroup
optimize.go:157
  in Optimizer.exploreGroup
optimize.go:157
  in Optimizer.exploreGroup
optimize.go:157
  in Optimizer.exploreGroup
optimize.go:157
  in Optimizer.exploreGroup
optimize.go:157
  in Optimizer.exploreGroup
optimize.go:133
  in Optimizer.onPhaseExploration
optimize.go:111
  in Optimizer.FindBestPlan
/home/francis/tidb/tidb/planner/optimize.go:169
  in optimize
/home/francis/tidb/tidb/planner/optimize.go:60
  in Optimize
/home/francis/tidb/tidb/planner/core/planbuilder.go:2695
  in PlanBuilder.buildExplain
/home/francis/tidb/tidb/planner/core/planbuilder.go:387
  in PlanBuilder.Build
/home/francis/tidb/tidb/planner/optimize.go:133
  in optimize
/home/francis/tidb/tidb/planner/optimize.go:60
  in Optimize
/home/francis/tidb/tidb/executor/compiler.go:61
  in Compiler.Compile
/home/francis/tidb/tidb/session/session.go:1112
  in session.execute
/home/francis/tidb/tidb/session/session.go:1066
  in session.Execute
/home/francis/tidb/tidb/util/testkit/testkit.go:144
  in TestKit.Exec
/home/francis/tidb/tidb/util/testkit/testkit.go:235
  in TestKit.MustQuery
integration_test.go:166
  in testIntegrationSuite.TestAggregation.func1
/home/francis/tidb/tidb/util/testutil/testutil.go:247
  in TestData.OnRecord
integration_test.go:164
  in testIntegrationSuite.TestAggregation
/home/francis/App/go/src/reflect/value.go:321
  in Value.Call
/home/francis/go/pkg/mod/github.com/pingcap/check@v0.0.0-20191216031241-8a5a85928f12/check.go:850
  in suiteRunner.forkTest.func1
/home/francis/go/pkg/mod/github.com/pingcap/check@v0.0.0-20191216031241-8a5a85928f12/check.go:739
  in suiteRunner.forkCall.func1
/home/francis/App/go/src/runtime/asm_amd64.s:1357
  in goexit
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

### PR DESCRIPTION
**Pull request by francis0407**
### What problem does this PR solve? 
fix #14590.

### What is changed and how it works?
1. PushSelDownAgg does not need ColumnSubstitue since those columns won't be changed in LogicalAggregation. (Note: we only pushes down predicate if all of it's columns are in `groupByCols`. In other words, predicate in `select a+b, max(c) from t group by a+b having a+b > 10` cannot be pushed down.)

2. Keep the old group expr in the rule MergeAggregationProjection, so that we can push down predicates in `select d, max(c) from (select a+b as d, c from t) t1 group by d having d > 10`.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by lamxTyler** [comment]
@francis0407 Please resolve conflicts.

**Comment by francis0407** [comment]
Finally T.T ....

**Pull request merged**
