### PR TITLE
executor: implement parallel merge join

### PR DESCRIPTION
**Pull request by iamzhoug37**
### What problem does this PR solve? 
 merge join parallelize to speed up the merge join executor.
test case:
machine configuration：4 CPU,8G memory
Two identical tables A and B contain 1000 numbers, each of which has 1000 rows.
SQL：`select count(*) from A left join B on a.i = b.i`
old tidb-server cost：2 min 12.55 sec
new tidb-server cost: 1 min 39.84 sec
 After merge join parallelled, time cost reduce 20%, cpu's using up to 300%~400%

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Comment by qw4990** [comment]
Hi, @iamzhoug37 , could you please solve the CI problems?

**Comment by iamzhoug37** [comment]
ok

**Comment by zz-jason** [comment]
@iamzhoug37 friendly ping, any update?

**Comment by zz-jason** [comment]
closed due to outdated, fell free to reopen it if it's needed.

**Pull request closed without merging**
