### PR TITLE
makefile: add --enable=deadcode to static-check

### PR DESCRIPTION
**Pull request by An-DJ**
### What problem does this PR solve?

Issue Number:  #22979 

Problem Summary: packages which linter `--enable=deadcode` cannot pass are as follows.

- [X] planner (#23117)
- [X] plugin (#23163)
- [X] store (#23120)
- [X] executor (#23111)
- [X] expression (#23118)

### What is changed and how it works?

What's Changed: All items which cannot pass are solved by pr above. This pr just open `--enable=deadcode` in Makefile.

How it Works: Make `check-static` success.

### Check List 

Tests 

- No code

Side effects

- none

### Release note 

- No release note

### CODE REVIEW

**Comment by wjhuang2016** [comment]
/LGTM，thanks.

**Review by ngaut — APPROVED** [review]
/LGTM

**Pull request merged**
