### PR TITLE
tests: debug / fix rawkv

### PR DESCRIPTION
**Pull request by YuJuncen**
Signed-off-by: yujuncen <yujuncen@pingcap.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/31267

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Review by joccau — APPROVED** [review]
LGTM

**Review by 3pointer — APPROVED** [review]

**Comment by YuJuncen** [comment]
image

/merge

**Pull request merged**
