### PR TITLE
*: shard implicit row ID

### PR DESCRIPTION
**Pull request by coocood**

### CODE REVIEW

**Comment by coocood** [comment]
/run-all-test tikv=release-1.0 tidb-test=release-1.0 tidb-private-test=release-1.0

**Comment by coocood** [comment]
/run-all-tests tikv=release-1.0 tidb-test=release-1.0 tidb-private-test=release-1.0

**Comment by coocood** [comment]
@shenli @zimulala PTAL

**Comment by shenli** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
