### PR TITLE
planner: rename stable-result-mode to ordered-result-mode

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary: planner: rename stable-result-mode to ordered-result-mode

### What is changed and how it works?

planner: rename stable-result-mode to ordered-result-mode

### Check List 

Tests 

- Unit test

### Release note 

- `No release note`

### CODE REVIEW

**Review by Reminiscent — APPROVED** [review]

**Comment by Reminiscent** [comment]
Please fix the test in ```FAIL: set_test.go:41: testSerialSuite1.TestSetVar```

**Review by zhangjinpeng1987 — APPROVED** [review]
LGTM

**Comment by zhangjinpeng1987** [comment]
Also should cherry pick to the latest release-4.0 branch

**Comment by qw4990** [comment]
> Also should cherry pick to the latest release-4.0 branch

Yes, I'll pick it after merging https://github.com/pingcap/tidb/pull/25995, https://github.com/pingcap/tidb/pull/26084

**Review by winoros — APPROVED** [review]

**Pull request merged**
