### PR TITLE
*: upgrade pd client

### PR DESCRIPTION
**Pull request by CabinfeverB**
Signed-off-by: Cabinfever_B <cabinfeveroier@gmail.com>

### What problem does this PR solve?

Issue Number: ref [#5207](https://github.com/tikv/pd/issues/5207)

Problem Summary:

### Check List

Tests 

- [x] Manual test (add detailed scripts or steps below)
kill pd leader and insert data
image

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]

**Comment by sticnarf** [comment]
@CabinfeverB Maybe you need to update the bazel file again after updating client-go

**Pull request merged**
