### PR TITLE
planner: append common handle columns into the schema of index merge table plan

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23906

Problem Summary:

Planner fails to build a plan.

### What is changed and how it works?

What's Changed:
- append common handle columns into the schema of index merge table plan

### Related changes

N/A

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- Append common handle columns into the schema of index merge table plan

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by tangenta — COMMENTED** [review]
I found the following case still failed:

```sql
drop table if exists t;
create table t (a int, b int, c int, primary key (a, b) clustered, key idx_c(c));
insert into t values (0, 1, 2);
select /*+ use_index_merge(t) */ c from t where c > 10 or a < 1;
```

```console
ERROR 1105 (HY000): invalid encoded key
```

**Comment by tangenta** [comment]
> I found the following case still failed:
> 
> ```sql
> drop table if exists t;
> create table t (a int, b int, c int, primary key (a, b) clustered, key idx_c(c));
> insert into t values (0, 1, 2);
> select /*+ use_index_merge(t) */ c from t where c > 10 or a < 1;
> ```
> 
> ```
> ERROR 1105 (HY000): invalid encoded key
> ```

This problem will be fixed in https://github.com/pingcap/tidb/pull/23936.

**Comment by ichn-hu** [comment]
I enabled e2e-test just now, but it is failing, sorry for bringing trouble.

**Pull request merged**
