### PR TITLE
statistics: migrate test-infra to testify for statistics/handle/ddl_test.go

### LINKED ISSUE #28125: migrate test-infra to testify for `statistics/handle/ddl_test.go`

### PR DESCRIPTION
**Pull request by feitian124**
### What problem does this PR solve?

Issue Number: close #28125 

based on pr https://github.com/pingcap/tidb/pull/28301

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM.

/hold

for rebase after base PR merged.

**Review by xuyifangreeneyes — APPROVED** [review]

**Comment by feitian124** [comment]
@mmyj could you help merge? thanks.

**Comment by feitian124** [comment]
seems merge not work, could you help check? @mmyj

**Review by mmyj — APPROVED** [review]
lgtm

**Comment by mmyj** [comment]
@feitian124 Merge done.

**Pull request merged**
