### PR TITLE
ddl: disable some DDL operation when a table is cached

### LINKED ISSUE #32826: Disable some DDL operation when the table is cached

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #32826

Problem Summary:

### What is changed and how it works?

When the table is cached, some DDL operation is not safe any more.
For example, add index or add colum, to even truncate table...
Instead of modify the DDL operation to make the operation safe, we can simply disable it.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

This limitation is documented https://github.com/pingcap/docs-cn/pull/8557/
The user need to 'alter table nocache' first if they want to do those DDL operations.

### Release note

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by wjhuang2016 — COMMENTED** [review]
Are these DDL complete?

**Comment by tiancaiamao** [comment]
> Are these DDL complete?

Not really all DDL operations, but most of the cache table related that may affect the correctness are disabled

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
