### PR TITLE
parser: Support show index in tbl

### PR DESCRIPTION
**Pull request by shenli**
Fix: https://github.com/pingcap/tidb/issues/1849
@zimulala @coocood @tiancaiamao PTAL

### CODE REVIEW

**Comment by tiancaiamao** [comment]
https://dev.mysql.com/doc/refman/5.7/en/show-index.html

There is also a `INDEXES`  and `[WHERE expr]`, maybe we can fix them together?
if `[WHERE expr]` is non-trivial, `INDEXES` should be add...

**Comment by shenli** [comment]
I will fix it in the latter PR. "WHERE expr" need more test cases.

**Comment by hanfei1991** [comment]
LGTM

**Comment by coocood** [comment]
@shenli can we define `IndexOrKeys` as  `"INDEX" | "KEYS"`

**Comment by shenli** [comment]
@coocood PTAL

**Comment by coocood** [comment]
LGTM

**Pull request merged**
