### PR TITLE
docs/design: add proposal for window functions

### PR DESCRIPTION
**Pull request by lamxTyler**
### What problem does this PR solve? 

Add proposal for window functions.
### Check List 

Tests 

 - No code

Code changes

 - None

Side effects

 - None

Related changes

 - None

PTAL @zz-jason @winoros @lzmhhh123

### CODE REVIEW

**Comment by morgo** [comment]
Under "compatibility", should we maybe point out that Window Functions are a MySQL 8.0 feature (we only claim 5.7.  See https://github.com/pingcap/tidb/issues/7968 for 8.0).

**Comment by ngaut** [comment]
@morgo You are right.

**Comment by zz-jason** [comment]
@winoros @lzmhhh123 @XuHuaiyu PTAL

**Comment by lzmhhh123** [comment]
LGTM

**Pull request merged**
