### PR TITLE
resource_control: update static calibrate cpu params

### LINKED ISSUE #44012: static Calibrate cpu factor need to be multiplied by 1000
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Observing the code reveals

### 2. What did you expect to see? (Required)
cpu factor need to be multiplied by 1000

### 3. What did you see instead (Required)
cpu formula is ms, the previous calculation forgot to make cpu factor multiplied by 1000

### 4. What is your TiDB version? (Required)
7.1.0

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: close #44012

Problem Summary:

### What is changed and how it works?
- cpu formula is ms, the previous calculation forgot to multiply by 1000

### Check List

Tests 

- [x] Unit test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by HuSharp** [comment]
@nolouch @glorv @CabinfeverB PTAL, thx!

**Review by glorv — APPROVED** [review]

**Review by CabinfeverB — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
lgtm

**Pull request merged**
