### PR TITLE
config: Unify the style for storage quota config name

### PR DESCRIPTION
**Pull request by Yisaer**
### What problem does this PR solve?
Unify the style for storage quota config name to replace `temp` into `tmp`

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Release note 
None

### CODE REVIEW

**Comment by zz-jason** [comment]
@Yisaer do we need to cherry-pick this PR to release-4.0?

**Comment by Yisaer** [comment]
@zz-jason sure, I would also create a pr for documents.

**Pull request merged**
