### PR TITLE
planner/core: support partition pruning for partition expression floor(unix_timestamp())

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/16354

Problem Summary:

Support partition pruning for `floor(unix_timestamp()`

```
create table t (ts timestamp(3)) partition by range (floor(unix_timestamp(ts))) (
...)
```

### What is changed and how it works?

What's Changed:

Take function `floor(unix_timestamp())` as monotoneIncFuncs, special handle for this case.

How it Works:

If the partition function is monotoneous, i.e. 

> for all x > y => f(x) > f(y)

That partition function can be used by the partition pruning algorithm.

If we view `floor(unix_timestamp())` as a single function, it basicly conform to the definition.

> for all x > y => f(x) >= f(y)

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @imtbkcat

**Comment by jackysp** [comment]
PTAL @eurekaka @XuHuaiyu

**Comment by tiancaiamao** [comment]
PTAL @XuHuaiyu @lysu

**Pull request merged**
