### PR TITLE
store/tikv: sort keys in batch get (#25416)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25416 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25417
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25417:release-5.1-f7f1878f142e
```

---

Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?

Issue Number: close #https://github.com/pingcap/tidb/issues/25412
Problem Summary:

Batch-get assumes `batchKeys` is in order which is wrong.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

Make keys in order.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 
- No code

Side effects

### Release note 

- No release note.

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by lysu — APPROVED** [review]

**Comment by youjiali1995** [comment]
Some codes relies on the order of keys.

**Pull request closed without merging**
