### PR TITLE
ddl: using pingcap/log and unify the log format( #9659)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
cherry-pick #9659

### CODE REVIEW

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by bb7133** [comment]
Please fix the conflict

**Comment by bb7133** [comment]
LGTM

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Pull request merged**
