### PR TITLE
store/gcworker: fix test data race

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/27821

Problem Summary:

The `SetOracle` need to be called before other usages.

### What is changed and how it works?
What's Changed:
Add new function `CreateMockStoreWithOracle` to create testkit with optional `Oracle` instance so it can setup before bootstrapping.

### Check List 

Tests 

- [x] Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
Thanks for fixing this issue! LGTM.

**Comment by tisonkun** [comment]
Sorry I don't know who else to be requested review 😅

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
