### PR TITLE
executor: forbid stale read table with tiflash (#25561)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25561 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25571
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25571:release-5.1-5794e8ccd0ba
```

---

Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Problem Summary: Should ban tiflash stale read.

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

```
mysql root@localhost:(none)> create table test.table1 (id int primary key);
mysql root@localhost:(none)> ALTER TABLE test.table1 SET TIFLASH REPLICA 1
mysql root@localhost:(none)> SELECT * FROM information_schema.tiflash_replica // ensure tiflash replica is up
mysql root@localhost:(none)> explain analyze select * from test.table1 as of timestamp NOW();
(1105, 'staleness requests requires tikv backend')
mysql root@localhost:(none)> explain analyze select count(*) from test.table1 as of timestamp NOW();
(1105, 'staleness requests requires tikv backend')
```

### Release note 

- No release note

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by xhebox** [comment]
Depends on #25567

**Comment by nolouch** [comment]
PTAL @lzmhhh123 @Yisaer

**Review by lzmhhh123 — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
