### PR TITLE
cmd: add more explaintests for generated columns

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve? 
Add more explaintests for stored generated columns as indices/partition columns

### What is changed and how it works?
Added more explaintests

### Check List 

Tests 

 - Integration test

### CODE REVIEW

**Comment by bb7133** [comment]
PTAL @zz-jason @winkyao @tiancaiamao

**Comment by tiancaiamao** [comment]
LGTM

**Comment by tiancaiamao** [comment]
Please fix CI @bb7133

**Pull request merged**
