### PR TITLE
util/topsql: migrate test-infra to testify

### LINKED ISSUE #26428: migrate test-infra to testify for `util/topsql` pkg

### PR DESCRIPTION
**Pull request by yedamao**
### What problem does this PR solve?

Issue Number: close #26428 

### Release note 

```release-note
None.
```

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
Thanks for submitting this PR @yedamao ! Also I'd like to know whether or not we can run these tests in parallel.

**Comment by yedamao** [comment]
@tisonkun these tests depend some global variables in other pkg, we can not run these tests in parallel.

**Review by tisonkun — APPROVED** [review]
Thanks for your information @yedamao . LGTM.

I'd like to know which variables they depend on. May take a closer look to see if it is necessary. Global variable is general a bad idea.

**Comment by tisonkun** [comment]
/cc @xhebox @tiancaiamao @mmyj

PTAL

**Review by xhebox — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]
LGTM

**Pull request merged**
