### PR TITLE
ddl: fix canceling model.ActionRebaseAutoID and model.ActionShardRowID ddl jobs (#9226)

### PR DESCRIPTION
**Pull request by winkyao**
Cherry-pick from #9226

### CODE REVIEW

**Comment by jackysp** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by jackysp** [comment]
Please resolve the conflicts.

**Comment by zimulala** [comment]
@winkyao  Please fix Conflicting.

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by winkyao** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Pull request merged**
