### PR TITLE
br-stream: fix rewrite skip file end key

### PR DESCRIPTION
**Pull request by YuJuncen**
Signed-off-by: Yu Juncen <yujuncen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #???

Problem Summary:

There is a bug when we writing the end key of file: if the file key is encoded (log file), we would leave end key be empty. 

### What is changed and how it works?

Fixed it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Restore time cost reduced to 2mins (from 50mins).
image

```release-note
None
```

### CODE REVIEW

**Review by 3pointer — APPROVED** [review]
LGTM

**Review by kennytm — APPROVED** [review]

**Comment by YuJuncen** [comment]
(Well, before we merge master, it seems that both br-integration-test and mysql-test cannot be passed...)

**Comment by YuJuncen** [comment]
`Merging to branch br-stream is forbidden.`

🤔

**Comment by YuJuncen** [comment]
(Well, let me merge it manually...)

**Pull request merged**
