### PR TITLE
planner: fix err check

### PR DESCRIPTION
**Pull request by Tjianke**
### What problem does this PR solve?

Issue Number: #22979  

Problem Summary:

### What is changed and how it works?

What's Changed: 
- added basic err check
- some assert failed so I commented them with `// to fix:`. Needs further action, either ignore these error or fix tests.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Comment by pingyu** [comment]
LGTM

**Review by zz-jason — APPROVED** [review]
/LGTM

**Pull request merged**
