### PR TITLE
*: use release-2.1 parser

### PR DESCRIPTION
**Pull request by lysu**
fix wrong merge of https://github.com/pingcap/tidb/pull/9880 and use https://github.com/pingcap/parser/pull/257 's parser

This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/9886)

### CODE REVIEW

**Comment by lysu** [comment]
/run-all-tests tidb-private-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by lysu** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by lysu** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
