### PR TITLE
parser: disallow subquery without table alias (#19102)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19102 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/parser/issues/963

Parser PR: https://github.com/pingcap/parser/pull/968

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Add table alias validation in `preprocess.go`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects
N/A

### Release note 

- No release note

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
@tangenta please resolve conflicts.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by kennytm — COMMENTED** [review]
lgtm

**Review by zz-jason — APPROVED** [review]
LGTM

**Pull request merged**
