### PR TITLE
build, test: Reconstruct tidb-server to support fuzz

### PR DESCRIPTION
**Pull request by oraluben**
### What problem does this PR solve?

dvyukov/go-fuzz is a tool that can test go code by coverage-guided fuzzing.
It requires the go program to be tested to be run in a separate go module, which cannot be module `main`.
To archive that, we make function `main` in `tidb-server/main.go` public,
but I'm not sure if that's the best option.

I would like to know if this (kind of) PR has chance to be merged,
and do you think there's better way to do it? (some other thoughts below)
I also worry about potential incompatibility.

Please advise.

### What is changed and how it works?

What's Changed:
How it Works:

Rename module `main` in `tidb-server/` and make function `main` in `tidb-server/main.go` public.

#### Other proposals
something looks like this:
image
The `Main` function in `internal/server.go` will be only accessible within this repo.
See https://github.com/oraluben/tidb/compare/f9d4af027...8a989ab3c for an example.

### Related changes

I updated some (maybe not all) of the affected build scripts.

### CODE REVIEW

**Comment by zyguan** [comment]
@zhouqiang-cl Is there anything (related to CI/CD) we need to take into account when introducing these changes?

**Comment by zhouqiang-cl** [comment]
> @zhouqiang-cl Is there anything (related to CI/CD) we need to take into account when introducing these changes?

Maybe run fuzzing daily?

**Comment by zyguan** [comment]
> > @zhouqiang-cl Is there anything (related to CI/CD) we need to take into account when introducing these changes?
> 
> Maybe run fuzzing daily?

That's better. I actually wonder if it would break our CI/CD.

**Comment by zhouqiang-cl** [comment]
> > > @zhouqiang-cl Is there anything (related to CI/CD) we need to take into account when introducing these changes?
> > 
> > 
> > Maybe run fuzzing daily?
> 
> That's better. I actually wonder if it would break our CI/CD.

I think not, seems it will not break the original build process

**Pull request closed without merging**
