### PR TITLE
parser: refactor parser first step

### LINKED ISSUE #4538: “process” is not allowed being as column name
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
`create table a (process double);`

2. What did you expect to see?
```
mysql> create table a (process double);
Query OK, 0 rows affected (0.05 sec)

mysql> desc a;
+---------+--------+------+-----+---------+-------+
| Field   | Type   | Null | Key | Default | Extra |
+---------+--------+------+-----+---------+-------+
| process | double | YES  |     | NULL    |       |
+---------+--------+------+-----+---------+-------+
1 row in set (0.00 sec)
```

3. What did you see instead?
```
MySQL [renee]> create table a (process double);
ERROR 1105 (HY000): line 0 column 23 near " double)" (total length 31)
MySQL [renee]> create table a (processa double);
Query OK, 0 rows affected (0.16 sec)
```

4. What version of TiDB are you using (`tidb-server -V`)?
Release Version: 0.8.0
Git Commit Hash: f4799b54328212bf725875fe580dc523484b1402
Git Commit Branch: pre-ga
UTC Build Time:  2017-09-13 10:34:15

### PR DESCRIPTION
**Pull request by coocood**
This is the first step to refactor parser. it solve several problems.

1. function name can be general identifier, we don't need to define a keyword for a builtin function.

2. write test to make sure keyword is consistent with lexer token. this fixes #4538.

3. Removed ReservedKeyword, solve the identifier in scanner.

4. Simplified precedence definition.

### CODE REVIEW

**Comment by coocood** [comment]
@tiancaiamao @winkyao @XuHuaiyu PTAL

**Comment by ngaut** [comment]
Well done.

**Comment by shenli** [comment]
Is there an issue or trello card to trace the whole refactor work?

**Comment by coocood** [comment]
@shenli 
Here is the issue, I should mention it in PR description
https://github.com/pingcap/tidb/issues/4525

**Comment by tiancaiamao** [comment]
This PR changes a lot of code, but I think it's ok as long as the tests works.
Well done! @coocood

**Comment by coocood** [comment]
@tiancaiamao 
There are about 200 lines are caused by go fmt, only about 500 added lines need to review.

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
