### PR TITLE
executor: optimize unit test by unset some serial test suites

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Optimize executor unit tests by change 2 `SerialSuite` to `Suite`

### What is changed and how it works?
change test suite `testRecoverTable` and `testShowStatsSuite` from `SerialSuites` to `Suite` so thay can run parallel with other test suites, thus we can run unit test must quicker.

Before change:
```
$ go test -v -vet=off -p 20 -timeout 7m -race github.com/pingcap/tidb/executor
ok  	github.com/pingcap/tidb/executor	90.628s
```

After change:
```
$ go test -v -vet=off -p 20 -timeout 7m -race github.com/pingcap/tidb/executor
ok  	github.com/pingcap/tidb/executor	75.868s
```

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

Side effects

Related changes

Release note

### CODE REVIEW

**Comment by glorv** [comment]
@zimulala [the latest unit test build](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/21826/pipeline) was failed by ddl test `testDBSuite4.TestAddIndex4` which is a known issue has not resolved yet. So shall we try merge again?

**Comment by zimulala** [comment]
@glorv We can rerun this test.

**Pull request merged**
