### PR TITLE
ddl: remove the unstable check

### PR DESCRIPTION
**Pull request by zimulala**
The `testCreateIndex` will use the system schema version to check the job's `SchemaVersion`. After finishing the normal index(idx_normal) there are still two cancelled jobs in the `DDLJobList`. And They can update the system schema version. So when `testCreateIndex` checks the job's `SchemaVersion`, the system schema may be updated by other canceled jobs. 
The `TestCleanJobs` will be removed after we initially support the parallel DDL. So now I remove the unstable check to fix it.

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @coocood

**Comment by zimulala** [comment]
PTAL @winkyao @XuHuaiyu

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by winkyao** [comment]
build failed. @zimulala

**Comment by zimulala** [comment]
PTAL @winkyao

**Pull request merged**
