### PR TITLE
*: support 'show master status'

### PR DESCRIPTION
**Pull request by tiancaiamao**
Different from MySQL, this command in TiDB just shows the TSO

Fix https://github.com/pingcap/tidb/issues/6695

```
mysql> show master status;
+-------------+--------------------+--------------+------------------+-------------------+
| File        | Position           | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+-------------+--------------------+--------------+------------------+-------------------+
| tidb-binlog | 400668057259474944 |              |                  |                   |
+-------------+--------------------+--------------+------------------+-------------------+
1 row in set (0.00 sec)
```

@shenli

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by holys** [comment]
LGTM

**Comment by shenli** [comment]
@tiancaiamao Please cherry-pick this to the release-2.0 .

**Pull request merged**
