### PR TITLE
session: improve collation_server handling

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Problem Summary:

This revisits https://github.com/pingcap/tidb/pull/23932 with a simpler fix, which I noticed while performing some other refactoring.

The original problem is that when setting the `character_set_server`, the `collation_server` is also set; which leads to the collation no longer being set because it is already set.

Because `collation_server` also sets the `character_set_server`, this PR takes the approach of removing the code that sets `character_set_server`. Both variables will be set with `collation_server`.

### What is changed and how it works?

What's Changed:

Small code improvement, function neutral.

### Related changes

- Original PR https://github.com/pingcap/tidb/pull/23932

### Check List 

Tests 

- Unit test (covered by existing tests)

Side effects

- None

### Release note 

- No release note

### CODE REVIEW

**Review by xiongjiwei — APPROVED** [review]
lgtm

**Review by wjhuang2016 — COMMENTED** [review]
After we remove the code that sets character_set_server, if glocal character_set_server is set, session character_set_server will not take effect.

**Pull request merged**
