### PR TITLE
br/pkg/lightning: migrate test-infra to testify

### LINKED ISSUE #28239: migrate test-infra to testify for `br/pkg/lightning/metric`

### LINKED ISSUE #28242: migrate test-infra to testify for `br/pkg/lightning/tikv`

### LINKED ISSUE #28243: migrate test-infra to testify for `br/pkg/lightning/verification`

### LINKED ISSUE #28244: migrate test-infra to testify for `br/pkg/lightning/worker`

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

### What problem does this PR solve?

Issue Number: close #28239, close #28243, close #28242, close #28244

### Release note

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
@tangenta PTAL

**Review by xiongjiwei — APPROVED** [review]

**Pull request merged**
