### PR TITLE
executor: fix confusing statement label (#6419)

### PR DESCRIPTION
**Pull request by jackysp**
Cherry pick https://github.com/pingcap/tidb/pull/6419 to release 2.0

### CODE REVIEW

**Comment by jackysp** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@jackysp Please add the original PR link here.

**Comment by jackysp** [comment]
PTAL @shenli

**Pull request merged**
