### PR TITLE
store/tikv: share type OneByOneSuite for tests related to tikv

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: AndreMouche

### What problem does this PR solve?
This PR removes duplicated `OneByOneSuite` in tikv, and shares type OneByOneSuite for those tests related to tikv.

Part of https://github.com/pingcap/tidb/issues/22513

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by youjiali1995 — APPROVED** [review]

**Comment by AndreMouche** [comment]
run-e2e-test

**Pull request merged**
