### PR TITLE
br/pkg/task: migrate test-infra to testify

### LINKED ISSUE #28181: migrate test-infra to testify for `br/pkg/task`

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #28181.

Signed-off-by: tison <wander4096@gmail.com>

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Comment by tisonkun** [comment]
ping @3pointer @kennytm

**Review by disksing — APPROVED** [review]

**Pull request merged**
