### PR TITLE
domain: refactor plan replayer implemention

### PR DESCRIPTION
**Pull request by Yisaer**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/38779

Problem Summary:

### What is changed and how it works?

 refactor plan replayer implemention in order to make `sctx` independent with each compoment and make `DumpPlanReplayerInfo` can be visited by `domain` package

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
/hold

@Yisaer Please fix linter

```
domain/domain.go:1535:67: empty-lines: extra empty line at the end of a block (all_revive)

```

**Pull request merged**
