### PR TITLE
store/tikv:move LockExpire error from tikv package to tidb since it i…

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: AndreMouche

### What problem does this PR solve?
This PR moves LockExpire error from tikv package to tidb since it is only used by TiDB ddl package
Part of https://github.com/pingcap/tidb/issues/22513

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by youjiali1995 — APPROVED** [review]
LGTM. BTW it's not only used by the DDL package.

**Pull request merged**
