### PR TITLE
executor: reject setting read ts to a future time (#25732)

### LINKED ISSUE #25680: Don't allow reading a snapshot with the timestamp greater than the current max timestamp
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

TiDB can read data with a user-defined timestamp(using `tidb_snapshot` or stale-read) which may be greater than the current max timestamp in PD. It can update the max_ts in TiKV and the async-commit transaction may commit data with the version which is greater than the next timestamp in PD, so the following transactions can't read it which means the transaction isolation is broken.

### 2. What did you expect to see? (Required)

TiDB doesn't allow setting snapshot with the version which is greater than the current max version.

### 3. What did you see instead (Required)
```
mysql root@127.0.0.1:test> set @@tidb_snapshot = '2022-06-24 16:59:02';
Query OK, 0 rows affected
Time: 0.022s
```

### 4. What is your TiDB version? (Required)

v5.0.0-v5.0.2

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25732 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25763
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25763:release-5.1-92ddceb6a4ab
```

---

### What problem does this PR solve?

Issue Number: close #25680

### What is changed and how it works?

This PR checks the read ts in two cases:

* Set by `tidb_snapshot` system variable
* Stale read

It first checks with latest local timestamp (with low cost). If the check fails, it gets a timestamp from PD to do a double check.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
- Breaking backward compatibility

### Release note 

- Do not allow setting read timestamp to a future time.

### CODE REVIEW

**Comment by sticnarf** [comment]
PTAL @nolouch @Yisaer

**Review by nolouch — APPROVED** [review]
lgtm

**Review by nolouch — APPROVED** [review]

**Review by youjiali1995 — APPROVED** [review]

**Comment by nolouch** [comment]
PTAl @Yisaer

**Review by Yisaer — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
