### PR TITLE
planner/memo: migrate test-infra to testify

### LINKED ISSUE #26860: migrate test-infra to testify for `planner/memo`
You may try to analyze first and spawn more subtasks on demand (no strict) instead of one big PR handle the whole package which is hard to review.

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

### What problem does this PR solve?

Issue Number: close #26860

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
/cc @xhebox @mmyj 

Please take a look. Almost trivial changes, do worry about the size :P

**Comment by mmyj** [comment]
`planner/memo/group_test.go` need to be formatted.

**Review by mmyj — APPROVED** [review]
lgtm, btw the `planner/memo/group_test.go` need to be formatted.

**Comment by tisonkun** [comment]
> lgtm, btw the `planner/memo/group_test.go` need to be formatted.

fixed.

**Comment by tisonkun** [comment]
/cc @xiongjiwei 

🙈

**Comment by tisonkun** [comment]
/cc @disksing 

Please take a look. Thanks!

**Review by disksing — APPROVED** [review]

**Pull request merged**
