### PR TITLE
stats: refine row count estimation

### PR DESCRIPTION
**Pull request by lamxTyler**
## What have you changed? (mandatory)

This PR fixes two problems:

- When using the greedy algorithm to calculate selectivity,  we prefer the index stats or pk stats. However,  if the index or pk stats cannot cover any conditions, they should be skipped, if not, we may quit the calculation early although we may be able to use other column stats to estimate.

- When estimating the row count for the pseudo primary key, if the range point is special kind of value like `MaxValue`, we should also specially handle it.

## What are the type of the changes (mandatory)?

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested (mandatory)?

explain test

PTAL @coocood @winoros @zz-jason @fipped

### CODE REVIEW

**Comment by shenli** [comment]
Will this improve the performance of sysbench?

**Comment by lamxTyler** [comment]
@shenli  I think no, because the query of sysbench is quite simple.

**Comment by shenli** [comment]
LGTM

**Pull request merged**
