### PR TITLE
server: Combined fix for authentication issues (#29738)

### LINKED ISSUE #29725: tidb returns 'Unknown auth plugin' when some old clients to connect
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a tidb cluster
2. use mysql 5.1 client to connect the tidb
3. the client Connect success to v5.2.2, but can't connect to v5.3.0

related  #27855 #27931

### 2. What did you expect to see? (Required)

```sql
╭─tidb@localhost ~/tiup-cluster-config
╰─$ mysql --version                                                                                                                                                                    1 ↵
mysql  Ver 14.14 Distrib 5.1.73, for pc-linux-gnu (i686) using readline 5.1
╭─tidb@localhost ~/tiup-cluster-config
╰─$ mysql -u root -h 172.16.4.131 -P 4100
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 7
Server version: 5.7.25-TiDB-v5.2.2 TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible

Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```
### 3. What did you see instead (Required)
```sql
╭─tidb@localhost ~/pingcap/tidb ‹master*›
╰─$ mysql --version                                                                                                                                                                    1 ↵
mysql  Ver 14.14 Distrib 5.1.73, for pc-linux-gnu (i686) using readline 5.1
╭─tidb@localhost ~/pingcap/tidb ‹master*›
╰─$ mysql -u root -h 172.16.4.131 -P 4100
ERROR 1105 (HY000): Unknown auth plugin
```
### 4. What is your TiDB version? (Required)
release-5.3(bdc9987370d6d393cb8)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #29738 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/30233
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/30233:release-5.3-6756bd2ea824
```

---

### What problem does this PR solve?

Issue Number:

- close #29725

Problem Summary:

Combined fix for multiple authentication issues

Contains fixes from:

- #29732

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

```release-note
- Compatibility with MySQL 5.1 clients has been improved
```

### CODE REVIEW

**Comment by dveeden** [comment]
From https://github.com/dveeden/tidb_client_test:

```
TiDB Client Test
Connected to:
	Release Version: v5.3.0-3-g6a0263a39
	Edition: Community
	Git Commit Hash: 6a0263a39545da3944627c747bfcada74d3324e7
	Git Branch: release-5.3-6756bd2ea824
	UTC Build Time: 2021-11-29 14:53:26
	GoVersion: go1.16.8
	Race Enabled: false
	TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
	Check Table Before Drop: false
Clients:
	/home/dvaneeden/opt/mysql/5.1.73/bin/mysql
	/home/dvaneeden/opt/mysql/5.7.31/bin/mysql
	/home/dvaneeden/opt/mysql/5.7.36/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.22/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.25/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.26/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.27/bin/mysql
-----------------------------------------------
Testing with mysql_native_password as default authentication plugin
Testing /home/dvaneeden/opt/mysql/5.1.73/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/5.7.31/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/5.7.36/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.22/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.25/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.26/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.27/bin/mysql: success=8, failures=0
Testing with caching_sha2_password as default authentication plugin
Testing /home/dvaneeden/opt/mysql/5.1.73/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/5.7.31/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/5.7.36/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.22/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.25/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.26/bin/mysql: success=8, failures=0
Testing /home/dvaneeden/opt/mysql/8.0.27/bin/mysql: success=8, failures=0
```

**Comment by dveeden** [comment]
https://github.com/pingcap/tidb/pull/30047 should probably be merged first

**Review by dveeden — APPROVED** [review]

**Comment by guo-shaoge** [comment]
Looks like #30450 already fixed.

**Pull request closed without merging**
