### PR TITLE
expression: Fix errors for JSON functions | tidb-test=pr/2339

### LINKED ISSUE #53799: Incomplete and incorrect errors for arguments of JSON functions
## Bug Report

Some JSON functions have errors where:
- The error text differs from MySQL
- The error has an incorrect number of arguments for the message
- The error has an error code that differs from MySQL

### 1. Minimal reproduce step (Required)

```
SELECT JSON_CONTAINS(123, '');
SELECT JSON_CONTAINS('{}', 123);
SELECT JSON_OVERLAPS(123, '');
SELECT JSON_OVERLAPS('{}', 123);
SELECT 'abc' MEMBER OF(123);
```

### 2. What did you expect to see? (Required)

With MySQL 8.4.0

```
mysql> SELECT JSON_CONTAINS(123, '');
ERROR 3146 (22032): Invalid data type for JSON data in argument 1 to function json_contains; a JSON string or JSON type is required.
mysql> SELECT JSON_CONTAINS('{}', 123);
ERROR 3146 (22032): Invalid data type for JSON data in argument 2 to function json_contains; a JSON string or JSON type is required.
mysql> SELECT JSON_OVERLAPS(123, '');
ERROR 3146 (22032): Invalid data type for JSON data in argument 1 to function json_overlaps; a JSON string or JSON type is required.
mysql> SELECT JSON_OVERLAPS('{}', 123);
ERROR 3146 (22032): Invalid data type for JSON data in argument 2 to function json_overlaps; a JSON string or JSON type is required.
mysql> SELECT 'abc' MEMBER OF(123);
ERROR 3146 (22032): Invalid data type for JSON data in argument 2 to function member of; a JSON string or JSON type is required.
```

### 3. What did you see instead (Required)

```
mysql> SELECT JSON_CONTAINS(123, '');
ERROR 3069 (22032): Invalid JSON data provided to function %!s(int=1): json_contains
mysql> SELECT JSON_CONTAINS('{}', 123);
ERROR 3069 (22032): Invalid JSON data provided to function %!s(int=2): json_contains
mysql> SELECT JSON_OVERLAPS(123, '');
ERROR 3069 (22032): Invalid JSON data provided to function %!s(int=1): json_overlaps
mysql> SELECT JSON_OVERLAPS('{}', 123);
ERROR 3069 (22032): Invalid JSON data provided to function %!s(int=2): json_overlaps
mysql> SELECT 'abc' MEMBER OF(123);
ERROR 3069 (22032): Invalid JSON data provided to function %!s(int=2): member of
```

### 4. What is your TiDB version? (Required)

```
Release Version: v8.1.0
Edition: Community
Git Commit Hash: 945d07c5d5c7a1ae212f6013adfb187f2de24b23
Git Branch: HEAD
UTC Build Time: 2024-05-21 03:51:57
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #53799 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
The errors for incorrect arguments to various JSON functions have been corrected.
```

### CODE REVIEW

**Comment by dveeden** [comment]
With this PR:

```
mysql> SELECT JSON_CONTAINS(123, '');
ERROR 3146 (22032): Invalid data type for JSON data in argument 1 to function json_contains; a JSON string or JSON type is required.
mysql> SELECT JSON_CONTAINS('{}', 123);
ERROR 3146 (22032): Invalid data type for JSON data in argument 2 to function json_contains; a JSON string or JSON type is required.
mysql> SELECT JSON_OVERLAPS(123, '');
ERROR 3146 (22032): Invalid data type for JSON data in argument 1 to function json_overlaps; a JSON string or JSON type is required.
mysql> SELECT JSON_OVERLAPS('{}', 123);
ERROR 3146 (22032): Invalid data type for JSON data in argument 2 to function json_overlaps; a JSON string or JSON type is required.
mysql> SELECT 'abc' MEMBER OF(123);
ERROR 3146 (22032): Invalid data type for JSON data in argument 2 to function member of; a JSON string or JSON type is required.
mysql> SELECT TIDB_VERSION()\G
*************************** 1. row ***************************
TIDB_VERSION(): Release Version: v8.2.0-alpha-300-gcba4a6d779
Edition: Community
Git Commit Hash: cba4a6d779223b6f155b2c465a5853f9d8061261
Git Branch: json_arg_err
UTC Build Time: 2024-06-04 09:29:04
GoVersion: go1.22.3
Race Enabled: false
Check Table Before Drop: false
Store: unistore
1 row in set (0.00 sec)
```

**Review by windtalker — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
