### PR TITLE
update vendor to build on ARM64 (#10805)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
cherry-pick #10805

### CODE REVIEW

**Comment by crazycs520** [comment]
@zhouqiang-cl  PTAL

**Comment by jackysp** [comment]
Plz wait for the plugin build fix.

**Comment by lysu** [comment]
CI need merge https://github.com/pingcap/tidb/pull/11157 first

**Comment by crazycs520** [comment]
@lysu @jackysp PTAL

**Pull request merged**
