### PR TITLE
ddl: fix admin check table error after rename index with scalar function 

### LINKED ISSUE #56045: panic when admin check table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
set global tidb_enable_global_index=1;
create table t ( col_1 json ,col_2 tinyint  unsigned not null default 57 , key idx_1 ( col_2 ,(cast(col_1 as CHAR(64) array)) ) ,unique key idx_2 ( (cast(col_1 as CHAR(64) array)) ) global ,primary key  ( col_2 )  /*T![clustered_index] clustered */ ) charset utf8 collate utf8_general_ci partition by hash ( col_2 ) partitions 5;

alter table t rename index idx_1 to idx_1_1;

admin check table t;
```

### 2. What did you expect to see? (Required)
No panic
### 3. What did you see instead (Required)
``` SQL

mysql> admin check table t;
ERROR 1105 (HY000): runtime error: index out of range [1] with length 1
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #56045

Problem Summary:

### What changed and how does it work?

`renameIndexes` didn't rename generated columns previously, causing error during `buildPhysicalIndexLookUpReader`.

To make the newly added test works, we don't clear `idxPart.Expr` (which is shallow copied from `stmt`) in `BuildHiddenColumnInfo`. Since this stmt will be used twice.

https://github.com/pingcap/tidb/blob/027f01b7ef88e41fd982996b675ba1cad94f715b/pkg/ddl/schematracker/checker.go#L225-L235

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
> To make the newly added test works, we don't clear idxPart.Expr (which is shallow copied from stmt) in BuildHiddenColumnInfo. Since this stmt will be used twice.

I think it's not worthy to change the code logic. You can call Checker.Disable / Enable for this test. There are other places that the original statement is changed inside DDL so we need to disable checker. And please write a unit test in pkg/ddl/schematracker to make sure the skipped SQL can be executed and SHOW CREATE TABLE is correct. You can refer to TestBitDefaultValues and checkShowCreateTable

**Review by wjhuang2016 — APPROVED** [review]

**Comment by joechenrh** [comment]
> I think it's not worthy to change the code logic. You can call Checker.Disable / Enable for this test. There are other places that the original statement is changed inside DDL so we need to disable checker. And please write a unit test in pkg/ddl/schematracker to make sure the skipped SQL can be executed and SHOW CREATE TABLE is correct. You can refer to TestBitDefaultValues and checkShowCreateTable

May it's not necessary to write test in pkg/ddl/schematracker. Because `rename index` can be executed without error, and `SHOW CREATE TABLE` will also return correct info. The error is raised from `admin check table`.

**Comment by lance6716** [comment]
Anyway, skipped DDL of checker should have a place to test. Otherwise we won't make sure it will always be correct in future

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
