### PR TITLE
expression: fix elt with gbk charset

### LINKED ISSUE #31331: builtin func `elt` result is not same when return binary
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```mysql
create table t (a enum('a一','b二','c三','d四') default 'c三', b binary(10)) charset=gbk;
insert into t values (1, 0x1234);
select elt(1, a, b) from t;
select elt(1, a, a) from t;
select elt(1, a, 0x12) from t;
```

### 2. What did you expect to see? (Required)
```
mysql> select elt(1, a, b) from t;
+----------------------------+
| elt(1, a, b)               |
+----------------------------+
| 0x61D2BB                   |
+----------------------------+
1 row in set (0.00 sec)

mysql> select elt(1, a, a) from t;
+--------------+
| elt(1, a, a) |
+--------------+
| a一          |
+--------------+
1 row in set (0.00 sec)

mysql> select elt(1, a, 0x12) from t;
+-----------------+
| elt(1, a, 0x12) |
+-----------------+
| a一             |
+-----------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> select elt(1, a, b) from t;
+----------------------------+
| elt(1, a, b)               |
+----------------------------+
| 0x61E4B880                 |
+----------------------------+
1 row in set (0.01 sec)

mysql> select elt(1, a, a) from t;
+--------------+
| elt(1, a, a) |
+--------------+
| a一          |
+--------------+
1 row in set (0.01 sec)

mysql> select elt(1, a, 0x12) from t;
+----------------------------------+
| elt(1, a, 0x12)                  |
+----------------------------------+
| 0x61E4B880                       |
+----------------------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
```mysql
mysql> select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                  |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.5.0-alpha
Edition: Community
Git Commit Hash: 974b5784adbbd47d14659916d47dd986effa7b4e
Git Branch: release-5.4
UTC Build Time: 2022-01-05 06:41:46
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #31331

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix elt with gbk charset
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @tangenta @xiongjiwei 
PTAL

**Review by xiongjiwei — APPROVED** [review]

**Comment by Defined2014** [comment]
/needs-cherry-pick-5.4

**Review by zimulala — APPROVED** [review]
LGTM

**Pull request merged**
