### PR TITLE
*: added_goword_for_spelling_checking

### PR DESCRIPTION
**Pull request by zhexuany**
This commit has to fail. Since we bring a breaking change `goword`, there are a lot of comment styele mistake. 

This fixes https://github.com/pingcap/tidb/issues/3111

### CODE REVIEW

**Comment by ngaut** [comment]
Good job!

**Comment by shenli** [comment]
@zhexuany Great!
I think it is better to introduce goword but do not put it into check task. So we could merge this PR without breaking CI. Then we will use `make goword` to find the typos and fix them. After all things are fixed we will move gowork checking into check task.
What do you think about this?

**Comment by iamzhout** [comment]
agree with @shenli , going forward step by step instead of breaking current build makes more sense, or submit a big PR with all typos being fixed simultaneously will be also a good idea.

**Comment by zhexuany** [comment]
@shenli Yes, That is what I am thinking. But we need make a protocol which will correct old code base and also prevent future committed code having the same problem.

**Comment by zhexuany** [comment]
@shenli PTAL. 
Also, please inform team members, do run `make goword` before commit any changes.

**Comment by ngaut** [comment]
LGTM. Bye the way, After the PR, Could you send another big PR to prevent future spelling issues?

**Comment by zhexuany** [comment]
@ngaut I am working on pre-commit, https://github.com/pingcap/tidb/pull/3112/files#diff-f59e272145d77c010aad8a8802af0c56R13. I will add `goword` check in pre-commit.

**Comment by ngaut** [comment]
Cool

**Comment by coocood** [comment]
LGTM

**Pull request merged**
