### PR TITLE
region_cache: filter peers on tombstone or dropped stores (#24726)

### PR DESCRIPTION
**Pull request by youjiali1995**
### What problem does this PR solve?
Problem Summary:
Backport some bug fixes.

### What is changed and how it works?

What's Changed:
Cherry-pick https://github.com/pingcap/tidb/pull/23695 and #24726.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- Fix the issue that sometimes fails to send requests if there are tombstone stores.

### CODE REVIEW

**Review by longfangsong — APPROVED** [review]

**Comment by JmPotato** [comment]
@youjiali1995 Any updates? Should we continue merging this PR into `release-4.0`?

**Comment by youjiali1995** [comment]
@JmPotato I have registered it in the v4.0.15 bug triage list. Waiting for triage.

**Review by sticnarf — APPROVED** [review]

**Pull request merged**
