### PR TITLE
coprocessor: skip empty tidb nodes

### LINKED ISSUE #36546: Cluster in-mem table query is slow when there are empty tidb nodes in etcd
## Background

We found that the query latency of Slow Query and SQL Statements in TiDB Dashboard was high in a cloud cluster, and the reason is that TiDB nodes with empty IP addresses often appear in etcd. So queries to `INFORMATION_SCHEMA.CLUSTER_SLOW_QUERY` will get stuck on coprocessor requests until they time out.

Empty TiDB nodes are created by BR.

## Solution

We first need to solve the problem of BR generating empty nodes, which is already in progress. But the robustness of TiDB itself also needs to be improved. Instead of waiting for a timeout, we should choose to skip or report an error immediately when encountering an empty node.

### PR DESCRIPTION
**Pull request by mornyx**
Issue Number: close #36546

### What is changed and how it works?

As described in #36546, we should avoid trying to send coprocessor requests to apparently illegal TiDB addresses. In this PR, our solution is: When building cop tasks, check the node address to decide whether to skip it directly.

### Release note

```release-note
None
```

Signed-off-by: mornyx <mornyx.z@gmail.com>

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Comment by zhongzc** [comment]
Can we ignore tidb info with empty IP returned by etcd?

https://github.com/pingcap/tidb/blob/965454fd16f1ce88f29948edea14aa33dce9363b/domain/infosync/info.go#L552-L563

**Comment by xhebox** [comment]
> Can we ignore tidb info with empty IP returned by etcd?
> 
> https://github.com/pingcap/tidb/blob/965454fd16f1ce88f29948edea14aa33dce9363b/domain/infosync/info.go#L552-L563

I think we can, but I am not sure if we should.

**Comment by mornyx** [comment]
> Can we ignore tidb info with empty IP returned by etcd?
> 
> https://github.com/pingcap/tidb/blob/965454fd16f1ce88f29948edea14aa33dce9363b/domain/infosync/info.go#L552-L563

I can't guarantee whether other code has special dependencies on nodes, even BR nodes. So I just skipped where the problem occurred and didn't modify the entire data source..

**Review by crazycs520 — APPROVED** [review]

**Comment by mornyx** [comment]
This PR avoids sending copr requests to TiDB nodes with empty IP addresses. Unfortunately, many tests depend on this behavior. When we create a mock store and use it to bootstrap a mock session, all tests will depend on this fact: there is only one node in the entire mocked cluster with an empty IP address and it can handle copr requests normally.

So the optimization of this PR is not easy to achieve, since issue https://github.com/pingcap/tidb/issues/36546 has been resolved by pr https://github.com/pingcap/tidb/pull/36558, I will close this PR.

**Pull request closed without merging**
