### PR TITLE
http: fix scatter table

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve? 
Currently, the scatter table API cannot work well because the key in the HTTP request for the scatter table is not escaped. This PR is also related to pingcap/pd#1642.

### What is changed and how it works?
This PR fixes it by escaping the key.

### Check List 

Tests 

 - Manual test (by using an existed cluster to verify it)

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

**Comment by jackysp** [comment]
Could we use pd client api?

**Comment by rleungx** [comment]
@jackysp For now, we only support it by using HTTP API. But the answer may be yes later.

**Comment by XuHuaiyu** [comment]
Should we cherry-pick this commit to release-2.1 and release-3.0?

**Comment by rleungx** [comment]
@XuHuaiyu Yes, we should.

**Comment by jackysp** [comment]
TiDB only needs one approval to merge to master, please don't approve it too early. @nolouch

**Pull request merged**
