### PR TITLE
session: test that temporary tables will also be retried

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

Close https://github.com/pingcap/tidb/issues/24560

Problem Summary:
Even if data of global temporary tables are only visible to the current transaction, DML on it needs to be retried because DML on normal tables may rely on the data of global temporary tables. 

E.g.
```sql
INSERT INTO normal_table SELECT * FROM temp_table;
UPDATE normal_table, temp_table SET normal_table.b=temp_table.b WHERE normal_table.a=temp_table.a;
```

### What is changed and how it works?

What's Changed: Add some test cases.

### Related changes

- N/A

### Check List 

Tests 

- Unit test

Side effects

- N/A

### Release note 

- No release notes.

### CODE REVIEW

**Comment by lysu** [comment]
it seems the race is caused by 

https://github.com/pingcap/tidb/blob/b1d134d7d9264a72df902087866b6de23d4efb93/session/session.go#L530-L550


the code snippet breaks the agreement that "memdb stage must be empty after stepped into txn commit phase"

> so commit's `reset()` method will try to rollback and change those stage buffer during async cleanup.

it's better let those filter logic be executed as a virtual stmt and do a StmtCommit,  maybe can change it to

```
	// Filter out the temporary table key-values.
	if tables := s.GetSessionVars().TxnCtx.GlobalTemporaryTables; tables != nil {
		if err := func() error {
			memBuffer := s.txn.GetMemBuffer()
			defer func() {
				s.txn.cleanup() // reset and new a empty stage buffer
			}()
			for tid := range tables {
				seekKey := tablecodec.EncodeTablePrefix(tid)
				endKey := tablecodec.EncodeTablePrefix(tid + 1)
				iter, err := memBuffer.Iter(seekKey, endKey)
				if err != nil {
					return err
				}
				for iter.Valid() && iter.Key().HasPrefix(seekKey) {
					if err = memBuffer.Delete(iter.Key()); err != nil {
						return errors.Trace(err)
					}
					s.txn.UpdateEntriesCountAndSize()
					if err = iter.Next(); err != nil {
						return errors.Trace(err)
					}
				}
			}
			s.txn.flushStmtBuf() // flush to root membuffer
			return nil
		}(); err != nil {
			return err
		}
	}
```

@cfzjywxk

**Comment by tiancaiamao** [comment]
> memdb stage must be empty

Do you mean that the Delete operation make the stage dirty? @lysu

**Comment by lysu** [comment]
> > memdb stage must be empty
> 
> Do you mean that the Delete operation make the stage dirty? @lysu

yes~, those delete will make latest stage buffer dirty, so reset will try to rollback dirty buffer and  cleanup will try to read dirty buffer at the same time, it's better make those delete op affact on root buffer before commit

**Pull request merged**
