### PR TITLE
expression: push builtin function FLOOR down to TiKV

### PR DESCRIPTION
**Pull request by zz-jason**
Thank you for working on TiDB! Please read TiDB's [CONTRIBUTING](https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md) document **BEFORE** filing this PR.

## What have you changed? (mandatory)

Push builtin function `FLOOR` down to TiKV, before this PR, we have to pull all the records to TiDB and calculate the filter result:
```sql
TiDB(localhost:4000) > desc select * from t where floor(a) > 10;
+---------------+-------------+---------------+------+----------------------------------------------+----------+
| id            | parents     | children      | task | operator info                                | count    |
+---------------+-------------+---------------+------+----------------------------------------------+----------+
| TableScan_6   |             |               | cop  | table:t, range:[-inf,+inf], keep order:false | 10000.00 |
| TableReader_7 | Selection_5 |               | root | data:TableScan_6                             | 10000.00 |
| Selection_5   |             | TableReader_7 | root | gt(floor(test.t.a), 10)                      | 8000.00  |
+---------------+-------------+---------------+------+----------------------------------------------+----------+
3 rows in set (0.00 sec)
```

After this PR, we can calculate the filter result in to multi TiKV servers in parallel: 
```sql
TiDB(localhost:4000) > desc select * from t where floor(a) > 10;
+---------------+-------------+-------------+------+----------------------------------------------+----------+
| id            | parents     | children    | task | operator info                                | count    |
+---------------+-------------+-------------+------+----------------------------------------------+----------+
| TableScan_5   | Selection_6 |             | cop  | table:t, range:[-inf,+inf], keep order:false | 10000.00 |
| Selection_6   |             | TableScan_5 | cop  | gt(floor(test.t.a), 10)                      | 8000.00  |
| TableReader_7 |             |             | root | data:Selection_6                             | 8000.00  |
+---------------+-------------+-------------+------+----------------------------------------------+----------+
3 rows in set (0.00 sec)
```

## What are the type of the changes (mandatory)?

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested (mandatory)?

- unit test

## Does this PR affect documentation (docs/docs-cn) update? (optional)

No.

## Add a few positive/negative examples (optional)

### CODE REVIEW

**Comment by shenli** [comment]
Do we need to update the tikv min-version?

**Comment by zz-jason** [comment]
No need to

**Comment by zhexuany** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
LGTM

Maybe we should refer the related TiKV PR, otherwise tag a DNM label if it's not ready. @zz-jason  @AndreMouche

**Comment by zz-jason** [comment]
@tiancaiamao TiKV has supported `floor` a long time ago, it's safe to push it to tikv since we have passed all the tests including the random generated tests for `floor`

**Pull request merged**
