### PR TITLE
executor: fix csv parser  (#9005)

### PR DESCRIPTION
**Pull request by imtbkcat**
### What problem does this PR solve? 
cherry-pick https://github.com/pingcap/tidb/pull/9005

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

 - Increased code complexity

### CODE REVIEW

**Comment by jackysp** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by jackysp** [comment]
/run-integration-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by jackysp** [comment]
/run-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
@jackysp PTAL

**Pull request merged**
