### PR TITLE
planner: fix YCSB read-heavy regression caused by prep/exec statements

### LINKED ISSUE #37829: commit 7bdb7b5 cause 5%-6% performance downgrade in ycsb read-heavy workloadb and workloadc
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Deploy a tidb cluster and run ycsb workloadb and workloadc. 

### 2. What did you expect to see? (Required)
No performance downgrade.

### 3. What did you see instead (Required)
commit 7bdb7b5 cause 5%-6% performance downgrade
image

image

### 4. What is your TiDB version? (Required)

commit 7bdb7b5705ff19b533157373a861c720fc64c5f8

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #37829

Problem Summary: planner: fix YCSB read-heavy regression caused by prep/exec statements

### What is changed and how it works?

`PlanCacheStmt` is forgotten to set after https://github.com/pingcap/tidb/pull/37455.
`PlanCacheStmt` can cache some column info, so if it's not set, TiDB has to generate column info every time while writing data back to the client, which can incur performance regression.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by qw4990** [comment]
Seems like it's effective:
origin_img_v2_c83f8ed7-6d13-4871-a57b-1d82a70080ag

**Comment by qw4990** [comment]
origin_img_v2_61a5dac8-6978-4ce5-8ebe-e446e97933cg
This PR v.s. https://github.com/pingcap/tidb/pull/37890

**Review by Reminiscent — APPROVED** [review]

**Review by chrysan — APPROVED** [review]

**Pull request merged**
