### PR TITLE
execution: commit the transaction before responding explain analyze results to the client (#38044)

### LINKED ISSUE #37373: Explain analyze delete from doesn't work as expected
### 1. Minimal reproduce step (Required)
- sysbench prepare with 10000000 rows 
- run below by script without stop between each SQL(manual execute one by one can't reproduce)
```
mysql -uroot -D sbtest -e "select count(*) from sbtest where id < 10000000 limit 10000;"
mysql -uroot -D sbtest -e "explain analyze delete from sbtest where id < 10000000 limit 10000;" 
mysql -uroot -D sbtest -e "explain analyze delete from sbtest where id < 10000000 limit 10000;"
mysql -uroot -D sbtest -e "explain analyze delete from sbtest where id < 10000000 limit 10000;"
mysql -uroot -D sbtest -e "explain analyze delete from sbtest where id < 10000000 limit 10000;"
mysql -uroot -D sbtest -e "explain analyze delete from sbtest where id < 10000000 limit 10000;"
mysql -uroot -D sbtest -e "select count(*) from sbtest where id < 10000000 limit 10000;"
```

### 2. What did you expect to see? (Required)
the first select count(*) - the second select count(*) = 50000

### 3. What did you see instead (Required)
the first select count(*) - the second select count(*) < 50000

### 4. What is your TiDB version? (Required)

```
Release Version: v6.3.0-alpha
Edition: Community
Git Commit Hash: 8b5b724d8a932239303a1d0ba547323eb0e5161b
Git Branch: heads/refs/tags/v6.3.0-alpha
UTC Build Time: 2022-08-19 14:31:05
GoVersion: go1.18.5
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #38044 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/38060
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/38060:release-5.4-b0e073478ffe
```

---

### What problem does this PR solve?

Issue Number: close #37373 

Problem Summary:
The explain analyze statement execution with DML executors may respond to the client before the transaction commit finishing.

### What is changed and how it works?
Trigger the commit operation if the statement is an `explain analyze` statement with DML executors before returning the record set of itself.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
   -  Sleep before the commit
   -  Execute explain analyze
   - Check if it responses before the commit has finished
- [ ] No code

Side effects

Documentation

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue explain analyze with DML executors may respond to the client before the transaction commit has finished.
```

### CODE REVIEW

**Review by zyguan — APPROVED** [review]

**Comment by MyonKeminta** [comment]
There are still some conflicts.

**Comment by cfzjywxk** [comment]
@MyonKeminta 
Conflicts are resolved, PTAL

**Review by ekexium — APPROVED** [review]

**Comment by zyguan** [comment]
> @MyonKeminta Conflicts are resolved, PTAL

We have to use old version of testkit.

**Review by zyguan — APPROVED** [review]

**Comment by hawkingrei** [comment]
@cfzjywxk PTAL

```
[2022-09-23T09:44:19.618Z] planner/core/integration_test.go:19: File is not `goimports`-ed (goimports)

[2022-09-23T09:44:19.618Z] 	"fmt"

```

**Pull request merged**
