### PR TITLE
*: Add missing `ld` for arm64 Go builds

### PR DESCRIPTION
**Pull request by SalvatoreT**
Without this `binutils-gold` package, the build can't find `ld`.
https://stackoverflow.com/a/66529210/4951255

Closes https://github.com/pingcap/tidb/issues/25757

Problem Summary:

`ld` was missing for `arm64` builds of Docker.

What's Changed:

Add `ld` back with `binutils-gold`.

### Demo

```
❯ docker build -t pingcap/tidb:latest . --no-cache
[+] Building 75.2s (22/22) FINISHED
 => [internal] load build definition from Dockerfile                                                                                      0.0s
 => => transferring dockerfile: 1.37kB                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                         0.0s
 => => transferring context: 2B                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                          1.6s
 => [internal] load metadata for docker.io/library/golang:1.16-alpine                                                                     1.6s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                             0.0s
 => [auth] library/golang:pull token for registry-1.docker.io                                                                             0.0s
 => CACHED [builder  1/10] FROM docker.io/library/golang:1.16-alpine@sha256:34e3951701d7cc4153ca322933ed82edf8575af0d3f5c40362dca3b3c2bc  0.0s
 => CACHED [stage-1 1/5] FROM docker.io/library/alpine@sha256:234cb88d3020898631af0ccbbcca9a66ae7306ecd30c9720690858c1b007d2a0            0.0s
 => [internal] load build context                                                                                                         0.1s
 => => transferring context: 235.14kB                                                                                                     0.1s
 => [builder  2/10] RUN apk add --no-cache     wget     make     git     gcc     binutils-gold     musl-dev                               6.4s
 => [stage-1 2/5] RUN apk add --no-cache     curl                                                                                         1.1s
 => [builder  3/10] RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd6  0.7s
 => [builder  4/10] RUN mkdir -p /go/src/github.com/pingcap/tidb                                                                          0.2s
 => [builder  5/10] WORKDIR /go/src/github.com/pingcap/tidb                                                                               0.0s
 => [builder  6/10] COPY go.mod .                                                                                                         0.0s
 => [builder  7/10] COPY go.sum .                                                                                                         0.0s
 => [builder  8/10] RUN GO111MODULE=on go mod download                                                                                   28.7s
 => [builder  9/10] COPY . .                                                                                                              0.6s
 => [builder 10/10] RUN make                                                                                                             36.3s
 => [stage-1 3/5] COPY --from=builder /go/src/github.com/pingcap/tidb/bin/tidb-server /tidb-server                                        0.2s
 => [stage-1 4/5] COPY --from=builder /usr/local/bin/dumb-init /usr/local/bin/dumb-init                                                   0.0s
 => exporting to image                                                                                                                    0.2s
 => => exporting layers                                                                                                                   0.2s
 => => writing image sha256:850af5ee97b0200ab167944a9d581a69f0b0f83e3874e7d1379fd62e98476d28                                              0.0s
 => => naming to docker.io/pingcap/tidb:latest                                                                                            0.0s
```

### Side effects

Additional library on the Docker container

### Release note

- No release note

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]

**Comment by bb7133** [comment]
Hello, thank you for your contribution!

**Comment by bb7133** [comment]
PTAL @zhouqiang-cl

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Comment by SalvatoreT** [comment]
Thank you!

**Pull request merged**
