### PR TITLE
ddl/reorg: enlarge runDDLJob wait timeout

### PR DESCRIPTION
**Pull request by crazycs520**
## What have you changed? (mandatory)

Enlarge ReorgWaitTimeout to avoid too many useless log

## What are the type of the changes (mandatory)?

The currently defined types are listed below, please pick one of the types for this PR by removing the others:
- Improvement (non-breaking change which is an improvement to an existing feature)

### CODE REVIEW

**Comment by shenli** [comment]
Will there be any drawback in this way?

**Comment by shenli** [comment]
Where is the `too many useless log`?

**Comment by crazycs520** [comment]
If `ReorgWaitTimeout` to small, when add index to a table with lots of data, `func (d *ddl) runReorgJob()` will return  frequently because of update DDL reorgInfo , then DDL owner will get the job again from queue, continue to do the job ...... this process will produce many redundancy log.

Drawback is if someone cancel the add index job, the job will be cancel at most after `ReorgWaitTimeout`

**Comment by shenli** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Pull request merged**
