### PR TITLE
executor: fix KVSnapshot missing set txnScope

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

KVSnapshot missing set txnScope which will cause `PointGet`/`BatchPointGet` local stale read not work.

### What is changed and how it works?

Fix KVSnapshot missing set txnScope

### Release note 

- No release note

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Comment by JmPotato** [comment]
Do we need to cherry-pick this PR?

**Review by xhebox — APPROVED** [review]

**Pull request merged**
