### PR TITLE
statistics: fix wrong point range in crossValidationSelectivity

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: ref #28030

Problem Summary:
Fix the second problem described in #28030.

### What is changed and how it works?

When we calculate the selectivity of multi-column equal conditions in `crossValidationSelectivity`, we construct the point range to calculate the selectivity for each column that has the equal condition, and then multiply these selectivities to get the final selectivity. However, we have a tiny fault when constructing the point range for each column, which is that we don't correctly set `LowExclude`/`HighExclude`. Since the column range is point range(`LowVal` is equal to `HighVal`), we need to set both `LowExclude` and `HighExclude` to false. Otherwise we would get 0.0 estRow.

You can try the unit test on master and will find the test fails. On master the optimizer thinks estRow of TableRangeScan is 0.00 rather than 2.00, which is wrong estimation.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by xuyifangreeneyes** [comment]
/cherry-pick-5.0

**Review by time-and-fate — APPROVED** [review]

**Pull request merged**
