### PR TITLE
remove junk from go.sum

### PR DESCRIPTION
**Pull request by gregwebs**
### What problem does this PR solve?

In the transition to go modules some junk was added to tidb's dependencies. #8054
Code review pointed this out and also the fact that any of the dependencies may have changed from what they were pegged at, but these issues has not been addressed.

This PR just removes some obvious junk.

### What is changed and how it works?

I deleted a couple weird things in the go.sum

Tests

If it compiles it should work.

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8364)

### CODE REVIEW

**Comment by zz-jason** [comment]
@tiancaiamao PTAL

**Comment by zz-jason** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Comment by tiancaiamao** [comment]
https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file

> The go command maintains a cache of downloaded packages and computes
> and records the cryptographic checksum of each package at download time.
> In normal operation, the go command checks these pre-computed checksums
> against the main module's go.sum file, instead of recomputing them on
> each command invocation. The 'go mod verify' command checks that
> the cached copies of module downloads still match both their recorded
> checksums and the entries in go.sum.

And here:
https://www.reddit.com/r/golang/comments/97dxj1/should_i_add_the_gosum_file_to_the_repo_of_a/

We should just take care of the `go.mod` file.  @gregwebs

**Comment by gregwebs** [comment]
See in [PD](https://github.com/pingcap/pd/pull/1269#issuecomment-429306990) where this same thing happened: there were dependencies showing up that made no sense. Then the process was done more carefully and the dependencies were no longer there.

Unfortunately I don't have deep insight into the go mod process. The only thing I can say for certain is that airbrake was not a dependency before go modules and then showed up afterwards, and that we certainly don't use it. I run `make` or even `go mod tidy` it doesn't show up in go.sum

**Pull request closed without merging**
