### PR TITLE
*: fix some errcheck

### PR DESCRIPTION
**Pull request by wuliuqii**
### What problem does this PR solve?

Issue Number: part of #22979 

Problem Summary:

### What is changed and how it works?

What's Changed: added errcheck

### Check List 

Tests 

- No code

### Release note 

- No release note.

### CODE REVIEW

**Comment by tisonkun** [comment]
@wuliuqii Thanks for your contribution! Would you mind to do a whole check of errcheck instead of fragmented prs?

**Comment by wuliuqii** [comment]
OK，I'll try

**Comment by tisonkun** [comment]
@wuliuqii Any updates? BTW there is an ongoing effort to restructure tests #26022 , you may be interested in.

**Review by tisonkun — APPROVED** [review]
Well. Anyway I think this PR is good to merge.

**Review by zimulala — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]

**Pull request merged**
