### PR TITLE
sessionctx: Remove date_format, datetime_format,max_tmp_tables variables

### LINKED ISSUE #9155: MySQL 8.0: Remove date_format, datetime_format,max_tmp_tables variables
## Feature Request

**Is your feature request related to a problem? Please describe:**

MySQL 8.0 removes the following variables which have no actual behavior, so they should be safe to remove in TiDB as well:
```
date_format
datetime_format
max_tmp_tables
```

**Describe the feature you'd like:**

Remove:
```
date_format
datetime_format
max_tmp_tables
```
**Describe alternatives you've considered:**

I do not believe this feature requires a compatibility mode.

**Teachability, Documentation, Adoption, Migration Strategy:**

Improves MySQL 8.0 compatibility, makes TiDB behavior easier to explain.

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #9155 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
The `date_format`, `datetime_format` and `max_tmp_tables` variables have been removed.
```

### CODE REVIEW

**Review by mjonss — APPROVED** [review]
What are the manual tests? :)
I assume that the variables could be read before, and now cannot be read?

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by dveeden** [comment]
> What are the manual tests? :) I assume that the variables could be read before, and now cannot be read?

Without this PR
```
mysql> SHOW GLOBAL VARIABLES LIKE 'datetime_format';
+-----------------+-------------------+
| Variable_name   | Value             |
+-----------------+-------------------+
| datetime_format | %Y-%m-%d %H:%i:%s |
+-----------------+-------------------+
1 row in set (0.00 sec)

mysql> SHOW GLOBAL VARIABLES LIKE 'max_tmp_tables';
+----------------+-------+
| Variable_name  | Value |
+----------------+-------+
| max_tmp_tables | 32    |
+----------------+-------+
1 row in set (0.00 sec)

mysql> SHOW GLOBAL VARIABLES LIKE 'date_format';
+---------------+----------+
| Variable_name | Value    |
+---------------+----------+
| date_format   | %Y-%m-%d |
+---------------+----------+
1 row in set (0.00 sec)
```

With this PR:
```
mysql> SHOW GLOBAL VARIABLES LIKE 'datetime_format';
Empty set (0.00 sec)

mysql> SHOW GLOBAL VARIABLES LIKE 'max_tmp_tables';
Empty set (0.00 sec)

mysql> SHOW GLOBAL VARIABLES LIKE 'date_format';
Empty set (0.00 sec)
```

**Pull request merged**
