### PR TITLE
Revert "topsql: enable topsql feature by default (#33195)"

### LINKED ISSUE #33492: Disable TopSQL by default since the performance  regression is too large
## Background

Since after enable TopSQL, sysbench `oltp-point-get` QPS will has 10% performance  regression, so should disable TopSQL by default.

### PR DESCRIPTION
**Pull request by crazycs520**
This reverts commit 44cf3986e38363ecabf97145a2ca75b52d4428e1.

### What problem does this PR solve?

Issue Number: close #33492

Problem Summary: Disable TopSQL by default since the performance regression is too large

### Check List

Tests 
### Release note

```release-note
None
```

### CODE REVIEW

**Comment by ngaut** [comment]
I remember someone is  try to do more optimizations to fix this issue. Is it works?

**Comment by crazycs520** [comment]
> I remember someone is try to do more optimizations to fix this issue. Is it works?

The current optimization effect is not significant for the time being.

**Review by zhongzc — APPROVED** [review]

**Comment by mornyx** [comment]
LGTM

**Comment by breeswish** [comment]
> I remember someone is try to do more optimizations to fix this issue. Is it works?

@ngaut The current performance regression for Sysbench PointSelect is still notable (>5%) so that we have decided to not enable it by default for now. 

Luckily,

- In more complicated cases like TPCC and TPCH the regression is small, so that user **is likely** to not meet such high regressions in real world.
- Users can enable or disable the Top SQL feature on-demand in the UI or via SQL.
- For "Windows Task Manager" in Windows and "Monitor" in MacOS, user only calls it out when needed, i.e. the system is slow. So that we think Top SQL can act similarly: enable on-demand when cluster is in high load.

For reasons above, we will use v6.0.0 with default disabled as the first iteration. It will guide us whether we should do further optimizations in future, or just enable it by default later.

**Review by breeswish — APPROVED** [review]

**Comment by breeswish** [comment]
Please also roll in @bb7133 to review whether this PR rollback is a safe change.

**Review by qw4990 — APPROVED** [review]
/merge

**Pull request merged**
