### PR TITLE
executor: Correct typo: s/TslNone/TlsNone/

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

This corrects a typo

### Related changes
- https://github.com/pingcap/parser/pull/1270
- https://github.com/pingcap/parser/issues/1239

### Release note 

- No release note

Leaving this as draft as the pingcap/parser PR needs to be merged first so we can update the parser.

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Comment by dveeden** [comment]
```
$ go get github.com/pingcap/parser@1599cceb78b94ca3f273d165a12ec8988927d595
go get: upgraded github.com/pingcap/errors v0.11.5-0.20201126102027-b0a155152ca3 => v0.11.5-0.20210425183316-da1aaba5fb63
go get: upgraded github.com/pingcap/log v0.0.0-20210317133921-96f4fcab92a4 => v0.0.0-20210625125904-98ed8e2eb1c7
go get: upgraded github.com/pingcap/parser v0.0.0-20210618124025-07ae8d9291c4 => v0.0.0-20210707100355-1599cceb78b9
go get: upgraded go.uber.org/zap v1.17.0 => v1.18.1
```
Updating pingcap/parser results in errors due to https://github.com/pingcap/parser/pull/1262 requiring changes in tidb

```
$ make server
CGO_ENABLED=1 GO111MODULE=on go build  -tags codes  -ldflags '-X "github.com/pingcap/parser/mysql.TiDBReleaseVersion=v5.2.0-alpha-223-g337f93d50-dirty" -X "github.com/pingcap/tidb/util/versioninfo.TiDBBuildTS=2021-07-07 10:09:45" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitHash=337f93d507a9a4138f10ae0e4638f38adbd03fe0" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitBranch=TlsNone" -X "github.com/pingcap/tidb/util/versioninfo.TiDBEdition=Community" ' -o bin/tidb-server tidb-server/main.go
# github.com/pingcap/tidb/planner/core
planner/core/common_plans.go:1004:15: undefined: ast.ExplainFormatROW
planner/core/common_plans.go:1019:18: undefined: ast.ExplainFormatROW
planner/core/common_plans.go:1019:99: undefined: ast.ExplainFormatBrief
planner/core/common_plans.go:1021:17: undefined: ast.ExplainFormatVerbose
planner/core/common_plans.go:1023:17: undefined: ast.ExplainFormatROW
planner/core/common_plans.go:1025:17: undefined: ast.ExplainFormatDOT
planner/core/common_plans.go:1027:17: undefined: ast.ExplainFormatHint
planner/core/common_plans.go:1052:7: undefined: ast.ExplainFormatROW
planner/core/common_plans.go:1052:29: undefined: ast.ExplainFormatBrief
planner/core/common_plans.go:1052:53: undefined: ast.ExplainFormatVerbose
planner/core/common_plans.go:1052:53: too many errors
make: *** [Makefile:158: server] Error 2
```

**Review by bb7133 — APPROVED** [review]

**Comment by bb7133** [comment]
Please update the parser.

**Comment by dveeden** [comment]
> Please update the parser.

:white_check_mark:

**Comment by dveeden** [comment]
@zhuo-zhi took care of this in #26696 / a27d306e65a0f2bff923867895ac5b55e8a47546

**Pull request closed without merging**
