### PR TITLE
tidb-server:fix metrics push way

### PR DESCRIPTION
**Pull request by nolouch**
if multiple tidb start in one machine , they have same group key ( job and instance) in pushgateway. use `FromGatherer` will cause mutual influence , late push one will remove all metrics with same key in early and then save its own metrics. `AddFromGatherer` just update without remove previous data.

### CODE REVIEW

**Comment by shenli** [comment]
@nolouch If we restart a tidb-server, will it remove all metrics before retarting?

**Comment by shenli** [comment]
LGTM

**Comment by nolouch** [comment]
if restart it just remove metrics in pushgateway and push new. but in running, one tidb will delete others tidb metrics with same group key in pushgateway ,so prometheus will pull the damaged data.

**Comment by shenli** [comment]
@coocood PTAL

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
