### PR TITLE
plan: support subquery in `Do` statement (#8343)

### PR DESCRIPTION
**Pull request by eurekaka**
cherry-pick #8343

### CODE REVIEW

**Comment by zz-jason** [comment]
LGTM

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
```

**Comment by eurekaka** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
