### PR TITLE
planner: fix inappropriate null flag of null constants

### LINKED ISSUE #23309: The FieldType of a NULL constant is not set correctly, which cause TiFlash return wrong result.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

refer to pingcap/tics#1522

1. Mini reproduce
```sql
create table t(a int primary key,b int);
insert into t values(0,2);
ALTER TABLE t SET TIFLASH REPLICA 1;
select * from t2 where a!=null or b=1;
```
2. Expected result
Empty set
3. Actual result
The result from Tikv engine is correct, but the TiFlash engine is 
```
+---+------+
| a | b    |
+---+------+
| 0 |    2 |
+---+------+
```

Cluster version:
Release Version: v4.0.0-beta.2-2209-gfebac515b
Edition: Community
Git Commit Hash: febac515b1369643216e1efc971a262615dc4794
Git Branch: master
UTC Build Time: 2021-03-01 03:47:27
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

As showed in blow, the root cause is for a Null constant, TiDB still set the not null flag.

test

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #23309 

Problem Summary: planner: fix inappropriate null flag of null constants

### What is changed and how it works?

remove NotNullFlag of null constants when modifying their types.

### Check List 

Tests 

- Unit test

### Release note 

- planner: fix inappropriate null flag of null constants

### CODE REVIEW

**Review by Reminiscent — APPROVED** [review]
/LGTM

**Review by winoros — APPROVED** [review]

**Comment by hi-rustin** [comment]
> /label sig/planner

Try `/sig planner`

**Comment by zimulala** [comment]
@qw4990  Please cherry-pick to v5.0

**Pull request merged**
