### PR TITLE
*: fix cop task runtime information is wrong in the concurrent executor (#19849)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19849 to release-4.0

---

### What problem does this PR solve?

close https://github.com/pingcap/tidb/issues/19847

### What is changed and how it works?

In some case such as `index join`, 1 plan maybe use multiple `executor` for concurrency, so, 1 plan ID maybe have multiple executor runtime stats.

This PR use an array to record executor runtime stats and merge them when query the executor runtime stats. 

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test 

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- Fix cop task runtime information is wrong in the concurrent executor.

### CODE REVIEW

**Review by XuHuaiyu — COMMENTED** [review]
ci failed

**Review by AilinKid — COMMENTED** [review]
LGTM

**Comment by zz-jason** [comment]
@crazycs520 seems the cherry-pick is incorrect: `Files changed (0)`

**Comment by crazycs520** [comment]
wait https://github.com/pingcap/tidb/pull/20199 merge first.

**Comment by crazycs520** [comment]
Wait https://github.com/pingcap/tidb/pull/20430 merge first.

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by tangenta — COMMENTED** [review]
LGTM

**Review by crazycs520 — APPROVED** [review]

**Comment by crazycs520** [comment]
@SunRunAway, Could you help to merge?

**Pull request merged**
