### PR TITLE
parser: fix a bug when default value match `+ NumLiteral` or `- NumLiteral`

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
### What problem does this PR solve?
parser will get wrong default value when sql looks like:
```
alter table test add column(age int default -1);
```
and after Parse the default value will be `NULL`.

this bug is found in syncer.

### What is changed and how it works?
fix bug in parser.y

### Check List

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
run syncer, execute sql looks like `alter table test add column(age int default -1);`  in mysql.

### CODE REVIEW

**Comment by eurekaka** [comment]
> and after Parse the default value will be NULL.

I checked the code path and behavior of this sql, seems it works fine on master branch now:
```sql
MySQL [test]> create table ttt(a int);
Query OK, 0 rows affected (0.01 sec)

MySQL [test]> alter table ttt add column(age int default -1);
Query OK, 0 rows affected (0.02 sec)

MySQL [test]> insert into ttt(a) values(1);
Query OK, 1 row affected (0.10 sec)

MySQL [test]> select * from ttt;
+------+------+
| a    | age  |
+------+------+
|    1 |   -1 |
+------+------+
1 row in set (0.00 sec)
```

`UnaryOperationExpr` is able to handle the `-1`. Could you please elaborate more on the details of the bug?

**Comment by WangXiangUSTC** [comment]
@eurekaka 
you can use these code check it 
```
package main

import (
	"fmt"
	"strconv"
	
	"github.com/pingcap/tidb/parser"
	"github.com/pingcap/tidb/ast"
	"github.com/pingcap/tidb/types"
)

func formatStringValue(s string) string {
	if s == "" {
		return "''"
	}
	return fmt.Sprintf("'%s'", s)
}

func defaultValueToSQL(opt *ast.ColumnOption) string {
	sql := " DEFAULT "
	datum := opt.Expr.GetDatum()
	switch datum.Kind() {
	case types.KindNull:
		fmt.Println("types.KindNull")
		expr, ok := opt.Expr.(*ast.FuncCallExpr)
		if ok {
			fmt.Printf("%s", expr.FnName.O)
			sql += expr.FnName.O
		} else {
			fmt.Println("NULL")
			sql += "NULL"
		}

	case types.KindInt64:
		fmt.Println("KindInt64")
		sql += strconv.FormatInt(datum.GetInt64(), 10)

	case types.KindString:
		fmt.Println("KindString")
		sql += formatStringValue(datum.GetString())

	default:
		fmt.Printf("%v", datum.GetValue())
		sql += fmt.Sprintf("%v", datum.GetValue())
	}

	return sql
}

func columnOptionsToSQL(options []*ast.ColumnOption) string {
	sql := ""
	for _, opt := range options {
		switch opt.Tp {
		case ast.ColumnOptionNotNull:
			fmt.Println("ColumnOptionNotNull")
			sql += " NOT NULL"
		case ast.ColumnOptionNull:
			fmt.Println("ColumnOptionNull")
			sql += " NULL"
		case ast.ColumnOptionDefaultValue:
			fmt.Println("ColumnOptionDefaultValue")
			sql += defaultValueToSQL(opt)
		case ast.ColumnOptionAutoIncrement:
			fmt.Println("ColumnOptionAutoIncrement")
			sql += " AUTO_INCREMENT"
		case ast.ColumnOptionUniqKey:
			fmt.Println("ColumnOptionUniqKey")
			sql += " UNIQUE KEY"
		case ast.ColumnOptionPrimaryKey:
			fmt.Println("ColumnOptionPrimaryKey")
			sql += " PRIMARY KEY"
		case ast.ColumnOptionComment:
			fmt.Println("ColumnOptionComment")
			sql += fmt.Sprintf(" COMMENT '%v'", opt.Expr.GetValue())
		case ast.ColumnOptionOnUpdate: // For Timestamp and Datetime only.
			fmt.Println("ColumnOptionOnUpdate")
			sql += " ON UPDATE CURRENT_TIMESTAMP"
		case ast.ColumnOptionFulltext:
			panic("not implemented yet")
		default:
			panic("not implemented yet")
		}
	}

	return sql
}

func main() {
	sql := "alter table ttt add column(age int not null default -1);"
	stmts, err := parser.New().Parse(sql, "", "")
	if err != nil {
		fmt.Println(err)
		return
	}

	switch v := stmts[0].(type) {
	case *ast.AlterTableStmt:
		for _, spec := range v.Specs {
			fmt.Println(columnOptionsToSQL(spec.NewColumns[0].Options))
		}
	}
}

```

**Comment by shenli** [comment]
@WangXiangUSTC I guess the root cause is that in `defaultValueToSQL` only handles value-expr. But some default expressions are not evaluated in parser. I guess they are evaluated in somewhere like planner or ddl module.

**Comment by eurekaka** [comment]
Right, `defaultValueToSQL` does not handle `UnaryOperationExpr `, `UnaryOperationExpr ` is evaluated in ddl module by calling `evalAstExpr` function of plan package. Here is the callstack:
```
 0  0x00000000012f37ae in github.com/pingcap/tidb/plan.(*expressionRewriter).Leave
    at ./plan/expression_rewriter.go:757
 1  0x0000000000b2bd2b in github.com/pingcap/tidb/ast.(*ValueExpr).Accept
    at ./ast/expressions.go:129
 2  0x0000000000b33d31 in github.com/pingcap/tidb/ast.(*UnaryOperationExpr).Accept
    at ./ast/expressions.go:887
 3  0x00000000012e65fd in github.com/pingcap/tidb/plan.(*planBuilder).rewriteExprNode
    at ./plan/expression_rewriter.go:133
 4  0x00000000012e5ffc in github.com/pingcap/tidb/plan.(*planBuilder).rewriteWithPreprocess
    at ./plan/expression_rewriter.go:105
 5  0x00000000012e5cb8 in github.com/pingcap/tidb/plan.(*planBuilder).rewrite
    at ./plan/expression_rewriter.go:81
 6  0x00000000012e562b in github.com/pingcap/tidb/plan.evalAstExpr
    at ./plan/expression_rewriter.go:49
 7  0x000000000124c736 in github.com/pingcap/tidb/ddl.getDefaultValue
    at ./ddl/ddl_api.go:428
 8  0x000000000124b017 in github.com/pingcap/tidb/ddl.columnDefToCol
    at ./ddl/ddl_api.go:341
 9  0x000000000124a2ea in github.com/pingcap/tidb/ddl.buildColumnAndConstraint
    at ./ddl/ddl_api.go:247
10  0x0000000001257d78 in github.com/pingcap/tidb/ddl.(*ddl).AddColumn
    at ./ddl/ddl_api.go:1246
```

Does this `defaultValueToSQL` function come from syncer? Should we modify parser in TiDB or should we enhance `defaultValueToSQL` in syncer?

**Comment by shenli** [comment]
@WangXiangUSTC

**Comment by WangXiangUSTC** [comment]
@shenli @eurekaka I fix it in syncer, so pr can be closed. Thanks!

**Pull request closed without merging**
