### PR TITLE
config: complete the list of deprecated configurations

### PR DESCRIPTION
**Pull request by bobotu**
### What problem does this PR solve?

When upgrading from v3.0, `check-config` will fail due to some deprecated configs not listed in `deprecatedConfig`. This PR complete this list.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 
- No code

### Release note 

- Make the configuration checker compatible with older versions of the configuration

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM

**Comment by jackysp** [comment]
please resolve conflicts, @bobotu .

**Pull request merged**
