### PR TITLE
statistics: skip build statistics for view in auto analyze

### LINKED ISSUE #25898: data race in `tidb/domain/domain.go:1336`
## Bug Report

Please answer these questions before submitting your issue. Thanks!
```
[2021-07-01T21:16:43.031Z] ==================
[2021-07-01T21:16:43.031Z] WARNING: DATA RACE
[2021-07-01T21:16:43.031Z] Read at 0x00c004d7d728 by goroutine 107:
[2021-07-01T21:16:43.031Z]   github.com/pingcap/parser/types.(*FieldType).EvalType()
[2021-07-01T21:16:43.031Z]       /nfs/cache/mod/github.com/pingcap/parser@v0.0.0-20210618124025-07ae8d9291c4/types/field_type.go:96 +0x44
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/statistics.NewHistogram()
[2021-07-01T21:16:43.031Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/statistics/histogram.go:96 +0x80
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/statistics.PseudoTable()
[2021-07-01T21:16:43.031Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/statistics/table.go:688 +0x34c
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).GetPartitionStats()
[2021-07-01T21:16:43.031Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:519 +0x159
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).GetTableStats()
[2021-07-01T21:16:43.031Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:511 +0xe12
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).HandleAutoAnalyze()
[2021-07-01T21:16:43.031Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/statistics/handle/update.go:944 +0xde3
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/domain.(*Domain).autoAnalyzeWorker()
[2021-07-01T21:16:43.031Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/domain/domain.go:1336 +0x2ea
[2021-07-01T21:16:43.031Z] 
[2021-07-01T21:16:43.031Z] Previous write at 0x00c004d7d728 by goroutine 87:
[2021-07-01T21:16:43.031Z]   [failed to restore the stack]
[2021-07-01T21:16:43.031Z] 
[2021-07-01T21:16:43.031Z] Goroutine 107 (running) created at:
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/domain.(*Domain).UpdateTableStatsLoop()
[2021-07-01T21:16:43.031Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/domain/domain.go:1170 +0x350
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/session.BootstrapSession()
[2021-07-01T21:16:43.031Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/session/session.go:2490 +0x653
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/table/tables_test.(*testSuite).SetUpSuite()
[2021-07-01T21:16:43.031Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/table/tables/tables_test.go:65 +0x15c
[2021-07-01T21:16:43.031Z]   runtime.call16()
[2021-07-01T21:16:43.031Z]       /usr/local/go/src/runtime/asm_amd64.s:550 +0x3d
[2021-07-01T21:16:43.031Z]   reflect.Value.Call()
[2021-07-01T21:16:43.031Z]       /usr/local/go/src/reflect/value.go:337 +0xd8
[2021-07-01T21:16:43.031Z]   github.com/pingcap/check.(*suiteRunner).runFixture.func1()
[2021-07-01T21:16:43.031Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:799 +0x1d0
[2021-07-01T21:16:43.031Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2021-07-01T21:16:43.031Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x11d
[2021-07-01T21:16:43.031Z] 
[2021-07-01T21:16:43.031Z] Goroutine 87 (finished) created at:
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).prepare()
[2021-07-01T21:16:43.031Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/projection.go:271 +0xd04
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).parallelExecute()
[2021-07-01T21:16:43.031Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/projection.go:208 +0x5cb
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).Next()
[2021-07-01T21:16:43.031Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/projection.go:181 +0x10d
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/executor.Next()
[2021-07-01T21:16:43.031Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/executor.go:286 +0x2a8
[2021-07-01T21:16:43.031Z]   github.com/pingcap/tidb/executor.(*recordSet).Next()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/adapter.go:145 +0x115
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/session.(*execStmtResult).Next()
[2021-07-01T21:16:43.032Z]       <autogenerated>:1 +0x84
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/session.GetRows4Test()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/session/tidb.go:307 +0x35e
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/session.ResultSetToStringSlice()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/session/tidb.go:325 +0xba
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).ResultSetToResultWithCtx()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:389 +0xad
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).ResultSetToResult()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:384 +0x566
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustQuery()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:327 +0x571
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/table/tables_test.(*testSuite).TestViewColumns()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/table/tables/tables_test.go:739 +0x7b3
[2021-07-01T21:16:43.032Z]   runtime.call16()
[2021-07-01T21:16:43.032Z]       /usr/local/go/src/runtime/asm_amd64.s:550 +0x3d
[2021-07-01T21:16:43.032Z]   reflect.Value.Call()
[2021-07-01T21:16:43.032Z]       /usr/local/go/src/reflect/value.go:337 +0xd8
[2021-07-01T21:16:43.032Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2021-07-01T21:16:43.032Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xb3b
[2021-07-01T21:16:43.032Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2021-07-01T21:16:43.032Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x11d
[2021-07-01T21:16:43.032Z] ==================
[2021-07-01T21:16:43.032Z] ==================
[2021-07-01T21:16:43.032Z] WARNING: DATA RACE
[2021-07-01T21:16:43.032Z] Read at 0x00c004d7cfb0 by goroutine 107:
[2021-07-01T21:16:43.032Z]   github.com/pingcap/parser/types.(*FieldType).Clone()
[2021-07-01T21:16:43.032Z]       /nfs/cache/mod/github.com/pingcap/parser@v0.0.0-20210618124025-07ae8d9291c4/types/field_type.go:63 +0x3b5
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/statistics.NewHistogram()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/statistics/histogram.go:100 +0x4d4
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/statistics.PseudoTable()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/statistics/table.go:688 +0x34c
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).GetPartitionStats()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:519 +0x159
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).GetTableStats()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:511 +0xe12
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).HandleAutoAnalyze()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/statistics/handle/update.go:944 +0xde3
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/domain.(*Domain).autoAnalyzeWorker()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/domain/domain.go:1336 +0x2ea
[2021-07-01T21:16:43.032Z] 
[2021-07-01T21:16:43.032Z] Previous write at 0x00c004d7cfb0 by goroutine 87:
[2021-07-01T21:16:43.032Z]   [failed to restore the stack]
[2021-07-01T21:16:43.032Z] 
[2021-07-01T21:16:43.032Z] Goroutine 107 (running) created at:
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/domain.(*Domain).UpdateTableStatsLoop()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/domain/domain.go:1170 +0x350
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/session.BootstrapSession()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/session/session.go:2490 +0x653
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/table/tables_test.(*testSuite).SetUpSuite()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/table/tables/tables_test.go:65 +0x15c
[2021-07-01T21:16:43.032Z]   runtime.call16()
[2021-07-01T21:16:43.032Z]       /usr/local/go/src/runtime/asm_amd64.s:550 +0x3d
[2021-07-01T21:16:43.032Z]   reflect.Value.Call()
[2021-07-01T21:16:43.032Z]       /usr/local/go/src/reflect/value.go:337 +0xd8
[2021-07-01T21:16:43.032Z]   github.com/pingcap/check.(*suiteRunner).runFixture.func1()
[2021-07-01T21:16:43.032Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:799 +0x1d0
[2021-07-01T21:16:43.032Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2021-07-01T21:16:43.032Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x11d
[2021-07-01T21:16:43.032Z] 
[2021-07-01T21:16:43.032Z] Goroutine 87 (finished) created at:
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).prepare()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/projection.go:271 +0xd04
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).parallelExecute()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/projection.go:208 +0x5cb
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).Next()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/projection.go:181 +0x10d
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/executor.Next()
[2021-07-01T21:16:43.032Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/executor.go:286 +0x2a8
[2021-07-01T21:16:43.032Z]   github.com/pingcap/tidb/executor.(*recordSet).Next()
[2021-07-01T21:16:43.033Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/adapter.go:145 +0x115
[2021-07-01T21:16:43.033Z]   github.com/pingcap/tidb/session.(*execStmtResult).Next()
[2021-07-01T21:16:43.033Z]       <autogenerated>:1 +0x84
[2021-07-01T21:16:43.033Z]   github.com/pingcap/tidb/session.GetRows4Test()
[2021-07-01T21:16:43.033Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/session/tidb.go:307 +0x35e
[2021-07-01T21:16:43.033Z]   github.com/pingcap/tidb/session.ResultSetToStringSlice()
[2021-07-01T21:16:43.033Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/session/tidb.go:325 +0xba
[2021-07-01T21:16:43.033Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).ResultSetToResultWithCtx()
[2021-07-01T21:16:43.033Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:389 +0xad
[2021-07-01T21:16:43.033Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).ResultSetToResult()
[2021-07-01T21:16:43.033Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:384 +0x566
[2021-07-01T21:16:43.033Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustQuery()
[2021-07-01T21:16:43.033Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:327 +0x571
[2021-07-01T21:16:43.033Z]   github.com/pingcap/tidb/table/tables_test.(*testSuite).TestViewColumns()
[2021-07-01T21:16:43.033Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/table/tables/tables_test.go:739 +0x7b3
[2021-07-01T21:16:43.033Z]   runtime.call16()
[2021-07-01T21:16:43.033Z]       /usr/local/go/src/runtime/asm_amd64.s:550 +0x3d
[2021-07-01T21:16:43.033Z]   reflect.Value.Call()
[2021-07-01T21:16:43.033Z]       /usr/local/go/src/reflect/value.go:337 +0xd8
[2021-07-01T21:16:43.033Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2021-07-01T21:16:43.033Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xb3b
[2021-07-01T21:16:43.033Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2021-07-01T21:16:43.033Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x11d
[2021-07-01T21:16:43.033Z] ==================
```

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tidb-unit-test-nightly/runs/3334/nodes/116/steps/534/log/?start=0

### 4. What is your TiDB version? (Required)
master

### LINKED ISSUE #27274: data race detected in the test
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
[2021-08-17T03:01:44.935Z] ==================
[2021-08-17T03:01:44.935Z] WARNING: DATA RACE
[2021-08-17T03:01:44.935Z] Read at 0x00c00cf9bae8 by goroutine 59:
[2021-08-17T03:01:44.935Z]   github.com/pingcap/parser/types.(*FieldType).EvalType()
[2021-08-17T03:01:44.935Z]       /nfs/cache/mod/github.com/pingcap/parser@v0.0.0-20210812031716-f8bd71b2c3d9/types/field_type.go:96 +0x44
[2021-08-17T03:01:44.935Z]   github.com/pingcap/tidb/statistics.NewHistogram()
[2021-08-17T03:01:44.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/histogram.go:97 +0x80
[2021-08-17T03:01:44.935Z]   github.com/pingcap/tidb/statistics.PseudoTable()
[2021-08-17T03:01:44.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/table.go:703 +0x34c
[2021-08-17T03:01:44.935Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).GetPartitionStats()
[2021-08-17T03:01:44.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:525 +0x159
[2021-08-17T03:01:44.935Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).GetTableStats()
[2021-08-17T03:01:44.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:517 +0xe12
[2021-08-17T03:01:44.936Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).HandleAutoAnalyze()
[2021-08-17T03:01:44.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle/update.go:952 +0xde3
[2021-08-17T03:01:44.936Z]   github.com/pingcap/tidb/domain.(*Domain).autoAnalyzeWorker()
[2021-08-17T03:01:44.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/domain/domain.go:1350 +0x2ea
[2021-08-17T03:01:44.936Z] 
[2021-08-17T03:01:44.936Z] Previous write at 0x00c00cf9bae8 by goroutine 125:
[2021-08-17T03:01:44.936Z]   github.com/pingcap/tidb/executor.tryFillViewColumnType()
[2021-08-17T03:01:44.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/show.go:1776 +0x67c
[2021-08-17T03:01:44.936Z]   github.com/pingcap/tidb/executor.(*hugeMemTableRetriever).dataForColumnsInTable()
[2021-08-17T03:01:44.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:663 +0x133
[2021-08-17T03:01:44.936Z]   github.com/pingcap/tidb/executor.(*hugeMemTableRetriever).setDataForColumns()
[2021-08-17T03:01:44.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:652 +0x2ca
[2021-08-17T03:01:44.936Z]   github.com/pingcap/tidb/executor.(*hugeMemTableRetriever).retrieve()
[2021-08-17T03:01:44.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:2556 +0x333
[2021-08-17T03:01:44.936Z]   github.com/pingcap/tidb/executor.(*MemTableReaderExec).Next()
[2021-08-17T03:01:44.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/memtable_reader.go:114 +0x6f8
[2021-08-17T03:01:44.936Z]   github.com/pingcap/tidb/executor.Next()
[2021-08-17T03:01:44.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:286 +0x2a8
[2021-08-17T03:01:44.936Z]   github.com/pingcap/tidb/executor.(*SelectionExec).Next()
[2021-08-17T03:01:44.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:1302 +0x715
[2021-08-17T03:01:44.936Z]   github.com/pingcap/tidb/executor.Next()
[2021-08-17T03:01:44.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:286 +0x2a8
[2021-08-17T03:01:44.936Z]   github.com/pingcap/tidb/executor.(*projectionInputFetcher).run()
[2021-08-17T03:01:44.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:381 +0x498
[2021-08-17T03:01:44.936Z] 
```

CI link https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/9376/pipeline

### 2. What did you expect to see? (Required)
No Race

### 3. What did you see instead (Required)
Race

### 4. What is your TiDB version? (Required)

Master

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #27274

I'm not sure will it also close #25898 and #26539, because in those two, the data race stack is lost.
After this fix, if we don't see them in the future, that means they are also fixed.

Problem Summary:

The DATA RACE happen between `explain view` (or "select * from information_schema.columns") and auto-analyze.

Auto analyze need to read the table column info, while 'explain view' will modify it.
`tryFillViewColumnType` will modify the column in model.TableInfo, It's not a operation on a copy of data.
This operation is dangerous.

### What is changed and how it works?

What's Changed:

View is a special table, it doesn't not need to maintain the statistics.
This commit skip build statistics for view.

How it Works:

Statistics will skip the view table, so it doesn't conflict with the `explain view` or `select * from infoschema.columns` ...

Maybe change the `tryFillViewColumnType` function is another option, but **this fix is obviously right, and just one line change**.

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by lzmhhh123 — APPROVED** [review]

**Comment by lzmhhh123** [comment]
@tiancaiamao does this pr need to cherry-pick?

**Pull request merged**
