### PR TITLE
mock: add more mock to avoid dm ci failed

### PR DESCRIPTION
**Pull request by okJiang**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/50938

Problem Summary:

### Check List

Tests 

- [x] Unit test
image

- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
Seems the problem is in #50039 you changed the behaviour of `TestModifyFromNullToNotNull`. The unit test should always keep same behaviour as DM. Please revert it.

**Review by lance6716 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Pull request merged**
