### PR TITLE
executor: forbid stale read table with tiflash

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Problem Summary: Should ban tiflash stale read.

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

```
mysql root@localhost:(none)> create table test.table1 (id int primary key);
mysql root@localhost:(none)> ALTER TABLE test.table1 SET TIFLASH REPLICA 1
mysql root@localhost:(none)> SELECT * FROM information_schema.tiflash_replica // ensure tiflash replica is up
mysql root@localhost:(none)> explain analyze select * from test.table1 as of timestamp NOW();
(1105, 'staleness requests requires tikv backend')
mysql root@localhost:(none)> explain analyze select count(*) from test.table1 as of timestamp NOW();
(1105, 'staleness requests requires tikv backend')
```

### Release note 

- No release note

### CODE REVIEW

**Comment by nolouch** [comment]
cc @lzmhhh123

**Review by lzmhhh123 — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by lzmhhh123** [comment]
MPP gather should be considered?

**Comment by lzmhhh123** [comment]
executor/mpp_gather.go

**Comment by xhebox** [comment]
> executor/mpp_gather.go

It is created in the table reader executor, several lines behind my patch `useMPPExecution` and `buildMPPGather`. So it is considered.

**Comment by lzmhhh123** [comment]
> > executor/mpp_gather.go
> 
> It is created in the table reader executor, several lines behind my patch `useMPPExecution` and `buildMPPGather`. So it is considered.

Ok, that's fine.

**Review by nolouch — APPROVED** [review]

**Pull request merged**
