### PR TITLE
 ddl: update parser to make TiDB treat charset and collate case insensitive (#8577)

### PR DESCRIPTION
**Pull request by winkyao**
Cherry-pick from #8577 

Merge https://github.com/pingcap/parser/pull/70 first. I will update the go.mod after the parser pr is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8611)

### CODE REVIEW

**Comment by jackysp** [comment]
https://github.com/pingcap/parser/pull/70 is merged @winkyao

**Comment by winkyao** [comment]
go.mod is updated.

**Comment by winkyao** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Comment by winkyao** [comment]
/run-all-tests tikv=release-2.1 tidb-test=release-2.1 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tikv=release-2.1 tidb-test=pr/686 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tikv=release-2.1 tidb-test=pr/686 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-common-test tikv=release-2.1 tidb-test=pr/686 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-common-test tikv=release-2.1 tidb-test=pr/686 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-unit-test tikv=release-2.1 tidb-test=pr/686 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-common-test tikv=release-2.1 tidb-test=pr/686 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-common-test tikv=release-2.1 tidb-test=pr/686 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tikv=release-2.1 tidb-test=release-2.1 pd=release-2.1

**Comment by winkyao** [comment]
/run-all-tests tikv=release-2.1 tidb-test=release-2.1 pd=release-2.1

**Pull request merged**
