### PR TITLE
*: record and print the plan in slow log. (#12179)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
cherry-pick https://github.com/pingcap/tidb/pull/12179/files

conflict file list:
```shell
        both modified:   config/config.go
        both modified:   expression/builtin.go
        both modified:   expression/builtin_info.go
        both modified:   expression/integration_test.go
        both modified:   go.mod
        both modified:   go.sum
        both modified:   planner/core/initialize.go
        both modified:   planner/core/plan.go
        both modified:   planner/core/point_get_plan.go
        both modified:   planner/core/rule_partition_processor.go
        both modified:   sessionctx/variable/varsutil.go
        both modified:   util/logutil/log.go
```

### CODE REVIEW

**Comment by crazycs520** [comment]
run-unit-test

**Comment by qrr1995** [comment]
run-unit-test

**Pull request merged**
