### PR TITLE
planner, expression: pushdown AggFuncMode to coprocessor (#31392)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #31392 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/32276
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/32276:release-5.1-f949e01e0b20
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/30923
ref: 
https://github.com/pingcap/tipb/pull/254
https://github.com/pingcap/tics/pull/3822

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by MimeLyc** [comment]
refresh

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
