### PR TITLE
server: add debug log

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Manual test log:
```
[2022/09/02 15:55:55.565 +08:00] [WARN] [conn_stmt.go:68] ["[DEBUG] [STMT_PREPARE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:54080 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [sql="INSERT INTO t VALUES( ?, ? )"] [stmtID=1] [hasError=false] []
[2022/09/02 15:55:55.565 +08:00] [WARN] [conn_stmt.go:68] ["[DEBUG] [STMT_PREPARE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:54080 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [sql="INSERT INTO t VALUES( ?)"] [stmtID=0] [hasError=true] [error="[planner:1136]Column count doesn't match value count at row 1"]
[2022/09/02 15:55:55.565 +08:00] [INFO] [conn.go:877] ["command dispatched failed"] [conn=3] [connInfo="id:3, addr:127.0.0.1:54080 status:10, collation:utf8mb4_general_ci, user:root"] [command=Prepare] [status="inTxn:0, autocommit:1"] [sql="INSERT INTO t VALUES( ?)"] [txn_mode=PESSIMISTIC] [err="[planner:1136]Column count doesn't match value count at row 1\ngithub.com/pingcap/errors.AddStack\n\t/home/timeandfate/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/home/timeandfate/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/normalize.go:156\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).buildValuesListOfInsert\n\t/home/timeandfate/code/tidb/planner/core/planbuilder.go:2981\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).buildInsert\n\t/home/timeandfate/code/tidb/planner/core/planbuilder.go:2796\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).Build\n\t/home/timeandfate/code/tidb/planner/core/planbuilder.go:646\ngithub.com/pingcap/tidb/executor.(*PrepareExec).Next\n\t/home/timeandfate/code/tidb/executor/prepared.go:208\ngithub.com/pingcap/tidb/session.(*session).PrepareStmt\n\t/home/timeandfate/code/tidb/session/session.go:1745\ngithub.com/pingcap/tidb/server.(*TiDBContext).Prepare\n\t/home/timeandfate/code/tidb/server/driver_tidb.go:265\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmtPrepare\n\t/home/timeandfate/code/tidb/server/conn_stmt.go:77\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/timeandfate/code/tidb/server/conn.go:1118\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/timeandfate/code/tidb/server/conn.go:860\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/timeandfate/code/tidb/server/server.go:485\nruntime.goexit\n\t/usr/lib/go/src/runtime/asm_amd64.s:1594"]
[2022/09/02 15:55:55.566 +08:00] [WARN] [conn_stmt.go:68] ["[DEBUG] [STMT_PREPARE]"] [conn=5] [connInfo="id:5, addr:127.0.0.1:54084 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [sql="SELECT * FROM t WHERE a = ?"] [stmtID=1] [hasError=false] []
[2022/09/02 15:55:55.566 +08:00] [WARN] [2pc.go:1448] ["schemaLeaseChecker is not set for this transaction"] [sessionID=3] [startTS=435710946329493505] [commitTS=435710946329493506]
[2022/09/02 15:55:55.567 +08:00] [WARN] [conn_stmt.go:150] ["[DEBUG] [STMT_EXECUTE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:54080 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false] []
[2022/09/02 15:55:55.567 +08:00] [WARN] [conn_stmt.go:150] ["[DEBUG] [STMT_EXECUTE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:54080 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false] []
[2022/09/02 15:55:55.568 +08:00] [WARN] [conn_stmt.go:150] ["[DEBUG] [STMT_EXECUTE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:54080 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false] []
[2022/09/02 15:55:55.568 +08:00] [WARN] [conn_stmt.go:150] ["[DEBUG] [STMT_EXECUTE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:54080 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false] []
[2022/09/02 15:55:55.569 +08:00] [WARN] [conn_stmt.go:150] ["[DEBUG] [STMT_EXECUTE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:54080 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false] []
[2022/09/02 15:55:55.569 +08:00] [WARN] [conn_stmt.go:150] ["[DEBUG] [STMT_EXECUTE]"] [conn=5] [connInfo="id:5, addr:127.0.0.1:54084 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false] []
[2022/09/02 15:55:55.570 +08:00] [WARN] [conn_stmt.go:150] ["[DEBUG] [STMT_EXECUTE]"] [conn=5] [connInfo="id:5, addr:127.0.0.1:54084 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false] []
[2022/09/02 15:55:55.570 +08:00] [WARN] [conn_stmt.go:655] ["[DEBUG] [STMT_CLOSE]"] [connInfo="id:5, addr:127.0.0.1:54084 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] []
[2022/09/02 15:55:55.570 +08:00] [WARN] [conn_stmt.go:655] ["[DEBUG] [STMT_CLOSE]"] [connInfo="id:3, addr:127.0.0.1:54080 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] []

```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by time-and-fate** [comment]
Manual test log:
```
[2022/09/02 14:21:11.512 +08:00] [INFO] [conn_stmt.go:68] ["[DEBUG] [STMT_PREPARE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:56674 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [sql="INSERT INTO t VALUES( ?, ? )"] [stmtID=1] [hasError=false]
[2022/09/02 14:21:11.513 +08:00] [INFO] [conn_stmt.go:68] ["[DEBUG] [STMT_PREPARE]"] [conn=5] [connInfo="id:5, addr:127.0.0.1:56690 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [sql="SELECT * FROM t WHERE a = ?"] [stmtID=1] [hasError=false]
[2022/09/02 14:21:11.513 +08:00] [WARN] [2pc.go:1448] ["schemaLeaseChecker is not set for this transaction"] [sessionID=3] [startTS=435709456289103873] [commitTS=435709456289103874]
[2022/09/02 14:21:11.514 +08:00] [INFO] [conn_stmt.go:149] ["[DEBUG] [STMT_EXECUTE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:56674 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false]
[2022/09/02 14:21:11.514 +08:00] [INFO] [conn_stmt.go:149] ["[DEBUG] [STMT_EXECUTE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:56674 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false]
[2022/09/02 14:21:11.514 +08:00] [INFO] [conn_stmt.go:149] ["[DEBUG] [STMT_EXECUTE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:56674 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false]
[2022/09/02 14:21:11.514 +08:00] [INFO] [conn_stmt.go:149] ["[DEBUG] [STMT_EXECUTE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:56674 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false]
[2022/09/02 14:21:11.515 +08:00] [INFO] [conn_stmt.go:149] ["[DEBUG] [STMT_EXECUTE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:56674 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false]
[2022/09/02 14:21:11.516 +08:00] [INFO] [conn_stmt.go:149] ["[DEBUG] [STMT_EXECUTE]"] [conn=5] [connInfo="id:5, addr:127.0.0.1:56690 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false]
[2022/09/02 14:21:11.516 +08:00] [INFO] [conn_stmt.go:149] ["[DEBUG] [STMT_EXECUTE]"] [conn=5] [connInfo="id:5, addr:127.0.0.1:56690 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [stmtID=1] [hasError=false]

```

**Comment by tiancaiamao** [comment]
Shall we log the delete stmt operation? maybe the user use it after delete, the log need to catch that case.

**Review by qw4990 — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
