### PR TITLE
lightning: allow burst traffic

### LINKED ISSUE #49519: allow burst to happen in lightning local backend
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
We really don't need a bust to prevent in lightning as it always send in batches. It might cause unnecessary throttle. 

### 2. What did you expect to see? (Required)
More even distribution of network traffic across tikvs
### 3. What did you see instead (Required)
I am seeing uneven distribution of traffic sometimes. But i don't have clear evidence point to this issue. However, i think it is a good fix to have. We already have it in prod. 
### 4. What is your TiDB version? (Required)
6.5

### PR DESCRIPTION
**Pull request by mittalrishabh**
### What problem does this PR solve?

Issue Number: close #49519

Problem Summary:
It unnecessarily controls the burst which is not required in lightning as it always sends in big batches. 
### What changed and how does it work?
Remove the burst limit
### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by D3Hunter** [comment]
> It unnecessarily controls the burst which is not required in lightning as it always sends in big batches.

you say `allow burst` in the issue, but in the code you're `remove the 20% burst`

> I am seeing uneven distribution of traffic sometimes. But i don't have clear evidence point to this issue. However, i think it is a good fix to have. We already have it in prod.

can you paste some result before/after this pr?

**Comment by mittalrishabh** [comment]
> > It unnecessarily controls the burst which is not required in lightning as it always sends in big batches.
> 
> you say `allow burst` in the issue, but in the code you're `remove the 20% burst`
> 
> > I am seeing uneven distribution of traffic sometimes. But i don't have clear evidence point to this issue. However, i think it is a good fix to have. We already have it in prod.
> 
> can you paste some result before/after this pr?

Githib Request is to allow burst in lightning because it always send large batches to tikv.  I don't have the clear evidence on how much it improve the lightning. But i don't see any regression and it is working fine in our production environment.

**Comment by lance6716** [comment]
@mittalrishabh Hi I need more time to look up the git history, to find out why we have this burst.

**Comment by D3Hunter** [comment]
> > > It unnecessarily controls the burst which is not required in lightning as it always sends in big batches.
> > 
> > 
> > you say `allow burst` in the issue, but in the code you're `remove the 20% burst`
> > > I am seeing uneven distribution of traffic sometimes. But i don't have clear evidence point to this issue. However, i think it is a good fix to have. We already have it in prod.
> > 
> > 
> > can you paste some result before/after this pr?
> 
> Githib Request is to allow burst in lightning because it always send large batches to tikv. I don't have the clear evidence on how much it improve the lightning. But i don't see any regression and it is working fine in our production environment.

we already have burst, this pr only changes burst from `limit * (1 + 20%)` to `limit`

**Pull request closed without merging**
