### PR TITLE
cop: display kv read time details in the execution information

### PR DESCRIPTION
**Pull request by cfzjywxk**
<!--

Thank you for contributing to TiDB!

PR Title Format:
1. pkg [, pkg2, pkg3]: what's changed
2. *: what's changed

-->

### What problem does this PR solve?
<!--

Please create an issue first to describe the problem.

There MUST be one line starting with "Issue Number:  " and
linking the relevant issues via the "close" or "ref".

For more info, check https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#referring-to-an-issue.

-->

Issue Number: ref #28937 

Problem Summary:
```
explain analyze select * from t1;
+-----------------------+---------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------+-----------+------+
| id                    | estRows | actRows | task      | access object | execution info                                                                                                                                                                                                                                                                                                                                               | operator info                               | memory    | disk |
+-----------------------+---------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------+-----------+------+
| TableReader_5         | 6.00    | 6       | root      |               | time:104.4ms, loops:2, RU:0.714463, cop_task: {num: 1, max: 104.2ms, proc_keys: 6, tot_proc: 704.9µs, tot_wait: 513.1µs, rpc_num: 1, rpc_time: 104.1ms, copr_cache_hit_ratio: 0.00, build_task_duration: 553.6µs, max_distsql_concurrency: 1}                                                                                                                | data:TableFullScan_4                        | 542 Bytes | N/A  |
| └─TableFullScan_4     | 6.00    | 6       | cop[tikv] | table:t1      | tikv_task:{time:104ms, loops:1}, scan_detail: {total_process_keys: 6, total_process_keys_size: 295, total_keys: 7, get_snapshot_time: 206.9µs, rocksdb: {key_skipped_count: 6, block: {cache_hit_count: 2}}}, total_process_time: 704.9µs, total_suspend_time: 100.9ms, total_wait_time: 513.1µs, total_kv_read_wall_time: 104ms, tikv_wall_time: 103.1ms    | keep order:false, stats:partial[k1:missing] | N/A       | N/A  |
+-----------------------+---------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------+-----------+------+

The `total_kv_read_wall_time` could be displayed in the execution information.

```


### What changed and how does it work?

### Check List

Tests <!-- At least one of them must be included. -->
- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code


Side effects


Documentation



### Release note

<!-- compatibility change, improvement, bugfix, and new feature need a release note -->

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by cfzjywxk** [comment]
Em... The cache is not updated. sigh...

**Review by zyguan — APPROVED** [review]

**Review by ekexium — COMMENTED** [review]
Can we have a unit test for it?

**Comment by cfzjywxk** [comment]
> Can we have a unit test for it?

@ekexium The test is added, PTAL

**Review by ekexium — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM

**Comment by cfzjywxk** [comment]
Why
```
=== NAME  TestImportInto

    testing.go:1465: race detected during execution of test

--- FAIL: TestImportInto (27.60s)

    --- FAIL: TestImportInto/TestGlobalSortBasic (11.07s)

    --- PASS: TestImportInto/TestGlobalSortMultiFiles (8.73s)

    --- PASS: TestImportInto/TestSplitFile (5.83s)

=== NAME  

    testing.go:1465: race detected during execution of test

FAIL
```
this related failure?

**Pull request merged**
