### PR TITLE
domain: rename `binary_path` to `deploy_path` (reopen #16585)

### PR DESCRIPTION
**Pull request by mapleFU**
Signed-off-by: mapleFU <1506118561@qq.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

In tidb cluster, all components has a content like `binary_path` or `deploy_path`. And we want to unify them to `deploy_path`.

### What is changed and how it works?

What's Changed:

field name for `binary_path`.

### Check List 

Tests 

- No code

Side effects

No

### Release note 

* Unify the component interface and change `binary_path` to `deploy_path`.

### CODE REVIEW

**Comment by breeswish** [comment]
LGTM

**Comment by zz-jason** [comment]
@mapleFU please add some labels for this PR.

**Pull request merged**
