### PR TITLE
executor, planner: clone proj schema for different children in buildProj4Union

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve? 
``` sql
create table t(a int, b int);
insert into t values(1,2);
select a, b from (select a, 0 as d, b from t union all select a, 0 as d, b from t) test;
```

we want:

``` sql
+------+------+
| a    | b    |
+------+------+
|    1 |    2 |
|    1 |    2 |
+------+------+
```

but got:
``` sql
+------+------+
| a    | b    |
+------+------+
|    1 |    0 |
|    1 |    2 |
+------+------+
```

### What is changed and how it works?
Clone the schema for different projections which are built in `buildProjection4Union`.

Before this commit, `Schema.Columns` of different `LogicalProjection`s which are built upon the children of Union refer to the *same* Column slice.

The `Schema.Columns` is `[test.a, d, test.b]` in the above example.
After calling Union.Children[0].PruneColumn, we use [this](https://github.com/pingcap/tidb/blob/master/planner/core/rule_column_pruning.go#L68) to prune the columns.
Thus Union.Children[1].schema.Columns will become `[test.a, test.b, test.b]`.
Furthermore, [used bool slice](https://github.com/pingcap/tidb/blob/master/planner/core/rule_column_pruning.go#L65) will become [true, true, false], and cause test.b be pruned wrongly. 

### Check List 

Tests 

 - Integration test

Code changes

 - Has exported function/method change

Side effects

none

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by zz-jason** [comment]
should be cherry-picked to release-2.1 and release-2.0?

**Comment by zz-jason** [comment]
@kennytm @winoros PTAL

**Comment by XuHuaiyu** [comment]
I'll cherry-pick the commit after this PR be merged.

**Comment by winoros** [comment]
Emmm... You mean the columns that share the same unique id may cause bug if they share the same memory address?

**Comment by XuHuaiyu** [comment]
Not quite but almost. @winoros

**Comment by winoros** [comment]
Actually we just need to use a new slice header, don't need to clone the columns.
But whatever this can lgtm.

**Pull request merged**
