### PR TITLE
infoschema: support generation_expression column in information_schema.columns

### PR DESCRIPTION
**Pull request by jackysp**
## What have you changed? (mandatory)

Support generation_expression column in information_schema.columns will fix https://github.com/pingcap/tidb/issues/6949

## What are the type of the changes (mandatory)?

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested (mandatory)?

Unit test.

PTAL @hicqu @coocood @zz-jason

### CODE REVIEW

**Comment by jackysp** [comment]
merge it with https://github.com/pingcap/tidb-test/pull/568

**Comment by coocood** [comment]
LGTM

**Comment by coocood** [comment]
@zhexuany PTAL

**Pull request merged**
