### PR TITLE
DDL: add log when TiFlash replica available changed

### LINKED ISSUE #39242: Add log when TiFlash replica available changed
## Enhancement
Currently partition tables [only print log about `partitionID` but not `tableID`](https://github.com/pingcap/tidb/blob/e9253f73e0696443ee08473bd72f85230dc39be3/ddl/ddl_tiflash_api.go#L512) when they become `available`, it's inconvenient to find out if the partition table available when address bugs.

### PR DESCRIPTION
**Pull request by hehechen**
Signed-off-by: hehechen <chentongli@pingcap.com>

### What problem does this PR solve?

Issue Number: close #39242

Problem Summary:
Currently partition tables [only print log about `partitionID` but not `tableID`](https://github.com/pingcap/tidb/blob/e9253f73e0696443ee08473bd72f85230dc39be3/ddl/ddl_tiflash_api.go#L512) when they become `available`, it's inconvenient to find out if the partition table available when address bugs.
### What is changed and how it works?
Add log when TiFlash replica available changed
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by breezewish** [comment]
Could you describe in the PR body or issue body about why do we need this change?

**Comment by hehechen** [comment]
> Could you describe in the PR body or issue body about why do we need this change?

done

**Review by breezewish — APPROVED** [review]

**Review by CalvinNeo — APPROVED** [review]
lgtm

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
