### PR TITLE
executor: fix unstable TestStaleSelect

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

Fix unstable test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by xhebox — COMMENTED** [review]
So it is stable now?

**Comment by Yisaer** [comment]
I tested this case 100 times by `test.count 100` and the results is fine. I guess it's stable now.

**Review by wjhuang2016 — COMMENTED** [review]
So much sleep in this test, I guess that's why it's unstable?

**Comment by Yisaer** [comment]
> So much sleep in this test, I guess that's why it's unstable?

good catch, I think the root cause of the unstable test might be caused by `test dynamic timestamp stale select` when meeting cpu resource shortage.  I removed these testcases for now. @xhebox  WDYT?

**Review by xhebox — APPROVED** [review]
makes sense, dynamic timestamp test is much strict than other tests.

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
