### PR TITLE
executor: metrics slow query is divided into internal and general (#22350)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #22350 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/22405
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/22405:release-4.0-42edd7a29f9f
```

---

### What problem does this PR solve?

Currently `slow query metrics` contains `internal SQL`, 
These `internal SQL` may affect customers and DBA analysis problems, so add label to distinguish `internal` and `general`.

image

### What is changed and how it works?
 
What's Changed:

`Slow query` is divided into `internal` and `general` labels

How it Works:

`Slow query` is divided into `internal` and `general` labels

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

### Release note  
- Metrics slow query is divided into internal and general

### CODE REVIEW

**Comment by sev7ndayyoo** [comment]
@jackysp PTAL

**Review by jackysp — COMMENTED** [review]
LGTM

**Comment by jackysp** [comment]
PTAL @lysu

**Comment by lysu** [comment]
LGTM

**Review by jackysp — APPROVED** [review]

**Pull request merged**
