### PR TITLE
planner/core: pushdown TiFlash store type check to ColumnToProto

### LINKED ISSUE #55462: infoschema v1 and v2 are inconsistent during TestDisaggregatedTiFlashGeneratedColumn
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This issue is similar to #55442. Run TestDisaggregatedTiFlashGeneratedColumn using #55030.

### 2. What did you expect to see? (Required)

Test passed

### 3. What did you see instead (Required)

```
--- FAIL: TestDisaggregatedTiFlashGeneratedColumn (0.51s)
panic: inconsistent infoschema [recovered]
        panic: inconsistent infoschema [recovered]
        panic: inconsistent infoschema

goroutine 23 [running]:
testing.tRunner.func1.2({0x1070259a0, 0x10795bfe0})
        /Users/joechenrh/deps/go/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
        /Users/joechenrh/deps/go/src/testing/testing.go:1634 +0x33c
panic({0x1070259a0?, 0x10795bfe0?})
        /Users/joechenrh/deps/go/src/runtime/panic.go:770 +0x124
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec.func1()
        /Users/joechenrh/code/tidb-test/pkg/executor/adapter.go:484 +0x428
panic({0x1070259a0?, 0x10795bfe0?})
        /Users/joechenrh/deps/go/src/runtime/panic.go:770 +0x124
github.com/pingcap/tidb/pkg/infoschema.(*InfoschemaV3).TableByID(0x14006a72360, 0x6c)
        /Users/joechenrh/code/tidb-test/pkg/infoschema/infoschema_v3.go:225 +0xb8
github.com/pingcap/tidb/pkg/infoschema.(*SessionExtendedInfoSchema).TableByID(0x14007a63b90, 0x6c)
        /Users/joechenrh/code/tidb-test/pkg/infoschema/infoschema.go:843 +0x94
github.com/pingcap/tidb/pkg/executor.buildTableReq(0x14009931880, 0x3, {0x14005c8a870, 0x1, 0x14000da5cd8?})
        /Users/joechenrh/code/tidb-test/pkg/executor/builder.go:3913 +0x160
github.com/pingcap/tidb/pkg/executor.buildNoRangeIndexLookUpReader(0x14009931880, 0x14008425340)
        /Users/joechenrh/code/tidb-test/pkg/executor/builder.go:3981 +0xc4
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).buildIndexLookUpReader(0x14009931880, 0x14008425340)
        /Users/joechenrh/code/tidb-test/pkg/executor/builder.go:4043 +0xa4
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).build(0x10a1a80a0?, {0x1079cb4e0?, 0x14008425340})
        /Users/joechenrh/code/tidb-test/pkg/executor/builder.go:294 +0x98c
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).buildProjection(0x14009931880, 0x1400a559b20)
        /Users/joechenrh/code/tidb-test/pkg/executor/builder.go:2013 +0x68
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).build(0x107a23cd8?, {0x1079cafe0?, 0x1400a559b20})
        /Users/joechenrh/code/tidb-test/pkg/executor/builder.go:276 +0x92c
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).buildExplain(0x14009931880, 0x140082ac8f0)
        /Users/joechenrh/code/tidb-test/pkg/executor/builder.go:1236 +0x1ac
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).build(0x107a23cd8?, {0x1079cbe60?, 0x140082ac8f0})
        /Users/joechenrh/code/tidb-test/pkg/executor/builder.go:194 +0x119c
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).buildExecutor(0x14006e12870)
        /Users/joechenrh/code/tidb-test/pkg/executor/adapter.go:1210 +0x164
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec(0x14006e12870, {0x10799fef8, 0x14008259ce0})
        /Users/joechenrh/code/tidb-test/pkg/executor/adapter.go:555 +0x688
github.com/pingcap/tidb/pkg/session.runStmt({0x10799fe50, 0x10ad5b848}, 0x14001994008, {0x1079b4640, 0x14006e12870})
        /Users/joechenrh/code/tidb-test/pkg/session/session.go:2288 +0x344
github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt(0x14001994008, {0x10799fe50?, 0x10ad5b848?}, {0x1079b9020, 0x14009931180})
        /Users/joechenrh/code/tidb-test/pkg/session/session.go:2149 +0xd64
github.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext(0x140066a0050, {0x10799fe50, 0x10ad5b848}, {0x1400693aaa0, 0x44}, {0x0, 0x0, 0x0})
        /Users/joechenrh/code/tidb-test/pkg/testkit/testkit.go:385 +0x6f4
github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustQueryWithContext(0x140066a0050, {0x10799fe50, 0x10ad5b848}, {0x1400693aaa0, 0x44}, {0x0, 0x0, 0x0})
        /Users/joechenrh/code/tidb-test/pkg/testkit/testkit.go:196 +0xc8
github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustQuery(0x106341132?, {0x1400693aaa0?, 0x14000da7dc0?}, {0x0?, 0x1?, 0x0?})
        /Users/joechenrh/code/tidb-test/pkg/testkit/testkit.go:174 +0x78
github.com/pingcap/tidb/pkg/executor/test/tiflashtest.TestDisaggregatedTiFlashGeneratedColumn.func1(0x0)
        /Users/joechenrh/code/tidb-test/pkg/executor/test/tiflashtest/tiflash_test.go:1601 +0x2b4
github.com/pingcap/tidb/pkg/executor/test/tiflashtest.TestDisaggregatedTiFlashGeneratedColumn(0x1400193a9c0)
        /Users/joechenrh/code/tidb-test/pkg/executor/test/tiflashtest/tiflash_test.go:1668 +0x4f0
testing.tRunner(0x1400193a9c0, 0x10794df68)
        /Users/joechenrh/deps/go/src/testing/testing.go:1689 +0xec
created by testing.(*T).Run in goroutine 1
        /Users/joechenrh/deps/go/src/testing/testing.go:1742 +0x318
FAIL    github.com/pingcap/tidb/pkg/executor/test/tiflashtest   1.642s
```

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #55462

### What changed and how does it work?

As described in https://github.com/pingcap/tidb/issues/55462, the infoschema checker has found inconsistent with v1 and v2 in `TestDisaggregatedTiFlashGeneratedColumn`, thus throw a panic.

This is because the column info returned from `getOriginalPhysicalTableScan` is modifed here:

https://github.com/pingcap/tidb/blob/f73e3e34c5b39dcc7c7908cb7fdabd920fb5bf44/pkg/planner/core/find_best_task.go#L2461-L2467

As described in the comments, we should do this check in `ColumnToProto` to avoid `ColumnInfo` changes.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by fzzf678 — APPROVED** [review]

**Review by CbcWestwolf — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Comment by winoros** [comment]
>  if ts.StoreType == kv.TiFlash { 
>  	for _, col := range ts.Columns { 
>  		if col.IsVirtualGenerated() { 
>  			col.AddFlag(mysql.GeneratedColumnFlag) 
>  		} 
>  	} 
>  } 

image
This flag is the one only used in the execution phase and especially the MPP phase.
So we can move it to the phase converting plan to pb. Instead of adding a Clone method that affects all SQLs.\

And, changing ColumnInfo during plan phase is a dangerous operation. Don't do it.
image

**Comment by winoros** [comment]
```
// ColumnToProto converts model.ColumnInfo to tipb.ColumnInfo.
func ColumnToProto(c *model.ColumnInfo, forIndex bool) *tipb.ColumnInfo {
	pc := &tipb.ColumnInfo{
		ColumnId:  c.ID,
		Collation: collate.RewriteNewCollationIDIfNeeded(int32(mysql.CollationNames[c.GetCollate()])),
		ColumnLen: int32(c.GetFlen()),
		Decimal:   int32(c.GetDecimal()),
		Flag:      int32(c.GetFlag()),
		Elems:     c.GetElems(),
	}
	if forIndex {
		// Use array type for read the multi-valued index.
		pc.Tp = int32(c.FieldType.ArrayType().GetType())
		if c.FieldType.IsArray() {
			// Use "binary" collation for read the multi-valued index. Most of the time, the `Collation` of this hidden
			// column should already been set to "binary". However, in old versions, the collation is set to the default
			// value. See https://github.com/pingcap/tidb/issues/46717
			pc.Collation = int32(mysql.CollationNames["binary"])
		}
	} else {
		pc.Tp = int32(c.GetType())
	}
	return pc
}
```

You can do the same thing as the `forIndex`. You don't need to clone the `model.ColumnInfo`, you just need to fix it for the `tipb.ColumnInfo`.

**Pull request merged**
