### PR TITLE
expression: enable dayname/monthname function push down for tiflash

### LINKED ISSUE #32594: Support DayName/MonthName function push down for TiFlash

### PR DESCRIPTION
**Pull request by yibin87**
### What problem does this PR solve?

Issue Number: close #32594 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by windtalker — COMMENTED** [review]
Should add some ut for this.

**Comment by yibin87** [comment]
> Should add some ut for this.

UT added

**Review by ngaut — APPROVED** [review]
LGTM

**Comment by windtalker** [comment]
I suggest to squash the commits.

**Review by windtalker — APPROVED** [review]
LGTM

**Review by fzhedu — COMMENTED** [review]
please check whether the function is related to sql_mode?

**Comment by yibin87** [comment]
> please check whether the function is related to sql_mode?

Didn't find any sql mode related to these two functions. Their behaviors are controlled by lc_time_names variable. However, it is a read only variable in TiDB.

**Pull request merged**
