### PR TITLE
parser: use ExpressionListOpt for json functions.

### PR DESCRIPTION
**Pull request by coocood**
Keep the same as other built-in functions, so when wrong argument count is passed, 
`Incorrect parameter count` error will be returned instead of parser error.

### CODE REVIEW

**Comment by coocood** [comment]
@hsqlu @tiancaiamao PTAL

**Comment by shenli** [comment]
LGTM
@hicqu PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Comment by hicqu** [comment]
LGTM. @coocood , thanks for this.

**Pull request merged**
