### PR TITLE
expression: implement comparison between json opaque

### LINKED ISSUE #37315: The implementation of JSON Opaque compare is incorrect
I forgot to implement the comparison between json opaques :man_facepalming: . Any comparison between json opaque will cause panic.

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #37315

Problem Summary:

The comparison between json opaque is not implemented. They are currently comparing the `.GetString` of them, which will cause panic!

### What is changed and how it works?

Implement the json opaque through comparing the `.GetOpaque().Buf`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that comparison between json opaque will cause panic
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
LGTM

but please triage your issue in TiRelease, or just skip the triage of this PR.

**Review by xiongjiwei — APPROVED** [review]

**Pull request merged**
