### PR TITLE
planner: fix hash partition prune with `is null` condition

### LINKED ISSUE #58374: Query hash partition caused panic
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE IF NOT EXISTS `testPartition` (
    `OrderDate` DATETIME
) PARTITION BY HASH(
    YEAR(`OrderDate`) * 10000 + MONTH(`OrderDate`) * 100 + DAYOFMONTH(`OrderDate`)
) PARTITIONS 50;
insert into `testPartition` value (NULL);
select * from  `testPartition` where `OrderDate` is null;
```

### 2. What did you expect to see? (Required)

```sql
mysql> select * from  `testPartition` where `OrderDate` is null;
+-----------+
| OrderDate |
+-----------+
| NULL      |
+-----------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
select * from  `smartbimpp`.`testPartition` where `OrderDate` is null;
ERROR 1105 (HY000): runtime error: index out of range [2] with length 2
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
```
mysql> select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v8.5.0-alpha-356-gc8f3417f53-dirty
Edition: Community
Git Commit Hash: c8f3417f53f20b111157af979b4f20effdd5cff8
Git Branch: fix-42416
UTC Build Time: 2024-12-18 06:51:15
GoVersion: go1.23.4
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #58374

Problem Summary: Let codes in `getUsedHashPartitions` same as `getUsedKeyPartitions`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by mjonss — COMMENTED** [review]
If we de-duplicate the partition columns from the expression, we can improve the PR.

**Pull request merged**
