### PR TITLE
executor: migrate test-infra to testify for testRecoverTable

### LINKED ISSUE #33435: migrate test-infra to testify for executor_test.go testRecoverTable

### PR DESCRIPTION
**Pull request by tisonkun**
Issue Number: close #33435 

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
```
PANIC: executor_failpoint_test.go:265: testSerialSuite1.TestCollectCopRuntimeStats

[2022-04-07T01:59:24.531Z] 

[2022-04-07T01:59:24.531Z] ... Panic: testSerialSuite1.TestCollectCopRuntimeStats argument should be *check.C

[2022-04-07T01:59:24.531Z] OOPS: 0 passed, 1 PANICKED
```

**Comment by tisonkun** [comment]
@hawkingrei updated

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
