### PR TITLE
tests: make TestIndexLookupMergeJoinHang and TestIssue18068 stable (#23741)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23741 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23796
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23796:release-5.0-19919e3f3cf7
```

---

### What problem does this PR solve?

Problem Summary:

Failpoints **MUST** be used in the serial test suties.

https://github.com/pingcap/tidb/pull/19765

### What is changed and how it works?

NA

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

NA

### Release note 

- No release note

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
LGTM

**Review by lzmhhh123 — APPROVED** [review]

**Comment by bb7133** [comment]
Please resolve the conflicts @tangenta

**Pull request merged**
