### PR TITLE
test: cleanup mocktikv usage

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?

`mocktikv` is moving to an internal package. There is a new reference of mocktikv after https://github.com/pingcap/tidb/pull/25911

### What is changed and how it works?

use testutils package instead.

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Comment by tiancaiamao** [comment]
CI is failing... is the change related?

**Comment by disksing** [comment]
> CI is failing... is the change related?

the session test is failed. Should be irrelevant.

**Review by tiancaiamao — APPROVED** [review]

**Review by AndreMouche — APPROVED** [review]
LGTM

**Pull request merged**
