### PR TITLE
table: clean up useless code

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
Clean up some useless code in package table.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by siddontang** [comment]
do we have other useless codes?

**Comment by jackysp** [comment]
> do we have other useless codes?

Maybe.

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
