### PR TITLE
session: fix the txn.Size() function for TxnState

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

```
begin;
insert into t values (1);
insert into t values (1);
insert into t values (1);

txn.Size() is still 0
```

### What is changed and how it works?

TxnState implements the kv.Transaction, its `Size()` function should
consider the cached transaction data.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @coocood @jackyu

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
I see https://github.com/pingcap/tidb/issues/14777 a thousand times!

/rebuild

**Pull request merged**
