### PR TITLE
table partition: add test for exchange partition

### LINKED ISSUE #35996: table partition: exchange partition with table enhance
## Enhancement

The current  exchange partition with table design can cause bugs when DDL and DML are executed concurrently.

### PR DESCRIPTION
**Pull request by ymkzpx**
### What problem does this PR solve?

Issue Number: close #35996

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None.
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by mjonss — APPROVED** [review]
LGTM

**Comment by hawkingrei** [comment]
@ymkzpx Please fix your test.

```
TestAlterTableExchangePartition
```

**Comment by mjonss** [comment]
@ymkzpx please update the test with the correct error (1733? instead of 1146) :)

**Comment by ymkzpx** [comment]
@ymkzpx test

**Comment by ymkzpx** [comment]
@ymkzpx test

**Comment by Kzpx** [comment]
@ymkzpx test

**Comment by Kzpx** [comment]
@ymkzpx test

**Pull request merged**
