### PR TITLE
executor: fix window function when order by item contain NULL

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve? 

NULL cannot get compare func then panicked.

### What is changed and how it works?

Filter NULL out.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by winoros** [comment]
For normal sort, the order-by items are pruned during column pruning. But it's not very suitable for window function.
If we do this in planner when we do this is better? during plan building?

**Comment by lamxTyler** [comment]
@winoros What do you mean by `pruned`? Could you give an example? I tried and there is still `OrderBy` in the `PhysicalWindow`.

**Comment by winoros** [comment]
@lamxTyler Normal sort here i mean the `ORDER BY` clause without window function.
If you run `select * from t order by NULL, a`. The `NULL` is pruned in column pruning.

**Comment by lamxTyler** [comment]
@winoros Feels like it is should not be pruned. In MySQL,
```sql
MySQL [test]> select sum(a) over(order by 1 range between 1 preceding and 1 following) from t;
ERROR 3592 (HY000): Window '<unnamed window>': ORDER BY or PARTITION BY uses legacy position indication which is not supported, use expression.
MySQL [test]> select sum(a) over(order by null range between 1 preceding and 1 following) from t;
ERROR 3587 (HY000): Window '<unnamed window>' with RANGE N PRECEDING/FOLLOWING frame requires exactly one ORDER BY expression, of numeric or temporal type
MySQL [test]> select sum(a) over(order by 1.0 range between 1 preceding and 1 following) from t;
+---------------------------------------------------------------------+
| sum(a) over(order by 1.0 range between 1 preceding and 1 following) |
+---------------------------------------------------------------------+
|                                                                   6 |
|                                                                   6 |
|                                                                   6 |
|                                                                   6 |
+---------------------------------------------------------------------+
4 rows in set (0.002 sec)
```

Sometimes we need it in the execution phase, and sometimes it is not allowed.

**Comment by winoros** [comment]
@lamxTyler The failed-to-run cases you mentioned should be checked in `buildWindowFunctionFrameBound`. This pr doesn't break the rules?

**Comment by lamxTyler** [comment]
@winoros Yes, never mind.

**Pull request merged**
