### PR TITLE
statistics: fix panic when move analyze jobs to history

### PR DESCRIPTION
**Pull request by lamxTyler**
### What problem does this PR solve? 

Fix https://github.com/pingcap/tidb/issues/10280

### What is changed and how it works?

We should check the length of history jobs, not normal jobs.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

 - None

Related changes

 - None

### CODE REVIEW

**Comment by shenli** [comment]
Should we cherry-pick this to the release-2.1?

**Comment by lamxTyler** [comment]
@shenli No, because release-2.1 does not support analyze jobs.

**Pull request merged**
