### PR TITLE
*: enable nogo to use fast incremental linter

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: ref #35345

Problem Summary:

### What is changed and how it works?

We spend [too much time](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check/detail/tidb_ghpr_check/66772/pipeline/77) on the linter. we can use a fast incremental linter by enabling nogo to save time. It uses bazel's remote cache to check the code linter when the code has been changed.

First we use Bazel nogo to replace with govet

### Check List

Tests 

- [x] Unit test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
Is there a report comparing govet and nogo? It can be a non-trivial change and I'd assume there is a discussion about such toolchain switch.

cc @tiancaiamao @bb7133 @tangenta (IIRC there is an ongoing #28720)

We can discussion at the issue first, see also https://github.com/pingcap/tidb/issues/35345#issuecomment-1156214788.

**Comment by hawkingrei** [comment]
> Is there a report comparing govet and nogo? It can be a non-trivial change and I'd assume there is a discussion about such toolchain switch.
> 
> cc @tiancaiamao @bb7133 @tangenta (IIRC there is an ongoing #28720)
> 
> We can discussion at the issue first, see also [#35345 (comment)](https://github.com/pingcap/tidb/issues/35345#issuecomment-1156214788).

they are the same thing. they use the ```golang.org/x/tools/go/analysis/passes``` to implement the ```vet```. They can different how to run the vet. ```govet``` is a command tool so that it cannot cache it and skip it when you meet it against and bazel nogo can do it

**Review by tangenta — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
