### PR TITLE
ranger: handle decimal overflow properly when building index ranges

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23483

Problem Summary:

Planner reports error for a query.

### What is changed and how it works?

What's Changed: Ignore the overflow error for decimal type in ranger.

How it Works: `zeroMyDecimal` would be returned if overflow error occurs, so `convertPoint` would adjust the `excl` of the boundary accordingly, and impossible ranges would be removed by consequent `validIntervals()`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- Handle decimal overflow properly when building index ranges

### CODE REVIEW

**Review by time-and-fate — APPROVED** [review]
/lgtm

**Comment by time-and-fate** [comment]
btw the error message `DECIMAL value is out of range in '(10, 0)'` is a little strange.:sweat_smile:

**Review by winoros — APPROVED** [review]

**Pull request merged**
