### PR TITLE
executor: split hashjoin into workers(part2)

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve?

Issue Number: refer https://github.com/pingcap/tidb/issues/39061

Problem Summary:

### What is changed and how it works?
Modify the `probeWorker` attribute to `[]probeWorker`.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
```
executor/benchmark_test.go:935:4: e.probeWorker undefined (type *HashJoinExec has no field or method probeWorker)

executor/benchmark_test.go:937:5: e.probeWorker undefined (type *HashJoinExec has no field or method probeWorker)

```

**Review by wshwsh12 — APPROVED** [review]
Please fix the CI. Rest LGTM

**Review by guo-shaoge — APPROVED** [review]

**Pull request merged**
