### PR TITLE
planner: update generated column inside a transaction should return error (#8909)

### PR DESCRIPTION
**Pull request by zz-jason**
cherry pick #8909 to release-2.1

### CODE REVIEW

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 pd-release-2.1 tikv=release-2.1

**Comment by eurekaka** [comment]
@zz-jason CI failed, PTAL

**Comment by zz-jason** [comment]
@eurekaka CI is fixed. PTAL, thanks

**Comment by eurekaka** [comment]
/run-all-tests tidb-test=release-2.1 pd-release-2.1 tikv=release-2.1

**Comment by zz-jason** [comment]
😂

**Pull request merged**
