### PR TITLE
executor: Lower the log level from info to debug for index merge reader

### LINKED ISSUE #41949: too much logs about `[index_merge_reader.go:791] ["worker finish without panic"]`
## Enhancement

```
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:791] ["worker finish without panic"] [worker=IndexMergeProcessWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:791] ["worker finish without panic"] [worker=IndexMergeProcessWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:791] ["worker finish without panic"] [worker=IndexMergePartialIndexWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:791] ["worker finish without panic"] [worker=IndexMergeProcessWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.066 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:791] ["worker finish without panic"] [worker=IndexMergePartialIndexWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:791] ["worker finish without panic"] [worker=IndexMergeProcessWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:791] ["worker finish without panic"] [worker=IndexMergePartialIndexWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:791] ["worker finish without panic"] [worker=IndexMergePartialIndexWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:791] ["worker finish without panic"] [worker=IndexMergePartialIndexWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:791] ["worker finish without panic"] [worker=IndexMergeProcessWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:791] ["worker finish without panic"] [worker=IndexMergeProcessWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:1343] ["worker finish without panic"] [worker=IndexMergeTableScanWorker]
[2023/03/06 03:44:16.610 +00:00] [INFO] [index_merge_reader.go:791] ["worker finish without panic"] [worker=IndexMergeProcessWorker]
```

### PR DESCRIPTION
**Pull request by yibin87**
### What problem does this PR solve?

Issue Number: close #41949 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]

**Comment by dveeden** [comment]
The checklist in the PR description says there is a unit test, but I don't see any. I think this is only tested manually, which I think is ok for this PR.

**Pull request merged**
