### PR TITLE
privilege: add drop_priv check when truncate table

### PR DESCRIPTION
**Pull request by winkyao**
### What problem does this PR solve? 

Before this PR, TiDB user truncate table only needs delete_priv. After this PR, needs drop_priv. To be consistent with MySQL. https://dev.mysql.com/doc/refman/5.7/en/privileges-provided.html#priv_drop

### What is changed and how it works?

Add drop_priv to the visitInfo in the plan builder.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### CODE REVIEW

**Comment by winkyao** [comment]
@tiancaiamao PTAL

**Comment by winkyao** [comment]
@xiekeyi98 PTAL

**Comment by winkyao** [comment]
@xiekeyi98 Done.

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
