### PR TITLE
go.mod: update PD to fix the flag issue (#27337)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #27337 to release-5.2
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/27338
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/27338:release-5.2-6a1b9fe34286
```

---

Signed-off-by: you06 <you1474600@gmail.com>

### What problem does this PR solve?

Issue Number: #27156

Problem Summary:  now PD imports [check](https://github.com/pingcap/check) package in some un-test packages, when TiDB imports them, TiDB will inherit some flags from check package. After this, `check.v` flag enables the unstable feature in production mode.

### What is changed and how it works?

This PR upgrade PD and import from PD no more introduce flags from check package.

What's Changed:

Update PD to the latest master, this removes flag pollution which will ship unstable features to the production environment. 

How it Works:

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by you06** [comment]
@bb7133 @crazycs520 PTAL this.

**Review by bb7133 — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Pull request merged**
