### PR TITLE
ddl: quickly process the next job after processing the cancelled DDL job

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

When the owner and the receiving DDL TiDB are on the same TiDB, quickly process the next job after processing the canceled DDL job.

### What is changed and how it works?

- When the DDL job is "JobStateRollbackDone", we notify the receiving DDL TiDB to process the finished job.

- Add a log after the DDL JOB fails.

What's Changed:

How it Works:

This optimization also enables faster testing.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

This optimization also enables faster testing.

Before this PR:
Executing `go test` takes **196.455s** in the DDL package.

After this PR:
Executing `go test` takes **134.877s** in the DDL package.

### Release note 

- When the owner and the receiving DDL TiDB are on the same TiDB, quickly process the next job after processing the canceled DDL job.

### CODE REVIEW

**Comment by xhebox** [comment]
> ddl.go:L576 // If a job is a history job, the state must be JobStateSynced or JobStateRollbackDone or JobStateCancelled.

I believe the behavior is correct.

/lgtm

**Comment by zimulala** [comment]
PTAL @AilinKid

**Pull request merged**
