### PR TITLE
executor: support table partition in show create table stmt

### PR DESCRIPTION
**Pull request by zhexuany**
support table partition in show create table statement.

### CODE REVIEW

**Comment by zhexuany** [comment]
Regarding of range partition, some syntax is not yet supported. Further change will be made later.

**Comment by zhexuany** [comment]
@coocood @ciscoxll PTAL

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Comment by jackysp** [comment]
I think the create partition syntax is wrong with max value. @zhexuany @coocood

**Comment by coocood** [comment]
@jackysp 
It can be executed in MySQL.

**Pull request merged**
