### PR TITLE
*: Fix select lock option for union statement

### PR DESCRIPTION
**Pull request by tiancaiamao**
In "A union B for update", "for update" belongs to union statement, so both A
and B should use it.

Update this one https://github.com/pingcap/tidb/pull/6335

@coocood @zz-jason @shenli

### CODE REVIEW

**Comment by shenli** [comment]
Is this the same behaviour with MySQL?

**Comment by spongedu** [comment]
@shenli @tiancaiamao 
I think the solution here is not the same with MySQL. I test these cases in MySQL 5.7.
In MySQL:
First, execute this in the first tx: 
```sql
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from t  union select * from t2 for update;
+----+----+---------+
| id | tn | type    |
+----+----+---------+
|  1 |  5 | cat     |
|  2 |  6 | dog     |
|  3 |  7 | duck    |
|  4 | 29 | chicken |
|  4 | 99 | chicken |
+----+----+---------+
5 rows in set (0.01 sec)
```

Then, execute this in the second tx:
```sql
mysql> update t  set tn = 31 where id = 4;                                                                                                     Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> update t2  set tn = 31 where id = 4;
ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction
```
**the `FOR UPDATE` statement here affect only the second `SelectStmt`.**

Another condition:
First, execute this in the first tx: 
```sql
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from t  union select * from t2 limit 100  for update;                                                                          +----+-----+---------+
| id | tn  | type    |
+----+-----+---------+
|  1 |   5 | cat     |
|  2 |   6 | dog     |
|  3 |   7 | duck    |
|  4 | 187 | chicken |
+----+-----+---------+
4 rows in set (0.01 sec)
```

Then, execute this in the second tx:
```sql
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> update t2 set tn = 1 where id = 1;                                                                                                      Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> update t set tn = 1 where id = 1;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```
**Both Update works. The `FOR UPDATE` statement here seems work on neither `SelectStmt`**

I think the difference between TiDB and MySQL on transaction isolation don't affect the effect scope of `SelectLock` here.

**Comment by tiancaiamao** [comment]
I test on MySQL

```
mysql> select version();
+------------+
| version()  |
+------------+
| 5.6.34-log |
+------------+
1 row in set (0.00 sec)
```

and find

```
select * from t  union select * from t2 for update;
select * from t  union select * from t2 limit 100  for update; 
```

In both of them, FOR UPDATE statement affect  the second SelectStmt. @spongedu

**Comment by tiancaiamao** [comment]
From MySQL:
https://github.com/mysql/mysql-server/blob/4f1d7cf5fcb11a3f84cff27e37100d7295e7d5ca/sql/parse_tree_nodes.h#L1892

> It's not possible to express the difference between
>       (SELECT ... UNION SELECT ...) ORDER BY ... LIMIT ...
>       and
>       SELECT ... UNION (SELECT ... ORDER BY ... LIMIT ...)

This function adjust order by and limit, using a `is_union()` flag, but it seems that select lock option is not considered in the function.
So, we can view the `for update` belongs to the second select statement.
I'll update it.

**Comment by spongedu** [comment]
@tiancaiamao  I don't have a `MySQL 5.6.34-log` instance at hand, but I test in another `5.6` MySQL.
```sql
mysql> select version();
+-----------+
| version() |
+-----------+
| 5.6.40    |
+-----------+
1 row in set (0.00 sec)
```
The result is as your described, `FOR UPDATE` statement affect the second SelectStmt .  I repeat this again in 5.7, and `FOR UPDATE` don't work, as I test before.  You can take an experiment as well. 
It's interesting that the behavior is different between `MySQL 5.6` and `MySQL 5.7`.  Since TiDB consists with `MySQL 5.7`'s behavior in most case,  I think we'd better do the same here. What do you think? @tiancaiamao @shenli

**Comment by spongedu** [comment]
@coocood agree

**Comment by shenli** [comment]
@tiancaiamao Please address the comments and resolve the conflicts.

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
PTAL @shenli

**Pull request merged**
