### PR TITLE
*: remove the assertion proto

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

The assertion proto was introduced to verify the data consistancy, but I find
it's complex and hard to achieve that goal. Adding additional assertions just
makes more memory occupation, especially in the large transaction.
So it's better to remove it.

### What is changed and how it works?

Remove code.

Some of the codes are kept because the pessimistic lock protocol is still using them.
Such as here https://github.com/pingcap/tidb/blob/c719de710b57b255fe887f70b61a23277d33a83e/store/tikv/2pc.go#L656
and part of the mocktikv codes.

### Check List 

Tests 

 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @coocood @jackysp

**Comment by coocood** [comment]
LGTM

**Pull request merged**
