### PR TITLE
session: add a benchmark test for issue 27633

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

What's Changed:

The plan builder seems to be slow, I write a benchmark for it.
See https://github.com/pingcap/tidb/issues/27633

How it Works:

Add a benchmark function.

```
cd session;
go test -run TestXXX -bench BenchmarkCompileExecutePreparedStmt -cpuprofile cpu.out -benchmem -benchtime 30s
go tool pprof -lines=1 -http=:6060 cpu.out
```

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Comment by tisonkun** [comment]
@tiancaiamao can you log a baseline of this bench in the PR description?

Also I'm unsure whether golang supports spotting perf regression automatically.

**Comment by tiancaiamao** [comment]
> @tiancaiamao can you log a baseline of this bench in the PR description?
> 
> Also I'm unsure whether golang supports spotting perf regression automatically.

We run the benchmark test in the list [here](https://github.com/pingcap/tidb/pull/27640/files#diff-3fc2c686f9f40a65dd432449b3ecdd8dce85afc1f0c6088b09ed4a64eb905de0L1752-L1776) daily, and collect the result [here](https://perf.pingcap.com/d/MeR8a6jMz/nightly-branch-performance-monitor?viewPanel=10&orgId=1) and [here](http://www.zenlife.tk:18081/)   @tisonkun

**Comment by tisonkun** [comment]
@tiancaiamao thanks for your information! It seems the list link wrong? I don't see a list of bench cases but file diff of this PR.

**Comment by tiancaiamao** [comment]
> @tiancaiamao thanks for your information! It seems the list link wrong? I don't see a list of bench cases but file diff of this PR.

https://github.com/pingcap/tidb/blob/c22605b3502273261cf8430e3a0b75eb5201c24d/session/bench_test.go#L1864-L1888

**Review by ichn-hu — APPROVED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]
LGTM

**Pull request merged**
