### PR TITLE
*: use go-deadlock to check mutex usages

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: ref #33847

Problem Summary:

https://github.com/sasha-s/go-deadlock is an awesome tool to detect deadlock usage. This PR substitutes `sync.Mutex` with `deadlock.Mutex` in the build for the unit test.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by bb7133** [comment]
It looks not easy to adopt it, please check the failed CI:

https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_build/detail/tidb_ghpr_build/58357/pipeline
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check/detail/tidb_ghpr_check/60313/pipeline
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/46546/pipeline

**Comment by tangenta** [comment]
@bb7133 I found that "RWMutex" can be replaced as well. The global replace does not work correctly... Let me fix it.

**Pull request closed without merging**
