### PR TITLE
store: fix SetOption race error

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: Song Gao <disxiaofei@163.com>

### What problem does this PR solve?

ref https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_unit_test/runs/67016/nodes/86/steps/347/log/?start=0

### Release note 

* No release note

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Comment by hi-rustin** [comment]
> /merge

If the CI test fails, you just re-trigger the test that failed and the bot will merge the PR for you after the CI passes.

**Pull request merged**
