### PR TITLE
telemetry: remove the codes of Telemetry

### LINKED ISSUE #49939: RFC: remove all codes of telemetry
## Enhancement

After #41336, PingCAP(the company behind TiDB) stopped collecting telemetry data from all running clusters, and I don't think any other organization or user is using this feature. So IMHO it's time to clean up all the codes and turn `EnableTelemetry` to a deprecated configuration(configurable but never work).

What do we get from it:
* A (slightly) higher overall code coverage, the code coverage of `telemetry` pkg is only [42%](https://app.codecov.io/gh/pingcap/tidb/tree/master/pkg).
* Easier maintenance of the codebase, for there'll be fewer codes.

If you have any concerns about this, feel free to leave your comments in this issue.

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve?

Issue Number: close #49939 

Problem Summary:

### What changed and how does it work?

As is described.

Configuration '[enable-telemetry](https://docs.pingcap.com/tidb/stable/tidb-configuration-file#enable-telemetry-new-in-v402)' and the system variable '[tidb_enable_telemetry](https://docs.pingcap.com/tidb/stable/system-variables#tidb_enable_telemetry-new-in-v402)' are kept for compatibility consideration, but they're both deprecated after this PR: the values of them are meanningless. 

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [x] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [x] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Deprecate Telemetry for TiDB:
* Deprecate configuration '[enable-telemetry](https://docs.pingcap.com/tidb/stable/tidb-configuration-file#enable-telemetry-new-in-v402)' and the system variable '[tidb_enable_telemetry](https://docs.pingcap.com/tidb/stable/system-variables#tidb_enable_telemetry-new-in-v402)': the values of them are meaningless now.
* Remove all SQL syntax of Telemetry, including `ADMIN SHOW TELEMETRY` and `ADMIN RESET TELEMETRY_ID`.
* Remove `TELEMETRY` and `TELEMETRY_ID` from TiDB unreserved keywords list.
```

### CODE REVIEW

**Review by ngaut — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by lance6716 — COMMENTED** [review]
/approve

for lightning and domain

**Review by zimulala — APPROVED** [review]

**Review by BornChanger — APPROVED** [review]
br part lgtm

**Comment by wuhuizuo** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: _[Benjamin2037](https://github.com/pingcap/tidb/pull/51202#pullrequestreview-1894788473)_, _[BornChanger](https://github.com/pingcap/tidb/pull/51202#pullrequestreview-1894806120)_, _[lance6716](https://github.com/pingcap/tidb/pull/51202#pullrequestreview-1894791603)_, _[ngaut](https://github.com/pingcap/tidb/pull/51202#pullrequestreview-1894511372)_, _[windtalker](https://github.com/pingcap/tidb/pull/51202#pullrequestreview-1894785559)_, _[zimulala](https://github.com/pingcap/tidb/pull/51202#pullrequestreview-1894797899)_ **Once this PR has been reviewed and has the lgtm label**, please assign [d3hunter](https://github.com/d3hunter), [easonn7](https://github.com/easonn7) for approval. For more information see [the Kubernetes Code Review Process](https://book.prow.tidb.net/#/workflows/pr).
> 
> The full list of commands accepted by this bot can be found [here](https://prow.tidb.net/command-help?repo=pingcap%2Ftidb).
> 
> Needs approval from an approver in each of these files:
> * ~[OWNERS](https://github.com/pingcap/tidb/blob/master/OWNERS)~ [Benjamin2037,lance6716,ngaut,windtalker,zimulala]
> * ~[br/pkg/lightning/OWNERS](https://github.com/pingcap/tidb/blob/master/br/pkg/lightning/OWNERS)~ [Benjamin2037,lance6716]
> * **[pkg/config/OWNERS](https://github.com/pingcap/tidb/blob/master/pkg/config/OWNERS)**
> * ~[pkg/ddl/OWNERS](https://github.com/pingcap/tidb/blob/master/pkg/ddl/OWNERS)~ [Benjamin2037,zimulala]
> * ~[pkg/distsql/OWNERS](https://github.com/pingcap/tidb/blob/master/pkg/distsql/OWNERS)~ [Benjamin2037,windtalker]
> * ~[pkg/domain/OWNERS](https://github.com/pingcap/tidb/blob/master/pkg/domain/OWNERS)~ [lance6716,zimulala]
> * ~[pkg/expression/OWNERS](https://github.com/pingcap/tidb/blob/master/pkg/expression/OWNERS)~ [windtalker]
> * **[pkg/parser/OWNERS](https://github.com/pingcap/tidb/blob/master/pkg/parser/OWNERS)** [BornChanger]
>   > Need more approvers for rest parts.
> * **[pkg/sessionctx/variable/OWNERS](https://github.com/pingcap/tidb/blob/master/pkg/sessionctx/variable/OWNERS)**
> 
> Approvers can indicate their approval by writing `/approve` in a comment Approvers can cancel approval by writing `/approve cancel` in a comment

@bb7133 rest parts need be approved by [d3hunter](https://github.com/d3hunter) and [easonn7](https://github.com/easonn7)

**Pull request merged**
