### PR TITLE
executor, statistics: fix unstable `TestAnalyzeIndexExtractTopN`

### PR DESCRIPTION
**Pull request by rebelice**
### What problem does this PR solve?

Issue Number: part of #23967 

Problem Summary:

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Comment by qw4990** [comment]
Please resolve conflicts.

**Comment by hawkingrei** [comment]
I think it can be closed.

**Pull request closed without merging**
