### PR TITLE
tunning connection between tikv and tidb

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>

### What problem does this PR solve? 

When the connection between TiKV and TiDB is not large enough, there may be a flow skew issue in 
 TiKV. This problem happens when most of the data flow is handled by TiKV's one gRPC thread.

### What is changed and how it works?

Enlarge the connection between TiKV and TiDB.

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
@disksing @hicqu @BusyJay PTAL

**Comment by disksing** [comment]
Consider a cluster with 100 tikv nodes, each TiDB instance will establish 12800 connections. That looks too many.

**Comment by zz-jason** [comment]
@zhangjinpeng1987 friendly ping, any update?

**Comment by zz-jason** [comment]
Close due to outdated, fell free to reopen it once this PR is needed again in the future.

**Pull request closed without merging**
