### PR TITLE
 github,makefile: move license check into check_dev Jenkins job

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

None

Problem Summary:

### What is changed and how it works?

Moving to the check-dev Jenkins job, we got fed up with the GitHub actions queue.

### Check List

Tests 

- [x] No code

Side effects

None

Documentation

None

### Release note

```release-note
None
```

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Comment by hi-rustin** [comment]
/hold

We have a better solution.

**Comment by hi-rustin** [comment]
/unhold

It works: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check/detail/tidb_ghpr_check/34465/

**Comment by kennytm** [comment]
/lgtm cancel

i don't think this works, "check-license" is a Required pass.

**Comment by hi-rustin** [comment]
check_dev was required.

We need to adjust bot's config before we merge it.

You can review it.

**Comment by hi-rustin** [comment]
/hold

Waiting for https://github.com/ti-community-infra/configs/pull/464 landed.

**Comment by hi-rustin** [comment]
> /lgtm cancel
> 

This command was deprecated a long time ago and you need to request changes for it to take effect.

**Comment by hi-rustin** [comment]
/cc @tisonkun @xhebox 

Could you please take a look? Thanks!

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
@hi-rustin required `check-license` should be adjust. And previous release branches should be take care of also,

**Comment by hi-rustin** [comment]
> @hi-rustin required `check-license` should be adjust. And previous release branches should be take care of also,

It looks like the release branch needs to be skipped, let's close it for now. I'll try again when I have time to work on it.

**Comment by hi-rustin** [comment]
Thanks for your review!  💚 💙 💜 💛 ❤️

**Comment by kennytm** [comment]
@hi-rustin 

1. if the command is not working you should take it out of https://prow.tidb.io/command-help#lgtm
2. the proper way to cancel the approval or request-change should be "Dismiss Review", yet ti-chi-bot ignores it last time I checked

1-fs8

**Pull request closed without merging**
