### PR TITLE
*: add trace support for subquery (#11182)

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry-pick https://github.com/pingcap/tidb/pull/11182

This is a refactor(kind of) rather than a bug fix, but we'd better cherry-pick it to reduce further cherry-pick conflicts.

### CODE REVIEW

**Comment by jackysp** [comment]
Please resolve the conflicts.

**Comment by jackysp** [comment]
PTAL @lysu @coocood

**Comment by coocood** [comment]
LGTM

**Comment by zz-jason** [comment]
@tiancaiamao Please resolve the conflicts.

**Comment by tiancaiamao** [comment]
Done @zz-jason

**Comment by zz-jason** [comment]
conflicted again ..

**Pull request merged**
