### PR TITLE
expression: fix abs push down sign bug (#8622)

### PR DESCRIPTION
**Pull request by lysu**
cherry-pick #8622 to 2.1

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8628)

### CODE REVIEW

**Comment by lysu** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
Can we use tidb-test master? some script in tidb-test not cherry-pick to release2.1 now

**Comment by lysu** [comment]
@zhouqiang-cl run tidb-test@master with 2.1/2.0 branch code maybe cannot pass all testcase

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
LGTM

**Comment by zz-jason** [comment]
@XuHuaiyu @eurekaka PTAL

**Comment by zz-jason** [comment]
@zhouqiang-cl Seems the CI script is not correct:
```

2s
+ curl --output /dev/null --silent --head --fail http://172.16.30.25/download/builds/pingcap/tidb-test/422f0e12210746b6fd4a5e48215ca096db35881a/centos7/tidb-test.tar.gz

+ curl http://172.16.30.25/download/builds/pingcap/tidb-test/422f0e12210746b6fd4a5e48215ca096db35881a/centos7/tidb-test.tar.gz

+ tar xz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed


  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 9829k  100 9829k    0     0  19.9M      0 --:--:-- --:--:-- --:--:-- 19.9M

+ mkdir -p /go/pkg/mod

+ mkdir -p /home/jenkins/workspace/tidb_ghpr_common_test/go/pkg

+ ln -sT /go/pkg/mod /home/jenkins/workspace/tidb_ghpr_common_test/go/pkg/mod

+ cd tidb_test

+ GOPATH=/home/jenkins/workspace/tidb_ghpr_common_test/go

+ ./build.sh

/home/jenkins/workspace/tidb_ghpr_common_test/go/src/github.com/pingcap/tidb-test@tmp/durable-0ac97380/script.sh: line 5: ./build.sh: No such file or directory

+ cd mysql_test

/home/jenkins/workspace/tidb_ghpr_common_test/go/src/github.com/pingcap/tidb-test@tmp/durable-0ac97380/script.sh: line 6: cd: mysql_test: No such file or directory

+ cd randgen-test

/home/jenkins/workspace/tidb_ghpr_common_test/go/src/github.com/pingcap/tidb-test@tmp/durable-0ac97380/script.sh: line 7: cd: randgen-test: No such file or directory

+ cd analyze_test

/home/jenkins/workspace/tidb_ghpr_common_test/go/src/github.com/pingcap/tidb-test@tmp/durable-0ac97380/script.sh: line 8: cd: analyze_test: No such file or directory

script returned exit code 1
```
PTAL

**Comment by zz-jason** [comment]
> Can we use tidb-test master? some script in tidb-test not cherry-pick to release2.1 now

@zhouqiang-cl We can't. `tidb` 2.1 have to run the test of `tidb-test` 2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
