### PR TITLE
br/pkg/storage: migrate test-infra to testify

### LINKED ISSUE #28179: migrate test-infra to testify for `br/pkg/storage`

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #28179.

Signed-off-by: tison <wander4096@gmail.com>

```release-note
None
```

/cc @3pointer @kennytm

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
@tangenta PTAL

**Review by tangenta — APPROVED** [review]

**Pull request merged**
