### PR TITLE
ddl: add ddl_reorg_batch_size variable to control ddl worker batch ze and enlarge default batch size. (#8365)

### PR DESCRIPTION
**Pull request by crazycs520**
cherry-pick #8365

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8614)

### CODE REVIEW

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by crazycs520** [comment]
/run-integration-ddl-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-integration-ddl-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by crazycs520** [comment]
/run-integration-ddl-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
