### PR TITLE
sessionctx/variable, ddl: fix sysvar API usage

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/35051

Problem Summary:

This fixes all but one occurence where global-only variables were being loaded into the session. This was a historical feature, and predates when sysvar cache existed, and generally the system variable compatibility was much lower.

It does not fix one occurence: `TiDBRowFormatVersion`. This case is slightly more tricky and should be solved separately.

### What is changed and how it works?

Several global-only system variables were previously loaded into new sessions and cached. They now behave more compatible with MySQL and remain in global scope.

### Check List

Tests 

- [x] Unit test (existing tests)
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Several global-only system variables were previously loaded into new sessions and cached. They now behave more compatible with MySQL and remain in global scope.
```

### CODE REVIEW

**Comment by morgo** [comment]
@CbcWestwolf PTAL and let me know what you think too :-)

**Comment by CbcWestwolf** [comment]
> @CbcWestwolf PTAL and let me know what you think too :-)

Thank you!
According to the implementation of `func (sv *SysVar) SkipInit()`, it seems that the declarations of `skipInit: true` are not more needed for only-global-scope or instance-scope sysvars in `sysvar.go`. Would you like to remove them in these PRs?

**Comment by morgo** [comment]
> Would you like to remove them in these PRs?

Yes. I plan to work on that next. There are only some very limited cases where it is absolutely required.

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by bb7133 — COMMENTED** [review]
PTAL @tangenta @Defined2014 , this change is slightly related to the ongoing 'multiple schema change' project.

**Review by Defined2014 — APPROVED** [review]

**Pull request merged**
