### PR TITLE
store/tikv: do not send batch commands to tiflash

### PR DESCRIPTION
**Pull request by hanfei1991**
### What problem does this PR solve?

Problem Summary:

After set @@global.tidb_allow_batch_cop = true and send query to tiflash; Sometimes it will report TiKV server timeout error. Observing the tidb log, it has many ["receive a grpc cancel signal from remote"] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"].

It's because client_batch.go will recycle "idle" connection, but TiFlash request does not use client_batch request, its connection is deleted by mistake.

What's Changed:

After discussion, we decide not to send batch commands to tiflash

Tests 

- Manual test 

Side effects

This is not a important feature fot tiflash, so it has no side effects

### Release note 
- Do not send batch commands to tiflash, to fix unpredictable timeout for tiflash engine.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM

**Comment by jebter** [comment]
@zz-jason PTAL

**Comment by zz-jason** [comment]
@hanfei1991 do we need to cherry-pick this PR to release 4.0?

**Comment by hanfei1991** [comment]
@zz-jason yeah, we need to cherry-pick, but I don't have authority to add label now :P

**Comment by hanfei1991** [comment]
@zz-jason We don't have any mock tiflash engine, it's not easy to add tests.

**Comment by hanfei1991** [comment]
tidb repo

**Pull request merged**
