### PR TITLE
br,test: fix data race for parquet test

### LINKED ISSUE #27473: data race in `br/pkg/lightning/mydump.setDatumByInt()`
## Bug Report

Please answer these questions before submitting your issue. Thanks!
```
[2021-08-23T01:47:18.489Z] WARNING: DATA RACE
[2021-08-23T01:47:18.489Z] Read at 0x000005e1e900 by goroutine 63:
[2021-08-23T01:47:18.489Z]   time.Now()
[2021-08-23T01:47:18.489Z]       /usr/local/go/src/time/time.go:1073 +0xf6
[2021-08-23T01:47:18.489Z]   time.sendTime()
[2021-08-23T01:47:18.489Z]       /usr/local/go/src/time/sleep.go:149 +0x49
[2021-08-23T01:47:18.490Z] 
[2021-08-23T01:47:18.490Z] Previous write at 0x000005e1e900 by goroutine 70:
[2021-08-23T01:47:18.490Z]   ??()
[2021-08-23T01:47:18.490Z]       -:0 +0xffffffffffffffff
[2021-08-23T01:47:18.490Z]   fmt.(*pp).fmtInteger()
[2021-08-23T01:47:18.490Z]       /usr/local/go/src/fmt/print.go:379 +0x20d
[2021-08-23T01:47:18.490Z]   fmt.(*pp).printArg()
[2021-08-23T01:47:18.490Z]       /usr/local/go/src/fmt/print.go:680 +0x96f
[2021-08-23T01:47:18.490Z]   fmt.(*pp).doPrintf()
[2021-08-23T01:47:18.490Z]       /usr/local/go/src/fmt/print.go:1122 +0x9f7
[2021-08-23T01:47:18.490Z]   fmt.Sprintf()
[2021-08-23T01:47:18.490Z]       /usr/local/go/src/fmt/print.go:219 +0x73
[2021-08-23T01:47:18.490Z]   github.com/pingcap/tidb/br/pkg/lightning/mydump.setDatumByInt()
[2021-08-23T01:47:18.490Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/br/pkg/lightning/mydump/parquet_parser.go:489 +0x1cd
[2021-08-23T01:47:18.490Z]   github.com/pingcap/tidb/br/pkg/lightning/mydump.setDatumValue()
[2021-08-23T01:47:18.490Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/br/pkg/lightning/mydump/parquet_parser.go:411 +0x1da
[2021-08-23T01:47:18.490Z]   github.com/pingcap/tidb/br/pkg/lightning/mydump.(*ParquetParser).ReadRow()
[2021-08-23T01:47:18.490Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/br/pkg/lightning/mydump/parquet_parser.go:380 +0x51d
[2021-08-23T01:47:18.490Z]   github.com/pingcap/tidb/br/pkg/lightning/mydump.testParquetParserSuite.TestParquetVariousTypes()
[2021-08-23T01:47:18.490Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/br/pkg/lightning/mydump/parquet_parser_test.go:194 +0x2064
[2021-08-23T01:47:18.491Z]   github.com/pingcap/tidb/br/pkg/lightning/mydump.(*testParquetParserSuite).TestParquetVariousTypes()
[2021-08-23T01:47:18.491Z]       <autogenerated>:1 +0x49
[2021-08-23T01:47:18.491Z]   runtime.call16()
[2021-08-23T01:47:18.491Z]       /usr/local/go/src/runtime/asm_amd64.s:550 +0x3d
[2021-08-23T01:47:18.491Z]   reflect.Value.Call()
[2021-08-23T01:47:18.491Z]       /usr/local/go/src/reflect/value.go:337 +0xd8
[2021-08-23T01:47:18.491Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2021-08-23T01:47:18.491Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xb3b
[2021-08-23T01:47:18.491Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2021-08-23T01:47:18.491Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x11d
[2021-08-23T01:47:18.491Z] 
[2021-08-23T01:47:18.491Z] Goroutine 63 (running) created at:
[2021-08-23T01:47:18.491Z]   github.com/xitongsys/parquet-go/reader.(*ParquetReader).read()
[2021-08-23T01:47:18.491Z]       /nfs/cache/mod/github.com/xitongsys/parquet-go@v1.5.5-0.20201110004701-b09c49d6d457/reader/reader.go:328 +0x88b
[2021-08-23T01:47:18.491Z]   github.com/xitongsys/parquet-go/reader.(*ParquetReader).Read()
[2021-08-23T01:47:18.491Z]       /nfs/cache/mod/github.com/xitongsys/parquet-go@v1.5.5-0.20201110004701-b09c49d6d457/reader/reader.go:196 +0x1fe
[2021-08-23T01:47:18.491Z]   github.com/xitongsys/parquet-go/reader.(*ParquetReader).ReadByNumber()
[2021-08-23T01:47:18.491Z]       /nfs/cache/mod/github.com/xitongsys/parquet-go@v1.5.5-0.20201110004701-b09c49d6d457/reader/reader.go:212 +0x209
[2021-08-23T01:47:18.491Z]   github.com/pingcap/tidb/br/pkg/lightning/mydump.(*ParquetParser).ReadRow()
[2021-08-23T01:47:18.491Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/br/pkg/lightning/mydump/parquet_parser.go:359 +0x8e5
[2021-08-23T01:47:18.491Z]   github.com/pingcap/tidb/br/pkg/lightning/mydump.testParquetParserSuite.TestParquetParser()
[2021-08-23T01:47:18.491Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/br/pkg/lightning/mydump/parquet_parser_test.go:65 +0xbb3
[2021-08-23T01:47:18.491Z]   github.com/pingcap/tidb/br/pkg/lightning/mydump.(*testParquetParserSuite).TestParquetParser()
[2021-08-23T01:47:18.492Z]       <autogenerated>:1 +0x49
[2021-08-23T01:47:18.492Z]   runtime.call16()
[2021-08-23T01:47:18.492Z]       /usr/local/go/src/runtime/asm_amd64.s:550 +0x3d
[2021-08-23T01:47:18.492Z]   reflect.Value.Call()
[2021-08-23T01:47:18.492Z]       /usr/local/go/src/reflect/value.go:337 +0xd8
[2021-08-23T01:47:18.492Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2021-08-23T01:47:18.492Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xb3b
[2021-08-23T01:47:18.492Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2021-08-23T01:47:18.492Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x11d
[2021-08-23T01:47:18.492Z] ==================
```

### 1. Minimal reproduce step (Required)

in ci https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tidb-unit-test-nightly/runs/9385/nodes/117/steps/465/log/?start=0

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #27473

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [x] Unit test

Side effects

Documentation

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
@glorv IIUC `SerialSuite` means only all `SerialSuite` run in serial, but it is still run parallel with other `Suite`. How does this PR fix the problem?

**Comment by glorv** [comment]
> parallel

No. SerialSuites are scheduled to be running serially at last. So there should be no data race then

**Comment by tisonkun** [comment]
@glorv thanks for your explanation! Good to know and checked it.

**Review by Little-Wallace — APPROVED** [review]
LGTM

**Review by 3pointer — APPROVED** [review]

**Review by kennytm — APPROVED** [review]

**Pull request merged**
