### PR TITLE
table: set the datum collation correctly in CastValue()

### LINKED ISSUE #30930: "get old row failed" when `replace` into case-insensitive primary key
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t;
create table t (a varchar(20) charset utf8mb4 collate utf8mb4_general_ci primary key);
replace into t(a) values (_binary'A '),(_binary'A');
select a from t;
```

### 2. What did you expect to see? (Required)
```sql
mysql> replace into t(a) values (_binary'A '),(_binary'A');
Query OK, 3 rows affected (0.00 sec)
Records: 2  Duplicates: 1  Warnings: 0

mysql> select a from t;
+---+
| a |
+---+
| A |
+---+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```sql
mysql> REPLACE INTO t(a) VALUES (_binary'A '),(_binary'A');
ERROR 1105 (HY000): can not be duplicated row, due to old row not found. handle 1 not found
```

### 4. What is your TiDB version? (Required)

23c71f1a3b

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #30930

### What is changed and how it works?

Even if the strings are transformed to UTF-8 charset, the collation in the datum should be unchanged.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

**Review by xiongjiwei — APPROVED** [review]

**Review by wjhuang2016 — COMMENTED** [review]
Please add the unit-test in TestCastValue

**Comment by zimulala** [comment]
PTAL @wjhuang2016

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
