### PR TITLE
parser: update `parser.y` make keywords in the order

### LINKED ISSUE #50066: run `make` in `pkg/parser` will make `Keywords` out of order
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run `make` in `pkg/parser`
then `git diff`

### 2. What did you expect to see? (Required)

nothing output

### 3. What did you see instead (Required)

```diff
diff --git a/pkg/parser/keywords.go b/pkg/parser/keywords.go
index 17fed04c8f..63f1d23a4e 100644
--- a/pkg/parser/keywords.go
+++ b/pkg/parser/keywords.go
@@ -611,9 +611,9 @@ var Keywords = []KeywordsType{
        {"UNCOMMITTED", false, "unreserved"},
        {"UNDEFINED", false, "unreserved"},
        {"UNICODE", false, "unreserved"},
-       {"UNIVERSAL", false, "unreserved"},
        {"UNKNOWN", false, "unreserved"},
        {"USER", false, "unreserved"},
+       {"UNIVERSAL", false, "unreserved"},
        {"VALIDATION", false, "unreserved"},
        {"VALUE", false, "unreserved"},
        {"VARIABLES", false, "unreserved"},
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #50066

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]
it's good that we write a script or something to automatically sort them

**Comment by hawkingrei** [comment]
It will be removed. Because the universal binding is cancelled.

**Comment by hawkingrei** [comment]
```universal``` is removed by #50103.

**Pull request closed without merging**
