### PR TITLE
gcworker: export resolveLocks api for test (#18064)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #18064 to release-4.0

---

Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?

Problem Summary:
It's hard to test green GC. Previously I invoke the code directly to test it but I have to update the dependency periodically and it's hard to solve dependency conflicts.

### What is changed and how it works?

What's Changed:
I add an HTTP API for it. And it's available only for tests.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- No release note

### CODE REVIEW

**Comment by cfzjywxk** [comment]
LGTM

**Comment by cfzjywxk** [comment]
@jackysp need help to merge

**Comment by youjiali1995** [comment]
Can the release branch merge PRs during releasement?

**Pull request merged**
