### PR TITLE
chore: migrate to new prow reviewing

### PR DESCRIPTION
**Pull request by wuhuizuo**
### What problem does this PR solve?

Issue Number: ref #44015

Problem Summary: migrate to native prow LGTM + approve plugins

- Backgroup: https://internals.tidb.io/t/topic/854
- Ref: https://github.com/ti-community-infra/configs/issues/824

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- None

Documentation

- None

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by wuhuizuo** [comment]
/retest
it affected by 429 error when download golang toolchain sdk in bazel building.

**Review by niubell — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Comment by wuhuizuo** [comment]
> /cc 3pointer niubell benjamin2037 bb7133

/hold

wait for all owner confirmed.

**Pull request merged**
