### PR TITLE
optimizer/plan: fix splitWhere

### PR DESCRIPTION
**Pull request by coocood**
Fixes https://github.com/pingcap/tidb/issues/859

but after a recent refactor, only first column in the index can be used.

I'll add back multi column index support after join plan has been implemented.

### CODE REVIEW

**Comment by coocood** [comment]
@roger-lijian @shenli @qiuyesuifeng PTAL

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by ngaut** [comment]
You  should add tests to make sure we actually using index.

**Comment by shenli** [comment]
LGTM

**Pull request merged**
