### PR TITLE
planner: do not remove the first row func if it is a constant | tidb-test=pr/2277

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/38756

Problem Summary:

### What changed and how does it work?

Do not remove the first row func if the group by expr is a constant.

For instance, if you try `SELECT DISTINCT SQRT(1) FROM t`
```sql
mysql> explain SELECT DISTINCT SQRT(1) FROM t;
+---------------------------+----------+-----------+---------------+-------------------------------------------------------+
| id                        | estRows  | task      | access object | operator info                                         |
+---------------------------+----------+-----------+---------------+-------------------------------------------------------+
| HashAgg_8                 | 1.00     | root      |               | group by:Column#5, funcs:firstrow(Column#5)->Column#3 |
| └─TableReader_9           | 1.00     | root      |               | data:HashAgg_4                                        |
|   └─HashAgg_4             | 1.00     | cop[tikv] |               | group by:1,                                           |
|     └─TableFullScan_7     | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo                        |
+---------------------------+----------+-----------+---------------+-------------------------------------------------------+
4 rows in set (0.00 sec)
```

As you can see, we accidentally removed the first-row func because the group by expr is a constant 1 and the arg is also 1.

But if you try `SELECT DISTINCT SQRT(2) FROM t`, it works well.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the TiDB issue with incorrect results when the function's argument matches the group by key
```

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
🔢 Self-check

**Review by elsa0520 — APPROVED** [review]
LGTM

**Review by fixdb — APPROVED** [review]
+1

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
