### PR TITLE
ddl: report error for empty name index

### LINKED ISSUE #18149: TiDB can create empty name index.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> CREATE TABLE t1(x INT, KEY ``(x));
Query OK, 0 rows affected (0.00 sec)
```
### 2. What did you expect to see? (Required)
In MySQL:
```
mysql> CREATE TABLE t1(x INT, KEY ``(x));
ERROR 1280 (42000): Incorrect index name ''
```

## Score
400

## SIG Slack Channel
You can join [#sig-ddl ](https://app.slack.com/client/TH91JCS4W/CMAKWBNJU)on slack in your spare time to discuss and get help with mentors or others.

## Mentor(s)
* @wjhuang2016 

## Recommended Skills

* Golang

## Learning Materials
N/A

### PR DESCRIPTION
**Pull request by chanme**
### What problem does this PR solve?

Issue Number: close #18149  

Problem Summary: TiDB can create empty name index

### What is changed and how it works?
In mysql grammar, one cannot use empty name index, when `checkIndexInfo`, we should report error for the non-primary indexes.

What's Changed:
when calling the `checkIndexInfo`, we add one more arg  `isPrimary` to tell whether this index is primary, inside the check we report the error for `len(indexName) == 0 && !isPrimary`
How it Works:
```
mysql> CREATE TABLE `t` (x INT, KEY ``(x));
ERROR 1280 (42000): Incorrect index name ''
```

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)
```
mysql> CREATE TABLE `t` (x INT, KEY ``(x));
ERROR 1280 (42000): Incorrect index name ''
```
### Release note 
- Report error for empty name index

### CODE REVIEW

**Comment by tangenta** [comment]
@chanme This statement is failed in the test:
```sql
create table t (i int key, j int, unique key (i, j));
```
```
Error 1280: Incorrect index name ''
```

**Comment by chanme** [comment]
> @chanme This statement is failed in the test:
> 
> ```sql
> create table t (i int key, j int, unique key (i, j));
> ```
> 
> ```
> Error 1280: Incorrect index name ''
> ```

It seems that a lot of cases use empty name index, I will check for all related cases and fix them.

**Comment by tangenta** [comment]
> > @chanme This statement is failed in the test:
> > ```sql
> > create table t (i int key, j int, unique key (i, j));
> > ```
> > 
> > 
> > ```
> > Error 1280: Incorrect index name ''
> > ```
> 
> It seems that a lot of cases use empty name index, I will check for all related cases and fix them.

I think this is much like a **default** name. If you test it with MySQL and `show index in t`, a default name `i` is chosen.

It is better to stay consistent with MySQL.

**Comment by chanme** [comment]
> > > @chanme This statement is failed in the test:
> > > ```sql
> > > create table t (i int key, j int, unique key (i, j));
> > > ```
> > > 
> > > 
> > > ```
> > > Error 1280: Incorrect index name ''
> > > ```
> > 
> > 
> > It seems that a lot of cases use empty name index, I will check for all related cases and fix them.
> 
> I think this is much like a **default** name. If you test it with MySQL and `show index in t`, a default name `i` is chosen.
> 
> It is better to stay consistent with MySQL.

You're right, I tested with the following cases in MYSQL.
for `unique index` and `normal index`, it's ok to create a key without an explicit name, but will report error when you give a name for it.
for `primary index`, the index name will be ignored and named as `PRIMARY` 

```
MariaDB [test]> create table t1 (i int, j int, key ``(i, j));       
ERROR 1280 (42000): Incorrect index name ''
MariaDB [test]> create table t1 (i int, j int, key (i, j));    
Query OK, 0 rows affected (0.24 sec)

MariaDB [test]> create table t2 (i int, j int, unique key `` (i, j)); 
ERROR 1280 (42000): Incorrect index name ''
MariaDB [test]> create table t2 (i int, j int, unique key (i, j));   
Query OK, 0 rows affected (1.12 sec)

MariaDB [test]> create table t3 (i int, j int, primary key `` (i, j));      
Query OK, 0 rows affected (0.33 sec)

MariaDB [test]> create table t4 (i int, j int, primary key (i, j));    
Query OK, 0 rows affected (0.44 sec)

MariaDB [test]> create table t5 (i int, j int, primary key `ss` (i, j)); 
Query OK, 0 rows affected (0.23 sec)
MariaDB [test]> show index in t5;

+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table | Non_unique | Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| t5    |          0 | PRIMARY  |            1 | i           | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
| t5    |          0 | PRIMARY  |            2 | j           | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
2 rows in set (0.00 sec)
```

**Comment by chanme** [comment]
MYSQL implementation [sql/sql_yacc.yy](https://github.com/mysql/mysql-server/blob/8.0/sql/sql_yacc.yy#L7400) will use a special variable `NULL_STR` to tell the index name is empty.
```
opt_index_name_and_type:
          opt_ident                  { $$= {$1, NULL}; }
        | opt_ident USING index_type { $$= {$1, NEW_PTN PT_index_type($3)}; }
        | ident TYPE_SYM index_type  { $$= {$1, NEW_PTN PT_index_type($3)}; }
        ;

opt_ident:
          /* empty */ { $$= NULL_STR; }
        | ident
        ;

struct MYSQL_LEX_STRING {
  char *str;
  size_t length;
};

LEX_STRING NULL_STR = {nullptr, 0};
```
while the tidb/parser parser will set the index name to "" when it's not given. 
```
IndexName:
	{
		$$ = ""
	}
|	Identifier
```
It's hard to tell whether the index name is **default to empty** or **explicitly named as empty**. I guess one need to modify the parser first.

**Comment by chanme** [comment]
It seems that fixing this inconsistency will somehow complex the code, so for now I'll close this pr.

**Pull request closed without merging**
