### PR TITLE
executor, plan: convert Limit to TableDual when meet `limit 0`

### LINKED ISSUE #5341: unexcepted index out of range error
Please answer these questions before submitting your issue. Thanks!
PTAL @coocood 

1. What did you do?
```
./gentest.pl --dsn dbi:mysql:host=127.0.0.1:port=4000:user=root:database=test --grammar=conf/limit_compare.yy --gendata --thread=1
```
``` sql


-- ----------------------------
--  Table structure for `D`
-- ----------------------------
DROP TABLE IF EXISTS `D`;
CREATE TABLE `D` (
  `pk` int(11) NOT NULL AUTO_INCREMENT,
  `col_int_nokey` int(11) DEFAULT NULL,
  `col_int_key` int(11) DEFAULT NULL,
  `col_date_key` date DEFAULT NULL,
  `col_date_nokey` date DEFAULT NULL,
  `col_time_key` time DEFAULT NULL,
  `col_time_nokey` time DEFAULT NULL,
  `col_datetime_key` datetime DEFAULT NULL,
  `col_datetime_nokey` datetime DEFAULT NULL,
  `col_varchar_key` varchar(1) DEFAULT NULL,
  `col_varchar_nokey` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`pk`),
  KEY `col_int_key` (`col_int_key`),
  KEY `col_date_key` (`col_date_key`),
  KEY `col_time_key` (`col_time_key`),
  KEY `col_datetime_key` (`col_datetime_key`),
  KEY `col_varchar_key` (`col_varchar_key`,`col_int_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Records of `D`
-- ----------------------------
BEGIN;
INSERT INTO `D` VALUES ('2', '8', '9', '2003-01-07', '2003-01-07', '14:34:45', '14:34:45', '2004-08-10 09:09:31', '2004-08-10 09:09:31', 'c', 'c'), ('3', '6', '9', null, null, '11:49:48', '11:49:48', '2005-03-21 04:31:40', '2005-03-21 04:31:40', 'o', 'o'), ('4', '6', '9', '2005-03-12', '2005-03-12', '18:12:55', '18:12:55', '2002-10-25 23:50:35', '2002-10-25 23:50:35', 'c', 'c'), ('5', '3', '9', '2000-08-02', '2000-08-02', '18:30:05', '18:30:05', '2001-04-01 21:14:04', '2001-04-01 21:14:04', 'd', 'd'), ('6', '9', '9', '1900-01-01', '1900-01-01', '14:19:30', '14:19:30', '2005-03-12 06:02:34', '2005-03-12 06:02:34', 'v', 'v'), ('7', '2', '9', '2006-07-06', '2006-07-06', '05:20:04', '05:20:04', '2001-05-06 14:49:12', '2001-05-06 14:49:12', 'm', 'm'), ('8', '1', '9', '2006-12-24', '2006-12-24', '20:29:31', '20:29:31', '2004-04-25 00:00:00', '2004-04-25 00:00:00', 'j', 'j'), ('11', '9', '9', null, null, '00:00:00', '00:00:00', '2009-09-07 18:40:43', '2009-09-07 18:40:43', 'z', 'z'), ('12', '8', '9', '2008-06-24', '2008-06-24', '09:58:06', '09:58:06', '2004-03-23 00:00:00', '2004-03-23 00:00:00', 'h', 'h'), ('13', null, '9', '2001-04-21', '2001-04-21', null, null, '2009-04-15 00:08:29', '2009-04-15 00:08:29', 'q', 'q'), ('14', '0', '9', '2003-11-22', '2003-11-22', '18:24:16', '18:24:16', '2000-04-21 00:00:00', '2000-04-21 00:00:00', 'w', 'w'), ('15', '5', '9', '2004-09-12', '2004-09-12', '17:39:57', '17:39:57', '2000-02-17 19:41:23', '2000-02-17 19:41:23', 'z', 'z'), ('16', '1', '9', '2006-06-20', '2006-06-20', '08:23:21', '08:23:21', '2003-09-20 07:38:14', '2003-09-20 07:38:14', 'j', 'j'), ('18', '6', '9', '2001-11-25', '2001-11-25', '21:50:46', '21:50:46', '2005-06-12 11:13:17', '2005-06-12 11:13:17', 'm', 'm'), ('19', '6', '9', '2004-10-26', '2004-10-26', '12:33:17', '12:33:17', '1900-01-01 00:00:00', '1900-01-01 00:00:00', 'n', 'n'), ('20', '1', '9', '2005-01-19', '2005-01-19', '03:06:43', '03:06:43', '2006-02-09 20:41:06', '2006-02-09 20:41:06', 'e', 'e'), ('21', '8', '9', '2008-07-06', '2008-07-06', '03:46:14', '03:46:14', '2004-05-22 01:05:57', '2004-05-22 01:05:57', 'u', 'u'), ('22', '1', '9', '1900-01-01', '1900-01-01', '20:34:52', '20:34:52', '2004-03-04 13:46:31', '2004-03-04 13:46:31', 's', 's'), ('23', '0', '9', '1900-01-01', '1900-01-01', null, null, '1900-01-01 00:00:00', '1900-01-01 00:00:00', 'u', 'u'), ('24', '4', '9', '2004-06-08', '2004-06-08', '10:41:20', '10:41:20', '2004-10-20 07:20:19', '2004-10-20 07:20:19', 'r', 'r'), ('25', '9', '9', '2007-02-20', '2007-02-20', '08:43:11', '08:43:11', '2006-04-17 00:00:00', '2006-04-17 00:00:00', 'g', 'g'), ('26', '8', '9', '2008-06-18', '2008-06-18', null, null, '2000-10-27 00:00:00', '2000-10-27 00:00:00', 'o', 'o'), ('27', '5', '9', '2008-05-15', '2008-05-15', '10:17:51', '10:17:51', '2007-04-14 08:54:06', '2007-04-14 08:54:06', 'w', 'w'), ('28', '9', '9', '2005-10-06', '2005-10-06', '06:34:09', '06:34:09', '2008-04-12 17:03:52', '2008-04-12 17:03:52', 'b', 'b'), ('30', null, '9', '2006-10-12', '2006-10-12', '04:02:32', '04:02:32', '1900-01-01 00:00:00', '1900-01-01 00:00:00', 'y', 'y'), ('31', null, '9', '2005-01-24', '2005-01-24', '02:33:14', '02:33:14', '2001-10-10 08:32:27', '2001-10-10 08:32:27', 'y', 'y'), ('33', '0', '9', null, null, '21:32:42', '21:32:42', '2001-12-16 05:31:53', '2001-12-16 05:31:53', 'p', 'p'), ('34', '3', '9', null, null, '23:04:47', '23:04:47', '2003-07-19 18:03:28', '2003-07-19 18:03:28', 's', 's'), ('35', '1', '9', '1900-01-01', '1900-01-01', '22:05:43', '22:05:43', '2001-03-27 11:44:10', '2001-03-27 11:44:10', 'e', 'e'), ('36', '75', '9', '2005-12-22', '2005-12-22', '02:05:45', '02:05:45', '2008-06-15 02:13:00', '2008-06-15 02:13:00', 'd', 'd'), ('37', '9', '9', '2005-05-03', '2005-05-03', '00:00:00', '00:00:00', '2009-03-14 21:29:56', '2009-03-14 21:29:56', 'd', 'd'), ('38', '7', '9', '2003-05-27', '2003-05-27', '18:09:07', '18:09:07', '2005-01-02 00:00:00', '2005-01-02 00:00:00', 'c', 'c'), ('39', null, '9', '2006-05-25', '2006-05-25', '10:54:06', '10:54:06', '2007-07-16 04:44:07', '2007-07-16 04:44:07', 'b', 'b'), ('40', null, '9', null, null, '23:15:50', '23:15:50', '2003-08-26 21:38:26', '2003-08-26 21:38:26', 't', 't'), ('42', '0', '9', '2009-02-14', '2009-02-14', '03:37:09', '03:37:09', '2000-01-06 20:32:48', '2000-01-06 20:32:48', 'y', 'y'), ('43', '204', '9', '2003-01-16', '2003-01-16', '22:26:06', '22:26:06', '2006-06-23 13:27:17', '2006-06-23 13:27:17', 'c', 'c'), ('44', '0', '9', '1900-01-01', '1900-01-01', '17:10:38', '17:10:38', '2007-11-27 00:00:00', '2007-11-27 00:00:00', 'd', 'd'), ('45', '9', '9', '2007-06-26', '2007-06-26', '00:00:00', '00:00:00', '2002-04-03 12:06:51', '2002-04-03 12:06:51', 'x', 'x'), ('46', '8', '9', '2004-03-27', '2004-03-27', '17:08:49', '17:08:49', '2008-12-28 09:47:42', '2008-12-28 09:47:42', 'p', 'p'), ('47', '7', '9', null, null, '19:04:40', '19:04:40', '2002-04-04 10:07:54', '2002-04-04 10:07:54', 'e', 'e'), ('50', '6', '9', '2004-05-13', '2004-05-13', null, null, '2009-02-19 03:17:06', '2009-02-19 03:17:06', 's', 's'), ('51', '5', '9', '2005-09-13', '2005-09-13', '10:58:07', '10:58:07', '1900-01-01 00:00:00', '1900-01-01 00:00:00', 'e', 'e'), ('52', '2', '9', '2005-10-03', '2005-10-03', '00:00:00', '00:00:00', '2000-11-10 08:20:01', '2000-11-10 08:20:01', 'l', 'l'), ('53', '3', '9', '2005-10-14', '2005-10-14', '09:43:15', '09:43:15', '2008-02-10 00:00:00', '2008-02-10 00:00:00', 'p', 'p'), ('54', '7', '9', null, null, '21:40:32', '21:40:32', '1900-01-01 00:00:00', '1900-01-01 00:00:00', 'h', 'h'), ('56', '145', '9', '2005-03-10', '2005-03-10', '16:47:26', '16:47:26', '2001-02-05 02:01:50', '2001-02-05 02:01:50', 'n', 'n'), ('57', '0', '9', '2000-06-19', '2000-06-19', '00:00:00', '00:00:00', '2000-10-28 08:44:25', '2000-10-28 08:44:25', 'v', 'v'), ('58', '1', '9', '2002-11-03', '2002-11-03', '05:25:59', '05:25:59', '2005-03-20 10:53:59', '2005-03-20 10:53:59', 'b', 'b'), ('59', '7', '9', '2009-01-05', '2009-01-05', '00:00:00', '00:00:00', '2001-06-02 13:54:13', '2001-06-02 13:54:13', 'x', 'x'), ('61', null, '9', '2005-07-02', '2005-07-02', '00:46:12', '00:46:12', '2009-07-16 13:05:43', '2009-07-16 13:05:43', 't', 't'), ('63', '2', '9', '2006-06-21', '2006-06-21', '02:13:59', '02:13:59', '2003-02-06 18:12:15', '2003-02-06 18:12:15', 'w', 'w'), ('64', '2', '9', null, null, '02:54:47', '02:54:47', '2006-06-05 03:22:51', '2006-06-05 03:22:51', 'k', 'k'), ('65', '8', '9', '2005-12-16', '2005-12-16', '18:13:59', '18:13:59', '2002-02-10 05:47:27', '2002-02-10 05:47:27', 'a', 'a'), ('66', '6', '9', '2004-11-05', '2004-11-05', '13:53:08', '13:53:08', '2001-08-01 08:50:52', '2001-08-01 08:50:52', 't', 't'), ('67', '1', '9', null, null, '22:21:30', '22:21:30', '1900-01-01 00:00:00', '1900-01-01 00:00:00', 'z', 'z'), ('68', null, '9', '2004-09-14', '2004-09-14', '11:41:50', '11:41:50', null, null, 'e', 'e'), ('69', '1', '9', '2002-04-06', '2002-04-06', '15:20:02', '15:20:02', '1900-01-01 00:00:00', '1900-01-01 00:00:00', 'q', 'q'), ('70', '0', '9', null, null, null, null, '2000-09-23 00:00:00', '2000-09-23 00:00:00', 'e', 'e'), ('71', '4', '9', '2002-11-13', '2002-11-13', null, null, '2007-07-09 08:32:49', '2007-07-09 08:32:49', 'v', 'v'), ('72', '1', '9', '2006-05-27', '2006-05-27', '07:51:52', '07:51:52', '2000-01-05 00:00:00', '2000-01-05 00:00:00', 'd', 'd'), ('73', '1', '9', '2000-12-22', '2000-12-22', '00:00:00', '00:00:00', '2000-09-24 00:00:00', '2000-09-24 00:00:00', 'u', 'u'), ('74', '27', '9', '2004-02-21', '2004-02-21', null, null, '2005-05-06 00:00:00', '2005-05-06 00:00:00', 'o', 'o'), ('75', '4', '9', '2009-05-15', '2009-05-15', null, null, '2000-03-11 00:00:00', '2000-03-11 00:00:00', 'b', 'b'), ('76', '6', '9', '2008-12-12', '2008-12-12', '12:31:05', '12:31:05', '2001-09-02 16:17:35', '2001-09-02 16:17:35', 'c', 'c'), ('77', '2', '9', '2000-04-15', '2000-04-15', '00:00:00', '00:00:00', '2006-04-25 05:43:44', '2006-04-25 05:43:44', 'q', 'q'), ('79', null, '9', '2001-10-18', '2001-10-18', '20:38:54', '20:38:54', '2004-08-06 00:00:00', '2004-08-06 00:00:00', 'h', 'h'), ('80', '9', '9', '2008-05-25', '2008-05-25', '00:30:15', '00:30:15', '2001-11-27 05:07:57', '2001-11-27 05:07:57', 'd', 'd'), ('81', '75', '9', '2004-12-02', '2004-12-02', '23:46:36', '23:46:36', '2009-06-28 03:18:39', '2009-06-28 03:18:39', 'w', 'w'), ('82', '2', '9', '2002-02-15', '2002-02-15', '19:03:13', '19:03:13', '2000-03-12 00:00:00', '2000-03-12 00:00:00', 'm', 'm'), ('83', '9', '9', '2002-03-03', '2002-03-03', '10:54:27', '10:54:27', null, null, 'i', 'i'), ('84', '4', '9', null, null, '00:25:47', '00:25:47', '2007-10-20 00:00:00', '2007-10-20 00:00:00', 'w', 'w'), ('85', '0', '9', '2003-01-26', '2003-01-26', '08:44:27', '08:44:27', '2009-09-27 00:00:00', '2009-09-27 00:00:00', 'f', 'f'), ('86', '0', '9', '2001-12-19', '2001-12-19', '08:15:38', '08:15:38', '2002-07-16 00:00:00', '2002-07-16 00:00:00', 'k', 'k'), ('87', '1', '9', '2001-08-07', '2001-08-07', '19:56:21', '19:56:21', '2005-02-20 00:00:00', '2005-02-20 00:00:00', 'v', 'v'), ('88', '119', '9', '2005-02-16', '2005-02-16', '00:00:00', '00:00:00', null, null, 'c', 'c'), ('89', '1', '9', '2006-06-10', '2006-06-10', '20:50:52', '20:50:52', '2001-07-16 00:00:00', '2001-07-16 00:00:00', 'y', 'y'), ('90', '7', '9', null, null, '03:54:39', '03:54:39', '2009-05-20 21:04:12', '2009-05-20 21:04:12', 'h', 'h'), ('92', '7', '9', '2003-04-27', '2003-04-27', '12:54:58', '12:54:58', '2005-07-12 00:00:00', '2005-07-12 00:00:00', 't', 't'), ('93', '2', '9', '2005-10-13', '2005-10-13', '04:02:43', '04:02:43', '2006-07-22 09:46:34', '2006-07-22 09:46:34', 'l', 'l'), ('94', '6', '9', '2003-10-02', '2003-10-02', '11:31:12', '11:31:12', '2001-09-01 00:00:00', '2001-09-01 00:00:00', 'a', 'a'), ('95', '4', '9', '2005-09-09', '2005-09-09', '20:20:04', '20:20:04', '2002-05-27 18:38:45', '2002-05-27 18:38:45', 'r', 'r'), ('96', '5', '9', null, null, '00:22:24', '00:22:24', null, null, 's', 's'), ('97', '7', '9', '2006-02-15', '2006-02-15', '10:09:31', '10:09:31', null, null, 'z', 'z'), ('98', '1', '9', '1900-01-01', '1900-01-01', null, null, '2009-08-08 22:38:53', '2009-08-08 22:38:53', 'j', 'j'), ('99', '7', '9', '2003-12-24', '2003-12-24', '18:45:35', '18:45:35', null, null, 'c', 'c'), ('100', '2', '9', '2001-07-26', '2001-07-26', '11:49:25', '11:49:25', '2007-04-25 05:08:49', '2007-04-25 05:08:49', 'f', 'f');
COMMIT;


```

``` sql
SELECT * FROM `D` WHERE `col_varchar_key` BETWEEN '2002-05-20' AND 4 ORDER BY `col_date_key` , `pk` LIMIT 0;
```

2. What did you expect to see?

no error

3. What did you see instead?

```
index out of range, goroutine 5904 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc4209b6160)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:389 +0xfd
panic(0x1c4fa20, 0x274d330)
	/Users/xuhuaiyu/.gvm/gos/go1.9/src/runtime/panic.go:491 +0x283
github.com/pingcap/tidb/executor.(*TopNExec).processChildChk(0xc42079e000, 0xc42078bb20, 0x0, 0x0, 0x9)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/sort.go:566 +0x295
github.com/pingcap/tidb/executor.(*TopNExec).executeTopN(0xc42079e000, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/sort.go:538 +0x13e
github.com/pingcap/tidb/executor.(*TopNExec).NextChunk(0xc42079e000, 0xc42078bb00, 0xc42078bb00, 0xc4213fbc70)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/sort.go:473 +0x184
github.com/pingcap/tidb/executor.(*recordSet).NextChunk(0xc4213fbbc0, 0xc42078bb00, 0xc4213fbbc0, 0xc42078bb00)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/adapter.go:96 +0x42
github.com/pingcap/tidb/server.(*tidbResultSet).NextChunk(0xc4205a09c0, 0xc42078bb00, 0x400, 0xc420c76c00)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/driver_tidb.go:302 +0x3d
github.com/pingcap/tidb/server.(*clientConn).writeChunks(0xc4209b6160, 0x2544a40, 0xc4205a09c0, 0x0, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:874 +0x3d5
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc4209b6160, 0x2d07d48, 0xc421201710, 0x2544a40, 0xc4205a09c0, 0xc4218e0000, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:799 +0x64e
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc4209b6160, 0x2d07d48, 0xc421201710, 0xc421259881, 0x6b, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:748 +0x115
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc4209b6160, 0xc421259881, 0x6c, 0x6c, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:530 +0x511
github.com/pingcap/tidb/server.(*clientConn).Run(0xc4209b6160)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:412 +0x18a
github.com/pingcap/tidb/server.(*Server).onConn(0xc4206040c0, 0x2547620, 0xc420de0e60)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/server.go:315 +0x144
created by github.com/pingcap/tidb/server.(*Server).Run
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/server.go:261 +0x496
```

4. What version of TiDB are you using (`tidb-server -V`)?
648e51d19e51120e9158f6333c060f17260b7ea6

### PR DESCRIPTION
**Pull request by XuHuaiyu**
Fix #5341 
Before this PR: 
``` sql
create table t(a char);
insert into t value('a');
select * from test.t where a < 1 order by a limit 0;
```
``` sql
+----------------+--------------+----------------+------+----------------------------------------------+-------+
| id             | parents      | children       | task | operator info                                | count |
+----------------+--------------+----------------+------+----------------------------------------------+-------+
| TableScan_15   |              |                | cop  | table:t, range:[-inf,+inf], keep order:false | 1.00  |
| TableReader_16 | Selection_14 |                | root | data:TableScan_15                            | 1.00  |
| Selection_14   | TopN_10      | TableReader_16 | root | lt(cast(test.t.a), 1)                        | 0.80  |
| TopN_10        |              | Selection_14   | root | test.t.a:asc, offset:0, count:0              | 0.00  |
+----------------+--------------+----------------+------+----------------------------------------------+-------+
```
This sql will get panic message as #5341 shows,
cause TopN cannot be pushed down, and the check [here](https://github.com/pingcap/tidb/blob/master/executor/sort.go#L401) will be true.

PTAL @coocood @zz-jason

### CODE REVIEW

**Comment by winoros** [comment]
Convert `TopN`/`Limit` to `TableDual` in plan building phase is a more better way.

**Comment by XuHuaiyu** [comment]
PTAL @winoros @zz-jason

**Comment by winoros** [comment]
CI failed.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
