### PR TITLE
statistics: fix auto analyze log information incomplete (#23522)

### LINKED ISSUE #23515: auto analyze log doesn't print table name and partition name
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

When auto analyze is triggered, the log information is incomplete. The parameters are not replaced by the actual values.
image

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23522 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23543
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23543:release-4.0-42141084fe10
```

---

### What problem does this PR solve?

Issue Number: close #23515 

Problem Summary:

After we changed our exec SQL API, SQL strings parameterized and need to be escaped to become the real SQL to be executed.
When logging auto analyze sql, we didn't do this.

### What is changed and how it works?

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

### Release note 

- no release note.

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
@time-and-fate please resolve conflict.

**Comment by zimulala** [comment]
@time-and-fate please resolve conflict.

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
