### PR TITLE
server: skip unstable test TestDBStmtCount

### LINKED ISSUE #43138: unstable test TestDBStmtCount
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
cd executor
go test -v -tags intest -run  TestDBStmtCount
```

### 2. What did you expect to see? (Required)

No error

### 3. What did you see instead (Required)

```
--- FAIL: TestDBStmtCount (0.67s)
    server_test.go:2160:
                Error Trace:    /home/genius/project/src/[github.com/pingcap/tidb/server/server_test.go:2160](http://github.com/pingcap/tidb/server/server_test.go:2160)
                                                        /home/genius/project/src/[github.com/pingcap/tidb/server/server_test.go:154](http://github.com/pingcap/tidb/server/server_test.go:154)
                                                        /home/genius/project/src/[github.com/pingcap/tidb/server/server_test.go:2123](http://github.com/pingcap/tidb/server/server_test.go:2123)
                                                        /home/genius/project/src/[github.com/pingcap/tidb/server/tidb_serial_test.go:1](http://github.com/pingcap/tidb/server/tidb_serial_test.go:1)
19
                Error:          Not equal:
                                expected: 3
                                actual  : 2
                Test:           TestDBStmtCount
FAIL
exit status 1
```
FAIL    [github.com/pingcap/tidb/server](http://github.com/pingcap/tidb/server)  0.710s

### 4. What is your TiDB version? (Required)

master e123433e2abda14e3540bc071d414f0a92e77725

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #43138

Problem Summary:

### What is changed and how it works?

Skip the test

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by tiancaiamao** [comment]
In https://github.com/pingcap/tidb/pull/43048, @time-and-fate try to pass CI by modify the test result.
But it's stable, and the workaround is not a stable way to workaround it.
So let's just skip it.

**Review by hawkingrei — APPROVED** [review]

**Review by time-and-fate — APPROVED** [review]

**Pull request merged**
