### PR TITLE
keyspace: support API V2 mock store

### PR DESCRIPTION
**Pull request by ystaticy**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/57969

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
support keyspace mock store, and add UT case.
```

### CODE REVIEW

**Review by djshow832 — APPROVED** [review]

**Comment by djshow832** [comment]
Please fix CI, rest LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
