### PR TITLE
executor: reuse memory in the deleteSingleTableByChunk

### LINKED ISSUE #54080: (*DeleteExec).deleteSingleTableByChunk spend too much time on making slices
## Enhancement

(*DeleteExec).deleteSingleTableByChunk spend too much time on making slices

https://flamegraph.com/share/e51414c2-2d3a-11ef-aba3-6a3d1814cbe4

image

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #54080

Problem Summary:

### What changed and how does it work?

(*DeleteExec).deleteSingleTableByChunk spend too much time on making slices

https://flamegraph.com/share/e51414c2-2d3a-11ef-aba3-6a3d1814cbe4

image

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

https://flamegraph.com/share/c1ef40c6-2d78-11ef-aba3-6a3d1814cbe4

image

I find many ```runtime.memmove``` in the ```executor.(*DeleteExec).deleteOneRow```
. so I think that deleteOneRow has copied the ```slices```. so it cannot affect the result.

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xzhangxian1008 — APPROVED** [review]
LGTM

**Review by jackysp — APPROVED** [review]

**Comment by hawkingrei** [comment]
> /hold

I cannot make sure whether ```[]types.Datum``` has refence in the ```deleteOneRow```.

**Comment by hawkingrei** [comment]
> > /hold
> 
> I cannot make sure whether `[]types.Datum` has refence in the `deleteOneRow`.

I use the ```sync.Pool``` and ```runtime.SetFinalize``` to refactor the code.

**Comment by hawkingrei** [comment]
> > > /hold
> > 
> > 
> > I cannot make sure whether `[]types.Datum` has refence in the `deleteOneRow`.
> 
> I use the `sync.Pool` and `runtime.SetFinalize` to refactor the code.

image

But using `runtime.SetFinalize` is not a good way. it still takes many time on it.

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
