### PR TITLE
statistics: add a priority queue API

### PR DESCRIPTION
**Pull request by Rustin170506**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/55063

Problem Summary:

### What changed and how does it work?

This PR added a new API `/stats/priority-queue` to output all current jobs in the priority queue.

The test output looks like:

```sh
curl http://10.2.6.161:10080/stats/priority-queue
{
 "current_jobs": [
  {
   "type": "analyzeDynamicPartition",
   "table_id": 18303,
   "weight": 0.39783801684240416,
   "partition_ids": [
    89490
   ],
   "index_ids": null,
   "partition_index_ids": {},
   "indicators": {
    "change_percentage": "2.31%",
    "table_size": "2948.00",
    "last_analysis_duration": "2m21.6s"
   },
   "has_newly_added_index": false
  },
  {
   "type": "analyzeDynamicPartition",
   "table_id": 17904,
   "weight": 0.3969517635632116,
   "partition_ids": [
    89360,
    87716,
    89770
   ],
   "index_ids": null,
   "partition_index_ids": {},
   "indicators": {
    "change_percentage": "2.23%",
    "table_size": "3322.00",
    "last_analysis_duration": "2m48.883666666s"
   },
   "has_newly_added_index": false
  },
  {
   "type": "analyzeDynamicPartition",
   "table_id": 17806,
   "weight": 0.22839572041819045,
   "partition_ids": [
    84340
   ],
   "index_ids": null,
   "partition_index_ids": {},
   "indicators": {
    "change_percentage": "1.03%",
    "table_size": "6772.00",
    "last_analysis_duration": "2m6.7s"
   },
   "has_newly_added_index": false
  }
 ],
 "must_retry_tables": []
}%           
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Rustin170506** [comment]
Tested locally: 
```shell
curl http://127.0.0.1:10080/stats/priority-queue
{
 "current_jobs": [],
 "must_retry_tables": []
}%     
```

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by elsa0520 — APPROVED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
