### PR TITLE
*: uniform kv error codes to util/dbterror

### LINKED ISSUE #33024: uniform kv error codes to the dbterror directory

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: ref #31716

close #33024

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
Is there an overall design about the final state of such error types unification?

I tend to describe the goal first instead of making changes first; otherwise we may likely lost the goal soon.

**Comment by hawkingrei** [comment]
> Is there an overall design about the final state of such error types unification?
> 
> I tend to describe the goal first instead of making changes first; otherwise we may likely lost the goal soon.

just migrate the location of the current error files to a single package for avoiding importing other packages when to use.

**Comment by hawkingrei** [comment]
> Is there an overall design about the final state of such error types unification?
> 
> I tend to describe the goal first instead of making changes first; otherwise we may likely lost the goal soon.

It just move the code position.

**Comment by tisonkun** [comment]
Long stale and large conflict. Any progress should be made in a new PR.

Closing to reduce noise ...

**Pull request closed without merging**
