### PR TITLE
add is_ipv4_mapped function

### PR DESCRIPTION
**Pull request by qhsong**
add is_ipv4_mapped function to detect an IP is a ipv4 mapped.

### CODE REVIEW

**Comment by qhsong** [comment]
refer some test code for @spongedu

**Comment by coocood** [comment]
@qhsong 
The argument should be binary representation of IPv6 address, which is the result of function `INET6_ATON`.

**Comment by qhsong** [comment]
Oops,make a huge mistake.


Golang parse mapped ipv6 address directly as an IPv4 address, maybe I need research more cases.





Get Outlook for Android









On Sun, Mar 19, 2017 at 9:37 AM +0800, "Ewan Chou" <notifications@github.com> wrote:












@qhsong

The argument should be binary representation of IPv6 address, which is the result of function INET6_ATON.

**Comment by qhsong** [comment]
mysql treat mapped ipv6 address as ipv6 address, but golang treats as ipv4 address


So, maybe we need change some code for #2882

**Comment by XuHuaiyu** [comment]
Hi, @qhsong 

I guess that you may use ip.To4() to check whether a mapped IPv6 address is IPv4 or IPv6?
If so, you may try to check `len(ip)==net.IPv4Len && ip.To4()!=nil`.

**Comment by qhsong** [comment]
Hi @XuHuaiyu ,
it is a good way to check ip address, but `is_ipv4_mapped` need use `inet_aton` output as its input.
So I need collect more detail on it.

BTW, I just make a mistake on this code due to my carelessness.

**Comment by coocood** [comment]
@qhsong 
Any update?

**Comment by qhsong** [comment]
@coocood  wait #3051 to merge into master and then I will update this branch.
It is related about `inet6_aton` function output.

**Comment by zhexuany** [comment]
ping @qhsong #3051 was merged.

**Comment by qhsong** [comment]
@zhexuany Ok, I do it ASAP

**Comment by qhsong** [comment]
It's too long since first commit and hard to merger to master, so I will close this PR and re-submit anther PR.

**Pull request closed without merging**
