### PR TITLE
executor,infoschema: move `dataForSessionVar` into executor

### PR DESCRIPTION
**Pull request by Rustin-Liu**
#15026 
Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>

### What problem does this PR solve? 
move `dataForSessionVar` into executor.

### What is changed and how it works?
move `dataForSessionVar` into executor.

### Check List 

Tests 

 - Unit test

Code changes

None
Side effects

None

Related changes

 None
Release note
None

### CODE REVIEW

**Comment by Rustin-Liu** [comment]
@sre-bot  /run-all-tests

**Comment by Rustin-Liu** [comment]
@sre-bot /run-all-tests

**Comment by Rustin-Liu** [comment]
@zz-jason  @lonng  PTAL~

**Comment by zz-jason** [comment]
Hi @Rustin-Liu is this PR aims to getting the score by solving that challenge program issue?

**Comment by Rustin-Liu** [comment]
> Hi @Rustin-Liu is this PR aims to getting the score by solving that challenge program issue?

No, I just knew that I already had 200 points.

**Comment by zz-jason** [comment]
> > Hi @Rustin-Liu is this PR aims to getting the score by solving that challenge program issue?
> 
> No, I just knew that I already had 200 points.

Congratulations! Glad to hear that you have gained 200 scores! You have unlocked the medium/difficulty issues, which also have much higher scores! 👍

**Pull request merged**
