### PR TITLE
pkg/lightning : remove get_regions call in physical backend

### LINKED ISSUE #45507: Remove getRegions call by lightning in physical import mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

When lightning runs in physical import mode, it runs this sql query

SELECT REGION_ID, APPROXIMATE_SIZE FROM information_schema.TIKV_REGION_STATUS WHERE TABLE_ID = ?

This call is made by each lightning process in parallel import mode and by multiple worker threads in a lightning process. It can potentially overload the PD if number of regions are too many. However, it appears that this call may be unnecessary since its purpose is to display a warning message and increment a counter in the SplitAndScatterRegionByRanges() function. Considering that lightning physical import always operates on a new table, splitting the new region should not pose any harm. 

### 2. What did you expect to see? (Required)
Less number of get region calls to PD
### 4. What is your TiDB version? (Required)
6.5

### PR DESCRIPTION
**Pull request by mittalrishabh**
### What problem does this PR solve?

Problem Summary:
When lightning runs in physical import mode, it runs this sql query

SELECT REGION_ID, APPROXIMATE_SIZE FROM information_schema.TIKV_REGION_STATUS WHERE TABLE_ID = ?

This call is made by each lightning process in parallel import mode and by multiple worker threads in a lightning process. It can potentially overload the PD if number of regions are too many. However, it appears that this call may be unnecessary since its purpose is to display a warning message and increment a counter in the SplitAndScatterRegionByRanges() function. Considering that lightning physical import always operates on a new table, splitting the new region should not pose any harm.

Issue Number: close #45507

### What is changed and how it works?
Remove the getRegions call from lightning
### Check List

Tests 

- [ ] Manual test (add detailed scripts or steps below)

1. Run lightning in parallel import mode
2. Check get_Regions call in PD dashboard. It should be 0
3. Lightning should run successfully

### Release note
We saw this issue in 6.5.0

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by wuhuizuo** [comment]
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.pingcap.net/pingcap/tidb?pullRequest=46202) before we can accept your contribution.

@mittalrishabh Thanks for your contribution, please sign the CAL.

**Comment by mittalrishabh** [comment]
retest

**Comment by lance6716** [comment]
Hi I copied the error message from "idc-jenkins-ci-tidb/build" CI.

```
br/pkg/lightning/backend/local/localhelper_test.go:480:62: too many arguments in call to local.SplitAndScatterRegionByRanges
	have ("context".Context, []Range, nil, bool, number)
	want ("context".Context, []Range, bool)
br/pkg/lightning/backend/local/localhelper_test.go:570:62: too many arguments in call to local.SplitAndScatterRegionByRanges
	have ("context".Context, []Range, nil, bool, number)
	want ("context".Context, []Range, bool)
br/pkg/lightning/backend/local/localhelper_test.go:829:63: too many arguments in call to local.SplitAndScatterRegionByRanges
	have ("context".Context, []Range, nil, bool, number)
	want ("context".Context, []Range, bool)
```

**Comment by mittalrishabh** [comment]
D3Hunter can you review this PR

**Comment by mittalrishabh** [comment]
can i get approval of this PR

**Review by D3Hunter — APPROVED** [review]

**Comment by Benjamin2037** [comment]
Already in 7.5 @mittalrishabh

**Pull request merged**
