### PR TITLE
docs: add design doc for full pessimistic mode

### LINKED ISSUE #31135: Add an option to have all types of transactions be in pessimistic mode
## Feature Request

**Is your feature request related to a problem? Please describe:**

Implicit transactions are still executed in optimistic mode even if the pessimistic transaction option is turned on, which is hard to explain to uses. And often we fall into the same trap when troubleshooting problems ourselves. Also, for the lock view, since it reads info from the wait manager, the lock view is not available for optimistic transactions. Therefore, due to the optimistic implicit transactions, causing incomplete lock information can also cause confusion to users.

**Describe the feature you'd like:**

Unify all types of transactions in pessimistic mode, and implicit transactions are also in pessimistic mode.

1. Solve the problem of incomplete lock view
2. Reduce the cost of user understanding
3. Avoid deadlock of two transactions implicitly committed (optimistic transaction deadlock)

**Describe alternatives you've considered:**

No.

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close #31135

Problem Summary: add design doc for #31135

### What is changed and how it works?

Add design doc for #31135

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by bb7133** [comment]
Would you introduce some technical details on how the this will be implemented?

**Comment by jackysp** [comment]
> Would you introduce some technical details on how the this will be implemented?

It is not worth to do it, it's really simple. See https://github.com/pingcap/tidb/pull/32056 for details. @bb7133

**Comment by jackysp** [comment]
PTAL @cfzjywxk @MyonKeminta @bb7133 @coocood

**Review by coocood — APPROVED** [review]

**Review by MyonKeminta — COMMENTED** [review]
Can you add some description about the option you added, including the name of the option, how it's used (config file or sysvar) and its default value?

**Comment by jackysp** [comment]
> Can you add some description about the option you added, including the name of the option, how it's used (config file or sysvar) and its default value?

After discussing with @bb7133 , it seems unnecessary to write rfc for this minor change, so let's just look at the pr [implementation](https://github.com/pingcap/tidb/pull/32056). @MyonKeminta

**Pull request closed without merging**
