### PR TITLE
statistcs, executor: support history read for 'show stats_X' command

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve? 
Support read the historical statistics for `show stats_X` when `tidb_snapshot` is set.

Note:
This commit can *ONLY* fix the history read problem when we try to query the statistics manually, other 2 individual problems need to be fixed when we set `tidb_snapshot`:

1. When we dump stats using http-api, the data is the latest.
2. When we execute normal select_stmt, the statistics used is the latest. 

### What is changed and how it works?
Read from kv instead of the memory buffer when tidb_snapshot is set.

### Check List 

Tests 

 - Integration test

Code changes

 - Has exported function/method change

Side effects

 - Possible performance regression
We need to read data from the network when `tidb_snapshot` is set.

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
PAUSED
I'll support `dump history stats` before this commit.

**Comment by zz-jason** [comment]
I've removed my request review, you can add me again once this PR is ready to review.

**Comment by zz-jason** [comment]
@XuHuaiyu any update?

**Comment by XuHuaiyu** [comment]
This is paused, I'll reopen this PR when restarting this work.

**Pull request closed without merging**
