### PR TITLE
Add -u with go get in Makefile

### PR DESCRIPTION
**Pull request by genedna**

### CODE REVIEW

**Comment by shenli** [comment]
@genedna This pr does not pass ci. You can check the detail here: https://travis-ci.org/pingcap/tidb/builds/93735000.

**Comment by siddontang** [comment]
Hi @genedna 
using `get -u` may cause make very slow. I think the best way is to using godep for these directly later.

**Comment by Unknwon** [comment]
Please merge this PR... or provide better solution... current `make` just feel bad. :dizzy_face:

**Comment by Unknwon** [comment]
Maybe add a `make update` command?

**Comment by ngaut** [comment]
Good idea, thanks @Unknwon 
@genedna  Could you support "make update" in makefile ?

**Comment by Unknwon** [comment]
@ngaut https://github.com/pingcap/tidb/pull/680

**Pull request closed without merging**
