### PR TITLE
store/tikv : fix tiflash batch cop request timeout

### PR DESCRIPTION
**Pull request by hanfei1991**
### What problem does this PR solve?

Problem Summary:

After set @@global.tidb_allow_batch_cop = true and send query to tiflash; Sometimes it will report `TiKV server timeout error`. Observing the tidb log, it has many ["receive a grpc cancel signal from remote"] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"].

It's because client_batch.go will recycle "idle" connection, but TiFlash request does not use `client_batch` request, its connection is deleted by mistake.

### What is changed and how it works?

What's Changed:

I add *storeType* field for connArray. If the storeType is `TiFlash`, it will not be deleted.

### Release note 

- Fix `TiKV Server timeout` for tiflash batch cop.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
TiFlash have not implement the batch protocol yet?
Then I believe a much simpler fix is just an one line change here:

```
enableBatch := req.StoreTp == kv.TiKV
```

https://github.com/pingcap/tidb/pull/17212/files#diff-deb6c7bcc2ba593559c11d2e92f8d8dcL320

**Comment by tiancaiamao** [comment]
LGTM  @lysu
I have to gently remind that disable the idle recycle mechanism may have potential problems.
Maybe the TiFlash server is gone (panic or restart) and the conn is not available any more, but the `addr => conn` information cache in the batch client never got refresh, TiDB can't recovery for the case.

**Comment by ilovesoup** [comment]
This is a fix for super batch feature in 4.0. Is is possible to merge back to to 4.0?

**Comment by hanfei1991** [comment]
After discussion, tidb will not send batch commands to tiflash.

**Pull request closed without merging**
