### PR TITLE
expression: fix date_add func in SECOND INTERVAL (#11312)

### PR DESCRIPTION
**Pull request by SunRunAway**
Automated cherry pick of #11312 on release-2.1.
#11312: fix(types/time): deal negative number in second unit
test(expression/integration_test): add test case

### CODE REVIEW

**Comment by SunRunAway** [comment]
@wshwsh12 
It has a CI problem, it seems any pull request is not cherry-picked.

**Comment by wshwsh12** [comment]
> @wshwsh12
> It has a CI problem, it seems any pull request is not cherry-picked.

Ok, let me take a look. I seems that https://github.com/pingcap/tidb/pull/11479 has not cherry-pick. Now I am trying to deal with it.

**Comment by wshwsh12** [comment]
Now I have cherry-picked the PR you need. Please resolve conflicts. And I think it will work well. @SunRunAway

**Comment by SunRunAway** [comment]
@wshwsh12 @zz-jason PTAL again, thanks.

**Pull request merged**
