### PR TITLE
session: support system variable interactive_timeout (#8487)

### PR DESCRIPTION
**Pull request by hhxcc**
### What problem does this PR solve? 
support system variable interactive_timeout.  #8487

### What is changed and how it works?
when client set Capability Flags CLIENT_INTERACTIVE, init wait_timeout with interactive_timeout

### Check List 

Tests 
 - Integration test

Code changes
 - Has exported variable/fields change

Related changes
 - Need to be included in the release note

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8573)

### CODE REVIEW

**Comment by hhxcc** [comment]
@lysu  Could you help to write a integration test , please ?

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
