### PR TITLE
*: Modify placement rule index to reserve some indexes for future work

### LINKED ISSUE #29986: Modify placement rule index to reserve some future index for default/system rules

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #29986

Problem Summary:

For issue #29986 we are considering to provide some global policies but still have some questions to be discussed. But we can reserve some indexes first to avoid the compatibility problems in the future.

Also removed some indexes that have not been used yet

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
The priority index for placement rule changed
```

### CODE REVIEW

**Review by xhebox — COMMENTED** [review]
Maybe give a larger preserve range. It will work anyway.

**Comment by lcwangchao** [comment]
> Maybe give a larger preserve range. It will work anyway.

Any suggestions？

**Comment by xhebox** [comment]
> > Maybe give a larger preserve range. It will work anyway.
> 
> Any suggestions？

I would recommend use `0x30` as a length of each range, i.e.:

`0x00-0x2e` reserved
`0x2f` table
`0x30-0x5e` reserved
`0x5f` partition

and so on.

**Comment by lcwangchao** [comment]
> > > Maybe give a larger preserve range. It will work anyway.
> > 
> > 
> > Any suggestions？
> 
> It does not really matter. But I would recommend use `0x30` as a length of each range, i.e.:
> 
> `0x00-0x2e` reserved `0x2f` table `0x30-0x5e` reserved `0x5f` partition
> 
> and so on.
> 
> This way, you actually have a chance to insert rules to the reserved range, which will override the rules before it. You could leave some more for database and indicies, if you like.

Okay. But I prefer a decimal format instead of hexadecimal because it is easy to read in json body

**Review by xhebox — APPROVED** [review]

**Review by sylzd — APPROVED** [review]

**Pull request merged**
