### PR TITLE
expression: improve length and decimal size when a base type add/minus/multiply a decimal

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve? 
Check the code of tests or see issue #11868.

### What is changed and how it works?
Cast decimal shouldn't simply assign decimal a `types.UnspecifiedLength`. We should consider the origin type variable's decimal and the decimal return type also needs to distinguish add/minus/multiply.

### Check List 

Tests 

 - Unit test
 - Integration test

Side effects

 - Increased code complexity

### CODE REVIEW

**Comment by qw4990** [comment]
@lzmhhh123 Please fix CI problems.

**Comment by lzmhhh123** [comment]
@zz-jason @lamxTyler Please retake a look.

**Comment by lamxTyler** [comment]
@lzmhhh123 Do we need to pick this to 3.0 since the test is changed and 3.0 also uses that test?

**Comment by lzmhhh123** [comment]
@lamxTyler Okay.

**Pull request merged**
