### PR TITLE
expression: support builtin func password for GBK

### LINKED ISSUE #29092: Support GBK for builtin function `PasswordFunc `

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #29092

Problem Summary: support builtin func password for GBK

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @AilinKid 
PTAL

**Review by xiongjiwei — APPROVED** [review]

**Pull request merged**
