### PR TITLE
*: update memdb to use new fast random util

### PR DESCRIPTION
**Pull request by bobotu**
### What problem does this PR solve? 
After #15213 introduced the new fast random util, we can remove the empty `.S` file in memdb package and use this new util package directly.

### What is changed and how it works?
To resolve the cyclic import, I have moved the fast random functions into a new package named `fastrandom` and cleanup the name of them.

### Check List 

Tests 
 - No code

Code changes
 - Has exported function/method change

### CODE REVIEW

**Comment by bobotu** [comment]
PTAL @coocood @tiancaiamao

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
