### PR TITLE
expression: keep xor result consistent with mysql 8

### LINKED ISSUE #12867: The 'xor' result is different between tidb and mysql8
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select 0.001 xor 0;
```

2. What did you expect to see?
```
mysql root@127.0.0.1:(none)> select 0.001 xor 0;
+-------------+
| 0.001 xor 0 |
+-------------+
| 1           |
+-------------+
1 row in set
Time: 0.014s
mysql root@127.0.0.1:(none)> select version();
+-----------+
| version() |
+-----------+
| 8.0.17    |
+-----------+
1 row in set
Time: 0.014s
```

3. What did you see instead?
```
mysql root@127.0.0.1:(none)> select 0.001 xor 0;
+-------------+
| 0.001 xor 0 |
+-------------+
| 0           |
+-------------+
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql root@127.0.0.1:(none)> select tidb_version();
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-alpha-560-g12a3ce088                      |
| Git Commit Hash: 12a3ce088b91c20261dccf6d38102b42f54eff0f         |
| Git Branch: master                                                |
| UTC Build Time: 2019-10-19 07:44:32                               |
| GoVersion: go version go1.13 darwin/amd64                         |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by sduzh**
### What problem does this PR solve?

The 'xor' result is different between tidb and mysql8

Issue Number: close #12867 

Problem Summary:

### What is changed and how it works?

What's Changed:

Keep xor result consistent with MySQL 8, instead of MySQL 5.7

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Breaking backward compatibility

### CODE REVIEW

**Comment by sduzh** [comment]
Seems like the integration-test needs an update.  @SunRunAway

**Comment by SunRunAway** [comment]
> Seems like the integration-test needs an update. @SunRunAway

That's right, I'll do it later.

**Comment by SunRunAway** [comment]
After this PR,
W/ mocktikv
```mysql
mysql> drop table if exists txor;
Query OK, 0 rows affected (0.04 sec)

mysql> create table txor(a double);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into txor values (0.001);
Query OK, 1 row affected (0.01 sec)

mysql> select * from txor where a xor 0 ;
+-------+
| a     |
+-------+
| 0.001 |
+-------+
1 row in set (0.00 sec)
```


W/ TiKV,
```mysql
mysql> drop table if exists txor;
create table txor(a double);
insert into txor values (0.001);
select * from txor where a xor 0 ;
Query OK, 0 rows affected (0.20 sec)

mysql> create table txor(a double);
Query OK, 0 rows affected (0.08 sec)

mysql> insert into txor values (0.001);
Query OK, 1 row affected (0.01 sec)

mysql> select * from txor where a xor 0 ;
ERROR 1105 (HY000): other error: [components/tidb_query/src/batch/runner.rs:90]: BatchSelectionExecutor: Evaluate error: [components/tidb_query/src/rpn_expr/mod.rs:509]: ScalarFunction Unspecified is not supported in batch mode
```

**Comment by SunRunAway** [comment]
@wshwsh12 @zz-jason PTAL again. Thanks

**Pull request merged**
