### PR TITLE
expression: correct the signature building of Values

### PR DESCRIPTION
**Pull request by XuHuaiyu**
PTAL @shenli @coocood @zz-jason

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
Please cherry-pick to release-1.0.

**Comment by coocood** [comment]
LGTM
Remember to send PR from your forked tidb repo next time.

**Comment by shenli** [comment]
CI failed.

**Comment by winkyao** [comment]
@XuHuaiyu Please fix ci,

**Pull request merged**
