### PR TITLE
stmtctx, execdetails: migrate execdetails inside the stmtctx and related methods to execdetails

### LINKED ISSUE #51516: Move `execdetails` related methods from `stmtctx` to `execdetails`.
## Enhancement

There are a lot of functions implemented by `stmtctx`, but only related to `execdetails`. For example `MergeExecDetails`. We can move them to `execdetails` pkg.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #51516

Problem Summary:

### What changed and how does it work?

Move some methods only related to `execdetails` from `stmtctx` to `execdetails` pkg.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > - Should be covered by existing tests. All codes are just copied around.
  > 

### Release note

```release-note
None
```

### CODE REVIEW

**Review by lcwangchao — APPROVED** [review]

**Review by Defined2014 — APPROVED** [review]

**Comment by YangKeao** [comment]
Waiting for https://github.com/PingCAP-QE/tidb-test/pull/2262

**Pull request merged**
