### PR TITLE
parser: Support VECTOR type

### PR DESCRIPTION
**Pull request by breezewish**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/54245

Problem Summary:

### What changed and how does it work?

Support parsing the VECTOR type. However we does not support execute it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by bb7133** [comment]
Hi @hawkingrei @breezewish are we going to support vector in the next release(v8.3.0)?

**Comment by breezewish** [comment]
@bb7133 Hi, the VECTOR type support is planned this Q, but we have not estimated work time for it yet.

**Review by crazycs520 — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Comment by dveeden** [comment]
@breezewish Looks like somehow `keywords.go` wasn't updated?

```
dvaneeden@dve-carbon:~/dev/pingcap/tidb/pkg/parser$ make 
GO111MODULE=on go build -o bin/goyacc goyacc/main.go goyacc/format_yacc.go
gofmt (simplify)
bin/goyacc -o parser.go -p yy -t Parser parser.y
Parse table entries: 3306781 of 7804360, x 16 bits == 6613562 bytes
bin/goyacc -o hintparser.go -p yyhint -t hintParser hintparser.y
Parse table entries: 25978 of 42344, x 16 bits == 51956 bytes
go generate
dvaneeden@dve-carbon:~/dev/pingcap/tidb/pkg/parser$ git diff
diff --git a/pkg/parser/keywords.go b/pkg/parser/keywords.go
index 74dc5a1b32..004d51d661 100644
--- a/pkg/parser/keywords.go
+++ b/pkg/parser/keywords.go
@@ -622,6 +622,7 @@ var Keywords = []KeywordsType{
        {"VALIDATION", false, "unreserved"},
        {"VALUE", false, "unreserved"},
        {"VARIABLES", false, "unreserved"},
+       {"VECTOR", false, "unreserved"},
        {"VIEW", false, "unreserved"},
        {"VISIBLE", false, "unreserved"},
        {"WAIT", false, "unreserved"},
```

**Comment by breezewish** [comment]
> @breezewish Looks like somehow `keywords.go` wasn't updated?
> 
> ```
> dvaneeden@dve-carbon:~/dev/pingcap/tidb/pkg/parser$ make 
> GO111MODULE=on go build -o bin/goyacc goyacc/main.go goyacc/format_yacc.go
> gofmt (simplify)
> bin/goyacc -o parser.go -p yy -t Parser parser.y
> Parse table entries: 3306781 of 7804360, x 16 bits == 6613562 bytes
> bin/goyacc -o hintparser.go -p yyhint -t hintParser hintparser.y
> Parse table entries: 25978 of 42344, x 16 bits == 51956 bytes
> go generate
> dvaneeden@dve-carbon:~/dev/pingcap/tidb/pkg/parser$ git diff
> diff --git a/pkg/parser/keywords.go b/pkg/parser/keywords.go
> index 74dc5a1b32..004d51d661 100644
> --- a/pkg/parser/keywords.go
> +++ b/pkg/parser/keywords.go
> @@ -622,6 +622,7 @@ var Keywords = []KeywordsType{
>         {"VALIDATION", false, "unreserved"},
>         {"VALUE", false, "unreserved"},
>         {"VARIABLES", false, "unreserved"},
> +       {"VECTOR", false, "unreserved"},
>         {"VIEW", false, "unreserved"},
>         {"VISIBLE", false, "unreserved"},
>         {"WAIT", false, "unreserved"},
> ```

@dveeden  Thanks for pointing out! A fix is now proposed in https://github.com/pingcap/tidb/pull/54371

**Pull request merged**
