### PR TITLE
executor: reduce useless memory allocation in min/max aggregate

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
When I test aggregate function memory usage, I find a useless memory allocation.

Workload: TPCH sf = 1G
SQL:  desc analyze select min(L_ORDERKEY) from lineitem group by L_PARTKEY   ,L_SUPPKEY , L_QUANTITY;
Pprof: 
Showing nodes accounting for 3440.05MB, 99.45% of 3459.25MB total
Dropped 183 nodes (cum <= 17.30MB)
Showing top 10 nodes out of 29
      flat  flat%   sum%        cum   cum%
 1447.26MB 41.84% 41.84%  2454.81MB 70.96%  github.com/pingcap/tidb/executor.(*baseHashAggWorker).getPartialResult
  661.04MB 19.11% 60.95%   661.04MB 19.11%  github.com/pingcap/tidb/executor/aggfuncs.newMaxMinHeap (inline)
  346.51MB 10.02% 70.96%  1007.55MB 29.13%  github.com/pingcap/tidb/executor/aggfuncs.(*maxMin4Int).AllocPartialResult
  216.42MB  6.26% 77.22%   216.42MB  6.26%  github.com/pingcap/tidb/executor.(*HashAggFinalWorker).getFinalResult
  207.48MB  6.00% 83.22%   207.48MB  6.00%  google.golang.org/grpc.(*parser).recvMsg

We can see aggfuncs.newMaxMinHeap alloc 600MB+ memory, but in aggreagte function, the struct is never be used.
After I remove the memory allocation, the memory usage reduces 600MB.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
The struct `maxMinHeap` in `partialResult4MaxMinXXX` is used by `maxMin4XXXSliding`, and is only used in Window Function. When we using aggregate function, we shouldn't alloc the memory.

How it Works:
Only alloc maxMinHeap in maxMinXXXSliding.AllocPartialResult().

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- Reduce the memory usage of Max/Min aggregate function.

### CODE REVIEW

**Review by ichn-hu — APPROVED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
@ti-chi-bot help me

**Pull request merged**
