### PR TITLE
executor: fix unexpected NotNullFlag in case when expr ret type

### LINKED ISSUE #23036: The expression of "case when" on clustered_index table get wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE t (a int NOT NULL,  PRIMARY KEY (a));
insert into t values(1),(2);
select * from t WHERE (CASE WHEN NULL THEN a END) IS NULL ;
```

### 2. What did you expect to see? (Required)
```
+---+
| a |
+---+
| 1 |
| 2 |
+---+
```
### 3. What did you see instead (Required)
Empty set
### 4. What is your TiDB version? (Required)
Release Version: v4.0.0-beta.2-2215-g6bd6df7d1
Edition: Community
Git Commit Hash: 6bd6df7d1ec0b0a2056a5d40aca8261c5cbfa871
Git Branch: master
UTC Build Time: 2021-03-01 08:36:48
GoVersion: go1.15.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #23036 

Problem Summary: 

    drop table if exists t1;
    create table t1(c1 int not null);
    insert into t1 values(1);
    select (case when null then c1 end) is null from t1;

Output should be empty set, but TiDB output "1". Because when we fold constant for **IsNull expr**, optimizer found the result type of CaseWhen expr has **NotNullFlag**, which is unexpected. So rewriter return false directly

### What is changed and how it works?

What's Changed: 
1. Erase NotNullFlag from the result type of CaseWhen expr. Because we don't know will any when clause be true until runtime.
2. make types.setTypeFlag() public. (types.setTypeFlag() -> types.SetTypeFlag())

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test: Add cases in expression.TestBuiltin()

Side effects: no

### Release note 

-  fix unexpected NotNullFlag in case when expr ret type

### CODE REVIEW

**Comment by guo-shaoge** [comment]
PTAL @lzmhhh123

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Pull request merged**
