### PR TITLE
kv: reduce the memory footprint of new kv

### PR DESCRIPTION
**Pull request by bobotu**
### What problem does this PR solve?
The value of `memdbVlogHdr.oldValue` is always `nullAddr` for each new kv. We can use a bit flag instead of storing the value of `nullAddr` in vlog to save 8 bytes. 

### Check List 

Tests 

- Unit test

### Release note 

- No release note.

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by bobotu** [comment]
PTAL @tiancaiamao

**Comment by bobotu** [comment]
PTAL @tiancaiamao

**Comment by bobotu** [comment]
PTAL @tiancaiamao

**Comment by bobotu** [comment]
PTAL @tiancaiamao

**Comment by bobotu** [comment]
This PR is pending review for a long time. I personally do not have enough time to follow this thread up in the future, so I'm going to close this PR.

For someone interested in this topic: 
It will be appreciated if you would like to open a new PR based on this idea. It is also a pleasure if you intend to reopen this PR and take over the work.

**Pull request closed without merging**
