### PR TITLE
lightning: remove alter table lock

### LINKED ISSUE #50105: remove alter table lock to improve performance when importing large mount of tables
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

here we run `alter table` in serial(add in https://github.com/pingcap/tidb-lightning/pull/87), we can run in parallel now and let tidb handle it

it's an enhancement, will make a bug to cp to older versions

https://github.com/pingcap/tidb/blob/d11a559ae2beb02c70996fb3bf03006aa3c9524f/br/pkg/lightning/importer/table_import.go#L954

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #50105

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
import large mount of tables(each table is about several tens of MB), after this pr, we can import from 674 tables/h/instance -> 809. Since TiDB still handle `alter table` in serial internally, the speedup is not that obvious. Note we are importing using 10 lightning, some instance have more improvement
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by D3Hunter** [comment]
/hold

to wait lightning ci

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Comment by D3Hunter** [comment]
ci pass
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_lightning_integration_test/detail/pull_lightning_integration_test/14/

**Pull request merged**
