### PR TITLE
planner: refactor Converting Partition Keys for shuffle hash join (#24456)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #24456 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/24490
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/24490:release-5.0-0859a3c029ad
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tics/issues/1865 

Problem Summary:
we should enforce a projection for hash partition join only for the partition keys which are a subset of join keys, but the current code enforces a projection for all join keys.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

### Release note 

- refactor converting partition keys for shuffle hash join

### CODE REVIEW

**Comment by rebelice** [comment]
Please handle the conflict

**Review by rebelice — APPROVED** [review]
/lgtm

**Review by hanfei1991 — APPROVED** [review]

**Pull request merged**
