### PR TITLE
[cherry-pick] mod: update the pd client

### PR DESCRIPTION
**Pull request by nolouch**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/47421 ref https://github.com/tikv/pd/issues/8349

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by glorv — DISMISSED** [review]

**Review by JmPotato — APPROVED** [review]

**Comment by nolouch** [comment]
ptal again @glorv

**Review by glorv — APPROVED** [review]

**Pull request merged**
