### PR TITLE
*: add an option to enable pessimistic mode for auto-commit transactions

### LINKED ISSUE #31135: Add an option to have all types of transactions be in pessimistic mode
## Feature Request

**Is your feature request related to a problem? Please describe:**

Implicit transactions are still executed in optimistic mode even if the pessimistic transaction option is turned on, which is hard to explain to uses. And often we fall into the same trap when troubleshooting problems ourselves. Also, for the lock view, since it reads info from the wait manager, the lock view is not available for optimistic transactions. Therefore, due to the optimistic implicit transactions, causing incomplete lock information can also cause confusion to users.

**Describe the feature you'd like:**

Unify all types of transactions in pessimistic mode, and implicit transactions are also in pessimistic mode.

1. Solve the problem of incomplete lock view
2. Reduce the cost of user understanding
3. Avoid deadlock of two transactions implicitly committed (optimistic transaction deadlock)

**Describe alternatives you've considered:**

No.

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close #31135

Problem Summary:
Add an option to enable pessimistic for auto-commit transactions.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. start a cluster and set `pessimistic-auto-commit = true` in config file
2. run sysbench update non index on pessimistic mode
3. check the results
截屏2022-01-30 下午3 51 30

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Add an option to enable pessimistic mode for auto-commit transactions.
```

### CODE REVIEW

**Comment by coocood** [comment]
Have you considered use session/global variable to control it?

**Comment by jackysp** [comment]
> Have you considered use session/global variable to control it?

With variables, I'm worried about introducing some historical baggage that I'm more worried about not being out of control in the future. If, someday, TiDB's auto-commit transactions don't have much performance difference between the two locking modes, I will remove this switch. @coocood

**Review by coocood — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
We may need to update the document as well.

**Comment by jackysp** [comment]
> We may need to update the document as well.

sure

**Pull request merged**
