### PR TITLE
ddl: split disttask scheduler to different stage

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: ref #41495.

Problem Summary:

This is a refactor PR for `ddlScheduler`.

### What is changed and how it works?

`ddlScheduler` is split into two stages, `readIndexToLocalStage` and `ingestIndexStage`. It is much clear than using `stepForImport` to distinguish these stages.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by ywqzzy** [comment]
rename file to xx-stage.go?
Rest LGTM

**Review by ywqzzy — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
