### PR TITLE
ddl: fix the covert job to rollingback job (#23903)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23903 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/24080
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/24080:release-5.0-4db325d04803
```

---

Signed-off-by: AilinKid <314806019@qq.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23893

Once `convertJob2RollbackJob` meets error, the job state can't be set as `JobStateRollingback` since
job state and args may not be correctly overwritten. The job will be fetched to run with the canceling
state again. So we should check the error count here.

### What is changed and how it works?

What's Changed:
 
1. change all the rollingback assignments to the last step in all ddl canceling logic.   
**This is aim to get rid of invalid job state and job args, while the job is assigned with rollingback state, which will lead errors in following rollingback logic, for example, json unmarshal error.**

2. Add error count check and force it be canceled in convertJob2RollbackJob
**This is aim to get rid of the infinite loop of canceling action once `convertJob2RollbackJob` gets an error.**

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- ddl: fix the covert job to rollingback job

### CODE REVIEW

**Comment by AilinKid** [comment]
PTAL @tangenta @crazycs520

**Review by tangenta — COMMENTED** [review]
/lgtm

**Review by tangenta — APPROVED** [review]

**Pull request merged**
