### PR TITLE
Revert "store/tikv: turn-off 'Sum' and 'Avg'."

### PR DESCRIPTION
**Pull request by shenli**
Reverts pingcap/tidb#1635 Merge after https://github.com/pingcap/tikv/pull/977
@coocood @zimulala PTAL

### CODE REVIEW

**Comment by coocood** [comment]
`columnNameToPBExpr` need to change too.

**Comment by shenli** [comment]
@coocood PTAL

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
@zimulala PTAL

**Pull request closed without merging**
