### PR TITLE
*: support auto_random on composite clustered primary key

### LINKED ISSUE #38572: ddl: allow defining auto_random on composite primary key
## Enhancement

For now, TiDB doesn't allow defining AUTO_RANDOM attribute on composite primary keys, even when the key is the clustered index:

```
mysql> create table log ( id bigint auto_random, b bigint, create_time datetime not null, primary key(id, create_time));
ERROR 8216 (HY000): Invalid auto random: column id is not the integer primary key, or the primary key is nonclustered
```

Sometimes defining a primary key is useful, for example, to match the requirement of partition keys, so we could relax this restriction.

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #38572

Problem Summary: 

> For now, TiDB doesn't allow defining AUTO_RANDOM attribute on composite primary keys, even when the key is the clustered index:
> 
> Sometimes defining a primary key is useful, for example, to match the requirement of partition keys, so we could relax this restriction.

### What is changed and how it works?

This PR allows the AUTO_RANDOM attribute to be defined on the column that is the first column in a clustered composite primary key. For example, 

```sql
mysql> create table t (a bigint auto_random, b int, primary key(a, b) clustered);
Query OK, 0 rows affected, 1 warning (0.03 sec)
``` 

However, if the column is not the first column in a composite primary key, it still returns an error:

```sql
mysql> create table t (a bigint auto_random, b int, primary key(b, a) clustered);
ERROR 8216 (HY000): Invalid auto random: column 'a' must be the first column in primary key
```

There are two reasons to impose such a restriction:

- From the users' perspective, defining such a AUTO_RANDOM column is useless to eliminating the write hot spot, which is a key function of AUTO_RANDOM.
- From the DB developers' perspective, AUTO_RANDOM is actually a table attribute. To relax this restriction, we need to add a field type flag like `auto_random_flag` to identify whether a column is AUTO_RANDOM, which means the more code changes.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Support defining AUTO_RANDOM on the first column in a composite clustered primary key.
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Review by xiongjiwei — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by tangenta** [comment]
/hold

@easonn7 PTAL

**Pull request merged**
