### PR TITLE
txn, session, test: Try to stabilize testTxnStateSerialSuite.TestRunning and TestBlocked

### LINKED ISSUE #27116: Unstable test `testTxnStateSerialSuite.TestBlocked`
## Bug Report
```
[2021-08-11T07:52:49.269Z] FAIL: session_test.go:4455: testTxnStateSerialSuite.TestBlocked

[2021-08-11T07:52:49.269Z] 

[2021-08-11T07:52:49.269Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:217:

[2021-08-11T07:52:49.269Z]     tk.c.Assert(err, check.IsNil, check.Commentf("sql:%s, %v, error stack %v", sql, args, errors.ErrorStack(err)))

[2021-08-11T07:52:49.269Z] ... value *errors.withMessage = previous statement: select * from t where a = 1 for update;: [domain:8028]Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]

[2021-08-11T07:52:49.269Z] ... sql:commit;, [], error stack [domain:8028]Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]

[2021-08-11T07:52:49.270Z] github.com/pingcap/errors.AddStack

[2021-08-11T07:52:49.270Z] 	/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/errors.go:174

[2021-08-11T07:52:49.270Z] github.com/pingcap/errors.Trace

[2021-08-11T07:52:49.270Z] 	/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/juju_adaptor.go:15

[2021-08-11T07:52:49.270Z] github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).checkSchemaValid

[2021-08-11T07:52:49.270Z] 	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20210806085616-14892a598eab/txnkv/transaction/2pc.go:1620

[2021-08-11T07:52:49.270Z] github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).execute

[2021-08-11T07:52:49.270Z] 	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20210806085616-14892a598eab/txnkv/transaction/2pc.go:1312

[2021-08-11T07:52:49.270Z] github.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).Commit

[2021-08-11T07:52:49.270Z] 	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20210806085616-14892a598eab/txnkv/transaction/txn.go:379

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/store/driver/txn.(*tikvTxn).Commit

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/driver/txn/txn_driver.go:71

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/session.(*LazyTxn).Commit

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/txn.go:364

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/session.(*session).commitTxnWithTemporaryData

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:578

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/session.(*session).doCommit

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:571

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/session.(*session).doCommitWithRetry

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:702

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/session.(*session).CommitTxn

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:764

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/session.autoCommitAfterStmt

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/tidb.go:254

[2021-08-11T07:52:49.270Z] --

[2021-08-11T07:52:49.270Z] FAIL: session_test.go:4439: testTxnStateSerialSuite.TestRunning

[2021-08-11T07:52:49.270Z] 

[2021-08-11T07:52:49.270Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:217:

[2021-08-11T07:52:49.270Z]     tk.c.Assert(err, check.IsNil, check.Commentf("sql:%s, %v, error stack %v", sql, args, errors.ErrorStack(err)))

[2021-08-11T07:52:49.270Z] ... value *errors.withMessage = previous statement: select * from t for update;: [domain:8028]Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]

[2021-08-11T07:52:49.270Z] ... sql:commit;, [], error stack [domain:8028]Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]

[2021-08-11T07:52:49.270Z] github.com/pingcap/errors.AddStack

[2021-08-11T07:52:49.270Z] 	/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/errors.go:174

[2021-08-11T07:52:49.270Z] github.com/pingcap/errors.Trace

[2021-08-11T07:52:49.270Z] 	/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/juju_adaptor.go:15

[2021-08-11T07:52:49.270Z] github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).checkSchemaValid

[2021-08-11T07:52:49.270Z] 	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20210806085616-14892a598eab/txnkv/transaction/2pc.go:1620

[2021-08-11T07:52:49.270Z] github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).execute

[2021-08-11T07:52:49.270Z] 	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20210806085616-14892a598eab/txnkv/transaction/2pc.go:1312

[2021-08-11T07:52:49.270Z] github.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).Commit

[2021-08-11T07:52:49.270Z] 	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20210806085616-14892a598eab/txnkv/transaction/txn.go:379

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/store/driver/txn.(*tikvTxn).Commit

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/driver/txn/txn_driver.go:71

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/session.(*LazyTxn).Commit

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/txn.go:364

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/session.(*session).commitTxnWithTemporaryData

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:578

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/session.(*session).doCommit

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:571

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/session.(*session).doCommitWithRetry

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:702

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/session.(*session).CommitTxn

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:764

[2021-08-11T07:52:49.270Z] github.com/pingcap/tidb/session.autoCommitAfterStmt

[2021-08-11T07:52:49.270Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/tidb.go:254

[2021-08-11T07:52:49.270Z] + false
```
Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/24756/pipeline

### PR DESCRIPTION
**Pull request by longfangsong**
### What problem does this PR solve?

Issue Number: close #27116

Problem Summary:

`testTxnStateSerialSuite.TestRunning` and `testTxnStateSerialSuite.TestBlocked` break sometimes.

### What is changed and how it works?

- Wait for all goroutings finished before return from the test
- Use "pause" instead of "sleep" when possible
- Sleep longer if we must
- Use `beforeLockKeys` instead of `mockStmtSlow`(which will also block "commit")

### Check List 

Tests 

- [x] Unit test

Side effects

NA

Documentation

NA

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by bb7133** [comment]
PTAL @xhebox @lysu @tiancaiamao

**Review by lysu — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Comment by longfangsong** [comment]
Still cannot figure out why `check_dev_2` failed.
Maybe related with #27410.

**Comment by longfangsong** [comment]
Now blocked by #27328.

**Review by tiancaiamao — APPROVED** [review]

**Review by lysu — APPROVED** [review]

**Pull request merged**
