### PR TITLE
*: Support query backoff detail in SLOW_QUERY and add runtime stats columns to STATEMENTS_SUMMARY、SLOW_QUERY (#20300)

### LINKED ISSUE #20025: Add additional runtime stats columns to SLOW_QUERY, STATEMENTS_SUMMARY, STATEMENTS_SUMMARY_HISTORY
## Development Task

Currently, some runtime information already log in the slow-log file, but doesn't obtained in `SLOW_QUERY`, `STATEMENTS_SUMMARY`, `STATEMENTS_SUMMARY_HISTORY`.

* `KV_total`
* `PD_total`
* `Backoff_total`
* `Write_sql_response_total`
* `Prepared`

## reference

You can refer PR: https://github.com/pingcap/tidb/pull/19625

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20300 to release-4.0

---

<!-- Thank you for contributing to TiDB!

PR Title Format:
1. pkg [, pkg2, pkg3]: what's changed
2. *: what's changed

-->

### What problem does this PR solve?

Issue Number: close #20025 #17938 
 <!-- REMOVE this line if no issue to close -->

Problem Summary:
Currently, slow log records the backoff detail in slow log.But can't query this backoff-detail from `SLOW_QUERY`/`CLUSTER_SLOW_QUERY`. Also, some runtime information already log in the slow-log file, but doesn't obtained in `SLOW_QUERY`, `STATEMENTS_SUMMARY`, `STATEMENTS_SUMMARY_HISTORY`.
- KV_total
- PD_total
- Backoff_total
- Write_sql_response_total
- Prepared

### What is changed and how it works?
What's Changed:
Add `KV_total, PD_total, Backoff_total, Write_sql_response_total, Prepared, Backoff_Detail` to table `Slow_Query` columns.
Add `SUM_KV_total, SUM_PD_total, SUM_Backoff_total, SUM_Write_sql_response_total, Prepared` to table `STATEMENTS_SUMMARY` columns.

#### Slow_Query table:
```
mysql> select KV_total,PD_total,Backoff_total,Write_sql_response_total,Backoff_Detail,Prepared from information_schema.slow_query limit 1;
+----------+----------+---------------+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
| KV_total | PD_total | Backoff_total | Write_sql_response_total | Backoff_Detail                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | Prepared |
+----------+----------+---------------+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
|        0 |        0 |             0 |                        0 | Cop_backoff_regionMiss_total_times: 200 Cop_backoff_regionMiss_total_time: 0.2 Cop_backoff_regionMiss_max_time: 0.2 Cop_backoff_regionMiss_max_addr: 127.0.0.1 Cop_backoff_regionMiss_avg_time: 0.2 Cop_backoff_regionMiss_p90_time: 0.2Cop_backoff_rpcPD_total_times: 200 Cop_backoff_rpcPD_total_time: 0.2 Cop_backoff_rpcPD_max_time: 0.2 Cop_backoff_rpcPD_max_addr: 127.0.0.1 Cop_backoff_rpcPD_avg_time: 0.2 Cop_backoff_rpcPD_p90_time: 0.2Cop_backoff_rpcTiKV_total_times: 200 Cop_backoff_rpcTiKV_total_time: 0.2 Cop_backoff_rpcTiKV_max_time: 0.2 Cop_backoff_rpcTiKV_max_addr: 127.0.0.1 Cop_backoff_rpcTiKV_avg_time: 0.2 Cop_backoff_rpcTiKV_p90_time: 0.2 |        0 |
+----------+----------+---------------+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
1 row in set (0.01 sec)
```
#### statements_summary table
```
mysql> select SUM_KV_TOTAL,SUM_PD_TOTAL,SUM_BACKOFF_TOTAL,SUM_WRITE_SQL_RESP_TOTAL,PREPARED from information_schema.statements_summary limit 1;
+--------------+--------------+-------------------+--------------------------+----------+
| SUM_KV_TOTAL | SUM_PD_TOTAL | SUM_BACKOFF_TOTAL | SUM_WRITE_SQL_RESP_TOTAL | PREPARED |
+--------------+--------------+-------------------+--------------------------+----------+
|            0 |            0 |                 0 |                    15951 |        0 |
+--------------+--------------+-------------------+--------------------------+----------+
1 row in set (0.00 sec)
```
#### statements_summary_history table
```
mysql> select SUM_KV_TOTAL,SUM_PD_TOTAL,SUM_BACKOFF_TOTAL,SUM_WRITE_SQL_RESP_TOTAL,PREPARED from information_schema.statements_summary_history limit 1;
+--------------+--------------+-------------------+--------------------------+----------+
| SUM_KV_TOTAL | SUM_PD_TOTAL | SUM_BACKOFF_TOTAL | SUM_WRITE_SQL_RESP_TOTAL | PREPARED |
+--------------+--------------+-------------------+--------------------------+----------+
|            0 |            0 |                 0 |                     4560 |        0 |
+--------------+--------------+-------------------+--------------------------+----------+
1 row in set (0.00 sec)
```

#### CLUSTER_SLOW_QUERY table
```
mysql> select KV_total,PD_total,Backoff_total,Write_sql_response_total,Backoff_Detail,Prepared from information_schema.CLUSTER_SLOW_QUERY limit 1;
+----------+----------+---------------+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
| KV_total | PD_total | Backoff_total | Write_sql_response_total | Backoff_Detail                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | Prepared |
+----------+----------+---------------+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
|        0 |        0 |             0 |                        0 | Cop_backoff_regionMiss_total_times: 200 Cop_backoff_regionMiss_total_time: 0.2 Cop_backoff_regionMiss_max_time: 0.2 Cop_backoff_regionMiss_max_addr: 127.0.0.1 Cop_backoff_regionMiss_avg_time: 0.2 Cop_backoff_regionMiss_p90_time: 0.2Cop_backoff_rpcPD_total_times: 200 Cop_backoff_rpcPD_total_time: 0.2 Cop_backoff_rpcPD_max_time: 0.2 Cop_backoff_rpcPD_max_addr: 127.0.0.1 Cop_backoff_rpcPD_avg_time: 0.2 Cop_backoff_rpcPD_p90_time: 0.2Cop_backoff_rpcTiKV_total_times: 200 Cop_backoff_rpcTiKV_total_time: 0.2 Cop_backoff_rpcTiKV_max_time: 0.2 Cop_backoff_rpcTiKV_max_addr: 127.0.0.1 Cop_backoff_rpcTiKV_avg_time: 0.2 Cop_backoff_rpcTiKV_p90_time: 0.2 |        0 |
+----------+----------+---------------+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
1 row in set (0.01 sec)
```
### Related changes
- Need to cherry-pick to the release branch

### Check List <!--REMOVE the items that are not applicable-->

Tests <!-- At least one of them must be included. -->

- Unit test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note <!-- bugfixes or new feature need a release note -->

- Support query backoff detail in SLOW_QUERY and add runtime stats columns to STATEMENTS_SUMMARY、SLOW_QUERY

### CODE REVIEW

**Comment by crazycs520** [comment]
@jyz0309 Please help to fix the conflict.

**Review by djshow832 — COMMENTED** [review]
LGTM

**Review by crazycs520 — COMMENTED** [review]
LGTM

@djshow832 PTAL

**Review by zz-jason — APPROVED** [review]
LGTM

**Pull request merged**
