### PR TITLE
expression: Push down json_contains to tikv

### LINKED ISSUE #37839: Support json_contains push down  to TiKV
## Enhancement
Now TiDB support some json function to TiKV : json_extract
We should also support json_contains function to tikv

### PR DESCRIPTION
**Pull request by lizhenhuan**
### What problem does this PR solve?

Issue Number:  close #37839

Problem Summary:
Implement json_contains function push down to tikv

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lizhenhuan** [comment]
image

**Comment by YangKeao** [comment]
The MySQL test failed, because the following SQL has different behavior after pushdown:

```
create table t1 (f1 json);
SELECT 1 FROM t1 WHERE f1 LIKE json_contains('key2' ,'key4' );
```

Before this PR, it returns ERROR 3141 (json format error). With this PR, it returns ERROR 1105 (unknown error). I guess there are some problems in the unistore, but not sure. PTAL

**Comment by YangKeao** [comment]
> The MySQL test failed, because the following SQL has different behavior after pushdown:
> 
> ```
> create table t1 (f1 json);
> SELECT 1 FROM t1 WHERE f1 LIKE json_contains('key2' ,'key4' );
> ```
> 
> Before this PR, it returns ERROR 3141 (json format error). With this PR, it returns ERROR 1105 (unknown error). I guess there are some problems in the unistore, but not sure. PTAL

https://github.com/pingcap/tidb/pull/38257 could fix this problem.

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by xiongjiwei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
