### PR TITLE
planner: fix window which depends on another

### PR DESCRIPTION
**Pull request by b41sh**
### What problem does this PR solve? 

fix window function: A window which depends on another cannot define partitioning
[#11007](https://github.com/pingcap/tidb/issues/11007)

### What is changed and how it works?

Modify the order of error judgments

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by SunRunAway** [comment]
Hi, Thanks for you PR.
Could you add a unit test?

**Comment by b41sh** [comment]
@SunRunAway I have add a unit test  PTAL

**Comment by cyliu0** [comment]
@b41sh This PR has been labeled with `needs-cherry-pick-3.0`. Plz cherry pick this one to release-3.0 and maybe consider to cherry pick it to release-3.1

**Pull request merged**
