### PR TITLE
br: Add system table from v5.3.0 into blacklist which shouldn't be restored

### PR DESCRIPTION
**Pull request by joccau**
Signed-off-by: joccau <zak.zhao@pingcap.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/29693

Problem Summary:
Prevent users from restoring system tables from V5.3.0, and add these system table into backlist

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

`./bin/br restore table --db mysql --table column_stats_usage --pd "172.16.6.117:22261" --storage "local:///tmp/gc"
Detail BR log in /var/folders/37/dyx4gvk55hx8wvl6j4mpr81w0000gn/T/br.log.2021-11-11T19.35.03+0800
Table restore <--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------> 100.00%
[2021/11/11 19:35:06.148 +08:00] [INFO] [collector.go:65] ["Table restore success summary"] [total-ranges=0] [ranges-succeed=0] [ranges-failed=0] [split-region=597.838875ms] [restore-ranges=0] [total-take=3.117879417s] [Result="Nothing to restore"] [Size=0] [BackupTS=429032866835333121]
`

### Release note

```release-note
None
```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]

**Comment by YuJuncen** [comment]
BTW, i guess we'd better make an allow list instead of a deny list here... 🤔

**Review by kennytm — APPROVED** [review]

**Pull request merged**
