### PR TITLE
util/hack: remove pingcap/check for utils/hack

### LINKED ISSUE #26181: migrate test-infra to testify for `util/hack` pkg

### PR DESCRIPTION
**Pull request by jyz0309**
Signed-off-by: jyz0309 <45495947@qq.com>

### What problem does this PR solve?

Issue Number: close #26181 

### What is changed and how it works?

What's Changed:
remove `pingcap/check` for `utils/hack`

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note 

-  remove pingcap/check for utils/hack

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]

**Comment by tisonkun** [comment]
@jyz0309 I submitted a PR https://github.com/jyz0309/tidb/pull/1 on this PR for using testify checkers to reduce code.

**Review by disksing — APPROVED** [review]

**Pull request merged**
