### PR TITLE
planner: support point get by `_tidb_rowid`

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve? 
As the title says.

### What is changed and how it works?
When trying to build the point_get plan. Check where `_tidb_rowid` can build a point_get plan when the primary key is not the handle.

### Check List 

Tests 

 - Unit test
 - Integration test

Side effects

 - Increased code complexity

### CODE REVIEW

**Comment by francis0407** [comment]
Shall we cherry-pick this to the release branch?

**Comment by XuHuaiyu** [comment]
@lzmhhh123 Do we need to cherry-pick this to releaes-2.1?

If not, please remove the label `needs-cherry-pick-2.1`

**Pull request merged**
