### PR TITLE
sessionctx/variable: fix select variable return wrong result when variable is only global scope variable (#8968)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
cherry-pick #8968

### Check List 

Tests

### CODE REVIEW

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.0 pd-release-2.0 tikv=release-2.0

**Comment by crazycs520** [comment]
/run-unit-test tidb-test=release-2.0 pd-release-2.0 tikv=release-2.0

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.0 pd-release-2.0 tikv=release-2.0

**Comment by zhouqiang-cl** [comment]
/run-integration-ddl-test tidb-test=release-2.0 pd-release-2.0 tikv=release-2.0

**Comment by zhouqiang-cl** [comment]
/run-unit-test tidb-test=release-2.0 pd-release-2.0 tikv=release-2.0

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.0 pd-release-2.0 tikv=release-2.0

**Comment by crazycs520** [comment]
@winkyao @XuHuaiyu PTAL

**Pull request merged**
