### PR TITLE
types: `Datum.ToString()` missed the case when datum is `kindNull`.

### PR DESCRIPTION
**Pull request by winoros**
Just as title said.
PTAL @zz-jason @lamxTyler @XuHuaiyu

### CODE REVIEW

**Comment by shenli** [comment]
Please add a test case.

**Comment by winkyao** [comment]
@winoros Plz fix ci, and add some test cases

**Comment by coocood** [comment]
What if the string value is `NULL`?
Missing null type prevents us from forgetting to check null.

**Comment by winoros** [comment]
@coocood show stats_buckets will use `DatumsToString` and may meet `NULL` values.

**Comment by coocood** [comment]
@winoros 
We can check NULL in `show stats_buckets`

**Pull request closed without merging**
