### PR TITLE
doc: fix example for partition table

### LINKED ISSUE #33326: example of partition table in tidb_http_api.md is weird
## Bug Report

    *Hint: On a partitioned table, use the `table(partition)` pattern as the table name, `test(p1)` for example:*

    ```shell
    $curl http://127.0.0.1:10080/mvcc/index/test(p1)/t1/idx/1\?a\=A
    ```

### PR DESCRIPTION
**Pull request by ekexium**
Signed-off-by: ekexium <ekexium@gmail.com>

### What problem does this PR solve?

Issue Number: close #33326 
Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

**Comment by tiancaiamao** [comment]
PTAL @mjonss

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
