### PR TITLE
executor: fix bug of stuck in query information_schema.columns (#18847)

### PR DESCRIPTION
**Pull request by crazycs520**
cherry-pick #18847 to release-4.0

---

Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

fix https://github.com/pingcap/tidb/issues/18845

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- 

### Release note 

- fix the issue of getting stuck when querying information_schema.columns

### CODE REVIEW

**Comment by imtbkcat** [comment]
/run-all-tests tidb-test=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by imtbkcat** [comment]
/run-integration-copr-test tidb-test=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by imtbkcat** [comment]
/run-all-tests=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by imtbkcat** [comment]
/run-all-tests tidb-test=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by imtbkcat** [comment]
/run-all-tests tidb-test=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by crazycs520** [comment]
/run-common-test  tidb-test=release-4.0 tikv=release-4.0 pd=release-4.0
/run-integration-common-test  tidb-test=release-4.0 tikv=release-4.0 pd=release-4.0
/run-integration-ddl-test   tidb-test=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by imtbkcat** [comment]
/run-common-test tidb-test=release-4.0 tikv=release-4.0 pd=release-4.0
/run-integration-copr-test tidb-test=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by imtbkcat** [comment]
/run-integration-compatibility-test tidb-test=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by imtbkcat** [comment]
/run-integration-compatibility-test tidb-test=release-4.0 tikv=release-4.0 pd=release-4.0

**Pull request merged**
