### PR TITLE
executor, util: fix invalid time format "YY-MM-DD HH:MM"(#3509)

### PR DESCRIPTION
**Pull request by XuHuaiyu**
fix issue #3509 
PTAL @shenli @tiancaiamao

### CODE REVIEW

**Comment by tiancaiamao** [comment]
CI fail, seems timezone issue, try to change the `builtinUnixTimestampSig` to use UTC. @XuHuaiyu

**Comment by hanfei1991** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
PTAL @tiancaiamao

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
