### PR TITLE
br : migrate test-infra to testify for lightning/backend/tidb/tidb_test.go

### LINKED ISSUE #29982: migrate test-infra to testify for `lightning/backend/tidb`

### PR DESCRIPTION
**Pull request by JayL-zxl**
### What problem does this PR solve?

Issue Number: close #29982 
migrate test-infra to testify for lightning/backend/tidb/tidb_test
Problem Summary:

### Check List

Tests 

- Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Review by zhangyangyu — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]
/merge

**Pull request merged**
