### PR TITLE
ddl: convert hexLit to stringLit in enum and set default value. (#20459)

### LINKED ISSUE #18977: Can't create latin1 enum
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql root@127.0.0.1:test> create table t1 (a enum(0xE4, '1', '2') not null default 0xE4) character set latin1;
```

### 2. What did you expect to see? (Required)
```
mysql root@127.0.0.1:test> create table t1 (a enum(0xE4, '1', '2') not null default 0xE4) character set latin1;
Query OK, 0 rows affected
Time: 0.024s
mysql root@127.0.0.1:test> show create table t1
+-------+----------------------------------------------+
| Table | Create Table                                 |
+-------+----------------------------------------------+
| t1    | CREATE TABLE `t1` (                          |
|       |   `a` enum('ä','1','2') NOT NULL DEFAULT 'ä' |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=latin1       |
+-------+----------------------------------------------+
1 row in set
Time: 0.016s
```

### 3. What did you see instead (Required)
```
mysql root@127.0.0.1:test> create table t1 (a enum(0xE4, '1', '2') not null default 0xE4) character set latin1;
(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 28 near "0xE4, \'1\', \'2\') not null default 0xE4) character set latin1" ')
```

### 4. Affected version (Required)

```
mysql root@127.0.0.1:test> select tidb_version()
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-888-g4645c6582                     |
| Edition: Community                                                |
| Git Commit Hash: 4645c6582d7d57ae256b1bd7a1c18476c56b4d3c         |
| Git Branch: master                                                |
| UTC Build Time: 2020-08-04 07:06:10                               |
| GoVersion: go1.14.4                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
1 row in set
Time: 0.015s
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20459 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #18977 

Problem Summary:

```
mysql> create table t1 (a enum(0xE4, '1', '2') not null default 0xE4) character set latin1;                                                                
(1067, "Invalid default value for 'a'")
```

### What is changed and how it works?

What's Changed:

When the datum kind is mysql.TypeEnum, the value should be stored as a string instead of an integer number.

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

- None

### Release note 

- fix cannot create enum and set column if its default value is hexLit

### CODE REVIEW

**Comment by zz-jason** [comment]
@tangwz could you help to resolve the conflicts and fix CI?

**Comment by tangwz** [comment]
@tangenta @wjhuang2016 PTAL.

Thanks.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by tangenta — COMMENTED** [review]
LGTM

**Review by tiancaiamao — APPROVED** [review]

**Comment by tangwz** [comment]
@tiancaiamao PTAL

**Pull request merged**
