### PR TITLE
lightning: fix init error-manager

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### What is changed and how it works?
Fix the bug this error-manager skip init schemas and tables because a field is not inited.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
  - `integration-br-test` contains the duplicate detect case
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by gozssky — APPROVED** [review]

**Review by kennytm — APPROVED** [review]

**Comment by kennytm** [comment]
```
[2021-11-15T09:14:28.663Z] FAIL: executor_test.go:52: testChecksumSuite.TestChecksum

[2021-11-15T09:14:28.663Z] 

[2021-11-15T09:14:28.663Z] executor_test.go:53:

[2021-11-15T09:14:28.663Z]     c.Assert(s.mock.Start(), IsNil)

[2021-11-15T09:14:28.663Z] ... value *errors.withStack = unix socket /tmp/tidb-{Port}.sock exists and is functional, not removing it ("unix socket /tmp/tidb-{Port}.sock exists and is functional, not removing it")
```

🤔

**Pull request merged**
