### PR TITLE
lightning: move invalid and dirty checkpoint's check in dataCheck.

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/27157 & https://github.com/pingcap/tidb/issues/27151

### What is changed and how it works?

What's Changed:
1. move invalid and dirty checkpoint's check in dataCheck.
2. remove duplicated check output.
### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by glorv — APPROVED** [review]

**Review by Little-Wallace — APPROVED** [review]
LGTM

**Comment by 3pointer** [comment]
/needs-cherry-pick-5.2

**Pull request merged**
