### PR TITLE
executor: remove old, never used "IndexLookUpJoin"

### PR DESCRIPTION
**Pull request by zz-jason**
IndexLookUpJoin is never used since all the executors are supporting chunk execution now

### CODE REVIEW

**Comment by ngaut** [comment]
Nice clean up.

**Comment by winoros** [comment]
Please rename the file. `new_index_lookup_join.go`->`index_join.go`.

**Comment by zz-jason** [comment]
@coocood @winoros PTAL

**Comment by shenli** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Pull request merged**
