### PR TITLE
infoschema_v2: disable tidb schema cache size

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: ref #50959 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
```
mysql> set global tidb_enable_noop_variables=OFF;
Query OK, 0 rows affected (0.02 sec)

mysql> set global tidb_schema_cache_size=3;
Query OK, 0 rows affected, 1 warning (0.02 sec)

mysql> show warnings;
+---------+------+------------------------------------------------------+
| Level   | Code | Message                                              |
+---------+------+------------------------------------------------------+
| Warning | 8144 | setting tidb_schema_cache_size has no effect in TiDB |
+---------+------+------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select @@tidb_schema_cache_size;
+--------------------------+
| @@tidb_schema_cache_size |
+--------------------------+
| 3                        |
+--------------------------+
1 row in set, 1 warning (0.00 sec)
```
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by ywqzzy — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Comment by tiancaiamao** [comment]
I'll unhold it near the branch frozen...

**Pull request merged**
