### PR TITLE
bindinfo: refine logs of SQL bind (#21351)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21351 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/21175

Problem Summary:

Log is continuously printed for baseline capture.

### What is changed and how it works?

What's Changed:

- refine log messages of SQL bind;
- change log levels to DEBUG

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

N/A

Side effects

N/A

### Release note 

- refine logs of SQL bind

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
LGTM

**Comment by qw4990** [comment]
PTAL @Reminiscent @lzmhhh123

**Review by Reminiscent — APPROVED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
