### PR TITLE
ddl: Remove expired keys on PD (#10406)

### PR DESCRIPTION
**Pull request by zimulala**
Cherry-pick #10406 to v2.1

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @crazycs520 @bb7133

**Comment by zimulala** [comment]
PTAL @crazycs520 @bb7133 @winkyao

**Comment by zimulala** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zimulala** [comment]
/run-all-tests tidb-test=pr/846 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by bb7133** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by winkyao** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zimulala** [comment]
/run-common-test tidb-test=pr/846 tidb-private-test=release-2.1 tikv=release-2.1
/run-integration-common-test tidb-test=pr/846 tidb-private-test=release-2.1 tikv=release-2.1
/run-integration-common-test tidb-test=pr/846 tidb-private-test=release-2.1 tikv=release-2.1

**Pull request merged**
