### PR TITLE
br: remove some useless code for golang lint check

### LINKED ISSUE #31046: lightning: storageDir seems not work
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`storageDir` seems not work in code: https://github.com/pingcap/tidb/blob/393415782452903b417a539d7fc8cdcecc6ab1bf/br/pkg/lightning/config/config.go#L956

### 2. What did you expect to see? (Required)
a meaningful usage.
### 3. What did you see instead (Required)
storageDir did nothing.
### 4. What is your TiDB version? (Required)

master

### LINKED ISSUE #31358: fix the bug issues with `.golangci.yml` rules.

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve?

Issue Number: Close #31046 

partial close #31358

Problem Summary:
1.  remove some useless code

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by glorv — APPROVED** [review]
LGTM

**Review by joccau — APPROVED** [review]
PGTM

**Pull request merged**
