### PR TITLE
parser:  appending item to list instead of appending list to item.

### PR DESCRIPTION
**Pull request by coocood**
Reduce memory allocation.

### CODE REVIEW

**Comment by coocood** [comment]
@shenli @ngaut PTAL

**Comment by ngaut** [comment]
LGTM. Please let @shenli to take a look.

**Comment by ngaut** [comment]
Please add tests.

**Comment by shenli** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
