### PR TITLE
session: update Host type to char(255) in mysql.* tables for compatible with mysql-8.0

### LINKED ISSUE #23476: Change mysql.user Host field to char(255)
## Feature Request

**Is your feature request related to a problem? Please describe:**

I want to set IP white list, but it exceed char(64).

**Describe the feature you'd like:**

Change mysql.user Host field to char(255).

```
root@127.0.0.1 : (none) 08:17:51> select version();
+-----------+
| version() |
+-----------+
| 8.0.19    |
+-----------+
1 row in set (0.00 sec)

root@127.0.0.1 : (none) 08:18:03> desc mysql.user;
+--------------------------+-----------------------------------+------+-----+-----------------------+-------+
| Field                    | Type                              | Null | Key | Default               | Extra |
+--------------------------+-----------------------------------+------+-----+-----------------------+-------+
| Host                     | char(255)                         | NO   | PRI |                       |       |
```

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #23476

Problem Summary: 

### What is changed and how it works?

What's Changed: change host type to char(255) in mysql.* tables. 

How it Works: change CreateUserTable sql in session/bootstrap.go

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note 

```release-note
Change host type to char(255) in mysql.* tables for compatible with mysql-8.0. 
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @morgo 
PTAL

**Comment by Defined2014** [comment]
/cc @xhebox @xiongjiwei 
PTAL

**Review by morgo — CHANGES_REQUESTED** [review]
This will only take effect in new installs. Please also write a bootstrap task to upgrade tables from a previous version of TiDB, and then increment the bootstrap version.

**Comment by Defined2014** [comment]
> This will only take effect in new installs. Please also write a bootstrap task to upgrade tables from a previous version of TiDB, and then increment the bootstrap version.

Updated, PTAL.

**Review by xhebox — APPROVED** [review]

**Review by morgo — APPROVED** [review]

**Pull request merged**
