### PR TITLE
br/pkg/membuf: migrate test-infra to testify

### LINKED ISSUE #28172: migrate test-infra to testify for `br/pkg/membuf`

### PR DESCRIPTION
**Pull request by shadw3002**
### What problem does this PR solve?

Issue Number: close #28172 

Problem Summary: migrate test-infra to testify for br/pkg/membuf

### What is changed and how it works?

What's Changed: migrate test-infra to testify for br/pkg/membuf

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by shadw3002** [comment]
/cc @tisonkun
PTAL

**Review by tisonkun — APPROVED** [review]
LGTM. Thanks for your contribution!

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
Thanks for your contribution, welcome to pick more issues 👍

**Pull request merged**
