### PR TITLE
sessionctx/variable: turn off TiDBEnablePseudoForOutdatedStats by default

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: ref #27601

Problem Summary:

### What is changed and how it works?

Change the default value of `TiDBEnablePseudoForOutdatedStats` from true to false. After the pr, by default, when table stats are outdated, we still use the outdated stats rather  than pseudo stats, which is reasonable in most cases.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — COMMENTED** [review]
I think it needs some benchmark to verify...

**Review by chrysan — APPROVED** [review]

**Comment by xuyifangreeneyes** [comment]
> I think it needs some benchmark to verify...

In [CE Benchmark on stale statistics](https://pingcap.feishu.cn/docs/doccnznm12zF5KxPINkzsOFOeed), when stats healthy is 50%, using outdated stats(tidb_enable_pseudo_for_outdated_stats = off) has a smaller q-error then using pseudo stats(tidb_enable_pseudo_for_outdated_stats = on) when doing cardinality estimation benchmark on IMDB + JOB.

**Review by xhebox — APPROVED** [review]

**Comment by hawkingrei** [comment]
@pingcap/tidb-configuration-reviewer PTAL

/hold

**Review by qw4990 — APPROVED** [review]

**Comment by xuyifangreeneyes** [comment]
Found a unreasonable behavior when `tidb_enable_pseudo_for_outdated_stats` is false:
```
mysql> create table t(a int,  b int, c int,  index idx_a(a));
Query OK, 0 rows affected (0.02 sec)

mysql> show stats_meta;
+---------+------------+----------------+---------------------+--------------+-----------+
| Db_name | Table_name | Partition_name | Update_time         | Modify_count | Row_count |
+---------+------------+----------------+---------------------+--------------+-----------+
| test    | t          |                | 2022-08-03 23:46:19 |            0 |         0 |
+---------+------------+----------------+---------------------+--------------+-----------+
1 row in set (0.04 sec)

mysql> explain select * from t;
+-----------------------+----------+-----------+---------------+--------------------------------+
| id                    | estRows  | task      | access object | operator info                  |
+-----------------------+----------+-----------+---------------+--------------------------------+
| TableReader_5         | 10000.00 | root      |               | data:TableFullScan_4           |
| └─TableFullScan_4     | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+-----------------------+----------+-----------+---------------+--------------------------------+
2 rows in set (0.00 sec)

mysql> insert into t values (1,2,2), (3,4,4), (5,6,6), (7,8,8), (9,10,10);
Query OK, 5 rows affected (0.00 sec)
Records: 5  Duplicates: 0  Warnings: 0

mysql> show stats_meta;
+---------+------------+----------------+---------------------+--------------+-----------+
| Db_name | Table_name | Partition_name | Update_time         | Modify_count | Row_count |
+---------+------------+----------------+---------------------+--------------+-----------+
| test    | t          |                | 2022-08-03 23:46:19 |            0 |         0 |
+---------+------------+----------------+---------------------+--------------+-----------+
1 row in set (0.00 sec)

mysql> explain select * from t;
+-----------------------+----------+-----------+---------------+--------------------------------+
| id                    | estRows  | task      | access object | operator info                  |
+-----------------------+----------+-----------+---------------+--------------------------------+
| TableReader_5         | 10000.00 | root      |               | data:TableFullScan_4           |
| └─TableFullScan_4     | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+-----------------------+----------+-----------+---------------+--------------------------------+
2 rows in set (0.00 sec)

mysql> show stats_meta;
+---------+------------+----------------+---------------------+--------------+-----------+
| Db_name | Table_name | Partition_name | Update_time         | Modify_count | Row_count |
+---------+------------+----------------+---------------------+--------------+-----------+
| test    | t          |                | 2022-08-03 23:47:56 |            5 |         5 |
+---------+------------+----------------+---------------------+--------------+-----------+
1 row in set (0.00 sec)

mysql> explain select * from t;
+-----------------------+---------+-----------+---------------+----------------------+
| id                    | estRows | task      | access object | operator info        |
+-----------------------+---------+-----------+---------------+----------------------+
| TableReader_5         | 5.00    | root      |               | data:TableFullScan_4 |
| └─TableFullScan_4     | 5.00    | cop[tikv] | table:t       | keep order:false     |
+-----------------------+---------+-----------+---------------+----------------------+
2 rows in set (0.00 sec)
```
When `modify_count` is 5 and `row_count` is 5, the optimizer doesn't think that it uses pseudo stats. However, it actually does use pseudo stats because it hasn't collected any stats so far.

**Comment by xuyifangreeneyes** [comment]
> Found a unreasonable behavior when `tidb_enable_pseudo_for_outdated_stats` is false:
> 
> ```
> mysql> create table t(a int,  b int, c int,  index idx_a(a));
> Query OK, 0 rows affected (0.02 sec)
> 
> mysql> show stats_meta;
> +---------+------------+----------------+---------------------+--------------+-----------+
> | Db_name | Table_name | Partition_name | Update_time         | Modify_count | Row_count |
> +---------+------------+----------------+---------------------+--------------+-----------+
> | test    | t          |                | 2022-08-03 23:46:19 |            0 |         0 |
> +---------+------------+----------------+---------------------+--------------+-----------+
> 1 row in set (0.04 sec)
> 
> mysql> explain select * from t;
> +-----------------------+----------+-----------+---------------+--------------------------------+
> | id                    | estRows  | task      | access object | operator info                  |
> +-----------------------+----------+-----------+---------------+--------------------------------+
> | TableReader_5         | 10000.00 | root      |               | data:TableFullScan_4           |
> | └─TableFullScan_4     | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo |
> +-----------------------+----------+-----------+---------------+--------------------------------+
> 2 rows in set (0.00 sec)
> 
> mysql> insert into t values (1,2,2), (3,4,4), (5,6,6), (7,8,8), (9,10,10);
> Query OK, 5 rows affected (0.00 sec)
> Records: 5  Duplicates: 0  Warnings: 0
> 
> mysql> show stats_meta;
> +---------+------------+----------------+---------------------+--------------+-----------+
> | Db_name | Table_name | Partition_name | Update_time         | Modify_count | Row_count |
> +---------+------------+----------------+---------------------+--------------+-----------+
> | test    | t          |                | 2022-08-03 23:46:19 |            0 |         0 |
> +---------+------------+----------------+---------------------+--------------+-----------+
> 1 row in set (0.00 sec)
> 
> mysql> explain select * from t;
> +-----------------------+----------+-----------+---------------+--------------------------------+
> | id                    | estRows  | task      | access object | operator info                  |
> +-----------------------+----------+-----------+---------------+--------------------------------+
> | TableReader_5         | 10000.00 | root      |               | data:TableFullScan_4           |
> | └─TableFullScan_4     | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo |
> +-----------------------+----------+-----------+---------------+--------------------------------+
> 2 rows in set (0.00 sec)
> 
> mysql> show stats_meta;
> +---------+------------+----------------+---------------------+--------------+-----------+
> | Db_name | Table_name | Partition_name | Update_time         | Modify_count | Row_count |
> +---------+------------+----------------+---------------------+--------------+-----------+
> | test    | t          |                | 2022-08-03 23:47:56 |            5 |         5 |
> +---------+------------+----------------+---------------------+--------------+-----------+
> 1 row in set (0.00 sec)
> 
> mysql> explain select * from t;
> +-----------------------+---------+-----------+---------------+----------------------+
> | id                    | estRows | task      | access object | operator info        |
> +-----------------------+---------+-----------+---------------+----------------------+
> | TableReader_5         | 5.00    | root      |               | data:TableFullScan_4 |
> | └─TableFullScan_4     | 5.00    | cop[tikv] | table:t       | keep order:false     |
> +-----------------------+---------+-----------+---------------+----------------------+
> 2 rows in set (0.00 sec)
> ```
> 
> When `modify_count` is 5 and `row_count` is 5, the optimizer doesn't think that it uses pseudo stats. However, it actually does use pseudo stats because it hasn't collected any stats so far.

It is solved by #37444

**Pull request merged**
