### PR TITLE
expression: fix wrong collation for `concat` function (#24297)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #24297 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/24300
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/24300:release-4.0-c1518ac72125
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/24296

Problem Summary:

use connection charset and collation if function arg has no explicit collation.

### Release note 

- fix wrong collation for concat function

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Please resolve conflicts @xiongjiwei

**Review by wjhuang2016 — APPROVED** [review]

**Comment by xiongjiwei** [comment]
@tiancaiamao PTAL

**Review by ichn-hu — APPROVED** [review]

**Pull request merged**
