### PR TITLE
*: ignore DDL statement for query duration metrics

### PR DESCRIPTION
**Pull request by tiancaiamao**
DDL may be quite slow, take it into account would make our query duration metrics less accurate.

@shenli @zimulala @coocood

### CODE REVIEW

**Comment by tiancaiamao** [comment]
fix https://github.com/pingcap/tidb/issues/5074

**Comment by shenli** [comment]
LGTM
@coocood @zimulala PTAL

**Comment by coocood** [comment]
@tiancaiamao 
We can add `InDDLStmt` field in `StatementContext`.

**Comment by tiancaiamao** [comment]
How can we get `InDDLStmt` in server package, if it's add to `StatementContext` ? @coocood

**Comment by coocood** [comment]
We can get `SessionVars`.

**Comment by tiancaiamao** [comment]
1. `server.QueryCtx` interface doesn't have a `SessionVars` method.
2. When we record metrics in `dispatch()`, `StatementContext` maybe destoryed already.

**Comment by coocood** [comment]
1. Just add this method or we can just embed `context.Context` to `QueryCtx` interface.
2. We only reset the StatementCtx before the next statement.

**Comment by coocood** [comment]
LGTM

**Comment by zimulala** [comment]
Please fix CI.

**Pull request merged**
