### PR TITLE
txn: Fix the issue that analyze panics when aggressive locking is enabled globally

### LINKED ISSUE #41194: Enabling Aggressive Locking causes panic in analyze etc
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Enable aggressive locking globally:
```sql
set @@global.tidb_pessimistic_txn_aggressive_locking = 1;
```
2. Restart TiDB node
3. Run a analyze statement

### 2. What did you expect to see? (Required)

Everything goes well

### 3. What did you see instead (Required)

It causes panic.

The panic can be in various forms. An example:

```
[txn.go:660] ["Trying to start aggressive locking while it's already started"] [stack="github.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).StartAggressiveLocking
	/home/gopath/pkg/mod/github.com/ekexium/client-go/v2@v2.0.0-alpha.0.20230208084408-7ff10c724231/txnkv/transaction/txn.go:660
github.com/pingcap/tidb/store/driver/txn.(*tikvTxn).StartAggressiveLocking
	/data3/tidb5/eke/tidb/store/driver/txn/txn_driver.go:390
github.com/pingcap/tidb/session.(*LazyTxn).StartAggressiveLocking
	/data3/tidb5/eke/tidb/session/txn.go:479
github.com/pingcap/tidb/sessiontxn/isolation.(*basePessimisticTxnContextProvider).OnHandlePessimisticStmtStart
	/data3/tidb5/eke/tidb/sessiontxn/isolation/base.go:517
github.com/pingcap/tidb/session.(*txnManager).OnHandlePessimisticStmtStart
	/data3/tidb5/eke/tidb/session/txnmanager.go:184
github.com/pingcap/tidb/executor.(*ExecStmt).handlePessimisticDML
	/data3/tidb5/eke/tidb/executor/adapter.go:991
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay
	/data3/tidb5/eke/tidb/executor/adapter.go:776
github.com/pingcap/tidb/executor.(*ExecStmt).Exec
	/data3/tidb5/eke/tidb/executor/adapter.go:574
github.com/pingcap/tidb/session.runStmt
	/data3/tidb5/eke/tidb/session/session.go:2353
github.com/pingcap/tidb/session.(*session).ExecuteStmt
	/data3/tidb5/eke/tidb/session/session.go:2217
github.com/pingcap/tidb/session.(*session).ExecuteInternal
	/data3/tidb5/eke/tidb/session/session.go:1670
github.com/pingcap/tidb/statistics/handle.(*Handle).getStatsReader
	/data3/tidb5/eke/tidb/statistics/handle/handle.go:2070
github.com/pingcap/tidb/statistics/handle.(*Handle).getGlobalStatsReader
	/data3/tidb5/eke/tidb/statistics/handle/handle.go:2046
github.com/pingcap/tidb/statistics/handle.(*Handle).LoadNeededHistograms
	/data3/tidb5/eke/tidb/statistics/handle/handle.go:1044
github.com/pingcap/tidb/domain.(*Domain).loadStatsWorker
	/data3/tidb5/eke/tidb/domain/domain.go:1976
github.com/pingcap/tidb/util.(*WaitGroupEnhancedWrapper).Run.func1
	/data3/tidb5/eke/tidb/util/wait_group_wrapper.go:96"]
```

Another example:

```
[2023/02/08 16:54:50.914 +08:00] [ERROR] [conn.go:1064] ["connection running loop panic"] [conn=2199023255955] [lastSQL="analyze table t;"] [err="Trying to start aggressive locking while it's already started"] [stack="github.com/pingcap/tidb/server.(*clientConn).Run.func1
	/home/tidb/misono/sync/tidb/server/conn.go:1067
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:884
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1
	/home/tidb/misono/sync/tidb/executor/adapter.go:456
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:884
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1
	/home/tidb/misono/sync/tidb/executor/adapter.go:456
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:884
github.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).StartAggressiveLocking
	/home/tidb/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.6-0.20230207090754-29dfcc272912/txnkv/transaction/txn.go:660
github.com/pingcap/tidb/store/driver/txn.(*tikvTxn).StartAggressiveLocking
	/home/tidb/misono/sync/tidb/store/driver/txn/txn_driver.go:387
github.com/pingcap/tidb/session.(*LazyTxn).StartAggressiveLocking
	/home/tidb/misono/sync/tidb/session/txn.go:479
github.com/pingcap/tidb/sessiontxn/isolation.(*basePessimisticTxnContextProvider).OnHandlePessimisticStmtStart
	/home/tidb/misono/sync/tidb/sessiontxn/isolation/base.go:514
github.com/pingcap/tidb/session.(*txnManager).OnHandlePessimisticStmtStart
	/home/tidb/misono/sync/tidb/session/txnmanager.go:184
github.com/pingcap/tidb/executor.(*ExecStmt).handlePessimisticDML
	/home/tidb/misono/sync/tidb/executor/adapter.go:988
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay
	/home/tidb/misono/sync/tidb/executor/adapter.go:776
github.com/pingcap/tidb/executor.(*ExecStmt).Exec
	/home/tidb/misono/sync/tidb/executor/adapter.go:574
github.com/pingcap/tidb/session.runStmt
	/home/tidb/misono/sync/tidb/session/session.go:2338
github.com/pingcap/tidb/session.(*session).ExecuteStmt
	/home/tidb/misono/sync/tidb/session/session.go:2195
github.com/pingcap/tidb/session.(*session).ExecuteInternal
	/home/tidb/misono/sync/tidb/session/session.go:1655
github.com/pingcap/tidb/statistics/handle.finishTransaction
	/home/tidb/misono/sync/tidb/statistics/handle/ddl.go:341
github.com/pingcap/tidb/statistics/handle.SaveTableStatsToStorage.func2
	/home/tidb/misono/sync/tidb/statistics/handle/handle.go:1550
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:890
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1
	/home/tidb/misono/sync/tidb/executor/adapter.go:456
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:884
github.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).StartAggressiveLocking
	/home/tidb/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.6-0.20230207090754-29dfcc272912/txnkv/transaction/txn.go:660
github.com/pingcap/tidb/store/driver/txn.(*tikvTxn).StartAggressiveLocking
	/home/tidb/misono/sync/tidb/store/driver/txn/txn_driver.go:387
github.com/pingcap/tidb/session.(*LazyTxn).StartAggressiveLocking
	/home/tidb/misono/sync/tidb/session/txn.go:479
github.com/pingcap/tidb/sessiontxn/isolation.(*basePessimisticTxnContextProvider).OnHandlePessimisticStmtStart
	/home/tidb/misono/sync/tidb/sessiontxn/isolation/base.go:514
github.com/pingcap/tidb/session.(*txnManager).OnHandlePessimisticStmtStart
	/home/tidb/misono/sync/tidb/session/txnmanager.go:184
github.com/pingcap/tidb/executor.(*ExecStmt).handlePessimisticDML
	/home/tidb/misono/sync/tidb/executor/adapter.go:988
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay
	/home/tidb/misono/sync/tidb/executor/adapter.go:776
github.com/pingcap/tidb/executor.(*ExecStmt).Exec
	/home/tidb/misono/sync/tidb/executor/adapter.go:574
github.com/pingcap/tidb/session.runStmt
	/home/tidb/misono/sync/tidb/session/session.go:2338
github.com/pingcap/tidb/session.(*session).ExecuteStmt
	/home/tidb/misono/sync/tidb/session/session.go:2195
github.com/pingcap/tidb/session.(*session).ExecuteInternal
	/home/tidb/misono/sync/tidb/session/session.go:1655
github.com/pingcap/tidb/statistics/handle.SaveTableStatsToStorage
	/home/tidb/misono/sync/tidb/statistics/handle/handle.go:1580
github.com/pingcap/tidb/statistics/handle.(*Handle).SaveTableStatsToStorage
	/home/tidb/misono/sync/tidb/statistics/handle/handle.go:1524
github.com/pingcap/tidb/executor.(*AnalyzeExec).handleResultsError
	/home/tidb/misono/sync/tidb/executor/analyze.go:318
github.com/pingcap/tidb/executor.(*AnalyzeExec).Next
	/home/tidb/misono/sync/tidb/executor/analyze.go:185
github.com/pingcap/tidb/executor.Next
	/home/tidb/misono/sync/tidb/executor/executor.go:324
github.com/pingcap/tidb/executor.(*ExecStmt).next
	/home/tidb/misono/sync/tidb/executor/adapter.go:1195
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor
	/home/tidb/misono/sync/tidb/executor/adapter.go:947
github.com/pingcap/tidb/executor.(*ExecStmt).handlePessimisticDML
	/home/tidb/misono/sync/tidb/executor/adapter.go:1001
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay
	/home/tidb/misono/sync/tidb/executor/adapter.go:776
github.com/pingcap/tidb/executor.(*ExecStmt).Exec
	/home/tidb/misono/sync/tidb/executor/adapter.go:574
github.com/pingcap/tidb/session.runStmt
	/home/tidb/misono/sync/tidb/session/session.go:2338
github.com/pingcap/tidb/session.(*session).ExecuteStmt
	/home/tidb/misono/sync/tidb/session/session.go:2195
github.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt
	/home/tidb/misono/sync/tidb/server/driver_tidb.go:247
github.com/pingcap/tidb/server.(*clientConn).handleStmt
	/home/tidb/misono/sync/tidb/server/conn.go:1999
github.com/pingcap/tidb/server.(*clientConn).handleQuery
	/home/tidb/misono/sync/tidb/server/conn.go:1849
github.com/pingcap/tidb/server.(*clientConn).dispatch
	/home/tidb/misono/sync/tidb/server/conn.go:1380
github.com/pingcap/tidb/server.(*clientConn).Run
	/home/tidb/misono/sync/tidb/server/conn.go:1129
github.com/pingcap/tidb/server.(*Server).onConn
	/home/tidb/misono/sync/tidb/server/server.go:625"]
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What problem does this PR solve?

Issue Number: close #41194

Problem Summary:

### What is changed and how it works?

This PR disables aggressive locking for internal sessions and restricted SQLs, which is a fix for issue #41194 which sometimes leads to panic to analyze statements.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

(It's an unreleased bug. no release note is needed.)

### CODE REVIEW

**Review by cfzjywxk — APPROVED** [review]

**Review by ekexium — APPROVED** [review]

**Comment by hawkingrei** [comment]
/hold 

CI is too busy.

**Comment by ekexium** [comment]
> /hold
> 
> CI is too busy.

Manual admission control 😢

**Comment by hawkingrei** [comment]
I'm a CI policeman. T T

**Comment by cfzjywxk** [comment]
@hawkingrei 
Need help the merge is still blocked.

**Comment by hawkingrei** [comment]
> @hawkingrei Need help the merge is still blocked.

It is a sad story.

**Pull request merged**
