### PR TITLE
*: do not start slow-log timer before parsing

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve? 
Starting slow-log timer making most of the cost time of multi-query greater than slow-log-threshold, which prints too many useless logs.

### What is changed and how it works?
Do not start slow-log timer before parsing.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by jackysp** [comment]
PTAL @coocood

**Comment by coocood** [comment]
LGTM

**Comment by jackysp** [comment]
PTAL @crazycs520

**Pull request merged**
