### PR TITLE
executor: reset all state when table reader executor close (#33219)

### LINKED ISSUE #33214: the query results for enum column is wrong
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
source  [test.txt](https://github.com/pingcap/tidb/files/8285072/test.txt);

alter table IDT_MULTI15863STROBJSTROBJ cache;
# please execute many times to reporduce
 select col1 from IDT_MULTI15863STROBJSTROBJ t1 where (select count(*) from IDT_MULTI15863STROBJSTROBJ t2 where t2.col1 in (t1.col1, "none")) > 1;
```
### 2. What did you expect to see? (Required)
```
MySQL [test]> select col1 from IDT_MULTI15863STROBJSTROBJ t1 where (select count(*) from IDT_MULTI15863STROBJSTROBJ t2 where t2.col1 in (t1.col1, "none")) > 1;
+------+
| col1 |
+------+
...
+------+
58 rows in set (0.03 sec)
```
### 3. What did you see instead (Required)
```

MySQL [test]> select col1 from IDT_MULTI15863STROBJSTROBJ t1 where (select count(*) from IDT_MULTI15863STROBJSTROBJ t2 where t2.col1 in (t1.col1, "none")) > 1;
+------+
| col1 |
+------+
...
+------+
60 rows in set (0.03 sec)
```
### 4. What is your TiDB version? (Required)

```
Release Version: v6.0.0-alpha-122-g46c43fe
Edition: Community
Git Commit Hash: 46c43febcac0e24bc9f0872e93cf6125db69d93d
Git Branch: master
UTC Build Time: 2022-03-17 01:02:30
GoVersion: go1.17.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #33219 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/33227
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/33227:release-5.4-64b057dea2e9
```

---

### What problem does this PR solve?

Issue Number: close #33214

Problem Summary:

### What is changed and how it works?

When there is a `Apply` executor, it may Open/Close its children executor several times.

```
mysql> explain select col from t t1 where (select count(*) from t t2 where t2.col = t1.col or t2.col =  'sdf') > 1;
+------------------------------------+---------+-----------+---------------+-------------------------------------------------------+
| id                                 | estRows | task      | access object | operator info                                         |
+------------------------------------+---------+-----------+---------------+-------------------------------------------------------+
| Projection_13                      | 5.00    | root      |               | test.t.col                                            |
| └─Apply_15                         | 5.00    | root      |               | CARTESIAN inner join                                  |
|   ├─UnionScan_16(Build)            | 5.00    | root      |               |                                                       |
|   │ └─TableReader_18               | 5.00    | root      |               | data:TableFullScan_17                                 |
|   │   └─TableFullScan_17           | 5.00    | cop[tikv] | table:t1      | keep order:false, stats:pseudo                        |
|   └─Selection_19(Probe)            | 0.80    | root      |               | gt(Column#5, 1)                                       |
|     └─StreamAgg_21                 | 1.00    | root      |               | funcs:count(1)->Column#5                              |
|       └─UnionScan_22               | 0.01    | root      |               | or(eq(test.t.col, test.t.col), eq(test.t.col, "sdf")) |
|         └─TableReader_25           | 0.01    | root      |               | data:Selection_24                                     |
|           └─Selection_24           | 0.01    | cop[tikv] |               | or(eq(test.t.col, test.t.col), eq(test.t.col, "sdf")) |
|             └─TableFullScan_23     | 5.00    | cop[tikv] | table:t2      | keep order:false, stats:pseudo                        |
+------------------------------------+---------+-----------+---------------+-------------------------------------------------------+
11 rows in set (0.00 sec)
```

So it's important that after Open/Close, the executor can be reused.
However, the table reader doen't reset its `keyRange` and when UnionScan Open/Close it will get repeated keyRange.
And finally return wrong result to its parent executor.

### Check List

Tests 

- [ ] Unit test
- [X] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by ichn-hu — CHANGES_REQUESTED** [review]
@tiancaiamao please resolve conflicts

**Comment by tiancaiamao** [comment]
Done @ichn-hu

**Review by ichn-hu — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Pull request merged**
