### PR TITLE
*: Upgrade the indirectly referenced github.com/gorilla/websocket module…

### PR DESCRIPTION
**Pull request by s3nt3**
### What problem does this PR solve?

Solve a dos issue: https://deps.dev/advisory/OSV/GO-2020-0019?from=%2Fgo%2Fgithub.com%252Fpingcap%252Ftidb%2Fv5.2.0-alpha%252Bincompatible

### What is changed and how it works?

What's Changed:

Upgrade the go.etcd.io/etcd from v0.5.0-alpha.5.0.20200824191128-ae9734ed278b to v0.5.0-alpha.5.0.20210512015243-d19fbe541bf9.

How it Works:

The module github.com/gorilla/websocket is indirectly referenced by go.etcd.io/etcd. By upgrading go.etcd.io/etcd, github.com/gorilla/websocket has been upgraded to v1.4.2, which is no longer affected.

### Check List 

Tests 

- [x] Unit test
- [x] Integration test
- [x] No code

Side effects

- [x] Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by bb7133** [comment]
LGTM, please resolve the conflicts, thanks!

**Review by kennytm — APPROVED** [review]

**Review by morgo — APPROVED** [review]

**Pull request merged**
