### PR TITLE
Built-in Function: quote

### PR DESCRIPTION
**Pull request by silentred**

### CODE REVIEW

**Comment by silentred** [comment]
It seems CI failed to report the status back.

**Comment by coocood** [comment]
@silentred 
That's because the PR has conflict.
I resolved it and merged master.

**Comment by tiancaiamao** [comment]
A comprehensive understanding on string literal escape in MySQL is not that easy.

The input of the function in Go representation (when `eval` called)
```
SELECT QUOTE('Don\'t!');
```
 is actually
```
`Don't`
``` 
not
```
`Don\'t`
```

Because the lexer already handle the escape. 
https://github.com/pingcap/tidb/blob/master/parser/lexer.go#L518

If you write

```
Don\'t
```

in the test code, the real SQL input is equal to this:

```
SELECT QUOTE('Don\\\'t');
```

-----------

If you want to implement this function, just add a backslash (\\) 
before each backslash, single quote ('), ASCII NUL, and Control+Z.

**Comment by tiancaiamao** [comment]
I find someone already work on it.
https://github.com/pingcap/tidb/issues/2863

**Comment by silentred** [comment]
@tiancaiamao  
mysql 5.7
```
mysql> select quote("Don't!");
+-----------------+
| quote("Don't!") |
+-----------------+
| 'Don\'t!'       |
+-----------------+

mysql> select quote("Don\'t!");
+------------------+
| quote("Don\'t!") |
+------------------+
| 'Don\'t!'        |
+------------------+
```

**Comment by coocood** [comment]
@silentred 
We appreciate your effort, but this function has been implemented by another PR, we have to close it.
I'm sorry.

**Pull request closed without merging**
