### PR TITLE
dumpling: remove useless code

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: ref #31716

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by purelind** [comment]
### TiDB MergeCI notify
**🟠 Bad News! New failing [1] after this pr merged.**
These new failed integration tests seem to be caused by the current PR, please try to fix these new failed integration tests, thanks!
CI Name | Result | Duration | Compare with Parent commit
------------ | ------------- | ------------- | -------------
[idc-jenkins-ci-tidb/common-test](https://ci.pingcap.net/job/tidb_ghpr_common_test/9455/display/redirect) | 🟥 failed 1, success 11, total 12 | 5 min 16 sec | New failing
[idc-jenkins-ci-tidb/integration-br-test](https://ci.pingcap.net/job/tidb_ghpr_integration_br_test/8755/display/redirect) | 🟥 failed 24, success 5, total 29 | 15 min | Existing failure
[idc-jenkins-ci-tidb/integration-copr-test](https://ci.pingcap.net/job/tidb_ghpr_integration_copr_test/9032/display/redirect) | ✅ all 1 tests passed | 5 min 9 sec | Fixed
[idc-jenkins-ci/integration-cdc-test](https://ci.pingcap.net/job/tidb_ghpr_integration_cdc_test/1791/display/redirect) | 🟢 all 34 tests passed | 46 min | Existing passed
[idc-jenkins-ci-tidb/code-coverage](https://ci.pingcap.net/job/tidb_ghpr_coverage/2984/display/redirect) | 🟢 Lines coverage: 63.48% | 12 min | Existing passed
[idc-jenkins-ci-tidb/integration-common-test](https://ci.pingcap.net/job/tidb_ghpr_integration_common_test/10624/display/redirect) | 🟢 all 11 tests passed | 11 min | Existing passed
[idc-jenkins-ci-tidb/sqllogic-test-2](https://ci.pingcap.net/job/tidb_ghpr_sqllogic_test_2/9119/display/redirect) | 🟢 all 28 tests passed | 7 min 33 sec | Existing passed
[idc-jenkins-ci-tidb/integration-ddl-test](https://ci.pingcap.net/job/tidb_ghpr_integration_ddl_test/9244/display/redirect) | 🟢 all 6 tests passed | 5 min 57 sec | Existing passed
[idc-jenkins-ci-tidb/tics-test](https://ci.pingcap.net/job/tidb_ghpr_tics_test/8873/display/redirect) | 🟢 all 1 tests passed | 5 min 47 sec | Existing passed
[idc-jenkins-ci-tidb/sqllogic-test-1](https://ci.pingcap.net/job/tidb_ghpr_sqllogic_test_1/9181/display/redirect) | 🟢 all 26 tests passed | 5 min 32 sec | Existing passed
[idc-jenkins-ci-tidb/mybatis-test](https://ci.pingcap.net/job/tidb_ghpr_mybatis/9043/display/redirect) | 🟢 all 1 tests passed | 3 min 39 sec | Existing passed
[idc-jenkins-ci-tidb/integration-compatibility-test](https://ci.pingcap.net/job/tidb_ghpr_integration_campatibility_test/10031/display/redirect) | 🟢 all 1 tests passed | 3 min 22 sec | Existing passed
[idc-jenkins-ci-tidb/plugin-test](https://ci.pingcap.net/job/tidb_merged_pr_build/2853/display/redirect) | 🟢 build success, plugin test success | 4min | Existing passed

**Pull request merged**
