### PR TITLE
go.mod: upgrade the client-go to use a more readble key log format

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Issue Number: https://github.com/pingcap/tidb/issues/29787

Problem Summary:

See more details at https://github.com/tikv/client-go/pull/375.

### Check List

Tests 

- [x] Unit test
- [x] Integration test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by kennytm — APPROVED** [review]

**Comment by JmPotato** [comment]
@disksing @kennytm Could you please help merge this PR with a 	`/merge`? Thx~

**Comment by kennytm** [comment]
@JmPotato seems you need to fix some code 👀 

```
[2021-11-15T08:17:07.596Z] store/mockstore/mockcopr/cop_handler_dag.go:46:2: cannot find package "." in:

[2021-11-15T08:17:07.596Z] 	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211115071040-a3f1c41ac1a0/testutils

[2021-11-15T08:17:07.596Z] metrics/metrics.go:19:2: cannot find package "." in:

[2021-11-15T08:17:07.596Z] 	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211115071040-a3f1c41ac1a0/metrics

[2021-11-15T08:17:07.596Z] store/mockstore/mockcopr/cop_handler_dag.go:46:2: cannot find package "." in:

[2021-11-15T08:17:07.596Z] 	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211115071040-a3f1c41ac1a0/testutils
```

**Comment by JmPotato** [comment]
> @JmPotato seems you need to fix some code 👀
> 
> ```
> [2021-11-15T08:17:07.596Z] store/mockstore/mockcopr/cop_handler_dag.go:46:2: cannot find package "." in:
> 
> [2021-11-15T08:17:07.596Z] 	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211115071040-a3f1c41ac1a0/testutils
> 
> [2021-11-15T08:17:07.596Z] metrics/metrics.go:19:2: cannot find package "." in:
> 
> [2021-11-15T08:17:07.596Z] 	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211115071040-a3f1c41ac1a0/metrics
> 
> [2021-11-15T08:17:07.596Z] store/mockstore/mockcopr/cop_handler_dag.go:46:2: cannot find package "." in:
> 
> [2021-11-15T08:17:07.596Z] 	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211115071040-a3f1c41ac1a0/testutils
> ```

I think it's a CI env problem rather than the code itself 👀.

**Pull request merged**
