### PR TITLE
executor: properly escape backquotes in identifiers in SHOW CREATE TABLE

### LINKED ISSUE #8259: SHOW CREATE TABLE does not escape the backquotes in the identifiers
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```sql
create table `foo``bar` (`id``baz` int);
show create table `foo``bar`;
```

2. What did you expect to see?

The "Create Table" column should read 

```sql
CREATE TABLE `foo``bar` (
  `id``baz` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

3. What did you see instead?

The `` ` `` in the table and column names aren't escaped, producing the invalid DDL

```sql
CREATE TABLE `foo`bar` (
  `id`baz` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Master version.

```
Release Version: v2.1.0-beta-602-gf3a9745e2
Git Commit Hash: f3a9745e2c42137b069d41a5aa9df9b32195282d
Git Branch: master
UTC Build Time: 2018-11-09 05:14:59
GoVersion: go version go1.11.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Fix #8259.

### What is changed and how it works?

Added a method which properly escapes and doubles the backquotes in an identifier (````"foo`bar"```` → ````"`foo``bar`"````)

In the implementation of SHOW CREATE TABLE and SHOW CREATE DATABASE, we replaced all usages of ````fmt.Sprintf("`%s`", stuff.Name.O)```` into `escape(stuff.Name, sqlMode)`.

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
    - Manually executed the steps described in #8259.

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
(The "integration-ddl-test" failed previously in [run 4106](https://internal.pingcap.net/jenkins/blue/organizations/jenkins/tidb_ghpr_integration_ddl_test/detail/tidb_ghpr_integration_ddl_test/4106/pipeline/), which seems to be spurious. The re-run at [run 4109](https://internal.pingcap.net/jenkins/blue/organizations/jenkins/tidb_ghpr_integration_ddl_test/detail/tidb_ghpr_integration_ddl_test/4109/pipeline) passed)

**Comment by zz-jason** [comment]
@kennytm we should cherry pick this change to release-2.1 and release-2.0 branch

**Pull request merged**
