### PR TITLE
store/copr: reserve and reuse some goroutines in a pool for handling coprocessor requests

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### What is changed and how it works?

The coprocessor sender use many short-life goroutines.
Keep some goroutines and reuse them to reduce goroutine alloc/free

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)

Run sysbench locally to see everything is still ok

```
sysbench --config-file=config oltp_read_only --tables=32 --table-size=3000000 run
```

Before:

```
SQL statistics:
    queries performed:
        read:                            5074734
        write:                           0
        other:                           724962
        total:                           5799696
    transactions:                        362481 (1006.82 per sec.)
    queries:                             5799696 (16109.15 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

General statistics:
    total time:                          360.0243s
    total number of events:              362481

Latency (ms):
         min:                                    9.12
         avg:                                   15.89
         max:                                   54.39
         95th percentile:                       20.74
         sum:                              5758733.36

Threads fairness:
    events (avg/stddev):           22655.0625/21.76
    execution time (avg/stddev):   359.9208/0.01
```

After:

```
SQL statistics:
    queries performed:
        read:                            5385044
        write:                           0
        other:                           769292
        total:                           6154336
    transactions:                        384646 (1068.42 per sec.)
    queries:                             6154336 (17094.67 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

General statistics:
    total time:                          360.0142s
    total number of events:              384646

Latency (ms):
         min:                                    7.85
         avg:                                   14.97
         max:                                   50.55
         95th percentile:                       19.65
         sum:                              5758597.74

Threads fairness:
    events (avg/stddev):           24040.3750/18.03
    execution time (avg/stddev):   359.9124/0.00
```

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by tiancaiamao** [comment]
update client-go would fix https://github.com/pingcap/tidb/pull/39752 https://github.com/pingcap/tidb/issues/40255

**Review by xhebox — APPROVED** [review]
It is both an optimization and bug fix for server hang problem?

**Comment by BusyJay** [comment]
Any plan to land this change?

**Comment by tiancaiamao** [comment]
> Any plan to land this change?

The master tidb had update the go.mod in other pr.  @BusyJay 
https://github.com/pingcap/tidb/pull/40350/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L224

**Pull request closed without merging**
