### PR TITLE
expression: correct constant propagation for collation

### LINKED ISSUE #22665: constant propagation is wrong used for some collation.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t1(a char(10) collate utf8mb4_general_ci, index (a));
create table t2(a char(10) collate utf8_bin, index (a));
insert into t1 values ("a");
insert into t2 values ("A");
set names utf8 collate utf8_general_ci;
select * from t1, t2 where t1.a=t2.a and t1.a= "a";
```

### 2. What did you expect to see? (Required)
```
mysql> select * from t1, t2 where t1.a=t2.a and t1.a= "a";
+------+------+
| a    | a    |
+------+------+
| a    | A    |
+------+------+
1 row in set (0.01 sec)
```
### 3. What did you see instead (Required)
```
mysql> select * from t1, t2 where t1.a=t2.a and t1.a= "a";
Empty set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

4.0 - 4.0.10, 5.0 rc, master

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #22665 

Problem Summary:
Check the collation more strictly.

### What is changed and how it works?

Propagate constant only if their collations are strictly equal.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- fix a bug may cause wrong constant propagation and get the wrong result.

### CODE REVIEW

**Review by xiongjiwei — COMMENTED** [review]
LGTM

**Review by winoros — COMMENTED** [review]
lgtm

**Review by qw4990 — APPROVED** [review]
/LGTM

**Pull request merged**
