### PR TITLE
util/paging: choose min paging size default value as 128, and max value as 8192

### LINKED ISSUE #36328: Expirement to choose the best value for page size (or self-adapting)
In the past, we use default value min paging size = 64
max paging size = 8192 (64 << 7) 

We need to figure out whether this setting is reasonable.

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #36328

Problem Summary:

### What is changed and how it works?

When min paging size is too small, we need more network round-trip.
But when it's too large, the packet size grow and consume more memory.

There are two variable, min paging size and max paging size to control behaviour.
After expirement, I'd like to choose the default min paging size to 128.

In the following picture, I expirement with:

- disable paging
- enable paging, min paging size = 16
- min paging size = 32
- min paging size = 64 (the current default)
- min paging size = 128
- min paging size = 256
- min paging size = 512

image

The `DistSQL QPS` panel reflect the total qps
The `Coprocessor Query Per Second` panel reflect the actual paging requests, one distsql query may result in several, they are in 1:N relationship

Coprocessor query for two reason:
1. one distsql query visit several regions, so it's splited per region
2. paging result too large, so it involves multiple network round-trip

For 2, we want to choose the best defalut value for `tidb_min_paging_size` to reduce network round-trip to get better performance.
From the `Coprocessor Query Per Second` panel, it's obvious that size = 16 is too small,
128, 256, 512 are basicaly the same...

| min paging size | qps |
|-------------------- | -------- | 
| off | 16944.88 |
| 16 | 16616.43 |
| 32 | 18496.36 |
| 64 | 17970.63 |
| 128 | 19771.29 |
| 256 | 19649.98 |
| 512 | 19608.02 |

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by tiancaiamao** [comment]
B.T.W, copr-cache hit rate may account for that paging performance become better than non-paging, but it's just my speculation.

**Comment by tiancaiamao** [comment]
For  max paging size = 8192, we've tested that setting will not bring obvious performance regression comparing to non-paging, in some other AP testing scenarios not listed here.

**Review by XuHuaiyu — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]

**Pull request merged**
