### PR TITLE
executor: remove duplicate entry in show privileges

### LINKED ISSUE #23724: Duplicate entry of "Alter" privilege
https://github.com/pingcap/tidb/blob/55580eef8f7456e625ededa367c94c7ad7f1eed0/executor/show.go#L1374-L1378

straightforward as shown above.

### PR DESCRIPTION
**Pull request by tisonkun**
### What problem does this PR solve?

Issue Number: close #23724

Problem Summary:

straightforward

### What is changed and how it works?

What's Changed:

remove duplicate entry in show privileges

### Related changes

N/A

### Release note 

- No release note

### CODE REVIEW

**Comment by tisonkun** [comment]
even we have a wrong test...

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/82760/pipeline

**Comment by morgo** [comment]
Please fix the following test:
```
[2021-03-31T09:02:43.683Z] FAIL: executor_test.go:302: testSuiteP1.TestShow
[2021-03-31T09:02:43.683Z] 
[2021-03-31T09:02:43.683Z] executor_test.go:321:
[2021-03-31T09:02:43.683Z]     tk.MustQuery("show privileges").Check(testkit.Rows("Alter Tables To alter the table",
[2021-03-31T09:02:43.683Z]         "Alter Tables To alter the table",
```

**Comment by tisonkun** [comment]
> Please fix the following test:
> 
> ```
> [2021-03-31T09:02:43.683Z] FAIL: executor_test.go:302: testSuiteP1.TestShow
> [2021-03-31T09:02:43.683Z] 
> [2021-03-31T09:02:43.683Z] executor_test.go:321:
> [2021-03-31T09:02:43.683Z]     tk.MustQuery("show privileges").Check(testkit.Rows("Alter Tables To alter the table",
> [2021-03-31T09:02:43.683Z]         "Alter Tables To alter the table",
> ```

I've already fix it. You can see the latest CI report. It is already passed.

**Comment by tisonkun** [comment]
> Please fix the following test:
> 
> ```
> [2021-03-31T09:02:43.683Z] FAIL: executor_test.go:302: testSuiteP1.TestShow
> [2021-03-31T09:02:43.683Z] 
> [2021-03-31T09:02:43.683Z] executor_test.go:321:
> [2021-03-31T09:02:43.683Z]     tk.MustQuery("show privileges").Check(testkit.Rows("Alter Tables To alter the table",
> [2021-03-31T09:02:43.683Z]         "Alter Tables To alter the table",
> ```

https://github.com/pingcap/tidb/pull/23738/commits/871925e6a4245e2c83b1398678cf01d84f80a670

Here is the commit and you see the following commit in pending because tide phase required mergeable state. Though it seems a bit frustrating.

**Comment by tiancaiamao** [comment]
PTAL @morgo

**Comment by tisonkun** [comment]
@tiancaiamao thanks for your review and taking care of this!

**Comment by tisonkun** [comment]
@morgo @tiancaiamao it seems merging procedure blocked by the bot. Could you please help on this pr?

**Comment by morgo** [comment]
The unit-test is currently failing, and blocking new PRs from merging. We will fix it soon, sorry for the inconvenience.

**Comment by tisonkun** [comment]
> The unit-test is currently failing, and blocking new PRs from merging. We will fix it soon, sorry for the inconvenience.

thanks for your information @morgo ! I will wait for the test fixed and stop triggering tests.

**Pull request merged**
