### PR TITLE
statistics: optimize the global histogram merging algorithm

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary: statistics: optimize the global histogram merging algorithm

### What is changed and how it works?

statistics: optimize the global histogram merging algorithm
1. remove empty buckets
2. introduce a damping factor when calculating bucket NDV
3. limit the minimum size of global buckets
4. adjust bucket boundaries according to NDV
5. disable bucket NDV in global-stats

### Check List 

Tests 

- Unit test

### Release note 

- statistics: optimize the global histogram merging algorithm

### CODE REVIEW

**Review by rebelice — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]
/LGTM

**Pull request merged**
