### PR TITLE
expression: support quarter pushdown to tiflash

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve?

Issue Number: related to https://github.com/pingcap/tics/issues/3356

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Support pushdown function quarter to tiflash
```

### CODE REVIEW

**Review by ichn-hu — COMMENTED** [review]
please consider add unit test in `expr_to_pb_test.go`, e.g. https://github.com/pingcap/tidb/pull/30983/files

**Review by windtalker — APPROVED** [review]
LGTM

**Review by guo-shaoge — APPROVED** [review]

**Pull request merged**
