### PR TITLE
*: Telemetry for multi-column RANGE COLUMNS partitioning

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: ref #36636

Problem Summary:

Added telemetry for tracking how often multi-column RANGE COLUMNS partitioning is used.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Added telemetry for counting number of tables created with multi-column RANGE COLUMNS partitioning.
```

### CODE REVIEW

**Comment by mjonss** [comment]
For a diff between this PR and the base https://github.com/pingcap/tidb/pull/36637, see https://github.com/mjonss/tidb/pull/1

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
