### PR TITLE
expression: wrap to_binary and from_binary for cast function's argument

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

copr-test is failed, this pr fix the problem. close https://github.com/pingcap/tidb/issues/30707

we need wrap `to_binary` and `from_binary` for `castStringAsString` function, not only the const binary literal

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by tangenta — COMMENTED** [review]
I don't understand why does it need `to_binary()`. The result is a utf8 string, isn't it?

**Comment by xiongjiwei** [comment]
> I don't understand why does it need `to_binary()`. The result is a utf8 string, isn't it?

for case like
```sql
cast(0x61 as char(10))
cast(a as binary)
```

**Review by tangenta — APPROVED** [review]

**Pull request merged**
