### PR TITLE
server: fix column info for resultType/flag for enum&set type.

### LINKED ISSUE #6910: When the field list of the select statement contains the Enum type, the client will report an error
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

When I use Server Prepared Statements, that is set `useServerPrepStmts=true`, if the select statement's field list contains the `Enum` type, the client will report an error.

```
CREATE TABLE shirts (
    name VARCHAR(40),
    size ENUM('small', 'medium', 'large')
);

INSERT INTO shirts (name, size) VALUES ('dress shirt','large'), ('t-shirt','medium'),('polo shirt','small');

mysql> desc shirts;
+-------+--------------------------------+------+------+---------+-------+
| Field | Type                           | Null | Key  | Default | Extra |
+-------+--------------------------------+------+------+---------+-------+
| name  | varchar(40)                    | YES  |      | NULL    |       |
| size  | enum('small','medium','large') | YES  |      | NULL    |       |
+-------+--------------------------------+------+------+---------+-------+
```
Java Code snippet：

```
    String DB_URL = "jdbc:mysql://xxx.xxx.xxxx.xxx:4000/test";
    Properties info = new Properties();
    info.setProperty("user", "root");
    info.setProperty("password", "");
    info.setProperty("useServerPrepStmts", "true");
    Connection conn = DriverManager.getConnection(DB_URL, info);

    String sql = "SELECT name, size FROM shirts WHERE name = ?";

    PreparedStatement preparedStatement = conn.prepareStatement(sql);
    preparedStatement.setString(1, "t-shirt");
    ResultSet resultSet = preparedStatement.executeQuery();

    while (resultSet.next()) {
        String name = resultSet.getString("name");
        String size = resultSet.getString("size");
        System.out.println(name + ", " + size );
    }
```
MySQL Connector/J version：

```
<dependency>
     <groupId>mysql</groupId>
     <artifactId>mysql-connector-java</artifactId>
     <version>6.0.6</version>
</dependency>
```

2. What did you expect to see?

I expect the TiDB to return the correct query result.

3. What did you see instead?

The client reported the following error message:

```
Exception in thread "main" java.sql.SQLException: Unknown type '247' in column '1' of '2' in binary-encoded result set.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1299)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:701)
	at com.mysql.cj.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1923)
	at com.apusic.test.CursorExample.main(CursorExample.java:27)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

----------------------------------------------------------------------------------------------------------------+
| Release Version: v2.1.0-alpha-75-g41f8ac195
Git Commit Hash: 41f8ac19523386d0eb6ca871397f49f834958169
Git Branch: master
UTC Build Time: 2018-06-26 07:08:04
GoVersion: go version go1.10.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e |
+------------------------------------------------------------------------------------

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

fixes #6910 

In MySQL-protocol for `enum` and `set` type, server send column-metadata as `string` type and remark `enum` or `set` in `flag` field.

maybe see:
https://github.com/mysql/mysql-server/blob/99a4c9262047edce8bb67086d22f745c67afe2ef/sql/field.h#L4165

https://github.com/mysql/mysql-server/blob/99a4c9262047edce8bb67086d22f745c67afe2ef/sql/field.h#L4225

### What is changed and how it works?

modify `ColumnInfo#Dump()`(write metadata stage) to return special type, and doesn't modify `column.type`, because later we will use it to write data stage.

### Check List

 - Integration test, in TiDB-Test with protocol in https://github.com/pingcap/tidb-test/pull/603

Code changes

 - Change response

Side effects

 - no

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/7417)

### CODE REVIEW

**Comment by zz-jason** [comment]
does type `bit` have the same issue?

**Comment by lysu** [comment]
it seems `bit` is ok and no magic, only `enum`/`set` return a different type - -|||

**Comment by zz-jason** [comment]
OK, LGTM

**Comment by coocood** [comment]
LGTM

**Pull request merged**
