### PR TITLE
[DNM] txn: Inject some errors for test

### PR DESCRIPTION
**Pull request by MyonKeminta**
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>

### What is changed and how it works?

What's Changed: Manually injected some failures in transaction logic.

Still thinking if there can be more, and whether the triggering probability is proper.

### Release note 

- No release note.

### CODE REVIEW

**Comment by cfzjywxk** [comment]
Some skip for async rollback pessimistic locks is needed.

**Comment by MyonKeminta** [comment]
Oh... something went wrong in the last commit

**Comment by cfzjywxk** [comment]
@zyguan @you06 This patch.

**Comment by zz-jason** [comment]
I'm going to close this PR since it hasn't been updated for a long time. feel free to reopen if you want to continue with it.

**Pull request closed without merging**
