### PR TITLE
store: fix typo

### PR DESCRIPTION
**Pull request by newer027**
Fix some small typos

### CODE REVIEW

**Comment by jackysp** [comment]
Please sign our CLA, @newer027 . Thanks!

**Comment by newer027** [comment]
@jackysp Thanks. I have signed the CLA, but the commit record of cheng-jian cannot be removed.

**Comment by zz-jason** [comment]
@newer027 Please sign the CLA.

**Comment by newer027** [comment]
@zz-jason I can not sign the CLA as cheng-jian because It's not a github account.

**Comment by jackysp** [comment]
How about git reset then commit using a github ID? And then push -f.

**Comment by newer027** [comment]
@jackysp It works, thanks!

**Comment by jackysp** [comment]
Thanks for your contribution, @newer027 !

**Pull request merged**
