### PR TITLE
lightning/parser: support STARTING BY and IGNORE n LINES

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: ref #40499

Problem Summary:

### What is changed and how it works?

- STARTING BY: add token. When meet it reset the state of parser
- IGNORE n LINES: skip output for n times readRecords

Hide these configuration for lightning, only prepare for future LOAD DATA integration

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by gozssky** [comment]
@lance6716 Could you explain why we need these two configurations? Is it possible to do them outside the parser?

**Comment by lance6716** [comment]
> @lance6716 Could you explain why we need these two configurations? Is it possible to do them outside the parser?

I can't come up with a simple change outside parser. We need use parser to know where a line ends, and these two configurations can skip errors when find line endings.

I have added some unit tests, when the skipped content contains special characters like fields delimiter it's very complex.

**Comment by lance6716** [comment]
/hold

IGNORE n LINES should be able to move out of parser, let caller call `ReadUntilTerminator` for n times. And I'll check if put more restriction on STARTING BY could simplify the code

**Comment by lance6716** [comment]
should be replaced by https://github.com/pingcap/tidb/pull/40821

**Pull request closed without merging**
