### PR TITLE
expression: check NotNullFlag of columns when simplifying binary operations (#24049)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #24049 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/24063
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/24063:release-5.0-75a031af4ad3
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23891

Problem Summary:

Wrong result of queries.

### What is changed and how it works?

What's Changed:

Check NotNullFlag in `refineArgs` before saying that the result of the expression is exceptional.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- Fix wrong query result when column contains null values

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by time-and-fate — APPROVED** [review]
/lgtm

**Pull request merged**
