### PR TITLE
lightning: make some s3/gcs external storage fields public

### LINKED ISSUE #39204: BR / Lightning : Make Some S3 / GCS `ExternalStorage` Implementations Fields Public
## Enhancement
Sometimes, when constructing an S3 / GCS implementation of `ExternalStorage`, we want to use some inner fields to do some further platform-specific operations on the storage.  For example, when we constructing an S3 `ExternalStorage`, we want to get the S3 client object, so that we can call some S3 APIs by ourselves.  In this case, we don't want to re-invent the wheel to implement the S3 client construction again, but rather reuse the S3 client from the S3 `ExternalStorage` implementation.

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: close #39204 

Problem Summary:

### What is changed and how it works?
* Expose the constructor for S3 / GCS external storage implementations.
* Expose the GCS external storage implementation public.
* Expose some fields for these implementations.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
   Write an external program to construct an S3 / GCS storage implementation, and use the newly exposed fields to achieve some S3 / GCS operations.  
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by dsdashun** [comment]
Integration BR test passed: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_br_test/detail/tidb_ghpr_integration_br_test/11103/pipeline

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
