### PR TITLE
*: Add support "show open tables" (#10166)

### PR DESCRIPTION
**Pull request by zimulala**
Cherry-pick #10166 to v2.1

Related to pingcap/parser#317

### CODE REVIEW

**Comment by zimulala** [comment]
/run-all-test tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zimulala** [comment]
/run-all-test tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zimulala** [comment]
PTAL @tiancaiamao @winkyao

**Comment by tiancaiamao** [comment]
LGTM

**Comment by jackysp** [comment]
/run-all-test tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by jackysp** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by tiancaiamao** [comment]
Please fix CI @zimulala

**Pull request merged**
