### PR TITLE
planner/cascades[WIP]: add transformation rule EliminateMultiMaxMin

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?
This PR adds Transformation rule EliminateMultiMaxMin, which is a part of max/min elimination in cascades planner.
part of #13709

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Side effects

 - Possible performance regression

### CODE REVIEW

**Comment by SeaRise** [comment]
@winoros

**Comment by SeaRise** [comment]
@winoros 
this pr conflict to RuleBatch.
So it is not yet completed..

**Comment by francis0407** [comment]
Yes, I prefer this rule to match the pattern `Aggregation -> DataSource`. If we want to that, we must implement the rule `PushSelDownDataSource`, which is blocked by this PR https://github.com/pingcap/tidb/pull/15090.

**Comment by zz-jason** [comment]
I'm going to close this PR since it hasn't been updated for a long time. feel free to reopen if you want to continue with it. thank you for your contribution.

**Pull request closed without merging**
