### PR TITLE
lightning: refine error message for empty schema file

### LINKED ISSUE #37571: Lightning: Unclear Error Message When Schema File Is Empty For an MDTableMeta
## Enhancement
Currently, when the schema file is not provided for an `MDTableMeta`, and we try to `GetSchema()` for it, the error message is not very clear about that.  For example, for an S3 data source, the error message is: 
```
get create table statement from schema file error: mytable: InvalidParameter: 1 validation error(s) found.\n- minimum field size of 1, GetObjectInput.Key.\n
```
We need to return a clear error message, indicating that the schema file is missing for the `GetSchema()` invocations.

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: close #37571 

Problem Summary:

### What is changed and how it works?
Added some logic to check whether the schema file path is empty or whether the schema file does exist.
If the checks don't pass, return a clear error.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

**Comment by dsdashun** [comment]
Integration BR test passed: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_br_test/detail/tidb_ghpr_integration_br_test/10364/pipeline

**Review by niubell — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

**Pull request merged**
