### PR TITLE
*: improve syntax error code & message compatibility

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

ref https://github.com/pingcap/parser/pull/175

and pre-append user-friendly error message, and use right error code.

### What is changed and how it works?

- ref parser
- use `SyntaxError`, `SyntaxWarn` convert error/warns returned by parser

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change

Side effects

 - N/A

Related changes

 - N/A

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/9103)

### CODE REVIEW

**Comment by lysu** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Comment by AndrewDi** [comment]
@tiancaiamao It seems like this PR has broken Integration Test:
```
FAIL: integration_test.go:3735: testIntegrationSuite.TestUnknowHintIgnore

integration_test.go:3740:
    tk.MustQuery("show warnings").Check(testkit.Rows("Warning 1064 You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 29 near \"unknown_hint(c1)*/ 1\" "))
/home/andrew/Developer/Go/src/github.com/pingcap/tidb/util/testkit/testkit.go:55:
    res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
... obtained string = "[Warning 1064 You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use near 'line 1 column 29 near \"select /*+ unknown_hint(c1)*/ 1\" (total length 31)' at line %!d(MISSING)]\n"
... expected string = "[Warning 1064 You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 29 near \"unknown_hint(c1)*/ 1\" ]\n"
... sql:show warnings, args:[]

```

**Pull request merged**
