### PR TITLE
CircleCI: upgrade go version from 1.15 to 1.16

### PR DESCRIPTION
**Pull request by ngaut**
### What problem does this PR solve?

Upgrade go version from 1.15 to 1.16

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]

**Review by jackysp — COMMENTED** [review]
lgtm

**Comment by jackysp** [comment]
> /lgtm

Seems the bot is not working in the review comment.

**Comment by hi-rustin** [comment]
@ti-chi-bot  please update this pr branch

**Pull request merged**
