### PR TITLE
util: remove Parallel for TestIndexRange

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

remove Parallel for TestIndexRange because it will try to change the global newCollationEnabled value. it will cause some problems.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by tisonkun — COMMENTED** [review]
Thanks for fixing this problem. Could you help in moving all serial tests to `range_serial_test.go`?

**Review by wjhuang2016 — APPROVED** [review]

**Comment by hawkingrei** [comment]
> Thanks for fixing this problem. Could you help in moving all serial tests to `range_serial_test.go`?

Done

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
