### PR TITLE
[DNM] Investigate ci failure

### PR DESCRIPTION
**Pull request by lonng**
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository

Release note

 - Write release note for bug-fix or new feature.

### CODE REVIEW

**Comment by H-ZeX** [comment]
If run with PR/918, then the err msg is 
```

[2019-10-17T09:27:54.507Z] 2019/10/17 17:27:54.100  [fatal] run test [window_functions] err: sql:SELECT SUM(c/d), LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)  FROM t GROUP BY a,b;: failed to run query 

[2019-10-17T09:27:54.507Z] "SELECT SUM(c/d), LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)  FROM t GROUP BY a,b;" 

[2019-10-17T09:27:54.507Z]  around line 1273, 

[2019-10-17T09:27:54.507Z] we need(168):

[2019-10-17T09:27:54.507Z] SELECT SUM(c/d), LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)  FROM t GROUP BY a,b;

[2019-10-17T09:27:54.507Z] SUM(c/d)	LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)

[2019-10-17T09:27:54.507Z] 1.000000000	1.000000000

[2019-10-17T09:27:54.507Z] 2.000000000	2.0000

[2019-10-17T09:27:54.507Z] but got(168):

[2019-10-17T09:27:54.507Z] SELECT SUM(c/d), LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)  FROM t GROUP BY a,b;

[2019-10-17T09:27:54.507Z] SUM(c/d)	LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)

[2019-10-17T09:27:54.507Z] 1.0000	1.0000

[2019-10-17T09:27:54.507Z] 2.0000	2.0000

[2019-10-17T09:27:54.507Z] 3.0000	3.0000

[2019-10-17T09:27:54.507Z] 
```

**Comment by H-ZeX** [comment]
If run with PR/918, then the err msg is, ([Ref from](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_integration_common_test/detail/tidb_ghpr_integration_common_test/6217/pipeline/)) 
```
[2019-10-17T09:27:54.507Z] 2019/10/17 17:27:54.100  [fatal] run test [window_functions] err: sql:SELECT SUM(c/d), LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)  FROM t GROUP BY a,b;: failed to run query 
[2019-10-17T09:27:54.507Z] "SELECT SUM(c/d), LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)  FROM t GROUP BY a,b;" 
[2019-10-17T09:27:54.507Z]  around line 1273, 
[2019-10-17T09:27:54.507Z] we need(168):
[2019-10-17T09:27:54.507Z] SELECT SUM(c/d), LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)  FROM t GROUP BY a,b;
[2019-10-17T09:27:54.507Z] SUM(c/d)	LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)
[2019-10-17T09:27:54.507Z] 1.000000000	1.000000000
[2019-10-17T09:27:54.507Z] 2.000000000	2.0000
[2019-10-17T09:27:54.507Z] but got(168):
[2019-10-17T09:27:54.507Z] SELECT SUM(c/d), LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)  FROM t GROUP BY a,b;
[2019-10-17T09:27:54.507Z] SUM(c/d)	LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)
[2019-10-17T09:27:54.507Z] 1.0000	1.0000
[2019-10-17T09:27:54.507Z] 2.0000	2.0000
[2019-10-17T09:27:54.507Z] 3.0000	3.0000
[2019-10-17T09:27:54.507Z] 
```

However, if run with the PR/919, it is ok.

**Comment by H-ZeX** [comment]
For `tidb_ghpr_integration_common_test`, if run `/run-all-tests tidb-test=pr/921`, it will fail, if run `/run-all-tests tidb-test=pr/919`, it will pass.
image

For `tidb_ghpr_common_test`, if run `/run-all-tests tidb-test=pr/921`, it will pass, if run `/run-all-tests tidb-test=pr/919`, it will fail.
image

use PR/919, PR/918's commit (until 2019.10.19 00:32)

**Comment by H-ZeX** [comment]
[This test, tidb_ghpr_integration_common_test 6310](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_integration_common_test/detail/tidb_ghpr_integration_common_test/6310/pipeline/115) use right TiDB version and right mysql test script version

```
[2019-10-18T16:15:37.225Z] + echo 'tidb-server-version: '
[2019-10-18T16:15:37.225Z] tidb-server-version: 
[2019-10-18T16:15:37.225Z] ++ /home/jenkins/workspace/tidb_ghpr_integration_common_test/go/src/github.com/pingcap/tidb-test/mysql_test/bin/tidb-server -V
[2019-10-18T16:15:37.225Z] + echo Release Version: v4.0.0-alpha-568-g70ed27c69b Git Commit Hash: 70ed27c69b1b19eeaa0c90ebacede1a28a4b1621 Git Branch: HEAD UTC Build Time: 2019-10-17 08:27:02 GoVersion: go version go1.13 linux/amd64 Race Enabled: false TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 Check Table Before Drop: false
[2019-10-18T16:15:37.225Z] Release Version: v4.0.0-alpha-568-g70ed27c69b Git Commit Hash: 70ed27c69b1b19eeaa0c90ebacede1a28a4b1621 Git Branch: HEAD UTC Build Time: 2019-10-17 08:27:02 GoVersion: go version go1.13 linux/amd64 Race Enabled: false TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 Check Table Before Drop: false
```
But its result is wrong. This version's TiDB should has this result (TODO, I need to download 70ed27c69b1b19eeaa0c90ebacede1a28a4b1621 ‘s TiDB to check.)
```
[2019-10-17T09:27:54.507Z] SELECT SUM(c/d), LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)  FROM t GROUP BY a,b;
[2019-10-17T09:27:54.507Z] SUM(c/d)	LAST_VALUE(SUM(c/d)) OVER (ORDER BY a)
[2019-10-17T09:27:54.507Z] 1.000000000	1.000000000
[2019-10-17T09:27:54.507Z] 2.000000000	2.0000
```

However, [This test, tidb_ghpr_common_test 6373](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/6373/pipeline/)'s TiDB version may be right 
image.
And it's TiDB output is right. 
image

**Comment by zz-jason** [comment]
@lonng can we close this PR now?

**Pull request closed without merging**
