### PR TITLE
server: do not set opentracing span context  unnecessarily

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Problem Summary:

https://github.com/pingcap/tidb/pull/20330 introduce this issue.
When open tracing is not enabled in the configuration file, there is no need to set the span in the context.

Set the `span` would activate this kind of code at the whole codebase, and brings roughly 5% performance penalty.

```
	if span := opentracing.SpanFromContext(ctx); span != nil && span.Tracer() != nil {
		span1 := span.Tracer().StartSpan("session.doCommitWitRetry", opentracing.ChildOf(span.Context()))
		defer span1.Finish()
		ctx = opentracing.ContextWithSpan(ctx, span1)
	}
```

### What is changed and how it works?

What's Changed:

do not set opentracing span context  unnecessarily

How it Works:

So avoid the unnecessary performance penalty

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

### Release note 

- No release note

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
Nice catch

**Comment by tiancaiamao** [comment]
PTAL @bb7133

**Pull request merged**
