### PR TITLE
planner: Fix the issue that TiDB may dispatch duplicated tasks to TiFlash (#32813)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #32813 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/32840
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/32840:release-5.3-fcdbf826ea8a
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/32814, https://github.com/pingcap/tics/issues/4163

Problem Summary:

1. if a fragment has two children, one's ExchangeSender is Broadcast Type, another's is Type PassThrough.
2. This fragment should be singleton, but because of the wrong implementation, it isn't.
3. So this fragment will generate two tasks, and the data will be double.

### What is changed and how it works?

if there is one child with passthrough exchangeType, the fragment will be singleton.

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
planner: Fix the issue that TiDB may dispatch duplicated tasks to TiFlash
```

### CODE REVIEW

**Review by LittleFall — APPROVED** [review]

**Review by LittleFall — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM

**Comment by LittleFall** [comment]
[2022-06-14T10:51:53.852Z] FAIL: executor_test.go:52: testChecksumSuite.TestChecksum

[2022-06-14T10:51:53.852Z] 

[2022-06-14T10:51:53.852Z] executor_test.go:53:

[2022-06-14T10:51:53.852Z]     c.Assert(s.mock.Start(), IsNil)

[2022-06-14T10:51:53.852Z] ... value *errors.withStack = unix socket /tmp/tidb-{Port}.sock exists and is functional, not removing it ("unix socket /tmp/tidb-{Port}.sock exists and is functional, not removing it")

[2022-06-14T10:51:53.852Z] 

[2022-06-14T10:51:53.852Z] OOPS: 0 passed, 1 FAILED

**Comment by LittleFall** [comment]
[2022-06-14T11:08:11.070Z] FAIL: db_test.go:1688: testDBSuite1.TestDropPrimaryKey
[2022-06-14T11:08:11.070Z] 
[2022-06-14T11:08:11.070Z] db_test.go:1692:
[2022-06-14T11:08:11.070Z]     testDropIndex(c, s.store, s.lease, createSQL, dropIdxSQL, idxName)
[2022-06-14T11:08:11.070Z] db_test.go:2022:
[2022-06-14T11:08:11.070Z]     c.Assert(handles, HasLen, 0, Commentf("take time %v", time.Since(startTime)))
[2022-06-14T11:08:11.070Z] ... obtained map[int64]struct {} = map[int64]struct {}{1:struct {}{}, 2:struct {}{}, 3:struct {}{}, 4:struct {}{}, 5:struct {}{}, 6:struct {}{}, 7:struct {}{}, 8:struct {}{}, 9:struct {}{}, 10:struct {}{}, 11:struct {}{}, 12:struct {}{}, 13:struct {}{}, 14:struct {}{}, 15:struct {}{}, 16:struct {}{}, 17:struct {}{}, 18:struct {}{}, 19:struct {}{}, 20:struct {}{}, 21:struct {}{}, 22:struct {}{}, 23:struct {}{}, 24:struct {}{}, 25:struct {}{}, 26:struct {}{}, 27:struct {}{}, 28:struct {}{}, 29:struct {}{}, 30:struct {}{}, 31:struct {}{}, 32:struct {}{}, 33:struct {}{}, 34:struct {}{}, 35:struct {}{}, 36:struct {}{}, 37:struct {}{}, 38:struct {}{}, 39:struct {}{}, 40:struct {}{}, 41:struct {}{}, 42:struct {}{}, 43:struct {}{}, 44:struct {}{}, 45:struct {}{}, 46:struct {}{}, 47:struct {}{}, 48:struct {}{}, 49:struct {}{}, 50:struct {}{}, 51:struct {}{}, 52:struct {}{}, 53:struct {}{}, 54:struct {}{}, 55:struct {}{}, 56:struct {}{}, 57:struct {}{}, 58:struct {}{}, 59:struct {}{}, 60:struct {}{}, 61:struct {}{}, 62:struct {}{}, 63:struct {}{}, 64:struct {}{}, 65:struct {}{}, 66:struct {}{}, 67:struct {}{}, 68:struct {}{}, 69:struct {}{}, 70:struct {}{}, 71:struct {}{}, 72:struct {}{}, 73:struct {}{}, 74:struct {}{}, 75:struct {}{}, 76:struct {}{}, 77:struct {}{}, 78:struct {}{}, 79:struct {}{}, 80:struct {}{}, 81:struct {}{}, 82:struct {}{}, 83:struct {}{}, 84:struct {}{}, 85:struct {}{}, 86:struct {}{}, 87:struct {}{}, 88:struct {}{}, 89:struct {}{}, 90:struct {}{}, 91:struct {}{}, 92:struct {}{}, 93:struct {}{}, 94:struct {}{}, 95:struct {}{}, 96:struct {}{}, 97:struct {}{}, 98:struct {}{}, 99:struct {}{}, 100:struct {}{}}
[2022-06-14T11:08:11.070Z] ... n int = 0
[2022-06-14T11:08:11.070Z] ... take time 15.250932146s
[2022-06-14T11:08:11.070Z]

**Comment by LittleFall** [comment]
unit-test broken, wait until it fixed

**Pull request merged**
