### PR TITLE
vendor: Update pdClient and kvproto

### PR DESCRIPTION
**Pull request by MyonKeminta**
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>

### What problem does this PR solve? 

This PR updates pdClient and kvproto to latest version.

### What is changed and how it works?

None.

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by MyonKeminta** [comment]
@coocood @zhangjinpeng1987 Please help me merge it, thanks

**Pull request merged**
