### PR TITLE
plugin/conn_ip_example_test.go: migrate test-infra to testify

### LINKED ISSUE #26745: migrate test-infra to testify for `plugin/conn_ip_example_test.go`

### PR DESCRIPTION
**Pull request by unconsolable**
Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>

### What problem does this PR solve?

Issue Number: close #26745 

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM

**Review by morgo — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by unconsolable** [comment]
> /run-check_dev_2

I found that the check failed at `tidb_test.go`
```
[2021-08-02T02:05:47.502Z] ----------------------------------------------------------------------
[2021-08-02T02:05:47.502Z] FAIL: tidb_test.go:866: tidbTestSerialSuite.TestTLS
[2021-08-02T02:05:47.502Z] 
[2021-08-02T02:05:47.502Z] tidb_test.go:960:
[2021-08-02T02:05:47.502Z]     c.Assert(stats["Ssl_server_not_before"], Equals, serverCert.NotBefore.Format("Jan _2 15:04:05 2006 MST"))
[2021-08-02T02:05:47.502Z] ... obtained string = "Aug 2 01:55:19 2021 UTC"
[2021-08-02T02:05:47.502Z] ... expected string = "Aug  2 01:55:19 2021 UTC"
[2021-08-02T02:05:47.502Z] 
```

Corresponding check logic in `tidb_test.go` is as follows: 
```go
c.Assert(err, IsNil)
c.Assert(stats, HasKey, "Ssl_server_not_after")
c.Assert(stats, HasKey, "Ssl_server_not_before")
c.Assert(stats["Ssl_server_not_after"], Equals, serverCert.NotAfter.Format("Jan _2 15:04:05 2006 MST"))
c.Assert(stats["Ssl_server_not_before"], Equals, serverCert.NotBefore.Format("Jan _2 15:04:05 2006 MST"))
```

However, generate `stats["Ssl_server_not_before"]` in `stat.go` is as follows:
```go
if tlsConfig != nil {
	if len(tlsConfig.Certificates) == 1 {
		pc, err := x509.ParseCertificate(tlsConfig.Certificates[0].Certificate[0])
		if err != nil {
			logutil.BgLogger().Error("Failed to parse TLS certficates to get server status", zap.Error(err))
		} else {
			m[serverNotAfter] = pc.NotAfter.Format("Jan _2 15:04:05 2006 MST")
			m[serverNotBefore] = pc.NotBefore.Format("Jan 2 15:04:05 2006 MST")
		}
	}
}
```

Maybe different time format leads to the error?

**Comment by tisonkun** [comment]
> > /run-check_dev_2
> 
> I found that the check failed at `tidb_test.go`
> 
> ```
> [2021-08-02T02:05:47.502Z] ----------------------------------------------------------------------
> [2021-08-02T02:05:47.502Z] FAIL: tidb_test.go:866: tidbTestSerialSuite.TestTLS
> [2021-08-02T02:05:47.502Z] 
> [2021-08-02T02:05:47.502Z] tidb_test.go:960:
> [2021-08-02T02:05:47.502Z]     c.Assert(stats["Ssl_server_not_before"], Equals, serverCert.NotBefore.Format("Jan _2 15:04:05 2006 MST"))
> [2021-08-02T02:05:47.502Z] ... obtained string = "Aug 2 01:55:19 2021 UTC"
> [2021-08-02T02:05:47.502Z] ... expected string = "Aug  2 01:55:19 2021 UTC"
> [2021-08-02T02:05:47.502Z] 
> ```
> 
> Corresponding check logic in `tidb_test.go` is as follows:
> 
> ```go
> c.Assert(err, IsNil)
> c.Assert(stats, HasKey, "Ssl_server_not_after")
> c.Assert(stats, HasKey, "Ssl_server_not_before")
> c.Assert(stats["Ssl_server_not_after"], Equals, serverCert.NotAfter.Format("Jan _2 15:04:05 2006 MST"))
> c.Assert(stats["Ssl_server_not_before"], Equals, serverCert.NotBefore.Format("Jan _2 15:04:05 2006 MST"))
> ```
> 
> However, generate `stats["Ssl_server_not_before"]` in `stat.go` is as follows:
> 
> ```go
> if tlsConfig != nil {
> 	if len(tlsConfig.Certificates) == 1 {
> 		pc, err := x509.ParseCertificate(tlsConfig.Certificates[0].Certificate[0])
> 		if err != nil {
> 			logutil.BgLogger().Error("Failed to parse TLS certficates to get server status", zap.Error(err))
> 		} else {
> 			m[serverNotAfter] = pc.NotAfter.Format("Jan _2 15:04:05 2006 MST")
> 			m[serverNotBefore] = pc.NotBefore.Format("Jan 2 15:04:05 2006 MST")
> 		}
> 	}
> }
> ```
> 
> Maybe different time format leads to the error?

You're right and there is a fix https://github.com/pingcap/tidb/pull/26781 . Let's wait a bit.

**Pull request merged**
