### PR TITLE
session:don't use utc to created a customized timezone but empty string 

### PR DESCRIPTION
**Pull request by zhexuany**
### What problem does this PR solve? 
This PR does not resolve any problem or bug, but it clears the confusion. 

~UTC is known as timezone with 0 timezone offset. We created a customized time zone with this name but not with 0-time zone offset. This behavior may cause potential confusion which can be cleared by this PR.~

### What is changed and how it works?
~The strategy of the naming part is when we want to create a customized time zone with the offset. We just add `-offset` right after `UTC` if the offset is smaller than 0.  If the offset is larger than 0, then we append `+offset` after `utc`~

Only use the empty string to create customised time zone. 
### Check List 

Tests 

 no need to add the new test.

### CODE REVIEW

**Comment by coocood** [comment]
I think we should use the empty string for consistency.

**Comment by coocood** [comment]
LGTM

**Comment by zhexuany** [comment]
cc @coocood just update my changes, please take a look.

**Comment by coocood** [comment]
Need to update here as well?
https://github.com/pingcap/tidb/blob/master/types/convert_test.go#L699

**Comment by XuHuaiyu** [comment]
A comment needs to be addressed. @zhexuany

**Comment by zhexuany** [comment]
@coocood @XuHuaiyu Just addressed the comment. Could you take a look when you have time?

**Pull request merged**
