### PR TITLE
ddl: refine pre-split region logic

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
The original logic of `pre_split_region` will split 2^(`pre_split_region -1`) regions. It was strange for the user to understand and remember it.

This PR will simply split 2^(`pre_split_region`) regions when `create table` with `pre_split_region`.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

Related changes

 - Need to cherry-pick to the release branch

Release Note
 - Change `pre_split_regions` logic for easy to understand and remember.

### CODE REVIEW

**Comment by crazycs520** [comment]
Related docs PR: https://github.com/pingcap/docs-cn/pull/1780

**Comment by zz-jason** [comment]
@crazycs520 Can we make `pre_split_region` to be a boolean value? Let `shard_row_id_bits` to control the number of regions/shards to be split if that option is turned on?

**Comment by crazycs520** [comment]
@zz-jason For the compatibility, not suggest making `pre_split_region` to be a boolean value.
We plan to add 2 new option: `row_id_shard_count` , `pre_split_region_count`, then gradually deprecated `pre_split_region` and `shard_row_id_bit`

**Pull request merged**
