### PR TITLE
parser: support 'use index' in delete statement from single table

### PR DESCRIPTION
**Pull request by lzmhhh123**
The `TableSource` in `DELETE FROM` is realized by `type Join`. So, we just add the `IndexHintListOpt` in sql matching rules in parser, that we can use `USE INDEX` hint in delete statement without change plan.

### CODE REVIEW

**Comment by winoros** [comment]
Add a test in plan package to test whether the hint takes effect.

**Comment by zz-jason** [comment]
We can firstly support the syntax. @winoros

**Comment by lzmhhh123** [comment]
@winoros I have added a test case in `physical_plan_test.go`, PTAL.

**Pull request merged**
