### PR TITLE
server: support forward request for plan replayer with tls enabled

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/29213

Problem Summary:

### What is changed and how it works?

support forward request for plan replayer with tls enabled

### Check List

Tests 

- [x] Manual test (add detailed scripts or steps below)

1. Deploy tidb cluster with 2 tidb-server and with tls enabled.
2. Get url token from tidb-server 1
3. Send download request by url to tidb-server 2
4. tidb-server 2 can forward request to tidb-server in order to provide the plan replayer file

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Comment by xhebox** [comment]
@Yisaer Please ignore G402 to fix CI. Or use real certs from options.

**Review by xhebox — APPROVED** [review]

**Comment by Yisaer** [comment]
> ignore G402 to fix CI. Or use real certs from options

updated.

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
