### PR TITLE
metrics: remove useless tikvclient_backoff_total

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve? 
After https://github.com/pingcap/tidb-ansible/pull/1067, tikvclient_backoff_total is useless anymore.

### What is changed and how it works?
Remove it.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
Start a cluster to check the metrics of KV backoff OPS in TiDB.

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by lysu** [comment]
please fix build

**Pull request merged**
