### PR TITLE
lightning: fix integration test

### LINKED ISSUE #41960: Release-6.5 Branch BR Integration Test Failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Run the `lightning_reload_cert` integration test

### 2. What did you expect to see? (Required)
The test should pass.

### 3. What did you see instead (Required)
The test failed.  Reporting the following:
`lightning should report connection error due to certificate expired, but no error is reported`

### 4. What is your TiDB version? (Required)
latest commit in release-6.5 branch

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: close #41960 

Problem Summary:

### What is changed and how it works?
Fixed the integration test failure introduced by https://github.com/pingcap/tidb/pull/40793

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by maxshuang — APPROVED** [review]

**Review by niubell — APPROVED** [review]
LGTM

**Comment by dsdashun** [comment]
Integration test passed: https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/15425/pipeline/124/

**Pull request merged**
