### PR TITLE
executor,store: fix a bug caused by HashJoinExec encode/decode

### PR DESCRIPTION
**Pull request by tiancaiamao**
HashJoinExec encodeRow method doesn't consider timezone,
but decodeRow method does, this introduce a bug.

The test case can reproduce the bug, it get wrong result '2003-06-09 18:51:26'

PTAL @coocood @hanfei1991 @zimulala @shenli @XuHuaiyu

### CODE REVIEW

**Comment by zimulala** [comment]
Need to do the same thing in mockTiKV?

**Comment by hanfei1991** [comment]
LGTM

**Comment by tiancaiamao** [comment]
mockTiKV already use timezone. @zimulala

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
