### PR TITLE
infoschema: fix the nil pointer

### LINKED ISSUE #52842: pdms: Sometimes, the INFORMATION_SCHEMA.cluster_info table does not show the PDMS instance when there are multiple PD instances deployed.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)
```
sh-4.2# tiup cluster display tidbcluster
Cluster type:       tidb
Cluster name:       tidbcluster
Cluster version:    v8.1.0-pre
Deploy user:        root
SSH type:           builtin
Dashboard URL:      http://pd1-peer:2379/dashboard
Grafana URL:        http://tiup-peer:3000
ID                     Role          Host              Ports        OS/Arch       Status  Data Dir                       Deploy Dir
--                     ----          ----              -----        -------       ------  --------                       ----------
tiup-peer:19093        alertmanager  tiup-peer         19093/19094  linux/x86_64  Up      /tiup/data/alertmanager-19093  /tiup/deploy/alertmanager-19093
tiup-peer:3000         grafana       tiup-peer         3000         linux/x86_64  Up      -                              /tiup/deploy/grafana-3000
pd1-peer:2379          pd            pd1-peer          2379/2380    linux/x86_64  Up|UI   /tiup/data/pd-2379             /tiup/deploy/pd-2379
pd2-peer:2379          pd            pd2-peer          2379/2380    linux/x86_64  Up|L    /tiup/data/pd-2379             /tiup/deploy/pd-2379
pd3-peer:2379          pd            pd3-peer          2379/2380    linux/x86_64  Up      /tiup/data/pd-2379             /tiup/deploy/pd-2379
tiup-peer:9090         prometheus    tiup-peer         9090/12020   linux/x86_64  Up      /tiup/data/prometheus-9090     /tiup/deploy/prometheus-9090
scheduling1-peer:3379  scheduling    scheduling1-peer  3379         linux/x86_64  Up      /tiup/data/scheduling-3379     /tiup/deploy/scheduling-3379
scheduling2-peer:3379  scheduling    scheduling2-peer  3379         linux/x86_64  Up|P    /tiup/data/scheduling-3379     /tiup/deploy/scheduling-3379
tidb1-peer:4000        tidb          tidb1-peer        4000/10080   linux/x86_64  Up      -                              /tiup/deploy/tidb-4000
tidb2-peer:4000        tidb          tidb2-peer        4000/10080   linux/x86_64  Up      -                              /tiup/deploy/tidb-4000
tikv1-peer:20160       tikv          tikv1-peer        20160/20180  linux/x86_64  Up      /tiup/data/tikv-20160          /tiup/deploy/tikv-20160
tikv2-peer:20160       tikv          tikv2-peer        20160/20180  linux/x86_64  Up      /tiup/data/tikv-20160          /tiup/deploy/tikv-20160
tikv3-peer:20160       tikv          tikv3-peer        20160/20180  linux/x86_64  Up      /tiup/data/tikv-20160          /tiup/deploy/tikv-20160
tso1-peer:3379         tso           tso1-peer         3379         linux/x86_64  Up|P    /tiup/data/tso-3379            /tiup/deploy/tso-3379
tso2-peer:3379         tso           tso2-peer         3379         linux/x86_64  Up      /tiup/data/tso-3379            /tiup/deploy/tso-3379
```

```
MySQL [INFORMATION_SCHEMA]> select * from cluster_info;
+------+------------------+------------------+---------+------------------------------------------+---------------------+--------------------+-----------+
| TYPE | INSTANCE         | STATUS_ADDRESS   | VERSION | GIT_HASH                                 | START_TIME          | UPTIME             | SERVER_ID |
+------+------------------+------------------+---------+------------------------------------------+---------------------+--------------------+-----------+
| tidb | tidb1-peer:4000  | tidb1-peer:10080 | 8.1.0   | cfeca9b1b6976d355e8181475d6d0cb5792daade | 2024-04-23 13:23:17 | 1h34m58.088693769s |      1313 |
| tidb | tidb2-peer:4000  | tidb2-peer:10080 | 8.1.0   | cfeca9b1b6976d355e8181475d6d0cb5792daade | 2024-04-23 13:23:20 | 1h34m55.088698107s |       988 |
| pd   | pd1-peer:2379    | pd1-peer:2379    | 8.1.0   | 4e13bfc36a2073c5788d5b90be4e4418aea6da5a | 2024-04-23 13:20:44 | 1h37m31.088699322s |         0 |
| pd   | pd2-peer:2379    | pd2-peer:2379    | 8.1.0   | 4e13bfc36a2073c5788d5b90be4e4418aea6da5a | 2024-04-23 13:20:47 | 1h37m28.088700272s |         0 |
| pd   | pd3-peer:2379    | pd3-peer:2379    | 8.1.0   | 4e13bfc36a2073c5788d5b90be4e4418aea6da5a | 2024-04-23 13:20:53 | 1h37m22.088702396s |         0 |
| tikv | tikv2-peer:20160 | tikv2-peer:20180 | 8.1.0   | d512fedad46c4624b4ad025900be605e5a92ec5f | 2024-04-23 13:22:42 | 1h35m33.088703366s |         0 |
| tikv | tikv3-peer:20160 | tikv3-peer:20180 | 8.1.0   | d512fedad46c4624b4ad025900be605e5a92ec5f | 2024-04-23 13:22:59 | 1h35m16.088704244s |         0 |
| tikv | tikv1-peer:20160 | tikv1-peer:20180 | 8.1.0   | d512fedad46c4624b4ad025900be605e5a92ec5f | 2024-04-23 13:22:08 | 1h36m7.088705131s  |         0 |
+------+------------------+------------------+---------+------------------------------------------+---------------------+--------------------+-----------+
8 rows in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)
v8.1.0

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: close #52842

Problem Summary:

### Check List

Tests 

- [x] Manual test 

5 pd and let 2 of them down

```
[root@tiup-0 ~]# mysql -uroot -P4000 -h tidb2-peer
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 1891631112
Server version: 8.0.11-TiDB-v8.1.0 TiDB Server (Apache License 2.0) Community Edition, MySQL 8.0 compatible

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> select * from INFORMATION_SCHEMA.CLUSTER_INFO;
+-------+------------------+------------------+---------+------------------------------------------+---------------------+--------------------+-----------+
| TYPE  | INSTANCE         | STATUS_ADDRESS   | VERSION | GIT_HASH                                 | START_TIME          | UPTIME             | SERVER_ID |
+-------+------------------+------------------+---------+------------------------------------------+---------------------+--------------------+-----------+
| tidb  | tidb1-peer:4000  | tidb1-peer:10080 | 8.1.0   | de597811f9f9c9d35d2672bea19f47c9ba640aaa | 2024-05-08 12:15:52 | 4m12.910063312s    |       354 |
| tidb  | tidb2-peer:4000  | tidb2-peer:10080 | 8.1.0   | de597811f9f9c9d35d2672bea19f47c9ba640aaa | 2024-05-08 12:19:24 | 40.910070448s      |       902 |
| pd    | pd1-peer:2379    | pd1-peer:2379    | 8.1.0   | 13eaf8aaa661dc0d3885ac9e59145f69752cee2d | 2024-05-08 10:34:06 | 1h45m58.910073449s |         0 |
| pd    | pd2-peer:2379    | pd2-peer:2379    | 8.1.0   | 13eaf8aaa661dc0d3885ac9e59145f69752cee2d | 2024-05-08 10:34:06 | 1h45m58.910078184s |         0 |
| pd    | pd3-peer:2379    | pd3-peer:2379    | 8.1.0   | 13eaf8aaa661dc0d3885ac9e59145f69752cee2d | 2024-05-08 10:34:06 | 1h45m58.910082244s |         0 |
| tikv  | tikv1-peer:20160 | tikv1-peer:20180 | 8.1.0   | 56613f7c3e28c02853cc51d15bc1b77f68b58be8 | 2024-05-08 10:34:08 | 1h45m56.910086149s |         0 |
| tikv  | tikv6-peer:20160 | tikv6-peer:20180 | 8.1.0   | 56613f7c3e28c02853cc51d15bc1b77f68b58be8 | 2024-05-08 10:34:08 | 1h45m56.910097746s |         0 |
| tikv  | tikv4-peer:20160 | tikv4-peer:20180 | 8.1.0   | 56613f7c3e28c02853cc51d15bc1b77f68b58be8 | 2024-05-08 10:34:08 | 1h45m56.910100326s |         0 |
| tikv  | tikv5-peer:20160 | tikv5-peer:20180 | 8.1.0   | 56613f7c3e28c02853cc51d15bc1b77f68b58be8 | 2024-05-08 10:34:08 | 1h45m56.910106934s |         0 |
| tikv  | tikv3-peer:20160 | tikv3-peer:20180 | 8.1.0   | 56613f7c3e28c02853cc51d15bc1b77f68b58be8 | 2024-05-08 10:34:08 | 1h45m56.910109353s |         0 |
| tikv  | tikv2-peer:20160 | tikv2-peer:20180 | 8.1.0   | 56613f7c3e28c02853cc51d15bc1b77f68b58be8 | 2024-05-08 10:34:08 | 1h45m56.910111749s |         0 |
| ticdc | ticdc1-peer:8300 | ticdc1-peer:8300 | 8.1.0   | d40018ffe07b288952b786f119bb70994f73f7f0 | 2024-05-08 10:38:30 | 1h41m34.910114169s |         0 |
| ticdc | ticdc2-peer:8300 | ticdc2-peer:8300 | 8.1.0   | d40018ffe07b288952b786f119bb70994f73f7f0 | 2024-05-08 10:38:30 | 1h41m34.910116453s |         0 |
+-------+------------------+------------------+---------+------------------------------------------+---------------------+--------------------+-----------+
13 rows in set, 6 warnings (0.04 sec)
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by rleungx** [comment]
/test check-dev2
--

**Pull request merged**
