### PR TITLE
planner: keep the original join schema in predicate pushdown (#24862)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #24862 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/28295
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/28295:release-5.0-5d7c852770eb
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tics/issues/1978

Problem Summary:

Panic caused by join schema changes in predicate pushdown.

### What is changed and how it works?

What's Changed:

Keep the original join schema in predicate pushdown, instead of generating a new one from the child operators.

How it Works:

We don't infer NotNull info from scalar functions now, so we don't need to update the join schema in predicate pushdown. I have tried adding a new projection on top of join if the schema changes, it would break a lot of tests, so I simply remove the `mergeSchema()` function call.

### Related changes

N/A

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- Keep the original join schema in predicate pushdown

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Comment by qw4990** [comment]
All panics have the same stack with https://github.com/pingcap/tidb/issues/23030, so it seems we have to pick https://github.com/pingcap/tidb/pull/23246 first.

**Comment by qw4990** [comment]
Wait for https://github.com/pingcap/tidb/pull/30881

**Pull request merged**
