### PR TITLE
ddl: migrate test-infra to testify for column modify tests 

### LINKED ISSUE #32935: migrate test-infra to testify for column modified tests

### PR DESCRIPTION
**Pull request by tisonkun**
### What problem does this PR solve?

Issue Number: close #32935 

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
@tisonkun  Please fix the linter.

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
