### PR TITLE
*: use the unified log format for the remaining packages (#9743)

### PR DESCRIPTION
**Pull request by zimulala**
Cherry-pick #9743 to v2.1

### CODE REVIEW

**Comment by zimulala** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by jackysp** [comment]
Should we keep on using "golang.org/x/net/context" instead of "context" in release 2.1?

**Comment by zimulala** [comment]
@jackysp I don't know, I see some places use "context", so I use it. What is your suggestion?

**Comment by jackysp** [comment]
Maybe we need to replace all the "golang.org/x/net/context" to "context" in the future.

**Comment by zz-jason** [comment]
@zimulala please resolve conflicts

**Comment by zimulala** [comment]
PTAL @crazycs520 @XuHuaiyu

**Comment by XuHuaiyu** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
