### PR TITLE
test: make TestFromUnixTime stable in different timezone

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Problem Summary:

parser's circleci test use different timezone cause test fail in TestFromUnixTime

https://circleci.com/gh/pingcap/parser/5283?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### What is changed and how it works?

What's Changed:

fix timezone as UTC when running this test.

### Related changes

- Need to cherry-pick to the release branch(need help 3.0/3.1 parser CI)

### Check List 

Tests 

- Unit test

Side effects

- only test code

### Release note 

n/a

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/16692)

### CODE REVIEW

**Comment by cfzjywxk** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

```
[2020-04-22T09:52:16.625Z] ==================
[2020-04-22T09:52:16.625Z] WARNING: DATA RACE
[2020-04-22T09:52:16.625Z] Write at 0x00000562efb0 by goroutine 126:
[2020-04-22T09:52:16.625Z]   github.com/pingcap/tidb/executor/seqtest_test.(*testOOMSuite).registerHook()
[2020-04-22T09:52:16.625Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200117041106-d28c14d3b1cd/log.go:110 +0x271
[2020-04-22T09:52:16.625Z]   github.com/pingcap/tidb/executor/seqtest_test.(*testOOMSuite).SetUpSuite()
[2020-04-22T09:52:16.625Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/seqtest/seq_executor_test.go:1402 +0x50
[2020-04-22T09:52:16.625Z]   runtime.call32()
[2020-04-22T09:52:16.625Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a
[2020-04-22T09:52:16.625Z]   reflect.Value.Call()
[2020-04-22T09:52:16.625Z]       /usr/local/go/src/reflect/value.go:321 +0xd3
[2020-04-22T09:52:16.625Z]   github.com/pingcap/check.(*suiteRunner).runFixture.func1()
[2020-04-22T09:52:16.625Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:799 +0x195
[2020-04-22T09:52:16.625Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2020-04-22T09:52:16.625Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113
[2020-04-22T09:52:16.625Z] 
[2020-04-22T09:52:16.625Z] Previous read at 0x00000562efb0 by goroutine 175:
[2020-04-22T09:52:16.625Z]   github.com/pingcap/tidb/domain.(*Domain).handleEvolvePlanTasksLoop.func1.1()
[2020-04-22T09:52:16.625Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/logutil/log.go:344 +0x5d
[2020-04-22T09:52:16.626Z]   github.com/pingcap/tidb/domain.(*Domain).handleEvolvePlanTasksLoop.func1()
[2020-04-22T09:52:16.626Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/domain/domain.go:942 +0x4ef
```

**Comment by zz-jason** [comment]
@lysu do we need to cherry-pick it to release-4.0?

**Pull request merged**
