### PR TITLE
store,kv: snapshot doesn't cache the non-exists kv entries lead to poor 'insert ignore' performance (#12872)

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry-pick https://github.com/pingcap/tidb/pull/12872

### CODE REVIEW

**Comment by tiancaiamao** [comment]
/run-all-tests

PTAL @jackysp @coocood @crazycs520

**Comment by coocood** [comment]
LGTM

**Comment by ngaut** [comment]
Do we have benchmark for "insert ignore" SQL?

**Comment by tiancaiamao** [comment]
Not yet. I test the case manually in this PR and working with our QA team to add such a bench test to our system.
@ngaut 

/rebuild

**Pull request merged**
