### PR TITLE
bootstrap: add mysql.user columns for parser#1121 (#21856)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21856 to release-5.0-rc

---

### What problem does this PR solve?

Problem Summary: https://github.com/pingcap/parser/pull/1121 added `Repl_client_priv` and `Repl_slave_priv` to support parsing `REPLICATION CLIENT`, `REPLICATION SLAVE`. In order make TiDB compatible with parser, I added those two columns to `mysql.user`

needed for https://github.com/pingcap/dm/issues/1320

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- pass original tests

Side effects

### Release note 

- No release note

### CODE REVIEW

**Comment by lance6716** [comment]
reminder: don't forget https://github.com/pingcap/tidb/pull/22011

**Comment by lance6716** [comment]
ping @XuHuaiyu

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
