### PR TITLE
expression: migrate test-infra to testify for constant_fold_test.go

### LINKED ISSUE #28851: migrate test-infra to testify for `expression/constant_fold_test.go`

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #28851.

Signed-off-by: tison <wander4096@gmail.com>

### Release note

```release-note
None
```

/cc @xhebox @hawkingrei

### CODE REVIEW

**Review by LittleFall — APPROVED** [review]
LGTM~

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
