### PR TITLE
session,sessionctx: enable tidb_enable_paging by default

### LINKED ISSUE #35273: enable coprocessor paging by default
## Enhancement

I want to expose enable coprocessor paging by default so the bugs can be exposed as soon as possible.
And we have enough time to handle them before the next release.

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #35273

Problem Summary:

~~Please review https://github.com/pingcap/tidb/pull/35244 first, this is based on that PR.~~

### What is changed and how it works?

Set the default `tidb_enable_paging` value to true.
For the newly bootstraped cluster, the global variable `tidb_enable_paging` is set.
For the old cluster, the default value is not changed.

The would make us cover the bugs as soon as possible before the next release.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
For a newly bootstraped cluster, the default value of `tidb_enable_paging` is true. The coprocessor paging protocol is enabled by default. For existing cluster, the default value is still false unless the user set it explicitly. 
```

### CODE REVIEW

**Review by XuHuaiyu — APPROVED** [review]

**Comment by tiancaiamao** [comment]
ref #35633

**Review by wshwsh12 — APPROVED** [review]

**Pull request merged**
