### PR TITLE
br: remove cdclog in br

### PR DESCRIPTION
**Pull request by joccau**
Signed-off-by: joccau <zak.zhao@pingcap.com>

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:
Delete code about `cdclog` in `br`. 
It related to https://github.com/pingcap/ticdc/pull/3599

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Review by fengou1 — APPROVED** [review]
LGTM, it looks those code shall be removed from br repo.

**Review by YuJuncen — APPROVED** [review]

**Pull request merged**
