### PR TITLE
executor: fix join result generator's bug.

### LINKED ISSUE #5326: unexpected error occurred when run randgen
Please answer these questions before submitting your issue. Thanks!
PTAL @winoros 

1. What did you do?
```
./gentest.pl --dsn dbi:mysql:host=127.0.0.1:port=4000:user=root:database=test --grammar=conf/optimizer_subquery.yy --gendata --thread=1
```

```sql

-- ----------------------------
--  Table structure for `C`
-- ----------------------------
DROP TABLE IF EXISTS `C`;
CREATE TABLE `C` (
  `pk` int(11) NOT NULL AUTO_INCREMENT,
  `col_int_nokey` int(11) DEFAULT NULL,
  `col_int_key` int(11) DEFAULT NULL,
  `col_date_key` date DEFAULT NULL,
  `col_date_nokey` date DEFAULT NULL,
  `col_time_key` time DEFAULT NULL,
  `col_time_nokey` time DEFAULT NULL,
  `col_datetime_key` datetime DEFAULT NULL,
  `col_datetime_nokey` datetime DEFAULT NULL,
  `col_varchar_key` varchar(1) DEFAULT NULL,
  `col_varchar_nokey` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`pk`),
  KEY `col_int_key` (`col_int_key`),
  KEY `col_date_key` (`col_date_key`),
  KEY `col_time_key` (`col_time_key`),
  KEY `col_datetime_key` (`col_datetime_key`),
  KEY `col_varchar_key` (`col_varchar_key`,`col_int_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Records of `C`
-- ----------------------------
BEGIN;
INSERT INTO `C` VALUES ('1', null, '2', null, null, '11:28:45', '11:28:45', '2004-10-11 18:13:16', '2004-10-11 18:13:16', 'w', 'w'), ('2', '7', '9', '2001-09-19', '2001-09-19', '20:25:14', '20:25:14', null, null, 'm', 'm'), ('3', '9', '3', '2004-09-12', '2004-09-12', '13:47:24', '13:47:24', '1900-01-01 00:00:00', '1900-01-01 00:00:00', 'm', 'm'), ('4', '7', '9', null, null, '19:24:11', '19:24:11', '2009-07-25 00:00:00', '2009-07-25 00:00:00', 'k', 'k'), ('5', '4', null, '2002-07-19', '2002-07-19', '15:59:13', '15:59:13', null, null, 'r', 'r'), ('6', '2', '9', '2002-12-16', '2002-12-16', '00:00:00', '00:00:00', '2008-07-27 00:00:00', '2008-07-27 00:00:00', 't', 't'), ('7', '6', '3', '2006-02-08', '2006-02-08', '15:15:04', '15:15:04', '2002-11-13 16:37:31', '2002-11-13 16:37:31', 'j', 'j'), ('8', '8', '8', '2006-08-28', '2006-08-28', '11:32:06', '11:32:06', '1900-01-01 00:00:00', '1900-01-01 00:00:00', 'u', 'u'), ('9', null, '8', '2001-04-14', '2001-04-14', '18:32:33', '18:32:33', '2003-12-10 00:00:00', '2003-12-10 00:00:00', 'h', 'h'), ('10', '5', '53', '2000-01-05', '2000-01-05', '15:19:25', '15:19:25', '2001-12-21 22:38:22', '2001-12-21 22:38:22', 'o', 'o'), ('11', null, '0', '2003-12-06', '2003-12-06', '19:03:19', '19:03:19', '2008-12-13 23:16:44', '2008-12-13 23:16:44', null, null), ('12', '6', '5', '1900-01-01', '1900-01-01', '00:39:46', '00:39:46', '2005-08-15 12:39:41', '2005-08-15 12:39:41', 'k', 'k'), ('13', '188', '166', '2002-11-27', '2002-11-27', null, null, null, null, 'e', 'e'), ('14', '2', '3', null, null, '00:00:00', '00:00:00', '2006-09-11 12:06:14', '2006-09-11 12:06:14', 'n', 'n'), ('15', '1', '0', '2003-05-27', '2003-05-27', '13:12:11', '13:12:11', '2007-12-15 12:39:34', '2007-12-15 12:39:34', 't', 't'), ('16', '1', '1', '2005-05-03', '2005-05-03', '04:56:48', '04:56:48', '2005-08-09 00:00:00', '2005-08-09 00:00:00', 'c', 'c'), ('17', '0', '9', '2001-04-18', '2001-04-18', '19:56:05', '19:56:05', '2001-09-02 22:50:02', '2001-09-02 22:50:02', 'm', 'm'), ('18', '9', '5', '2005-12-27', '2005-12-27', '19:35:19', '19:35:19', '2005-12-16 22:58:11', '2005-12-16 22:58:11', 'y', 'y'), ('19', null, '6', '2004-08-20', '2004-08-20', '05:03:03', '05:03:03', '2007-04-19 00:19:53', '2007-04-19 00:19:53', 'f', 'f'), ('20', '4', '2', '1900-01-01', '1900-01-01', '18:38:59', '18:38:59', '1900-01-01 00:00:00', '1900-01-01 00:00:00', 'd', 'd');
COMMIT;

```

``` sql

-- ----------------------------
--  Table structure for `CC`
-- ----------------------------
DROP TABLE IF EXISTS `CC`;
CREATE TABLE `CC` (
  `pk` int(11) NOT NULL AUTO_INCREMENT,
  `col_int_nokey` int(11) DEFAULT NULL,
  `col_int_key` int(11) DEFAULT NULL,
  `col_date_key` date DEFAULT NULL,
  `col_date_nokey` date DEFAULT NULL,
  `col_time_key` time DEFAULT NULL,
  `col_time_nokey` time DEFAULT NULL,
  `col_datetime_key` datetime DEFAULT NULL,
  `col_datetime_nokey` datetime DEFAULT NULL,
  `col_varchar_key` varchar(1) DEFAULT NULL,
  `col_varchar_nokey` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`pk`),
  KEY `col_int_key` (`col_int_key`),
  KEY `col_date_key` (`col_date_key`),
  KEY `col_time_key` (`col_time_key`),
  KEY `col_datetime_key` (`col_datetime_key`),
  KEY `col_varchar_key` (`col_varchar_key`,`col_int_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=10;

-- ----------------------------
--  Records of `CC`
-- ----------------------------
BEGIN;
INSERT INTO `CC` VALUES ('10', '7', '8', null, null, '01:27:35', '01:27:35', '2002-02-26 06:14:37', '2002-02-26 06:14:37', 'v', 'v'), ('11', '1', '9', '2006-06-14', '2006-06-14', '19:48:31', '19:48:31', '1900-01-01 00:00:00', '1900-01-01 00:00:00', 'r', 'r'), ('12', '5', '9', '2002-09-12', '2002-09-12', '00:00:00', '00:00:00', '2006-12-03 09:37:26', '2006-12-03 09:37:26', 'a', 'a'), ('13', '3', '186', '2005-02-15', '2005-02-15', '19:53:05', '19:53:05', '2008-05-26 12:27:10', '2008-05-26 12:27:10', 'm', 'm'), ('14', '6', null, null, null, '19:18:56', '19:18:56', '2004-12-14 16:37:30', '2004-12-14 16:37:30', 'y', 'y'), ('15', '92', '2', '2008-11-04', '2008-11-04', '10:55:12', '10:55:12', '2003-02-11 21:19:41', '2003-02-11 21:19:41', 'j', 'j'), ('16', '7', '3', '2004-09-04', '2004-09-04', '00:25:00', '00:25:00', '2009-10-18 02:27:49', '2009-10-18 02:27:49', 'd', 'd'), ('17', null, '0', '2006-06-05', '2006-06-05', '12:35:47', '12:35:47', '2000-09-26 07:45:57', '2000-09-26 07:45:57', 'z', 'z'), ('18', '3', '133', '1900-01-01', '1900-01-01', '19:53:03', '19:53:03', null, null, 'e', 'e'), ('19', '5', '1', '1900-01-01', '1900-01-01', '17:53:30', '17:53:30', '2005-11-10 12:40:29', '2005-11-10 12:40:29', 'h', 'h'), ('20', '1', '8', '1900-01-01', '1900-01-01', '11:35:49', '11:35:49', '2009-04-25 00:00:00', '2009-04-25 00:00:00', 'b', 'b'), ('21', '2', '5', '2005-01-13', '2005-01-13', null, null, '2002-11-27 00:00:00', '2002-11-27 00:00:00', 's', 's'), ('22', null, '5', '2006-05-21', '2006-05-21', '06:01:40', '06:01:40', '2004-01-26 20:32:32', '2004-01-26 20:32:32', 'e', 'e'), ('23', '1', '8', '2003-09-08', '2003-09-08', '05:45:11', '05:45:11', '2007-10-26 11:41:40', '2007-10-26 11:41:40', 'j', 'j'), ('24', '0', '6', '2006-12-23', '2006-12-23', '00:00:00', '00:00:00', '2005-10-07 00:00:00', '2005-10-07 00:00:00', 'e', 'e'), ('25', '210', '51', '2006-10-15', '2006-10-15', '00:00:00', '00:00:00', '2000-07-15 05:00:34', '2000-07-15 05:00:34', 'f', 'f'), ('26', '8', '4', '2005-04-06', '2005-04-06', '06:11:01', '06:11:01', '2000-04-03 16:33:32', '2000-04-03 16:33:32', 'v', 'v'), ('27', '7', '7', '2008-04-07', '2008-04-07', '13:02:46', '13:02:46', null, null, 'x', 'x'), ('28', '5', '6', '2006-10-10', '2006-10-10', '21:44:25', '21:44:25', '2001-04-25 01:26:12', '2001-04-25 01:26:12', 'm', 'm'), ('29', null, '4', '1900-01-01', '1900-01-01', '22:43:58', '22:43:58', '2000-12-27 00:00:00', '2000-12-27 00:00:00', 'c', 'c');
COMMIT;

```
``` sql
SELECT table1 . `col_date_key` 
FROM 

( C AS table1 
	LEFT OUTER JOIN 
	( ( CC AS table2 INNER JOIN CC AS table3 ON (table3 . `col_int_key` = table2 . `col_int_key`  ) ) )
	 ON (table3 . `col_varchar_key` = table2 . `col_varchar_nokey`  ) ) 

WHERE (  table3 . `col_varchar_nokey` NOT IN ( 
	SELECT   SUBQUERY1_t1 . `col_varchar_key` AS SUBQUERY1_field1 
	FROM 
	( C AS SUBQUERY1_t1 
		STRAIGHT_JOIN 
		( C AS SUBQUERY1_t2 
			LEFT  JOIN C AS SUBQUERY1_t3 
			ON (SUBQUERY1_t3 . `col_int_key` = SUBQUERY1_t2 . `col_int_key`  ) ) 
		ON (SUBQUERY1_t3 . `col_int_key` = SUBQUERY1_t2 . `col_int_key`  ) )   ) ) 
 OR table1 . `col_varchar_key` > table2 . `col_varchar_key`;
```

2. What did you expect to see?
no error 

3. What did you see instead?

```
interface conversion: interface {} is nil, not types.Time, goroutine 177 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc4205608f0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:389 +0xfd
panic(0x1c56f80, 0xc4218d77c0)
	/Users/xuhuaiyu/.gvm/gos/go1.9/src/runtime/panic.go:491 +0x283
github.com/pingcap/tidb/types.(*Datum).GetMysqlTime(...)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/types/datum.go:299
github.com/pingcap/tidb/types.DatumRow.GetTime(...)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/types/row.go:118
github.com/pingcap/tidb/types.(*DatumRow).GetTime(0xc4218155c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:1 +0x1bb
github.com/pingcap/tidb/server.dumpTextRow(0xc421477c00, 0x4, 0x400, 0xc4202f0eb8, 0x1, 0x1, 0x254e020, 0xc4218155c0, 0xc421839770, 0x1, ...)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/util.go:311 +0x68e
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc4205608f0, 0x2afd950, 0xc42052fc80, 0x2534980, 0xc4219a6fc0, 0xc421830000, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:831 +0x3c9
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc4205608f0, 0x2afd950, 0xc42052fc80, 0xc421478001, 0x29c, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:748 +0x115
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc4205608f0, 0xc421478001, 0x29d, 0x29d, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:530 +0x511
github.com/pingcap/tidb/server.(*clientConn).Run(0xc4205608f0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:412 +0x18a
github.com/pingcap/tidb/server.(*Server).onConn(0xc4205291a0, 0x2537560, 0xc4202f05c0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/server.go:315 +0x144
created by github.com/pingcap/tidb/server.(*Server).Run
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/server.go:261 +0x496

```

4. What version of TiDB are you using (`tidb-server -V`)?

githash 
```
38f794d875ef64ac68a81ac2d8109d3690bcaf74
```

### PR DESCRIPTION
**Pull request by winoros**
fix #5326 
Test is added in integration test.

### CODE REVIEW

**Comment by zz-jason** [comment]
LGTM

**Comment by shenli** [comment]
Could you add a few words to describe the bug?

**Comment by winoros** [comment]
@shenli It's very strange. 
`outerResult.rows` is a slice of Row `[]Row`, Row is slice of the datum `[]Datum`.
 In code, there's call like `doFunc(outerResult.rows[i])` where `doFunc`'s parameters' list is `outer Row`.
And in the `doFunc`, we do `outer = append(outer, newDatum)`. Then i found that after the `doFunc`, `outerResult.rows[i+1][0]` become the `newDatum` instead of the original value.
This can be reproduced when hash join's join concurrency is 1.

**Comment by zz-jason** [comment]
According to @winoros, the hash join's `outerExec` is another hash join, witch produces results based on a continuous `Datum` slice, a simplified example is:

outerExec.Next:
```go
// here buffer is that continuous Datum slice
result := outerExec.buffer[outerExec.Start, rowLen]
outerExec.Start += rowLen
return result
```

Parent(hash join) got this result and append another `Datum` on the end of this row will influence the next result got by parent:

```go
package main

import "fmt"

func main() {
    buffer := make([]int, 100)
    row1 := buffer[:50]
    row2 := buffer[50:]

    row1 = append(row1, 1)
    fmt.Printf("row2[0]=%v\n", row2[0])
}
```

and the result is `1`

**Comment by winoros** [comment]
@zz-jason If we change to this.
```go
package main

import "fmt"

func main() {
    buffer := make([]int, 100)
    row1 := buffer[:50:50]
    row2 := buffer[50:]

    row1 = append(row1, 1)
    fmt.Printf("row2[0]=%v\n", row2[0])
}
```
This result will be correct.

**Pull request merged**
