### PR TITLE
*: support record kv/pd time for a SQL statement (#17591)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #17591 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/17367

also fixes https://github.com/pingcap/tidb/issues/17361 by hand

Problem Summary:

we are missing record many cost time in the current slow log, for example:

- point-get network/kv time or time for backoff when it meet error in point-get
- batch-check/rebuild index check network/kv time or time for backoff when they meet
- resolve lock network/kv time(getStatus+resolve 2 rpc) and backoff when it meets
- some request met region cache miss and request pd to get region info rpc time
- .....

### What is changed and how it works?

What's Changed, How it Works:

the question is we are hard to pass execDetail for every this low level operation and record time.]

so in this PR, we change the other way: just add an interceptor for pd/kv client and record time in context.Context.

so we can record time no matter how deep the method is if we can pass context.Context in.

### Related changes

- n/a

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - addition small memory alloc and time.Now call

### Release note 

- Support record kv/pd time for a SQL statement

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/17591)

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
@lysu please resolve conflicts and fix CI.

**Review by zz-jason — COMMENTED** [review]
LGTM

**Review by jackysp — APPROVED** [review]
LGTM

**Pull request merged**
