### PR TITLE
*: fix appdash version (#49943)

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close None

Problem Summary:

Cherry-pick https://github.com/pingcap/tidb/pull/49943

Update appdash version.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by wuhuizuo** [comment]
/hold

wait the bot create another PR to fix.

**Review by xhebox — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Comment by tiancaiamao** [comment]
Need to run `make bazel_prepare`
@overvenus

**Comment by purelind** [comment]
check_dev is failed, Please run `make bazel_prepare` to update `.bazel` files

**Comment by wuhuizuo** [comment]
@tiancaiamao @xhebox PTAL the new PR: https://github.com/pingcap/tidb/pull/50112

@overvenus is on vacation.

**Comment by wuhuizuo** [comment]
Solved in #50112

**Pull request closed without merging**
