### PR TITLE
test: stable global var test

### LINKED ISSUE #16598: unit test TestConcurrentOneFlight fails
FAIL:global_vars_cache_test.go:104:testGVCSuite.TestConcurrentOneFlight

## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
[2020-04-20T05:38:57.344Z] FAIL: global_vars_cache_test.go:104: testGVCSuite.TestConcurrentOneFlight
[2020-04-20T05:38:57.344Z] 
[2020-04-20T05:38:57.344Z] global_vars_cache_test.go:174:
[2020-04-20T05:38:57.344Z]     c.Assert(counter, Equals, int32(1))
[2020-04-20T05:38:57.344Z] ... obtained int32 = 100
[2020-04-20T05:38:57.344Z] ... expected int32 = 1
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

Seen at https://github.com/pingcap/tidb/pull/16591#issuecomment-616322290

### LINKED ISSUE #16636: global_vars_cache_test.go:testGVCSuite.TestConcurrentOneFlight failed
global_vars_cache_test.go:testGVCSuite.TestConcurrentOneFlight

Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/33096/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_check_2/32692/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/33111/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/33224/display/redirect

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve?

Issue Number: close #16598, close #16636 

Problem Summary:
The results may not be stable if the input function executes very fast

### What is changed and how it works?

What's Changed:
Add some sleep in the input function, so the key may not be deleted too soon and other goroutines could be scheduled

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### CODE REVIEW

**Comment by coocood** [comment]
@cfzjywxk 
Still failling
```
[2020-04-20T09:30:07.328Z] FAIL: global_vars_cache_test.go:38: testGVCSuite.TestSimple

[2020-04-20T09:30:07.328Z] 

[2020-04-20T09:30:07.328Z] global_vars_cache_test.go:48:

[2020-04-20T09:30:07.328Z]     c.Assert(err, IsNil)

[2020-04-20T09:30:07.328Z] ... value *errors.fundamental = mock reload failed ("mock reload failed")
```

**Comment by coocood** [comment]
LGTM

**Comment by cfzjywxk** [comment]
@lysu @jackysp @SunRunAway  PTAL

**Pull request merged**
