### PR TITLE
statistics: change default value of tidb_analyze_version to 1 (#31826)

### PR DESCRIPTION
**Pull request by yiwen92**
close pingcap/tidb#31748

Cherry pick from #31826 to v5.2

What problem does this PR solve?
Issue Number: close https://github.com/pingcap/tidb/issues/31748

Problem Summary:

What is changed and how it works?
Set the default value for tidb_analyze_version to 1 to avoid OOM issues, because this was an experimental feature in v5.1 and v5.2

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [X] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Comment by yiwen92** [comment]
related docs updated in https://github.com/pingcap/docs-cn/pull/8551

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
