### PR TITLE
*: add show push down for ShowTables (#31919)

### LINKED ISSUE #30803: Show tables Compatibility differences
We use tidb and  elastic-job。
We have create job_execution_log in tidb。However, at startup, the program will also try to rebuild the table, because the table already exists, so the program will report an error.

By checking the source code, it is found that elastic job uses 【SHOW FULL TABLES LIKE 'JOB_EXECUTION_LOG';】 No results were returned。when we use lowercase [SHOW FULL TABLES LIKE 'job_execution_log';]It can return normally。

When we use MySQL。Whether in large or lowercase  It can return normally。

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #31919 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/33338
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/33338:release-5.4-93454da4c40f
```

---

Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #30803

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
@zimulala @tiancaiamao PTAL

**Review by tiancaiamao — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

**Pull request merged**
