### PR TITLE
executor: load data statement shoule not be prepared (#21188)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21188 to release-3.0

---

### What problem does this PR solve?

tidb throw  unexpected error while execute load data statement in prepare statement 

Problem Summary:

The current error is：
‘Load data: previous  load data option isn't closed normal’。
expected error is：
‘This command is not supported in the prepared statement protocol yet‘

### What is changed and how it works?

What's Changed:

add a logic, if there is load data in prepare statement, return error 'ErrUnsupportedPs' 

How it Works:
add a logic, if there is load data in prepare statement, return error 'ErrUnsupportedPs' 

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
1. execute
load data local infile 't1.txt' into table t1 fields terminated by '|' ignore 1 lines
2. below log will show in the log file.

[2020/11/22 21:31:11.349 +08:00] [INFO] [conn.go:801] ["command dispatched failed"] [conn=2199023255557] [connInfo="id:2199023255557, addr:127.0.0.1:56357 status:10, collation:utf8_general_ci, user:root"] [command=Prepare] [status="inTxn:0, autocommit:1"] [sql="load data local infile 't1.txt' into table t1 fields terminated by '|' ignore 1 lines"] [txn_mode=OPTIMISTIC] [err="[executor:1295]This command is not supported in the prepared statement protocol yet"]
	
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
- Raise an error when preparing the `load data` statement.

### CODE REVIEW

**Review by jackysp — COMMENTED** [review]
errors.toml should be deleted.

**Review by jackysp — COMMENTED** [review]
LGTM

**Comment by lysu** [comment]
LGTM

**Review by jackysp — APPROVED** [review]

**Pull request merged**
