### PR TITLE
*: adapt `utf8mb4_0900_ai_ci` collation

### LINKED ISSUE #6942: mysql client 8.0 failed to connect to tidb-server
1. What did you do?
If possible, provide a recipe for reproducing the error.

use mysql 8.0 client.

```
➜ ./bin/mysql -h 127.0.0.1 -P 4000 -u root
ERROR 1105 (HY000): Unknown charset id 255

➜ ./bin/mysql -V
./bin/mysql  Ver 8.0.11 for osx10.13 on x86_64 (Source distribution)
```

2. What did you expect to see?

connected

3. What did you see instead?

ERROR 1105 (HY000): Unknown charset id 255

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version: v2.1.0-alpha-89-g0547af60a
Git Commit Hash: 0547af60af60d16e262208ca0684e771386f62eb
Git Branch: dev-fix-maria-db-client
UTC Build Time: 2018-06-28 03:21:07
GoVersion: go version go1.10.1 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e

```

This issue is related with 8.0 new collation.

before we fix it, the user can add `--default-character-set utf8`when use MySQL 8.0 client to bypass this problem.

### LINKED ISSUE #9426: Support for utf8mb4_0900_ai_ci
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

attempt to connect to database using utf8mb4 as the default character set.

```Bash
> mysql -P4000 -uroot --default-character-set=utf8mb4
```

2. What did you expect to see?

a mysql prompt.

3. What did you see instead?

`ERROR 1105 (HY000): Unknown charset id 255`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

| Release Version: v3.0.0-beta-27-g6398788
Git Commit Hash: 6398788f6bb722d29d06b754e3d1d61d02a3090e
Git Branch: master
UTC Build Time: 2019-01-31 08:42:28
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |

-- 

Setting the character set after connecting works as expected:
```SQL
PS C:\> mysql -P4000 -uroot --default-character-set=utf8
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 54
Server version: 5.7.10-TiDB-v3.0.0-beta-27-g6398788 MySQL Community Server (Apache License 2.0)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%';
+--------------------------+---------+
| Variable_name            | Value   |
+--------------------------+---------+
| character_set_system     | utf8    |
| character_set_client     | utf8    |
| character_set_results    | utf8    |
| character_set_connection | utf8    |
| character_set_database   | utf8mb4 |
| character_set_filesystem | binary  |
| character_set_server     | utf8mb4 |
+--------------------------+---------+
7 rows in set (0.01 sec)

mysql> set names utf8mb4;
Query OK, 0 rows affected (0.00 sec)

mysql> SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%';
+--------------------------+---------+
| Variable_name            | Value   |
+--------------------------+---------+
| character_set_system     | utf8    |
| character_set_client     | utf8mb4 |
| character_set_results    | utf8mb4 |
| character_set_connection | utf8mb4 |
| character_set_server     | utf8mb4 |
| character_set_database   | utf8mb4 |
| character_set_filesystem | binary  |
+--------------------------+---------+
7 rows in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

MySQL client 8.0 use `utf8mb4_0900_ai_ci` as default collation and login tidb with MySQL 8.0 client will meet error like https://github.com/pingcap/tidb/issues/9426 and https://github.com/pingcap/tidb/issues/6942

closes #9426
closes #6942

### What is changed and how it works?

adapt `utf8mb4_0900_ai_ci` & doesn't throw a error

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - update parser https://github.com/pingcap/parser/pull/294

Side effects

 - N/A

Related changes

 - Need to update the documentation
 - Need to be included in the release note

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/10183)

### CODE REVIEW

**Comment by lysu** [comment]
@bb7133 @winkyao  PTAL

**Comment by bb7133** [comment]
LGTM

**Comment by shenli** [comment]
Should we cherry-pick this to the release-2.1?

**Pull request merged**
