### PR TITLE
parser: don't support `ALTER TABLE ... DROP FOREIGN KEY if exists`

### LINKED ISSUE #56701: `ALTER TABLE ... DROP FOREIGN KEY IF EXISTS ...` shouldn't be supported in parser
See https://bugs.mysql.com/bug.php?id=5746. MySQL doesn't have this syntax. TiDB also didn't support this operation, but the `parser` actually can parse it.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #56701

Problem Summary:

`ALTER TABLE ... DROP FOREIGN KEY IF EXISTS ... ` should not be supported by parser.

### What changed and how does it work?

Remove this grammer from parser.

Previously, TiDB also didn't implement this feature. `ALTER TABLE ... DROP FOREIGN KEY if exists ... ` behaves the same with or without the `if exists`. 

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notxxxes-style-guide.html) to write a quality release note.

```release-note
Don't support alter table ... drop foreign key if exists grammer
```

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]
LGTM, I don't think it would break anything really.

**Review by crazycs520 — APPROVED** [review]

**Review by yudongusa — APPROVED** [review]
LGTM. Document change PRs are also checked.

**Pull request merged**
