### PR TITLE
expression: function INSERT should return NULL if any argument is NULL

### PR DESCRIPTION
**Pull request by tcmichael**
### What problem does this PR solve? 
Function INSERT should be NULL if any argument is NULL.
Closes#11174

### What is changed and how it works?
change order of error judgement.

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by tcmichael** [comment]
@SunRunAway PTAL

**Comment by eurekaka** [comment]
@tcmichael Thanks for the contribution, it would be appreciated if you can help to cherry-pick this fix to release-2.1 and release-3.0 branch as well.

**Pull request merged**
