### PR TITLE
*: add a panel for GC rate and GOMEMLIMIT

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: ref #49008

Problem Summary:

### What changed and how does it work?
- global sort requires large mount of mem/cpu, add this inside `Server` to help diagnose

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

image

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Comment by tangenta** [comment]
Maybe we can add a 'Runtime' section and move all the panels from `pkg/metrics/grafana/tidb_runtime.json` to here.

**Comment by D3Hunter** [comment]
> Maybe we can add a 'Runtime' section and move all the panels from `pkg/metrics/grafana/tidb_runtime.json` to here.

`Runtime` dashboard is not that useful to help diagnose mem/cpu issues, except cpu/mem/goroutine which is also duplicated in the `Server` part.

we can move or delete them, but can do it later.

**Pull request merged**
