### PR TITLE
planner: Support normal left/right outer MPPTask join with other condition to use either side as build side

### LINKED ISSUE #43347: Allow MPPTask to use either side as build side for left/right outer join
## Enhancement
Just for non-cross, non-null_aware joins.
https://github.com/pingcap/tiflash/pull/7344

### PR DESCRIPTION
**Pull request by yibin87**
### What problem does this PR solve?

Issue Number: close #43347 

Problem Summary:

### What is changed and how it works?
Add support only for normal ones: non-cross, non-nullAware joins.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by yibin87** [comment]
hold until https://github.com/pingcap/tiflash/pull/7344 is merged.

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
