### PR TITLE
parser: Accept `PASSWORD REQUIRE CURRENT DEFAULT`

### LINKED ISSUE #53305: user password options not compatible with MySQL
## Bug Report

To migrate from MySQL 8.x to TiDB one might copy user accounts by running `SHOW CREATE USER ...` on MySQL and executing the result on TiDB. However this fails due to a mismatch in what MySQL produces and what TiDB accepts.

More info:
- #7968 (See the entry for 8.0.13)
- https://dev.mysql.com/doc/refman/8.0/en/create-user.html#create-user-password-management
- https://dev.mysql.com/worklog/task/?id=11544
- https://dev.mysql.com/blog-archive/mysql-8-0-13-change-current-password-policy/

### 1. Minimal reproduce step (Required)

On MySQL 8.0.37
```sql
CREATE USER 'test1'@'%' IDENTIFIED WITH 'mysql_native_password' BY 'secret';
SHOW CREATE USER 'test1'@'%';
```

Then on TiDB execute what MySQL produced:
```sql
CREATE USER `test1`@`%` IDENTIFIED WITH 'mysql_native_password' AS '*14E65567ABDB5135D0CFD9A70B3032C179A49EE7' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT
```

### 2. What did you expect to see? (Required)

```
Query OK, 0 rows affected (0.00 sec)
```

### 3. What did you see instead (Required)

```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 266 near "REQUIRE CURRENT DEFAULT" 
```
### 4. What is your TiDB version? (Required)

```
mysql> SELECT TIDB_VERSION()\G
*************************** 1. row ***************************
TIDB_VERSION(): Release Version: v7.5.1
Edition: Community
Git Commit Hash: 7d16cc79e81bbf573124df3fd9351c26963f3e70
Git Branch: heads/refs/tags/v7.5.1
UTC Build Time: 2024-02-27 14:28:32
GoVersion: go1.21.6
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

And also today's `master` branch.

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #53305 

Problem Summary:

1. This only accepts `CREATE USER ... PASSWORD REQUIRE CURRENT DEFAULT`. It doesn't support `PASSWORD REQUIRE CURRENT OPTIONAL`.
2. This isn't stored, checked or validated.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
TiDB now accepts `PASSWORD REQUIRE CURRENT DEFAULT` as part of `CREATE USER` to aid MySQL 8.0 compatibility
```

### CODE REVIEW

**Review by CbcWestwolf — APPROVED** [review]
LGTM

**Review by lastincisor — APPROVED** [review]
LGTM

**Review by ljun0712 — APPROVED** [review]

**Comment by ljun0712** [comment]
LGTM（This PR is only for syntax compatibility with MySQL.）

**Review by tangenta — APPROVED** [review]

**Pull request merged**
