### PR TITLE
*: force_init_stats doesn't block http api's startup

### LINKED ISSUE #50854: force_init_stats doesn't block HTTP API's startup
## Enhancement

In the current implementation, the force_init_stats block the startup of HTTP APIs. This could potentially lead to issues as the API cannot be accessed before the stats are properly initialized.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #50854

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

create many tables, we can read the metrics HTTP API but cannot operator MySQL port.

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by AilinKid — APPROVED** [review]

**Review by elsa0520 — APPROVED** [review]
LGTM

**Review by BornChanger — APPROVED** [review]
br part lgtm.

**Pull request merged**
