### PR TITLE
executor: fix unordered trace events in row format

### PR DESCRIPTION
**Pull request by lucklove**
The trace statement can print out a trace tree, however, in row
format, the tree is unordered, where earlier events may be placed
behind.

Signed-off-by: lucklove <gnu.crazier@gmail.com>

### What problem does this PR solve? 
The trace statement may result unordered events tree, for example:
```
 MySQL  localhost:4000  SQL > trace format='row' select * from mysql.user limit 1;
+------------------------------------------+-----------------+-----------+
| operation                                | startTS         | duration  |
+------------------------------------------+-----------------+-----------+
| trace                                    | 16:22:29.456361 | 763.741µs |
|   ├─*executor.LimitExec.Next             | 16:22:29.456875 | 226.354µs |
|   │ └─*executor.TableReaderExecutor.Next | 16:22:29.456877 | 209.508µs |
|   ├─*executor.LimitExec.Next             | 16:22:29.457109 | 904ns     |
|   └─session.Execute                      | 16:22:29.456371 | 487.914µs |
|     ├─executor.Compile                   | 16:22:29.456448 | 265.957µs |
|     │ └─session.getTxnFuture             | 16:22:29.456455 | 1.173µs   |
|     ├─session.runStmt                    | 16:22:29.456725 | 101.817µs |
|     │ ├─TableReaderExecutor.Open         | 16:22:29.456750 | 37.667µs  |
|     │ │ └─distsql.Select                 | 16:22:29.456765 | 15.333µs  |
|     │ └─session.CommitTxn                | 16:22:29.456813 | 10.098µs  |
|     │   └─session.doCommitWitRetry       | 16:22:29.456815 | 1.873µs   |
|     └─session.ParseSQL                   | 16:22:29.456377 | 12.654µs  |
+------------------------------------------+-----------------+-----------+
```
`session.ParseSQL` is behind `session.Compile`, it's not correct.

### What is changed and how it works?
Sort sub events before appending them into chunk.

### Check List 

Tests 
 - Unit test
 - Manual test
```
trace select * from mysql.user limit 1;
```

Code changes

Side effects

Related changes
 - Need to cherry-pick to the release branch

Release note
 - fix unordered trace events in row format.

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
PTAL @tiancaiamao

**Comment by tiancaiamao** [comment]
LGTM

**Comment by tiancaiamao** [comment]
Once upon a time, the result is sorted, until I remove it by mistake. @lucklove 
https://github.com/pingcap/tidb/pull/11633/files#diff-249234629b44bb39716865035fc89d8eL94

**Comment by zz-jason** [comment]
@lucklove the bot failed to cherry pick this PR to release 3.0 and 3.1, could you manually in your spare time?

**Comment by lucklove** [comment]
@zz-jason OK,  I'll do it

**Pull request merged**
