### PR TITLE
telemetry: fix skip condition on apple m1 in tests

### LINKED ISSUE #28108: telemetry_test.TestPreview fails on apple M1
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

go test -run TestPreview

### 2. What did you expect to see? (Required)

Success

### 3. What did you see instead (Required)

--- FAIL: TestPreview (1.31s)
    telemetry_test.go:84:
        	Error Trace:	telemetry_test.go:84
        	Error:      	Should be true
        	Test:       	TestPreview

### 4. What is your TiDB version? (Required)

TiDB master branch

go version go1.16.7 darwin/arm64

Although there are two PRs for this #26826, #26785, but the case still fails. According to https://golang.org/doc/go1.16#darwin, `darwin/arm64` should be used to detect apple M1, not `darwin/arm`.

### PR DESCRIPTION
**Pull request by zhangyangyu**
### What problem does this PR solve?

Issue Number: close #28108 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

change the skip condition for apple m1

How it Works:

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]

**Review by mjonss — APPROVED** [review]
I just verified the change and that it fixes the test on my macbook air M1.

**Comment by morgo** [comment]
> /cc @morgo

sorry, I don't have an M1 to verify.

**Review by morgo — APPROVED** [review]
OK, I trust Mattias' approval. LGTM.

**Pull request merged**
