### PR TITLE
makefile: update build cmd in graceshutdown & globalkilltest  makefile

### PR DESCRIPTION
**Pull request by purelind**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/47705

Problem Summary:
Relate to https://github.com/pingcap/tidb/pull/47123, we need to update build cmds to modify tidb-server src path.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [x] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by pingyu — APPROVED** [review]
LGTM~

**Comment by purelind** [comment]
e2e-test failed with error log, This seems to be an unstable test, unrelated to the current PR. The error will be fixed in another PR. 
```shell
--- FAIL: TestConnIDUpgradeAndDowngrade (20.94s)
    global_kill_test.go:116: 
        	Error Trace:	/home/jenkins/agent/workspace/pingcap/tidb/pull_e2e_test/tidb/tests/globalkilltest/global_kill_test.go:116
			/home/jenkins/agent/workspace/pingcap/tidb/pull_e2e_test/tidb/tests/globalkilltest/global_kill_test.go:830
        	Error:      	"161480738" is not greater than "4294967296"
        	Test:       	TestConnIDUpgradeAndDowngrade
        	Messages:   	connID 9a00022
FAIL
exit status 1
FAIL	github.com/pingcap/tidb/tests/globalkilltest	375.488s
script returned exit code 1
```

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
