### PR TITLE
executor,sessionctx: handle last_insert_id(0) like MySQL

### LINKED ISSUE #58201: incorrect handling of last_insert_id(0)
## Bug Report

The meaning of 0x00 in the OK packet of the MySQL protocol for the last insert id is not well defined, leading to various compatibility issues. 

See also:
- https://bugs.mysql.com/bug.php?id=116939
- https://github.com/vitessio/vitess/issues/17298
- https://gitlab.com/wireshark/wireshark/-/issues/20285
- https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_basic_ok_packet.html

### 1. Minimal reproduce step (Required)

```sql
select last_insert_id(1);
select last_insert_id(0);
select last_insert_id();
```

### 2. What did you expect to see? (Required)

MySQL 9.1.0
```
mysql-9.1.0> select last_insert_id(1);
+-------------------+
| last_insert_id(1) |
+-------------------+
|                 1 |
+-------------------+
1 row in set (0.00 sec)

mysql-9.1.0> select last_insert_id(0);
+-------------------+
| last_insert_id(0) |
+-------------------+
|                 0 |
+-------------------+
1 row in set (0.00 sec)

mysql-9.1.0> select last_insert_id();
+------------------+
| last_insert_id() |
+------------------+
|                0 |
+------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql-8.0.11-TiDB-v8.5.0-alpha-290-g30069c537d> select last_insert_id(1);
+-------------------+
| last_insert_id(1) |
+-------------------+
|                 1 |
+-------------------+
1 row in set (0.00 sec)

mysql-8.0.11-TiDB-v8.5.0-alpha-290-g30069c537d> select last_insert_id(0);
+-------------------+
| last_insert_id(0) |
+-------------------+
|                 0 |
+-------------------+
1 row in set (0.00 sec)

mysql-8.0.11-TiDB-v8.5.0-alpha-290-g30069c537d> select last_insert_id();
+------------------+
| last_insert_id() |
+------------------+
|                1 |
+------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v8.5.0-alpha-290-g30069c537d
Edition: Community
Git Commit Hash: 30069c537deb1d87da913a0b0cc914dc7bc3fa4d
Git Branch: master
UTC Build Time: 2024-12-12 07:28:06
GoVersion: go1.23.4
Race Enabled: false
Check Table Before Drop: false
Store: unistore
```

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #58201

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Handling of `last_insert_id(0)` was changed to be compatible with MySQL
```

### CODE REVIEW

**Review by mjonss — COMMENTED** [review]
Please create a test as well? maybe in tests/integration?
Otherwise LGTM :)

**Review by jackysp — APPROVED** [review]
LGTM

**Review by mjonss — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Review by yudongusa — APPROVED** [review]

**Pull request merged**
