### PR TITLE
[DNM] *: update the Txn interfaces to support the local transaction

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Part of #20448. We need to support the local transaction ability to make the use of Local TSO.

### What is changed and how it works?

* Add the `LocalTxn` and `NewLocalTxn` methods to support the local transaction.
* Update the store interfaces to support starting the local transaction.
* Update the corresponding tests.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note.

### CODE REVIEW

**Comment by JmPotato** [comment]
@nolouch Could you please help me assign some people to review this PR?

**Comment by JmPotato** [comment]
Move to #21353.

**Comment by nolouch** [comment]
Is this PR unnecessary?

**Comment by JmPotato** [comment]
> Is this PR unnecessary?

Yes, #21353 can cover all the needs.

**Pull request closed without merging**
