### PR TITLE
store: reduce time of ConnTestSuite.TestTiFlashFallback

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: #26593 

### What is changed and how it works?

What's Changed:

Use failpoint to set `copNextMaxBackoff` to 2ms.

How it Works:

The retry time will decrease. Before the pr,
```
PASS: conn_test.go:756: ConnTestSuite.TestTiFlashFallback       264.538s
```
After the pr,
```
PASS: conn_test.go:756: ConnTestSuite.TestTiFlashFallback       15.997s
```

### Check List 

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by xuyifangreeneyes** [comment]
`ConnTestSuite.TestTiFlashFallback` still needs 15.997s. The time mainly comes from `time.Sleep(time.Second)` in `Server.EstablishMPPConnectionWithStoreID` and `MPPTaskHandler.HandleEstablishConn`.

**Review by tiancaiamao — APPROVED** [review]
It's a big improvement, I agree with change... 

But 15.997s is still very long, as long as it's not removed from this list, I can't mark https://github.com/pingcap/tidb/issues/26593 as done.

https://github.com/pingcap/tidb/blob/d11889c1b067d81e7eb8ce98887545d706c1174e/tools/check/check-timeout.go#L78

**Review by winoros — APPROVED** [review]

**Pull request merged**
