### PR TITLE
expression: implement vectorized evaluation for `builtinLog2ArgsSig`

### PR DESCRIPTION
**Pull request by tsthght**
### What problem does this PR solve? 
expression: implement vectorized evaluation for `builtinLog2ArgsSig`,for #12105

### What is changed and how it works?
```
goos: darwin
goarch: amd64
pkg: github.com/pingcap/tidb/expression
BenchmarkVectorizedBuiltinMathFunc/builtinLog2ArgsSig-VecBuiltinFunc-8         	  100000	     15137 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinMathFunc/builtinLog2ArgsSig-NonVecBuiltinFunc-8      	   50000	     35137 ns/op	       0 B/op	       0 allocs/op
```

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by Reminiscent** [comment]
@tsthght  Please resolve the conflict, Thanks.

**Comment by qw4990** [comment]
@tsthght Please resolve the CI problem.

**Comment by qw4990** [comment]
@tsthght Please solve the CI problem.

**Pull request merged**
