### PR TITLE
telemetry&util/memory: bump "gopsutil" version to fix a bug that may cause build failure in macOS

### PR DESCRIPTION
**Pull request by SabaPing**
### What problem does this PR solve?

Bump gopsutil version to fix a bug that may cause build fail in macOS.

As mentioned in https://github.com/shirou/gopsutil/issues/976, `gopsutil` with old version did not include `TargetConditionals.h` and may cause TiDB build failure in macOS.

image

```shell
> make vet
vet
GO111MODULE=on go vet -all $(go list ./...| grep -vE "cmd|github.com\/pingcap\/tidb\/tests|github.com\/pingcap\/tidb\/br") 2>&1 | awk '{ print } END { if (NR > 0) { exit 1 } }'
# github.com/shirou/gopsutil/cpu
../../go/pkg/mod/github.com/shirou/gopsutil@v3.21.2+incompatible/cpu/cpu_darwin_cgo.go:13:5: warning: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
make: *** [vet] Error 1

```

This PR(https://github.com/shirou/gopsutil/pull/1042) has fixed the issue. And TiDB should catch up this fix.

### What is changed and how it works?

Bump `gopsutil` version in `go.mod` and `go.sum`

### Release note 

```release-note
NONE
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@tangenta @wjhuang2016 PTAL

**Comment by SabaPing** [comment]
This problem was fixed by #30523. Closed for now.

**Pull request closed without merging**
