### PR TITLE
fix a race when re-create batch-commands client

### PR DESCRIPTION
**Pull request by hicqu**
### What problem does this PR solve? 
In some cases, if TiKVs get down, TiDB can't know it quickly.

### What is changed and how it works?
When re-create the client, one goroutine will hold a lock until the client is created successfully. So pending requests can't be sent to network, and they can only be canceled after 60s.
This PR fix the problem by fix the lock usage. 

Tests
Unit tests. Because the network test framework is still in progress, no new test cases to cover it now, exactly. We can test batch-commands API after the test framework is ready.

### CODE REVIEW

**Comment by hicqu** [comment]
Before the PR TiDB needs 60s to retry requests if one TiKV fails:
MySQL [sbtest]> select count(*) from sbtest1;
+----------+
| count(*) |
+----------+
|  1000000 |
+----------+
1 row in set (1 min 4.908 sec)

**Comment by tiancaiamao** [comment]
I query the [grpc document](https://grpc.io/docs/guides/concepts.html) and find that gRPC guarantees message ordering within an individual RPC call in the streaming request.

So a simple way to handle async request-response notification:

```
ch := make(chan *tikvpb.BatchCommandsRequest)

// send side loop:
err := client.Send(req)
if err == nil {
    ch <- req
}

// recv side loop:
client.Recv()
if err != nil {
    drain(ch)
    recreate(client)
}
<-ch
```

And handle the client re-create:

```
type clientAndCh struct {
    client *batchCommandsClient
    ch chan *tikvpb.BatchCommandsRequest
}

type Client struct {
    *clientAndCh
    version int64 // cas change of the *clientAndCh
}
```

**Comment by hicqu** [comment]
I still prefer to add a lock to make `insert requests into the map` and `grpc.send` as an atomic. Or suppose this situation:
1. SendLoop adds requests into the map, but does not send them yet;
2. RecvLoop catch an error when call `grpc.Recv`, so fail all requests in the map and then clear the map;
3. RecvLoop re-create the connection successfully;
4. SendLoop sends the requests successfully;
5. RecvLoop will receive responses of those requests, but in the map there is no such IDs.
If we just ignore this case, It's hard to debug I guess.
Do I make sense?

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
