### PR TITLE
store: use first backoff error rather than last backoff error to generate mysql error

### PR DESCRIPTION
**Pull request by zhexuany**
Thank you for working on TiDB! Please read TiDB's [CONTRIBUTING](https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md) document **BEFORE** filing this PR.

When backoff excceds its max sleep time, backoff need return a mysql error. Originally, we generate mysql error using last backoff type. It turns out old way is not quite useful when we want to know what is the first reason caused the following backoff operation. 
So I changed generating mysql error logic from printing last backoff type to first backoff type.

Improvement

No need to add test since just one line change.

No. Backoff only is used internally.

This PR solves https://github.com/pingcap/tidb/issues/6793

### CODE REVIEW

**Comment by breeswish** [comment]
LGTM!

**Comment by coocood** [comment]
LGTM

**Comment by zhexuany** [comment]
@breeswish All tests are just passed, maybe you can approve this PR?

**Comment by breeswish** [comment]
@zhexuany Thanks! I'll have a test later, after that I would give an approval.

**Pull request merged**
