### PR TITLE
*: udpate pd client vendor

### PR DESCRIPTION
**Pull request by disksing**
### What problem does this PR solve? 
Fix the hanging problem described here: https://github.com/pingcap/pd/pull/1267

### What is changed and how it works?
Update pd client vendor.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch (I am not entirely sure)

### CODE REVIEW

**Comment by shenli** [comment]
LGTM
@disksing Please cherry-pick to the release branch.

**Comment by disksing** [comment]
@shenli Will do after merge.
@zhexuany @tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
