### PR TITLE
*: remove lichunzhu from owner of four components

### PR DESCRIPTION
**Pull request by Benjamin2037**
Issue Number: ref #46911

Problem Summary:
As title mentioned.

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [X] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

### Release note
```release-note
None
```

### CODE REVIEW

**Review by wuhuizuo — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Comment by Lloyd-Pottiger** [comment]
@Benjamin2037 Could you please give a more detailed reason? Since it is an open-source repo, why community contributors can not be the owner of the components?

**Review by JmPotato — CHANGES_REQUESTED** [review]
I don't quite understand the motivation behind this PR. It seems that you removed @lichunzhu from several owner lists where he is not the only member. If progress cannot proceed normally due to an inactive owner during review, you can directly assign it to another owner. Why do you need to remove a certain owner?

**Comment by lance6716** [comment]
My approving comes from this reason: by seeing the referring issue "Make assigning be appropriate and reviewing be efficient." It will improve the accuracy of this bot action

image

However, I don't know if the accuracy is just an intermediate goal and futher goodness will be hurt.

**Comment by ywqzzy** [comment]
> My approving comes from this reason: by seeing the referring issue "Make assigning be appropriate and reviewing be efficient." It will improve the accuracy of this bot action
> 
> image
> 
> However, I don't know if the accuracy is just an intermediate goal and futher goodness will be hurt.

This is a drawback from the bot not the owner list.
It's harmful to just remove the owner from owner list without notification.
Don't know why we have to remove owner, the previous owner won't lead huge change for the code base and won't harm the code base.

**Comment by ywqzzy** [comment]
> > My approving comes from this reason: by seeing the referring issue "Make assigning be appropriate and reviewing be efficient." It will improve the accuracy of this bot action
> > image
> > However, I don't know if the accuracy is just an intermediate goal and futher goodness will be hurt.
> 
> This is a drawback from the bot but not the owner list. It's harmful to just remove the owner from owner list without notification. Don't know why we have to remove owner, the previous owner won't lead huge change for the code base and won't harm the code base.

**Comment by Benjamin2037** [comment]
Actually, the owner is a mechanism to ensure before all prs merge into TiDB. The owner team of this components/dir must has at least one member to know the related changes and not cause any breaking or compatibility risks. That is why we need keep owner list always refresh to dev team members. But unfortunate, our owner definition did and owner life cycle are not very clearly to our developer.

**Comment by Benjamin2037** [comment]
I will pause this pr merge, and wait more sync information to clarify this owner mechanism.

**Comment by zhangyangyu** [comment]
> Actually, the owner is a mechanism to ensure before all prs merge into TiDB. The owner team of this components/dir must has at least one member to know the related changes and not cause any breaking or compatibility risks. That is why we need keep owner list always refresh to dev team members. But unfortunate, our owner definition did and owner life cycle are not very clearly to our developer.

The owner team should refer to the general open source maintainers/committers, not the dev team, the dev team will not own the component. If there is a dev team need to acting effectively on the component, keep a more tight eye on related PRs. Currently all the owners will receive notification and won't miss anything. And if @lichunzhu is bored with the notifications, he could give up the ownership on his own.

**Pull request closed without merging**
