### PR TITLE
ddl: forbidden conversion decimal to date/datetime/timestamp

### LINKED ISSUE #25007: Conversion `decimal` to `timestamp` is inconsistent with MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set global tidb_enable_change_column_type = 1;

drop table tbl_19;
create table tbl_19 ( col_73 decimal(45,8) default 13.654 not null);
insert  into tbl_19 set col_73 = 0.4352;

alter table tbl_19 change column col_73 col_159 timestamp;
select * from tbl_19;
```

### 2. What did you expect to see? (Required)
```
mysql> alter table tbl_19 change column col_73 col_159 timestamp;
ERROR 1292 (22007): Incorrect datetime value: '0.43520000' for column 'col_159' at row 1

mysql> select * from tbl_19;
+------------+
| col_73     |
+------------+
| 0.43520000 |
+------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
tidb> alter table tbl_19 change column col_73 col_159 timestamp;
Query OK, 0 rows affected (2.53 sec)

tidb> select * from tbl_19;
+---------------------+
| col_159             |
+---------------------+
| 0000-00-00 00:00:00 |
+---------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.1.0-alpha-73-gcd10f944b
Edition: Community
Git Commit Hash: cd10f944b2e583625861b3bdba2f4fe145c578b8
Git Branch: master
```

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: close #25007 

Problem Summary:
Currently, decimal cast to date/datetime/timestamp type are not support yet.

Proposal: [xxx](url) 

What's Changed:

- Forbidden conversion decimal to date/datetime/timestamp we should fix after support.
- Adjust the code of `checkTypeChangeSupported`.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- forbidden conversion decimal to date/datetime/timestamp

### CODE REVIEW

**Review by AilinKid — COMMENTED** [review]
/LGTM

**Review by tangenta — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
