### PR TITLE
vendor: fix tipb depency version.

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

fixes vendor question introduced by #7596 which confict with https://github.com/pingcap/tipb/pull/102

In master, run `dep ensure` should not modify vendor, and it seems vendor code is unconsistent to tipb

### What is changed and how it works?

- remove `github.com/pingcap/tip` in Gopkg.lock
- `dep ensure -add github.com/pingcap/tipb/go-tipb`

### Check List 

Tests 

 - Unit test

Code changes

 - No code

Side effects

 - No

Related changes

 - No

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/7653)

### CODE REVIEW

**Comment by lysu** [comment]
need help @coocood @zhexuany  PTAL thx~

**Comment by coocood** [comment]
LGTM

**Pull request merged**
