### PR TITLE
statistics: remove reassignment of Handle.pool in NewHandle

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### What is changed and how it works?

remove reassignment of `Handle.pool` in `NewHandle`.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tiancaiamao** [comment]
What the problem this PR solve? @xuyifangreeneyes

**Review by tiancaiamao — APPROVED** [review]
I see... a tiny clean up

**Review by Reminiscent — APPROVED** [review]

**Pull request merged**
