### PR TITLE
tiny clean up

### PR DESCRIPTION
**Pull request by ngaut**

### CODE REVIEW

**Comment by lysu** [comment]
@ngaut  this is in purpose,  `revokeStmtLabel = stringutil.StringerStr("RevokeStmt"`

will make every setLabel call do a interface conv but `revokeStmtLabel fmt.Stringer` no need that?

**Comment by ngaut** [comment]
Go doesn't need to do it explicitly.

**Comment by lysu** [comment]
yes，go can do that explicitly, but conv it in var definition just conv one time, versus this conv occur in every method invoke?

**Comment by ngaut** [comment]
Not sure if the compiler is smart enough to do that. Could you show more details?

**Comment by lysu** [comment]
```
var innerListLabel = stringutil.StringerStr("innerList")
var innerListLabel2 fmt.Stringer = stringutil.StringerStr("innerList")

var x = struct {
	f fmt.Stringer
}{}

//go:noinline
func test(f fmt.Stringer) {
	x.f = f
}

func f1()  {
	test(innerListLabel)
}

func f2()  {
	test(innerListLabel2)
}
```


```
"".f1 STEXT size=100 args=0x0 locals=0x20
	0x0000 00000 (test.go:20)	TEXT	"".f1(SB), ABIInternal, $32-0
	0x0000 00000 (test.go:20)	MOVQ	(TLS), CX
	0x0009 00009 (test.go:20)	CMPQ	SP, 16(CX)
	0x000d 00013 (test.go:20)	JLS	93
	0x000f 00015 (test.go:20)	SUBQ	$32, SP
	0x0013 00019 (test.go:20)	MOVQ	BP, 24(SP)
	0x0018 00024 (test.go:20)	LEAQ	24(SP), BP
	0x001d 00029 (test.go:20)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x001d 00029 (test.go:20)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x001d 00029 (test.go:20)	FUNCDATA	$3, gclocals·bfec7e55b3f043d1941c093912808913(SB)
	0x001d 00029 (test.go:21)	PCDATA	$2, $1
	0x001d 00029 (test.go:21)	PCDATA	$0, $0
	0x001d 00029 (test.go:21)	MOVQ	"".innerListLabel(SB), AX
	0x0024 00036 (test.go:21)	MOVQ	"".innerListLabel+8(SB), CX
	0x002b 00043 (test.go:21)	PCDATA	$2, $0
	0x002b 00043 (test.go:21)	MOVQ	AX, (SP)
	0x002f 00047 (test.go:21)	MOVQ	CX, 8(SP)
	0x0034 00052 (test.go:21)	CALL	runtime.convTstring(SB)
	0x0039 00057 (test.go:21)	PCDATA	$2, $1
	0x0039 00057 (test.go:21)	MOVQ	16(SP), AX
	0x003e 00062 (test.go:21)	PCDATA	$2, $2
	0x003e 00062 (test.go:21)	LEAQ	go.itab.github.com/pingcap/tidb/util/stringutil.StringerStr,fmt.Stringer(SB), CX
	0x0045 00069 (test.go:21)	PCDATA	$2, $1
	0x0045 00069 (test.go:21)	MOVQ	CX, (SP)
	0x0049 00073 (test.go:21)	PCDATA	$2, $0
	0x0049 00073 (test.go:21)	MOVQ	AX, 8(SP)
	0x004e 00078 (test.go:21)	CALL	"".test(SB)

"".f2 STEXT size=74 args=0x0 locals=0x18
	0x0000 00000 (test.go:24)	TEXT	"".f2(SB), ABIInternal, $24-0
	0x0000 00000 (test.go:24)	MOVQ	(TLS), CX
	0x0009 00009 (test.go:24)	CMPQ	SP, 16(CX)
	0x000d 00013 (test.go:24)	JLS	67
	0x000f 00015 (test.go:24)	SUBQ	$24, SP
	0x0013 00019 (test.go:24)	MOVQ	BP, 16(SP)
	0x0018 00024 (test.go:24)	LEAQ	16(SP), BP
	0x001d 00029 (test.go:24)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x001d 00029 (test.go:24)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x001d 00029 (test.go:24)	FUNCDATA	$3, gclocals·568470801006e5c0dc3947ea998fe279(SB)
	0x001d 00029 (test.go:25)	PCDATA	$2, $0
	0x001d 00029 (test.go:25)	PCDATA	$0, $0
	0x001d 00029 (test.go:25)	MOVQ	"".innerListLabel2(SB), AX
	0x0024 00036 (test.go:25)	PCDATA	$2, $1
	0x0024 00036 (test.go:25)	MOVQ	"".innerListLabel2+8(SB), CX
	0x002b 00043 (test.go:25)	MOVQ	AX, (SP)
	0x002f 00047 (test.go:25)	PCDATA	$2, $0
	0x002f 00047 (test.go:25)	MOVQ	CX, 8(SP)
	0x0034 00052 (test.go:25)	CALL	"".test(SB)
```

we can see those two function's asm, will find `f2` is better

**Comment by ngaut** [comment]
Thanks for explanation, could you file an PR to add comments and link to this PR?
I will close the PR.

**Pull request closed without merging**
