### PR TITLE
ddl: fix panic in TestParallelDDL (#16969)

### LINKED ISSUE #15597: ddl_worker_test.go:testDDLSuite.TestParallelDDL failed
ddl_worker_test.go:testDDLSuite.TestParallelDDL

Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/28573/display/redirect

### PR DESCRIPTION
**Pull request by lance6716**
manually cherry-pick #16969 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #15597 

Problem Summary:

1. `MockContext` failed interface type assertion, causing a panic. Proof see https://github.com/pingcap/tidb/issues/15597#issuecomment-623045298

2. try to reduce alloc slightly, BTW

### What is changed and how it works?

1. check type assertion and return `statistics.PseudoRowCount` on failure

2. change 'make new slice, append old elements, append new element' to 'append new element to old slice'

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- 
No release note

### CODE REVIEW

**Comment by lance6716** [comment]
PTAL @wjhuang2016

**Comment by lance6716** [comment]
kindly ping @zimulala @wjhuang2016

**Comment by wjhuang2016** [comment]
> kindly ping @zimulala @wjhuang2016

I don't have permission to merge this PR. Don't worry, this PR will be merged soon.

**Comment by lance6716** [comment]
ping @zimulala

**Comment by lance6716** [comment]
in fact I'm not surprised of merge failed 🤣

**Pull request merged**
