### PR TITLE
ddl: implement backoff strategy for async event notification in tests

### PR DESCRIPTION
**Pull request by Rustin170506**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/58344 close https://github.com/pingcap/tidb/issues/58421

Problem Summary:

### What changed and how does it work?

Enhance the asyncNotifyEvent function to include a backoff mechanism when sending events to the channel during unit tests. This prevents indefinite blocking on a full channel by attempting to send the event multiple times before giving up, while also logging a warning if the notification fails.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by lance6716 — APPROVED** [review]
not sure if 10 * 10ms is enough. BTW how did you test it?

**Comment by lance6716** [comment]
/hold

wait for addressing comment

**Review by tiancaiamao — APPROVED** [review]

**Comment by Rustin170506** [comment]
> not sure if 10 * 10ms is enough. BTW how did you test it?

Tested with the case from the issue.

image

**Pull request merged**
