### PR TITLE
bindinfo: migrate test-infra to testify(staging-4)

### LINKED ISSUE #27177: migrate test-infra to testify for `bindinfo` pkg

### PR DESCRIPTION
**Pull request by w169q169**
### What problem does this PR solve?

Issue Number: close #27177 

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by w169q169** [comment]
/cc @tisonkun  @sylzd 
PTAL

**Review by tisonkun — APPROVED** [review]
LGTM. Thanks for your contribution!

**Comment by tisonkun** [comment]
/uncc @sylzd @xhebox @mmyj 

Reschedule due to Chinese National Day.

/cc @morgo 

Could you take a look at this PR?

**Review by mmyj — APPROVED** [review]
lgtm

**Comment by tisonkun** [comment]
@mmyj thanks for your review lol.

**Pull request merged**
