### PR TITLE
cmd/explaintest: add a test to cover partition selection on hash partition

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Add a test to cover more cases.

Problem Summary:

This test covers a regression from https://github.com/pingcap/tidb/pull/13772
I don't even know it's happened and it's fixed, if not seeing this in the forum https://asktug.com/t/topic/33395/8

### What is changed and how it works?

So I want to add a case to cover it.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

### Release note

- No release note

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @jackysp @imtbkcat

**Comment by jackysp** [comment]
Please resolve conflicts, @tiancaiamao .

**Comment by jackysp** [comment]
Please resolve the conflicts.

**Comment by tiancaiamao** [comment]
/run-all-tests
PTAL @imtbkcat

**Pull request merged**
