### PR TITLE
util/types: change FieldType of exprNode to value instead of pointer

### PR DESCRIPTION
**Pull request by tiancaiamao**
reduce object allocation

### CODE REVIEW

**Comment by shenli** [comment]
Any bench result?

**Comment by tiancaiamao** [comment]
parser benchmark before vs after:
```
BenchmarkParse-4	   30000	     51556 ns/op	    5888 B/op	     112 allocs/op
BenchmarkParse-4	   30000	     50503 ns/op	    6000 B/op	     104 allocs/op
```

**Comment by shenli** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Pull request merged**
