### PR TITLE
planner: cleanup point update cache logic

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
Force cache point update plan is a little tricky. Users could use prepare plan cache instead.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Cleanup its logic.

How it Works:

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Review by cfzjywxk — COMMENTED** [review]
/lgtm

**Comment by jackysp** [comment]
PTAL @coocood

**Pull request merged**
