### PR TITLE
statistics: fix a data race in auto-analyze

### PR DESCRIPTION
**Pull request by Rustin170506**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/53460

Problem Summary:

I found some issues in the previous implementation.

1. There is a typo.
2. There is a data race when we handle the error.
3. The name is outdated.
4. There are no tests for the concurrent analysis.
5. The variable cannot be displayed correctly.

### What changed and how does it work?

1. Fixed the typo.
2. Fixed the data race.
3. Added a unit test for it.
4. Renamed the function.
5. Added a validation for it.
6. Fixed the display issue.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Rustin170506 — COMMENTED** [review]
The current implementation does not satisfy our new priority queue because it is not aware of the currently running table, and in the future we will need to skip updates to the running table. So we need to maintain at least the running tables ID.
Also the efficiency of this current implementation is determined by the slowest table every time, we should make the refresher ensure that there are always n tasks going on concurrently without creating unnecessary blocking of each other.
I will improve this when I implement the new priority queue.

🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by AilinKid — APPROVED** [review]

**Comment by Rustin170506** [comment]
For the validation, I tested it locally again:
```sql
mysql> select @@tidb_auto_analyze_concurrency;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    2803892230
Current database: *** NONE ***

+---------------------------------+
| @@tidb_auto_analyze_concurrency |
+---------------------------------+
|                                |
+---------------------------------+
1 row in set (0.08 sec)

mysql> select @@tidb_auto_analyze_concurrency;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    2657091590
Current database: *** NONE ***

+---------------------------------+
| @@tidb_auto_analyze_concurrency |
+---------------------------------+
| 2                               |
+---------------------------------+
1 row in set (0.03 sec)

mysql> set global tidb_enable_auto_analyze_priority_queue = OFF;
Query OK, 0 rows affected, 1 warning (0.01 sec)

mysql> select @@tidb_enable_auto_analyze_priority_queue;
+-------------------------------------------+
| @@tidb_enable_auto_analyze_priority_queue |
+-------------------------------------------+
|                                         0 |
+-------------------------------------------+
1 row in set (0.00 sec)

mysql> set global tidb_auto_analyze_concurrency = 10;
ERROR 1105 (HY000): cannot set tidb_auto_analyze_concurrency: requires both tidb_enable_auto_analyze and tidb_enable_auto_analyze_priority_queue to be true. Current values: tidb_enable_auto_analyze=true, tidb_enable_auto_analyze_priority_queue=false
```

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
