### PR TITLE
mock-tikv: fix write write conflict check.

### PR DESCRIPTION
**Pull request by bobotu**
Mock-tikv will fail to check `write write conflict` when there is a rollback between two conflict write.
This error cause #3283.

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @AndreMouche @disksing

**Comment by disksing** [comment]
Nice catch!
But I think another way to fix could be better: when append `mvccValue` to `mvccEntry`, we make sure the `values` are always in good order by their startTS or commitTS, then we can keep the behavior same as the real tikv. What's your opinion? cc @AndreMouche

**Comment by bobotu** [comment]
You are right @disksing. And checking all `commitTS` is slower than keep all `commitTS` in right order.

**Comment by disksing** [comment]
In fact, I am more concerned about whether it is as much as possible to simulate the real tikv rather than its efficiency. In real tikv, the entries' keys are encoded to ensure that they are ordered by ts.

**Comment by bobotu** [comment]
Got it. I'll file a new commit later. @disksing

**Comment by disksing** [comment]
@bobotu It seems that you code is not well formatted, could you run `make format`?

**Comment by disksing** [comment]
LGTM.

**Comment by AndreMouche** [comment]
LGTM

**Comment by disksing** [comment]
@bobotu Thanks for you contribution :)

**Pull request merged**
