### PR TITLE
 statistics/handle: enable flaky and shard test

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: ref #35247

Problem Summary:

### Check List

Tests 

- [x] Unit test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
@hawkingrei I think you should intend to request review instead of assign :)

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
Real TiKV tests is flaky also, which I guess is related to resource limitation of gha. If you can migrate the runtime to bazel, that will be great.

**Comment by hawkingrei** [comment]
> Real TiKV tests is flaky also, which I guess is related to resource limitation of gha. If you can migrate the runtime to bazel, that will be great.

I will. But bazel uses a remote cache to accelerate CI so CI needs to be near the remote cache and we maybe migrate gha into Jenkins.

**Comment by hawkingrei** [comment]
> @hawkingrei I think you should intend to request review instead of assign :)

It is my problem. Github’s app is too hard to use. T T

**Review by chrysan — APPROVED** [review]

**Pull request merged**
