### PR TITLE
coprocessor: enable push float down to tikv.

### PR DESCRIPTION
**Pull request by winoros**
Float constant should be pushed down to tikv.
Actually, all cast sig should be also pushed down to tikv. But there's something to do with error handling.
PTAL @XuHuaiyu @zz-jason @hanfei1991

### CODE REVIEW

**Comment by shenli** [comment]
Is TiKV able to handle float?

**Comment by BusyJay** [comment]
Yes, for +, -, *, / operations and abs, ceil, floor functions.

**Comment by winoros** [comment]
The failed case of jenkins' unit test is fixed in #4969 .It failed because test code is not stable enough.

**Pull request merged**
