### PR TITLE
planner: introduce flat plan

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/35888 ref https://github.com/pingcap/tidb/issues/35889

### What is changed and how it works?

- Introduce the flat plan.
- Use the flat plan to implement `EXPLAIN` logic.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by AilinKid — COMMENTED** [review]
basically LGTM, make sure it passed tidb-test before it merged

**Review by AilinKid — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Pull request merged**
