### PR TITLE
ddl: rename batchSize to batchCnt

### PR DESCRIPTION
**Pull request by ngaut**
In fact, batchCnt is the correct meaning of current context.

### CODE REVIEW

**Comment by ngaut** [comment]
PTAL @disksing @shenli

**Comment by disksing** [comment]
Search results from github code:
batchSize  527,436 results
batchCnt 287 results
batchCount 131,452 results

Also, a lot of usages of `batchSize` means 'the count', so I suggest to keep it.

**Comment by ngaut** [comment]
We shouldn't judge by how many results of each key word, they have different means here. Please ref:
http://documents.software.dell.com/secure-copy/7.0/user-guide/setting-copy-options/maximizing-copy-performance/adjusting-batch-count

**Comment by disksing** [comment]
LGTM

**Comment by coocood** [comment]
How about keep 'batchSize' for count, but rename to `batchBytes` for bytes?
We are used to 'batchSize', rename to batch count makes reading code uncomfortable.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
