### PR TITLE
test: try to stablize the test case

### LINKED ISSUE #22235: db_test.go:testDBSuite3.TestTransactionWithWriteOnlyColumn failed
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/62729/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/62729/display/redirect</a>

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve?

Issue Number: close #22235 

Problem Summary:

The test case `TestTransactionWithWriteOnlyColumn` will execute a transaction in the DDL hook function, issues we met:
- [Failure](https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_unit_test/runs/62761/nodes/74/steps/306/log/?start=0/). This is because the transaction may see a older schema version at start, and the  commit will fail.
[2021-01-07T00:08:26.543Z] ----------------------------------------------------------------------
[2021-01-07T00:08:26.543Z] FAIL: db_test.go:3454: testDBSuite3.TestTransactionWithWriteOnlyColumn
[2021-01-07T00:08:26.543Z] 
[2021-01-07T00:08:26.543Z] db_test.go:3498:
[2021-01-07T00:08:26.543Z]     c.Assert(checkErr, IsNil)
[2021-01-07T00:08:26.543Z] ... value *errors.fundamental = err: previous statement: update t1 set a=2 where a=1: [domain:8028]Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later], sql: commit, job schema state: write only ("err: previous statement: update t1 set a=2 where a=1: [domain:8028]Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later], sql: commit, job schema state: write only")
- [Failure](https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_unit_test/runs/62749/nodes/74/steps/300/log/?start=0).This is because the insert may fail using strcit mode for `not null` column insertions.
[2021-01-06T20:08:34.385Z]. FAIL: db_test.go:3454: testDBSuite3.TestTransactionWithWriteOnlyColumn
[2021-01-06T20:08:34.385Z] 
[2021-01-06T20:08:34.385Z] db_test.go:3506:
[2021-01-06T20:08:34.385Z]     c.Assert(checkErr, IsNil)
[2021-01-06T20:08:34.385Z] ... value *errors.fundamental = err: [table:1364]Field 'c' doesn't have a default value, sql: insert into t1 set a=1, job schema state: write only ("err: [table:1364]Field 'c' doesn't have a default value, sql: insert into t1 set a=1, job schema state: write only")
[2021-01-06T20:08:34.385Z] 

### What is changed and how it works?

What's Changed:
- Add some sleep to let the transaction start with the newest schema version so that commit will see the same schema version.
- Change the alter statement removing the `not null` constraint.

How it Works:

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- `No release note`

### CODE REVIEW

**Comment by AilinKid** [comment]
I think both these are caused by the fact that:
the begin schema is different from the commit schema, which means during the txn in ddl callback, the async schema reload has succeeded at least once.  This caused by a high overload of CI environment which has been **proved** in issue https://github.com/pingcap/tidb/issues/21773, click it for more details...

And this issue seems has been fixed by PR https://github.com/pingcap/tidb/pull/22226, which passed the domain in the ddl callback{} which will ensure the schema reload after each schema change synchronously.

**Comment by AilinKid** [comment]
PTAL @xiongjiwei @wjhuang2016

**Comment by xiongjiwei** [comment]
> I think both these are caused by the fact that:
> the begin schema is different from the commit schema

agree, we can see that, the InfoSchema is loaded after the callback function

```
[2021-01-04T03:30:00.627Z] [2021/01/04 11:30:00.450 +08:00] [INFO] [callback_test.go:63] ["on job run before"] [job="ID:238, Type:drop column, State:running, SchemaState:write only, SchemaID:45, TableID:235, RowCount:0, ArgLen:0, start time: 2021-01-04 11:29:59.827 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2021-01-04T03:30:00.627Z] [2021/01/04 11:30:00.451 +08:00] [INFO] [domain.go:129] ["diff load InfoSchema success"] [usedSchemaVersion=320] [neededSchemaVersion=321] ["start time"=2.748821ms] [phyTblIDs="[235]"] [actionTypes="[64]"]
[2021-01-04T03:30:00.627Z] [2021/01/04 11:30:00.452 +08:00] [WARN] [session.go:1123] ["run statement failed"] [schemaVersion=320] [error="[table:1364]Field 'c' doesn't have a default value"] [session="{\n  \"currDBName\": \"test_db\",\n  \"id\": 179,\n  \"status\": 3,\n  \"strictMode\": true,\n  \"txn\": \"421981323382226944\",\n  \"user\": null\n}"]
```

**Comment by cfzjywxk** [comment]
> I think both these are caused by the fact that:
> the begin schema is different from the commit schema, which means during the txn in ddl callback, the async schema reload has succeeded at least once. This caused by a high overload of CI environment which has been **proved** in issue #21773, click it for more details...
> 
> And this issue seems has been fixed by PR #22226 (just merged today), which passed the domain in the ddl callback{} which will ensure the schema reload synchronously after each schema change.
> 
> image

Got it, thanks~

**Pull request closed without merging**
