### PR TITLE
tidb: modify module name in go.mod, add v2

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Fix https://github.com/golang/go/issues/30499

### What is changed and how it works?

I'm not sure it works, let's have a try

### Check List 

Tests 

 - No code

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
I'm not sure whether we should add /v3 for master branch, and /v2 for release-2.0 and release-2.1

**Comment by XuHuaiyu** [comment]
According to https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher, it seems we do need to add `/v3` for `master`.

**Comment by XuHuaiyu** [comment]
We may check whether [marwan-at-work](https://github.com/marwan-at-work/mod) helps.

**Comment by tiancaiamao** [comment]
I tried to modify go.mod adding a `v3` to the mod path but with no luck.
Now I move the code to a `v3` directory, it seems a more promising approach. 
@XuHuaiyu 

The Makefile script still needs to upgrade.

**Comment by jackysp** [comment]
Should we close this PR? Open it when we have plans to do this again.

**Pull request closed without merging**
