### PR TITLE
stroe: allow session variable tidb_snapeshot accepting tso. 

### PR DESCRIPTION
**Pull request by zhexuany**
cherry-picking PR #6749 into our release-2.0. For more detail, please refer to that PR.

### CODE REVIEW

**Comment by zhexuany** [comment]
@shenli @coocood PTAL. This is just a cherry-pick PR.

**Comment by coocood** [comment]
LGTM

**Comment by coocood** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by ngaut** [comment]
We don't need to cherry pick the PR. 2.0 should focus on bug fix.

**Comment by zhexuany** [comment]
This feature was requested from SRE team. From time to time, they have found `set tidb_snapeshot=datetime` is not enough. Why is this? Well, the precision of datetime generally does not work and this is where the need of directly setting `tso` to this session variable arisen.

**Pull request merged**
