### PR TITLE
coprocessor: let tiflash split range task consistent with tikv

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve? 
As before, we always set the full range for the region request of TiFlash. But there is some problem when we switch on the region merge. The retry of the merged region may cause the duplicate read. So TiFlash support the range in coprocessor and TiDB make the range split consistent with TiKV.

### What is changed and how it works?
Make the range split of TiFlash region request consistent with TiKV.

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by lzmhhh123** [comment]
> Does the previous changes in [/planner/core/find_best_task.go@`master`#L1085](https://github.com/pingcap/tidb/blob/master/planner/core/find_best_task.go#L1085)
> need to be reverted?

I think we'd better not. The process of CBO would be affected.

**Comment by windtalker** [comment]
> > Does the previous changes in [/planner/core/find_best_task.go@`master`#L1085](https://github.com/pingcap/tidb/blob/master/planner/core/find_best_task.go#L1085)
> > need to be reverted?
> 
> I think we'd better not. The process of CBO would be affected.

Ok, but better to revert it in the future. And the changes in https://github.com/pingcap/tidb/blob/master/planner/core/explain.go#L153 
should be reverted.

**Comment by lzmhhh123** [comment]
> > > Does the previous changes in [/planner/core/find_best_task.go@`master`#L1085](https://github.com/pingcap/tidb/blob/master/planner/core/find_best_task.go#L1085) [](/pingcap/tidb/blob/HEAD@{2020-02-10T12:03:13Z}/planner/core/find_best_task.go#L1085)
> > > need to be reverted?
> > 
> > 
> > I think we'd better not. The process of CBO would be affected.
> 
> Ok, but better to revert it in the future. And the changes in [/planner/core/explain.go@`master`#L153](https://github.com/pingcap/tidb/blob/master/planner/core/explain.go#L153) [](/pingcap/tidb/blob/HEAD@{2020-02-10T12:03:13Z}/planner/core/explain.go#L153)
> should be reverted.

OK.

**Pull request merged**
