### PR TITLE
parser,expression: decimal support for interval

### PR DESCRIPTION
**Pull request by colinback**
Hello, I wanna separate #6045 into 2 PRs. This PR is going to support decimal input for interval. So
following sql should work same as MySQL:
- `SELECT DATE_ADD('2009-01-01', INTERVAL 6/4 HOUR_MINUTE)`
- `SELECT DATE_ADD('1970-01-01 12:00:00', INTERVAL CAST(6/4 AS DECIMAL(3,1)) HOUR_MINUTE)`
- `SELECT DATA_ADD('2009-01-01', INTERVAL 1.5 HOUR_MINUTE)`

In terms of `SELECT INTERVAL 1 DAY + '2008-12-31'`, it is not easy for me. I need more time to study yacc due to the  shift/reduce conflict problem.

### CODE REVIEW

**Comment by shenli** [comment]
@colinback Thanks!

**Comment by colinback** [comment]
Sorry, I just notice that I remove some last changes in parser_test.go. I commit amend.

**Comment by colinback** [comment]
@shenli Can you help to run all-tests again? I update a bit.

**Comment by colinback** [comment]
@XuHuaiyu Is this failure during integration-common-test a known issue?
```
FAIL: scan_mock_test.go:28: testScanMockSuite.TestScanMultipleRegions

scan_mock_test.go:47:
    c.Assert([]byte{ch}, BytesEquals, []byte(scanner.Key()))
... bytes_one []uint8 = []byte{0x74}
... bytes_two []uint8 = []byte{0x73, 0x65, 0x65, 0x6b, 0x5f, 0x31, 0x35, 0x32, 0xff, 0x32, 0x30, 0x33, 0x36, 0x38, 0x31, 0x38, 0x5f, 0xff, 0x6b, 0x65, 0x79, 0x30, 0x30, 0x30, 0x30, 0x30, 0xff, 0x30, 0x30, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfa}

time="2018-03-26T12:00:18+08:00" level=error msg="updateTS error: rpc error: code = Canceled desc = context canceled" 
```

**Comment by tiancaiamao** [comment]
It's fixed in https://github.com/pingcap/tidb/pull/6147
Please merge master. @colinback

**Comment by colinback** [comment]
@zhexuany Would someone review the code?

**Comment by zz-jason** [comment]
@tiancaiamao PTAL

**Comment by zhexuany** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

Good job! @colinback

**Pull request merged**
