### PR TITLE
ddl, table: fix Duplicate partition field in list partition

### LINKED ISSUE #31784: partition by list columns with  two same fields in column list  : not resulting error in tidb.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
set tidb_enable_list_partition=on;
drop table if exists t1; 
create table t1 (a int, b int)
partition by list columns(a,a)
( partition p values in ((1,1)));
```
### 2. What did you expect to see? (Required)
```sql
mysql> create table t1 (a int, b int)
    -> partition by list columns(a,a)
    -> ( partition p values in ((1,1)));
ERROR 1652 (HY000): Duplicate partition field name 'a'
```
### 3. What did you see instead (Required)
```sql
mysql> create table t1 (a int, b int)
    -> partition by list columns(a,a)
    -> ( partition p values in ((1,1)));
Query OK, 0 rows affected (0.00 sec)
```

### 4. What is your TiDB version? (Required)
```sql
| Release Version: v5.4.0-alpha-264-g6efa36df6
Edition: Community
Git Commit Hash: 6efa36df6cff325106f67ecfe3d79816ba37ca6a
Git Branch: master
UTC Build Time: 2021-12-28 02:03:55
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #31784

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
return error when have duplicate columns in list partition.
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @mjonss @xiongjiwei @xhebox 
PTAL

**Review by xiongjiwei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by Defined2014** [comment]
@xhebox @xiongjiwei Cloud you help me merge it?

**Pull request merged**
