### PR TITLE
makefile: Makefile add buildflag

### PR DESCRIPTION
**Pull request by winkyao**
if we want to use gdb or delve to debug TiDB, we need add `-gcflags="-N -l"` flags to `$GOBUILD`, after this pr, we can compile TiDB more easier by:

```
BUILD_FLAG='-gcflags="-N -l"' make
```

### CODE REVIEW

**Comment by jackysp** [comment]
CI failed @winkyao .

**Comment by shenli** [comment]
Is it better to add a task named `make debug`?

**Comment by winkyao** [comment]
@shenli I think add a flag to `GOBUILD` is the simplest way. because there is many binaries use GOBUILD

**Comment by coocood** [comment]
LGTM

@shenli 
We may need to set some other flags in some cases.

**Comment by shenli** [comment]
OK!
LGTM

**Pull request merged**
