### PR TITLE
executor: `kill tidb [session id]` can't stop executors and release resources quickly 

### PR DESCRIPTION
**Pull request by qw4990**
cherry-pick for #9844

### CODE REVIEW

**Comment by qw4990** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
@qw4990 build failed:
```

+ make

CGO_ENABLED=1 GO111MODULE=on go build   -ldflags '-X "github.com/pingcap/parser/mysql.TiDBReleaseVersion=v2.1.7-15-g893111b323" -X "github.com/pingcap/tidb/util/printer.TiDBBuildTS=2019-04-01 12:06:58" -X "github.com/pingcap/tidb/util/printer.TiDBGitHash=893111b323494e5089182d67561388677160b9e8" -X "github.com/pingcap/tidb/util/printer.TiDBGitBranch=HEAD" -X "github.com/pingcap/tidb/util/printer.GoVersion=go version go1.11.2 linux/amd64" ' -o bin/tidb-server tidb-server/main.go

# github.com/pingcap/tidb/server

server/server.go:370:4: undefined: logutil

server/server.go:370:19: undefined: context

server/server.go:370:73: undefined: zap

make: *** [server] Error 2

script returned exit code 2
```

**Comment by qw4990** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by qw4990** [comment]
It seems that we have to wait for #9955

**Comment by xiekeyi98** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
