### PR TITLE
executor: avoid concurrently update for `SimpleLRUCache` in `ApplyCache`

### LINKED ISSUE #50347: Panic: concurrent map writes of ParallelNestedLoopApplyExec's SimpleLRUCache
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)
From customer case, not sure how to reproduce it, just the panic stack
fatal error: concurrent map writes
 
goroutine 349945042302 [running]:
github.com/pingcap/tidb/util/kvcache.(*SimpleLRUCache).Put(0xc6eb5946c0, {0x5d72e00, 0xc82454dab8}, {0x52a62a0?, 0xc1d757f730})
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/kvcache/simple_lru.go:114 +0x396
github.com/pingcap/tidb/executor.(*applyCache).put(0xcabeb98aa0, {0xc1c8be0060?, 0xb12eb0f14f0b7?, 0x8a12c80?}, {0x52a62a0, 0xc1d757f730})
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/apply_cache.go:66 +0xe5
github.com/pingcap/tidb/executor.(*applyCache).Set(0xcabeb98aa0, {0xc1c8be0060, 0x2e, 0x2e}, 0xc1d757f730)
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/apply_cache.go:93 +0x132
github.com/pingcap/tidb/executor.(*ParallelNestedLoopApplyExec).fetchAllInners(0xc617193d40, {0x5d98390, 0xc60643b440}, 0x9)
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/parallel_apply.go:338 +0xa8f
github.com/pingcap/tidb/executor.(*ParallelNestedLoopApplyExec).fillInnerChunk(0xc617193d40, {0x5d98390, 0xc60643b440}, 0x9, 0xc3bde2ebe0)
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/parallel_apply.go:384 +0x32f
github.com/pingcap/tidb/executor.(*ParallelNestedLoopApplyExec).innerWorker(0xc617193d40, {0x5d98390, 0xc60643b440}, 0xc713dd9e60?)
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/parallel_apply.go:247 +0x1ba
created by github.com/pingcap/tidb/executor.(*ParallelNestedLoopApplyExec).Next
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/parallel_apply.go:146 +0x328
[tidb_stderr.log](https://github.com/pingcap/tidb/files/13910697/tidb_stderr.log)

### 4. What is your TiDB version? (Required)
v7.1.1

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #50347

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by SeaRise** [comment]
This PR only fixes the crash, other issues are tracked in https://github.com/pingcap/tidb/issues/50360

**Review by jackysp — APPROVED** [review]

**Review by yibin87 — APPROVED** [review]
LGTM

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
