### PR TITLE
store/tikv: encode keys before save to mvcc store.

### LINKED ISSUE #2104: store/tikv/mock-tikv: encode keys before save them to MvccStore
Currently `mock-tikv` does not encode keys, which is different from real tikv-server. We should keep the behavior same with tikv or it will conceal bugs in unit tests.

### PR DESCRIPTION
**Pull request by disksing**
Fix #2104 

/cc @coocood @zimulala

### CODE REVIEW

**Comment by coocood** [comment]
Can we encode keys at the start of `handleRequest`, decode keys at the end of `handleRequest`?
I think this would be much cleaner.

**Comment by disksing** [comment]
@coocood Requests have different structures, if we encode/decode at `handleRequest` we have to deal with different types of requests respectively too.
Also, tikv-server do the codec at mvcc level, better to keep the same.

**Comment by coocood** [comment]
@disksing 
If codec is done deeply in every function call, we will have much higher cognitive load, we have to think if this key is encoded or not.

I'm not suggesting change tikv-server, but for tikv-server, do codec as pre-process and post-process is better too.

**Comment by coocood** [comment]
Another benefit is that we can avoid extra encoding in `keyInRegion`, every key is encoded only once.

**Comment by disksing** [comment]
@coocood
Still can't agree :)
The background of the whole encoding issue is: mvcc needs to append ts to the key  and also need a key be comparable before it goes to rocksdb.
As for `rpcHandler`, a) it doesn't know any thing about mvcc, the request may bypass mvcc and save to store directly (rawkv API in another PR); b) it doesn't have to know which field will be encoded to a key of storage engine, for example, the `primary` field of `Prewrite` is a key but will never be part of rocksdb key.

**Comment by disksing** [comment]
PTAL @zimulala @coocood

**Comment by coocood** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
