### PR TITLE
exectuor: reduce listInDisk.GetChunk memory usage(constructing of chunk in rows)

### LINKED ISSUE #35636: Optimize the memory usage of GetChunk for listInDisk.
Now listInDisk.GetChunk will construct a chunk for each row, and then append all data to one chunk. 
We can do it in one step, to reduce memory alloc and free

### PR DESCRIPTION
**Pull request by jianzhiyao**
### What problem does this PR solve?
Issue Number: close #35636

### What is changed and how it works?

rewirte listInDisk.GetChunk

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
reduce constructing of chunk in rows
```

### CODE REVIEW

**Comment by jianzhiyao** [comment]
PTAL @wshwsh12

**Comment by wshwsh12** [comment]
Are there any benchmark results for comparison?

**Review by xhebox — APPROVED** [review]

**Comment by xhebox** [comment]
Probably it is not that optimal. But I think it will not make it worse at least.

**Comment by jianzhiyao** [comment]
> Are there any benchmark results for comparison?


### benchstat result

```
name                   old time/op    new time/op    delta
ListInDisk_GetChunk-8    28.9ms ± 2%    11.6ms ± 3%  -59.81%  (p=0.000 n=10+10)

name                   old alloc/op   new alloc/op   delta
ListInDisk_GetChunk-8    71.4MB ± 0%     0.6MB ± 0%  -99.14%  (p=0.000 n=10+8)

name                   old allocs/op  new allocs/op  delta
ListInDisk_GetChunk-8     39.2k ± 0%     16.5k ± 0%  -58.04%  (p=0.000 n=8+10)
```

**Review by wshwsh12 — APPROVED** [review]
LGTM

**Pull request merged**
