### PR TITLE
ddl: add TiDB version to metrics

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve? 
Confirm the TiDB version where the owner is located.

### What is changed and how it works?
Add "TiDBReleaseVersion" to the metric of "DDLOwner".

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
screen shot 2018-10-15 at 15 02 09

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by shenli** [comment]
What will happen if we upgrade the tidb-server?

**Comment by zimulala** [comment]
@shenli 
After this owner is rolling upgrade, the metric will add a new record.
screen shot 2018-10-16 at 13 45 38

**Comment by zimulala** [comment]
@shenli 
Do you need to take another look?

**Pull request merged**
