### PR TITLE
metrics: monitoring GOMAXPROCS (#18987)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #18987 to release-4.0

---

### What problem does this PR solve?
Monitoring `GOMAXPROCS` on Grafana to help diagnosing CPU usage issues.

图片

### Release note

- Monitoring `GOMAXPROCS` on Grafana to help diagnosing CPU usage issues.

### CODE REVIEW

**Comment by bobotu** [comment]
The reason for the conflict is we have not cherry pick https://github.com/pingcap/tidb/pull/17706 to `release-4.0`.
Do we need to include it in 4.0? @lysu @jackysp

**Comment by jackysp** [comment]
> The reason for the conflict is we have not cherry pick #17706 to `release-4.0`.
> Do we need to include it in 4.0? @lysu @jackysp

I think we could also include #17706 in 4.0.

**Review by zz-jason — COMMENTED** [review]
@bobotu please resolve the conflicts and fix CI.

**Comment by bobotu** [comment]
PTAL @zz-jason @lysu @jackysp 
https://github.com/pingcap/tidb/pull/19396 depends on this PR.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by zz-jason — APPROVED** [review]
LGTM

**Pull request merged**
