### PR TITLE
domain,owner: unify and normalize the format of the log (#9646)(#10012)

### PR DESCRIPTION
**Pull request by xiekeyi98**
### What problem does this PR solve? 

Cherry-pick from https://github.com/pingcap/tidb/pull/9646 and https://github.com/pingcap/tidb/pull/10012 ( bug fix for #9646)
Unify and normalize the format of the log.

### What is changed and how it works?

Use the new library to log.

### Check List 

Tests 

 - Unit test
 - Integration test

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/9953)

### CODE REVIEW

**Comment by xiekeyi98** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by xiekeyi98** [comment]
Wait https://github.com/pingcap/tidb/pull/9659 to be cherry-picked.

**Comment by zz-jason** [comment]
@xiekeyi98 https://github.com/pingcap/tidb/pull/9659 is merged, please fix ci.

**Comment by xiekeyi98** [comment]
@zz-jason  I'm waiting for #9659  to be cherry-picked.
Indeed, I'm waiting for https://github.com/pingcap/tidb/pull/9955 merged.

**Comment by xiekeyi98** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by xiekeyi98** [comment]
/run-all-tests tidb-test=pr/775 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by xiekeyi98** [comment]
/run-all-tests tidb-test=pr/775 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by xiekeyi98** [comment]
/run-intergration-compatibility-test tidb-test=pr/775 tidb-private-test=release-2.1 tikv=release-2.

**Comment by xiekeyi98** [comment]
/run-all-tests tidb-test=pr/775 tidb-private-test=release-2.1 tikv=release-2.1

**Pull request merged**
