### PR TITLE
fix: parseDuration error when parse string of one digit

### PR DESCRIPTION
**Pull request by hawkingrei**
when parseDuration("1"), it will give a error “invalid time format” , it should return "00:00:01"

but now i fix it

@shenli PTAL

### CODE REVIEW

**Comment by shenli** [comment]
@hawkingrei Could your construct a scenario to raise an error caused by this issue using SQL?

**Comment by hawkingrei** [comment]
@shenli  

mysql> SELECT TIMESTAMP('2003-12-31 12:00:00','1');
+--------------------------------------+
| TIMESTAMP('2003-12-31 12:00:00','1') |
+--------------------------------------+
| 2003-12-31 12:00:01                  |
+--------------------------------------+
1 row in set (0.00 sec)

**Comment by shenli** [comment]
LGTM
@tiancaiamao PTAL

**Comment by XuHuaiyu** [comment]
LGTM

**Pull request merged**
