### PR TITLE
privilege: fix RequestVerificationWithUser use of default roles (#24442)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #24442 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/24532
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/24532:release-5.0-b8cad01bef30
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/24414

Problem Summary:

Views support a feature to run in the security of the DEFINER. This is useful because it allows column level / row level security to effectively be supported, when TiDB supports neither.

However, the implementation was buggy because `RequestVerificationWithUser` in the privilege API did not consider default roles for that user correctly. In this fix it now does.

### What is changed and how it works?

What's Changed:

Bug fix only.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

- None

### Release note 

- SQL Views now consider the default roles associated with the SQL DEFINER correctrly.

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Comment by bb7133** [comment]
、merge

**Comment by morgo** [comment]
@zhouqiang-cl This was cherry picked to 4.0 but not 5.0. This is a problem because the user who reported the issue was on 4.0 but they've now upgraded to 5.0. So the bug is not fixed for them :(

**Pull request merged**
