### PR TITLE
planner/core: the order by with default field not parsed (#11210)

### PR DESCRIPTION
**Pull request by gaoxingliang**
### What problem does this PR solve? 
Fix https://github.com/pingcap/tidb/issues/11210
when order by with `default(colName)` is not resolved and got unknown column

### What is changed and how it works?
parse the column name expr in the order by resolver.

### Check List 

Tests 

 - Unit test  -- added and passed

### CODE REVIEW

**Comment by gaoxingliang** [comment]
Need more time to fix UTs

**Comment by zz-jason** [comment]
@gaoxingliang friendly ping, any update?

**Comment by gaoxingliang** [comment]
> @gaoxingliang friendly ping, any update?

the progress is not good. I think I missed something when I try to parse the ColumnName so many cases need to be considered (similar with the ColumnNameExpr, but I don't understand the difference). I think I need to close this PR temp now and do more checks.

**Comment by zz-jason** [comment]
@gaoxingliang friendly ping, any update?

**Comment by gaoxingliang** [comment]
> Can we check if the column has default value definition in expression rewriting of `buildSort` and report error (if no definition) or replace the ByItem to a constant?

Hi, it will not working. I test and found the schema information is not correct when we calling the plan.schema in buildSort and try to remapped in the `itemTransformer`

**Comment by eurekaka** [comment]
@gaoxingliang Sorry I didn't get your point. IMHO, theoretically, we can make the transformation when resolving the ORDER BY clause.

**Comment by gaoxingliang** [comment]
Hi @eurekaka below is more details about this issue.
the problem occur when the default(x) is not added into the plan p.Schema() at [logical_plan_builder.go#buildSort](https://github.com/pingcap/tidb/blob/release-3.0/planner/core/logical_plan_builder.go#L1005)
So I try to find where the schema select fields are added with comparison with another func like `length(x)` 
I found it's added in the `havingWindowAndOrderbyExprResolver` with case `ColumnNameExpr` at [here](https://github.com/pingcap/tidb/blob/release-3.0/planner/core/logical_plan_builder.go#L1282) for `length` function.
but for `default` function, it's a `ColumnName` instead of a `ColumnNameExpr` which I think this is what parser done. I don't get the difference.

for your suggestion, the [transformer] (https://github.com/pingcap/tidb/blob/release-3.0/planner/core/logical_plan_builder.go#L2132) happened after the error occur. so I don't think that will fix this problem.

**Comment by zz-jason** [comment]
Hi @gaoxingliang, friendly ping, any update?

**Pull request closed without merging**
