### PR TITLE
expression, util: add an interface Times for chunk.Column

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve? 
1. Add an interface chunk.Column.Times
2. Add an interface chunk.Column.ResizeTime

### What is changed and how it works?
Benchmark result
``` shell
$ GO111MODULE=on go test -bench=BenchmarkTime -run=none 
goos: darwin
goarch: amd64
pkg: github.com/pingcap/tidb/util/chunk
BenchmarkTimeRow-4         10000            151708 ns/op
BenchmarkTimeVec-4         50000             33028 ns/op
PASS

```

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

N/A

Related changes

N/A

### CODE REVIEW

**Comment by coocood** [comment]
How much memory allocation increased when we store the `Time` struct directly?

**Comment by qw4990** [comment]
> How much memory allocation increased when we store the `Time` struct directly?

13 bytes -> 20 bytes.

**Comment by zz-jason** [comment]
> How much memory allocation increased when we store the `Time` struct directly?

@XuHuaiyu Also, could you provide some benchmarks on the evaluation of time values?

**Comment by XuHuaiyu** [comment]
@zz-jason Added. And the result is added in the description.

**Comment by XuHuaiyu** [comment]
@coocood @qw4990 
Actually
14 bytes --> 20 bytes

**Pull request merged**
