### PR TITLE
executor,util: Correct error for MAX_EXECUTION_TIME | tidb-test=pr/2115

### LINKED ISSUE #43031: Error for MAX_EXECUTION_TIME isn't compatible with MySQL
### 1. Minimal reproduce step (Required)

Get a statement that gets interrupted because it reaches the `MAX_EXECUTION_TIME`.

Different statements are used for MySQL and TiDB because of #34344 (and #43027 )

### 2. What did you expect to see? (Required)

MySQL 8.0.32
```
mysql> drop table if exists t1;
Query OK, 0 rows affected (0.12 sec)

mysql> CREATE TABLE t1 (a INT, b VARCHAR(300));
Query OK, 0 rows affected (0.15 sec)

mysql> INSERT INTO t1 VALUES (1, 'string');
Query OK, 1 row affected (0.02 sec)

mysql> SELECT /*+ MAX_EXECUTION_TIME(1) */ *, SLEEP(5) FROM t1;
ERROR 3024 (HY000): Query execution was interrupted, maximum statement execution time exceeded
```

### 3. What did you see instead (Required)

```
tiup playground --without-monitor --tiflash 0 7.0.0
tiup bench tpcc prepare --warehouses 100
```

```
sql> SELECT /*+ MAX_EXECUTION_TIME(1) */ * FROM stock;
ERROR: 1317 (70100): Query execution was interrupted
```

### 4. What is your TiDB version? (Required)

```
Release Version: v7.0.0
Edition: Community
Git Commit Hash: 7376954cd868dbc44fc3015c9ef89c53749339a7
Git Branch: heads/refs/tags/v7.0.0
UTC Build Time: 2023-03-29 13:32:13
GoVersion: go1.20.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
```

The error number isn't the same as MySQL.

See also: https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html#error_er_query_timeout

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #43031 

Problem Summary:

- The query gets killed if it hits the max execution time
- Where we return an error to the client we don't know why the query was killed, so we return a generic error

This PR changes this so that `Killed` gets set to 2 instead of  1 if the query was killed because of the max execution time and then later uses this to send the right error to the client.

1. Why is `Killed` a `uint32` instead of a bool?
2. Is using a `Killed` value other than 0 or 1 safe? Or should we change checks from `==1` to `>0` etc?
3. Is there a better way to communicate the reason something was killed to the goroutine/process that sends the error to the client?

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
The error message that is returned by the server if a query hits the `MAX_EXECUTION_TIME` was made to match the error that MySQL returns.
```

### Related PRs
- https://github.com/pingcap/tidb-test/pull/2115

### CODE REVIEW

**Comment by dveeden** [comment]
```
mysql> SELECT /*+ MAX_EXECUTION_TIME(1) */ * FROM stock;
ERROR 3024 (HY000): Query execution was interrupted, maximum statement execution time exceeded
mysql> SELECT TIDB_VERSION()\G
*************************** 1. row ***************************
TIDB_VERSION(): Release Version: v7.1.0-alpha-199-g1da003b3b9
Edition: Community
Git Commit Hash: 1da003b3b92d76d21ea6572156a8576b4fba4ce9
Git Branch: max_exec_time_err
UTC Build Time: 2023-04-13 10:12:48
GoVersion: go1.20.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
1 row in set (0.00 sec)
```

**Review by CbcWestwolf — APPROVED** [review]

**Comment by CbcWestwolf** [comment]
You need to change the result in the mysql-test case due to the changing error message :-)

**Comment by dveeden** [comment]
@CbcWestwolf I put the PR for that in the description.

**Review by xhebox — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
