### PR TITLE
*: update tikv/client-go to fix lock nowait bug

### LINKED ISSUE #32754: NOWAIT does not have effect in pessimistic locking
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t (id BIGINT PRIMARY KEY);
INSERT INTO t VALUES (1);
BEGIN;
SELECT * FROM t WHERE id = 1 FOR UPDATE;
```

In another session:

```
SELECT * FROM t WHERE id = 1 FOR UPDATE NOWAIT;
```

### 2. What did you expect to see? (Required)

In the second session, it should return error immediately.

### 3. What did you see instead (Required)

One second passed before an error is returned.

### 4. What is your TiDB version? (Required)

TiDB 5.4

### PR DESCRIPTION
**Pull request by sticnarf**
Signed-off-by: Yilin Chen <sticnarf@gmail.com>

### What problem does this PR solve?

Issue Number: close #32754

### What is changed and how it works?

Update client-go to include the fix https://github.com/tikv/client-go/pull/435

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
Fix the bug that locking with NOWAIT does not return immediately when encountering a lock.
```

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by sticnarf** [comment]
The CI failure seems unrelated. Let's try again 
/run-unit-tests

**Pull request merged**
