### PR TITLE
metrics: add adding index worker duration back

### LINKED ISSUE #32188: Add adding index duration back after #30915
## Enhancement
https://github.com/pingcap/tidb/pull/30915 remove adding index worker duration, add it back.

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve?

Issue Number: close #32188

Problem Summary:
Add adding index duration back after #30915

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. start a cluster.
1. run Sysbench prepare to adding some indices.
image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by jackysp** [comment]
> Visit the grafana server at: http://172.16.5.5:32651, it will last for 5 hours

image

**Review by zimulala — APPROVED** [review]
LGTM

**Review by ngaut — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
