### PR TITLE
expression: separate signatures for `ModInt`

### PR DESCRIPTION
**Pull request by fredchenbj**
Signed-off-by: fredchenbj <cfworking@163.com>

PCP https://github.com/pingcap/tidb/issues/13978

### What problem does this PR solve?

Separate signatures for ModInt

### CODE REVIEW

**Comment by fredchenbj** [comment]
jenkins error:
```
[2020-04-13T02:27:40.515Z] CGO_ENABLED=1 GO111MODULE=on go build  -tags codes  -ldflags '-X "github.com/pingcap/parser/mysql.TiDBReleaseVersion=v4.0.0-beta.2-221-g8368f9e953" -X "github.com/pingcap/tidb/util/printer.TiDBBuildTS=2020-04-13 02:27:40" -X "github.com/pingcap/tidb/util/printer.TiDBGitHash=8368f9e953a5764b79b2d116ccf8e0e398112596" -X "github.com/pingcap/tidb/util/printer.TiDBGitBranch=HEAD" ' -o bin/tidb-server tidb-server/main.go

[2020-04-13T02:27:43.780Z] go: github.com/pingcap/tipb@v0.0.0-20200407063720-d3751d9e74ed: Get http://goproxy.pingcap.net/github.com/pingcap/tipb/@v/v0.0.0-20200407063720-d3751d9e74ed.mod: dial tcp 172.16.5.188:80: connect: no route to host
```

**Comment by fredchenbj** [comment]
@breeswish PTAL.

**Comment by breeswish** [comment]
Thanks! Maybe you need to open PR in TiKV to support these new signatures first?

**Comment by fredchenbj** [comment]
> Thanks! Maybe you need to open PR in TiKV to support these new signatures first?

OK, I will give a pr in TiKV those two days.

**Comment by zz-jason** [comment]
I'm going to close this PR since it hasn't been updated for a long time. feel free to reopen if you want to continue with it. thank you for your contribution.

**Pull request closed without merging**
