### PR TITLE
*: Create security-report.md

### PR DESCRIPTION
**Pull request by haohaoxuex2005**
Let users know that how to report a security issue.

### What problem does this PR solve?

Issue Number:  #25832 

### What is changed and how it works?

Add a security report template to tell users how to submit security issues.

What's Changed:  None

How it Works: None

### Related changes

- None

### Check List 

Tests 

- No code

Side effects

- None

### Release note 

- No release note

### CODE REVIEW

**Comment by haohaoxuex2005** [comment]
This pr is to create a template for users to report security issues in ISSUE_TEMPLATE

**Comment by haohaoxuex2005** [comment]
Explain that this template is to make it more convenient for users to know how to report a security vulnerability by email. It is not for users to submit an issue, so they did not follow the issue template.

**Comment by tisonkun** [comment]
@haohaoxuex2005 I think you can make use of the yaml header functionality so that we redirect the user want to send a security report

```
---
name: "Security Report"
about: Please follow <security-report.md> to submit security report.
---
```

**Comment by tisonkun** [comment]
You may push a commit to your fork's master and see the result

**Comment by tisonkun** [comment]
image

I think it can be closed.

**Comment by haohaoxuex2005** [comment]
> image
> 
> I think it can be closed.

Thanks! I close it.

**Pull request closed without merging**
