### PR TITLE
store/copr: return ErrTiFlashServerTimeout when MPP meets network error

### LINKED ISSUE #23414: MPP cop request should give correct error when tiflash is killed when request is sent.
## Development Task

Step
- Start cluster
- Create a table with tiflash replica.
- Send a tiflash MPP request.
- set @@session.tidb_allow_fallback_to_tikv = 'tiflash';
- Kill tiflash server before the query is finished.

Expected result:
- The query is successfully executed with tikv engine.

Got:
- `ERROR 1105 (HY000): rpc error: code = Unavailable desc = transport is closing`

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #23414 

Problem Summary:
When killing TiFlash server before the query with MPP is finished, the error `ERROR 1105 (HY000): rpc error: code = Unavailable desc = transport is closing` occurs. Since the error is not `ErrTiFlashServerTimeout`, we cannot retry the query with TiKV.

### What is changed and how it works?

What's Changed & How it Works:
In `(*mppIterator) establishMPPConns`, when we meet some RPC error, we log the error and send `ErrTiFlashServerTimeout` to the upper level.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- refine error handling for MPP to allow fallback to TiKV when TiFlash is down

### CODE REVIEW

**Review by hanfei1991 — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Comment by winoros** [comment]
There's other unstable tests not related with this PR, merged first.

**Pull request merged**
