### PR TITLE
executor: fix user without process privilege can access cluster's systemInfo, Load, Hardware

### PR DESCRIPTION
**Pull request by AilinKid**
Signed-off-by: ailinkid <314806019@qq.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/26121, https://github.com/pingcap/tidb/issues/26123, https://github.com/pingcap/tidb/issues/26126

### What is changed and how it works?

*: What's Changed: executor: fix user without process privilege can access cluster's systemInfo, Load, Hardware

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- executor: fix user without process privilege can access cluster's systemInfo, Load, Hardware

### CODE REVIEW

**Comment by mjonss** [comment]
I did something similar in #26220 please take a look which of the similar patches we should use 😄 
Otherwise LGTM

**Review by djshow832 — COMMENTED** [review]
Test  (at least manually) that users with process privilege can access those tables.

**Comment by AilinKid** [comment]
Duplicated with #26220, we will use it.

**Comment by AilinKid** [comment]
I found these test can be suppliments to #26220, so after it merged, I will merge these tests.

**Pull request closed without merging**
