### PR TITLE
statistics: fix auto analyze log information incomplete

### LINKED ISSUE #23515: auto analyze log doesn't print table name and partition name
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

When auto analyze is triggered, the log information is incomplete. The parameters are not replaced by the actual values.
image

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #23515 

Problem Summary:

After we changed our exec SQL API, SQL strings parameterized and need to be escaped to become the real SQL to be executed.
When logging auto analyze sql, we didn't do this.

### What is changed and how it works?

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

### Release note 

- no release note.

### CODE REVIEW

**Review by eurekaka — APPROVED** [review]
/LGTM

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
