### PR TITLE
[logutil]: Fix `MaxDays` and `MaxBackups` not working for slow-query-logger

### PR DESCRIPTION
**Pull request by SabaPing**
### What problem does this PR solve?

Fix `MaxDays` and `MaxBackups` not working for slow-query-logger

Issue Number: https://github.com/pingcap/tidb/issues/25716

Problem Summary:

`MaxDays` and `MaxBackups` not working for slow-query-logger. This may causes unexpected disk usage.

### What is changed and how it works?

Tests 

_**It seems that code related to log-file-lifecycle-control is not covered by any test case yet ?**_

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
Fix `MaxDays` and `MaxBackups` not working for slow log.
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@bb7133 PTAL

**Review by qw4990 — APPROVED** [review]

**Comment by bb7133** [comment]
Hi @SabaPing did you verified the change locally?

**Comment by bb7133** [comment]
Please provide a 'manual test' in the PR description, thanks!

**Comment by jyz0309** [comment]
I have tested it, /cc @bb7133

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
