### PR TITLE
planner/core: migrate test-infra to testify for physical_plan_test.go

### LINKED ISSUE #28409: migrate test-infra to testify for `planner/core/physical_plan_test.go`

### PR DESCRIPTION
**Pull request by tisonkun**
### What problem does this PR solve?

Issue Number: close #28409 close #32108

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @johnhaxx7

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
