### PR TITLE
expression: fix enum cannot use index to update (#27752)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #27752 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/28048
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/28048:release-5.1-e154b31e84e2
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/27750

`eval` with enum type should use `ParseEnum`

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by tiancaiamao** [comment]
For oncall 3716

**Review by tangenta — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
@ti-chi-bot

**Pull request merged**
