### PR TITLE
*: ensure TABLE statement works

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve?

Relevant to #21486

Problem Summary: 

### What is changed and how it works?

What's Changed:

1. A `SelectStmt` currently can be either a `SELECT`, `TABLE` or `VALUES` statement. The planner did not support the last two due to the missing `Fields` field. 
2. Because of (1), several functions expecting a `SelectStmt` only contains the word `SELECT` fails. In particular `EXPLAIN TABLE t` crashes.

How it Works:

1. Updated parser to include pingcap/parser#1118 so that `TABLE x` is equivalent to `SELECT * FROM x`.
2. Refactored the two functions relying on the keyword SELECT exactly to recognize TABLE and VALUES too.

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- Support the SQL standard `TABLE t` statement (compatible with MySQL 8.0.19), which is equivalent to the `SELECT * FROM t` statement.

### CODE REVIEW

**Comment by kennytm** [comment]
cc @xuyifangreeneyes #21569.

**Review by winoros — COMMENTED** [review]
Refer to the current impl of the TABLE stmt in the parser. It doesn't support hint right?

**Comment by kennytm** [comment]
@winoros Yes, the `/*+ ... */` comment is not special after the TABLE keyword.

**Comment by kennytm** [comment]
Not sure when, but all test cases in https://github.com/pingcap/tidb/pull/21487/files#diff-5863dfb268ffb04636ac662437541fa5f08aaea0a666c33826556fd641d73d53 including `EXPLAIN TABLE t` are now passing on v8.1. So closing.

**Pull request closed without merging**
