### PR TITLE
server: fix unstable test TestDumpStatsAPI

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: None

Problem Summary: fix unstable test TestDumpStatsAPI

https://ci.pingcap.net/job/atom-ut/1297/testReport/github/com_pingcap_tidb_server/TestDumpStatsAPI/

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @morgo @lcwangchao @djshow832 @hawkingrei 
PTAL

**Review by hawkingrei — APPROVED** [review]

**Review by morgo — APPROVED** [review]

**Comment by morgo** [comment]
You could also set the socket to empty string, but I think this works fine.

**Review by lcwangchao — APPROVED** [review]

**Pull request merged**
