### PR TITLE
util: Use TLSv1.2 as minimum TLS version by default

### LINKED ISSUE #36036: The minimum TLS version should comply with IETF RFC 8996
## Enhancement

TLSv1.1 and older should not be used by default.

- https://www.rfc-editor.org/rfc/rfc8996.html#name-do-not-use-tls-11
- https://dev.mysql.com/worklog/task/?id=14519
- https://dev.mysql.com/doc/refman/8.0/en/encrypted-connection-protocols-ciphers.html#encrypted-connection-supported-protocols

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #36036

Problem Summary:

- https://www.rfc-editor.org/rfc/rfc8996.html#name-do-not-use-tls-11
- https://dev.mysql.com/worklog/task/?id=14519

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
The minimum TLS version has been changed from TLSv1.1 to TLSv1.2 to comply with IETF RFC 8996.
```

### CODE REVIEW

**Comment by zhangyangyu** [comment]
I think this is not a simple one line change. It might affect some users still using TLSv1.1(both conscious & unconscious). We need to see how the product managers think.

**Comment by dveeden** [comment]
> I think this is not a simple one line change. It might affect some users still using TLSv1.1(both conscious & unconscious). We need to see how the product managers think.

Yes I agree. 

If people use very old clients that use YaSSL they won't be able to use TLSv1.2 or newer.
(see also: https://dev.mysql.com/doc/refman/5.7/en/ssl-libraries.html )

However this should only be merged into master and not be backported. So this won't affect users of TiDB v6.1.x or older.

This is only changing the default, so people can change the config to allow TLSv1.1 if needed.

This will improve security and may also be beneficial for compliance with various regulations.

**Comment by dveeden** [comment]
This is how MySQL handles this: (source: https://dev.mysql.com/doc/refman/8.0/en/encrypted-connection-protocols-ciphers.html )

image

**Comment by lulukelu** [comment]
Customers can choose TLS 1.1, 1.2, 1.3 versions, the default is to configure TLS 1.2, but does not support TLS1.0?

**Comment by dveeden** [comment]
> Customers can choose TLS 1.1, 1.2, 1.3 versions, the default is to configure TLS 1.2, but does not support TLS1.0?

By default TiDB supports TLSv1.1, 1.2 and 1.3. It can be configured to support TLSv1.0.

This change would change the default to only support TLSv1.2 and TLSv1.3.

**Comment by dveeden** [comment]
@lulukelu could you suggest reviewers for this PR?

**Review by lulukelu — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by bb7133** [comment]
> Unless you are using very old versions of MySQL Server or connectors, you are unlikely to have connections using TLSv1.0 or TLSv1.1. 

I have a concern that this will break some existing users if they're using very old clients. I tried to search for the version of clients that support TLS v1 only, but didn't get a clear conclusion yet.

**Comment by dveeden** [comment]
> > Unless you are using very old versions of MySQL Server or connectors, you are unlikely to have connections using TLSv1.0 or TLSv1.1.
> 
> I have a concern that this will break some existing users if they're using very old clients. I tried to search for the version of clients that support TLS v1 only, but didn't get a clear conclusion yet.

MySQL v5.6 and earlier only supported TLSv1.0. Very early on in the MySQL 5.7 lifecycle support for TLSv1.1 was added. The YaSSL library that was used for the community edition only supported TLSv1.0 and TLSv1.1, but not TLSv1.2 or newer. Later on support for YaSSL was removed (replaced by OpenSSL). Note that MySQL 5.7 is nearing end-of-life soon.

If this breaks things then a configuration change should allow TLSv1.1 (and TLSv1.0) if needed.

- https://bugs.mysql.com/bug.php?id=75239
- https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-10.html
- https://dev.mysql.com/doc/refman/5.7/en/source-ssl-library-configuration.html

**Comment by ljun0712** [comment]
From a security perspective, the product needs to be factory-safe by default, while retaining the compatibility of non-secure versions. Users can modify it according to their own conditions, and the security risks caused by the modification are borne by the customer.
So from the perspective of the security team, we agree with this modification.

**Review by CbcWestwolf — APPROVED** [review]

**Comment by dveeden** [comment]
/hold

I'd like to make sure @bb7133 is ok with merging this.

**Review by ljun0712 — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
