### PR TITLE
server: support for client multi-statement option (#19459)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19459 to release-4.0

---

### What problem does this PR solve?

Problem Summary:

The server previously did not correctly support the multi-statement client feature, which meant that multi-statement was always enabled. With this PR now it could be enabled or disabled (up to the client!)

### What is changed and how it works?

What's Changed:

How it Works:

### Related changes

- Need to cherry-pick to the release branch
- Docs: https://github.com/pingcap/docs/pull/4029

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

The go-sql driver allows changing the multi-statement option as a connection parameter, and I have added this to the test suite. I have also manually tested against the MySQL C client, which many drivers are based on. It allows changing the options of an open connection, and TiDB correctly supports this RPC. Here is that example program:

```
/*
* gcc example.c -o example  `mysql_config --cflags --libs`
*/
#include <mysql.h>
#include <stdio.h>
#include <string.h>

void run_single_test(MYSQL *conn) {

  if (mysql_query(conn, "update t1 set a = 1 where b = 1")) {
    printf("ERROR: %s\n", mysql_error(conn));
  } else {
    printf("SUCCESS: %s\n", mysql_error(conn));
  }

}

void run_multi_test(MYSQL *conn) {

  if (mysql_query(conn, "update t1 set a = 1 where b = 1;update t1 set a = 2 where b = 2;update t1 set a = 3 where b = 3;")) {
    printf("ERROR: %s\n", mysql_error(conn));
  } else {
    printf("SUCCESS: %s\n", mysql_error(conn));
  }

}

int main(int argc, char **argv) {

  MYSQL *conn = mysql_init(NULL);

  if (conn == NULL)  {
      fprintf(stderr, "%s\n", mysql_error(conn));
      exit(1);
  }

  if (mysql_real_connect(conn, "127.0.0.1", "root", "", "test", 4000, NULL, 0) == NULL) {
//   if (mysql_real_connect(conn, "127.0.0.1", "msandbox", "msandbox", "test", 8021, NULL, 0) == NULL) {
      fprintf(stderr, "%s\n", mysql_error(conn));
      mysql_close(conn);
      exit(1);
  }

  run_single_test(conn); // works
  run_multi_test(conn); // fails
  mysql_set_server_option(conn, MYSQL_OPTION_MULTI_STATEMENTS_ON);
  run_single_test(conn); // works
  run_multi_test(conn); // works

  mysql_close(conn);
  exit(0);

}
```
Here is the output of the program (whether or not the tables exist is inconsequential):
```
nullnotnil@ubuntu:~$ gcc example.c -o example  `mysql_config --cflags --libs` && ./example 
ERROR: Table 'test.t1' doesn't exist
ERROR: client has multi-statement capability disabled
ERROR: Table 'test.t1' doesn't exist
ERROR: Table 'test.t1' doesn't exist
```

Side effects

- Breaking backward compatibility

Some clients may incorrectly be depending on the current behavior! It may break for them.

### Release note 

- The TiDB Server previously did not correctly support disabling client multi-statement support.

### CODE REVIEW

**Comment by nullnotnil** [comment]
It looks like it needs tidb-test PR 1090 cherry picked to the release branch as well.

**Comment by lysu** [comment]
LGTM

**Review by lysu — COMMENTED** [review]
LGTM

**Review by jackysp — APPROVED** [review]
LGTM

**Comment by bb7133** [comment]
The release-4.0 branch is frozen for now, let's hold it until merging is available again.

**Pull request merged**
