### PR TITLE
txn: forbid savepoint when lazy uniqueness check is enabled

### PR DESCRIPTION
**Pull request by ekexium**
Signed-off-by: ekexium <eke@fastmail.com>

### What problem does this PR solve?

Issue Number: ref #36579 

Problem Summary:

It's hard to tell and implement the correct or expected behavior when lazy uniqueness check is enabled and savepoint is used. So forbid such use case.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by sticnarf** [comment]
Is it counter-intuitive that the error happens when rolling back to the savepoint? Can we raise the error when creating the savepoint?

**Comment by TonsnakeLin** [comment]
LGTM.

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
