### PR TITLE
planner: disable mpp_outer_join_fixed_build_side by default

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

Currently, `mpp_outer_join_fixed_build_side` is enabled by default, we want to disable it by default since let the optimizer choose the build side can speed up the query in most cases.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by hanfei1991 — APPROVED** [review]

**Review by fzhedu — APPROVED** [review]
/LGTM

**Review by fzhedu — APPROVED** [review]
/LGTM

**Review by hanfei1991 — APPROVED** [review]

**Pull request merged**
