### PR TITLE
util/encrypt: migrate test-infra to testify

### LINKED ISSUE #27816: migrate test-infra to testify for `util/encrypt` pkg

### PR DESCRIPTION
**Pull request by karuppiah7890**
### What problem does this PR solve?

Issue Number: close #27816

Problem Summary: migrate test-infra to testify for `util/encrypt` package

### What is changed and how it works?

What's Changed:

Migrated tests to use testify package instead of `github.com/pingcap/check package` for assertions and any test utils and matchers that `github.com/pingcap/check` provided

### Check List

Tests

- [x] Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by karuppiah7890** [comment]
Question: Do we need the extra options for the goleak? To ignore some top level functions. But I didn't get any leak error while running

```bash
{ make failpoint-enable; go test github.com/pingcap/tidb/util/encrypt; make failpoint-disable; }
```

So I'm guessing there's nothing to ignore in this case, unlike here https://github.com/pingcap/tidb/blob/master/ddl/failtest/main_test.go#L37-L42

**Comment by karuppiah7890** [comment]
By the way, I noticed some unrelated errors while running all the tests -

```bash
tidb $ make gotest
Running in native mode.
gsttimeout-check
grep 'PASS:' gotest.log | go run tools/check/check-timeout.go || { $(find $PWD/ -type d | grep -vE "(\.git|tools)" | xargs tools/bin/failpoint-ctl disable); exit 1; }
^R
The following test cases take too long to finish:
PASS: builtin_time_vec_generated_test.go:6727: testVectorizeSuite1.TestVectorizedBuiltinTimeEvalOneVecGenerated	6.754s
PASS: builtin_time_vec_test.go:575: testVectorizeSuite2.TestVectorizedBuiltinTimeEvalOneVec	7.341s
PASS: builtin_time_vec_test.go:579: testVectorizeSuite2.TestVectorizedBuiltinTimeFunc	5.569s
--- PASS: TestClusterConfigInfoschema (5.71s)
--- PASS: TestCTEPreviewAndReport (7.12s)
exit status 252
make: *** [gotest] Error 1
tidb $ 
```

**Comment by karuppiah7890** [comment]
There seems to be an unrelated error in pipeline too over here https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/33109/pipeline

```bash
[2021-09-13T15:40:22.324Z] FAIL
[2021-09-13T15:40:22.324Z] + cat test.log
[2021-09-13T15:40:22.324Z] + grep -Ev '^\[[[:digit:]]{4}(/[[:digit:]]{2}){2}'
[2021-09-13T15:40:22.324Z] + grep -A 30 '\-------'
[2021-09-13T15:40:22.324Z] + grep -A 29 FAIL
[2021-09-13T15:40:22.324Z] FAIL: attributes_sql_test.go:237: testDBSuite8.TestFlashbackTable
[2021-09-13T15:40:22.324Z] 
[2021-09-13T15:40:22.324Z] attributes_sql_test.go:301:
[2021-09-13T15:40:22.324Z]     c.Assert(rows2[0][3], Equals, rows[0][3])
[2021-09-13T15:40:22.324Z] ... obtained string = "7480000000000021ff4e5f720000000000fa"
[2021-09-13T15:40:22.324Z] ... expected string = "7480000000000000ff375f720000000000fa"
```

**Comment by karuppiah7890** [comment]
Oops. Sorry, I just did rebase and force pushed and noticed that there was a merge being done

**Comment by tisonkun** [comment]
Hi @karuppiah7890 ! Thanks for your contribution and sorry for our unstable tests in such a terrible situation.

For any failing tests you found, you can try to find an issue on https://github.com/pingcap/tidb/issues/25899:

* If there is already one, report another instance you meet so that we may increase its priority.
* If there is none, create an issue and ask for link in the tracking issue for unstable tests.

Thanks for your understanding.

**Comment by unconsolable** [comment]
> Question: Do we need the extra options for the goleak? To ignore some top level functions. But I didn't get any leak error while running
> 
> ```shell
> { make failpoint-enable; go test github.com/pingcap/tidb/util/encrypt; make failpoint-disable; }
> ```
> 
> So I'm guessing there's nothing to ignore in this case, unlike here https://github.com/pingcap/tidb/blob/master/ddl/failtest/main_test.go#L37-L42

For some test cases, goroutine leaks are known issues, we should add these goroutines to ignore list, such as 
https://github.com/pingcap/tidb/blob/9d3b67f45048a27b48f01ead4e256bc8cb8a0979/ddl/failtest/main_test.go#L37-L40

But some goroutine leaks are caused by test code, we should try to fix them.

**Comment by tisonkun** [comment]
> Oops. Sorry, I just did rebase and force pushed and noticed that there was a merge being done

Never mind. If my action causes any inconvenient, please let me know.

In our [dev guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#contributing-process) it says:

> Review and address comments on your pull request. If your pull request becomes outdated with the target branch, you need to rebase your pull request to keep it up to date. Since TiDB uses squash and merge, simply merging master to catch up the change is also acceptable.

Since the catching up so frequently I move to use the merge button gradually.

**Comment by karuppiah7890** [comment]
Makes sense 👍

**Comment by karuppiah7890** [comment]
@unconsolable how do I know if my test has any known goroutine leaks and that I need to ignore them? Similar to https://github.com/pingcap/tidb/blob/master/ddl/failtest/main_test.go#L37-L42

How was it found that https://github.com/pingcap/tidb/blob/master/ddl/failtest/main_test.go#L37-L42 has known goroutine leaks - does it always show as leak error or only sometimes?

**Comment by unconsolable** [comment]
> @unconsolable how do I know if my test has any known goroutine leaks and that I need to ignore them? Similar to https://github.com/pingcap/tidb/blob/master/ddl/failtest/main_test.go#L37-L42
> 
> How was it found that https://github.com/pingcap/tidb/blob/master/ddl/failtest/main_test.go#L37-L42 has known goroutine leaks - does it always show as leak error or only sometimes?

I usually add `main_test.go` first and run locally, then when I encounter goroutine leak, I will refer the list here
https://github.com/pingcap/tidb/blob/9d3b67f45048a27b48f01ead4e256bc8cb8a0979/util/testleak/leaktest.go#L55-L69

However, there is a exception. https://github.com/pingcap/tidb/pull/27704#discussion_r700046480

**Comment by karuppiah7890** [comment]
Cool ! So, when I ran in my local, I noticed no issues / errors related to goroutine leaks, let me also check the exception now

**Comment by karuppiah7890** [comment]
Looks like after rebase there are no unstable errors in my local and in CI, interesting

**Comment by tisonkun** [comment]
@karuppiah7890 the most unstable timeout checker is temporarily disabled by #27980

**Comment by karuppiah7890** [comment]
Ah okay!

**Review by morgo — APPROVED** [review]

**Review by mmyj — APPROVED** [review]
lgtm

**Review by tisonkun — COMMENTED** [review]
@karuppiah7890 I think almost these test cases can be run in parallel.

**Comment by karuppiah7890** [comment]
@tisonkun I just saw this comment. Should I raise another PR? With `t.Parallel()` in all these tests. That's what you mean right @tisonkun ?

**Comment by tisonkun** [comment]
> @tisonkun I just saw this comment. Should I raise another PR? With `t.Parallel()` in all these tests. That's what you mean right @tisonkun ?

I think it is ok to leave as is since it is almost lightweight test. But if you can investigate the possibility for running in parallel, I'd like to give it a review and moderate the contribution. You can create an issue for the follow up and then a PR, if you'd like to do it.

**Comment by karuppiah7890** [comment]
Yes, the tests are lightweight indeed, all running within less than 1 second. But yes, parallelization would be cool. I will raise an issue and a PR for it sometime 👍

**Comment by karuppiah7890** [comment]
Created the issue for now - #28034

**Pull request merged**
