### PR TITLE
*: update tikv/client-go to improve failpoint performance issue

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?

Update `tikv/client-go` to resolve failpoint performance issue.

### What's changed

- update client-go
- for test packages that need failpoints in client-go, enable it in `TestingT`
- in `main.go`, when `enableTestAPI` is true, enable failpoints of client-go.

### Check List 

Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
I'm a bit worry that now when we depend on client-go failpoint we have to remember write `tikv.EnableFailpoints`.

Do you have a picture when and how a developer depend on client-go failpoint remember calling `tikv.EnableFailpoints`? And if not, does it produce false positive or false negative?

**Comment by disksing** [comment]
I think this question is more about how to write tests based on failpoint.
My little thought is that after we set up a failpoint in a test, it is best to verify in some way that it is actually triggered. A contrary example is that I previously found a test that did not adjust the failpoint path after changing the mockstore from mocktikv to unistore, which caused the test to become invalid.

**Comment by tisonkun** [comment]
@disksing Yep. If a test requires enabling failpoints but forget would produce error, then it makes sense to me.

**Review by tisonkun — APPROVED** [review]
LGTM

**Review by tisonkun — APPROVED** [review]

**Comment by tiancaiamao** [comment]
I'll not be bothered by those performance issues any more, I'm tracking the performance regression now.  ⚆_⚆

**Review by tiancaiamao — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]

**Pull request merged**
