### PR TITLE
ebs br: control the snapshots batch size for fsr enable/disable

### LINKED ISSUE #48505: ebs br: enable AWS snapshot FSR failed for API quota limitation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run EBS snapshot restore with `fsr` warmup option against a k8s cluster where each data plane has more than 10 TiKV nodes.

### 2. What did you expect to see? (Required)

Restore succeed

### 3. What did you see instead (Required)
`I1109 18:47:18.189386       9 restore.go:186] Error: InvalidRequest: Number of values of parameter SourceSnapshotIds must be less than or equal to 10.
	status code: 400, request id: 0e20ce03-a38a-4742-824d-014239952e5e`

### 4. What is your TiDB version? (Required)

TiDB and BR 6.5 nightly

### PR DESCRIPTION
**Pull request by BornChanger**
### What problem does this PR solve?

Issue Number: close #48505 

Problem Summary:

### What is changed and how it works?
This PR will control the batch size of snapshots for AWS snapshot FSR enablement.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by nkg-** [comment]
Looks great. Thanks for the quick fix.

**Review by YuJuncen — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
