### PR TITLE
kv: cleanup outdated code

### PR DESCRIPTION
**Pull request by bobotu**
### What problem does this PR solve?
This is the last patchset of #18650. Please see the full description in the original PR page.

This PR only contains cleanup works.

This patchset is based on https://github.com/pingcap/tidb/pull/18657, I'll rebase this branch after the parent PR is merged.

Closes #18650

### Release note 

-  No release note

### CODE REVIEW

**Comment by bobotu** [comment]
PTAL @coocood @jackysp @lysu

**Comment by coocood** [comment]
LGTM

**Pull request merged**
