### PR TITLE
bindinfo: migrate testSerialSuite to testify

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

### What problem does this PR solve?

Issue Number: ref #27177

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
/cc @sylzd @tiancaiamao 

cc @w169q169

**Comment by sylzd** [comment]
lgtm

**Review by sylzd — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Comment by tisonkun** [comment]
/assign @tiancaiamao 

Could you help on merging this PR? Or we require another reviewer?

**Review by djshow832 — APPROVED** [review]

**Pull request merged**
