### PR TITLE
store: keep alive for etcd client

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

Same problem like https://github.com/pingcap/tidb/pull/14118.

### What is changed and how it works?

Add keep alive options for etcd client.

### Check List 

Tests 
 - No code

Code changes

Side effects

Related changes

Release note

### CODE REVIEW

**Comment by nolouch** [comment]
LGTM.

**Comment by tiancaiamao** [comment]
LGTM

**Comment by tiancaiamao** [comment]
PTAL  @lysu

**Pull request merged**
