### PR TITLE
store: make storage type a enum

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: ref #57275

Problem Summary:

### What changed and how does it work?
as title 

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

**Comment by D3Hunter** [comment]
wait https://github.com/pingcap/tidb/issues/57298 fixed

**Review by yudongusa — APPROVED** [review]
Please provide more detailed description of the issue.

**Review by yudongusa — APPROVED** [review]

**Pull request merged**
