### PR TITLE
tikv: enlarge batch size

### PR DESCRIPTION
**Pull request by ngaut**
Enlarge batch size from 128 to 256 to reduce network round trip.

### CODE REVIEW

**Comment by disksing** [comment]
LGTM.

**Comment by zz-jason** [comment]
do we have some test on how the batch size affect the cpu/mem performance ?

**Comment by shenli** [comment]
@zz-jason DDL worker will get 256 rows for each time. So cache 100 rows is not suitable.

**Comment by shenli** [comment]
LGTM

**Pull request merged**
