### PR TITLE
raw_restore: fix the issue that raw restore rewrite the t prefix keys

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/35279

Problem Summary:

### Check List

Tests 

- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
before this PR 
image

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix the issue that raw restore rewrite the t prefix keys
```

### CODE REVIEW

**Review by pingyu — APPROVED** [review]
LGTM~

**Review by glorv — APPROVED** [review]

**Pull request merged**
