### PR TITLE
store/tikv: batch regions in a single scatter request

### PR DESCRIPTION
**Pull request by rleungx**
Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

Problem Summary: For now, we call `ScatterRegions` for every single region.

### What is changed and how it works?

What's Changed: This PR supports sending multi regions in a single request.

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Review by Yisaer — APPROVED** [review]
/lgtm

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by tisonkun** [comment]
@rleungx may this PR goes to client-go? I think there is no `store/tikv` now.

**Comment by rleungx** [comment]
Close it since the corresponding code has moved to `client-go` repo.

**Pull request closed without merging**
