### PR TITLE
*: migrate tidb-tools

### LINKED ISSUE #32999: migrate tidb-tools into tidb

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #32999

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Comment by disksing** [comment]
maybe we should replace testify in `tidb-tools` repo and merge to here later.

**Review by BornChanger — COMMENTED** [review]
please fix the failure of idc-jenkins-ci-tidb/check_dev, which seems to be improper comments.

**Comment by tisonkun** [comment]
@hawkingrei shall this be closed according to https://github.com/pingcap/tidb/pull/33296?

**Comment by lance6716** [comment]
> @hawkingrei shall this be closed according to #33296?

ping @hawkingrei

**Pull request closed without merging**
