### PR TITLE
expression: correct returntype of TIDB_PARSE_TSO()

### LINKED ISSUE #37964: Wrong return type for TIDB_PARSE_TSO leads to issues with Java based tools
## Bug Report

With Java based tools like DataGrip the return type of `TIDB_PARSE_TSO` leads to issues.

### 1. Minimal reproduce step (Required)

With DataGrip or IntelliJ run this:

```
BEGIN;
SELECT @@tidb_current_ts, TIDB_PARSE_TSO(@@tidb_current_ts);
ROLLBACK;
```

### 2. What did you expect to see? (Required)

Resultset with the numeric TSO and the date/time of the current TSO.

### 3. What did you see instead (Required)

image

```
java.sql.SQLException: Invalid length (26) for type DATE
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:99)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getDate(ResultSetImpl.java:776)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1265)
	in JdbcHelperImpl.getObject(JdbcHelperImpl.java:324)
Caused by: com.mysql.cj.exceptions.DataReadException: Invalid length (26) for type DATE
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.getDate(MysqlTextValueDecoder.java:269)
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeDate(MysqlTextValueDecoder.java:77)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:92)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:243)
	at com.mysql.cj.protocol.a.result.TextBufferRow.getValue(TextBufferRow.java:132)
	... 23 more
```

### 4. What is your TiDB version? (Required)

```Release Version: v6.3.0-alpha
Edition: Community
Git Commit Hash: 29f83a0b25926390c757f71a84baa2322a289f78
Git Branch: heads/refs/tags/v6.3.0-alpha
UTC Build Time: 2022-09-18 14:33:04
GoVersion: go1.19
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
```

Note also this:
```
$ mysql -h 127.0.0.1 -P 4000 -u root --column-type-info -e 'BEGIN; SELECT @@tidb_current_ts, TIDB_PARSE_TSO(@@tidb_current_ts); ROLLBACK;'
Field   1:  `@@tidb_current_ts`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_bin (46)
Length:     0
Max_length: 18
Decimals:   31
Flags:      

Field   2:  `TIDB_PARSE_TSO(@@tidb_current_ts)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       DATE
Collation:  utf8mb4_bin (46)
Length:     10
Max_length: 26
Decimals:   0
Flags:      NOT_NULL 


+--------------------+-----------------------------------+
| @@tidb_current_ts  | TIDB_PARSE_TSO(@@tidb_current_ts) |
+--------------------+-----------------------------------+
| 436101387569332226 | 2022-09-19 15:39:30.696000        |
+--------------------+-----------------------------------+
```

Here `Max_length` is 26 and the `Type` is `DATE`. To me it looks like this should have been a `DATETIME` instead of a `DATE` as it has both a date and a time component.

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #37964

Problem Summary:

`TIDB_PARSE_TSO()` returns a date and time. It should use the `DATETIME` datatype instead of `DATE`.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]
LGTM

**Review by lance6716 — APPROVED** [review]
it's apparently correct but still better to paste your manually testing as in https://github.com/pingcap/tidb/issues/37964

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by bb7133** [comment]
> It's apparently correct but still better to paste your manually testing as in https://github.com/pingcap/tidb/issues/37964

Please update the PR description, thanks!

**Pull request merged**
