### PR TITLE
executor: fix table id to partition id mapping in select lock executor

### LINKED ISSUE #26251: Join partition table with normal table for update should lock normal table but not
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Prepare:
```
create table tp (id int primary key) partition by range (id) (partition p0 values less than (100));
create table tn (id int primary key);
insert into tp values(1),(2);
insert into tn values(1),(2);
```

Session1:
```
begin;
select * from tp,tn where tp.id=tn.id and tn.id<=1 for update;
```

Session2:
```
begin;
select * from tn where id=1 for update;
```

### 2. What did you expect to see? (Required)

Session2 should be blocked util session1's txn is committed or aborted.

### 3. What did you see instead (Required)

Session2 not blocked.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #26251

Problem Summary:

### What is changed and how it works?

What's Changed:

In `SelectLock` executor, `tblID2PIDColumnIndex`   map the table ID to partition ID column, the partition ID is obtained by

```
offset := e.tblID2PIDColumnIndex[id]
physicalID = row.GetInt64(offset)
```

In some cases like #26251, the table is not a partition table, so it's not in `tblID2PIDColumnIndex`
The original table ID should be used, instead of try to mapping it to partition ID.

How it Works:

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- Fix a bug 'select for update' does not correctly lock the data when a normal table join a partition table.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Wait for review after https://github.com/pingcap/tidb/pull/26373

**Comment by tiancaiamao** [comment]
PTAL @zhuo-zhi  @qw4990

**Review by zhuo-zhi — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Pull request merged**
