### PR TITLE
variables: enable variable hook to access storage

### LINKED ISSUE #38225: enable variable hook to access store
## Enhancement

Now the variable hook cannot access the storage. The initial senerio is to set/get external timestamp through pd:

```
GetGlobal: func(s *SessionVars) (string, error) {
    externalTimestamp := s.GetStore().GetOracle().GetCustomTimestamp(context.TODO(), 0)
    ....
}
```

I want to add a new interface

```
type HookContext interface {
    GetStore() kv.Storage
}

type SessionVars struct {
    ....
    
    HookContext
}
```

It will bring a problem: the cyclic initialization is a little tiring. For example,  if you are creating a `session`, it will be like: 

```
s = &session {}
s.vars = SessionVars {
    HookContext: s
}
```

If don't like cyclic initialization, we could create a struct to provide the store as a hook context.

## Other options

I have also tried other options, but none of them works well:

1. Add more variables to the hook. However the hook is not called directly, so I have to add these variables (e.g. kv.Storage) to every layers, and the caller on the most outside should always call with `sctx.xxx().xxxx(sctx.GetStore())`. It's redundant, and the code change is too much.
2. Pass in the `sessionctx.Context` instead of `SessionVars`. Obviously, there are cycle import between `sessionctx` and `variable`.

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

This PR enables variable hooks to access storage.

Issue Number: close #38225

Problem Summary:

As described in #38225, current system variable cannot call pd services in the hook, which is just needed by the external-timestamp-read feature.

### What is changed and how it works?

Add a new interface `HookEvent` (which has already been implemented by `session`), and assign it to the `SessionVars`.

The only concern is about the cycle initialization. It's ugly and tiring.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
@xhe @bb7133 Could you help me to `/merge` this PR?

**Comment by morgo** [comment]
I don't think this is required. See https://github.com/pingcap/tidb/pull/38182 for an example on how to access storage.

If the Setter func calls a noop, you can overwrite the noop from another part of code (such as domain) to have the required context.

**Pull request merged**
