### PR TITLE
store/tikv: fix bug of cleaning store cache on grpc canceled error

### PR DESCRIPTION
**Pull request by hhkbp2**
Hi,

This PR fixes bug seen in the production cluster. Log messages like 

```
2017/07/06 21:07:37 region_cache.go:419: [info] drop regions of store 49978 from cache due to request fail, err: rpc error: code = Canceled desc = context canceled
```

should not happen. It should not clean buffered store info from region cache when the context is canceled. 

Related to #3390 #3259

### CODE REVIEW

**Comment by hhkbp2** [comment]
PTAL @tiancaiamao @disksing

**Comment by disksing** [comment]
LGTM.

**Comment by zimulala** [comment]
Please fix CI.

**Comment by tiancaiamao** [comment]
Any update? @hhkbp2

**Comment by hhkbp2** [comment]
@tiancaiamao @zimulala PTAL
A mock server is added to the test case to avoid the interfere of "socket unavailable" error. CI should be fine now.

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
