### PR TITLE
expression: fix typo

### PR DESCRIPTION
**Pull request by kururuken**
### What problem does this PR solve?

Problem Summary:

Fix typo in expression/builtin_time: `newDateArighmeticalUtil` -> `newDateArithmeticalUtil`

### What is changed and how it works?

What's Changed:

`newDateArighmeticalUtil` -> `newDateArithmeticalUtil`

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by b41sh** [comment]
LGTM

**Review by tisonkun — APPROVED** [review]
Thanks for your contribution! LGTM.

**Comment by tisonkun** [comment]
cc @b41sh @tangenta could you please help on merging this PR?

**Pull request merged**
