### PR TITLE
 ddl: fix the case that fails to split a table

### PR DESCRIPTION
**Pull request by zimulala**
If we fail to split a table, but the table is created, we will get an error as follows:
```
mysql> create database sbtest;
Query OK, 0 rows affected (0.09 sec)
mysql> use sbtest;
Database changed
mysql> CREATE TABLE `shtable` (
    ->   `id` int(11) NOT NULL AUTO_INCREMENT,
    ->    PRIMARY KEY (`id`)
    ->  );
ERROR 1050 (42S01): Table 'shtable' already exists
```

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @disksing @coocood @shenli

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
