### PR TITLE
parser: Support STRAIGHT_JOIN...USING

### LINKED ISSUE #54162: SELECT ... STRAIGHT_JOIN ... USING ... returns syntax error
### 1. Minimal reproduce step (Required)

```sql
SELECT 1 FROM (SELECT 1 x) a STRAIGHT_JOIN (SELECT 1 x) b USING (x);
```

### 2. What did you expect to see? (Required)

```
mysql-8.4.0> SELECT 1 FROM (SELECT 1 x) a STRAIGHT_JOIN (SELECT 1 x) b USING (x);
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql-8.0.11-TiDB-v8.1.0> SELECT 1 FROM (SELECT 1 x) a STRAIGHT_JOIN (SELECT 1 x) b USING (x);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 63 near "USING (x)" 
```

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #54162

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [x] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Support for `SELECT ... STRAIGHT_JOIN ... USING ( ... )` was added
```

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
> ensuring that each of them provides their approval
😂 

/assign bb7133 bornchanger d3hunter easonn7 tangenta

**Review by D3Hunter — APPROVED** [review]

**Comment by lance6716** [comment]
ping @bb7133 @bornchanger @tangenta

**Review by hawkingrei — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by kennytm** [comment]
looks like approval from `sig-critical-approvers-parser` is required.

**Review by yudongusa — APPROVED** [review]

**Pull request merged**
