### PR TITLE
c4pt0r/fix copyright infringement

### PR DESCRIPTION
**Pull request by qiuyesuifeng**
fixes https://github.com/pingcap/tidb/issues/45

### CODE REVIEW

**Comment by c4pt0r** [comment]
@cznic

**Comment by c4pt0r** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Comment by cznic** [comment]
@c4pt0r  Thanks for CCing me. I'm sorry to miss the time window for reviewing the PR before merging. We live in different time zones, I would suggest to wait like 24 hours - in case you would like to hear from me ;-)

Anyway, the PR is 99% ok, except for some minor issues, which I believe can be addressed rather easily:

- The particular [`LICENSE`] (https://github.com/cznic/ql/blob/9c77931b60c6317f94de402268bbc3e8334b71f4/LICENSE) file, mentioned by the QL copyright code comments is nowhere to be found. Please put that file somewhere. The repository root is possibly a convenient place.

- I suggest to use a distinct name for the QL license file, like, for example `QL-LICENSE`, to not confuse the TIDB and QL licenses. In such case the QL copyright comments in source code should probably be updated to s/LICENSE/QL-LICENSE/.

- The util/format.go is not copyright `ql authors`, but `strutil authors`. I suggest to use the name `STRUTIL-LICENSE` and put the copy of that [license](https://github.com/cznic/strutil/blob/1eb03e3cc9d345307a45ec82bd3016cde4bd4464/LICENSE) in either the repo root or in the `util` directory.

I suggest to reopen this issue or fill a new one as a reminder to solve these final nits.

Thank you very much for your kind cooperation.

**Comment by c4pt0r** [comment]
@cznic gotcha! We'll fix it in a new PR.
:)

**Comment by c4pt0r** [comment]
Could we put all LICENSE files into a separated directory and update the copyright comments to root/LICENSES/QL-LICENSE? Just for keeping root directory clean.  ;D

**Comment by cznic** [comment]
@c4pt0r I see no problem with that approach.

**Comment by c4pt0r** [comment]
OK, cool, we'll fix it right away :+1:

**Comment by qiuyesuifeng** [comment]
@cznic  
#75  PTAL.

**Comment by cznic** [comment]
@qiuyesuifeng I think PR #74 , already merged, did the same.

**Comment by qiuyesuifeng** [comment]
yes, i made a mistake.
#75  has been closed.
#74 is the correct one.

Thank u.

**Pull request merged**
