### PR TITLE
util/ranger: fix func name typo

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
### What problem does this PR solve?

Func name typo

### What is changed and how it works?

Fix wrong func name

### Check List 

Tests 

No

Side effects

No

### Release note

- No release note.

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Comment by wjhuang2016** [comment]
Please update the release note and title.

**Review by AndreMouche — APPROVED** [review]
LGTM

**Review by disksing — APPROVED** [review]

**Comment by tisonkun** [comment]
This PR requires a "sig/planner" committer to merge :\

**Review by rebelice — APPROVED** [review]

**Pull request merged**
