### PR TITLE
Makefile: filter gotest.log on error

### LINKED ISSUE #28042: Only print go test output on failure, not the full tidb log
## Enhancement

When running `make dev` or `make gotest` the full content of gotest.log is returned on the console, but it would be better (less noise and bandwidth) if the tidb-server logs were removed, and only output from the tests were shown. The gotest.log still includes the full log and can be inspected further if needed.

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #28042 

Problem Summary:
When running `make dev` or `make gotest` and there is an error, one is overwhelmed with log output, by filtering we can reduce noise and bandwidth on errors, while the gotest.log still exists for further deep dives.

### What is changed and how it works?

What's Changed:
instead of `cat` the full file, use `grep -v ...` to remove non needed log entries

### Check List 

Tests 

- [X] Manual test (add detailed scripts or steps below)
  - run `make gotest` with a non-passing repository state and see the output decrease a lot and directly give the error.

Side effects

n/a

Documentation

Build/output change only
### Release note 

```release-note
None.
```

### CODE REVIEW

**Review by ngaut — APPROVED** [review]
Good catch. LGTM

**Review by xhebox — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]
Thanks. It makes things better.

However, it is still brittle and based on pattern match. I'd prefer we investigate on `go test -json` and filter output structually.

**Comment by tisonkun** [comment]
Also the original purpose of `cat` is bringing error log for failed test. It seems this patch also filter them out?

**Review by tisonkun — COMMENTED** [review]
Could you elaborate the regex in comments?

**Comment by mjonss** [comment]
> Thanks. It makes things better.
> 
> However, it is still brittle and based on pattern match. I'd prefer we investigate on `go test -json` and filter output structurally.

The reason for only removing log lines was to remove noice, not to only extract what could possibly be interesting, I think that is a good enough start at least.


> Also the original purpose of `cat` is bringing error log for failed test. It seems this patch also filter them out?

It does filter out all logs from tidb run and passing/ok go test output to avoid showing non interesting logs while running `make dev` or `make gotest`. I did not intend to filter out core lines like which test failed.


> Could you elaborate the regex in comments?

I added comments for the regex in my latest commit.

**Comment by mjonss** [comment]
> Thanks. It makes things better.
> 
> However, it is still brittle and based on pattern match. I'd prefer we investigate on `go test -json` and filter output structurally.

I just tried `go test -json` and it basically only changes each text line into a json object instead, so going from:
```
FAIL: executor_test.go:5658: testSuiteWithCliBaseCharset.TestCharsetFeature
```
to:
```json
{"Time":"2021-09-16T17:12:01.151088773+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"FAIL: executor_test.go:5658: testSuiteWithCliBaseCharset.TestCharsetFeature\n"}
```
Which I'm not sure is giving much more information, especially not in the `make gotest` context.

And it will still also just encode each line in the output to a json object instead, so the detailed error would be changed from:
```
executor_test.go:5692:
    tk.MustQuery("select _gbk 'a'").Check(testkit.Rows("a"))
/home/mattias/repos/tidb/util/testkit/testkit.go:364:
    tk.c.Assert(errors.ErrorStack(err), check.Equals, "", comment)
... obtained string = "" +
...     "[parser:1064]You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 15 near \"\"Get collation error for charset: gbk \n" +
...     "github.com/pingcap/errors.AddStack\n" +
...     "\t/home/mattias/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/errors.go:174\n" +
...     "github.com/pingcap/errors.(*Error).GenWithStackByArgs\n" +
...     "\t/home/mattias/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/normalize.go:159\n" +
...     "github.com/pingcap/tidb/util.SyntaxError\n" +
...     "\t/home/mattias/repos/tidb/util/misc.go:161\n" +
...     "github.com/pingcap/tidb/session.(*session).Parse\n" +
...     "\t/home/mattias/repos/tidb/session/session.go:1341\n" +
...     "github.com/pingcap/tidb/util/testkit.(*TestKit).Exec\n" +
...     "\t/home/mattias/repos/tidb/util/testkit/testkit.go:190\n" +
...     "github.com/pingcap/tidb/util/testkit.(*TestKit).MustQuery\n" +
...     "\t/home/mattias/repos/tidb/util/testkit/testkit.go:363\n" +
...     "github.com/pingcap/tidb/executor_test.(*testSuiteWithCliBaseCharset).TestCharsetFeature\n" +
...     "\t/home/mattias/repos/tidb/executor/executor_test.go:5692\n" +
...     "reflect.Value.call\n" +
...     "\t/usr/lib/go-1.16/src/reflect/value.go:476\n" +
...     "reflect.Value.Call\n" +
...     "\t/usr/lib/go-1.16/src/reflect/value.go:337\n" +
...     "github.com/pingcap/check.(*suiteRunner).forkTest.func1\n" +
...     "\t/home/mattias/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850\n" +
...     "github.com/pingcap/check.(*suiteRunner).forkCall.func1\n" +
...     "\t/home/mattias/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739\n" +
...     "runtime.goexit\n" +
...     "\t/usr/lib/go-1.16/src/runtime/asm_amd64.s:1371"
... expected string = ""
... sql:select _gbk 'a', args:[]
```
to:
```json
{"Time":"2021-09-16T17:12:01.151093957+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"executor_test.go:5692:\n"}
{"Time":"2021-09-16T17:12:01.151096796+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"    tk.MustQuery(\"select _gbk 'a'\").Check(testkit.Rows(\"a\"))\n"}
{"Time":"2021-09-16T17:12:01.151099381+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"/home/mattias/repos/tidb/util/testkit/testkit.go:364:\n"}
{"Time":"2021-09-16T17:12:01.151102095+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"    tk.c.Assert(errors.ErrorStack(err), check.Equals, \"\", comment)\n"}
{"Time":"2021-09-16T17:12:01.151104789+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"... obtained string = \"\" +\n"}
{"Time":"2021-09-16T17:12:01.151107608+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"[parser:1064]You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 15 near \\\"\\\"Get collation error for charset: gbk \\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151110559+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"github.com/pingcap/errors.AddStack\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151113267+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"\\t/home/mattias/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/errors.go:174\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151115956+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"github.com/pingcap/errors.(*Error).GenWithStackByArgs\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151118489+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"\\t/home/mattias/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/normalize.go:159\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151121056+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"github.com/pingcap/tidb/util.SyntaxError\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151127281+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"\\t/home/mattias/repos/tidb/util/misc.go:161\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151130352+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"github.com/pingcap/tidb/session.(*session).Parse\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151133006+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"\\t/home/mattias/repos/tidb/session/session.go:1341\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151135647+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"github.com/pingcap/tidb/util/testkit.(*TestKit).Exec\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151138222+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"\\t/home/mattias/repos/tidb/util/testkit/testkit.go:190\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151140738+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"github.com/pingcap/tidb/util/testkit.(*TestKit).MustQuery\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151143272+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"\\t/home/mattias/repos/tidb/util/testkit/testkit.go:363\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151145826+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"github.com/pingcap/tidb/executor_test.(*testSuiteWithCliBaseCharset).TestCharsetFeature\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151149767+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"\\t/home/mattias/repos/tidb/executor/executor_test.go:5692\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151152564+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"reflect.Value.call\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151155182+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"\\t/usr/lib/go-1.16/src/reflect/value.go:476\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151157725+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"reflect.Value.Call\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151160212+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"\\t/usr/lib/go-1.16/src/reflect/value.go:337\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151162757+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"github.com/pingcap/check.(*suiteRunner).forkTest.func1\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151165309+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"\\t/home/mattias/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151167859+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"github.com/pingcap/check.(*suiteRunner).forkCall.func1\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.15117039+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"\\t/home/mattias/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.151173125+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"runtime.goexit\\n\" +\n"}
{"Time":"2021-09-16T17:12:01.15117587+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"...     \"\\t/usr/lib/go-1.16/src/runtime/asm_amd64.s:1371\"\n"}
{"Time":"2021-09-16T17:12:01.151178524+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"... expected string = \"\"\n"}
{"Time":"2021-09-16T17:12:01.15118481+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"... sql:select _gbk 'a', args:[]\n"}
{"Time":"2021-09-16T17:12:01.15118774+08:00","Action":"output","Package":"github.com/pingcap/tidb/executor","Test":"TestT","Output":"\n"}
```

**Comment by tisonkun** [comment]
Here is an example https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/33937/pipeline/

**Comment by tisonkun** [comment]
> I just tried `go test -json` and it basically only changes each text line into a json object instead, so going from:

You may found that we now get `"Test": "TestT"`. But with #26022 fixed we can get the detailed test func name so that we only filter those logs belong to failed test. However, it may take a bit long time.

For the PR itself, I'm afraid that omitting the logs of failed test will cause regression on debugging ci failure and waiting for @tiancaiamao 's advice. This is an example that only leaves assertion fail but not the log of that case  https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/33937/pipeline/.

**Comment by mjonss** [comment]
> > I just tried `go test -json` and it basically only changes each text line into a json object instead, so going from:
> 
> You may found that we now get `"Test": "TestT"`. But with #26022 fixed we can get the detailed test func name so that we only filter those logs belong to failed test. However, it may take a bit long time.
> 
> For the PR itself, I'm afraid that omitting the logs of failed test will cause regression on debugging ci failure and waiting for @tiancaiamao 's advice. This is an example that only leaves assertion fail but not the log of that case https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/33937/pipeline/.

Ah, so gotest is also used in the CI, I would be fine having separate execution paths or configuration (mostly for different log output) between developer used make commands and the CI tooling (if it depends on the log output from `make`).

What if I duplicate `gotest` to `devgotest` with gotest.log filtering and keeping `test` as-is and replacing `test` in `dev` to use the filtering `devgotest`?
Something like:
```diff
-dev: checklist check test
+dev: checklist check devtest
  
+devtest: checklist explaintest devgotest gogenerate br_unit_test
+       @>&2 echo "Great, all tests passed."
+

+# Same as gotest, but suppress a lot of noise in the gotest.log file on error
+devgotest: failpoint-enable
...
```

**Comment by tiancaiamao** [comment]
Can we get the original full log? Maybe we need to change the CI pipeline to get the file download link to get `gotest.log`?
Sometimes it's difficult to reproduce the FAIL case in our own environment and we need the original log to analyze.
@mjonss

**Comment by mjonss** [comment]
> Can we get the original full log? Maybe we need to change the CI pipeline to get the file download link to get `gotest.log`?
> Sometimes it's difficult to reproduce the FAIL case in our own environment and we need the original log to analyze.
> @mjonss

I don't know enough about the CI framework to answer the question. But I changed the PR according to above, i.e. separate the `make dev` (used by developers) from `make test` (used by CI) by duplicating `gotest` to `devgotest` and make use of it in `make dev` instead which then keeps the old behaviour for CI and filters the log for `make dev` or the new `make devgotest`

**Comment by bb7133** [comment]
LGTM, PTAL @zhouqiang-cl

**Review by tiancaiamao — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
@purelind PTAL, did we need to modify CI?

**Comment by purelind** [comment]
> @purelind PTAL, did we need to modify CI?

After merging https://github.com/PingCAP-QE/ci/pull/432 , the current changes will not affect the ci

**Pull request merged**
