### PR TITLE
lightning: enable setting conflict max-error

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: ref #40743 

Problem Summary:

### What is changed and how it works?
* Support setting a map ( string => int64 ) for max-error in toml .  
* The map supports setting conflict max-error count
* If the conflict max-error limit is reached during recording conflict errors in a batch, record this batch of data and then report the error.  
* Added unit tests and integration tests

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Added support for modifying the maximum number of conflict errors by setting `lightning.max-error` as an associated map 
```

### CODE REVIEW

**Comment by dsdashun** [comment]
integration br test passed: https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/14887/pipeline

**Review by gozssky — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
