### PR TITLE
tikv/region_cache:use []byte instead of kv.Key in KeyLocation

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: AndreMouche

### What problem does this PR solve?
This PR tries to use []byte instead of kv.Key in tikv.KeyLocation
Part of https://github.com/pingcap/tidb/issues/22513

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]

**Comment by hi-rustin** [comment]
> /merge

If the CI test fails, you just re-trigger the test that failed and the bot will merge the PR for you after the CI passes.

You don't need to keep `/merge`, just rerun the failed test by `/run-failed-test-name`.

**Comment by hi-rustin** [comment]
> /merge

If the CI test fails, you just re-trigger the test that failed and the bot will merge the PR for you after the CI passes.

You don't need to keep /merge, just rerun the failed test by /run-failed-test-name.

**Comment by AndreMouche** [comment]
> > /merge
> 
> If the CI test fails, you just re-trigger the test that failed and the bot will merge the PR for you after the CI passes.
> 
> You don't need to keep /merge, just rerun the failed test by /run-failed-test-name.

Thanks @hi-rustin

**Pull request merged**
