### PR TITLE
server: stable test

### LINKED ISSUE #23450: tidb_test.go:tidbTestSerialSuite.TestTLS failed
```
[2021-03-20T07:11:20.018Z] tidb_test.go:599:
[2021-03-20T07:11:20.018Z]     c.Assert(err, IsNil)
[2021-03-20T07:11:20.018Z] ... value *errors.withStack = dsn:root@tcp(127.0.0.1:36636)/test?tls=skip-verify&tidb_int_primary_key_default_as_clustered=true: sql: database is closed ("dsn:root@tcp(127.0.0.1:36636)/test?tls=skip-verify&tidb_int_primary_key_default_as_clustered=true: sql: database is closed")
```

[tidb_ghpr_unit_test](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/80640/pipeline)

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #23450

Problem Summary: Do not close the database in the goroutine. It should be a defer.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Review by xiongjiwei — APPROVED** [review]
/lgtm

**Comment by xhebox** [comment]
@wjhuang2016 missed.

It is introduced in #22999 by @Tjianke , merged by @xiongjiwei and me. It is an overlook...

**Pull request merged**
