### PR TITLE
Dockerfile:Add curl in the image (#20694)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20694 to release-4.0

---

### What problem does this PR solve?

we need curl to perform the readiness probe.
ref https://github.com/pingcap/tidb-operator/pull/3438

### What is changed and how it works?
Add curl in the image

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
build the image and try to run it

Side effects

### Release note 
- No release note

### CODE REVIEW

**Comment by lysu** [comment]
LGTM

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Comment by july2993** [comment]
@lysu PTAL

**Comment by lysu** [comment]
@wangggong @zz-jason PTAL help merge thx

**Comment by wangggong** [comment]
LGTM

**Review by zz-jason — APPROVED** [review]
LGTM

**Pull request merged**
