### PR TITLE
*: add TableSample ID for PhysicalIDToTypeString()

### PR DESCRIPTION
**Pull request by jyz0309**
Signed-off-by: jyz0309 <45495947@qq.com>

### What problem does this PR solve?

Problem Summary:
The TableSampleID is not shown in PhysicalIDToTypeString() , it will make the plan have "UnknownPlan"
### What is changed and how it works?

What's Changed:
add TableSampleID case.

### Related changes
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

### Release note 

-  add TableSampleID for PhysicalIDToTypeString()

### CODE REVIEW

**Comment by jyz0309** [comment]
> Add some test cases?

I will add it tonight, and plz review this pr tomorrow, thx : )

**Comment by jyz0309** [comment]
@djshow832 PTAL

**Review by qw4990 — APPROVED** [review]

**Review by eurekaka — APPROVED** [review]
/lgtm

**Pull request merged**
