### PR TITLE
planner: fix wrong type when unsigned int value union int value

### LINKED ISSUE #24953: executor: select with join return inconsistent result with MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
[initSQLs.txt](https://github.com/pingcap/tidb/files/6559552/initSQLs.txt)
[execSQLs.txt](https://github.com/pingcap/tidb/files/6559553/execSQLs.txt)

table A & B
```
CREATE TABLE `tbl_9` (
  `col_54` mediumint NOT NULL DEFAULT '2412996',
  `col_55` int NOT NULL,
  `col_56` bigint unsigned NOT NULL,
  `col_57` varchar(108) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`col_57`(3),`col_55`,`col_56`,`col_54`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin

CREATE TABLE `tbl_0` (
  `col_76` bigint(20) unsigned DEFAULT NULL,
  `col_1` time NOT NULL DEFAULT '13:11:28',
  `col_2` datetime DEFAULT '1990-07-29 00:00:00',
  `col_3` date NOT NULL DEFAULT '1976-09-16',
  `col_4` date DEFAULT NULL,
  `col_143` varbinary(208) DEFAULT 'lXRTXUkTeWaJ',
  KEY `idx_0` (`col_2`,`col_1`,`col_76`,`col_4`,`col_3`),
  PRIMARY KEY (`col_1`,`col_3`) /*T![clustered_index] NONCLUSTERED */,
  KEY `idx_2` (`col_1`,`col_4`,`col_76`,`col_3`),
  KEY `idx_3` (`col_4`,`col_76`,`col_3`,`col_2`,`col_1`),
  UNIQUE KEY `idx_4` (`col_76`,`col_3`,`col_1`,`col_4`),
  KEY `idx_5` (`col_3`,`col_4`,`col_76`,`col_2`),
  KEY `idx_6` (`col_2`),
  KEY `idx_7` (`col_76`,`col_3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```
data:
```
mysql> select * from tbl_9;
+----------+------------+--------------------+--------------+
| col_54   | col_55     | col_56             | col_57       |
+----------+------------+--------------------+--------------+
| -5765442 | -597990898 | 384599625723370089 | ZdfkUJiHcOfi |
+----------+------------+--------------------+--------------+
1 row in set (0.00 sec)

mysql> select * from tbl_0;
+----------------+----------+---------------------+------------+------------+----------------------------+
| col_76         | col_1    | col_2               | col_3      | col_4      | col_143                    |
+----------------+----------+---------------------+------------+------------+----------------------------+
| 20041024160000 | 14:50:49 | 2018-08-22 00:00:00 | 2034-07-12 | 1977-08-12 | 0x6C58525458556B546557614A |
| 19890518150000 | 08:03:54 | 2007-11-30 00:00:00 | 1996-04-02 | NULL       | 0x6C58525458556B546557614A |
| 19860222160000 | 21:09:52 | 2000-10-02 00:00:00 | 1974-08-13 | 1974-04-24 | 0x6C58525458556B546557614A |
| 20150628160000 | 04:32:54 | 2000-01-17 00:00:00 | 2024-02-22 | 2028-07-13 | 0x6C58525458556B546557614A |
| 20200804160000 | 16:38:23 | 2000-09-11 00:00:00 | 1989-08-07 | 2032-03-01 | 0x6C58525458556B546557614A |
| 19811111160000 | 01:12:46 | 1974-09-22 00:00:00 | 2020-01-12 | 2004-01-26 | 0x6C58525458556B546557614A |
| 20211205160000 | 19:30:41 | 2005-08-09 00:00:00 | 2031-12-17 | NULL       | 0x6C58525458556B546557614A |
| 20270430160000 | 03:18:03 | 2007-01-05 00:00:00 | 1986-02-24 | 1979-09-24 | 0x6C58525458556B546557614A |
| 20170417160000 | 01:30:55 | 2025-01-04 00:00:00 | 2005-05-10 | 2022-01-15 | 0x6C58525458556B546557614A |
| 20231105160000 | 16:26:44 | 1981-06-05 00:00:00 | 1994-04-28 | 1984-01-22 | 0x6C58525458556B546557614A |
+----------------+----------+---------------------+------------+------------+----------------------------+
10 rows in set (0.01 sec)
```

query
```
( select   col_76,col_1,col_143,col_2 from tbl_0 where tbl_0.col_3 in ( '1985-05-02' , '1970-03-30' , '2011-02-11' , '1976-02-19' ) or tbl_0.col_143 in ( 'I' , 'aRiVigHtdeK' , 'YaNdSUQBhCzMDxZ' , 'FWtSvtrzLjUA' ) or tbl_0.col_1 != '04:01:38.00' or tbl_0.col_2 in ( '1982-08-07' ) and tbl_0.col_76 = 'David'  for update ) union ( select   col_54,col_57,col_55,col_56 from tbl_9 where tbl_9.col_54 != -3118426 or tbl_9.col_57 in ( 'WHdkJ' , 'K' , 'jQuqGpkPq' , 'SQnN' , 'rCD' ) and tbl_9.col_57 in ( 'FlBiopzXU' , 'FtOlINHPZM' ) )
```

### 2. What did you expect to see? (Required)
MySQL
```
+----------------+--------------+----------------------------+---------------------+
| col_76         | col_1        | col_143                    | col_2               |
+----------------+--------------+----------------------------+---------------------+
| 19811112000000 | 01:12:46     | 0x6C58525458556B546557614A | 1974-09-22 00:00:00 |
| 20170418000000 | 01:30:55     | 0x6C58525458556B546557614A | 2025-01-04 00:00:00 |
| 20270501000000 | 03:18:03     | 0x6C58525458556B546557614A | 2007-01-05 00:00:00 |
| 20150629000000 | 04:32:54     | 0x6C58525458556B546557614A | 2000-01-17 00:00:00 |
| 19890519000000 | 08:03:54     | 0x6C58525458556B546557614A | 2007-11-30 00:00:00 |
| 20041025000000 | 14:50:49     | 0x6C58525458556B546557614A | 2018-08-22 00:00:00 |
| 20231106000000 | 16:26:44     | 0x6C58525458556B546557614A | 1981-06-05 00:00:00 |
| 20200805000000 | 16:38:23     | 0x6C58525458556B546557614A | 2000-09-11 00:00:00 |
| 20211206000000 | 19:30:41     | 0x6C58525458556B546557614A | 2005-08-09 00:00:00 |
| 19860223000000 | 21:09:52     | 0x6C58525458556B546557614A | 2000-10-02 00:00:00 |
|       -5765442 | ZdfkUJiHcOfi | 0x2D353937393930383938     | 384599625723370089  |
+----------------+--------------+----------------------------+---------------------+
11 rows in set, 1 warning (0.00 sec)
```
TiDB
```
+----------------+--------------+----------------------------+------------------------------------------+
| col_76         | col_1        | col_143                    | col_2                                    |
+----------------+--------------+----------------------------+------------------------------------------+
| 19860222160000 | 21:09:52     | 0x6C58525458556B546557614A | 0x323030302D31302D30322030303A30303A3030 |
| 20150628160000 | 04:32:54     | 0x6C58525458556B546557614A | 0x323030302D30312D31372030303A30303A3030 |
|              0 | ZdfkUJiHcOfi | 0x2D353937393930383938     | 0x333834353939363235373233333730303839   |
| 20211205160000 | 19:30:41     | 0x6C58525458556B546557614A | 0x323030352D30382D30392030303A30303A3030 |
| 20270430160000 | 03:18:03     | 0x6C58525458556B546557614A | 0x323030372D30312D30352030303A30303A3030 |
| 20170417160000 | 01:30:55     | 0x6C58525458556B546557614A | 0x323032352D30312D30342030303A30303A3030 |
| 20231105160000 | 16:26:44     | 0x6C58525458556B546557614A | 0x313938312D30362D30352030303A30303A3030 |
| 19890518150000 | 08:03:54     | 0x6C58525458556B546557614A | 0x323030372D31312D33302030303A30303A3030 |
| 20200804160000 | 16:38:23     | 0x6C58525458556B546557614A | 0x323030302D30392D31312030303A30303A3030 |
| 20041024160000 | 14:50:49     | 0x6C58525458556B546557614A | 0x323031382D30382D32322030303A30303A3030 |
| 19811111160000 | 01:12:46     | 0x6C58525458556B546557614A | 0x313937342D30392D32322030303A30303A3030 |
+----------------+--------------+----------------------------+------------------------------------------+
11 rows in set, 2 warnings (0.00 sec)

```

### 3. What did you see instead (Required)
1: May the case can be further simplified. From the result, we can see warning as `Truncated incorrect FLOAT value: 'David'`
2: Maybe MySQL's logic for truncate `David` is not consistent with TiDB
3: Besides, the main point may be the `col_2`

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: close #24953 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- fix wrong type when unsigned int value union int value

### CODE REVIEW

**Comment by sylzd** [comment]
It's conflict with the UT `TestUnionAutoSignedCast`. Could I change [the line](https://github.com/pingcap/tidb/blob/master/executor/executor_test.go#L4203):
```go
	tk.MustQuery("select id, i, b, d, dd from t2 union select id, i, b, d, dd from t1 order by id").
		Check(testkit.Rows("1 0 0 0 -1", "2 1 1 1.1 1"))
```

to 

```go
	tk.MustQuery("select id, i, b, d, dd from t2 union select id, i, b, d, dd from t1 order by id").
		Check(testkit.Rows("1 -1 -1 -1.1 -1", "2 1 1 1.1 1"))
```

**Comment by tisonkun** [comment]
@sylzd you can use `/cc @reviewer` to request review.

/cc @XuHuaiyu @ichn-hu

**Comment by tisonkun** [comment]
Also would you setup a link to the correct issue? #24593 is an unrelated PR that closed.

**Comment by sylzd** [comment]
> Also would you setup a link to the correct issue? #24593 is an unrelated PR that closed.

Certainly! I made a mistake,  it's #24953!

**Comment by XuHuaiyu** [comment]
I've test the failed case in MySQL 5.7 and MySQL 8.0

The failed case seems to be a bug in MySQL 5.7.
But it was fixed in MySQL 8.0

**Comment by XuHuaiyu** [comment]
I found a similar MySQL bug issue https://bugs.mysql.com/bug.php?id=95148.
I think we can modify the test result of the test cases if we've confirmed in MySQL8.0

**Comment by sylzd** [comment]
> I found a similar MySQL bug issue https://bugs.mysql.com/bug.php?id=95148.
> I think we can modify the test result of the test cases if we've confirmed in MySQL8.0

So, you mean I can modify like this?

> @XuHuaiyu @ichn-hu
> 
> It's conflict with the UT `TestUnionAutoSignedCast`. Could I change [the line](https://github.com/pingcap/tidb/blob/master/executor/executor_test.go#L4203):
> 
> ```go
> 	tk.MustQuery("select id, i, b, d, dd from t2 union select id, i, b, d, dd from t1 order by id").
> 		Check(testkit.Rows("1 0 0 0 -1", "2 1 1 1.1 1"))
> ```
> 
> to
> 
> ```go
> 	tk.MustQuery("select id, i, b, d, dd from t2 union select id, i, b, d, dd from t1 order by id").
> 		Check(testkit.Rows("1 -1 -1 -1.1 -1", "2 1 1 1.1 1"))
> ```

**Comment by sylzd** [comment]
> I found a similar MySQL bug issue https://bugs.mysql.com/bug.php?id=95148.
> I think we can modify the test result of the test cases if we've confirmed in MySQL8.0

refer to https://bugs.mysql.com/bug.php?id=95148, I changed the line,  PTAL~

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Pull request merged**
