### PR TITLE
expression: fix the issue that incorrect result for query that uses an AND operator on floats

### LINKED ISSUE #15743: Incorrect result for query that uses an AND operator on floats
Consider the following statements:

```sql
CREATE TABLE t0(c0 BOOL);
INSERT INTO t0 VALUES (0);
SELECT * FROM t0 WHERE 1 AND 0.4; -- expected: {0}, actual: {}
```
Unexpectedly, the `SELECT` does not fetch any rows. `1 AND 0.4` should evaluate to `1`, which means that the whole predicate should evaluate to `TRUE`. The negated predicate seems to correctly evaluate to `FALSE`:

```sql
SELECT * FROM t0 WHERE NOT (1 AND 0.4); -- {}
```

I found this bug with the following environment:
```
mysql> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.12
Git Commit Hash: 8c4696b3f3408c61dd7454204ddd67c93501609a
Git Branch: heads/refs/tags/v3.0.12
UTC Build Time: 2020-03-16 09:56:22
GoVersion: go version go1.13 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### LINKED ISSUE #16426: precision problems when handling decimal calculation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
mysql root@127.0.0.1:test> create table t (a int);                                                                                        
mysql root@127.0.0.1:test> insert into t values (42);                                                                                     
mysql root@127.0.0.1:test> select * from t where a / 1000000;                                                                             
```

### 2. What did you expect to see?
```
mysql root@127.0.0.1:test> create table t (a int);                                                                                        
Query OK, 0 rows affected
Time: 0.596s
mysql root@127.0.0.1:test> insert into t values (42);                                                                                     
Query OK, 1 row affected
Time: 0.211s
mysql root@127.0.0.1:test> select * from t where a / 1000000;                                                                             
+----+
| a  |
+----+
| 42 |
+----+
1 row in set
Time: 0.030s
```

### 3. What did you see instead?
```
mysql root@127.0.0.1:test> create table t (a int);                                          
Query OK, 0 rows affected
Time: 0.025s
mysql root@127.0.0.1:test> insert into t values (42);                                       
Query OK, 1 row affected
Time: 0.005s
mysql root@127.0.0.1:test> select * from t where a / 1000000;                               
+---+
| a |
+---+
0 rows in set
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
The latest master branch.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #15743, close #16426 

### What is changed and how it works?

Don't round the value when converting it to `bool`.

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by zz-jason** [comment]
Please fix UT:
```
[2020-03-31T13:24:24.756Z] FAIL: datum_test.go:66: testDatumSuite.TestToBool

[2020-03-31T13:24:24.756Z] 

[2020-03-31T13:24:24.756Z] datum_test.go:70:

[2020-03-31T13:24:24.756Z]     testDatumToBool(c, float32(0.1), 0)

[2020-03-31T13:24:24.756Z] datum_test.go:63:

[2020-03-31T13:24:24.756Z]     c.Assert(b, Equals, res64)

[2020-03-31T13:24:24.756Z] ... obtained int64 = 1

[2020-03-31T13:24:24.756Z] ... expected int64 = 0
```

**Comment by qw4990** [comment]
```
[2020-04-01T11:53:55.438Z] Statement: #839 -  SELECT ATAN( `col_varbinary_32`, ( ROUND( `col_year_key` ) ) ) AS field1, ABS( 8188107072512983040 ) AS field2, - 0 AS field3 FROM `table10_int_autoinc` WHERE LOG( `col_varchar_64_key`, '2033-08-25 07:33:37.038938' ) /* QNO 841 CON_ID 184 */ 
[2020-04-01T11:53:55.438Z] NoPushDown Output: 
[2020-04-01T11:53:55.438Z] field1	field2	field3
[2020-04-01T11:53:55.438Z] 0	8188107072512983040	0
[2020-04-01T11:53:55.438Z] 0	8188107072512983040	0
[2020-04-01T11:53:55.438Z] 0	8188107072512983040	0
[2020-04-01T11:53:55.438Z] 
[2020-04-01T11:53:55.438Z] 
[2020-04-01T11:53:55.438Z] WithPushDown Output: 
[2020-04-01T11:53:55.438Z] field1	field2	fie
[2020-04-01T11:53:55.438Z] 0	8188107072512983040	0
```
It seems that the `coprocessor` also has this problem, could you help me to fix it? @zhongzc

**Comment by zhongzc** [comment]
@qw4990 ok

**Comment by zhongzc** [comment]
Seems there're still issues in TiDB. 
In MySQL 5.7:
```sql
mysql root@127.0.0.1:test> SELECT ATAN( `col_varbinary_32`, ( ROUND( `col_year_key` ) ) ) AS field1, ABS( 8188107072512983040 ) AS field2, - 0 AS field3 FROM `table
                           10_int_autoinc` WHERE LOG( `col_varchar_64_key`, '2033-08-25 07:33:37.038938' ) /* QNO 841 CON_ID 184 */
+--------+---------------------+--------+
| field1 | field2              | field3 |
+--------+---------------------+--------+
| 0.0    | 8188107072512983040 | 0      |
+--------+---------------------+--------+

```

**Comment by qw4990** [comment]
> @qw4990 Seems there're still issues in TiDB.
> In MySQL 5.7:
> 
> ```sql
> mysql root@127.0.0.1:test> SELECT ATAN( `col_varbinary_32`, ( ROUND( `col_year_key` ) ) ) AS field1, ABS( 8188107072512983040 ) AS field2, - 0 AS field3 FROM `table
>                            10_int_autoinc` WHERE LOG( `col_varchar_64_key`, '2033-08-25 07:33:37.038938' ) /* QNO 841 CON_ID 184 */
> +--------+---------------------+--------+
> | field1 | field2              | field3 |
> +--------+---------------------+--------+
> | 0.0    | 8188107072512983040 | 0      |
> +--------+---------------------+--------+
> ```

Yes ... It is fixed in MySQL 8.0: https://bugs.mysql.com/bug.php?id=99120

**Comment by zhongzc** [comment]
type DECIMAL has a similar problem:
```sql
mysql root@127.0.0.1:test> create table t (a decimal(2, 1));
Query OK, 0 rows affected
Time: 0.793s
mysql root@127.0.0.1:test> insert into t values (0.4);
Query OK, 1 row affected
Time: 0.200s
mysql root@127.0.0.1:test> select * from t where a;
+---+
| a |
+---+
```

In MySQL 8.0:
```sql
mysql root@127.0.0.1:test> create table t (a decimal(2, 1));
Query OK, 0 rows affected
Time: 0.518s
mysql root@127.0.0.1:test> insert into t values (0.4);
Query OK, 1 row affected
Time: 0.121s
mysql root@127.0.0.1:test> select * from t where a;
+-----+
| a   |
+-----+
| 0.4 |
+-----+
```

**Comment by qw4990** [comment]
> type DECIMAL has a similar problem:
> 
> ```sql
> mysql root@127.0.0.1:test> create table t (a decimal(2, 1));
> Query OK, 0 rows affected
> Time: 0.793s
> mysql root@127.0.0.1:test> insert into t values (0.4);
> Query OK, 1 row affected
> Time: 0.200s
> mysql root@127.0.0.1:test> select * from t where a;
> +---+
> | a |
> +---+
> ```
> 
> In MySQL 8.0:
> 
> ```sql
> mysql root@127.0.0.1:test> create table t (a decimal(2, 1));
> Query OK, 0 rows affected
> Time: 0.518s
> mysql root@127.0.0.1:test> insert into t values (0.4);
> Query OK, 1 row affected
> Time: 0.121s
> mysql root@127.0.0.1:test> select * from t where a;
> +-----+
> | a   |
> +-----+
> | 0.4 |
> +-----+
> ```

It's another problem in TiDB? @zhongzc

**Comment by zhongzc** [comment]
@qw4990 Sorry for the inappropriate example.
TiDB doesn't handle decimal calculations well. Here's a more accurate example:

In TiDB (with tidb pr/15927):
```sql
mysql root@127.0.0.1:test> create table t (a int);                                          
Query OK, 0 rows affected
Time: 0.025s
mysql root@127.0.0.1:test> insert into t values (42);                                       
Query OK, 1 row affected
Time: 0.005s
mysql root@127.0.0.1:test> select * from t where a / 1000000;                               
+---+
| a |
+---+
0 rows in set
```

In TiKV (with tidb pr/15927 and tikv pr/7342) and MySQL 8.0:
```sql
mysql root@127.0.0.1:test> create table t (a int);                                                                                        
Query OK, 0 rows affected
Time: 0.596s
mysql root@127.0.0.1:test> insert into t values (42);                                                                                     
Query OK, 1 row affected
Time: 0.211s
mysql root@127.0.0.1:test> select * from t where a / 1000000;                                                                             
+----+
| a  |
+----+
| 42 |
+----+
1 row in set
Time: 0.030s
```

**Comment by qw4990** [comment]
> @qw4990 Sorry for the inappropriate example.
> TiDB doesn't handle decimal calculations well. Here's a more accurate example:
> 
> In TiDB (with tidb pr/15927):
> 
> ```sql
> mysql root@127.0.0.1:test> create table t (a int);                                          
> Query OK, 0 rows affected
> Time: 0.025s
> mysql root@127.0.0.1:test> insert into t values (42);                                       
> Query OK, 1 row affected
> Time: 0.005s
> mysql root@127.0.0.1:test> select * from t where a / 1000000;                               
> +---+
> | a |
> +---+
> 0 rows in set
> ```
> 
> In TiKV (with tidb pr/15927 and tikv pr/7342) and MySQL 8.0:
> 
> ```sql
> mysql root@127.0.0.1:test> create table t (a int);                                                                                        
> Query OK, 0 rows affected
> Time: 0.596s
> mysql root@127.0.0.1:test> insert into t values (42);                                                                                     
> Query OK, 1 row affected
> Time: 0.211s
> mysql root@127.0.0.1:test> select * from t where a / 1000000;                                                                             
> +----+
> | a  |
> +----+
> | 42 |
> +----+
> 1 row in set
> Time: 0.030s
> ```

This is a new problem and I created a new issue for it(https://github.com/pingcap/tidb/issues/16426).
I will fix this new problem soon after merging this PR.

**Comment by qw4990** [comment]
Wait for https://github.com/tikv/tikv/pull/7342.

**Pull request merged**
