### PR TITLE
cop: cop request should contains  buckets version

### LINKED ISSUE #46557: cop request should add the current bucket version

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: close #46557
ref: https://github.com/tikv/client-go/pull/918

Problem Summary:

### Check List

Tests 

- [ ] Manual test (add detailed scripts or steps below)
image

Side effects

Documentation

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

**Comment by rleungx** [comment]
CI failed @bufferflies

**Review by crazycs520 — APPROVED** [review]

**Comment by hawkingrei** [comment]
> [CLA assistant check](https://cla.pingcap.net/pingcap/tidb?pullRequest=46446) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.pingcap.net/pingcap/tidb?pullRequest=46446) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.pingcap.net/check/pingcap/tidb?pullRequest=46446) it.

Please sign the CLA.

**Pull request merged**
