### PR TITLE
*: move package context to sessionctx

### PR DESCRIPTION
**Pull request by tiancaiamao**
The github.com/pingcap/tidb/context package name confused us with
standard context package, so rename it to sessionctx.

@coocood @winkyao @shenli

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
/run-integration-common-test tidb-test=pr/464 tidb-private-test=pr/6

**Comment by tiancaiamao** [comment]
Now all test pass.
@coocood  @zz-jason  PTAL, also
tidb-test https://github.com/pingcap/tidb-test/pull/464
tidb-private-test https://github.com/pingcap/tidb-private-test/pull/6

**Pull request merged**
