### PR TITLE
executor: fix a bug when apply meets index join

### PR DESCRIPTION
**Pull request by hanfei1991**
correct the `Open` and `Close` function

### CODE REVIEW

**Comment by zz-jason** [comment]
I think a better way is to rewrite ApplyExec to not re-open and re-close a same child. @tiancaiamao PTAL

**Comment by zz-jason** [comment]
related to this issue: https://github.com/pingcap/tidb/issues/4983

**Comment by coocood** [comment]
We should rebuild a new executor every time.

**Comment by hanfei1991** [comment]
This is a temprory bug fix which apprears in #5378 . Better changes will be done in the future.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
