### PR TITLE
ddl, ci: force domain to reload schema before execute SQL. (#19580)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19580 to release-4.0

---

### What problem does this PR solve?

Issue Number: #19481 #19480 #19479 

Problem Summary:

DDL test may fail on high CPU load. After do some test, we found that golang's timer will generate a huge bias on high CPU load. So we need to force call `Domain.Reload()` manually.

### What is changed and how it works?

What's Changed:

Add `Domain.Reload()` function call on failed cases.

### Related changes

- No changes

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- No

### Release note 

- ddl: make CI test more stable.

### CODE REVIEW

**Comment by blacktear23** [comment]
@bb7133 @wjhuang2016 PTAL

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Comment by bb7133** [comment]
LGTM

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
