### PR TITLE
tablecodec: fix text type decode for old row format

### LINKED ISSUE #23708: admin check failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
[log6.sql.zip](https://github.com/pingcap/tidb/files/6229316/log6.sql.zip)
source sql.6;
admin check table tbl_2;

### 2. What did you expect to see? (Required)
No error.
### 3. What did you see instead (Required)
```
mysql> admin check table tbl_2;
ERROR 1105 (HY000): handle 13, index:types.Datum{k:0x5, decimal:0x0, length:0x0, i:0, collation:"binary", b:[]uint8{0x6c, 0x77}, x:interface {}(nil)} != record:<nil>
```
### 4. What is your TiDB version? (Required)
master, fresh build.

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #23708 

Problem Summary:
Didn't set collation. It's the patch for https://github.com/pingcap/tidb/pull/23045

### What is changed and how it works?

Set collation for unflaten.
### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test
  Star a tiup cluster, and do the operations as the issue says.
  admin check table, no error.

### Release note 

- fix text type decode for old row format

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by AilinKid — COMMENTED** [review]
/lgtm

**Comment by lysu** [comment]
https://github.com/pingcap/ticdc/blob/4301513218dd7cec91ff1f214e1ba79d7c0ed590/cdc/entry/codec.go#L273-L278

@leoppro @wjhuang2016 does this unflatten need to change too?

**Comment by zimulala** [comment]
@wjhuang2016 Please address comments

**Pull request merged**
