### PR TITLE
planner/core: migrate  test-infra to testify for `cache_test.go`

### LINKED ISSUE #28386: migrate test-infra to testify for `planner/core/cache_test.go`

### PR DESCRIPTION
**Pull request by karuppiah7890**
### What problem does this PR solve?

Issue Number: close #28386

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

### Check List 

Tests

- [x] Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM. Good job!

**Review by Reminiscent — APPROVED** [review]

**Pull request merged**
