### PR TITLE
table:fix desc table not compatibile with MySQL

### PR DESCRIPTION
**Pull request by b41sh**
### What problem does this PR solve? 

Fix desc table not compatible with MySQL. [#9983](https://github.com/pingcap/tidb/issues/9983) 

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by xiekeyi98** [comment]
I will help you to fix the test.

**Comment by b41sh** [comment]
thank you @xiekeyi98

**Comment by erjiaqing** [comment]
LGTM

**Pull request merged**
