### PR TITLE
br: split br and lightning tests in pipelines

### PR DESCRIPTION
**Pull request by purelind**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/48955

Problem Summary: Support running test cases for  br and lightning in different pipelines.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [x] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by purelind** [comment]
> @purelind: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-br-integration-test	[79deea2](https://github.com/pingcap/tidb/commit/79deea2cb0359e048f5f0e62e24d3cc49fd2286e)	[link](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/pull_br_integration_test/527/display/redirect)	false	`/test pull-br-integration-test`
> wip/pull-lightning-integration-test	[79deea2](https://github.com/pingcap/tidb/commit/79deea2cb0359e048f5f0e62e24d3cc49fd2286e)	[link](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/pull_lightning_integration_test/4/display/redirect)	false	`/test pull-lightning-integration-test`
> [Full PR test history](https://prow.tidb.net/pr-history?org=pingcap&repo=tidb&pr=48921). [Your PR dashboard](https://prow.tidb.net/pr?query=is%3Apr%20state%3Aopen%20author%3Apurelind).

repaly test with updated br pipeline  https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_br_integration_test/detail/pull_br_integration_test/528/pipeline/

https://github.com/PingCAP-QE/ci/pull/2633 The changes to the br pipeline will be merged after the current PR is merged.

**Comment by purelind** [comment]
> link

test `lightning_write_limit` in pull-lightning-integration-test seems to be a problem that needs fixing
image

**Comment by lance6716** [comment]
> > @purelind: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name	Commit	Details	Required	Rerun command
> > pull-br-integration-test	[79deea2](https://github.com/pingcap/tidb/commit/79deea2cb0359e048f5f0e62e24d3cc49fd2286e)	[link](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/pull_br_integration_test/527/display/redirect)	false	`/test pull-br-integration-test`
> > wip/pull-lightning-integration-test	[79deea2](https://github.com/pingcap/tidb/commit/79deea2cb0359e048f5f0e62e24d3cc49fd2286e)	[link](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/pull_lightning_integration_test/4/display/redirect)	false	`/test pull-lightning-integration-test`
> > [Full PR test history](https://prow.tidb.net/pr-history?org=pingcap&repo=tidb&pr=48921). [Your PR dashboard](https://prow.tidb.net/pr?query=is%3Apr%20state%3Aopen%20author%3Apurelind).
> 
> repaly test with updated br pipeline https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_br_integration_test/detail/pull_br_integration_test/528/pipeline/
> 
> [PingCAP-QE/ci#2633](https://github.com/PingCAP-QE/ci/pull/2633) The changes to the br pipeline will be merged after the current PR is merged.

I didn't see the new filename run_group_lightning_tests.sh in QE repo, how did CI trigger it?

**Comment by lance6716** [comment]
> > link
> 
> test `lightning_write_limit` in pull-lightning-integration-test seems to be a problem that needs fixing image

Can you help to fix the problem in this PR? I guess it's caused by upgrading dependency packages some times ago.

```diff
diff --git a/br/tests/lightning_write_limit/config.toml b/br/tests/lightning_write_limit/config.toml
index e45e694126..b56a6fce47 100644
--- a/br/tests/lightning_write_limit/config.toml
+++ b/br/tests/lightning_write_limit/config.toml
@@ -1,5 +1,5 @@
 [tikv-importer]
-store-write-bwlimit = "1Mi"
+store-write-bwlimit = "1MiB"

 [mydumper.csv]
 header = false
```

**Review by D3Hunter — APPROVED** [review]

**Comment by purelind** [comment]
> repaly test with updated br pipeline https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_br_integration_test/detail/pull_br_integration_test/528/pipeline/
> 
> [PingCAP-QE/ci#2633](https://github.com/PingCAP-QE/ci/pull/2633) The changes to the br pipeline will be merged after the current PR is merged.

repaly test with updated br pipeline https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_br_integration_test/detail/pull_br_integration_test/528/pipeline/

https://github.com/PingCAP-QE/ci/pull/2633 The changes to the br pipeline will be merged after the current PR is merged.

**Comment by purelind** [comment]
> /test pull-br-integration-test

repaly test with updated br pipeline https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_br_integration_test/detail/pull_br_integration_test/528/pipeline/

https://github.com/PingCAP-QE/ci/pull/2633 The changes to the br pipeline will be merged after the current PR is merged.

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
