### PR TITLE
*: Refine error message about "Out of range value for column" (#6334)

### PR DESCRIPTION
**Pull request by zz-jason**
cherry pick #6334 to release 2.0

### CODE REVIEW

**Comment by iamxy** [comment]
build failed.

```
make[1]: Leaving directory `/home/jenkins/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb'

GOPATH=/home/jenkins/workspace/tidb_ghpr_build/go:/go CGO_ENABLED=1 go build -race -ldflags '-X "github.com/pingcap/tidb/mysql.TiDBReleaseVersion=v2.0.0-16-gd3c37ec" -X "github.com/pingcap/tidb/util/printer.TiDBBuildTS=2018-05-10 04:18:24" -X "github.com/pingcap/tidb/util/printer.TiDBGitHash=d3c37eca8841b4702b23c3826440bb2495aaa1d4" -X "github.com/pingcap/tidb/util/printer.TiDBGitBranch=HEAD" -X "github.com/pingcap/tidb/util/printer.GoVersion=go version go1.10.2 linux/amd64"' -o bin/tidb-server tidb-server/main.go

# github.com/pingcap/tidb/executor

executor/write.go:1461:20: not enough arguments in call to e.filterErr

	have (error)

	want (error, bool)

make: *** [server] Error 2

script returned exit code 2
```

**Comment by XuHuaiyu** [comment]
https://github.com/pingcap/tidb-test/pull/512 should be cherry-pick to tidb-test release2.0? @zz-jason

**Comment by zz-jason** [comment]
@XuHuaiyu PTAL

**Comment by shenli** [comment]
LGTM
Please remind to cherry-pick corresponding PR to the test repo.

**Pull request merged**
