### PR TITLE
Privileges: fix delete privilege check wrongly (#22971)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #22971 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23215
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23215:release-4.0-2a909bf2f1c6
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/22946

Problem Summary:

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

- fix the delete stmt privilege check.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @winoros

**Review by winoros — APPROVED** [review]

**Pull request merged**
