### PR TITLE
planner: add more rand-gen test cases for the new cost implementation

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: ref #33945

Problem Summary: planner: add more rand-gen test cases for the new cost implementation

### What is changed and how it works?
planner: add more rand-gen test cases for the new cost implementation

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xuyifangreeneyes — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]

**Comment by hawkingrei** [comment]
@qw4990 You need to update mysql-test case to fix it.

**Comment by qw4990** [comment]
> @qw4990 You need to update mysql-test case to fix it.

OK, I'll fix it soon.

**Pull request merged**
