### PR TITLE
planner: check filter condition in func convertToPartialTableScan

### LINKED ISSUE #25045: can't find column while use index merge
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create table t1(a int primary key, b int, c int, key(b), key(c));
explain select /*+ use_index_merge(t1) */ * from t1 where c=10 or (b=10 and a=10);
```

### 2. What did you expect to see? (Required)
execute successfully 
### 3. What did you see instead (Required)
```sql
MySQL root@127.0.0.1:test> explain select /*+ use_index_merge(t1) */ * from t1 where c=10 or (b=10 and a=10);
(1105, "Can't find column test.t1.b in schema Column: [test.t1.a] Unique key: []")
```
### 4. What is your TiDB version? (Required)
```sql
MySQL root@127.0.0.1:test> select tidb_version()\G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v5.1.0-alpha-87-g0158f71cd
Edition: Community
Git Commit Hash: 0158f71cda6ccbbd382c6e8759904234baca259c
Git Branch: HEAD
UTC Build Time: 2021-06-01 11:51:39
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by zhuo-zhi**
### What problem does this PR solve?

Issue Number: close #25045 

Problem Summary:

Cannot find column while use index merge

### What is changed and how it works?

What's Changed:

- Change logic in func convertToPartialTableScan.

How it Works:

- Remove ineffective filter conditions in func `convertToPartialTableScan` to prevent use column out of the schema of `PhysicalTableScan`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- N/A

### Release note 

- planner: check filter condition in func convertToPartialTableScan

### CODE REVIEW

**Review by rebelice — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Review by rebelice — APPROVED** [review]

**Comment by zhuo-zhi** [comment]
needs-cherry-pick-5.0

**Pull request merged**
