### PR TITLE
vendor: remove gogo protobuf and update tipb again

### PR DESCRIPTION
**Pull request by zhexuany**
Thank you for working on TiDB! Please read TiDB's [CONTRIBUTING](https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md) document **BEFORE** filing this PR.

## What have you changed? (mandatory)
When I tried to generate tipb's side code, I use latest `gogo` protobuf. However, as required, we have to use `v0.5`. Last PR only regenerates `go-tipb` and leaves `go-binlog` and `go-mysqlx` untouched. This PR is trying to fix irrelevant code brought by last PR #6825 

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:
- Summarize your change (mandatory)
       * update tipb in vendor 
```
dep ensure -update GitHub.com/pingcap/tipb
./hack/clean-vendor.sh
```

## How has this PR been tested (mandatory)?
no need to test

### CODE REVIEW

**Comment by shenli** [comment]
Please fix the CI.

**Comment by zhexuany** [comment]
@coocood @jackysp PTAL ;)

**Comment by coocood** [comment]
LGTM

**Pull request merged**
