### PR TITLE
bootstrap: modify `variable_value` column to `varchar(16383)`

### LINKED ISSUE #48029: Data too long when setting @@tidb_cloud_storage_uri
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Previously, global variable value cannot have more than 1024 characters:
```
mysql> desc mysql.global_variables;
+----------------+---------------+------+------+---------+-------+
| Field          | Type          | Null | Key  | Default | Extra |
+----------------+---------------+------+------+---------+-------+
| VARIABLE_NAME  | varchar(64)   | NO   | PRI  | NULL    |       |
| VARIABLE_VALUE | varchar(1024) | YES  |      | NULL    |       |
+----------------+---------------+------+------+---------+-------+
2 rows in set (0.00 sec)
```

However, S3 URI is easy to exceed 1024 if it consists of multiple query parameters.

### 2. What did you expect to see? (Required)

No error.

### 3. What did you see instead (Required)

```
ERROR 1406 (22001): Data too long for column 'VARIABLE_VALUE' at row 1; 
```

### 4. What is your TiDB version? (Required)

9224f62ef8

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #48029

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zimulala — APPROVED** [review]
LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Review by zimulala — CHANGES_REQUESTED** [review]
Do we need to update `CreateGlobalVariablesTable` too?

**Review by zimulala — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]

**Pull request merged**
