### PR TITLE
build-in: add truncate build-in function

### PR DESCRIPTION
**Pull request by keviswang**

### CODE REVIEW

**Comment by coocood** [comment]
@keviswang 

This function returns different types, it can be int,  decimal or double.
Please take a look at how `round` function is implemented and type inferred.

**Comment by shenli** [comment]
@keviswang Any update?
Please resolve the conflicts.

**Comment by XuHuaiyu** [comment]
@keviswang
hi, any updates?

**Comment by coocood** [comment]
@keviswang 
I'm sorry, this function has been implemented already.

**Pull request closed without merging**
