### PR TITLE
executor: sort handles for double read.

### PR DESCRIPTION
**Pull request by hanfei1991**
we should sort handles for double read after scanning index first time.

### CODE REVIEW

**Comment by winoros** [comment]
Any tests can cover this?

**Comment by hanfei1991** [comment]
@winoros test is hard to add. This problem only happens for multi regions.

**Comment by winoros** [comment]
Okay LGTM

**Comment by ngaut** [comment]
There are mock interfaces, please figure out a test.

**Comment by shenli** [comment]
LGTM

**Pull request merged**
