### PR TITLE
cherry-pick-8.1: br: fix insert gc failed due to slow schema reload (#57742)

### PR DESCRIPTION
**Pull request by Tristan1900**
close pingcap/tidb#57743

(cherry picked from commit 8fe061897e804a3127974d96faa6a0d57ce4cb1b)

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by BornChanger — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]

**Review by lance6716 — COMMENTED** [review]
/approve

for domain part

**Comment by Tristan1900** [comment]
same tests failing on 8.1 already for some reason, not introduced in this PR

**Pull request merged**
