### PR TITLE
variable: move some of global definations to consts

### LINKED ISSUE #37089: variable: move some of global definations to const
## Enhancement

See description PR in #37088

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #37089

### What is changed and how it works?

- Make some global variables t to const definitions  to achieve better readability.
- Removed useless global variable `DefTiDBDDLEnableFastReorg`
- Renamed `ddlErrorCountlimit` => `ddlErrorCountLimit`

### Check List

Tests 

- [x] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]

**Comment by hawkingrei** [comment]
@lcwangchao Can you help me update the bazel config by gazelle ?

/hold

**Pull request merged**
