### PR TITLE
sessionctx/variable: fix incorrect parallel tests

### LINKED ISSUE #27979: session_test.go has incorrect parallel tests cause data race
this parallel may cause `fatal error: concurrent map writes`, because `variable.SetSessionSystemVar` will write variable to `SessionVars.systems`.   PTAL @penthaapatel @tisonkun @morgo

_Originally posted by @xiongjiwei in https://github.com/pingcap/tidb/pull/27848#discussion_r707003622_

### PR DESCRIPTION
**Pull request by tisonkun**
### What problem does this PR solve?

Issue Number: close #27979 

Problem Summary: details in the issue.

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
/cc @xiongjiwei

PTAL for following up https://github.com/pingcap/tidb/pull/27848#discussion_r707003622

**Review by xiongjiwei — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

**Comment by tisonkun** [comment]
@cfzjywxk I just learn that you should remove "do-not-merge" label manually to proceed the PR.

**Comment by tisonkun** [comment]
@Mini256 please take a look at this issue. I'm afraid we're blocked for any changes on sessionctx/variable. It is weird that after a config reviewer ( @cfzjywxk ) review or remove the label, it is still there.

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
