### PR TITLE
util/ranger: fix incorrect behavior about index who has prefix column(#8851)

### PR DESCRIPTION
**Pull request by winoros**
cherry-pick #8851 to release-2.0 branch

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8877)

### CODE REVIEW

**Comment by zz-jason** [comment]
LGTM
/run-all-tests

**Comment by zz-jason** [comment]
/run-all-test tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by eurekaka** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by zz-jason** [comment]
/run-unit-test tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by winoros** [comment]
/run-all-tests tikv=release-2.0 tidb-test=release-2.0 pd=release-2.0 gofail=etcd-io

**Pull request merged**
