### PR TITLE
[DNM]parser: store sql in parser and move offset related method

### PR DESCRIPTION
**Pull request by tiancaiamao**
clean up code for rewriting lexer
See https://github.com/pingcap/tidb/issues/1490

after this and several previous PRs, there should be no `(*lex)` in parser.y any more

### CODE REVIEW

**Comment by shenli** [comment]
CI failed.

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@coocood PTAL

**Comment by coocood** [comment]
LGTM

**Pull request merged**
