### PR TITLE
ddl: skip race test for Tests that change global config

### PR DESCRIPTION
**Pull request by coocood**
### What problem does this PR solve? 
Race test fails frequently on `TestTreatOldVersionUTF8AsUTF8MB4` because it write global config field `TreatOldVersionUTF8AsUTF8MB4 ` and it is read by a background goroutine.

### What is changed and how it works?
Skip the test when race is enabled.

### Check List 

Tests 
 - No code

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Maybe you forgets to commit this package:
github.com/pingcap/tidb/util/israce

@coocood

**Comment by coocood** [comment]
@tiancaiamao 
It's not a new package

**Comment by coocood** [comment]
@crazycs520 PTAL

**Comment by coocood** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
