### PR TITLE
ddl, test: delete unstable code that cause test failed in ddl

### LINKED ISSUE #18194: TestLockTables Failed.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

----------------------------------------------------------------------
```
FAIL: db_test.go:4261: testDBSuite2.TestLockTables

db_test.go:4373:
    c.Assert(terror.ErrorEqual(err, infoschema.ErrTableLocked), IsTrue, Commentf("err: %v\n", err))
... obtained bool = false
... err: previous statement: insert into t1 set a=1: [domain:8028]Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]


db_test.go:4373:
    c.Assert(terror.ErrorEqual(err, infoschema.ErrTableLocked), IsTrue, Commentf("err: %v\n", err))
/Users/bba/pc/tidb/util/testkit/testkit.go:207:
    tk.c.Assert(err, check.IsNil, check.Commentf("sql:%s, %v, error stack %v", sql, args, errors.ErrorStack(err)))
... value *errors.withStack = [schema:8020]Table 't1' was locked in WRITE by server: 1aae4613-cbd4-4872-9cf0-6f9dd007e4c7_session: 119 ("[schema:8020]Table 't1' was locked in WRITE by server: 1aae4613-cbd4-4872-9cf0-6f9dd007e4c7_session: 119")
... sql:drop table if exists t1,t2, [], error stack [schema:8020]Table 't1' was locked in WRITE by server: 1aae4613-cbd4-4872-9cf0-6f9dd007e4c7_session: 119
github.com/pingcap/errors.AddStack
        /Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/errors.go:174
github.com/pingcap/parser/terror.(*Error).GenWithStackByArgs
        /Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/parser@v0.0.0-20200609110328-c65941b9fbb3/terror/terror.go:243
github.com/pingcap/tidb/lock.(*Checker).CheckTableLock
        /Users/bba/pc/tidb/lock/lock.go:90
github.com/pingcap/tidb/planner/core.CheckTableLock
        /Users/bba/pc/tidb/planner/core/optimizer.go:114
github.com/pingcap/tidb/planner.optimize
        /Users/bba/pc/tidb/planner/optimize.go:176
github.com/pingcap/tidb/planner.Optimize
        /Users/bba/pc/tidb/planner/optimize.go:64
github.com/pingcap/tidb/executor.(*Compiler).Compile
        /Users/bba/pc/tidb/executor/compiler.go:62
github.com/pingcap/tidb/session.(*session).ExecuteStmt
        /Users/bba/pc/tidb/session/session.go:1144
github.com/pingcap/tidb/util/testkit.(*TestKit).Exec
        /Users/bba/pc/tidb/util/testkit/testkit.go:160
github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec
        /Users/bba/pc/tidb/util/testkit/testkit.go:206
runtime.Goexit
        /Users/bba/.gvm/gos/go1.13/src/runtime/panic.go:563
github.com/pingcap/check.(*C).stopNow
        /Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:108
github.com/pingcap/check.(*C).Assert
        /Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/helpers.go:179
github.com/pingcap/tidb/ddl_test.(*testDBSuite2).TestLockTables
        /Users/bba/pc/tidb/ddl/db_test.go:4373
reflect.Value.call
        /Users/bba/.gvm/gos/go1.13/src/reflect/value.go:460
reflect.Value.Call
        /Users/bba/.gvm/gos/go1.13/src/reflect/value.go:321
github.com/pingcap/check.(*suiteRunner).forkTest.func1
        /Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850
github.com/pingcap/check.(*suiteRunner).forkCall.func1
        /Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739
runtime.goexit
        /Users/bba/.gvm/gos/go1.13/src/runtime/asm_amd64.s:1357

[2020/06/24 00:02:33.522 +08:00] [INFO] [split_region.go:205] ["split regions complete"] ["region count"=1] ["region IDs"="[916]"]
[2020/06/24 00:02:33.522 +08:00] [INFO] [index.go:1240] ["[ddl] split table range from PD"] [physicalTableID=186] [startHandle=1] [endHandle=2]
[2020/06/24 00:02:33.523 +08:00] [INFO] [session.go:2218] ["CRUCIAL OPERATION"] [conn=0] [schemaVersion=245] [cur_db=test_db_state] [sql="create table t(a int, b int, c int, d int auto_increment,e int, index idx1(d), index idx2(d,e))"] [user=]
```

### 5. Root Cause Analysis
Caused by disabling retry in TestCommitWhenSchemaChange
image

### PR DESCRIPTION
**Pull request by zhaox1n**
### What problem does this PR solve?

Issue Number: close #18194

Problem Summary:
`atomic.StoreUint32(&session.SchemaChangedWithoutRetry, 1)`  cause test unstable in ddl

### What is changed and how it works?

change `TestCommitWhenSchemaChange` to `testIntegrationSuite7`

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Comment by zhaox1n** [comment]
> I think it's better to change `testIntegrationSuite3` to `testIntegrationSuite7`. Because `testIntegrationSuite7` is `SerialSuites`, it will not affect other test.

Done

**Comment by wjhuang2016** [comment]
> How can you confirm that the issue of #18194 is caused by the setting of "SchemaChangedWithoutRetry"?

According to the log near TestLockTables

**Comment by zhaox1n** [comment]
> How can you confirm that the issue of #18194 is caused by the setting of "SchemaChangedWithoutRetry"?

I just add  `sleep` behind the `atomic.StoreUint32(&session.SchemaChangedWithoutRetry, 1)  `, It can reproduce the problem, which could show the potential risk.

**Pull request merged**
