### PR TITLE
infoschema/slow_query: fix token too long (#10328)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
Cherry-pick #10328

### CODE REVIEW

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by eurekaka** [comment]
@crazycs520 CI failed.

**Pull request merged**
