### PR TITLE
executor: enhance global index

### LINKED ISSUE #21732: query partition table with global unique index get wrong result
## Development Task

Related issue: https://github.com/pingcap/tidb/issues/18032

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

TiDB config:

```toml
enable-global-index=true
```

```sql
create table t (a int, b int GENERATED ALWAYS AS (3*a-2*a) VIRTUAL) partition by hash(b) partitions 2;
alter table t add unique index idx (a);
insert into t (a) values  (1),(2),(3);
select * from t ignore index (idx);
select * from t use index (idx);
```

### 2. What did you expect to see? (Required)

```sql
test> select * from t use index (idx);
+---+---+
| a | b |
+---+---+
| 2 | 2 |
| 1 | 1 |
| 3 | 3 |
+---+---+
```

### 3. What did you see instead (Required)

```sql
test> select * from t use index (idx);
+---+---+
| a | b |
+---+---+
0 rows in set
Time: 0.014s
```

### 4. What is your TiDB version? (Required)

```sql
test> select tidb_version();
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1812-gd33b81b1e                    |
| Edition: Community                                                |
| Git Commit Hash: d33b81b1ee69bd60a56e45f87774e76014720a6e         |
| Git Branch: master                                                |
| UTC Build Time: 2020-12-14 12:59:19                               |
| GoVersion: go1.14.4                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### LINKED ISSUE #40149: executor: when enable global index on partition table, the executor return unique index not wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
1. enable global index

tidb.toml:
enable-global-index = true

2. create test_t1
mysql> CREATE TABLE `test_t1` (
  `a` int(11) NOT NULL,
  `b` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY RANGE (`c`)
(PARTITION `p0` VALUES LESS THAN (10),
 PARTITION `p1` VALUES LESS THAN (MAXVALUE));
Query OK, 0 rows affected (0.12 sec)

3. add a unique index on column a


mysql> alter table test_t1 add unique  p_a (a);     
Query OK, 0 rows affected (2.92 sec)


4. insert a record

mysql> insert into test_t1 values (1,1,1);       
Query OK, 1 row affected (0.00 sec)

5. select the value, but no return

mysql> select * from test_t1 where a = 1; 
Empty set, 1 warning (0.00 sec)

mysql> explain select * from test_t1 where a = 1;
+--------------------+---------+------+-------------------------------------------+---------------+
| id                 | estRows | task | access object                             | operator info |
+--------------------+---------+------+-------------------------------------------+---------------+
| PartitionUnion_9   | 1.00    | root |                                           |               |
| ├─Point_Get_10     | 1.00    | root | table:test_t1, partition:p0, index:p_a(a) |               |
| └─Point_Get_11     | 1.00    | root | table:test_t1, partition:p1, index:p_a(a) |               |
+--------------------+---------+------+-------------------------------------------+---------------+
3 rows in set, 1 warning (0.00 sec)

```

### LINKED ISSUE #40497: global index: specify the table partition, but return all partitions' rows
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
  drop table if exists p;
  create table p (id int, c int) partition by range (c) (
       partition p0 values less than (4),
       partition p1 values less than (7),
       partition p2 values less than (10));
  alter table p add unique idx(id);
  insert into p values (1,3), (3,4), (5,6), (7,9);
  select * from p partition(p0) use index (idx);
```
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
when execturing the query: select * from p partition(p0) use index (idx) 
the result should be: "1 3"
### 3. What did you see instead (Required)
[”1 3“， ”3 4“， ”5 6“, "7 9"]
### 4. What is your TiDB version? (Required)
version: release-5.0

<!-- Paste the output of SELECT tidb_version() -->
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                                  |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.0.0-414-g6ca79c09c3-dirty
Edition: Community
Git Commit Hash: 6ca79c09c34ecbda1a49a961c049b477eb8f6a65
UTC Build Time: 2023-01-10 08:47:50
GoVersion: go1.16.10
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.77 sec)

### PR DESCRIPTION
**Pull request by L-maple**
…tition

### What problem does this PR solve?

Issue Number: close #40497 
Issue Number: close #21732
Issue Number: close #40149

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by L-maple** [comment]
cc @mjonss @tiancaiamao

**Comment by bb7133** [comment]
@L-maple Hi~ Is there any reason you closed this PR?

**Comment by L-maple** [comment]
> @L-maple Hi~ Is there any reason you closed this PR?

I propose a new PR, which has a better branch name. See here: https://github.com/pingcap/tidb/pull/41197?w=1 . I cc you in this new PR and please help me review the code.

**Pull request closed without merging**
