### PR TITLE
domain: refine error code for package domain

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve? 
Not all the errors in `domain` package have error code.

### What is changed and how it works?
Add them. Related to https://github.com/pingcap/parser/pull/595.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported variable/fields change

Side effects

 - Breaking backward compatibility

### CODE REVIEW

**Comment by bb7133** [comment]
Close this PR temporarily because of PR quota

**Comment by bb7133** [comment]
> `runTestErrorCode` test failed in CI. This PR changes the error code, I think we need to change `ErrUnknown` to `ErrInfoSchemaExpired ` in `runTestErrorCode`.

Addressed, thanks

**Comment by bb7133** [comment]
PTAL @zimulala

**Comment by jackysp** [comment]
I think it should wait for some PRs which are trying to fix CI.

**Pull request merged**
