### PR TITLE
parser: use utf-8 charset to decode enum binary string literal

### LINKED ISSUE #30740: index out of range when create gbk charset enum column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(a enum('a', 0x91) charset gbk);
```

### 2. What did you expect to see? (Required)

`no panic`

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #30740, a patch for #31231

Problem Summary:

After #31231, specifying GBK charset on table still causes panic:

```sql
mysql> create table t (a enum(0x91)) charset gbk;
ERROR 1105 (HY000): runtime error: index out of range [1] with length 1
```

The problem still exists because the decoding procedure in #31231 only applicable when the column charset is specified. After the investigation, I found that  it is not possible to get the "environment" charset during parsing. So we cannot decode the binary literal strings before storing them into `FieldType`.

On the other hand, it involves a lot of changes if we decode before reading them. The `FieldType.Elem` needs to know which string is a binary literal.

### What is changed and how it works?

Finally I decide to always use utf-8 to validate the binary literal. This is incompatible with MySQL on other charset like GBK, and it will be one of the limitation that we need to document.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by tangenta** [comment]
This PR will be cherry-pick to v5.4 along with #31231.

**Pull request merged**
