### PR TITLE
*:Revert "txn, session: Add (cluster_)trx_summary table (#28835)" on release-6.2

### PR DESCRIPTION
**Pull request by longfangsong**
This reverts commit df9b54bcb31f2c356e70b5d901f4b44192855fa3.

### What problem does this PR solve?

Problem Summary: ref #34457

This pr belongs to a large, unfinished project. It should not be released with version 6.2.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by ekexium — APPROVED** [review]
I believe it's a common issue that is not supposed to be solved by manually reverting every WIP feature.

**Comment by cfzjywxk** [comment]
@longfangsong 
Does this partial pr affect some other features so we need to revert?

**Comment by longfangsong** [comment]
> @longfangsong Does this partial pr affect some other features so we need to revert?

No, just this one.

**Review by cfzjywxk — APPROVED** [review]

**Comment by VelocityLight** [comment]
This pull request is closed because it's related version has closed automatic cherry-picking.
If it's still needed, you can reopen it or just regenerate it using bot,
see:
- https://prow.tidb.io/command-help#cherrypick
- https://book.prow.tidb.net/#/plugins/cherrypicker

You can find more details at:
- https://internals.tidb.io/t/topic/785

**Pull request closed without merging**
