### PR TITLE
planner: avoid overwriting `path.IndexFilters` whe ... (#18076)

### LINKED ISSUE #17233: wrong result set when query nested JOINs
### 1. Minimal reproduce step (Required)
first import data from this sql file: 
[db.sql.txt](https://github.com/pingcap/tidb/files/4632566/db.sql.txt)

```sql
SELECT view_10.col_1 FROM view_5 JOIN view_4 JOIN view_10;
```
returns:
```bash
...
|    14 |
|    14 |
|    14 |
|     6 |
|     6 |
|     6 |
|     6 |
|     6 |
|     7 |
|     7 |
|     7 |
|     7 |
|     7 |
|     8 |
|     8 |
|     8 |
|     8 |
|     8 |
|     9 |
|     9 |
|     9 |
|     9 |
|     9 |
|    10 |
|    10 |
|    10 |
|    10 |
|    10 |
|    11 |
|    11 |
|    11 |
|    11 |
|    11 |
|    12 |
|    12 |
|    12 |
|    12 |
|    12 |
|    13 |
|    13 |
|    13 |
|    13 |
|    13 |
|    14 |
|    14 |
|    14 |
|    14 |
|    14 |
+-------+
585 rows in set, 9 warnings (0.06 sec)
```
but these values do not exist in view_10:
```sql
SELECT col_1 FROM view_10;
```
got results:
```bash
+-------+
| col_1 |
+-------+
|    16 |
|    18 |
|    19 |
+-------+
3 rows in set (0.00 sec)
```

### 2. What did you expect to see? (Required)

in mysql:
`SELECT view_10.col_1 FROM view_5 JOIN view_4 JOIN view_10;`
```bash
…
| 18 |
| 19 |
| 16 |
| 18 |
| 19 |
| 16 |
| 18 |
| 19 |
+----+
195 rows in set, 3 warnings (0.55 sec)
```

### 3. Affected version (Required)
```
+------------------------------------------+
| version()                                |
+------------------------------------------+
| 5.7.25-TiDB-v4.0.0-beta.2-307-g8322e8a2e |
+------------------------------------------+
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #18076 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #17233 

Problem Summary: avoid overwriting `path.IndexFilters` when deriving index path statistics

### What is changed and how it works?
Avoid overwriting `path.IndexFilters` when deriving index path statistics

### Check List 

Tests 

- Unit test

### Release note 

- planner: avoid overwriting `path.IndexFilters` when deriving index path statistics

### CODE REVIEW

**Comment by eurekaka** [comment]
@qw4990 please resolve conflicts.

**Comment by qw4990** [comment]
PTAL @eurekaka @lzmhhh123

**Review by zz-jason — COMMENTED** [review]
@qw4990 please resolve conflicts and fix CI.

**Comment by qw4990** [comment]
> @qw4990 please resolve conflicts and fix CI.

Fixed, PTAL.

**Review by zz-jason — APPROVED** [review]
LGTM

**Pull request merged**
