### PR TITLE
infoschema, executor, txn: change some field name in TIDB_TRX table

### PR DESCRIPTION
**Pull request by longfangsong**
### What problem does this PR solve?

Problem Summary:
Some field names in TIDB_TRX table are not very easy to understand.

### What is changed and how it works?

What's Changed:

Change `COUNT` into `MEM_BUFFER_KEYS` and `LEN` into `MEM_BUFFER_BYTES`.

### Check List 

Tests 

- No code

### Release note 

- No release note.

### CODE REVIEW

**Review by MyonKeminta — APPROVED** [review]

**Review by MyonKeminta — APPROVED** [review]

**Review by youjiali1995 — APPROVED** [review]

**Comment by hi-rustin** [comment]
> /merge

@MyonKeminta  You don't need to `/merge` as often, and if a test fails, you only need to run the test that failed. The bot will automatically merge PRs when all tests pass. there is no need to use `/merge` to trigger all tests.

**Pull request merged**
