### PR TITLE
tests: improve tests for Windows platform

### PR DESCRIPTION
**Pull request by bobotu**
### What is changed and how it works?
* Skip some tests which cannot run on the Windows platform.
* Use `127.0.0.1` instead of `0.0.0.0` to avoid trigger Windows Firewall notice.
* Update unistore to fix `recover from KILL` issue, which is important after we delete the entire mocktikv from TiDB.

### Release note 

-  No release note

### CODE REVIEW

**Comment by jackysp** [comment]
PTAL @tiancaiamao

**Comment by bobotu** [comment]
@jackysp I have updated unistore to correctly recover from SIGKILL on Windows😁

**Comment by bobotu** [comment]
PTAL @tiancaiamao

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
