### PR TITLE
ddl: migrate test-infra to testify for add index tests 

### LINKED ISSUE #32863: migrate test-infra to testify for add index tests

### PR DESCRIPTION
**Pull request by tisonkun**
### What problem does this PR solve?

Issue Number: close #32863 

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
Have some test cases failed.

**Review by hawkingrei — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Pull request merged**
