### PR TITLE
statistics/handle: migrate test-infra to testify

### LINKED ISSUE #27141: migrate test-infra to testify for `statistics`
* [x] #28116
* [x] #28117
* [x] #28118
* [x] #28119
* [x] #28120
* [x] #28121
* [x] #28122
* [x] #28123
* [x] #28124
* [x] #28125
* [x] #28126
* [x] #28127
* [x] #28128
* [x] #28129
* [x] #28130
* [x] #28131

### LINKED ISSUE #28126: migrate test-infra to testify for `statistics/handle/handle_test.go`

### LINKED ISSUE #28127: migrate test-infra to testify for `statistics/handle/update_test.go`

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

Issue Number: close #28127 close #28126 close #27141 close #30006

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
/cc @hawkingrei @xhebox @mmyj 

cc @feitian124 I'm taking over your work to move forward the migrate effort.

**Review by hawkingrei — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Comment by feitian124** [comment]
ok, thanks. sorry for my slow progress recently.

**Comment by tisonkun** [comment]
@feitian124 never mind. Wish you and your family a nice day :)

**Pull request merged**
