### PR TITLE
txn: consider forceSyncCommit flag for async commit (#23548)

### LINKED ISSUE #23540: txn: the async commit transaction status judge may be inaccurate with fallback
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This is raised during the investigation of https://github.com/pingcap/tidb/issues/23477.

1. Raise an async commit transaction.
2. Let the transaction fallback to 2pc before the commit stage.
3. Raise another transaction trying to resolve the prewrite locks of the previous transaction.
4. The Resolving steps are as follows:
4.1 LockResolver.resolveLocks
4.2 --getTxnStatusFromLock
4.3 ----LockResolver.getTxnStatus
4.4 ------the primary lock is fetched with `UseAsyncCommit` set to true, return expired status to the callee.
4.5 --resolveLockAsync
4.6 ---- the `nonAsyncCommitLock` is reported
4.7 --`getTxnStatusFromLock` again with `forceSyncCommit` set to true
4.8 ----LockResolver.getTxnStatus again with `forceSyncCommit` set to true
4.9 ------ the primary lock is fetched with `UseAsyncCommit` set to true, return expired status to the callee.
               Note here, as the `forceSyncCommit` is set to true, the transaction is treated as a 2pc one, so the transaction
               status should be judged by the response returned from `check_txn_status` api, but not checking the ttl again.
4.10 ----- Resolve the locks using the normal 2pc lock process.

### 2. What did you expect to see? (Required)
- For the async commit transactions, the transaction status could only be decided by the `resolveLockAsync` path.
- For the normal 2pc transactions or fallback async commit transactions, the transaction status should only be decided by the `check_txn_status` api which checks the primary lock status.

### 4. What is your TiDB version? (Required)
master 
release-5.0

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23548 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23561
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23561:release-5.0-07db18fc566a
```

---

### What problem does this PR solve?

Issue Number: close #23540 

Problem Summary:
Make the transaction status check for async commit transactions accurate.

### What is changed and how it works?

What's Changed:
If the `forceSyncCommit` flag is set, make the `status` check use the 2pc path instead of the `async commit` path, as the
`UseAsyncCommit` flag in the primary lock is invalid after fallback.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- We may need to add some tests about the fallback transaction resolving in the UTF.

Side effects

### Release note 

- No release note.

### CODE REVIEW

**Review by youjiali1995 — APPROVED** [review]

**Comment by cfzjywxk** [comment]
@MyonKeminta @sticnarf need another approval.

**Review by MyonKeminta — APPROVED** [review]

**Pull request merged**
