### PR TITLE
executor,expression: avoid to append nil to warnings

### LINKED ISSUE #31569: some unexpected warning message when dealing with 0 ENUM
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
MySQL [(none)]> use test
Database changed
MySQL [test]> create table t100 (c int primary key, c2 enum('a', 'b'));
Query OK, 0 rows affected (0.010 sec)

MySQL [test]> set session sql_mode = '';
Query OK, 0 rows affected (0.001 sec)

MySQL [test]> insert into t100 values(5, 0);
Query OK, 1 row affected, 1 warning (0.001 sec)

MySQL [test]> insert into t100 values(4, 'a');
Query OK, 1 row affected (0.002 sec)

MySQL [test]> insert into t100 values(4, 0) on duplicate key update c=values(c), c2=values(c2);
Query OK, 2 rows affected, 2 warnings (0.003 sec)

MySQL [test]> show warnings;
+---------+------+------------------------------------------+
| Level   | Code | Message                                  |
+---------+------+------------------------------------------+
| Warning | 1265 | Data truncated for column '%s' at row %d |
| Warning | 1265 | Data truncated for column '%s' at row %d |
+---------+------+------------------------------------------+
2 rows in set (0.001 sec)

MySQL [test]> select * from t100;
+---+------+
| c | c2   |
+---+------+
| 4 |      |
| 5 |      |
+---+------+
2 rows in set (0.007 sec)

MySQL [test]> insert into t100 values(4, 'a') on duplicate key update c=values(c), c2=values(c2);
Query OK, 2 rows affected, 1 warning (0.002 sec)

MySQL [test]> show warnings;
ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference
MySQL [test]> select * from t100;
+---+------+
| c | c2   |
+---+------+
| 4 | a    |
| 5 |      |
+---+------+
2 rows in set (0.007 sec)

MySQL [test]> 
```

### 2. What did you expect to see? (Required)

message is normal

### 3. What did you see instead (Required)

Data truncated for column '%s' at row %d

ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference

### 4. What is your TiDB version? (Required)

```
Release Version: v5.4.0-alpha-573-g0943e10d5
Edition: Community
Git Commit Hash: 0943e10d50c814efc72231f0c7d59204b69773fd
Git Branch: master
UTC Build Time: 2021-12-31 02:18:26
GoVersion: go1.17.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by zyguan**
Signed-off-by: zyguan <zhongyangguan@gmail.com>

### What problem does this PR solve?

Issue Number: close #31569

Problem Summary: two issues are described in #31569:
1. nil pointer exception was thrown when `show warnings`.
2. the warning messages were incompleted (missing template args).

### What is changed and how it works?

Previously we always append the warning error even when it's a nil [here](https://github.com/pingcap/tidb/pull/29759/files#diff-71c7fc79262ffec4f54c185d1ecf02f8c0ad72bbf6707b21f6671422a0b91c96R370), which leads to the first issue. This PR uses `sc.HandleTruncate` to handle trancate warnings uniformly and amends warnings generated on inserting.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Comment by tangenta** [comment]
@zyguan Please fix the following failed integration tests:

```
TestInsertWrongValueForField – executor
TestInsert – executor
TestInsertIgnore – executor
TestIssue10402 – executor
TestStringtoDecimal – executor
TestIssue17745 – executor
TestShowWarnings – showtest_test
TestIssue19892 – expression
TestConvertToBit – expression
```

**Comment by zyguan** [comment]
> Please fix the following failed integration tests
Fixed, @tangenta @xhebox PTAL.

**Review by tangenta — APPROVED** [review]

**Pull request merged**
