### PR TITLE
*: fix data race in the ReuseChunkPool

### LINKED ISSUE #46282: DATA RACE in the ReuseChunkPool
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
==================
WARNING: DATA RACE
Write at 0x00c0086f71f0 by goroutine 49824:
  github.com/pingcap/tidb/sessionctx/variable.(*SessionVars).SetAlloc()
      sessionctx/variable/session.go:1608 +0x8d
  github.com/pingcap/tidb/testkit.(*TestKit).ExecWithContext()
      testkit/testkit.go:332 +0x2b2
  github.com/pingcap/tidb/testkit.(*TestKit).MustExecWithContext()
      testkit/testkit.go:132 +0xab
  github.com/pingcap/tidb/testkit.(*TestKit).MustExec()
      testkit/testkit.go:127 +0x10d
  github.com/pingcap/tidb/ddl/ingest_test.injectMockBackendMgr.func1()
      ddl/ingest/integration_test.go:45 +0x4a
  github.com/pingcap/tidb/ddl/ingest.(*MockBackendCtxMgr).Register()
      ddl/ingest/mock.go:55 +0x1c1
  github.com/pingcap/tidb/ddl.pickBackfillType()
      ddl/index.go:744 +0x552
  github.com/pingcap/tidb/ddl.(*worker).onCreateIndex()
      ddl/index.go:629 +0xe85
  github.com/pingcap/tidb/ddl.(*worker).runDDLJob()
      ddl/ddl_worker.go:1054 +0xb7e
  github.com/pingcap/tidb/ddl.(*worker).HandleDDLJobTable()
      ddl/ddl_worker.go:775 +0x7f6
  github.com/pingcap/tidb/ddl.(*ddl).delivery2worker.func1()
      ddl/job_table.go:414 +0xd58
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
      util/wait_group_wrapper.go:154 +0x84
Previous write at 0x00c0086f71f0 by goroutine 49818:
  github.com/pingcap/tidb/sessionctx/variable.(*SessionVars).ClearAlloc()
      sessionctx/variable/session.go:1624 +0x14a
  github.com/pingcap/tidb/testkit.(*TestKit).ExecWithContext.func1()
      testkit/testkit.go:318 +0x4e
  runtime.deferreturn()
      GOROOT/src/runtime/panic.go:477 +0x30
  github.com/pingcap/tidb/testkit.(*TestKit).MustExecWithContext()
      testkit/testkit.go:132 +0xab
  github.com/pingcap/tidb/testkit.(*TestKit).MustExec()
      testkit/testkit.go:127 +0x10d
  github.com/pingcap/tidb/ddl/ingest_test.injectMockBackendMgr.func1()
      ddl/ingest/integration_test.go:46 +0x67
  github.com/pingcap/tidb/ddl/ingest.(*MockBackendCtxMgr).Register()
      ddl/ingest/mock.go:55 +0x1c1
  github.com/pingcap/tidb/ddl.pickBackfillType()
      ddl/index.go:744 +0x552
  github.com/pingcap/tidb/ddl.(*worker).onCreateIndex()
      ddl/index.go:629 +0xe85
  github.com/pingcap/tidb/ddl.(*worker).runDDLJob()
      ddl/ddl_worker.go:1054 +0xb7e
  github.com/pingcap/tidb/ddl.(*worker).HandleDDLJobTable()
      ddl/ddl_worker.go:775 +0x7f6
  github.com/pingcap/tidb/ddl.(*ddl).delivery2worker.func1()
      ddl/job_table.go:414 +0xd58
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
      util/wait_group_wrapper.go:154 +0x84
Goroutine 49824 (running) created at:
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run()
      util/wait_group_wrapper.go:152 +0xf0
  github.com/pingcap/tidb/ddl.(*ddl).delivery2worker()
      ddl/job_table.go:373 +0x1c5
  github.com/pingcap/tidb/ddl.(*ddl).loadDDLJobAndRun()
      ddl/job_table.go:366 +0x50d
  github.com/pingcap/tidb/ddl.(*ddl).startDispatchLoop()
      ddl/job_table.go:302 +0xb5a
  github.com/pingcap/tidb/ddl.(*ddl).startDispatchLoop-fm()
      <autogenerated>:1 +0x33
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
      util/wait_group_wrapper.go:154 +0x84
Goroutine 49818 (running) created at:
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run()
      util/wait_group_wrapper.go:152 +0xf0
  github.com/pingcap/tidb/ddl.(*ddl).delivery2worker()
      ddl/job_table.go:373 +0x1c5
  github.com/pingcap/tidb/ddl.(*ddl).loadDDLJobAndRun()
      ddl/job_table.go:366 +0x50d
  github.com/pingcap/tidb/ddl.(*ddl).startDispatchLoop()
      ddl/job_table.go:302 +0xb5a
  github.com/pingcap/tidb/ddl.(*ddl).startDispatchLoop-fm()
      <autogenerated>:1 +0x33
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
      util/wait_group
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #46282

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by cfzjywxk — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Comment by tiancaiamao** [comment]
From the calling stack, you can infer that **the same session is used by different goroutine**, that's the root cause of the data race.
So a real fix should fix the test case to avoid that misusage, rather than add a mutex blindly.

**Comment by easonn7** [comment]
/approve

there is no variable change in this PR, LGTM

**Comment by tiancaiamao** [comment]
https://github.com/pingcap/tidb/blob/9411e829e300c3c98523dccd67548820fb50d881/ddl/ingest/integration_test.go#L44-L48

Return this session for several goroutines to use is unsafe.

**Pull request closed without merging**
