### PR TITLE
ddl: move update version function to a proper place

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/40217

Problem Summary:

Previously, adding index may update the schema version twice in a single round:

https://github.com/pingcap/tidb/blob/90c5a87637ab537427139951581edf87beabd543/ddl/index.go#L880
https://github.com/pingcap/tidb/blob/90c5a87637ab537427139951581edf87beabd543/ddl/index.go#L684

It breaks the assumption of `GetSchemaVersionWithNonEmptyDiff`, which may get an empty diff structure.

https://github.com/pingcap/tidb/blob/b477b1c946205dee9456e27e967e7edd4ffdb80f/meta/meta.go#L404-L408

### What is changed and how it works?

This is a patch for #40229. Only update the version once.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by xiongjiwei — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by tangenta** [comment]
@hawkingrei We don't need to open a separate PR for cherry-pick. The change is included in #40305.

**Pull request merged**
