### PR TITLE
brie: an IMPORT demo, construct lightning config and update go.mod

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

a very early-stage IMPORT demo.

```
mysql> import database * from '/tmp/test';
+-------------+------+----------+---------------------+---------------------+
| Data Source | Size | CommitTS | Queue Time          | Execution Time      |
+-------------+------+----------+---------------------+---------------------+
| /tmp/test   |    0 |        0 | 2020-11-04 13:43:27 | 2020-11-04 13:43:27 |
+-------------+------+----------+---------------------+---------------------+
1 row in set (10.31 sec)
```

this PR is to embed lightning into TiDB and test it could successfully import, not including canceling, proper user interface, error handling

### What is changed and how it works?

What's Changed:

update go.mod to include lightning as a library

construct lightning config, run lightning and return result

**Need a real TiKV and TiDB should run at 127.0.0.1:400 with user root and no password to test**

**Only considered some IMPORT syntax, see https://github.com/pingcap/parser/blob/3d18e257aed686577566fccff97b76caa2fdada7/parser.y#L4252-L4489** except for `CHECKPOINT` (enable default), `TIKV_IMPORTER` (will not support importer backend), `BACKEND` (local backend default), `ON_DUPLICATE`  `ON DUPLICATE` (can't choose tidb backend now), numeric `CSV_HEADER` (lightning didn't support)

How it Works:

add an embedded lightning

### Check List 

Tests 

- Manual test (please give advice on adding test)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- No release note

### CODE REVIEW

**Comment by lance6716** [comment]
@overvenus

**Comment by leoppro** [comment]
/need-cherry-pick-4.0

**Comment by leoppro** [comment]
/needs-cherry-pick-4.0

**Comment by lance6716** [comment]
save task metadata to a table: https://github.com/lance6716/tidb/compare/import...lance6716:persistent-queue?expand=1

I'll fix `./tools/check/check-errdoc.sh` error in CI soon

@overvenus

**Comment by lance6716** [comment]
CI passed, PTAL @overvenus

**Comment by lance6716** [comment]
PTAL @kennytm @3pointer @SunRunAway

**Comment by kennytm** [comment]
> Need a real TiKV and TiDB should run at 127.0.0.1:400 with user root and no password to test

i think the intention of this PR is just to demonstrate that it works, not actually *merge* into TiDB as-is?

**Comment by lance6716** [comment]
> > Need a real TiKV and TiDB should run at 127.0.0.1:400 with user root and no password to test
> 
> i think the intention of this PR is just to demonstrate that it works, not actually *merge* into TiDB as-is?

my intention is to split that work to many small PR, and right, this PR is just to demonstrate lightning could work. if there's a good place where providing enough functionality and easy to review, I would like push more to acquire accept.

**Pull request closed without merging**
