### PR TITLE
expression/expressions: replace iconv-go with text/transform

### PR DESCRIPTION
**Pull request by Unknwon**
Remove CGO requirement for compiling iconv-go currently is using.

Replace it with native implementation of Go.

`make` test has passed, but test cases don't look very detailed on `expression`, so not sure if everything will go well.

### CODE REVIEW

**Comment by Unknwon** [comment]
Thank god, passed this time.

**Comment by xiang90** [comment]
LGTM. But I cannot press the merge button. :(

**Comment by Unknwon** [comment]
Godep is killing GitHub diff. So, you can't even find where did I changed.

**Comment by xiang90** [comment]
@Unknwon I usually keep them into separate commits:
1. change
2. godep

**Comment by Unknwon** [comment]
godep save doesn't work with tidb out of box, so I changed everything manually :joy: really don't want to go through hell again.

**Comment by Unknwon** [comment]
OK... there is the diff:

```patch
diff --git a/expression/expressions/convert.go b/expression/expressions/convert.go
index b636cb5..8fc7918 100644
--- a/expression/expressions/convert.go
+++ b/expression/expressions/convert.go
@@ -17,11 +17,12 @@ import (
        "fmt"
        "strings"

-       iconv "github.com/djimenez/iconv-go"
        "github.com/juju/errors"
        "github.com/ngaut/log"
        "github.com/pingcap/tidb/context"
        "github.com/pingcap/tidb/expression"
+       "golang.org/x/net/html/charset"
+       "golang.org/x/text/transform"
 )

 // FunctionConvert provides a way to convert data between different character sets.
@@ -74,7 +75,13 @@ func (f *FunctionConvert) Eval(ctx context.Context, args map[interface{}]interfa
        } else if strings.ToLower(f.Charset) == "utf8mb4" {
                return value, nil
        }
-       target, err := iconv.ConvertString(str, "utf-8", f.Charset)
+
+       encoding, _ := charset.Lookup(f.Charset)
+       if encoding == nil {
+               return nil, fmt.Errorf("unknow char decoder %s", f.Charset)
+       }
+
+       target, _, err := transform.String(encoding.NewDecoder(), str)
        if err != nil {
                log.Errorf("Convert %s to %s with error: %v", str, f.Charset, err)
                return nil, errors.Trace(err)
```

**Comment by ngaut** [comment]
Thanks @Unknwon 
Could you use packages under https://github.com/golang. 
golang.org/x has moved to github.com/golang.

And @xiang90 is right, keep them into separate commits:
1. change
2. godep

The correct step is:
cd tidb
go restore
go save ./...

Could you fix it ? @Unknwon Thanks.

**Comment by coocood** [comment]
@Unknwon this PR introduced too much dependencies, can you remove the depedency of "golang.org/x/net/html/charset", all we need is a map from charset name to encoding. 
How about copy the code in https://github.com/golang/net/blob/master/html/charset/table.go

**Comment by Unknwon** [comment]
https://github.com/pingcap/tidb/pull/42

**Pull request closed without merging**
