### PR TITLE
let update/delete do old logicOptimize

### PR DESCRIPTION
**Pull request by hanfei19910905**
This pr make tidb-test pass.
@shenli @coocood @zimulala @tiancaiamao PTAL

### CODE REVIEW

**Comment by shenli** [comment]
Will we use new planner for update/insert/delete?

**Comment by hanfei19910905** [comment]
we have not applied new plan to update/delete, @XuHuaiyu is implementing it.

**Comment by shenli** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
