### PR TITLE
go.mod: update br to lastest 4.0-release

### LINKED ISSUE #17834: BACKUP sql command fails on large backup to S3
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This is a re-open request for https://github.com/tidb-challenge-program/bug-hunting-issue/issues/72

It appears that stability has recently improved, but on a large backup I can still trigger a failure.

### 2. What did you expect to see? (Required)

Success.

### 3. What did you see instead (Required)

It is a different failure to earlier, but a failure all the same:

```sql
mysql> BACKUP DATABASE `ontime` TO 's3://wwartmp/ontime1';
ERROR 8124 (HY000): Backup failed: msg:"Io(Custom { kind: Other, error: \"failed to put object Request ID: None Body: <?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?><Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>340B24D85405AB58</RequestId><HostId>9EBqS6ocs6TWIf4c90z0VA4kxToJa64o6oIWdEszpQbx9kP1F7yw1G6RR8DhsLmsp+7oKy1GIIdm6QN8ExqtEWVf9OT9buB/</HostId></Error>\" })"
```
### 4. Affected version (Required)

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-584-gf9189cfa9
Edition: Community
Git Commit Hash: f9189cfa9346779e864049819b13bc43ea39ffbe
Git Branch: master
UTC Build Time: 2020-06-07 02:59:29
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve?

Issue Number: close #17834

Problem Summary: 

BR had a bug that will cause fail to upload huge file to object storage.

This is a 'cherry-pick' of #17839 to v4.0.

### What is changed and how it works?

What's Changed: Run `go get GitHub.com/pingcap/br@release-4.0`

How it Works:

By update BR to latest version, we introduce the fix of that bug.

### Check List 

Tests 

- No code

### Release note 

- Fix a bug that caused fail to backup/restore to/from object storage

### CODE REVIEW

**Comment by 3pointer** [comment]
PTAL @wjhuang2016 @bb7133

**Comment by YuJuncen** [comment]
/run-all-tests

`FAIL: sql_fail_test.go:106: testSQLSuite.TestCoprocessorStreamRecvTimeout`

Is this temporary?

**Comment by YuJuncen** [comment]
/run-all-tests

`value *errors.fundamental = conn 1 Invalid transaction tso with txnStartTS=417450633096069120 while txnCommitTS=417450630474629122 ("conn 1 Invalid transaction tso with txnStartTS=417450633096069120 while txnCommitTS=417450630474629122")`

how can this happen...

**Pull request merged**
