### PR TITLE
ddl:`show full columns` for date, datetime, timestamp compatibility (#9810)

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve? 
cherry-pick #9810 to v2.1

Related PR: pingcap/tidb-test#768

### CODE REVIEW

**Comment by zimulala** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zimulala** [comment]
PTAL @crazycs520 @bb7133 @xiekeyi98

**Comment by bb7133** [comment]
LGTM

**Pull request merged**
