### PR TITLE
bazel: upgrade rules_go to prepare for Go 1.20

### LINKED ISSUE #40798: upgrade bazel and rules_go
## Enhancement

why we need to upgrade the bazel the rules_go?

in the release not of rules_go 0.38, it mentioned that new rules_go can support the go 1.20

```
This is the first release to support Go 1.20. When on this version of Go, it is highly recommended to use Bazel 6 and set 

--experimental_output_directory_naming_scheme=diff_against_baseline to prevent certain 

unnecessary rebuilds.
```

we find it have an new switch to accelerate the build in the bazel 6.0 . so that we decide to upgrade them.

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #40798

Problem Summary:

### What is changed and how it works?

in the release not of rules_go 0.38, it mentioned that new rules_go can support the go 1.20

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — COMMENTED** [review]
seems there's no change related to go 1.20, the PR title should be updated?

**Comment by hawkingrei** [comment]
> seems there's no change related to go 1.20, the PR title should be updated?

It just is ready for the go 1.20. because the old rules_go cannot be with go1.20. so we upgrade the rules_go first.

**Review by lance6716 — APPROVED** [review]

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
