### PR TITLE
planner/core: fix point-get db privilege check

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

current point-get code path checks db privilege by current db and miss check `db1` privilege for query using `db.tbl1`.

and see more detail in test case.

### What is changed and how it works?

check privilege using db in ast tree if it exists.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - impl

Side effects

 - n/a

Related changes

 - Need to cherry-pick to the release branch

Release note

 - planner/core: fix point-get db privilege check

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/12268)

### CODE REVIEW

**Comment by cyliu0** [comment]
@lysu This PR has been labeled with `needs-cherry-pick-3.1`. Plz cherry pick this one to release-3.1

**Comment by lysu** [comment]
@cyliu0 done https://github.com/pingcap/tidb/pull/13220

**Pull request merged**
