### PR TITLE
*: use pdqsort to improve sort performance

### LINKED ISSUE #34250: use pdqsort to improve sort performance
## Enhancement

ref https://github.com/zhangyunhao116/pdqsort/issues/2

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #34250

Problem Summary:

### What is changed and how it works?

- use pdqsort to sort  https://github.com/golang/go/issues/50154, In common patterns, pdqsort is often faster (i.e. 10x faster in sorted slices).
- remove ```github.com/cznic/sortutil```

BTW, it is not only improved performance by using the pdqsort, but also it can remove BCE by the using generics to improve performance.

### Check List

Tests 

- [x] Unit test
- [x] Integration test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]
Should we merge #35970 first?

**Comment by hawkingrei** [comment]
> Should we merge #35970 first?

I find the latest revive can find more problems in the repo. I will spend much time to fix them.

**Pull request merged**
