### PR TITLE
Fix session auth bug

### PR DESCRIPTION
**Pull request by losas**
Authentication passed when given any username with an empty password.

### CODE REVIEW

**Comment by shenli** [comment]
@losas Thanks for your PR. Please add an unit test.

**Comment by losas** [comment]
Sorry, i don't know how to do this.

**Comment by shenli** [comment]
@losas There is a test case in session_test.go. https://github.com/pingcap/tidb/blob/master/session_test.go#L746

 Your can compose a similar test case. You need to do something to make getPassword() throw error. I take a look at the code and find that if you set a value to session(or ctx), ExecRestrictedSQL() will return error. getPassword() will call ExecRestrictedSQL. So I think it is what we need.
https://github.com/pingcap/tidb/blob/master/session.go#L266

Hope this helps. If your need more information, please let me know.

**Comment by losas** [comment]
is that ok?

**Comment by shenli** [comment]
@losas Yes, this is a much smarter way than mine! Good job!
LGMT
@coocood @qiuyesuifeng  PTAL

**Comment by coocood** [comment]
LGTM
Thank you!

**Pull request merged**
