### PR TITLE
error: split an error type from ErrKeyColumnDoesNotExists

### LINKED ISSUE #35102: Can the meaning of ErrKeyColumnDoesNotExits be more clear?
## Feature Request

**Is your feature request related to a problem? Please describe:**

Some applications like DM need to retry basing on the error. Now ErrKeyColumnDoesNotExits has two meanings:

- If retry later, the DDL may succeed, like https://github.com/pingcap/tidb/blob/8401fa0263df9def3b8f4cf359782d40f0f8d101/ddl/column.go#L1551
- If retry later, the DDL will not succeed, like https://github.com/pingcap/tidb/blob/8401fa0263df9def3b8f4cf359782d40f0f8d101/ddl/ddl_api.go#L1870

**Describe the feature you'd like:**

Assign the first case a different error code.

**Describe alternatives you've considered:**

We use error message to tell them apart, but the error message may change in future.

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #35102 

Problem Summary: tools can't determine whether the error is retryable.

### What is changed and how it works?

add type "ErrColumnInChange" which is retryable

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Comment by lance6716** [comment]
small PR, ptal @xiongjiwei @hawkingrei

**Review by xiongjiwei — APPROVED** [review]

**Pull request merged**
