### PR TITLE
tidb: Add full jitter backoff when retry

### PR DESCRIPTION
**Pull request by shenli**
See: https://github.com/pingcap/tidb/pull/592
Based on latest master.

### CODE REVIEW

**Comment by siddontang** [comment]
kv.RunInNewTxn should support it too.

**Comment by shenli** [comment]
PTAL @siddontang

**Comment by shenli** [comment]
PTAL @siddontang

**Comment by siddontang** [comment]
LGTM

**Comment by ngaut** [comment]
Please add tests

**Comment by shenli** [comment]
PTAL @ngaut

**Pull request merged**
