### PR TITLE
statistics: update the count and modify variables of global-stats as well when dumping delta info

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary: statistics: update the count and modify variables of global-stats as well when dumping delta info

### What is changed and how it works?
statistics: update the count and modify variables of global-stats as well when dumping delta info
### Check List 

Tests 

- Unit test

### Release note 

- statistics: update the count and modify variables of global-stats as well when dumping delta info

### CODE REVIEW

**Review by rebelice — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]
/LGTM

**Pull request merged**
