### PR TITLE
executor: revert test case introduced in #18819 to solve the data race on release-4.0

### PR DESCRIPTION
**Pull request by ichn-hu**
Reverts pingcap/tidb#18819 , partially solved #19700 

This PR causes a data race that blocks all subsequent PRs, therefore it should consider a revert.

See: https://github.com/pingcap/tidb/pulls?q=is%3Apr+base%3Arelease-4.0+is%3Aclosed+sort%3Aupdated-desc 

starting from https://github.com/pingcap/tidb/pull/18819 , all CIs are broken.

### Release Note

- No release note

### CODE REVIEW

**Comment by zz-jason** [comment]
What's the root cause of the CI broken?

**Comment by ichn-hu** [comment]
> What's the root cause of the CI broken?

I am currently not sure, I still need more time to investigate about this (hugely because of PointGet under parallel execution), but it can be obvious that this PR causes the broken CI, and in order not to block PRs to release-4.0, I proposed this revert PR.

**Comment by zz-jason** [comment]
another question is, why the CI in the master branch isn't broken :joy:

**Comment by ichn-hu** [comment]
> another question is, why the CI in the master branch isn't broken

It might be fixed, but the fix is not ported to 4.0.

**Comment by ichn-hu** [comment]
> another question is, why the CI in the master branch isn't broken

After investigation, the cause of this data race is similar with this one https://github.com/pingcap/tidb/issues/16817#issuecomment-620969926 , both are due to point get at the outer side of look up merge join, which after execution, enters `finishStmt` and turned the `txn.Transaction` into invalid, while the point get executor is still running, checking the transaction variable in `Next`, see https://github.com/pingcap/tidb/blob/104d372dbb44cf1ef5e6a479a48b4753e65a9835/executor/point_get.go#L144 .

It does not cause panic, just because it only checks if `txn.Transaction` is nil or not, not dereferencing it, while such check concurrently raced with the set to nil.

The reason it does not happen on master is because @tiancaiamao moved this check from `Next` to `Open` in https://github.com/pingcap/tidb/commit/05b2e2bdcc2a8f0329cf0bb7e870cfa9278f6a62#r42000685 .

I do not have a fix for this right now, I plan to port this PR to 4.0-release to see if it could solve the problem, however this PR changes too much code, it would splendid if @tiancaiamao could help with this.

**Comment by ichn-hu** [comment]
@zz-jason After discussion with @tiancaiamao , we decided to temporarily comment out the offending test case, once we solved the race condition, we will add it back.

**Comment by zz-jason** [comment]
OK. Does it only affect the unit tests?

**Comment by ichn-hu** [comment]
> OK. Does it only affect the unit tests?

As for now, only this unit test will cause the data race, but this is indeed a bug that need to be fixed no matter what, and it is already fixed on master, just not yet ported to release-4.0. The port (or cherry-pick) is complicated, and need more time, therefore we would like to temporarily fix it by revert the test.

**Review by lzmhhh123 — COMMENTED** [review]
You can use 
```go
if israce.RaceEnabled {
	c.Skip("skip race test")
}
```
instead of comment out the cases.

**Comment by zz-jason** [comment]
> > OK. Does it only affect the unit tests?
> 
> As for now, only this unit test will cause the data race, but this is indeed a bug that need to be fixed no matter what, and it is already fixed on master, just not yet ported to release-4.0. The port (or cherry-pick) is complicated, and need more time, therefore we would like to temporarily fix it by revert the test.

Seems we only need to fix the test? Just confirm, is there a potential data race issue when users file queries?

**Comment by ichn-hu** [comment]
> > > OK. Does it only affect the unit tests?
> > 
> > 
> > As for now, only this unit test will cause the data race, but this is indeed a bug that need to be fixed no matter what, and it is already fixed on master, just not yet ported to release-4.0. The port (or cherry-pick) is complicated, and need more time, therefore we would like to temporarily fix it by revert the test.
> 
> Seems we only need to fix the test? Just confirm, is there a potential data race issue when users file queries?

Yes, it is possible, therefore we need to fix it.

**Comment by ichn-hu** [comment]
@zz-jason @SunRunAway let's merge this revert.

**Review by SunRunAway — APPROVED** [review]
LGTM

**Pull request merged**
