### PR TITLE
privilege: remove leading and trailing space when create user and role

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/20592

remove `user` and `host` leading and trailing space when `create user` and role

Tests 

- Unit test

### Release note 

- fix a bug that `create user` may contain a line breaker in prefix or suffix

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Comment by glkappe** [comment]
When will this pr be cherry-pick

**Comment by wjhuang2016** [comment]
> When will this pr be cherry-pick

We don't have a plan to cherry-pick. Is there any user who need this?

**Comment by glkappe** [comment]
This is not a very important pr. The burden of cherry-pick should not be too great. This demand is also submitted by asktug. The pr of cherry-pick is also necessary.

**Comment by glkappe** [comment]
@yudongusa Please help the Cherry Pick of this PR? TNX

**Pull request closed without merging**
