### PR TITLE
server: add test for OPTIONALLY keyword

### PR DESCRIPTION
**Pull request by imtbkcat**
### What problem does this PR solve? 
fix https://github.com/pingcap/parser/issues/179

### What is changed and how it works?
Related parser PR: https://github.com/pingcap/parser/pull/192

This PR add integrated test for `LOAD DATA` with `OPTIONALLY` keyword.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

no

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM
PTAL @jackysp

**Comment by tiancaiamao** [comment]
PTAL @jackysp

**Comment by jackysp** [comment]
Please update the go.mod file.

**Pull request merged**
