### PR TITLE
meta: make auto increment id can be adjust. (#10978)

### PR DESCRIPTION
**Pull request by imtbkcat**
cherry-pick #10978 
Some modification to address conflict and make it work

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by coocood** [comment]
/run-all-tests tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by jackysp** [comment]
Please cherry-pick the tidb-test for release-2.1.

**Comment by imtbkcat** [comment]
/run-all-tests tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-test=pr/845

**Comment by imtbkcat** [comment]
/run-common-test tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-test=pr/845

**Comment by jackysp** [comment]
/run-common-test tikv=release-2.1 pd=release-2.1 tidb-test=pr/845

**Comment by jackysp** [comment]
/run-integration-common-test tikv=release-2.1 pd=release-2.1 tidb-test=pr/845

**Pull request merged**
