### PR TITLE
executor: add missing update table delta for TxnCtx (#20982)

### LINKED ISSUE #20975: Unexpected "Information schema is changed" when commits
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
``` sql
mysql> drop table t2, t1;
Query OK, 0 rows affected (0.04 sec)

mysql> create table t1(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values (1);
Query OK, 1 row affected (0.00 sec)

mysql> begin pessimistic;
Query OK, 0 rows affected (0.00 sec)

mysql> update t1 set a=a;
Query OK, 0 rows affected (0.00 sec)
Rows matched: 1  Changed: 0  Warnings: 0

/* session 2 */ mysql> create table t2(a int);
Query OK, 0 rows affected (0.00 sec)

mysql> commit;
ERROR 8028 (HY000): Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]
```

### 2. What did you expect to see? (Required)
Commit successfully.
### 3. What did you see instead (Required)
Information schema is changed during the execution of the statement
### 4. What is your TiDB version? (Required)

4.0 master

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20982 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #20975

Problem Summary:

```sql
mysql> drop table t2, t1;
Query OK, 0 rows affected (0.04 sec)

mysql> create table t1(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values (1);
Query OK, 1 row affected (0.00 sec)

mysql> begin pessimistic;
Query OK, 0 rows affected (0.00 sec)

mysql> update t1 set a=a;
Query OK, 0 rows affected (0.00 sec)
Rows matched: 1  Changed: 0  Warnings: 0

/* session 2 */ mysql> create table t2(a int);
Query OK, 0 rows affected (0.00 sec)

mysql> commit;
ERROR 8028 (HY000): Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]
```

### What is changed and how it works?

What's Changed:

When update statement without changes it missing track table ID for SchemaValidator. So when execute `commit` statement will cause SchemaValidator check whole Schema without tables and this will cause schema change error.

### Related changes

- No

### Check List 

Tests 

- Manual test (steps see below)

```sql
mysql> drop table t2, t1;
Query OK, 0 rows affected (0.04 sec)

mysql> create table t1(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values (1);
Query OK, 1 row affected (0.00 sec)

mysql> begin pessimistic;
Query OK, 0 rows affected (0.00 sec)

mysql> update t1 set a=a;
Query OK, 0 rows affected (0.00 sec)
Rows matched: 1  Changed: 0  Warnings: 0

/* session 2 */ mysql> create table t2(a int);
Query OK, 0 rows affected (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.00 sec)
```

Side effects

- Performance regression
    - Consumes more CPU when DML cause nothing changes
    - Consumes more MEM when DML cause nothing changes
    - Add lock for update TableDeltaMap may cause little slower

### Release note 

- No Release Note

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Comment by cfzjywxk** [comment]
LGTM

**Comment by cfzjywxk** [comment]
> Anyone has some idea about why `TestRetrySchemaChangeForEmptyChange` failed?

Seems it's because the [read number](https://github.com/pingcap/tidb/pull/21279/files#diff-4c9a4c1e9a402d07a0a78f4db9f766d23f1ff57ceda1e75c4e83b579488ad301R904) is zero using [`select for update`](https://github.com/ti-srebot/tidb/blob/release-4.0-e6e894dcc409/session/session_test.go#L2140) in the case, we added the table `t` into the delta map in this pr, and its schema changed.
Before this change there will be no tables in the delta map and the transaction is not dirty, the commit will succeed.

**Comment by cfzjywxk** [comment]
@bb7133 I changed the milestone but I'm not sure if it's ok to put it to next release.

**Comment by bb7133** [comment]
After discussion with @cfzjywxk and @blacktear23 , we realized that this PR leads to a regression issue to the txn & schema change conflicts:

```
session1.Exec("begin pessimistic")
session2.Exec("alter table t add k int")
session1.Exec("select * from t for update")
session1.Exec("update t set i = -i")
session1.Exec("delete from t")
session1.Exec("insert into t1 values (1)")
session1.Exec("commit")
```

Which caused failed `Information Schema is changed` error for the transaction when the 'amend transaction feature' is not enabled. We hold this PR until a better solution is found.

**Comment by bb7133** [comment]
Close this PR temporarily for the reason above.

**Comment by cfzjywxk** [comment]
> > Anyone has some idea about why `TestRetrySchemaChangeForEmptyChange` failed?
> 
> Seems it's because the [read number](https://github.com/pingcap/tidb/pull/21279/files#diff-4c9a4c1e9a402d07a0a78f4db9f766d23f1ff57ceda1e75c4e83b579488ad301R904) is zero using [`select for update`](https://github.com/ti-srebot/tidb/blob/release-4.0-e6e894dcc409/session/session_test.go#L2140) in the case, we added the table `t` into the delta map in this pr, and its schema changed. We could skip add delta table if there is no data fetched for `SelectLockExec`.

@bb7133 @blacktear23 I think with this change we could merge this pr on release-4.0.

**Comment by cfzjywxk** [comment]
Ping @bb7133 @blacktear23  ~
I think we need this on v4.0.10.

We could use the following rules to check tidb hehaviours are expected withouth considering amend related logic.
- For txn changes nothing(no lock or write in the memory buffer), the txn should not be dirty and schema check will not be executed.(clean txn should not be checked and no `infoschema changed` error is returnd).
- For txn with pessimistic locks only(update t set id = id where id = 1), the related table id should be added into the delta map and schema check is needed and related table schema version is checked.(lock only txn commit should not report error like `table id empty`). Note For `selectLockExec` it will not lock any rows if no rows are returned, then the table id should not be added into the delta map.
- For txn with write, the related table is checked.

**Comment by cfzjywxk** [comment]
@you06 @MyonKeminta PTAL

**Comment by blacktear23** [comment]
> Ping @bb7133 @blacktear23 ~
> I think we need this on v4.0.10.
> 
> We could use the following rules to check tidb hehaviours are expected withouth considering amend related logic.
> 
> * For txn changes nothing(no lock or write in the memory buffer), the txn should not be dirty and schema check will not be executed.(clean txn should not be checked and no `infoschema changed` error is returnd).
> * For txn with pessimistic locks only(update t set id = id where id = 1), the related table id should be added into the delta map and schema check is needed and related table schema version is checked.(lock only txn commit should not report error like `table id empty`). Note For `selectLockExec` it will not lock any rows if no rows are returned, then the table id should not be added into the delta map.
> * For txn with write, the related table is checked.

Update this PR or create a new PR for release-4.0 branch?

**Comment by cfzjywxk** [comment]
> > Ping @bb7133 @blacktear23 ~
> > I think we need this on v4.0.10.
> > We could use the following rules to check tidb hehaviours are expected withouth considering amend related logic.
> > 
> > * For txn changes nothing(no lock or write in the memory buffer), the txn should not be dirty and schema check will not be executed.(clean txn should not be checked and no `infoschema changed` error is returnd).
> > * For txn with pessimistic locks only(update t set id = id where id = 1), the related table id should be added into the delta map and schema check is needed and related table schema version is checked.(lock only txn commit should not report error like `table id empty`). Note For `selectLockExec` it will not lock any rows if no rows are returned, then the table id should not be added into the delta map.
> > * For txn with write, the related table is checked.
> 
> Update this PR or create a new PR for release-4.0 branch?

What about create a new PR?

**Comment by cfzjywxk** [comment]
New implementation in https://github.com/pingcap/tidb/pull/21996, close this one.

**Pull request closed without merging**
