### PR TITLE
expression, types: remove the usage of "TypeClass" in "builtin_compare.go"

### PR DESCRIPTION
**Pull request by zz-jason**
to #4394

### CODE REVIEW

**Comment by coocood** [comment]
@zz-jason 
There are many places `IsStringKind` replaced `ClassString`,  are those bugs?

**Comment by zz-jason** [comment]
@coocood no, they follow the behavior of mysql.

**Comment by coocood** [comment]
@zz-jason 
Got it

**Comment by coocood** [comment]
LGTM

**Pull request merged**
