### PR TITLE
execute: fill arguments when returning `ErrUnknownSystemVar` in `SetSessionSystemVar` (#20102)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20102 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary: fill arguments when returning `ErrUnknownSystemVar` in `SetSessionSystemVar`

### What is changed and how it works?

fill arguments when returning `ErrUnknownSystemVar` in `SetSessionSystemVar`

### Check List 

Tests 

- Unit test

### Release note 

- fill arguments when returning `ErrUnknownSystemVar` in `SetSessionSystemVar`

### CODE REVIEW

**Comment by bb7133** [comment]
@qw4990 , please resolve the conflicts.

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by SunRunAway — APPROVED** [review]

**Comment by SunRunAway** [comment]
```

[2020-11-21T14:19:24.617Z] FAIL: varsutil_test.go:104: testVarsutilSuite.TestVarsutil

[2020-11-21T14:19:24.617Z] 

[2020-11-21T14:19:24.617Z] varsutil_test.go:454:

[2020-11-21T14:19:24.617Z]     c.Assert(err, ErrorMatches, ".*]Unknown system variable 'UnknownVariable'")

[2020-11-21T14:19:24.617Z] ... error string = "[variable:1193]Unknown system variable 'unknownvariable'"

[2020-11-21T14:19:24.617Z] ... regex string = ".*]Unknown system variable 'UnknownVariable'"
```

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Review by SunRunAway — APPROVED** [review]

**Pull request merged**
