### PR TITLE
statistics: reduce the log output

### PR DESCRIPTION
**Pull request by Rustin170506**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/55906

Problem Summary:

### What changed and how does it work?

After I tested it in the real cluster, The logs were a little overwhelming.

So I changed it to print logs only if it takes longer than the threshold(150ms).

The current test result, for 1k tables:
```log
tidb.log:[2024/11/06 19:17:14.008 +08:00] [INFO] [queue.go:337] ["DML changes processed"] [category=stats] [duration=4.609153ms]
tidb.log:[2024/11/06 19:19:14.003 +08:00] [INFO] [queue.go:315] ["Start to fetch DML changes of jobs"] [category=stats]
tidb.log:[2024/11/06 19:19:14.008 +08:00] [INFO] [queue.go:337] ["DML changes processed"] [category=stats] [duration=4.651311ms]
tidb.log:[2024/11/06 19:19:19.996 +08:00] [INFO] [refresher.go:187] ["No tables to analyze"] [category=stats] [sampled=]
tidb.log:[2024/11/06 19:21:14.003 +08:00] [INFO] [queue.go:315] ["Start to fetch DML changes of jobs"] [category=stats]
tidb.log:[2024/11/06 19:21:14.008 +08:00] [INFO] [queue.go:337] ["DML changes processed"] [category=stats] [duration=4.815927ms]
tidb.log:[2024/11/06 19:21:14.008 +08:00] [INFO] [queue.go:318] ["Start to refresh last analysis durations of jobs"] [category=stats]
tidb.log:[2024/11/06 19:21:14.009 +08:00] [INFO] [queue.go:645] ["Last analysis duration refreshed"] [category=stats] [duration=9.037µs]
tidb.log:[2024/11/06 19:21:14.009 +08:00] [INFO] [queue.go:321] ["Start to request must retry jobs"] [category=stats]
tidb.log:[2024/11/06 19:21:14.010 +08:00] [INFO] [queue.go:612] ["Must retry jobs requeued"] [category=stats] [duration=3.536µs]
tidb.log:[2024/11/06 19:23:14.003 +08:00] [INFO] [queue.go:315] ["Start to fetch DML changes of jobs"] [category=stats]
tidb.log:[2024/11/06 19:23:14.009 +08:00] [INFO] [queue.go:337] ["DML changes processed"] [category=stats] [duration=4.902583ms]
tidb.log:[2024/11/06 19:24:22.996 +08:00] [INFO] [refresher.go:187] ["No tables to analyze"] [category=stats] [sampled=]
tidb.log:[2024/11/06 19:25:14.003 +08:00] [INFO] [queue.go:315] ["Start to fetch DML changes of jobs"] [category=stats]
tidb.log:[2024/11/06 19:25:14.008 +08:00] [INFO] [queue.go:337] ["DML changes processed"] [category=stats] [duration=4.587099ms]
tidb.log:[2024/11/06 19:26:14.003 +08:00] [INFO] [queue.go:321] ["Start to request must retry jobs"] [category=stats]
tidb.log:[2024/11/06 19:26:14.004 +08:00] [INFO] [queue.go:612] ["Must retry jobs requeued"] [category=stats] [duration=6.005µs]
```
The current test result, for 1m tables:
```log
tidb.log:[2024/11/06 19:28:54.954 +08:00] [INFO] [queue.go:337] ["DML changes processed"] [category=stats] [duration=116.376734ms]
tidb.log:[2024/11/06 19:28:54.955 +08:00] [INFO] [queue.go:318] ["Start to refresh last analysis durations of jobs"] [category=stats]
tidb.log:[2024/11/06 19:28:54.955 +08:00] [INFO] [queue.go:645] ["Last analysis duration refreshed"] [category=stats] [duration=6.274µs]
tidb.log:[2024/11/06 19:28:54.955 +08:00] [INFO] [queue.go:321] ["Start to request must retry jobs"] [category=stats]
tidb.log:[2024/11/06 19:28:54.956 +08:00] [INFO] [queue.go:612] ["Must retry jobs requeued"] [category=stats] [duration=8.521µs]
tidb.log:[2024/11/06 19:29:39.491 +08:00] [INFO] [refresher.go:187] ["No tables to analyze"] [category=stats] [sampled=]
tidb.log:[2024/11/06 19:30:54.837 +08:00] [INFO] [queue.go:315] ["Start to fetch DML changes of jobs"] [category=stats]
tidb.log:[2024/11/06 19:30:54.958 +08:00] [INFO] [queue.go:337] ["DML changes processed"] [category=stats] [duration=119.915ms]
tidb.log:[2024/11/06 19:32:54.837 +08:00] [INFO] [queue.go:315] ["Start to fetch DML changes of jobs"] [category=stats]
tidb.log:[2024/11/06 19:32:54.960 +08:00] [INFO] [queue.go:337] ["DML changes processed"] [category=stats] [duration=121.760741ms]
tidb.log:[2024/11/06 19:33:54.837 +08:00] [INFO] [queue.go:321] ["Start to request must retry jobs"] [category=stats]
tidb.log:[2024/11/06 19:33:54.838 +08:00] [INFO] [queue.go:612] ["Must retry jobs requeued"] [category=stats] [duration=7.207µs]
```

Also, I stabilized one flaky test in this PR.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] [Manual test](https://github.com/pingcap/tidb/pull/57184#issuecomment-2459673262)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Rustin170506** [comment]
Tested locally:
```log
[2024/11/06 20:31:32.177 +08:00] [INFO] [queue.go:143] ["Priority queue initialized"] [category=stats] [duration=8.653875ms]
[2024/11/06 20:31:32.177 +08:00] [INFO] [refresher.go:187] ["No tables to analyze"] [category=stats] [sampled=]
[2024/11/06 20:31:36.977 +08:00] [INFO] [store_cache.go:532] ["change store resolve state"] [store=130] [addr=127.0.0.1:3930] [from=unresolved] [to=resolved] [liveness-state=reachable]
[2024/11/06 20:32:28.288 +08:00] [INFO] [manager.go:474] ["get owner"] ["owner info"="[log-backup] /tidb/br-stream/owner ownerManager 0fdbbe82-6208-45d0-a5cd-60a842516ec6"] ["owner key"=/tidb/br-stream/owner/22319301754e1a0a] [ownerID=0fdbbe82-6208-45d0-a5cd-60a842516ec6] [op=none]
[2024/11/06 20:32:28.288 +08:00] [INFO] [manager.go:335] ["become owner"] ["owner info"="[log-backup] /tidb/br-stream/owner ownerManager 0fdbbe82-6208-45d0-a5cd-60a842516ec6"]
[2024/11/06 20:32:29.153 +08:00] [INFO] [owner_daemon.go:56] ["daemon became owner"] [id=0fdbbe82-6208-45d0-a5cd-60a842516ec6] [daemon-id=LogBackup::Advancer]
[2024/11/06 20:32:29.155 +08:00] [INFO] [advancer.go:523] ["Subscription handler spawned."] [category="log backup subscription manager"]
[2024/11/06 20:33:32.177 +08:00] [INFO] [queue.go:322] ["Start to fetch DML changes of jobs"] [category=stats] [sampled=]
[2024/11/06 20:34:09.035 +08:00] [WARN] [pd.go:168] ["get timestamp too slow"] ["cost time"=37.699292ms]
[2024/11/06 20:36:29.141 +08:00] [INFO] [domain.go:3096] ["refreshServerIDTTL succeed"] [serverID=1844] ["lease id"=22319301754e19f9]
[2024/11/06 20:36:32.175 +08:00] [INFO] [queue.go:328] ["Start to request must retry jobs"] [category=stats] [sampled=]
[2024/11/06 20:36:35.166 +08:00] [INFO] [refresher.go:187] ["No tables to analyze"] [category=stats] [sampled=]
[2024/11/06 20:37:55.020 +08:00] [WARN] [pd.go:168] ["get timestamp too slow"] ["cost time"=36.537125ms]
[2024/11/06 20:41:29.148 +08:00] [INFO] [domain.go:3096] ["refreshServerIDTTL succeed"] [serverID=1844] ["lease id"=22319301754e19f9]
[2024/11/06 20:41:29.237 +08:00] [INFO] [gc_worker.go:415] ["starts the whole job"] [category="gc worker"] [uuid=64c05d575e00009] [safePoint=453744076833685504] [concurrency=1]
[2024/11/06 20:41:29.237 +08:00] [INFO] [gc_worker.go:1201] ["start resolve locks"] [category="gc worker"] [uuid=64c05d575e00009] [safePoint=453744076833685504] [concurrency=1]
[2024/11/06 20:41:29.237 +08:00] [INFO] [range_task.go:167] ["range task started"] [name=resolve-locks-runner] [startKey=] [endKey=] [concurrency=1]
[2024/11/06 20:41:29.268 +08:00] [INFO] [range_task.go:276] ["range task finished"] [name=resolve-locks-runner] [startKey=] [endKey=] ["cost time"=30.433ms] ["completed regions"=64]
[2024/11/06 20:41:29.268 +08:00] [INFO] [gc_worker.go:1226] ["finish resolve locks"] [category="gc worker"] [uuid=64c05d575e00009] [safePoint=453744076833685504] [regions=64]
[2024/11/06 20:41:32.176 +08:00] [INFO] [queue.go:325] ["Start to refresh last analysis durations of jobs"] [category=stats] [sampled=]
[2024/11/06 20:41:38.164 +08:00] [INFO] [refresher.go:187] ["No tables to analyze"] [category=stats] [sampled=]
[2024/11/06 20:42:29.194 +08:00] [INFO] [gc_worker.go:373] ["there's already a gc job running, skipped"] [category="gc worker"] ["leaderTick on"=64c05d575e00009]
[2024/11/06 20:43:09.289 +08:00] [INFO] [gc_worker.go:832] ["start delete ranges"] [category="gc worker"] [uuid=64c05d575e00009] [ranges=0]
[2024/11/06 20:43:09.289 +08:00] [INFO] [gc_worker.go:906] ["finish delete ranges"] [category="gc worker"] [uuid=64c05d575e00009] ["num of ranges"=0] ["cost time"=122.25µs]
[2024/11/06 20:43:09.291 +08:00] [INFO] [gc_worker.go:956] ["start redo-delete ranges"] [category="gc worker"] [uuid=64c05d575e00009] ["num of ranges"=0]
[2024/11/06 20:43:09.292 +08:00] [INFO] [gc_worker.go:999] ["finish redo-delete ranges"] [category="gc worker"] [uuid=64c05d575e00009] ["num of ranges"=0] ["cost time"=1.625µs]
[2024/11/06 20:43:09.296 +08:00] [WARN] [gc_worker.go:1189] ["distributed mode will be used"] [category="gc worker"] ["invalid gc mode"=]
[2024/11/06 20:43:09.305 +08:00] [INFO] [gc_worker.go:1263] ["sent safe point to PD"] [category="gc worker"] [uuid=64c05d575e00009] ["safe point"=453744076833685504]
[2024/11/06 20:45:33.039 +08:00] [WARN] [pd.go:168] ["get timestamp too slow"] ["cost time"=50.5895ms]
[2024/11/06 20:46:29.155 +08:00] [INFO] [domain.go:3096] ["refreshServerIDTTL succeed"] [serverID=1844] ["lease id"=22319301754e19f9]
[2024/11/06 20:46:38.185 +08:00] [INFO] [refresher.go:187] ["No tables to analyze"] [category=stats] [sampled=]
[2024/11/06 20:49:32.187 +08:00] [INFO] [queue.go:322] ["Start to fetch DML changes of jobs"] [category=stats] [sampled=]

```

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by AilinKid — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
