### PR TITLE
DDL: use new PD API to get TiFlash replica table regionCount

### LINKED ISSUE #38570: Get TiFlash replica table region count by PD new API /pd/api/v1/stats/region\?count
## Enhancement
After this [PR](https://github.com/tikv/pd/pull/5610) merged, TiDB can get TiFlash replica table region count by PD new API `/pd/api/v1/stats/region\?count` to reduce the overhead of PD when there are many regions.

### PR DESCRIPTION
**Pull request by hehechen**
Signed-off-by: hehechen <chentongli@pingcap.com>

### What problem does this PR solve?

Issue Number: close #38570

Problem Summary:
If the table with TiFlash replica has many regions, such as more than 1 million, the `/pd/api/v1/stats/region` called to get region count will bring large overhead to the PD and may affect OLTP workload.
### What is changed and how it works?
use new PD API `/pd/api/v1/stats/region?count` to get TiFlash replica table regionCount
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Create table, split 1 million regions, set TiFlash replica 1.
Before modified, flame graph of PD:
image
After modified, flame graph of PD:
image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by hehechen** [comment]
cc @breezewish @crazycs520 @CalvinNeo

**Review by CalvinNeo — APPROVED** [review]
lgtm

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
