### PR TITLE
 *: replace 'logutil.Logger(context.Background())' with 'logutil.BgLogger()'

### PR DESCRIPTION
**Pull request by lonng**
### What problem does this PR solve? 

Lots of code snippets use `logutil.Logger(context.Background())'` to retrieve a logger and no necessary extra cost will consume in `logutil.Logger` function. 

This PR adds a simple function which returns a global logger directly.

1. The simple function will be inlined at the call site to eliminate the cost.
2. Eliminate the virtual function call cost of `ctx.Value()`

### What is changed and how it works?

1. Define the function `logutil.BgLogger()`
2. Replace 'logutil.Logger(context.Background())' with 'logutil.BgLogger()' 
3. Fix imports

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by lonng** [comment]
@tiancaiamao @winkyao PTAL

**Comment by winkyao** [comment]
@lonng Well done.

**Pull request merged**
