### PR TITLE
expression: fix binary str numeric result type

### LINKED ISSUE #27698: varbinary + int should be double
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
create table tg(a varbinary(10));
insert into tg values ("123458.12");
select 1+a from tg;
```

### 2. What did you expect to see? (Required)
123459.12
### 3. What did you see instead (Required)
123459
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by solotzg**
### What problem does this PR solve?

Issue Number: close #27698

Problem Summary:

wait for https://github.com/pingcap/tidb-test/pull/1890

### What is changed and how it works?

- add func `isConstantBinaryLiteral` to check if expr is constant binary literal
- if expression is constant binary literal, like `0x1234`, `0b00011`, cast to integer
- for other binary str column related expression, like `varbinary` or `blob`, cast to double.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix a bug that TiDB use wrong numeric result type when handling binary string.
```

### CODE REVIEW

**Comment by solotzg** [comment]
@guo-shaoge @XuHuaiyu  PTAL

**Review by guo-shaoge — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Comment by BornChanger** [comment]
@solotzg  please fix the regression your pr brought according to @Willendless's comment in https://github.com/tikv/tikv/pull/13031#issuecomment-1190415668.

**Pull request merged**
