### PR TITLE
executor: support 'SHOW CONFIG' syntax to show configs of PD and TiKV instances

### LINKED ISSUE #16229: support 'SHOW CONFIG' syntax to show configs of PD and TiKV instances
## Feature Request

**Describe the feature you'd like:**

After implementing this proposal(https://github.com/pingcap/tidb/pull/13660), TiKV and PD support to dynamic configs.
Now we can get PD and TiKV instances' configs from PD according to `pd-ctl`.
Using `pd-ctl` is not convenient for our user, so we need to support to show configs by SQL.

After discussing, we decide to support these syntaxes:
1. show config [where ...]

For example: 
1. show config
2. show config where type="tikv"

Our parser has already supported this syntax now.(https://github.com/pingcap/parser/issues/768)

**Teachability, Documentation, Adoption, Migration Strategy:**

https://github.com/pingcap/tidb/pull/13660

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #16229 

Problem Summary: support `SHOW CONFIG` syntax to show configs of PD and TiKV instances

### What is changed and how it works?
When processing `SHOW CONFIG`, the `ShowExec` fetches all configs from `PD` and show them to the user.

After this PR:
```
mysql> show config where type='pd' and name like '%log.file%';
+------+----------------+----------------------+-------+
| Type | Instance       | Name                 | Value |
+------+----------------+----------------------+-------+
| pd   | 127.0.0.1:2379 | log.file.filename    |       |
| pd   | 127.0.0.1:2379 | log.file.max-backups | 0     |
| pd   | 127.0.0.1:2379 | log.file.max-days    | 0     |
| pd   | 127.0.0.1:2379 | log.file.max-size    | 0     |
+------+----------------+----------------------+-------+
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by overvenus** [comment]
LGTM

**Comment by qw4990** [comment]
> Could you add some integration tests?

One unit test is added. PTAL.

**Pull request merged**
