### PR TITLE
*: fix linter WIP

### PR DESCRIPTION
**Pull request by Tjianke**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- fix linter WIP

### CODE REVIEW

**Comment by xiongjiwei** [comment]
This PR is too big, and there are many other `PRs`  do the job. I think we can close this PR, right? @Tjianke

**Comment by Tjianke** [comment]
> This PR is too big, and there are many other `PRs` do the job. I think we can close this PR, right? @Tjianke

Sure

**Pull request closed without merging**
