### PR TITLE
meta/autoid: show auto_inc allocator only when cache = 1

### LINKED ISSUE #55615: `SHOW TABLE NEXT_ROW_ID` display incorrect allocators
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table t (a int primary key auto_increment, b int);
Query OK, 0 rows affected (0.18 sec)

mysql> show table t next_row_id;
```

### 2. What did you expect to see? (Required)

```
mysql> show table t next_row_id;
+---------+------------+-------------+--------------------+----------------+
| DB_NAME | TABLE_NAME | COLUMN_NAME | NEXT_GLOBAL_ROW_ID | ID_TYPE        |
+---------+------------+-------------+--------------------+----------------+
| test    | t          | a           |                  1 | _TIDB_ROWID    |
+---------+------------+-------------+--------------------+----------------+
```

### 3. What did you see instead (Required)

```
mysql> show table t next_row_id;
+---------+------------+-------------+--------------------+----------------+
| DB_NAME | TABLE_NAME | COLUMN_NAME | NEXT_GLOBAL_ROW_ID | ID_TYPE        |
+---------+------------+-------------+--------------------+----------------+
| test    | t          | a           |                  1 | _TIDB_ROWID    |
| test    | t          | a           |                  1 | AUTO_INCREMENT |
+---------+------------+-------------+--------------------+----------------+
2 rows in set (36.70 sec)
```

### 4. What is your TiDB version? (Required)

1bf01f4108

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #55615

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]
remember to leave some good-first-issue for new developers

**Review by zimulala — APPROVED** [review]
LGTM

**Pull request merged**
