### PR TITLE
statistics: make sure the PQ can be re-initialized

### PR DESCRIPTION
**Pull request by Rustin170506**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/55906

Problem Summary:

### What changed and how does it work?

In the following scenario:

1. In a three-node cluster, node1 initially becomes the stats owner and starts and initializes the PQ.
2. Due to network or etcd issues, an owner re-election occurs.
3. Node2 becomes the stats owner, starting and initializing the PQ, while node1 shuts down the PQ.
4. Another issue triggers a re-election.
5. Node1 is re-elected as the owner. However, because we forgot to reset `pq.syncFields.initialized`, it can no longer properly start or reinitialize the PQ.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test https://github.com/pingcap/tidb/pull/57194#issuecomment-2461582368
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Comment by Rustin170506** [comment]
> Should we add the manual test step in comment ?

I will post my test report later on GitHub. There is no way to public the lark wiki to the public.

**Review by elsa0520 — APPROVED** [review]
LGTM

**Comment by Rustin170506** [comment]
/hold

I will post the test step here.

**Review by qw4990 — APPROVED** [review]

**Comment by Rustin170506** [comment]
The test step:

### Injecting Network Issues for Stats Owner Testing

1. **Check Current Stats Owner**  
   - Current stats owner is identified.
   - Example log entries:
     ```
     [INFO] [queue.go:645] ["Last analysis duration refreshed"] [category=stats] [duration=13.153µs]
     [INFO] [queue.go:321] ["Start to request must retry jobs"] [category=stats]
     [INFO] [queue.go:612] ["Must retry jobs requeued"] [category=stats] [duration=5.16µs]
     [INFO] [queue.go:315] ["Start to fetch DML changes of jobs"] [category=stats]
     [INFO] [queue.go:337] ["DML changes processed"] [category=stats] [duration=118.752964ms]
     [INFO] [queue.go:312] ["Priority queue stopped"] [category=stats]
     ```

2. **Switch Stats Owner**  
   - New stats owner is assigned.
   - Example log entries:
     ```
     [INFO] [queue.go:136] ["Priority queue initialized"] [category=stats] [duration=51.638362416s]
     [INFO] [queue.go:315] ["Start to fetch DML changes of jobs"] [category=stats]
     [INFO] [queue.go:337] ["DML changes processed"] [category=stats] [duration=120.802913ms]
     ```

3. **Inject Network Issues**  
   - Block network communication on the designated port.
   - Example commands:
     ```bash
     iptables -A INPUT -p tcp -s <NODE_1_IP> --sport 8889 -j DROP
     iptables -A INPUT -p tcp -s <NODE_2_IP> --sport 8889 -j DROP
     iptables -A OUTPUT -p tcp -d <NODE_1_IP> --dport 8889 -j DROP
     iptables -A OUTPUT -p tcp -d <NODE_2_IP> --dport 8889 -j DROP
     ```

4. **Verify New Stats Owner**  
   - Check if the correct node starts the Priority Queue (PQ).
   - Example log entries:
     ```
     [INFO] [queue.go:312] ["Priority queue stopped"] [category=stats]
     [INFO] [queue.go:136] ["Priority queue initialized"] [category=stats] [duration=52.177676874s]
     ```

**Pull request merged**
