### PR TITLE
ttl: make the TTL compatible with dumpling, lightning and BR 

### LINKED ISSUE #40215: Turn off `TTL_ENABLE` when restore TTL tables with lighting or BR

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #40215

### What is changed and how it works?

When backup/restore a table with TTL options, for example:

```
CREATE TABLE t(t timestamp) TTL=`t` + INTERVAL 1 DAY
```

The behaviors of the below tools:

- dumpling: same with `show create output`:

```
CREATE TABLE `t` (
  `t` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin /*T![ttl] TTL=`t` + INTERVAL 1 DAY */ /*T![ttl] TTL_ENABLE='ON' */
```

- lighting: restore with `TTL_ENABLE` OFF:

```
CREATE TABLE `t` (
  `t` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin /*T![ttl] TTL=`t` + INTERVAL 1 DAY */ /*T![ttl] TTL_ENABLE='OFF' */
```

- BR: restore with `TTL_ENABLE` OFF:

```
CREATE TABLE `t` (
  `t` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin /*T![ttl] TTL=`t` + INTERVAL 1 DAY */ /*T![ttl] TTL_ENABLE='OFF' */
```

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
BR/lightning will force restore a TTL table with `TTL_ENABLE='OFF'`
```

### CODE REVIEW

**Comment by joccau** [comment]
https://github.com/pingcap/tidb/blob/32f9604345e7b176ef8b003a02516c96b511636e/br/pkg/task/stream.go#L1201
Should modify here:
```
if tableInfo.TTLInfo != nil{
    tableInof.TTLInfo.Enable = false
}
```

**Review by joccau — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
