### PR TITLE
ddl: use the individual infosyncer for each attributes test

### LINKED ISSUE #27892: Unstable test testDBSuite8.TestRecoverTable
## Bug Report

Please answer these questions before submitting your issue. Thanks!

```
[2021-09-08T10:32:20.520Z] FAIL: attributes_sql_test.go:183: testDBSuite8.TestRecoverTable

[2021-09-08T10:32:20.520Z] 

[2021-09-08T10:32:20.520Z] attributes_sql_test.go:231:

[2021-09-08T10:32:20.520Z]     // check partition p0's rule

[2021-09-08T10:32:20.520Z]     c.Assert(rows1[1][0], Equals, "schema/test/t1/p0")

[2021-09-08T10:32:20.520Z] ... obtained string = "schema/test/t2"

[2021-09-08T10:32:20.520Z] ... expected string = "schema/test/t1/p0"
```

### 1. Minimal reproduce step (Required)

https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/32090/pipeline/62

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Trying to fix #27892 #28020 #29734

Problem Summary: There are some unstable tests in region label testing. 

### What is changed and how it works?

What's Changed: This PR is trying to make the tests stable by using the individual `infosyncer` for each attributes test. Also, the PR renames the table names so that we can locate the problem easier.

### Check List 

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by djshow832** [comment]
It seems that you are not sure about the reason, right?

**Comment by rleungx** [comment]
I'm going to use SerialSuites for these attributes tests. @djshow832

**Review by Defined2014 — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
