### PR TITLE
session: Add failpoint session/beforeLoockKeys

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What problem does this PR solve?

Problem Summary: Currently it's not very easy to construct a case in test that can stably get `Running` state transactions in TIDB_TRX tables. This PR adds a failpoint at a place just before starting acquiring locks. This helps in integration tests.

### What is changed and how it works?

What's Changed: Adds failpoint `github.com/pingcap/tidb/session/beforeLockKeys`

### Check List 

Tests 

- [ ] Integration test

Side effects

- None
Documentation

- None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by longfangsong** [comment]
> Currently it's not very easy to construct a case in test that can stably get `Running` state transactions in TIDB_TRX tables. 

Can `github.com/pingcap/tidb/session/mockStmtSlow` (though might need a better name) archieve this goal?

**Comment by MyonKeminta** [comment]
> > Currently it's not very easy to construct a case in test that can stably get `Running` state transactions in TIDB_TRX tables.
> 
> Can `github.com/pingcap/tidb/session/mockStmtSlow` (though might need a better name) archieve this goal?

Its problem is that it also blocks the query to TIDB_TRX.

**Review by longfangsong — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Review by vivid392845427 — APPROVED** [review]

**Pull request merged**
