### PR TITLE
planner: hide the switch of dynamic-pruning and global-stats

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary: planner: hide the switch of dynamic-pruning and global-stats

### What is changed and how it works?

planner: hide the switch of dynamic-pruning and global-stats since these two features are not GA.

### Check List 

Tests 

- Unit test

### Release note 

- planner: hide the switch of dynamic-pruning and global-stats

### CODE REVIEW

**Review by Reminiscent — APPROVED** [review]
/LGTM

**Review by winoros — APPROVED** [review]

**Pull request merged**
