### PR TITLE
import: copy datum values when read first N rows

### LINKED ISSUE #37726: Lightning: All Rows Returned From `ReadFirstNRows` Are the Same for Parquet Data Source
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

* Prepare a parquet data source
* Use Lightning pre info getter's ReadFirstNRowsByTableName to preview the data

### 2. What did you expect to see? (Required)
The correct row data is returned

### 3. What did you see instead (Required)
All the row data are the same

### 4. What is your TiDB version? (Required)
Latest version

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: close #37726 

Problem Summary:

### What is changed and how it works?
When fetched the datum values slice, create a new slice with a copy of these datums, and append the new slice into the result.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by D3Hunter — APPROVED** [review]

**Comment by dsdashun** [comment]
BR integration test passed: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_br_test/detail/tidb_ghpr_integration_br_test/10440/

**Review by niubell — APPROVED** [review]
LGTM

**Pull request merged**
