### PR TITLE
*: move aggregate functions to an individual package "aggregation"

### PR DESCRIPTION
**Pull request by zz-jason**

### CODE REVIEW

**Comment by zz-jason** [comment]
@coocood @XuHuaiyu @hanfei1991 PTAL

**Comment by hanfei1991** [comment]
it's better to make aggregation a sub-package of expression.

**Comment by XuHuaiyu** [comment]
nothing be modified, just a movement?

**Comment by zz-jason** [comment]
@XuHuaiyu 
1. export `expression.pbConverter` to `expression.PbConverter`
2. export `PbConverter.ExprToPB()`
3. rename `expression.AggregationFunction` to `aggregation.Aggregation` to make check happy

others are just code movements

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Pull request merged**
