### PR TITLE
store/mockstore: migrate test-infra to testify for some files

### PR DESCRIPTION
**Pull request by unconsolable**
### What problem does this PR solve?

Issue Number: ref #27652

### What is changed and how it works?

- Migrate test predicates to testify

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by unconsolable** [comment]
/cc @tisonkun 
PTAL

**Review by tisonkun — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Comment by disksing** [comment]
Hi @unconsolable I updated the Pull Request title to make it more readable.

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
@unconsolable thanks for your contribution and @disksing thanks for your review.

@disksing could you help on merging this PR?

**Pull request merged**
