### PR TITLE
server: migrate test-infra to testify for server/util_test.go

### LINKED ISSUE #27808: migrate test-infra to testify for `server/util_test.go`
This is a subtask of #26863

### PR DESCRIPTION
**Pull request by yedamao**
### What problem does this PR solve?

Issue Number: close #27808 

### Release note 

```release-note
None.
```

### CODE REVIEW

**Comment by tisonkun** [comment]
Thanks for your contribution @yedamao ! I'm reviewing now.

**Review by tisonkun — APPROVED** [review]

**Review by morgo — APPROVED** [review]

**Pull request merged**
