### PR TITLE
executor: global kill 32bits (server ID part)

### PR DESCRIPTION
**Pull request by pingyu**
### What problem does this PR solve?

Issue Number: ref #8854

This PR is the server ID part of #25385

Design of global kill: https://github.com/pingcap/tidb/blob/master/docs/design/2020-06-01-global-kill.md

Problem Summary:

### What is changed and how it works?

- Add config item `able-32bits-connection-id`.
- Propose 32 bits server ID.
- Allocate 32 bits global connection ID.

### Check List

Tests 

- [x] Unit test
- [x] Integration test

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Support 32 bits global connection ID to enable kill connection by CTRL-C.
```

### CODE REVIEW

**Review by breezewish — APPROVED** [review]
Just naming recommendation. How about something like `EnableCompatGlobalKill` (enable mysql-client compatible global kill)? It sounds more user-oriented.

**Review by xuyifangreeneyes — APPROVED** [review]

**Pull request merged**
