### PR TITLE
*: Move privilege checking from ddl to stmts

### PR DESCRIPTION
**Pull request by shenli**
Make ddl.go clean
Fix https://github.com/pingcap/tidb/issues/557
@siddontang

### CODE REVIEW

**Comment by siddontang** [comment]
adding test later?

**Comment by shenli** [comment]
Unit test is here: https://github.com/pingcap/tidb/blob/master/privilege/privileges/privileges_test.go#L236

**Comment by siddontang** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
