### PR TITLE
metrics: refine metrics of infoschema

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: ref #46524

Problem Summary: refine metrics of infoschema

### What is changed and how it works?

- Remove duplicate metrics panel `Load Schema Duration`
- `Load Schema OPS` add information about load snapshot schema, it's important to diagnose problem for stale read request.
- Add `Schema Cache OPS` metric panel.

Before this PR:

image

This PR: 

image

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@xhebox @zimulala PTAL

**Review by zimulala — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]

**Pull request merged**
