### PR TITLE
metrics: add grafana and alertmanager scripts

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve? 
Maintain the grafana and alert manager scripts in TiDB repo. There are some scripts in overview.json, I don't know how to maintain them.

### What is changed and how it works?
Add grafana and alert manager scripts.

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by bb7133** [comment]
Do we need to cherry-pick this PR?

**Comment by jackysp** [comment]
> Do we need to cherry-pick this PR?

PTAL @tennix

**Comment by jackysp** [comment]
> > Do we need to cherry-pick this PR?
> 
> PTAL @tennix

I don't think so. PTAL @qiffang

**Pull request merged**
