### PR TITLE
executor: avoid unnecessary string EqualFold() comparisons

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Problem Summary: A profiling shows that strings.EqualFold consumes a lot of CPU time under a more frequent write load.

image

### What is changed and how it works?

What's Changed:  This PR reduces the case-insensitive comparisions.

### Related changes

NA

### Check List 

Tests 

- Unit test
- Integration test

Side effects

NA

### Release note 

- No release note

### CODE REVIEW

**Review by AilinKid — APPROVED** [review]
LGTM

**Comment by AilinKid** [comment]
Better put the svg profile in the description, it's more persuasive

**Review by djshow832 — APPROVED** [review]

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
