### PR TITLE
parser: fix function as identifier in TiDB is not compatible with Mysql

### LINKED ISSUE #30556: Function as identifier in Tidb is not compatible with Mysql(5.7 and 8.0)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
set SQL_MODE='';
drop table if exists  ADDDATE;
create table ADDDATE(a int); 
drop table ADDDATE;
create table ADDDATE (a int);

-- Tidb is treating function ADDDATE as identifer only when a blank space is given in  between ADDDATE (a int);
--Similar functions :
--SESSION_USER	
--SUBDATE
--SYSTEM_USER
```

### 2. What did you expect to see? (Required)
```sql
mysql> create table ADDDATE(a int); 
Query OK, 0 rows affected (0.01 sec)

mysql> drop table ADDDATE;
Query OK, 0 rows affected (0.00 sec)

mysql> create table ADDDATE (a int);
Query OK, 0 rows affected (0.01 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> create table ADDDATE(a int); 
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 20 near "ADDDATE(a int)" 
mysql> drop table ADDDATE;
ERROR 1051 (42S02): Unknown table 'test.ADDDATE'
mysql> create table ADDDATE (a int);
Query OK, 0 rows affected (0.00 sec)
```
### 4. What is your TiDB version? (Required)
```sql 
| Release Version: v5.4.0-alpha-264-g6efa36df6
Edition: Community
Git Commit Hash: 6efa36df6cff325106f67ecfe3d79816ba37ca6a
Git Branch: master
UTC Build Time: 2021-11-29 16:57:51
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

Issue Number: close #30556

Problem Summary:
Although MySQL declares in https://dev.mysql.com/doc/refman/8.0/en/function-resolution.html that the functions are recognized as functions for `create table x()`, 4 of them are still recognized as functions:
- `ADDDATE` and `SUBDATE`
- `SESSION_USER` and `SYSTEM_USER`

Which makes TiDB incompatible with MySQL.

For the case of `select x ()`, it's complicated: TiDB won't report errors for some of them but MySQL does. This incompatibility won't bring any problems. Instead, if we change it, it will break compatibility.

### What is changed and how it works?

- Remove the 4 functions from `btFuncTokenMap`
- Remove `builtinAddDate` and `builtinSubDate`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by djshow832** [comment]
What do you think of it? Do we merge this PR or do we just update the MySQL tests in the issue? @morgo @tangenta

**Comment by morgo** [comment]
> What do you think of it? Do we merge this PR or do we just update the MySQL tests in the issue? @morgo @tangenta

LGTM. It is hard to predict users with reserved words, so I think it is worth making it more compatible.

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by bb7133** [comment]
PTAL @morgo

**Review by morgo — APPROVED** [review]

**Pull request merged**
