### PR TITLE
vendor: update goleveldb to fix a data race

### PR DESCRIPTION
**Pull request by tiancaiamao**
```
WARNING: DATA RACE
Write at 0x00c42226bb60 by goroutine 113:
  runtime.closechan()
      /usr/local/go/src/runtime/chan.go:320 +0x0
  github.com/pingcap/goleveldb/leveldb.(*DB).mpoolDrain()
      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/_vendor/src/github.com/pingcap/goleveldb/leveldb/db_state.go:104 +0x1a2

Previous read at 0x00c42226bb60 by goroutine 27:
  runtime.chansend()
      /usr/local/go/src/runtime/chan.go:128 +0x0
  github.com/pingcap/goleveldb/leveldb.(*DB).mpoolPut()
      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/_vendor/src/github.com/pingcap/goleveldb/leveldb/db_state.go:74 +0x8e
  github.com/pingcap/goleveldb/leveldb.(*memDB).decref()
      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/_vendor/src/github.com/pingcap/goleveldb/leveldb/db_state.go:37 +0x26d
  github.com/pingcap/goleveldb/leveldb.(*DB).memCompaction()
      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/_vendor/src/github.com/pingcap/goleveldb/leveldb/db_compaction.go:347 +0xb66
  github.com/pingcap/goleveldb/leveldb.(*DB).mCompaction()
      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/_vendor/src/github.com/pingcap/goleveldb/leveldb/db_compaction.go:755 +0x1d7
```

`make update` removed many unrelated files, maybe somebody didn't update vendor in a proper way last time.

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by lamxTyler** [comment]
etcd/contrib/recipes should not be removed, as it is used by this [pr](https://github.com/pingcap/tidb/pull/4346)

**Pull request merged**
