### PR TITLE
*: adapt new api for the executor package (#22644)

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Problem Summary: cherry pick #22644

### Check List 

Tests 

- Unit test
- Integration test
- No code

### Release note 

- No release note

### CODE REVIEW

**Review by bb7133 — COMMENTED** [review]
LGTM

**Comment by xhebox** [comment]
> LGTM

@bb7133 The new bot does not react to `LGTM` anymore. Need a slash.

**Pull request merged**
