### PR TITLE
parser: support do some adminStmt in read-only mode

### LINKED ISSUE #37631: `tidb_restricted_read_only = on` will block `admin show ddl jobs`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set global tidb_restricted_read_only = on;
admin show ddl jobs
```

### 2. What did you expect to see? (Required)
admin show ddl jobs success

### 3. What did you see instead (Required)
```sql
MySQL [(none)]> admin show ddl jobs;
ERROR 1836 (HY000): Running in read-only mode
MySQL [(none)]>
```
flashback command has no response 

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #37631 
Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
support some adminStmt in read-only mode
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by xhebox — CHANGES_REQUESTED** [review]
`TestAdminShowDDLJobs` failed

**Review by tangenta — APPROVED** [review]

**Comment by Defined2014** [comment]
> `TestAdminShowDDLJobs` failed

Fixed.

**Review by hawkingrei — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
