### PR TITLE
store/tikv: fix unstable tests in snapshot_fail_test.go

### PR DESCRIPTION
**Pull request by sticnarf**
### What problem does this PR solve?

Failures like https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/65623/pipeline

The `k4` written by `TestRetryPointGetWithTS` may affect other tests.

And it's also important to remove `asyncCommitDoNothing` failpoint a bit later **after the point get assertion**. Otherwise, the transaction might not be affected by the failpoint if it didn't run to the failpoint before the failpoint is removed.

### What is changed and how it works?

Delete `k4` after running `TestRetryPointGetWithTS`. 

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note.

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Comment by hi-rustin** [comment]
@sticnarf  Please fix the staticcheck issues.

**Pull request merged**
