### PR TITLE
*: format the error message when query/instance exceeds memory quota

### LINKED ISSUE #42044: Refine the error message of `Out Of Memory Quota`
## Enhancement
The error message `Out Of Memory Quota` indicates that a query is canceled by tidb-server. 
The error message always confused the customers. They thought tidb-server crashed because of OOM when getting this message.

We'd better refine the error message. This error message will be threw in 2 cases:
1.  Memory usage of one single query exceeds tidb_mem_quota_query.
2. Memory usage of the tidb-server instance exceeds tidb_server_memory_limit, the query using the most memory will be canceled.

We can change the error messages to the follwing messages for these 2 individual cases:

Error message 1: Your query has been cancelled due to exceeding the allowed memory limit for a single SQL query. Please try narrowing your query scope or increase the tidb_mem_quota_query limit and try again.
Error message 2: Your query has been cancelled due to exceeding the allowed memory limit for the tidb-server instance and this query is currently using the most memory. Please try narrowing your query scope or increase the tidb_server_memory_limit and try again.

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve?

Issue Number: close #42044

Problem Summary:

### What is changed and how it works?
As described in the issue description.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Refine the error message when a query is killed because of exceeding the memory limit. When a query is killed because of exceeding `tidb_mem_quota_query`, error message `Your query has been cancelled due to exceeding the allowed memory limit for a single SQL query. Please try narrowing your query scope or increase the tidb_mem_quota_query limit and try again.` will be returend. When a query is killed because of the instance memory exceeds `tidb_server_memory_limit`, error message `Your query has been cancelled due to exceeding the allowed memory limit for the tidb-server instance and this query is currently using the most memory. Please try narrowing your query scope or increase the tidb_server_memory_limit and try again.` will be returned.
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
@XuHuaiyu  Please fix it.

```
executor/adapter_test.go:1:1: 

--- executor/index_merge_reader_test.go

+++ executor/index_merge_reader_test.go

@@ -16,7 +16,6 @@

 

 import (

 	"fmt"

-	"github.com/pingcap/tidb/util/memory"

 	"math/rand"

 	"regexp"

 	"strconv"

@@ -28,6 +27,7 @@

 	"github.com/pingcap/tidb/testkit"

 	"github.com/pingcap/tidb/testkit/testutil"

 	"github.com/pingcap/tidb/util"

+	"github.com/pingcap/tidb/util/memory"

 	"github.com/stretchr/testify/require"

 	"golang.org/x/exp/slices"

 )

 (gci)

```

**Review by jackysp — APPROVED** [review]

**Comment by hawkingrei** [comment]
```
--- FAIL: TestPartitionAddPanic (2.79s)

panic: Out Of Memory Quota! [recovered]

	panic: Out Of Memory Quota! [recovered]

	panic: Out Of Memory Quota!


goroutine 145 [running]:

testing.tRunner.func1.2({0x4aa47a0, 0x58f1930})

	GOROOT/src/testing/testing.go:1526 +0x24e

testing.tRunner.func1()

	GOROOT/src/testing/testing.go:1529 +0x39f

panic({0x4aa47a0, 0x58f1930})

	GOROOT/src/runtime/panic.go:884 +0x213

github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1()

	executor/adapter.go:459 +0x55a

panic({0x4aa47a0, 0x58f1930})

	GOROOT/src/runtime/panic.go:884 +0x213

github.com/pingcap/tidb/ddl.checkPartitionByRange({0x5995fd0, 0xc0059f6a00}, 0xc005a18b60)

	ddl/ddl_api.go:2862 +0xfc

github.com/pingcap/tidb/ddl.checkPartitionDefinitionConstraints({0x5995fd0, 0xc0059f6a00}, 0xc005a18b60)

	ddl/ddl_api.go:2154 +0x137

github.com/pingcap/tidb/ddl.(*ddl).AddTablePartitions(0xc005a8e2a0, {0x5995fd0?, 0xc0059f6a00}, {{{0x518fc98, 0x4}, {0x518fc98, 0x4}}, {{0x5288294, 0x1}, {0x5288294, ...}}}, ...)

	ddl/ddl_api.go:3899 +0x6ad

github.com/pingcap/tidb/ddl.(*ddl).AlterTable(0xc005a8e2a0, {0x5928738, 0xc0088a4000}, {0x5995fd0, 0xc0059f6a00}, 0x5288294?)

	ddl/ddl_api.go:3354 +0x2730

github.com/pingcap/tidb/executor.(*DDLExec).executeAlterTable(0xc008cc8630, {0x5928738, 0xc0088a4000}, 0xc008860000)

	executor/ddl.go:384 +0x10f

github.com/pingcap/tidb/executor.(*DDLExec).Next(0xc008cc8630, {0x5928738?, 0xc0007c1fb0?}, 0x1?)

	executor/ddl.go:148 +0x2f3

github.com/pingcap/tidb/executor.Next({0x5928738, 0xc0007c1fb0}, {0x592bf40, 0xc008cc8630}, 0xc008cccff0)

	executor/executor.go:326 +0x302

github.com/pingcap/tidb/executor.(*ExecStmt).next(0xc005e55e00, {0x5928738, 0xc0007c1fb0}, {0x592bf40, 0xc008cc8630}, 0xc1080c2492edb945?)

	executor/adapter.go:1194 +0x7e

github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor(0xc005e55e00, {0x5928738?, 0xc0007c1fb0?}, {0x592bf40?, 0xc008cc8630})

	executor/adapter.go:939 +0x3f9

github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay(0xc005e55e00, {0x5928738, 0xc0007c1fb0}, {0x592bf40?, 0xc008cc8630?}, 0x0)

	executor/adapter.go:764 +0x29d

github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc005e55e00, {0x5928738, 0xc0007c1fb0})

	executor/adapter.go:564 +0xe58

github.com/pingcap/tidb/session.runStmt({0x5928738, 0xc0007c1ad0}, 0xc0059f6a00, {0x5935a90, 0xc005e55e00?})

	session/session.go:2347 +0x5a2

github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc0059f6a00, {0x5928738?, 0xc0007c1ad0?}, {0x593c988?, 0xc008860000?})

	session/session.go:2204 +0xf87

github.com/pingcap/tidb/testkit.(*TestKit).ExecWithContext(0xc008ccc8c0, {0x5928738, 0xc0007c1ad0}, {0x5288288, 0x41}, {0x0, 0x0, 0x0})

	testkit/testkit.go:324 +0x6b5

github.com/pingcap/tidb/testkit.(*TestKit).Exec(0x5915848?, {0x5288288, 0x41}, {0x0, 0x0, 0x0})

	testkit/testkit.go:297 +0x8f

ddl/failtest/failtest_test_test.TestPartitionAddPanic(0xc0009ee000)

	ddl/failtest/fail_db_test.go:581 +0x168

testing.tRunner(0xc0009ee000, 0x52fc570)

	GOROOT/src/testing/testing.go:1576 +0x10b

created by testing.(*T).Run

	GOROOT/src/testing/testing.go:1629 +0x3ea

--

```

**Pull request merged**
