### PR TITLE
aggfuncs: migrate test-infra to testify for executor/aggfuncs #28074

### LINKED ISSUE #28074: migrate test-infra to testify for `executor/aggfuncs`
* [x] #28501
* [x] #28504
* [x] #28505
* [x] #28506
* [x] #28507
* [x] #28508
* [x] #28509
* [x] #28510
* [x] #28511
* [x] #28512
* [x] #28513
* [x] #28514
* [x] #28515
* [x] #28516
* [x] #28517
* [x] #28518
* [x] #28519
* [x] #28520
* [x] #28521
* [x] #28522
* [x] #28523
* [x] #28503
* [x] #28502

### PR DESCRIPTION
**Pull request by Fajrinmk**
### What problem does this PR solve?

Issue Number: close #28074

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
Hi @Fajrinmk ! As the original task has been broken down into subtasks, as well as #28502 gets its own assignee, I'd suggest you to migrate test one issue by another.

Also please take a look at https://github.com/pingcap/tidb/pull/28526#issuecomment-931879437, where I already mentioned that:

> I'd prefer to see multiple PRs one for a dedicated issue instead of a huge PR contains "everything" and hard to review especially with a large number of line changes.

**Comment by tisonkun** [comment]
We encourage multiple PRs easy to review rather than one PR for everything.

If you want to take most of the work, you can resolve #28501 first.

**Comment by tisonkun** [comment]
Even if you want to do it as a whole, you should comment at #28074 first and ask for terminating all subtasks, instead of moving forward alone and force others to catch up with you. Given #28052 assigned to others, I tend to keep the shape we resolve them one by one.

**Comment by Fajrinmk** [comment]
ah okay, my bad, will close this

**Comment by tisonkun** [comment]
Thanks for your understanding!

**Pull request closed without merging**
