### PR TITLE
metric: record prepare execute fail as "Failed Query OPM" in monitor (#22596)

### LINKED ISSUE #17345: Execute Error in prepare stmt didn't report as Failed Query OPM in Granafa
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

execute fail with prepare

### 2. What did you expect to see? (Required)

see it in Failed Query OPM in Granafa and trigger alter

### 3. What did you see instead (Required)

no point and no altert

### 4. Affected version (Required)

my version is 3.0.13 maybe exits in higher version

### 5. Root Cause Analysis

bug

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #22596 to release-5.0-rc
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/22673
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/22673:release-5.0-rc-4e4968c50182
```

---

Signed-off-by: lysu <sulifx@gmail.com>

### What problem does this PR solve?

Issue Number: close #17345

Problem Summary:

prepared stmt's execute fail doesn't be recorded in Failed OPM monitor.

but DBA or alert system need rely on it.

### What is changed and how it works?

What's Changed, How it Works:

record metric in handleStmtExec

### Related changes

- Need to cherry-pick to the release branch 

### Check List 

Tests 

- No code (only metric)

Side effects

- n/a
- 
### Release note 

- Record prepare execute fail as "Failed Query OPM" in monitor

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/22596)

### CODE REVIEW

**Review by xhebox — COMMENTED** [review]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Comment by bb7133** [comment]
After talking with @lysu , we agree that this PR is useful and it's better to do the backports.

**Comment by bb7133** [comment]
LGTM

**Pull request closed without merging**
