### PR TITLE
*: use sync.Pool to improve the performance of insert statement

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve? 
There are too many temporary memory allocations in the insert statement.

### What is changed and how it works?
1. Use sync.Pool to improve the performance of insert statement.
1. Avoid `CloneRow` for insert select statement.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

 - Possible performance regression

### CODE REVIEW

**Comment by tiancaiamao** [comment]
This kind of change makes the code much more difficult to maintain without getting a large performance bonus. It's not worthy.
PTAL @coocood

**Comment by jackysp** [comment]
We could try it with `insert select` statement. @tiancaiamao

**Comment by tiancaiamao** [comment]
The use of `sync.Pool` doesn't make sense.
However, this change matters:

```
for _... {
   rows = append(rows)
}
exec(rows)
```

to 

```
for _ ... {
    rows = append(rows)
    if len(rows) > xxx {
        exec(rows)
        rows = rows[:0]
    }
}
```

This is because the intermediate data in []Datum format waste much more memory.

**Comment by coocood** [comment]
I think a datum slice doesn't worth to use a `sync.Pool`.

**Pull request closed without merging**
