### PR TITLE
statistics: add new DDL event for stats handler

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/48126#issuecomment-1794362183

Problem Summary:

### What is changed and how it works?

- Added new DDL event for stats handler. You can see https://github.com/pingcap/tidb/issues/48126#issuecomment-1794362183 to check why we need these fields and information.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
🔢

**Review by qw4990 — APPROVED** [review]

**Review by time-and-fate — COMMENTED** [review]
This will replace `pkg/ddl/util/event.go`, right?

**Review by time-and-fate — APPROVED** [review]

**Pull request merged**
