### PR TITLE
types: Fix checkMonthDay() to correctly handle leap year (#10342)

### PR DESCRIPTION
**Pull request by erjiaqing**
Cherry pick #10342 to release 2.1

### CODE REVIEW

**Comment by lamxTyler** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by jackysp** [comment]
Please fix CI.

**Comment by erjiaqing** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by erjiaqing** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by erjiaqing** [comment]
@jackysp PTAL

**Pull request merged**
