### PR TITLE
infoschema, executor: Resolve bug where show index from perf_schema had no results

### LINKED ISSUE #19231: The result of `show [index/keys] from performance_schema.events_statements_summary_by_digest` is empty
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
show [index/keys] from performance_schema.events_statements_summary_by_digest
```

### 2. What did you expect to see? (Required)
It should show the index of table `performance_schema.events_statements_summary_by_digest`.

The table `performance_schema.events_statements_summary_by_digest` has index SCHEMA_NAME(SCHEMA_NAME, DIGEST). And you can confirm with the following command
```
explain select * from performance_schema.events_statements_summary_by_digest where schema_name = 'A' and digest = 'B';
```
The result of the command is
```
+-------------+---------+------+-----------------------------------------------------------------------------------+---------------+
| id          | estRows | task | access object                                                                     | operator info |
+-------------+---------+------+-----------------------------------------------------------------------------------+---------------+
| Point_Get_1 | 1.00    | root | table:events_statements_summary_by_digest, index:SCHEMA_NAME(SCHEMA_NAME, DIGEST) |               |
+-------------+---------+------+-----------------------------------------------------------------------------------+---------------+
1 row in set (0.001 sec)
```

### 3. What did you see instead (Required)
Empty set

### 4. What is your TiDB version? (Required)
Release Version: v4.0.0-beta.2-961-g4f96c8463
Edition: Community
Git Commit Hash: 4f96c8463774e4c005fe3d69ed317828023fdbd8
Git Branch: master

### PR DESCRIPTION
**Pull request by johan-j**
### What problem does this PR solve?

Issue Number: close #19231
Problem Summary:
This resolves an issue where `show [index/keys] from performance_schema.events_statements_summary_by_digest` dont return any results.

### What is changed and how it works?
perfSchemaTable inherit from infoschema.VirtualTable. VirtualTable always return 'nil' for the Indices method. This is why, the show statement did not return any results.

What's Changed:
This is solved by overriding the Indices for type perfSchemaTable, and return the indices.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List

Tests
- Unit test

### Release note 
- Resolve issue 19231: Show index/key on performance_schema returned empty result.

### CODE REVIEW

**Comment by morgo** [comment]
LGTM

**Comment by hi-rustin** [comment]
@ti-chi-bot update this pr branch

**Pull request merged**
