### PR TITLE
executor: show memory consumption in slow query log

### PR DESCRIPTION
**Pull request by qw4990**
cherry-pick for #10162.

### CODE REVIEW

**Comment by qw4990** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-integration-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by qw4990** [comment]
/run-integration-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zyguan** [comment]
/run-integration-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zyguan** [comment]
/run-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zyguan** [comment]
/run-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zyguan** [comment]
/run-integration-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
LGTM

**Pull request merged**
