### PR TITLE
bugfix: fix invalid nil ptr error in corner cases.

### LINKED ISSUE #47531: panic:runtime error: invalid memory address or nil pointer
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

dashboard页面“SQL语句分析”、“慢查询”；客户端执行`select * from cluster_processlist`

### 2. What did you expect to see? (Required)
功能正常使用

### 3. What did you see instead (Required)
SQL语句分析查询报错：
image

PD日志如下：
image

客户端查询cluster_processlist报错：
image
tidb-server日志如下：
image

进入慢查询页面，报错：
image

### 4. What is your TiDB version? (Required)

5.7.25-TiDB-v7.1.1

image

image

image

image

部署了两个集群，这个集群有问题，另一个集群没问题

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What problem does this PR solve?

Issue Number: close #47531 

Problem Summary:

### What is changed and how it works?

```
This pr fix the invalid nil pointer error in some corner cases when trying to update the slowness statistsics.
```

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by LykxSassinator** [comment]
@cfzjywxk PTAL, thx

**Comment by LykxSassinator** [comment]
/cc @cfzjywxk 

PTAL, thx

**Comment by cfzjywxk** [comment]
The bazel related information needs to be updated too.

**Review by cfzjywxk — APPROVED** [review]

**Comment by cfzjywxk** [comment]
> /ok-to-test

@hawkingrei Is there a service to geneate this information for this PR?

**Comment by LykxSassinator** [comment]
As the `client-go` repo already updated in other prs, this pr can be closed manually.

**Pull request closed without merging**
