### PR TITLE
ddl: add ddl_reorg_batch_size variable to control ddl worker batch size.

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
here is a test:
environment: 1 machine, 16G, disk is nvme. both tidb,tikv,pd in this machine.
### test add index with different batch size
```sql
set @@tidb_ddl_reorg_worker_cnt=1;  #avoid region split impact testing, so set ddl worker to only 1.
mysql root@127.0.0.1:test> select * from t_slim limit 1;
+---+---+
| a | b |
+---+---+
| 1 | 1 |
+---+---+
mysql root@127.0.0.1:test> select count(*) from t_slim; #80W rows in this table.
+----------+
| count(*) |
+----------+
| 800000   |
+----------+

# there is no other workload in tidb, only add index test.
batchCnt = 128：
mysql> alter table t_slim add index idx1(a);
Time: 139.031s

batchCnt = 512：
mysql> alter table t_slim add index idx3(a);
Time: 67.523s

batchCnt = 1024：
mysql> alter table t_slim add index idx5(a);
Time: 35.031s

batchCnt = 4096：
mysql> alter table t_slim add index idx7(a);
Time: 19.246s

batchCnt = 8192：
mysql> alter table t_slim add index idx9(a);
Time: 15.309s

batchCnt = 10240：
mysql> alter table t_slim add index idx33(a);
Query OK, 0 rows affected
Time: 13.849s

batchCnt = 20480：
mysql root@192.168.197.180:test> alter table t_slim add index idx36(a)
Query OK, 0 rows affected
Time: 11.732s

batchCnt = 40960：
mysql> alter table t_slim add index idx39(a)
Query OK, 0 rows affected
Time: 11.501s



set @@tidb_ddl_reorg_worker_cnt=16; # add more ddl worker.
batchCnt = 8192：
mysql> alter table t_slim add index idx31(a); # only 8 regions in table t_slim, so only 8 ddl worker do task, other workers is idle.
Query OK, 0 rows affected
Time: 9.831s
```

### test with transaction conflict
80W rows in table, 1 session send add index request, 20 sessions send update request, table schema is:
```
# table t_slim have 80W rows records.
mysql> select * from t_slim order by a limit 10;
+---+----+
| a | b  |
+---+----+
| 0 | 1  |
| 1 | 2  |
...
mysql> select count(*) from t_slim;
+----------+
| count(*) |
+----------+
| 800000   |
+----------+


session 0: 
mysql> alter table t_slim add index idx(a);

session 1 ~ session 20:
for{
	n = rand.Intn(800000)
	update t_slim set a=${n+1} where a=${n}; 
	sleep(10ms)
}
```
**result**
```
batchcnt=128, ddl_reorg_worker_cnt=1;
add index cost time(s):
250.118721157
279.992544007
303.099265579
269.927179136



batchcnt=8196, ddl_reorg_worker_cnt=1;
add index cost time(s):
50.934135623
56.634457149
50.81117151
50.383097911

# check how many data has been updated:
mysql> select count(*) from t_slim where (a+1) != b;
+----------+
| count(*) |
+----------+
| 440973   |
+----------+
```

Maybe next step, I wish to make tidb can auto tune the batch size according to whether there is a transaction write conflict, if no conflict, increase the batch, other wise reduce the batch size.

### What is changed and how it works?
Add a session variable.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8365)

### CODE REVIEW

**Comment by crazycs520** [comment]
@winkyao @zimulala PTAL

**Comment by crazycs520** [comment]
[svg.tar.gz](https://github.com/pingcap/tidb/files/2602444/svg.tar.gz)

**Comment by winkyao** [comment]
@crazycs520 Good job.

**Comment by winkyao** [comment]
You need to append `TiDBDDLReorgBatchSize`  to `loadCommonGlobalVarsSQL`, then the global variable can affect all the sessions.

**Comment by winkyao** [comment]
I think 4096 maybe the proper default batch size.

**Pull request merged**
