### PR TITLE
executor: fix data race at the TestShowStatsExtended

### LINKED ISSUE #44532: DATA RACE at the NewSessionStatsCollector
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
==================
WARNING: DATA RACE
Write at 0x00c065987d30 by goroutine 533768:
  github.com/pingcap/tidb/statistics/handle.(*Handle).Clear()
      statistics/handle/handle.go:470 +0x60e
  github.com/pingcap/tidb/executor_test.TestShowStatsExtended()
      executor/show_stats_test.go:283 +0xca
  github.com/pingcap/tidb/domain.(*Domain).rebuildSysVarCache()
      domain/sysvar_cache.go:146 +0x8c4
  github.com/pingcap/tidb/domain.(*Domain).LoadSysVarCacheLoop()
      domain/domain.go:1620 +0xa8
  github.com/pingcap/tidb/session.BootstrapSession()
      session/session.go:3378 +0x6d3
  github.com/pingcap/tidb/domain.(*Domain).GetSessionCache()
      domain/sysvar_cache.go:62 +0x5c
  github.com/pingcap/tidb/session.(*session).loadCommonGlobalVariablesIfNeeded()
      session/session.go:3725 +0x104
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      session/session.go:2130 +0x145
  github.com/pingcap/tidb/session.(*session).ExecuteInternal()
      session/session.go:1668 +0x31b
  github.com/pingcap/tidb/domain.(*Domain).LoadPrivilegeLoop()
      domain/domain.go:1563 +0x130
  github.com/pingcap/tidb/session.BootstrapSession()
      session/session.go:3371 +0x684
  github.com/pingcap/tidb/testkit.bootstrap()
      testkit/mockstore.go:85 +0xac
  github.com/pingcap/tidb/testkit.CreateMockStoreAndDomain()
      testkit/mockstore.go:70 +0xe9
  github.com/pingcap/tidb/executor_test.TestShowStatsExtended()
      executor/show_stats_test.go:280 +0x58
  testing.tRunner()
      GOROOT/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1629 +0x47
Previous read at 0x00c065987d30 by goroutine 561851:
  github.com/pingcap/tidb/statistics/handle.(*Handle).NewSessionStatsCollector()
      statistics/handle/update.go:238 +0x88
  github.com/pingcap/tidb/session.attachStatsCollector()
      session/session.go:3619 +0xb1
  github.com/pingcap/tidb/session.BootstrapSession.func2()
      session/session.go:3488 +0x59
  github.com/pingcap/tidb/ttl/ttlworker.getSession()
      ttl/ttlworker/session.go:109 +0x5de
  github.com/pingcap/tidb/ttl/ttlworker.(*ttlDeleteWorker).loop()
      ttl/ttlworker/del.go:265 +0xef
  github.com/pingcap/tidb/ttl/ttlworker.(*ttlDeleteWorker).loop-fm()
      <autogenerated>:1 +0x39
  github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop()
      ttl/ttlworker/worker.go:134 +0xa3
  github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop-fm()
      <autogenerated>:1 +0x39
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
      util/wait_group_wrapper.go:154 +0x73
Goroutine 533768 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1629 +0x805
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:2036 +0x8d
  testing.tRunner()
      GOROOT/src/testing/testing.go:1576 +0x216
  testing.runTests()
      GOROOT/src/testing/testing.go:2034 +0x87c
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:1906 +0xb44
  github.com/pingcap/tidb/testkit/testmain.(*testingM).Run()
      testkit/testmain/wrapper.go:27 +0x42
  go.uber.org/goleak.VerifyTestMain()
      external/org_uber_go_goleak/testmain.go:53 +0x70
  github.com/pingcap/tidb/executor_test.TestMain()
      executor/main_test.go:76 +0x1013
  main.main()
      bazel-out/k8-fastbuild/bin/executor/executor_test_/testmain.go:1978 +0x5e8
Goroutine 561851 (running) created at:
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run()
      util/wait_group_wrapper.go:152 +0xe4
  github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).Start()
      ttl/ttlworker/worker.go:71 +0x12d
  github.com/pingcap/tidb/ttl/ttlworker.(*ttlDeleteWorker).Start()
      <autogenerated>:1 +0x37
  github.com/pingcap/tidb/ttl/ttlworker.(*taskManager).resizeWorkers()
      ttl/ttlworker/task_manager.go:219 +0x95e
  github.com/pingcap/tidb/ttl/ttlworker.(*taskManager).resizeDelWorkers()
      ttl/ttlworker/task_manager.go:182 +0x87
  github.com/pingcap/tidb/ttl/ttlworker.(*taskManager).resizeWorkersWithSysVar()
      ttl/ttlworker/task_manager.go:122 +0x224
  github.com/pingcap/tidb/ttl/ttlworker.(*JobManager).jobLoop()
      ttl/ttlworker/job_manager.go:165 +0x509
  github.com/pingcap/tidb/ttl/ttlworker.(*JobManager).jobLoop-fm()
      <autogenerated>:1 +0x39
  github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop()
      ttl/ttlworker/worker.go:134 +0xa3
  github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop-fm()
      <autogenerated>:1 +0x39
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
      util/wait_group_wrapper.go:154 +0x73
================== 
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #44532

Problem Summary:

### What is changed and how it works?

It appears that there is a problem with the test code where there may be a data race occurring in the TTL section. Therefore, the disable TTL feature is necessary for this test.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by zimulala** [comment]
Is there an issue or description associated with this PR?

**Review by qw4990 — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Pull request merged**
