### PR TITLE
server: make tokenLimit configurable

### PR DESCRIPTION
**Pull request by mccxj**
1.  for #4906
2.  minor typo. s/skip_auth/skip-auth/ at x-server/config.go

### CODE REVIEW

**Comment by coocood** [comment]
@mccxj 
The test failure is caused by a config with 0 token-limit.
Maybe we should check if the token-limit is 0 and set it to the default value 1000.

**Comment by coocood** [comment]
@mccxj 
There are places in `tidb_test.go` and `region_handler_test.go` we create `Config` directly without loading it from a file.

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
