### PR TITLE
Revert "*: add a String method for Datum to make the log more friendly"

### PR DESCRIPTION
**Pull request by jackysp**
Reverts pingcap/tidb#7426 to avoid to be misused with Datum.ToString.
PTAL @coocood

### CODE REVIEW

**Comment by jackysp** [comment]
According to the suggestion from @coocood , `String` has a similar name to `ToString`, which may be easy to be misused by someone else.

**Comment by coocood** [comment]
@shenli 
We can use `types.DatumsToString` instead.

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
