### PR TITLE
tidb-server: set TiDBMemQuotaQuery to the value in configuration file(#7729)

### PR DESCRIPTION
**Pull request by XuHuaiyu**
cherry pick from #7729

### CODE REVIEW

**Comment by lysu** [comment]
/run-all-tests tidb-test=pr/624 tikv=release-2.0 pd=release-2.0

**Comment by lamxTyler** [comment]
/run-common-test tidb-test=pr/624 tikv=release-2.0 pd=release-2.0
/run-integration-common-test tidb-test=pr/624 tikv=release-2.0 pd=release-2.0

**Comment by lysu** [comment]
/run-common-test tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0
/run-integration-common-test tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by coocood** [comment]
/run-all-tests tidb-test=pr/624 tikv=release-2.0 pd=release-2.0

**Comment by coocood** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Pull request merged**
