### PR TITLE
ddl: fix cancel rename index ddl error

### PR DESCRIPTION
**Pull request by ciscoxll**
### What problem does this PR solve? 
Cherry pick #8610

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by ciscoxll** [comment]
@crazycs520 PTAL.

**Comment by zimulala** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by ciscoxll** [comment]
@crazycs520 PTAL.

**Comment by zimulala** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by ciscoxll** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by ciscoxll** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Pull request merged**
