### PR TITLE
*: fix permissions of brie RESTORE to be RESTORE_ADMIN

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/24912

Problem Summary:

Previously the `RESTORE` command was intended to require `BACKUP_ADMIN` privilege, but this did not work correctly, as the internal execute commands required additional privileges (`ALTER`).

After discussion, `RESTORE` is a riskier operation than `BACKUP` and so it should require a distinct set of fine-grained permissions. The outcome of the discussion is that we would add the `RESTORE_ADMIN` dynamic privilege.

This is manually tested because it requires a tikv server to correctly reproduce the original issue.

### What is changed and how it works?

What's Changed:

Executing the `RESTORE` or `SHOW RESTORES` statements now requires the `RESTORE_ADMIN` privilege. For backward compatibility, the `SUPER` privilege is also permitted, but not recommended.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`: will provide.

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

Side effects

- None

### Release note 

- Executing the `RESTORE` or `SHOW RESTORES` statements now requires the `RESTORE_ADMIN` privilege. For backward compatibility, the `SUPER` privilege is also permitted, but not recommended.

### CODE REVIEW

**Review by kennytm — APPROVED** [review]
/lgtm

**Review by AilinKid — APPROVED** [review]

**Comment by morgo** [comment]
The test failure is because `SHOW PRIVILEGES` now has different results. I'll fix it tomorrow.

**Pull request merged**
