### PR TITLE
*: turn on unused linter

### PR DESCRIPTION
**Pull request by tisonkun**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23013

Problem Summary:

Turn on unused linter for better code quality

### Release note 

- No release note

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Review by xhebox — APPROVED** [review]

**Comment by xhebox** [comment]
Oops, looks like you need a reviewer from exec. @tisonkun

**Comment by tisonkun** [comment]
> Oops, looks like you need a reviewer from exec. @tisonkun

@xhebox I think the bot automatically add sig-execution because the patch touches some related files. If you confirm to the change, you can update the label as @nolouch .

**Review by lzmhhh123 — APPROVED** [review]

**Comment by xhebox** [comment]
@tisonkun `.github/labeler` the labeler configuration file is here. It is not recommended to tag unrelated labels.

**Pull request merged**
