### PR TITLE
make ide highlight easy

### PR DESCRIPTION
**Pull request by biolee**
make ide highlight and code search easy

### CODE REVIEW

**Comment by tiancaiamao** [comment]
1. `make update` is not intend to be called by user.
2. use both $GOPATH and vendor would make the build environment more complex, difficult for debugging.

When someone clone the repository, and `make` fail, it take us more efforts to find why,
so I don't think it's worth the change.

As an advanced developer, you can just do it locally. @biolee

**Comment by shenli** [comment]
@biolee Sorry, we do not want `vendor` represent in the root dir of TiDB. This may affect user's dependency path.

**Comment by biolee** [comment]
I do not understand why 

> This may affect user's dependency path.

and 

> make fail, it take us more efforts to find why

the [deign doc](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit)

> If there is a source directory d/vendor, then, when compiling a source file within the subtree rooted at d, import "p" is interpreted as import "d/vendor/p" if that path names a directory containing at least one file with a name ending in “.go”.
> When there are multiple possible resolutions, the most specific (longest) path wins.

that is to say vender have higher priority only on the packages in vender folder's parent folder  and its subfolder, it have no effect on outer folder's package, `GOBUILD   := GOPATH=$(CURDIR)/_vendor:$(GOPATH) CGO_ENABLED=0 $(GO) build`, mk no difference with the vender way

**Comment by tiancaiamao** [comment]
This is not a problem that worth debating, if you really need the vendor, just do it.

```
ln -s _vendor/src vendor
```

There are much more interesting and important works you can focus on, welcome to send us other PRs.

**Pull request closed without merging**
