### PR TITLE
sessionctx/variable: avoid SysVar clone every time when visiting system variable

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Problem Summary:

The current implementation for system variable is not good. To avoid DATA RACE in the unit test, it Clone() a new object every time.

When I handle #25573, I find it cause unnecessary allocation (every query needs to visit the session variable, and it's copy on read)

### What is changed and how it works?

What's Changed:

Change `SetSysVar` implementation to removing the object from the map and then register a new object...

How it Works:

`SysVar` are **almost** immutable ...  Here I say **almost**, I mean after initialized, they are not changed any more.

So we do not really need to Clone to avoid data race.

We can register this SysVar again, the map is protected under lock, and the SysVar is immutable, it do not need a lock or clone.

This change avoid the copy-on-read and is better for performance.

### Check List 

Tests 

- [ ] No code

```
cd session
go test -test.run TestXXX -test.bench BenchmarkPreparedPointGet -memprofile mem.out -benchmem -benchtime 30s
```

Before vs After:

```
BenchmarkPreparedPointGet-16    	 4316589	      8428 ns/op	    6510 B/op	      81 allocs/op
BenchmarkPreparedPointGet-16    	 4369659	      8196 ns/op	    6317 B/op	      80 allocs/op
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by morgo** [comment]
@tiancaiamao LGTM, but there is another possible fix I wanted to run by you:

The only scenario where Set is required is in changing the value of None-scoped variables (this is a very small amount of the total scope). We could instead move the values of read-only sysvars to a map, and use copy-on-write here.

**Comment by tiancaiamao** [comment]
This is the map:

```
// key -> value
tidb_transaction_isolation -> SysVar{Global | Session , Value: xxx}   <-- Value in SysVar actually means Default Value, 
tidb_enable_async_commit -> SysVar{Global | Session, Value: xxx}      <-- For global | session, SysVar & SysVar.Value never changes
tidb_tidb_slow_log_masking -> SysVar{}         <-- most of the system variables are initialized at init()
tidb_partition_prune_mode -> SysVar{}
tidb_server_version -> SysVar{ScopeNone, Value: xxx}       <-- None Scope, Immutable after initialize, some are initialized at SetSysVar()
...
```
The current code in this PR is using a lock to protect the map itself, and the `SysVar` objects in the map are immutable ...

> We could instead move the values of read-only sysvars to a map, and use copy-on-write here.

I don't quite get your point.  `copy-on-write` do you mean create a new map to replace the old one?  @morgo 
`SetSysVar` need to modify the map anyway, you can't copy a SysVar from the map and modify the copied SysVar value.

**Review by morgo — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
