### PR TITLE
table, executor: fix data race for the partition table's hash code

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve? 
```
WARNING: DATA RACE
Write at 0x00c000b7d2a8 by goroutine 115:
  github.com/pingcap/tidb/expression.(*ScalarFunction).HashCode()
      /Users/xia/workspace/src/github.com/pingcap/tidb/expression/scalar_function.go:317 +0xe7
  github.com/pingcap/tidb/expression.(*exprSet).Append()
      /Users/xia/workspace/src/github.com/pingcap/tidb/expression/constraint_propagation.go:40 +0x69
  github.com/pingcap/tidb/expression.newExprSet()
      /Users/xia/workspace/src/github.com/pingcap/tidb/expression/constraint_propagation.go:80 +0x25f
  github.com/pingcap/tidb/expression.constraintSolver.Solve()
      /Users/xia/workspace/src/github.com/pingcap/tidb/expression/constraint_propagation.go:100 +0x70
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).canBePruned()
      /Users/xia/workspace/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:195 +0x32c
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).prune()
      /Users/xia/workspace/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:144 +0x4b0
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).rewriteDataSource()
      /Users/xia/workspace/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:53 +0xa22
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).rewriteDataSource()
      /Users/xia/workspace/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:81 +0x130
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).optimize()
      /Users/xia/workspace/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:46 +0x56
  github.com/pingcap/tidb/planner/core.logicalOptimize()
      /Users/xia/workspace/src/github.com/pingcap/tidb/planner/core/optimizer.go:149 +0x1de
...
  github.com/pingcap/tidb/executor_test.(*testSuite1).TestPartitionHashCode.func1()
      /Users/xia/workspace/src/github.com/pingcap/tidb/executor/executor_test.go:5080 +0x150

Previous read at 0x00c000b7d2a8 by goroutine 103:
  github.com/pingcap/tidb/expression.(*ScalarFunction).HashCode()
      /Users/xia/workspace/src/github.com/pingcap/tidb/expression/scalar_function.go:314 +0x5e
  github.com/pingcap/tidb/expression.(*exprSet).Append()
      /Users/xia/workspace/src/github.com/pingcap/tidb/expression/constraint_propagation.go:40 +0x69
  github.com/pingcap/tidb/expression.newExprSet()
      /Users/xia/workspace/src/github.com/pingcap/tidb/expression/constraint_propagation.go:80 +0x25f
  github.com/pingcap/tidb/expression.constraintSolver.Solve()
      /Users/xia/workspace/src/github.com/pingcap/tidb/expression/constraint_propagation.go:100 +0x70
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).canBePruned()
      /Users/xia/workspace/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:195 +0x32c
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).prune()
      /Users/xia/workspace/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:144 +0x4b0
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).rewriteDataSource()
      /Users/xia/workspace/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:53 +0xa22
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).rewriteDataSource()
      /Users/xia/workspace/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:81 +0x130
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).optimize()
      /Users/xia/workspace/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:46 +0x56
  github.com/pingcap/tidb/planner/core.logicalOptimize()
      /Users/xia/workspace/src/github.com/pingcap/tidb/planner/core/optimizer.go:149 +0x1de
  github.com/pingcap/tidb/planner/core.DoOptimize()
      /Users/xia/workspace/src/github.com/pingcap/tidb/planner/core/optimizer.go:119 +0x84
```

### What is changed and how it works?
Get a hash code in advance to prevent data race afterward when generating partition expressions.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

Release note

 - Get a hash code in advance to prevent data race afterward when generating partition expressions.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM

**Comment by zimulala** [comment]
PTAL @XuHuaiyu @winoros

**Pull request merged**
