### PR TITLE
*: convert tikv.error which is returned by RegionCache.Locate to tidb.error 

### LINKED ISSUE #26147: In some cases, the error code of 1105 does not give specific error information
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run tipocket bank2，set nemesis type:pod-failure, the testcase fail, error message is null; for example：

2021/07/11 12:03:06 control.go:478: [info] recover nemesis type:pod-failure,duration:1m34s,node:node[comp=pd,ip=default-1626001720-pd-2.default-1626001720-pd-peer.tipocket-bank2.svc:2379,ns=tipocket-bank2,pod=default-1626001720-pd-2],invoke_args:[],recover_args:[]...

2021/07/11 12:03:06 kill.go:155: [info] unapply nemesis pod-failure on node default-1626001720-pd-2(ns:tipocket-bank2)

2021/07/11 12:03:06 client.go:397: [fatal] [bank2] ADMIN CHECK TABLE bank2_accounts fails: Error 1105: 

### 2. What did you expect to see? (Required)

return error code and detail error message

### 3. What did you see instead (Required)

Error 1105: 

### 4. What is your TiDB version? (Required)

Release Version: v5.1.0-4-ge96c2a6da
Edition: Community
Git Commit Hash: e96c2a6da635923d8964a2eedfb79ca2583d26c1
Git Branch: release-5.1
UTC Build Time: 2021-07-07 12:16:42
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: shirly <AndreMouche@126.com>

### What problem does this PR solve?

Issue Number: close #26147

Problem Summary:
This PR will fix the issue that `tidb` returns an `unknow` error with no message while it should return the error that pd is timeout.

### What is changed and how it works?

What's Changed:

It converts the `tikv.err` to `tidb.err` in copr/region_cache.go

How it Works:

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

### Release note 

```release-note
Fix #26147 that `tidb` returns an `unknow` error with no message while it should return the error that contains `pd is timeout`.
```

### CODE REVIEW

**Comment by disksing** [comment]
Do we need to add some release note?

**Review by disksing — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by sticnarf — APPROVED** [review]

**Pull request merged**
