### PR TITLE
*: show backfill type in `admin show ddl jobs`

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: ref #35983

Problem Summary: 

- There is no way to know whether a finished ADD INDEX statement used the "ingest" way to backfill the records.
- Support running multiple add index job with ingest way at the same time can cause the CPU usage being high. To reduce the effect to foreground workload, it is better to set a limit. 

### What is changed and how it works?

Before this PR:

```
+--------+-------------+------------+-----------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
| JOB_ID | DB_NAME     | TABLE_NAME | JOB_TYPE  | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE  |
+--------+-------------+------------+-----------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
|    166 | addindexlit | t          | add index | public       |       158 |      160 |         3 | 2022-10-28 22:58:22 | 2022-10-28 22:58:22 | 2022-10-28 22:58:25 | synced |
|    165 | addindexlit | t          | add index | public       |       158 |      160 |         3 | 2022-10-28 22:58:21 | 2022-10-28 22:58:21 | 2022-10-28 22:58:22 | synced |
+--------+-------------+------------+-----------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
```

After this PR:

```
+--------+-------------+------------+---------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
| JOB_ID | DB_NAME     | TABLE_NAME | JOB_TYPE                  | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE  |
+--------+-------------+------------+---------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
|    166 | addindexlit | t          | add index /* ingest */    | public       |       158 |      160 |         3 | 2022-10-28 22:58:22 | 2022-10-28 22:58:22 | 2022-10-28 22:58:25 | synced |
|    165 | addindexlit | t          | add index /* txn-merge */ | public       |       158 |      160 |         3 | 2022-10-28 22:58:21 | 2022-10-28 22:58:21 | 2022-10-28 22:58:22 | synced |
+--------+-------------+------------+---------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
```

The concurrent limit is set to 1 as well.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Benjamin2037 — COMMENTED** [review]
LGTM

**Review by Benjamin2037 — APPROVED** [review]

**Review by Benjamin2037 — COMMENTED** [review]
Do we need store the ingest type persist into job table or history table?

**Review by hawkingrei — APPROVED** [review]

**Comment by tangenta** [comment]
> Do we need store the ingest type persist into job table or history table?

@Benjamin2037 The type has persisted in `job.ReorgMeta.ReorgTp` : )

**Pull request merged**
