### PR TITLE
copr: remove unused code of examining join and exchange receiver

### PR DESCRIPTION
**Pull request by ichn-hu**
Signed-off-by: ichn-hu <zfhu16@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Since MPP requests are handled by MPP copr, normal DAG reqeust will not have join and exchange receiver.

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by ichn-hu** [comment]
@windtalker @fzhedu

**Review by windtalker — APPROVED** [review]
LGTM

**Review by fzhedu — APPROVED** [review]
/LGTM

**Comment by ichn-hu** [comment]
failure of the ut is due to https://github.com/pingcap/tidb/pull/27703

**Pull request merged**
