### PR TITLE
util: add InTest to check whether to be in test

### LINKED ISSUE #40929: add InTest to check whether to be in test
## Enhancement

We have many same code about checking whether to be in test. 

image

we need a simple way to unite it. so I think we can use a build tag to make it complete.

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #40929

Problem Summary:

### What is changed and how it works?

- add ```intest``` build tags when running test.
- add ```intest``` into bazel and ut tools for helping the developers to config.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zimulala — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by lance6716 — APPROVED** [review]

**Review by CbcWestwolf — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Comment by ekexium** [comment]
It makes running tests in Goland more inconvenient. One has to change the test template setting in Goland.
I'm wondering whether it's worth. At least we should update our developers' guide?

**Comment by hawkingrei** [comment]
> It makes running tests in Goland more inconvenient. One has to change the test template setting in Goland. I'm wondering whether it's worth. At least we should update our developers' guide?

I have updated the document about https://pingcap.github.io/tidb-dev-guide/get-started/setup-an-ide.html.

**Comment by ekexium** [comment]
> > It makes running tests in Goland more inconvenient. One has to change the test template setting in Goland. I'm wondering whether it's worth. At least we should update our developers' guide?
> 
> I have updated the document about https://pingcap.github.io/tidb-dev-guide/get-started/setup-an-ide.html.

So nice of you!

**Pull request merged**
