### PR TITLE
ddl: support altering the other charset to utf8 or utf8mb4 (#8037)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
cherry-pick #8037 ,
**Please merge https://github.com/pingcap/parser/pull/152 first.**

```sql
CREATE TABLE tt (
a varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT ''
) CHARACTER SET = utf8 COLLATE = utf8_general_ci;

INSERT INTO tt VALUES ('🕶小楠～');  // return error.

// before this PR, release 2.1 can not support change column charset.
alter table tt modify column a varchar(64) CHARACTER SET utf8mb4;

```

### Check List 

Tests 

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8951)

### CODE REVIEW

**Comment by zz-jason** [comment]
@crazycs520 Please add some proper labels. For example, component, type.

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=pr/713 pd=release-2.1 tikv=release-2.1

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=pr/713 pd=release-2.1 tikv=release-2.1

**Pull request merged**
