### PR TITLE
executor, plan: abandon the selection controller

### LINKED ISSUE #4526: panic in builtin DATE_FORMAT()
```sql
create table xx_order
(
    id bigint auto_increment,
    create_date datetime not null,
    primary key (id)
);

SELECT (select 1 from xx_order where DATE_FORMAT(o.create_date,'%Y-%m')) 
FROM xx_order o;
```

got panic:

```
2017/09/14 17:53:39.721 conn.go:387: [error] lastCmd SELECT DATE_FORMAT(o.create_date,'%Y-%m') as 'col_1' ,count(1) as 'col_2' ,(select count(1) from xx_order oo where DATE_FORMAT(oo.create_date,'%Y-%m')=DATE_FORMAT(o.create_date,'%Y-%m') and (oo.payment_status in (2,3) and oo.order_status not in (4,5)) and oo.is_first=1) as  'col_3' FROM xx_order o WHERE o.payment_status in (2,3) or o.order_status in (4,5) GROUP BY DATE_FORMAT(o.create_date,'%Y-%m') ORDER BY DATE_FORMAT(o.create_date,'%Y-%m') DESC limit 3, interface conversion: interface {} is nil, not types.Time, goroutine 4919 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc42147a630)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/server/conn.go:385 +0xcd
panic(0x10b3620, 0xc420b7df00)
    /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/pingcap/tidb/expression.evalExprToTime(0x19c8dc0, 0xc420a1afd0, 0x0, 0x0, 0x0, 0xc421543e00, 0x0, 0x0, 0x0, 0x0, ...)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/expression/expression.go:242 +0x2be
github.com/pingcap/tidb/expression.(*CorrelatedColumn).EvalTime(0xc420a1afd0, 0x0, 0x0, 0x0, 0xc421543e00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/expression/column.go:73 +0xa2
github.com/pingcap/tidb/expression.(*builtinDateFormatSig).evalString(0xc421439260, 0x0, 0x0, 0x0, 0xc42120fe20, 0x40ff78, 0x40, 0x10ffe40, 0x40f701)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/expression/builtin_time.go:663 +0xb2
github.com/pingcap/tidb/expression.(*baseStringBuiltinFunc).eval(0xc421439260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/expression/builtin.go:460 +0x87
github.com/pingcap/tidb/expression.(*ScalarFunction).Eval(0xc420b7cf40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/expression/scalar_function.go:184 +0x7e8
github.com/pingcap/tidb/expression.SubstituteCorCol2Constant(0x19c8e80, 0xc420b7cf40, 0x19c8e80, 0xc420b7de40, 0x0, 0x0)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/expression/util.go:257 +0x62f
github.com/pingcap/tidb/expression.SubstituteCorCol2Constant(0x19c8e80, 0xc420b7cf80, 0xc420fd1eb0, 0x1, 0x1, 0x19c8e80)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/expression/util.go:248 +0x2f7
github.com/pingcap/tidb/plan.(*Selection).checkScanController(0xc420e87380, 0xc420a30dc0)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/decorrelate.go:195 +0x29d
github.com/pingcap/tidb/plan.(*decorrelateSolver).optimize(0x1d44fe0, 0x19ccf60, 0xc420e87380, 0x0, 0x0, 0x0, 0x19ccf60, 0xc420e6c240, 0x0, 0x0)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/decorrelate.go:166 +0xf71
github.com/pingcap/tidb/plan.(*decorrelateSolver).optimize(0x1d44fe0, 0x19cc960, 0xc420611cb0, 0x0, 0x0, 0x0, 0x19cc960, 0xc420611b00, 0x0, 0x0)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/decorrelate.go:171 +0xc72
github.com/pingcap/tidb/plan.(*decorrelateSolver).optimize(0x1d44fe0, 0x19cca60, 0xc4211d2b40, 0x0, 0x0, 0x0, 0xc420a30ef0, 0x10, 0x1, 0xc420b7db80)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/decorrelate.go:171 +0xc72
github.com/pingcap/tidb/plan.(*decorrelateSolver).optimize(0x1d44fe0, 0x19cca60, 0xc4211d2b40, 0x0, 0x0, 0x0, 0x118da80, 0xc421210e00, 0xce6c07, 0x30)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/decorrelate.go:118 +0x1c31
github.com/pingcap/tidb/plan.(*decorrelateSolver).optimize(0x1d44fe0, 0x19ccd60, 0xc421543e50, 0x0, 0x0, 0x0, 0x1143560, 0x30, 0x30, 0xc42153d860)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/decorrelate.go:171 +0xc72
github.com/pingcap/tidb/plan.(*decorrelateSolver).optimize(0x1d44fe0, 0x19cd160, 0xc421543ef0, 0x0, 0x0, 0x0, 0x30, 0x118da80, 0x2e, 0x1)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/decorrelate.go:171 +0xc72
github.com/pingcap/tidb/plan.(*decorrelateSolver).optimize(0x1d44fe0, 0x19cc860, 0xc421543f40, 0x0, 0x0, 0x0, 0x1, 0x1, 0xc4212115a8, 0xc420b00030)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/decorrelate.go:171 +0xc72
github.com/pingcap/tidb/plan.(*decorrelateSolver).optimize(0x1d44fe0, 0x19ccd60, 0xc421543f90, 0x19b54a0, 0xc421288460, 0xc4209af498, 0x19ccd60, 0xc421543f90, 0x0, 0x0)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/decorrelate.go:171 +0xc72
github.com/pingcap/tidb/plan.logicalOptimize(0x7f, 0x19ccd60, 0xc421543f90, 0x19b54a0, 0xc421288460, 0xc4209af498, 0x119fb40, 0x1201b00, 0x1, 0x19ccd60)
    /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/optimizer.go:148 +0xd7
github.com/pingcap/t
2017/09/14 17:53:39.722 server.go:276: [info] [2] close connection
```

tidb version():

```
mysql> select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: 0.9.0
Git Commit Hash: b812f324c37421c881f7669322c946fba700b2f7
Git Branch: master
UTC Build Time: 2017-09-14 09:49:55 |
+-----------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by hanfei1991**
selection controller is a optimization for old plan. 
fix #4526

### CODE REVIEW

**Comment by winkyao** [comment]
@winoros @lamxTyler

**Comment by coocood** [comment]
Can we not skip the two tests?

**Comment by coocood** [comment]
@hanfei1991 
Is it hard to move the two tests to new plan in this PR?

**Comment by hanfei1991** [comment]
@coocood Moving test will take huge effort.

**Comment by hanfei1991** [comment]
@winkyao which one should be fixed ?

**Pull request merged**
