### PR TITLE
*: Remove column `TIBD_DIRECT_PLACEMENT` from some sys tables

### LINKED ISSUE #31426: Remove TIDB_DIRECT_PLACEMENT from infoschema.tables, infoschema.partitions, infoschema.schemata

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #31426

Problem Summary:

### What is changed and how it works?

Remove column `TIBD_DIRECT_PLACEMENT` from below tables in `information_schema`:

1. `INFORMATION_SCHEMA.SCHEMATA`
2. `INFORMATION_SCHEMA.TABLES`
3. `INFORMATION_SCHEMA.PARTITIONS`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Column `TIBD_DIRECT_PLACEMENT` is removed from tables in `INFORMATION_SCHEMA`
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by morgo — APPROVED** [review]

**Comment by hawkingrei** [comment]
Mysql-test found some problem. we need to update them.

```
 we need(469):
 SELECT * from INFORMATION_SCHEMA.SCHEMATA;
 CATALOG_NAME SCHEMA_NAME DEFAULT_CHARACTER_SET_NAME DEFAULT_COLLATION_NAME SQL_PATH TIDB_PLACEMENT_POLICY_NAME TIDB_DIRECT_PLACEMENT
 def d utf8mb4 utf8mb4_bin NULL NULL NULL
 def INFORMATION_SCHEMA utf8mb4 utf8mb4_bin NULL NULL NULL
 def infoschema utf8mb4 utf8mb4_bin NULL NULL NULL
 def METRICS_SCHEMA utf8mb4 utf8mb4_bin NULL NULL NULL
 def mysql utf8mb4 utf8mb4_bin NULL NULL NULL
 def PERFORMANCE_SCHEMA utf8mb4 utf8mb4_bin NU
 but got(469):
 SELECT * from INFORMATION_SCHEMA.SCHEMATA;
 CATALOG_NAME SCHEMA_NAME DEFAULT_CHARACTER_SET_NAME DEFAULT_COLLATION_NAME SQL_PATH TIDB_PLACEMENT_POLICY_NAME
 def d utf8mb4 utf8mb4_bin NULL NULL
 def INFORMATION_SCHEMA utf8mb4 utf8mb4_bin NULL NULL
 def infoschema utf8mb4 utf8mb4_bin NULL NULL
 def METRICS_SCHEMA utf8mb4 utf8mb4_bin NULL NULL
 def mysql utf8mb4 utf8mb4_bin NULL NULL
 def PERFORMANCE_SCHEMA utf8mb4 utf8mb4_bin NULL NULL
 def test utf8mb4 utf8mb4_bin NULL NULL
```

**Pull request merged**
