### PR TITLE
planner: report the warning when use the hint but the SQL has the binding

### PR DESCRIPTION
**Pull request by Reminiscent**
…ding

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/40910

Problem Summary:
 report the warning when use the hint but the SQL has the binding

### What is changed and how it works?
If we use the hints from binding, check whether the input's SQL has the hint. If it has, we should report the warning.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by fzzf678 — APPROVED** [review]

**Comment by Reminiscent** [comment]
TODO: Need to update the doc

**Pull request merged**
