### PR TITLE
executor: fix panic on Stream Aggregate

### LINKED ISSUE #6983: panic during stream aggregate
panic stack is:
```
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc421e04410, 0xc4202e5dff)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:425 +0x10e
panic(0x1d39000, 0x29cabd0)
        /Users/jianzhang.zj/opt/goroot/src/runtime/panic.go:505 +0x229
github.com/pingcap/tidb/server.(*clientConn).writeResultset.func1(0x0, 0x201e420, 0xc42088c550, 0xc4202e5bf0, 0xc421e04410)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:941 +0x325
panic(0x1d39000, 0x29cabd0)
        /Users/jianzhang.zj/opt/goroot/src/runtime/panic.go:505 +0x229
github.com/pingcap/tidb/expression.(*Column).EvalDecimal(0xc421a04a90, 0x203a360, 0xc421e061c0, 0x2038b00, 0xc421b6fa20, 0x0, 0xc4202e0001, 0xc4202e5790, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/expression/column.go:256 +0x49
github.com/pingcap/tidb/executor/aggfuncs.(*avgOriginal4Decimal).UpdatePartialResult(0xc42170ca20, 0x203a360, 0xc421e061c0, 0xc420eb6000, 0x1, 0x20, 0xc421702ab0, 0x0, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/aggfuncs/func_avg.go:72 +0x12c
github.com/pingcap/tidb/executor.(*StreamAggExec).consumeGroupRows(0xc421297040, 0x30aa6b8, 0xc421708400)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/aggregate.go:851 +0xe2
github.com/pingcap/tidb/executor.(*StreamAggExec).consumeOneGroup(0xc421297040, 0x30aa6b8, 0xc421708400, 0xc42170cbe0, 0x0, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/aggregate.go:836 +0x521
github.com/pingcap/tidb/executor.(*StreamAggExec).Next(0xc421297040, 0x30aa6b8, 0xc421708400, 0xc42170cbe0, 0xc42170a700, 0x2e0ad90)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/aggregate.go:791 +0x84
github.com/pingcap/tidb/executor.(*SortExec).fetchRowChunks(0xc4200ef680, 0x30aa6b8, 0xc421708400, 0x143bf39, 0xc42170cbc0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/sort.go:115 +0x248
github.com/pingcap/tidb/executor.(*SortExec).Next(0xc4200ef680, 0x30aa6b8, 0xc421708400, 0xc42170cbc0, 0x1, 0x1)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/sort.go:78 +0x10e
github.com/pingcap/tidb/executor.(*recordSet).Next(0xc421a06300, 0x30aa6b8, 0xc421708400, 0xc42170cbc0, 0xc421a06300, 0xc42170cbc0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/adapter.go:89 +0x56
github.com/pingcap/tidb/server.(*tidbResultSet).Next(0xc42088c550, 0x30aa6b8, 0xc421708400, 0xc42170cbc0, 0x4, 0x400)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/driver_tidb.go:334 +0x51
github.com/pingcap/tidb/server.(*clientConn).writeChunks(0xc421e04410, 0x30aa6b8, 0xc421708400, 0x201e420, 0xc42088c550, 0xc400005b00, 0xc421e04410, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:990 +0x409
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc421e04410, 0x30aa6b8, 0xc421708400, 0x201e420, 0xc42088c550, 0xc400008500, 0x0, 0x0, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:954 +0x1bc
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc421e04410, 0x30aa6b8, 0xc421708400, 0xc420046cb1, 0x6e, 0x0, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:871 +0x124
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc421e04410, 0xc420046cb1, 0x6f, 0x6f, 0x0, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:612 +0x51d
github.com/pingcap/tidb/server.(*clientConn).Run(0xc421e04410)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:470 +0x1be
github.com/pingcap/tidb/server.(*Server).onConn(0xc421e204e0, 0x20204c0, 0xc420d6a890)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/server.go:320 +0x22b
created by github.com/pingcap/tidb/server.(*Server).Run
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/server.go:260 +0x4dc
```

Create table and query statement is: [panic.txt](https://github.com/pingcap/tidb/files/2162394/panic.txt)

### PR DESCRIPTION
**Pull request by zz-jason**
## What have you changed? (mandatory)

This PR fix #6983.

For stream aggregate, if the last group in a `Chunk` only contains the last row of that `Chunk`, and there is no more data to be fetched from child, we reset the `Chunk` in `fetchChildIfNecessary` and got panic in `consumeGroupRows`.

## What are the type of the changes (mandatory)?

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested (mandatory)?

- unit test
- explain test
- randgen test

### CODE REVIEW

**Comment by zz-jason** [comment]
@XuHuaiyu @winoros PTAL, cc @shenli

**Comment by zimulala** [comment]
Which test covers the panic case?

**Comment by zz-jason** [comment]
@zimulala randgen-test, this PR fixes CI

**Pull request merged**
