### PR TITLE
testkit,store/mockstore: make store image to accelerate unit test

### LINKED ISSUE #42434: CI timeout due to bootstrap is very slow
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/20093/pipeline

```
PASS: TestReadPartitionTable (71.84s)
```

And if we dig into which stage this test is stuck at, we will see

```
[2023/03/21 15:34:51.514 +08:00] [INFO] [session.go:3813] ["CRUCIAL OPERATION"] [conn=0] [schemaVersion=0] [cur_db=mysql] [sql="CREATE DATABASE IF NOT EXISTS test"] [user=]
...
[2023/03/21 15:35:53.456 +08:00] [INFO] [session.go:3813] ["CRUCIAL OPERATION"] [conn=0] [schemaVersion=43] [cur_db=mysql] [sql="CREATE TABLE IF NOT EXISTS mysql.load_data_jobs (\n       job_id bigint(64) NOT NULL AUTO_INCREMENT,\n       expected_status ENUM('running', 'paused', 'canceled') NOT NULL DEFAULT 'running',\n       create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n       start_time TIMESTAMP(6) NULL DEFAULT NULL,\n       update_time TIMESTAMP(6) NULL DEFAULT NULL,\n       end_time TIMESTAMP(6) NULL DEFAULT NULL,\n       data_source TEXT NOT NULL,\n       table_schema VARCHAR(64) NOT NULL,\n       table_name VARCHAR(64) NOT NULL,\n       import_mode VARCHAR(64) NOT NULL,\n       create_user VARCHAR(32) NOT NULL,\n       progress TEXT DEFAULT NULL,\n       result_message TEXT DEFAULT NULL,\n       error_message TEXT DEFAULT NULL,\n       PRIMARY KEY (job_id),\n       KEY (create_time),\n       KEY (create_user));"] [user=]
```

bootstrap costs 62s in 71.84s

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #42434 

Problem Summary:

### What is changed and how it works?

In our unit test, almost every test case use

```
store := testkit.CreateMockStore(t)
tk := testkit.NewTestKit(t, store)
```

This will create a new mockstore and bootstrap it.
The bootstrap involves a lot of DDL operations, make the test slow.

We can create a bootstraped store as the test image, and later re-use the image to avoid the bootstrap everytime.
Just copy files from the image to get a  new bootstraped store for testing.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Comment by hawkingrei** [comment]
> If we are in bazel remote execution， The test cases will be in difference instances.

It is my wrong understanding. Ignore it.

**Comment by Defined2014** [comment]
Although we use a store image to accelerate UT, it still waits many time to run tests :(
```
[2023/05/06 10:45:49.123 +08:00] [INFO] [levels.go:70] ["table file not referenced in MANIFEST"] [id=1]
[2023/05/06 10:46:26.886 +08:00] [INFO] [tidb.go:80] ["new domain"] [store=ac30e7d0-1e53-4084-a3f6-60ed1d3ce014] ["ddl lease"=500ms] ["stats lease"=-1ns] ["index usage sync lease"=0s]
[2023/05/06 10:46:26.895 +08:00] [INFO] [domain.go:269] ["full load InfoSchema success"] [currentSchemaVersion=0] [neededSchemaVersion=43] ["start time"=8.497913ms]
[2023/05/06 10:46:26.895 +08:00] [INFO] [domain.go:584] ["full load and reset schema validator"]
```

**Comment by hawkingrei** [comment]
> Although we use a store image to accelerate UT, it still needs many seconds to run tests :(
> 
> ```
> [2023/05/06 10:45:49.123 +08:00] [INFO] [levels.go:70] ["table file not referenced in MANIFEST"] [id=1]
> [2023/05/06 10:46:26.886 +08:00] [INFO] [tidb.go:80] ["new domain"] [store=ac30e7d0-1e53-4084-a3f6-60ed1d3ce014] ["ddl lease"=500ms] ["stats lease"=-1ns] ["index usage sync lease"=0s]
> [2023/05/06 10:46:26.895 +08:00] [INFO] [domain.go:269] ["full load InfoSchema success"] [currentSchemaVersion=0] [neededSchemaVersion=43] ["start time"=8.497913ms]
> [2023/05/06 10:46:26.895 +08:00] [INFO] [domain.go:584] ["full load and reset schema validator"]
> ```

It is a sad news.

**Comment by tiancaiamao** [comment]
> [2023/05/06 10:45:49.123 +08:00] [INFO] [levels.go:70] ["table file not referenced in MANIFEST"] [id=1]

@Defined2014 This log is print from here

https://github.com/pingcap/badger/blob/828f39b09b6d33afd28e457f0f66280b8f1eb690/levels.go#LL70C55-L70C55

I haven't read the details but it seems this does not affect the functionality

**Review by xhebox — APPROVED** [review]

**Comment by hawkingrei** [comment]
I find goleak in this PR.

```
 --- PASS: TestSnapshotWithoutInterceptor (54.52s)
PASS
coverage: 1.1% of statements
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 5 in state syscall, with syscall.Syscall on top of the stack:
syscall.Syscall(0x536404b?, 0x0?, 0xa80?, 0x2111160?)
	GOROOT/src/syscall/syscall_linux.go:69 +0x25
syscall.Close(0xc000142560?)
	GOROOT/src/syscall/zsyscall_linux_amd64.go:320 +0x25
internal/poll.(*SysFile).destroy(...)
	GOROOT/src/internal/poll/fd_unixjs.go:24
internal/poll.(*FD).destroy(0xc00168c240)
	GOROOT/src/internal/poll/fd_unix.go:81 +0x51
internal/poll.(*FD).decref(0x7fec68aa4700?)
	GOROOT/src/internal/poll/fd_mutex.go:213 +0x53
internal/poll.(*FD).Close(0xc00168c240)
	GOROOT/src/internal/poll/fd_unix.go:104 +0x45
os.(*file).close(0xc00168c240)
	GOROOT/src/os/file_unix.go:315 +0x98
]
-- 
```

PTAL @tiancaiamao

**Comment by tiancaiamao** [comment]
> I find goleak in this PR.
> 
> ```
>  --- PASS: TestSnapshotWithoutInterceptor (54.52s)
> PASS
> coverage: 1.1% of statements
> goleak: Errors on successful test run: found unexpected goroutines:
> [Goroutine 5 in state syscall, with syscall.Syscall on top of the stack:
> syscall.Syscall(0x536404b?, 0x0?, 0xa80?, 0x2111160?)
> 	GOROOT/src/syscall/syscall_linux.go:69 +0x25
> syscall.Close(0xc000142560?)
> 	GOROOT/src/syscall/zsyscall_linux_amd64.go:320 +0x25
> internal/poll.(*SysFile).destroy(...)
> 	GOROOT/src/internal/poll/fd_unixjs.go:24
> internal/poll.(*FD).destroy(0xc00168c240)
> 	GOROOT/src/internal/poll/fd_unix.go:81 +0x51
> internal/poll.(*FD).decref(0x7fec68aa4700?)
> 	GOROOT/src/internal/poll/fd_mutex.go:213 +0x53
> internal/poll.(*FD).Close(0xc00168c240)
> 	GOROOT/src/internal/poll/fd_unix.go:104 +0x45
> os.(*file).close(0xc00168c240)
> 	GOROOT/src/os/file_unix.go:315 +0x98
> ]
> -- 
> ```
> 
> PTAL @tiancaiamao

How to reproduce it?  I run this test manually but it's ok:

```
go test -tags intest -run TestSnapshotWithoutInterceptor 
[2024/01/03 13:51:41.145 +08:00] [INFO] [levels.go:70] ["table file not referenced in MANIFEST"] [id=1]
[2024/01/03 13:51:41.240 +08:00] [INFO] [region_cache.go:2741] ["change store resolve state"] [store=1] [addr=store1] [from=unresolved] [to=resolved] [liveness-state=reachable]
[2024/01/03 13:51:41.250 +08:00] [INFO] [db.go:567] ["Closing database"]
[2024/01/03 13:51:41.250 +08:00] [INFO] [db.go:592] ["Memtable flushed"]
[2024/01/03 13:51:41.250 +08:00] [INFO] [db.go:596] ["Compaction finished"]
[2024/01/03 13:51:41.250 +08:00] [INFO] [db.go:615] ["BlobManager finished"]
[2024/01/03 13:51:41.250 +08:00] [INFO] [db.go:619] ["ResourceManager finished"]
[2024/01/03 13:51:41.250 +08:00] [INFO] [db.go:625] ["Waiting for closer"]
PASS
ok      github.com/pingcap/tidb/pkg/store/driver        0.314s 
```

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
