### PR TITLE
session: fix global variable collation_server does not take effect in new session

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

after setting the global `collation_server `, the new session's `collation_server` variable should use it.

global variable `collation_server` does not take effect because the `loadCommonGlobalVariablesIfNeeded` function overwrite the variables, and we had set the `collation_server` when setting the `character_set_server`, see https://github.com/pingcap/tidb/pull/21034

### Check List 

Tests 

- Unit test

### Release note 

- fix global variable collation_server does not take effect in new session

### CODE REVIEW

**Comment by xhebox** [comment]
I am not sure if this is the correct fix. I mean that global variables are promised to be refreshed every 3 mins. They will not take effect immediately.

**Comment by xiongjiwei** [comment]
> I am not sure if this is the correct fix. I mean that global variables are promised to be refreshed every 3 mins. They will not take effect immediately.

I have no knowledge about `global variables are promised to be refreshed every 3 mins`. Are there any materials?

**Comment by xhebox** [comment]
Here, I have one issue, https://github.com/pingcap/tidb/issues/22808.

**Comment by morgo** [comment]
/LGTM

> Here, I have one issue, #22808. Andy fault, there is a typo, it is 3s, or 2s, not mins.

On a single-server it is usually much quicker, this is just the documented time to receive updates asyncronously through etcd on other servers.

We have several examples where there can be a delay (another one is `FLUSH PRIVILEGES`), and usually fix it by syncronously also updating it locally. So technically the initiating server will apply the instruction twice.

I think the intention is that `set global` should be instant on the initiating server too, but I know there is a race condition if the new session starts too quickly. I am hoping that we can fix it in future by using a simple map to keep the global cache (similar to what privileges does) and not rely on internal SQL.

**Review by xhebox — APPROVED** [review]
LGTM

**Comment by xhebox** [comment]
> I think the intention is that set global should be instant on the initiating server too

Agreed.

> I am hoping that we can fix it in future by using a simple map to keep the global cache (similar to what privileges does) and not rely on internal SQL.

Well, I don't think it is a good idea to merge a PR that is not completely working, though... Anyway, let us merge it as it is proposed. But it should be fine to revert the change back when immediate global cache is implemented.

**Comment by morgo** [comment]
> Well, I don't think it is a good idea to merge a PR that is not completely working, though... 

If we do a more complete fix, I think it will be a lot of work, and not suitable to cherry pick to 5.0.

> Anyway, let us merge it as it is proposed. But it should be fine to revert the change back when immediate global cache is implemented, or whatever.

Agreed. Having the unit test here also helps for this future work.

**Pull request merged**
