### PR TITLE
planner: for UNION statements, ORDER BY cannot use column references including a table name (#8389)

### PR DESCRIPTION
**Pull request by dbjoa**
### What problem does this PR solve? 

Cherry-pick from #8389  to release-2.0 branch

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8514)

### CODE REVIEW

**Comment by zz-jason** [comment]
@dbjoa CI failed.

**Comment by ngaut** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Pull request merged**
