### PR TITLE
planner/core: fix a bug that check update privilege use wrong `AsName` and DBName (#9003)

### PR DESCRIPTION
**Pull request by bb7133**
Cherry-pick https://github.com/pingcap/tidb/pull/9003

### CODE REVIEW

**Comment by bb7133** [comment]
PTAL @tiancaiamao @lysu @zz-jason

**Comment by lysu** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by bb7133** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
