### PR TITLE
lightning: fix integration test

### LINKED ISSUE #39696: BR Integration Test Failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run BR's integration test

### 2. What did you expect to see? (Required)
All tests passed

### 3. What did you see instead (Required)
Test failed at `lightning_fail_fast`

### 4. What is your TiDB version? (Required)
Latest master

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: close #39696 

Problem Summary:

### What is changed and how it works?
In the new version, the error message from TiDB returns the sub error code, which breaks the integration test .
Fix the error message in the integration test.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by buchuitoudegou — APPROVED** [review]
I just met this error in my PR and was about to fix it😀

**Comment by buchuitoudegou** [comment]
please hold until the integration-test succeeds.

**Comment by dsdashun** [comment]
BR integration failed at `br_full_cluster_restore`.  All Lightning tests have passed.  
https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/14351/pipeline

**Review by maxshuang — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

**Pull request merged**
