### PR TITLE
executor: remove `monotime` package dependency

### PR DESCRIPTION
**Pull request by coocood**
This package has been removed in the latest etcd repo.
And Go 1.9 supports transparent monotonic time.

See https://golang.org/doc/go1.9#monotonic-time

### CODE REVIEW

**Comment by shenli** [comment]
Should  also update the dependency of Go to 1.9: https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md#go

**Comment by coocood** [comment]
@shenli PTAL

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@disksing PTAL

**Pull request merged**
