### PR TITLE
planner/core: fix error information when enter incorrect partition name

### LINKED ISSUE #44967: Bad error string in Incorrect partition name
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (a int) partition by list (a) (partition `s1 s2 ` values in (0));
```

### 2. What did you expect to see? (Required)
Incorrect partition name

### 3. What did you see instead (Required)
Incorrect partition name%!(EXTRA string=s1 s2 )

### 4. What is your TiDB version? (Required)

```
tidb_version(): Release Version: v7.1.0
Edition: Community
Git Commit Hash: 635a4362235e8a3c0043542e629532e3c7bb2756
Git Branch: heads/refs/tags/v7.1.0
UTC Build Time: 2023-05-30 10:50:03
GoVersion: go1.20.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
```

### PR DESCRIPTION
**Pull request by River2000i**
### What problem does this PR solve?

Issue Number: close #44967

Problem Summary: remove incorrect partition name in error information when enter incorrect partition name

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by Defined2014** [comment]
@River2000i It seems that there is a problem with ci, you can merge master and push again

**Pull request merged**
