### PR TITLE
executor: close the children of HashJoinExec and UnionExec after close goroutine finish

### PR DESCRIPTION
**Pull request by XuHuaiyu**
HashJoinExec.Close() may be called while `fetch outer goroutine`
and `join goroutines` are be still working.
If we close children before all the goroutines return,
the resources of children would be released,
and if the remained goroutines used the resources,
unexpected error may be throwed.

So as UnionExec

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by ngaut** [comment]
What's the purpose of the PR?

**Comment by XuHuaiyu** [comment]
I added a description.
PTAL @ngaut @coocood

**Pull request merged**
