### PR TITLE
parser,ddl: parse and ignore 'PARTITION BY LIST ..."

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

On the release-2.1 branch, TiDB fails to execute the following SQL:

```
create table t (a int) /*!50100 partition by list (a) (
partition p0 values in (1) ENGINE = InnoDB,
partition p1 values in (29) ENGINE = InnoDB,
partition p2 values in (2) ENGINE = InnoDB,
partition p3 values in (3) ENGINE = InnoDB) */
```

### What is changed and how it works?

Update parser, parse `PARTITION BY LIST` and ignore it.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Wait for https://github.com/pingcap/parser/pull/386

**Comment by tiancaiamao** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by imtbkcat** [comment]
@tiancaiamao please fix ci.

**Comment by tiancaiamao** [comment]
The parser was updated in https://github.com/pingcap/tidb/pull/11306

**Pull request merged**
