### PR TITLE
ddl: stabilize ddl tests (#18205)

### LINKED ISSUE #18202: TestDeleteOnly Failed.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
----------------------------------------------------------------------
FAIL: db_change_test.go:566: testStateChangeSuite.TestDeleteOnly

db_change_test.go:588:
    s.runTestInSchemaState(c, model.StateDeleteOnly, true, dropColumnSQL, sqls, query)
db_change_test.go:717:
    c.Assert(errors.ErrorStack(checkErr), Equals, "")
... obtained string = "" +
...     "sql: update t set c1 = 'c1_insert', c3 = '2018-02-12', c4 = 1, expect err: [planner:1054]Unknown column 'c1' in 'field list', got err: [planner:1054]Unknown column 'c1' in 'field_list'\n" +
...     "github.com/pingcap/tidb/ddl_test.(*testStateChangeSuiteBase).runTestInSchemaState.func1\n" +
...     "\t/Users/bba/pc/tidb/ddl/db_change_test.go:702\n" +
...     "github.com/pingcap/tidb/ddl.(*TestDDLCallback).OnJobUpdated\n" +
...     "\t/Users/bba/pc/tidb/ddl/callback_test.go:68\n" +
...     "github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue\n" +
...     "\t/Users/bba/pc/tidb/ddl/ddl_worker.go:516\n" +
...     "github.com/pingcap/tidb/ddl.(*worker).start\n" +
...     "\t/Users/bba/pc/tidb/ddl/ddl_worker.go:155\n" +
...     "runtime.goexit\n" +
...     "\t/Users/bba/.gvm/gos/go1.13/src/runtime/asm_amd64.s:1357"
... expected string = ""

PASS: db_integration_test.go:1419: testIntegrationSuite3.TestAlterColumn	0.716s

----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #18205 to release-4.0

---

Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #18202 

Problem Summary:
1. We set a hook OnJobUpdatedExported and execute some SQLs within the hook.
However, the schema may not sync.
We want to test the state DeleteOnly, but mostly it's WriteOnly.
In the state DeleteOnly, the returned err would be `field_list`, not `field list`. This problem exposure.

### What is changed and how it works?

1. Move `d.mu.hook.OnJobUpdated(job)`  after `w.waitSchemaChanged(nil, d, waitTime, schemaVer, job)`
2. Change `field_list` to `field list`, since the latter is more compatible with MySQL.
3. Refine some tests(TestWriteOnlyWriteNULL...), I asked @jackysp and he confirmed that the previous comments were wrong. It should be passed in write-only state. And I tested it 100 times to make sure it's stable.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

### Release note 

- No release note

### CODE REVIEW

**Comment by zz-jason** [comment]
@wjhuang2016 please fix the integration test.

**Review by winoros — COMMENTED** [review]
lgtm

**Pull request merged**
