### PR TITLE
*: update PD dependency to latest master

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Problem Summary: Update PD dependency to the latest master

### What is changed and how it works?

What's Changed: Just as above says

### Check List 

Tests 

- No code

### Release note 

- No release note

### CODE REVIEW

**Comment by JmPotato** [comment]
I suggest `rm go.sum && go mod tidy` once, it seems that there are many unnecessary changes in `go.sum` now.

**Review by JmPotato — APPROVED** [review]

**Review by HunDunDM — APPROVED** [review]

**Pull request merged**
