### PR TITLE
session, ddl: amend txn correctly when "modify column" needs reorg data with tidb_enable_amend_pessimistic_txn=on. (#26269)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #26269 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/26273
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/26273:release-5.1-6e72be0013da
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/26203 

Problem Summary:
Columns exist in an intermediate state when we support modifying the column type (which requires reorg the data). So we can't just check the public state columns when we check whether the operation is amendable.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

Use `WritableCols` instead of `Cols`.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note 

- amend transactions correctly when "modify column" needs reorg data with tidb_enable_amend_pessimistic_txn=on.

### CODE REVIEW

**Review by AilinKid — APPROVED** [review]

**Comment by zimulala** [comment]
PTAL @cfzjywxk

**Review by cfzjywxk — APPROVED** [review]
/lgtm

**Pull request merged**
