### PR TITLE
parser: remove outdated and unnecessary checkout-pr-branch.sh

### LINKED ISSUE #29886: `parser/checkout-pr-branch.sh` is outdated and not needed
It's against wrong repo and we could follow https://internals.tidb.io/t/topic/454.

### PR DESCRIPTION
**Pull request by zhangyangyu**
### What problem does this PR solve?

Issue Number: close #29886

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by morgo — APPROVED** [review]
LGTM, thank you for cleaning this up.

**Review by kennytm — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Comment by kennytm** [comment]
/run-check-dev-2 

`TestCheckClusterVersion` shouldn't be parallel. will be fixed later.

**Comment by kennytm** [comment]
/run-check_dev_2 

`TestCheckClusterVersion` shouldn't be parallel. will be fixed later.

**Comment by zhangyangyu** [comment]
thanks for all your quick responses!

**Pull request merged**
