### PR TITLE
bindinfo: fix affected row in drop sql binding so that we can avoid clear cache if affected rows is 0

### LINKED ISSUE #27758: Fix affected row in drop sql binding so that we can avoid clear cache if affected rows is 0
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Master branch

Drop bind sql use `UPDATE mysql.bind_info SET status = %?, update_time = %? WHERE original_sql = %? AND update_time < %?` to judge whether there exists the sql binding, but this is not true, the correct sql should add
`status != 'deleted'`, for example, if there exist several deleted sql binding.
image

### PR DESCRIPTION
**Pull request by yuqi1129**
…lear cache if affected rows is 0

### What problem does this PR solve?

Issue Number: close #27758 
Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lzmhhh123 — APPROVED** [review]

**Review by xiongjiwei — APPROVED** [review]

**Comment by yuqi1129** [comment]
@wshwsh12 , Can you help to review this PR?

**Comment by xiongjiwei** [comment]
@rebelice can you please take a look?

**Review by rebelice — APPROVED** [review]

**Pull request merged**
