### PR TITLE
expression: cleanup old functions

### LINKED ISSUE #58326: Left overs of old functions
## Enhancement

These are functions that were removed in MySQL 8.0 or earlier.

These are rejected in TiDB, but still handled specially in the code:

- `OLD_PASSWORD()`
- `ENCRYPT()`
- `DES_ENCRYPT()`
- `DES_DECRYPT()`

MySQL docs:
- https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
- https://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html#function_encrypt
- https://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html#function_des-encrypt
- https://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html#function_des-decrypt

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #58326 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by dveeden** [comment]
Demo:
```sql
SELECT old_password("a");
SELECT very_old_password("a");
use test
SELECT old_password("a");
SELECT very_old_password("a");
```

MySQL 9.1.0:
```
mysql-9.1.0> SELECT old_password("a");
ERROR 1046 (3D000): No database selected
mysql-9.1.0> SELECT very_old_password("a");
ERROR 1046 (3D000): No database selected
mysql-9.1.0> use test
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql-9.1.0> SELECT old_password("a");
ERROR 1305 (42000): FUNCTION test.old_password does not exist
mysql-9.1.0> SELECT very_old_password("a");
ERROR 1305 (42000): FUNCTION test.very_old_password does not exist
```

TiDB with this PR:
```
mysql-8.0.11-TiDB-v8.5.0-alpha-357-gaec0fc58bd-dirty> SELECT old_password("a");
ERROR 1046 (3D000): No database selected
mysql-8.0.11-TiDB-v8.5.0-alpha-357-gaec0fc58bd-dirty> SELECT very_old_password("a");
ERROR 1046 (3D000): No database selected
mysql-8.0.11-TiDB-v8.5.0-alpha-357-gaec0fc58bd-dirty> use test
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql-8.0.11-TiDB-v8.5.0-alpha-357-gaec0fc58bd-dirty> SELECT old_password("a");
ERROR 1305 (42000): FUNCTION test.old_password does not exist
mysql-8.0.11-TiDB-v8.5.0-alpha-357-gaec0fc58bd-dirty> SELECT very_old_password("a");
ERROR 1305 (42000): FUNCTION test.very_old_password does not exist
```

TiDB without this PR:
```
mysql-8.0.11-TiDB-v8.5.0-alpha-357-gaec0fc58bd> SELECT old_password("a");
ERROR 1305 (42000): FUNCTION OLD_PASSWORD does not exist
mysql-8.0.11-TiDB-v8.5.0-alpha-357-gaec0fc58bd> SELECT very_old_password("a");
ERROR 1046 (3D000): No database selected
mysql-8.0.11-TiDB-v8.5.0-alpha-357-gaec0fc58bd> use test
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql-8.0.11-TiDB-v8.5.0-alpha-357-gaec0fc58bd> SELECT old_password("a");
ERROR 1305 (42000): FUNCTION OLD_PASSWORD does not exist
mysql-8.0.11-TiDB-v8.5.0-alpha-357-gaec0fc58bd> SELECT very_old_password("a");
ERROR 1305 (42000): FUNCTION test.very_old_password does not exist
```

**Review by D3Hunter — APPROVED** [review]

**Review by mjonss — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
