### PR TITLE
*: remove ddl dependency

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: ref #31716

Problem Summary:

resolve the cycle import.

### What is changed and how it works?

- remove ```ddl``` dependency from other package by remove ```ddl``` error to ```dbterror``` package 
- remove some function of ```ddl``` to ```types``` package for removing ```ddl``` dependency in ```session```.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Comment by tisonkun** [comment]
@hawkingrei I'd suggest you create subtasks of #31716 to express your ideas and focuses on different categories of improvements, instead of pushing random "improvements" under an umbrella issue.

**Review by tisonkun — APPROVED** [review]
The change itself is good to go.

**Comment by hawkingrei** [comment]
@morgo PTAL. need a tidb-configuration-reviewer.

**Review by morgo — APPROVED** [review]

**Pull request merged**
