### PR TITLE
inforschema, executor, util/kvcache, util/statement_summary : Add STATEMENTS_SUMMARY_EVICTED into information_schema (#24513)

### LINKED ISSUE #23920: Record evicted information of statements_summary
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, `statements_summary_history` use LRU cache strategy to cache recent 200 statements and each statement with 24 histories by default. 

The old statements which frequently executed before may be evicted by the new statements. Then we can't see it at some time in the past.

In short, we want to record the following information for a certain period of time:

* evicted_statements_count

**Describe the feature you'd like:**

Add a new system table such as: `statements_summary_lost`, query this this will get the following information:

| Begin_time          | End_time            | Evicted_count |
| ------------------- | ------------------- | ------------- |
| 2021-04-08 12:00:00 | 2021-04-08 12:30:00 | 10            |
| 2021-04-08 12:30:00 | 2021-04-08 13:00:00 | 50            |

As, neet provide a related cluster table such as: `cluster_statements_summary_lost`:

Instance | Begin_time | End_time | Evicted_count |
-- | -- | -- | -- |
tidb-0 | 2021-04-08 12:00:00 | 2021-04-08 12:30:00 | 10 | 
tidb-1 | 2021-04-08 12:00:00 | 2021-04-08 12:30:00 | 50 | 

**Describe alternatives you've considered:**

related work PR: https://github.com/pingcap/tidb/pull/23714

**Teachability, Documentation, Adoption, Migration Strategy:**

I will provide a detailed design doc later ...

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #24513 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25296
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25296:release-4.0-0367c54698b4
```

---

### What problem does this PR solve?

Issue Number: close #23920 

Problem Summary:

### What is changed and how it works?

What's Changed:
- inforschema/tables.go
- executor/inforschema_reader.go
- executor/builder.go
- util/kvcache/simple_lru.go
- Add util/stmtsummary/evicted.go

How it Works:

1. Get evicted digests by editing statementSummaryMap's onEvict function
2. Adding evicted digest elements to corresponding record in `ssMap`'s `other` list.
3. register table to information schema.
### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Tests will be added as soon as possible.

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
- fix kvcache, making onEvict usable when quota==0. #24242 
- add information_schema.STATEMENTS_SUMMARY_EVICTED table to tidb.

### CODE REVIEW

**Comment by ClSlaid** [comment]
@breeswish PTAL
should be merged after #25298

**Comment by djshow832** [comment]
I don't think we should merge it into 4.0. It's risky.

**Comment by ClSlaid** [comment]
@breeswish @djshow832 PTAL

**Comment by crazycs520** [comment]
> I don't think we should merge it into 4.0. It's risky.

Without the test, the cherry-pick code change not too big, and this will be helpful to remind user/DBA to enlarge the `stmt-max-count` config.

**Review by crazycs520 — APPROVED** [review]
LGTM

**Pull request closed without merging**
