### PR TITLE
cmd, expression: fix convert binary string to gbk

### LINKED ISSUE #29735: Builtin func convert() can't deal with GBK charset correctly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

start tidb-server with 
```
./bin/tidb-server --config=cmd/explaintest/config.tom
```

```
drop table if exists t;
create table t(a binary(10));
insert into t values (0xe240), (0x01e240);
select convert(a using gbk) from t;
```

### 2. What did you expect to see? (Required)

```
mysql> select convert(a using gbk) from t;
+----------------------+
| convert(a using gbk) |
+----------------------+
| 釦                   |
| 釦                  |
+----------------------+
2 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select convert(a using gbk) from t;
ERROR 1105 (HY000): encoding: rune not supported by encoding.
```

### 4. What is your TiDB version? (Required)

```
mysql> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0-alpha-97-g5bece67a9
Edition: Community
Git Commit Hash: 5bece67a9bae979020186b9819b1d3e90cff6678
Git Branch: master
UTC Build Time: 2021-11-12 11:19:21
GoVersion: go1.16.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #29735 

Problem Summary: fix convert builtin fuc

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @xiongjiwei @zimulala @tangenta 
PTAL

**Review by xiongjiwei — APPROVED** [review]

**Review by zimulala — COMMENTED** [review]
Have the attributes of this file(new_character_set_builtin.result) changed? It becomes bin.

**Comment by Defined2014** [comment]
> Have the attributes of this file(new_character_set_builtin.result) changed? It becomes bin.

The previous test didn't covered this issue. I add a new test case here, the result is same as MySQL 8.0 @zimulala

**Comment by Defined2014** [comment]
> Have the attributes of this file(new_character_set_builtin.result) changed? It becomes bin.

Done. Replaced with other test cases. We can review the result in github right now. @zimulala

**Review by tangenta — APPROVED** [review]

**Pull request merged**
