### PR TITLE
ddl: fix drop database bug if the database has partition table  (#8319)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
cheery-pick from #8319

### Check List 

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8360)

### CODE REVIEW

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by crazycs520** [comment]
merge https://github.com/pingcap/tidb/pull/8392 first

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by zz-jason** [comment]
LGTM

**Comment by zz-jason** [comment]
@zimulala @XuHuaiyu PTAL

**Pull request merged**
