### PR TITLE
*: use timetuil.Now() rather than time.Now()

### PR DESCRIPTION
**Pull request by zhexuany**
### What problem does this PR solve? 
It solves the ambiguous current time issue by using tidb's global system timezone

### What is changed and how it works?
Adding wrapper `Now()` in `timeutil`. Any use of `time.Now()` should be replaced by `timeutil.Now()`

### Check List 

Tests 
 - existing test

Code changes
 - Has exported function/method change

Side effects
 No side effects
Related changes
 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by zz-jason** [comment]
@zhexuany CI failed. By the way, please add some proper labels for this PR 😄

**Comment by zhexuany** [comment]
This change only applies to timestamp calculation. That is why I put a WIP label on this PR.

**Pull request closed without merging**
