### PR TITLE
*: Annotations to fix gosec warnings of CWE-798

### PR DESCRIPTION
**Pull request by s3nt3**
### What problem does this PR solve?

Issue Number: ref #31310 

Problem Summary: fix gosec warnings of CWE-798 issue

This linter is designed to find hardcoded credentials or keys in constants. The cases it has detected here are known to be false positives (i.e. they are not credentials).

### Check List

Tests 

- [x] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Review by dveeden — COMMENTED** [review]
When running `make check-static` I didn't see any results related to gosec G101 and this PR doesn't modify `.golangci.yml`. I also don't seen any exclude rules in `.golangci.yml`. We should make sure that CI is configured correctly to avoid having to redo this later.

Also gosec allows configuration (also via `golangci-lint`). This may allow us to modify the pattern the G101 check uses etc. Maybe we should modify that instead. See https://github.com/securego/gosec#configuration for some info.

**Comment by dveeden** [comment]
Setting `exclude-use-default` to `false` shows a few more gosec issues, but still not the G101. Note that this probably includes many noisy checks.

```patch
diff --git a/.golangci.yml b/.golangci.yml
index 60670adf3..e16d9beb5 100644
--- a/.golangci.yml
+++ b/.golangci.yml
@@ -30,6 +30,7 @@ linters-settings:
   stylecheck:
     checks: ["-ST1003"]
 issues:
+  exclude-use-default: false
   exclude-rules:
     - path: _test\.go
       linters:
```

**Review by dveeden — APPROVED** [review]
With #31514 this does help with issues not found by earlier versions of golangci-lint/gosec.

It might still good to update the config with any of these:
- Adjust the G101 pattern etc.
- Set `confidence: "medium"` to ignore possibly noisy checks

**Review by morgo — APPROVED** [review]

**Pull request merged**
