### PR TITLE
*: update client-go pkg

### LINKED ISSUE #44990: Stale read maybe always blocked cause by ResolvedTS blocked
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. tidb-server config:

```yaml
[labels]
zone = "z1"
```

Then [stale read request](https://github.com/tikv/client-go/blob/5fde3098f9183d22507dbd16597ff5a5d7f84390/internal/locate/region_request.go#L546-L549) is always not GlobalStaleRead. Then when stale read requests meet `DataIsNotReady` error, TiDB will retry the next available region replica. But if the `ResolvedTS` is blocked, the stale read request will always recieve `DataIsNotReady` error.  In this situation, TiDB should send the stale read request to region leader, and remove the request.StaleRead flag, then the region leader can always handle it.

### 4. What is your TiDB version? (Required)

tidb v6.5.3

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #44990

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@cfzjywxk @you06 PTAL

**Review by hawkingrei — APPROVED** [review]

**Comment by cfzjywxk** [comment]
@MyonKeminta is updating the client-go dependency in another PR, which one should we use?

**Comment by MyonKeminta** [comment]
> @MyonKeminta is updating the client-go dependency in another [PR](https://github.com/pingcap/tidb/pull/45143), is it already included?

Already included and merged

**Pull request closed without merging**
