### PR TITLE
ddl: migrate test-infra to testify for ddl/db_partition_test.go

### LINKED ISSUE #28635: migrate test-infra to testify for `ddl/db_partition_test.go`

### PR DESCRIPTION
**Pull request by MiaoMiaoGarden**
### What problem does this PR solve?

Issue Number: close #28635

Problem Summary:

### What is changed and how it works?
migrate test-infra to testify for ddl/db_partition_test.go

### Check List

Tests 

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by JayL-zxl** [comment]
@tisonkun  PTAL

**Review by tangenta — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
