### PR TITLE
planner, executor: enhance the index join's choice

### LINKED ISSUE #47233: planner: support using partial EQ predicates to construct IndexJoins
## Enhancement

See the example below, the third query cannot use `IndexJoin`:
```
create table a(id int,name varchar(100));
create table b(id int,name varchar(100), key(id));

select /*+ INL_JOIN(a,b) */ *  from a,b where a.id=b.id;                                                                -- IndexJoin
select /*+ INL_JOIN(a,b) */ *  from a,b where a.id=b.id and a.name!=substr(b.name,1,10);      -- IndexJoin
select /*+ INL_JOIN(a,b) */ *  from a,b where a.id=b.id and a.name=substr(b.name,1,10);       -- HashJoin, cannot use IndexJoin
```

The root cause is that both `a.id=b.id` and `a.name=substr(b.name)` are `EQ predicates`, so the optimizer **has to** use them both as the `Join Keys` when constructing Joins. 
But `IndexJoin` cannot support `substr`, then the optimizer has to use `HashJoin` for the third query if the two predicates have to be used as `Join Keys`.

A better solution is to only use `a.id=b.id` as the `Join Key` and put `a.name=substr(b.name)` into joins' other conditions to construct IndexJoin:
image

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/47233

Problem Summary:

### What changed and how does it work?

Modify the codes to support:
- The projection has expression ->column.
- Not only one of UnionScan/Selection/Projection Exists.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by winoros** [comment]
The first round is to test that existing tests are passed.

**Comment by winoros** [comment]
I've added the new case.

**Review by elsa0520 — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
