### PR TITLE
planner: make some `show stmt` more fine-grained privilege check

### LINKED ISSUE #35393: `show stats_meta` needs select privileges of all tables in database mysql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create user a@'%' identified by '';
grant select on mysql.stats_meta to a@'%';
--! login with a
show stats_meta;
```

### 2. What did you expect to see? (Required)
No error.

### 3. What did you see instead (Required)
`Access denied for user 'a'@'127.0.0.1' to database 'mysql'`

### 4. What is your TiDB version? (Required)
v4.0.15

### PR DESCRIPTION
**Pull request by likzn**
### What problem does this PR solve?

Issue Number: close #35393

Problem Summary: `mysql.stats_meta`,`mysql.stats_buckets`,`mysql.stats_histograms` were in the `SystemDB`. So we can make a more fine-grained privilege check and `grant`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by likzn** [comment]
PTAL /cc @tangenta @jackysp

**Review by tangenta — APPROVED** [review]

**Comment by tangenta** [comment]
@likzn Please also update the test `TestAuditLogNormal`.

**Comment by likzn** [comment]
> @likzn Please also update the test `TestAuditLogNormal`.

Done

**Review by jackysp — APPROVED** [review]
LGTM

**Comment by jackysp** [comment]
Thanks for your contribution, @likzn !

**Pull request merged**
