### PR TITLE
*:update github.com/pingcap/sysutil

### PR DESCRIPTION
**Pull request by Max-Cheng**
Signed-off-by: Max-Cheng <aaron9shire@gmail.com>

### What problem does this PR solve?

https://github.com/pingcap/tidb-dashboard/issues/812

What's Changed:`go.mod`

### Related changes

- PR to update `pingcap/sysutil`
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 
- Support display cpu-arch

### CODE REVIEW

**Review by breeswish — APPROVED** [review]
LGTM. Seems that there are multiple sysutils in `go.sum`. Maybe you can try run `go mod tidy` to clean up these stale versions.

**Comment by Max-Cheng** [comment]
> LGTM. Seems that there are multiple sysutils in `go.sum`. Maybe you can try run `go mod tidy` to clean up these stale versions.

👌

**Comment by Max-Cheng** [comment]
Nope, it wasn't clean.This command included build script
```bash
co1a@ubuntu:~/tidb$ go mod tidy&&git diff
co1a@ubuntu:~/tidb$ 
```

**Comment by breeswish** [comment]
Okay. Maybe it is caused by TiDB is using a PD that is using an old sysutil. Anyway it's fine!

/cc @crazycs520 @jyz0309

**Review by jyz0309 — APPROVED** [review]

**Comment by breeswish** [comment]
@crazycs520 PTAL

**Pull request closed without merging**
