### PR TITLE
statistics: migrate test-infra to testify for statistics/handle/update_list_test.go

### LINKED ISSUE #28129: migrate test-infra to testify for `statistics/handle/update_list_test.go`

### PR DESCRIPTION
**Pull request by feitian124**
### What problem does this PR solve?

Issue Number: close #28129

based on #28186

### Release note
```release-note
None
```

### CODE REVIEW

**Review by mmyj — APPROVED** [review]
lgtm

**Review by tisonkun — APPROVED** [review]
LGTM. @mmyj I think we should merge the base PR #28186 first.

**Comment by mmyj** [comment]
@feitian124 Please resolve conflicting.

**Comment by feitian124** [comment]
> @feitian124 Please resolve conflicting.

updated, please check again. thanks.

**Pull request merged**
