### PR TITLE
*: change terror.ErrorEqual to Error.Equal, which is more effetive

### PR DESCRIPTION
**Pull request by winkyao**
the `terror.ErrorEqual()` compare whether two error object are equal, it do it correctlly, but not effectivelly. 

```
func ErrorEqual(err1, err2 error) bool {
	e1 := errors.Cause(err1)
	e2 := errors.Cause(err2)

	if e1 == e2 {
		return true
	}

	if e1 == nil || e2 == nil {
		return e1 == e2
	}

	te1, ok1 := e1.(*Error)
	te2, ok2 := e2.(*Error)
	if ok1 && ok2 {
		return te1.class == te2.class && te1.code == te2.code
	}

	return e1.Error() == e2.Error() // in most cases it is unnecessary
}
```

the cases modified in this PR, is the terror.Error object, it have a `Error.Equal` method, the method do the same thing, but it doesn't compare the error string.

`terror.ErrorEqual()` is used to compare the error except `terror.Error`, like below in [ddl_worker.go#L343](https://github.com/pingcap/tidb/blob/master/ddl/ddl_worker.go#L343):

```
if terror.ErrorEqual(err, goctx.DeadlineExceeded) {
	return
}
```

### CODE REVIEW

**Comment by winkyao** [comment]
@shenli @tiancaiamao @hanfei1991 @XuHuaiyu @zz-jason @breeswish @zimulala PTAL, please approve this PR with at least 3 LGTM.

**Comment by tiancaiamao** [comment]
If your concern is performance, just remove that line? @winkyao 

```
return e1.Error() == e2.Error() // in most cases it is unnecessary
```

**Comment by winkyao** [comment]
@tiancaiamao In some cases, `e1.Error() == e2.Error()` is necessary.

**Comment by tiancaiamao** [comment]
LGTM
PTAL @disksing

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
