### PR TITLE
Error message of duplicate primary key was not showing as expected, error message has been rectified

### LINKED ISSUE #35289: Error message of duplicate primary key is not shown properly
## Enhancement

Actual:
```sql
mysql> CREATE TABLE t1 (a BINARY(16) PRIMARY KEY);
Query OK, 0 rows affected (0.02 sec)

mysql> INSERT INTO t1 VALUES (AES_ENCRYPT('a','a'));
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (AES_ENCRYPT('a','a'));
ERROR 1062 (23000): Duplicate entry '{ W]�u����.�٧t' for key 'PRIMARY'
```

Expected:
```sql
mysql> CREATE TABLE t1 (a BINARY(16) PRIMARY KEY);
Query OK, 0 rows affected (0.05 sec)

mysql> INSERT INTO t1 VALUES (AES_ENCRYPT('a','a'));
Query OK, 1 row affected (0.02 sec)

mysql> INSERT INTO t1 VALUES (AES_ENCRYPT('a','a'));
ERROR 1062 (23000): Duplicate entry '{ W]\xA1\x06u\x9D\xBD\xB1\xA3.\xE2\xD9\xA7t' for key 't1.PRIMARY'
```

### PR DESCRIPTION
**Pull request by measutosh**
### What problem does this PR solve?

Issue Number: close #35289

Problem Summary:

### What is changed and how it works?
This PR modfies the **rune type strings** into **unicode style strings** as it was asked in the relevant issue

### Check List

Tests 

I have done the unit tests using `make gotest`
- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by measutosh** [comment]
/cc @tangenta, here is a submission from my side to solve the issue - [#35289](https://github.com/pingcap/tidb/issues/35289)

please have a look on it.

**Review by lance6716 — COMMENTED** [review]
Hi, can you add an unit test to illustrate the effects?

**Comment by measutosh** [comment]
> Hi, can you add an unit test to illustrate the effects?

Hi @lance6716 , I am quite new to this, unable to figure out how to write test case for this
that's why I have provided the demo code for your reference
Could you please provide some resource following which I can write the unit tests

**Comment by lance6716** [comment]
Maybe you can search for the usage of `MustGetErrMsg`, this is a testing function that assert the SQL must return a specific error message. @measutosh

**Review by tangenta — COMMENTED** [review]
For the ASCII characters we don't have to cast to "%u" style.

**Pull request closed without merging**
