### PR TITLE
*: enable makezero for bazel nogo

### LINKED ISSUE #36850: use makezero in bazel nogo
## Enhancement

use makezero in bazel nogo to speed up it.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #36850

Problem Summary:

### Check List

Tests 

- [x] Manual test (add detailed scripts or steps below)

Run it in CI

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Yisaer — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Comment by hawkingrei** [comment]
/needs-cherry-pick-6.2

**Comment by hawkingrei** [comment]
/needs-cherry-pick-release-6.2

**Pull request merged**
