### PR TITLE
expression: set correct return field type of builtin CONVERT() (#9305)

### PR DESCRIPTION
**Pull request by bb7133**
Cherry-pick https://github.com/pingcap/tidb/pull/9305, please merge parser cherry-pick https://github.com/pingcap/parser/pull/299 firstly.

This cherry-pick aims to solve a known charset issue:

```
mysql> create database ${SOME_DB} charset ""
```

Which reports errors in master branch as expected, but shows no error in release-2.1

### CODE REVIEW

**Comment by zz-jason** [comment]
@bb7133 please fix ci. BTW please add some proper labels for this PR.

**Comment by bb7133** [comment]
PTAL @lysu @XuHuaiyu @zz-jason

**Comment by zz-jason** [comment]
LGTM

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Pull request merged**
