### PR TITLE
metrics: adjust the parse & compile duration metrics (#9925)

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry-pick https://github.com/pingcap/tidb/pull/9925

PTAL @jackysp @lysu

### CODE REVIEW

**Comment by tiancaiamao** [comment]
/run-all-tests tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by shenli** [comment]
Please fix the CI.

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by jackysp** [comment]
/run-uint-tests tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by jackysp** [comment]
/run-uint-test tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Pull request merged**
