### PR TITLE
tidb-server: Remove tidb-server binary file from repo

### PR DESCRIPTION
**Pull request by shenli**

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by siddontang** [comment]
add it to ignore file already ?

**Comment by shenli** [comment]
It is already in .gitignore
➜  tidb git:(shenli/add-user-table) ✗ cat ./.gitignore 
/parser/parser.go
/parser/scanner.go
/interpreter/interpreter
/interpreter/test
/tidb-server/tidb-server
coverage.out%

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
