### PR TITLE
[store/copr]: check the tiflash availabilities before launching mpp queries.

### PR DESCRIPTION
**Pull request by hanfei1991**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
cherry-pick from https://github.com/pingcap/tidb/pull/26130

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- mpp: check the tiflash availabilities before launching mpp queries.

### CODE REVIEW

**Review by fzhedu — APPROVED** [review]
/LGTM

**Review by lysu — APPROVED** [review]

**Pull request merged**
