### PR TITLE
bindinfo: use new sql apis (#22653)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #22653 to release-5.0-rc
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/22734
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/22734:release-5.0-rc-745729fd9182
```

---

### What problem does this PR solve?

Part of pingcap/tidb-test#1152

### What is changed and how it works?

What's Changed:

This updates the bindinfo package to use the new SQL APIs.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- None

### Release note 

- No release note

### CODE REVIEW

**Comment by morgo** [comment]
This depends on https://github.com/pingcap/tidb/pull/22657 which depends on https://github.com/pingcap/tidb/pull/22687

**Comment by tiancaiamao** [comment]
Now #22657 and #22687 are both merged. @morgo

**Comment by morgo** [comment]
This is now ready for review.

**Review by xhebox — COMMENTED** [review]
/lgtm

**Pull request merged**
