### PR TITLE
domain: add uint tests for global_vars_cache

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve? 
Unit tests coverage from 0% to 100%.

### What is changed and how it works?
Add tests and remove the return value of `Disable`.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by shenli** [comment]
Good job!

**Comment by shenli** [comment]
Please fix the CI.

**Comment by zimulala** [comment]
PTAL @tiancaiamao

**Pull request merged**
