### PR TITLE
ddl,expression: make leak test more stable

### PR DESCRIPTION
**Pull request by tiancaiamao**
/run-unit-test

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
why this commit will be more stable?

**Comment by tiancaiamao** [comment]
I move `testleak.AfterTest()` from each test case to `SetupSuite()` and `TearDownSuite()`.
This would make the check less accurate, but easier to pass CI. @XuHuaiyu

**Pull request merged**
