### PR TITLE
util/kvcache: migrate test-infra to testify

### LINKED ISSUE #26182: migrate test-infra to testify for `util/kvcache` pkg

### PR DESCRIPTION
**Pull request by yeyypp**
### What problem does this PR solve?

Issue Number: close #26182 

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
Hi @yeyypp ! Thanks for submitting this PR. Please sign off CLA as @CLAassistant comment.

**Review by tisonkun — APPROVED** [review]
LGTM

**Comment by yeyypp** [comment]
> Hi @yeyypp ! Thanks for submitting this PR. Please sign off CLA as @CLAassistant comment.

Hi, I already signed the CLA, I don't know why this still not work.

**Comment by tisonkun** [comment]
> > Hi @yeyypp ! Thanks for submitting this PR. Please sign off CLA as @CLAassistant comment.
> 
> Hi, I already signed the CLA, I don't know why this still not work.

It works now.

/cc @xhebox @djshow832 

PTAL

**Review by xhebox — APPROVED** [review]

**Comment by tisonkun** [comment]
/cc @mmyj @tiancaiamao 

PTAL

**Review by djshow832 — APPROVED** [review]

**Comment by djshow832** [comment]
```
[2021-08-04T02:32:33.763Z] + make check

[2021-08-04T02:32:33.763Z] gofmt (simplify)

[2021-08-04T02:32:43.726Z] util/kvcache/simple_lru_test.go

[2021-08-04T02:32:43.726Z] make: *** [fmt] Error 1
```
Please check the CI.

**Comment by tisonkun** [comment]
> ```
> [2021-08-04T02:32:33.763Z] + make check
> 
> [2021-08-04T02:32:33.763Z] gofmt (simplify)
> 
> [2021-08-04T02:32:43.726Z] util/kvcache/simple_lru_test.go
> 
> [2021-08-04T02:32:43.726Z] make: *** [fmt] Error 1
> ```
> 
> Please check the CI.

I push a follow up to fix it.

**Pull request merged**
