### PR TITLE
ddl: fix rename locked table

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: close ##29752

Problem Summary:

### What is changed and how it works?

1. Handle the drop privilege when checking the lock
2. Add Test for renaming table with read/write lock
3. make a manual test at mysql-8.0.22-13 to ensure the same or similar behavior

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by morgo — APPROVED** [review]

**Comment by sylzd** [comment]
@lcwangchao

**Review by tiancaiamao — APPROVED** [review]
`CheckTableLock` is built on the privilege system looks very tricky to me...
And this fix works on a very narrow range and make the code more tricky, harder to read, from bad to worse...
Anyway, it fix something

**Comment by sylzd** [comment]
@tiancaiamao you are right~  maybe we can reconstruct it someday 🤣, if you propose a related issue, plz call me~~

**Pull request merged**
