### PR TITLE
planner: don't push down predicates over table dual

### LINKED ISSUE #35527: unexpected unresolved column error when the view refers to dual table
### 1. Minimal reproduce step (Required)
```sql
CREATE VIEW v0(c0) AS SELECT NULL;
SELECT v0.c0 FROM v0 WHERE (v0.c0 IS NULL) LIKE(NULL); -- ERROR 1105 (HY000) at line 2: Can't find column Column#1 in schema Column: [] Unique key: []
```
### 2. What did you expect to see? (Required)
No error information.

### 3. What did you see instead (Required)
ERROR 1105 (HY000) at line 2: Can't find column Column#1 in schema Column: [] Unique key: []

### 4. What is your TiDB version? (Required)

| Release Version: v6.2.0-alpha-143-gcd731af05
Edition: Community
Git Commit Hash: cd731af05a5446bb8dcba83f0e163176c75f5cea
Git Branch: master
UTC Build Time: 2022-06-20 07:36:55
GoVersion: go1.18.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
Store: unistore |

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #35527

Problem Summary:

When a table dual is used as view or subquery, the PPD(Predicate Push-Down) optimizer incorrectly pushes the predicate down to the table dual.

After rule-based optimization:
```
*core.LogicalProjection(*core.LogicalProjection(*core.LogicalSelection(*core.LogicalTableDual)))
```

After the physical optimization, the columns in condition need to be relocated using the schema of child operator(it is `TableDual` here). As we know, the schema of `TableDual` is always `nil`. An error is occurred.

### What is changed and how it works?

This PR avoids to push the predicates to the `TableDual`, but keeps a `Projection` over it instead.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by winoros** [comment]
```
mysql> explain select c0 from (select null as c0) v0 where c0 is null;
+-------------------+---------+------+---------------+-----------------+
| id                | estRows | task | access object | operator info   |
+-------------------+---------+------+---------------+-----------------+
| Projection_6      | 1.00    | root |               | <nil>->Column#1 |
| └─TableDual_7     | 1.00    | root |               | rows:1          |
+-------------------+---------+------+---------------+-----------------+
2 rows in set (0.01 sec)

mysql> explain select c0 from (select null as c0) v0 where c0 is null;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    403
Current database: test

+---------------------+---------+------+---------------+------------------+
| id                  | estRows | task | access object | operator info    |
+---------------------+---------+------+---------------+------------------+
| Selection_6         | 0.80    | root |               | isnull(Column#1) |
| └─Projection_7      | 1.00    | root |               | <nil>->Column#1  |
|   └─TableDual_8     | 1.00    | root |               | rows:1           |
+---------------------+---------+------+---------------+------------------+
3 rows in set (0.32 sec)
```

This change caused the above diff.
I'm also a little curious about why the normal `explain select c0 from (select null as c0) v0 where c0 is null;` would not trigger this bug because the view only support expanding itself now which means it should be the same with the above SQL`.

**Comment by tangenta** [comment]
> I'm also a little curious about why the normal explain select c0 from (select null as c0) v0 where c0 is null; would not trigger this bug

@winoros I tried to print the logical plan in each step of logical optimization:

```
[optimizer.go:456] ["logicalOptimize before"] [logic=*core.LogicalProjection(*core.LogicalSelection(*core.LogicalProjection(*core.LogicalTableDual)))]
[optimizer.go:470] [logicalOptimize] [rule=column_prune] [logic=*core.LogicalProjection(*core.LogicalSelection(*core.LogicalProjection(*core.LogicalTableDual)))]
[optimizer.go:470] [logicalOptimize] [rule=projection_eliminate] [logic=*core.LogicalProjection(*core.LogicalSelection(*core.LogicalProjection(*core.LogicalTableDual)))]
[optimizer.go:470] [logicalOptimize] [rule=predicate_push_down] [logic=*core.LogicalProjection(*core.LogicalProjection(*core.LogicalTableDual))]
...
[optimizer.go:475] ["logicalOptimize after"] [logic=*core.LogicalProjection(*core.LogicalProjection(*core.LogicalTableDual))]
```

You can see the `LogicalSelection` is eliminated by "predicate_push_down" rule. This is not happened in `where (c0 is null) like (null)`. For the operator `LIKE`, the first argument must be a string. Thus, a `cast` function is inserted automatically:

```
where cast((c0 is null) as string) like (null)
```

The "predicate_push_down" rule tries to eliminate the selection by `PropagateConstant` and then `DeleteTrueExprs`. However, because the collation of `NULL`("binary") is stricter than "utf8mb4_bin", which is the collation of `ast((c0 is null) as string)`, the column substitution failed. That's why the selection is not eliminated.

Anyway, even if the selection operator is not pushed down, it shouldn't report the error "Can't find column Column#1 in schema Column: [] Unique key: []".

**Review by mjonss — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]

**Pull request merged**
