### PR TITLE
statsitstics: avoid sync load column which is skiped type to analyze

### LINKED ISSUE #57138: sync load forget to skip the column which is in the tidb_analyze_skip_column_types
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `t1` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `content` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

INSERT INTO `t1` (`content`) VALUES ('这是一段示例文本内容。');
analyze table t1;
set global tidb_analyze_skip_column_types=text;
select * from t1 where content="abc";
```

### 2. What did you expect to see? (Required)

no sync load to trigger 
### 3. What did you see instead (Required)

sync load to trigger

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #57138

Problem Summary:

### What changed and how does it work?

Sometimes, we disable the analysis of certain columns using analyze_skip_column. However, these columns may still retain outdated statistics, especially after being modified. Since their statistics are larger, syncing them via sync load can be very slow and prone to timeouts. To address this, we filter out these columns.

image

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
statsitstics: avoid sync load column which is skiped to analyze

避免将 skip analyze 的列通过 sync load 加载
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]
LGTMeow

**Comment by hawkingrei** [comment]
/hold 

@elsa0520 PTAL

**Review by elsa0520 — APPROVED** [review]
LGTM

**Pull request merged**
