### PR TITLE
*: Handle the error of "CampaignOwner"

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?
Before this PR, it may encounter the following problems：
Screen Shot 2020-04-16 at 15 41 17

Problem Summary:
If we do `NewSession` failed in `ownerManager.CampaignOwner`, this TiDB server will not have  owner. And there will only be one log record.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
If we do `NewSession` failed in `ownerManager.CampaignOwner`, we throw the error up.

### Check List 

Tests 

- Unit test

### Release note 

- If we fail to connect to etcd while campaigning the owner, we can't start the module of DDL.

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @crazycs520 @tiancaiamao

**Comment by wjhuang2016** [comment]
@tiancaiamao PTAL

**Comment by zimulala** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
