### PR TITLE
tidb-server: check privilege feature set the default value to true

### PR DESCRIPTION
**Pull request by tiancaiamao**

### CODE REVIEW

**Comment by shenli** [comment]
We should make sure all of our online users are OK.

**Comment by shenli** [comment]
@tiancaiamao It is better to keep the flag for a while. So in case user meet any problem with the privilege system, there is a way to make his application work.

**Comment by tiancaiamao** [comment]
So, how about keep the flag, but change its default to true? @shenli

**Comment by shenli** [comment]
@tiancaiamao This way is better.

**Pull request merged**
