### PR TITLE
server,store,util: escape internal SQL statement

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Manually back port some of the changes https://github.com/pingcap/tidb/pull/22621

Problem Summary:

### What is changed and how it works?

What's Changed:

Escape SQL

How it Works:

### Check List 

Tests 

- No code

### Release note 

- No release note

### CODE REVIEW

**Review by xhebox — CHANGES_REQUESTED** [review]
https://github.com/pingcap/tidb/blob/4172f473dad30a53878a4539ad6d5cbf3b03e722/util/sqlexec/utils.go#L234-L235

There is `MustEscapeSQL` helper. Only invalidate type and OOM will cause error. Type/argument-length can be ensured statically. OOM should just crash.

So I believe you could use the function to simplify.

**Comment by tiancaiamao** [comment]
PTAL @xhebox @morgo

**Pull request merged**
