### PR TITLE
*: Refactor session#domainMap use RWMutex to replace Mutex

### LINKED ISSUE #33737: session#domainMap use RWMutex replace Mutex
## Enhancement
The Get() method of domainMap reading more and write less , so using mutex for synchronization is a serious waste of resources, which can be optimized from the following two aspects
1. Use RWMutex to replace Mutex synchronization block: it can improve the performance of reading and avoid blocking between reading and reading
2. Narrow the range of locks: Before using Defer to synchronize a large block of statements, we can separate locks, synchronize when reading, and synchronize when writing to reduce blocking time

The core change is insession/tidb.go as below as first edtion

```diff --git a/session/tidb.go b/session/tidb.go
index 911e64f37..236759b15 100644
--- a/session/tidb.go
+++ b/session/tidb.go
@@ -44,13 +44,11 @@ import (
 
 type domainMap struct {
        domains map[string]*domain.Domain
-       mu      sync.Mutex
+       mu      sync.RWMutex
 }
 
 func (dm *domainMap) Get(store kv.Storage) (d *domain.Domain, err error) {
-       dm.mu.Lock()
-       defer dm.mu.Unlock()
-
+       dm.mu.RLock()
        // If this is the only domain instance, and the caller doesn't provide store.
        if len(dm.domains) == 1 && store == nil {
                for _, r := range dm.domains {
@@ -60,6 +58,8 @@ func (dm *domainMap) Get(store kv.Storage) (d *domain.Domain, err error) {
 
        key := store.UUID()
        d = dm.domains[key]
+       dm.mu.RUnlock()
+
        if d != nil {
                return
        }
@@ -92,8 +92,7 @@ func (dm *domainMap) Get(store kv.Storage) (d *domain.Domain, err error) {
        if err != nil {
                return nil, err
        }
-       dm.domains[key] = d
-
+       dm.Set(store, d)
        return
 }
 
@@ -103,6 +102,12 @@ func (dm *domainMap) Delete(store kv.Storage) {
        dm.mu.Unlock()
 }
 
+func (dm *domainMap) Set(store kv.Storage, domain *domain.Domain) {
+       dm.mu.Lock()
+       dm.domains[store.UUID()] = domain
+       dm.mu.Unlock()
+}
+
 var (
        domap = &domainMap{
                domains: map[string]*domain.Domain{},
(
```

### PR DESCRIPTION
**Pull request by likzn**
### What problem does this PR solve?

Issue Number: close  #33737 

Problem Summary: Improve the performance of session#domainMap func of Get()

### Check List

Tests 

- [ ] Unit test
- [X] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
LGTM, but one comment.

This does not make much difference since domap is not used frequently anyway.. It is rarely used.

**Comment by xhebox** [comment]
@likzn SIgn CLA BTW

**Comment by likzn** [comment]
> @likzn SIgn CLA BTW

@xhebox  I had signed just now. And  I see a check-linsece in the workflow, but it dont start yet. And there is no "Details" button. What should I do..

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
