### PR TITLE
binlog: use pumps client to write binlog

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
### What problem does this PR solve? 
cherry pick commit from master

### What is changed and how it works?
git cherry-pick 508f5dd6263e4896d53fb37af99f3a1b747de713
resolve some conflicts

### Check List 

Tests 

 - Unit test

Related changes
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Comment by zz-jason** [comment]
LGTM

**Comment by zz-jason** [comment]
@lamxTyler @winoros PTAL

**Comment by WangXiangUSTC** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by WangXiangUSTC** [comment]
@winoros PTAL again

**Pull request merged**
