### PR TITLE
*: avoid using columnEvaluator for the Projectin build by buildProjtion4Union (#8142)

### PR DESCRIPTION
**Pull request by XuHuaiyu**
cherry-pick #8142

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
LGTM

**Comment by zz-jason** [comment]
@winoros @lamxTyler @eurekaka PTAL

**Comment by XuHuaiyu** [comment]
@winoros @lamxTyler @eurekaka PTAL

**Pull request merged**
