### PR TITLE
aggregation: handle non-integer input for bit related aggregate functions

### PR DESCRIPTION
**Pull request by crazycs520**
## What have you changed? (mandatory)
fix [issue#6987](https://github.com/pingcap/tidb/issues/6987#event-1717221272)
bit_or doesn't handle decimal

## What are the type of the changes (mandatory)?
Bug fix

## Does this PR affect documentation (docs/docs-cn) update? (optional)
No.

### CODE REVIEW

**Comment by zz-jason** [comment]
@crazycs520 You can add some tests in **executor/aggregate_test.go**

**Comment by crazycs520** [comment]
@zz-jason @XuHuaiyu Already add a test. PTAL.
`bit_and, bit_xor` also have the same problem too, I'll fix it.

**Comment by crazycs520** [comment]
@XuHuaiyu @zz-jason I fix the same bug of bit_and, bit_xor in this pr, PTAL.

**Pull request merged**
