### PR TITLE
planner: use the converted datum based on the target column to point get

### PR DESCRIPTION
**Pull request by Reminiscent**
### What problem does this PR solve?

Issue Number: close [#26638](https://github.com/pingcap/tidb/issues/26638)

Problem Summary:
1. When we use the `batchPointGet`, we do not convert the datum based on the target column type. It often happens in `in` condition or `prepare` statements.

### What is changed and how it works?
When we use the `batchPointGet`, we convert the datum based on the target column type.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

`None`

### CODE REVIEW

**Comment by qw4990** [comment]
@Reminiscent Please resolve conflicts.

**Review by qw4990 — APPROVED** [review]

**Review by time-and-fate — APPROVED** [review]

**Pull request merged**
