### PR TITLE
executor/aggfuncs: migrate test-infra to testify

### LINKED ISSUE #28074: migrate test-infra to testify for `executor/aggfuncs`
* [x] #28501
* [x] #28504
* [x] #28505
* [x] #28506
* [x] #28507
* [x] #28508
* [x] #28509
* [x] #28510
* [x] #28511
* [x] #28512
* [x] #28513
* [x] #28514
* [x] #28515
* [x] #28516
* [x] #28517
* [x] #28518
* [x] #28519
* [x] #28520
* [x] #28521
* [x] #28522
* [x] #28523
* [x] #28503
* [x] #28502

### LINKED ISSUE #28501: migrate test-infra to testify for `aggfunc_test.go`

### LINKED ISSUE #28511: migrate test-infra to testify for `func_json_objectagg_test.go`

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #28074.
This closes #28501.
This closes #28511.

Signed-off-by: tison <wander4096@gmail.com>

### Release note

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Comment by mmyj** [comment]
```

[2021-11-15T09:25:43.269Z] FAIL: handle_test.go:921: testSerialStatsSuite.TestAnalyzeGlobalStatsWithOpts

[2021-11-15T09:25:43.270Z] 

[2021-11-15T09:25:43.270Z] handle_test.go:952:

[2021-11-15T09:25:43.270Z]     s.checkForGlobalStatsWithOpts(c, tk, "test_gstats_opt", "p1", ca.topn, ca.buckets)

[2021-11-15T09:25:43.270Z] handle_test.go:916:

[2021-11-15T09:25:43.270Z]     // since the hist-building algorithm doesn't stipulate the final bucket number to be equal to the expected number exactly,

[2021-11-15T09:25:43.270Z]     // we have to check the results by a range here.

[2021-11-15T09:25:43.270Z]     c.Assert(numBuckets, GreaterEqual, buckets-delta)

[2021-11-15T09:25:43.270Z] ... compare_one int = 0

[2021-11-15T09:25:43.270Z] ... compare_two int = 9
```

**Comment by tisonkun** [comment]
@mmyj fixed.

**Review by mmyj — APPROVED** [review]
lgtm

**Comment by mmyj** [comment]
```

[2021-11-15T11:29:38.781Z] --- FAIL: TestCheckClusterVersion (0.00s)

[2021-11-15T11:29:38.781Z]     version_test.go:81: 

[2021-11-15T11:29:38.781Z]         	Error Trace:	version_test.go:81

[2021-11-15T11:29:38.781Z]         	Error:      	Received unexpected error:

[2021-11-15T11:29:38.781Z]         	            	[BR:Common:ErrVersionMismatch]version mismatch

[2021-11-15T11:29:38.782Z]         	            	TiKV node  version 3.1.0-beta.2 and BR v4.0.0-rc.1 major version mismatch, please use the same version of BR

[2021-11-15T11:29:38.782Z]         	            	github.com/pingcap/tidb/br/pkg/version.CheckVersionForBR

[2021-11-15T11:29:38.782Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/br/pkg/version/version.go:139

[2021-11-15T11:29:38.782Z]         	            	github.com/pingcap/tidb/br/pkg/version.CheckClusterVersion

[2021-11-15T11:29:38.782Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/br/pkg/version/version.go:107

[2021-11-15T11:29:38.782Z]         	            	github.com/pingcap/tidb/br/pkg/version.TestCheckClusterVersion

[2021-11-15T11:29:38.782Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/br/pkg/version/version_test.go:80

[2021-11-15T11:29:38.782Z]         	            	testing.tRunner

[2021-11-15T11:29:38.782Z]         	            		/usr/local/go/src/testing/testing.go:1193

[2021-11-15T11:29:38.782Z]         	            	runtime.goexit

[2021-11-15T11:29:38.782Z]         	            		/usr/local/go/src/runtime/asm_amd64.s:1371

[2021-11-15T11:29:38.782Z]         	Test:       	TestCheckClusterVersion
```

**Pull request merged**
