### PR TITLE
expression: json builtin function archetypes

### PR DESCRIPTION
**Pull request by mccxj**
### What problem does this PR solve? 

https://github.com/pingcap/tidb/issues/7546

### What is changed and how it works?

like https://pingcap.com/blog-cn/add-a-built-in-function/, add json builtin function archetypes.

### CODE REVIEW

**Comment by shenli** [comment]
@mccxj Thanks!

**Comment by zz-jason** [comment]
@XuHuaiyu PTAL

**Comment by zz-jason** [comment]
@winoros @eurekaka PTAL

**Comment by shenli** [comment]
LGTM

**Pull request merged**
