### PR TITLE
planner: return error when the item of ORDER BY is hidden column

### LINKED ISSUE #26214: order by hidden column should report errors
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `t` (
  `a` int(11) DEFAULT NULL,
  `b` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  KEY `expression_index` ((case when `a` < 0 then 1 else 2 end))
);
select * from t  where case when a < 0 then 1 else 2 end <= 1 order by 4;
```

### 2. What did you expect to see? (Required)
``` SQL
ERROR 1054 (42S22): Unknown column '4' in 'order clause'
```
### 3. What did you see instead (Required)
No error. The result is ordered by the hidden column.
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #26214 

Problem Summary:
If the item of ORDER BY is hidden column, TiDB should return `Unknown column xxx in 'order clause'` but it didn't.

### What is changed and how it works?

What's Changed & How it Works:
In `positionToScalarFunc`, check whether the column that `PositionExpr` refers to is hidden column. If yes, return error.

### Check List 

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [x] Performance regression: Consumes more CPU
- [x] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- return error when the item of ORDER BY is hidden column

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]

**Comment by Reminiscent** [comment]
Should we cherry-pick this PR? @xuyifangreeneyes

**Comment by xuyifangreeneyes** [comment]
> Should we cherry-pick this PR? @xuyifangreeneyes

IMO, we don't need to.

**Pull request merged**
