### PR TITLE
session: fix users which username contains '@' auth error

### PR DESCRIPTION
**Pull request by choleraehyq**
Fix https://github.com/pingcap/tidb/issues/3740

@breeswish @tiancaiamao @lamxTyler @zimulala PTAL

Signed-off-by: Cholerae Hu <huyingqian@pingcap.com>

### CODE REVIEW

**Comment by breeswish** [comment]
LGTM, although I prefer to use a structural solution, i.e. storing username and hostname independently.

**Comment by breeswish** [comment]
~~LGTM~~, although I prefer to use a structural solution, i.e. storing username and hostname independently.

Update:

I think storing via structure is the best and only correct solution for this issue. Your PR only solves #3740 but does not solve the fundamental problem. Consider the following scenario:
1. A user created a user named "a@b" with hostname "c@d" (by mistake).
2. The user want to modify this user to a correct hostname "localhost".
3. The operation will fail because we store username as "a@b@c".

**Comment by choleraehyq** [comment]
Agree with you. Close this PR.

**Comment by choleraehyq** [comment]
@breeswish mysql don't allowed `@` in host name.
```
mysql> create user 'a@b'@'c@d' identified by '123';
ERROR 1105 (HY000): Malformed hostname (illegal symbol: '@')
```

**Comment by breeswish** [comment]
There are still issues if we keep current strategy (i.e. store "username@host" together instead of a structure). For example, as you pointed out, MySQL will detect a malformed hostname (after parsing). However, when using the current strategy we cannot implement this "malformed hostname detect" feature because we can no longer distinguish which part is the hostname and which part is the username after parsing.

**Pull request closed without merging**
