### PR TITLE
executor: resort fields for reducing the memory allocated

### PR DESCRIPTION
**Pull request by hsqlu**
### What problem does this PR solve? 
#13925

### What is changed and how it works?
resort the fields according golangci-lint maligned output
```
executor/cluster_reader.go:210:33: struct of size 24 bytes could be of size 16 bytes (maligned)
type clusterServerInfoRetriever struct {
                                ^
executor/insert_common.go:37:19: struct of size 384 bytes could be of size 368 bytes (maligned)
type InsertValues struct {
                  ^
executor/join.go:42:19: struct of size 448 bytes could be of size 432 bytes (maligned)
type HashJoinExec struct {
                  ^
executor/join.go:719:26: struct of size 392 bytes could be of size 384 bytes (maligned)
type NestedLoopApplyExec struct {
                         ^
executor/load_data.go:506:18: struct of size 88 bytes could be of size 80 bytes (maligned)
type fieldWriter struct {
                 ^
executor/projection.go:55:21: struct of size 288 bytes could be of size 280 bytes (maligned)
type ProjectionExec struct {
                    ^
executor/update.go:33:17: struct of size 272 bytes could be of size 264 bytes (maligned)
type UpdateExec struct {
                ^
executor/benchmark_test.go:532:23: struct of size 104 bytes could be of size 96 bytes (maligned)
type hashJoinTestCase struct {
                      ^
```

### Check List 
Run golangci-lint before this change:
```
sessionctx/stmtctx/stmtctx.go:49:23: struct of size 608 bytes could be of size 584 bytes (maligned)
type StatementContext struct {
                      ^
config/config.go:58:13: struct of size 1080 bytes could be of size 1040 bytes (maligned)
type Config struct {
            ^
store/tikv/tikvrpc/tikvrpc.go:143:14: struct of size 152 bytes could be of size 144 bytes (maligned)
type Request struct {
             ^
meta/autoid/autoid.go:105:16: struct of size 96 bytes could be of size 88 bytes (maligned)
type allocator struct {
               ^
types/convert_test.go:885:13: struct of size 56 bytes could be of size 48 bytes (maligned)
        tests := []struct {
                   ^
sessionctx/variable/session.go:249:18: struct of size 1072 bytes could be of size 992 bytes (maligned)
type SessionVars struct {
                 ^
planner/util/path.go:27:17: struct of size 272 bytes could be of size 264 bytes (maligned)
type AccessPath struct {
                ^
distsql/select_result.go:54:19: struct of size 216 bytes could be of size 208 bytes (maligned)
type selectResult struct {
                  ^
store/tikv/2pc.go:101:24: struct of size 240 bytes could be of size 232 bytes (maligned)
type twoPhaseCommitter struct {
                       ^
store/tikv/client_batch.go:38:16: struct of size 96 bytes could be of size 88 bytes (maligned)
type batchConn struct {
               ^
store/tikv/kv.go:139:16: struct of size 240 bytes could be of size 232 bytes (maligned)
type tikvStore struct {
               ^
planner/memo/group.go:76:12: struct of size 80 bytes could be of size 72 bytes (maligned)
type Group struct {
           ^
planner/core/common_plans.go:521:13: struct of size 368 bytes could be of size 360 bytes (maligned)
type Insert struct {
            ^
planner/core/physical_plans.go:365:29: struct of size 528 bytes could be of size 520 bytes (maligned)
type PhysicalIndexMergeJoin struct {
                            ^
expression/builtin.go:46:22: struct of size 104 bytes could be of size 88 bytes (maligned)
type baseBuiltinFunc struct {
                     ^
expression/column.go:180:13: struct of size 104 bytes could be of size 96 bytes (maligned)
type Column struct {
            ^
expression/builtin_cast_test.go:836:24: struct of size 56 bytes could be of size 48 bytes (maligned)
        castToTimeCases2 := []struct {
                              ^
executor/cluster_reader.go:210:33: struct of size 24 bytes could be of size 16 bytes (maligned)
type clusterServerInfoRetriever struct {
                                ^
executor/insert_common.go:37:19: struct of size 384 bytes could be of size 368 bytes (maligned)
type InsertValues struct {
                  ^
executor/join.go:42:19: struct of size 448 bytes could be of size 432 bytes (maligned)
type HashJoinExec struct {
                  ^
executor/join.go:719:26: struct of size 392 bytes could be of size 384 bytes (maligned)
type NestedLoopApplyExec struct {
                         ^
executor/load_data.go:506:18: struct of size 88 bytes could be of size 80 bytes (maligned)
type fieldWriter struct {
                 ^
executor/projection.go:55:21: struct of size 288 bytes could be of size 280 bytes (maligned)
type ProjectionExec struct {
                    ^
executor/update.go:33:17: struct of size 272 bytes could be of size 264 bytes (maligned)
type UpdateExec struct {
                ^
executor/benchmark_test.go:532:23: struct of size 104 bytes could be of size 96 bytes (maligned)
type hashJoinTestCase struct {
                      ^
types/time_test.go:280:13: struct of size 64 bytes could be of size 56 bytes (maligned)
        table := []struct {
                   ^
types/time_test.go:319:13: struct of size 64 bytes could be of size 56 bytes (maligned)
        table := []struct {
                   ^
types/time_test.go:510:13: struct of size 80 bytes could be of size 64 bytes (maligned)
        table := []struct {
                   ^
types/time_test.go:661:11: struct of size 40 bytes could be of size 32 bytes (maligned)
        tbl := []struct {
                 ^
```

Run golangci-lint after this change:
```
sessionctx/stmtctx/stmtctx.go:49:23: struct of size 584 bytes could be of size 560 bytes (maligned)
type StatementContext struct {
                      ^
config/config.go:58:13: struct of size 1080 bytes could be of size 1040 bytes (maligned)
type Config struct {
            ^
types/convert_test.go:885:13: struct of size 56 bytes could be of size 48 bytes (maligned)
        tests := []struct {
                   ^
store/tikv/tikvrpc/tikvrpc.go:143:14: struct of size 152 bytes could be of size 144 bytes (maligned)
type Request struct {
             ^
meta/autoid/autoid.go:105:16: struct of size 96 bytes could be of size 88 bytes (maligned)
type allocator struct {
               ^
sessionctx/variable/session.go:214:18: struct of size 1072 bytes could be of size 992 bytes (maligned)
type SessionVars struct {
                 ^
planner/util/path.go:27:17: struct of size 272 bytes could be of size 264 bytes (maligned)
type AccessPath struct {
                ^
distsql/select_result.go:54:19: struct of size 216 bytes could be of size 208 bytes (maligned)
type selectResult struct {
                  ^
store/tikv/2pc.go:101:24: struct of size 240 bytes could be of size 232 bytes (maligned)
type twoPhaseCommitter struct {
                       ^
store/tikv/client_batch.go:38:16: struct of size 96 bytes could be of size 88 bytes (maligned)
type batchConn struct {
               ^
store/tikv/kv.go:139:16: struct of size 240 bytes could be of size 232 bytes (maligned)
type tikvStore struct {
               ^
planner/memo/group.go:76:12: struct of size 80 bytes could be of size 72 bytes (maligned)
type Group struct {
           ^
planner/core/common_plans.go:521:13: struct of size 368 bytes could be of size 360 bytes (maligned)
type Insert struct {
            ^
planner/core/physical_plans.go:365:29: struct of size 528 bytes could be of size 520 bytes (maligned)
type PhysicalIndexMergeJoin struct {
                            ^
expression/builtin.go:46:22: struct of size 104 bytes could be of size 88 bytes (maligned)
type baseBuiltinFunc struct {
                     ^
expression/column.go:180:13: struct of size 104 bytes could be of size 96 bytes (maligned)
type Column struct {
            ^
expression/builtin_cast_test.go:836:24: struct of size 56 bytes could be of size 48 bytes (maligned)
        castToTimeCases2 := []struct {
                              ^
types/time_test.go:280:13: struct of size 64 bytes could be of size 56 bytes (maligned)
        table := []struct {
                   ^
types/time_test.go:319:13: struct of size 64 bytes could be of size 56 bytes (maligned)
        table := []struct {
                   ^
types/time_test.go:510:13: struct of size 80 bytes could be of size 64 bytes (maligned)
        table := []struct {
                   ^
types/time_test.go:661:11: struct of size 40 bytes could be of size 32 bytes (maligned)
        tbl := []struct {
                 ^
```

### CODE REVIEW

**Comment by wjhuang2016** [comment]
Thanks, could you please run golangci-lint and put the result in checklist?

**Comment by hsqlu** [comment]
Run golangci-lint before this change:
```
sessionctx/stmtctx/stmtctx.go:49:23: struct of size 608 bytes could be of size 584 bytes (maligned)
type StatementContext struct {
                      ^
config/config.go:58:13: struct of size 1080 bytes could be of size 1040 bytes (maligned)
type Config struct {
            ^
store/tikv/tikvrpc/tikvrpc.go:143:14: struct of size 152 bytes could be of size 144 bytes (maligned)
type Request struct {
             ^
meta/autoid/autoid.go:105:16: struct of size 96 bytes could be of size 88 bytes (maligned)
type allocator struct {
               ^
types/convert_test.go:885:13: struct of size 56 bytes could be of size 48 bytes (maligned)
        tests := []struct {
                   ^
sessionctx/variable/session.go:249:18: struct of size 1072 bytes could be of size 992 bytes (maligned)
type SessionVars struct {
                 ^
planner/util/path.go:27:17: struct of size 272 bytes could be of size 264 bytes (maligned)
type AccessPath struct {
                ^
distsql/select_result.go:54:19: struct of size 216 bytes could be of size 208 bytes (maligned)
type selectResult struct {
                  ^
store/tikv/2pc.go:101:24: struct of size 240 bytes could be of size 232 bytes (maligned)
type twoPhaseCommitter struct {
                       ^
store/tikv/client_batch.go:38:16: struct of size 96 bytes could be of size 88 bytes (maligned)
type batchConn struct {
               ^
store/tikv/kv.go:139:16: struct of size 240 bytes could be of size 232 bytes (maligned)
type tikvStore struct {
               ^
planner/memo/group.go:76:12: struct of size 80 bytes could be of size 72 bytes (maligned)
type Group struct {
           ^
planner/core/common_plans.go:521:13: struct of size 368 bytes could be of size 360 bytes (maligned)
type Insert struct {
            ^
planner/core/physical_plans.go:365:29: struct of size 528 bytes could be of size 520 bytes (maligned)
type PhysicalIndexMergeJoin struct {
                            ^
expression/builtin.go:46:22: struct of size 104 bytes could be of size 88 bytes (maligned)
type baseBuiltinFunc struct {
                     ^
expression/column.go:180:13: struct of size 104 bytes could be of size 96 bytes (maligned)
type Column struct {
            ^
expression/builtin_cast_test.go:836:24: struct of size 56 bytes could be of size 48 bytes (maligned)
        castToTimeCases2 := []struct {
                              ^
executor/cluster_reader.go:210:33: struct of size 24 bytes could be of size 16 bytes (maligned)
type clusterServerInfoRetriever struct {
                                ^
executor/insert_common.go:37:19: struct of size 384 bytes could be of size 368 bytes (maligned)
type InsertValues struct {
                  ^
executor/join.go:42:19: struct of size 448 bytes could be of size 432 bytes (maligned)
type HashJoinExec struct {
                  ^
executor/join.go:719:26: struct of size 392 bytes could be of size 384 bytes (maligned)
type NestedLoopApplyExec struct {
                         ^
executor/load_data.go:506:18: struct of size 88 bytes could be of size 80 bytes (maligned)
type fieldWriter struct {
                 ^
executor/projection.go:55:21: struct of size 288 bytes could be of size 280 bytes (maligned)
type ProjectionExec struct {
                    ^
executor/update.go:33:17: struct of size 272 bytes could be of size 264 bytes (maligned)
type UpdateExec struct {
                ^
executor/benchmark_test.go:532:23: struct of size 104 bytes could be of size 96 bytes (maligned)
type hashJoinTestCase struct {
                      ^
types/time_test.go:280:13: struct of size 64 bytes could be of size 56 bytes (maligned)
        table := []struct {
                   ^
types/time_test.go:319:13: struct of size 64 bytes could be of size 56 bytes (maligned)
        table := []struct {
                   ^
types/time_test.go:510:13: struct of size 80 bytes could be of size 64 bytes (maligned)
        table := []struct {
                   ^
types/time_test.go:661:11: struct of size 40 bytes could be of size 32 bytes (maligned)
        tbl := []struct {
                 ^
```

Run golangci-lint after this change:
```
sessionctx/stmtctx/stmtctx.go:49:23: struct of size 584 bytes could be of size 560 bytes (maligned)
type StatementContext struct {
                      ^
config/config.go:58:13: struct of size 1080 bytes could be of size 1040 bytes (maligned)
type Config struct {
            ^
types/convert_test.go:885:13: struct of size 56 bytes could be of size 48 bytes (maligned)
        tests := []struct {
                   ^
store/tikv/tikvrpc/tikvrpc.go:143:14: struct of size 152 bytes could be of size 144 bytes (maligned)
type Request struct {
             ^
meta/autoid/autoid.go:105:16: struct of size 96 bytes could be of size 88 bytes (maligned)
type allocator struct {
               ^
sessionctx/variable/session.go:214:18: struct of size 1072 bytes could be of size 992 bytes (maligned)
type SessionVars struct {
                 ^
planner/util/path.go:27:17: struct of size 272 bytes could be of size 264 bytes (maligned)
type AccessPath struct {
                ^
distsql/select_result.go:54:19: struct of size 216 bytes could be of size 208 bytes (maligned)
type selectResult struct {
                  ^
store/tikv/2pc.go:101:24: struct of size 240 bytes could be of size 232 bytes (maligned)
type twoPhaseCommitter struct {
                       ^
store/tikv/client_batch.go:38:16: struct of size 96 bytes could be of size 88 bytes (maligned)
type batchConn struct {
               ^
store/tikv/kv.go:139:16: struct of size 240 bytes could be of size 232 bytes (maligned)
type tikvStore struct {
               ^
planner/memo/group.go:76:12: struct of size 80 bytes could be of size 72 bytes (maligned)
type Group struct {
           ^
planner/core/common_plans.go:521:13: struct of size 368 bytes could be of size 360 bytes (maligned)
type Insert struct {
            ^
planner/core/physical_plans.go:365:29: struct of size 528 bytes could be of size 520 bytes (maligned)
type PhysicalIndexMergeJoin struct {
                            ^
expression/builtin.go:46:22: struct of size 104 bytes could be of size 88 bytes (maligned)
type baseBuiltinFunc struct {
                     ^
expression/column.go:180:13: struct of size 104 bytes could be of size 96 bytes (maligned)
type Column struct {
            ^
expression/builtin_cast_test.go:836:24: struct of size 56 bytes could be of size 48 bytes (maligned)
        castToTimeCases2 := []struct {
                              ^
types/time_test.go:280:13: struct of size 64 bytes could be of size 56 bytes (maligned)
        table := []struct {
                   ^
types/time_test.go:319:13: struct of size 64 bytes could be of size 56 bytes (maligned)
        table := []struct {
                   ^
types/time_test.go:510:13: struct of size 80 bytes could be of size 64 bytes (maligned)
        table := []struct {
                   ^
types/time_test.go:661:11: struct of size 40 bytes could be of size 32 bytes (maligned)
        tbl := []struct {
                 ^
```

**Comment by Deardrops** [comment]
LGTM

**Comment by wjhuang2016** [comment]
@hsqlu Please fix the conflict

**Comment by hsqlu** [comment]
> @hsqlu Please resolve the conflict

Done. PTAL

**Pull request merged**
