### PR TITLE
types: migrate test-infra to testify for `datum_test.go`

### LINKED ISSUE #27999: migrate test-infra to testify for `datum_test.go`

### PR DESCRIPTION
**Pull request by karuppiah7890**
### What problem does this PR solve?

Issue Number: close #27999 

Problem Summary:

### What is changed and how it works?

What's Changed:
- Migrated 13 test functions in `types/datum_test.go` from `github.com/pingcap/check` to `github.com/stretchr/testify`
- Parallelized all the tests

### Check List

Tests

- [x] Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM. Nice work!

**Comment by karuppiah7890** [comment]
Looks like the CI failure is not related to this PR. Pipeline - https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/34525/pipeline/ . Failure log -

```bash
[2021-09-18T07:18:40.274Z] FAIL
[2021-09-18T07:18:40.274Z] + cat test.log
[2021-09-18T07:18:40.274Z] + grep -Ev '^\[[[:digit:]]{4}(/[[:digit:]]{2}){2}'
[2021-09-18T07:18:40.274Z] + grep -A 30 '\-------'
[2021-09-18T07:18:40.274Z] + grep -A 29 FAIL
[2021-09-18T07:18:40.274Z] FAIL: db_partition_test.go:2181: testIntegrationSuite5.TestTruncatePartitionAndDropTable
[2021-09-18T07:18:40.274Z] 
[2021-09-18T07:18:40.274Z] db_partition_test.go:2245:
[2021-09-18T07:18:40.274Z]     c.Assert(hasOldPartitionData, IsFalse, Commentf("take time %v", time.Since(startTime)))
[2021-09-18T07:18:40.274Z] ... obtained bool = true
[2021-09-18T07:18:40.274Z] ... take time 15.211611077s
```

**Review by mmyj — APPROVED** [review]
lgtm

**Pull request merged**
