### PR TITLE
expression, types: remove the useage of "evalExprToXXX" functions

### LINKED ISSUE #4405: abandon the usage of functions like `evalExprToReal`
construct a bigint constant value named `a` and a double constant value named `b`, and test builtin expression `a+b` with constant folding being disabled.

`go tool pprof`:
```
(pprof) top
380ms of 400ms total (95.00%)
Showing top 10 nodes out of 21 (cum >= 40ms)
      flat  flat%   sum%        cum   cum%
     120ms 30.00% 30.00%      120ms 30.00%  runtime.usleep
      70ms 17.50% 47.50%       70ms 17.50%  runtime.duffcopy
      40ms 10.00% 57.50%      220ms 55.00%  github.com/pingcap/tidb/expression.(*builtinArithmeticPlusRealSig).evalReal
      30ms  7.50% 65.00%      110ms 27.50%  github.com/pingcap/tidb/expression.(*Constant).EvalReal
      30ms  7.50% 72.50%       80ms 20.00%  github.com/pingcap/tidb/expression.evalExprToReal
      20ms  5.00% 77.50%       20ms  5.00%  github.com/pingcap/tidb/expression.(*Constant).GetTypeClass
      20ms  5.00% 82.50%      280ms 70.00%  github.com/pingcap/tidb/expression.(*ScalarFunction).Eval
      20ms  5.00% 87.50%      240ms 60.00%  github.com/pingcap/tidb/expression.(*baseRealBuiltinFunc).eval
      20ms  5.00% 92.50%       50ms 12.50%  github.com/pingcap/tidb/expression.evalExprToInt
      10ms  2.50% 95.00%       40ms 10.00%  github.com/pingcap/tidb/expression.(*Constant).Eval
```

1. `(*Constant).GetTypeClass` appears and take `5%` of total cpu time, which should not
2. cpu time ratio of `runtime.duffcopy` is too high, which is `17.50%`

flame graph produced with the previous profiling file by `go-torch`:

take a inside look at `callgrind` of function `evalExprToReal`:

So, we can summarize that:
1. the main cause of `runtime.duffcopy` is the duplication of `Datum` returned by `expr.Eval(Row)`
2. the root cause of `expression.(*Constant).GetTypeClass` is the function call `expr.GetTypeClass()`, which can be avoid totally

### PR DESCRIPTION
**Pull request by zz-jason**
fix #4405 

before this pr:

```
BenchmarkEvalInt-8              50000000                28.9 ns/op             0 B/op          0 allocs/op
BenchmarkEvalReal-8             50000000                30.5 ns/op             0 B/op          0 allocs/op
BenchmarkEvalString-8           50000000                34.6 ns/op             0 B/op          0 allocs/op
PASS
ok      github.com/pingcap/tidb/expression      4.825s
```

after this pr:
```
BenchmarkEvalInt-8              200000000                6.40 ns/op            0 B/op          0 allocs/op
BenchmarkEvalReal-8             200000000                6.72 ns/op            0 B/op          0 allocs/op
BenchmarkEvalString-8           100000000               15.3 ns/op             0 B/op          0 allocs/op
PASS
ok      github.com/pingcap/tidb/expression      5.554s
```

### CODE REVIEW

**Comment by shenli** [comment]
Impressive!

**Comment by zz-jason** [comment]
@shenli @coocood PTAL

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
