### PR TITLE
distsql: avoid false positive error log about `invalid cop task execution summaries length`

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
If TiDB is running query in MPP mode, there may be many error log about `invalid cop task execution summaries length`, it often makes user confused.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

In fact, for streaming rpc to TiFlash(BatchCop and MPP), it is by design that only the last response will carry the execution summaries, so it is ok if some responses have no execution summaries, should not trigger an error log in this case.
### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 
```release-note 
Avoid false positive error log about `invalid cop task execution summaries length` when running MPP query.
```

### CODE REVIEW

**Review by fzhedu — APPROVED** [review]
/LGTM

**Review by ichn-hu — APPROVED** [review]
LGTM

**Pull request merged**
