### PR TITLE
Control the number of rows in chunks returned by LimitExec (#9354)

### PR DESCRIPTION
**Pull request by qw4990**
cherry pick from #9354

### CODE REVIEW

**Comment by zz-jason** [comment]
LGTM

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by qw4990** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by qw4990** [comment]
@lysu  PTAL~

**Pull request merged**
