### PR TITLE
dockerfile: upgrade golang

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — COMMENTED** [review]
I have a suggestion:

```
RUN curl xxxxxx$(grep -m 1 go /tidb/go.mod | cut -d\  -f2)xxxx
```

Does that work?

**Comment by hawkingrei** [comment]
> I have a suggestion:
> 
> ```
> RUN curl xxxxxx$(grep -m 1 go /tidb/go.mod | cut -d\  -f2)xxxx
> ```
> 
> Does that work?

In principle, it is feasible, but I find it cumbersome to implement.

**Comment by hawkingrei** [comment]
> I have a suggestion:
> 
> ```
> RUN curl xxxxxx$(grep -m 1 go /tidb/go.mod | cut -d\  -f2)xxxx
> ```
> 
> Does that work?

In the bazel, it has [rules_docker](https://github.com/bazelbuild/rules_docker) to build image and bazel will manage go version. That would be very natural. However, the bad news is that the release system does not use Bazel, nor does it use this image file."

**Review by xhebox — APPROVED** [review]

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
