### PR TITLE
extension: fix unstable test TestAuditLogReservedDays

### LINKED ISSUE #43872: unstable test TestAuditLogReservedDays
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
    sysvar_test.go:364: 
        	Error Trace:	extension/enterprise/audit/sysvar_test.go:364
        	Error:      	Should not be: "/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/linux-sandbox/7067/execroot/__main__/bazel-out/k8-fastbuild/bin/extension/enterprise/audit/audit_test_/audit_test.runfiles/__main__/extension/enterprise/audit/tidb-audit-2023-05-16T16-01-19.786.log"
        	Test:       	TestAuditLogReservedDays
        	Messages:   	/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/linux-sandbox/7067/execroot/__main__/bazel-out/k8-fastbuild/bin/extension/enterprise/audit/audit_test_/audit_test.runfiles/__main__/extension/enterprise/audit/tidb-audit-2023-05-16T16-01-19.786.log /home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/linux-sandbox/7067/execroot/__main__/bazel-out/k8-fastbuild/bin/extension/enterprise/audit/audit_test_/audit_test.runfiles/__main__/extension/enterprise/audit/tidb-audit-2023-05-16T16-01-19.786.log
```

https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/ghpr_unit_test/runs/24584/nodes/59/steps/64/log/?start=0

### PR DESCRIPTION
**Pull request by CbcWestwolf**
### What problem does this PR solve?

Issue Number: close #43872

Problem Summary:

### Check List

Tests 

- [x] Unit test (current UT)
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by CbcWestwolf** [comment]
/cc hawkingrei lcwangchao  
PTAL

**Review by hawkingrei — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
