### PR TITLE
*: introduce @@tidb_max_paging_size system variable for tuning

### LINKED ISSUE #36328: Expirement to choose the best value for page size (or self-adapting)
In the past, we use default value min paging size = 64
max paging size = 8192 (64 << 7) 

We need to figure out whether this setting is reasonable.

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #36328

Problem Summary:

Default max paging size = 8192 seems not meet all the requirements.
We found a regression in tpch q17

image

When the paging size reach max_paging_size, it doesn't grow any more.
table reader may need more RPCs.

More RPCs does not necessarily mean more time for query.
For example, the consumer works concurrently with the producer, it's a pipeline ... there is not wait on the extra RPCs.

However, this is not the case for HashJoin.
The HashJoin probe side is a pipeline, while the build size is pipeline breaker: the probe size need to wait the build side to finish before it can work. More RPCs means slower.

### What is changed and how it works?

Default max paging size = 8192 can't work under all circumstance, expose a system variable @@tidb_max_paging_size for tuning.

When @@tidb_max_paging_size = max int64, the performance should be close to disable paging.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Expose a system variable @@tidb_max_paging_size for coprocessor paging protocol tuning.
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by xhebox — CHANGES_REQUESTED** [review]
Looks like tests is not fixed, @tiancaiamao 

···
 store/copr/coprocessor_test.go:511:15: cannot use true (untyped bool constant) as struct{Enable bool; MinPagingSize uint64; MaxPagingSize uint64} value in assignment (typecheck)

[2022-07-27T03:33:33.568Z] 	req.Paging = true

[2022-07-27T03:33:33.568Z] 	             ^

[2022-07-27T03:33:33.568Z] store/copr/coprocessor_test.go:512:6: req.MinPagingSize undefined (type *"github.com/pingcap/tidb/kv".Request has no field or method MinPagingSize) (typecheck)

[2022-07-27T03:33:33.568Z] 	req.MinPagingSize = paging.MinPagingSize
···

**Review by xhebox — APPROVED** [review]

**Comment by tiancaiamao** [comment]
PTAL @XuHuaiyu @wshwsh12

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
