### PR TITLE
config: fix config toml file `check-mb4-value-in-utf8` problem.

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
Currently in `config/config.toml.example` file,  variable  `check-mb4-value-in-utf8` is belong to the `[binlog]` scope,  but It should be  the global scope correspond to the `Config` struct.

### What is changed and how it works?
Move `check-mb4-value-in-utf8` to global scope in `config/config.toml.example` file.

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by xiekeyi98** [comment]
> fix config toml file problem.

What problem?

**Comment by crazycs520** [comment]
@xiekeyi98 Sorry for my fuzzy definition in PR description. PTAL again.

**Comment by shenli** [comment]
LGTM

**Comment by zimulala** [comment]
@crazycs520  Please pick this commit to v2.1.

**Pull request merged**
