### PR TITLE
ddl: remove useless error

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: ref #31716

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by ngaut — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by zimulala** [comment]
Please fix CI:
```
[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/39691/pipeline#step-59-log-230)[2022-03-09T08:19:49.929Z] /go/pkg/mod/github.com/pingcap/tidb-tools@v5.4.1-0.20220221041303-00998a9a4bfd+incompatible/pkg/dbutil/common.go:844:7: undefined: ddl.ErrDupKeyName

[2022-03-09T08:19:49.929Z] WARN invalid TestEvent: FAIL	github.com/pingcap/tidb/dumpling/export [build failed]
```

**Pull request merged**
