### PR TITLE
planner: add sub plan info of shuffleReceiver when query explain analyze

### LINKED ISSUE #27989: Missing sub plan info of ShuffleReceiver executor
### 1. Minimal reproduce step (Required)

1. preparing data 
```
tiup bench tpch -H 0.0.0.0 -P 4000 -U root -D tpch prepare
```
2. executing query
```sql
use tpch;
explain analyze
SELECT MIN(ps_supplycost) over (partition by p_partkey) as min_ps_supplycost
FROM tpch.part,
     tpch.partsupp,
     tpch.supplier,
     tpch.nation,
     tpch.region
WHERE p_partkey = ps_partkey
  AND s_nationkey = n_nationkey
  AND s_suppkey = ps_suppkey
  AND n_regionkey = r_regionkey;
```

### 2. What did you expect to see? (Required)

```
Projection_21
└─Shuffle_64
  └─Window_22
    └─Sort_63
      └─ShuffleReceiver_69
          └─sub join plan
```

### 3. What did you see instead (Required)

```
Projection_21
└─Shuffle_64
  └─Window_22
    └─Sort_63
      └─ShuffleReceiver_69
```

### 4. What is your TiDB version? (Required)

- master
- 5.2.1

### PR DESCRIPTION
**Pull request by mmyj**
### What problem does this PR solve?

Issue Number: close #27989 

Problem Summary:

The `explainPlanInRowFormat` function miss a processing to format `PhysicalShuffleReceiverStub` sub plan.

### What is changed and how it works?

What's Changed:

Add a processing to format `PhysicalShuffleReceiverStub` sub plan.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by mmyj** [comment]
- query
```
explain analyze
SELECT MIN(ps_supplycost) over (partition by p_partkey) as min_ps_supplycost
FROM tpch.part,
     tpch.partsupp,
     tpch.supplier,
     tpch.nation,
     tpch.region
WHERE p_partkey = ps_partkey
  AND s_nationkey = n_nationkey
  AND s_suppkey = ps_suppkey
  AND n_regionkey = r_regionkey;
```

- before
```
Projection_21,200642.05,800000,root,"","time:3.18s, loops:785, Concurrency:5",Column#31,651.4 KB,N/A
└─Shuffle_64,200642.05,800000,root,"","time:3.17s, loops:785, ShuffleConcurrency:5","execution info: concurrency:5, data sources:[Projection_24]",N/A,N/A
  └─Window_22,200642.05,800000,root,"","time:15.8s, loops:789",min(tpch.partsupp.ps_supplycost)->Column#31 over(partition by tpch.part.p_partkey),N/A,N/A
    └─Sort_63,200642.05,800000,root,"","time:15.3s, loops:789",tpch.part.p_partkey,7.60 MB,0 Bytes
      └─ShuffleReceiver_69,200642.05,0,root,"","","",N/A,N/A
```

- after
```
Projection_21,200642.05,800000,root,"","time:3.29s, loops:785, Concurrency:5",Column#31,651.4 KB,N/A
└─Shuffle_64,200642.05,800000,root,"","time:3.29s, loops:785, ShuffleConcurrency:5","execution info: concurrency:5, data sources:[Projection_24]",N/A,N/A
  └─Window_22,200642.05,800000,root,"","time:16.4s, loops:789",min(tpch.partsupp.ps_supplycost)->Column#31 over(partition by tpch.part.p_partkey),N/A,N/A
    └─Sort_63,200642.05,800000,root,"","time:15.9s, loops:789",tpch.part.p_partkey,7.60 MB,0 Bytes
      └─ShuffleReceiver_69,200642.05,0,root,"","","",N/A,N/A
        └─Projection_24,200642.05,1600000,root,"","time:17.3s, loops:1572, Concurrency:5","tpch.part.p_partkey, tpch.partsupp.ps_supplycost",497.5 KB,N/A
          └─HashJoin_37,200642.05,800000,root,"","time:2.74s, loops:783, build_hash_table:{total:2.73s, fetch:2.5s, build:230.6ms}, probe:{concurrency:5, total:14.5s, max:2.91s, probe:843.4ms, fetch:13.7s}","inner join, equal:[eq(tpch.partsupp.ps_partkey, tpch.part.p_partkey)]",37.0 MB,0 Bytes
            ├─HashJoin_39(Build),200000.00,800000,root,"","time:2.69s, loops:783, build_hash_table:{total:31.2ms, fetch:26.5ms, build:4.78ms}, probe:{concurrency:5, total:13.6s, max:2.73s, probe:927.8ms, fetch:12.7s}","inner join, equal:[eq(tpch.supplier.s_suppkey, tpch.partsupp.ps_suppkey)]",88.6 KB,0 Bytes
            │ ├─HashJoin_41(Build),2500.00,10000,root,"","time:27.5ms, loops:11, build_hash_table:{total:1.53ms, fetch:1.51ms, build:20.4µs}, probe:{concurrency:5, total:144.1ms, max:29.7ms, probe:15.5ms, fetch:128.7ms}","inner join, equal:[eq(tpch.nation.n_nationkey, tpch.supplier.s_nationkey)]",372 Bytes,0 Bytes
            │ │ ├─HashJoin_52(Build),6.25,25,root,"","time:1.42ms, loops:2, build_hash_table:{total:1.16ms, fetch:1.13ms, build:29.7µs}, probe:{concurrency:5, total:5.79ms, max:1.25ms, probe:90.6µs, fetch:5.7ms}","inner join, equal:[eq(tpch.region.r_regionkey, tpch.nation.n_regionkey)]",8.23 KB,0 Bytes
            │ │ │ ├─TableReader_56(Build),5.00,5,root,"","time:1.02ms, loops:2, cop_task: {num: 1, max: 2.5ms, proc_keys: 0, tot_proc: 2ms, rpc_num: 1, rpc_time: 2.43ms, copr_cache_hit_ratio: 0.00}",data:TableFullScan_55,170 Bytes,N/A
            │ │ │ │ └─TableFullScan_55,5.00,5,cop[tikv],table:region,"tikv_task:{time:5.9µs, loops:5}","keep order:false, stats:pseudo",N/A,N/A
            │ │ │ └─TableReader_54(Probe),25.00,25,root,"","time:537µs, loops:2, cop_task: {num: 1, max: 1.9ms, proc_keys: 0, tot_proc: 1ms, rpc_num: 1, rpc_time: 1.83ms, copr_cache_hit_ratio: 0.00}",data:TableFullScan_53,260 Bytes,N/A
            │ │ │   └─TableFullScan_53,25.00,25,cop[tikv],table:nation,"tikv_task:{time:15.6µs, loops:25}","keep order:false, stats:pseudo",N/A,N/A
            │ │ └─TableReader_58(Probe),10000.00,10000,root,"","time:27ms, loops:11, cop_task: {num: 1, max: 25.8ms, proc_keys: 0, tot_proc: 25ms, rpc_num: 1, rpc_time: 25.7ms, copr_cache_hit_ratio: 0.00}",data:TableFullScan_57,51.6 KB,N/A
            │ │   └─TableFullScan_57,10000.00,10000,cop[tikv],table:supplier,"tikv_task:{time:6.58ms, loops:10000}",keep order:false,N/A,N/A
            │ └─TableReader_60(Probe),800000.00,800000,root,"","time:2.72s, loops:783, cop_task: {num: 1, max: 2.4s, proc_keys: 0, tot_proc: 2.4s, rpc_num: 1, rpc_time: 2.4s, copr_cache_hit_ratio: 0.00}",data:TableFullScan_59,13.1 MB,N/A
            │   └─TableFullScan_59,800000.00,800000,cop[tikv],table:partsupp,"tikv_task:{time:599.4ms, loops:800000}",keep order:false,N/A,N/A
            └─TableReader_62(Probe),258688.00,200000,root,"","time:457.6ms, loops:197, cop_task: {num: 1, max: 431.7ms, proc_keys: 0, tot_proc: 431ms, rpc_num: 1, rpc_time: 431.6ms, copr_cache_hit_ratio: 0.00}",data:TableFullScan_61,791.7 KB,N/A
              └─TableFullScan_61,258688.00,200000,cop[tikv],table:part,"tikv_task:{time:78.2ms, loops:200000}",keep order:false,N/A,N/A

```

**Comment by mmyj** [comment]
@qw4990 PTAL

**Review by xiongjiwei — COMMENTED** [review]
it is great if you add some tests in `cmd/explaintest`

**Comment by mmyj** [comment]
> it is great if you add some tests in `cmd/explaintest`

done

**Comment by mmyj** [comment]
Only building executor stage will create a `PhysicalShuffleReceiverStub` for the `Shuffle`. It seems that we can not test plan using `explain` directly. @xiongjiwei

**Review by qw4990 — APPROVED** [review]

**Comment by xiongjiwei** [comment]
I do not know if the slow query plan should also be changed, can you please test it?

**Review by xiongjiwei — APPROVED** [review]

**Comment by chrysan** [comment]
> I do not know if the slow query plan should also be changed, can you please test it?

image
slow query plan even cannot recognize the shuffle operator, let's track this issue in a separated one.

**Pull request merged**
