### PR TITLE
evaluator: funcCast set value directly without types.DataItem.

### PR DESCRIPTION
**Pull request by coocood**
Other expression check `expr.GetValue() == nil` returns false when we wrap nil in DataItem.

### CODE REVIEW

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by siddontang** [comment]
Do you check this in mysqlworkbench? The return type is TypeNull?

**Comment by coocood** [comment]
@siddontang the cast function's type is set to the target type by typeInferer. the DataItem's type is not used.

**Comment by siddontang** [comment]
So can we remove DateItem now?

**Comment by coocood** [comment]
@siddontang it is used in old expression.

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
