### PR TITLE
executor: add syntax 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n' to retrieve DDL commands within a certain range

### LINKED ISSUE #36198: Use 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n' to retrieve DDL commands' content within a certain range (n+1, n+m)
## Feature Request

**Is your feature request related to a problem? Please describe:**
The feature is related to an issue from TiFlow: https://github.com/pingcap/tiflow/issues/4689
dm-worker keeps retrying to execute ddl when encounter "invalid connection" error, which is caused by the DDL costs a long duration or the DDL is queuing.

Proposed solution:
When encoutering "invalid connection", execute the 'ADMIN SHOW DDL' command every 10 seconds to check the status of the required DDL command in TiDB, and use the retrieved status to carry on the corresponding operation:
- If the status is synced, that means the downstream has finished synchronizing this DDL. The downstream can return a message to the upstream that tells him not to re-execute the DDL, and can continue to execute the following commands.
- If the status is cancelled, that means the user has cancelled the DDL or something went wrong during the synchronization. We cannot obtain the specific error, but we need to return an appropriate error to the user. Then the downstream can return a message to the upstream that tells him not to re-execute the DDL, and can continue to execute the following commands.
- If the status is something other than synced/cancelled (like running/none...), that means the downstream has not executed or is currently executing the DDL.  The downstream can return a message to the upstream that tells him the downstream has received his message and he do not need to re-execute the DDL, he just need to wait until the status turns to synced and can carry on the following commands.
- If the DDL cannot be found in the DDL history job queue, that means the DDL was lost due to some reason during the synchronization, and the downstream has not received the DDL. The downstream needs to return a message to the upstream that tells him to re-execute the DDL.

To check the the current state of the specified DDL command (running/none/synced...), we use 'ADMIN SHOW DDL JOBS' to retrive the JOB_ID corresponding to each DDL command. Then use 'ADMIN SHOW DDL JOB QUERIES JOB_ID' to find the content of each DDL command. By matching the database name, table name, and content with those of the specified DDL that we want to query, we can retrieve its state.

**Describe the feature you'd like:**
https://docs.pingcap.com/tidb/stable/sql-statement-admin-show-ddl#examples
Now the 'ADMIN SHOW DDL JOB QUERIES JOB_ID' command can only use JOB_ID to retrieve the last ten rows of DDL commands' content. Just like described in the website: 'You can only search the running DDL job corresponding to job_id within the last ten results in the DDL history job queue.'

I would like to request a feature that the users can use commands like 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n' to retrieve DDL commands' content within a certain range (n+1, n+m) that the users can assign themselves instead of only the last ten results.

Example:
```
mysql> ADMIN SHOW DDL JOBS;
+--------+---------+--------------------+--------------+----------------------+-----------+----------+-----------+-----------------------------------------------------------------+---------+
| JOB_ID | DB_NAME | TABLE_NAME         | JOB_TYPE     | SCHEMA_STATE         | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE   |
+--------+---------+--------------------+--------------+----------------------+-----------+----------+-----------+---------------------+-------------------------------------------+---------+
|     59 | test    | t1                 | add index    | write reorganization |         1 |       55 |     88576 | 2020-08-17 07:51:58 | 2020-08-17 07:51:58 | NULL                | running |
|     60 | test    | t2                 | add index    | none                 |         1 |       57 |         0 | 2020-08-17 07:51:59 | 2020-08-17 07:51:59 | NULL                | none    |
|     58 | test    | t2                 | create table | public               |         1 |       57 |         0 | 2020-08-17 07:41:28 | 2020-08-17 07:41:28 | 2020-08-17 07:41:28 | synced  |
|     56 | test    | t1                 | create table | public               |         1 |       55 |         0 | 2020-08-17 07:41:02 | 2020-08-17 07:41:02 | 2020-08-17 07:41:02 | synced  |
|     54 | test    | t1                 | drop table   | none                 |         1 |       50 |         0 | 2020-08-17 07:41:02 | 2020-08-17 07:41:02 | 2020-08-17 07:41:02 | synced  |
|     53 | test    | t1                 | drop index   | none                 |         1 |       50 |         0 | 2020-08-17 07:35:44 | 2020-08-17 07:35:44 | 2020-08-17 07:35:44 | synced  |
|     52 | test    | t1                 | add index    | public               |         1 |       50 |    451010 | 2020-08-17 07:34:43 | 2020-08-17 07:34:43 | 2020-08-17 07:35:16 | synced  |
|     51 | test    | t1                 | create table | public               |         1 |       50 |         0 | 2020-08-17 07:34:02 | 2020-08-17 07:34:02 | 2020-08-17 07:34:02 | synced  |
|     49 | test    | t1                 | drop table   | none                 |         1 |       47 |         0 | 2020-08-17 07:34:02 | 2020-08-17 07:34:02 | 2020-08-17 07:34:02 | synced  |
|     48 | test    | t1                 | create table | public               |         1 |       47 |         0 | 2020-08-17 07:33:37 | 2020-08-17 07:33:37 | 2020-08-17 07:33:37 | synced  |
|     46 | mysql   | stats_extended     | create table | public               |         3 |       45 |         0 | 2020-08-17 06:42:38 | 2020-08-17 06:42:38 | 2020-08-17 06:42:38 | synced  |
|     44 | mysql   | opt_rule_blacklist | create table | public               |         3 |       43 |         0 | 2020-08-17 06:42:38 | 2020-08-17 06:42:38 | 2020-08-17 06:42:38 | synced  |
+--------+---------+--------------------+--------------+----------------------+-----------+----------+-----------+---------------------+---------------------+-------------------------------+
12 rows in set (0.00 sec)
```

```
mysql> ADMIN SHOW DDL JOB QUERIES LIMIT 3 OFFSET 2;
+--------+------------------------------------------------------------------+
| JOB_ID | QUERY                                                            | 
+--------+------------------------------------------------------------------+
|     58 | CREATE TABLE t2 (id INT NOT NULL PRIMARY KEY auto_increment)     | 
|     56 | CREATE TABLE t1 (id INT NOT NULL PRIMARY KEY auto_increment)     | 
|     54 | DROP TABLE IF EXISTS t3                                          | 
+--------+------------------------------------------------------------------+
3 rows in set (0.00 sec)
```

Details and possible outcomes of this request can refer to this link:
https://docs.google.com/document/d/1shMk7UdczcWEdvd5YCPN7Ywr4L4JCbIWKtLEGZYSKD8/edit#heading=h.lj3nhy183z6n

**Describe alternatives you've considered:**
Alternative solution:
When encoutering "invalid connection", execute the 'ADMIN SHOW DDL' command every 10 seconds to check the status of the required DDL command in TiDB.
Select the current time of TiDB everytime a DDL command is executed. 
Use 'ADMIN SHOW DDL JOBS' command to retrieve CREATE_TIME of every DDL command ('ADMIN SHOW DDL JOBS' can show more than 10 results), then retrieve those DDL commands whose CREATE_TIME are later than the create time of the required DDL command.
Then match the DB_NAME, TABLE_NAME, JOB_TYPE of those retrieved DDLs with the corresponding variables of the required DDL, if all the corresponding variables are equal, then return the state of the DDL that meets this requirement.

Obviously, we can see that this solution is not quite rigorous. If the content of the selected DDL cannot be guaranteed to be exactly the same as that of the required DDL, only matching other variables would probably return the wrong state.

Besides, since dm does not use TiDB HTTP API, the solution related to it does not work.

**Teachability, Documentation, Adoption, Migration Strategy:**
The users can use commands like 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n' to retrieve DDL commands' content within a certain range (n+1, n+m) that the users can assign themselves instead of only the last ten results.

### PR DESCRIPTION
**Pull request by lyzx2001**
### What problem does this PR solve?

Issue Number: close #36198 

Problem Summary:
https://docs.pingcap.com/tidb/stable/sql-statement-admin-show-ddl#examples
Now the 'ADMIN SHOW DDL JOB QUERIES JOB_ID' command can only use JOB_ID to retrieve the last ten rows of DDL commands' content. Just like described in the website: 'You can only search the running DDL job corresponding to job_id within the last ten results in the DDL history job queue.'

Now I am adding a feature that the users can use commands like 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n' to retrieve DDL commands' content within a certain range (n+1, n+m) that the users can assign themselves instead of only the last ten results.

### What is changed and how it works?
Now the function can support 3 types of SQL commands, and the result examples can refer to:
```
mysql> ADMIN SHOW DDL JOB QUERIES LIMIT 3;  # Retrieve first 3 rows
+--------+------------------------------------------------------------------+
| JOB_ID | QUERY                                                            | 
+--------+------------------------------------------------------------------+
|     59 | ALTER TABLE t1 ADD INDEX index1 (col1)                           | 
|     60 | ALTER TABLE t2 ADD INDEX index1 (col1)                           | 
|     58 | CREATE TABLE t2 (id INT NOT NULL PRIMARY KEY auto_increment)     | 
+--------+------------------------------------------------------------------+
3 rows in set (0.00 sec)
```

```
mysql> ADMIN SHOW DDL JOB QUERIES LIMIT 2, 3;  # Retrieve rows 3-5
+--------+------------------------------------------------------------------+
| JOB_ID | QUERY                                                            | 
+--------+------------------------------------------------------------------+
|     58 | CREATE TABLE t2 (id INT NOT NULL PRIMARY KEY auto_increment)     | 
|     56 | CREATE TABLE t1 (id INT NOT NULL PRIMARY KEY auto_increment)     | 
|     54 | DROP TABLE IF EXISTS t3                                          | 
+--------+------------------------------------------------------------------+
3 rows in set (0.00 sec)
```

```
mysql> ADMIN SHOW DDL JOB QUERIES LIMIT 3 OFFSET 2;  # Retrieve rows 3-5
+--------+------------------------------------------------------------------+
| JOB_ID | QUERY                                                            | 
+--------+------------------------------------------------------------------+
|     58 | CREATE TABLE t2 (id INT NOT NULL PRIMARY KEY auto_increment)     | 
|     56 | CREATE TABLE t1 (id INT NOT NULL PRIMARY KEY auto_increment)     | 
|     54 | DROP TABLE IF EXISTS t3                                          | 
+--------+------------------------------------------------------------------+
3 rows in set (0.00 sec)
```

The syntax strictly conforms to the SELECT statement in MySQL:
https://dev.mysql.com/doc/refman/8.0/en/select.html

The first step of solving this issue #36198 is to transfer SQL commands to AST, which has been proposed in another PR #36285, and has been merged into master.

This PR contains changes about using AST to build plan and executor. I constructed a new struct ShowDDLJobQueriesWithRange to store limit and offset, then use the function buildShowDDLJobQueriesWithRange() to pass these information into the executor ShowDDLJobQueriesWithRangeExec. Then I implemented the Open() and Next() function for ShowDDLJobQueriesWithRangeExec.
 
Unit tests for these syntax are also added.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [x] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Add syntax 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n' to retrieve DDL commands' content within a certain range (n+1, n+m).
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]
LGTM. The behavior is not the same as before, 
```
You can only search the running DDL job corresponding to job_id within the last ten results in the DDL history job queue.
```

So, don't forget update docs.
https://docs.pingcap.com/zh/tidb/stable/sql-statement-admin-show-ddl

**Review by xhebox — APPROVED** [review]

**Comment by lyzx2001** [comment]
> LGTM. The behavior is not the same as before,
> 
> ```
> You can only search the running DDL job corresponding to job_id within the last ten results in the DDL history job queue.
> ```
> 
> So, don't forget update docs. https://docs.pingcap.com/zh/tidb/stable/sql-statement-admin-show-ddl

Copy that.

**Pull request merged**
