### PR TITLE
ddl, tables: remove useless NewIndexWithBuffer

### PR DESCRIPTION
**Pull request by winkyao**
tables.NewIndexWithBuffer is useless and confused, because the creating index key buffer can be reused in ctx.GetSessionVars().WriteStmtBufs.

### CODE REVIEW

**Comment by ngaut** [comment]
LGTM

**Comment by winkyao** [comment]
@zimulala PTAL

**Comment by tiancaiamao** [comment]
I'm looking into the integration-common-test failed test, please fix leak in unit-test. @winkyao

**Pull request merged**
