### PR TITLE
metrics: add server status count

### LINKED ISSUE #48291: Add server status count
## Enhancement

For large scale cluster, it may have a lots of tidb-servers, it's hard to get the exact number of tidb-server. And the overview dashboard can not be used in cloud/k8s env. A server status count should be added independently. And it should depend on blackbox.

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve?

Issue Number: close #48291

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. start a cluster
2. import tidb.json
3. check tidb->Server->TiDB server status on Grafana
image

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by v01dstar — APPROVED** [review]
LGTM

**Comment by jackysp** [comment]
@zimulala @hawkingrei PTAL, thx!

**Review by zimulala — APPROVED** [review]

**Pull request merged**
