### PR TITLE
planner: fix incorrect usage of UNION and INTO

### LINKED ISSUE #24309: `Incorrect usage of UNION and INTO` is not checked
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
``` sql
CREATE TABLE t1 (a int not null, b char (10) not null);
insert into t1 values(1,'a'),(2,'b'),(3,'c'),(3,'c');
CREATE TABLE t2 (a int not null, b char (10) not null);
insert into t2 values (3,'c'),(4,'d'),(5,'f'),(6,'e');
```

``` sql
select a,b from t1 into outfile 'skr' union select a,b from t2;
```
### 2. What did you expect to see? (Required)
``` sql
mysql> select a,b from t1 into outfile 'skr' union select a,b from t2;
ERROR 1221 (HY000): Incorrect usage of UNION and INTO
```

### 3. What did you see instead (Required)
``` sql
tidb> select a,b from t1 into outfile 'skr' union select a,b from t2;
+---+------+
| a | b    |
+---+------+
| 5 | f    |
| 6 | e    |
| 1 | a    |
| 2 | b    |
| 4 | d    |
| 3 | c    |
+---+------+
6 rows in set (0.01 sec)
```
### 4. What is your TiDB version? (Required)

7e1533392030514440d27ba98001c374cdf8808f in master

### PR DESCRIPTION
**Pull request by KinglittleQ**
### What problem does this PR solve?

Issue Number: close #24309 

Problem Summary:

Incorrect usage of UNION and INTO is not checked.

### What is changed and how it works?

What's Changed:

- Add a check in `checkSetOprSelectList` fucntion

How it Works:

- If there was an `INTO` in the `SELECT` statement of `UNION`, raise an error.

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- Fix incorrect usage of UNION and INTO

### CODE REVIEW

**Comment by b41sh** [comment]
almost ok, please fix test @KinglittleQ

**Comment by KinglittleQ** [comment]
@b41sh The MySql test failed and the error message is:
```
[2021-05-27T03:45:26.147Z] time="2021-05-27T11:45:26+08:00" level=fatal msg="run test [union] err: sql:select a,b from t1 into outfile 'skr' union select a,b from t2 order by a;: run \"select a,b from t1 into outfile 'skr' union select a,b from t2 order by a;\" at line 40 err Error 1221: Incorrect usage of UNION and INTO"
```

Looks like it is an expected output in my view.

Could you give me some hints about what caused this?

**Comment by b41sh** [comment]
> @b41sh The MySql test failed and the error message is:
> 
> ```
> [2021-05-27T03:45:26.147Z] time="2021-05-27T11:45:26+08:00" level=fatal msg="run test [union] err: sql:select a,b from t1 into outfile 'skr' union select a,b from t2 order by a;: run \"select a,b from t1 into outfile 'skr' union select a,b from t2 order by a;\" at line 40 err Error 1221: Incorrect usage of UNION and INTO"
> ```
> 
> Looks like it is an expected output in my view.
> 
> Could you give me some hints about what caused this?

It seems that the test cases are not updated.
PTAL @XuHuaiyu

**Comment by KinglittleQ** [comment]
@XuHuaiyu Could you please take a look?

**Review by guo-shaoge — APPROVED** [review]

**Comment by guo-shaoge** [comment]
> > @b41sh The MySql test failed and the error message is:
> > ```
> > [2021-05-27T03:45:26.147Z] time="2021-05-27T11:45:26+08:00" level=fatal msg="run test [union] err: sql:select a,b from t1 into outfile 'skr' union select a,b from t2 order by a;: run \"select a,b from t1 into outfile 'skr' union select a,b from t2 order by a;\" at line 40 err Error 1221: Incorrect usage of UNION and INTO"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Looks like it is an expected output in my view.
> > Could you give me some hints about what caused this?
> 
> It seems that the test cases are not updated.
> PTAL @XuHuaiyu

I run the new added case, looks like ok.

**Comment by guo-shaoge** [comment]
Sorry, I found another case that's unexpected. So approve is cancled.

    mysql> select 1 union select 2 into outfile 'skr';
    +---+
    | 1 |
    +---+
    | 2 |
    | 1 |
    +---+
    2 rows in set (0.00 sec)

**Comment by KinglittleQ** [comment]
@guo-shaoge What's the expected result? It is a valid statement in MySQL.

**Comment by guo-shaoge** [comment]
> @guo-shaoge What's the expected result? It is a valid statement in MySQL.

Sorry, it's my fault. We only need to fix this inner case.

**Comment by KinglittleQ** [comment]
@guo-shaoge Should I take any action now?

**Comment by KinglittleQ** [comment]
@hanfei1991 Could you take a look?

**Review by guo-shaoge — APPROVED** [review]

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
