### PR TITLE
*: support session variable 'warning_count' and 'error_count'

### PR DESCRIPTION
**Pull request by spongedu**
## What have you changed? (mandatory)

1. Support `show @@waring_count` and `show @@error_count` in `TiDB`

2. The modification that add an return value of `error` type  for `ResetStmtCtx`  is to make `kisielk/errcheck` happy.

## What are the type of the changes (mandatory)?

`enhancement`

## How has this PR been tested (mandatory)?

`Unittest`

### CODE REVIEW

**Comment by coocood** [comment]
@spongedu 
Can we remove `WarningCount`?

**Comment by spongedu** [comment]
@coocood we still need `WarningCount`. The behavior of the new added `NumWarnings` is a little different from `WarningCount` in behavior. For example, if the last sql statement generates a warning; 
both `WarningCount` and `NumWarnings` 1,  then if we execute `SHOW WARNINGS` after that,  `WarningCount` would be 0,  and `NumWarnings` is still 1.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
