### PR TITLE
tikvclient: fix a bug about unknown response from tikv

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve? 
Fix a bug (cause panic) about handling unknown responses from TiKV. 

### What is changed and how it works?
Cover unknown responses.

### Check List 

Tests 
Unit test.

Code changes

Side effects

Related changes

Need to cherry-pick to the release branch

Release note
Fix a panic about handling unknown responses from TiKV.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM

**Comment by lysu** [comment]
@hicqu please resolve conflicts if free

**Pull request merged**
