### PR TITLE
tikv: fix store addr cannot update bug after change new store addr and old addr be offline (#13495)

### PR DESCRIPTION
**Pull request by lysu**
cherry-pick #13495 to 3.0

conflict:

- on region_cache.go, 3.0 without tiflash logic
- on region_cache_test.go, 3.0 without follower-read, so need use another way to pre-load store2 into store cache

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/13576)

### CODE REVIEW

**Comment by lysu** [comment]
test has fixed ptal @coocood @jackysp

**Comment by coocood** [comment]
LGTM

**Pull request merged**
