### PR TITLE
ddl: check column and partition value have same type for range column partition (#12664)

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry-pick https://github.com/pingcap/tidb/pull/12664

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @jackysp @crazycs520 @zimulala

**Comment by tiancaiamao** [comment]
Block by https://github.com/pingcap/tidb/pull/12719

**Comment by cyliu0** [comment]
The blocked PR https://github.com/pingcap/tidb/pull/12719 has already been merged. Please move on to processing this cherry pick.

**Comment by tiancaiamao** [comment]
PTAL @jackysp @crazycs520 @zimulala

**Comment by tiancaiamao** [comment]
PTAL @crazycs520

**Comment by ericsyh** [comment]
@tiancaiamao pls fix conflicts.

**Comment by tiancaiamao** [comment]
PTAL @crazycs520 @jackysp @ericsyh

**Pull request merged**
