### PR TITLE
tikv: invalidate store's regions when store be removed in kv

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

this question can be reproduced by `TestReplaceAddrWithNewStore` testcase:

1. access A store using region1, then region1 will be put into region-cache
2. remove A store(store_id=1) in ip1:port2 from kv-cluster
3. then add B store(store_id=2) in the same ip1:port2 into kv-cluster 
4. access region1 again via region cache(make sure TTL isn't expired)

make sure 2-3 no any request hit region1, then 4 will be fail in infline loop

the root reason is: region-cache will try async fetch store A's new address but got nil, region request will [keep retry](https://github.com/pingcap/tidb/blob/eae30ebbcb8464d4644598db459337998ab1d43b/store/tikv/region_request.go#L244) and wait "new addr", this also will make cache TTL have no chance to invalidate cached info.

### What is changed and how it works?

invalidate regions in removed store, to let request have the chance to reload new region's store info from pd.

after this modification, `TestReplaceAddrWithNewStore` can works

### Check List 

Tests 

 - Unit test

Code changes

 - invalidate code

Side effects

 -  N/A

Related changes

 - Need to cherry-pick to the release  3.0

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/11567)

### CODE REVIEW

**Comment by lysu** [comment]
@coocood @tiancaiamao PTAL thx

**Comment by coocood** [comment]
LGTM

**Comment by dikang123** [comment]
Does this issue affect tikv v2.1.15？

**Comment by lysu** [comment]
@dikang123 no, this issue only affect v3.0.0 and v3.0.1

**Pull request merged**
