### PR TITLE
executor: fix KVSnapshot missing set txnScope (#25710)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25710 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25713
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25713:release-5.1-516584aaa47b
```

---

Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

KVSnapshot missing set txnScope which will cause `PointGet`/`BatchPointGet` local stale read not work.

### What is changed and how it works?

Fix KVSnapshot missing set txnScope

### Release note 

- No release note

### CODE REVIEW

**Comment by Yisaer** [comment]
This request also include following extra pr:

1. https://github.com/pingcap/tidb/pull/25712 remove unexpected dependency(client-go/v2) in release-5.1
2. https://github.com/pingcap/tidb/pull/25679 fix the unnecessary kv_get consuming for `set transaction read only as of timestamp ts... `

**Review by nolouch — APPROVED** [review]
LGTM

**Review by Yisaer — APPROVED** [review]

**Pull request merged**
