### PR TITLE
store: added retry and exponential backoff with full jitter for transaction Commit()

### PR DESCRIPTION
**Pull request by xwb1989**
`BackOffBase`, `BackOffCap` and `RetryLimit` are picked arbitrarily. Now they goes to `var` instead of `const` because we might want it customizable for package user.

### CODE REVIEW

**Comment by xwb1989** [comment]
fix #444

**Comment by xwb1989** [comment]
Now changes has gone to session.go

**Comment by ngaut** [comment]
Thanks @xwb1989 
Could you merge your changes to https://github.com/pingcap/tidb/pull/583

**Comment by siddontang** [comment]
kv.RunInNewTxn need this too.

**Comment by xwb1989** [comment]
Maybe I could better waiting for #583 being merged?

**Comment by ngaut** [comment]
Hi, @xwb1989  
#583 has been merged.

**Comment by ngaut** [comment]
Hi, @xwb1989 
Could you merge your code to https://github.com/pingcap/tidb/blob/master/kv/txn.go

**Comment by shenli** [comment]
@xwb1989  I added back off use the algorithm in your pr to the latest master.
https://github.com/pingcap/tidb/pull/658
So I close this pr.
Thanks for your pr.

**Comment by xwb1989** [comment]
Good to know. Thanks.

**Pull request closed without merging**
