### PR TITLE
plan, partition: re-implement hash partition pruning to support `in` and `or` and some other functions (#18574)

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Cherry-pick  https://github.com/pingcap/tidb/pull/18574 and https://github.com/pingcap/tidb/pull/19486

https://github.com/pingcap/tidb/pull/18574 fix hash partition pruning for `in` expression, the other one is required to make it build successful.

### Release note 

- re-implement hash partition pruning to support `in` and `or` and some other functions

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @crazycs520 @lysu

**Comment by lysu** [comment]
@tiancaiamao  test failured

and it seems this PR also cherry-pick a part logic of https://github.com/pingcap/tidb/pull/18707

**Comment by lysu** [comment]
LGTM

**Comment by tiancaiamao** [comment]
v4.0.10 is frozen, we need to wait for 4.0.11 to merge it.

**Pull request closed without merging**
