### PR TITLE
 executor: fix group_concat when chunk size is set to 1

### PR DESCRIPTION
**Pull request by XuHuaiyu**
## What have you changed? (mandatory)
Before this PR, the following sql would return wrong result.
``` sql
create table idx_agg (a int, b int, index (b));
insert idx_agg values (1, 1), (1, 2), (2, 2);
set @@tidb_max_chunk_size=1;
tidb> select group_concat(b) from idx_agg group by b;
+-----------------+
| group_concat(b) |
+-----------------+
| 1              |
| 22            |
+-----------------+
```
The PR fix the problem:
``` sql
tidb> select group_concat(b) from idx_agg group by b;
+-----------------+
| group_concat(b) |
+-----------------+
| 1             |
| 2,2         |
+-----------------+
2 rows in set (0.00 sec)
```
How does this bug occur？

This bug is caused by [this line](https://github.com/pingcap/tidb/blob/master/executor/aggfuncs/func_group_concat.go#L107).
When max_chunk_size is set to 1, [rowInGroup](https://github.com/pingcap/tidb/blob/master/executor/aggfuncs/func_group_concat.go#L83) pass into the function
contains only 1 row every time. As we can see, separator be appended
 [here](https://github.com/pingcap/tidb/blob/master/executor/aggfuncs/func_group_concat.go#L102-L104) would be truncated out of the loop.

How does this bug be fixed?

This commit first check whether `p.buffer != nil`, which means we've 
got part of the result for a group, if it's true, we'll append separator at 
the end of p.buffer. Through this, we can avoid truncating separator 
wrongly. Then we append the string be consist of the values. If 
this string is null, we'll truncated the separator which is appended at 
the first.

## What is the type of the changes? (mandatory)
Bug-fix

## How has this PR been tested? (mandatory)
unit test

## Does this PR affect tidb-ansible update? (mandatory)
no

## Does this PR need to be added to the release notes? (mandatory)
no

### CODE REVIEW

**Comment by winoros** [comment]
@XuHuaiyu The 800+ line change is all to fix the problem described in title?

**Comment by XuHuaiyu** [comment]
@winoros Noop, most of the lines are from  #7281 .
It would be nice if you can review it first.

The following functions fix and test the bug.
func_group_concat.go: func(e *groupConcat) UpdatePartialResult 
func_avg_test.go: TestMergePartialResult4GroupConcat

**Comment by zz-jason** [comment]
@XuHuaiyu can you remove the irrelevant changes so that we can be focused on the bugfix itself and merge this PR as soon as possible?

**Comment by XuHuaiyu** [comment]
PTAL @zz-jason @winoros

**Comment by XuHuaiyu** [comment]
PTAL @zz-jason

**Pull request merged**
