### PR TITLE
test: work around goroutine leak

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve?

Issue Number: close #xxx 

avoid goroutine leak from https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_unit_test/runs/67445/nodes/100/steps/319/log/?start=0
Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: work around this leak, fix this later with @hanfei1991 .

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

### Release note 

- No release note

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by lzmhhh123 — APPROVED** [review]

**Review by hanfei1991 — APPROVED** [review]
/LGTM

**Pull request merged**
