### PR TITLE
statistics: fix memtracker test

### PR DESCRIPTION
**Pull request by miamia0**
### What problem does this PR solve?

Issue Number: close [#18779](https://github.com/pingcap/tidb/issues/18779) 
### What is changed and how it works?
What's Changed:
there might be any sys table in statistic cache.

### Check List
Tests 
- Unit test

### Release note 
* none.

### CODE REVIEW

**Comment by miamia0** [comment]
> The `statsTbl.MemoryUsage` should not be equal to `do.StatsHandle().GetMemConsumed`?

yes,in this test,Besides `statsTbl`，there might be any system table in cache ,so `do.StatsHandle().GetMemConsumed` is more than `statsTbl.MemoryUsage`.

**Comment by SunRunAway** [comment]
@XuHuaiyu PTAL~

**Comment by miamia0** [comment]
> LGTM
> But, in this test, the `do.StatsHandle().GetMemConsumed()` is actually still equal to `statsTbl.MemoryUsage()`?
> Is it possible to change the test to make that two are different with each other?
in this test，`do.StatsHandle().GetMemConsumed()` is actually **not** equal to `statsTbl.MemoryUsage()`，because of sys tables .

**Pull request merged**
