### PR TITLE
tests: fix some tests failed when `system_time_zone != Asia/Shanghai`

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: ref #49493

Problem Summary: Deal with `TestTiDBTrx`, `TestSetTransactionReadOnlyAsOf` and flashback cluster related problems.

Just a workround for flashback cluster related test cases. The root case is https://github.com/pingcap/tidb/issues/49555.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zimulala — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
/hold 

Can you remove the timezone config in the bazel config.

**Comment by Defined2014** [comment]
> /hold
> 
> Can you remove the timezone config in the bazel config.

Not fixed all related PRs, I will do it after https://github.com/pingcap/tidb/issues/49493 closed.

**Pull request merged**
