### PR TITLE
log: avoid panic on unknown log format

### LINKED ISSUE #34359: panic on unknown log format
## Enhancement

Update `pingcap/log` corresponding to https://github.com/pingcap/log/issues/15.

### PR DESCRIPTION
**Pull request by tisonkun**
Issue Number: close #34359

```release-note
None
```

### CODE REVIEW

**Review by dveeden — CHANGES_REQUESTED** [review]
Looks like the API has changed a bit and this now needs something like:
```diff
diff --git a/util/logutil/log.go b/util/logutil/log.go
index e56245d4b..da90c55f0 100644
--- a/util/logutil/log.go
+++ b/util/logutil/log.go
@@ -225 +225,2 @@ func wrapTraceLogger(ctx context.Context, connID uint64, logger *zap.Logger) *za
-               traceCore := log.NewTextCore(log.NewTextEncoder(&log.Config{}), tl, tl).
+               te, _ := log.NewTextEncoder(&log.Config{})
+               traceCore := log.NewTextCore(te, tl, tl).
```
but with better error handling..

**Comment by tisonkun** [comment]
@dveeden you're right. I'm pushing another commit.

**Comment by tisonkun** [comment]
@dveeden updated. Other error handling should be handled via:

* log.InitLoggerWithWriteSyncer
* log.InitLogger

**Review by dveeden — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by mjonss — APPROVED** [review]
LGTM

**Pull request merged**
