### PR TITLE
*: move XXInfo/Job, etc, out from model pkg in parser to meta

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: ref #54436

Problem Summary:

### What changed and how does it work?
- following PR of https://github.com/pingcap/tidb/pull/55634, we move XXInfo/Job, etc, out from model pkg of parser to meta, also split it into different files
- some structs like CIStr is kept in parser/model to keep compatible with older version, will move them to ast pkg later
### Check List

Tests 

- [x] Unit test, only move code, reusing existing cases
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by joccau — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
lgtm

**Review by 3pointer — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Review by lcwangchao — COMMENTED** [review]
If you move model pkg out of parser, I'm not sure whether some other repos that depencies on the parser will break...

@bb7133  could you take a look?

**Comment by D3Hunter** [comment]
> If you move model pkg out of parser, I'm not sure whether some other repos that depencies on the parser will break...
> 
> @bb7133 could you take a look?

I checked some outer dependency of parser, they only depends on AST and model.CIStr, those part are not moved. I have already described it in the PR, ptal

**Review by lcwangchao — APPROVED** [review]

**Review by yudongusa — APPROVED** [review]
LGTM.

**Pull request merged**
