### PR TITLE
*: support order_index and no_order_index hint for planner

### LINKED ISSUE #39964: Support keep_order and no_keep_order hint for planner
## Enhancement
Now, it's easy to choose the wrong plans between `TopN` vs. `Limit + Keep Order`. It will affect the plan's performance. So we introduce the `keep_order` and `no_keep_order` hints.

The usage for those two hints are very similar to the `use_index` hint. `keep_order` hint can keep the index's order. And `no_keep_order` hint will not keep the index's order.

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Cherry pick #39965 #40089 #10155 #40945

Issue Number: close #39964

Problem Summary:

Support order_index and no_order_index hint for planner.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Comment by hawkingrei** [comment]
@xuyifangreeneyes PTAL

```
    result.go:49: 
        	Error Trace:	/home/jenkins/.tidb/tmp/45c44f383a26fe92ddbb5dda36c71ef8/sandbox/linux-sandbox/7145/execroot/__main__/bazel-out/k8-fastbuild/bin/planner/core/core_test_/core_test.runfiles/__main__/planner/core/result.go:49
        	            				/home/jenkins/.tidb/tmp/45c44f383a26fe92ddbb5dda36c71ef8/sandbox/linux-sandbox/7145/execroot/__main__/bazel-out/k8-fastbuild/bin/planner/core/core_test_/core_test.runfiles/__main__/planner/core/integration_test.go:1371
        	Error:      	Not equal: 
        	            	expected: "[Limit_12 1.00 root  offset:0, count:1]\n[└─Projection_17 1.00 root  test.t1.a, test.t1.b]\n[  └─IndexLookUp_16 1.00 root  ]\n[    ├─Limit_15(Build) 1.00 cop[tikv]  offset:0, count:1]\n[    │ └─IndexRangeScan_13 1.00 cop[tikv] table:t1, index:idx_a(a) range:[-inf,10), keep order:true, stats:pseudo]\n[    └─TableRowIDScan_14(Probe) 1.00 cop[tikv] table:t1 keep order:false, stats:pseudo]\n"
        	            	actual  : "[Projection_17 1.00 root  test.t1.a, test.t1.b]\n[└─IndexLookUp_16 1.00 root  limit embedded(offset:0, count:1)]\n[  ├─Limit_15(Build) 1.00 cop[tikv]  offset:0, count:1]\n[  │ └─IndexRangeScan_13 1.00 cop[tikv] table:t1, index:idx_a(a) range:[-inf,10), keep order:true, stats:pseudo]\n[  └─TableRowIDScan_14(Probe) 1.00 cop[tikv] table:t1 keep order:false, stats:pseudo]\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,7 +1,6 @@
        	            	-[Limit_12 1.00 root  offset:0, count:1]
        	            	-[└─Projection_17 1.00 root  test.t1.a, test.t1.b]
        	            	-[  └─IndexLookUp_16 1.00 root  ]
        	            	-[    ├─Limit_15(Build) 1.00 cop[tikv]  offset:0, count:1]
        	            	-[    │ └─IndexRangeScan_13 1.00 cop[tikv] table:t1, index:idx_a(a) range:[-inf,10), keep order:true, stats:pseudo]
        	            	-[    └─TableRowIDScan_14(Probe) 1.00 cop[tikv] table:t1 keep order:false, stats:pseudo]
        	            	+[Projection_17 1.00 root  test.t1.a, test.t1.b]
        	            	+[└─IndexLookUp_16 1.00 root  limit embedded(offset:0, count:1)]
        	            	+[  ├─Limit_15(Build) 1.00 cop[tikv]  offset:0, count:1]
        	            	+[  │ └─IndexRangeScan_13 1.00 cop[tikv] table:t1, index:idx_a(a) range:[-inf,10), keep order:true, stats:pseudo]
        	            	+[  └─TableRowIDScan_14(Probe) 1.00 cop[tikv] table:t1 keep order:false, stats:pseudo]
        	            	 
        	Test:       	TestKeepOrderHint
        	Messages:   	sql:explain select /*+ order_index(t1, idx_a) */ * from t1 where a<10 order by a limit 1;, args:[]
```

**Comment by xuyifangreeneyes** [comment]
> @xuyifangreeneyes PTAL
> 
> ```
>     result.go:49: 
>         	Error Trace:	/home/jenkins/.tidb/tmp/45c44f383a26fe92ddbb5dda36c71ef8/sandbox/linux-sandbox/7145/execroot/__main__/bazel-out/k8-fastbuild/bin/planner/core/core_test_/core_test.runfiles/__main__/planner/core/result.go:49
>         	            				/home/jenkins/.tidb/tmp/45c44f383a26fe92ddbb5dda36c71ef8/sandbox/linux-sandbox/7145/execroot/__main__/bazel-out/k8-fastbuild/bin/planner/core/core_test_/core_test.runfiles/__main__/planner/core/integration_test.go:1371
>         	Error:      	Not equal: 
>         	            	expected: "[Limit_12 1.00 root  offset:0, count:1]\n[└─Projection_17 1.00 root  test.t1.a, test.t1.b]\n[  └─IndexLookUp_16 1.00 root  ]\n[    ├─Limit_15(Build) 1.00 cop[tikv]  offset:0, count:1]\n[    │ └─IndexRangeScan_13 1.00 cop[tikv] table:t1, index:idx_a(a) range:[-inf,10), keep order:true, stats:pseudo]\n[    └─TableRowIDScan_14(Probe) 1.00 cop[tikv] table:t1 keep order:false, stats:pseudo]\n"
>         	            	actual  : "[Projection_17 1.00 root  test.t1.a, test.t1.b]\n[└─IndexLookUp_16 1.00 root  limit embedded(offset:0, count:1)]\n[  ├─Limit_15(Build) 1.00 cop[tikv]  offset:0, count:1]\n[  │ └─IndexRangeScan_13 1.00 cop[tikv] table:t1, index:idx_a(a) range:[-inf,10), keep order:true, stats:pseudo]\n[  └─TableRowIDScan_14(Probe) 1.00 cop[tikv] table:t1 keep order:false, stats:pseudo]\n"
>         	            	
>         	            	Diff:
>         	            	--- Expected
>         	            	+++ Actual
>         	            	@@ -1,7 +1,6 @@
>         	            	-[Limit_12 1.00 root  offset:0, count:1]
>         	            	-[└─Projection_17 1.00 root  test.t1.a, test.t1.b]
>         	            	-[  └─IndexLookUp_16 1.00 root  ]
>         	            	-[    ├─Limit_15(Build) 1.00 cop[tikv]  offset:0, count:1]
>         	            	-[    │ └─IndexRangeScan_13 1.00 cop[tikv] table:t1, index:idx_a(a) range:[-inf,10), keep order:true, stats:pseudo]
>         	            	-[    └─TableRowIDScan_14(Probe) 1.00 cop[tikv] table:t1 keep order:false, stats:pseudo]
>         	            	+[Projection_17 1.00 root  test.t1.a, test.t1.b]
>         	            	+[└─IndexLookUp_16 1.00 root  limit embedded(offset:0, count:1)]
>         	            	+[  ├─Limit_15(Build) 1.00 cop[tikv]  offset:0, count:1]
>         	            	+[  │ └─IndexRangeScan_13 1.00 cop[tikv] table:t1, index:idx_a(a) range:[-inf,10), keep order:true, stats:pseudo]
>         	            	+[  └─TableRowIDScan_14(Probe) 1.00 cop[tikv] table:t1 keep order:false, stats:pseudo]
>         	            	 
>         	Test:       	TestKeepOrderHint
>         	Messages:   	sql:explain select /*+ order_index(t1, idx_a) */ * from t1 where a<10 order by a limit 1;, args:[]
> ```

The plan change is caused by https://github.com/pingcap/tidb/pull/43883, which is expected.

**Pull request merged**
