### PR TITLE
use old scan method to collect idle goroutine instead of goroutine timer

### PR DESCRIPTION
**Pull request by AlexStocks**
The go timer is very inefficient. I think the old function gc&gcOnce which use scan method may be more efficient.

### CODE REVIEW

**Comment by coocood** [comment]
Any benchmark result to prove the change is more efficient?

**Comment by coocood** [comment]
@AlexStocks 
Thank you for your effort.
I'm sorry, but I have to close this PR. It adds too much complexity.

**Comment by AlexStocks** [comment]
Okay. Just Add a fsm compared to the old gc project.

**Pull request closed without merging**
