### PR TITLE
parser: blob and text support field length option

### PR DESCRIPTION
**Pull request by siddontang**
Manual doesn’t point this, but SQLAlchemy has this test and MySQL
parser handles this too.

### CODE REVIEW

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
But should we check flen value?

**Comment by siddontang** [comment]
No need to do, just pass parsing.

**Comment by siddontang** [comment]
PTAL @shenli

**Comment by shenli** [comment]
LGTM

**Pull request merged**
