### PR TITLE
config, server, executor: Reduce RSA keysize in testing

### LINKED ISSUE #26947: tidbTestSerialSuite.TestTLS takes more then 3 seconds
## Bug Report

Please answer these questions before submitting your issue. Thanks!
```
[2021-08-06T02:30:41.127Z] grep '^PASS:' gotest.log | go run tools/check/check-timeout.go || { $(find $PWD/ -type d | grep -vE "(\.git|tools)" | xargs tools/bin/failpoint-ctl disable); exit 1; }

[2021-08-06T02:30:41.127Z] The following test cases take too long to finish:

[2021-08-06T02:30:41.127Z] PASS: tidb_test.go:874: tidbTestSerialSuite.TestTLS	9.182s
```
### 1. Minimal reproduce step (Required)

in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/23436/pipeline

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #26947

Problem Summary: Using smaller RSA keys when testing reduces test run time

### Check List 

Documentation

- Adds a configuration option

### Release note 

```release-note
It is now possible to configure the RSA keysize of automatically generated RSA private keys
```

### CODE REVIEW

**Comment by kennytm** [comment]
would generating [ECDSA](https://pkg.go.dev/crypto/ecdsa) or [Ed25519](https://pkg.go.dev/crypto/ed25519) keys be more efficient than RSA 😅

**Comment by dveeden** [comment]
> would generating [ECDSA](https://pkg.go.dev/crypto/ecdsa) or [Ed25519](https://pkg.go.dev/crypto/ed25519) keys be more efficient than RSA sweat_smile

```
goos: linux
goarch: amd64
pkg: github.com/dveeden/keygentester
cpu: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
BenchmarkRsa4k-8     	       7	1490731837 ns/op
BenchmarkRsa528-8    	    1135	   5237020 ns/op
BenchmarkEcdsa-8     	  425629	     14857 ns/op
BenchmarkEd25519-8   	  122875	     54166 ns/op
```
```
goos: freebsd
goarch: amd64
pkg: github.com/dveeden/keygentester
cpu: Intel(R) Atom(TM) CPU  C2550  @ 2.40GHz
BenchmarkRsa4k-4     	       2	15946739888 ns/op
BenchmarkRsa528-4    	     280	  21446773 ns/op
BenchmarkEcdsa-4     	   83643	     71792 ns/op
BenchmarkEd25519-4   	   36759	    163191 ns/op
```
```golang
package main

import (
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"testing"
)

func BenchmarkRsa4k(b *testing.B) {
	for i := 0; i < b.N; i++ {
		rsa.GenerateKey(rand.Reader, 4096)
	}
}

func BenchmarkRsa528(b *testing.B) {
	for i := 0; i < b.N; i++ {
		rsa.GenerateKey(rand.Reader, 528)
	}
}

func BenchmarkEcdsa(b *testing.B) {
	for i := 0; i < b.N; i++ {
		ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	}
}

func BenchmarkEd25519(b *testing.B) {
	for i := 0; i < b.N; i++ {
		ed25519.GenerateKey(rand.Reader)
	}
}
```

**Comment by dveeden** [comment]
However I don't think we should move away from RSA as that probably has the best compatibility.

**Review by tiancaiamao — APPROVED** [review]

**Review by morgo — APPROVED** [review]

**Pull request merged**
