### PR TITLE
executor: add an unit test case for unreasonable invoking Close (#30696)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #30696 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/30768
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/30768:release-5.0-8cf847a57514
```

---

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:
Inspired by https://github.com/pingcap/tidb/issues/27125, https://github.com/pingcap/tidb/issues/30587, and https://github.com/pingcap/tidb/issues/30289, there is a common problem that the `Close` function may be invoked but the `Open` function is not invoked or returned with an error. In this senario, some member attributes are not initialized and the nil pointer panic triggered when invoking `Close`.

I add a unit test in this commit to test invoking the `Close` function directly without invoking the `Open` function before.
With this test, 3 more similar bugs are also found in `MergeJoinExec`, `CTEExec`, `IndexReader`. 

### Check List

Tests 

- [x] Unit test

Side effects

N/A

Documentation

N/A

### Release note

```release-note
None
```

### CODE REVIEW

**Review by wshwsh12 — APPROVED** [review]

**Review by guo-shaoge — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
@XuHuaiyu Seems there is an error on ci

**Comment by zhouqiang-cl** [comment]
```
[2021-12-19T14:03:39.016Z] level=warning msg="[runner] Can't run linter goanalysis_metalinter: ineffassign: analysis skipped: errors in package: [/home/jenkins/agent/workspace/tidb_ghpr_check/go/src/github.com/pingcap/tidb/executor/executor_test.go:8370:23: PhysicalCTE not declared by package core]"

[2021-12-19T14:03:39.016Z] level=info msg="[runner] processing took 8.239µs with stages: max_same_issues: 4.015µs, skip_dirs: 1.698µs, nolint: 422ns, max_from_linter: 296ns, cgo: 199ns, autogenerated_exclude: 155ns, filename_unadjuster: 143ns, identifier_marker: 141ns, skip_files: 136ns, uniq_by_line: 136ns, severity-rules: 129ns, path_prettifier: 128ns, source_code: 124ns, diff: 124ns, path_shortener: 72ns, exclude: 66ns, max_per_file_from_linter: 64ns, sort_results: 64ns, exclude-rules: 64ns, path_prefixer: 63ns"

[2021-12-19T14:03:39.016Z] level=info msg="[runner] linters took 3.35783262s with stages: goanalysis_metalinter: 3.357741943s"

[2021-12-19T14:03:39.016Z] level=error msg="Running error: ineffassign: analysis skipped: errors in package: [/home/jenkins/agent/workspace/tidb_ghpr_check/go/src/github.com/pingcap/tidb/executor/executor_test.go:8370:23: PhysicalCTE not declared by package core]"

[2021-12-19T14:03:39.016Z] level=info msg="Memory: 72 samples, avg is 403.6MB, max is 878.3MB"

[2021-12-19T14:03:39.016Z] level=info msg="Execution took 7.031901479s"

[2021-12-19T14:03:39.016Z] make: *** [check-static] Error 3
```

**Pull request merged**
