### PR TITLE
*: support cancel query like 'select * from information_schema.tables'

### LINKED ISSUE #57749: The KILL statement terminate a system table query connection for long time
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

millions tables
kill select count(*) from INFORMATION_SCHEMA.partitions;
it takes about 15 minutes kill the connection
```
[2024/11/27 03:45:34.419 +00:00] [WARN] [sqlkiller.go:61] ["kill initiated"] ["connection ID"=2405433398] [reason="[executor:1317]Query execution was interrupted"]
[2024/11/27 04:00:58.467 +00:00] [WARN] [sqlkiller.go:137] ["kill finished"] [conn=2405433398]
```

Same scenario for max_execution_time
set @@max_execution_time=1000;
select count(*) from INFORMATION_SCHEMA.partitions;
it takes about 17 minutes terminate the query
```
[2024/11/27 04:07:49.399 +00:00] [WARN] [expensivequery.go:97] ["execution timeout, kill it"] [costTime=17m24.497578181s] [maxExecutionTime=1s] [processInfo="{id:1579157424, user:root, host:10.200.0.166:60519, db:<nil>, command:Query, time:1044, state:autocommit, info:select count(*) from INFORMATION_SCHEMA.partitions}"]
[2024/11/27 04:07:49.399 +00:00] [INFO] [server.go:913] [kill] [conn=1579157424] [query=true] [maxExecutionTime=true] [runawayExceed=false]
[2024/11/27 04:07:49.499 +00:00] [WARN] [expensivequery.go:97] ["execution timeout, kill it"] [costTime=17m24.59749879s] [maxExecutionTime=1s] [processInfo="{id:1579157424, user:root, host:10.200.0.166:60519, db:<nil>, command:Query, time:1044, state:autocommit, info:select count(*) from INFORMATION_SCHEMA.partitions}"]
[2024/11/27 04:07:49.528 +00:00] [ERROR] [terror.go:317] ["function call errored"] [error="[executor:3024]Query execution was interrupted, maximum statement execution time exceeded"] 
```

### 4. What is your TiDB version? (Required)

master
dcc9dcc1ea75a26c1db00e7e4c1e01490e3916bf

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #57749

Problem Summary:

### What changed and how does it work?

Check ctx cancel in the loop.
`ListTables`  might be slow when there are too many tables, add a ctx to it to support cancel.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)

image
image

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by Rustin170506 — APPROVED** [review]
Looks good to me. Thanks! 👍

**Review by zimulala — APPROVED** [review]
LGTM

**Pull request merged**
