### PR TITLE
expression: make greatest/least type infer clean for integer

### LINKED ISSUE #32702: Clean the type infer of greatest/least for integer
## Enhancement
TiDB:
smallint/mediumint/int unsigned + smallint/mediumint/int = bigint unsigned for greatest, or bigint for least
bigint unsigned + bigint  = decimal(20, 0)

but MySQL8:
tinyint/smallint/mediumint unsigned + tinyint/smallint/mediumint = int
int unsigned + int  = bigint
bigint unsigned + bigint  = decimal(20, 0)

The code is a little strange and not compatible with MySQL. So i try to make it cleaner.

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #32702

Problem Summary:
TiDB:
```
smallint/mediumint/int unsigned + smallint/mediumint/int = bigint unsigned for greatest, or bigint for least
bigint unsigned + bigint = decimal(20, 0)
```

but MySQL8:
```
tinyint/smallint/mediumint unsigned + tinyint/smallint/mediumint = int
int unsigned + int = bigint
bigint unsigned + bigint = decimal(20, 0)
```

The code is a little strange and not compatible with MySQL. So i try to make it cleaner.

After changed:
```
smallint/mediumint/int unsigned + smallint/mediumint/int = bigint
bigint unsigned + bigint = decimal(20, 0)
```
### What is changed and how it works?
1. Delete `isEqualsInitUnsignedFlag`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility: 

1. before: int unsigned + int = bigint unsigned for greatest, or bigint for least
3. after: int unsigned + int = bigint

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

```release-note
expression: make greatest/least type infer clean for integer
```

### CODE REVIEW

**Comment by guo-shaoge** [comment]
This may affect tiflash's behavior. @windtalker maybe you are interested~

**Review by wshwsh12 — APPROVED** [review]

**Pull request merged**
