### PR TITLE
*: Fix checkHistoryJobInTest failed when br restore

### LINKED ISSUE #33205: br test failed when checkHistoryJobInTest when creating placement policy
### 1. Minimal reproduce step (Required)

[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline)

```
[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-864)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-865)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-866)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-867)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-868)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-869)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-870)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-871)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-872)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-873)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-874)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-875)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-876)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-877)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-878)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-879)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-880)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-881)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-882)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-883)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-884)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-885)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-886)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-887)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-888)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-889)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-890)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-891)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10638/pipeline#step-1092-log-892)[2022-03-17T05:26:52.631Z] set @@tidb_placement_mode='STRICT';

[2022-03-17T05:26:54.001Z] panic: job ID 194, parse ddl job failed, query set @@tidb_placement_mode='STRICT';

[2022-03-17T05:26:54.001Z] 

[2022-03-17T05:26:54.001Z] goroutine 441 [running]:

[2022-03-17T05:26:54.001Z] github.com/pingcap/tidb/ddl.checkHistoryJobInTest(0x3ef0ff8, 0xc00186db00, 0xc001f05b00)

[2022-03-17T05:26:54.001Z] 	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/ddl/ddl.go:649 +0x417

[2022-03-17T05:26:54.001Z] github.com/pingcap/tidb/ddl.(*ddl).doDDLJob(0xc000679e80, 0x3ef0ff8, 0xc00186db00, 0xc001992900, 0x0, 0x0)

[2022-03-17T05:26:54.001Z] 	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/ddl/ddl.go:726 +0xcf8

[2022-03-17T05:26:54.001Z] github.com/pingcap/tidb/ddl.(*ddl).CreatePlacementPolicyWithInfo(0xc000679e80, 0x3ef0ff8, 0xc00186db00, 0xc001f4a100, 0xc00186db01, 0xc0012b4490, 0xc001f464c0)

[2022-03-17T05:26:54.001Z] 	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/ddl/ddl_api.go:2479 +0x2c5

[2022-03-17T05:26:54.001Z] github.com/pingcap/tidb/br/pkg/gluetidb.(*tidbSession).CreatePlacementPolicy(0xc000e56110, 0x3e838b0, 0xc001fe2000, 0xc001f4a100, 0x0, 0xc001f48401)

[2022-03-17T05:26:54.001Z] 	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/gluetidb/glue.go:138 +0x105

[2022-03-17T05:26:54.001Z] github.com/pingcap/tidb/br/pkg/restore.(*DB).CreatePlacementPolicy(0xc000e565d0, 0x3e838b0, 0xc001fe2000, 0xc001f4a100, 0xc001f4a100, 0x1)

[2022-03-17T05:26:54.001Z] 	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/restore/db.go:139 +0x75

[2022-03-17T05:26:54.001Z] github.com/pingcap/tidb/br/pkg/restore.(*DB).ensurePlacementPolicy(0xc000e565d0, 0x3e838b0, 0xc001fe2000, 0xc001ea1da0, 0xc, 0xc001ea1db0, 0xc, 0xc001f483c0, 0x7f4179c3d108, 0x8)

[2022-03-17T05:26:54.001Z] 	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/restore/db.go:331 +0xc5

[2022-03-17T05:26:54.001Z] github.com/pingcap/tidb/br/pkg/restore.(*DB).ensureTablePlacementPolicies(0xc000e565d0, 0x3e838b0, 0xc001fe2000, 0xc001e99c80, 0xc001f483c0, 0xc00140ee68, 0x0)

[2022-03-17T05:26:54.001Z] 	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/restore/db.go:340 +0x206

[2022-03-17T05:26:54.001Z] github.com/pingcap/tidb/br/pkg/restore.(*DB).CreateTables(0xc000e565d0, 0x3e838b0, 0xc001fe2000, 0xc000b9d900, 0x1e, 0x20, 0xc001fa94d0, 0x1, 0xc001f483c0, 0x5bcef20, ...)

[2022-03-17T05:26:54.001Z] 	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/restore/db.go:271 +0x47b

[2022-03-17T05:26:54.001Z] github.com/pingcap/tidb/br/pkg/restore.(*Client).createTables(0xc000e08300, 0x3e838b0, 0xc001fe2000, 0xc000e565d0, 0xc0004d0640, 0xc000b9d900, 0x1e, 0x20, 0x0, 0x0, ...)

[2022-03-17T05:26:54.001Z] 	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/restore/client.go:524 +0x70e

[2022-03-17T05:26:54.001Z] github.com/pingcap/tidb/br/pkg/restore.(*Client).createTablesInWorkerPool.func1(0x1, 0x0, 0x0)

[2022-03-17T05:26:54.001Z] 	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/restore/client.go:714 +0xcc

[2022-03-17T05:26:54.001Z] github.com/pingcap/tidb/br/pkg/utils.(*WorkerPool).ApplyWithIDInErrorGroup.func1(0x0, 0x0)

[2022-03-17T05:26:54.001Z] 	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/utils/worker.go:82 +0x77

[2022-03-17T05:26:54.001Z] golang.org/x/sync/errgroup.(*Group).Go.func1(0xc001fa9560, 0xc001deaae0)

[2022-03-17T05:26:54.001Z] 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59

[2022-03-17T05:26:54.001Z] created by golang.org/x/sync/errgroup.(*Group).Go

[2022-03-17T05:26:54.001Z] 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #33205

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Comment by lcwangchao** [comment]
[](https://github.com/lcwangchao)/run-integration-br-tests

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by lcwangchao** [comment]
[](https://github.com/bb7133)/run-integration-br-tests

**Pull request merged**
