### PR TITLE
statistics: remove dead code

### PR DESCRIPTION
**Pull request by Rustin170506**
Signed-off-by: Rustin170506 <techregister@pm.me>

### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/57804

Problem Summary:

### What changed and how does it work?

In this PR, I removed the dead code. The stats loading for the PK, as shown, has never been executed, so it is safe to remove.

Some background:
1. https://github.com/pingcap/tidb/pull/37552 This PR tried to load it correctly.
2. https://github.com/pingcap/tidb/pull/53298 This PR decided to remove it at all.
3. Another fix based on the previous PR: https://github.com/pingcap/tidb/pull/53399
4. Another full rewrite: https://github.com/pingcap/tidb/pull/57803

So we just forgot to delete it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by AilinKid — APPROVED** [review]

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by winoros — APPROVED** [review]

**Pull request merged**
