### PR TITLE
sessionctx: fix var typo

### PR DESCRIPTION
**Pull request by shawn0915**
### What problem does this PR solve?

Issue Number: ref #45892 

Problem Summary: fix typo

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by shawn0915** [comment]
@winoros could you help take a look?

**Comment by shawn0915** [comment]
@hawkingrei please confirm again, thank you.

**Review by zimulala — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Review by Defined2014 — APPROVED** [review]

**Pull request merged**
