### PR TITLE
expression/expressions: replace iconv-go with text/transform

### PR DESCRIPTION
**Pull request by Unknwon**
Remove CGO requirement for compiling iconv-go currently is using.

Replace it with native implementation of Go.

`make` test has passed, but test cases don't look very detailed on `expression`, so not sure if everything will go well.

Let's see if you are good with changes, then I'll do the godep thing.

### CODE REVIEW

**Comment by coocood** [comment]
LGTM
please add godep.

**Comment by Unknwon** [comment]
Updated PR.

**Comment by coocood** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
LGTM
@Unknwon  Thanks.

**Comment by siddontang** [comment]
@Unknwon  this function may be used in other places, we may move this to util as an alone package (e.g, iconv) later.

**Comment by Unknwon** [comment]
> @Unknwon this function may be used in other places, we may move this to util as an alone package (e.g, iconv) later.

:smile: that's up to you. Not much differences for me.

**Pull request merged**
