### PR TITLE
util/chunk: fix incorrect result when set duration to `MutRow` (#8725)

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve? 

Cherry-pick #8725

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8746)

### CODE REVIEW

**Comment by winoros** [comment]
/run-all-tests tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-integration-ddl-test tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-integration-ddl-test tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-integration-ddl-test tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-integration-ddl-test tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by winkyao** [comment]
/run-all-tests tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Pull request merged**
