### PR TITLE
ddl: refine ddl change shard_rowid err msg

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
 refine ddl change shard_rowid err msg. Print next global ID value if overflow.

### What is changed and how it works?
use to:

```go
shard_row_id_bits 6 will cause next global auto ID overflow
```

now

```go
shard_row_id_bits 6 will cause next global auto ID 576460752303423488 overflow.
```

### Check List 

Tests 

 - No Logical code

### CODE REVIEW

**Comment by crazycs520** [comment]
@winkyao @zimulala PTAL

**Comment by XuHuaiyu** [comment]
@crazycs520 idc-jenkins-ci-tidb/check_dev_2  failed.

**Pull request merged**
