### PR TITLE
executor, privilege: fix show grants

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: fix https://github.com/pingcap/tidb/issues/25972 and fix https://github.com/pingcap/tidb/issues/26451

Problem Summary:

### What is changed and how it works?

What's Changed:

The behavior of `SHOW GRANTS` was incorrect when a user had the GRANT privilege. The meta data remained mostly correct (with one exception: REVOKE table privileges).

This fixes several issues and adds tests.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
Revoking the `GRANT OPTION` on a database or table level led to inconsistent results in the `SHOW GRANTS` statement. The output has been improved to be MySQL compatible.
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

**Comment by tiancaiamao** [comment]
```
[2021-07-28T04:44:27.530Z] PANIC: session_test.go:4484: testTxnStateSerialSuite.TestRollbacking
[2021-07-28T04:44:27.530Z] 
[2021-07-28T04:44:27.530Z] ... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0x10F85B8)
[2021-07-28T04:44:27.530Z] 
[2021-07-28T04:44:27.530Z] /usr/local/go/src/runtime/panic.go:965
[2021-07-28T04:44:27.530Z]   in gopanic
[2021-07-28T04:44:27.530Z] /usr/local/go/src/runtime/panic.go:212
[2021-07-28T04:44:27.530Z]   in panicmem
[2021-07-28T04:44:27.530Z] /usr/local/go/src/runtime/signal_unix.go:734
[2021-07-28T04:44:27.530Z]   in sigpanic
[2021-07-28T04:44:27.530Z] session_test.go:4498
[2021-07-28T04:44:27.530Z]   in testTxnStateSerialSuite.TestRollbacking
[2021-07-28T04:44:27.530Z] /usr/local/go/src/reflect/value.go:337
[2021-07-28T04:44:27.530Z]   in Value.Call
[2021-07-28T04:44:27.530Z] /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850
[2021-07-28T04:44:27.530Z]   in suiteRunner.forkTest.func1
[2021-07-28T04:44:27.530Z] /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739
[2021-07-28T04:44:27.530Z]   in suiteRunner.forkCall.func1
[2021-07-28T04:44:27.530Z] /usr/local/go/src/runtime/asm_amd64.s:1371
[2021-07-28T04:44:27.530Z]   in goexit
```

It seems the unit test is not stable now?

**Review by xhebox — APPROVED** [review]

**Pull request merged**
