### PR TITLE
*: annotate execution info in runtime/trace (#19407)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19407 to release-4.0

---

### What problem does this PR solve?
Based on #19293

### What is changed and how it works?
Add more region information on RPC client and forked goroutines in some `Executor`, to help us filter task based on customized conditions.

图片
图片
图片

### Check List 

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- No release note

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
@bobotu please resolve conflicts and resolve CI.

**Comment by lysu** [comment]
LGTM

**Review by zz-jason — APPROVED** [review]
LGTM

**Pull request merged**
