### PR TITLE
br: fix panic during merging files

### LINKED ISSUE #33801: BR sometimes panics when meet some malformed start key of file
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Restore a file starts with index key and malformed index value. (e.g. unmatched JSON length or DECIMAL length)
That is possible in real world because the start key of file was chosen by the start key / end key of region.

### 2. What did you expect to see? (Required)
Restore success.

### 3. What did you see instead (Required)
Panic at `DecodeIndexValue`.

### 4. What is your TiDB version? (Required)
Current master.

### PR DESCRIPTION
**Pull request by YuJuncen**
Signed-off-by: Yu Juncen <yujuncen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #33801

Problem Summary:
The merge small files operation may panic because it try to decode the index value, however the region boundary is sometime weird and make TiDB panic.

### What is changed and how it works?
This PR use `DecodeKeyHead` to replace `DecodeIndexKey`, which won't try to decode the index value. 

### Check List

Tests 

- [x] Unit test
A fuzz test shows that this change is probably panic-free:
```console
> go test -fuzz=FuzzMerge br/pkg/restore/merge_fuzz_test.go
fuzz: elapsed: 0s, gathering baseline coverage: 0/81 completed
fuzz: elapsed: 3s, gathering baseline coverage: 81/81 completed, now fuzzing with 17 workers
fuzz: elapsed: 3s, execs: 81 (27/sec), new interesting: 0 (total: 81)
fuzz: elapsed: 6s, execs: 8727 (2883/sec), new interesting: 5 (total: 86)
fuzz: elapsed: 9s, execs: 17959 (3077/sec), new interesting: 12 (total: 93)
fuzz: elapsed: 12s, execs: 47126 (9724/sec), new interesting: 20 (total: 101)
fuzz: elapsed: 15s, execs: 65828 (6234/sec), new interesting: 23 (total: 104)
fuzz: elapsed: 18s, execs: 88492 (7553/sec), new interesting: 25 (total: 106)
fuzz: elapsed: 21s, execs: 105989 (5833/sec), new interesting: 25 (total: 106)
fuzz: elapsed: 24s, execs: 151362 (15123/sec), new interesting: 28 (total: 109)
fuzz: elapsed: 27s, execs: 183271 (10637/sec), new interesting: 29 (total: 110)
fuzz: elapsed: 30s, execs: 216909 (11214/sec), new interesting: 31 (total: 112)
fuzz: elapsed: 33s, execs: 254825 (12636/sec), new interesting: 35 (total: 116)
fuzz: elapsed: 36s, execs: 278409 (7863/sec), new interesting: 35 (total: 116)
fuzz: elapsed: 39s, execs: 325000 (15529/sec), new interesting: 35 (total: 116)
fuzz: elapsed: 42s, execs: 346768 (7255/sec), new interesting: 35 (total: 116)
fuzz: elapsed: 45s, execs: 367738 (6991/sec), new interesting: 35 (total: 116)
fuzz: elapsed: 48s, execs: 406754 (13006/sec), new interesting: 35 (total: 116)
fuzz: elapsed: 51s, execs: 424218 (5819/sec), new interesting: 35 (total: 116)
fuzz: elapsed: 54s, execs: 439857 (5214/sec), new interesting: 35 (total: 116)
fuzz: elapsed: 57s, execs: 459651 (6597/sec), new interesting: 35 (total: 116)
fuzz: elapsed: 1m0s, execs: 480267 (6873/sec), new interesting: 35 (total: 116)
^Cfuzz: elapsed: 1m1s, execs: 485575 (5989/sec), new interesting: 35 (total: 116)
```
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix a bug that caused BR panics sometime when merge small file enabled.
```

### CODE REVIEW

**Review by 3pointer — APPROVED** [review]
LGTM, well done

**Comment by fengou1** [comment]
LGTM

**Review by fengou1 — APPROVED** [review]

**Pull request merged**
