### PR TITLE
session: do not allow historical read in local temporary tables

### LINKED ISSUE #25938: do not allow historical read in local temporary tables

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: close #25938

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lcwangchao — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Comment by sylzd** [comment]
@lcwangchao @tiancaiamao   It seems conflicts with `TestCreateTemporaryTable`, should we modify it?

```go
	// Considering snapshot, local temporary table is always visible.
	tk.MustExec("set @@tidb_snapshot = '2016-01-01 15:04:05.999999'")
	tk.MustExec("select * from overlap")
```

**Comment by lcwangchao** [comment]
> @lcwangchao @tiancaiamao It seems conflicts with `TestCreateTemporaryTable`, should we modify it?
> 
> ```go
> 	// Considering snapshot, local temporary table is always visible.
> 	tk.MustExec("set @@tidb_snapshot = '2016-01-01 15:04:05.999999'")
> 	tk.MustExec("select * from overlap")
> ```

I think we should remove this test.

**Comment by lcwangchao** [comment]
@sylzd Please modify the release note and set the content `None`

**Review by djshow832 — APPROVED** [review]

**Pull request merged**
