### PR TITLE
executor: fix DATA RACE in the TestAnalyzeParameters and other 3 test cases

### LINKED ISSUE #31930: DATA RACE in the TestAnalyzeParameters/TestAnalyzeTooLongColumns/TestExtractTopN/TestHashInTopN
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
==================
WARNING: DATA RACE
Read at 0x00c000fd5420 by goroutine 201:
  github.com/pingcap/tidb/domain.(*Domain).globalBindHandleWorkerLoop.func1()
      /go/tidb/domain/domain.go:1107 +0x2c4
Previous write at 0x00c000fd5420 by goroutine 205:
  [failed to restore the stack]
Goroutine 201 (running) created at:
  github.com/pingcap/tidb/domain.(*Domain).globalBindHandleWorkerLoop()
      /go/tidb/domain/domain.go:1090 +0xf1
  github.com/pingcap/tidb/domain.(*Domain).LoadBindInfoLoop()
      /go/tidb/domain/domain.go:1083 +0x1a4
  github.com/pingcap/tidb/session.BootstrapSession()
      /go/tidb/session/session.go:2655 +0x5aa
  github.com/pingcap/tidb/testkit.bootstrap()
      /go/tidb/testkit/mockstore.go:49 +0x84
  github.com/pingcap/tidb/testkit.CreateMockStoreAndDomain()
      /go/tidb/testkit/mockstore.go:42 +0xc4
  github.com/pingcap/tidb/testkit.CreateMockStore()
      /go/tidb/testkit/mockstore.go:34 +0x59
  github.com/pingcap/tidb/executor_test.TestAnalyzeParameters()
      /go/tidb/executor/analyze_test.go:185 +0x3e
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Goroutine 205 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1504 +0x9d1
  github.com/pingcap/tidb/testkit/testmain.(*testingM).Run()
      /go/tidb/testkit/testmain/wrapper.go:28 +0x42
  go.uber.org/goleak.VerifyTestMain()
      /home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x59
  github.com/pingcap/tidb/executor_test.TestMain()
      /go/tidb/executor/main_test.go:66 +0x6e4
  main.main()
      _testmain.go:695 +0x264
==================
==================
WARNING: DATA RACE
Write at 0x00c000e3f398 by goroutine 201:
  sync/atomic.CompareAndSwapInt32()
      /usr/local/go/src/runtime/race_amd64.s:334 +0xb
  sync/atomic.CompareAndSwapInt32()
      <autogenerated>:1 +0x1e
  github.com/pingcap/tidb/bindinfo.(*BindHandle).Update()
      /go/tidb/bindinfo/handle.go:126 +0x68
  github.com/pingcap/tidb/domain.(*Domain).globalBindHandleWorkerLoop.func1()
      /go/tidb/domain/domain.go:1107 +0x2d7
Previous write at 0x00c000e3f398 by goroutine 205:
  [failed to restore the stack]
Goroutine 201 (running) created at:
  github.com/pingcap/tidb/domain.(*Domain).globalBindHandleWorkerLoop()
      /go/tidb/domain/domain.go:1090 +0xf1
  github.com/pingcap/tidb/domain.(*Domain).LoadBindInfoLoop()
      /go/tidb/domain/domain.go:1083 +0x1a4
  github.com/pingcap/tidb/session.BootstrapSession()
      /go/tidb/session/session.go:2655 +0x5aa
  github.com/pingcap/tidb/testkit.bootstrap()
      /go/tidb/testkit/mockstore.go:49 +0x84
  github.com/pingcap/tidb/testkit.CreateMockStoreAndDomain()
      /go/tidb/testkit/mockstore.go:42 +0xc4
  github.com/pingcap/tidb/testkit.CreateMockStore()
      /go/tidb/testkit/mockstore.go:34 +0x59
  github.com/pingcap/tidb/executor_test.TestAnalyzeParameters()
      /go/tidb/executor/analyze_test.go:185 +0x3e
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Goroutine 205 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1504 +0x9d1
  github.com/pingcap/tidb/testkit/testmain.(*testingM).Run()
      /go/tidb/testkit/testmain/wrapper.go:28 +0x42
  go.uber.org/goleak.VerifyTestMain()
      /home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x59
  github.com/pingcap/tidb/executor_test.TestMain()
      /go/tidb/executor/main_test.go:66 +0x6e4
  main.main()
      _testmain.go:695 +0x264
==================
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #31930

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Comment by tangenta** [comment]
Please also update these cases:
- TestAnalyzeTooLongColumns
- TestExtractTopN
- TestHashInTopN
- TestAnalyzeIncrementalStreaming

**Comment by hawkingrei** [comment]
> * TestHashInTopN

All fixed

**Comment by hawkingrei** [comment]
> Please also update these cases:
> 
>     * TestAnalyzeTooLongColumns
> 
>     * TestExtractTopN
> 
>     * TestHashInTopN
> 
>     * TestAnalyzeIncrementalStreaming

All fixed

**Review by tiancaiamao — APPROVED** [review]
It seems to be a tiny code clean up, I can't how it fixes DATA RACE...
Anyway, the changes is fine.

**Pull request merged**
