### PR TITLE
*: add test for modifying default length of cast as decimal

### PR DESCRIPTION
**Pull request by HuGanghui**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23495

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: add test for modifying default length of cast as decimal in https://github.com/pingcap/parser/pull/1202

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Comment by HuGanghui** [comment]
[2021-03-31T01:46:20.869Z] 
[2021-03-31T01:46:20.869Z] ----------------------------------------------------------------------
[2021-03-31T01:46:20.869Z] FAIL: revoke_test.go:73: testSuite1.TestRevokeTableScope
[2021-03-31T01:46:20.869Z] 
[2021-03-31T01:46:20.869Z] revoke_test.go:85:
[2021-03-31T01:46:20.869Z]     res.Check(testkit.Rows("Select,Insert,Update,Delete,Create,Drop,Index,Alter,Show View"))
[2021-03-31T01:46:20.869Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:63:
[2021-03-31T01:46:20.869Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
[2021-03-31T01:46:20.869Z] ... obtained string = "[Select,Insert,Update,Delete,Create,Drop,Index,Alter,Create View,Show View]\n"
[2021-03-31T01:46:20.869Z] ... expected string = "[Select,Insert,Update,Delete,Create,Drop,Index,Alter,Show View]\n"
[2021-03-31T01:46:20.869Z] ... sql:SELECT Table_priv FROM mysql.tables_priv WHERE User="testTblRevoke" and host="localhost" and db="test" and Table_name="test1", args:[]
[2021-03-31T01:46:20.869Z]

**Comment by HuGanghui** [comment]
> @ichn-hu
> I don't know why this test failed, according to log, do we need to add `Create View` to expected string?
> 
> ```
> [2021-03-31T01:46:20.869Z] 
> [2021-03-31T01:46:20.869Z] ----------------------------------------------------------------------
> [2021-03-31T01:46:20.869Z] FAIL: revoke_test.go:73: testSuite1.TestRevokeTableScope
> [2021-03-31T01:46:20.869Z] 
> [2021-03-31T01:46:20.869Z] revoke_test.go:85:
> [2021-03-31T01:46:20.869Z]     res.Check(testkit.Rows("Select,Insert,Update,Delete,Create,Drop,Index,Alter,Show View"))
> [2021-03-31T01:46:20.869Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:63:
> [2021-03-31T01:46:20.869Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
> [2021-03-31T01:46:20.869Z] ... obtained string = "[Select,Insert,Update,Delete,Create,Drop,Index,Alter,Create View,Show View]\n"
> [2021-03-31T01:46:20.869Z] ... expected string = "[Select,Insert,Update,Delete,Create,Drop,Index,Alter,Show View]\n"
> [2021-03-31T01:46:20.869Z] ... sql:SELECT Table_priv FROM mysql.tables_priv WHERE User="testTblRevoke" and host="localhost" and db="test" and Table_name="test1", args:[]
> [2021-03-31T01:46:20.869Z] 
> ```

@xhebox this seems caused by https://github.com/pingcap/parser/commit/d7bda6c6001ad418071e436e979b13ab06c51761, PTAL and try to solve it.

**Comment by ichn-hu** [comment]
> > @ichn-hu
> > I don't know why this test failed, according to log, do we need to add `Create View` to expected string?
> > ```
> > [2021-03-31T01:46:20.869Z] 
> > [2021-03-31T01:46:20.869Z] ----------------------------------------------------------------------
> > [2021-03-31T01:46:20.869Z] FAIL: revoke_test.go:73: testSuite1.TestRevokeTableScope
> > [2021-03-31T01:46:20.869Z] 
> > [2021-03-31T01:46:20.869Z] revoke_test.go:85:
> > [2021-03-31T01:46:20.869Z]     res.Check(testkit.Rows("Select,Insert,Update,Delete,Create,Drop,Index,Alter,Show View"))
> > [2021-03-31T01:46:20.869Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:63:
> > [2021-03-31T01:46:20.869Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
> > [2021-03-31T01:46:20.869Z] ... obtained string = "[Select,Insert,Update,Delete,Create,Drop,Index,Alter,Create View,Show View]\n"
> > [2021-03-31T01:46:20.869Z] ... expected string = "[Select,Insert,Update,Delete,Create,Drop,Index,Alter,Show View]\n"
> > [2021-03-31T01:46:20.869Z] ... sql:SELECT Table_priv FROM mysql.tables_priv WHERE User="testTblRevoke" and host="localhost" and db="test" and Table_name="test1", args:[]
> > [2021-03-31T01:46:20.869Z] 
> > ```
> 
> @xhebox this seems caused by [pingcap/parser@d7bda6c](https://github.com/pingcap/parser/commit/d7bda6c6001ad418071e436e979b13ab06c51761), PTAL and try to solve it.

this test is fixed in https://github.com/pingcap/tidb/pull/23519, sorry for bring inconvenience, we can just ignore it for reviewing your PR.

**Review by ichn-hu — APPROVED** [review]
LGTM

**Comment by xhebox** [comment]
@HuGanghui You can fix it by adding 'Create View' in the test. That is the correct fix for this PR. You don't need to wait for the original PR.

**Comment by HuGanghui** [comment]
@xhebox I try it, but it will cause another test failure..., so maybe it's better to ignore it.

**Comment by xhebox** [comment]
@HuGanghui wait a sec, let me give a diff patch that works.

**Comment by xhebox** [comment]
> @xhebox I try it, but it will cause another test failure..., so maybe it's better to ignore it.

Here it is:

```
diff --git a/executor/revoke_test.go b/executor/revoke_test.go
index 21e2d4e15..eb5748fa7 100644
--- a/executor/revoke_test.go
+++ b/executor/revoke_test.go
@@ -82,7 +82,7 @@ func (s *testSuite1) TestRevokeTableScope(c *C) {
 
        // Make sure all the table privs for new user is Y.
        res := tk.MustQuery(`SELECT Table_priv FROM mysql.tables_priv WHERE User="testTblRevoke" and host="localhost" and db="test" and Table_name="test1"`)
-       res.Check(testkit.Rows("Select,Insert,Update,Delete,Create,Drop,Index,Alter,Show View"))
+       res.Check(testkit.Rows("Select,Insert,Update,Delete,Create,Drop,Index,Alter,Create View,Show View"))
 
        // Revoke each priv from the user.
        for _, v := range mysql.AllTablePrivs {
@@ -92,8 +92,15 @@ func (s *testSuite1) TestRevokeTableScope(c *C) {
                c.Assert(rows, HasLen, 1)
                row := rows[0]
                c.Assert(row, HasLen, 1)
-               p := fmt.Sprintf("%v", row[0])
-               c.Assert(strings.Index(p, mysql.Priv2SetStr[v]), Equals, -1)
+               op := mysql.Priv2SetStr[v]
+               found := false
+               for _, v := range strings.Split(fmt.Sprintf("%v", row[0]), ",") {
+                       if v == op {
+                               found = true
+                               break
+                       }
+               }
+               c.Assert(found, IsFalse)
        }
```

**Review by lzmhhh123 — APPROVED** [review]

**Comment by xhebox** [comment]
> /re-trigger

It does work with jenkins tests in TiDB. For TiDB, just use `/run-[test name]`.

**Comment by HuGanghui** [comment]
`
[2021-04-06T02:22:43.122Z] FAIL: analyze_test.go:238: testSuite1.TestAnalyzeIndexExtractTopN
[2021-04-06T02:22:43.122Z] 
[2021-04-06T02:22:43.122Z] analyze_test.go:288:
[2021-04-06T02:22:43.122Z]     c.Assert(idx.CMSketch.Equal(cms), IsTrue)
[2021-04-06T02:22:43.122Z] ... obtained bool = false
[2021-04-06T02:22:43.122Z] 
`

`
[2021-04-06T02:22:43.122Z] FAIL: analyze_test.go:238: testSuite1.TestAnalyzeIndexExtractTopN
[2021-04-06T02:22:43.122Z] 
[2021-04-06T02:22:43.122Z] analyze_test.go:288:
[2021-04-06T02:22:43.122Z]     c.Assert(idx.CMSketch.Equal(cms), IsTrue)
[2021-04-06T02:22:43.122Z] ... obtained bool = false
[2021-04-06T02:22:43.122Z] 
`
`
[2021-04-06T02:22:44.080Z] FAIL: analyze_test.go:511: testSerialSuite2.TestFastAnalyze4GlobalStats
[2021-04-06T02:22:44.080Z] 
[2021-04-06T02:22:44.080Z] analyze_test.go:523:
[2021-04-06T02:22:44.080Z]     c.Assert(err.Error(), Equals, "Fast analyze hasn't reached General Availability and only support analyze version 1 currently.")
[2021-04-06T02:22:44.080Z] ... obtained string = "[stats]: some partition level statistics are not in statistics version 2, please set tidb_analyze_version to 2 and analyze the this table"
[2021-04-06T02:22:44.080Z] ... expected string = "Fast analyze hasn't reached General Availability and only support analyze version 1 currently."
[2021-04-06T02:22:44.080Z] 
`
`
[2021-04-06T02:22:44.513Z] FAIL: simple_test.go:606: testSerialSuite.TestDropPartitionStats
[2021-04-06T02:22:44.513Z] 
[2021-04-06T02:22:44.513Z] simple_test.go:633:
[2021-04-06T02:22:44.513Z]     tk.MustExec("analyze table t")
[2021-04-06T02:22:44.513Z] /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:217:
[2021-04-06T02:22:44.513Z]     tk.c.Assert(err, check.IsNil, check.Commentf("sql:%s, %v, error stack %v", sql, args, errors.ErrorStack(err)))
[2021-04-06T02:22:44.513Z] ... value *errors.withStack = [stats]: some partition level statistics are not in statistics version 2, please set tidb_analyze_version to 2 and analyze the this table ("[stats]: some partition level statistics are not in statistics version 2, please set tidb_analyze_version to 2 and analyze the this table")
[2021-04-06T02:22:44.513Z] ... sql:analyze table t, [], error stack [stats]: some partition level statistics are not in statistics version 2, please set tidb_analyze_version to 2 and analyze the this table
`

**Comment by HuGanghui** [comment]
@lzmhhh123 This PR can be merged, right? Or do we need to wait for all the tests to pass？

**Comment by lzmhhh123** [comment]
> @lzmhhh123 This PR can be merged, right? Or do we need to wait for all the tests to pass？

Don't worry. The CI is unstable now. The PR can be auto-merged when CI becomes stable.

**Comment by HuGanghui** [comment]
ok, thanks.

**Pull request merged**
