### PR TITLE
executor: fix show create table for partitioned table

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Show create table result:

```
CREATE TABLE `log` (
  `LOG_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `ROUND_ID` bigint(20) unsigned NOT NULL,
  `USER_ID` int(10) unsigned NOT NULL,
  `USER_IP` int(10) unsigned DEFAULT NULL,
  `END_TIME` datetime NOT NULL,
  `USER_TYPE` int(11) DEFAULT NULL,
  `APP_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`LOG_ID`,`END_TIME`),
  KEY `IDX_EndTime` (`END_TIME`),
  KEY `IDX_RoundId` (`ROUND_ID`),
  KEY `IDX_UserId_EndTime` (`USER_ID`,`END_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
PARTITION BY RANGE ( month(`end_time`) ) (
  PARTITION p1 VALUES LESS THAN (2),
  PARTITION p2 VALUES LESS THAN (3),
  PARTITION p3 VALUES LESS THAN (4),
  PARTITION p4 VALUES LESS THAN (5),
  PARTITION p5 VALUES LESS THAN (6),
  PARTITION p6 VALUES LESS THAN (7),
  PARTITION p7 VALUES LESS THAN (8),
  PARTITION p8 VALUES LESS THAN (9),
  PARTITION p9 VALUES LESS THAN (10),
  PARTITION p10 VALUES LESS THAN (11),
  PARTITION p11 VALUES LESS THAN (12),
  PARTITION p12 VALUES LESS THAN (MAXVALUE)
) AUTO_INCREMENT=505488
```

`AUTO_INCREMENT=505488` should not be after PARTITION definitions.
If there is a `COMMENT=xxx`, it would meet the same problem as `AUTO_INCREMENT=xxx`.

### What is changed and how it works?

Fix the order, let the PARTITION definitions come last

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @lysu @jackysp

**Comment by shenli** [comment]
The description is not clear. You not only handle the `AUTO_INCREMENT` part, but also the `COMMENT` part.

**Comment by tiancaiamao** [comment]
@shenli Updated

**Pull request merged**
