### PR TITLE
server: add metric for connection idle time (#21265)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21265 to release-4.0

---

### What problem does this PR solve?

Add a client connection idle time duration metric. such as below:

image

Then, it will be easy to check the idle connections.

The idle time is calculated from the last finish execution time.

### What is changed and how it works?

add metric.

### Related changes

- Need to cherry-pick to the release branch: release 4.0

### Check List 

Tests 

- Manual test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- Add metric for connection idle time

### CODE REVIEW

**Comment by crazycs520** [comment]
@jackysp @lysu PTAL

**Comment by lysu** [comment]
LGTM

**Review by jackysp — APPROVED** [review]
LGTM

**Pull request merged**
