### PR TITLE
*: bump etcd's version to 3.2.18

### PR DESCRIPTION
**Pull request by zhexuany**
etcd's version was already updated in pd side. Since both tidb and pd lock etcd's version, it is better to maintain the consistency. 
@shenli @disksing PTAL

### CODE REVIEW

**Comment by shenli** [comment]
@disksing PTAL

**Comment by disksing** [comment]
No code change?

**Comment by zhexuany** [comment]
@shenli  @disksing PTAL again.

**Comment by disksing** [comment]
LGTM.

**Comment by zhexuany** [comment]
@shenli PTAL

**Comment by shenli** [comment]
LGTM

**Pull request merged**
