### PR TITLE
executor: fix regression by Tracker.Consume in aggregate.

### LINKED ISSUE #22881: 02-18 Performance regression on TPCH multiple queries
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
Version:
tidb: 937472423112000c875f7c8607aa57b4b31eaf10(master) 2021-02-18 16:17:53
tikv: c514eb5e71bc0e150a168463d2fd7ad777fffaa7(master) 2021-02-18 03:36:18
pd: 0b00c7edb169927b3fbe9862989a600bb807921e(master) 2021-02-18 02:11:10

Compare:
tidb: https://github.com/pingcap/tidb/compare/c9af430...9374724
tikv: https://github.com/tikv/tikv/compare/cff4789...c514eb5
pd: https://github.com/pingcap/pd/compare/760fb65...0b00c7e

01.sql elapsed_ms: 61334.85 ± 0.4233% (std=172.22) delta: -0.15%
02.sql elapsed_ms: 18047.79 ± 2.0972% (std=246.24) delta: 19.98%
03.sql elapsed_ms: 52342.23 ± 0.2185% (std=83.69) delta: -0.18%
04.sql elapsed_ms: 26386.43 ± 0.6675% (std=123.78) delta: -0.93%
06.sql elapsed_ms: 31398.67 ± 9.7538% (std=1957.57) delta: -0.99%
07.sql elapsed_ms: 51491.36 ± 0.2447% (std=84.53) delta: -0.25%
08.sql elapsed_ms: 42626.65 ± 1.1833% (std=334.64) delta: -1.65%
09.sql elapsed_ms: 162548.41 ± 1.2139% (std=1354.16) delta: -0.34%
10.sql elapsed_ms: 48616.65 ± 4.7659% (std=1386.77) delta: 14.00%
11.sql elapsed_ms: 13318.37 ± 3.8688% (std=339.06) delta: 10.25%
12.sql elapsed_ms: 45654.66 ± 0.2327% (std=70.30) delta: -0.33%
13.sql elapsed_ms: 46410.86 ± 1.1512% (std=371.58) delta: 9.36%
14.sql elapsed_ms: 32762.64 ± 0.0869% (std=22.07) delta: -1.77%
15.sql elapsed_ms: 65382.29 ± 0.7012% (std=298.72) delta: 0.62%
16.sql elapsed_ms: 11998.75 ± 2.9283% (std=238.54) delta: -3.01%
17.sql elapsed_ms: 122738.06 ± 0.3687% (std=331.69) delta: 15.86%
19.sql elapsed_ms: 43757.52 ± 0.3204% (std=99.29) delta: -0.45%
20.sql elapsed_ms: 39008.77 ± 0.4969% (std=146.87) delta: 4.69%
21.sql elapsed_ms: 82118.67 ± 0.0676% (std=39.80) delta: 0.05%
22.sql elapsed_ms: 26629.85 ± 0.3765% (std=68.08) delta: -6.68%
```

By bisect, I found this performance regression was caused by https://github.com/pingcap/tidb/pull/22463

### 4. What is your TiDB version? (Required)

master fb84db123cad3f5996e712e8f7695ecfd27ac4de

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve?

Issue Number: close #22881  

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

Side effects

### Release note 

- No release note

### CODE REVIEW

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Review by lzmhhh123 — COMMENTED** [review]
/LGTM

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Pull request merged**
