### PR TITLE
expression: set pb code for builtinArithmeticDivideDecimalSig

### PR DESCRIPTION
**Pull request by zz-jason**
## Main Modification

set pb code `ScalarFuncSig_DivideDecimal` for `builtinArithmeticDivideDecimalSig`

```sql
drop table if exists t;
create table t(a decimal(10, 2), b bigint);
insert into t values(1.3, 1);
```

To fix this panic in TiKV/mocktikv:
```sql
TiDB(localhost:4000) > select * from t where a/1 > 1;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

### CODE REVIEW

**Comment by zz-jason** [comment]
@XuHuaiyu @coocood PTAL

**Comment by zz-jason** [comment]
This PR needs to be cherry picked to release 2.0

**Comment by coocood** [comment]
@zz-jason 
Please add a test cae

**Comment by zz-jason** [comment]
@coocood https://github.com/pingcap/tidb-test/pull/531

**Comment by coocood** [comment]
LGTM

**Pull request merged**
