### PR TITLE
expression: fix wrong result for field function

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

field function doesn't consider collation in vecEvalInt, because the generator may overwrite it.

### What is changed and how it works?

Manually change the implementation of vecEvalInt of the field function.

### Check List 

Tests 

- Integration test

Side effects

### Release note 
- fix wrong result for field function when the argument contains column

### CODE REVIEW

**Comment by SunRunAway** [comment]
> I think that we should modify expression/generator/string_vec.go and use it to generate code.

@bb7133 PTAL

**Comment by wjhuang2016** [comment]
I will fix it soon

**Pull request merged**
