### PR TITLE
telemetry: add reviewer rule

### LINKED ISSUE #36087: Proposal: require review rules for telemetry
Hi, developers!

**Background**
The collection of telemetry data is related to PingCAP’s [privacy policy](https://pingcap.com/zh/privacy-policy/) for our customers. Therefore, the telemetry files need to be reviewed by the legal, security, and telemetry framework team when it is modified.

**TiDB Telemetry**
For TiDB, the following folder is issued:

[tidb/telemetry at master · pingcap/tidb](https://github.com/pingcap/tidb/tree/master/telemetry)

TiDB is an open source distributed HTAP database compatible with the MySQL protocol - tidb/telemetry at master · pingcap/tidb

changes on this folder should be reviewed by anyone of:

@AstroProfundis 
@lucklove 
@kaixu120811 

In order to add the rules in review PR, we plan to add the review required bot in pingcap/tidb repos.

### PR DESCRIPTION
**Pull request by AstroProfundis**
Signed-off-by: Allen Zhong <zhongbenli@pingcap.com>

### What problem does this PR solve?

Add reviewer rule for the `/telemetry` directory

Issue Number: close #36087 

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by wuhuizuo** [comment]
> [FORMAT CHECKER NOTIFICATION]
> 
> **Notice**: To remove the `do-not-merge/needs-linked-issue` label, please provide the linked issue number on one line in the PR body, for example: `Issue Number: close #123` or `Issue Number: ref #456`.
> 
> 📖 For more info, you can check the ["Contribute Code"](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#referring-to-an-issue) section in the development guide.

@AstroProfundis you should add issue ref in PR description

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
