### PR TITLE
*: upgrade go version to 1.16

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?
go version is too old.

### What is changed and how it works?
What's Changed:
- use latest

### Release note 
- No release note

### CODE REVIEW

**Review by ngaut — APPROVED** [review]
LGTM

**Review by youjiali1995 — COMMENTED** [review]
/LGTM

**Comment by zz-jason** [comment]
@disksing @ngaut @youjiali1995 

we need more test cases to measure the result of upgrading the Golang version, for example:

- **Compability tests**: this may be covered by the current integration and unit tests, but it's better to design more tests for the Golang compiler and runtime
- **Benchmark tests**: we need to measure whether there are performance improvements or reductions after upgrading to the new go version under certain test scenarios

/cc @shuke987 @zhouqiang-cl

**Review by AndreMouche — APPROVED** [review]
LGTM

**Comment by zz-jason** [comment]
@disksing Is there any plan to upgrade the Jenkins package pipeline to utilize the new go version?

**Comment by disksing** [comment]
> @disksing Is there any plan to upgrade the Jenkins package pipeline to utilize the new go version?

no plan :P I'm updating it because my PR(https://github.com/pingcap/tidb/pull/22891) needs go1.14+ to support the diamond inherit.

**Pull request merged**
