### PR TITLE
*: refactor the RestrictedSQLExecutor interface (#22579)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #22579 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/22621
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/22621:release-4.0-ea6ccf82e934
```

---

### What problem does this PR solve?

Problem Summary:

Improve security for our code.

### What is changed and how it works?

The initial definition of `RestrictedSQLExecutor` looks like this:

```
type RestrictedSQLExecutor interface {
	// ExecRestrictedSQL run sql statement in ctx with some restriction.
	ExecRestrictedSQL(sql string) ([]chunk.Row, []*ast.ResultField, error)
}
```

It's not good for security reasons, the usage pattern looks like this:

```
sql  = fmt.Sprintf('select xxx from ..%s ', varFromOutside)
stmt, err = ExecRestrictedSQL(sql) 
...
```

Later on, we add more methods to the interface which IMO, ugly:

```
	// ExecRestrictedSQLWithContext run sql statement in ctx with some restriction.
	ExecRestrictedSQLWithContext(ctx context.Context, sql string, opts ...OptionFuncAlias) ([]chunk.Row, []*ast.ResultField, error)
	// ExecRestrictedSQLWithSnapshot run sql statement in ctx with some restriction and with snapshot.
	// If current session sets the snapshot timestamp, then execute with this snapshot timestamp.
	// Otherwise, execute with the current transaction start timestamp if the transaction is valid.
	ExecRestrictedSQLWithSnapshot(sql string) ([]chunk.Row, []*ast.ResultField, error)
```

I propose to use this one as its new definition:

```
type RestrictedSQLExecutor interface {
	ParseWithParams(ctx context.Context, sql string, args ...interface{}) (ast.StmtNode, error)
	ExecRestrictedStmt(ctx context.Context, stmt ast.StmtNode, opts ...OptionFuncAlias) ([]chunk.Row, []*ast.ResultField, error)
}
```

This interface is secure, and easy to use:

```
stmt  = exec.ParseWithParams('select xxx from ..%? ', varFromOutside)
res, err = ExecRestrictedSQL(stmt) 
...
```

What's Changed:

`ParseWithParams()` now returns `ast.StmtNode` rather than `[]ast.StmtNode`, multiple statements are not allowed here.

Update the "util", "store", and "domain" packages,  ensure they use the new (secure) API.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

- Breaking backward compatibility
API change

### Release note 

- No release note

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Depends on https://github.com/pingcap/tidb/pull/22548

**Review by xhebox — COMMENTED** [review]
/lgtm

**Comment by tiancaiamao** [comment]
PTAL @morgo

**Pull request merged**
