### PR TITLE
expression: ComposeCNF/DNFConditions don't need to fold constant

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve? 

Reduce the `foldConstant` cost of 
image

relates to #10828

### What is changed and how it works?

Before create the CNF/DNF expression. The leaves have all done the `unfoldConstant`. So we just check whether they have true/false/null or are all constant. Don't need to call `unfoldConstant` again and again.

### Check List 

Tests 

 - Exsiting Unit test

Related changes

 - Need to be included in the release note

### CODE REVIEW

**Comment by winoros** [comment]
I think this pr doesn't solve the root cause of this performance issue.
The root cause is that for a specific expression, optimizations can be done only once. But we do it again and again.

Fow now, we only has constant folding optimization. But we may have some other optimizations like doing some arithmetic simplification mentioned in https://github.com/pingcap/tidb/issues/11653 . We need to make sure that these optimizations can be applied only once for one expression.

Actually, the changed codes does a constant folding procedure before building the CNF/DNF tree. Just don't fold each leaf again and again. So it's a special case to avoid part of useless calls of folding constant, don't solve the root cause actually. If we can solve the root problem in a more general way, we don't need to write codes to do a lite version of constant folding when creating one CNF/DNF tree, just call `FoldConstant` directly.

**Comment by lamxTyler** [comment]
If the optimization in this pr is not urgent needed, I prefer to close it and solve the root problem.

**Comment by winoros** [comment]
Yeah i agree with you. I'll try another way when i'm free.

**Pull request closed without merging**
