### PR TITLE
plan: copy the physical info to avoid panic.

### PR DESCRIPTION
**Pull request by hanfei1991**
When we get a physical info from memory table, we shouldn't change it directly. We should always copy it firstly.
@shenli @coocood @winoros @lamxTyler PTAL

### CODE REVIEW

**Comment by coocood** [comment]
@hanfei1991 
Do you mean only memory table should be copied?
But the test is not memory table.

**Comment by hanfei1991** [comment]
@coocood memory table means dp table

**Comment by coocood** [comment]
LGTM

**Comment by coocood** [comment]
@hanfei1991 
The cached plan info is stored in a field called `planMap`.
And we never used something called `dp table` and `memory table` has special meaning like information_schema tables.

**Comment by ngaut** [comment]
What is dp table ?

**Pull request merged**
