### PR TITLE
expression, types: fix unexpected result from TIME() when fsp digits > 6 (#21652)

### LINKED ISSUE #20995: expression: unexpected result from TIME() when fsp digits > 6
## Bug Report

It seems that TiDB will report an error when fsp digits is greater than 6, but MySQL will round it to the nearest 6-digit fsp number.

### 1. Minimal reproduce step (Required)

```sql
SELECT TIME(0.1234567);
```

### 2. What did you expect to see? (Required)
```
+-----------------+
| time(0.1234567) |
+-----------------+
| 00:00:00.123457 |
+-----------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
ERROR 1105 (HY000): Invalid fsp 7
```

### 4. What is your TiDB version? (Required)

master branch

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21652 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #20995 

Problem Summary:

### What is changed and how it works?

What's Changed:
fix unexpected result from TIME() when fsp digits > 6
How it Works:
if fsp digits > 6, fsp digits is set to  `MaxFsp`.
### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
tidb-test PR:
https://github.com/pingcap/tidb-test/pull/1129

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by zz-jason — APPROVED** [review]

**Comment by qw4990** [comment]
There are some problems with CI. I close it now and will pick it manually again later.

**Pull request closed without merging**
