### PR TITLE
variable: revise TiDBStatsCacheMemQuota settting code

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/34052

Problem Summary:

### What is changed and how it works?

revise TiDBStatsCacheMemQuota settting code by moving code into `SetGlobal`

### Check List

Tests 

- [x] Manual test (add detailed scripts or steps below)

I manually tested `set global tidb_stats_cache_mem_quota`, it still work

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by chrysan — APPROVED** [review]

**Review by morgo — APPROVED** [review]

**Comment by morgo** [comment]
Nice work! We should consider using this same trick in the other cases where we need `domain` in sysvars. It will simplify the sysvar_cache code.

**Pull request merged**
