### PR TITLE
lightning: adapt new behaviour that "write" may return epoch error (#…

### LINKED ISSUE #47694: lightning check the error of write RPC
https://github.com/tikv/tikv/issues/15003

### PR DESCRIPTION
**Pull request by lance6716**
…47667)

close pingcap/tidb#47694

### What problem does this PR solve?

Issue Number: close #47694

Problem Summary:

### What changed and how does it work?

~This PR also pick https://github.com/pingcap/tidb/pull/50129 to run the integration tests locally~

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

CI passed after skip a failed BR test https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Frelease-6.5%2Fpull_br_integration_test/detail/pull_br_integration_test/25/pipeline/

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by D3Hunter — APPROVED** [review]

**Comment by lance6716** [comment]
/hold

will add a commit to skip failed tests

**Comment by lance6716** [comment]
CI passed https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Frelease-6.5%2Fpull_br_integration_test/detail/pull_br_integration_test/25/pipeline/

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
