### PR TITLE
codec: fix ARM build fail

### LINKED ISSUE #165: Test fail on ARM(raspberry pi)
All tests passes except the following two:

```
# github.com/pingcap/tidb/util/codec
util/codec/codec_test.go:133: constant 1152921504606846975 overflows int
util/codec/codec_test.go:153: constant -9223372036854775808 overflows int
util/codec/codec_test.go:158: constant -9223372036854775808 overflows int
util/codec/codec_test.go:582: constant 9223372036854775807 overflows int
util/codec/codec_test.go:582: constant -9223372036854775808 overflows int
util/codec/codec_test.go:582: too many errors
```

I know it's kind of non-critical, but just in case you know how to fix it.

And another one:

```
FAIL	github.com/pingcap/tidb/util/types [build failed]
godep: go exit status 2
Makefile:76: recipe for target 'gotest' failed
make: *** [gotest] Error 1
```

### PR DESCRIPTION
**Pull request by siddontang**
fix #165

### CODE REVIEW

**Comment by siddontang** [comment]
How about now?

@Unknwon

**Comment by Unknwon** [comment]
hmm....

```
# github.com/pingcap/tidb/util/types
util/types/convert_test.go:474: constant 4294967295 overflows int
util/types/convert_test.go:475: constant 4294967295 overflows int
util/types/convert_test.go:477: constant -9223372036854775808 overflows int
util/types/convert_test.go:478: constant -9223372036854775808 overflows int
util/types/convert_test.go:479: constant 9223372036854775807 overflows int
util/types/convert_test.go:479: too many errors
```

**Comment by siddontang** [comment]
@Unknwon  Do you use the latest code? I have updated it..

**Comment by Unknwon** [comment]
Yes I use git pull and checked commit SHA with git log -1

**Comment by siddontang** [comment]
Hi @Unknwon 

Try it again.

**Comment by Unknwon** [comment]
OK I'm in class will do in 1 hours.

**Comment by Unknwon** [comment]
I rally mean 2 hours...

**Comment by siddontang** [comment]
Sorry :-) 
I will try to use Go cross-build, maybe.

**Comment by Unknwon** [comment]
It can speed up the fix progress if you can :)

**Comment by siddontang** [comment]
How about the newest one?

Can it work?

**Comment by Unknwon** [comment]
All passed!

**Comment by siddontang** [comment]
Cool

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
