### PR TITLE
[hotfix]: cherry-pick 33946, 34538 and 35367 to v5.2.4

### PR DESCRIPTION
**Pull request by zimulala**
cherry-pick https://github.com/pingcap/tidb/pull/33946, https://github.com/pingcap/tidb/pull/34538 and https://github.com/pingcap/tidb/pull/35367 to v5.2.4

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the panic issue when joining information_schema.columns.
```

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @tangenta @crazycs520 @tiancaiamao

**Review by tangenta — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]

**Pull request merged**
