### PR TITLE
[DNM]Tiny clean up check index exists.

### PR DESCRIPTION
**Pull request by qiuyesuifeng**
@siddontang

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by siddontang** [comment]
@shenli , This pr depends on https://github.com/pingcap/tidb/pull/481, so it is not ok now.

**Comment by qiuyesuifeng** [comment]
@siddontang  PTAL

**Comment by siddontang** [comment]
please resolve the conflict. :-)

**Pull request closed without merging**
