### PR TITLE
expression: fix err code in Regexp()/RegexpBinary()

### PR DESCRIPTION
**Pull request by bb7133**
## What have you changed? (mandatory)
Fix the code of error caused by invalid regexp pattern in Regexp()/RegexpBinary(), for example:

```
(TiDB before this PR)
mysql> select 'a' rlike '(*';
ERROR 1105 (HY000): error parsing regexp: missing argument to repetition operator: `*`
```

```
(TiDB in this PR)
mysql> select 'a' rlike '(*';
ERROR 1139 (42000): Got error 'error parsing regexp: missing argument to repetition operator: `' from regexp

```
```
(MySQL 5.7)
mysql> select 'a' rlike '(*';
ERROR 1139 (42000): Got error 'repetition-operator operand invalid' from regexp
```

## What are the type of the changes (mandatory)?
Bug fix

## How has this PR been tested (mandatory)?
Added some more test cases

## Refer to a related PR or issue link (optional)
[TiKV PR 3196](https://github.com/pingcap/tikv/pull/3196)

### CODE REVIEW

**Comment by bb7133** [comment]
BTW, the current regexp error msg truncation length is 64(https://github.com/pingcap/tidb/blob/5445ced722cc06dda108e26830fcceaa30a0300b/mysql/errname.go#L157), looks it is not long enough for the msg of 'regexp' package, for example:

`regexp.Compile("(*") `gives the msg:
`error parsing regexp: missing argument to repetition operator: `*``
after 64 bytes truncation:
`error parsing regexp: missing argument to repetition operator: ``

IMHO it's better to enlarge the truncation length

**Comment by shenli** [comment]
Thanks! @bb7133

**Comment by shenli** [comment]
@bb7133 I think it is OK to enlarge the length of ErrRegexp message.

**Pull request merged**
