### PR TITLE
disttask: refactor dispatcher so we have chance to add init logics per task type

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: ref #46258

Problem Summary:

### What is changed and how it works?

- rename existing `Dispatcher` to `Extension` to reflect what it does, this extension must be created together with below `Dispatcher`. no need to be registered
- add new `Dispatcher` interface, make it one type per `task type`, and must registered. in this way, each `task type` can have chance to add different init logics.
- for unknown task type, fail it before start dispatcher

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Comment by D3Hunter** [comment]
@ywqzzy

**Review by ywqzzy — APPROVED** [review]

**Pull request merged**
