### PR TITLE
[WIP]util/log: use logrus to replace ngaut/log

### PR DESCRIPTION
**Pull request by andelf**
- add `--log-format` command line arguments
- replace ngaut/log
- [ ] fix systimemon
- [x] vendor update
- [ ] put sql into a separate field (next PR)

### CODE REVIEW

**Comment by andelf** [comment]
Should ngaut/systimemon be moved to sth. like `github.com/pingcap/pkg/systimemon` ?

**Comment by zimulala** [comment]
Please fix CI. @andelf

**Comment by zimulala** [comment]
Why to change the log?

**Comment by siddontang** [comment]
Use JSON format for ELK later @zimulala

**Comment by zimulala** [comment]
I got it. @siddontang

**Comment by andelf** [comment]
Close. will rewrite latter.

**Pull request closed without merging**
