### PR TITLE
planner, server: fix execute statements twice after prepare a statement

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve? 
When we run the sysbench's oltp_point_select tests, some connections panic. the stack as follows:
 ```
invalid memory address or nil pointer dereference\""] [stack="goroutine 42350688 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x24b6b80, 0xc0038f8330, 0xc002492300)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:598 +0xee
panic(0x1f9b5c0, 0x33b29c0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb/planner/core.(*BlockHintProcessor).MaxSelectStmtOffset(...)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/planner/core/hints.go:40
github.com/pingcap/tidb/planner/core.NewPlanBuilder(0x24fa600, 0xc002d8a300, 0x24d6dc0, 0xc0042893b0, 0x0, 0xcbb0ad)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/planner/core/planbuilder.go:312 +0x44
github.com/pingcap/tidb/planner.OptimizeExecStmt(0x24b6b80, 0xc0038f8330, 0x24fa600, 0xc002d8a300, 0xc0011d1950, 0x24d6dc0, 0xc0042893b0, 0xc001293ef0, 0x37f5980, 0x24d6dc0, ...)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/planner/optimize.go:230 +0x5c
github.com/pingcap/tidb/session.(*session).CachedPlanExec(0xc002d8a300, 0x24b6b80, 0xc0038f8330, 0xc000000013, 0xc003fecca0, 0xc0018734c0, 0x1, 0x1, 0x203000, 0x203000, ...)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/session.go:1189 +0x185
github.com/pingcap/tidb/session.(*session).ExecutePreparedStmt(0xc002d8a300, 0x24b6b80, 0xc0038f8330, 0xc000000013, 0xc0018734c0, 0x1, 0x1, 0x18, 0xc00450d3f0, 0x1d08ba4, ...)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/session.go:1274 +0x335
github.com/pingcap/tidb/server.(*TiDBStatement).Execute(0xc003c87490, 0x24b6b80, 0xc0038f8330, 0xc0018734c0, 0x1, 0x1, 0x1, 0xc003b9ec6a, 0x1, 0xa)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/driver_tidb.go:75 +0x85
...
```

### What is changed and how it works?
Use `&plannercore.BlockHintProcessor{}` instead of nil.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @XuHuaiyu @cfzjywxk

**Comment by cfzjywxk** [comment]
the nil value is used by design,  this has been fixed in #12482 and #12486 commit

**Pull request closed without merging**
