### PR TITLE
planner/core: remove unstable test

### PR DESCRIPTION
**Pull request by hanfei1991**
### What problem does this PR solve?

Problem Summary:

This test is for broadcast join in v4.x.x, which is not used any more. The test is unstable so we'd better to remote it.

### What is changed and how it works?

remote test

### Check List 

Tests 

- Unit test

### Release note 

- planner/core: remove unstable test

### CODE REVIEW

**Review by fzhedu — APPROVED** [review]
/LGTM

**Comment by bb7133** [comment]
@hanfei1991 Do we need to cherry-pick it?

**Review by bb7133 — APPROVED** [review]

**Comment by tisonkun** [comment]
> more

@hanfei1991 will bcj be removed later? If so, is there a plan?

**Pull request merged**
