### PR TITLE
tidb-server: make max-procs in config file take ef ... (#17706)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #17706 to release-4.0

---

### What problem does this PR solve?

Problem Summary:
 In case the user wants to change this value under cgroups, the `maxprocs.Set` will overwrite the user's settings in the config file.

### What is changed and how it works?
Call `runtime.GOMAXPROCS(int(cfg.Performance.MaxProcs))` after `maxprocs.Set`.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Release note 
* make max-procs in config file take effect under cgroups

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
@bobotu please resolve conflicts

**Comment by bobotu** [comment]
PTAL @zz-jason

**Review by tennix — APPROVED** [review]
LGTM

**Review by zz-jason — APPROVED** [review]

**Pull request merged**
