### PR TITLE
expression: support ConstItem() for expression (#10004)

### PR DESCRIPTION
**Pull request by lysu**
cherry-pick #10004 to 2.1

it needed by bugfix cherry-pick for #10064

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/10381)

### CODE REVIEW

**Comment by lysu** [comment]
/run-all-test tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by jackysp** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by lysu** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by lysu** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Pull request merged**
