### PR TITLE
*: remove gitcookie.sh

### LINKED ISSUE #25772: Remove unused gitcookie.sh
## Development Task

gitcookie.sh is introduced by 0573c47a18c70f98f59f4549c6df3009f3a5ca7f  and move to travis config at 6a80a69a4cf5e707efdedec98bd38c17482bcb15

Given we are using Jenkins for ci now this file is outdated and should be removed.

cc @zhouqiang-cl @coocood

### PR DESCRIPTION
**Pull request by tisonkun**
gitcookie.sh is introduced by 0573c47a18c70f98f59f4549c6df3009f3a5ca7f and move to travis config at 6a80a69a4cf5e707efdedec98bd38c17482bcb15

Given we are using Jenkins for ci this file is outdated and should be removed.

Signed-off-by: tison <wander4096@gmail.com>

### What problem does this PR solve?

Issue Number: close #25772

### Release note

- No release note

### CODE REVIEW

**Review by coocood — APPROVED** [review]

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
@coocood @zhouqiang-cl would you mind to help on the merging phase?

**Pull request merged**
