### PR TITLE
planner: set enumsetasint if original value is int in point get

### LINKED ISSUE #56832: Wrong ENUM value is updated to and seems it's mixed up with ENUM index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table t (id int primary key, c enum('0', '1', '2'));
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t values (0,'0'), (1,'1'), (2,'2');
Query OK, 3 rows affected (0.01 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> update t set c = 2 where id = 0;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from t;
+----+------+
| id | c    |
+----+------+
|  0 | 1    |
|  1 | 1    |
|  2 | 2    |
+----+------+
3 rows in set (0.00 sec)

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.27    |
+-----------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)

as above

### 3. What did you see instead (Required)

```
mysql> create table t (id int primary key, c enum('0', '1', '2'));
Query OK, 0 rows affected (0.04 sec)

mysql> insert into t values (0,'0'), (1,'1'), (2,'2');
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> update t set c = 2 where id = 0;
Query OK, 1 row affected (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from t;
+----+------+
| id | c    |
+----+------+
|  0 | 2    |
|  1 | 1    |
|  2 | 2    |
+----+------+
3 rows in set (0.01 sec)

mysql> select version();
+-----------------------------------------+
| version()                               |
+-----------------------------------------+
| 8.0.11-TiDB-v8.4.0-alpha-25-gb02581a7a4 |
+-----------------------------------------+
1 row in set (0.01 sec)
```

in the last SELECT, the first row is different from MySQL

### 4. What is your TiDB version? (Required)

```
Release Version: v8.4.0-alpha-25-gb02581a7a4
Edition: Community
Git Commit Hash: b02581a7a47e98b49901c025767d175ee63fbf23
Git Branch: HEAD
UTC Build Time: 2024-08-23 03:07:52
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #56832

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]
LGTM, but still have a minor bug

```
mysql> update t set c = 0 where id = 0;
ERROR 1265 (01000): Data truncated for column '%s' at row %d

mysql> update t set c = -1 where id = 0;
ERROR 1406 (22001): Data Too Long, field len 1, data len 2
```

The error msg is not same as MySQL.

**Review by AilinKid — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]
LGTMeow

**Pull request merged**
