### PR TITLE
expression: fix issue that function `dayname` is incompatible with Mysql when doing arithmetic(#9975)

### PR DESCRIPTION
**Pull request by qw4990**
cherry-pick for #9975

### CODE REVIEW

**Comment by qw4990** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
@qw4990 Please resolve conflicts

**Comment by qw4990** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by qw4990** [comment]
@zz-jason fixed.

**Pull request merged**
