### PR TITLE
planner: support explain analyze for mpp task with union (#24898)

### PR DESCRIPTION
**Pull request by hanfei1991**
### What problem does this PR solve?

Problem Summary: After supporting union-all, the explain analyze of mpp with union-all will not work. Due to the copying and elimination of plans around union all, the number of explain plans don't match the number of actual running plans.

### What is changed and how it works?
What's Changed:
break the check of equal plan numbers.
How it Works:

### Check List 

Tests 

### Release note 

- planner: support explain analyze for mpp task with union

### CODE REVIEW

**Review by eurekaka — COMMENTED** [review]
LGTM. BTW, please add a test case.

**Comment by hanfei1991** [comment]
@eurekaka Thanks for reviewing! There is not a explain analyze test for tiflash/mpp yet. 'cause the mock engine doesn't support returning a summary. We have added some in TiFlash integration tests. We will add them to TiDB in the near future!

**Review by lzmhhh123 — APPROVED** [review]

**Review by eurekaka — APPROVED** [review]

**Pull request merged**
