### PR TITLE
tests: fix unstable test in resource group

### LINKED ISSUE #44883: unstable test TestResourceGroupRunaway
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
 [2023/06/21 18:38:34.445 +08:00] [INFO] [db.go:625] ["Waiting for closer"]
--- FAIL: TestResourceGroupRunaway (31.28s)
    resource_group_test.go:255: 
        	Error Trace:	ddl/tests/resourcegroup/resource_group_test.go:255
        	Error:      	"[[rg1 select /*+ resource_group(rg1) */ * from t 2023-06-21 18:38:31]]" should have 0 item(s), but has 1
        	Test:       	TestResourceGroupRunaway
FAIL
```

### PR DESCRIPTION
**Pull request by CabinfeverB**
### What problem does this PR solve?

Issue Number: close #44883

Problem Summary:

### What is changed and how it works?
introduce EventuallyMustQueryAndCheck into `TestKit` to assert query eventually

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by CabinfeverB** [comment]
cc @hawkingrei @glorv

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
