### PR TITLE
*: update PD client

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Update PD client to take some fixes and optimizations: tikv/pd#3413, tikv/pd#3430, tikv/pd#3432

### What is changed and how it works?

Update PD client and related dependencies in `go.mod`.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note.

### CODE REVIEW

**Review by Yisaer — COMMENTED** [review]
/lgtm

**Review by Yisaer — COMMENTED** [review]
LGTM

**Review by Yisaer — APPROVED** [review]
LGTM

**Review by nolouch — APPROVED** [review]

**Pull request merged**
