### PR TITLE
br/tools: use curl tool to download golangci-lint

### LINKED ISSUE #28802: Use curl tool to download golangci-lint in br
## Enhancement

In `br/tools/Makefile`, we use `go build` to build a golangci-lint which uses GPL-3.0 license. This may cause license risk. So the better way to get golangci-lint is to download it using `curl` tool, just like `tidb/Makefile`.

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #28802 

Problem Summary: use curl tool to download golangci-lint

### Release note 

```release-note
use curl tool to download golangci-lint
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @bb7133 
PTAL

**Comment by kennytm** [comment]
@Defined2014 it was used in a `/br/Makefile` when initially migrated here, but then the code are gradually being merged.

**Pull request merged**
