### PR TITLE
expression, executor, plan: rewrite builtin function ceil

### PR DESCRIPTION
**Pull request by 0x04C2**
The functionality of `ceil` is similar to the `floor`. Please take a look. @XuHuaiyu Thanks

### CODE REVIEW

**Comment by 0x04C2** [comment]
Hi @hanfei1991 , Is there anything wrong on the CI env?
I see that the most of CI fail reason is described following

```
FAIL: varsutil_test.go:59: testVarsutilSuite.TestVarsutil
varsutil_test.go:122:
    c.Assert(v.TimeZone.String(), Equals, tt.expect)
... obtained string = "UTC"
... expected string = "Local"
```

**Comment by hanfei1991** [comment]
Yes, we are fixing this problem. Please wait a minute :)

**Comment by 0x04C2** [comment]
Cool. Thank you for replying shortly

**Comment by XuHuaiyu** [comment]
`ceiling` is an alias of `ceil`(expression/ builtin.go: 580)
please add some test cases for it.

**Comment by shenli** [comment]
@0x04C2 CI is fixed.

**Comment by 0x04C2** [comment]
@shenli Thank you!

**Comment by 0x04C2** [comment]
@XuHuaiyu I have added cases for the ceiling. PTAL

**Comment by XuHuaiyu** [comment]
LGTM 
PTAL @zz-jason

**Pull request merged**
