### PR TITLE
plan: fix the value of attribute correlated of HashAgg

### PR DESCRIPTION
**Pull request by winoros**
Currently the value of HashAgg's attribute `correlated` doesn't consider the effect of its child node, which will make the Cache plan added to the wrong position

PTAL @hanfei1991 @coocood @XuHuaiyu @shenli @zimulala

### CODE REVIEW

**Comment by hanfei1991** [comment]
Add some tests plz.

**Comment by hanfei1991** [comment]
I think the test should be added to executor_test.go

**Comment by hanfei1991** [comment]
LGTM

**Comment by coocood** [comment]
Why logical `Aggregation` plan `IsCorrelated` is not correct?

**Comment by hanfei1991** [comment]
Because agg push down didn't consider if its child is correlated @coocood

**Comment by shenli** [comment]
LGTM

**Pull request merged**
