### PR TITLE
infoschema: fix the bug that the metric of hot region will be same

### PR DESCRIPTION
**Pull request by HunDunDM**
Signed-off-by: Zheng Xiangsheng <hundundm@gmail.com>

### What problem does this PR solve?

Problem Summary:

```
MySQL [(none)]> SELECT * FROM INFORMATION_SCHEMA.TIDB_HOT_REGIONS;
+----------+----------+---------------+------------------+------------+-----------+-------+----------------+--------------+------------+
| TABLE_ID | INDEX_ID | DB_NAME       | TABLE_NAME       | INDEX_NAME | REGION_ID | TYPE  | MAX_HOT_DEGREE | REGION_COUNT | FLOW_BYTES |
+----------+----------+---------------+------------------+------------+-----------+-------+----------------+--------------+------------+
|       57 |     NULL | btest         | btest10          | NULL       |  21166161 | read  |            235 |            0 |      23637 |
|       75 |     NULL | btest         | btest2           | NULL       |  21164290 | read  |            235 |            0 |      23637 |
|       64 |     NULL | btest         | btest3           | NULL       |      1622 | read  |            235 |            0 |      23637 |
|       71 |     NULL | btest         | btest8           | NULL       |  21164357 | read  |            235 |            0 |      23637 |
|       66 |     NULL | btest         | btest7           | NULL       |      1731 | read  |            235 |            0 |      23637 |
...
|       71 |     NULL | btest         | btest8           | NULL       |  21156334 | write |           1140 |            0 |     122823 |
|       84 |     NULL | btest         | btest9           | NULL       |  21166277 | write |           1140 |            0 |     122823 |
|       68 |     NULL | btest         | btest14          | NULL       |  21170223 | write |           1140 |            0 |     122823 |
|       81 |     NULL | btest         | btest11          | NULL       |  21166145 | write |           1140 |            0 |     122823 |
|       75 |     NULL | btest         | btest2           | NULL       |  21169517 | write |           1140 |            0 |     122823 |
...
+----------+----------+---------------+------------------+------------+-----------+-------+----------------+--------------+------------+
```

### What is changed and how it works?

What's Changed:

How it Works:

* fix the bug that they point to the same pointer

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
  - `SELECT * FROM INFORMATION_SCHEMA.TIDB_HOT_REGIONS;`

### Release note 

- fix the bug that the metric of hot region will be same

### CODE REVIEW

**Comment by rleungx** [comment]
Related to https://github.com/pingcap/tidb/issues/21260

**Review by Yisaer — COMMENTED** [review]
LGTM

**Review by disksing — APPROVED** [review]

**Comment by HunDunDM** [comment]
duplicate #21278

**Pull request closed without merging**
