### PR TITLE
*: add server ip in connection info

### LINKED ISSUE #38493: Add a new framework to extend tidb's function outside the repo
## Feature Request

- [x] #38496
- [x] #38566
- [x] #38588
- [x] #38623
- [x] #38693
- [x] #38707
- [x] #38723
- [x] #38752
- [x] #38788
- [x] #38962
- [x] #39049
- [x] https://github.com/pingcap/tidb/pull/39086

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #38493

### What is changed and how it works?

Add server ip into `ConnectionInfo`

### Check List

Tests 

- [x] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by bb7133** [comment]
Could you add some test cases for this PR?

**Comment by lcwangchao** [comment]
> Could you add some test cases for this PR?

I just added some lines in a test case. But it may cause a conflict when another PR merged. I'll handle it at that time

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
