### PR TITLE
check if the current master could pass the CI.

### PR DESCRIPTION
**Pull request by ciscoxll**
This PR #7248 has not run all tests. because CI server is down.
So use this PR check if the current master could pass the CI.

### CODE REVIEW

**Comment by ciscoxll** [comment]
@jackysp Please check the `jenkins -ci-tidb/unit-test` error.

**Comment by ciscoxll** [comment]
@tiancaiamao Please help to see.

**Comment by jackysp** [comment]
The reason for the failure is the test reached the time limit (10 min).
It could be
1. some DDLs went into an endless loop;
2. our tests run tool slowly.

**Comment by jackysp** [comment]
Can not find any panics and other failures in the log files. Try to rerun it.
/run-unit-test

**Comment by jackysp** [comment]
Can not find any panics and other failures in the log files. Try to rerun it.
/run-unit-test

**Comment by jackysp** [comment]
Seems it goes well. I think our tests run too slow. Maybe we could add the timeout of `make race`.

**Comment by ciscoxll** [comment]
@shenli `run-all-tests` all through.

**Comment by shenli** [comment]
@ciscoxll Got it! Thanks!

**Pull request closed without merging**
