### PR TITLE
cherry-pick: replace gofail with the new failpoint implementation

### PR DESCRIPTION
**Pull request by lonng**
…0184)

Signed-off-by: Lonng <chris@lonng.org>

### What problem does this PR solve? 

Cherry-pick: #10184

### CODE REVIEW

**Comment by lonng** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by lonng** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by lonng** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by lonng** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by lonng** [comment]
@winkyao @lonng @tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
