### PR TITLE
tests: make TestIssue20658 stable

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/25012, https://github.com/pingcap/tidb/issues/21263 again =_=

Problem Summary:

The problematic test code:
```go
tk.MustQuery(sql).Sort().Rows()
```

`Sort()` method of `testkit.Result` is not suitable to sort the floating numbers, especially in the **approximate equivalence test**. For example, the following 2 result set should be approximately equal.

```
92.24
920.0000000000001
```
```
92.24
919.9999999999999
```

However, after sorting in the alphabetical order, the second result set becomes:

```
919.9999999999999
92.24
```

Finally, the line-by-line comparison test failed.

### What is changed and how it works?

What's Changed: Do the sort after parsing into floating numbers.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

NA

### Release note 

- No release note

### CODE REVIEW

**Review by JinLingChristopher — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]

**Review by xiongjiwei — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

**Comment by hi-rustin** [comment]
@ti-chi-bot update

**Comment by hi-rustin** [comment]
@ti-chi-bot update

**Comment by hi-rustin** [comment]
@ti-chi-bot update

**Pull request merged**
