### PR TITLE
Revert "*: Remove useless code and use the DAG mode in tests (#3069)"

### PR DESCRIPTION
**Pull request by hanfei1991**
This reverts commit d8c52e8ac9325df750c2f985fe5f743e840d3938.

We revert it because we will use offset to fill column's data. It is not compatible with old planner.

### CODE REVIEW

**Comment by coocood** [comment]
Can you explain this in more detail?
Why revert it now but not before?

**Comment by hanfei1991** [comment]
In old planner, we pass column ID to kv layer. But we are planning to pass column index for kv layer in new planner after resolving index again. It's not compitable.

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
