### PR TITLE
Improve CONTRIBUTING.md documentation.

### PR DESCRIPTION
**Pull request by ladrift**
1. Fix a header level mistake.
2. Capitalize the first character.

### CODE REVIEW

**Comment by shenli** [comment]
LGTM
@ladrift Thanks!

**Comment by ladrift** [comment]
Well, why this PR is still not merged? Is that approval take effect? @shenli

**Comment by shenli** [comment]
We need at least two LGTMs for each PR.

@coocood PTAL

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
