### PR TITLE
Change from glide to dep

### PR DESCRIPTION
**Pull request by zhexuany**
Not sure which version should I add to `Gopkg.toml`. Please comment in this PR, so I can change it later. Now `dep` supports `prune` operation which allow use prune test files and non-go files. In future, this could be absorbed into `ensure` operation. But this is still in progress. As for now, we have to run `dep prune` after `dep ensure`.

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/5355)

### CODE REVIEW

**Comment by zhexuany** [comment]
Before:
If we run `find _vendor/ -type f | wc -l`, only 799 files are vended. 
After:
If we run `find vendor -type f | wc -l`, 1555 files are vended. 

Not sure is it worth to change to `dep`.

**Comment by zhexuany** [comment]
just come up with a script call `clean_vendor.sh` in directory `hack`. We can execute it and delete all irrelevant files. By do this, only 800 files in vendor.

**Comment by coocood** [comment]
@zhexuany 
What's the difference between manual delete tests file and `[prune]` in `gopkg.toml`?

**Comment by zhexuany** [comment]
`dep prune` only delete some `*_test.go` but not all of them. 
Here is the guide for reproducing:
1. run `dep ensure`
2. `find vendor/ -name "*_test.go" | wc -l` gives us 851. 
3. run `dep prune`
4. `find vendor/ -name "*_test.go" | wc -l` gives us 374. 

The number means how many `*_test.go` is still in vendor.

**Comment by coocood** [comment]
@zhexuany 
Can you find the reason why those test files are not deleted?

**Comment by zhexuany** [comment]
@coocood 

Check this issue https://github.com/golang/dep/issues/944 
It is on progress. `dep prune` should have full functionality after closing this issue. `dep` team is currently working on this.

**Comment by coocood** [comment]
@zhexuany 
The assembly files should not be deleted.
So I think manually delete files is not safe.

**Comment by zhexuany** [comment]
@coocood 
agreed. 
Maybe can change it to just delete certain files like `*_test.go` and `.gitignore` and etc.

**Pull request closed without merging**
