### PR TITLE
ddl: speed up the execution time of `TestBackwardCompatibility`.

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: #24459

### What is changed and how it works?

What's Changed:
When the test here wants to execute "add index", the number of ranges in the table is greater than the number of index workers. Here the index worker is 4, so the number of ranges is set to 10.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

| branch | `go test -check.f TestBackwardCompatibility`  |  go test ddl package with race(`go test -v -vet=off -p 5 -timeout 20m -race`)   |     `TestBackwardCompatibility` execution time in running ddl package test with race |
----------------------------------------------------------- |----------- |----------- |----------- |
 |   before this PR(2ca98e393cb6873727a177cb5c974fa8d3ca61c5)  |      56s      |       566s |  79s  | 
 |   after this PR |      7s      |       505s | 14s  | 

### Release note 

- `No release note`.

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @AilinKid @tangenta @XuHuaiyu

**Review by AilinKid — COMMENTED** [review]
/lgtm

**Comment by wjhuang2016** [comment]
Should we cherrypick it?

**Pull request merged**
