### PR TITLE
server: add tiflash fallback testcase

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Related PR: #22459, #23103, #23226

### What is changed and how it works?

What's Changed:

Add TiFlash fallback testcase for simple TiFlash query (unary + non-streaming).

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- add TiFlash fallback testcase

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Review by hanfei1991 — APPROVED** [review]
/LGTM

**Pull request merged**
