### PR TITLE
planner: check convert outer join to inner join if prepare stmt meet prepared plan cache is enable

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/22167

Problem Summary:

### What is changed and how it works?

please refer https://github.com/pingcap/tidb/issues/22167#issuecomment-754360727

### Check List 

Tests 

- Unit test

### Release note 

- fix a bug that may get the wrong result when using `prepared plan cache` in join stmt

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
LGTM

**Comment by qw4990** [comment]
/cc rebelice
PTAL @eurekaka @rebelice

**Review by eurekaka — COMMENTED** [review]
I remember @xuyifangreeneyes is working on another solution for this problem, i.e, keep applying this optimization but do not put it into plan cache.

**Comment by xuyifangreeneyes** [comment]
> I remember @xuyifangreeneyes is working on another solution for this problem, i.e, keep applying this optimization but do not put it into plan cache.

Yes, but I haven't written PR. Besides, `EvaluateExprWithNull` is involved in other two optimization where similar bug may also exist.

**Comment by xiongjiwei** [comment]
sure, I closed this PR, @xuyifangreeneyes working on this

**Pull request closed without merging**
