### PR TITLE
store/copr: fix tiflash integration test by disable paging on tiflash

### LINKED ISSUE #35673: handle paging compatibility for tiflash
## Enhancement

https://github.com/pingcap/tidb/pull/35275 breaks the tiflash integration test.

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #35673

Problem Summary:

### What is changed and how it works?

~~If the storage engine doesn't support paging, they may send the whole region data.
Then we can still use the old way to handle the response.~~

~~TiFlash doesn't support coprocessor paging, disable it on tiflash.
Most of the query should go to `sendBatchCop()` code path.~~

### Check List

Tests 

- [ ] Unit test
- [X] Integration test

- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wshwsh12 — APPROVED** [review]
LGTM

**Comment by tiancaiamao** [comment]
Just disable tiflash can't fix mocktikv
Some of the CI pipeline and also DM are still relying on mocktikv
So choose the other way to fix.

@wshwsh12 @XuHuaiyu

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
