### PR TITLE
br: Remove statement from closure to prevent concurrent operation during backup system table (#29730)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #29730 to release-5.2
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/29976
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/29976:release-5.2-bc10104e05b0
```

---

Signed-off-by: joccau <zak.zhao@pingcap.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/29710

Problem Summary:
Append the prefix `__TiDB_BR_Temporary_` into system database `mysql` multiply.
It causes restore failed because of incorrect schema name

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Backup system table before fix
`
[2021/11/12 14:30:15.438 +08:00] [INFO] [validate.go:78] ["checksum success"] [db=__TiDB_BR_Temporary___TiDB_BR_Temporary___TiDB_BR_Temporary_mysql] [table=person]
`

Backup  and restore system table after fix 
`
[2021/11/12 15:54:00.890 +08:00] [INFO] [validate.go:78] ["checksum success"] [db=__TiDB_BR_Temporary_mysql] [table=person]
`

`
[2021/11/12 16:12:22.328 +08:00] [INFO] [ddl.go:553] ["[ddl] start DDL job"] [job="ID:168, Type:rename table, State:none, SchemaState:queueing, SchemaID:3, TableID:123, RowCount:0, ArgLen:3, start time: 2021-11-12 16:12:22.229 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"] [query="RENAME TABLE `__tidb_br_temporary_mysql`.`person` TO `mysql`.`person`;"]
`

### Release note

```release-note
None
```

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Review by fengou1 — APPROVED** [review]
it look we fixed schema.dbInfo.Name be updated by the concurrent coroutines.

**Review by 3pointer — APPROVED** [review]

**Comment by VelocityLight** [comment]
This pull request is closed because it's related version has closed automatic cherry-picking.
If it's still needed, you can reopen it or just regenerate it using bot,
see:
- https://prow.tidb.io/command-help#cherrypick
- https://book.prow.tidb.net/#/plugins/cherrypicker

You can find more details at:
- https://internals.tidb.io/t/topic/785

**Pull request closed without merging**
