### PR TITLE
metrics: enlarge upper limits of some duration metrics

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve?

Issue Number: 
close https://github.com/pingcap/tidb/issues/17450

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
* No release note

### CODE REVIEW

**Comment by jackysp** [comment]
PTAL @lysu @coocood

**Comment by coocood** [comment]
LGTM

**Pull request merged**
