### PR TITLE
*: fix the date race in `TestCharsetFeature`

### PR DESCRIPTION
**Pull request by xiongjiwei**
- close https://github.com/pingcap/tidb/issues/27476
- close https://github.com/pingcap/tidb/issues/27474
- close https://github.com/pingcap/tidb/issues/27485

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by zimulala — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Review by zimulala — APPROVED** [review]

**Comment by tisonkun** [comment]
@zimulala @xhebox @bb7133 I think one of you should comment `/merge` for merging this ifx.

**Pull request merged**
