### PR TITLE
server: Mute HTTP handler logs (#15015)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #15015 to release-3.0

---

Signed-off-by: Breezewish <me@breeswish.org>

### What problem does this PR solve? 

Resolve the issue that TiDB prints too much logs when use with Dashboard.

### What is changed and how it works?

Remove logs in HTTP handlers, since Dashboard requests TiDB HTTP API frequently.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

### Release note 

- Mute HTTP handler logs

### CODE REVIEW

**Review by zimulala — COMMENTED** [review]
LGTM

**Comment by zz-jason** [comment]
@breeswish please add a release note.

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by zz-jason — APPROVED** [review]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Pull request merged**
