### PR TITLE
config: typo fix for `distinct-agg-push-down`

### LINKED ISSUE #24001: distinct-agg-push-down is in config.toml.example but can't be found in @@tidb_config in 5.0.0
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Whether support pushing down aggregation with distinct to cop task
distinct-agg-push-down = false

### 2. What did you expect to see? (Required)
can be found in select @@tidb_config

### 3. What did you see instead (Required)
can't be found

### 4. What is your TiDB version? (Required)
v5.0.0

### PR DESCRIPTION
**Pull request by b41sh**
### What problem does this PR solve?

Issue Number: close #24001 

Problem Summary:

### What is changed and how it works?

What's Changed: config `distinct-agg-push-down` typo fix

### Check List 

Tests 

- No code

### Release note 

- No release note

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
LGTM

**Comment by XuHuaiyu** [comment]
Need test case.

**Comment by xhebox** [comment]
Introduced here, https://github.com/pingcap/tidb/commit/c28a69583e81e6eeb206f1478c3641f1ae5fb1a3. So we need to cherry-pick back to 5.0 and 5.0-rc, I think. @b41sh

**Comment by b41sh** [comment]
> Need test case.

I add some test, PTAL @XuHuaiyu

**Comment by b41sh** [comment]
> Introduced here, [c28a695](https://github.com/pingcap/tidb/commit/c28a69583e81e6eeb206f1478c3641f1ae5fb1a3). So we need to cherry-pick back to 5.0 and 5.0-rc, I think. @b41sh

ok

**Pull request merged**
