### PR TITLE
executor, types: fix bug of insert into unsigned float/double (#6939)

### PR DESCRIPTION
**Pull request by XuHuaiyu**
cherry-pick https://github.com/pingcap/tidb/pull/6939

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
PTAL @zz-jason @winoros

**Comment by XuHuaiyu** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by coocood** [comment]
WARNING: DATA RACE
Read at 0x00c42013cfb8 by goroutine 45:
  github.com/pingcap/tidb/domain.(*Domain).LoadPrivilegeLoop.func1()
      /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/domain/domain.go:562 +0x1f6

**Comment by shenli** [comment]
@tiancaiamao Is the data race issue fixed in master?

**Comment by tiancaiamao** [comment]
I'm not sure, the CI log is gone. @shenli @coocood

**Comment by XuHuaiyu** [comment]
/run-unit-test tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by coocood** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
PTAL @zz-jason

**Pull request merged**
