### PR TITLE
ddl: update parser to make TiDB treat charset and collate case insensitive

### LINKED ISSUE #8304: Character set name is case sensitive in TiDB
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I use  mydumper from version 1. 0 dumper to version 2. 0. 8.for example, character sets are case-sensitive.

2. What did you expect to see?
I can loader to 2.0.8

3. What did you see instead?
dumper sql:
create table test
(id int)
ENGINE=InnoDB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN;

Can't recognize UTF8, if I change to utf8, it can be created

Is there a parameter that can be controlled case-sensitive

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
1.0.8 to 2.0.8

### PR DESCRIPTION
**Pull request by winkyao**
### What problem does this PR solve? 

Fix #8304 

### What is changed and how it works?

Actually, https://github.com/pingcap/parser/pull/66 fix this problem, we just add some test cases and update the go.mod to the corresponding parser will work.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8577)

### CODE REVIEW

**Comment by winkyao** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
@zimulala  release-2.1 is not using master branch parser

**Comment by winkyao** [comment]
@zimulala The changes in parser need to cherry-pick to 2.1 branches later. Never mind.

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
