### PR TITLE
planner/core: fix Wrong behavior of prepare && execute

### PR DESCRIPTION
**Pull request by hhxcc**
cherry-pick #9204

### CODE REVIEW

**Comment by hhxcc** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by eurekaka** [comment]
@hhxcc please fix the CI, seems it is caused by that fact that UT uses some variables which do not exist in 2.1 branch.

**Comment by hhxcc** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by hhxcc** [comment]
@eurekaka ok, done.

**Comment by eurekaka** [comment]
/run-integration-ddl-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
