### PR TITLE
br: support checkSum during restore dml kv-events.

### PR DESCRIPTION
**Pull request by joccau**
Signed-off-by: joccau <zak.zhao@pingcap.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/33400

Problem Summary:
- Support checkSum in file level when stream restore DML kv-events.
- 
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [x] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]
BTW, shall we calculate the SHA256 of meta files while downloading them too?

**Comment by joccau** [comment]
> BTW, shall we calculate the SHA256 of meta files while downloading them too?

If do this,  the interface readFile(ExternStorage API) should support `sheckSum`, because `br` read metalog directly.

**Comment by YuJuncen** [comment]
> > BTW, shall we calculate the SHA256 of meta files while downloading them too?
> 
> If do this, the interface readFile(ExternStorage API) should support `sheckSum`, because `br` read metalog directly.

Why not just do the sha256 checksumming during reading the file?

**Pull request merged**
