### PR TITLE
ddl: fix create partition table not suport bit and year column type

### PR DESCRIPTION
**Pull request by crazycs520**
## What have you changed? (mandatory)
TiDB
```SQL
mysql:test> create TABLE t20 (c1 int,c2 bit(10)) partition by range(c2) (partition p0 values less than (10));
(1105, "Field '`c2`' is of a not allowed type for this type of partitioning")
mysql:test> create TABLE t21 (c1 int,c2 year) partition by range( c2 ) (partition p0 values less than (2000));
(1105, "Field '`c2`' is of a not allowed type for this type of partitioning")
```
MySQL 
```SQL
mysql:test> create TABLE t20 (c1 int,c2 bit(10)) partition by range(c2) (partition p0 values less than (10));
Query OK, 0 rows affected
Time: 0.014s
mysql:test> create TABLE t21 (c1 int,c2 year) partition by range( c2 ) (partition p0 values less than (2000));
Query OK, 0 rows affected
Time: 0.014s
```

## What is the type of the changes? (mandatory)

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)

Unit Test

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No
## Does this PR need to be added to the release notes? (mandatory)
No

### CODE REVIEW

**Comment by crazycs520** [comment]
@ciscoxll @winkyao @zimulala PTAL

**Comment by winkyao** [comment]
@ciscoxll PTAL

**Pull request merged**
