### PR TITLE
executor, infoschema: fix display of default CURRENT_TIMESTAMP with decimal (#11070)

### PR DESCRIPTION
**Pull request by bb7133**
Cherry-pick https://github.com/pingcap/tidb/pull/11070

### CODE REVIEW

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by winkyao** [comment]
/run-integration-ddl-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zimulala** [comment]
/run-integration-ddl-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
/run-integration-ddl-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
