### PR TITLE
sessionctx/variable: add tests to ensure skipInit can be removed

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/35051

Problem Summary:

The skipInit feature is left over from a refactor. The problem is, the usage of it has actually increased :(

### What is changed and how it works?

This is a change to tests only to ensure no new variables are introduced with skipInit.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by xhebox** [comment]
/hold

Waiting for configuration reviewer, ping @bb7133

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
