### PR TITLE
execution : fix Compatibility between select and mysql

### LINKED ISSUE #20069: v4.0.5 - Compatibility between select and mysql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

CREATE TABLE `ttt` (
 `a` int(10) unsigned,
 `b` int(10) unsigned
);

insert into ttt values(1,10),(20,2);

select * from ttt where a-b>0 and a=20;

### 2. What did you expect to see? (Required)
Return a correct value：
mysql retrue：

mysql> select * from ttt where a-b>0 and a=20;
+----+---+
| a  | b |
+----+---+
| 20 | 2 |
+----+---+
1 row in set (0.02 sec)

### 3. What did you see instead (Required)
tidb return：
mysql> select * from ttt where a-b>0 and a=20;
1690 - BIGINT UNSIGNED value is out of range in '(1 - 10)'

### 4. What is your TiDB version? (Required)
image

## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @lzmhhh123

### PR DESCRIPTION
**Pull request by luxinle**
### What problem does this PR solve?

Issue Number: close #20069 

Problem Summary:

### What is changed and how it works?

What's Changed:
Loop all the where conditions, when check the row result.
How it Works:

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-1498-g8c418b977-dirty
Edition: Community
Git Commit Hash: 8c418b9773504ebb62db7358447ce77970c15e66
Git Branch: fixCompatibility
UTC Build Time: 2020-11-05 07:39:59
GoVersion: go1.14.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

mysql> select * from ttt where a-b>0 and a=20;
+------+------+
| a    | b    |
+------+------+
|   20 |    2 |
+------+------+
1 row in set (0.00 sec)

mysql> select * from ttt where a-b>0 and a=1;
ERROR 1690 (22003): BIGINT UNSIGNED value is out of range in '(Column#0 - Column#0)'
mysql>
```

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by luxinle** [comment]
@ti-srebot /run-all-tests

**Comment by luxinle** [comment]
@lzmhhh123 PTAL

**Comment by luxinle** [comment]
@qw4990 PTAL

**Review by lzmhhh123 — COMMENTED** [review]
@luxinle Please add some tests for this fix.

**Comment by luxinle** [comment]
When I test this sql below.
In Mysql: 8.0.15 
mysql> select * from t where a-b>0 and a=1 and b=10 and a-b>0 and a=20;
ERROR 1690 (22003): BIGINT UNSIGNED value is out of range in '(1 - 10)'
mysql>

After fix code:
In Tidb:
mysql> select * from t where a-b>0 and a=1 and b=10 and a-b>0 and a=20;
Empty set (0.00 sec)
mysql>
I think this is another tidb bug. Maybe should be fix in another code.

**Comment by luxinle** [comment]
@ti-srebot /run-all-tests

**Comment by luxinle** [comment]
@lzmhhh123 PTAL

**Comment by luxinle** [comment]
@XuHuaiyu PTAL

**Comment by wshwsh12** [comment]
I think #21061 has fixed the issue.... @luxinle  PTAL

I also have a test for your comment  https://github.com/pingcap/tidb/pull/20868#issuecomment-722994148
In mysql,  the error is created in constant propagate, not scan table:
```
MySQL [test]>  select * from ttt where a-b>0 and a = 1 and b = 9;
ERROR 1690 (22003): BIGINT UNSIGNED value is out of range in '(1 - 9)'
```
In tidb master 6cd3c6574, tidb will produce a tabledual:
```
[tidb]> select * from ttt where a-b>0 and a = 1 and b = 9;
Empty set (0.001 sec)
[tidb]> desc select * from ttt where a-b>0 and a = 1 and b = 9;
+-------------+---------+------+---------------+---------------+
| id          | estRows | task | access object | operator info |
+-------------+---------+------+---------------+---------------+
| TableDual_5 | 1.60    | root |               | rows:0        |
+-------------+---------+------+---------------+---------------+
1 row in set (0.001 sec)
```

**Comment by wshwsh12** [comment]
> I think this is another tidb bug. Maybe should be fix in another code.

I create another issue for this https://github.com/pingcap/tidb/issues/21625

**Comment by wshwsh12** [comment]
Thanks for your contribution.
I think the issue has been fixed, so I close this PR now. Feel free to re-open this PR or create another Issue/PR if you have any problem.

**Pull request closed without merging**
