### PR TITLE
expression: use maximum length for integer display

### LINKED ISSUE #45338: Incompatible behaviors on display width
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
I try to store the same value in a TINYINT column but with different display widths, TiDB returns different values.

```SQL
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (c1 TINYINT(1) NOT NULL);
INSERT INTO t1 VALUES (-127);
SELECT c1 FROM t1 WHERE CAST(IFNULL(c1, '-') AS CHAR); -- {}, wrong

DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (c1 TINYINT(2) NOT NULL);
INSERT INTO t1 VALUES (-127);
SELECT c1 FROM t1 WHERE CAST(IFNULL(c1, '-') AS CHAR); -- {-127}, right

DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (c1 TINYINT(3) NOT NULL);
INSERT INTO t1 VALUES (-127);
SELECT c1 FROM t1 WHERE CAST(IFNULL(c1, '-') AS CHAR); -- {-127}, right
```
### 2. What did you expect to see? (Required)
These three SELECTs return the same value -127.
I try the above example in MySQL, they all return -127.
### 3. What did you see instead (Required)
The first returns empty, while the other two return -127.
### 4. What is your TiDB version? (Required)

Release Version: v7.2.0
Edition: Community
Git Commit Hash: 9fd5f4a8e4f273a60fbe7d3848f85a1be8f0600b
Git Branch: heads/refs/tags/v7.2.0
UTC Build Time: 2023-06-27 15:04:42
GoVersion: go1.20.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv

### LINKED ISSUE #56462: Casting integer with display width to string results in truncation
### 1. Minimal reproduce step (Required)

```sql
DROP TABLE IF EXISTS test.t;
CREATE TABLE test.t (id bigint(11) UNSIGNED PRIMARY KEY);
INSERT INTO test.t VALUES (1234567890123456);
SELECT IFNULL(id, 'abcdef') FROM test.t;
```

### 2. What did you expect to see? (Required)

MySQL:
```
mysql-9.0.1> DROP TABLE IF EXISTS test.t;
Query OK, 0 rows affected (0.02 sec)

mysql-9.0.1> CREATE TABLE test.t (id bigint(11) UNSIGNED PRIMARY KEY);
Query OK, 0 rows affected, 1 warning (0.02 sec)

mysql-9.0.1> INSERT INTO test.t VALUES (1234567890123456);
Query OK, 1 row affected (0.00 sec)

mysql-9.0.1> SELECT IFNULL(id, 'abcdef') FROM test.t;
+----------------------+
| IFNULL(id, 'abcdef') |
+----------------------+
| 1234567890123456     |
+----------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

TiDB:
```
mysql-8.0.11-TiDB-v8.3.0> DROP TABLE IF EXISTS test.t;
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql-8.0.11-TiDB-v8.3.0> CREATE TABLE test.t (id bigint(11) UNSIGNED PRIMARY KEY);
Query OK, 0 rows affected (0.05 sec)

mysql-8.0.11-TiDB-v8.3.0> INSERT INTO test.t VALUES (1234567890123456);
Query OK, 1 row affected (0.00 sec)

mysql-8.0.11-TiDB-v8.3.0> SELECT IFNULL(id, 'abcdef') FROM test.t;
+----------------------+
| IFNULL(id, 'abcdef') |
+----------------------+
| 12345678901          |
+----------------------+
1 row in set, 1 warning (0.00 sec)

mysql-8.0.11-TiDB-v8.3.0> SHOW WARNINGS;
+---------+------+------------------------------------------+
| Level   | Code | Message                                  |
+---------+------+------------------------------------------+
| Warning | 1406 | Data Too Long, field len 11, data len 16 |
+---------+------+------------------------------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

- v8.3.0
- v7.5.1

### Related

This is similar to #44213 but for a different set of types.

This is related to https://github.com/pingcap/tidb/issues/44786

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #56462 close #45338

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Issues related to casting integers with a non-default display width to strings have been fixed.
```

### CODE REVIEW

**Comment by dveeden** [comment]
This looks good:
```
mysql-8.0.11-TiDB-v8.4.0-alpha-325-g74034d4ac2-dirty> DROP TABLE IF EXISTS test.t;
Query OK, 0 rows affected (0.02 sec)

mysql-8.0.11-TiDB-v8.4.0-alpha-325-g74034d4ac2-dirty> CREATE TABLE test.t (id bigint(11) UNSIGNED PRIMARY KEY);
Query OK, 0 rows affected (0.01 sec)

mysql-8.0.11-TiDB-v8.4.0-alpha-325-g74034d4ac2-dirty> INSERT INTO test.t VALUES (1234567890123456);
Query OK, 1 row affected (0.00 sec)

mysql-8.0.11-TiDB-v8.4.0-alpha-325-g74034d4ac2-dirty> SELECT IFNULL(id, 'abcdef') FROM test.t;
+----------------------+
| IFNULL(id, 'abcdef') |
+----------------------+
| 1234567890123456     |
+----------------------+
1 row in set (0.00 sec)
```

This should result in a warning and truncation, but no longer does:
```
mysql-8.0.11-TiDB-v8.4.0-alpha-325-g74034d4ac2-dirty> WITH a AS (SELECT 1234 v) SELECT CAST(v AS CHAR(2)) FROM a;
+--------------------+
| CAST(v AS CHAR(2)) |
+--------------------+
| 1234               |
+--------------------+
1 row in set (0.00 sec)
```

**Comment by Defined2014** [comment]
Hi @dveeden, is this PR ready for review?

**Comment by dveeden** [comment]
> Hi @dveeden, is this PR ready for review? 
Not yet, the problem. There is a regression that needs to be fixed. See https://github.com/pingcap/tidb/pull/56463#issuecomment-2397827533 for details.

> And I think this PR also could fix #45338
Yes, correct.

> Maybe we should modified `setFlenFromArgs` function to fix it.

**Comment by dveeden** [comment]
> Maybe we should modified `setFlenFromArgs` function to fix it.

Yes. Thanks!

**Review by Defined2014 — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
