### PR TITLE
testkit: fix data race in `GetInternalSessionStartTSList`

### LINKED ISSUE #54374: DATA RACE at the github.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).StartTS()
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
==================
WARNING: DATA RACE
Read at 0x00c0017247a0 by goroutine 33385:
  github.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).StartTS()
      external/com_github_tikv_client_go_v2/txnkv/transaction/txn.go:1635 +0x4c
  github.com/pingcap/tidb/pkg/store/driver/txn.(*tikvTxn).StartTS()
      <autogenerated>:1 +0x17
  github.com/pingcap/tidb/pkg/session.(*LazyTxn).StartTS()
      <autogenerated>:1 +0x46
  github.com/pingcap/tidb/pkg/testkit.(*MockSessionManager).GetInternalSessionStartTSList()
      pkg/testkit/mocksessionmanager.go:165 +0x2d5
  github.com/pingcap/tidb/pkg/domain/infosync.(*InfoSyncer).ReportMinStartTS()
      pkg/domain/infosync/info.go:756 +0x8b
  github.com/pingcap/tidb/pkg/domain.(*Domain).infoSyncerKeeper()
      pkg/domain/domain.go:743 +0x564
  github.com/pingcap/tidb/pkg/domain.(*Domain).infoSyncerKeeper-fm()
      <autogenerated>:1 +0x33
  github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1()
      pkg/util/wait_group_wrapper.go:99 +0xd2
Previous write at 0x00c0017247a0 by goroutine 33382:
  github.com/tikv/client-go/v2/txnkv/transaction.NewTiKVTxn()
      external/com_github_tikv_client_go_v2/txnkv/transaction/txn.go:175 +0xb6
  github.com/tikv/client-go/v2/tikv.(*KVStore).Begin()
      external/com_github_tikv_client_go_v2/tikv/kv.go:382 +0x419
  github.com/pingcap/tidb/pkg/store/mockstore/mockstorage.(*mockStorage).Begin()
      pkg/store/mockstore/mockstorage/storage.go:81 +0x57
  github.com/pingcap/tidb/pkg/session.(*txnFuture).wait()
      pkg/session/txn.go:713 +0xd43
  github.com/pingcap/tidb/pkg/session.(*LazyTxn).changePendingToValid()
      pkg/session/txn.go:297 +0x186
  github.com/pingcap/tidb/pkg/session.(*LazyTxn).Wait()
      pkg/session/txn.go:615 +0x279
  github.com/pingcap/tidb/pkg/sessiontxn/isolation.(*baseTxnContextProvider).ActivateTxn()
      pkg/sessiontxn/isolation/base.go:290 +0x176
  github.com/pingcap/tidb/pkg/sessiontxn/isolation.(*baseTxnContextProvider).GetStmtReadTS()
      pkg/sessiontxn/isolation/base.go:186 +0x2e
  github.com/pingcap/tidb/pkg/sessiontxn/isolation.(*OptimisticTxnContextProvider).GetStmtReadTS()
      pkg/sessiontxn/isolation/optimistic.go:100 +0x64
  github.com/pingcap/tidb/pkg/session.(*txnManager).GetStmtReadTS()
      pkg/session/txnmanager.go:98 +0x117
  github.com/pingcap/tidb/pkg/executor.(*executorBuilder).getSnapshotTS()
      pkg/executor/builder.go:2024 +0x149
  github.com/pingcap/tidb/pkg/executor.buildNoRangeTableReader()
      pkg/executor/builder.go:3432 +0x3d9
  github.com/pingcap/tidb/pkg/executor.(*executorBuilder).buildTableReader()
      pkg/executor/builder.go:3579 +0x993
  github.com/pingcap/tidb/pkg/executor.(*executorBuilder).build()
      pkg/executor/builder.go:288 +0x1744
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).buildExecutor()
      pkg/executor/adapter.go:1211 +0x3cd
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec()
      pkg/executor/adapter.go:560 +0xdb4
  github.com/pingcap/tidb/pkg/session.runStmt()
      pkg/session/session.go:2296 +0x5d3
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt()
      pkg/session/session.go:2157 +0x1ac4
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternalStmt()
      pkg/session/session.go:2009 +0x1e9
  github.com/pingcap/tidb/pkg/session.(*session).ExecRestrictedSQL.func1()
      pkg/session/session.go:1974 +0x2d7
  github.com/pingcap/tidb/pkg/session.(*session).withRestrictedSQLExecutor()
      pkg/session/session.go:1960 +0x3b6
  github.com/pingcap/tidb/pkg/session.(*session).ExecRestrictedSQL()
      pkg/session/session.go:1964 +0x144
  github.com/pingcap/tidb/pkg/domain.(*Domain).refreshMDLCheckTableInfo()
      pkg/domain/domain.go:822 +0x4ec
  github.com/pingcap/tidb/pkg/domain.(*Domain).loadSchemaInLoop()
      pkg/domain/domain.go:977 +0x166
  github.com/pingcap/tidb/pkg/domain.(*Domain).Init.func2()
      pkg/domain/domain.go:1310 +0x54
  github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1()
      pkg/util/wait_group_wrapper.go:99 +0xd2
Goroutine 33385 (running) created at:
  github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run()
      pkg/util/wait_group_wrapper.go:94 +0x145
  github.com/pingcap/tidb/pkg/domain.(*Domain).Init()
      pkg/domain/domain.go:1315 +0x20af
  github.com/pingcap/tidb/pkg/session.(*domainMap).Get.func1()
      pkg/session/tidb.go:92 +0x559
  github.com/pingcap/tidb/pkg/util.RunWithRetry()
      pkg/util/misc.go:70 +0x84
  github.com/pingcap/tidb/pkg/session.(*domainMap).Get()
      pkg/session/tidb.go:79 +0x2eb
  github.com/pingcap/tidb/pkg/session.createSessionWithOpt()
      pkg/session/session.go:3696 +0x6c
  github.com/pingcap/tidb/pkg/session.createSession()
      pkg/session/session.go:3688 +0x35
  github.com/pingcap/tidb/pkg/session.createSessionsImpl()
      pkg/session/session.go:3673 +0x81
  github.com/pingcap/tidb/pkg/session.createSessions()
      pkg/session/session.go:3660 +0x44
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      pkg/session/session.go:3444 +0x4cd
  github.com/pingcap/tidb/pkg/session.BootstrapSession()
      pkg/session/session.go:3376 +0xad
  github.com/pingcap/tidb/pkg/testkit.bootstrap()
      pkg/testkit/mockstore.go:254 +0x94
  github.com/pingcap/tidb/pkg/testkit.CreateMockStoreAndDomain()
      pkg/testkit/mockstore.go:225 +0xd2
  github.com/pingcap/tidb/pkg/testkit.CreateMockStore()
      pkg/testkit/mockstore.go:70 +0x3dd
  github.com/pingcap/tidb/pkg/planner/core_test.TestTooLongBinaryPlan()
      pkg/planner/core/binary_plan_test.go:125 +0x2f5
  testing.tRunner()
      GOROOT/src/testing/testing.go:1595 +0x261
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1648 +0x44
Goroutine 33382 (running) created at:
  github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run()
      pkg/util/wait_group_wrapper.go:94 +0x145
  github.com/pingcap/tidb/pkg/domain.(*Domain).Init()
      pkg/domain/domain.go:1309 +0x1ea4
  github.com/pingcap/tidb/pkg/session.(*domainMap).Get.func1()
      pkg/session/tidb.go:92 +0x559
  github.com/pingcap/tidb/pkg/util.RunWithRetry()
      pkg/util/misc.go:70 +0x84
  github.com/pingcap/tidb/pkg/session.(*domainMap).Get()
      pkg/session/tidb.go:79 +0x2eb
  github.com/pingcap/tidb/pkg/session.createSessionWithOpt()
      pkg/session/session.go:3696 +0x6c
  github.com/pingcap/tidb/pkg/session.createSession()
      pkg/session/session.go:3688 +0x35
  github.com/pingcap/tidb/pkg/session.createSessionsImpl()
      pkg/session/session.go:3673 +0x81
  github.com/pingcap/tidb/pkg/session.createSessions()
      pkg/session/session.go:3660 +0x44
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      pkg/session/session.go:3444 +0x4cd
  github.com/pingcap/tidb/pkg/session.BootstrapSession()
      pkg/session/session.go:3376 +0xad
  github.com/pingcap/tidb/pkg/testkit.bootstrap()
      pkg/testkit/mockstore.go:254 +0x94
  github.com/pingcap/tidb/pkg/testkit.CreateMockStoreAndDomain()
      pkg/testkit/mockstore.go:225 +0xd2
  github.com/pingcap/tidb/pkg/testkit.CreateMockStore()
      pkg/testkit/mockstore.go:70 +0x3dd
  github.com/pingcap/tidb/pkg/planner/core_test.TestTooLongBinaryPlan()
      pkg/planner/core/binary_plan_test.go:125 +0x2f5
  testing.tRunner()
      GOROOT/src/testing/testing.go:1595 +0x261
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1648 +0x44
================== 
```

### LINKED ISSUE #54395: DATA RACE in `GetInternalSessionStartTSList`
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/12327/pipeline/

```
WARNING: DATA RACE

Read at 0x00c03cf8c008 by goroutine 303:

  github.com/pingcap/tidb/pkg/session.(*LazyTxn).Valid()

      pkg/session/txn.go:227 +0x39

  github.com/pingcap/tidb/pkg/testkit.(*MockSessionManager).GetInternalSessionStartTSList()

      pkg/testkit/mocksessionmanager.go:164 +0x2e2

  github.com/pingcap/tidb/pkg/domain/infosync.(*InfoSyncer).ReportMinStartTS()

      pkg/domain/infosync/info.go:756 +0xb9

  github.com/pingcap/tidb/pkg/domain.(*Domain).infoSyncerKeeper()

      pkg/domain/domain.go:743 +0x53a

  github.com/pingcap/tidb/pkg/domain.(*Domain).infoSyncerKeeper-fm()

      <autogenerated>:1 +0x33

  github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1()

      pkg/util/wait_group_wrapper.go:99 +0xf4



Previous write at 0x00c03cf8c008 by goroutine 1274:

  github.com/pingcap/tidb/pkg/session.(*LazyTxn).changeToInvalid()

      pkg/session/txn.go:341 +0x17a

  github.com/pingcap/tidb/pkg/session.(*session).doCommitWithRetry.func1()

      pkg/session/session.go:779 +0x84

  runtime.deferreturn()

      GOROOT/src/runtime/panic.go:477 +0x30

  github.com/pingcap/tidb/pkg/session.(*session).CommitTxn()

      pkg/session/session.go:928 +0x1be

  github.com/pingcap/tidb/pkg/session.autoCommitAfterStmt()

      pkg/session/tidb.go:281 +0x435

  github.com/pingcap/tidb/pkg/session.finishStmt()

      pkg/session/tidb.go:243 +0x273

  github.com/pingcap/tidb/pkg/session.(*execStmtResult).Finish.func1()

      pkg/session/session.go:2370 +0x149

  sync.(*Once).doSlow()

      GOROOT/src/sync/once.go:74 +0xf0

  sync.(*Once).Do()

      GOROOT/src/sync/once.go:65 +0x44

  github.com/pingcap/tidb/pkg/session.(*execStmtResult).Finish()

      pkg/session/session.go:2365 +0x9d

  github.com/pingcap/tidb/pkg/session.(*execStmtResult).Close()

      pkg/session/session.go:2384 +0x77

  github.com/pingcap/tidb/pkg/util/sqlexec.RecordSet.Close-fm()

      <autogenerated>:1 +0x42

  github.com/pingcap/tidb/pkg/parser/terror.Call()

      pkg/parser/terror/terror.go:315 +0x51

  github.com/pingcap/tidb/pkg/util/sqlexec.ExecSQL.func1()

      pkg/util/sqlexec/restricted_sql_executor.go:257 +0x33

  runtime.deferreturn()

      GOROOT/src/runtime/panic.go:477 +0x30

  github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).ExecuteSQLWithNewSession.func1()

      pkg/disttask/framework/storage/task_table.go:183 +0xf8

  github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).WithNewSession()

      pkg/disttask/framework/storage/task_table.go:147 +0x1a1

  github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).ExecuteSQLWithNewSession()

      pkg/disttask/framework/storage/task_table.go:182 +0x184

  github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).GetTaskExecInfoByExecID()

      pkg/disttask/framework/storage/task_table.go:270 +0x259

  github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).handleTasks()

      pkg/disttask/framework/taskexecutor/manager.go:193 +0xd5

  github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).handleTasksLoop()

      pkg/disttask/framework/taskexecutor/manager.go:184 +0x2c4

  github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).handleTasksLoop-fm()

      <autogenerated>:1 +0x33

  github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1()

      pkg/util/wait_group_wrapper.go:157 +0x9d



Goroutine 303 (running) created at:

  github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run()

      pkg/util/wait_group_wrapper.go:94 +0x164

  github.com/pingcap/tidb/pkg/domain.(*Domain).Init()

      pkg/domain/domain.go:1315 +0x1c05

  github.com/pingcap/tidb/pkg/session.(*domainMap).Get.func1()

      pkg/session/tidb.go:92 +0x4c6

  github.com/pingcap/tidb/pkg/util.RunWithRetry()

      pkg/util/misc.go:70 +0xb1

  github.com/pingcap/tidb/pkg/session.(*domainMap).Get()

      pkg/session/tidb.go:79 +0x319

  github.com/pingcap/tidb/pkg/session.createSessionWithOpt()

      pkg/session/session.go:3696 +0x84

  github.com/pingcap/tidb/pkg/session.createSession()

      pkg/session/session.go:3688 +0x46

  github.com/pingcap/tidb/pkg/session.createSessionsImpl()

      pkg/session/session.go:3673 +0xa4

  github.com/pingcap/tidb/pkg/session.createSessions()

      pkg/session/session.go:3660 +0x56

  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()

      pkg/session/session.go:3444 +0x5d6

  github.com/pingcap/tidb/pkg/session.BootstrapSession()

      pkg/session/session.go:3376 +0x4b

  github.com/pingcap/tidb/tests/realtikvtest.CreateMockStoreAndDomainAndSetup()

      tests/realtikvtest/testkit.go:124 +0x1d9

  github.com/pingcap/tidb/tests/realtikvtest.CreateMockStoreAndSetup()

      tests/realtikvtest/testkit.go:99 +0x253

  tests/realtikvtest/importintotest/importintotest_test.(*mockGCSSuite).SetupSuite()

      tests/realtikvtest/importintotest/util_test.go:65 +0x227

  github.com/stretchr/testify/suite.Run()

      external/com_github_stretchr_testify/suite/suite.go:157 +0x63e

  tests/realtikvtest/importintotest/importintotest_test.TestImportInto()

      tests/realtikvtest/importintotest/util_test.go:50 +0x90

  testing.tRunner()

      GOROOT/src/testing/testing.go:1595 +0x261

  testing.(*T).Run.func1()

      GOROOT/src/testing/testing.go:1648 +0x44



Goroutine 1274 (running) created at:

  github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run()

      pkg/util/wait_group_wrapper.go:155 +0xf0

  github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).Start()

      pkg/disttask/framework/taskexecutor/manager.go:147 +0xe8

  github.com/pingcap/tidb/pkg/domain.(*Domain).distTaskFrameworkLoop()

      pkg/domain/domain.go:1543 +0x87

  github.com/pingcap/tidb/pkg/domain.(*Domain).InitDistTaskLoop.func1()

      pkg/domain/domain.go:1537 +0xeb

  github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1()

      pkg/util/wait_group_wrapper.go:99 +0xf4

==================

-- Test timed out at 2024-07-02 15:07:07 UTC --
```

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #54395, close #54374

Problem Summary:

The original implementation of `GetInternalSessionStartTSList` called `Txn(false)`. However, it's not safe to use it if there is something running on the session (which may also use txn internal state).

### What changed and how does it work?

I changed to call `TxnInfo`, which is safe to be called concurrently, as it'll have an internal lock and copy the data.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > It should pass the test without data race.
  > 

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
A panic happen where you change the part.

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
