### PR TITLE
Revert "executor: fix show global variables return session variables also (#19341) (#21045)"

### LINKED ISSUE #24326: show session variables is very slow on first run
## Bug Report

This is reported here:

https://asktug.com/t/topic/69586
https://asktug.com/t/topic/69767
https://asktug.com/t/topic/69699

### 1. Minimal reproduce step (Required)

`SHOW VARIABLES` in a new session

### 2. What did you expect to see? (Required)

It should always be fast.

### 3. What did you see instead (Required)

The first execution is slow.

### 4. What is your TiDB version? (Required)

Verified against master:
```sql
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-2748-g8b0305aa2-dirty
Edition: Community
Git Commit Hash: 8b0305aa2af38f201c893fe9ce8c9af4201ebbc8
Git Branch: master
UTC Build Time: 2021-04-27 14:20:08
GoVersion: go1.13.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by bb7133**
This reverts commit a1bdbef0856fece30c73a7e6dc1ace82c2aa9a96.

### What problem does this PR solve?

Issue Number: close #24326 for TiDB v4.0

Problem Summary:

- [x] Manual test (add detailed scripts or steps below)

The following code is used to do the tests:
```
class Test1 {    
   public static void main(String[] args) throws Exception {    
        System.setProperty( "oracle.jdbc.Trace", Boolean.TRUE.toString() );    
        Class.forName("com.mysql.jdbc.Driver").newInstance();    
        String url = "jdbc:mysql://address=(protocol=tcp)(host=127.0.0.1)(port=4000)(user=root)/test?&useUnicode=true&characterEncoding=UTF-8";    
        Connection conn = DriverManager.getConnection(url, "", "");    
        DatabaseMetaData meta = conn.getMetaData();    
        System.out.println("Driver version: " + meta.getDriverVersion());    
        System.out.println("Server version: " + meta.getDatabaseProductVersion());    
    
        int connId = 0;    
        while (connId < 20) {    
            try {    
                long startTime = System.currentTimeMillis();    
                conn = DriverManager.getConnection(url, "", "");    
                long duration = System.currentTimeMillis() - startTime;    
                System.out.println("Time for onConnection #" + connId + ": " + duration);    
                connId ++;    
            } catch (Exception e) {    
                System.out.println("Exception: "+e);    
                e.printStackTrace();    
            } finally {    
                conn.close();    
            }    
        }    
    }    
}   
```
Before this PR, a long connection duration can be noticed because of #24326 and the [MySQL connector bug #75592](https://bugs.mysql.com/bug.php?id=75592):

```
Driver version: mysql-connector-java-5.1.34 ( Revision: jess.balint@oracle.com-20141014163213-wqbwpf1ok2kvo1om )
Server version: 5.7.25-TiDB-v4.0.14
Time for onConnection #0: 71
Time for onConnection #1: 53
Time for onConnection #2: 48
Time for onConnection #3: 45
Time for onConnection #4: 74
Time for onConnection #5: 63
Time for onConnection #6: 44
Time for onConnection #7: 42
Time for onConnection #8: 37
Time for onConnection #9: 40
Time for onConnection #10: 50
Time for onConnection #11: 68
Time for onConnection #12: 40
Time for onConnection #13: 56
Time for onConnection #14: 41
Time for onConnection #15: 43
Time for onConnection #16: 41
Time for onConnection #17: 48
Time for onConnection #18: 96
Time for onConnection #19: 54
```

After reverting the commit, the duration of connection reduced:
```
Driver version: mysql-connector-java-5.1.34 ( Revision: jess.balint@oracle.com-20141014163213-wqbwpf1ok2kvo1om )
Server version: 5.7.25-TiDB-v4.0.14-1-geea91a40c
Time for onConnection #0: 12
Time for onConnection #1: 18
Time for onConnection #2: 16
Time for onConnection #3: 16
Time for onConnection #4: 24
Time for onConnection #5: 27
Time for onConnection #6: 25
Time for onConnection #7: 17
Time for onConnection #8: 19
Time for onConnection #9: 17
Time for onConnection #10: 16
Time for onConnection #11: 15
Time for onConnection #12: 17
Time for onConnection #13: 21
Time for onConnection #14: 14
Time for onConnection #15: 15
Time for onConnection #16: 14
Time for onConnection #17: 16
Time for onConnection #18: 18
Time for onConnection #19: 15
```

Side effects

- This PR brings #18517 back.

Documentation

- To be added

### Release note 

- Revert #21045 to avoid #24326.

### CODE REVIEW

**Review by zimulala — COMMENTED** [review]
> After reverting the commit, duration of connection reduced.

Could you briefly describe the reduction in execution time? The approximate time is reduced from how many milliseconds to how many milliseconds？

**Review by zimulala — DISMISSED** [review]
LGTM

**Review by guo-shaoge — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
