### PR TITLE
ddl: support creating columnar tables

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?
Problem Summary:
Support creating columnar tables whose backend is TiFlash. 

### What is changed and how it works?
What's Changed:
Add an `IsColumnar` field to the `TableInfo` in https://github.com/pingcap/parser/pull/1000 and set it when the engine of a table is TiFlash. Columnar tables must have an explicit handle and don't support indices.

### Check List 

Tests 

- Unit test

### Release note 

- Support creating columnar tables.

### CODE REVIEW

**Comment by cfzjywxk** [comment]
LGTM

**Comment by youjiali1995** [comment]
I implemented it in a new branch.

**Pull request closed without merging**
