### PR TITLE
disttask: batch insert subtasks

### LINKED ISSUE #47178: global sort add index doesn't set subtask limit led state count exceeds the transaction limitation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a cluster with tidb default Performance.StmtCountLimit
2. enable tidb_enable_disk_task and set tidb_cloud_storage_uri
3. add index 
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
add index success
### 3. What did you see instead (Required)
![图片](https://github.com/pingcap/tidb/assets/10184437/de5498ed-e9d4-4ac9-823a-5414361c76ae)

### 4. What is your TiDB version? (Required)
```sql
mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: 3ccd09e63addddeb0d33b5b87594a2d61fffd1d8
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time: 2023-09-21 11:46:28
GoVersion: go1.21.1
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
```
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: ref #46258 close #47178

Problem Summary:

### What is changed and how it works?
Insert subtasks in one sql.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
```
newSubtasks := []*proto.Subtask{}
	for i := 0; i < 10000; i++ {
		newSubtasks = append(newSubtasks, &proto.Subtask{
			Step:        proto.StepInit,
			Type:        proto.TaskTypeExample,
			SchedulerID: "instance1",
			Meta:        []byte(""),  // with big enough bytes
		})
	}
	retryable, err := sm.UpdateGlobalTaskAndAddSubTasks(task, newSubtasks, prevState)
	require.NoError(t, err)
	require.Equal(t, true, retryable)

	cnt, err := sm.GetSubtaskInStatesCnt(task.ID, proto.TaskStatePending)
	require.Equal(t, int64(10000), cnt)
``` 
pass this test
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Benjamin2037** [comment]
Please mark no code，since this pr does no need to add ut.

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Comment by okJiang** [comment]
rest lgtm, if can pass manual test that insert 5000+ rows

**Review by okJiang — APPROVED** [review]

**Pull request merged**
