### PR TITLE
update codec

### PR DESCRIPTION
**Pull request by disksing**
1. remove kv.Encoder.
2. seperate encodeKey/encodeValue.
3. remove 'string' encode flag, use 'byte' flag instead.

split from #704

### CODE REVIEW

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
@siddontang  PTAL

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
