### PR TITLE
makefile: Add timezone to BR tests

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Problem Summary:

The BR tests always fail for me because of my `TZ` being UTC−06:00:

```
FAIL: parquet_parser_test.go:83: testParquetParserSuite.TestParquetVariousTypes

parquet_parser_test.go:141:
    c.Assert(rowValue[i], Equals, row[i].GetString())
... obtained string = "2020-10-29"
... expected string = "2020-10-28"

OOPS: 67 passed, 1 FAILED
--- FAIL: TestMydumps (0.05s)

```

This uses the same workaround as other tests to set the TZ to Shanghai.

### What is changed and how it works?

Set the TZ to Shanghai for tests.

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by bb7133** [comment]
LGTM, but is it possible to update the test case for 'UTC+0' instead of 'CST'?

**Comment by kennytm** [comment]
this is caused by #27482

**Comment by morgo** [comment]
> LGTM, but is it possible to update the test case for 'UTC+0' instead of 'CST'? @kennytm @3pointer

We use `@export TZ='Asia/Shanghai';` in the other tests already. It is only for br_unit_test that we don't.

**Comment by morgo** [comment]
@kennytm @3pointer PTAL again, thx :-)

**Review by kennytm — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
