### PR TITLE
br: don't encode key of raw kv.

### LINKED ISSUE #36490: br: raw restore fail in integration test "br_rawkv"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Run integration test "br_rawkv". There will be chance that the test is failed.
See https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/12538/pipeline/#step-1407-log-587

### 2. What did you expect to see? (Required)
Test succeed.

### 3. What did you see instead (Required)
Test failed.

### 4. What is your TiDB version? (Required)
v6.2.0-alpha

### Error information
Error stack:
```
[2022-07-23T04:41:05.499Z] [2022/07/23 12:41:05.360 +08:00] [ERROR] [restore.go:85] ["failed to restore raw kv"] [error="startKey > endKey, startKey: 0000000000000000f8, endkey: 0000000000000000f7: [BR:Restore:ErrRestoreInvalidRange]invalid restore range"] [errorVerbose="[BR:Restore:ErrRestoreInvalidRange]invalid restore range
startKey > endKey, startKey: 0000000000000000f8, endkey: 0000000000000000f7
github.com/pingcap/tidb/br/pkg/restore.PaginateScanRegion
	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/restore/split.go:437
github.com/pingcap/tidb/br/pkg/restore.(*RegionSplitter).Split
	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/restore/split.go:107
github.com/pingcap/tidb/br/pkg/restore.SplitRanges
	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/restore/util.go:486
github.com/pingcap/tidb/br/pkg/task.RunRestoreRaw
	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/task/restore_raw.go:149
github.com/pingcap/tidb/br/cmd/br.runRestoreRawCommand
	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/cmd/br/restore.go:84
github.com/pingcap/tidb/br/cmd/br.newRawRestoreCommand.func1
	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/cmd/br/restore.go:167
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/pingcap/tidb/br/cmd/br.main
	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/cmd/br/main.go:57
github.com/pingcap/tidb/br/cmd/br.TestRunMain.func1
	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/cmd/br/main_test.go:40
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1571"] [stack="github.com/pingcap/tidb/br/cmd/br.runRestoreRawCommand
	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/cmd/br/restore.go:85
github.com/pingcap/tidb/br/cmd/br.newRawRestoreCommand.func1
	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/cmd/br/restore.go:167
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/pingcap/tidb/br/cmd/br.main
	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/cmd/br/main.go:57
github.com/pingcap/tidb/br/cmd/br.TestRunMain.func1
	/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/cmd/br/main_test.go:40"]
```

### PR DESCRIPTION
**Pull request by pingyu**
Issue Number: #36490

Signed-off-by: pingyu <yuping@pingcap.com>

### What problem does this PR solve?

Issue Number: close #36490

Problem Summary: br raw restore fail in integration test "br_rawkv"

### What is changed and how it works?
Do not encode keys for raw mode.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix issue #36490 
```

### CODE REVIEW

**Comment by 3pointer** [comment]
I think we can unified the function after we implement `encodeBytesExt` in other places, just like (https://github.com/D3Hunter/tidb/blob/78471a819922344da1e9e8a79079c18c9c457fbb/br/pkg/restore/split.go#L544-L546)

**Comment by 3pointer** [comment]
And I think we should check and make sure all `encodeBytes` changed to `encodeBytesExt`🤔

**Comment by pingyu** [comment]
> And I think we should check and make sure all `encodeBytes` changed to `encodeBytesExt`🤔

+1. Let me have a try.

**Review by 3pointer — APPROVED** [review]
LGTM

**Review by fengou1 — APPROVED** [review]

**Review by Leavrth — APPROVED** [review]

**Pull request merged**
