### PR TITLE
*: support alter table row_format for the compatibility

### LINKED ISSUE #48754: Skip `ALTER TABLE ... ENGINE=innodb ROW_FORMAT=DYNAMIC`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE x(a int) ENGINE=innodb;
ALTER TABLE x ENGINE=innodb, ROW_FORMAT=DYNAMIC
```

Ref: https://github.com/OllieJones/index-wp-mysql-for-speed/issues/58

### 2. What did you expect to see? (Required)

SQL executed successfully without reporting errors. No alter is executed.

### 3. What did you see instead (Required)

Error: This type of ALTER TABLE is currently unsupported

### 4. What is your TiDB version? (Required)

v7.1.0

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #48754

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

image

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by breezewish — APPROVED** [review]
Should we add a unit test to avoid future break?

**Comment by hawkingrei** [comment]
> Should we add a unit test to avoid future break?

added

**Review by zimulala — APPROVED** [review]
LGTM

**Pull request merged**
