### PR TITLE
ddl: allow multiple fast reorg running at the same time

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #52596

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

1. global sort + add index, 1 large table + 1 small table

```
mysql> admin show ddl jobs;
+--------+---------+-------------------------+------------------------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------------+
| JOB_ID | DB_NAME | TABLE_NAME              | JOB_TYPE                     | SCHEMA_STATE         | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE         |
+--------+---------+-------------------------+------------------------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------------+
|    110 | test    | sbtest1                 | add index /* ingest cloud */ | write reorganization |         2 |      104 |  17820251 | 2024-04-23 03:42:10 | 2024-04-23 03:42:10 | NULL                | running       |
|    111 | test    | sbtest2                 | add index /* ingest cloud */ | write reorganization |         2 |      108 |         0 | 2024-04-23 03:42:21 | 2024-04-23 03:42:21 | NULL                | running       |
```

```
mysql> admin show ddl jobs;
+--------+---------+-----------------------+------------------------------+--------------+-----------+----------+------------+---------------------+---------------------+---------------------+---------------+
| JOB_ID | DB_NAME | TABLE_NAME            | JOB_TYPE                     | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT  | CREATE_TIME         | START_TIME          | END_TIME            | STATE         |
+--------+---------+-----------------------+------------------------------+--------------+-----------+----------+------------+---------------------+---------------------+---------------------+---------------+
|    111 | test    | sbtest2               | add index /* ingest cloud */ | public       |         2 |      108 |   19999999 | 2024-04-23 03:42:21 | 2024-04-23 03:42:21 | 2024-04-23 03:43:12 | synced        |
|    110 | test    | sbtest1               | add index /* ingest cloud */ | public       |         2 |      104 | 5000000000 | 2024-04-23 03:42:10 | 2024-04-23 03:42:10 | 2024-04-23 05:59:04 | synced        |
```

2. add index, 1 large table + 1 small table

```
mysql> admin show ddl jobs;
+--------+---------+-----------------------+------------------------------+----------------------+-----------+----------+------------+---------------------+---------------------+---------------------+---------------+
| JOB_ID | DB_NAME | TABLE_NAME            | JOB_TYPE                     | SCHEMA_STATE         | SCHEMA_ID | TABLE_ID | ROW_COUNT  | CREATE_TIME         | START_TIME          | END_TIME            | STATE         |
+--------+---------+-----------------------+------------------------------+----------------------+-----------+----------+------------+---------------------+---------------------+---------------------+---------------+
|    114 | test    | sbtest1               | add index /* ingest */       | write reorganization |         2 |      104 |          0 | 2024-04-23 07:06:58 | 2024-04-23 07:06:58 | NULL                | running       |
|    115 | test    | sbtest2               | add index /* ingest */       | write reorganization |         2 |      108 |          0 | 2024-04-23 07:07:02 | 2024-04-23 07:07:03 | NULL                | running       |
```

```
mysql> admin show ddl jobs;
+--------+---------+------------+------------------------------+--------------+-----------+----------+------------+---------------------+---------------------+---------------------+---------------+
| JOB_ID | DB_NAME | TABLE_NAME | JOB_TYPE                     | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT  | CREATE_TIME         | START_TIME          | END_TIME            | STATE         |
+--------+---------+------------+------------------------------+--------------+-----------+----------+------------+---------------------+---------------------+---------------------+---------------+
|    115 | test    | sbtest2    | add index /* ingest */       | public       |         2 |      108 |   19999999 | 2024-04-23 07:07:02 | 2024-04-23 07:07:03 | 2024-04-23 07:08:10 | synced        |
|    114 | test    | sbtest1    | add index /* ingest */       | public       |         2 |      104 | 5000000000 | 2024-04-23 07:06:58 | 2024-04-23 07:06:58 | 2024-04-23 10:35:18 | synced        |
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]

**Comment by D3Hunter** [comment]
global sort of import-into requires 8c at least, add-index should be constrainted too, have we check it anywhere?

**Comment by lance6716** [comment]
/unhold

finished two manual tests

**Pull request merged**
