### PR TITLE
*: store some global variable into PD for global config

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Spec: [Global variables rule them ALL](https://docs.google.com/document/d/1N0FPIoOz4uSGEx435uf-XtU_hNEruIGMNhXkxdNNqK8/edit?n=Global_variables_rule_them_ALL)

Issue Number: https://github.com/pingcap/tidb/issues/28786

### What is changed and how it works?

This is the first PR of #28786, and this PR only do 1 thing: store global config into PD(etcd) when set global variable when the variable has the related global config.

### Check List 

Tests 

- [x] Unit test
- [x] Manual test (add detailed scripts or steps below)

```sql
mysql>set @@global.tidb_enable_top_sql=1;
Query OK, 0 rows affected
```

```shell
▶ etcdctl --endpoints=127.0.0.1:2379 get "/global/config" --prefix
/global/config/enable_resource_metering
true
```

```sql
mysql>set @@global.tidb_enable_top_sql=0;
Query OK, 0 rows affected
Time: 0.011s
```

```shell
▶ etcdctl --endpoints=127.0.0.1:2379 get "/global/config" --prefix
/global/config/enable_resource_metering
false
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
> I think you should not store log redact, since it will not take effect globally, which is a bug to user.

ok

**Comment by breeswish** [comment]
Could you also add tests to verify the global variables table?

**Comment by crazycs520** [comment]
> Could you also add tests to verify the global variables table?

done

**Comment by crazycs520** [comment]
@breeswish @rleungx PTAL

**Pull request merged**
