### PR TITLE
*: add context.Context to NewTxn(), tiny refactor

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Tiny refactor to make `trace` more friendly

### What is changed and how it works?

- add context.Context to NewTxn()
- add opentracing stub code for Insert.Next and Update.Next
- split `trace` json result into multiple line

### Check List 

Tests 

 - No code (tiny refactor)

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8530)

### CODE REVIEW

**Comment by tiancaiamao** [comment]
/run-all-tests
PTAL @lysu @jackysp

**Comment by tiancaiamao** [comment]
Done @jackysp

**Comment by jackysp** [comment]
Is it possible to trace `load data`? Maybe we could do it in another PR.

**Comment by tiancaiamao** [comment]
Possible, but `load data` may need to install an opentracing cluster

**Comment by tiancaiamao** [comment]
PTAL @jackysp

**Comment by tiancaiamao** [comment]
@jackysp

**Comment by zz-jason** [comment]
@tiancaiamao Please merge master and resolve conflicts.

**Pull request merged**
