### PR TITLE
server: Use alternative socket file if we can't cleanup the configured socket

### LINKED ISSUE #30663: Different users can't start tidb because of the permission issue of sock file
## Bug Report

On ubuntu 18.04 , I found example tidb cluster cannot work well

### 1. Minimal reproduce step (Required)
1. install tiup ,according to [guide](https://docs.pingcap.com/tidb/stable/quick-start-with-tidb#Linux)，create topo.yaml and edit ip to 127.0.0.1
2. run `tiup cluster deploy xxx 5.3.0 ./topo.yaml --user root -p` 
3.  run `tiup cluster start xxx ` 

### 2. What did you expect to see? (Required)
 After running  ` tiup cluster display xxx ` , all nodes' status should be up
### 3. What did you see instead (Required)
But tidb's status is always down

### 4. What is your TiDB version? (Required)
5.3.0

### 5. appendix
1. system info： ` Linux version 4.15.0-96-generic (buildd@lgw01-amd64-004) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 `
2. ufw  firewall has been stopped and disabled

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #30663 

Problem Summary:

If the (stale) socket file is owned by another user it might not be possible to cleanup the socket.

### What is changed and how it works?

If the socket (say `/tmp/tidb-4000.sock` can't be cleaned up, use `/tmp/tidb-4000-1641833129.sock`, where 1641833129 is a timestamp.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Test:

- Run `sudo ./bin/tidb-server`, then send a SIGKILL to it.
- Run `sudo rm -rf /tmp/tidb/kv/LOCK`
- Run `./bin/tidb-server`
- Check logs

```
[2022/01/10 17:45:29.634 +01:00] [WARN] [server.go:328] ["Unix socket exists and is nonfunctional, removing it"] [socket=/tmp/tidb-4000.sock] [error="dial unix /tmp/tidb-4000.sock: connect: permission denied"]
[2022/01/10 17:45:29.634 +01:00] [ERROR] [server.go:264] ["failed to cleanup socket"] [error="failed to remove socket file /tmp/tidb-4000.sock"] [new-socket=/tmp/tidb-4000-1641833129.sock]
[2022/01/10 17:45:29.634 +01:00] [INFO] [server.go:270] ["server is running MySQL protocol"] [socket=/tmp/tidb-4000-1641833129.sock]
```

Another check would be to run something like `sudo nc -lU /tmp/tidb-4000.sock`.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
A alternative file will be used if the specified socket file is not in a usable state during startup
```

### CODE REVIEW

**Comment by morgo** [comment]
Code looks fine, but I don't like the idea of just randomly changing the location if the socket file exists. Consider the case that if tidb couldn't bind to port 4000: this would be like saying that's okay, try binding to port 4001. Please check with @easonn7 

My suggestion is that we fail faster and make the error message clearer.

**Comment by dveeden** [comment]
> Code looks fine, but I don't like the idea of just randomly changing the location if the socket file exists. Consider the case that if tidb couldn't bind to port 4000: this would be like saying that's okay, try binding to port 4001. Please check with @easonn7
> 
> My suggestion is that we fail faster and make the error message clearer.

If I run `sudo nc -lp 4000` and then start `./tidb-server` I get a lot of output, with the last line being:
```
[2022/01/11 18:01:13.153 +01:00] [FATAL] [main.go:665] ["failed to create the server"] [error="listen tcp 0.0.0.0:4000: bind: address already in use"] [stack="main.createServer\n\t/home/dvaneeden/dev/pingcap/tidb/tidb-server/main.go:665\nmain.main\n\t/home/dvaneeden/dev/pingcap/tidb/tidb-server/main.go:203\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:225"] [stack="main.createServer\n\t/home/dvaneeden/dev/pingcap/tidb/tidb-server/main.go:665\nmain.main\n\t/home/dvaneeden/dev/pingcap/tidb/tidb-server/main.go:203\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:225"]
```

If I run `sudo nc -lU /tmp/tidb-4000.sock` and then start `./tidb-server` I get a lot of output, with the last line being:
```
[2022/01/11 18:03:04.266 +01:00] [FATAL] [main.go:665] ["failed to create the server"] [error="failed to remove socket file /tmp/tidb-4000.sock"] [stack="main.createServer\n\t/home/dvaneeden/dev/pingcap/tidb/tidb-server/main.go:665\nmain.main\n\t/home/dvaneeden/dev/pingcap/tidb/tidb-server/main.go:203\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:225"] [stack="main.createServer\n\t/home/dvaneeden/dev/pingcap/tidb/tidb-server/main.go:665\nmain.main\n\t/home/dvaneeden/dev/pingcap/tidb/tidb-server/main.go:203\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:225"]
```

So currently there isn't a big difference in how errors in the TCP listener and the UNIX socket listener are handled.

@morgo does this mean that we should "fail faster" for both listeners?

I could improve the error message a bit and make it look like this:
```
error="failed to create /tmp/tidb-4000.sock, please remove the file and try again"
```

or

```
error="socket file /tmp/tidb-4000.sock already exists, please change the 'socket' setting or remove the file"
``

**Review by djshow832 — COMMENTED** [review]
When will this new socket file be cleaned up?

**Comment by dveeden** [comment]
> When will this new socket file be cleaned up?

On startup `tidb-server` will invoke `cleanupStaleSocket()` unless `socket` is set to an empty string.

Then `cleanupStaleSocket()` checks if the specified file contains a socket file. If that's the case it tries to use `net.Dial()` to connect to it. If that succeeds then it is not safe to remove the socket file as another process is likely using it. If it can't connect then it will try to remove the file.

However if the socket file is owned by `root` other users will hit a permission error when trying to remove the file.

If `cleanupStaleSocket()` isn't able to cleanup the stale socket file (which shouldn't be there in the first place) then the server fails to start.

**Pull request closed without merging**
