### PR TITLE
telemetry: Add unit test for builtin function usage

### PR DESCRIPTION
**Pull request by leiysky**
### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by lucklove — APPROVED** [review]
LGTM

**Comment by lucklove** [comment]
Close this PR please, the feature of this test will be revoked.

**Comment by tisonkun** [comment]
@leiysky @lucklove this PR still valid?

**Comment by leiysky** [comment]
> @leiysky @lucklove this PR still valid?

Yes, would you like to help us merge this?

**Review by breeswish — APPROVED** [review]

**Pull request merged**
