### PR TITLE
store/tikv: make groupSortedMutationByRegion as a normal function in 2pc

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: AndreMouche

### What problem does this PR solve?
This PR makes the function `groupSortedMutationByRegion` as a normal function in 2pc.go since it is only used in this file . It is preparing for the later PR: create `tikv/region` package https://github.com/pingcap/tidb/pull/25205

Part of https://github.com/pingcap/tidb/issues/22513

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]
2pc.go becomes even larger...

**Review by disksing — APPROVED** [review]

**Pull request merged**
