### PR TITLE
metrics: add metrics dashboards for sync-load

### PR DESCRIPTION
**Pull request by chrysan**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### What is changed and how it works?
Add dashboards for sync-load metrics

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by chrysan** [comment]
https://github.com/pingcap/tidb/pull/30026

**Review by winoros — APPROVED** [review]

**Review by xuyifangreeneyes — APPROVED** [review]
LGTM

**Pull request merged**
