### PR TITLE
expression: make `sleep` function response to the kill statement

### LINKED ISSUE #10955: MAX_EXECUTION_TIME behavior differences from MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

MAX_EXECUTION_TIME was recently added in https://github.com/pingcap/tidb/issues/7008
I noticed a few behavior differences from MySQL.

2. What did you expect to see?

TiDB supports `set max_execution_time=1000;`, but does not support using this as a hint. This is important for languages such as Go, where connection pools (unless using a transaction) may share connections between gorountines. Thus, setting a session var is unreliable:

```
tidb> select /*+ MAX_EXECUTION_TIME(1000) */ SLEEP(5);
+----------+
| SLEEP(5) |
+----------+
|        0 |
+----------+
1 row in set (5.00 sec)

mysql80> select /*+ MAX_EXECUTION_TIME(1000) */ SLEEP(5);
+----------+
| SLEEP(5) |
+----------+
|        1 |
+----------+
1 row in set (1.00 sec)
```

The second issue is that when interrupting a sleep'ed query, MySQL will just have the sleep function return 1. TiDB instead returns an error:

```
tidb> set max_execution_time=100;
Query OK, 0 rows affected (0.00 sec)

tidb> SELECT SLEEP(10);
ERROR 1317 (70100): Query execution was interrupted

mysql80> set max_execution_time=100;
Query OK, 0 rows affected (0.00 sec)

mysql80> select sleep(10);
+-----------+
| sleep(10) |
+-----------+
|         1 |
+-----------+
1 row in set (0.10 sec)
```

A third issue is that the setting the global var did not work as expected:
```
morgo@ryzen:~/go/src/github.com/pingcap/tidb$ mysql -e 'set global max_execution_time=100'
morgo@ryzen:~/go/src/github.com/pingcap/tidb$ time mysql -e 'select sleep(10)'
+-----------+
| sleep(10) |
+-----------+
|         0 |
+-----------+

real    0m10.010s
user    0m0.005s
sys     0m0.000s

(Creating a new connection does show max_execution_time as 100, but this is not taking effect.)
```

A fourth issue is that the sleep function does not seem to cancel/interrupt. The query still runs for 60 seconds, even though it is only supposed to run for 100ms (this is different from 3rd issue, note the error message):

```
morgo@ryzen:~/go/src/github.com/pingcap/tidb$ time mysql -e 'set max_execution_time=100;select sleep(60)'
ERROR 1317 (70100) at line 1: Query execution was interrupted

real    1m0.010s
user    0m0.005s
sys     0m0.000s
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v3.0.0-rc.1-240-gcf5f42b8e
Git Commit Hash: cf5f42b8ece0fad2b3f93c6753747b392f33f4c8
Git Branch: master
UTC Build Time: 2019-06-26 03:16:26
GoVersion: go version go1.12.1 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Fixes #10955

Execute `select sleep()` in one session, and `kill tidb query xxx` in another session,
the `sleep` query is not interrupted.

```
mysql> select sleep(10);
+-----------+
| sleep(10) |
+-----------+
|         0 |
+-----------+
1 row in set (10.00 sec)
```

### What is changed and how it works?

Check the `Killed` variable once in a while during the sleep function.

### Check List 

Tests 

 - Unit test

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @jackysp @XuHuaiyu

**Comment by lysu** [comment]
@tiancaiamao  I think I found a bug :thinking: 

In MySQL:

```
select /*+ MAX_EXECUTION_TIME(1000) */ sleep(4), (select sleep(5));
+----------+-------------------+
| sleep(4) | (select sleep(5)) |
+----------+-------------------+
|        1 |                 1 |
+----------+-------------------+
1 row in set (1.00 sec)
```

but in TiDB:

```
mysql> select /*+ MAX_EXECUTION_TIME(1000) */ sleep(4), (select sleep(5));
+----------+-------------------+
| sleep(4) | (select sleep(5)) |
+----------+-------------------+
|        1 |                 0 |
+----------+-------------------+
1 row in set (6.09 sec)
```

**Comment by tiancaiamao** [comment]
@lysu Good job, you find a bug! But this is not true:

> it seems we only can kill one operator, but if later operators have time-wasted task, the query cannot return immediately

The real problem is that `MAX_EXECUTION_TIME` hint **can only kill query in execute phase**, while in your given query, `sleep` happens plan build phase.

To verify that, you can try this, this takes 5s:

```
mysql> explain select /*+ MAX_EXECUTION_TIME(1000) */ 1,  (select sleep(5));
+--------------------+-------+------+---------------+
| id                 | count | task | operator info |
+--------------------+-------+------+---------------+
| Projection_9       | 1.00  | root | 1, 0          |
| └─TableDual_10     | 1.00  | root | rows:1        |
+--------------------+-------+------+---------------+
2 rows in set (5.00 sec)
```

As a contrast, this query returns immediately:

```
mysql> explain select /*+ MAX_EXECUTION_TIME(1000) */ 1,  sleep(5);
+-------------------+-------+------+---------------+
| id                | count | task | operator info |
+-------------------+-------+------+---------------+
| Projection_3      | 1.00  | root | 1, sleep(5)   |
| └─TableDual_4     | 1.00  | root | rows:1        |
+-------------------+-------+------+---------------+
2 rows in set (0.01 sec)
```

When there is a `sleep` in  `(select sleep(5))`, we'll execute the subquery, this happens in the plan building phase and can not be canceled by `MAX_EXECUTION_TIME`

**Comment by tiancaiamao** [comment]
I think we can file an issue, and merge this PR first.

**Comment by tiancaiamao** [comment]
PTAL @lysu

**Pull request merged**
