### PR TITLE
config: add a config of resolve lock lite threshold

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

cherry-pick @Connor1996's #25835 to 5.0

Problem Summary:

When encountering a lock to resolve, TiDB chooses either ResolveLock or ResolveLockLite depending on the transaction size of the lock. Previously, ResolveLockLite is used when the transaction size is smaller than 16 which is a fixed number.

But we meet the case that ResolveLock is relatively slow due to too many tombstones between the range of the Region where the lock locates. To resolve that, we'd better use ResolveLockLite to avoid the effect of too many tombstones, so make the threshold configurable.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed, How it Works:

add a resolveLite threshold config

### Related changes

- Need to cherry-pick to the release branch master(go-client), 5.1

### Check List 

Tests 

- Just config change

Side effects

- n/a

### Release note 

- Support change resolve lock lite threshold by config file

### CODE REVIEW

**Comment by sticnarf** [comment]
The default value is changed from 16 to 128?

**Comment by lysu** [comment]
> The default value is changed from 16 to 128?

good catch...maybe only those on-call user need 128(and support didn't want to change configuration file).. reset it to 16~

**Comment by lysu** [comment]
> The default value is changed from 16 to 128?

good catch...maybe only those on-call user need 128(and support didn't want to change the configuration file).. reset it to 16~

**Review by Connor1996 — COMMENTED** [review]
Should we merge it in master first?

**Comment by Connor1996** [comment]
> good catch...maybe only those on-call user need 128(and supporter didn't want to change configuration file).. reset it to 16~

Yes, though hard to tell 16 is a better one

**Comment by lysu** [comment]
> Should we merge it in master first?

I will do it later...master has be split to two repo (tidb and go-client)..cherry-pick from master is not very friendly  😢

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
How about using a global variable? Changing config needs restart TiDB

**Comment by lysu** [comment]
> How about using a global variable? Changing config needs restart TiDB

maybe config is enough, this config seems not be frequently change

**Comment by youjiali1995** [comment]
> But we meet the case that ResolveLock is relatively slow due to too many tombstones between the range of the Region where the lock locates. To resolve that, we'd better use ResolveLockLite to avoid the effect of too many tombstones, so make the threshold configurable.

Which issue?

**Comment by djshow832** [comment]
Not used. Close it temporarily.

**Pull request closed without merging**
