### PR TITLE
dockerfile: cache pkg except current repo

### LINKED ISSUE #30799: failed to build docker image
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
git clone this repo
docker build .

### 2. What did you expect to see? (Required)
build docker image success

### 3. What did you see instead (Required)
```
$ docker build .
[+] Building 44.4s (17/21)
 => [internal] load build definition from Dockerfile                                           0.0s
 => => transferring dockerfile: 1.44kB                                                         0.0s
 => [internal] load .dockerignore                                                              0.0s
 => => transferring context: 2B                                                                0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                               5.1s
 => [internal] load metadata for docker.io/library/golang:1.16-alpine                          5.1s
 => [auth] library/golang:pull token for registry-1.docker.io                                  0.0s
 => [auth] library/alpine:pull token for registry-1.docker.io                                  0.0s
 => [builder  1/10] FROM docker.io/library/golang:1.16-alpine@sha256:41610aabe4ee677934b0868  10.5s
 => => resolve docker.io/library/golang:1.16-alpine@sha256:41610aabe4ee677934b08685f7ffbeaa89  0.0s
 => => sha256:1a89e8eeedd549875510e5e4e14010906a58878526814e6df25d1400985 281.90kB / 281.90kB  0.7s
 => => sha256:94645a83ff95687e6f078c140cfcac8def006923ed4019ef74fa189e6d9f0b14 153B / 153B     0.9s
 => => sha256:41610aabe4ee677934b08685f7ffbeaa89166ed30df9da3f569d1e63789e199 1.65kB / 1.65kB  0.0s
 => => sha256:fbb7b9282fdecc2e6ff25b1c93fdb95b751d9aa139698126b005d33602cdf8d 1.36kB / 1.36kB  0.0s
 => => sha256:308af99b59fa2f336068e41f115d7826429dd7532b0aa2424ac260e43afcf38 5.21kB / 5.21kB  0.0s
 => => sha256:9b3977197b4f2147bdd31e1271f811319dcd5c2fc595f14e81f5351ab6275b9 2.72MB / 2.72MB  1.5s
 => => sha256:9b61b37a4c3706b7b5cc5dc8ff477f656916cdf8f9720345e26c6b1a750 101.15MB / 101.15MB  6.7s
 => => sha256:94849eefd260f6f3935c2600d11ca08a46beacdcde0c9069347625ca7ce67d7b 125B / 125B     1.4s
 => => extracting sha256:9b3977197b4f2147bdd31e1271f811319dcd5c2fc595f14e81f5351ab6275b99     37.7s
 => => extracting sha256:1a89e8eeedd549875510e5e4e14010906a58878526814e6df25d14009856c6ff      0.1s
 => => extracting sha256:94645a83ff95687e6f078c140cfcac8def006923ed4019ef74fa189e6d9f0b14      0.0s
 => => extracting sha256:9b61b37a4c3706b7b5cc5dc8ff477f656916cdf8f9720345e26c6b1a750cd5c9      3.5s
 => => extracting sha256:94849eefd260f6f3935c2600d11ca08a46beacdcde0c9069347625ca7ce67d7b      0.0s
 => [internal] load build context                                                              9.4s
 => => transferring context: 312.53MB                                                          9.3s
 => [stage-1 1/5] FROM docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc  1.7s
 => => resolve docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc  0.0s
 => => sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c930 1.64kB / 1.64kB  0.0s
 => => sha256:c74f1b1166784193ea6c8f9440263b9be6cae07dfe35e32a5df7a31358ac2060 528B / 528B     0.0s
 => => sha256:8e1d7573f448dc8d0ca13293b1768959a2528ff04be704f1f3d35fd3dbf6da3 1.49kB / 1.49kB  0.0s
 => => sha256:9b3977197b4f2147bdd31e1271f811319dcd5c2fc595f14e81f5351ab6275b9 2.72MB / 2.72MB  1.5s
 => => extracting sha256:9b3977197b4f2147bdd31e1271f811319dcd5c2fc595f14e81f5351ab6275b99      0.2s
 => [stage-1 2/5] RUN apk add --no-cache     curl                                              3.5s
 => [builder  2/10] RUN apk add --no-cache     wget     make     git     gcc     binutils-go  10.2s
 => [builder  3/10] RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/re  1.6s
 => [builder  4/10] RUN mkdir -p /go/src/github.com/pingcap/tidb                               0.1s
 => [builder  5/10] WORKDIR /go/src/github.com/pingcap/tidb                                    0.0s
 => [builder  6/10] COPY go.mod .                                                              0.0s
 => [builder  7/10] COPY go.sum .                                                              0.0s
 => ERROR [builder  8/10] RUN GO111MODULE=on go mod download                                  16.7s
------
 > [builder  8/10] RUN GO111MODULE=on go mod download:
#17 16.67 go: github.com/pingcap/tidb/parser@v0.0.0-20211011031125-9b13dc409c5e (replaced by ./parser): reading parser/go.mod: open /go/src/github.com/pingcap/tidb/parser/go.mod: no such file or directory
------
executor failed running [/bin/sh -c GO111MODULE=on go mod download]: exit code: 1
```

### 4. What is your TiDB version? (Required)
latest code in master branch

### PR DESCRIPTION
**Pull request by lijie0123**
Signed-off-by: lijie <lijie@pingcap.com>

### What problem does this PR solve?

Issue Number: close #30799

Problem Summary:

### What is changed and how it works?
ignore mods in current repo during docker cache go packages

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by cyliu0** [comment]
Why not just move `COPY . .` to the head of `go mod download`?

**Comment by lijie0123** [comment]
> Why not just move `COPY . .` to the head of `go mod download`?

It will disable caching. Even remove cache block is better than move copy . . ahead

**Comment by lijie0123** [comment]
consider using buildkit grammer `RUN --mount cache`， which require higher version docker

**Pull request closed without merging**
