### PR TITLE
lightning: fix oom when mem/cpu ratio is low

### LINKED ISSUE #43728: lightning might oom when mem/cpu ratio is low
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

- each row of the target table is large, say 20k, and there's many int values cannot be stored correctly, so cause ErrDataOutOfRange warning when encoding
- lightning might oom when memory is not that enough during sorting, say cpu/mem is 1:2, and we're using default region-concurrency
### 4. What is your TiDB version? (Required)
current master

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #43728

Problem Summary:

### What is changed and how it works?

we ignore warnings when encoding rows now, but warnings uses the same memory as parser, since the input
`row []types.Datum` share the same underlying buf, and when doing CastValue, we're using `hack.String`/`hack.Slice`.
when generating error such as `mysql.ErrDataOutOfRange`, the data will be part of the error, causing the buf
unable to release. So we truncate the warnings.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  - one csv file test, about 1g, each row is about 20k. add a sleep after encode this file, then get a memory profile

before
  
SEFXbEcoDA

after

JHzPzcRMCC
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by niubell — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Comment by D3Hunter** [comment]
ci pass
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_br_test/detail/tidb_ghpr_integration_br_test/12554/pipeline

**Pull request merged**
