### PR TITLE
server: Split TestTLS

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: #26947

Problem Summary: `TestTLS` can take more than 3 minutes. Splitting this helps to identify what part is problematic

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

**Review by morgo — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
Seems TestTLSAuto still take much time
[2021-08-17T02:30:32.622Z] PASS: tidb_test.go:874: tidbTestSerialSuite.TestTLSAuto	6.148s

in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/26519/pipeline

**Comment by dveeden** [comment]
> Seems TestTLSAuto still take much time
> [2021-08-17T02:30:32.622Z] PASS: tidb_test.go:874: tidbTestSerialSuite.TestTLSAuto 6.148s
> 
> in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/26519/pipeline

@zhouqiang-cl Yes, that's why https://github.com/pingcap/tidb/issues/26947 is not closed yet. This is due to the RSA key size and the issue has a proposed solution.

**Pull request merged**
