### PR TITLE
executor: fill warning message with column name and row index

### PR DESCRIPTION
**Pull request by lamxTyler**
### What problem does this PR solve? 

When there is data truncate in DML, the column name and row index is not showed in warning messages.

### What is changed and how it works?

Fill in the column name and row count in warnings by tranverse the warnings.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

 - None

Related changes

 - Need to cherry-pick to the release branch
Release note

 - fill in warning message with column name and row index when there are data truncates

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
@jackysp This seems to be a problem of usability and compatibility.
There are detailed info in the error message, but not the warning message.

I'm also curious about the impact on the performance.

**Comment by lamxTyler** [comment]
Test [insert ignore](https://gist.github.com/lamxTyler/6726ff0b4a7de8df2c29d30bc179cc01) that will generate warnings for every pair using sysbench with 16 threads and runing for 300s, this pr has a perfomance downgrade about 4.6%(before：4775.7993 tps, after 4556.1745 tps).
@jackysp @XuHuaiyu

**Comment by jackysp** [comment]
I think "Truncated incorrect FLOAT value: 'a'" contains enough info which is much better than 'Data Truncated' that is blamed in the internal issue. Getting the number of rows for the warnings is a heavy operation for the current implementation.
What do you think, @lamxTyler @XuHuaiyu .

**Comment by XuHuaiyu** [comment]
@jackysp Do you mean that we can modify the error message?

**Comment by lamxTyler** [comment]
Close it due to performance issues.

**Pull request closed without merging**
