### PR TITLE
session: forbid setting both tidb_snapshot and tidb_read_staleness

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: yisaer <disxiaofei@163.com>

### What is changed and how it works?

forbid setting both tidb_snapshot and tidb_read_staleness

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Review by nolouch — COMMENTED** [review]
lgtm

**Comment by JmPotato** [comment]
@pingcap/tidb-configuration-reviewer PTAL, thx!

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
