### PR TITLE
config: set the default value of auto_tls to false

### PR DESCRIPTION
**Pull request by bb7133**
### What is changed and how it works?

What's Changed:

As described in the title, we would set the default value of `auto_tls` to `false` for compatibility with earlier releases:

In #24141 the 'automatical creation of TLS certificates' is introduced for the consideration of MySQL's default behavior. However, when the client specifies to use an encrypted connection(the default behavior for most clients/connectors), a performance regression can be noticed.

The problem here is, many of the users may not be aware if they're using a client with the encrypted connection, so we decided to set the default value of `auto_tls` in the code to avoid the potential performance regression while keeping it to `true` in the config example file.

However, the value in the config example file will be kept to `true` so that it is recommended(mostly for new clusters).

### Check List 

Tests 

- [ ] Manual test (add detailed scripts or steps below)

Start a new TiDB with a configuration that does not contain `auto_tls`, and confirm that the default value is `false`.

Documentation

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by dveeden — COMMENTED** [review]
First a practical issue: This causes `TestConfig` to fail:
```
[2021-08-23T06:21:19.441Z]         	            	Diff:
[2021-08-23T06:21:19.441Z]         	            	--- Expected
[2021-08-23T06:21:19.441Z]         	            	+++ Actual
[2021-08-23T06:21:19.441Z]         	            	@@ -71,3 +71,3 @@
[2021-08-23T06:21:19.441Z]         	            	   EnableSEM: (bool) false,
[2021-08-23T06:21:19.441Z]         	            	-  AutoTLS: (bool) false,
[2021-08-23T06:21:19.441Z]         	            	+  AutoTLS: (bool) true,
[2021-08-23T06:21:19.441Z]         	            	   MinTLSVersion: (string) ""
[2021-08-23T06:21:19.441Z]         	Test:       	TestConfig
[2021-08-23T06:21:19.441Z] --- FAIL: TestConfig (0.02s)
```

> The problem here is, many of the users may not be aware if they're using a client with the encrypted connection, so we decided to set the default value of auto_tls in the code to avoid the potential performance regression while keeping it to true in the config example file.

Here the choice is between *Security* and *Performance*.

This can delay the initial startup of the server by a little. I'm not sure if this is really a problem. I expect the performance impact to be minimal when running.

I would opt to keep this enabled and allow people to turn it of if the performance impact is problematic.

Leaving this enabled would:

- Result in a secure-by-default situation. Especially for those setups where there is not enough infrastructure and/or knowledge to setup TLS.
- Result in more testing with TLS etc.
- Make it easier for people to use `caching_sha2_password` as without TLS this won't work.

I don't think this is a very technical decision to be made. This is mostly a strategic one. I'm fine with both options, but I would prefer TLS to be on by default.

**Comment by bb7133** [comment]
> I would opt to keep this enabled and allow people to turn it of if the performance impact is problematic.

**Review by AilinKid — APPROVED** [review]
LGTM

**Review by xiongjiwei — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Review by morgo — APPROVED** [review]

**Review by morgo — APPROVED** [review]

**Pull request merged**
