### PR TITLE
ddl: make 'alter table reorganize partition' report error

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

```
create table t ( id int, fname varchar(25), lname varchar(25), dob date) partition by range( year(dob) ) (
    partition p0 values less than (1980),
    partition p1 values less than (1990),
    partition p2 values less than (2000),
    partition p3 values less than maxvalue
);

alter table t reorganize partition p0 into (
    partition n0 values less than (1970),
    partition n1 values less than (1980)
);
```

This operation is not supported yet, return an error explicitly is better that simply ignore the statement.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

Make 'alter table reorganize partition' report error.

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- `alter table reorganize partition` is not implemented, report error explicitly for this operation

### CODE REVIEW

**Comment by jackysp** [comment]
Should it be backported to the release branches? I think it is hard to decide.

**Comment by tiancaiamao** [comment]
Our QA think return error is the expected behavior, and the test cases are designed accordingly.
@jackysp

**Comment by tiancaiamao** [comment]
Fix https://github.com/pingcap/tidb/issues/16930

**Comment by jackysp** [comment]
ok

**Comment by tiancaiamao** [comment]
Fix https://github.com/pingcap/tidb/issues/16931

**Pull request merged**
