### PR TITLE
planner,expression,util: scatter hotspot index in certain scenes by expression index

### PR DESCRIPTION
**Pull request by TonsnakeLin**
### What problem does this PR solve?

It propose a solution to solve the problem that hot indexes hinder the scalability of TiDB in certain case. The detail design please refer the doc [here](https://docs.google.com/document/d/1gJvM0XqrTosY7plrjL20qpP1CoV8N23B8WkZxLHes24/edit#).

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains experimental features

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by TonsnakeLin** [comment]
@cfzjywxk @youjiali1995 @sticnarf @MyonKeminta @tiancaiamao

**Comment by TonsnakeLin** [comment]
@cfzjywxk @youjiali1995 @sticnarf @MyonKeminta @tiancaiamao
I don't known why so many commits I pushed  some days ago still appeared in this draft PR.
In actually, The relative commit was since Dec 10, 2021

**Comment by sticnarf** [comment]
@TonsnakeLin Every time you create a new pull request, I suggest you use a separate branch. The branch should be based on the latest master and only contain your related changed.

**Comment by tiancaiamao** [comment]
> @TonsnakeLin Every time you create a new pull request, I suggest you use a separate branch. The branch should be based on the latest master and only contain your related changes.

That's the develop model in TiKV? @sticnarf  Here in TiDB I suggest small PRs (less than 300 lines) with test case for each PR.

The master branch is active and a separate branch with too much change will conflicts a lot.

**Comment by tiancaiamao** [comment]
> The detail design please refer the doc here.

For design document please use github https://github.com/pingcap/tidb/tree/master/docs/design

Google docs is for discussing internally and your link is not a public one. @TonsnakeLin

**Comment by sticnarf** [comment]
> > @TonsnakeLin Every time you create a new pull request, I suggest you use a separate branch. The branch should be based on the latest master and only contain your related changes.
> 
> That's the develop model in TiKV? @sticnarf Here in TiDB I suggest small PRs (less than 300 lines) with test case for each PR.
> 
> The master branch is active and a separate branch with too much change will conflicts a lot.

Ah, I don't mean the development model. I just find @TonsnakeLin seems to reuse his other branches to create this PR, and that leads to the problem.

**Comment by TonsnakeLin** [comment]
> 

Got it, I have opened the privilege for every one and you can refer the doc first to understand my code.
I will make a design doc as you said later

**Comment by TonsnakeLin** [comment]
> > > @TonsnakeLin Every time you create a new pull request, I suggest you use a separate branch. The branch should be based on the latest master and only contain your related changes.
> > 
> > 
> > That's the develop model in TiKV? @sticnarf Here in TiDB I suggest small PRs (less than 300 lines) with test case for each PR.
> > The master branch is active and a separate branch with too much change will conflicts a lot.
> 
> Ah, I don't mean the development model. I just find @TonsnakeLin seems to reuse his other branches to create this PR, and that leads to the problem.

Thanks every much! yes,  so I deleted my repository of tidb and fork it again, and made a new branch to create a new drat PR, as bellow.
https://github.com/pingcap/tidb/pull/30659
Please review the code for the new draft PR, Thanks to @cfzjywxk @youjiali1995 @sticnarf 
@MyonKeminta @tiancaiamao

**Pull request closed without merging**
