### PR TITLE
Revert "planner: remove the useless variable tidb_enable_point_get_cache"

### LINKED ISSUE #48958: Should we keep `EnablePointGetCache` realted codes?
## Enhancement

We can only enable `EnablePointGetCache` by golang code rather than a global variable. And its default value is `false` which means it nerver be used anytime.

The realed global variable is deleted by #36844.  

(Seems https://github.com/pingcap/tidb/pull/36844 is a mistake, maybe we could add it back or totally remove it.

### LINKED ISSUE #51007: Add `tidb_enable_point_get_cache` back
## Enhancement
`tidb_enable_point_get_cache` was wrongly removed in https://github.com/pingcap/tidb/pull/36844 . It should be added back.

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve?

Issue Number: close #51007, also will close #48958

Problem Summary:

### What changed and how does it work?
Revert https://github.com/pingcap/tidb/pull/36844
Add `tidb_enable_point_get_cache` back.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]
Please close https://github.com/pingcap/tidb/issues/48958 after this PR merged.

**Review by qw4990 — APPROVED** [review]

**Comment by Defined2014** [comment]
/cc @easonn7 @yudongusa

PTAL

**Review by AilinKid — COMMENTED** [review]
/retest

**Comment by yudongusa** [comment]
@jackysp did we have enough tests on adding this back to make sure it still works?

**Comment by jackysp** [comment]
> @jackysp did we have enough tests on adding this back to make sure it still works?

@yudongusa When this switch was added originally, it seems that no testing was done. I think we can add the test for this switch in other pull requests. Currently, it is in a hidden state without documentation, so it will not affect customers either.

**Review by qw4990 — APPROVED** [review]

**Pull request closed without merging**
