### PR TITLE
tidb-server: change flag v to V

### PR DESCRIPTION
**Pull request by overvenus**
PTAL @andelf @shenli 

cc pingcap/pd#472
cc pingcap/tikv#1499

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by coocood** [comment]
Any other product use `-V`?

**Comment by coocood** [comment]
LGTM

**Comment by andelf** [comment]
@coocood 


```
$ mysql -V
mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3
$ mysql -v
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
$ mysql --version
mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3
```

```
# psql -V
psql (PostgreSQL) 9.3.15
# psql -v
/usr/lib/postgresql/9.3/bin/psql: option requires an argument -- 'v'
Try "psql --help" for more information.
# psql --version
psql (PostgreSQL) 9.3.15
```

**Comment by andelf** [comment]
LGTM

**Pull request merged**
