### PR TITLE
server: return results of ongoing queries when graceful shutdown (#19669)

### LINKED ISSUE #19663: Got `Query execution was interrupted` when graceful shutdown
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```mysql
create table t(a int);
select 1 from t where (select sleep(3)) ;
```

During the sleeping, kill(sig terminate) the tidb-server

### 2. What did you expect to see? (Required)

```
Empty set (3.01 sec)
```
And after the result returned, the server exits gracefully.

### 3. What did you see instead (Required)

```
ERROR 1317 (70100): Query execution was interrupted
```
## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @qw4990

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19669 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #19663 

Problem Summary:

Got `Query execution was interrupted` when graceful shutdown

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Should not return `ErrQueryInterrupted` when server state is `connStatusWaitShutdown`. Results of ongoing queries should be returned successfully when graceful shutdown.

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Add an e2e test:

master:
```bash
$ make
cd /Users/sunrunaway/code/gopath/src/github.com/pingcap/tidb && \
	CGO_ENABLED=1 GO111MODULE=on go build  -tags codes -ldflags '-X "github.com/pingcap/parser/mysql.TiDBReleaseVersion=v4.0.0-beta.2-1669-gb3f8be7d3" -X "github.com/pingcap/tidb/util/versioninfo.TiDBBuildTS=2020-11-30 09:26:36" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitHash=b3f8be7d3c9a719d043f41db14b62d259a79ecb2" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitBranch=master" -X "github.com/pingcap/tidb/util/versioninfo.TiDBEdition=Community"' -o /Users/sunrunaway/code/gopath/src/github.com/pingcap/tidb/tests/graceshutdown/bin/tidb-server tidb-server/main.go
Build TiDB Server successfully!
$ ./run-tests.sh
INFO[0000] starting tidb: bin/tidb-server --store=mocktikv --path=/tmp/tidb_gracefulshutdown/mocktikv -P=5501 --status=8500 --log-file=/tmp/tidb_gracefulshutdown/tidb5501.log 
INFO[0000] connect to server 127.0.0.1:5501 ok          
INFO[0001] service "tidb" Interrupt                     

----------------------------------------------------------------------
FAIL: graceshutdown_test.go:113: TestGracefulShutdownSuite.TestGracefulShutdown

graceshutdown_test.go:144:
    c.Assert(err, IsNil)
... value *mysql.MySQLError = &mysql.MySQLError{Number:0x525, Message:"Query execution was interrupted"} ("Error 1317: Query execution was interrupted")

OOPS: 0 passed, 1 FAILED
--- FAIL: TestGracefulShutdown (3.54s)
FAIL
exit status 1
FAIL	graceshutdown	3.557s
```

This branch:
```
$ make
cd /Users/sunrunaway/code/gopath/src/github.com/pingcap/tidb && \
	CGO_ENABLED=1 GO111MODULE=on go build  -tags codes -ldflags '-X "github.com/pingcap/parser/mysql.TiDBReleaseVersion=v4.0.0-beta.2-1671-g77e9fc4ad" -X "github.com/pingcap/tidb/util/versioninfo.TiDBBuildTS=2020-11-30 09:21:36" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitHash=77e9fc4ada3d6266f7d8e8702574f4c8d261e794" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitBranch=issue19663" -X "github.com/pingcap/tidb/util/versioninfo.TiDBEdition=Community"' -o /Users/sunrunaway/code/gopath/src/github.com/pingcap/tidb/tests/graceshutdown/bin/tidb-server tidb-server/main.go
Build TiDB Server successfully!
$ ./run-tests.sh
INFO[0000] starting tidb: bin/tidb-server --store=mocktikv --path=/tmp/tidb_gracefulshutdown/mocktikv -P=5501 --status=8500 --log-file=/tmp/tidb_gracefulshutdown/tidb5501.log 
INFO[0000] connect to server 127.0.0.1:5501 ok          
INFO[0001] service "tidb" Interrupt                                          
PASS: graceshutdown_test.go:113: TestGracefulShutdownSuite.TestGracefulShutdown	3.538s
OK: 1 passed
PASS
ok  	graceshutdown	3.549s
```

### Release note 

- return results of ongoing queries when graceful shutdown.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM

**Comment by zz-jason** [comment]
@SunRunAway please resolve conflicts.

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
