### PR TITLE
sessionctx: refactor set to be in struct

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Problem Summary:

Currently `SetSystemVar` is implemented as a large `switch` statement. While it's now possible for plugins to call `RegisterSysVar()` and `UnregisterSysVar()` and provide a validation function, it was not possible to provide a function for when the value is changed.

As well as catering for the plugin use case, it should help simplify built-in variables as code can be specified in fewer places (this is a work in progress - since the code is still not DRY in [managing builtin variables](https://github.com/pingcap/tidb/blob/master/session/session.go#L2381-L2501) or variables that can be[ set via the HTTP API](https://github.com/pingcap/tidb/blob/master/server/http_handler.go#L690-L794)).

The initial implementation only converts one sysVar to use the struct for `SetSession`. My concern is with merge conflicts. If we agree that the design of this change is correct, I can followup by merging the other changes in batches.

### What is changed and how it works?

What's Changed:

+ Internal refactor

How it Works:

Function neutral change.

### Related changes

- None

### Check List 

Tests 

- Unit test (covered by existing tests)

Side effects

- May be slightly more verbose code in some instances (but more self-contained and manageable).

### Release note 

- No release notes

### CODE REVIEW

**Review by xhebox — COMMENTED** [review]
Looks like the experimental refactor is done on `TiDBMultiStatementMode`, do we fire another PR on `InteractiveTimeout`?

And yes, I like the idea of putting all variables in several declaration arrays. Possibly we can have `func XXXVarBuilder() Variable` to union all kinds of variables, or something similar. But for now, I agreed that the non-DRY parts of `SysVar` should be cleaned first.

**Comment by morgo** [comment]
> Looks like the experimental refactor is done on `TiDBMultiStatementMode`, do we fire another PR on `InteractiveTimeout`?

Yes, I can move it to another PR.

**Pull request merged**
