### PR TITLE
release-1.0: cherry-pick #5447

### PR DESCRIPTION
**Pull request by winoros**
Cherry-pick one pr.
PTAL @hanfei1991 @coocood @shenli

### CODE REVIEW

**Comment by hanfei1991** [comment]
/run-all-tests tikv=release-1.0 tidb-test=release-1.0 tidb-private-test=release-1.0

**Comment by winoros** [comment]
/run-sqllogic-test tikv=release-1.0 tidb-test=release-1.0 tidb-private-test=release-1.0

**Comment by shenli** [comment]
Please fix the CI.

**Comment by winoros** [comment]
@shenli The ci failed due to travis itself. Restart it and now fixed.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
