### PR TITLE
misc: Update kvproto

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary: Update to a KvProto that contains ScanDetailV2.

This PR partially cherry picks #20966 . Only kvproto change is included.

### What is changed and how it works?

What's Changed: Update kvproto

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Comment by lichunzhu** [comment]
An extended PR of https://github.com/pingcap/tidb/pull/21919

**Review by breeswish — APPROVED** [review]

**Comment by lichunzhu** [comment]
@breeswish Could you please give a `/lgtm`?

**Pull request merged**
