### PR TITLE
planner: fix a corner case in column pruning rule (#10974)

### PR DESCRIPTION
**Pull request by bb7133**
Cherry-pick https://github.com/pingcap/tidb/pull/10974

### CODE REVIEW

**Comment by eurekaka** [comment]
@bb7133 CI failed, PTAL

**Comment by bb7133** [comment]
hi @eurekaka @zz-jason , CI failed because in v2.1 `PruneColumns()` doesn't return anything, so I ignored the error returned from `NewAggFuncDesc` but CI complained. 

Now I added a panic to handle the possible error. Not sure if this is a good idea:

https://github.com/pingcap/tidb/pull/11019/files#diff-e96c32593ee8e5ead5adbd45e60e61d9R106

**Comment by bb7133** [comment]
/run-all-tests tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by bb7133** [comment]
/run-integration-ddl-test  tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by eurekaka** [comment]
> Now I added a panic to handle the possible error. Not sure if this is a good idea

I think it's fine, because the panic should never be triggered for `first_row(1)`

**Pull request merged**
