### PR TITLE
*: use golang built-in functions rather than mathutil

### LINKED ISSUE #56594: use golang built-in functions rather than mathutil
## Enhancement

like we can use `max` rather than

https://github.com/pingcap/tidb/blob/7158ac65ee454d38455cd636b562649b08906e18/pkg/util/mathutil/math.go#L71-L80

### PR DESCRIPTION
**Pull request by songzhibin97**
### What problem does this PR solve?

Issue Number: close #56594

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by songzhibin97** [comment]
#56594

**Comment by lance6716** [comment]
The CI message is 

```
Please run `make bazel_prepare` to update `.bazel` files, or just apply the following git diff (run `git apply -` and paste following contents with ctrl-D as ending):
diff --git a/br/cmd/br/BUILD.bazel b/br/cmd/br/BUILD.bazel
index a20f29fce1..6e3615a62c 100644
--- a/br/cmd/br/BUILD.bazel
+++ b/br/cmd/br/BUILD.bazel
@@ -37,7 +37,6 @@ go_library(
         "//pkg/util",
         "//pkg/util/gctuner",
         "//pkg/util/logutil",
-        "//pkg/util/mathutil",
         "//pkg/util/memory",
         "//pkg/util/metricsutil",
         "//pkg/util/redact",
diff --git a/cmd/importer/BUILD.bazel b/cmd/importer/BUILD.bazel
index cd8de53165..e11e994a22 100644
--- a/cmd/importer/BUILD.bazel
+++ b/cmd/importer/BUILD.bazel
@@ -26,7 +26,6 @@ go_library(
         "//pkg/statistics/handle/storage",
         "//pkg/statistics/handle/util",
         "//pkg/types",
-        "//pkg/util/mathutil",
         "@com_github_burntsushi_toml//:toml",
         "@com_github_go_sql_driver_mysql//:mysql",
         "@com_github_pingcap_errors//:errors",
diff --git a/pkg/autoid_service/BUILD.bazel b/pkg/autoid_service/BUILD.bazel
index 54054f5362..8cfbe0007b 100644
--- a/pkg/autoid_service/BUILD.bazel
+++ b/pkg/autoid_service/BUILD.bazel
@@ -16,7 +16,6 @@ go_library(
         "//pkg/owner",
         "//pkg/util/etcd",
         "//pkg/util/logutil",
-        "//pkg/util/mathutil",
         "@com_github_pingcap_errors//:errors",
         "@com_github_pingcap_failpoint//:failpoint",
         "@com_github_pingcap_kvproto//pkg/autoid",
diff --git a/pkg/ddl/tests/partition/BUILD.bazel b/pkg/ddl/tests/partition/BUILD.bazel
index 6af9cc3391..7f65dece9d 100644
--- a/pkg/ddl/tests/partition/BUILD.bazel
+++ b/pkg/ddl/tests/partition/BUILD.bazel
@@ -41,7 +41,6 @@ go_test(
         "//pkg/util/codec",
         "//pkg/util/dbterror",
         "//pkg/util/logutil",
-        "//pkg/util/mathutil",
         "@com_github_pingcap_errors//:errors",
         "@com_github_pingcap_failpoint//:failpoint",
         "@com_github_stretchr_testify//assert",
diff --git a/pkg/executor/importer/BUILD.bazel b/pkg/executor/importer/BUILD.bazel
index b878428a97..45affc02d7 100644
--- a/pkg/executor/importer/BUILD.bazel
+++ b/pkg/executor/importer/BUILD.bazel
@@ -66,7 +66,6 @@ go_library(
         "//pkg/util/filter",
         "//pkg/util/intest",
         "//pkg/util/logutil",
-        "//pkg/util/mathutil",
         "//pkg/util/promutil",
         "//pkg/util/sqlexec",
         "//pkg/util/sqlkiller",
diff --git a/pkg/parser/types/BUILD.bazel b/pkg/parser/types/BUILD.bazel
index 4e82ed0da8..c9af955d45 100644
--- a/pkg/parser/types/BUILD.bazel
+++ b/pkg/parser/types/BUILD.bazel
@@ -14,7 +14,6 @@ go_library(
         "//pkg/parser/format",
         "//pkg/parser/mysql",
         "//pkg/parser/terror",
-        "@com_github_cznic_mathutil//:mathutil",
     ],
 )
 
diff --git a/pkg/privilege/privileges/BUILD.bazel b/pkg/privilege/privileges/BUILD.bazel
index 3d12422553..3b095b09a3 100644
--- a/pkg/privilege/privileges/BUILD.bazel
+++ b/pkg/privilege/privileges/BUILD.bazel
@@ -31,7 +31,6 @@ go_library(
         "//pkg/util/dbterror",
         "//pkg/util/hack",
         "//pkg/util/logutil",
-        "//pkg/util/mathutil",
         "//pkg/util/sem",
         "//pkg/util/stringutil",
         "@com_github_lestrrat_go_jwx_v2//jwk",
diff --git a/pkg/util/cdcutil/BUILD.bazel b/pkg/util/cdcutil/BUILD.bazel
index 5b70a0cc29..805598f965 100644
--- a/pkg/util/cdcutil/BUILD.bazel
+++ b/pkg/util/cdcutil/BUILD.bazel
@@ -6,7 +6,6 @@ go_library(
     importpath = "github.com/pingcap/tidb/pkg/util/cdcutil",
     visibility = ["//visibility:public"],
     deps = [
-        "//pkg/util/mathutil",
         "@com_github_pingcap_errors//:errors",
         "@com_github_pingcap_log//:log",
         "@io_etcd_go_etcd_client_v3//:client",
diff --git a/pkg/util/mvmap/BUILD.bazel b/pkg/util/mvmap/BUILD.bazel
index 83144cce78..5596e1820b 100644
--- a/pkg/util/mvmap/BUILD.bazel
+++ b/pkg/util/mvmap/BUILD.bazel
@@ -8,7 +8,6 @@ go_library(
     ],
     importpath = "github.com/pingcap/tidb/pkg/util/mvmap",
     visibility = ["//visibility:public"],
-    deps = ["//pkg/util/mathutil"],
 )
 
 go_test(
diff --git a/tools/tazel/BUILD.bazel b/tools/tazel/BUILD.bazel
index d087ef079e..2e6c2c4330 100644
--- a/tools/tazel/BUILD.bazel
+++ b/tools/tazel/BUILD.bazel
@@ -10,7 +10,6 @@ go_library(
     importpath = "github.com/pingcap/tidb/tools/tazel",
     visibility = ["//visibility:private"],
     deps = [
-        "//pkg/util/mathutil",
         "//pkg/util/set",
         "@com_github_bazelbuild_buildtools//build:go_default_library",
         "@com_github_pingcap_log//:log",

```

**Comment by songzhibin97** [comment]
> The CI message is

image
dependencies don't seem to download

**Review by Defined2014 — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
lgtm

**Review by tangenta — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
