### PR TITLE
planner, statistics: refine stats loaded status and when to use pseudo stats

### LINKED ISSUE #37485: Some unreasonable behaviors on stats status and using pseudo stats
## Enhancement

```
mysql> use test;
Database changed
mysql> create table t(a int,  b int, c int,  index idx_a(a));
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t values (1,2,2), (3,4,4), (5,6,6), (7,8,8), (9,10,10);
Query OK, 5 rows affected (0.00 sec)
Records: 5  Duplicates: 0  Warnings: 0
```
Wait about 1min for dumping count/modify_count delta into disk.
```
mysql> show stats_meta;
+---------+------------+----------------+---------------------+--------------+-----------+
| Db_name | Table_name | Partition_name | Update_time         | Modify_count | Row_count |
+---------+------------+----------------+---------------------+--------------+-----------+
| test    | t          |                | 2022-08-30 20:49:17 |            5 |         5 |
+---------+------------+----------------+---------------------+--------------+-----------+
1 row in set (0.04 sec)

mysql> show stats_histograms;
+---------+------------+----------------+-------------+----------+---------------------+----------------+------------+--------------+-------------+-------------+-----------------+----------------+----------------+---------------+
| Db_name | Table_name | Partition_name | Column_name | Is_index | Update_time         | Distinct_count | Null_count | Avg_col_size | Correlation | Load_status | Total_mem_usage | Hist_mem_usage | Topn_mem_usage | Cms_mem_usage |
+---------+------------+----------------+-------------+----------+---------------------+----------------+------------+--------------+-------------+-------------+-----------------+----------------+----------------+---------------+
| test    | t          |                | idx_a       |        1 | 2022-08-30 20:48:38 |              0 |          0 |            0 |           0 | allLoaded   |               0 |              0 |              0 |             0 |
+---------+------------+----------------+-------------+----------+---------------------+----------------+------------+--------------+-------------+-------------+-----------------+----------------+----------------+---------------+
1 row in set (0.00 sec)
```
We haven't analyzed the table `t` yet but `Load_status` of `t.idx_a` is `allLoaded`. I think that `show stats_histograms` don't need to display columns/indices whose stats are uninitialized.
```
mysql> set @@tidb_enable_pseudo_for_outdated_stats = true;
Query OK, 0 rows affected (0.00 sec)

mysql> explain select * from t;
+-----------------------+---------+-----------+---------------+--------------------------------+
| id                    | estRows | task      | access object | operator info                  |
+-----------------------+---------+-----------+---------------+--------------------------------+
| TableReader_5         | 5.00    | root      |               | data:TableFullScan_4           |
| └─TableFullScan_4     | 5.00    | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+-----------------------+---------+-----------+---------------+--------------------------------+
2 rows in set (0.00 sec)

mysql> set @@tidb_enable_pseudo_for_outdated_stats = false;
Query OK, 0 rows affected (0.00 sec)

mysql> explain select * from t;
+-----------------------+---------+-----------+---------------+----------------------+
| id                    | estRows | task      | access object | operator info        |
+-----------------------+---------+-----------+---------------+----------------------+
| TableReader_5         | 5.00    | root      |               | data:TableFullScan_4 |
| └─TableFullScan_4     | 5.00    | cop[tikv] | table:t       | keep order:false     |
+-----------------------+---------+-----------+---------------+----------------------+
2 rows in set (0.00 sec)
```
We can see `stats:pseudo` is used when `tidb_enable_pseudo_for_outdated_stats` is true while it is not used when `tidb_enable_pseudo_for_outdated_stats` is false. I think in both cases `stats:pseudo` should be used because real stats hasn't been collected and it belongs to `pseudoEstimationNotAvailable` rather than `pseudoEstimationOutdate`.

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #37485

Problem Summary:

### What is changed and how it works?

1. When loading stats from storage, we need to set `StatsLoadedStatus` for each index/column. 

For index, we check whether `statsVer` is 0. If it is 0, index stats don't exist and we set its status to `uninitialized`. Otherwise we set its status to `allLoaded`.

 For column, we check `statsVer != 0 || colHist.Count > 0` to know whether column stats exist. `colHist.Count > 0` is for the case that we create column stats but don't set `statsVer` when adding/modifying a column. 

* If column stats don't exist, we set its status to `uninitialized`. 
* If column stats exist but we don't load buckets/topn/cmsketch for the column, we set its status to `allEvicted`. 
* If column stats exist and we load all column stats, we set its status to `allLoaded`.

2. `show stats_histograms` only displays stats information for index/column whose stats is initialized.
3. If no index/column of the table has stats, we use pseudo stats and `pseudoEstimationNotAvailable` inc.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Yisaer — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]

**Comment by hawkingrei** [comment]
@xuyifangreeneyes Please fix the test cases.

**Review by Yisaer — APPROVED** [review]

**Pull request merged**
