### PR TITLE
infoschema: add column of `Has_more_result` into table of `slow_query`

### LINKED ISSUE #33733: `Has_more_results` missing in `SLOW_QUERY` table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

select * from information_schema.slow_query;

### 2. What did you expect to see? (Required)

Should get the `Has_more_results` column.

### 3. What did you see instead (Required)

Don't get it.

### 4. What is your TiDB version? (Required)

1c658e5eb65b513350139782d43bf5868064b27e

### PR DESCRIPTION
**Pull request by likzn**
### What problem does this PR solve?

Issue Number: close #33733

Problem Summary: `SlowQueryLogItems` struct has `Has_more_result` variable but `slow_query` table has not this column so that when we `select * form infomation.slow_query` ,the `Has_more_result` will be absent

### What is changed and how it works?

Add column of `Has_more_result` into `slow_query` table

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by jackysp — APPROVED** [review]
LGTM

**Comment by jackysp** [comment]
PTAL @crazycs520

**Review by crazycs520 — APPROVED** [review]

**Pull request merged**
