### PR TITLE
parser: fix the Incompatible parser behavior for HAVING clause #34642

### LINKED ISSUE #34642: Incompatible parser behavior for HAVING clause
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
SELECT (SELECT * FROM (SELECT 'a') t) AS f1 HAVING (f1 = 'a' OR TRUE);
SELECT (SELECT * FROM (SELECT 'a') t) + 1 AS f1 HAVING (f1 = 'a' OR TRUE);
SELECT 1 + (SELECT * FROM (SELECT 'a') t) AS f1 HAVING (f1 = 'a' OR TRUE);
```
### 2. What did you expect to see? (Required)

Executed successfully.

### 3. What did you see instead (Required)

Parser error.

### 4. What is your TiDB version? (Required)

current master

### PR DESCRIPTION
**Pull request by fanrenhoo**
Signed-off-by: fanrenhoo <fanrenhoo@sina.com>

### What problem does this PR solve?

Issue Number: close #34642

Problem Summary: make the basic select statement compatible for having clause

### What is changed and how it works?
before the basic select statement incompatible for having claues, but MySQL does. So make parser to compatible for this case.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
After fix, now it works as：
MySQL [(none)]> SELECT (SELECT * FROM (SELECT 'a') t) AS f1 HAVING (f1 = 'a' OR TRUE);
+------+
| f1   |
+------+
| a    |
+------+
1 row in set (0.00 sec)

MySQL [(none)]> SELECT (SELECT * FROM (SELECT 'a') t) + 1 AS f1 HAVING (f1 = 'a' OR TRUE);
+----+
| f1 |
+----+
|  1 |
+----+
1 row in set, 2 warnings (0.00 sec)

MySQL [(none)]> SELECT 1 + (SELECT * FROM (SELECT 'a') t) AS f1 HAVING (f1 = 'a' OR TRUE);
+----+
| f1 |
+----+
|  1 |
+----+
1 row in set, 2 warnings (0.00 sec)

- [ ] No code

Side effects
No
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation
No
- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Make the basic select statement compatible for having clause like mysql does.
```

### CODE REVIEW

**Review by xhebox — CHANGES_REQUESTED** [review]
Need corresponding tests, it is not necessarily manual tests. Also, this only adds parser tests, TiDB did not adapt the changes, so the issue can not be closed.

**Comment by xhebox** [comment]
> > Need corresponding tests, it is not necessarily manual tests. Also, this only adds parser tests, TiDB did not adapt the changes, so the issue can not be closed.
> 
> THKS. Did you mean TiDB should not have this situation having syntax, or mean I need do more test?

Need tests. And I mean, just adding syntax did not add the functionality. It will pass the parsing, but will do nothing. Should also include that. Maybe you should contact the author of the issue.

**Comment by fanrenhoo** [comment]
> > > Need corresponding tests, it is not necessarily manual tests. Also, this only adds parser tests, TiDB did not adapt the changes, so the issue can not be closed.
> > 
> > 
> > THKS. Did you mean TiDB should not have this situation having syntax, or mean I need do more test?
> 
> Need tests. And I mean, just adding syntax did not add the functionality. It will pass the parsing, but will do nothing. Should also include that. Maybe you should contact the author of the issue.

I added test cases, please check. THKS much

**Comment by xhebox** [comment]
> > > > Need corresponding tests, it is not necessarily manual tests. Also, this only adds parser tests, TiDB did not adapt the changes, so the issue can not be closed.
> > > 
> > > 
> > > THKS. Did you mean TiDB should not have this situation having syntax, or mean I need do more test?
> > 
> > 
> > Need tests. And I mean, just adding syntax did not add the functionality. It will pass the parsing, but will do nothing. Should also include that. Maybe you should contact the author of the issue.
> 
> I added test cases, please check. THKS much

That is not enough. Both tests in parser and TiDB are needed.

**Comment by fanrenhoo** [comment]
@xhebox Hi, added parser test as suggested, please check. THKS.

**Review by xhebox — APPROVED** [review]

**Comment by fanrenhoo** [comment]
@zimulala Hi, how about this one? THKS

**Comment by xhebox** [comment]
I had gave LGTM, you should try to request others..

**Review by winoros — APPROVED** [review]

**Comment by xhebox** [comment]
@fanrenhoo Please solve the conflict.

**Comment by fanrenhoo** [comment]
> @fanrenhoo Please solve the conflict.

Done. THKS

**Pull request merged**
