### PR TITLE
rowcodec: forbidden Kind{Null/MinNotNull/MaxValue} encode datum & add test

### LINKED ISSUE #15632: Improve the coverage of key path in rowcodec
## Development Task

- [x] [decoder.go#L247](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/util/rowcodec/decoder.go#L247)

- [x] [decoder.go#L290](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/util/rowcodec/decoder.go#L290)

- [x] [encoder.go#L212](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/util/rowcodec/encoder.go#L212)

- [x] [row.go#L172](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/util/rowcodec/row.go#L172)

- [x] [row.go#L188](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/util/rowcodec/row.go#L188)

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Issue Number: close #15632

Problem Summary:

add coverage

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

add test

How it Works:

add test

### Related changes

- n/a

### Check List 

Tests 

- Unit test

Side effects

- n/a

### Release note 

n/a

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/16223)

### CODE REVIEW

**Comment by lysu** [comment]
```
	case types.KindNull:	
	case types.KindMinNotNull:	
	case types.KindMaxValue:
```

should only occur in build query range or point, should never see it in rowcodec, so should throw error

**Comment by coocood** [comment]
EncodeValueDatum is an exported function.
We need to make sure it is not used by any tools.

**Comment by lysu** [comment]
> EncodeValueDatum is an exported function.
> We need to make sure it is not used by any tools.

I have do some check for pingcap's repo and unistore repo, no other tools use this method directly, and this is a new method add after rowcodec, we can make it be unexported

**Comment by coocood** [comment]
LGTM

**Comment by lysu** [comment]
@jackysp need a approve :D

**Pull request merged**
