### PR TITLE
*: Update pd client to apply a new api path

### PR DESCRIPTION
**Pull request by okJiang**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/56254

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
/hold

After this PR, lightning can't use a different version with cluster? If so please check with PM

**Comment by okJiang** [comment]
@lance6716 This api seems not be used by lightning. You can check it.

**Comment by HuSharp** [comment]
> /retest

Have you updated `bazel`?

**Comment by HuSharp** [comment]
> > /retest
> 
> Have you updated `bazel`?

You need to run `make bazel_prepare` and update cache in `10.2.12.124` :)

**Comment by okJiang** [comment]
> > > /retest
> > 
> > 
> > Have you updated `bazel`?
> 
> You need to run `make bazel_prepare` and update cache in `10.2.12.124` :) @okJiang

Done~

**Comment by okJiang** [comment]
https://github.com/pingcap/tidb/pull/56292 has updated pd-client to a newer version. So we can close this pr and issue.

**Pull request closed without merging**
