### PR TITLE
store/tikv: fix typo

### PR DESCRIPTION
**Pull request by Ahacad**
### What problem does this PR solve?

Problem Summary: fix typo

### What is changed and how it works?

What's Changed:

How it Works:

### Check List 

Tests 

Side effects

### Release note 

- No release note

### CODE REVIEW

**Comment by tangenta** [comment]
@Ahacad Could you please also fix other typos in this file? They are:

```
stablishMPPConnectionRequest
combinates
streaing
timeouted
```

It is OK if you don't want to. This PR still can be merged :)

**Comment by Ahacad** [comment]
The typos have been fixed. :smile:

**Pull request merged**
