### PR TITLE
expression: fix the return type of coalesce when arg type is DATE | tidb-test=pr/2387

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

cherry-pick of https://github.com/pingcap/tidb/pull/48032

Issue Number: close https://github.com/pingcap/tidb/issues/46475

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by wuhuizuo** [comment]
please ignore the two aborted CI statuses:

image


Maybe they are caused by prow bug.

**Review by windtalker — APPROVED** [review]
LGTM

**Review by wshwsh12 — APPROVED** [review]

**Pull request merged**
