### PR TITLE
cgroup: get right value when cgroup set max value

### LINKED ISSUE #38664: get wrong mem limit/usage when cgroup memory set max

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #38664 

Problem Summary:

### What is changed and how it works?

in the old code, we cannot judge the container when it is in the docker compose.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

test in the docker by @amyangfei 

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Comment by lance6716** [comment]
Not have much certainty that `0::/` represent it's inside a container. 

> The entry for cgroup v2 is always in the format “0::$PATH”:

https://docs.kernel.org/admin-guide/cgroup-v2.html

After some searching `0::/` represent "root cgroup", but I'm not sure it means this process is inside a container

**Comment by amyangfei** [comment]
> Not have much certainty that `0::/` represent it's inside a container.
> 
> > The entry for cgroup v2 is always in the format “0::$PATH”:
> 
> https://docs.kernel.org/admin-guide/cgroup-v2.html
> 
> After some searching `0::/` represent "root cgroup", but I'm not sure it means this process is inside a container

It depends on the cgroup hierarchy, maybe it is better to check whether `cgroup` is enabled for the current process instead of checking whether it is in a container.

**Comment by lance6716** [comment]
if cgroup is enabled, we use memory limit from cgroup, otherwise we use memory limit of physical machine

**Comment by hawkingrei** [comment]
@lance6716 fix the wrong handling when cgroup is set as the max value.

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
