### PR TITLE
session: make TestInnodbLockWaitTimeout faster and remove useless testcase

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

go test -check.f TestInnodbLockWaitTimeout

Before:

```
ok  	github.com/pingcap/tidb/session	5.164s
```
After:
```
ok  	github.com/pingcap/tidb/session	2.184s
```
### What is changed and how it works?

Make some code run parallelly instead of sequentially, so the total wait time reduce.
There is code to check the `innodb_lock_wait_timeout = 2` take effect, so theoretically this unit test can't finish within 2s.

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @coocood @cfzjywxk

**Comment by cfzjywxk** [comment]
LGTM

**Comment by tiancaiamao** [comment]
PTAL @coocood @lysu

**Comment by coocood** [comment]
@tiancaiamao the title needs update

**Comment by tiancaiamao** [comment]
Done @coocood

**Pull request merged**
