### PR TITLE
planner: fix a bug that point get plan returns wrong column name

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23291

as https://github.com/pingcap/tidb/issues/23291#issuecomment-799042832 says, `the results of TiDB are problematic`
also, we explicitly select the column name and expect to get the result with the same column name.

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
```sql
create table t1(`COL1` varchar(255), PRIMARY KEY (`COL1`));
insert into t1 values("a");
SELECT col1 FROM t1 where col1="a";
+------+
| col1 |    -- it should be lower case
+------+
| a    |
+------+
1 row in set
```

### Release note 

- fix a bug that point get plan returns wrong column name

### CODE REVIEW

**Review by djshow832 — COMMENTED** [review]
Please add test cases.

**Comment by xiongjiwei** [comment]
> Please add test cases.

it is hard to use our test framework to test the result column name, I have tried to enhance it, but it will export a lot of variables and changes a lot. So I add a `Manual test`

**Review by eurekaka — APPROVED** [review]
/lgtm

**Comment by lysu** [comment]
@xiongjiwei  maybe need cherry-pick to 4.0-5.0 some user need it in oncall

**Pull request merged**
