### PR TITLE
sessionctx: add optimization-time and wait-TS-time into the slow log (#17869)

### LINKED ISSUE #17557: Add more information in slow logs to help analyze slow queries
## Development Task
Now information in slow logs(or `slow-query-table`) is not enough to analyze slow queries.
After discussing, we should add these useful information into it:
- [x] 1. time-consuming in the parse phase
- [x] 2. time-consuming for compiling the query
- [x] 3. time-consuming for rewriting the query (#17569)
- [x] 4. time-consuming for optimizing the query (#17869)
- [x] 5. time-consuming to wait for TSO (#17869)
- [x] 6. detailed execution information (like results of `explain analyze`)(#15008)(#17573)
- [x] 7. if this query hits the plan cache(#16197)
- [x] 8. if there are subqueries processed in the compile phase (#17569)
- [ ] 9. support [`ScanDetailV2`](https://github.com/pingcap/kvproto/pull/600)
- [x] 10. if this query use disk(#16883)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #17869 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/22918
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/22918:release-4.0-405a5d009dcd
```

---

### What problem does this PR solve?

Issue Number: related to #17557 

Problem Summary: add optimization-time and wait-TS-time into the slow log

### What is changed and how it works?

One step to resolve #17557.
Add optimization-time and wait-TS-time into the slow log.

### Check List 

Tests 

- Unit test

### Release note 

- add optimization-time and wait-TS-time into the slow log

### CODE REVIEW

**Comment by crazycs520** [comment]
@qw4990 @Reminiscent PTAL

**Review by Reminiscent — APPROVED** [review]
/LGTM

**Pull request merged**
