### PR TITLE
tests: fix e2e test `graceshutdown`

### LINKED ISSUE #45108: tests: e2e test `graceshutdown` failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run CI pipeline [merged_e2e_test](https://prow.tidb.net/?repo=pingcap%2Ftidb&type=postsubmit&job=pingcap%2Ftidb%2Fmerged_e2e_test).

### 2. What did you expect to see? (Required)

Pipeline succeed.

### 3. What did you see instead (Required)

Pipeline was failed.

```

+ cd tests/graceshutdown
+ make
cd /home/jenkins/agent/workspace/pingcap/tidb/merged_e2e_test/tidb && \
CGO_ENABLED=1 GO111MODULE=on go build  -tags codes -ldflags '-X "github.com/pingcap/tidb/parser/mysql.TiDBReleaseVersion=v7.3.0-alpha-55-g767267a184" -X "github.com/pingcap/tidb/util/versioninfo.TiDBBuildTS=2023-06-27 02:37:24" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitHash=767267a1845a4d9bfab7835142bc9beb9f491489" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitBranch=HEAD" -X "github.com/pingcap/tidb/util/versioninfo.TiDBEdition=Community"' -o /home/jenkins/agent/workspace/pingcap/tidb/merged_e2e_test/tidb/tests/graceshutdown/bin/tidb-server tidb-server/main.go
Build TiDB Server successfully!
+ ./run-tests.sh
go: downloading go.uber.org/goleak v1.2.1
[2023/06/27 10:37:44.307 +08:00] [INFO] [graceshutdown_test.go:48] ["starting tidb"] [cmd="bin/tidb-server --store=mocktikv --path=/tmp/tidb_gracefulshutdown/mocktikv -P=5501 --status=8500 --log-file=/tmp/tidb_gracefulshutdown/tidb5501.log"]
[2023/06/27 10:37:44.808 +08:00] [WARN] [graceshutdown_test.go:89] ["ping addr failed"] [addr=127.0.0.1:5501] ["retry count"=0] [error="dial tcp 127.0.0.1:5501: connect: connection refused"]
[2023/06/27 10:37:45.059 +08:00] [WARN] [graceshutdown_test.go:89] ["ping addr failed"] [addr=127.0.0.1:5501] ["retry count"=1] [error="dial tcp 127.0.0.1:5501: connect: connection refused"]
[2023/06/27 10:37:45.561 +08:00] [INFO] [graceshutdown_test.go:113] ["connect to server ok"] [addr=127.0.0.1:5501]
[2023/06/27 10:37:46.583 +08:00] [INFO] [graceshutdown_test.go:61] ["service Interrupt"] [name=tidb]
[mysql] 2023/06/27 10:37:46 packets.go:37: unexpected EOF
--- FAIL: TestGracefulShutdown (2.28s)
    graceshutdown_test.go:155: 
        	Error Trace:	/home/jenkins/agent/workspace/pingcap/tidb/merged_e2e_test/tidb/tests/graceshutdown/graceshutdown_test.go:155
        	Error:      	Received unexpected error:
        	            	invalid connection
        	Test:       	TestGracefulShutdown
FAIL
exit status 1
FAIL	github.com/pingcap/tidb/tests/graceshutdown	2.280s
script returned exit code 1
```

See https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fmerged_e2e_test/detail/merged_e2e_test/1588/pipeline/.

### PR DESCRIPTION
**Pull request by pingyu**
### What problem does this PR solve?

Issue Number: close #45108

Problem Summary:

### What is changed and how it works?

#44953 changed to wait for connections in transaction only for graceful shutdown..

This PR fix the e2e test case [`graceshutdown`](https://github.com/pingcap/tidb/tree/master/tests/graceshutdown) by executing query in transaction.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by pingyu** [comment]
> /cc @Defined2014

PTAL~

**Review by hawkingrei — APPROVED** [review]

**Comment by pingyu** [comment]
> /check-issue-triage-complete

@hawkingrei I think it's required to add a `severity/xxx` label to https://github.com/pingcap/tidb/issues/45108. Could you help to do so ? I don't have the permission.

**Comment by hawkingrei** [comment]
All tests should be run using Bazel to avoid repeatedly executing them.

**Review by Defined2014 — APPROVED** [review]

**Pull request merged**
