### PR TITLE
parser: create index support LOCK syntax (#5851)

### PR DESCRIPTION
**Pull request by winkyao**

### CODE REVIEW

**Comment by jackysp** [comment]
LGTM

**Comment by jackysp** [comment]
/run-all-tests tikv=release-1.0 tidb-test=release-1.0 tidb-private-test=release-1.0

**Comment by winkyao** [comment]
/run-unit-test  tikv=release-1.0 tidb-test=release-1.0 tidb-private-test=release-1.0

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
