### PR TITLE
session: switch to pessimistic txn mode for autocommit statement retry.

### PR DESCRIPTION
**Pull request by coocood**
### What problem does this PR solve?

Optimize high conflicting autocommit DML.

### What is changed and how it works?

Autocommit statements always use optimistic transaction mode, but when the conflict rate is high (zipfian distribution), it may retry too many times.

Switch to pessimistic transaction mode for retry can reduce retry cost.

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

benchmark ycsb zipfian workload and compare the result.
There is no error anymore and the performance increased more than 200%.

### Release note 

- switch to pessimistic txn mode for autocommit statement retry

### CODE REVIEW

**Comment by coocood** [comment]
> maybe we could force using pessimistic transaction for transaction retry

It's possible that the TiKV is configured to disable pessimistic transactions.

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
