### PR TITLE
executor: Fix query hang on hash aggregate operator

### PR DESCRIPTION
**Pull request by zz-jason**
## What have you changed? (mandatory)

there can be a situation that the final worker of hash aggregate can be blocked in receiving from the `finalResultHolderCh` and the main thread blocked in receiving from the `finalOutputCh`, which is closed when final worker exits.

actually the final work should be able to detect the query is finished when receiving from the `finalResultHolderCh`, so I use a `select` to do the receiving work.

## What are the type of the changes (mandatory)?

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested (mandatory)?

- unit test
- explain test

### CODE REVIEW

**Comment by zz-jason** [comment]
@XuHuaiyu @winoros and CC: @shenli

**Comment by zz-jason** [comment]
@winoros Test is on the tidb-private-test, no need to add

**Comment by winoros** [comment]
@zz-jason It can also improve the test coverage. Unit test doesn't cover `receiveFinalResultHolder` totally.

**Comment by shenli** [comment]
LGTM

**Pull request merged**
