### PR TITLE
infoschema: support query partition_id from infoschema.partitions (#22240)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #22240 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/22489
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/22489:release-4.0-b24095d909e7
```

---

Signed-off-by: lysu <sulifx@gmail.com>

### What problem does this PR solve?

Problem Summary:

current we has no easy way to get partition ids for a table, but sometime we need it to help diagnose

### What is changed and how it works?

What's Changed, How it Works:

add `TIDB_PARTITION_ID` to information_schema.partitions

### Related changes

- Need to cherry-pick to the release branch 4.0/5.0.rc to help diagnose in oncall

### Check List 

Tests 

- Unit test

Side effects

- n/a

### Release note 

- support query partition_id from infoschema.partitions

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/22240)

### CODE REVIEW

**Review by jackysp — COMMENTED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]
/LGTM

**Pull request merged**
