### PR TITLE
*: fix length of all show stmt

### PR DESCRIPTION
**Pull request by XuHuaiyu**
further improve #4544 
PTAL @shenli @winkyao @coocood

### CODE REVIEW

**Comment by shenli** [comment]
LGTM
Good job!

**Comment by coocood** [comment]
@XuHuaiyu 
`ColumnInfo` will be called after the first time of `Next`, so we need to do it in first call of `Next`.
See:
https://github.com/pingcap/tidb/blob/master/server/conn.go#L781
https://github.com/pingcap/tidb/blob/master/server/conn.go#L798

**Comment by shenli** [comment]
@XuHuaiyu Please fix ci.

**Comment by XuHuaiyu** [comment]
PTAL @coocood

**Comment by coocood** [comment]
CI failed.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
