### PR TITLE
planner, type: remove the prefix 0 in the bit array when we get the BinaryLiteral

### LINKED ISSUE #23511: The result of selecting with hexadecimal is wrong when bit as the primary key
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```mysql
CREATE TABLE `t1`  (
  `COL1` bit(11) NOT NULL,
	 PRIMARY KEY (`COL1`) USING BTREE
)

CREATE TABLE `t2`  (
  `COL1` bit(11) NOT NULL
)

insert into t1 values(b'00000111001');
insert into t2 values(b'00000111001');
```

### 2. What did you expect to see? (Required)
```mysql
mysql> select * from t1 where col1 = 0x39;
+-------------+
| COL1        |
+-------------+
| 00000111001 |
+-------------+
1 row in set (0.06 sec)

mysql> select * from t1 where col1 = 0x0039;
+-------------+
| COL1        |
+-------------+
| 00000111001 |
+-------------+
1 row in set (0.06 sec)

mysql> select * from t2 where col1 = 0x39;
+-------------+
| COL1        |
+-------------+
| 00000111001 |
+-------------+
1 row in set (0.05 sec)

mysql> select * from t2 where col1 = 0x0039;
+-------------+
| COL1        |
+-------------+
| 00000111001 |
+-------------+
1 row in set (0.06 sec)

```
### 3. What did you see instead (Required)
```mysql
mysql> select * from t1 where col1 = 0x39;
Empty set

mysql> select * from t1 where col1 = 0x0039;
+-------------+
| COL1        |
+-------------+
| 00000111001 |
+-------------+
1 row in set (0.08 sec)

mysql> select * from t2 where col1 = 0x39;
+-------------+
| COL1        |
+-------------+
| 00000111001 |
+-------------+
1 row in set (0.09 sec)

mysql> select * from t2 where col1 = 0x0039;
+-------------+
| COL1        |
+-------------+
| 00000111001 |
+-------------+
1 row in set (0.10 sec)

```
### 4. What is your TiDB version? (Required)
```mysql
Release Version: v4.0.0-beta.2-2390-gfd706ab76
Edition: Community
Git Commit Hash: fd706ab76bd09ac859aa0a4de7fe9e07da3c5508
Git Branch: master
UTC Build Time: 2021-03-17 11:37:12
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by Reminiscent**
### What problem does this PR solve?

Issue Number: close #23511 

Problem Summary: The existence of the prefix 0 makes the comparison of bit errors.

### What is changed and how it works?
When we compare the bit value, we should remove the prefix 0.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by winoros — COMMENTED** [review]
What does this zero mean?

**Comment by Reminiscent** [comment]
> What does this zero mean?

For example, the value `0x0039` should be equal to `0x39`. And the two zeros before the number 39 are the prefix 0.

**Comment by winoros** [comment]
Do we only need to consider the first zero? would there be a case that multiple leading zero occur?

**Comment by Reminiscent** [comment]
> Do we only need to consider the first zero? would there be a case that multiple leading zero occur?

Add more tests to cover multiple leading zero.

**Comment by Reminiscent** [comment]
@qw4990 @winoros PTAL

**Review by winoros — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
