### PR TITLE
server: if status address already in use, return an error

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve? 
If the status address already in use, we only log it. We don't know why the status server is unavailable except by looking at the logs.
If we don't start the status server, we can set `report-status` to false.

### What is changed and how it works?
If the status address already in use, we return an error and interrupt the service.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

Release note

 - If the status address already in use, return an error

### CODE REVIEW

**Comment by jackysp** [comment]
How to avoid the rolling upgrade failure?

**Comment by zimulala** [comment]
@jackysp 
I don't understand. If the status address is bind, if we don't return an error(the behavior like before this RP), the rolling upgrade also a failure.

**Comment by zimulala** [comment]
PTAL @jackysp @lysu

**Comment by coocood** [comment]
LGTM

**Pull request merged**
