### PR TITLE
planner: fix a bug that caused OrderBy correlated subquery can't find the outer schema

### LINKED ISSUE #26945: Table alias is not propagated to subquery
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
DROP TABLE IF EXISTS t1, t2;
CREATE TABLE t1 (a INT, b INT);
CREATE TABLE t2 (a INT, b INT);
INSERT INTO t1 VALUES (1, 1);
INSERT INTO t2 VALUES (1, 1);
SELECT one.a FROM t1 one ORDER BY (SELECT two.b FROM t2 two WHERE two.a = one.b);
```

### 2. What did you expect to see? (Required)

```
+------+
| a    |
+------+
|    1 |
+------+
1 row in set (0.00 sec)

```

### 3. What did you see instead (Required)

```
ERROR 1054 (42S22): Unknown column 'one.b' in 'where clause'
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.1.0
Edition: Community
Git Commit Hash: 8acd5c88471cb7b4d4c4a8ed73b4d53d6833f13e
Git Branch: heads/refs/tags/v5.1.0
UTC Build Time: 2021-06-24 07:10:32
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by rebelice**
### What problem does this PR solve?

Issue Number: close #26945

Problem Summary:

### What is changed and how it works?

Before this PR, when we build OrderBy correlated subquery, we will find the outer column from `outerSchemas` and `outerNames`. But the `outerSchemas` and `outerNames` will be pruned by `BuildSelect`. We may not find columns in some cases.

Here we use `allSchemas` and `allNames` instead of `outerSchemas` and `outerNames`. Because `allSchemas` and `allNames` will not be pruned.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
planner: fix a bug that caused OrderBy correlated subquery can't find the outer schema
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by winoros — CHANGES_REQUESTED** [review]
emm, leave me some time to re-think a little(

**Comment by kolbe** [comment]
@winoros any update to this issue?

**Review by winoros — COMMENTED** [review]
After I go through the codes.
What you should modify is `havingWindowAndOrderbyExprResolver`.

For example, `select a from t order by b`. The `b` doesn't appear in the select fields. But we can also execute the SQL successfully. This is because this visitor detects the `b` in order by item and rewrite it to `select a from (select a, b from t order by b)`.

```
func (b *PlanBuilder) resolveHavingAndOrderBy(sel *ast.SelectStmt, p LogicalPlan) (
	map[*ast.AggregateFuncExpr]int, map[*ast.AggregateFuncExpr]int, error) {
	extractor := &havingWindowAndOrderbyExprResolver{
		p:            p,
		selectFields: sel.Fields.Fields,
		aggMapper:    make(map[*ast.AggregateFuncExpr]int),
		colMapper:    b.colMapper,
		outerSchemas: b.outerSchemas,
		outerNames:   b.outerNames,
	}
	stepping into group by, order by and having.
	sel.Fields.Fields = extractor.selectFields
	return ...
}
```

So we just need to modify the behavior when the extractor goes into the order by clause. This changes would be more stable.

**Review by winoros — COMMENTED** [review]
After I go through the codes.
What you should modify is `havingWindowAndOrderbyExprResolver`.

For example, `select a from t order by b`. The `b` doesn't appear in the select fields. But we can also execute the SQL successfully. This is because this visitor detects the `b` in order by item and rewrite it to `select a from (select a, b from t order by b)`.

```
func (b *PlanBuilder) resolveHavingAndOrderBy(sel *ast.SelectStmt, p LogicalPlan) (
	map[*ast.AggregateFuncExpr]int, map[*ast.AggregateFuncExpr]int, error) {
	extractor := &havingWindowAndOrderbyExprResolver{
		p:            p,
		selectFields: sel.Fields.Fields,
		aggMapper:    make(map[*ast.AggregateFuncExpr]int),
		colMapper:    b.colMapper,
		outerSchemas: b.outerSchemas,
		outerNames:   b.outerNames,
	}
	stepping into group by, order by and having.
	sel.Fields.Fields = extractor.selectFields
	return ...
}
```

So we just need to modify the behavior when the extractor goes into the order by clause. This changes would be more stable.

**Pull request closed without merging**
