### PR TITLE
config, session: make Local Transaction not to affect Stale Read  (#25559)

### LINKED ISSUE #25479: Refine the behavior of `@@txn_scope` value and Local Txn
## Feature Request

Now, if we configure the `zone` label for a TiDB instance, then the default value of `@@txn_scope` will be "local", which is not quite reasonable. Because:

* User may only want to use the zone label to make sure the stale read could read the nearest data without enabling the Local TSO feature for the PD.
* Labeling a TiDB instance with a zone label without configuring the PD to enable Local TSO will get a PD timeout error because `@@txn_scope` is "local" by default, which is confusing.

So I suggest setting the default value of `@@txn_scope` to "global".

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25559 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25668
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25668:release-5.1-b858ce43c01d
```

---

Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Close #25479.

Decouple Stale Read and Local Txn by adding a new system variable named `EnableLocalTxn`. Should merge after #25525.

### What is changed and how it works?

Because both Stale Read and Local Txn need the `zone` label to determine their behavior, however, the latter is not released yet, to make sure they will not bother each other. I add a system variable `EnableLocalTxn` to disable Local Txn.

### Related changes

- tikv/client-go#93

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- `No release note`.

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
@ti-chi-bot

**Comment by zhouqiang-cl** [comment]
@ti-chi-bot

**Pull request merged**
