### PR TITLE
expression, util: rewrite IsHybridType func

### PR DESCRIPTION
**Pull request by XuHuaiyu**
For a `Hex( e.g. 0xFFFF )` or a `Bit( e.g. 0b10101 )` ValueExpr, we infer the type 
of it as [mysql.TypeVarchar](https://github.com/pingcap/tidb/blob/master/util/types/field_type.go#L199),
so it cannot be checked whether a `constant` is HybridType just using the field type.

@shenli @hanfei1991

### CODE REVIEW

**Comment by shenli** [comment]
Any test case?

**Comment by XuHuaiyu** [comment]
@shenli @hanfei1991
PTAL

**Comment by hanfei1991** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
