### PR TITLE
store/tikv: do not backoff when PessimisticLock return locked error

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

When PessimisticLock gets a locked error, TiKV has already back off before returning the response, so it's unnecessary to back off again in TiDB.

### What is changed and how it works?

Reset the change here:

https://github.com/pingcap/tidb/pull/12852/files#diff-499c236856cd9ce3300d3f5ccde41a23R721

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @coocood

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
PTAL @lysu

**Comment by cfzjywxk** [comment]
LGTM

**Comment by crazycs520** [comment]
@tiancaiamao  need cherry-pick 3.1?

**Pull request merged**
