### PR TITLE
executor: add testcases for kill auto analyze

### LINKED ISSUE #32911: Add testcase for kill auto analyze

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #32911

Problem Summary:

### What is changed and how it works?

1. Check `session.GetSessionVars().Killed` every time the analyze executor calls `nextRaw`. Though `Killed` is checked every 3 second in `(*copIterator).recvFromRespCh`, the check depends on time. `Next(ctx context.Context, e Executor, req *chunk.Chunk)` is a wrapper function on `e.Next()` and checks `Killed` before and after calling `e.Next()`. Similarly, I think we also should check `Killed` every time the analyze executor calls `nextRaw`(If `nextRaw` is wrapped by `Next`, we don't need to have additional `Killed` check but currently it is not wrapped).
2. Add the testcase for kill auto analyze(#31724).

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]

**Comment by xuyifangreeneyes** [comment]
At first I tried to make analyze stop at certain status(pending/running/finished) by sleeping 100ms using failpoint. However, it may not be what we expected when stress of CI is heavy. Hence we use another way: just execute kill auto analyze in failpoint.

**Pull request merged**
