### PR TITLE
parser: support trace plan statement 

### PR DESCRIPTION
**Pull request by Yisaer**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/29661

### What is changed and how it works?

support `trace plan` statement

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by rebelice — APPROVED** [review]

**Comment by kennytm** [comment]
so the "public documentation" in https://docs.google.com/document/d/19sdPOWexBuobN4DvOBfMXAdlyb4lvBSPRG-GqRM5USE/edit# uses the draft syntax

```sql
trace format='row' level='optimize' select …;
-- or
trace target='optimize' select …;
```

while in this PR the syntax is

```sql
trace plan select …;
```

The current PR is also made mutually exclusive with the `FORMAT` option i.e. the following is a syntax error:

```sql
trace format='json' plan select …;
```

i'd like to know if these are dedicated since there is no ***public*** discussion why it is changed into the current form.

**Review by kennytm — CHANGES_REQUESTED** [review]
↑

**Comment by Yisaer** [comment]
The syntax design in the document was an initial design. As adding an extra parameter will make the syntax more complex, we decided to use `trace plan statement` to indicates optimize trace. (And it is easy to implement and maintain.)

Also, we currently have no plan to add an extra parameter for `trace plan statement`, thus we are not going to support `trace plan format = '...' statement`. @kennytm

**Review by kennytm — APPROVED** [review]

**Review by rebelice — APPROVED** [review]

**Pull request merged**
