### PR TITLE
*: avoid copy in the SortSampleItems

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: ref #47275

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

before

```
$ go test -benchmem -run=^$ -bench ^BenchmarkBuildHistAndTopN$ github.com/pingcap/tidb/pkg/statistics
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/pkg/statistics
BenchmarkBuildHistAndTopN-8            1        1363438291 ns/op        72031328 B/op    4000055 allocs/op

```

after

```
$ go test -benchmem -run=^$ -bench ^BenchmarkBuildHistAndTopN$ github.com/pingcap/tidb/pkg/statistics
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/pkg/statistics
BenchmarkBuildHistAndTopN-8            1        1352474167 ns/op        64027744 B/op    4000054 allocs/op

```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Comment by hawkingrei** [comment]
/hold

waiting for the benchmark test

**Pull request merged**
