### PR TITLE
executor/inspect: ignore some config inconsistence check (#15666) (#15741)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

cherry-pick (#15666) (#15741)

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### CODE REVIEW

**Comment by reafans** [comment]
LGTM

**Comment by zz-jason** [comment]
the data race should be fixed by https://github.com/pingcap/tidb/pull/15852

**Pull request merged**
