### PR TITLE
planner/core: migrate test-infra to testify for rule_ tests

### LINKED ISSUE #28396: migrate test-infra to testify for `planner/core/rule_inject_extra_projection_test.go`

### LINKED ISSUE #28397: migrate test-infra to testify for `planner/core/rule_join_reorder_dp_test.go`

### LINKED ISSUE #28398: migrate test-infra to testify for `planner/core/rule_result_reorder_test.go`

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

### What problem does this PR solve?

Issue Number: close #28396 close #28397 close #28398

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
/cc @hawkingrei @rebelice 

cc @johnhaxx7

**Review by hawkingrei — APPROVED** [review]

**Review by rebelice — APPROVED** [review]

**Pull request merged**
