### PR TITLE
executor: wrong result of nullif expr when used with is null expr.

### LINKED ISSUE #23157: The result of expression nullif is not correct
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t(a int primary key);
insert into t values(1),(2);
select * from t where nullif(a,a) is null;
```

### 2. What did you expect to see? (Required)
```
+---+
| a |
+---+
| 1 |
| 2 |
+---+
```
### 3. What did you see instead (Required)
Empty set
### 4. What is your TiDB version? (Required)
Release Version: v4.0.0-beta.2-2287-g280d07c4a-dirty
Edition: Community
Git Commit Hash: 280d07c4a0bab259ed21466f1262e2409805daa5
Git Branch: master
UTC Build Time: 2021-03-05 11:03:56
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #23157

Problem Summary: 

    drop table t;
    create table t(a int primary key);
    insert into t values(1),(2);
    select * from t where nullif(a,a) is null;

The result of Nullif expr is unexpected, same reason as #23102 . 

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: In TiDB, we rewrite Nullif(e1, e2) as If(e1 = e2, NULL, e2), so we need to change InferType4ControlFuncs()(which will be call in ifFunctionClass::getFunction), unset NotNullFlag if any argument is NULL.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test: TestNullifWithIsNull()

Side effects:no

### Release note 

- wrong result of nullif expr when used with is null expr

### CODE REVIEW

**Comment by guo-shaoge** [comment]
@lzmhhh123

**Review by lzmhhh123 — APPROVED** [review]

**Review by ichn-hu — APPROVED** [review]

**Pull request merged**
