### PR TITLE
planner/core: rename var 'len' to avoid colliding with builtin function

### PR DESCRIPTION
**Pull request by haochengxia**
### What problem does this PR solve?

Problem Summary: unify the commas in the comments in `planner/core/rule_aggregation_elimination.go` and rename var `len` avoiding colliding with builtin function in `planner/core/rule_column_pruning.go`.

### What is changed and how it works?

What's Changed: comments.

How it Works: No work.

### Related changes

- None

### Check List

Tests 

- No code

Side effects

- None

### Release note 

- No release note

### CODE REVIEW

**Comment by haochengxia** [comment]
cc @tangenta @zimulala

**Review by tangenta — APPROVED** [review]

**Review by zz-jason — APPROVED** [review]
/lgtm

**Pull request merged**
