### PR TITLE
lightning: optimize integration test lightning_checkpoint

### LINKED ISSUE #31593: unstable integration test lightning_checkpoint
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)
See: https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/9528/pipeline

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #31593

Problem Summary:

### What is changed and how it works?
Make test `lightning_checkpoint` more stable.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by gozssky — APPROVED** [review]

**Review by kennytm — APPROVED** [review]

**Comment by kennytm** [comment]
/run-check_dev_2

```
[2022-01-17T05:50:47.116Z] FAIL: pessimistic_test.go:1150: testPessimisticSuite.TestPessimisticLockNonExistsKey

[2022-01-17T05:50:47.116Z] 

[2022-01-17T05:50:47.116Z] pessimistic_test.go:1167:

[2022-01-17T05:50:47.116Z]     c.Check(storeerr.ErrLockAcquireFailAndNoWaitSet.Equal(err), IsTrue, Commentf("got %v", err))

[2022-01-17T05:50:47.116Z] ... obtained bool = false

[2022-01-17T05:50:47.116Z] ... got <nil>

[2022-01-17T05:50:47.116Z] 

[2022-01-17T05:50:47.116Z] pessimistic_test.go:1169:

[2022-01-17T05:50:47.116Z]     c.Check(storeerr.ErrLockAcquireFailAndNoWaitSet.Equal(err), IsTrue, Commentf("got %v", err))

[2022-01-17T05:50:47.116Z] ... obtained bool = false

[2022-01-17T05:50:47.116Z] ... got <nil>

[2022-01-17T05:50:47.116Z] 

[2022-01-17T05:50:47.116Z] pessimistic_test.go:1171:

[2022-01-17T05:50:47.116Z]     c.Check(storeerr.ErrLockAcquireFailAndNoWaitSet.Equal(err), IsTrue, Commentf("got %v", err))

[2022-01-17T05:50:47.116Z] ... obtained bool = false

[2022-01-17T05:50:47.116Z] ... got <nil>
```

**Comment by kennytm** [comment]
/run-unit-test

```
[2022-01-17T05:59:18.352Z] panic: runtime error: invalid memory address or nil pointer dereference [recovered]

[2022-01-17T05:59:18.352Z] 	panic: runtime error: invalid memory address or nil pointer dereference

[2022-01-17T05:59:18.352Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x3988064]

[2022-01-17T05:59:18.352Z] 

[2022-01-17T05:59:18.352Z] goroutine 54141 [running]:

[2022-01-17T05:59:18.352Z] testing.tRunner.func1.2(0x3f87b00, 0x6458710)

[2022-01-17T05:59:18.352Z] 	/usr/local/go/src/testing/testing.go:1143 +0x332

[2022-01-17T05:59:18.352Z] testing.tRunner.func1(0xc000882900)

[2022-01-17T05:59:18.352Z] 	/usr/local/go/src/testing/testing.go:1146 +0x4b6

[2022-01-17T05:59:18.352Z] panic(0x3f87b00, 0x6458710)

[2022-01-17T05:59:18.352Z] 	/usr/local/go/src/runtime/panic.go:965 +0x1b9

[2022-01-17T05:59:18.352Z] github.com/pingcap/tidb/executor_test.TestSavedAnalyzeOptions(0xc000882900)

[2022-01-17T05:59:18.352Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze_test.go:1344 +0x1064

[2022-01-17T05:59:18.355Z] testing.tRunner(0xc000882900, 0x46111d0)

[2022-01-17T05:59:18.355Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef

[2022-01-17T05:59:18.355Z] created by testing.(*T).Run

[2022-01-17T05:59:18.355Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
```

**Pull request merged**
