### PR TITLE
sessionctx: enable clustered index by default

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Problem Summary:

The "clustered index" feature has been GA in release-5.0. We decide to change the default value of `tidb_enable_clustered_index` to `ON`, with the following advantages:

- The point get performance in certain scenarios can be improved.
- Compared with the original default value `INT_ONLY`, it is easier to understand for new users.

### What is changed and how it works?

This PR changes the default value of `tidb_enable_clustered_index` to `ON`.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by jackysp — COMMENTED** [review]
Why do you change it now?

**Comment by tangenta** [comment]
@jackysp It is planned in the next release.

**Review by ngaut — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by jackysp** [comment]
There is a risk that TiDB does not support alter primary key yet, so if clustered index is enabled by default, users will have to rebuild the table if they find a serious hotspot problem. @tangenta

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
