### PR TITLE
statistics: remove the dependency of stats GC on LastUpdateVersion

### LINKED ISSUE #23406: trigger stats gc properly
## Development Task

```
MySQL [test]> create table t(a int, b int);
Query OK, 0 rows affected (0.01 sec)

MySQL [test]> insert into t values(1,1),(2,2),(3,3);
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

MySQL [test]> analyze table t;
Query OK, 0 rows affected (0.04 sec)

MySQL [test]> select * from mysql.stats_meta;
+--------------------+----------+--------------+-------+
| version            | table_id | modify_count | count |
+--------------------+----------+--------------+-------+
| 423597320592162816 |       51 |            0 |     3 |
+--------------------+----------+--------------+-------+
1 row in set (0.00 sec)

MySQL [test]> drop table t;
Query OK, 0 rows affected (0.02 sec)

MySQL [test]> select * from mysql.stats_meta;
+--------------------+----------+--------------+-------+
| version            | table_id | modify_count | count |
+--------------------+----------+--------------+-------+
| 423597320592162816 |       51 |            0 |     3 |
+--------------------+----------+--------------+-------+
1 row in set (0.00 sec)
```

Even after 2 stats gc intervals, i.e, 10 mins, the records in `mysql.stats_meta`, `mysql.stats_histograms` and `mysql.stats_buckets` are not removed.

The stats gc can only properly work if there are other stats operations that would update the `LastUpdateVersion` of stats cache in the stats owner.

We should optimize stats gc to remove this assumption.

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Issue Number: close #23406 

Problem Summary:

stats GC cannot be triggered if there is no analyze.

### What is changed and how it works?

What's Changed:

Remove the dependency of stats GC on `LastUpdateVersion`, instead use the current timestamp as the base time, i.e, trigger the stats GC periodically.

### Related changes

N/A

### Check List 

Tests 

- Unit test: to be added
- Manual test: execute the reproduction steps in the issue, the records are removed after 10 mins.

Side effects

N/A

### Release note 

- Remove the dependency of stats GC on LastUpdateVersion

### CODE REVIEW

**Review by Reminiscent — COMMENTED** [review]
Is there any good way to add related tests? Besides, please fix the failed test.

**Comment by eurekaka** [comment]
@Reminiscent I have updated the test cases, the tests in gc_test.go now can cover the code changes in this PR now.

**Review by time-and-fate — APPROVED** [review]
/lgtm

**Review by winoros — APPROVED** [review]

**Pull request merged**
