### PR TITLE
*: Upgrade to go 1.16 && remove deprecated io/ioutil

### PR DESCRIPTION
**Pull request by TennyZhuang**
### What problem does this PR solve?

Problem Summary:

Upgrade to go 1.16

And [Deprecation of io/ioutil](https://golang.org/doc/go1.16#ioutil)

### What is changed and how it works?

How it Works:

```sh
fastmod --accept-all -e go "ioutil\.WriteFile" "os.WriteFile"
fastmod --accept-all -e go "ioutil\.TempFile" "os.CreateTemp"
fastmod --accept-all -e go "ioutil\.TempDir" "os.MkdirTemp"
fastmod --accept-all -e go "ioutil\.ReadFile" "os.ReadFile"
fastmod --accept-all -e go "ioutil\.ReadAll" "io.ReadAll"
fastmod --accept-all -e go "ioutil\.ReadDir" "os.ReadDir"
fastmod --accept-all -e go "ioutil\.NopCloser" "io.NopCloser"
fastmod --accept-all -e go "ioutil\.Discard" "io.Discard"

goimports -w .
```

And a little manual fix in slow_query.go `getAllFiles`

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- No release note

### CODE REVIEW

**Comment by tisonkun** [comment]
ref https://github.com/pingcap/tidb/issues/22198

**Comment by tisonkun** [comment]
@TennyZhuang it seems `go mod tidy` generated a different `go.sum` file. Please resolve diff and push updates.

**Comment by TennyZhuang** [comment]
It still failed on `go mod tidy`

**Comment by TennyZhuang** [comment]
It failed on <github.com/pingcap/tidb-build-plugin>, which is not open source. @tisonkun can you help me to fix it?

**Comment by bb7133** [comment]
Hi @TennyZhuang , we've updated the plugin codes, now the build is fine, thanks for your efforts.

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
