### PR TITLE
expression/aggregation, plan: set PB field type and ExtraHandle column  type

### PR DESCRIPTION
**Pull request by coocood**
## What have you changed? (mandatory)

1. Set the Aggregation expression field type in PB.
2. Set the type for ExtraHandle Column.

## What is the type of the changes? (mandatory)

- Improvement (non-breaking change which is an improvement to an existing feature)

Those are required to implement the chunk execution in the faketikv and mocktikv.

### CODE REVIEW

**Comment by coocood** [comment]
@zz-jason @winoros PTAL

**Comment by zz-jason** [comment]
@coocood "implement chunk execution in the coprocessor" is not on our roadmap

**Comment by zz-jason** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Comment by coocood** [comment]
failed test is caused by the CI environment.
force merged for now.

**Pull request merged**
