### PR TITLE
plugin: keep plugin enable/disable state when tidb restart

### LINKED ISSUE #37922: plugin: The plugin enable/disable state will be lost when restart
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. start a tidb cluster with plugin
2. disable a plugin
3. restart a tidb server
4. `show plugins` to see the plugin's enable/disable state

### 2. What did you expect to see? (Required)

The plugin's state should be disabled after restart.

### 3. What did you see instead (Required)

The plugin's state changes back to enable after restart.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #37922

Problem Summary:

The plugin enable/disable state will be lost when instance restart. This PR fixed this.

### Check List

Tests 

- [x] Manual test (add detailed scripts or steps below)
  - start a tidb instance with plugin
  - `show plugins` returns the default enabled is true
  - `admin plugins disable audit` to disable audit plugin
  - restart tidb server
  - `show plugins` shows the audit plugin is disabled

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
@lcwangchao  have data race found in the real tikv test.
```
[2022-09-19T09:35:12.562Z] WARNING: DATA RACE

[2022-09-19T09:35:12.562Z] Write at 0x00000ad9c410 by goroutine 501:

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/telemetry.postReportNonTransactionalCounter()

[2022-09-19T09:35:12.562Z]       telemetry/data_feature_usage.go:348 +0x2ce

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/telemetry.postReportTelemetryData()

[2022-09-19T09:35:12.562Z]       telemetry/data.go:67 +0x29b

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/telemetry.reportUsageData()

[2022-09-19T09:35:12.562Z]       telemetry/telemetry.go:117 +0x157

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/telemetry.ReportUsageData()

[2022-09-19T09:35:12.562Z]       telemetry/telemetry.go:159 +0xae

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/telemetry.InitialRun()

[2022-09-19T09:35:12.562Z]       telemetry/telemetry.go:177 +0x351

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/domain.(*Domain).TelemetryReportLoop()

[2022-09-19T09:35:12.562Z]       domain/domain.go:1463 +0xc5

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/session.BootstrapSession.func1()

[2022-09-19T09:35:12.562Z]       session/session.go:2808 +0x7a

[2022-09-19T09:35:12.562Z] 

[2022-09-19T09:35:12.562Z] Previous write at 0x00000ad9c410 by goroutine 289:

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/telemetry.postReportNonTransactionalCounter()

[2022-09-19T09:35:12.562Z]       telemetry/data_feature_usage.go:348 +0x2ce

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/telemetry.postReportTelemetryData()

[2022-09-19T09:35:12.562Z]       telemetry/data.go:67 +0x29b

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/telemetry.reportUsageData()

[2022-09-19T09:35:12.562Z]       telemetry/telemetry.go:117 +0x157

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/telemetry.ReportUsageData()

[2022-09-19T09:35:12.562Z]       telemetry/telemetry.go:159 +0xae

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/telemetry.InitialRun()

[2022-09-19T09:35:12.562Z]       telemetry/telemetry.go:177 +0x351

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/domain.(*Domain).TelemetryReportLoop()

[2022-09-19T09:35:12.562Z]       domain/domain.go:1463 +0xc5

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/session.BootstrapSession.func1()

[2022-09-19T09:35:12.562Z]       session/session.go:2808 +0x7a

[2022-09-19T09:35:12.562Z] 

[2022-09-19T09:35:12.562Z] Goroutine 501 (running) created at:

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/session.BootstrapSession()

[2022-09-19T09:35:12.562Z]       session/session.go:2807 +0x874

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/tests/realtikvtest.CreateMockStoreAndDomainAndSetup()

[2022-09-19T09:35:12.562Z]       tests/realtikvtest/testkit.go:103 +0x179

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/tests/realtikvtest.CreateMockStoreAndSetup()

[2022-09-19T09:35:12.562Z]       tests/realtikvtest/testkit.go:79 +0x38

[2022-09-19T09:35:12.562Z]   tests/realtikvtest/brietest/brietest_test.TestForCoverage()

[2022-09-19T09:35:12.562Z]       tests/realtikvtest/brietest/binlog_test.go:54 +0x27

[2022-09-19T09:35:12.562Z]   testing.tRunner()

[2022-09-19T09:35:12.562Z]       GOROOT/src/testing/testing.go:1446 +0x216

[2022-09-19T09:35:12.562Z]   testing.(*T).Run.func1()

[2022-09-19T09:35:12.562Z]       GOROOT/src/testing/testing.go:1493 +0x47

[2022-09-19T09:35:12.562Z] 

[2022-09-19T09:35:12.562Z] Goroutine 289 (running) created at:

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/session.BootstrapSession()

[2022-09-19T09:35:12.562Z]       session/session.go:2807 +0x874

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/tests/realtikvtest.CreateMockStoreAndDomainAndSetup()

[2022-09-19T09:35:12.562Z]       tests/realtikvtest/testkit.go:103 +0x179

[2022-09-19T09:35:12.562Z]   github.com/pingcap/tidb/tests/realtikvtest.CreateMockStoreAndSetup()

[2022-09-19T09:35:12.562Z]       tests/realtikvtest/testkit.go:79 +0xcc

[2022-09-19T09:35:12.562Z]   tests/realtikvtest/brietest/brietest_test.TestBackupAndRestore()

[2022-09-19T09:35:12.562Z]       tests/realtikvtest/brietest/backup_restore_test.go:33 +0xb8

[2022-09-19T09:35:12.562Z]   testing.tRunner()

[2022-09-19T09:35:12.562Z]       GOROOT/src/testing/testing.go:1446 +0x216

[2022-09-19T09:35:12.562Z]   testing.(*T).Run.func1()

[2022-09-19T09:35:12.562Z]       GOROOT/src/testing/testing.go:1493 +0x47

[2022-09-19T09:35:12.562Z] ==================

```

**Pull request merged**
