### PR TITLE
server: store the updated labels into etcd

### LINKED ISSUE #51427: update labels API not work for some modules
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. start a tidb server
2. check there are no labels
```bash
curl 127.0.0.1:10080/info/all
{
 "servers_num": 1,
 "owner_id": "d807298d-d747-4ded-b896-480beceed704",
 "is_all_server_version_consistent": true,
 "all_servers_info": {
  "d807298d-d747-4ded-b896-480beceed704": {
   "version": "8.0.11-TiDB-v8.0.0-alpha-208-gf0a26dd2a3",
   "git_hash": "f0a26dd2a36d688d9a691302edb5429d1f15e351",
   "ddl_id": "d807298d-d747-4ded-b896-480beceed704",
   "ip": "127.0.0.1",
   "listening_port": 4000,
   "status_port": 10080,
   "lease": "45s",
   "binlog_status": "Off",
   "start_timestamp": 1709205226,
   "labels": {},
   "server_id": 914
  }
 }
}
```

3. update labels

```bash
curl -X POST -d "{\"foo\": \"bar\"}" 127.0.0.1:10080/labels
{
 "foo": "bar"
}%
```
Also check the log

```log
[2024/02/29 20:16:50.815 +09:00] [INFO] [tikv_handler.go:2005] ["update server labels"] [labels="{\"foo\":\"bar\"}"]
```

4. check the labels again by `curl 127.0.0.1:10080/info/all`

### 2. What did you expect to see? (Required)

```bash
curl 127.0.0.1:10080/info/all
{
 "servers_num": 1,
 "owner_id": "d807298d-d747-4ded-b896-480beceed704",
 "is_all_server_version_consistent": true,
 "all_servers_info": {
  "d807298d-d747-4ded-b896-480beceed704": {
   "version": "8.0.11-TiDB-v8.0.0-alpha-208-gf0a26dd2a3",
   "git_hash": "f0a26dd2a36d688d9a691302edb5429d1f15e351",
   "ddl_id": "d807298d-d747-4ded-b896-480beceed704",
   "ip": "127.0.0.1",
   "listening_port": 4000,
   "status_port": 10080,
   "lease": "45s",
   "binlog_status": "Off",
   "start_timestamp": 1709205226,
   "labels": {"foo": "bar"}, // there should be labels
   "server_id": 914
  }
 }
}
```

### 3. What did you see instead (Required)

```bash
curl 127.0.0.1:10080/info/all
{
 "servers_num": 1,
 "owner_id": "d807298d-d747-4ded-b896-480beceed704",
 "is_all_server_version_consistent": true,
 "all_servers_info": {
  "d807298d-d747-4ded-b896-480beceed704": {
   "version": "8.0.11-TiDB-v8.0.0-alpha-208-gf0a26dd2a3",
   "git_hash": "f0a26dd2a36d688d9a691302edb5429d1f15e351",
   "ddl_id": "d807298d-d747-4ded-b896-480beceed704",
   "ip": "127.0.0.1",
   "listening_port": 4000,
   "status_port": 10080,
   "lease": "45s",
   "binlog_status": "Off",
   "start_timestamp": 1709205226,
   "labels": {}, // there are no labels instead
   "server_id": 914
  }
 }
}
```

### 4. What is your TiDB version? (Required)

```
Release Version: v8.0.0-alpha-208-gf0a26dd2a3
Edition: Community
Git Commit Hash: f0a26dd2a36d688d9a691302edb5429d1f15e351
Git Branch: HEAD
UTC Build Time: 2024-02-06 03:48:06
GoVersion: go1.21.6
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

### PR DESCRIPTION
**Pull request by you06**
### What problem does this PR solve?

Issue Number: close #51427

Problem Summary:

### What changed and how does it work?

Update the latest labels to etcd when label api is called.

### Check List

Tests 

- [x] Unit test
- [] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Ran the case described in the issue now got:

```bash
~ » curl 127.0.0.1:10080/info/all
{
...
   "labels": {},
...
}%
----------------------------------------------------------------------------------
~ » curl -X POST -d "{\"foo\": \"bar\"}" 127.0.0.1:10080/labels
{
 "foo": "bar"
}%
----------------------------------------------------------------------------------
~ » curl 127.0.0.1:10080/info/all
{
...
   "labels": {
    "foo": "bar"
   },
...
 }
}%
----------------------------------------------------------------------------------
~ » curl -X POST -d "{\"foo\": \"tidb\"}" 127.0.0.1:10080/labels                                                                                                                                                                                               you06@you06s-MBP
{
 "foo": "tidb"
}%
----------------------------------------------------------------------------------
~ » curl 127.0.0.1:10080/info/all
{
...
   "labels": {
    "foo": "tidb"
   },
...
}%
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by you06** [comment]
@glorv PTAL

**Review by glorv — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by zimulala — APPROVED** [review]

**Pull request merged**
