### PR TITLE
planner: fix tidb can point update data even if tidb_super_read_only is on (#32547)

### LINKED ISSUE #32539: tidb can point update data even if tidb_super_read_only is on
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t (a int primary key, b int)
insert into t values (1, 2), (3, 4);
set global tidb_restricted_read_only=1;
update table t set b = 1 where a = 1;
```

### 2. What did you expect to see? (Required)

```
ERROR 1836 (HY000): Running in read-only mode
```

### 3. What did you see instead (Required)

```
Query OK, 1 row affected (0.002 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #32547 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/32551
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/32551:release-5.3-221801b5525c
```

---

### What problem does this PR solve?

Issue Number: close #32539

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by guo-shaoge — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]

**Review by guo-shaoge — APPROVED** [review]

**Comment by ichn-hu** [comment]
the unstable test is fixed in https://github.com/pingcap/tidb/pull/30716 on master but not cherry picked

**Pull request merged**
