### PR TITLE
executor: fix analyze update panic cause by duplicate call analyze executor Close method (#20390)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20390 to release-4.0

---

### What problem does this PR solve?

Close https://github.com/pingcap/tidb/issues/20389

related PR: https://github.com/pingcap/tidb/pull/19106

### Related changes

- No.

### Check List 

Tests 

- Unit test

Side effects

- No

### Release note 

- No

### CODE REVIEW

**Comment by crazycs520** [comment]
@SunRunAway @tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Review by SunRunAway — APPROVED** [review]

**Pull request merged**
