### PR TITLE
util: Change the output dir of the PLAN REPLAYER to be temp_dir

### LINKED ISSUE #55513: Allow to specify diagnostics folder
## Enhancement

TiDB Server piggybacks on [--log-file](https://docs.pingcap.com/tidb/stable/command-line-flags-for-tidb-configuration#--log-file) param or [filename](https://docs.pingcap.com/tidb/dev/tidb-configuration-file#filename) config to define a folder where to put diagnostic data emitted by [PLAN REPLAYER](https://docs.pingcap.com/tidb/v8.2/sql-plan-replayer#use-plan-replayer-to-save-and-restore-the-on-site-information-of-a-cluster) or `oom_record` from [excessive memory usage](https://docs.pingcap.com/tidb/stable/configure-memory-usage#trigger-the-alarm-of-excessive-memory-usage).

The default value of [filename](https://docs.pingcap.com/tidb/dev/tidb-configuration-file#filename) is empty string `""`, which translates to the working directory. In the container world it translates to the root directory `"/"` unless overridden in the container file. [TiDB Dockerfile](https://github.com/PingCAP-QE/artifacts/blob/8c68fc33a780e2c83b3f69133c17682385753192/dockerfiles/cd/builders/tidb/Dockerfile#L43) explicitly sets it to  the root directory as well.

Note that if [filename](https://docs.pingcap.com/tidb/dev/tidb-configuration-file#filename)  is specified, the tidb-server logs stops going to the system output, which breaks easy log access using `kubectl log` command and breaks standard log export setup for kubernetes clusters.

Please consider to add a command line flag or system variable to specify the directory for the diagnostic data mentioned above.

### PR DESCRIPTION
**Pull request by mengxian-li**
### What problem does this PR solve?

Issue Number: close #55513

Problem Summary: 
@Tema 

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Verified in a test cluster that the PLAN REPLAYER worked:
```
use test;
mysql> create table replayer_test(a int, b int);
mysql> insert into replayer_test values(1,1), (2, 2), (3, 3);
mysql> analyze table replayer_test;
mysql> plan replayer dump explain select * from replayer_test;
+-----------------------------------------------------------+
| File_token                                                |
+-----------------------------------------------------------+
| replayer_3kAIFhAJ2gJPs9qLL__K4Q==_1734048775715226847.zip |
+-----------------------------------------------------------+
1 row in set (0.17 sec)
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by mengxian-li** [comment]
Looks like the `fast_test_tiprow` failed with:
```
FATAL: Could not find system javabase. Ensure JAVA_HOME is set, or javac is on your PATH.
```
@hawkingrei Do you have idea of what's going wrong there?

**Comment by hawkingrei** [comment]
@mengxian-li You need to sync code with master.

**Review by hawkingrei — APPROVED** [review]

**Comment by mengxian-li** [comment]
@hawkingrei I synced with master, but `fast_test_tiprow` still failed

**Comment by mengxian-li** [comment]
@hawkingrei Could you stamp on the latest commit?

**Review by qw4990 — APPROVED** [review]

**Comment by hawkingrei** [comment]
> @hawkingrei Could you stamp on the latest commit?

OK, I have checked it. it is great.

**Pull request merged**
