### PR TITLE
cherry pick some commit about pump client to release 2.0

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
### What problem does this PR solve? 
cherry pick some commit about pump client to release 2.0

### What is changed and how it works?
git cherry-pick {commit}

### Check List 

Related changes
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Comment by lysu** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by WangXiangUSTC** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by zz-jason** [comment]
LGTM

**Pull request closed without merging**
