### PR TITLE
ddl: compare expression in check partition definition according to column type (#21226)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21226 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/21227
close https://github.com/pingcap/tidb/issues/21225

Problem Summary:

it is a patch of https://github.com/pingcap/tidb/pull/20937, we cannot compare datetime, date, time type column as string type

### Check List 

Tests 

- Unit test

### Release note 

- fix a bug that checks partition definition according to column type

### CODE REVIEW

**Comment by xiongjiwei** [comment]
@tiancaiamao @crazycs520 PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Review by crazycs520 — APPROVED** [review]
LGTM

**Review by tiancaiamao — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Review by SunRunAway — APPROVED** [review]

**Pull request merged**
