### PR TITLE
session: directly get txn from session in runStmt

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
1. We don't active txn in `runStmt`, so it doesn't need to use Txn(false) to get the txn, we could use the txn in session directly.
1. When pass false to Txn(), maybe return without an error is a little clear.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:
Change them as summary said.

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM

**Comment by jackysp** [comment]
PTAL @lysu @coocood

**Comment by coocood** [comment]
LGTM

**Pull request merged**
