### PR TITLE
*: add super privilege check for some admin commands

### LINKED ISSUE #51366: Some admin command can be executed without super privilege
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql -utest -h127.0.0.1 -P4000 -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1350565896
Server version: 8.0.11-TiDB-v8.0.0-alpha-253-gd96244d34b TiDB Server (Apache License 2.0) Community Edition, MySQL 8.0 compatible

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> admin reload expr_pushdown_blacklist;
Query OK, 0 rows affected (0.00 sec)

mysql> admin plugins enable p;
ERROR 1105 (HY000): plugin 'p' not found
-- plugin should exist similar bug

mysql> ADMIN FLUSH bindings;
Query OK, 0 rows affected (0.00 sec)

mysql> ADMIN CAPTURE bindings;
Query OK, 0 rows affected (0.01 sec)

mysql> ADMIN RELOAD bindings;
Query OK, 0 rows affected (0.00 sec)

mysql> show plugins;
Empty set (0.00 sec)

mysql> SHOW GRANTS FOR 'test'@'%';
+----------------------------------+
| Grants for test@%                |
+----------------------------------+
| GRANT USAGE ON *.* TO 'test'@'%' |
+----------------------------------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)

```sql
Error 8121 (HY000): privilege check for 'Super' fail
```

### 3. What did you see instead (Required)

Executed successfully

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #51366

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
add super privilege checks for some admin commands
```

### CODE REVIEW

**Review by songrijie — APPROVED** [review]
Along with the privilege enforcement, we shall include extra dynamic privileges ASAP that allows non-root users share the admin operations. //cc @ljun0712 

The given list in this PR looks fine to me.

**Review by qw4990 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Comment by ljun0712** [comment]
LGTM. 
The parts related to SUPER permissions will be adjusted in the future.

**Pull request merged**
