### PR TITLE
expression: implement functionClass and builtinFunction for some funcs.

### PR DESCRIPTION
**Pull request by hanfei1991**
refactor step by step.
@shenli @coocood @zimulala @tiancaiamao PTAL

### CODE REVIEW

**Comment by c4pt0r** [comment]
What about some tests?

**Comment by hanfei1991** [comment]
@c4pt0r test has exists for builtin****. After we finish the refactor, we will add test for `eval`

**Comment by zimulala** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
