### PR TITLE
types: fix incorrect order of set resultFrac

### LINKED ISSUE #7781: Precision of aggregation's result for exact value is wrong.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create table t(a int, b int);
insert into t values(1, 0), (2, 1), (2, 2);
select avg(b) from t group by a;
```

2. What did you expect to see?
The result should be `0.0000` and `1.500`.

3. What did you see instead?
It's `0` and `1.500`.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master with commit f387dfff09068f1bde478a287897a03e0dabcf6f.

### PR DESCRIPTION
**Pull request by Kingwl**
### What problem does this PR solve? 
fix #7781 

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by shenli** [comment]
@Kingwl Thanks!

**Comment by winoros** [comment]
I reviewed the code in `doDivMod`. Seems that this is caused by assign `zeroMyDecimal` to `to`. Thus the modification on `resultFrac` is lost.
So we need to fix the similar case in `DecimalAdd`, `DecimalSub` and some other method?

**Comment by Kingwl** [comment]
in this pr or another?🌚

**Comment by winoros** [comment]
You can do those in this pr too. Thanks!

**Comment by winoros** [comment]
@Kingwl 
I'll fix the test in private repo. Don't worry for that.

**Comment by Kingwl** [comment]
I'm not sure that how to add others test case and not break anything

**Comment by winoros** [comment]
@Kingwl 
Add test case like `-1 + 1` is okay?

**Comment by winoros** [comment]
Hi @Kingwl , there's a test https://paste.ubuntu.com/p/fHG5jZCYY4/ , where the order of `0.0000000` and `0.0000` in the result is not stable.
Would you please to investigate it?

**Comment by Kingwl** [comment]
sure

**Comment by Kingwl** [comment]
tracked at https://github.com/pingcap/tidb/pull/7853

**Pull request closed without merging**
