### PR TITLE
planner: when pushing `topN` down below `proj`, check whether `topN.ByItems` contains a column(with ID=0) generated by `proj`

### LINKED ISSUE #40535: invalid memory address or nil pointer dereference during find_best_task
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `eda2f928-9e08-4a11-b0a2-c9c74ac67a3d` (
  `b0dceb86-8cc7-4793-8399-267b6203bd9e` bigint(20) NOT NULL DEFAULT '-2312745469307452950',
  `d7680f00-2bcc-47e7-a824-578f02596c62` datetime DEFAULT '5316-02-03 06:54:49',
  `43856708-fe5e-4621-a5f6-5bcae4388dbe` tinyblob DEFAULT NULL,
  PRIMARY KEY (`b0dceb86-8cc7-4793-8399-267b6203bd9e`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `6b47f970-0e36-4b97-bf5f-c10a5f8e87d2` (
  `eb6dac0f-faf2-460e-b9cd-12c09d34ed02` set('kn8pu','7et','vekx6','v3','liwrh','q14','1met','nnd5i','5o0','8cz','l') DEFAULT '7et,vekx6,liwrh,q14,1met',
  `8ff9cf50-5f41-41ab-945c-0d3294b2df9d` float DEFAULT '1.683167',
  KEY `458a28d4-3bed-42ea-bad6-5166af85b71d` (`8ff9cf50-5f41-41ab-945c-0d3294b2df9d`,`eb6dac0f-faf2-460e-b9cd-12c09d34ed02`),
  KEY `ffa721d4-f094-4a56-9f73-27bf4fb75b4f` (`8ff9cf50-5f41-41ab-945c-0d3294b2df9d`)
) ENGINE=InnoDB DEFAULT CHARSET=gbk COLLATE=gbk_chinese_ci;

( select   /*+ agg_to_cop()  */  locate( `eda2f928-9e08-4a11-b0a2-c9c74ac67a3d`.`43856708-fe5e-4621-a5f6-5bcae4388dbe` , `eda2f928-9e08-4a11-b0a2-c9c74ac67a3d`.`43856708-fe5e-4621-a5f6-5bcae4388dbe` ) as r0 , `eda2f928-9e08-4a11-b0a2-c9c74ac67a3d`.`43856708-fe5e-4621-a5f6-5bcae4388dbe` as r1 from `eda2f928-9e08-4a11-b0a2-c9c74ac67a3d` where not( IsNull( `eda2f928-9e08-4a11-b0a2-c9c74ac67a3d`.`b0dceb86-8cc7-4793-8399-267b6203bd9e` ) )   order by r0,r1  ) union all ( select     concat_ws(',', `6b47f970-0e36-4b97-bf5f-c10a5f8e87d2`.`8ff9cf50-5f41-41ab-945c-0d3294b2df9d` , `6b47f970-0e36-4b97-bf5f-c10a5f8e87d2`.`eb6dac0f-faf2-460e-b9cd-12c09d34ed02` ) as r0 , `6b47f970-0e36-4b97-bf5f-c10a5f8e87d2`.`eb6dac0f-faf2-460e-b9cd-12c09d34ed02` as r1 from `6b47f970-0e36-4b97-bf5f-c10a5f8e87d2`    order by r0,r1  ) order by 1 limit 273;
```

### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
```
[conn.go:1058] ["connection running loop panic"] [conn=223449350066407177] [lastSQL="( select   /*+ agg_to_cop()  */  locate( `eda2f928-9e08-4a11-b0a2-c9c74ac67a3d`.`43856708-fe5e-4621-a5f6-5bcae4388dbe` , `eda2f928-9e08-4a11-b0a2-c9c74ac67a3d`.`43856708-fe5e-4621-a5f6-5bcae4388dbe` ) as r0 , `eda2f928-9e08-4a11-b0a2-c9c74ac67a3d`.`43856708-fe5e-4621-a5f6-5bcae4388dbe` as r1 from `eda2f928-9e08-4a11-b0a2-c9c74ac67a3d` where not( IsNull( `eda2f928-9e08-4a11-b0a2-c9c74ac67a3d`.`b0dceb86-8cc7-4793-8399-267b6203bd9e` ) )   order by r0,r1  ) union all ( select     concat_ws(',', `6b47f970-0e36-4b97-bf5f-c10a5f8e87d2`.`8ff9cf50-5f41-41ab-945c-0d3294b2df9d` , `6b47f970-0e36-4b97-bf5f-c10a5f8e87d2`.`eb6dac0f-faf2-460e-b9cd-12c09d34ed02` ) as r0 , `6b47f970-0e36-4b97-bf5f-c10a5f8e87d2`.`eb6dac0f-faf2-460e-b9cd-12c09d34ed02` as r1 from `6b47f970-0e36-4b97-bf5f-c10a5f8e87d2`    order by r0,r1  ) order by 1 limit 273"] [err="runtime error: invalid memory address or nil pointer dereference"] [stack="github.com/pingcap/tidb/server.(*clientConn).Run.func1\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1061\nruntime.gopanic\n\t/usr/local/go1.19.3/src/runtime/panic.go:884\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile.func1\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/executor/compiler.go:70\nruntime.gopanic\n\t/usr/local/go1.19.3/src/runtime/panic.go:884\nruntime.panicmem\n\t/usr/local/go1.19.3/src/runtime/panic.go:260\nruntime.sigpanic\n\t/usr/local/go1.19.3/src/runtime/signal_unix.go:835\ngithub.com/pingcap/tidb/planner/core.(*PhysicalTopN).getPushedDownTopN\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/task.go:926\ngithub.com/pingcap/tidb/planner/core.(*PhysicalTopN).attach2Task\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/task.go:976\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).enumeratePhysicalPlans4Task\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:252\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).findBestTask\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:440\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).enumeratePhysicalPlans4Task\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:224\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).findBestTask\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:440\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).enumeratePhysicalPlans4Task\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:224\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).findBestTask\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:440\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).enumeratePhysicalPlans4Task\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:224\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).findBestTask\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:440\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).enumeratePhysicalPlans4Task\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:224\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).findBestTask\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:440\ngithub.com/pingcap/tidb/planner/core.physicalOptimize\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:947\ngithub.com/pingcap/tidb/planner/core.DoOptimize\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:296\ngithub.com/pingcap/tidb/planner.optimize\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/optimize.go:426\ngithub.com/pingcap/tidb/planner.Optimize\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/optimize.go:254\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/executor/compiler.go:114\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2184\ngithub.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/driver_tidb.go:247\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmt\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:2093\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1943\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1374\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1123\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:625"]
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Dousir9**
### What problem does this PR solve?

Issue Number: close #40535 

Problem Summary:

The minimal reproduce step can be simplified to:
```sql
CREATE TABLE `t1` (
  `c1` bigint(20) NOT NULL DEFAULT '-2312745469307452950',
  `c2` datetime DEFAULT '5316-02-03 06:54:49',
  `c3` tinyblob DEFAULT NULL,
  PRIMARY KEY (`c1`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `t2` (
  `c1` set('kn8pu','7et','vekx6','v3','liwrh','q14','1met','nnd5i','5o0','8cz','l') DEFAULT '7et,vekx6,liwrh,q14,1met',
  `c2` float DEFAULT '1.683167',
  KEY `k1` (`c2`,`c1`),
  KEY `k2` (`c2`)
) ENGINE=InnoDB DEFAULT CHARSET=gbk COLLATE=gbk_chinese_ci;

( select   /*+ agg_to_cop()  */  locate( `t1`.`c3` , `t1`.`c3` ) as r0 , `t1`.`c3` as r1 from `t1` where not( IsNull( `t1`.`c1` ) )   order by r0,r1  ) union all ( select     concat_ws(',', `t2`.`c2` , `t2`.`c1` ) as r0 , `t2`.`c1` as r1 from `t2`    order by r0,r1  ) order by 1 limit 273;
```

logical plan before `logicalOptimize`:

```sql
*core.LogicalLimit
  *core.LogicalSort
    *core.LogicalUnionAll
      *core.LogicalProjection
        *core.LogicalSort
          *core.LogicalProjection
            *core.DataSource
      *core.LogicalProjection
        *core.LogicalSort
          *core.LogicalProjection
            *core.DataSource   
```

logical plan after `logicalOptimize`:

```sql
*core.LogicalTopN
  *core.LogicalUnionAll
    *core.LogicalProjection
      *core.LogicalProjection
        *core.LogicalTopN
          *core.DataSource
    *core.LogicalProjection
      *core.LogicalProjection
        *core.LogicalTopN <-
          *core.DataSource
```

In  `planner/core/task.go:*PhysicalTopN.attach2Task`： `TopN.ByItems` contains a column that cannot be obtained from `copTask.indexPlan`, so the optimizer chooses to use `copTask.tablePlan`, but `copTask.tablePlan` is `nil`,  this results in "null pointer dereference".

### What is changed and how it works?
There is a column in `topN.ByItems` is generated by `proj`, when `topN` is pushed down below `proj`, `topN` cannot obtain the column from datasource, to fix this, we can check whether `topN.ByItems` contains a column(with ID=0) generated by `proj`, if so, `proj` will prevent the optimizer from pushing `topN` down.
1. A column with ID=0 indicates that the column cannot be resolved by data source.
2. To determine whether a column is generated by projection, we can check whether the child of proj contains the column.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
Please put the test into the existing file.

**Comment by Dousir9** [comment]
> You mentioned that the TopN has a column that cannot be resolved by the data source? If so, that top-n should not be pushed down from the `Projection` via `LogicalProjection.pushDownTopN`.
> 
> So could you show me what's the `ByItems` of the wrong `TopN`?
> 
> A better way to fix it is that you should change the code of the `LogicalProjection.pushDownTopN` instead of the `LogicalSort.pushDownTopN`

The `ByItems` of the wrong `TopN` is `[cast(to_binary(Column#8), longblob)]` and the `Column#8` is generated by Projection. Since `TopN` is pushed down below `proj` , the task type could be `copTask`, after checking `ByItems`, the optimizer thinks that `TopN` is allowed to be pushed down to TiKV/TiFlash, but DataSource indexPlan did not contain `Column#8`, causing the query optimizer to choose tablePlan, but tablePlan is nil.

You are right, I will change the code of `LogicalProjection.pushDownTopN` instead of the `LogicalSort.pushDownTopN`.

**Review by wjhuang2016 — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Comment by Dousir9** [comment]
@qw4990  please comment /ok-to-test, thanks.

**Comment by wjhuang2016** [comment]
Some tests failed, please fix them

**Comment by Dousir9** [comment]
@qw4990 @wjhuang2016  I have changed code and "What is changed and how it works?".

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
