### PR TITLE
planner,privilege: requires extra privileges for REPLACE and INSERT ON DUPLICATE statements

### LINKED ISSUE #23909: Users with only Insert privilege can perform `REPLACE` on that table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

As root:

```sql
create user rrrr;
create table t(a int primary key, b text);
insert into t values (1, 'aa'), (2, 'bb');
grant select, insert on t to rrrr;
```

As user `rrrr`:

```sql
replace into test.t values (1, 'oh no');
```

### 2. What did you expect to see? (Required)

User `rrrr` should not be able to execute the REPLACE:

```
ERROR 1142 (42000): DELETE command denied to user 'rrrr'@'localhost' for table 't'
```

### 3. What did you see instead (Required)

The REPLACE completed successfully:

```
mysql> replace into test.t values (1, 'oh no');
Query OK, 2 rows affected (0.09 sec)
```

The row is indeed replaced:

```
mysql> select * from t;
+---+-------+
| a | b     |
+---+-------+
| 1 | oh no |
| 2 | bb    |
+---+-------+
```

### 4. What is your TiDB version? (Required)

1. v4.0.12
2. a certain old master version at 8ddd41c960caaebbdeb28da33c781fca1464f05f

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve?

Issue Number: close #23909

Problem Summary:

The REPLACE statements requires Insert+Delete privileges, and INSERT INTO ON DUPLICATE requires Insert+Update privileges, but currently TiDB only checks for the Insert privilege, allowing users to delete or change records even without the permission.

### What is changed and how it works?

Add back the extra privilege check when the InsertStmt contains the OnDuplicate clause or IsReplace.

### Related changes

- Need to cherry-pick to the release branch
    * release-4.0, release-5.0

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- Users now need both Insert and Delete privileges on a table to perform REPLACE.
- Users now need both Insert and Update privileges on a table to perform INSERT … ON DUPLICATE KEY UPDATE.

### CODE REVIEW

**Comment by morgo** [comment]
The unit tests are currently failing against master. See: https://github.com/pingcap/tidb/pull/23910

**Review by crazycs520 — APPROVED** [review]
lgtm

**Pull request merged**
