### PR TITLE
statistics: migrate test-infra to testify for statistics_test.go

### LINKED ISSUE #28123: migrate test-infra to testify for `statistics/statistics_test.go`

### PR DESCRIPTION
**Pull request by feitian124**
### What problem does this PR solve?

Issue Number: close #28123 

notice: serial tests and their helper methods moved to statistics_serial_test.go

### Release note
```release-note
None
```

### CODE REVIEW

**Comment by feitian124** [comment]
ci failed due to 

```
[2021-10-07T15:38:04.703Z] ./tools/check/check-tidy.sh
[2021-10-07T15:38:04.703Z] testSuite
[2021-10-07T15:38:04.703Z] ./tools/check/check_testSuite.sh
[2021-10-07T15:38:04.703Z] testStatisticsSuite in ./statistics is not enabled
[2021-10-07T15:38:04.703Z] make: *** [testSuite] Error 1
```

**Comment by feitian124** [comment]
ci fails due to https://github.com/pingcap/tidb/issues/27889

```
[2021-10-08T11:58:21.339Z] FAIL: db_partition_test.go:2181: testIntegrationSuite5.TestTruncatePartitionAndDropTable
[2021-10-08T11:58:21.339Z] 
[2021-10-08T11:58:21.339Z] db_partition_test.go:2282:
[2021-10-08T11:58:21.339Z]     c.Assert(hasOldPartitionData, IsFalse)
[2021-10-08T11:58:21.339Z] ... obtained bool = true
```
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/37185/pipeline

**Comment by tisonkun** [comment]
> notice the last commit add an useless line to workaround for tools/check/check_testSuite.sh not sure what is a better way, rename the struct name? disable the check?

Rename the suite could work, let me try to push a follow up for you to resolve conflict as well as workaround this check

**Comment by feitian124** [comment]
> Could you elaborate how you determinate serial tests? That is, how you decide a test should be run in serial or in parallel.

check the first commit, you can find there are 2 suites, one is `testSerialIntegrationSuite`

**Comment by feitian124** [comment]
> @feitian124 I don't find one. Do you mix it up with #28693 ? I find all tests under `testStatisticsSuite`.

@tisonkun sorry i mix it up.
i find them by test, if add `t.parallal` they will fail, and i noticed they all called `buildIndex`, so i guess this maybe the reason.
but i did not find the true reason...

**Comment by feitian124** [comment]
`buildIndex(ctx, 256, 1, s.rc)` shares `s.rc`(which is a interface type),  so  pass like slice, 
so `req := records.NewChunk()` shoud be a shared variable?

**Comment by tisonkun** [comment]
/cc @rebelice 

Could you please take a look at this PR?

**Pull request merged**
