### PR TITLE
Incremental restore: fix the issue that backfill data is not covered by newTS

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/54426

Problem Summary:
see https://github.com/pingcap/tidb/issues/54426#issuecomment-2208088735
### What changed and how does it work?
make sure the rewritten data cover the backfilled data.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
 fix the issue that backfill ddls(add index/modify column) may not restored correctly during incremental restore.
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]
It may be worth noting that
`Restore GC Safepoint TS` < `DDL ts` < `Incremental kv Rewrite ts`

**Review by YuJuncen — APPROVED** [review]

**Pull request merged**
