### PR TITLE
ddl: rename table name for test add/drop index.

### PR DESCRIPTION
**Pull request by hicqu**
Previously there is same table name between add/drop index test cases. Sometimes those cases will confict with each other. This PR fix it.

### CODE REVIEW

**Comment by zimulala** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Comment by tiancaiamao** [comment]
Please resolve conflicts. @hicqu

**Comment by hicqu** [comment]
@tiancaiamao , PTAL, thanks.

**Pull request merged**
