### PR TITLE
planner: fix CTE bug when MergeJoin is used (#25514)

### LINKED ISSUE #25474: Got error when use merge_join hint in CTE
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

    drop table if exists t1, t2;
    create table t1(c1 int);
    insert into t1 values(1), (2), (1), (2);
    create table t2(c1 int primary key);
    insert into t2 values(1), (2), (3);
    with recursive cte1(c1) as (select c1 from t1 union select c1 + 1 c1 from t1 where c1 < 3) select /*+ MERGE_JOIN(dt1, dt2) */ * from cte1 dt1 left join t1 dt2 on dt1.c1 = dt2.c1 order by dt1.c1, dt2.c1;

### 2. What did you expect to see? (Required)

    mysql>     with recursive cte1(c1) as (select c1 from t1 union select c1 + 1 c1 from t1 where c1 < 3) select /*+ MERGE_JOIN(dt1, dt2) */ * from cte1 dt1 left join t1 dt2 on dt1.c1 = dt2.c1 order by dt1.c1, dt2.c1;
    +------+------+
    | c1   | c1   |
    +------+------+
    |    1 |    1 |
    |    1 |    1 |
    |    2 |    2 |
    |    2 |    2 |
    |    3 | NULL |
    +------+------+
    5 rows in set (0.00 sec)
### 3. What did you see instead (Required)

    mysql>     with recursive cte1(c1) as (select c1 from t1 union select c1 + 1 c1 from t1 where c1 < 3) select /*+ MERGE_JOIN(dt1, dt2) */ * from cte1 dt1 left join t1 dt2 on dt1.c1 = dt2.c1 order by dt1.c1, dt2.c1;
    ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query
### 4. What is your TiDB version? (Required)

master and 5.1

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25514 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/26658
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/26658:release-5.1-57d704bffed5
```

---

Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #25474 

Problem Summary: When use MERGE JOIN to join a CTE table, planner give errors

    mysql>     with recursive cte1(c1) as (select c1 from t1 union select c1 + 1 c1 from t1 where c1 < 3) select /*+ MERGE_JOIN(dt1, dt2) */ * from cte1 dt1 left join t1 dt2 on dt1.c1 = dt2.c1 order by dt1.c1, dt2.c1;
    ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query

### What is changed and how it works?

What's Changed: Change logic in `LogicalCTE.findBestTask`, when prop requires sort item, we add a sort operator explicitly.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects: no

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- planner: fix CTE bug when MergeJoin is used

### CODE REVIEW

**Comment by guo-shaoge** [comment]
It's better to merge this pr after #26661 is merged. Otherwise may got conflicts.

**Review by AilinKid — APPROVED** [review]

**Review by xuyifangreeneyes — APPROVED** [review]

**Pull request merged**
