### PR TITLE
expression: Fix JSON quote | tidb-test=pr/2343

### LINKED ISSUE #37294: `json_quote` return different result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (c varchar(20) collate utf8mb4_bin) charset utf8mb4;
insert into t values ('\\');
insert into t values (X'0C');
insert into t values ('"');
insert into t values ('\a');
insert into t values ('\b');
insert into t values ('\t');
insert into t values ('\n');
insert into t values ('\r');
insert into t values (X'10');
select json_quote(group_concat(c order by c, hex(c))) from t;
```

### 2. What did you expect to see? (Required)

```sql
"\b,\t,\n,\f,\r,\u0010,\",\\,a"
```

### 3. What did you see instead (Required)

```
"\b,\t,\n,\f,\r,\x10,\",\\,a"
```

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #37294

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
The `JSON_QUOTE()` function was updated to use unicode escapes in a more MySQL compatible way
```

### CODE REVIEW

**Comment by dveeden** [comment]
```
mysql> WITH RECURSIVE nr(n) AS (SELECT 1 n UNION ALL SELECT n+1 FROM nr WHERE n<25) SELECT JSON_QUOTE(CONVERT(UNHEX(n) USING utf8mb4)) FROM nr;
+---------------------------------------------+
| JSON_QUOTE(CONVERT(UNHEX(n) USING utf8mb4)) |
+---------------------------------------------+
| "\u0001"                                    |
| "\u0002"                                    |
| "\u0003"                                    |
| "\u0004"                                    |
| "\u0005"                                    |
| "\u0006"                                    |
| "\u0007"                                    |
| "\b"                                        |
| "\t"                                        |
| "\u0010"                                    |
| "\u0011"                                    |
| "\u0012"                                    |
| "\u0013"                                    |
| "\u0014"                                    |
| "\u0015"                                    |
| "\u0016"                                    |
| "\u0017"                                    |
| "\u0018"                                    |
| "\u0019"                                    |
| " "                                         |
| "!"                                         |
| "\""                                        |
| "#"                                         |
| "$"                                         |
| "%"                                         |
+---------------------------------------------+
25 rows in set (0.00 sec)

mysql> SELECT TIDB_VERSION()\G
*************************** 1. row ***************************
TIDB_VERSION(): Release Version: v8.2.0-alpha-332-g65bea5c15e
Edition: Community
Git Commit Hash: 65bea5c15e69cd22a9f9a28896f32aba5aedb4d7
Git Branch: json_quote_fix
UTC Build Time: 2024-06-12 08:18:30
GoVersion: go1.22.3
Race Enabled: false
Check Table Before Drop: false
Store: unistore
1 row in set (0.00 sec)

mysql> 
```

**Comment by dveeden** [comment]
Not exactly the same, but much closer:
image

**Comment by dveeden** [comment]
Found a difference for invalid characters:

MySQL:
```
mysql-8.4.0> SELECT JSON_QUOTE(CONVERT(0x80 USING utf8mb4));
+-----------------------------------------+
| JSON_QUOTE(CONVERT(0x80 USING utf8mb4)) |
+-----------------------------------------+
| NULL                                    |
+-----------------------------------------+
1 row in set, 1 warning (0.00 sec)

Warning (Code 1300): Invalid utf8mb4 character string: '80'
mysql-8.4.0> 
```

TiDB:
```
mysql> SELECT JSON_QUOTE(CONVERT(0x80 USING utf8mb4));
+-----------------------------------------+
| JSON_QUOTE(CONVERT(0x80 USING utf8mb4)) |
+-----------------------------------------+
| NULL                                    |
+-----------------------------------------+
1 row in set (0.00 sec)
```
Note that this happens on TiDB both with and without this PR.

**Comment by dveeden** [comment]
I found a _small_ issue:

I developed this with Go 1.22. Some results are different with Go 1.21 and below because of the following:

https://tip.golang.org/doc/go1.22

> encoding/json
> 
> Marshaling and encoding functionality now escapes '\b' and '\f' characters as \b and \f instead of \u0008 and \u000c.

**Review by hawkingrei — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
