### PR TITLE
config, kv: make TxnEntryCountLimit and TxnTotalSizeLimit configurable (#9035)

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve? 
Cherry pick #9035 to release 2.1.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

### CODE REVIEW

**Comment by jackysp** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by disksing** [comment]
LGTM.

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
