### PR TITLE
mpp: Fix the crash or error when mpp generate empty task list. (#31658)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #31658 to release-5.2
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/31696
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/31696:release-5.2-f1f92302642f
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/31636

Problem Summary: apply may generate an empty range list, and then generate an empty mpp task list, but we don't handle it correctly.

### What is changed and how it works?

handle the situation when mpp task list is empty.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
        need add the original case to our intergration cases

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the crash or error when generating an empty mpp task list.
```

### CODE REVIEW

**Comment by windtalker** [comment]
Throw error if task is empty?

**Comment by LittleFall** [comment]
> #31658

that's https://github.com/pingcap/tidb/pull/33136 will do..

**Comment by LittleFall** [comment]
> Throw error if task is empty?

that's https://github.com/pingcap/tidb/pull/33136 will do..

**Pull request merged**
