### PR TITLE
store: update kvrpc.Cleanup proto and change its behaviour #12212

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry-pick https://github.com/pingcap/tidb/pull/12212

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @coocood @youjiali1995 @MyonKeminta

**Comment by coocood** [comment]
LGTM

**Comment by MyonKeminta** [comment]
Sorry test were run with wrong version of TiKV.
/run-all-tests tikv=pr/5589

**Comment by tiancaiamao** [comment]
Waiting for https://github.com/pingcap/tidb/pull/12560 to fix CI (go mod tidy)

**Pull request merged**
