### PR TITLE
util/admin: support admin recover index on the partition table

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Before this PR,  `admin recover index` won't take effect on partition table.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- No

### Release note 

- Support admin recover index on the partition table.

### CODE REVIEW

**Comment by crazycs520** [comment]
@tiancaiamao @zimulala PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Comment by tiancaiamao** [comment]
PTAL @XuHuaiyu @imtbkcat

**Pull request merged**
