### PR TITLE
planner, stats: try to reduce the function calls for range building

### PR DESCRIPTION
**Pull request by winoros**
***JUST FOR TESTING***

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Comment by winoros** [comment]
/run-all-tests tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by winoros** [comment]
/run-all-tests tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
It is wield release-2.1 seems miss some test

**Comment by zhouqiang-cl** [comment]
seems go version is not correct, you should update branch and then rerun the tests

**Comment by zz-jason** [comment]
@zhouqiang-cl This PR is based on v2.1.8, do we have an environment to run integration test for this version?

**Comment by winoros** [comment]
will prepare a production-ready version

**Pull request closed without merging**
