### PR TITLE
types: Introduce fuzzing by adding 3 fuzzers

### PR DESCRIPTION
**Pull request by AdamKorcz**
### What problem does this PR solve?

Issue Number: https://github.com/pingcap/tidb/issues/318

Problem Summary:
In above mentioned issue as well as [here](https://github.com/pingcap/tidb/issues/11756), interest has been expressed in doing more in terms of fuzzing. Two points of interest have been highlighted:

1. The TiDB community would like to include fuzzing into the project using go-fuzz.
2. Continuous fuzzing should be setup on oss-fuzz.

### What is changed and how it works?

What's Changed: This PR adds 3 fuzzers that target parts of the types subsystem.

How it Works: The fuzzers can be run locally, and I have managed to run them on oss-fuzz's infrastructure as well.

### Related changes

I will be glad to integrate TiDB into oss-fuzz. This will enable Google to run these 3 fuzzers as well as all future fuzzers continuously. In case a bug is found, all maintainers are notified with a detailed bug report. The service is offered free of charge with an implied expectation that the found bugs are fixed, so the resources spent on fuzzing TiDB are put to good use.

To integrate TiDB into oss-fuzz, all I need are the email addresses of the maintainers that should receive the bug reports. This is a public list that can be changed at any time.

### Check List 

Tests 

- No code

Side effects

None. The fuzzers are not implemented into TiDB as of writing. To setup continuous fuzzing in oss-fuzz, it is strongly recommended to have the fuzzers in the upstream repository. 

### Release note 

I would like to mention, that currently the fuzzers are located in the folder together with their targets. This might not be a sustainable solution for future work as coverage starts to increase with more fuzzers. For good organization, I ask kindly for opinions on where to place these. It could perhaps be in `/types/fuzz/` and this pattern could be used on all subsystems.

### CODE REVIEW

**Comment by zz-jason** [comment]
Awesome, thanks for your contribution! @zhouqiang-cl PTAL as well.

**Comment by zhouqiang-cl** [comment]
@zz-jason Please take a look again

**Comment by zz-jason** [comment]
LGTM
/approve

**Comment by AdamKorcz** [comment]
I am glad my contribution is appreciated. Since there has been interest in setting up continuous fuzzing, shall I integrate TiDB into oss-fuzz?

**Comment by zhouqiang-cl** [comment]
@AdamKorcz thank you for your PR. It is very appreciated that if you can integrate TiDB into oss-fuzz. What message do we need to provide

Thank you again

**Comment by AdamKorcz** [comment]
I need at least one email address for the bug reports. The list of email addresses will be public and can be changed at any time.

**Comment by zhouqiang-cl** [comment]
aha. My email address is zhouqiang@pingcap.com, @AdamKorcz thank you 
@zz-jason Did you need to receive the message too? If need, please provide your email

**Pull request merged**
