### PR TITLE
Pass gofmt

### PR DESCRIPTION
**Pull request by zimulala**
pass gofmt

### CODE REVIEW

**Comment by xiang90** [comment]
this is `gofmt -s`, right?

**Comment by zimulala** [comment]
yep.

**Comment by xiang90** [comment]
@zimulala Ideally, you should mention this in CONTRIBUTION.md and add this test into travis.

**Comment by zimulala** [comment]
It's my next pr.

**Comment by ngaut** [comment]
LGTM

**Comment by xiang90** [comment]
@zimulala ah. great!

**Comment by zimulala** [comment]
@xiang90 ^_^

**Comment by shenli** [comment]
LGTM

**Pull request merged**
