### PR TITLE
rebase release-2.0 to release-2.0-binlog

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
### What problem does this PR solve? 
rebase release-2.0 to release-2.0-binlog to get the new update

### What is changed and how it works?
git rebase release-2.0

### Check List 

Tests 

 - Unit test
 - Integration test

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8928)

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by WangXiangUSTC** [comment]
/run-all-tests tikv=release-2.0 tidb-test=release-2.0 pd=release-2.0

**Comment by WangXiangUSTC** [comment]
/run-all-tests tikv=release-2.0 tidb-test=release-2.0 pd=release-2.0

**Comment by zz-jason** [comment]
@WangXiangUSTC Can we merge this PR now?

**Comment by WangXiangUSTC** [comment]
@zz-jason yes, Please help me merge this pr

**Pull request merged**
