### PR TITLE
executor, expression: calculating the default value for datetime should consider the time zone

### PR DESCRIPTION
**Pull request by zz-jason**
### What problem does this PR solve? 

The default value calculated for datetime column has not consider the timezone. This PR fixes it.

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by zz-jason** [comment]
@XuHuaiyu @tiancaiamao @eurekaka @lysu PTAL.

**Comment by coocood** [comment]
@zz-jason We should not convert timezone for DateTime type.

**Comment by zz-jason** [comment]
@coocood Why?

**Comment by coocood** [comment]
@zz-jason never mind

CI failed, due to `no database selected`

**Comment by XuHuaiyu** [comment]
I think what @coocood mean is that:
When `insert` using current_timestamp, timezone should be take into consideration.
But when `selecting` we should not convert it using timezone, because that we do not know in which timezone the DATETIME value is inserted since DATETIME does not maintain the info of timezone.

**Comment by zz-jason** [comment]
Got it. After investigating, mysql document says: 
> MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval. (This does not occur for other types such as DATETIME.) 

And the behavior seems like MySQL converts **DATETIME** values from the current time zone to UTC for storage, but for retrieval, MySQL doesn't convert back from UTC to the current time zone.

**Pull request merged**
