### PR TITLE
ddl: add check when add foreign key.

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
```sql
create table t1 (a int, b int);
create table t2 (a int, b int);
alter table t1 add foreign key (c) REFERENCES t2(a);
select * from information_schema.key_column_usage;
```
`alter table t1 add foreign key (c) REFERENCES t2(a);` should return error `key column c doesn't exist in table`
but currently tidb will execute successfully. then next select will cause panic.

### What is changed and how it works?
Add check when add foreign key.

### Check List 

Tests 
 - Integration test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by crazycs520** [comment]
@winkyao @zimulala @ciscoxll PTAL

**Comment by crazycs520** [comment]
@winkyao PTAL

**Comment by zz-jason** [comment]
@crazycs520 Should we cherry pick this PR to release-2.1 and release-2.0 branch?

**Pull request merged**
