### PR TITLE
ddl: dynamic adjust add index worker number. (#8295)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
cherry-pick #8295 

### Check List 

Tests 

Code changes

Side effects

Related changes

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8786)

### CODE REVIEW

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by crazycs520** [comment]
/run-integration-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by crazycs520** [comment]
/run-integration-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by crazycs520** [comment]
/run-integration-compatibility-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zimulala** [comment]
PTAL @winkyao @ciscoxll

**Comment by winkyao** [comment]
@crazycs520 Cherry-pick needn't three LGTM.

**Pull request merged**
