### PR TITLE
expression: remove unnecessary warnings for `AND/OR` expressions | tidb-test=pr/2409

### PR DESCRIPTION
**Pull request by gengliqi**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/56481

Problem Summary:
This PR is intended to fix the bug introduced by the fix PRs of https://github.com/pingcap/tidb/issues/17725.
The unnecessary warnings appear when evaluating the first argument generates some warnings and evaluating the second argument generates errors or warnings.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by windtalker — APPROVED** [review]
lgtm

**Review by yibin87 — APPROVED** [review]
LGTM

**Comment by purelind** [comment]
Please wait for this PR https://github.com/pingcap/tidb/pull/51126 to be merged first.

**Pull request merged**
