### PR TITLE
statistics: handle lock and unlock operations correctly

### PR DESCRIPTION
**Pull request by Rustin170506**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/55906

Problem Summary:

### What changed and how does it work?

Handle the lock and unlock operations correctly.

1. When we unlock the tables, we need to update the version in order to trigger an update, allowing the priority queue to check the latest count and the modify_count.
2. When we lock the tables, we need to update the version as well. This lets the priority queue know that the table has been changed, and we need to evaluate it again.
3. In the priority queue, when we enqueue the table, we will check if this table has been locked or unlocked.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by elsa0520 — APPROVED** [review]
LGTM

**Review by winoros — APPROVED** [review]

**Pull request merged**
