### PR TITLE
*: seperate hash keys from join keys in IndexJoin (#20761)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20761 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/20710 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Extract the `column <eq> column` conditions from OtherCondition to 
help to build the hashtable for IndexJoin and IndexHashJoin.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

N/A

### Release note 

- No release note.

### CODE REVIEW

**Review by lzmhhh123 — COMMENTED** [review]
The test failed:

```bash
[2020-11-16T08:48:01.025Z] ... obtained string = "" +

[2020-11-16T08:48:01.025Z] ...     "[Projection_11 2.00 root  Column#17]\n" +

[2020-11-16T08:48:01.025Z] ...     "[└─Apply_13 2.00 root  CARTESIAN left outer semi join, other cond:eq(test.t.e, Column#16)]\n" +

[2020-11-16T08:48:01.025Z] ...     "[  ├─TableReader_15(Build) 2.00 root  data:TableFullScan_14]\n" +

[2020-11-16T08:48:01.025Z] ...     "[  │ └─TableFullScan_14 2.00 cop[tikv] table:t keep order:false]\n" +

[2020-11-16T08:48:01.025Z] ...     "[  └─StreamAgg_20(Probe) 1.00 root  funcs:count(1)->Column#16]\n" +

[2020-11-16T08:48:01.025Z] ...     "[    └─IndexJoin_36 2.00 root  inner join, inner:TableReader_35, outer key:test.t.a, inner key:test.t.a, equal cond:eq(test.t.a, test.t.a)]\n" +

[2020-11-16T08:48:01.025Z] ...     "[      ├─IndexReader_29(Build) 2.00 root  index:IndexRangeScan_28]\n" +

[2020-11-16T08:48:01.025Z] ...     "[      │ └─IndexRangeScan_28 2.00 cop[tikv] table:s, index:idx(b, c, d) range: decided by [eq(test.t.b, 1) in(test.t.c, 1, 2) eq(test.t.d, test.t.a)], keep order:false]\n" +

[2020-11-16T08:48:01.025Z] ...     "[      └─TableReader_35(Probe) 1.00 root  data:TableRangeScan_34]\n" +

[2020-11-16T08:48:01.025Z] ...     "[        └─TableRangeScan_34 1.00 cop[tikv] table:t1 range: decided by [test.t.a], keep order:false]\n"

[2020-11-16T08:48:01.025Z] ... expected string = "" +

[2020-11-16T08:48:01.025Z] ...     "[Projection_11 2.00 root  Column#17]\n" +

[2020-11-16T08:48:01.025Z] ...     "[└─Apply_13 2.00 root  CARTESIAN left outer semi join, other cond:eq(test.t.e, Column#16)]\n" +

[2020-11-16T08:48:01.025Z] ...     "[  ├─TableReader_15(Build) 2.00 root  data:TableFullScan_14]\n" +

[2020-11-16T08:48:01.025Z] ...     "[  │ └─TableFullScan_14 2.00 cop[tikv] table:t keep order:false]\n" +

[2020-11-16T08:48:01.025Z] ...     "[  └─StreamAgg_20(Probe) 1.00 root  funcs:count(1)->Column#16]\n" +

[2020-11-16T08:48:01.025Z] ...     "[    └─IndexJoin_36 2.00 root  inner join, inner:TableReader_35, outer key:test.t.a, inner key:test.t.a]\n" +

[2020-11-16T08:48:01.025Z] ...     "[      ├─IndexReader_29(Build) 2.00 root  index:IndexRangeScan_28]\n" +

[2020-11-16T08:48:01.025Z] ...     "[      │ └─IndexRangeScan_28 2.00 cop[tikv] table:s, index:idx(b, c, d) range: decided by [eq(test.t.b, 1) in(test.t.c, 1, 2) eq(test.t.d, test.t.a)], keep order:false]\n" +

[2020-11-16T08:48:01.025Z] ...     "[      └─TableReader_35(Probe) 1.00 root  data:TableRangeScan_34]\n" +

[2020-11-16T08:48:01.025Z] ...     "[        └─TableRangeScan_34 1.00 cop[tikv] table:t1 range: decided by [test.t.a], keep order:false]\n"

[2020-11-16T08:48:01.025Z] ... sql:explain select t.e in (select count(*) from t s use index(idx), t t1 where s.b = 1 and s.c in (1, 2) and s.d = t.a and s.a = t1.a) from t, args:[]
```

**Review by lzmhhh123 — DISMISSED** [review]
LGTM

**Review by winoros — COMMENTED** [review]
lgtm

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
