### PR TITLE
server: change status port in test to be lower than 10000

### PR DESCRIPTION
**Pull request by SunRunAway**
### What problem does this PR solve?

Issue Number: close #xxx 

```
[2020-06-03T06:43:38.448Z] ----------------------------------------------------------------------
[2020-06-03T06:43:38.448Z] FAIL: <autogenerated>:1: tidbTestSerialSuite.SetUpSuite
[2020-06-03T06:43:38.448Z] 
[2020-06-03T06:43:38.448Z] tidb_test.go:92:
[2020-06-03T06:43:38.448Z]     c.Assert(err, IsNil)
[2020-06-03T06:43:38.448Z] ... value *errors.withStack = listen tcp 0.0.0.0:10094: bind: address already in use ("listen tcp 0.0.0.0:10094: bind: address already in use")
[2020-06-03T06:43:38.448Z] 
[2020-06-03T06:43:38.448Z] 
[2020-06-03T06:43:38.448Z] ----------------------------------------------------------------------
```
Problem Summary:
change tidb-server status port in unit test to be lower than 10000, to prevent conflicting [ephemeral port](https://en.wikipedia.org/wiki/Ephemeral_port) of linux operating system.

In our Jenkins environment, 
```
$ sysctl  net.ipv4.ip_local_port_range
net.ipv4.ip_local_port_range = 10000	30000
```

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

### Release note 

- No release note.

### CODE REVIEW

**Comment by glorv** [comment]
LGTM

**Comment by zz-jason** [comment]
Could you describe why do we need this change in the PR description to help others to understand this PR?

**Pull request merged**
