### PR TITLE
planner: fix the issue that IndexJoin with plan-cache return wrong results after changing some parameters unexpectedly (#29496)

### LINKED ISSUE #29486: prepared-plan-cache: the inl_join return wrong results
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

prepared-plan-cache.enabled = true
```
use test;
drop table if exists UK_MULTI_COL_11691;
CREATE TABLE `UK_MULTI_COL_11691` (
  `COL1` binary(20) DEFAULT NULL,
  `COL2` tinyint(16) DEFAULT NULL,
  `COL3` time DEFAULT NULL,
  UNIQUE KEY `U_M_COL` (`COL1`(10),`COL2`,`COL3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
insert into UK_MULTI_COL_11691 values(0x340C604874B52E8D30440E8DC2BB170621D8A088, 126, "-105:17:32"),
(0x28EC2EDBAC7DF99045BDD0FCEAADAFBAC2ACF76F, 126, "102:54:04"),
(0x11C38221B3B1E463C94EC39F0D481303A58A50DC, 118, "599:13:47"),
(0x03E2FC9E0C846FF1A926BF829FA9D7BAED3FD7B1, 118, "-257:45:13");

prepare stmt from 'SELECT/*+ INL_JOIN(t1, t2) */ t2.* FROM UK_MULTI_COL_11691 t1 JOIN UK_MULTI_COL_11691 t2 ON t1.col1 = t2.col1 WHERE t1.col2 BETWEEN ? AND ? AND t2.col2 BETWEEN ? AND ?;';
set @a=-29408, @b=-9254, @c=-1849, @d=-2346;
execute stmt using @a,@b,@c,@d;
set @a=126, @b=126, @c=-125, @d=707;
execute stmt using @a,@b,@c,@d;

prepare stmt from 'SELECT/*+ INL_JOIN(t1, t2) */ t2.* FROM UK_MULTI_COL_11691 t1 JOIN UK_MULTI_COL_11691 t2 ON t1.col1 = t2.col1 WHERE t1.col2 BETWEEN ? AND ? AND t2.col2 BETWEEN ? AND ?;';
set @a=126, @b=126, @c=-125, @d=707;
execute stmt using @a,@b,@c,@d;
```
### 2. What did you expect to see? (Required)
```
mysql> execute stmt using @a,@b,@c,@d;
+--------------------------------------------+------+------------+
| COL1                                       | COL2 | COL3       |
+--------------------------------------------+------+------------+
| 0x340C604874B52E8D30440E8DC2BB170621D8A088 |  126 | -105:17:32 |
| 0x28EC2EDBAC7DF99045BDD0FCEAADAFBAC2ACF76F |  126 | 102:54:04  |
+--------------------------------------------+------+------------+
2 rows in set (0.00 sec)

mysql>
mysql>
mysql> prepare stmt from 'SELECT/*+ INL_JOIN(t1, t2) */ t2.* FROM UK_MULTI_COL_11691 t1 JOIN UK_MULTI_COL_11691 t2 ON t1.col1 = t2.col1 WHERE t1.col2 BETWEEN ? AND ? AND t2.col2 BETWEEN ? AND ?;';
Query OK, 0 rows affected (0.00 sec)

mysql> set @a=126, @b=126, @c=-125, @d=707;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using @a,@b,@c,@d;
+--------------------------------------------+------+------------+
| COL1                                       | COL2 | COL3       |
+--------------------------------------------+------+------------+
| 0x340C604874B52E8D30440E8DC2BB170621D8A088 |  126 | -105:17:32 |
| 0x28EC2EDBAC7DF99045BDD0FCEAADAFBAC2ACF76F |  126 | 102:54:04  |
+--------------------------------------------+------+------------+
2 rows in set (0.00 sec)

```

### 3. What did you see instead (Required)
```
mysql> execute stmt using @a,@b,@c,@d;
+--------------------------------------------+------+------------+
| COL1                                       | COL2 | COL3       |
+--------------------------------------------+------+------------+
| 0x340C604874B52E8D30440E8DC2BB170621D8A088 |  126 | -105:17:32 |
| 0x28EC2EDBAC7DF99045BDD0FCEAADAFBAC2ACF76F |  126 | 102:54:04  |
| 0x11C38221B3B1E463C94EC39F0D481303A58A50DC |  118 | 599:13:47  |
| 0x03E2FC9E0C846FF1A926BF829FA9D7BAED3FD7B1 |  118 | -257:45:13 |
+--------------------------------------------+------+------------+
4 rows in set (0.00 sec)

mysql>
mysql>
mysql> prepare stmt from 'SELECT/*+ INL_JOIN(t1, t2) */ t2.* FROM UK_MULTI_COL_11691 t1 JOIN UK_MULTI_COL_11691 t2 ON t1.col1 = t2.col1 WHERE t1.col2 BETWEEN ? AND ? AND t2.col2 BETWEEN ? AND ?;';
Query OK, 0 rows affected (0.00 sec)

mysql> set @a=126, @b=126, @c=-125, @d=707;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using @a,@b,@c,@d;
+--------------------------------------------+------+------------+
| COL1                                       | COL2 | COL3       |
+--------------------------------------------+------+------------+
| 0x340C604874B52E8D30440E8DC2BB170621D8A088 |  126 | -105:17:32 |
| 0x28EC2EDBAC7DF99045BDD0FCEAADAFBAC2ACF76F |  126 | 102:54:04  |
+--------------------------------------------+------+------------+
2 rows in set (0.00 sec)

```
### 4. What is your TiDB version? (Required)

```
Release Version: v5.4.0-alpha-25-g1b5b44047
Edition: Community
Git Commit Hash: 1b5b44047c6643e428798c332583d387256ba151
Git Branch: master
UTC Build Time: 2021-11-05 01:46:40
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #29496 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/29504
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/29504:release-5.3-cdd141dcca4a
```

---

### What problem does this PR solve?

Issue Number: close #29486

Problem Summary: planner: fix the issue that IndexJoin with plan-cache return wrong results after changing some parameters unexpectedly

### What is changed and how it works?

Check whether the width of rebuilt range changes, if it is, then some expected access conditions must be changed and cannot be used to calculate range, and then return an error to let the optimizer optimize this query again in this case for safety.

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
planner: fix the issue that IndexJoin with plan-cache return wrong results after changing some parameters unexpectedly
```

### CODE REVIEW

**Comment by qw4990** [comment]
wait for https://github.com/pingcap/tidb/pull/29377

**Review by rebelice — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]

**Pull request merged**
