### PR TITLE
util/cteutil: migrate test-infra to testify

### LINKED ISSUE #26173: migrate test-infra to testify for `util/cteutil` pkg

### PR DESCRIPTION
**Pull request by xiaoshengMr**
Signed-off-by: xiaoshengmr <xiaoshengmr@163.com>

### What problem does this PR solve?

Issue Number: close #26173 

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
/cc @xhebox @tiancaiamao @mmyj 

PTAL >_<

**Review by xhebox — APPROVED** [review]

**Review by guo-shaoge — APPROVED** [review]

**Comment by tisonkun** [comment]
@xhebox would you mind to help on merging?

**Comment by zhouqiang-cl** [comment]
@ti-chi-bot

**Pull request merged**
