### PR TITLE
*: add clustered index info in `show index from` stmt (#23329)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23329 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23361
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23361:release-5.0-9c48b24cb108
```

---

### What problem does this PR solve?

Problem Summary:

support show index's clustered property in `show index from tbl` stmt

### What is changed and how it works?

What's Changed, How it Works:

add `Clustered` column to `show index from tbl`'s result

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- n/a

### Release note 

- n/a

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/23329)

### CODE REVIEW

**Comment by lysu** [comment]
need merge with https://github.com/pingcap/tidb-test/pull/1171

**Comment by lysu** [comment]
@wjhuang2016  PTAL

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
