### PR TITLE
plan: use original field name when `Column` is extracted from `IfNull`

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve? 

Fix https://github.com/pingcap/tidb/issues/8221

### What is changed and how it works?

Specially mark extracted `Column` to be a referenced column when eliminating `IfNull`, then in `BuildProjectionField`, this `Column` would be treated as an expression for inferring field name.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported variable/fields change

Side effects

N/A

Related changes

Since `IfNull` elimination is only in master branch, no cherry-pick for release branch needed.

### CODE REVIEW

**Comment by winoros** [comment]
Unit-test failed

**Comment by eurekaka** [comment]
@zz-jason @lamxTyler @winoros  @XuHuaiyu PTAL

**Comment by zz-jason** [comment]
LGTM

**Pull request merged**
