### PR TITLE
domain: change some stats log level as WARN

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/58315

Problem Summary:

### What changed and how does it work?

want to know the reason why this function will be failed.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
/hold

Also use sampled logger to reduce log size if they are failed for a long time. Free to unhold

**Comment by hawkingrei** [comment]
> /hold
> 
> Also use sampled logger to reduce log size if they are failed for a long time. Free to unhold

They are all controlled by timers, and the interval is at the second level, so there won't be too many logs. In fact, if there is a problem for a long time, too many logs can also help them trigger the log warn alarm.

**Review by winoros — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
