### PR TITLE
expression: Support push function replace down to TiFlash

### PR DESCRIPTION
**Pull request by fuzhe1989**
### What problem does this PR solve?

Issue Number: pingcap/tics#1860

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- Support push down function replace to TiFlash.

### CODE REVIEW

**Review by zanmato1984 — APPROVED** [review]
LGTM

**Review by jackysp — APPROVED** [review]
LGTM

**Comment by jackysp** [comment]
Please add the release note and resolve conflicts. @fuzhe1989

**Pull request merged**
