### PR TITLE
*: update test cases to support new collation enabled by default

### LINKED ISSUE #18803: charset: upgrade existing CI tests for enabled new collation
## Development Task

The new collation framework('CI collations') is supported in TiDB v4.0, however, due to the cluster configuration `new_collations_enabled_on_first_bootstrap`, the unit tests/integration tests in current CI are designed to run after an explicit `TestNewCollationEnabled()`, for example:

https://github.com/pingcap/tidb/blob/b249dc5780407b256d1383e92f56bd843d2682ed/expression/integration_test.go#L6551

That is, the impact of the new collation framework is large but the tests for them are relatively limited.

We would like to enhance the existing CI tests by allowing running them all with enabled new collation framework, in order to archive that, some of the cases need to be upgraded accordingly:

1. The schema-changing tests: when the new collation framework is enabled, TiDB narrowed the available collations to those supported really, some cases failed with the message below:

```
[ddl:1273]Unsupported collation when new collation is enabled: 'utf8_unicode_ci'
```

2. Some padding related query tests: when the new collation framework is enabled, some padding-related behaviors are corrected to provide better compatibility with MySQL, which may lead to failed test cases like below:

```
tk.MustExec(`create table t(a char(4) primary key, b char(4));`)
tk.MustExec(`insert into t values("a ", "b ");`)
tk.MustPointGet(`select * from t where a = "a ";`).Check(testkit.Rows())

... obtained string = "[a b]\n"
... expected string = ""
```

3. The protocol buffer related tests: when the new collation is enabled, TiDB rewrites some collation ID in the generated protobuf message sent to TiKV, and those test cases against the messages need to be updated:

```
FAIL: misc_test.go:207: testMiscSuite.TestToPB

misc_test.go:228:
    c.Assert(ColumnToProto(column).String(), Equals, "column_id:1 collation:45 columnLen:-1 decimal:-1 ")
... obtained string = "column_id:1 collation:-45 columnLen:-1 decimal:-1 "
... expected string = "column_id:1 collation:45 columnLen:-1 decimal:-1 "
```

4. The [Jepsen tests against TiDB](https://jepsen.io/analyses/tidb-2.1.7): 
  * Most test cases in Jepsen are with integer-only schema, so the test cases are theoretically not affected by the new collation framework, we can simply enable the new collation framework without updating those cases. 
  * The only exception is ['Sequencial'](https://jepsen.io/consistency/models/sequential), in which case the primary key is defined on a `VARCHAR` column, some trivial work is needed to update its collation to `utf8mb4_general_ci` to test its correctness for the new collations.

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve?

Issue Number: close #18803 

Problem Summary:

### What is changed and how it works?

What's Changed:

All unit/integration tests will be ran with new collation configuration enabled

How it Works:

Change some cases.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Comment by bb7133** [comment]
Failed test case: https://github.com/pingcap/tidb/issues/19713

**Comment by tisonkun** [comment]
@bb7133 shall we port this to master? It seems weird we only do for 4.0.

**Comment by tisonkun** [comment]
@zimulala please take a look at this PR to see how we can handle it.

**Comment by tiancaiamao** [comment]
4.0 should not handle it ... leave it to newer version

**Pull request closed without merging**
