### PR TITLE
tikv: fix retry batchCop request with old copTask bug (#18176)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #18176 to release-4.0

---

### What problem does this PR solve?

Problem Summary:

batchCop requests meet region error will rebuild CopTask，but in retry handle it didn't use new CopTask.

### What is changed and how it works?

What's Changed, How it Works:

use new CopTask instead of old one

### Related changes

- Need to cherry-pick to the release branch 4.0

### Check List 

Tests 

- not easy to add test but simple change

Side effects

- n/a

### Release note 

-  Fix retry batchCop request with old copTask bug

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/18176)

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by zanmato1984** [comment]
Ping.

**Pull request merged**
