### PR TITLE
util/hack: define a MutableString type for function hack.String

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

The `hack.String()` function is not safe, the returned string is not actually constant.

```
a := []byte{'a', 'b', 'c'}
b := hack.String(a)   // b = "abc"
a[0] = 's'
fmt.Println(b) // b = "sbc", Oh, my god!
```

```
b := string(a)    // safe, bad performance
```

```
func hack.String([]byte) string
b := hack.String(a)  // good performance, but unsafe
```
```
func hack.String([]byte) MutableString
b := hack.String(a)  // both safe ...
c := string(b)       // ... and good performance
```

When the caller get a `MutableString`, he knows this is not a `string`
And when the user use `string(b)` to cast the `MutableString`, he knows it's a type cast.

### What is changed and how it works?

Define a MutableString type for the return value of `hack.String`.

Some changes are irrelevant, I'll rebase it after https://github.com/pingcap/tidb/pull/9194

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @lysu

**Comment by breeswish** [comment]
I think this PR misleadingly suggest that `string(MutableString)` produce an immutable string. Actually the produced string is still unsafe.

**Comment by dragonly** [comment]
A little supplement to @breeswish 
When I write a function requiring a `string`, I assume its immutability naturally, but currently the caller can pass in a `string(MutableString)` which breaks the protocol. As I can tell, the tidb codebase now is full of this mis-assumption, which is very dangerous.

**Pull request merged**
