### PR TITLE
*: close RecordSet

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: ref #31716

Problem Summary:

### What is changed and how it works?

In history, We have met many [problems](https://github.com/pingcap/tidb/pull/34837/files) caused by forgetting to close RecordSet. so we refactor the test case by closing the record set to make the test stable.

### Check List

Tests 

- [x] Unit test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xiongjiwei — APPROVED** [review]

**Review by tisonkun — COMMENTED** [review]
This change seems related to cleanup code to use `testkit` methods. What's the relation to `close RecordSet`?

**Comment by hawkingrei** [comment]
> This change seems related to cleanup code to use `testkit` methods. What's the relation to `close RecordSet`?

In history,  We have met many [problems](https://github.com/pingcap/tidb/pull/34837/files) caused by forgetting to close RecordSet. so we refactor the test case by closing the record set to make the test stable.

**Review by tisonkun — APPROVED** [review]
You're right that `ExecToErr` closes the RecordSet while `Exec` doesn't.

**Pull request merged**
