### PR TITLE
executor: cherry-pick 4a91a24

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Reminiscent — DISMISSED** [review]

**Review by xuyifangreeneyes — DISMISSED** [review]

**Comment by wuhuizuo** [comment]
/run-mysql-test tidb-test=70d29a00974262399c5382db97f0da6a7d084746

**Review by Reminiscent — APPROVED** [review]

**Review by xuyifangreeneyes — APPROVED** [review]

**Pull request merged**
