### PR TITLE
planner, sctx: open enhanced index join pattern by default | tidb-test=pr/2395

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/47233

Problem Summary:

### What changed and how does it work?

Open the var `tidb_enable_inl_join_inner_multi_pattern` by default.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
默认开启 tidb_enable_inl_join_inner_multi_pattern，扩展 TiDB Index Join 的能力
open the variable `tidb_enable_inl_join_inner_multi_pattern` by default, enhancing the power of TiDB's index join.
```

### CODE REVIEW

**Comment by winoros** [comment]
The extra changes in https://github.com/pingcap/tidb/pull/56172/files#diff-e82acde450b380d2b2347aeb83d34bffaaa10b19d9eb24ea7aadbef96d71c875 is to solve the following issue:

- When there are virtual columns, there'll be projection.
image
- But union scan cannot support projection as its inner child
image
- UnionScan's Attach2Task deals with this case.
image


So I changed the code to solve this issue. The affected test is `TestIssue53951` when it chooses `g2` as the index join's inner child.

**Review by hawkingrei — APPROVED** [review]

**Review by elsa0520 — APPROVED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]

**Comment by AilinKid** [comment]
@zimulala ptal

**Review by tangenta — APPROVED** [review]
lgtm for infoschema

**Review by Leavrth — APPROVED** [review]

**Pull request merged**
