### PR TITLE
br: don't print slow log in br without SlowLogFile config

### PR DESCRIPTION
**Pull request by joccau**
Signed-off-by: joccau <zak.zhao@pingcap.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/32202

Problem Summary: As title.

### What is changed and how it works?
If user set flag about SlowLogFile when use `backup/restore(br)` , it needs not to print slow log into screen.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

image

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]
LGTM

BTW, the slow log was disabled at here in the `br-stream` branch, maybe we'd better remove that after this get merged.
https://github.com/pingcap/tidb/pull/32168/files#diff-92e085286590114ba97017dac40686023bd6f3ee6b7e9375a4f0cd0d450f02aaR39

**Review by kennytm — APPROVED** [review]

**Pull request merged**
