### PR TITLE
add make command shell

### PR DESCRIPTION
**Pull request by insionng**

### CODE REVIEW

**Comment by ngaut** [comment]
@qiuyesuifeng Please take a look.

@insionng Thank you, Could you sign the CLA. CI failed

**Comment by insionng** [comment]
okay~

**Comment by shenli** [comment]
@c4pt0r 
Please take a look.

**Comment by qiuyesuifeng** [comment]
@insionng Thanks for your PR.

There are some additional things need to do:
1 For making tidb, u must do things as follows:
1.1 godep
`godep` is to get godep tool(`https://github.com/tools/godep`) which is used for easy building without getting dependency packages.

1.2 parser
`parser` is to get goyacc and golex package, generate `parser/parser.go` and `parser/scanner.go` which are needed by tidb building.
In your make.cmd, u have done this, but also need some work like in `tidb/Makefile` to generate `parser/scanner.go`：
`golex -o parser/scanner.go parser/scanner.l`

1.3 build
Godep go build

1.4 test
Godep go test ./...

2 For making interpreter, u must do things as follows:
2.1 add `ldflags` go build option[nice to haves]
LDFLAGS += -X "github.com/pingcap/tidb/util/printer.TiDBBuildTS=$(shell date -u '+%Y-%m-%d %I:%M:%S')"
LDFLAGS += -X "github.com/pingcap/tidb/util/printer.TiDBGitHash=$(shell git rev-parse HEAD)"
The ldflags is very useful for us to check and fix bugs.
The correct interpreter output looks like as follows:
```
Welcome to the TiDB.
Version:
Git Commit Hash: bf97f61c450912a5c1f4cfba44bb11297fa7876f
UTC Build Time:  20150913214037

tidb>
```

2.2 build
Godep go build -ldflags "-X github.com/pingcap/tidb/util/printer.TiDBBuildTS=%TiDBBuildTS% -X github.com/pingcap/tidb/util/printer.TiDBGitHash=%TiDBGitHash%"
TiDBBuildTS and TiDBGitHash variables are set in above 2.1

So u can see above, maybe some more work to do in make.cmd.
And also, for unix/mac users, i think it is better to install make tool.
Thanks again, looking forward to your update :)

**Comment by insionng** [comment]
It has been updated.

**Comment by ngaut** [comment]
Well done. Looks like we don't need make.sh.
Just keep make.cmd is fine. We could still use make instead of make.sh.
Could you please remove make.sh. Then we will merge this PR.
Thanks. @insionng

**Comment by c4pt0r** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM. Thank you @insionng

**Pull request merged**
