### PR TITLE
*: move most of the packages to 'pkg'

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve?

Issue Number: ref #41241

Problem Summary:

### What is changed and how it works?

As mentioned in #41241, this PR will move most of first-level packages to a new 'pkg' directory. However, `dumpling` and `br` are not moved since further discussions are needed.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > Just move files.

Side effects

- NA

Documentation

- [] No end-user documents update is needed, but we need to update some developer-faced documents.

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by bb7133** [comment]
I used the following scripts to update all '.go' files:

```
#!/bin/bash

# Define an array called pkg_list, each element containing a tuple of source and target directories
pkg_list=(
  "autoid_service pkg/autoid_service"
  "bindinfo pkg/bindinfo"
  "config pkg/config"
  "ddl pkg/ddl"
  "distsql pkg/distsql"
  "disttask pkg/disttask"
  "domain pkg/domain"
  "errno pkg/errno"
  "executor pkg/executor"
  "extension pkg/extension"
  "expression pkg/expression"
  "infoschema pkg/infoschema"
  "keyspace pkg/keyspace"
  "kv pkg/kv"
  "lock pkg/lock"
  "metrics pkg/metrics"
  "owner pkg/owner"
  "meta pkg/meta"
  "parser pkg/parser"
  "privilege pkg/privilege"
  "planner pkg/planner"
  "plugin pkg/plugin"
  "resourcemanager pkg/resourcemanager"
  "server pkg/server"
  "session pkg/session"
  "sessionctx pkg/sessionctx"
  "sessiontxn pkg/sessiontxn"
  "statistics pkg/statistics"
  "structure pkg/structure"
  "store pkg/store"
  "table pkg/table"
  "tablecodec pkg/tablecodec"
  "telemetry pkg/telemetry"
  "testkit pkg/testkit"
  "tidb-binlog pkg/tidb-binlog"
  "timer pkg/timer"
  "ttl pkg/ttl"
  "types pkg/types"
  "tidb-server cmd/tidb-server"
)

mkdir -p pkg

if [[ $(uname) == "Darwin" ]]; then
  sed_command="sed -i ''"
else
  sed_command="sed -i"
fi

echo "SED_COMMAND: $sed_command"

for entry in "${pkg_list[@]}"; do
  source_dir="${entry%% *}"
  target_dir="${entry#* }"

  if [ -d "$target_dir" ]; then
    echo "Error: The target directory '$target_dir' already exists."
    exit 1
  fi

  git mv "$source_dir" "$target_dir"

  n_source="github.com/pingcap/tidb/$source_dir"
  n_target="github.com/pingcap/tidb/$target_dir"

  find . -type f -name "*.go" -exec $sed_command -i '' -e "s|$n_source|$n_target|g" {} +
done
```

**Comment by wuhuizuo** [comment]
> I used the following scripts to update all '.go' files:
> 
> ```
> #!/bin/bash
> 
> # Define an array called pkg_list, each element containing a tuple of source and target directories
> pkg_list=(
>   "autoid_service pkg/autoid_service"
>   "bindinfo pkg/bindinfo"
>   "config pkg/config"
>   "ddl pkg/ddl"
>   "distsql pkg/distsql"
>   "disttask pkg/disttask"
>   "domain pkg/domain"
>   "errno pkg/errno"
>   "executor pkg/executor"
>   "extension pkg/extension"
>   "expression pkg/expression"
>   "infoschema pkg/infoschema"
>   "keyspace pkg/keyspace"
>   "kv pkg/kv"
>   "lock pkg/lock"
>   "metrics pkg/metrics"
>   "owner pkg/owner"
>   "meta pkg/meta"
>   "parser pkg/parser"
>   "privilege pkg/privilege"
>   "planner pkg/planner"
>   "plugin pkg/plugin"
>   "resourcemanager pkg/resourcemanager"
>   "server pkg/server"
>   "session pkg/session"
>   "sessionctx pkg/sessionctx"
>   "sessiontxn pkg/sessiontxn"
>   "statistics pkg/statistics"
>   "structure pkg/structure"
>   "store pkg/store"
>   "table pkg/table"
>   "tablecodec pkg/tablecodec"
>   "telemetry pkg/telemetry"
>   "testkit pkg/testkit"
>   "tidb-binlog pkg/tidb-binlog"
>   "timer pkg/timer"
>   "ttl pkg/ttl"
>   "types pkg/types"
>   "tidb-server cmd/tidb-server"
> )
> 
> mkdir -p pkg
> 
> if [[ $(uname) == "Darwin" ]]; then
>   sed_command="sed -i ''"
> else
>   sed_command="sed -i"
> fi
> 
> for entry in "${pkg_list[@]}"; do
>   source_dir="${entry%% *}"
>   target_dir="${entry#* }"
> 
>   if [ -d "$target_dir" ]; then
>     echo "Error: The target directory '$target_dir' already exists."
>     exit 1
>   fi
> 
>   git mv "$source_dir" "$target_dir"
> 
>   n_source="github.com/pingcap/tidb/$source_dir"
>   n_target="github.com/pingcap/tidb/$target_dir"
> 
>   find . -type f -name "*.go" -exec $sed_command -i '' -e "s|$n_source|$n_target|g" {} +
> done
> ```

Could you also add a shell script attachment in this comment?

**Review by chrysan — APPROVED** [review]

**Review by chrysan — APPROVED** [review]

**Comment by wuhuizuo** [comment]
/approve

just refresh the OWNERS links

**Review by zanmato1984 — APPROVED** [review]

**Review by zanmato1984 — APPROVED** [review]

**Review by zanmato1984 — APPROVED** [review]

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by BornChanger — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
