### PR TITLE
executor: fix `show table status` for the database with upper-cased name (#23896)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23896 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23958
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23958:release-4.0-dbd5a3622a53
```

---

Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
`show table status` does not work for a database with upper-cased name.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:
Fix it. Introduced by https://github.com/pingcap/tidb/pull/22644

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- fix `show table status` for the database with upper-cased name.

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
LGTM

**Comment by jackysp** [comment]
PTAL @morgo @xiongjiwei

**Pull request merged**
