### PR TITLE
planner,executor: fix 'select ...(join on partition table) for update' panic (#21148)

### LINKED ISSUE #20028: Index out of range when querying on partitioned tables within a transaction
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t1, t2;
-- init
create table t1 (c_datetime datetime, primary key (c_datetime)) partition by range (to_days(c_datetime)) ( partition p0 values less than (to_days('2020-02-01')), partition p1 values less than (to_days('2020-04-01')), partition p2 values less than (to_days('2020-06-01')), partition p3 values less than maxvalue) ;
create table t2 (c_datetime datetime, unique key(c_datetime));
insert into t1 values ('2020-06-26 03:24:00'), ('2020-02-21 07:15:33'), ('2020-04-27 13:50:58');
insert into t2 values ('2020-01-10 09:36:00'), ('2020-02-04 06:00:00'), ('2020-06-12 03:45:18');
-- txn
begin;
select * from t1 join t2 on t1.c_datetime >= t2.c_datetime for update; -- ERROR 1105 (HY000): runtime error: index out of range
rollback;
```

### 2. What did you expect to see? (Required)

No error reported.

### 3. What did you see instead (Required)

```
mysql> begin;
Query OK, 0 rows affected (0.05 sec)

mysql> select * from t1 join t2 on t1.c_datetime >= t2.c_datetime for update;
ERROR 1105 (HY000): runtime error: index out of range [2] with length 2

```

### 4. What is your TiDB version? (Required)

master @ fa6baa9f5321d88f81a99e56af00526643e7bcaa
release-4.0 @ 51d365fc45fdfc039eb204a96268c5bd1c55075f

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21148 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25501
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25501:release-4.0-0490590b014c
```

---

### What problem does this PR solve?

Issue Number: close #20028 

Problem Summary:

'select ... for update' need the table ID to construct the lock key.
When this SQL works on a partitioned table, the table ID should be partition ID.

So how to get that partition ID?  
In http://github.com/pingcap/tidb/pull/14921 I try to avoid column pruning of the partition columns, 
so we can get the partition column data, and then use it to calculate the partition to get the ID.

That fix works on a single table, but not the joining of tables.

### What is changed and how it works?

What's Changed:

In the logical plan phase, if `buildSelectLock` find itself works on partitioned tables, 
change the schema add an extra partition ID column to the DataSource.

Some tiny changes in the column pruning step to get the correct schema.

In the TableReader executor, fill the extra partition ID column in the chunk row.

In the SelectLockExec, use the partition ID from the chunk row, to construct the correct lock key.

How it Works:

Let the table reader return an extra column with partition ID, so the
SelectLockExec can use that partition ID to construct the lock key.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- Fix panic when 'select ... for update' works on a join operation and the join uses partition table

### CODE REVIEW

**Comment by tiancaiamao** [comment]
`model.ExtraPidColID` is renamed to `modelExtraPidColID` because I don't want to cherry-pick too much unrelated (parser) changes.
And the fix for https://github.com/pingcap/tidb/issues/25528 is also included, so we don't need another cherry-pick of #25537 and #25652

PTAL @qw4990 @zhuo-zhi

**Review by qw4990 — COMMENTED** [review]
It seems like we don't need to pick it into v4.0 since v4.0 doesn't support dynamic-mode, alright? @tiancaiamao

**Comment by tiancaiamao** [comment]
The bug is not introduced by dynamic-mode, it's there in 4.0 branch, so we still need to fix it.

**Review by zhuo-zhi — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
