### PR TITLE
tidb: add a transaction count metric

### PR DESCRIPTION
**Pull request by tiancaiamao**
We have query count metrics but it's based on mysql command.
This metric is based on SQL transaction count.

@coocood @shenli

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by coocood** [comment]
I think put it in `doCommitWithRetry` is better, because `NewTxn` may also commit a transaction.

**Comment by tiancaiamao** [comment]
I update `NewTxn` so that `CommitTxn` would be called. @coocood

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by coocood** [comment]
FAIL: tidb_test.go:115: TidbTestSuite.TestAuth

tidb_test.go:117:
    runTestAuth(c)
server_test.go:128:
    dbt.Assert(err, IsNil, Commentf("Exec %s", query))
... value *mysql.MySQLError = &mysql.MySQLError{Number:0x415, Message:"Access denied for user 'authtest2'@'127.0.0.1' (using password: YES)"} ("Error 1045: Access denied for user 'authtest2'@'127.0.0.1' (using password: YES)")
... Exec USE mysql;

**Pull request merged**
