### PR TITLE
infoschema, executor, txn: seperate TxnIdle and TxnRunning state

### PR DESCRIPTION
**Pull request by longfangsong**
### What problem does this PR solve?

Problem Summary:

Currently `infoschma.TIDB_TRX.STATE` regard a transaction state is `NORMAL` no matter whether it is executing a statement or not, this is some times misleading.

### What is changed and how it works?

What's Changed:
Seperate  `Normal` state into `Running` and `Idle` state.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test(Need a utf)

Side effects

- [x] Performance regression: Consumes more Memory

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- `Seperate "Normal" state into "Running" and "Idle" state.`

### CODE REVIEW

**Review by MyonKeminta — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
/lgtm

**Review by MyonKeminta — APPROVED** [review]

**Pull request merged**
