### PR TITLE
*: refine the behavior of StrToInt and StrToFloat and support convert JSON to date, time and timestamp  (#17902)

### LINKED ISSUE #17898: Wrong handling of  strToInt and strToFloat
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
TiDB> create table t0(a char(10), b int as ((a))); 
Execute success (0.02 sec)
TiDB> insert into t0(a) values("0.5");
Execute success (0.00 sec)
TiDB> select * from t0;
+-----+---+
| a   | b | 
+-----+---+
| 0.5 | 0 | 
+-----+---+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
```
mysql> select * from t0;
+------+------+
| a    | b    |
+------+------+
| 0.5  |    1 |
+------+------+
1 row in set (0.00 sec)
```

### 4. Affected version (Required)

master

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #17902 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #17898 

Problem Summary:

TiDB don't distinguish cast(explicit CAST function or implicit cast) from cast(when casting into a column type, CastValue()). 
We try to distinguish them according to if the statement is a select statement or an insert statement. 
However, it's not correct, especially when the virtual generated column comes out. We can't make sure the value inserted and read are the same.
So we can't depend on if the type of the statement. We need to keep a principle. If some values are converted to a column type, then use CastValue(). Otherwise, don't use it.

Here is an example:
We didn't support converted a JSON to date. When we had a virtual generated column and it needed to be converted from a JSON to date,  we used CastJsonAsDuration to do that. This is wrong. So I supported convert JSON to date, time, and timestamp within CastValue(), though their logics are quite similar.

Finally, I correct some tests.  If you test these tests in MySQL and previously TiDB, you will see that the warnings of TiDB are wrong.

### What is changed and how it works?

1. refine the behavior of StrToInt and StrToFloat. Handling them differently according to the function call them.
2. implement convert JSON to date, time, and timestamp.
3. correct some tests.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- refine the behavior of StrToInt and StrToFloat and support convert JSON to date, time and timestamp

### CODE REVIEW

**Comment by Reminiscent** [comment]
LGTM

**Comment by qw4990** [comment]
@wjhuang2016 This PR has two LGTs, please fix the CI.

**Pull request merged**
