### PR TITLE
BR: Git action improvement

### LINKED ISSUE #29622: BR: git action improvement
## Enhancement
currently, the runner quota only had 20 runner, those have to run all PR around 158 repo under PingCap. BR Git Action taken 30 minutes for each commit. We remote those redundant compile action, and trigger window compile only PR merged.

### PR DESCRIPTION
**Pull request by fengou1**
### What problem does this PR solve?

Issue Number: close #29622

Problem Summary:
currently, the runner quota only had 20 runner, those have to run all PR around 158 repo under PingCap. BR Git Action taken 30 minutes for each commit. We remote those redundant compile action, and trigger window compile only PR merged.

### What is changed and how it works?
Remove compile under linux familiy kernel, BR only requires go  to build project.
So that we remove MAC OS, FreeBSD and Ubuntu, only keep window platform, and only merge PR will trigger the Windows compile action.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by kennytm** [comment]
* The "Ubuntu" one is actually building against AArch64
* The FreeBSD one was introduced in pingcap/br#1070 because it was found that FreeBSD's types are not exactly compatible with Linux.

These are still valuable. I'd suggest, based on https://github.community/t/trigger-action-via-pull-request-message/17630/4:

1. change the `pull_request` trigger to run only when a label was added:

    ```yaml
    on:
      push:
        ...
      pull_request:
        types: [labeled]  # <--
        branches:
          ...
    ```

2. make the jobs conditional, only run when the label added is `action/run-br-cross-platform-build` .

    ```yaml
    jobs:
      compile-windows:
        if: github.event_name == 'push' || github.event_name == 'pull_request' && github.event.label.name == 'action/run-br-cross-platform-build'
        ...
      compile-freebsd:
        if: github.event_name == 'pull_request' && github.event.label.name == 'action/run-br-cross-platform-build'
        ...
      compile-linux-aarch64:
        if: github.event_name == 'pull_request' && github.event.label.name == 'action/run-br-cross-platform-build'
        ...
      compile-macos:
        if: github.event_name == 'pull_request' && github.event.label.name == 'action/run-br-cross-platform-build'
        ...
    ```

**Review by kennytm — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
