### PR TITLE
topsql: fix data race in reporter test (#31440)

### LINKED ISSUE #31439: DATA RACE in the ```TestReporterWorker```
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
==================
WARNING: DATA RACE
Read at 0x00c0001382e0 by goroutine 73:
  github.com/pingcap/tidb/util/topsql/reporter.TestReporterWorker()
      /go/tidb/util/topsql/reporter/reporter_test.go:508 +0x484
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Previous write at 0x00c0001382e0 by goroutine 76:
  github.com/pingcap/tidb/util/topsql/reporter.(*mockDataSink2).TrySend()
      /go/tidb/util/topsql/reporter/datasink_test.go:52 +0xce
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).trySend()
      /go/tidb/util/topsql/reporter/reporter.go:321 +0x2f9
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).doReport()
      /go/tidb/util/topsql/reporter/reporter.go:309 +0x255
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).reportWorker()
      /go/tidb/util/topsql/reporter/reporter.go:282 +0x106
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).Start·dwrap·5()
      /go/tidb/util/topsql/reporter/reporter.go:111 +0x39
Goroutine 73 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1504 +0x9d1
  go.uber.org/goleak.VerifyTestMain()
      /home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x59
  github.com/pingcap/tidb/util/topsql/reporter.TestMain()
      /go/tidb/util/topsql/reporter/main_test.go:26 +0x44
  main.main()
      _testmain.go:117 +0x264
Goroutine 76 (running) created at:
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).Start()
      /go/tidb/util/topsql/reporter/reporter.go:111 +0x118
  github.com/pingcap/tidb/util/topsql/reporter.TestReporterWorker()
      /go/tidb/util/topsql/reporter/reporter_test.go:481 +0x75
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
==================
==================
WARNING: DATA RACE
Read at 0x00c002c82008 by goroutine 73:
  github.com/pingcap/tidb/util/topsql/reporter.TestReporterWorker()
      /go/tidb/util/topsql/reporter/reporter_test.go:509 +0x504
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Previous write at 0x00c002c82008 by goroutine 76:
  github.com/pingcap/tidb/util/topsql/reporter.(*mockDataSink2).TrySend()
      /go/tidb/util/topsql/reporter/datasink_test.go:52 +0x95
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).trySend()
      /go/tidb/util/topsql/reporter/reporter.go:321 +0x2f9
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).doReport()
      /go/tidb/util/topsql/reporter/reporter.go:309 +0x255
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).reportWorker()
      /go/tidb/util/topsql/reporter/reporter.go:282 +0x106
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).Start·dwrap·5()
      /go/tidb/util/topsql/reporter/reporter.go:111 +0x39
Goroutine 73 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1504 +0x9d1
  go.uber.org/goleak.VerifyTestMain()
      /home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x59
  github.com/pingcap/tidb/util/topsql/reporter.TestMain()
      /go/tidb/util/topsql/reporter/main_test.go:26 +0x44
  main.main()
      _testmain.go:117 +0x264
Goroutine 76 (running) created at:
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).Start()
      /go/tidb/util/topsql/reporter/reporter.go:111 +0x118
  github.com/pingcap/tidb/util/topsql/reporter.TestReporterWorker()
      /go/tidb/util/topsql/reporter/reporter_test.go:481 +0x75
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
==================
==================
WARNING: DATA RACE
Read at 0x00c002c80050 by goroutine 73:
  github.com/pingcap/tidb/util/topsql/reporter.TestReporterWorker()
      /go/tidb/util/topsql/reporter/reporter_test.go:509 +0x51e
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Previous write at 0x00c002c80050 by goroutine 76:
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).reportWorker()
      /go/tidb/util/topsql/reporter/reporter.go:283 +0x2d2
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).Start·dwrap·5()
      /go/tidb/util/topsql/reporter/reporter.go:111 +0x39
Goroutine 73 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1504 +0x9d1
  go.uber.org/goleak.VerifyTestMain()
      /home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x59
  github.com/pingcap/tidb/util/topsql/reporter.TestMain()
      /go/tidb/util/topsql/reporter/main_test.go:26 +0x44
  main.main()
      _testmain.go:117 +0x264
Goroutine 76 (running) created at:
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).Start()
      /go/tidb/util/topsql/reporter/reporter.go:111 +0x118
  github.com/pingcap/tidb/util/topsql/reporter.TestReporterWorker()
      /go/tidb/util/topsql/reporter/reporter_test.go:481 +0x75
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
==================
==================
WARNING: DATA RACE
Read at 0x00c002c80000 by goroutine 73:
  github.com/pingcap/tidb/util/topsql/reporter.TestReporterWorker()
      /go/tidb/util/topsql/reporter/reporter_test.go:510 +0x617
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Previous write at 0x00c002c80000 by goroutine 76:
  github.com/pingcap/tidb/util/topsql/reporter.records.toProto()
      /go/tidb/util/topsql/reporter/datamodel.go:423 +0x298
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).reportWorker()
      /go/tidb/util/topsql/reporter/reporter.go:283 +0x249
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).Start·dwrap·5()
      /go/tidb/util/topsql/reporter/reporter.go:111 +0x39
Goroutine 73 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1504 +0x9d1
  go.uber.org/goleak.VerifyTestMain()
      /home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x59
  github.com/pingcap/tidb/util/topsql/reporter.TestMain()
      /go/tidb/util/topsql/reporter/main_test.go:26 +0x44
  main.main()
      _testmain.go:117 +0x264
Goroutine 76 (running) created at:
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).Start()
      /go/tidb/util/topsql/reporter/reporter.go:111 +0x118
  github.com/pingcap/tidb/util/topsql/reporter.TestReporterWorker()
      /go/tidb/util/topsql/reporter/reporter_test.go:481 +0x75
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
==================
==================
WARNING: DATA RACE
Read at 0x00c002c80018 by goroutine 73:
  github.com/pingcap/tidb/util/topsql/reporter.TestReporterWorker()
      /go/tidb/util/topsql/reporter/reporter_test.go:511 +0x71b
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Previous write at 0x00c002c80018 by goroutine 76:
  github.com/pingcap/tidb/util/topsql/reporter.records.toProto()
      /go/tidb/util/topsql/reporter/datamodel.go:423 +0x298
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).reportWorker()
      /go/tidb/util/topsql/reporter/reporter.go:283 +0x249
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).Start·dwrap·5()
      /go/tidb/util/topsql/reporter/reporter.go:111 +0x39
Goroutine 73 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1504 +0x9d1
  go.uber.org/goleak.VerifyTestMain()
      /home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x59
  github.com/pingcap/tidb/util/topsql/reporter.TestMain()
      /go/tidb/util/topsql/reporter/main_test.go:26 +0x44
  main.main()
      _testmain.go:117 +0x264
Goroutine 76 (running) created at:
  github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).Start()
      /go/tidb/util/topsql/reporter/reporter.go:111 +0x118
  github.com/pingcap/tidb/util/topsql/reporter.TestReporterWorker()
      /go/tidb/util/topsql/reporter/reporter_test.go:481 +0x75
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
==================
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #31440 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/31496
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/31496:release-5.4-f7663a881c2b
```

---

Signed-off-by: mornyx <mornyx.z@gmail.com>

Issue Number: close #31439

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by mornyx** [comment]
Should be merged after https://github.com/pingcap/tidb/pull/31414

**Review by crazycs520 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
