### PR TITLE
executor: buffer snapshotChunk to avoid too many object memory allocation (#6312)

### PR DESCRIPTION
**Pull request by XuHuaiyu**
PTAL @zz-jason @coocood

### CODE REVIEW

**Comment by zz-jason** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
No apparent performance improvement using the benchmark test,
the qps of tpc-c improves from 14k to 22k refer to [this](https://github.com/pingcap/tidb/pull/6312#issuecomment-382309773).

**Comment by XuHuaiyu** [comment]
/run-common-test tidb-test=release-1.0 tidb-private-test=release-1.0 tikv=release-1.0
/run-integration-common-tests tidb-test=release-1.0 tidb-private-test=release-1.0 tikv=release-1.0

**Comment by XuHuaiyu** [comment]
/run-common-test tidb-test=release-2.0 tidb-private-test=release-2.0 tikv=release-2.0
/run-integration-common-tests tidb-test=release-2.0 tidb-private-test=release-2.0 tikv=release-2.0

**Pull request closed without merging**
