### PR TITLE
br: more db pools to create databases

### LINKED ISSUE #56866: more db pool size is needed for br to create many databases
## Enhancement
Currently, BR only has 16 db pools to create databases, and it takes about more than one hour to create 200K databases. However, if BR uses 100 db pools to create databases, it only takes about half an hour to finish create 200K databases.

https://github.com/pingcap/tidb/blob/c550aae6a125e20c2aaa8d4f11a2f090bc8b2b50/br/pkg/restore/snap_client/client.go#L69

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #56866

Problem Summary:
Currently, BR only has 16 db pools to create databases, and it takes about more than one hour to create 200K databases. 
### What changed and how does it work?
Use 100 db pools to create databases, and it only takes about half an hour to finish create 200K databases.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by princejha95** [comment]
Why we are only thinking till 200K databases ? Would this number can change in future ? If yes, we again have to make similar changes, right ?

**Review by YuJuncen — APPROVED** [review]

**Comment by Leavrth** [comment]
> Why we are only thinking till 200K databases ? Would this number can change in future ? If yes, we again have to make similar changes, right ?

hi, @princejha95 .
During the entire database creation process, the creation speed is basically constant. Therefore, the speed of creating databases does not depend on the number of databases to be created.
The purpose of increasing db pool size is to reduce the impact of one database creation DDL latency. The time it took to create the 200K databases is just one example. Based on this PR, we can infer that
```
+-----------------+-----------+
| databases count | time cost |
+-----------------+-----------+
| 200 K           | 30 min    |
+-----------------+-----------+
| 400 K           | 60 min    |
+-----------------+-----------+
| 600 K           | 90 min    |
+-----------------+-----------+
...
```

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
