### PR TITLE
server: make dump binary time more compatible with MySQL (#21127)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21127 to release-4.0

---

Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
Dumping binary time is not compatible with MySQL with short values, e.g. 2020-11-19. MySQL will only dump 4 bytes.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Adjust the length with the time value.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
https://github.com/pingcap/tidb-test/pull/1106

### Release note 

- Make dump binary time more compatible with MySQL

### CODE REVIEW

**Comment by jackysp** [comment]
https://github.com/pingcap/tidb-test/pull/1108 related test.

**Comment by cfzjywxk** [comment]
LGTM

**Comment by lysu** [comment]
LGTM

**Review by jackysp — APPROVED** [review]

**Pull request merged**
