### PR TITLE
kv: use last range if streaming response does not contain a range entry 

### LINKED ISSUE #12131: May receive multiple rows in streaming mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

When tidb open streaming mode in pr10949 , we may receive multiple rows in TiDB.

When we prepare enviroment:

```
CREATE TABLE t1 (i INT);
INSERT INTO t1 VALUES (10),(11),(12),(13),(14),(15),(16),(17),(18),(19),
                      (20),(21),(22),(23),(24),(25),(26),(27),(28),(29),
                      (30),(31),(32),(33),(34),(35);
```

And run the SQL below for multiple times:
```

CREATE TABLE t2 (a CHAR(2), b CHAR(2), c CHAR(2), INDEX (a, b));
INSERT INTO t2 (a, b) SELECT i, i FROM t1; # 插入一把记录
INSERT INTO t2 (a, b) SELECT t1.i, t1.i FROM t1, t1 x1, t1 x2;

UPDATE t2 SET c = 10 ORDER BY a DESC, b DESC LIMIT 5;
# SHOW SESSION STATUS LIKE 'Sort%';
# SHOW STATUS LIKE 'Handler_read_%';
SELECT * FROM t2 WHERE c = 10 ORDER BY a DESC, b DESC;

DROP TABLE t2;
```

`SELECT * FROM t2 WHERE c = 10 ORDER BY a DESC, b DESC;` May return the response below:

```
mysql> SELECT * FROM t2 WHERE c = 10 ORDER BY a DESC, b DESC;
+------+------+------+
| a    | b    | c    |
+------+------+------+
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
+------+------+------+
20 rows in set (2.37 sec)
```

Here it returns multiple times of rows(expect 5, may get 10, 15 or more).

2. What did you expect to see?

```
mysql> SELECT * FROM t2 WHERE c = 10 ORDER BY a DESC, b DESC;
+------+------+------+
| a    | b    | c    |
+------+------+------+
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
+------+------+------+
5 rows in set (1.67 sec)
```

3. What did you see instead?

```
mysql> SELECT * FROM t2 WHERE c = 10 ORDER BY a DESC, b DESC;
+------+------+------+
| a    | b    | c    |
+------+------+------+
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
| 35   | 35   | 10   |
+------+------+------+
20 rows in set (2.37 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

In pr 11949. @SunRunAway

### PR DESCRIPTION
**Pull request by SunRunAway**
### What problem does this PR solve? 

Fix #12131, see https://github.com/pingcap/tidb/issues/12131#issuecomment-547828104

### What is changed and how it works?

use last range if streaming response does contain a range entry

### Check List 

Tests 

 - None

Code changes

 - None

Side effects

 - None

Related changes

 - None

Release note

 - None

### CODE REVIEW

**Comment by breeswish** [comment]
BTW note that last range is a range that has already been scanned.

**Comment by SunRunAway** [comment]
> BTW note that last range is a range that has already been scanned.

Exactly.

**Pull request merged**
