### PR TITLE
expression: implement vectorized evaluation for builtinVectorFloat32

### PR DESCRIPTION
**Pull request by EricZequan**
### What problem does this PR solve?

Issue Number: ref #54245 

Problem Summary:
Implement vectorized evaluation for `builtinVecDimsSig`, `builtinVecL1DistanceSig`, `builtinVecL2DistanceSig`, `builtinVecNegativeInnerProductSig`, `builtinVecCosineDistanceSig`, `builtinVecL2NormSig`, `builtinVecFromTextSig`, `builtinVecAsTextSig`

### What changed and how does it work?
The benchmark shows that the performance almost 1.5x fater than before. 
`builtinVecAsTextSig` and `builtinVecFromTextSig`  maintain similar performance after vectorization.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
```
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/pkg/expression
BenchmarkVectorizedBuiltinVecFunc/builtinVecCosineDistanceSig-VecBuiltinFunc-8         	   91862	     13229 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecCosineDistanceSig-NonVecBuiltinFunc-8      	   59492	     20113 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecCosineDistanceSig-VecBuiltinFunc#01-8      	  941388	      1301 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecCosineDistanceSig-NonVecBuiltinFunc#01-8   	  105184	     11463 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecCosineDistanceSig-VecBuiltinFunc#02-8      	 1000000	      1112 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecCosineDistanceSig-NonVecBuiltinFunc#02-8   	  180105	      6701 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecCosineDistanceSig-VecBuiltinFunc#03-8      	   67474	     17779 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecCosineDistanceSig-NonVecBuiltinFunc#03-8   	   40598	     29538 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecNegativeInnerProductSig-VecBuiltinFunc-8   	   99116	     12042 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecNegativeInnerProductSig-NonVecBuiltinFunc-8         	   61656	     19307 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecNegativeInnerProductSig-VecBuiltinFunc#01-8         	  950893	      1308 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecNegativeInnerProductSig-NonVecBuiltinFunc#01-8      	  102386	     11614 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecNegativeInnerProductSig-VecBuiltinFunc#02-8         	 1000000	      1068 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecNegativeInnerProductSig-NonVecBuiltinFunc#02-8      	  177921	      6726 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL2NormSig-VecBuiltinFunc-8                          	  187917	      6342 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL2NormSig-NonVecBuiltinFunc-8                       	   88740	     11773 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL2NormSig-VecBuiltinFunc#01-8                       	 1436419	       818.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL2NormSig-NonVecBuiltinFunc#01-8                    	  179916	      6678 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecAsTextSig-VecBuiltinFunc-8                          	    5595	    206589 ns/op	   98946 B/op	    3722 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecAsTextSig-NonVecBuiltinFunc-8                       	    5821	    208008 ns/op	   98944 B/op	    3722 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecAsTextSig-VecBuiltinFunc#01-8                       	  735926	      1638 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecAsTextSig-NonVecBuiltinFunc#01-8                    	  248377	      4854 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecFromTextSig-VecBuiltinFunc-8                        	    8546	    133772 ns/op	  204811 B/op	    5120 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecFromTextSig-NonVecBuiltinFunc-8                     	    8816	    137360 ns/op	  204800 B/op	    5120 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecFromTextSig-VecBuiltinFunc#01-8                     	  734040	      1617 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecFromTextSig-NonVecBuiltinFunc#01-8                  	  243121	      4855 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecDimsSig-VecBuiltinFunc-8                            	  279516	      4349 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecDimsSig-NonVecBuiltinFunc-8                         	  125860	      9396 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecDimsSig-VecBuiltinFunc#01-8                         	 1429896	       834.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecDimsSig-NonVecBuiltinFunc#01-8                      	  179166	      6665 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL1DistanceSig-VecBuiltinFunc-8                      	   43821	     27381 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL1DistanceSig-NonVecBuiltinFunc-8                   	   33884	     35434 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL1DistanceSig-VecBuiltinFunc#01-8                   	  933763	      1299 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL1DistanceSig-NonVecBuiltinFunc#01-8                	  102906	     11725 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL1DistanceSig-VecBuiltinFunc#02-8                   	 1000000	      1084 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL1DistanceSig-NonVecBuiltinFunc#02-8                	  183038	      6588 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL2DistanceSig-VecBuiltinFunc-8                      	  100116	     11971 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL2DistanceSig-NonVecBuiltinFunc-8                   	   62168	     19728 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL2DistanceSig-VecBuiltinFunc#01-8                   	  939297	      1332 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL2DistanceSig-NonVecBuiltinFunc#01-8                	  106024	     11305 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL2DistanceSig-VecBuiltinFunc#02-8                   	 1000000	      1325 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinVecFunc/builtinVecL2DistanceSig-NonVecBuiltinFunc#02-8                	  173904	      6700 ns/op	       0 B/op	       0 allocs/op
PASS
```
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by breezewish — APPROVED** [review]

**Review by breezewish — CHANGES_REQUESTED** [review]
Wrong approval

**Comment by EricZequan** [comment]
@breezewish Updated. This pr is ready for review.

**Review by breezewish — APPROVED** [review]
Looks good! Please also find other reviewers for more approvals.

**Review by windtalker — APPROVED** [review]
lgtm

**Pull request merged**
