### PR TITLE
util/types: (*Datum).ConvertTo adopt in-place convert semantic

### PR DESCRIPTION
**Pull request by tiancaiamao**
there is no need to generate a new copy of data
this change will reduce allocation, and runtime.duffcopy will also be benefited

### CODE REVIEW

**Comment by shenli** [comment]
Any performance compare result?

**Comment by tiancaiamao** [comment]
Not test for performance yet, but this change remove `CastValue` in pprof file completely.
pprof file show that `CastValue` is top3 of object allocation, which take 4~5% of overall allocations.

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
PTAL @shenli

**Comment by zimulala** [comment]
LGTM

**Comment by tiancaiamao** [comment]
if ConvertTo use in-place semantic, it would introduce a problem: sometime we should not modify the raw value. for example, 

```
set @a = 2;
select a+1.23;
```

`@a` should not change to floating-point number from a exact number.


we need copy a Datum and operator on the copy. 
I wonder whether the copy will be malloced on stack, so I tested that code:

```
func main() {
	d := types.NewStringDatum("123")
	t := types.NewFieldType(mysql.TypeNewDecimal)
	c := d
	c.ConvertTo(t)
}
```

```
go build -gcflags '-m' aaa.go

# command-line-arguments
./aaa.go:10: inlining call to types.NewFieldType
./aaa.go:11: moved to heap: c
./aaa.go:12: c escapes to heap
./aaa.go:10: main &types.FieldType literal does not escape
```

that means c escaped, it's malloced in heap ... the optimization would be pointless

**Pull request closed without merging**
