### PR TITLE
add changelog for v2.1.0-rc.4

### PR DESCRIPTION
**Pull request by zz-jason**
### What problem does this PR solve? 

add changelog for v2.1.0-rc.4

### Check List 

Tests 

 - No code

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by zz-jason** [comment]
@shenli PTAL

**Comment by zz-jason** [comment]
@CaitinChen PTAL

**Comment by zz-jason** [comment]
@winkyao PTAL

**Comment by shenli** [comment]
@zz-jason We need to add this to the release-2.1 branch.

**Comment by zz-jason** [comment]
@shenli okay, let's merge this PR firstly.

**Comment by shenli** [comment]
LGTM

**Pull request merged**
