### PR TITLE
planner: enable the dynamic mode of partition tables by default

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: related to #24150 

Problem Summary: planner: enable the dynamic mode of partition tables by default

### What is changed and how it works?

planner: enable the dynamic mode of partition tables by default

### Check List 

Tests 

- Unit test

### Release note 

- planner: enable the dynamic mode of partition tables by default

### CODE REVIEW

**Comment by qw4990** [comment]
WIP since some integration and tidb-test cases may need to be updated.

**Review by tiancaiamao — APPROVED** [review]

**Review by rebelice — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Pull request merged**
