### PR TITLE
tests/realtikvtest: add tests for adding index

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/35983

Problem Summary:

To improve the confidence that the code change about add-index optimization is correct, we add the integration tests first.

### What is changed and how it works?

This PR adds the test for the `ADD INDEX` statements. It covers the following cases:

- Different data types such as integers, decimals, time, char, blob and JSON.
- Unique indexes, non-unique indexes and primary keys.
- Range-partition table and non-partition table.
- Insert, update and delete workloads during adding index.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
  On my laptop, this test costs about 2 mins:
  ```
  ok  	github.com/pingcap/tidb/tests/realtikvtest/addindextest	132.083s
  ```
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by hawkingrei** [comment]
wait for https://github.com/PingCAP-QE/ci/pull/1294 merging

**Pull request merged**
