### PR TITLE
disttask: change the test package to "*_test"

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/42262

Problem Summary:

### What is changed and how it works?

- Change the test package to "*_test"
- Tiny update
- Make `TestSimple` stable, add a round operation for time.
```
 dispatcher_test.go:150: 
        	Error Trace:	disttask/framework/dispatcher/dispatcher_test.go:150
        	            				disttask/framework/dispatcher/dispatcher_test.go:178
        	Error:      	Not equal: 
        	            	expected: "2023-03-15 03:01:18"
        	            	actual  : "2023-03-15 03:01:19"
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lcwangchao — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by zimulala** [comment]
Failed because DATA RACE: https://github.com/pingcap/tidb/issues/42270

**Comment by zimulala** [comment]
Failed because DATA RACE: https://github.com/pingcap/tidb/issues/42307

**Pull request merged**
