### PR TITLE
tikv: support scatter region with option api (#19844)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19844 to release-4.0

---

### What problem does this PR solve?

ref https://github.com/tikv/pd/issues/2732

Problem Summary:

### What is changed and how it works?
Updated pd scatter regions API to the latest version. If the regions to be scattered referenced to a table, the tableID would be sent as an parameter to the scatter api

The reason why pd providing a new api to support scattering in described in https://github.com/tikv/pd/issues/2732 .

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note
* No release note

### CODE REVIEW

**Review by lzmhhh123 — COMMENTED** [review]
Please fix conflicts.

**Comment by Yisaer** [comment]
@lzmhhh123 PTAL

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Comment by ichn-hu** [comment]
LGTM

**Review by ichn-hu — DISMISSED** [review]

**Review by zz-jason — COMMENTED** [review]
@Yisaer please resolve conflicts and fix CI.

**Comment by Yisaer** [comment]
@Yisaer  solve the conflict.

**Review by SunRunAway — APPROVED** [review]

**Pull request merged**
