### PR TITLE
session: don't change the DDL lease when doing bootstrap (#10908)

### PR DESCRIPTION
**Pull request by zimulala**
Cherry pick #10908  to v2.1

### CODE REVIEW

**Comment by zimulala** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zimulala** [comment]
PTAL @bb7133 @crazycs520 @winkyao

**Comment by bb7133** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by mahjonp** [comment]
/run-integration-ddl-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
