### PR TITLE
br: update the readme.md document url from v4.0 to stable.

### LINKED ISSUE #36182: br: update the readme.md document url from v4.0 to stable.
## Enhancement

br: update the readme.md document url from v4.0 to stable.

### PR DESCRIPTION
**Pull request by yangl**
### What problem does this PR solve?

Issue Number: close #36182

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [X] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by yangl** [comment]
Anyone who will review this pr?

**Review by xiongjiwei — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Pull request merged**
