### PR TITLE
executor: fix data race in the slowQueryRuntimeStats

### LINKED ISSUE #39631: DATA RACE in the slowQueryRuntimeStats
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
=================
WARNING: DATA RACE
Read at 0x00c010058750 by goroutine 136021:
  github.com/pingcap/tidb/executor.(*slowQueryRuntimeStats).Clone()
      executor/slow_query.go:1037 +0x4b
  github.com/pingcap/tidb/util/execdetails.(*RuntimeStatsColl).RegisterStats()
      util/execdetails/execdetails.go:735 +0x204
  github.com/pingcap/tidb/executor.(*MemTableReaderExec).Close()
      executor/memtable_reader.go:141 +0x12a
  github.com/pingcap/tidb/executor.(*recordSet).Close()
      executor/adapter.go:182 +0x4c
  github.com/pingcap/tidb/session.(*execStmtResult).Close()
      session/session.go:2401 +0x6f
  github.com/pingcap/tidb/testkit.(*TestKit).QueryToErr()
      testkit/testkit.go:206 +0x311
  github.com/pingcap/tidb/infoschema_test.TestSlowQueryOOM.func2()
      infoschema/cluster_tables_test.go:697 +0xb1
  github.com/pingcap/tidb/infoschema_test.TestSlowQueryOOM()
      infoschema/cluster_tables_test.go:703 +0x953
  github.com/pingcap/tidb/session.runStmt()
      session/session.go:2346 +0x761
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      session/session.go:2210 +0x1025
  github.com/pingcap/tidb/testkit.(*TestKit).ExecWithContext()
      testkit/testkit.go:318 +0x96e
  github.com/pingcap/tidb/testkit.(*TestKit).MustExecWithContext()
      testkit/testkit.go:127 +0xb7
  github.com/pingcap/tidb/testkit.(*TestKit).MustExec()
      testkit/testkit.go:122 +0xf7
  github.com/pingcap/tidb/infoschema_test.TestSlowQueryOOM()
      infoschema/cluster_tables_test.go:691 +0x727
  github.com/pingcap/tidb/domain.(*Domain).rebuildSysVarCache()
      domain/sysvar_cache.go:146 +0x844
  github.com/pingcap/tidb/domain.(*Domain).LoadSysVarCacheLoop()
      domain/domain.go:1360 +0xa8
  github.com/pingcap/tidb/session.BootstrapSession()
      session/session.go:3016 +0x693
  github.com/pingcap/tidb/domain.(*Domain).GetSessionCache()
      domain/sysvar_cache.go:62 +0x59
  github.com/pingcap/tidb/session.(*session).loadCommonGlobalVariablesIfNeeded()
      session/session.go:3268 +0x104
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      session/session.go:2125 +0x2a5
  github.com/pingcap/tidb/session.(*session).ExecuteInternal()
      session/session.go:1673 +0x471
  github.com/pingcap/tidb/domain.(*Domain).LoadPrivilegeLoop()
      domain/domain.go:1302 +0x130
  github.com/pingcap/tidb/session.BootstrapSession()
      session/session.go:3009 +0x644
  github.com/pingcap/tidb/testkit.bootstrap()
      testkit/mockstore.go:84 +0xac
  github.com/pingcap/tidb/testkit.CreateMockStoreAndDomain()
      testkit/mockstore.go:69 +0xe9
  github.com/pingcap/tidb/infoschema_test.TestSlowQueryOOM()
      infoschema/cluster_tables_test.go:628 +0x6c
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1493 +0x47
Previous write at 0x00c010058750 by goroutine 148447:
  github.com/pingcap/tidb/executor.(*slowQueryRetriever).parseSlowLog()
      executor/slow_query.go:473 +0x56d
  github.com/pingcap/tidb/executor.(*slowQueryRetriever).parseDataForSlowLog()
      executor/slow_query.go:211 +0x234
  github.com/pingcap/tidb/executor.(*slowQueryRetriever).initializeAsyncParsing.func1()
      executor/slow_query.go:1141 +0x71
Goroutine 136021 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1493 +0x75d
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:1846 +0x99
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.runTests()
      GOROOT/src/testing/testing.go:1844 +0x7ec
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:1726 +0xa84
  go.uber.org/goleak.VerifyTestMain()
      external/org_uber_go_goleak/testmain.go:53 +0x70
  github.com/pingcap/tidb/infoschema.TestMain()
      infoschema/main_test.go:32 +0x43c
  main.main()
      bazel-out/k8-fastbuild/bin/infoschema/infoschema_test_/testmain.go:216 +0x5e8
Goroutine 148447 (running) created at:
  github.com/pingcap/tidb/executor.(*slowQueryRetriever).initializeAsyncParsing()
      executor/slow_query.go:1141 +0x199
  github.com/pingcap/tidb/executor.(*slowQueryRetriever).retrieve()
      executor/slow_query.go:86 +0x14b
  github.com/pingcap/tidb/executor.(*MemTableReaderExec).Next()
      executor/memtable_reader.go:118 +0x443
  github.com/pingcap/tidb/executor.Next()
      executor/executor.go:328 +0x5c3
  github.com/pingcap/tidb/executor.(*ExecStmt).next()
      executor/adapter.go:1142 +0x89
  github.com/pingcap/tidb/executor.(*recordSet).Next()
      executor/adapter.go:153 +0x164
  github.com/pingcap/tidb/session.(*execStmtResult).Next()
      <autogenerated>:1 +0x76
  github.com/pingcap/tidb/session.GetRows4Test()
      session/tidb.go:336 +0xea
  github.com/pingcap/tidb/testkit.(*TestKit).QueryToErr()
      testkit/testkit.go:205 +0x2f1
  github.com/pingcap/tidb/infoschema_test.TestSlowQueryOOM.func2()
      infoschema/cluster_tables_test.go:697 +0xb1
  github.com/pingcap/tidb/infoschema_test.TestSlowQueryOOM()
      infoschema/cluster_tables_test.go:703 +0x953
  github.com/pingcap/tidb/session.runStmt()
      session/session.go:2346 +0x761
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      session/session.go:2210 +0x1025
  github.com/pingcap/tidb/testkit.(*TestKit).ExecWithContext()
      testkit/testkit.go:318 +0x96e
  github.com/pingcap/tidb/testkit.(*TestKit).MustExecWithContext()
      testkit/testkit.go:127 +0xb7
  github.com/pingcap/tidb/testkit.(*TestKit).MustExec()
      testkit/testkit.go:122 +0xf7
  github.com/pingcap/tidb/infoschema_test.TestSlowQueryOOM()
      infoschema/cluster_tables_test.go:691 +0x727
  github.com/pingcap/tidb/domain.(*Domain).rebuildSysVarCache()
      domain/sysvar_cache.go:146 +0x844
  github.com/pingcap/tidb/domain.(*Domain).LoadSysVarCacheLoop()
      domain/domain.go:1360 +0xa8
  github.com/pingcap/tidb/session.BootstrapSession()
      session/session.go:3016 +0x693
  github.com/pingcap/tidb/domain.(*Domain).GetSessionCache()
      domain/sysvar_cache.go:62 +0x59
  github.com/pingcap/tidb/session.(*session).loadCommonGlobalVariablesIfNeeded()
      session/session.go:3268 +0x104
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      session/session.go:2125 +0x2a5
  github.com/pingcap/tidb/session.(*session).ExecuteInternal()
      session/session.go:1673 +0x471
  github.com/pingcap/tidb/domain.(*Domain).LoadPrivilegeLoop()
      domain/domain.go:1302 +0x130
  github.com/pingcap/tidb/session.BootstrapSession()
      session/session.go:3009 +0x644
  github.com/pingcap/tidb/testkit.bootstrap()
      testkit/mockstore.go:84 +0xac
  github.com/pingcap/tidb/testkit.CreateMockStoreAndDomain()
      testkit/mockstore.go:69 +0xe9
  github.com/pingcap/tidb/infoschema_test.TestSlowQueryOOM()
      infoschema/cluster_tables_test.go:628 +0x6c
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1493 +0x47
================== 
```

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #39631

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
You can fix this by following change:
```diff
diff --git a/executor/memtable_reader.go b/executor/memtable_reader.go
index dc215e71fe..4d6e5112bf 100644
--- a/executor/memtable_reader.go
+++ b/executor/memtable_reader.go
@@ -138,7 +138,7 @@ func (e *MemTableReaderExec) Next(ctx context.Context, req *chunk.Chunk) error {
 // Close implements the Executor Close interface.
 func (e *MemTableReaderExec) Close() error {
        if stats := e.retriever.getRuntimeStats(); stats != nil && e.runtimeStats != nil {
-               e.ctx.GetSessionVars().StmtCtx.RuntimeStatsColl.RegisterStats(e.id, stats)
+               defer e.ctx.GetSessionVars().StmtCtx.RuntimeStatsColl.RegisterStats(e.id, stats)
        }
        return e.retriever.close()
 }
```

**Review by crazycs520 — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]

**Pull request merged**
