### PR TITLE
types: handle `NULL datum` if we need convert it to string.

### PR DESCRIPTION
**Pull request by winoros**
Thank you for working on TiDB! Please read TiDB's [CONTRIBUTING](https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md) document **BEFORE** filing this PR.

## What have you changed? (mandatory)

Statistics may contain `NULL` values, and this will make `DatumsToString` fail.
So we may meet error if we run `show stats` or `dump stats`.

## What are the type of the changes (mandatory)?
Bug fix

## How has this PR been tested (mandatory)?

~~I don't know how to generate a good case for this test. @lamxTyler any good suggestion?~~

added one in unit-test.

PTAL @coocood @lamxTyler @zz-jason

### CODE REVIEW

**Comment by lamxTyler** [comment]
```sql
create table t(a int, index idx(a));
insert into t values (null);
analyze table t;
show stats_buckets;
```
Is this okay?

**Comment by winoros** [comment]
added @lamxTyler PTAL

**Comment by coocood** [comment]
LGTM

**Pull request merged**
