### PR TITLE
server: Change proxyprotocol to lazy mode

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Issue Number: ref #36312

Problem Summary:

As using AWS NLB and enable PROXY protocol v2 (PPv2) NLB will not send PPv2 header data until client send data to server. This will trigger `go-proxyprotocol` raise timeout error and client cannot handshake with server.

### What is changed and how it works?

This PR will use new version of `go-proxyprotocol` and set the mode to `lazy`. Then the PPv2 header will be handled when the first `Read` function call. That will allow TiDB server can send handshake packet before NLB send PPv2 header.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Support AWS NLB proxy protocol
```

### CODE REVIEW

**Review by xhebox — COMMENTED** [review]
LGTM, is this still in WIP? Or are we waiting for verifications?

**Comment by blacktear23** [comment]
just waiting for aws verification

**Comment by blacktear23** [comment]
@xhebox AWS NLB test passed and one more thing, if we change proxy protocol to lazy mode, the header read timeout is useless. So shall we add some comments for related command line parameter?

**Comment by xhebox** [comment]
> @xhebox AWS NLB test passed and one more thing, if we change proxy protocol to lazy mode, the header read timeout is useless. So shall we add some comments for related command line parameter?

Sure!

**Review by xhebox — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
