### PR TITLE
planner: fix bug that aggregate push down may generate wrong plan for outer joins

### LINKED ISSUE #34465: mpp: wrong planner behaviors when `tidb_opt_agg_push_down` and `tidb_enforce_mpp` enabled
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run with tiflash

```
1. table schema.

CREATE TABLE `customer` (
  `C_CUSTKEY` bigint(20) NOT NULL,
  `C_NAME` varchar(25) NOT NULL,
  `C_ADDRESS` varchar(40) NOT NULL,
  `C_NATIONKEY` bigint(20) NOT NULL,
  `C_PHONE` char(15) NOT NULL,
  `C_ACCTBAL` decimal(15,2) NOT NULL,
  `C_MKTSEGMENT` char(10) NOT NULL,
  `C_COMMENT` varchar(117) NOT NULL,
  PRIMARY KEY (`C_CUSTKEY`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;


CREATE TABLE `orders` (
  `O_ORDERKEY` bigint(20) NOT NULL,
  `O_CUSTKEY` bigint(20) NOT NULL,
  `O_ORDERSTATUS` char(1) NOT NULL,
  `O_TOTALPRICE` decimal(15,2) NOT NULL,
  `O_ORDERDATE` date NOT NULL,
  `O_ORDERPRIORITY` char(15) NOT NULL,
  `O_CLERK` char(15) NOT NULL,
  `O_SHIPPRIORITY` bigint(20) NOT NULL,
  `O_COMMENT` varchar(79) NOT NULL,
  PRIMARY KEY (`O_ORDERKEY`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

2. set tiflash replica for table customer and orders
3. insert into customer values (6, "a", "a", 2, "12345", 3, "Z", "haha");
4. set @@tidb_enforce_mpp=1; set @@tidb_opt_agg_push_down=1;
5.
                     select
                             c_custkey,
                             count(o_orderkey) as c_count
                     from
                             customer left outer join orders on
                                     c_custkey = o_custkey
                     group by
                             c_custkey

```

Run without tiflash

```
1. 
CREATE TABLE `customer` (
  `C_CUSTKEY` bigint(20) NOT NULL,
  `C_NAME` varchar(25) NOT NULL,
  `C_ADDRESS` varchar(40) NOT NULL,
  `C_NATIONKEY` bigint(20) NOT NULL,
  `C_PHONE` char(15) NOT NULL,
  `C_ACCTBAL` decimal(15,2) NOT NULL,
  `C_MKTSEGMENT` char(10) NOT NULL,
  `C_COMMENT` varchar(117) NOT NULL,
  PRIMARY KEY (`C_CUSTKEY`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;


CREATE TABLE `orders` (
  `O_ORDERKEY` bigint(20) NOT NULL,
  `O_CUSTKEY` bigint(20) NOT NULL,
  `O_ORDERSTATUS` char(1) NOT NULL,
  `O_TOTALPRICE` decimal(15,2) NOT NULL,
  `O_ORDERDATE` date NOT NULL,
  `O_ORDERPRIORITY` char(15) NOT NULL,
  `O_CLERK` char(15) NOT NULL,
  `O_SHIPPRIORITY` bigint(20) NOT NULL,
  `O_COMMENT` varchar(79) NOT NULL,
  PRIMARY KEY (`O_ORDERKEY`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

2. insert into customer values (6, "a", "a", 2, "12345", 3, "Z", "haha");
3.
select c_custkey,count(o_orderkey) as c_count from customer left outer join orders on c_custkey = o_custkey group by c_custkey;
4.
+-----------+---------+
| c_custkey | c_count |
+-----------+---------+
|         6 |       0 |
+-----------+---------+

4. set @@tidb_enforce_mpp=1; set @@tidb_opt_agg_push_down=1;
5. 
explain select c_custkey,count(o_orderkey) as c_count from customer left outer join orders on c_custkey = o_custkey group by c_custkey;
+----------------------------------+----------+-----------+----------------+---------------------------------------------------------------------------------------------------------------------------------+
| id                               | estRows  | task      | access object  | operator info                                                                                                                   |
+----------------------------------+----------+-----------+----------------+---------------------------------------------------------------------------------------------------------------------------------+
| Projection_8                     | 1.00     | root      |                | test.customer.c_custkey, Column#18                                                                                              |
| └─Projection_9                   | 1.00     | root      |                | Column#19, test.customer.c_custkey                                                                                              |
|   └─HashJoin_11                  | 1.00     | root      |                | left outer join, equal:[eq(test.customer.c_custkey, test.orders.o_custkey)]                                                     |
|     ├─TableReader_13(Build)      | 1.00     | root      |                | data:TableFullScan_12                                                                                                           |
|     │ └─TableFullScan_12         | 1.00     | cop[tikv] | table:customer | keep order:false, stats:pseudo                                                                                                  |
|     └─HashAgg_18(Probe)          | 8000.00  | root      |                | group by:test.orders.o_custkey, funcs:count(Column#20)->Column#19, funcs:firstrow(test.orders.o_custkey)->test.orders.o_custkey |
|       └─TableReader_19           | 8000.00  | root      |                | data:HashAgg_14                                                                                                                 |
|         └─HashAgg_14             | 8000.00  | cop[tikv] |                | group by:test.orders.o_custkey, funcs:count(test.orders.o_orderkey)->Column#20                                                  |
|           └─TableFullScan_17     | 10000.00 | cop[tikv] | table:orders   | keep order:false, stats:pseudo                                                                                                  |
+----------------------------------+----------+-----------+----------------+---------------------------------------------------------------------------------------------------------------------------------+
6.
select c_custkey,count(o_orderkey) as c_count from customer left outer join orders on c_custkey = o_custkey group by c_custkey;

+-----------+---------+
| c_custkey | c_count |
+-----------+---------+
|         6 |    NULL |
+-----------+---------+
```

### 2. What did you expect to see? (Required)

```
+-----------+---------+
| c_custkey | c_count |
+-----------+---------+
|         6 |       0 |
+-----------+---------+
```

### 3. What did you see instead (Required)

with tiflash

`ERROR 1105 (HY000): other error for mpp stream: DB::Exception: Cannot convert NULL value to non-Nullable type`

without tiflash

```
+-----------+---------+
| c_custkey | c_count |
+-----------+---------+
|         6 |    NULL |
+-----------+---------+
```

### 4. What is your TiFlash/TiDB/TiKV version? (Required)

master、release-5.4

### PR DESCRIPTION
**Pull request by fixdb**
### What problem does this PR solve?

Issue Number: close #34465

Problem Summary:
When we push down aggregate past outer join, the top count aggregate assumed
that the partial count aggregate always return non-null value. But in case of
outer joins when the aggregate is pushed down to the null generating side of
the outer join, the input for the final aggregate may be nullable.

Before this patch, the final count aggregate always assume its input is not
nullable, hence during aggregate elimination, the optimizer rewrote aggregate
into a plain column of null-generating side of outer join, which led to the
wrong result.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by qw4990** [comment]
We should format these files by using `gofmt -w {file-path}`:
```
[2022-05-10T06:38:28.319Z] planner/core/integration_test.go
[2022-05-10T06:38:28.319Z] planner/core/rule_aggregation_push_down.go
[2022-05-10T06:38:28.319Z] planner/core/integration_test.go
[2022-05-10T06:38:28.319Z] planner/core/rule_aggregation_push_down.go
[2022-05-10T06:38:28.319Z] make: *** [fmt] Error 1
```

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by Reminiscent — APPROVED** [review]

**Comment by fixdb** [comment]
Looks like a flaky test failure:

Error: 5/13 15:07:04.424 +00:00] [ERROR] [handle.go:655] ["[stats] dump stats delta fail"] [error="previous statement: update mysql.stats_meta set version = 433181011321028609, count = count + 1, modify_count = modify_count + 1 where table_id = 69: [domain:8027]Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV"] [errorVerbose="[domain:8027]Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV\ngithub.com/tikv/client-go/v2/txnkv/transaction.

**Pull request merged**
