### PR TITLE
session: let handleAssertionFailure work for partitioned table

### LINKED ISSUE #40629: Assertion error log cannot print mvcc info for partitioned table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

An assertion error on a partitioned table

### 2. What did you expect to see? (Required)

Corresponding MVCC info in logs.

### 3. What did you see instead (Required)

"assertion failed but table not found in infoschema"

### 4. What is your TiDB version? (Required)

6.1 to master (6.5).

### PR DESCRIPTION
**Pull request by ekexium**
### What problem does this PR solve?

Issue Number: close #40629

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Comment by ekexium** [comment]
@cfzjywxk PTAL

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
