### PR TITLE
expression: avoid `Order By` constant expression error when plan cache is enabled

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/16203 

Problem Summary:

Error is reported for `order by rand()` when plan cache is enabled.

### What is changed and how it works?

What's Changed:

- remove `Rand` / `Sysdate` / `UUID` from `DeferredFunctions`, because they should not be folded into constant according to `unFoldableFunctions`, otherwise, they would be converted to a `Constant` with `DeferredExpr` in `funcCallToExpression`. This change makes the behavior regarding these functions consistent when plan cache is enabled / disabled.

- check if the order by items can be treated as constants during execution using a new function, instead of `IsMutableEffectsExpr`, which is specifically designed for de-duplicating expressions.

How it Works:

Related previous PRs for this change:
- https://github.com/pingcap/tidb/pull/8105: enables plan cache for functions like `now()`;
- https://github.com/pingcap/tidb/pull/10064: first fix for `order by rand()` when plan cache is disabled by using `ConstItem()`;
- https://github.com/pingcap/tidb/pull/11839: second fix for `order by rand()` when plan cache is disabled by using `IsMutableEffectsExpr()`;

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

N/A

### CODE REVIEW

**Comment by zz-jason** [comment]
should we also cherry-pick this bugfix to release-2.1, release-3.0 and release-3.1?

**Comment by eurekaka** [comment]
> should we also cherry-pick this bugfix to release-2.1, release-3.0 and release-3.1?

@zz-jason plan cache is not GA for those branches, so we don't need cherry-picks for them?

**Comment by zz-jason** [comment]
Users may use plan cache in these releases. If they met this bug and not willing to upgrade the cluster to release-4.0, maybe they can update there cluster to the latest version in the corresponding release branch.

**Comment by lawyerphx** [comment]
LGTM

**Comment by SunRunAway** [comment]
Should `LogicalTopN` also be modified?

**Pull request merged**
