### PR TITLE
ddl, executor: fix creating unique index without partition column error when enable-global-index is true

### LINKED ISSUE #21731: create unique index without partition column error when enable-global-index is true
## Development Task

Please answer these questions before submitting your issue. Thanks!

related issue: https://github.com/pingcap/tidb/issues/18032

### 1. Minimal reproduce step (Required)

TiDB config:

```toml
enable-global-index=true
```

```sql
create table t (a int, b int, unique index idx(a)) partition by list columns(b) (partition p0 values in (1), partition p1 values in (2));
```

### 2. What did you expect to see? (Required)

Execute success.

Currently, `create table` without unique index, but `alter table add unique index` later will be success.

```sqll
test> create table t (a int, b int) partition by list columns(b) (partition p0 values in (1), partition p1 values in (2));
Query OK, 0 rows affected
Time: 0.098s
test> alter table t add unique index idx (a);
Query OK, 0 rows affected
Time: 2.818s
```

### 3. What did you see instead (Required)

```sql
test> create table t (a int, b int, unique index idx(a)) partition by list columns(b) (partition p0 values in (1), partition p1 values in (2));
(1503, "A UNIQUE INDEX must include all columns in the table's partitioning function")
```

### 4. What is your TiDB version? (Required)

```sql
> select tidb_version();
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1812-gd33b81b1e                    |
| Edition: Community                                                |
| Git Commit Hash: d33b81b1ee69bd60a56e45f87774e76014720a6e         |
| Git Branch: master                                                |
| UTC Build Time: 2020-12-14 12:59:19                               |
| GoVersion: go1.14.4                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #21731 

Problem Summary:

### What is changed and how it works?

What's Changed:
fix creating unique index without partition column error when enable-global-index is true
How it Works:
check whether `enable-global-index` is enabled, if it is enabled, error should not be thrown.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by xhebox — COMMENTED** [review]
Do we need to cherry pick to 5.0rc, @crazycs520 ? Rest LGTM.

**Comment by tiancaiamao** [comment]
It seems the test environment is not stable now.

**Pull request merged**
