### PR TITLE
tests: move IT in executor to tests/integrationtest (PART 11)

### LINKED ISSUE #47076: Move IT in `executor/` to `tests/integrationtest`
- [x] pkg/executor/adapter_test.go
 - [x] pkg/executor/aggfuncs/func_max_min_test.go
 - [x] pkg/executor/analyze_test.go
 - [x] pkg/executor/asyncloaddata/util_test.go
 - [x] pkg/executor/batch_point_get_test.go
 - [x] pkg/executor/charset_test.go
 - [x] pkg/executor/cluster_table_test.go
 - [x] pkg/executor/compact_table_test.go
 - [x] pkg/executor/copr_cache_test.go
 - [x] pkg/executor/cte_test.go
 - [x] pkg/executor/delete_test.go
 - [x] pkg/executor/distsql_test.go
 - [x] pkg/executor/executor_failpoint_test.go
 - [x] pkg/executor/executor_test.go
 - [x] pkg/executor/executor_txn_test.go
 - [x] pkg/executor/explainfor_test.go
 - [x] pkg/executor/explain_test.go
 - [x] pkg/executor/grant_test.go
 - [x] pkg/executor/historical_stats_test.go
 - [x] pkg/executor/hot_regions_history_table_test.go
 - [x] pkg/executor/importer/chunk_process_testkit_test.go
 - [x] pkg/executor/importer/job_test.go
 - [x] pkg/executor/importer/precheck_test.go
 - [x] pkg/executor/import_into_test.go
 - [x] pkg/executor/index_advise_test.go
 - [x] pkg/executor/index_lookup_join_test.go
 - [x] pkg/executor/index_lookup_merge_join_test.go
 - [x] pkg/executor/infoschema_cluster_table_test.go
 - [x] pkg/executor/infoschema_reader_test.go
 - [x] pkg/executor/insert_test.go
 - [x] pkg/executor/inspection_common_test.go
 - [x] pkg/executor/inspection_result_test.go
 - [x] pkg/executor/inspection_summary_test.go
 - [x] pkg/executor/internal/calibrateresource/calibrate_resource_test.go
 - [x] pkg/executor/internal/querywatch/query_watch_test.go
 - [x] pkg/executor/join_test.go
 - [x] pkg/executor/memtable_reader_test.go
 - [x] pkg/executor/merge_join_test.go
 - [x] pkg/executor/metrics_reader_test.go
 - [x] pkg/executor/parallel_apply_test.go
 - [x] pkg/executor/partition_table_test.go
 - [x] pkg/executor/point_get_test.go
 - [x] pkg/executor/prepared_test.go
 - [x] pkg/executor/recover_test.go
 - [x] pkg/executor/resource_tag_test.go
 - [x] pkg/executor/revoke_test.go
 - [x] pkg/executor/rowid_test.go
 - [x] pkg/executor/sample_test.go
 - [x] pkg/executor/select_into_test.go
 - [x] pkg/executor/set_test.go
 - [x] pkg/executor/show_placement_test.go
 - [x] pkg/executor/show_stats_test.go
 - [x] pkg/executor/simple_test.go
 - [x] pkg/executor/slow_query_sql_test.go
 - [x] pkg/executor/sort_test.go
 - [x] pkg/executor/stale_txn_test.go
 - [x] pkg/executor/statement_context_test.go
 - [x] pkg/executor/temporary_table_test.go
 - [x] pkg/executor/test/admintest/admin_test.go
 - [x] pkg/executor/test/aggregate/aggregate_test.go
 - [x] pkg/executor/test/analyzetest/analyze_bench_test.go
 - [x] pkg/executor/test/analyzetest/analyze_test.go
 - [x] pkg/executor/test/analyzetest/memorycontrol/memory_control_test.go
 - [x] pkg/executor/test/autoidtest/autoid_test.go
 - [x] pkg/executor/test/ddl/ddl_test.go
 - [x] pkg/executor/test/distsqltest/distsql_test.go
 - [ ] pkg/executor/test/executor/executor_test.go
 - [ ] pkg/executor/test/fktest/foreign_key_test.go
 - [ ] pkg/executor/test/indexmergereadtest/index_merge_reader_test.go
 - [x] pkg/executor/test/issuetest/executor_issue_test.go
 - [x] pkg/executor/test/jointest/hashjoin/hash_join_test.go
 - [x] pkg/executor/test/jointest/join_test.go
 - [x] pkg/executor/test/kvtest/kv_test.go
 - [x] pkg/executor/test/loaddatatest/load_data_test.go
 - [x] pkg/executor/test/loadremotetest/util_test.go
 - [x] pkg/executor/test/memtest/mem_test.go
 - [x] pkg/executor/test/oomtest/oom_test.go
 - [x] pkg/executor/test/partitiontest/partition_test.go
 - [ ] pkg/executor/test/passwordtest/password_management_test.go
 - [ ] pkg/executor/test/seqtest/prepared_test.go
 - [x] pkg/executor/test/seqtest/seq_executor_test.go
 - [x] pkg/executor/test/showtest/show_test.go
 - [x] pkg/executor/test/simpletest/chunk_reuse_test.go
 - [x] pkg/executor/test/simpletest/simple_test.go
 - [x] pkg/executor/test/splittest/split_table_test.go
 - [x] pkg/executor/test/tiflashtest/tiflash_test.go
 - [x] pkg/executor/test/unstabletest/memory_test.go
 - [x] pkg/executor/test/unstabletest/unstable_test.go
 - [x] pkg/executor/test/writetest/write_test.go
 - [x] pkg/executor/tikv_regions_peers_table_test.go
 - [x] pkg/executor/trace_test.go
 - [x] pkg/executor/union_scan_test.go
 - [x] pkg/executor/update_test.go
 - [x] pkg/executor/window_test.go
 - [x] pkg/executor/write_concurrent_test.go

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #47076

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by Defined2014** [comment]
/cc @SeaRise @YangKeao 
PTAL

**Review by SeaRise — APPROVED** [review]
lgtm

**Pull request merged**
