### PR TITLE
server: add context cancel for domain close

### LINKED ISSUE #17999: BR built-in tidb cannot ended
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
can't be stable reproduced now, but it is suspected that it was caused by the transfer region leader at the end of backup process

### 2. What did you expect to see? (Required)
br exit normally
### 3. What did you see instead (Required)
The br can't be close , it  report error 
```
{"log":"I0611 13:03:50.883378       1 restore.go:86] [2020/06/11 13:03:50.883 +00:00] [ERROR] [domain.go:522] [\"reload schema in loop, schema syncer restart failed\"] [error=\"rpc error: code = Canceled desc = grpc: the client connection is closing\"] [errorVerbose=\"rpc error: code = Canceled desc = grpc: the client connection is closing\\ngithub.com/pingcap/errors.AddStack\\n\\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/errors.go:174\\ngithub.com/pingcap/errors.Trace\\n\\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/juju_adaptor.go:15\\ngithub.com/pingcap/tidb/owner.contextDone\\n\\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200512142211-0623e4d44563/owner/manager.go:380\\ngithub.com/pingcap/tidb/owner.NewSession\\n\\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200512142211-0623e4d44563/owner/manager.go:142\\ngithub.com/pingcap/tidb/ddl/util.(*schemaVersionSyncer).Restart\\n\\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200512142211-0623e4d44563/ddl/util/syncer.go:216\\ngithub.com/pingcap/tidb/domain.(*Domain).mustRestartSyncer\\n\\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200512142211-0623e4d44563/domain/domain.go:547\\ngithub.com/pingcap/tidb/domain.(*Domain).loadSchemaInLoop\\n\\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200512142211-0623e4d44563/domain/domain.go:520\\nruntime.goexit\\n\\t/usr/local/go/src/runtime/asm_amd64.s:1357\"] [stack=\"github.com/pingcap/tidb/domain.(*Domain).loadSchemaInLoop\\n\\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200512142211-0623e4d44563/domain/domain.go:522\"]\n","stream":"stderr","time":"2020-06-11T13:03:50.883645205Z"}
```
and br internal tidb can't be closed. keep report these logs
```
{"log":"I0611 13:03:50.883394       1 restore.go:86] [2020/06/11 13:03:50.883 +00:00] [INFO] [domain.go:512] [\"reload schema in loop, schema syncer need restart\"]\n","stream":"stderr","time":"2020-06-11T13:03:50.883672465Z"}
{"log":"I0611 13:03:50.883407       1 restore.go:86] [2020/06/11 13:03:50.883 +00:00] [INFO] [schema_validator.go:96] [\"the schema validator stops\"]\n","stream":"stderr","time":"2020-06-11T13:03:50.883677902Z"}
{"log":"W0611 13:09:17.448668       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1alpha1.Restore ended with: too old resource version: 1327937 (1331390)\n","stream":"stderr","time":"2020-06-11T13:09:17.448850479Z"}
{"log":"I0611 15:18:53.717773       1 restore.go:86] [2020/06/11 15:18:53.717 +00:00] [WARN] [pd.go:109] [\"get timestamp too slow\"] [\"cost time\"=43.169697ms]\n","stream":"stderr","time":"2020-06-11T15:18:53.717971657Z"}
{"log":"I0611 16:09:01.910550       1 restore.go:86] [2020/06/11 16:09:01.910 +00:00] [WARN] [pd.go:109] [\"get timestamp too slow\"] [\"cost time\"=220.465054ms]\n","stream":"stderr","time":"2020-06-11T16:09:01.910688936Z"}
{"log":"I0611 16:24:51.696514       1 restore.go:86] [2020/06/11 16:24:51.696 +00:00] [WARN] [pd.go:109] [\"get timestamp too slow\"] [\"cost time\"=33.098493ms]\n","stream":"stderr","time":"2020-06-11T16:24:51.696693992Z"}
{"log":"I0611 17:31:31.697048       1 restore.go:86] [2020/06/11 17:31:31.696 +00:00] [WARN] [pd.go:109] [\"get timestamp too slow\"] [\"cost time\"=33.609679ms]\n","stream":"stderr","time":"2020-06-11T17:31:31.697175795Z"}
{"log":"I0611 17:40:11.696457       1 restore.go:86] [2020/06/11 17:40:11.696 +00:00] [WARN] [pd.go:109] [\"get timestamp too slow\"] [\"cost time\"=33.019079ms]\n","stream":"stderr","time":"2020-06-11T17:40:11.696641733Z"}
{"log":"I0611 19:17:45.767572       1 restore.go:86] [2020/06/11 19:17:45.734 +00:00] [WARN] [pd.go:109] [\"get timestamp too slow\"] [\"cost time\"=56.109443ms]\n","stream":"stderr","time":"2020-06-11T19:17:45.769989219Z"}
{"log":"W0611 19:22:01.289109       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1alpha1.Restore ended with: too old resource version: 1331390 (1482263)\n","stream":"stderr","time":"2020-06-11T19:22:01.289332203Z"}
{"log":"I0611 19:30:51.701140       1 restore.go:86] [2020/06/11 19:30:51.701 +00:00] [WARN] [pd.go:109] [\"get timestamp too slow\"] [\"cost time\"=37.719021ms]\n","stream":"stderr","time":"2020-06-11T19:30:51.701291149Z"}
{"log":"I0611 22:31:37.717964       1 restore.go:86] [2020/06/11 22:31:37.706 +00:00] [WARN] [pd.go:109] [\"get timestamp too slow\"] [\"cost time\"=36.104787ms]\n","stream":"stderr","time":"2020-06-11T22:31:37.718086967Z"}
```
### 4. Affected version (Required)
v4.0.0

### 5. Root Cause Analysis
use GDB debug br process,  @kennytm find some clue
```
現況:
* BR 的 `(*Mgr).Close` 在等 `(*Domain).Close` 完成, 然而 `(*Domain).Close` 正在一個 `(*WaitGroup).Wait` 裡
* 這個 WaitGroup 等待 4 個 goroutine, 除了 loadSchemaInLoop (goroutine 282) 之外全部已正常結束
    - loadSchemaInLoop
    - topNSlowQueryLoop
    - infoSyncerKeeper
    - topologySyncerKeeper
* loadSchemaInLoop 的 stack trace 如下:
    22. [loadSchemaInLoop](https://github.com/pingcap/tidb/blob/0623e4d44563c0675b08f43f79d041b08d76d0ec/domain/domain.go#L520)
        * lease = 1s
    21. [mustRestartSyncer](https://github.com/pingcap/tidb/blob/0623e4d44563c0675b08f43f79d041b08d76d0ec/domain/domain.go#L547)
        * ctx = context.Background(), why?
        * do.ddl.ddlCtx.schemaSyncer.etcdCli.conn.target = "endpoint://client-50704b2f-0f96-4261-ba52-3051224ee74c/db-pd.tidb1271064089996562432:2379"
        * 懷疑是 isClose() 在 Restart 或 time.Sleep(time.Second) 期間由 false 變成 true
    20. [syncer.Restart](https://github.com/pingcap/tidb/blob/0623e4d44563c0675b08f43f79d041b08d76d0ec/ddl/util/syncer.go#L216)
    19. [owner.NewSession](https://github.com/pingcap/tidb/blob/0623e4d44563c0675b08f43f79d041b08d76d0ec/owner/manager.go#L163)
        * i = 0
        * retryCnt = math.MaxInt64
        * logPrefix = "[ddl-syncer] /tidb/ddl/all_schema_versions/d07b88b3-97e9-41b7-8f14-f3e6e28eee4a"
        * ttl = 90
    18. [concurrency.NewSession](https://github.com/etcd-io/etcd/blob/3cf2f69b5738fb702ba1a935590f36b52b18979b/clientv3/concurrency/session.go#L46)
        (...skip...)
    12. [unaryClientInterceptor](https://github.com/etcd-io/etcd/blob/3cf2f69b5738fb702ba1a935590f36b52b18979b/clientv3/retry_interceptor.go#L61)
        * method = "/etcdserverpb.Lease/LeaseGrant"
        * attempt = 92
        * callOpts.max = 100
        * lastErr = "grpc: the client connection is closing"
```

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve?

Issue Number: close #17999 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

There two possible problems:

1. The `ctx` is checked when etcdClient retries to build connections, if it's already done etcdClient will stop retrying. But the context is not canceled when domain is about to close and the etcdClient keeps retrying, the `LoadSchemaLoop` cannot finish and domain cannot be closed.
 
2. The `NewSession` function may keep retrying as the schema syner will pass in a huge retry limit number, it's also needed to signal the `ctx` to let `NewSession` quit so that `LoadSchemaLoop` will quit.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

Side effects

### Release note 

- Add context cancel for domain close

### CODE REVIEW

**Comment by cfzjywxk** [comment]
> Why not change the [ctx](https://github.com/pingcap/tidb/blob/master/domain/domain.go#L554) in `mustRestartSyncer`?

Done. There are still some parts in `schemaSyner` uses background context,  maybe we could make them the same in the future

**Comment by jackysp** [comment]
@zimulala PTAL

**Comment by cfzjywxk** [comment]
> Sorry @jackysp, you don't have permission to trigger auto merge event on this branch. You are not a committer for the related sigs:[ddl](https://github.com/pingcap/community/tree/master/special-interest-groups/sig-ddl)([slack](https://slack.tidb.io/invite?team=tidb-community&channel=sig-ddl&ref=github)).

This bot is weird...

**Comment by kennytm** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/40279/pipeline

```
[2020-06-18T06:23:27.353Z] FAIL: point_get_test.go:64: testPointGetSuite.TearDownTest

[2020-06-18T06:23:27.353Z] 

[2020-06-18T06:23:27.353Z] point_get_test.go:66:

[2020-06-18T06:23:27.353Z]     tk.MustExec("use test")

[2020-06-18T06:23:27.353Z] /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:207:

[2020-06-18T06:23:27.353Z]     tk.c.Assert(err, check.IsNil, check.Commentf("sql:%s, %v, error stack %v", sql, args, errors.ErrorStack(err)))

[2020-06-18T06:23:27.353Z] ... value *errors.withStack = [tikv:9006]GC life time is shorter than transaction duration, transaction starts at 2020-06-18 14:23:27.065 +0800 CST, GC safe point is 2020-06-18 14:23:27.076 +0800 CST ("[tikv:9006]GC life time is shorter than transaction duration, transaction starts at 2020-06-18 14:23:27.065 +0800 CST, GC safe point is 2020-06-18 14:23:27.076 +0800 CST")
```

**Comment by cfzjywxk** [comment]
> @cfzjywxk merge failed.

```
[2020-06-19T04:58:50.103Z] TiFlash seems doesn't started, retrying...
```
Seems tiflash problem not solved yet?

**Comment by kennytm** [comment]
```
[2020-06-19T06:04:11.999Z] Cannot contact test-go1130-memvolume-kbklc: java.lang.InterruptedException

[2020-06-19T06:04:36.592Z] + '[' -f test.sh ']'

[2020-06-19T06:04:44.537Z] java.net.SocketTimeoutException: sent ping but didn't receive pong within 30000ms (after 0 successful ping/pongs)
```

**Comment by kennytm** [comment]
<details><summary>Data race.</summary>

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_unit_test/runs/40522/nodes/69/log/?start=0

```
[2020-06-19T06:22:54.751Z] ==================
[2020-06-19T06:22:54.751Z] WARNING: DATA RACE
[2020-06-19T06:22:54.751Z] Read at 0x00c04947f330 by goroutine 301:
[2020-06-19T06:22:54.751Z]   runtime.chansend()
[2020-06-19T06:22:54.751Z]       /usr/local/go/src/runtime/chan.go:142 +0x0
[2020-06-19T06:22:54.751Z]   github.com/pingcap/tidb/executor.(*innerMergeWorker).doMergeJoin.func1()
[2020-06-19T06:22:54.751Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:535 +0x344
[2020-06-19T06:22:54.751Z]   github.com/pingcap/tidb/executor.(*innerMergeWorker).doMergeJoin()
[2020-06-19T06:22:54.751Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:591 +0x99f
[2020-06-19T06:22:54.751Z]   github.com/pingcap/tidb/executor.(*innerMergeWorker).handleTask()
[2020-06-19T06:22:54.751Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:500 +0xc33
[2020-06-19T06:22:54.751Z]   github.com/pingcap/tidb/executor.(*innerMergeWorker).run()
[2020-06-19T06:22:54.751Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:420 +0x28d
[2020-06-19T06:22:54.751Z] 
[2020-06-19T06:22:54.751Z] Previous write at 0x00c04947f330 by goroutine 935:
[2020-06-19T06:22:54.751Z]   runtime.closechan()
[2020-06-19T06:22:54.751Z]       /usr/local/go/src/runtime/chan.go:334 +0x0
[2020-06-19T06:22:54.751Z]   github.com/pingcap/tidb/executor.(*IndexLookUpMergeJoin).Close()
[2020-06-19T06:22:54.751Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:715 +0xef
[2020-06-19T06:22:54.751Z]   github.com/pingcap/tidb/executor.(*baseExecutor).Close()
[2020-06-19T06:22:54.751Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:171 +0xad
[2020-06-19T06:22:54.751Z]   github.com/pingcap/tidb/executor.(*LimitExec).Close()
[2020-06-19T06:22:54.751Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:1058 +0x6c
[2020-06-19T06:22:54.751Z]   github.com/pingcap/tidb/executor.(*baseExecutor).Close()
[2020-06-19T06:22:54.751Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:171 +0xad
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).Close()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:317 +0x24e
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor.(*recordSet).Close()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:151 +0x59
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/session.(*execStmtResult).Close()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1246 +0x7b
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:209 +0x426
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:46 +0x469
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:36 +0x2b1
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:35 +0x27a
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:34 +0x243
[2020-06-19T06:22:54.752Z]   github.com/pingcap/failpoint.parseTerm()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:148 +0x24d
[2020-06-19T06:22:54.752Z]   github.com/pingcap/failpoint.parse()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:125 +0xb4
[2020-06-19T06:22:54.752Z]   github.com/pingcap/failpoint.newTerms()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:97 +0x6a
[2020-06-19T06:22:54.752Z]   github.com/pingcap/failpoint.(*Failpoint).Enable()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoint.go:53 +0x53
[2020-06-19T06:22:54.752Z]   github.com/pingcap/failpoint.(*Failpoints).Enable()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoints.go:104 +0x160
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoints.go:224 +0x79
[2020-06-19T06:22:54.752Z]   runtime.call32()
[2020-06-19T06:22:54.752Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a
[2020-06-19T06:22:54.752Z]   reflect.Value.Call()
[2020-06-19T06:22:54.752Z]       /usr/local/go/src/reflect/value.go:321 +0xd3
[2020-06-19T06:22:54.752Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa
[2020-06-19T06:22:54.752Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113
[2020-06-19T06:22:54.752Z] 
[2020-06-19T06:22:54.752Z] Goroutine 301 (running) created at:
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor.(*IndexLookUpMergeJoin).startWorkers()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:206 +0x609
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor.(*IndexLookUpMergeJoin).Open()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:182 +0x3ba
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor.(*baseExecutor).Open()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:159 +0xa9
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor.(*LimitExec).Open()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:1046 +0x52
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor.(*baseExecutor).Open()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:159 +0xa9
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).Open()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:84 +0x52
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:327 +0x25f
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/session.runStmt()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1201 +0x2c1
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1166 +0xa6f
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:206 +0x91
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:46 +0x469
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:36 +0x2b1
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:35 +0x27a
[2020-06-19T06:22:54.752Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:34 +0x243
[2020-06-19T06:22:54.752Z]   github.com/pingcap/failpoint.parseTerm()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:148 +0x24d
[2020-06-19T06:22:54.752Z]   github.com/pingcap/failpoint.parse()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:125 +0xb4
[2020-06-19T06:22:54.752Z]   github.com/pingcap/failpoint.newTerms()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:97 +0x6a
[2020-06-19T06:22:54.752Z]   github.com/pingcap/failpoint.(*Failpoint).Enable()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoint.go:53 +0x53
[2020-06-19T06:22:54.752Z]   github.com/pingcap/failpoint.(*Failpoints).Enable()
[2020-06-19T06:22:54.752Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoints.go:104 +0x160
[2020-06-19T06:22:54.753Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()
[2020-06-19T06:22:54.753Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoints.go:224 +0x79
[2020-06-19T06:22:54.753Z]   runtime.call32()
[2020-06-19T06:22:54.753Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a
[2020-06-19T06:22:54.753Z]   reflect.Value.Call()
[2020-06-19T06:22:54.753Z]       /usr/local/go/src/reflect/value.go:321 +0xd3
[2020-06-19T06:22:54.753Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2020-06-19T06:22:54.753Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa
[2020-06-19T06:22:54.753Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2020-06-19T06:22:54.753Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113
[2020-06-19T06:22:54.753Z] 
[2020-06-19T06:22:54.753Z] Goroutine 935 (running) created at:
[2020-06-19T06:22:54.753Z]   github.com/pingcap/check.(*suiteRunner).forkCall()
[2020-06-19T06:22:54.753Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4a3
[2020-06-19T06:22:54.753Z]   github.com/pingcap/check.(*suiteRunner).forkTest()
[2020-06-19T06:22:54.753Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x1b9
[2020-06-19T06:22:54.753Z]   github.com/pingcap/check.(*suiteRunner).doRun()
[2020-06-19T06:22:54.753Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x13a
[2020-06-19T06:22:54.753Z]   github.com/pingcap/check.(*suiteRunner).run()
[2020-06-19T06:22:54.753Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:696 +0x13f
[2020-06-19T06:22:54.753Z]   github.com/pingcap/check.Run()
[2020-06-19T06:22:54.753Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:150 +0x5a
[2020-06-19T06:22:54.753Z]   github.com/pingcap/check.RunAll()
[2020-06-19T06:22:54.753Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:136 +0x906
[2020-06-19T06:22:54.753Z]   github.com/pingcap/check.TestingT()
[2020-06-19T06:22:54.753Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:99 +0x751
[2020-06-19T06:22:54.753Z]   github.com/pingcap/tidb/executor_test.TestT()
[2020-06-19T06:22:54.753Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:95 +0x263
[2020-06-19T06:22:54.753Z]   testing.tRunner()
[2020-06-19T06:22:54.753Z]       /usr/local/go/src/testing/testing.go:909 +0x199
[2020-06-19T06:22:54.753Z] ==================
```

</details>

**Pull request merged**
