### PR TITLE
gcunter: stable TestTuner

### LINKED ISSUE #41280: flaky test in util/gctuner
### 1. Minimal reproduce step (Required)

```
$go test -count=10 -run Test* github.com/pingcap/tidb/util/gctuner
--- FAIL: TestGlobalMemoryTuner (2.22s)
    memory_limit_tuner_test.go:103:
                Error Trace:    /x/tarball/gctuner/tidb-master/util/gctuner/memory_limit_tuner_test.go:103
                Error:          Not equal:
                                expected: 858993459
                                actual  : 1181116006
                Test:           TestGlobalMemoryTuner
    memory_limit_tuner_test.go:64:
                Error Trace:    /x/tarball/gctuner/tidb-master/util/gctuner/memory_limit_tuner_test.go:64
                                                        /x/tarball/gctuner/tidb-master/util/gctuner/panic.go:522
                                                        /x/tarball/gctuner/tidb-master/util/gctuner/testing.go:871
                                                        /x/tarball/gctuner/tidb-master/util/gctuner/memory_limit_tuner_test.go:103
                Error:          Should be false
                Test:           TestGlobalMemoryTuner
--- FAIL: TestTuner (0.29s)
    tuner_test.go:57:
                Error Trace:    /x/tarball/gctuner/tidb-master/util/gctuner/tuner_test.go:57
                Error:          "285" is not less than or equal to "250"
                Test:           TestTuner
--- FAIL: TestGlobalMemoryTuner (1.67s)
    memory_limit_tuner_test.go:92:
                Error Trace:    /x/tarball/gctuner/tidb-master/util/gctuner/memory_limit_tuner_test.go:92
                Error:          Not equal:
                                expected: 1181116006
                                actual  : 858993459
                Test:           TestGlobalMemoryTuner
    memory_limit_tuner_test.go:64:
                Error Trace:    /x/tarball/gctuner/tidb-master/util/gctuner/memory_limit_tuner_test.go:64
                                                        /x/tarball/gctuner/tidb-master/util/gctuner/panic.go:522
                                                        /x/tarball/gctuner/tidb-master/util/gctuner/testing.go:871
                                                        /x/tarball/gctuner/tidb-master/util/gctuner/memory_limit_tuner_test.go:92
                Error:          Should be false
                Test:           TestGlobalMemoryTuner
--- FAIL: TestGlobalMemoryTuner (1.66s)
    memory_limit_tuner_test.go:92:
                Error Trace:    /x/tarball/gctuner/tidb-master/util/gctuner/memory_limit_tuner_test.go:92
                Error:          Not equal:
                                expected: 1181116006
                                actual  : 858993459
                Test:           TestGlobalMemoryTuner
    memory_limit_tuner_test.go:64:
                Error Trace:    /x/tarball/gctuner/tidb-master/util/gctuner/memory_limit_tuner_test.go:64
                                                        /x/tarball/gctuner/tidb-master/util/gctuner/panic.go:522
                                                        /x/tarball/gctuner/tidb-master/util/gctuner/testing.go:871
                                                        /x/tarball/gctuner/tidb-master/util/gctuner/memory_limit_tuner_test.go:92
                Error:          Should be false
                Test:           TestGlobalMemoryTuner
--- FAIL: TestFinalizer (0.01s)
    finalizer_test.go:40:
                Error Trace:    /x/tarball/gctuner/tidb-master/util/gctuner/finalizer_test.go:40
                Error:          Not equal:
                                expected: 9
                                actual  : 8
                Test:           TestFinalizer
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #41280

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
Does 1 second enough 😂

**Comment by hawkingrei** [comment]
> Does 1 second enough 😂

I hope so, I will adjust later if it is not enough.

**Review by xhebox — APPROVED** [review]

**Pull request merged**
