### PR TITLE
*: fix wrong resource tag of transaction commit statement

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs <crazycs520@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Related PR: #24854

This PR fix wrong resource tag of transaction commit statement.

### Related changes

- N/A

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

Side effects

- N/A

### Release note 

- No release note.

### CODE REVIEW

**Comment by crazycs520** [comment]
Merge https://github.com/pingcap/tidb/pull/25617 first.

**Review by jackysp — APPROVED** [review]
LGTM

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
