### PR TITLE
Update stmt use  FromIdentVisitor for column eval.

### PR DESCRIPTION
**Pull request by qiuyesuifeng**

### CODE REVIEW

**Comment by shenli** [comment]
Why export those types?

**Comment by qiuyesuifeng** [comment]
For we will use rsets.ClauseType in stmt package, so i make those exported.

**Comment by siddontang** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
PTAL

**Comment by shenli** [comment]
LGTM

**Pull request merged**
