### PR TITLE
mocktikv: extract coprRPCHandler

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?
mocktikv depend on tidb because it needs to support coprocessor.

Part of https://github.com/pingcap/tidb/issues/22513

### What is changed and how it works?
What's Changed:
- extract coprRPCHandler interface, later we can move coprocessor ralted logic out of mocktikv

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by AndreMouche — APPROVED** [review]
LGTM

**Review by JmPotato — APPROVED** [review]

**Comment by disksing** [comment]
PTAL @AndreMouche @JmPotato

**Pull request merged**
