### PR TITLE
sessionctx, executor: fix failure of reading MaxPreparedStmtCount

### LINKED ISSUE #39735: max_prepared_stmt_count doesn't take effect
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
set @@global.max_prepared_stmt_count = 2;
prepare stmt1 from 'select ? as num from dual';
prepare stmt2 from 'select ? as num from dual';
prepare stmt3 from 'select ? as num from dual';
```

### 2. What did you expect to see? (Required)
```
mysql> set @@global.max_prepared_stmt_count = 2;
Query OK, 0 rows affected (0.00 sec)

mysql> prepare stmt1 from 'select ? as num from dual';
Query OK, 0 rows affected (0.00 sec)

mysql> prepare stmt2 from 'select ? as num from dual';
Query OK, 0 rows affected (0.00 sec)

mysql> prepare stmt3 from 'select ? as num from dual';
ERROR 1461 (42000): Can't create more than maxPreparedStmtCount statements (current value: 2)
```

### 3. What did you see instead (Required)
```
mysql> set @@global.max_prepared_stmt_count = 2;
Query OK, 0 rows affected (0.01 sec)

mysql> prepare stmt1 from 'select ? as num from dual';
Query OK, 0 rows affected (0.00 sec)

mysql> prepare stmt2 from 'select ? as num from dual';
Query OK, 0 rows affected (0.00 sec)

mysql> prepare stmt3 from 'select ? as num from dual';
Query OK, 0 rows affected (0.00 sec)
```

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #39735

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]

**Comment by xuyifangreeneyes** [comment]
I found another bug about `max_prepared_stmt_count` from the failure mysql_test `ps`.
```
create table t1
(
  a int primary key,
  b char(10)
);

prepare stmt4 from 'update t1 set a=? where b=?';
set @arg1=55, @arg2='five';
execute stmt4 using @arg1, @arg2;

prepare stmt4 from 'create table t2 (a int)';
execute stmt4;
deallocate prepare stmt4;

set global max_prepared_stmt_count=1;
prepare stmt from "select 1";
```
Here is the result of TiDB(this pr):
```
mysql> create table t1
    -> (
    ->   a int primary key,
    ->   b char(10)
    -> );
Query OK, 0 rows affected (0.07 sec)

mysql> prepare stmt4 from 'update t1 set a=? where b=?';
Query OK, 0 rows affected (0.00 sec)

mysql> set @arg1=55, @arg2='five';
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt4 using @arg1, @arg2;
Query OK, 0 rows affected (0.02 sec)
Rows matched: 0  Changed: 0  Warnings: 0

mysql> prepare stmt4 from 'create table t2 (a int)';
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> execute stmt4;
Query OK, 0 rows affected (0.02 sec)

mysql> deallocate prepare stmt4;
Query OK, 0 rows affected (0.00 sec)

mysql> set global max_prepared_stmt_count=1;
Query OK, 0 rows affected (0.01 sec)

mysql> prepare stmt from "select 1";
ERROR 1461 (42000): Can't create more than maxPreparedStmtCount statements (current value: 1)
```
And here is the result of MySQL:
```
mysql> create table t1
    -> (
    ->   a int primary key,
    ->   b char(10)
    -> );
Query OK, 0 rows affected (0.16 sec)

mysql> prepare stmt4 from 'update t1 set a=? where b=?';
Query OK, 0 rows affected (0.01 sec)
Statement prepared

mysql> set @arg1=55, @arg2='five';
Query OK, 0 rows affected (0.01 sec)

mysql> execute stmt4 using @arg1, @arg2;
Query OK, 0 rows affected (0.01 sec)
Rows matched: 0  Changed: 0  Warnings: 0

mysql> prepare stmt4 from 'create table t2 (a int)';
Query OK, 0 rows affected (0.01 sec)
Statement prepared

mysql> execute stmt4;
Query OK, 0 rows affected (0.02 sec)

mysql> deallocate prepare stmt4;
Query OK, 0 rows affected (0.00 sec)

mysql> set global max_prepared_stmt_count=1;
Query OK, 0 rows affected (0.00 sec)

mysql> prepare stmt from "select 1";
Query OK, 0 rows affected (0.00 sec)
Statement prepared
```

**Comment by qw4990** [comment]
> stmt4

Could you please create a separated bug issue for this and assign it to me and @Reminiscent ...

**Comment by xuyifangreeneyes** [comment]
> > stmt4
> 
> Could you please create a separated bug issue for this and assign it to me and @Reminiscent ...

OK. I opened another issue https://github.com/pingcap/tidb/issues/39969

**Review by qw4990 — APPROVED** [review]

**Comment by xuyifangreeneyes** [comment]
/cherry-pick-to-6.5

**Pull request merged**
