### PR TITLE
executor: do not read from lock cache when snapshot read (#21529)

### LINKED ISSUE #21447: txn: read using different executors in transaction result in different results
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
/* init */ drop table if exists t1;
/* init */ CREATE TABLE `t1` ( `id` int(11) primary key, `name` varchar(20) DEFAULT NULL );
/* init */ insert into t1 values(1,'abc');

/* t1 */ begin;
/* t2 */ begin;
/* t2 */ select * from t1 where id  = 1; -- the result is "1 abc" before the update commit in t1
/* t1 */ UPDATE t1 SET name='xyz' WHERE id=1;
/* t1 */ commit;
/* t2 */ UPDATE t1 SET name='xyz' WHERE id=1; -- update the same row with same value using point get
/* t2 */ select * from t1;               -- the result is "1, abc"
/* t2 */ select * from t1 where id = 1 ; -- the result is "1, xyz"
/* t2 */ commit;
```

If the child of update is `tableScan`
```sql
/* init */ drop table if exists t1;
/* init */ CREATE TABLE `t1` ( `id` int(11) primary key, `name` varchar(20) DEFAULT NULL );
/* init */ insert into t1 values(1,'abc');

/* t1 */ begin;
/* t2 */ begin;
/* t2 */ select * from t1 where id  = 1; -- the result is "1 abc" before the update commit in t1
/* t1 */ UPDATE t1 SET name='xyz' ;
/* t1 */ commit;
/* t2 */ UPDATE t1 SET name='xyz' ; -- update the same row with same value using table scan
/* t2 */ select * from t1;               -- the result is "1, abc"
/* t2 */ select * from t1 where id = 1 ; -- the result is "1, abc", same with previous result
/* t2 */ commit;
```

### 2. What did you expect to see? (Required)

`t2` will return same results using different executors.

### 3. What did you see instead (Required)

`t2` returns the snapshot value for `tableScan` but current value for `pointGet` which may confuse the user.

### 4. What is your TiDB version? (Required)
```
Edition: Community
Git Commit Hash: f533a79253ff2b3b2d5077a259f1b28c7a1a313a
Git Branch: release-4.0

```

Maybe it's related with #21087

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21529 to release-4.0

---

Signed-off-by: you06 <you1474600@gmail.com>

### What problem does this PR solve?

Issue Number: close #21447

Problem Summary:

### What is changed and how it works?

What's Changed:

When read from snapshot and key not exist in membuffer, do not look up from lock cache.

How it Works:

Lock key will write lock cache, if the key is locked but the value is not affected the locked value will only be written into lock cache, the cached value should not read by a snapshot read.

### Related changes

- Need to cherry-pick to the release-4.0

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Comment by cfzjywxk** [comment]
Seems `batch point get` processing is missing?

**Comment by you06** [comment]
> 
> 
> Seems `batch point get` processing is missing?

Fixed.

**Review by jackysp — COMMENTED** [review]
LGTM

**Comment by cfzjywxk** [comment]
@jebter I think we need to do some benchmark after merging this PR, maybe there will be some benchmark improvement relying on the mistakenly used `pessimistic lock cache`, for example like
```
select * from t for update where pk = 1;
select * from t where pk = 1;
select * from t where pk = 1;
```
There may be some regression for this kind of benchmark.

**Comment by cfzjywxk** [comment]
LGTM

**Comment by you06** [comment]
Here's the result testing with https://gist.github.com/you06/ac94678ccfb69448238e31955ebd5350

| thread | count |  689914f3dfdea83b41c60a5baad2f818f88a8a48  |  this PR  |
| ---- | ---- | ---- | ---- |
|  1  |  1024  |  0.526ms/1896  |  1.274ms/784  |
|  2  |  1024  |  0.402ms/4958  |  1.087ms/1837  |
|  4  |  1024  |  0.350ms/11399  |  1.134ms/3521  |
|  8  |  1024  |  0.353ms/22569  |  1.008ms/7924 |
|  16  |  1024  |  0.469ms/34003  |  1.010ms/15824  |
|  32  |  1024  |  0.662ms/48259  |  1.456ms/21955  |
|  64  |  1024  |  1.073ms/59572  |  2.079ms/30766  |
|  128  |  1024  |  1.991ms/64261  |  3.348ms/38216  |
|  256  |  1024  |  3.132ms/81699  |  5.188ms/49333  |
|  512  |  1024  |  6.483ms/78963  |  9.363ms/54674  |

The latency reading from lock cache is much lower, however point get from tikv seems efficient enough.

@cfzjywxk cc

**Review by jackysp — APPROVED** [review]

**Pull request merged**
