### PR TITLE
expression: add PI into canFuncBePushed

### PR DESCRIPTION
**Pull request by Fullstop000**
Signed-off-by: Fullstop000 <fullstop1005@gmail.com>

Relate to https://github.com/tikv/tikv/pull/5812

### What problem does this PR solve? 
Add `PI()` in `canFuncBePushed`

### Check List 

Tests 

 - Integration test with copr-test

Code changes

No

Side effects
No

Related changes

No

Release note

### CODE REVIEW

**Comment by SunRunAway** [comment]
Is it really need to be push down ?

**Comment by Fullstop000** [comment]
Not sure about the necessity. Is it a requirement to modify the `canFuncBePushed` whatever a vectorized/non-vectorized push-down-function is added in TiKV? According to the https://github.com/tikv/community/blob/master/sig/coprocessor/workflow-zh_CN.md, this PR is required.

**Comment by lonng** [comment]
@SunRunAway Yes, this function should be pushed down.

**Comment by breeswish** [comment]
Looks like the best solution is to optimize this function away into a constant..? @winoros

**Comment by breeswish** [comment]
According to @winoros PI will be collapsed into constants so that PI will not actually being pushed down. Do you think we should abandon the implementation of this UDF? @winoros @lonng

**Comment by Fullstop000** [comment]
@breeswish Do I need to modify this PR to add `setPbCode` for `Pi`?

**Comment by lonng** [comment]
@Fullstop000 The PR https://github.com/pingcap/tidb/pull/13334 has fixed all `setPbCode` issues.

**Pull request closed without merging**
