### PR TITLE
planner, expression: fix incorrect result of nature join

### LINKED ISSUE #17856: The implement of natural join in TiDB
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t0(a int);
create table t1(a int);
insert into t0 values(0);
insert into t0 values(1);
insert into t0 values(2);
insert into t0 values(3);
insert into t1 values(3);
insert into t1 values(1);
insert into t1 values(0);
insert into t1 values(2);
```

### 2. What did you expect to see? (Required)
The following result is in MySQL:
```
mysql> select * from t0 natural join t1;
+------+
| a    |
+------+
|    3 |
|    1 |
|    0 |
|    2 |
+------+
4 rows in set (0.01 sec)
```
### 3. What did you see instead (Required)
```
mysql> select * from t0 natural join t1;
+------+
| a    |
+------+
|    1 |
+------+
1 row in set (0.01 sec)
```
### 4. Affected version (Required)
Any version implementing natural join in this way is affected.

### 5. Root Cause Analysis
When using `explain`, get:
```
mysql> explain select * from t0 natural join t1;
+------------------------------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------+
| id                           | estRows | task      | access object | operator info                                                                                                |
+------------------------------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------+
| MergeJoin_7                  | 4.00    | root      |               | inner join, left key:test.t0._tidb_rowid, right key:test.t1._tidb_rowid, other cond:eq(test.t0.a, test.t1.a) |
| ├─TableReader_37(Build)      | 3.20    | root      |               | data:Selection_36                                                                                            |
| │ └─Selection_36             | 3.20    | cop[tikv] |               | not(isnull(test.t1.a))                                                                                       |
| │   └─TableFullScan_35       | 4.00    | cop[tikv] | table:t1      | keep order:true, stats:pseudo                                                                                |
| └─TableReader_34(Probe)      | 3.20    | root      |               | data:Selection_33                                                                                            |
|   └─Selection_33             | 3.20    | cop[tikv] |               | not(isnull(test.t0.a))                                                                                       |
|     └─TableFullScan_32       | 4.00    | cop[tikv] | table:t0      | keep order:true, stats:pseudo                                                                                |
+------------------------------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------+
7 rows in set (0.00 sec)
```
We can see in `MergeJoin_7`, `rowid` is the part of join conditions. If the primary keys are not defined or have different names, `rowid` cannot be in join conditions.

And other natural join cases are also affected.

### PR DESCRIPTION
**Pull request by hailanwhu**
### What problem does this PR solve?

Issue Number: close #17856 

Problem Summary:
The natural join result is not correct due to `rowid` used in join conditions.
### What is changed and how it works?

 

What's Changed:
when building natural join plan, do not consider `rowid`.

### Check List 

Tests 

- Unit test
- Integration test

### CODE REVIEW

**Comment by wjhuang2016** [comment]
https://bugs.mysql.com/bug.php?id=99807 It also affects TiDB.

**Review by zz-jason — COMMENTED** [review]
LGTM

**Comment by wjhuang2016** [comment]
> https://bugs.mysql.com/bug.php?id=99807 It also affects TiDB.

@hailanwhu Please resolve this problem.

**Comment by hailanwhu** [comment]
> > https://bugs.mysql.com/bug.php?id=99807 It also affects TiDB.
> 
> @hailanwhu Please resolve this problem.

I will fix it by Saturday.

**Pull request closed without merging**
