### PR TITLE
gomod: update tidb-tools version

### PR DESCRIPTION
**Pull request by AndrewDi**
### What problem does this PR solve? 
Update tidb-tools version, so that we can build tidb on windows.

### What is changed and how it works?
Update tidb-tools version in go.mod.

### Check List 

Tests 

 - No code

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8945)

### CODE REVIEW

**Comment by zz-jason** [comment]
@WangXiangUSTC PTAL

**Comment by WangXiangUSTC** [comment]
LGTM

**Pull request merged**
