### PR TITLE
mockstore: move tidb redirector out of unistore and mocktikv

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?
In order to make `mocktikv`/`unistore` be able send RPCs to tidb server. There is a special hack in to `mocktikv` and `unistore` to create a real rpc client to send TiDB requests. https://github.com/pingcap/tidb/pull/14344

### What is changed and how it works?
This PR extracts the hack out of mock stores. It prevents special code for the mockstore from being mixed in with the production code. The extraction also reduces duplicate code. This PR can also be considered part of https://github.com/pingcap/tidb/issues/25808 (making mockstores not have to care if the remote end is TiDB)

### Check List 

Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Comment by disksing** [comment]
Originally introduced by https://github.com/pingcap/tidb/pull/14344

**Review by crazycs520 — APPROVED** [review]
lgtm

**Review by sticnarf — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]
LGTM

**Pull request merged**
