### PR TITLE
fix desc is not compatible with MySQL(#10358)

### PR DESCRIPTION
**Pull request by mantuliu**
Cherry pick #10358 to release 2.1

### CODE REVIEW

**Comment by jackysp** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zhouqiang-cl** [comment]
@zyguan PTAL, seems go version is not correct

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zyguan** [comment]
/run-all-tests tidb-test=pr/802 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zz-jason** [comment]
@jackysp PTAL

**Pull request merged**
