### PR TITLE
statistics: add more tests for extended stats

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Not a problem, add more unit tests for extended stats feature.

### What is changed and how it works?

What's Changed:

No code change.

### Related changes

N/A

### Check List 

Tests 

- Unit test
- No code

Side effects

N/A

### Release note 

- N/A

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by time-and-fate — APPROVED** [review]
/lgtm

**Pull request merged**
