### PR TITLE
types: fix a bug in decimal multiplication

### PR DESCRIPTION
**Pull request by winkyao**
## What have you changed? (mandatory)

Before this PR, we got the result from `select 0.5999991229316*0.918755041726043` is not correct:

```
mysql> select 0.5999991229316*0.918755041726043;
+-----------------------------------+
| 0.5999991229316*0.918755041726043 |
+-----------------------------------+
|    0.551252217)0-++'-+4062276588 |
+-----------------------------------+
1 row in set (0.00 sec)
``` 

This is because we don't handle the overflow in DecimalMul, after this PR, we got:

```
mysql> select 0.5999991229316*0.918755041726043;
+-----------------------------------+
| 0.5999991229316*0.918755041726043 |
+-----------------------------------+
|    0.5512522192246113614062276588 |
+-----------------------------------+
1 row in set (0.08 sec)
```

## What is the type of the changes? (mandatory)

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)

UT

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

NO

## Does this PR affect tidb-ansible update? (mandatory)

NO

## Does this PR need to be added to the release notes? (mandatory)

yes

```
fix a bug in decimal multiplication.
```

### CODE REVIEW

**Comment by winkyao** [comment]
@coocood @lysu PTAL

**Comment by coocood** [comment]
@winkyao 
Can we replace all the `add` with `add2`?

**Comment by winkyao** [comment]
@coocood In MySQL, the ADD2 is only used in decimal_mul, I think we should keep the logic.

**Comment by lysu** [comment]
@AndreMouche maybe coprocess need fix this question too?

**Comment by AndreMouche** [comment]
no,we needn't

**Pull request merged**
