### PR TITLE
*: change fsp from int8 to int

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Avoid unnecessary type conversion.

### What is changed and how it works?

change fsp from int8 to int

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
'None'
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
LGTM. Internal conversion is not necessary for the existence of `encodeValueDatum`.

**Comment by xhebox** [comment]
@wjhuang2016 Maybe rebase and merge this PR..?

**Comment by wjhuang2016** [comment]
> @wjhuang2016 Maybe rebase and merge this PR..?

But I don't have enough time now🤣

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
