### PR TITLE
server: fix cannot listen on ipv6 address

### LINKED ISSUE #38860: cannot listen on ipv6 address
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

start tidb with `--host="::"`

### 2. What did you expect to see? (Required)

tidb listen on [::]:4000

### 3. What did you see instead (Required)

tidb not listen on [::]:4000

### 4. What is your TiDB version? (Required)

v6.1.0

### PR DESCRIPTION
**Pull request by nexustar**
### What problem does this PR solve?

Issue Number: close #38860 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by nexustar** [comment]
> can you paste the result of manually test?

before:
Screenshot from 2022-11-04 09-54-14

after:
Screenshot from 2022-11-04 09-54-16

when set --host to "::" , tidb do not bind to right address

**Review by Defined2014 — APPROVED** [review]

**Pull request merged**
