### PR TITLE
store/tikv: resolve all locks no matter they're expired or not in `BatchResolveLocks`

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Should GC rollback a transaction even its lock TTL is not expired? That's hard to answer.

If we choose YES, **transactions may be killed unexpectedly by GC**.
If we choose NO, then the GC processing would be blocked by active transactions.
We're in a dilemma.

After we introduce the support for large transactions, [the TTL may be updating](https://github.com/pingcap/tidb/pull/12177).
It's hard to guarantee when GC could run if we let active transactions block GC.

The simpler solution is to let GC rollback transactions, which is the same as the elder version TiDB does.

### What is changed and how it works?

In https://github.com/pingcap/tidb/pull/11999 we choose to not resolve large transaction's lock, that's not a thoughtful change, and has potential correctness issues.

In this commit, BatchResolveLocks would resolve all locks no matter they're expired or not.

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @coocood @MyonKeminta @jackysp

**Comment by MyonKeminta** [comment]
Is there any test for it?

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
> Is there any test for it?
Construct a counterexample that does unsafe GC in the unit test is not easy work.

**Comment by MyonKeminta** [comment]
@tiancaiamao How about try to test only the `BatchResolveLock` function, and check whether it cleans up locks correctly and returns correct results?

**Comment by tiancaiamao** [comment]
> @tiancaiamao How about try to test only the `BatchResolveLock` function, and check whether it cleans up locks correctly and returns correct results?

Sounds reasonable ...

**Comment by tiancaiamao** [comment]
PTAL @MyonKeminta

**Comment by tiancaiamao** [comment]
Ping @MyonKeminta

**Comment by tiancaiamao** [comment]
PTAL @MyonKeminta

**Comment by tiancaiamao** [comment]
PTAL @jackysp

**Pull request merged**
