### PR TITLE
statistics: fix global index statistics

### LINKED ISSUE #46366: statistics: global index has wrong statistics
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
`enable-global-index = true; ` in config.

```SQL
set @@session.tidb_analyze_version = 1;
drop table if exists t;
CREATE TABLE t ( a int, b int, c int default 0, key(a) )
			PARTITION BY RANGE (a) (
			PARTITION p0 VALUES LESS THAN (10),
			PARTITION p1 VALUES LESS THAN (20),
			PARTITION p2 VALUES LESS THAN (30),
			PARTITION p3 VALUES LESS THAN (40));
insert into t(a,b) values (1,1), (2,2), (3,3), (15,15), (25,25), (35,35);
alter table t add unique index idx(b);
analyze table t;
EXPLAIN SELECT b FROM t use index(idx) WHERE b < 16 ORDER BY b;
```

### 2. What did you expect to see? (Required)
image

### 3. What did you see instead (Required)
image

### 4. What is your TiDB version? (Required)

image

### PR DESCRIPTION
**Pull request by L-maple**
### What problem does this PR solve?
This PR is to solve generating global index analyze task correctly.

Issue Number: close #46366

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by L-maple** [comment]
@Defined2014 Hi, is there any advice for this PR? so that I can improve it. Maybe I should also cc other PingCap members, but I don't know any other.

**Review by Defined2014 — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Review by mjonss — APPROVED** [review]

**Comment by mjonss** [comment]
@L-maple can you please run `make bazel_prepare`?

From the CI:
```
Please run `make bazel_prepare` to update `.bazel` files, or just apply the following git diff (run `git apply -` and paste following contents):
diff --git a/statistics/BUILD.bazel b/statistics/BUILD.bazel
index 28c6256096..6f850fadfd 100644
--- a/statistics/BUILD.bazel
+++ b/statistics/BUILD.bazel
@@ -76,7 +76,7 @@ go_test(
     data = glob(["testdata/**"]),
     embed = [":statistics"],
     flaky = True,
-    shard_count = 40,
+    shard_count = 41,
     deps = [
         "//config",
         "//parser/ast",


Checksum diff:
339c339
< b54ff08891a88900ec5b35b688f048c6  ./statistics/BUILD.bazel
---
> 14525ab2877702752b3050102a9ed0f9  ./statistics/BUILD.bazel
```

**Comment by L-maple** [comment]
> @L-maple can you please run `make bazel_prepare`?
> 
> From the CI:
> 
> ```
> Please run `make bazel_prepare` to update `.bazel` files, or just apply the following git diff (run `git apply -` and paste following contents):
> diff --git a/statistics/BUILD.bazel b/statistics/BUILD.bazel
> index 28c6256096..6f850fadfd 100644
> --- a/statistics/BUILD.bazel
> +++ b/statistics/BUILD.bazel
> @@ -76,7 +76,7 @@ go_test(
>      data = glob(["testdata/**"]),
>      embed = [":statistics"],
>      flaky = True,
> -    shard_count = 40,
> +    shard_count = 41,
>      deps = [
>          "//config",
>          "//parser/ast",
> 
> 
> Checksum diff:
> 339c339
> < b54ff08891a88900ec5b35b688f048c6  ./statistics/BUILD.bazel
> ---
> > 14525ab2877702752b3050102a9ed0f9  ./statistics/BUILD.bazel
> ```

@mjonss thanks your advice! 
but I execute `make bazel_prepare` in my mac, but it prompts the following err:
image

I will rebase master, and see what diff I need apply from CI.

**Pull request merged**
