### PR TITLE
ddl: rename test file names and clean up

### PR DESCRIPTION
**Pull request by zimulala**
## What have you changed? (mandatory)
Do some rename operations, as follows:
ddl_db_test.go -> db_test.go
ddl_db_change_test.go -> db_change_test.go
integration_test.go -> db_integration_test.go

Move some gofail tests from ddl_db_test.go to fail_db_test.go

## What are the type of the changes (mandatory)?
- Improvement (non-breaking change which is an improvement to an existing feature)

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM
Please resolve conflict.

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@zimulala Please resolve the conflict.

**Pull request merged**
