### PR TITLE
executor: fix incorrect rows returned by `TABLESAMPLE` 

### LINKED ISSUE #25257: tablesample returns error result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. config `split-table` as `false`
2. exec sql:
```
create table test.tsample1(id int primary key);
create table test.tsample2(id int primary key);
insert into test.tsample2 values(1);
select * from test.tsample1 tablesample regions();
```

### 2. What did you expect to see? (Required)

```
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)

```
+----+
| id |
+----+
|  1 |
+----+
1 row in set (1.58 sec)
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by jingshanglu**
### What problem does this PR solve?

Issue Number: close #25257
Problem Summary:
Startup parameter --split-table=false, `TableSampleExecutor` does not handle the case where the end of the region is `nil`.

Tests 

- Unit test
- Manual test 
```
create table test.tsample1(id int primary key);
create table test.tsample2(id int primary key);
insert into test.tsample2 values(1);
select * from test.tsample1 tablesample regions();
```

### Release note 

* Add the processing of region end as `nil`

### CODE REVIEW

**Review by tangenta — COMMENTED** [review]
Could you please add a test in `sample_test.go`?

**Comment by jingshanglu** [comment]
> Could you please add a test in `sample_test.go`?

ok

**Review by bb7133 — COMMENTED** [review]
LGTM

**Review by bb7133 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Pull request merged**
