### PR TITLE
*: tiny clean up

### PR DESCRIPTION
**Pull request by tiancaiamao**
I would prefer to change RecordSet interface to return
slice of values, rather than slice of pointers.
But change an interface involve too many changes.

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
LGTM
Please paste performance comparison here.

**Comment by tiancaiamao** [comment]
this is a tiny change and doesn't influence much.
run 5 times and get the average TPS

> ./tidb-bench -addr=:5001 -rows 1000000 -c 100 

before = 38231
after = 39909

**Comment by shenli** [comment]
@tiancaiamao Great! Please merge this PR.

**Pull request merged**
