### PR TITLE
br/lightning: migrate test to using testify

### LINKED ISSUE #28241: migrate test-infra to testify for `br/pkg/lightning/restore`
## Sub tasks

- [x] #32036

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?

Issue Number: close #28241

Problem Summary: Migrate tests

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note
```release-note
None
```

### CODE REVIEW

**Comment by disksing** [comment]
Now we have no idea why the test fails. holding.

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
