### PR TITLE
ddl: don't modify a column charset when the table's version is less than TableInfoVersion1 (#9480)

### PR DESCRIPTION
**Pull request by zimulala**
Cherry-pick #9480 to v2.1
Related pingcap/parser#225

### CODE REVIEW

**Comment by zimulala** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zimulala** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by cwen0** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by cwen0** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
