### PR TITLE
*: Fix go vet errors

### PR DESCRIPTION
**Pull request by shenli**
Fix following errors:
store/localstore/isolation_test.go:80: declaration of err shadows
declaration at store/localstore/isolation_test.go:59:
store/localstore/isolation_test.go:98: declaration of err shadows
declaration at store/localstore/isolation_test.go:59:

### CODE REVIEW

**Comment by siddontang** [comment]
em, my `make check` doesn't show these errors.......

**Comment by shenli** [comment]
Maybe we use different versions of vet.

➜  tidb git:(master) ✗ make check
go get github.com/golang/lint/golint
vet
vet --shadow
store/localstore/isolation_test.go:80: declaration of err shadows declaration at store/localstore/isolation_test.go:59: 
store/localstore/isolation_test.go:98: declaration of err shadows declaration at store/localstore/isolation_test.go:59: 
make: *** [check] Error 1
➜  tidb git:(master) ✗

**Comment by siddontang** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
LGTM

**Pull request merged**
