### PR TITLE
*: add a new way to calculate TPS

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve? 
Add a new way to calculate TPS. 

### What is changed and how it works?
Using `TPS = (Com_commit + Com_rollback) / Seconds` to calculate TPS. 

### Check List 

Tests 
 - No code
Screen Shot 2019-09-26 at 12 47 53

Related changes

 - Need to cherry-pick to the release branch

Release note

 - Write release note for bug-fix or new feature.

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @jackysp @coocood @lysu

**Comment by zimulala** [comment]
PTAL @jackysp @coocood @lysu

**Comment by zimulala** [comment]
PTAL @jackysp @coocood @lysu

**Comment by coocood** [comment]
LGTM

**Pull request merged**
