### PR TITLE
types , executor_test: fix invalid year value cast incorrect

### LINKED ISSUE #25993: invalid year value cast incorrect
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
set sql_mode = '';
CREATE TABLE t1 (a int, y YEAR);
insert ignore t1 values (1, 1900), (2, 2156), (3, '1900'), (4, '2156');
```

### 2. What did you expect to see? (Required)
As described in [doc](https://docs.pingcap.com/tidb/stable/data-type-date-and-time#date-and-time-types)

> Invalid YEAR value is automatically converted to 0000

```sql
mysql> select * from t1;
+------+------+
| a    | y    |
+------+------+
|    1 | 0000 |
|    2 | 0000 |
|    3 | 0000 |
|    4 | 0000 |
+------+------+
```
### 3. What did you see instead (Required)
```sql
mysql> select * from t1;
+------+------+
| a    | y    |
+------+------+
|    1 | 1901 |
|    2 | 2155 |
|    3 | 1901 |
|    4 | 2155 |
+------+------+

```
### 4. What is your TiDB version? (Required)
```sql
 Release Version: v5.2.0-alpha-206-gcb06e116c
Edition: Community
Git Commit Hash: cb06e116c1bfb1089c2e1df5072e889a3b7decd3
Git Branch: master
UTC Build Time: 2021-07-05 10:33:48
GoVersion: go1.16.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by jansu-dev**
### What problem does this PR solve?

Issue Number: close #25993

Problem Summary:

```sql
mysql> use test
Database changed

mysql> CREATE TABLE t1 (a int, y YEAR);
Query OK, 0 rows affected (0.01 sec)

mysql> insert ignore t1 values (1, 1900), (2, 2156), (3, '1900'), (4, '2156');
Query OK, 4 rows affected, 4 warnings (0.00 sec)
Records: 4  Duplicates: 0  Warnings: 4

mysql> SELECT * FROM `t1`;
+------+------+
| a    | y    |
+------+------+
|    1 | 1901 |
|    2 | 2155 |
|    3 | 1901 |
|    4 | 2155 |
+------+------+
4 rows in set (0.00 sec)
```

### What is changed and how it works?
```sql
mysql> use test
Database changed

mysql> CREATE TABLE t1 (a int, y YEAR);
Query OK, 0 rows affected (0.01 sec)

mysql> insert ignore t1 values (1, 1900), (2, 2156), (3, '1900'), (4, '2156');
Query OK, 4 rows affected, 4 warnings (0.00 sec)
Records: 4  Duplicates: 0  Warnings: 4

mysql> SELECT * FROM `t1`;
+------+------+
| a    | y    |
+------+------+
|    1 | 0000 |
|    2 | 0000 |
|    3 | 0000 |
|    4 | 0000 |
+------+------+
4 rows in set (0.00 sec)
```
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix `invalid year value cast incorrect`
```

### CODE REVIEW

**Comment by bb7133** [comment]
It looks that the CI failed:

```
[2021-12-19T11:21:56.250Z] 
[2021-12-19T11:21:56.250Z] ----------------------------------------------------------------------                                                                                                                 [2021-12-19T11:21:56.250Z] FAIL: integration_test.go:4336: testIntegrationSuite.TestIssue29834
[2021-12-19T11:21:56.250Z] 
[2021-12-19T11:21:56.250Z] integration_test.go:4345:
[2021-12-19T11:21:56.250Z]     // Only can generate one index join plan. Because the index join inner child can not be tableDual.
[2021-12-19T11:21:56.250Z]     tk.MustQuery("show warnings").Check(testkit.Rows("Warning 1105 The parameter of nth_plan() is out of range."))
[2021-12-19T11:21:56.250Z] /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:67:
[2021-12-19T11:21:56.250Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
[2021-12-19T11:21:56.250Z] ... obtained string = ""
[2021-12-19T11:21:56.250Z] ... expected string = "[Warning 1105 The parameter of nth_plan() is out of range.]\n"
[2021-12-19T11:21:56.250Z] ... sql:show warnings, args:[]
[2021-12-19T11:21:56.250Z] 
```
@jansu-dev Please check it and see if it is not introduced by this PR(if not, this is an unstable test case).

**Comment by jansu-dev** [comment]
> It looks that the CI failed:
> 
> ```
> [2021-12-19T11:21:56.250Z] 
> [2021-12-19T11:21:56.250Z] ----------------------------------------------------------------------                                                                                                                 [2021-12-19T11:21:56.250Z] FAIL: integration_test.go:4336: testIntegrationSuite.TestIssue29834
> [2021-12-19T11:21:56.250Z] 
> [2021-12-19T11:21:56.250Z] integration_test.go:4345:
> [2021-12-19T11:21:56.250Z]     // Only can generate one index join plan. Because the index join inner child can not be tableDual.
> [2021-12-19T11:21:56.250Z]     tk.MustQuery("show warnings").Check(testkit.Rows("Warning 1105 The parameter of nth_plan() is out of range."))
> [2021-12-19T11:21:56.250Z] /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:67:
> [2021-12-19T11:21:56.250Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
> [2021-12-19T11:21:56.250Z] ... obtained string = ""
> [2021-12-19T11:21:56.250Z] ... expected string = "[Warning 1105 The parameter of nth_plan() is out of range.]\n"
> [2021-12-19T11:21:56.250Z] ... sql:show warnings, args:[]
> [2021-12-19T11:21:56.250Z] 
> ```
> 
> @jansu-dev Please check it and see if it is not introduced by this PR(if not, this is an unstable test case).

@bb7133 

I have discovered what is the problem.Some discovering detail can get from [The TiDB Internal Question](https://internals.tidb.io/t/topic/532)  

And,should I close this PR? when I finish all problem about the modification, then to restart a new PR?

**Pull request closed without merging**
