### PR TITLE
sessionctx,executor: disallowed set `null` to sysvar

### LINKED ISSUE #32850: TiDB doesn't return an error on set @@SQL_MODE=NULL
### 1. Minimal reproduce step

```sql
set @@SQL_MODE=NULL;
```

### 2. What did you expect to see? 
```sql
mysql> set @@SQL_MODE=NULL;
ERROR 1231 (42000): Variable 'sql_mode' can't be set to the value of 'NULL'
```
### 3. What did you see instead 
```sql
tidb> set @@SQL_MODE=NULL;
Query OK, 0 rows affected (0.00 sec)
```
### 4. What is your TiDB version? 

```
tidb_version(): Release Version: v5.5.0-alpha-210-g11f4ca802
Edition: Community
Git Commit Hash: 11f4ca802083ee38d5972730ba8f9b72395316fb
Git Branch: master
UTC Build Time: 2022-02-24 04:52:01
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.02 sec)
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #32850

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility
Setting a sysvar to `NULL` is no longer permitted. This is not a common operation, but could cause compatibility issues in some cases.

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
An error is now returned when setting system variables to the value `NULL`. It is recommended to instead set to the empty string value ("") instead.
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @morgo @xhebox 
PTAL

**Review by xhebox — COMMENTED** [review]
I think the logic can be added to `Validation`.

https://github.com/pingcap/tidb/blob/6517f3b315a030e1f1a0bfa07c3c246a07a49fef/sessionctx/variable/varsutil.go#L205-L216

This will be executed soon after `getVarValue` is invoked.

**Comment by morgo** [comment]
I tested MySQL 8.0.28 to see how many sysvars can actually be set to `NULL`. It's not many -

session vars:
```
$ for VAR in `~/sandboxes/msb_8_0_28/use test -BNe 'show session variables' | cut -f1`; do ~/sandboxes/msb_8_0_28/use -e "SET $VAR=NULL" 2>1 > /dev/null && echo "[YES] $VAR"; done;
[YES] character_set_results
[YES] innodb_ft_user_stopword_table
[YES] innodb_tmpdir
[YES] session_track_system_variables
```

Only `character_set_results` applies to TiDB here. The other variables are noops/not present.

For global vars:
```
$ for VAR in `~/sandboxes/msb_8_0_28/use test -BNe 'show global variables' | cut -f1`; do ~/sandboxes/msb_8_0_28/use -e "SET GLOBAL $VAR=NULL" 2>1 > /dev/null && echo "[YES] $VAR"; done;
[YES] admin_ssl_ca
[YES] admin_ssl_capath
[YES] admin_ssl_cert
[YES] admin_ssl_cipher
[YES] admin_ssl_crl
[YES] admin_ssl_crlpath
[YES] admin_ssl_key
[YES] admin_tls_ciphersuites
[YES] character_set_results
[YES] init_connect
[YES] init_replica
[YES] init_slave
[YES] innodb_ft_aux_table
[YES] innodb_ft_server_stopword_table
[YES] innodb_ft_user_stopword_table
[YES] innodb_redo_log_archive_dirs
[YES] innodb_tmpdir
[YES] mandatory_roles
[YES] session_track_system_variables
[YES] ssl_ca
[YES] ssl_capath
[YES] ssl_cert
[YES] ssl_cipher
[YES] ssl_crl
[YES] ssl_crlpath
[YES] ssl_key
[YES] tls_ciphersuites
```

The ssl/tls, init_connect, character_set_results variables apply to TiDB. The others are noops/not implemented.

The other problem with global variables is because we string internally, we can not correctly represent a `NULL` value unless we change the sysvar API.

I think a better solution is to either (a) disallow `NULL` for all, or (b) continue treating it as empty string (and document the incompatibility).

**Comment by Defined2014** [comment]
> I tested MySQL 8.0.28 to see how many sysvars can actually be set to `NULL`. It's not many -
> 
> session vars:
> 
> ```
> $ for VAR in `~/sandboxes/msb_8_0_28/use test -BNe 'show session variables' | cut -f1`; do ~/sandboxes/msb_8_0_28/use -e "SET $VAR=NULL" 2>1 > /dev/null && echo "[YES] $VAR"; done;
> [YES] character_set_results
> [YES] innodb_ft_user_stopword_table
> [YES] innodb_tmpdir
> [YES] session_track_system_variables
> ```
> 
> Only `character_set_results` applies to TiDB here. The other variables are noops/not present.
> 
> For global vars:
> 
> ```
> $ for VAR in `~/sandboxes/msb_8_0_28/use test -BNe 'show global variables' | cut -f1`; do ~/sandboxes/msb_8_0_28/use -e "SET GLOBAL $VAR=NULL" 2>1 > /dev/null && echo "[YES] $VAR"; done;
> [YES] admin_ssl_ca
> [YES] admin_ssl_capath
> [YES] admin_ssl_cert
> [YES] admin_ssl_cipher
> [YES] admin_ssl_crl
> [YES] admin_ssl_crlpath
> [YES] admin_ssl_key
> [YES] admin_tls_ciphersuites
> [YES] character_set_results
> [YES] init_connect
> [YES] init_replica
> [YES] init_slave
> [YES] innodb_ft_aux_table
> [YES] innodb_ft_server_stopword_table
> [YES] innodb_ft_user_stopword_table
> [YES] innodb_redo_log_archive_dirs
> [YES] innodb_tmpdir
> [YES] mandatory_roles
> [YES] session_track_system_variables
> [YES] ssl_ca
> [YES] ssl_capath
> [YES] ssl_cert
> [YES] ssl_cipher
> [YES] ssl_crl
> [YES] ssl_crlpath
> [YES] ssl_key
> [YES] tls_ciphersuites
> ```
> 
> The ssl/tls, init_connect, character_set_results variables apply to TiDB. The others are noops/not implemented.
> 
> The other problem with global variables is because we use string internally, we can not correctly represent a `NULL` value unless we change the sysvar API.
> 
> I think a better solution is to either (a) disallow `NULL` for all, or (b) continue treating it as empty string (and document the incompatibility).

I agree with those solutions. And I will close this issue.

**Comment by Defined2014** [comment]
@morgo updated, PTAL

**Review by morgo — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
