### PR TITLE
planner: include schema name when checking duplicate table aliases

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/24563
close https://github.com/pingcap/tidb/issues/24550

Problem Summary:

Incompatible behaviors regarding duplicate table alias check with MySQL.

### What is changed and how it works?

What's Changed:

Include schema name when checking duplicate table aliases.

### Related changes

N/A

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- Fix incompatibility of duplicate table alias check with MySQL

### CODE REVIEW

**Comment by eurekaka** [comment]
integration-common-test

**Review by time-and-fate — COMMENTED** [review]
Found a bad case:
`select * from db1.t as t1,  (select * from t) as t1;`
This is valid on MySQL 8.0.25 but invalid on this PR.

**Comment by eurekaka** [comment]
Well, the behavior difference of MySQL for these 2 queries is pretty confusing.

```
MySQL [db1]> select * from db1.t as t1, t as t1;
ERROR 1066 (42000): Not unique table/alias: 't1'
MySQL [db1]> select * from db1.t as t1, (select * from t) as t1;
+------+------+
| a    | a    |
+------+------+
|    1 |    1 |
+------+------+
1 row in set (0.00 sec)
```

**Comment by eurekaka** [comment]
Close this PR until we find another solution to cover all MySQL behaviors.

**Comment by oops-lgtm** [comment]
> Well, the behavior difference of MySQL for these 2 queries is pretty confusing.
> 
> ```
> MySQL [db1]> select * from db1.t as t1, t as t1;
> ERROR 1066 (42000): Not unique table/alias: 't1'
> MySQL [db1]> select * from db1.t as t1, (select * from t) as t1;
> +------+------+
> | a    | a    |
> +------+------+
> |    1 |    1 |
> +------+------+
> 1 row in set (0.00 sec)
> ```

tested in MySQL 8.0.27, seems it's valid now
```sql
mysql> select version();
+--------------+
| version()    |
+--------------+
| 8.0.27-debug |
+--------------+
1 row in set (0.00 sec)

mysql> select * from db1.t1 as t1, t1 as t1;
Empty set (0.00 sec)
```

**Pull request closed without merging**
