### PR TITLE
vendor: update logrus

### PR DESCRIPTION
**Pull request by zhexuany**
This PR updates logrus version.

### CODE REVIEW

**Comment by zhexuany** [comment]
`dep` is able to update `logrus` to its latest version `1.0.5`. But `logrus`'s 1.0.5 release breaks a entry hook which you can find in [this issue](https://github.com/sirupsen/logrus/issues/729). That is why we have to add a constraint in our `Gopkg.toml` file to force `dep` update `logrus` to a given hash commit.

**Comment by shenli** [comment]
LGTM
@coocood @tiancaiamao PTAL

**Comment by zhexuany** [comment]
@dgsb Thanks to keeping us posted. We will investigate this. If `1.0.6` does resolve the issue, we can update to the latest version.

**Pull request merged**
