### PR TITLE
*: better gosec filtering

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: ref #31310

Problem Summary:

- ~The newer golangci-lint version brings a newer gosec version~
- ~The newer golangci-lint version allows proper filtering for gosec based on confidence and severity~

See https://github.com/golangci/golangci-lint/releases for details

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by dveeden** [comment]
c11e65052716d0fb99867b02eb4e573f207d66f8 by @tiancaiamao made some of the changes that I had in here to update the golangcilint version not needed anymore.

**Review by tangenta — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
