### PR TITLE
*: migrate tidb-tools

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/32999

Problem Summary:

### What is changed and how it works?

migrate tidb-tools into tidb and remove tidb-tool dependency.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by BornChanger — APPROVED** [review]
LGTM~

**Review by kennytm — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
