### PR TITLE
store: fix race in mergeLockScanner

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What problem does this PR solve? 

There's a bug in new added `mergeLockScanner`. In the `Start` function, it starts goroutine with a closure that captures loop variable, and as a result the PhysicalScanLock requests are not properly sent to each store. Also when PhysicalScanLock receives error, it cannot be sent to the channel because the `close(ch)` statement was put on a incorrect place.

### What is changed and how it works?

Fixed the race and covered it in tests.

### Check List 

Tests 

 - Unit test

Code changes

 - Exported MockClientStream to use in tests.

Side effects

 - No

Related changes

 - Need to cherry-pick to release-4.0 branch

Release note

 - The related feature (Green GC) will not be included in previous releases, so the bug fix doesn't need release note either.

### CODE REVIEW

**Comment by youjiali1995** [comment]
Test failed. @MyonKeminta

**Comment by bb7133** [comment]
Should we cherry-pick this PR to release-3.0?

**Comment by sticnarf** [comment]
@bb7133 We needn't. This issue only affects 4.0

**Comment by bb7133** [comment]
> @bb7133 We needn't. This issue only affects 4.0

Thanks!

**Comment by bb7133** [comment]
Hi @MyonKeminta , we don't need to do 4.0-cherry-pick for now. Before the release of 4.0.0-beta.1, all commits in master will be merged to 4.0 branch regularly.

Thanks for the attention anyway!

**Pull request merged**
