### PR TITLE
Avoid using tipb.KeyRange

### PR DESCRIPTION
**Pull request by shenli**
We do not need to set key ranges in tipb.SelectRequest.
We only need kv.KeyRange and kvproto/coprocessor.KeyRange.
This run faster in some of our cases. I will make code more cleaner latter in this PR.

@coocood @BusyJay @tiancaiamao PTAL

### CODE REVIEW

**Comment by shenli** [comment]
Reduce make slice when running EncodeRowKeyWithHandle.

Before:
BenchmarkEncodeRowKeyWithHandle-4	10000000	       118 ns/op
ok  	github.com/pingcap/tidb/tablecodec	1.324s

After:
BenchmarkEncodeRowKeyWithHandle-4	30000000	        47.7 ns/op
ok  	github.com/pingcap/tidb/tablecodec	1.498s

**Comment by shenli** [comment]
BenchmarkEncodeEndKey-4             	20000000	        97.2 ns/op
BenchmarkEncodeRowKeyWithPrefixNex-4 	10000000	       121 ns/op

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
