### PR TITLE
planner: fix prepare insert statement with union can not work

### LINKED ISSUE #37901: Error execute insert statement with date type using the prepare api
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t4 (a date) ;
prepare st1 from "insert into t4(a) select dt from (select ? as dt from dual union all select sysdate() ) a" ; 
set @t='2022-01-01 00:00:00.000000' ;
execute st1 using @t ;

### 2. What did you expect to see? (Required)

Statement executed without error.

### 3. What did you see instead (Required)

mysql> use test;
Database changed
mysql> create table t4 (a date) ;
Query OK, 0 rows affected (0.07 sec)

mysql> prepare st1 from "insert into t4(a) select dt from (select ? as dt from dual union all select sysdate() ) a" ; 
Query OK, 0 rows affected (0.00 sec)

mysql> set @t='2022-01-01 00:00:00.000000' ;
Query OK, 0 rows affected (0.00 sec)

mysql> execute st1 using @t ;
ERROR 1406 (22001): Data Too Long, field len 19, data len 26

### 4. What is your TiDB version? (Required)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.1.1
Edition: Community
Git Commit Hash: 5263a0abda61f102122735049fd0dfadc7b7f8b2
Git Branch: heads/refs/tags/v6.1.1
UTC Build Time: 2022-08-25 10:42:41
GoVersion: go1.18.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by fzzf678**
### What problem does this PR solve?

Issue Number: close #37901 

Problem Summary:
When build prepare stmt with union, we need Infer union result types by its children's types. The child's `flen` may be `-1`  represent UnspecifiedLength as the type is `varString` or other , we did't deal this particular case
### What is changed and how it works?
Add special conditions control this case
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]

**Review by fixdb — APPROVED** [review]
+1

**Comment by fixdb** [comment]
@qw4990 we need to cherry-pick this to 6.1

**Pull request merged**
