### PR TITLE
vendor: update tipb package

### PR DESCRIPTION
**Pull request by huachaohuang**
Add checksum request for "ADMIN CHECKSUM TABLE".

### CODE REVIEW

**Comment by zimulala** [comment]
Please add some comments about why need to update these.

**Comment by coocood** [comment]
The new generated file doesn't need to import 
`github.com/gogo/protobuf`

**Comment by huachaohuang** [comment]
@zimulala I have added a description.
@coocood I have removed the `github.com/gogo/protobuf`.
PTAL

**Comment by coocood** [comment]
LGTM

**Pull request merged**
