### PR TITLE
executor: avoid double closing child in "NestedLoopJoinExec" && "HashSemiJoinExec"

### LINKED ISSUE #5327: close of closed channel for UnionExec
Please answer these questions before submitting your issue. Thanks!
PTAL @zz-jason 

1. What did you do?
```
./gentest.pl --dsn dbi:mysql:host=127.0.0.1:port=4000:user=root:database=test --grammar=conf/optimizer_subquery.yy --gendata --thread=1
```

``` sql
SELECT     ( SELECT   MIN(  SUBQUERY1_t2 . `pk` ) AS SUBQUERY1_field1 FROM ( C AS SUBQUERY1_t1 INNER JOIN D AS SUBQUERY1_t2 ON (SUBQUERY1_t2 . `col_varchar_key` = SUBQUERY1_t1 . `col_varchar_key`  ) ) WHERE SUBQUERY1_t1 . `col_varchar_key` <= table1 . `col_varchar_key` AND SUBQUERY1_t2 . `col_varchar_key` >= SUBQUERY1_t1 . `col_varchar_nokey` ) AS field1 , COUNT(  table1 . `col_int_nokey` ) AS field2 , COUNT(  table2 . `pk` ) AS field3 , table1 . `col_date_key` AS field4 , table1 . `col_varchar_nokey` AS field5 , table1 . `col_varchar_nokey` AS field6 FROM ( (  SELECT   SUBQUERY2_t1 . * FROM ( C AS SUBQUERY2_t1 STRAIGHT_JOIN C AS SUBQUERY2_t2 ON (SUBQUERY2_t2 . `col_int_key` = SUBQUERY2_t1 . `pk`  ) )  ) AS table1 STRAIGHT_JOIN ( ( (  SELECT   SUBQUERY3_t2 . * FROM ( C AS SUBQUERY3_t1 INNER JOIN B AS SUBQUERY3_t2 ON (SUBQUERY3_t2 . `col_int_key` = SUBQUERY3_t1 . `col_int_key`  ) ) WHERE ( SUBQUERY3_t2 . `col_varchar_key` = 'j' OR SUBQUERY3_t2 . `pk` >= 5 ) ) AS table2 STRAIGHT_JOIN C AS table3 ON (table3 . `col_int_key` = table2 . `col_int_nokey`  ) ) ) ON (table3 . `col_varchar_key` = table2 . `col_varchar_nokey`  ) ) WHERE (  table1 . `col_varchar_key` <= ALL ( SELECT 'o' UNION DISTINCT SELECT 'h' ) ) AND table1 . `col_varchar_key` = 'l' OR table2 . `col_varchar_key` <> 'k'  GROUP BY field1, field4, field5, field6;
```

[createtable.txt](https://github.com/pingcap/tidb/files/1534394/createtable.txt)

2. What did you expect to see?

no error occurred

3. What did you see instead?

`MySQL console will not raise an error, TiDB log does.`

```
close of closed channel, goroutine 9718 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc421186000)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:389 +0xfd
panic(0x1c46420, 0x1ecd040)
	/Users/xuhuaiyu/.gvm/gos/go1.9/src/runtime/panic.go:491 +0x283
github.com/pingcap/tidb/executor.(*UnionExec).Close(0xc4211d8d00, 0xc421719850, 0x19a7254)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/executor.go:1089 +0x63
github.com/pingcap/tidb/executor.(*HashAggExec).Close(0xc420f064d0, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/aggregate.go:49 +0x8a
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc4208884e0, 0x1bdae60, 0x2553501)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/executor.go:124 +0x73
github.com/pingcap/tidb/executor.(*HashJoinExec).Close(0xc4208884e0, 0xbb, 0x4000)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/join.go:75 +0x6f
github.com/pingcap/tidb/executor.(*HashAggExec).Close(0xc420f068f0, 0xc42143c318, 0xc4217199a0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/aggregate.go:49 +0x8a
github.com/pingcap/tidb/executor.(*NestedLoopJoinExec).Close(0xc421448900, 0xbb, 0x4000)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/join.go:478 +0x90
github.com/pingcap/tidb/executor.(*ApplyJoinExec).Close(0xc42066a320, 0x1156bc3, 0xc42094a0b2)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/join.go:804 +0x34
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc420927f80, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/executor.go:124 +0x73
github.com/pingcap/tidb/executor.(*SortExec).Close(0xc4210a83c0, 0xc4206349c0, 0xc42114e009)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/sort.go:62 +0x6d
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc4211a6080, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/executor.go:124 +0x73
github.com/pingcap/tidb/executor.(*recordSet).Close(0xc421ce4cc0, 0x3, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/adapter.go:123 +0x38
github.com/pingcap/tidb/server.(*tidbResultSet).Close(0xc420827500, 0x0, 0xc4206349c8)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/driver_tidb.go:310 +0x33
github.com/pingcap/tidb/server.(ResultSet).Close-fm(0x1e24f40, 0xc421719b18)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:792 +0x2f
github.com/pingcap/tidb/terror.Call(0xc421719bc8)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/terror/terror.go:333 +0x2b
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc421186000, 0x2b39230, 0xc42085ae40, 0x2534980, 0xc420827500, 0xc420810000, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:848 +0x4d7
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc421186000, 0x2b39230, 0xc42085ae40, 0xc420990d81, 0x406, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:748 +0x115
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc421186000, 0xc420990d81, 0x407, 0x407, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:530 +0x511
github.com/pingcap/tidb/server.(*clientConn).Run(0xc421186000)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:412 +0x18a
github.com/pingcap/tidb/server.(*Server).onConn(0xc4203bff20, 0x2537560, 0xc420e80060)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/server.go:315 +0x144
created by github.com/pingcap/tidb/server.(*Server).Run
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/server.go:261 +0x496

```

4. What version of TiDB are you using (`tidb-server -V`)?
githash: 38f794d875ef64ac68a81ac2d8109d3690bcaf74

### PR DESCRIPTION
**Pull request by zz-jason**
fix #5327

### CODE REVIEW

**Comment by zz-jason** [comment]
@XuHuaiyu @hanfei1991 PTAL

**Comment by shenli** [comment]
LGTM

**Pull request merged**
