### PR TITLE
ddl: support exchange partition for label rules

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/27101

### What is changed and how it works?

What's Changed:
- change `onExchangeTablePartition` to make it work for label rules

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (https://github.com/pingcap/endless/pull/38/commits/7a90fb2ac860a6f42a2051e11983d0bb8891f7f3)
- [ ] No code

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [x] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]

**Review by xhebox — APPROVED** [review]
LGTM, but maybe there should be one api like `GetXXXX() map[string]*Label`, we have too much pattern like:

```
	for _, rule := range rules {
		if rule.ID ...
	}
```

**Comment by karuppiah7890** [comment]
Just curious, why no automated tests for this PR? Like unit test for example @rleungx

**Comment by xhebox** [comment]
> 
> 
> Just curious, why no automated tests for this PR? Like unit test for example @rleungx

Before pingcap/tidb#27551, unit tests are technically impossible. This PR, however, is proposed before #27551. I've discussed with the author in the lark, and agreed to push the tests in the following PRs.

**Comment by karuppiah7890** [comment]
okay. I don't have much context. I was just trying to understand. I still don't know much so no idea about how #27551 and this PR and unit tests are related. Just wanted to ask since other folks also commented about unit test and I noticed many unit tests in the repo in general and noticed some recent commits in master not having unit tests and wondered why not, since no unit test / no test can be very problematic in the long run

And no idea about any private repos too 😅

**Comment by rleungx** [comment]
> okay. I don't have much context. I was just trying to understand. I still don't know much so no idea about how #27551 and this PR and unit tests are related. Just wanted to ask since other folks also commented about unit test and I noticed many unit tests in the repo in general and noticed some recent commits in master not having unit tests and wondered why not, since no unit test / no test can be very problematic in the long run
> 
> And no idea about any private repos too 😅

I'm going to make up the unit tests in the next few days. ^ ^

**Comment by karuppiah7890** [comment]
@rleungx Cool! 🚀

**Comment by rleungx** [comment]
@karuppiah7890 FYI, I have made up some basic unit tests for this feature in https://github.com/pingcap/tidb/pull/27715.

**Pull request merged**
