### PR TITLE
plan, types: add type class, infer coalesce.

### PR DESCRIPTION
**Pull request by coocood**
The implementation reference MySQL's source code.
`TypeClass` corresponds to `Item_result` in MySQL.

### CODE REVIEW

**Comment by coocood** [comment]
See:

https://github.com/mysql/mysql-server/blob/5.7/sql/item_cmpfunc.cc#L4341

https://github.com/mysql/mysql-server/blob/5.7/sql/item_cmpfunc.cc#L60

**Comment by andelf** [comment]
LGTM, now tpcc runs OK. :)

**Comment by shenli** [comment]
@coocood Can we use this function: https://github.com/pingcap/tidb/blob/master/util/types/field_type.go#L194

**Comment by coocood** [comment]
@shenli 
In MySQL that function is used for calculating length and decimal.
Since we only infer type here, we don't need that funtion in this PR.

**Comment by shenli** [comment]
LGTM
@tiancaiamao @zimulala PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
