### PR TITLE
mockstore: remove unused code

### PR DESCRIPTION
**Pull request by ichn-hu**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

The code removed is not used, so removed for clearity.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by coocood — APPROVED** [review]

**Review by ngaut — APPROVED** [review]
LGTM

**Comment by ichn-hu** [comment]
CI failure https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/33603/pipeline/ is caused by a know issue https://github.com/pingcap/tidb/issues/27889, and it contains the needed debug info @tiancaiamao PTAL, I'll trigger the rerun of the CI.

**Pull request merged**
