### PR TITLE
util/format: migrate test-infra to testify

### LINKED ISSUE #26179: migrate test-infra to testify for `util/format` pkg

### PR DESCRIPTION
**Pull request by OAkaLala**
### What problem does this PR solve?
Issue Number: close #26179 

### What is changed and how it works?
What's Changed: Migrate test-infra to testify for util/format pkg.

### Release note

- No release note

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
Thanks for your contribution @OAkaLala ! LGTM.

**Review by xhebox — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Pull request merged**
