### PR TITLE
*: cleanup sysvar API usage

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/36639

Problem Summary:

Currently, the sysvar API has some confusing usage. This simplifies/unifies the exported API.

### What is changed and how it works?

See https://github.com/pingcap/tidb/issues/36639 for an explanation.

Unfortunately because of backward compatibility, SetSystemVar is split into SetSystemVar (with validation) + SetSystemVarWithoutValidation. This will need to be cleaned up in a future PR (this change is already large enough).

### Check List

Tests 

- [x] Unit test
Covered by existing tests, which are fixed here.
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility
Internal API change, not suitable for cherry pick.

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
The internal system variable API has been refactored and improved. This is a function neutral change.
```

### CODE REVIEW

**Comment by morgo** [comment]
This incorporates the previous PR https://github.com/pingcap/tidb/pull/35088 - since it is required to be fixed.

**Review by CbcWestwolf — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
