### PR TITLE
metrics:  divide Database Time Overview panel into 3 sub-panels

### LINKED ISSUE #33782: It would be better to use stack bar chart to display database time overview information
## Enhancement
It would be better to use stack bar chart to display database time overview information.

### PR DESCRIPTION
**Pull request by Yui-Song**
### What problem does this PR solve?

Issue Number: close #33782

Problem Summary:
It would be better to use stack bar chart to display database time overview information

### What is changed and how it works?
Update Performance Overview dashboard to divide Database Time Overview panel into 3 stack bar chart panels: 
- Database Time by SQL Type
- Database Time by SQL Phase
- SQL Execute Time Overview

image

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

**Review by jackysp — COMMENTED** [review]
Why need to cherry pick to 5.x? I think it is not a bug fix.

**Review by jackysp — COMMENTED** [review]
I think the third panel is not very useful, because there're some parallel executions in it. And there're some internal SQLs which will make it a little weird. See, 
image
For an empty cluster, the execution time is 0, but it still has other values.

**Comment by dbsid** [comment]
> For an empty cluster, the execution time is 0, but it still has other values.

yes，we've seen similar cases when there is ddl/auto analyze workload, the kv reuqest/tso time comes from the internal job. It takes significant work to identified the backend workloads. How about for the third graph, we show the execution time for both internal and general? Currently it only show the general execution time.

**Comment by jackysp** [comment]
> > For an empty cluster, the execution time is 0, but it still has other values.
> 
> yes，we've seen similar cases when there is ddl/auto analyze workload, the kv reuqest/tso time comes from the internal job. It takes significant work to identified the backend workloads. How about for the third graph, we show the execution time for both internal and general? Currently it only show the general execution time.

It's better if you don't distinguish internal and general.

**Comment by dbsid** [comment]
> It's better if you don't distinguish internal and general.

@Yui-Song how about for the third graph, we split the current "execute time" to "general execute time" and "internal execute time", and also need to add comments for the first/two graph that db time is for general sql type.

**Review by breeswish — APPROVED** [review]

**Pull request merged**
