### PR TITLE
types: convert string to MySQL BIT correctly (#21310)

### LINKED ISSUE #18681: load data can't load value 0/1/true/false for bit(1)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Create data file `test.txt`
```
cat test.txt
true    false   0       1
```
2. Start a tidb and connect.
```
use test;
create table t(a bit(1),b bit(1),c bit(1),d bit(1));
load data local infile 'test.txt' into table t fields terminated by '\t' enclosed by '^' lines terminated by '\n';
select * from t;
+------+------+------+------+
| a    | b    | c    | d    |
+------+------+------+------+
| NULL | NULL | NULL | NULL |
+------+------+------+------+
1 row in set (0.00 sec)

```

### 2. What did you expect to see? (Required)

Can load successfully.

### 3. What did you see instead (Required)

Null.

### 4. Affected version (Required)

All version.

### 5. Root Cause Analysis

String '0','1','true','false' convert bit(1) will cause truncated.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21310 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/22420
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/22420:release-4.0-ca93c7fc16b9
```

---

### What problem does this PR solve?

Issue Number: close #18681 

Problem Summary:

`LOAD DATA` does not take effect on BIT. Because `LOAD DATA` regards all input as strings and TiDB cannot convert any string to bit correctly

### What is changed and how it works?

What's Changed:

- convert string to bit correctly
- consider `true`, `false`, `0`, `1`

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- 
- convert string to MySQL BIT correctly

### CODE REVIEW

**Comment by rebelice** [comment]
PTAL @ichn-hu, @lzmhhh123

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ichn-hu — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]
LGTM

**Pull request merged**
