### PR TITLE
Planner,MPP: check whether the order-by items can be pushed down to tiflash/tikv or not (#29763)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #29763 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/29779
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/29779:release-5.3-4b295081eaf8
```

---

### What problem does this PR solve?

Issue Number: close #xxx
related to https://github.com/pingcap/tics/issues/3342

Problem Summary: agg functions do not check whether the order-by items can be pushed down to tiflash or not

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by guo-shaoge** [comment]
@fzhedu please remember to merge this pr. A new version is about to release. Thanks!

**Review by windtalker — APPROVED** [review]
LGTM

**Review by fzhedu — APPROVED** [review]
/LGTM

**Pull request merged**
