### PR TITLE
execdetails: tiny optimization for executor stats

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: ref #56649

Problem Summary: tiny optimization for executor stats.

### What changed and how does it work?

- Avoid use `fmt.sprintf`
- Use int instead of string in `storeType` field.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zyguan — COMMENTED** [review]
Maybe we can use a buf pool (instead of calling `bytes.NewBuffer` every time) to eliminate the overhead of bytes grow/copy

**Comment by crazycs520** [comment]
> Maybe we can use a buf pool (instead of calling `bytes.NewBuffer` every time) to eliminate the overhead of bytes grow/copy

Nice catch, how about pull another PR to do this, since `bytes.NewBuffer` is called in many places, we can change all of them.

**Review by zyguan — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
