### PR TITLE
executor: use sys session to build view for `info_schema.columns` retrieval

### LINKED ISSUE #32459: Joining views of `information_schema.columns` panic
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
第一步：创建视图
   create view vw_dict as 
 select a.table_schema,
              a.table_name as tabname,
              a.column_name,
              a.column_type,
              a.column_default,
              a.is_nullable,
              b.column_comment
         from information_schema.columns  a
         left join information_schema.columns  b
           on (a.table_name = b.table_name and
              a.column_name = b.column_name and
              b.table_schema = 'accountdb')
        where (a.table_schema = 'query_account')
        order by a.table_name, a.ordinal_position

第二步：查询视图
 select * from vw_dict
where tabname = 't_loan'

### 2. What did you expect to see? (Required)
和没有视图一样，正常出结果
### 3. What did you see instead (Required)
前端查询的navicat显示：
[Err] 2013 - Lost connection to MySQL server during query

后台的部分tidb节点状态是：Down
### 4. What is your TiDB version? (Required)

Release Version: v5.3.0
Edition: Community
Git Commit Hash: 4a1b2e9fe5b5afb1068c56de47adb07098d768d6
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-24 13:32:39
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #32459

Problem Summary:

From the panic cases related to `information_schema.columns` we encountered recently, the stack is like:

```
goroutine 656 [running]:
runtime.throw({0x103052e20, 0x15})
        /opt/homebrew/Cellar/go/1.17.5/libexec/src/runtime/panic.go:1198 +0x54 fp=0x14015deee20 sp=0x14015deedf0 pc=0x1008ced04
runtime.mapassign_fast64ptr(0x1036021e0, 0x14015c478c0, 0x140107b0900)
        /opt/homebrew/Cellar/go/1.17.5/libexec/src/runtime/map_fast64.go:266 +0x3c8 fp=0x14015deee80 sp=0x14015deee20 pc=0x1008a6bd8
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource(0x14013e55d40, {0x103aaf4d0, 0x14013d17f20}, 0x14015d56410, 0x14015df4050)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4315 +0x30b0 fp=0x14015defed0 sp=0x14015deee80 pc=0x10228ec10
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildResultSetNode(0x14013e55d40, {0x103aaf4d0, 0x14013d17f20}, {0x103ad2ea8, 0x14015df4000})
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:348 +0x2dc fp=0x14015df0410 sp=0x14015defed0 pc=0x10225d3ac
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildJoin(0x14013e55d40, {0x103aaf4d0, 0x14013d17f20}, 0x14010b60ab0)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:669 +0xe28 fp=0x14015df0c20 sp=0x14015df0410 pc=0x102262848
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildResultSetNode(0x14013e55d40, {0x103aaf4d0, 0x14013d17f20}, {0x103ad22f8, 0x14010b60ab0})
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:335 +0x7b0 fp=0x14015df1160 sp=0x14015df0c20 pc=0x10225d880
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildTableRefs(0x14013e55d40, {0x103aaf4d0, 0x14013d17f20}, 0x14015d78780)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:329 +0xb4 fp=0x14015df1270 sp=0x14015df1160 pc=0x10225cf54
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect(0x14013e55d40, {0x103aaf4d0, 0x14013d17f20}, 0x14015d4db00)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:3624 +0x760 fp=0x14015df1de0 sp=0x14015df1270 pc=0x102287440
github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build(0x14013e55d40, {0x103aaf4d0, 0x14013d17f20}, {0x103acacc0, 0x14015d4db00})
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/planner/core/planbuilder.go:700 +0xa3c fp=0x14015df22e0 sp=0x14015df1de0 pc=0x1022f332c
github.com/pingcap/tidb/planner/core.(*PlanBuilder).BuildDataSourceFromView(0x14013e55d40, {0x103aaf4d0, 0x14013d17f20}, {{0x1401077ede0, 0x4}, {0x1401077ede4, 0x4}}, 0x140107b0a80)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4597 +0x3f0 fp=0x14015df2770 sp=0x14015df22e0 pc=0x102293ce0
github.com/pingcap/tidb/executor.tryFillViewColumnType({0x103aaf4d0, 0x14013d17f20}, {0x103b212b0, 0x14010b7b680}, {0x103aeccc8, 0x14000331110}, {{0x1401077ede0, 0x4}, {0x1401077ede4, 0x4}}, ...)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/executor/show.go:1901 +0x134 fp=0x14015df28c0 sp=0x14015df2770 pc=0x102c65d14
github.com/pingcap/tidb/executor.(*hugeMemTableRetriever).dataForColumnsInTable(0x14015d5dd50, {0x103aaf4d0, 0x14013d17f20}, {0x103b212b0, 0x14010b7b680}, 0x14000330700, 0x140107b0a80, 0x201c, 0x14013e21810)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/executor/infoschema_reader.go:680 +0xf8 fp=0x14015df3100 sp=0x14015df28c0 pc=0x102ba2368
github.com/pingcap/tidb/executor.(*hugeMemTableRetriever).setDataForColumns(0x14015d5dd50, {0x103aaf4d0, 0x14013d17f20}, {0x103b212b0, 0x14010b7b680}, 0x14013e21810)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/executor/infoschema_reader.go:669 +0x21c fp=0x14015df3230 sp=0x14015df3100 pc=0x102ba20cc
github.com/pingcap/tidb/executor.(*hugeMemTableRetriever).retrieve(0x14015d5dd50, {0x103aaf4d0, 0x14013d17f20}, {0x103b212b0, 0x14010b7b680})
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/executor/infoschema_reader.go:2614 +0x300 fp=0x14015df3370 sp=0x14015df3230 pc=0x102bbaf00
github.com/pingcap/tidb/executor.(*MemTableReaderExec).Next(0x14010bcfdd0, {0x103aaf4d0, 0x14013d17f20}, 0x14015d3d950)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/executor/memtable_reader.go:118 +0x390 fp=0x14015df3570 sp=0x14015df3370 pc=0x102c0bd30
github.com/pingcap/tidb/executor.Next({0x103aaf4d0, 0x14013d17f20}, {0x103ab6758, 0x14010bcfdd0}, 0x14015d3d950)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/executor/executor.go:302 +0x61c fp=0x14015df3830 sp=0x14015df3570 pc=0x102b60efc
github.com/pingcap/tidb/executor.(*SelectionExec).Next(0x14015d560d0, {0x103aaf4d0, 0x14013d17f20}, 0x14015d78730)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/executor/executor.go:1394 +0x2bc fp=0x14015df39f0 sp=0x14015df3830 pc=0x102b6874c
github.com/pingcap/tidb/executor.Next({0x103aaf4d0, 0x14013d17f20}, {0x103ab6bd8, 0x14015d560d0}, 0x14015d78730)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/executor/executor.go:302 +0x61c fp=0x14015df3cb0 sp=0x14015df39f0 pc=0x102b60efc
github.com/pingcap/tidb/executor.(*HashJoinExec).fetchBuildSideRows(0x14015d3ab40, {0x103aaf4d0, 0x14013d17f20}, 0x140111bf4a0, 0x14000a7d6e0)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/executor/join.go:282 +0x23c fp=0x14015df3e90 sp=0x14015df3cb0 pc=0x102beb1bc
github.com/pingcap/tidb/executor.(*HashJoinExec).fetchAndBuildHashTable.func2()
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/executor/join.go:731 +0xd4 fp=0x14015df3f50 sp=0x14015df3e90 pc=0x102bf00c4
github.com/pingcap/tidb/util.WithRecovery(0x14015d7f500, 0x14015ca3e10)
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/util/misc.go:100 +0x5c fp=0x14015df3fc0 sp=0x14015df3f50 pc=0x101944b2c
runtime.goexit()
        /opt/homebrew/Cellar/go/1.17.5/libexec/src/runtime/asm_arm64.s:1133 +0x4 fp=0x14015df3fc0 sp=0x14015df3fc0 pc=0x1009071d4
created by github.com/pingcap/tidb/executor.(*HashJoinExec).fetchAndBuildHashTable
        /Users/tangenta/gopath/src/github.com/pingcap/tidb/executor/join.go:728 +0x280
```

All of these stacks have the common function: `tryFillViewColumnType` and `fetchBuildSideRows`.

- `tryFillViewColumnType` is used to extract the field type of a view in `information_schema.columns`.
- `fetchBuildSideRows` is used by HashJoinExec to get the build side of the result. It is run concurrently with `fetchProbeSideChunks` to speed up the query.

As explained in #32618, the root cause is: the goroutines created by `HashJoinExec` concurrently accessed a field in the same session.

### What is changed and how it works?

This PR uses a system session to `tryFillViewColumnType`, preventing the same session is accessed concurrently.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix an issue that panic when joining `information_schema.columns` tables.
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]

**Comment by tangenta** [comment]
Waiting for https://github.com/pingcap/tidb/pull/33991.

**Comment by tangenta** [comment]
Waiting for https://github.com/pingcap/tidb/pull/34133.

**Pull request merged**
