### PR TITLE
ddl: migrate two test cases in ddl/column_test.go to testify

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: ref #28631

Problem Summary: Let TestModifyColumn and TestFieldCase use testify and run them in serial.

unstable test link
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/28702/pipeline

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Let TestModifyColumn and TestFieldCase use testify
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @xiongjiwei @hawkingrei 
PTAL

**Review by hawkingrei — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Comment by hawkingrei** [comment]
@tisonkun PTAL

**Pull request merged**
