### PR TITLE
executor: generate fields in chunkRowRecordSet lazily

### PR DESCRIPTION
**Pull request by sticnarf**
### What problem does this PR solve?

Issue Number: ref #36049

### What is changed and how it works?

`colNames2ResultFields` was always called in `runPessimisticSelectForUpdate`. But the `Fields` method of `chunkRowRecordSet` is not always used. We can set `fields` to `nil` first in `runPessimisticSelectForUpdate` and generate it lazily when `Fields` is really called.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by ekexium** [comment]
LGTM. Is it possible to cache the results for the same inputs?

**Comment by sticnarf** [comment]
> LGTM. Is it possible to cache the results for the same inputs?

Caching is possible. But I find it is not called if the statement has a prepared plan cache. So.. Maybe not quite necessary?

**Review by ekexium — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

**Comment by cfzjywxk** [comment]
> > LGTM. Is it possible to cache the results for the same inputs?
> 
> Caching is possible. But I find it is not called if the statement has a prepared plan cache. So.. Maybe not quite necessary?

@sticnarf 
Do you mean the `colNames2ResultFields` is not called if the prepared plan cache is used?

**Comment by sticnarf** [comment]
> > > LGTM. Is it possible to cache the results for the same inputs?
> > 
> > 
> > Caching is possible. But I find it is not called if the statement has a prepared plan cache. So.. Maybe not quite necessary?
> 
> @sticnarf Do you mean the `colNames2ResultFields` is not called if the prepared plan cache is used?

Yes. More accurately, the `Fields` method of the result set is not called if `preparedStmt` is not nil:

https://github.com/pingcap/tidb/blob/5a4c14cfd54a2b18075bd48978ae481b88fd1771/server/driver_tidb.go#L447

Then, `colNames2ResultFields` is not called because we use the cached columns info.

**Pull request merged**
