### PR TITLE
executor: track partialResultMap in unparalleled aggreagte.

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary: 
In https://github.com/pingcap/tidb/pull/22463, I introduce a way to estimate the memory usage for Golamg Map. But only used in paralleled logic in HashAggExec.
The unparalleled logic is also using partialResultMap, and the memory usage should also be tracked.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: Apply https://github.com/pingcap/tidb/pull/22463 to unparalleled logic.

How it Works:

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

- No release note

### CODE REVIEW

**Review by ichn-hu — APPROVED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
> /merge

You only need to trigger /merge once, and if the CI test fails, you just re-trigger the test that failed and the bot will merge the PR for you after the CI passes.

**Pull request merged**
