### PR TITLE
[cherry-pick to pre-ga]executor,mysql: fix #4540, Navicat for MySQL compability of show create table(#4544)

### LINKED ISSUE #4540: navicat 11 `show create table` truncate
we have a table name t1:

```
CREATE TABLE `t1` (
  `a` char(36) NOT NULL,
  `b` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `c` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `d` varchar(50) DEFAULT '',
  `e` char(36) NOT NULL DEFAULT '',
  `f` char(36) NOT NULL DEFAULT '',
  `g` char(1) NOT NULL DEFAULT 'N',
  `h` varchar(100) NOT NULL,
  `i` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `j` varchar(10) DEFAULT '',
  `k` varchar(10) DEFAULT '',
  `l` varchar(20) DEFAULT '',
  `m` varchar(20) DEFAULT '',
  `n` varchar(30) DEFAULT '',
  `o` varchar(100) DEFAULT '',
  `p` varchar(50) DEFAULT '',
  `q` varchar(50) DEFAULT '',
  `r` varchar(100) DEFAULT '',
  `s` varchar(20) DEFAULT '',
  `t` varchar(50) DEFAULT '',
  `u` varchar(100) DEFAULT '',
  `v` varchar(50) DEFAULT '',
  `w` varchar(300) NOT NULL,
  `x` varchar(250) DEFAULT '',
  PRIMARY KEY (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
```
we always set flen of `show create table` to 256, in most client, it will not use the flen. But in older navicat version (older than navicat 12), it will cause `show create table` truncated:

```
/*
Navicat MySQL Data Transfer

Source Server         : tidb
Source Server Version : 50701
Source Host           : 192.168.59.105:4000
Source Database       : test

Target Server Type    : MYSQL
Target Server Version : 50701
File Encoding         : 65001

Date: 2017-09-15 17:50:55
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for t1
-- ----------------------------
DROP TABLE IF EXISTS `t1`;
CREATE TABLE `t1` (
  `a` char(36) NOT NULL,
  `b` timestamp NOT NULL DEFAULT CURRENT_;

-- ----------------------------
-- Records of t1
```

### PR DESCRIPTION
**Pull request by winkyao**
this is a cherry pick.

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by zz-jason** [comment]
@winkyao ci failed

**Comment by zimulala** [comment]
Please merge origin/pre-ga to fix CI.

**Pull request merged**
