### PR TITLE
gc: delete TiFlash placement rules in batch

### LINKED ISSUE #54068: Delete TiFlash placement rules in gc worker may take a long time
## Enhancement

Now in gc worker, we delete placement rules of TiFlash one by one. It may takes a long time when `drop database` or `drop table` with a lot of partitions. We can easily optimize it by batch delete.

https://github.com/pingcap/tidb/blob/8f568472a39980f948a9f901f58f0b0073ac494e/pkg/store/gcworker/gc_worker.go#L1547-L1557

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #54068

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by JaySon-Huang** [comment]
@Lloyd-Pottiger describes your enhancement in the release note please

**Comment by Lloyd-Pottiger** [comment]
> @Lloyd-Pottiger describes your enhancement in the release note please

done

**Pull request merged**
