### PR TITLE
expression: check timezone when encoding timestamp datum (#10303)

### PR DESCRIPTION
**Pull request by erjiaqing**
Cherry #10303 to release-2.1

### CODE REVIEW

**Comment by zz-jason** [comment]
LGTM

**Comment by lamxTyler** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-integration-compatibility-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
