### PR TITLE
schema: sequence should always be the one row

### PR DESCRIPTION
**Pull request by AilinKid**
Signed-off-by: ailinkid <314806019@qq.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/30786 and [#CI test failure](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/25026/pipeline)

Problem Summary:
```
[2021-12-16T05:18:24.991Z] ----------------------------------------------------------------------
[2021-12-16T05:18:24.991Z] FAIL: infoschema_reader_test.go:957: testInfoschemaTableSuite.TestSequences
[2021-12-16T05:18:24.991Z] 
[2021-12-16T05:18:24.991Z] infoschema_reader_test.go:966:
[2021-12-16T05:18:24.991Z]     tk.MustQuery("SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME , TABLE_TYPE, ENGINE, TABLE_ROWS FROM information_schema.tables WHERE TABLE_TYPE='SEQUENCE' AND TABLE_NAME='seq2'").Check(testkit.Rows("def test seq2 SEQUENCE InnoDB 1"))
[2021-12-16T05:18:24.991Z] /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:67:
[2021-12-16T05:18:24.991Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
[2021-12-16T05:18:24.991Z] ... obtained string = "[def test seq2 SEQUENCE InnoDB 9]\n"
[2021-12-16T05:18:24.991Z] ... expected string = "[def test seq2 SEQUENCE InnoDB 1]\n"
[2021-12-16T05:18:24.991Z] ... sql:SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME , TABLE_TYPE, ENGINE, TABLE_ROWS FROM information_schema.tables WHERE TABLE_TYPE='SEQUENCE' AND TABLE_NAME='seq2', args:[]
[2021-12-16T05:18:24.991Z] 
```

### What is changed and how it works?
sequence count should always be the one row rather than according to the stats info.

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tangenta** [comment]
Should we disable the statistics on the sequence tables?

**Comment by AilinKid** [comment]
> Should we disable the statistics on the sequence tables?

any usage base? maybe we should

**Review by bb7133 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
LGTM

**Pull request merged**
