### PR TITLE
*: use tidb_index_lookup_join_currency to control the number of IndexLookupJoin inner workers

### PR DESCRIPTION
**Pull request by zz-jason**
before this PR, we use `tidb_index_lookup_currency` to control the currency of index lookup reader and index lookup join, after this PR:

| session variable | effect |
|-----------------|-------|
| tidb_index_lookup_currency | control the currency of index lookup reader |
| tidb_index_lookup_join_currency | control the currency of index lookup join |

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by winoros** [comment]
add test for it.

**Pull request merged**
