### PR TITLE
plan: cut unuseful search branch to improve performence.

### PR DESCRIPTION
**Pull request by hanfei1991**
If the prop is empty and selection is nil, we don't need to consider index scan.
If the prop is empty, we don't need to consider enforce sorter.
@shenli @coocood @zimulala @tiancaiamao @XuHuaiyu @winoros PTAL

### CODE REVIEW

**Comment by zimulala** [comment]
Fix CI @hanfei1991

**Comment by hanfei1991** [comment]
Before change:
BenchmarkBasic-4                      100000         15965 ns/op
BenchmarkTableScan-4                    2000        683003 ns/op
BenchmarkTableLookup-4                 20000         93759 ns/op
BenchmarkStringIndexScan-4              2000        700549 ns/op
BenchmarkStringIndexLookup-4           10000        105579 ns/op
BenchmarkIntegerIndexScan-4             2000        697651 ns/op
BenchmarkIntegerIndexLookup-4          10000        100078 ns/op
BenchmarkDecimalIndexScan-4             2000        752956 ns/op
BenchmarkDecimalIndexLookup-4          10000        108311 ns/op
After change:
BenchmarkBasic-4                      200000         16911 ns/op
BenchmarkTableScan-4                    2000        651861 ns/op
BenchmarkTableLookup-4                 20000         96550 ns/op
BenchmarkStringIndexScan-4              2000        695863 ns/op
BenchmarkStringIndexLookup-4           20000        102792 ns/op
BenchmarkIntegerIndexScan-4             2000        687823 ns/op
BenchmarkIntegerIndexLookup-4          10000        100590 ns/op
BenchmarkDecimalIndexScan-4             2000        763613 ns/op
BenchmarkDecimalIndexLookup-4          10000        104836 ns/op

**Comment by hanfei1991** [comment]
A more explicit bench result, before change:
BenchmarkExplainTableScan-4                30000         44607 ns/op
BenchmarkExplainTableLookup-4              20000         71500 ns/op
BenchmarkExplainStringIndexScan-4          20000         75814 ns/op
after change.
BenchmarkExplainTableScan-4                30000         41463 ns/op
BenchmarkExplainTableLookup-4              20000         70530 ns/op
BenchmarkExplainStringIndexScan-4          20000         74494 ns/op

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
