### PR TITLE
br: Remove statement from closure to prevent concurrent operation during backup system table

### PR DESCRIPTION
**Pull request by joccau**
Signed-off-by: joccau <zak.zhao@pingcap.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/29710

Problem Summary:
Append the prefix `__TiDB_BR_Temporary_` into system database `mysql` multiply.
It causes restore failed because of incorrect schema name

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Backup system table before fix
`
[2021/11/12 14:30:15.438 +08:00] [INFO] [validate.go:78] ["checksum success"] [db=__TiDB_BR_Temporary___TiDB_BR_Temporary___TiDB_BR_Temporary_mysql] [table=person]
`

Backup  and restore system table after fix 
`
[2021/11/12 15:54:00.890 +08:00] [INFO] [validate.go:78] ["checksum success"] [db=__TiDB_BR_Temporary_mysql] [table=person]
`

`
[2021/11/12 16:12:22.328 +08:00] [INFO] [ddl.go:553] ["[ddl] start DDL job"] [job="ID:168, Type:rename table, State:none, SchemaState:queueing, SchemaID:3, TableID:123, RowCount:0, ArgLen:3, start time: 2021-11-12 16:12:22.229 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"] [query="RENAME TABLE `__tidb_br_temporary_mysql`.`person` TO `mysql`.`person`;"]
`

### Release note

```release-note
None
```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]
LGTM, maybe also add a test (with race enabled, this would be easy to be caught)?

**Comment by joccau** [comment]
Need to cherry-pick 5.2.* in tidb Repo and 5.1.* in br repo

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
