### PR TITLE
metrics: add max query duration per resource group metrics

### PR DESCRIPTION
**Pull request by Connor1996**
### What problem does this PR solve?

Issue Number: Ref #43691 

Problem Summary:

### What is changed and how it works?

Add max query duration per resource group metrics
截屏2023-06-16 21 46 28

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by glorv — APPROVED** [review]

**Review by CabinfeverB — COMMENTED** [review]
Can u paste a grafana UI screenshot?

**Comment by Connor1996** [comment]
> Can u paste a grafana UI screenshot?

updated

**Review by nolouch — APPROVED** [review]

**Pull request merged**
