### PR TITLE
store/tikv:remove the usage of kv.TransactionOption

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: AndreMouche

### What problem does this PR solve?
This PR removes the usage of `kv.TransactionOption` from package `store/tikv` because we think it is hard for tikv-client users to understand `TransactionOption`. It reverts part of #23130 
Part of https://github.com/pingcap/tidb/issues/22513

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by sticnarf — COMMENTED** [review]
/lgtm

**Review by sticnarf — APPROVED** [review]

**Pull request merged**
