### PR TITLE
session, session_test: Improve read-only for autocommit statements

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/32895

Problem Summary:

Super Read Only and Restricted Read Only in TiDB use eventual consistency: there is a risk that after having enabled read-only, there are still some inflight operations which are still permitted to write to the database.

This PR reduces one of the main scenarios where inflight operations could continue to write after read-only is enabled: auto-commit transactions.

### What is changed and how it works?

The read-only flag was previously only checked while planning a query. It is now checked when planning _and_ committing a query. This applies for all types of commits: implicit and explicit (aka using the 'commit' statement).

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
The system variables tidb_super_read_only / tidb_restricted_read_only have been improved. Previously it was possible that a long running autocommit statement could make changes if it started before read-only was enabled. The read-only flag is now rechecked before committing the statement.
```

### CODE REVIEW

**Comment by morgo** [comment]
**Note:** The CLA bot is showing green, but I need to re-sign it. This contribution is coming from me at my new employer.

**Comment by jackysp** [comment]
> **Note:** The CLA bot is showing green, but I need to re-sign it. This contribution is coming from me at my new employer.

I assume that since this is a community and your committer status hasn't changed, I think you don't need to re-sign? PTAL @zhangyangyu

**Comment by zhangyangyu** [comment]
> > **Note:** The CLA bot is showing green, but I need to re-sign it. This contribution is coming from me at my new employer.
> 
> I assume that since this is a community and your committer status hasn't changed, I think you don't need to re-sign? PTAL @zhangyangyu

I think yes. The CLA bot checks if a GitHub account signs the CLA or not. So even if you change email address, just the addresses are bound to same GitHub account, you have to re-sign. If you change your GitHub account ID, you need to re-sign. Currently it has nothing to do with your employer.

**Review by xhebox — APPROVED** [review]
The semantics of restricted-read-only and super-read-only is ambiguous to me, but that is another problem.

LGTM

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
