### PR TITLE
*: cherry pick many bug fix since rc3 (#3713)

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry pick to rc3 @shenli @zimulala

### CODE REVIEW

**Comment by hanfei1991** [comment]
LGTM

**Comment by breeswish** [comment]
Missing?

https://github.com/pingcap/tidb/pull/3696/files#diff-91bbeda7eb98a7adc57b9e47e2cf5c2bR57

**Comment by tiancaiamao** [comment]
Yes, just this commit is cherry-pick to rc3. @breeswish

**Comment by breeswish** [comment]
@tiancaiamao got it. my diff was outdated due to browser cache.

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@tiancaiamao Please fix ci.

**Pull request merged**
