### PR TITLE
tests: make TestIndexLookupMergeJoinHang and TestIssue18068 stable

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Problem Summary:

Failpoints **MUST** be used in the serial test suties.

https://github.com/pingcap/tidb/pull/19765

### What is changed and how it works?

NA

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

NA

### Release note 

- No release note

### CODE REVIEW

**Review by lysu — COMMENTED** [review]
/lgtm

**Review by xhebox — APPROVED** [review]
/lgtm

**Pull request merged**
