### PR TITLE
*: fix index join on partition table data race

### LINKED ISSUE #33751: [FAIL]  executor TestPartitionTableIndexJoinAndIndexReader

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #33751 #33762 #32846

Problem Summary:

### What is changed and how it works?

IndexJoin executor builds the inner executor in different goroutine, and `PartitionPruning` is called during the executor building.
`PartitionPruning` is not thread-safe, so the code get DATA RACE.

I use `sync.Once` to do `PartitionPruning` only once and it also avoid the DATA RACE.

`pushDownNot` is not thread safe, it modifies the `conds` slice.
I move this part to from executor building phase to physical plan phase to avoid concurrent.

And `session.ParseSQL` is not thread-safe, in index join, hash partition pruning, several inner executor will be built at the same time. They would call `session.ParseSQL` in several different goroutines.
I revert a small optimization to make `session.ParseSQL` thread-safe.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)

Check no data race after this fix:

```
make ut X='run executor TestPartitionTableIndexJoinIndexLookUp --race'
make ut X='run executor TestDynamicPruningUnderIndexJoin --race'
```

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by mjonss — APPROVED** [review]
LGTM and thanks for the "to the point" description of the change!

I only have one small question/suggestion.

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
