### PR TITLE
executor: reset hasMatch flag for each outer row in merge join (#9046)

### PR DESCRIPTION
**Pull request by eurekaka**
cherry-pick #9046

### CODE REVIEW

**Comment by eurekaka** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by eurekaka** [comment]
/run-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1
/run-integration-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by winkyao** [comment]
/run-integration-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1 -tidb-test=pr/721

**Comment by winkyao** [comment]
@eurekaka I am fixing the broken ci.

**Comment by eurekaka** [comment]
/run-integration-common-test tidb-test=pr/721 tikv=release-2.1 pd=release-2.1

**Pull request merged**
