### PR TITLE
executor: improve SET sysvar=DEFAULT handling

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/29670

Problem Summary:

The usage of setting a sysvar to 'DEFAULT' contains 2 main compatibility issues:
- It accepts a 'string' as default, which means that the option 'default' is not possible.
- ~Setting a session scoped variable to default sets it to the global var value, not the compiled default.~ This fix was wrong, and has been reverted.

Fixing this helps with porting tests.

### What is changed and how it works?

Setting a system variable to `DEFAULT` has been improved to be more compatible with MySQL.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Setting a system variable to `DEFAULT` has been improved to be more compatible with MySQL.
```

### CODE REVIEW

**Review by dveeden — APPROVED** [review]

**Review by mjonss — APPROVED** [review]
LGTM

**Comment by morgo** [comment]
PTAL @bb7133

**Comment by bb7133** [comment]
> Setting a session scoped variable to default sets it to the global var value, not the compiled default.

I don't get the point here, according to [MySQL manual](https://dev.mysql.com/doc/refman/5.7/en/set-variable.html):

> To set a global system variable value to the compiled-in MySQL default value or a session system variable to the current corresponding global value, set the variable to the value DEFAULT. For example, the following two statements are identical in setting the session value of max_join_size to the current global value:

> SET @@SESSION.max_join_size = DEFAULT;
> SET @@SESSION.max_join_size = @@GLOBAL.max_join_size;

I tried the behavior of MySQL 5.7.28:

```
mysql> SELECT @@default_storage_engine;
+--------------------------+
| @@default_storage_engine |
+--------------------------+
| InnoDB                   |
+--------------------------+
1 row in set (0.00 sec)

mysql> SET GLOBAL default_storage_engine = 'Memory';
Query OK, 0 rows affected (0.00 sec)

mysql> SET default_storage_engine = 'MyISAM';
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT @@default_storage_engine;
+--------------------------+
| @@default_storage_engine |
+--------------------------+
| MyISAM                   |
+--------------------------+
1 row in set (0.01 sec)

mysql> SET default_storage_engine = DEFAULT;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT @@default_storage_engine;
+--------------------------+
| @@default_storage_engine |
+--------------------------+
| MEMORY                   |
+--------------------------+
1 row in set (0.00 sec)
```

So for MySQL, session scoped variable to default sets it to the global var value.

**Comment by morgo** [comment]
> I don't get the point here, according to [MySQL manual](https://dev.mysql.com/doc/refman/5.7/en/set-variable.html):
> 
> > To set a global system variable value to the compiled-in MySQL default value or a session system variable to the current corresponding global value, set the variable to the value DEFAULT. For example, the following two statements are identical in setting the session value of max_join_size to the current global value:
> 
> > SET @@SESSION.max_join_size = DEFAULT;
> > SET @@SESSION.max_join_size = @@GLOBAL.max_join_size;

@bb7133 See the comment in the issue here: https://github.com/pingcap/tidb/issues/29670#issuecomment-965698735

The original author of this code read the docs and made the same mistake :( They are only identical in outcome, and not in behavior. The wording in the docs is accurate but clumsy.

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
