### PR TITLE
sessionctx: add sysvar to control low resolution tso update interval

### PR DESCRIPTION
**Pull request by Tema**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/51081

Problem Summary:

### What changed and how does it work?

Introduce `tidb_low_resolution_tso_update_interval` global sysvar which is used to control how often to update transaction timestamp for the existing low resolution TSO feature: https://docs.pingcap.com/tidb/stable/system-variables#tidb_low_resolution_tso

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  > 1. set global tidb_low_resolution_tso_update_interval=10;
  > 1. Observe tso req/s metric increased
  > 
image
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
A new gloabl sysvar `tidb_low_resolution_tso_update_interval` can be  used to control how often to update transaction timestamp for low resolution TSO feature: https://docs.pingcap.com/tidb/stable/system-variables#tidb_low_resolution_tso
```

### CODE REVIEW

**Review by zyguan — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]

**Comment by crazycs520** [comment]
@Tema, I hope you don't mind, I just pushed a tiny change into this PR to refine code.

**Review by zimulala — APPROVED** [review]

**Pull request merged**
