### PR TITLE
expression: support push bit column down to TiKV

### PR DESCRIPTION
**Pull request by Yisaer**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/30738

Problem Summary:

### What is changed and how it works?

Support push bit column down to TiKV

### Check List

Tests 

- [x] Unit test
- [x] Integration test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Comment by Yisaer** [comment]
hold until https://github.com/tikv/tikv/pull/12016 merged

**Review by LittleFall — APPROVED** [review]

**Pull request merged**
