### PR TITLE
*: speed up `create table` when the number of tables is relatively large

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/49370

Problem Summary:
`ListTables` took a lot of time when the number of tables was relatively large

### What changed and how does it work?
Because the unmarshal of the `TableInfo` structure takes a large proportion of time, we only needn't all structures of the `TableInfo`. So we use `TableNameInfo` instead of it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Execute `checkTableNotExistsFromStore` function consumption of time.

| Total Table Count 	| Current DB Table Count 	| Master Branch Take Time 	| After this PR Table Time 	|
|-------------------	|------------------------	|-------------------------	|--------------------------	|
| 437k              	| 215k                   	| 23-26s                  	| 12-14s                   	|

Master branch info:
截屏2023-12-12 14 56 09

截屏2023-12-12 15 15 27

After this PR info(The middle area is particularly high because the owner of another service is transferred):
截屏2023-12-12 14 56 16

截屏2023-12-12 15 15 19

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]
12-14s is still not good enough IMO 🤔 Can you let the issue open? Maybe others can try different solutions for it.

**Comment by zimulala** [comment]
> 12-14s is still not good enough IMO 🤔 Can you leave the issue open? Maybe others can try different solutions for it.

This is a solution with relatively small changes and relatively large benefits. As for the other possible optimizations, they are more complex (the root cause may be JSON unmarshal problems) and may not have a good solution in the short term. Subsequent optimization may be more like https://github.com/pingcap/tidb/issues/19177.

**Review by tiancaiamao — APPROVED** [review]

**Review by Defined2014 — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Pull request merged**
