### PR TITLE
ddl/util: migrate test-infra with testify matchers

### LINKED ISSUE #27672: migrate test-infra to testify for `ddl/util` pkg

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

### What problem does this PR solve?

Issue Number: close #27672

### Release note

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by tisonkun** [comment]
@xhebox @zimulala 

test leaks unstably because we have code snippets below:

```go
// test.go

d.SchemaSyncer().NotifyCleanExpiredPaths()
// Make sure the clean worker is done.
notifiedCnt := 1
for i := 0; i < 100; i++ {
	isNotified := d.SchemaSyncer().NotifyCleanExpiredPaths()
	if isNotified {
		notifiedCnt++
	}
	// notifyCleanExpiredPathsCh's length is 1,
	// so when notifiedCnt is 3, we can make sure the clean worker is done at least once.
	if notifiedCnt == 3 {
		break
	}
	time.Sleep(20 * time.Millisecond)
}
require.Equal(t, 3, notifiedCnt)
```

```go
func (s *schemaVersionSyncer) StartCleanWork() {
	for {
		select {
		case <-s.notifyCleanExpiredPathsCh:
			if !s.ownerChecker.IsOwner() {
				continue
			}

			for i := 0; i < opDefaultRetryCnt; i++ {
				childCtx, cancelFunc := context.WithTimeout(s.ctx, opDefaultTimeout)
				resp, err := s.etcdCli.Leases(childCtx)
				cancelFunc()
				if err != nil {
					logutil.BgLogger().Info("[ddl] syncer clean expired paths, failed to get leases.", zap.Error(err))
					continue
				}

				if isFinished := s.doCleanExpirePaths(resp.Leases); isFinished {
					break
				}
				time.Sleep(opRetryInterval)
			}
		case <-s.ctx.Done():
			return
		}
	}
}
```

in [this report](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/35854/pipeline) we have the latter goroutine leaks

I don't know how can we determinate wait for retry exceeding or we just notify the retry to stop.

**Comment by zimulala** [comment]
> @xhebox @zimulala
> 
> test leaks unstably because we have code snippets below:
> 
> ```go
> // test.go
> 
> d.SchemaSyncer().NotifyCleanExpiredPaths()
> // Make sure the clean worker is done.
> notifiedCnt := 1
> for i := 0; i < 100; i++ {
> 	isNotified := d.SchemaSyncer().NotifyCleanExpiredPaths()
> 	if isNotified {
> 		notifiedCnt++
> 	}
> 	// notifyCleanExpiredPathsCh's length is 1,
> 	// so when notifiedCnt is 3, we can make sure the clean worker is done at least once.
> 	if notifiedCnt == 3 {
> 		break
> 	}
> 	time.Sleep(20 * time.Millisecond)
> }
> require.Equal(t, 3, notifiedCnt)
> ```
> 
> ```go
> // syncer.go
> 
> func (s *schemaVersionSyncer) StartCleanWork() {
> 	for {
> 		select {
> 		case <-s.notifyCleanExpiredPathsCh:
> 			if !s.ownerChecker.IsOwner() {
> 				continue
> 			}
> 
> 			for i := 0; i < opDefaultRetryCnt; i++ {
> 				childCtx, cancelFunc := context.WithTimeout(s.ctx, opDefaultTimeout)
> 				resp, err := s.etcdCli.Leases(childCtx)
> 				cancelFunc()
> 				if err != nil {
> 					logutil.BgLogger().Info("[ddl] syncer clean expired paths, failed to get leases.", zap.Error(err))
> 					continue
> 				}
> 
> 				if isFinished := s.doCleanExpirePaths(resp.Leases); isFinished {
> 					break
> 				}
> 				time.Sleep(opRetryInterval)
> 			}
> 		case <-s.ctx.Done():
> 			return
> 		}
> 	}
> }
> ```
> 
> in [this report](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/35854/pipeline) we have the latter goroutine leaks
> 
> I don't know how can we determinate wait for retry exceeding or we just notify the retry to stop.

May need to wait for some time after `d.Stop`. Probably when `ctx` calls cancel, `StartCleanWork` is also in the treatment of the `notifyCleanExpiredPathsCh` case.

**Comment by xhebox** [comment]
> ```go
> SchemaSyncer
> ```

A workaround is to add a wait-guard for `SchemaSyncer`, e.g. wait group.

**Comment by tisonkun** [comment]
> May need to wait for some time after `d.Stop`. Probably when `ctx` calls cancel, `StartCleanWork` is also in the treatment of the `notifyCleanExpiredPathsCh` case.

@zimulala I second your analyze but add a sleep seems possibly introduce unstable test as it is failed now.

**Comment by xhebox** [comment]
> @zimulala @xhebox I pushed a commit [fbc365a](https://github.com/pingcap/tidb/commit/fbc365a937d2f2ca99249e0ddf64082ad66d44ff) to introduce a wait group for determinate testing. But I'm unsure whether or not it is safe.

I think there is no problem.

One more thing, if you call `.Wait()` in `Close()`, then there is no need for new interfaces. Then it does not only affect the test, but also serve for smooth shutdown.

**Comment by tisonkun** [comment]
@xhebox I'm afraid whether it breaks other setups. Can you or how can I be confident that block in `Close` won't cause unintended bug?

I'll try to take a closer look and actually tend to your suggestion.

**Comment by xhebox** [comment]
> @xhebox I'm afraid whether it breaks other callers. Can you or how can I be confident that block in `Close` won't cause unintended bug?
> 
> I'll try to take a closer look and actually tend to your suggestion.

From my observation, the only change is that `ddl` will wait for the closing of `syncer`. A graceful shutdown is merely an improvement. I can not really come up with any case that may cause trouble.

**Comment by zimulala** [comment]
> > @xhebox I'm afraid whether it breaks other callers. Can you or how can I be confident that block in `Close` won't cause unintended bug?
> > I'll try to take a closer look and actually tend to your suggestion.
> 
> From my observation, the only change is that `ddl` will wait for the closing of `syncer`. A graceful shutdown is merely an improvement. I can not really come up with any case that may cause trouble.

This may cause TiDB to take longer to shut down, and so the time to roll the upgrade will be longer. But that's less likely.

**Comment by tisonkun** [comment]
@zimulala I notice that we already call `removeSelfVersionPath` that may retry for seconds. Pushed a commit aa376ce1e07d807a0beedf3de7c8200553f48b22 to remove public interface and wait in `Close`.

**Comment by tisonkun** [comment]
@zimulala @xhebox ready to review. Thanks for your suggestions!

**Comment by tisonkun** [comment]
/cc @zimulala @mmyj 

Waiting for another reviewer :P

**Review by zimulala — APPROVED** [review]
LGTM

**Pull request merged**
