### PR TITLE
executor: adjust message about Charset&&Collation in 'show create table` for compatibility

### PR DESCRIPTION
**Pull request by xiekeyi98**
### What problem does this PR solve? 

Cherry-pick from #9113

### CODE REVIEW

**Comment by xiekeyi98** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by xiekeyi98** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zimulala** [comment]
Please fix the CI.

**Comment by xiekeyi98** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by xiekeyi98** [comment]
/run-all-tests tidb-test=pr/736 tikv=release-2.1 pd=release-2.1

**Comment by xiekeyi98** [comment]
/run-common-tests tidb-test=pr/736 tikv=release-2.1 pd=release-2.1

**Comment by xiekeyi98** [comment]
/run-common-tests tidb-test=pr/736 tikv=release-2.1 pd=release-2.1

**Comment by xiekeyi98** [comment]
/run-all-tests tidb-test=pr/736 tikv=release-2.1 pd=release-2.1

**Pull request merged**
