### PR TITLE
br/pkg/kv: migrate test-infra to testify

### LINKED ISSUE #28169: migrate test-infra to testify for `br/pkg/kv`

### PR DESCRIPTION
**Pull request by shadw3002**
### What problem does this PR solve?

Issue Number: close #28169 

Problem Summary: migrate test-infra to testify for br/pkg/kv

### What is changed and how it works?

What's Changed: migrate test-infra to testify for br/pkg/kv

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by shadw3002** [comment]
/cc @tisonkun
PTAL

**Review by mmyj — APPROVED** [review]
lgtm

**Review by tisonkun — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
