### PR TITLE
parser: move LOAD DATA REMOTE into LOAD DATA

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/40499

Problem Summary:

### What is changed and how it works?

change some syntax of https://github.com/pingcap/tidb/pull/40489 , now we can use `LOAD DATA ...` to replace `LOAD DATA REMOTE ...`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by gozssky — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by wuhuizuo** [comment]
> /hold ci wrong status reported

it's a bug of Jenkins controller API.

/unhold state is correct now

**Pull request merged**
