### PR TITLE
*: remove remote cache uri

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### Check List

Tests 

- [x] Unit test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — COMMENTED** [review]
Move `test-output=...jenkins` into outer files, what about? So that we can finally `make bazel_test` or whatever locally.

BTW, I think it can refer #36764, and listed there for records.

**Review by xhebox — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
