### PR TITLE
admin: only check public index

### PR DESCRIPTION
**Pull request by crazycs520**
cherry-pick #8748

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8750)

### CODE REVIEW

**Comment by crazycs520** [comment]
/run-all-tests tikv=release-2.0 pd=release-2.0 tidb-test=release-2.0

**Comment by winkyao** [comment]
@crazycs520 please make your title more informational.

**Comment by crazycs520** [comment]
/run-unit-test -tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Pull request merged**
