### PR TITLE
readme: remove adopters (pingcap/docs#8725)

### PR DESCRIPTION
**Pull request by renbaoshuo**
### What problem does this PR solve?

Problem Summary:

see: https://github.com/pingcap/docs/pull/8725

Issue Number: ref #35180 

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by ran-huang — APPROVED** [review]
LGTM. Thanks!

**Comment by xhebox** [comment]
to #35180

**Review by xiongjiwei — APPROVED** [review]

**Pull request merged**
