### PR TITLE
gc_worker: enable green GC by default

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?
Problem Summary:
Green GC will be released in v4.0.3.

### What is changed and how it works?
What's Changed:
Enable green GC by default and make the config public.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`: coming soon.
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- Enable green GC by default.

### CODE REVIEW

**Comment by cfzjywxk** [comment]
> @youjiali1995 merge failed.

Seems unrelated fail...
```
[2020-06-22T11:36:07.446Z] ==================

[2020-06-22T11:36:07.446Z] WARNING: DATA RACE

[2020-06-22T11:36:07.446Z] Write at 0x00c02553ca68 by goroutine 100:

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*testIndexChangeSuite).TestIndexChange()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/index_change_test.go:135 +0x148b

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*testIndexChangeSuite).TestIndexChange()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/index_change_test.go:130 +0x114c

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*testIndexChangeSuite).TestIndexChange()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/index_change_test.go:69 +0x4bf

[2020-06-22T11:36:07.446Z]   runtime.call32()

[2020-06-22T11:36:07.446Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-06-22T11:36:07.446Z]   reflect.Value.Call()

[2020-06-22T11:36:07.446Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-06-22T11:36:07.446Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-06-22T11:36:07.446Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113

[2020-06-22T11:36:07.446Z] 

[2020-06-22T11:36:07.446Z] Previous read at 0x00c02553ca68 by goroutine 384:

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*testIndexChangeSuite).TestIndexChange.func1()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/index_change_test.go:95 +0x104

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*TestDDLCallback).OnJobUpdated()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/callback_test.go:72 +0x200

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*TestDDLCallback).OnJobUpdated()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/callback_test.go:66 +0x50

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:511 +0x250

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:434 +0x19b

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:511 +0x250

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/kv.RunInNewTxn()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/kv/txn.go:47 +0x110

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:434 +0x19b

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:511 +0x250

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/kv.RunInNewTxn()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/kv/txn.go:47 +0x110

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:434 +0x19b

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:511 +0x250

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/kv.RunInNewTxn()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/kv/txn.go:47 +0x110

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:434 +0x19b

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:511 +0x250

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/kv.RunInNewTxn()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/kv/txn.go:47 +0x110

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:434 +0x19b

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:511 +0x250

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/kv.RunInNewTxn()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/kv/txn.go:47 +0x110

[2020-06-22T11:36:07.446Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.446Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:434 +0x19b

[2020-06-22T11:36:07.447Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:511 +0x250

[2020-06-22T11:36:07.447Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue.func1()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:466 +0x50a

[2020-06-22T11:36:07.447Z]   github.com/pingcap/tidb/kv.RunInNewTxn()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/kv/txn.go:47 +0x110

[2020-06-22T11:36:07.447Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:434 +0x19b

[2020-06-22T11:36:07.447Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:511 +0x250

[2020-06-22T11:36:07.447Z]   github.com/pingcap/tidb/ddl.(*worker).start()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:155 +0x465

[2020-06-22T11:36:07.447Z] 

[2020-06-22T11:36:07.447Z] Goroutine 100 (running) created at:

[2020-06-22T11:36:07.447Z]   github.com/pingcap/check.(*suiteRunner).forkCall()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4a3

[2020-06-22T11:36:07.447Z]   github.com/pingcap/check.(*suiteRunner).forkTest()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x1b9

[2020-06-22T11:36:07.447Z]   github.com/pingcap/check.(*suiteRunner).doRun()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x13a

[2020-06-22T11:36:07.447Z]   github.com/pingcap/check.(*suiteRunner).asyncRun.func1()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:650 +0xf7

[2020-06-22T11:36:07.447Z] 

[2020-06-22T11:36:07.447Z] Goroutine 384 (running) created at:

[2020-06-22T11:36:07.447Z]   github.com/pingcap/tidb/ddl.(*ddl).Start()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl.go:338 +0xaf3

[2020-06-22T11:36:07.447Z]   github.com/pingcap/tidb/ddl.testNewDDLAndStart()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_test.go:112 +0x89

[2020-06-22T11:36:07.447Z]   github.com/pingcap/tidb/ddl.(*testIndexChangeSuite).TestIndexChange()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/index_change_test.go:55 +0x11d

[2020-06-22T11:36:07.447Z]   runtime.call32()

[2020-06-22T11:36:07.447Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-06-22T11:36:07.447Z]   reflect.Value.Call()

[2020-06-22T11:36:07.447Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-06-22T11:36:07.447Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-06-22T11:36:07.447Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-06-22T11:36:07.447Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113

[2020-06-22T11:36:07.447Z] ==================
```

**Comment by AndreMouche** [comment]
LGTM

**Pull request merged**
