### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by raywill**
### What problem does this PR solve?

Problem Summary:

I found several typos using a typo checker.

```
tidb-master/docs/design/2020-06-24-placement-rules-in-sql.md
 gauranteed (suggestion: guaranteed)
 ruels (suggestion: rules)
 gaurantee (suggestion: guarantee)
 repicas (suggestion: replicas)
 placment (suggestion: placement)
 furture (suggestion: future)
 atomacity (suggestion: atomicity)
```

### What is changed and how it works?

What's Changed: doc file changed

How it Works: fix typo

### Related changes

NA

### Check List 

Tests 

- No code

Side effects

 - No side effect

### Release note 

- No Release Note

### CODE REVIEW

**Comment by raywill** [comment]
@ti-srebot updated release note

**Review by xiongjiwei — APPROVED** [review]

**Review by ichn-hu — APPROVED** [review]

**Comment by guo-shaoge** [comment]
> seems that the Jenkins job is not so stable. No code changed, but check_dev_2 failed with 1 case.

Trying to fix in #25035 .

**Pull request merged**
