### PR TITLE
*: cherry-pick 27121

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Related to https://github.com/pingcap/parser/pull/1363.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Recognize 'references' privilege and ignore it.
```

### CODE REVIEW

**Comment by dveeden** [comment]
I assume this is no longer current now that pingcap/parser is merged into pingcap/tidb?

**Comment by tangenta** [comment]
@dveeden In release v5.2 the parser repo is not merged.

**Review by xhebox — APPROVED** [review]

**Comment by xhebox** [comment]
to #26703

**Comment by xhebox** [comment]
/hold

test is faling stably, need a second look

**Pull request merged**
