### PR TITLE
planner, sessionctx : Add 'last_plan_from_binding' to help know whether sql's plan is matched with the hints in the binding (#18017)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #18017 to release-4.0

---

### What problem does this PR solve?

Issue Number: close [#16425](https://github.com/pingcap/tidb/issues/16425)

Problem Summary:
Add `last_plan_from_binding` to help know whether sql's plan is matched with the hints in the binding

### What is changed and how it works?
What's Changed:
- add a session scope system variable `last_plan_from_binding` to help decide whether the plan cache got hit.
- display the `last_plan_from_binding` in slow log and statement summary table

### Related changes
- PR to update `pingcap/docs/pingcap/docs-cn`

- Unit test
- Integration test

### Release note 

- Add 'last_plan_from_binding' to help know whether sql's plan is matched with the hints in the binding

### CODE REVIEW

**Comment by Reminiscent** [comment]
@eurekaka @zz-jason PTAL. Thanks!

**Review by eurekaka — COMMENTED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]
LGTM

**Pull request merged**
