### PR TITLE
*: use the forked github.com/pingcap/gofail

### PR DESCRIPTION
**Pull request by tiancaiamao**
Use our forked gofail in release-2.0, not a cherry pick actually but we've do the same things on master

Tiny update Makefile
Remove Gopkg.toml

### CODE REVIEW

**Comment by tiancaiamao** [comment]
@zyguan What's happening?

**Comment by zhouqiang-cl** [comment]
your mean check_dev? check_dev has a little issue in release-2.0.  I am fixing it

**Pull request merged**
