### PR TITLE
types: migrate test-infra to testify for core_time_test.go

### LINKED ISSUE #27998: migrate test-infra to testify for `core_time_test.go`

### PR DESCRIPTION
**Pull request by unconsolable**
Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>

### What problem does this PR solve?

Issue Number: close #27998

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by unconsolable** [comment]
/cc @mmyj @xhebox 
PTAL

**Review by mmyj — APPROVED** [review]
lgtm

**Review by xhebox — APPROVED** [review]

**Pull request merged**
