### PR TITLE
ttl: use `SQL_NO_CACHE` to skip tikv block cache for TTL scan queries

### LINKED ISSUE #43206: NotFillCache should be true for Cop task from TTL scan workers
## Enhancement

It looks like TTL scale worker's full table scan COP KV requests contaminate RocksDB block cache. we need to add `NotFillCache: true` to avoid this situation.

img_v2_84257a28-a2df-4404-a7c6-f8a5382d54dg

img_v2_c6d6ab36-c059-48b8-8e72-bb6014532dcg

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #43206

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
ttl: use `SQL_NO_CACHE` to skip tikv block cache for TTL scan queries
```

### CODE REVIEW

**Comment by dbsid** [comment]
the pr works as expected

image

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
