### PR TITLE
ddl: support alter table TABLE_NAME engine=xxxx

### LINKED ISSUE #27188: tidb 5.0 continues to support engine modification
background:
On a synchronization link like `mysql -> dm -> tidb`, if you upgrade tidb to 5.0, the synchronization will be interrupted, and it will be painful to restore the synchronization. If there is no other special reason, we should continue to support `alter table xx engine = innodb`. Syntax, otherwise it is necessary to communicate with `tidb-tools` to do the upgrade compatibility work, this is very important

5.x：
mysql> alter table order engine=innodb;
ERROR 8200 (HY000): This type of ALTER TABLE is currently unsupported

4.0：
MySQL [test]> alter table order engine=innodb;
Query OK, 0 rows affected (0.00 sec)

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #27188

### What is changed and how it works?

What's Changed:

support alter table TABLE_NAME engine=xxxx

### Check List 

Tests 

- [x] Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by dveeden** [comment]
`ALTER TABLE t ENGINE=InnoDB` in MySQL is often used to rebuild tables that already use the InnoDB storage engine. This is mostly done as InnoDB datafiles never shrink and rebuilding builds a new datafile and copies the table. This allows one to release disk space back to the OS/FS.

A newer syntax for this is `ALTER TABLE t FORCE`.

Would rebuilding a table make sense for TiDB? Maybe when rotating encryption keys and/or when changing compression options? But that's probably then not per table but to force compaction in TiKV?

**Comment by xhebox** [comment]
> Would rebuilding a table make sense for TiDB? Maybe when rotating encryption keys and/or when changing compression options? But that's probably then not per table but to force compaction in TiKV?

I think that is basically correct.

**Review by xhebox — COMMENTED** [review]
Maybe only allow `innodb`, what if `alter ... engine=tiflash`?

**Comment by hawkingrei** [comment]
> Would rebuilding a table make sense for TiDB? Maybe when rotating encryption keys and/or when changing compression options? But that's probably then not per table but to force compaction in TiKV?

This pr solves the problem that runs ``` alter table  TABLE_NAME engine=innodb``` doesn't raise the error. it is important for
some tools to complete tasks.

**Comment by dveeden** [comment]
> Maybe only allow `innodb`, what if `alter ... engine=tiflash`?

This looks interesting, but then `SHOW CREATE TABLE...` should also list `TiFlash` as engine.

**Review by dveeden — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Review by djshow832 — COMMENTED** [review]
Can you add some test cases?
BTW, does it need `tidb_enable_noop_functions=true`?

**Review by bb7133 — APPROVED** [review]

**Comment by bb7133** [comment]
> Can you add some test cases?
> BTW, does it need `tidb_enable_noop_functions=true`?

Had a talk with @morgo , we do not need to consider `tidb_enable_noop_functions` for this case.

**Comment by bb7133** [comment]
run-check_dev_2

**Comment by skyzh** [comment]
It seems that TiDB integration test “tikv_ghpr_integration_common_test” will always fail after this PR is merged. Would you please take a look? @hawkingrei

**Comment by tisonkun** [comment]
ping @hawkingrei

**Pull request merged**
