### PR TITLE
executor: forbid read from stale query result

### LINKED ISSUE #25876: Stale read are ignored in view
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Prepare:
```
create table txx (id int);
insert into txx values(1);
create view vxx as select * from txx as of timestamp '1900-00-00 00:00:00';
```

Run select:

```
select * from vxx;
```

### 2. What did you expect to see? (Required)

```
ERROR 1356 (HY000): View 'test.vxx' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
```
OR

Create view should not success for `select ... as of ...`

### 3. What did you see instead (Required)

```
+------+
| id   |
+------+
|    1 |
+------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Refer #25876 

Problem Summary: Because the design of planner, `select` SQL in the view is not preprocess/checked while creating. I mean all the `handleTableName` are ignored due to `inCreateOrDropTable` mask.

Stale reads, however, relies on `handleTableName` to get the needed information. And I did not come up with a solution to only preprocess/check-staleness for the table name in the `select` part but view name.

The result is that, I can not tell if it is a stale query while executing DDL `create view`, nor can we tell while executing/optimizing. Not from the preprocess result of the whole SQL. It can be extracted from the `as ...` part, though.

The check is added in the creation process(DDL) to reduce performance impact. It is added in executor, however, due to cyclic imports between planner and ddl.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- Forbid creating view from stale query

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Review by Yisaer — APPROVED** [review]

**Comment by xhebox** [comment]
@Yisaer Please merge.

**Comment by ichn-hu** [comment]
@xhebox would you add close #25876 in the PR description?

**Comment by xhebox** [comment]
@ichn-hu The fix is a non-elegant workaround due to limitations of TiDB code base. It is not closed because we wanted to do some improvements later. But it is hard. What do you prefer? Open a new issue that may exist for a long time, or just change the name of the old issue.

**Comment by ichn-hu** [comment]
> @ichn-hu The fix is a non-elegant workaround due to limitations of TiDB code base. It is not closed because we wanted to do some improvements later. But it is hard. What do you prefer? Open a new issue that may exist for a long time, or just change the name of the old issue.

I am okay with either way, but if we change the name of the old issue, please make it a feature request and remove the type/bug label. Our team is currently in bug jail, so we need to do so, sorry for bringing convenience.

**Pull request merged**
