### PR TITLE
planner: support specify table partition in optimize hint (#17638)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #17638 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/17113

Problem Summary: support specify table parition in optimize hint

### What is changed and how it works?

What's Changed: support specify table parition in optimize hint

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`: after this PR merge, we should update the docs.
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- support specify table partition in optimize hint

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Please resolve conflict. @lzmhhh123

**Review by zz-jason — COMMENTED** [review]
@lzmhhh123 please resolve conflicts and fix Ci.

**Comment by lzmhhh123** [comment]
@zz-jason @tiancaiamao PTAL.

**Review by zz-jason — COMMENTED** [review]
@lzmhhh123 please resolve conflicts.

**Comment by AilinKid** [comment]
Is it a 4.0.6 release block?

**Review by zz-jason — APPROVED** [review]
LGTM

**Review by SunRunAway — APPROVED** [review]
LGTM

**Review by SunRunAway — APPROVED** [review]

**Pull request merged**
