### PR TITLE
*: run CI test on release 2.0

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Comment by jackysp** [comment]
/run-all-tests tidb-test=release-2.0 tidb-private-test=release-2.0 tikv=release-2.0

**Comment by jackysp** [comment]
/run-common-test tidb-test=release-2.0 tidb-private-test=release-2.0 tikv=release-2.0
/run-integration-common-test tidb-test=release-2.0 tidb-private-test=release-2.0 tikv=release-2.0

**Comment by jackysp** [comment]
/run-unit-test tidb-test=release-2.0 tidb-private-test=release-2.0 tikv=release-2.0

**Comment by zhouqiang-cl** [comment]
/run-unit-test tidb-test=release-2.0 tidb-private-test=release-2.0 tikv=release-2.0

**Comment by zhouqiang-cl** [comment]
/run-unit-tests tidb-test=release-2.0 tidb-private-test=release-2.0 tikv=release-2.0

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.0 tidb-private-test=release-2.0 tikv=release-2.0

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.0 tidb-private-test=release-2.0 tikv=release-2.0

**Pull request closed without merging**
