### PR TITLE
makefile: let `make fmt` ensure std imports before non-std

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Problem Summary:

we recieve many CR advises about "resort your import" every day 
(and we also give many CR advises about it to others every day :dog:  )

### What is changed and how it works?

add import check to `make fmt` to ensure std import/ non-std import group together and std one before non-std one.

What's Changed:

check import

How it Works:

check import...maybe we can rewrite it automic...but for this version we just check and report error

### Related changes

- n/a

### Check List 

Tests 

- Manual test: and ohter files are found by this new check.

Side effects

- n/a

### Release note 

n/a

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/16816)

### CODE REVIEW

**Comment by SunRunAway** [comment]
How long does `make fmt` take after this PR?

**Comment by lysu** [comment]
> How long does `make fmt` take after this PR?

before

```
> time make fmt
gofmt (simplify)
make fmt  5.55s user 0.31s system 126% cpu 4.648 total
```

after

```
time make fmt
gofmt (simplify)
make fmt  5.85s user 0.41s system 131% cpu 4.759 total
```

**Pull request merged**
