### PR TITLE
*: fix `go mod tidy` in Go1.13 (12055)

### PR DESCRIPTION
**Pull request by tiancaiamao**
I find `go mod tidy` fail on release-3.0 if I use Go 1.13:

```
➜  tidb git:(cherry-clean-up) go mod tidy
go: downloading gopkg.in/stretchr/testify.v1 v1.4.0
github.com/pingcap/tidb/ddl imports
	github.com/twinj/uuid tested by
	github.com/twinj/uuid.test imports
	gopkg.in/stretchr/testify.v1/assert: cannot find module providing package gopkg.in/stretchr/testify.v1/assert
```

Our CI environment has upgraded the Go compiler to Go 1.13 @leoppro

### CODE REVIEW

**Comment by lysu** [comment]
@tiancaiamao we need to add release note and let dba notice incompatible problem.

and next 3.0 need upgrade pump first, then upgrade TiDB.

see binlog issue:
https://github.com/pingcap/tidb-binlog/issues/753
https://github.com/pingcap/tidb-binlog/pull/756

and grpc incompatible PR:
https://github.com/grpc/grpc-go/issues/2406

the question is: pump using cmux to proxy grpc and http, but new grpc's handshake need change the usage of cmux, so pump need upgrade to new code.

**Comment by lysu** [comment]
@tiancaiamao  maybe we can only change `github.com/twinj/uuid` and don't upgrade grpc?

**Comment by tiancaiamao** [comment]
Well, If I can solve the failed CI in https://github.com/pingcap/tidb/pull/12417, I don't need this PR.

**Comment by tiancaiamao** [comment]
I've reset the grpc changes

**Pull request merged**
