### PR TITLE
expression: fix inaccurate error info for year column out of range (#18871)

### LINKED ISSUE #18792: Inaccurate error info for year column out of range
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql root@127.0.0.1:test> create table t (a year)
mysql root@127.0.0.1:test> insert into t values(2156)
```

### 2. What did you expect to see? (Required)
On MySQL:
```sql
mysql root@127.0.0.1:test> insert into t values(2156)
(1264, "Out of range value for column 'a' at row 1")
```

### 3. What did you see instead (Required)
On TiDB:
```sql
mysql root@127.0.0.1:test> insert into t values(2156)
(1105, 'cannot convert datum from bigint to type year.')
```

### 4. Affected version (Required)

```
Release Version: v4.0.0-beta.2-835-g1fed1fb89
Edition: Community
Git Commit Hash: 1fed1fb895e133f5a5e6818ac24087b7c3a0d4f8
Git Branch: master
UTC Build Time: 2020-07-27 02:56:55
GoVersion: go1.14.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #18871 to release-3.0

---

### What problem does this PR solve?

Issue Number: close #18792

Problem Summary:
Inaccurate error info for year column out of range.

### What is changed and how it works?

What's Changed:
Modified return error type as overflow.

### Check List

Tests

- Manual test
```
tidb> create table t (a year)
tidb> insert into t values(2156)
ERROR 1264 (22003): Out of range value for column 'a' at row 1
```
- Unit test

### Release note
- Fix inaccurate error info for year column out of range.

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
LGTM

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Comment by bb7133** [comment]
The following case should be updated:

```
[2020-11-11T07:02:23.428Z] ----------------------------------------------------------------------
[2020-11-11T07:02:23.428Z] FAIL: db_test.go:2960: testDBSuite5.TestAddIndexForGeneratedColumn
[2020-11-11T07:02:23.428Z] 
[2020-11-11T07:02:23.428Z] db_test.go:2971:
[2020-11-11T07:02:23.428Z]     c.Assert(err.Error(), Equals, "[ddl:15]cannot decode index value, because cannot convert datum from unsigned bigint to type year.")
[2020-11-11T07:02:23.428Z] ... obtained string = "[ddl:15]cannot decode index value, because [types:1690]DECIMAL value is out of range in '(4, 0)'"
[2020-11-11T07:02:23.428Z] ... expected string = "[ddl:15]cannot decode index value, because cannot convert datum from unsigned bigint to type year."
[2020-11-11T07:02:23.428Z] 
```

**Comment by SunRunAway** [comment]
@xiaodong-ji Could you help take a look?

**Comment by xiaodong-ji** [comment]
> @xiaodong-ji Could you help take a look?

may need to execute the make errdoc command to update the errors.toml file.

**Comment by xiaodong-ji** [comment]
How to update the PR created by this ti-srebot.

**Review by SunRunAway — APPROVED** [review]

**Pull request closed without merging**
