### PR TITLE
expression: fix invalid `Flen` of decimal value when using plan cache

### LINKED ISSUE #28064: Decimal compare string parameter can't be pushed down when using plan cache
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
enable plan cache
```sql
CREATE TABLE `t` (
  `a` decimal(10,0) DEFAULT NULL,
  `b` decimal(10,0) DEFAULT NULL,
  `c` decimal(10,0) DEFAULT NULL,
  `d` decimal(10,0) DEFAULT NULL,
  KEY `iabc` (`a`,`b`,`c`)
);
set @a='123', @b='234', @c='345';
prepare stmt1 from 'select * from t use index (iabc) where a = ? and b = ? and c = ?';
execute stmt1 using @a, @b, @c;
```

### 2. What did you expect to see? (Required)
```
+-------------------------------+---------+-----------+------------------------------+-----------------------------------------------------------------+
| id                            | estRows | task      | access object                | operator info                                                   |
+-------------------------------+---------+-----------+------------------------------+-----------------------------------------------------------------+
| IndexLookUp_7                 | 0.00    | root      |                              |                                                                 |
| ├─IndexRangeScan_5(Build)     | 0.00    | cop[tikv] | table:t, index:iabc(a, b, c) | range:[123 234 345,123 234 345], keep order:false, stats:pseudo |
| └─TableRowIDScan_6(Probe)     | 0.00    | cop[tikv] | table:t                      | keep order:false, stats:pseudo                                  |
+-------------------------------+---------+-----------+------------------------------+-----------------------------------------------------------------+
```

### 3. What did you see instead (Required)
```
+---------------------------------+----------+---------+-----------+------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+--------+------+
| id                              | estRows  | actRows | task      | access object                | execution info                                                                                                                                                  | operator info                                           | memory | disk |
+---------------------------------+----------+---------+-----------+------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+--------+------+
| Selection_5                     | 8000.00  | 0       | root      |                              | time:1.37ms, loops:1                                                                                                                                            | eq(test.t.a, 123), eq(test.t.b, 234), eq(test.t.c, 345) | N/A    | N/A  |
| └─IndexLookUp_8                 | 10000.00 | 0       | root      |                              | time:1.36ms, loops:1,  table_task: {total_time: 5.03ms, num: 0, concurrency: 5}                                                                                 |                                                         | N/A    | N/A  |
|   ├─IndexFullScan_6(Build)      | 10000.00 | 0       | cop[tikv] | table:t, index:iabc(a, b, c) | time:682.4µs, loops:1, cop_task: {num: 1, max: 397µs, proc_keys: 0, rpc_num: 1, rpc_time: 333.6µs, copr_cache_hit_ratio: 0.00}, tikv_task:{time:0s, loops:0}    | keep order:false, stats:pseudo                          | N/A    | N/A  |
|   └─TableRowIDScan_7(Probe)     | 10000.00 | 0       | cop[tikv] | table:t                      |                                                                                                                                                                 | keep order:false, stats:pseudo                          | N/A    | N/A  |
+---------------------------------+----------+---------+-----------+------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+--------+------+
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #28064

Problem Summary: please see the issue for details.

### What is changed and how it works?

Add a check for `Flen` in `WrapWithCastAsDecimal()`. When they are -1, change them to decimal type default value.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by time-and-fate** [comment]
Seems the failed common-test is irrelevant to this PR. The same error message is also on the current master branch.

**Review by wjhuang2016 — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
