### PR TITLE
expression: fix precision loss when casting time to string

### LINKED ISSUE #34659: Precision loss when casting time to string
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
select cast(date_add(cast('00:00:00' as time), interval 1.1 second) as char);
```

### 2. What did you expect to see? (Required)

MySQL 8.0:
```
+-----------------------------------------------------------------------+
| cast(date_add(cast('00:00:00' as time), interval 1.1 second) as char) |
+-----------------------------------------------------------------------+
| 00:00:01.1                                                            |
+-----------------------------------------------------------------------+
```

### 3. What did you see instead (Required)

TiDB:
```
+-----------------------------------------------------------------------+
| cast(date_add(cast('00:00:00' as time), interval 1.1 second) as char) |
+-----------------------------------------------------------------------+
| 00:00:01                                                              |
+-----------------------------------------------------------------------+
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                     |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.0.0
Edition: Community
Git Commit Hash: 36a9810441ca0e496cbd22064af274b3be771081
Git Branch: heads/refs/tags/v6.0.0
UTC Build Time: 2022-03-31 10:33:28
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by zanmato1984**
### What problem does this PR solve?

Issue Number: close #34659

Problem Summary:

Precision (fsp) for duration was lost during parsing interval with second unit, resulting in subsequent precision loss for `date_add` result.

### What is changed and how it works?

Refine the interval parsing logic to properly set fsp.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by ngaut — APPROVED** [review]

**Comment by hawkingrei** [comment]
@zanmato1984 Please fix it.

```
[2022-05-14T19:03:44.399Z] types/time_test.go:1651:34: cannot initialize 5 variables with 6 values (typecheck)

[2022-05-14T19:03:44.399Z] 		res1, res2, res3, res4, err := types.ParseDurationValue(col.unit, col.format)

```

**Pull request merged**
