### PR TITLE
tidb-server: handle the help manually (#24073)

### LINKED ISSUE #24046: tidb-server --help exit with code 2
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sh
tidb-server --help
echo $?
```

### 2. What did you expect to see? (Required)

`0`

### 3. What did you see instead (Required)

`2`

### 4. What is your TiDB version? (Required)

`v5.0.0`

```
Release Version: v5.0.0
Edition: Community
Git Commit Hash: bdac0885cd11bdf571aad9353bfc24e13554b91c
Git Branch: heads/refs/tags/v5.0.0
UTC Build Time: 2021-04-06 16:39:10
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #24073 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/24074
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/24074:release-5.0-cd25915b51f8
```

---

### What problem does this PR solve?

Issue Number: close #24046 

Problem Summary:  Check [flag: exit 0 when -h or -help invoked but undefined](https://github.com/golang/go/commit/dcf0929de6a12103a8fd7097abd6e797188c366d). The newer go does not have this problem. But we can still solve it by manually triggering the usage.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- Set the return value to 0 if --help is passed to cli, for golang below version 1.15

### CODE REVIEW

**Review by AilinKid — COMMENTED** [review]
/LGTM

**Review by xiongjiwei — APPROVED** [review]
/lgtm

**Pull request merged**
