### PR TITLE
privilege: make 'grant all privileges' work right

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

```
mysql> create user superadmin;
Query OK, 1 row affected (0.02 sec)

mysql> grant all privileges on *.* to superadmin;
Query OK, 0 rows affected (0.01 sec)

mysql> select * from mysql.user where user='superadmin'\G;
*************************** 1. row ***************************
                 Host: %
                 User: superadmin
             Password: 
          Select_priv: Y
          Insert_priv: Y
          Update_priv: Y
          Delete_priv: Y
          Create_priv: Y
            Drop_priv: Y
         Process_priv: Y
           Grant_priv: Y
      References_priv: Y
           Alter_priv: Y
         Show_db_priv: Y
           Super_priv: Y
Create_tmp_table_priv: N
     Lock_tables_priv: N
         Execute_priv: Y
     Create_view_priv: Y
       Show_view_priv: Y
  Create_routine_priv: N
   Alter_routine_priv: N
           Index_priv: Y
     Create_user_priv: Y
           Event_priv: N
         Trigger_priv: Y
     Create_role_priv: Y
       Drop_role_priv: Y
       Account_locked: NULL
1 row in set (0.00 sec)
```

As you may see above, `grant all privileges` doesn't really grant **all** privileges to the user, 
the value of columns like `Create_tmp_table_priv` `Lock_tables_priv` `Create_routine_priv` `Alter_routine_priv` `Event_priv` are `N` 

### What is changed and how it works?

When we say **all** privileges, the parser doesn't take those `Create_tmp_table_priv` alike into account.
That's weird.

```
mysql> show grants for 'superadmin';                                                                                                                                                                  +-------------------------------------------------+
| Grants for superadmin@%                         |
+-------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO 'superadmin'@'%' |
+-------------------------------------------------+
1 row in set (0.00 sec)
```

The root cause of this bug is that the **all privileges** definition and the `mysql.user` privileges column inconsistency.
The fix is done in the parser repo, this commit updates the parser (go.mod) and add a test.

### Check List 

Tests 

 - Unit test

Side effects

 - Breaking backward compatibility

Related changes

Don't cherry-pick this to release-3.0, as it can't fix the wrong data, and has potential compatibility issues.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
The CI is failing because of the `go mod tidy` check. The parser should be merged first.
PTAL @imtbkcat @lysu @jackysp

**Comment by jackysp** [comment]
https://github.com/pingcap/parser/pull/400 is merged.

**Comment by imtbkcat** [comment]
@tiancaiamao Please update go mod.

**Pull request merged**
