### PR TITLE
ddl: remove the unnecessary test

### LINKED ISSUE #36826: unstable test TestReorgOwne
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
         	Error Trace:	/home/jenkins/.tidb/tmp/04446c229c5a73c16deb3edddcb4db34/sandbox/processwrapper-sandbox/4754/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/schema_test.go:48
        	            				/home/jenkins/.tidb/tmp/04446c229c5a73c16deb3edddcb4db34/sandbox/processwrapper-sandbox/4754/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/reorg_test.go:68
        	Error:      	Received unexpected error:
        	            	[schema:1050]Table 't' already exists
        	            	github.com/pingcap/errors.AddStack
        	            		external/com_github_pingcap_errors/errors.go:174
        	            	github.com/pingcap/errors.Trace
        	            		external/com_github_pingcap_errors/juju_adaptor.go:15
        	            	github.com/pingcap/tidb/ddl.(*ddl).DoDDLJob
        	            		ddl/ddl.go:1055
        	            	github.com/pingcap/tidb/ddl_test.testCreateTable
        	            		ddl/schema_test.go:47
        	            	github.com/pingcap/tidb/ddl_test.TestReorgOwner
        	            		ddl/reorg_test.go:68
        	            	testing.tRunner
        	            		GOROOT/src/testing/testing.go:1439
        	            	runtime.goexit
        	            		GOROOT/src/runtime/asm_amd64.s:1571
        	Test:       	TestReorgOwner 
```

https://prow.pingcap.net/view/gs/pingcapprow/logs/bazel_test_tidb/1554315795041882112

```
         	Error Trace:	/home/jenkins/.tidb/tmp/04446c229c5a73c16deb3edddcb4db34/sandbox/processwrapper-sandbox/4639/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/column_change_test.go:400
        	            				/home/jenkins/.tidb/tmp/04446c229c5a73c16deb3edddcb4db34/sandbox/processwrapper-sandbox/4639/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/schema_test.go:52
        	            				/home/jenkins/.tidb/tmp/04446c229c5a73c16deb3edddcb4db34/sandbox/processwrapper-sandbox/4639/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/reorg_test.go:68
        	Error:      	Not equal: 
        	            	expected: 35
        	            	actual  : 36
        	Test:       	TestReorgOwner 
```

https://prow.pingcap.net/view/gs/pingcapprow/logs/bazel_test_tidb/1554466791571329024

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #36826

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by tiancaiamao** [comment]
Also remove it this from the `BUILD.bazel` files list? @wjhuang2016

**Pull request merged**
