### PR TITLE
session: refine StmtHistory code

### PR DESCRIPTION
**Pull request by zhexuany**
Thank you for working on TiDB! Please read TiDB's [CONTRIBUTING](https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md) document **BEFORE** filing this PR.

### Please explain **IN DETAIL** what the changes are in this PR and why they are needed:
I refine `StmtHistory` via `type alias`.

### The currently defined types are listed below, please pick one of the types for this PR by removing the others:

- Improvement (non-breaking change which is an improvement to an existing feature)

### Please describe the tests that you ran to verify your changes. Have you finished unit tests, integration tests, or manual tests?

Changes only refine code not bringing any new functionality; hence test is needless.

### CODE REVIEW

**Comment by shenli** [comment]
@zhexuany Please make the format of the description right.

**Comment by shenli** [comment]
@coocood @tiancaiamao PTAL

**Comment by coocood** [comment]
@zhexuany 
I think it doesn't make much difference and I prefer the original code.

**Comment by coocood** [comment]
The original code is more extensible, we may need to add other properties to the history later.

**Comment by tiancaiamao** [comment]
Agree with @coocood

**Comment by shenli** [comment]
So should we close this PR?

**Comment by zhexuany** [comment]
@coocood I feel like at least need give me an opportunity to argue it rather than simply closing it. 

As you pointed, my proposal may hurt extensibly, but have you ever check the history of the code? By git blame, `StmtHistory` was created 33 months ago. If it ever need to be extended, it should already has been done.

**Comment by coocood** [comment]
@zhexuany 
I still think struct type is better than slice type even without the extensibility, it has less `*` in the code.

**Comment by zhexuany** [comment]
I just took the advantage of type alias. It has more `*` but less `sh.history`. From a point view of saving time and more neat code, I prefer type alias code.

**Pull request closed without merging**
