### PR TITLE
statistics: fix panic when `getStatsReader` fail

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

The `defer` func is not placed correctly. Thus it would panic in some cases.

### What is changed and how it works?

Check the error before the defer func. Avoid potential panic.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by zz-jason** [comment]
How did you find this bug?

**Comment by winoros** [comment]
@zz-jason It's reported by @mahjonp .

**Pull request merged**
