### PR TITLE
*: use Go1.11 module for dependency management

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

In the release-2.0 branch.
The code in vendor and the version in Gopkg.lock is inconsistent.
Somebody probably update vendor without using `dep`, now the vendor is broken.
Migrate to Go module.

### What is changed and how it works?

- The parser is not touched.
- Go is update to 1.11.3
- Some package changes

tipb/kvproto use the same version as tikv https://github.com/tikv/tikv/blob/d3bd2c721e5ae53fc808c7d37fdb04d6e2a470fc/Cargo.lock#L1350
grpc is the same with pd, v1.7.5
etcd is update to 3.2.18, the same with pd https://github.com/pingcap/pd/blob/860ef894f1cae254dead276ab9d6078455b10bf1/Gopkg.lock#L106
pd-client use pd v2.0.10
Others are untouched as the Gopkg.lock specified.

### Check List 

Tests 

 - No code

Side effects

Potential bugs maybe introduced when updating some of the third-part packages
I've check those important ones, so it should be compatible with TiKV&PD

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8821)

### CODE REVIEW

**Comment by tiancaiamao** [comment]
/run-all-tests tidb-test=release-2.0 pd=release-2.0 tikv=release-2.0

**Comment by tiancaiamao** [comment]
/run-all-tests tidb-test=release-2.0 pd=release-2.0 tikv=release-2.0

**Comment by zyguan** [comment]
/run-all-tests tidb-test=pr/710 pd=release-2.0 tikv=release-2.0

**Comment by zyguan** [comment]
/run-all-tests tidb-test=pr/710 pd=release-2.0 tikv=release-2.0

**Comment by zyguan** [comment]
/run-all-tests tidb-test=pr/710 pd=release-2.0 tikv=release-2.0 gofail=etcd-io

**Comment by tiancaiamao** [comment]
Awesome! @zyguan

**Comment by tiancaiamao** [comment]
PTAL @jackysp @shenli

**Comment by jackysp** [comment]
/run-all-tests tidb-test=pr/710 pd=release-2.0 tikv=release-2.0 gofail=etcd-io

**Comment by jackysp** [comment]
PTAL @winkyao

**Pull request merged**
