### PR TITLE
executor: make admin check table error more readable.

### PR DESCRIPTION
**Pull request by winkyao**
Before:

```
ERROR 1105 (HY000): test err:[admin:1]index:&{60001 [{9 0 6 0 43835000000000 [] <nil>}]} != record:&{60001 [{9 0 0 0 43835000000000 [] <nil>}]}
```

After:

```
ERROR 1105 (HY000): test err:[admin:1]index:&admin.RecordData{Handle:60001, Values:[]types.Datum{types.Datum{k:0x9, collation:0x0, decimal:0x6, length:0x0, i:43835000000000, b:[]uint8(nil), x:interface {}(nil)}}} != record:&admin.RecordData{Handle:60001, Values:[]types.Datum{types.Datum{k:0x9, collation:0x0, decimal:0x0, length:0x0, i:43835000000000, b:[]uint8(nil), x:interface {}(nil)}}}
```
Make debugging easier. @zimulala @coocood  PTAL

### CODE REVIEW

**Comment by shenli** [comment]
@winkyao Please fix the CI.

**Comment by winkyao** [comment]
@winoros The data structure is RecordData, not just Datumn.

**Comment by winoros** [comment]
i mean, why not implement `String` method for `recordData`

**Comment by winkyao** [comment]
Below is output of types.DatumsToString, it is not enough message to trace the bug. @winoros 
```
ERROR 1105 (HY000): test err:[admin:1]index:RecordData{Handle: 1, Values:12:10:35.000000} != record:RecordData{Handle: 1, Values:12:10:35}
```

**Comment by zz-jason** [comment]
When you see a log in log file: `types.Datum{k:0x9, collation:0x0, decimal:0x6, length:0x0, i:43835000000000, b:[]uint8(nil), x:interface {}(nil)}`, without looking into the code, how do you know:
1. what type is the datum?
2. what does `i:43835000000000` means?
3 ...

I think this PR has nothing to do with `readable`

**Comment by winkyao** [comment]
@zz-jason This command is used for debugging, so our goal is a readable error info. And once the error returns, we must look into the code, because this is a definite bug.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
