### PR TITLE
util/topsql: fix goroutine leak in test

### LINKED ISSUE #31960: Resolve goroutine leak for util/topsql

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?

Issue Number: close #31960

Problem Summary: Close mock server to resolve goroutine leak

### Check List

Tests
- [x] Unit test

### Release note
```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM. Thanks!

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
