### PR TITLE
planner/implementation: migrate test-infra to testify

### LINKED ISSUE #26858: migrate test-infra to testify for `planner/implementation`
You may try to analyze first and spawn more subtasks instead of one big PR handle the whole package which is hard to review.

### PR DESCRIPTION
**Pull request by yedamao**
### What problem does this PR solve?

Issue Number: close #26858  

### Release note 

```release-note
None.
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
Thanks for your contribution!

/cc @xhebox @rebelice 

PTAL

**Review by xhebox — APPROVED** [review]
Not a planner reviewer though.

**Comment by tisonkun** [comment]
> Not a planner reviewer though.

I notify you since there is no sig/planner label, weird but we can move forward （x)

**Review by rebelice — APPROVED** [review]

**Pull request merged**
