### PR TITLE
planner: ban (index) merge join heuristically when convert eq cond to other cond (#21138)

### LINKED ISSUE #20710: Optimizer does not consider the cost of other condition in Index Join
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql> create table t(a int, b int, index (a));
Query OK, 0 rows affected (0.01 sec)
```

SQL is 
```sql
select * from t t1 inner join t t2 on t1.a = t2.a and t1.b = t2.b;
```
If Index Join is used, currently **_t1.a = t2.a_** is put in the equality condition, and **_t1.b = t2.b_** is put in other conditions. If the selectivity of **_t1.a = t2.a_** is high, there will be quite a lot of rows that need to be filtered with **_t1.b = t2.b_**. This part of the cost will be very large.
```sql
mysql> explain select /*+ INL_HASH_JOIN(t1) */ * from t t1 inner join t t2 on t1.a = t2.a and t1.b = t2.b;
+-------------------------------+----------+-----------+----------------------+-------------------------------------------------------------------------------------------------------------+
| id                            | estRows  | task      | access object        | operator info                                                                                               |
+-------------------------------+----------+-----------+----------------------+-------------------------------------------------------------------------------------------------------------+
| IndexHashJoin_30              | 12475.01 | root      |                      | inner join, inner:IndexLookUp_27, outer key:test.t.a, inner key:test.t.a, other cond:eq(test.t.b, test.t.b) |
| ├─TableReader_41(Build)       | 9980.01  | root      |                      | data:Selection_40                                                                                           |
| │ └─Selection_40              | 9980.01  | cop[tikv] |                      | not(isnull(test.t.a)), not(isnull(test.t.b))                                                                |
| │   └─TableFullScan_39        | 10000.00 | cop[tikv] | table:t2             | keep order:false, stats:pseudo                                                                              |
| └─IndexLookUp_27(Probe)       | 1.25     | root      |                      |                                                                                                             |
|   ├─Selection_25(Build)       | 1.25     | cop[tikv] |                      | not(isnull(test.t.a))                                                                                       |
|   │ └─IndexRangeScan_23       | 1.25     | cop[tikv] | table:t1, index:a(a) | range: decided by [eq(test.t.a, test.t.a)], keep order:false, stats:pseudo                                  |
|   └─Selection_26(Probe)       | 1.25     | cop[tikv] |                      | not(isnull(test.t.b))                                                                                       |
|     └─TableRowIDScan_24       | 1.25     | cop[tikv] | table:t1             | keep order:false, stats:pseudo                                                                              |
+-------------------------------+----------+-----------+----------------------+-------------------------------------------------------------------------------------------------------------+
9 rows in set (0.01 sec)
```

If Hash Join is used, **_t1.a = t2.a and t1.b = t2.b_** will be put in equal condition. There is no such problem.

```sql
mysql> explain select * from t t1 inner join t t2 on t1.a = t2.a and t1.b = t2.b;
+------------------------------+----------+-----------+---------------+-------------------------------------------------------------------+
| id                           | estRows  | task      | access object | operator info                                                     |
+------------------------------+----------+-----------+---------------+-------------------------------------------------------------------+
| HashJoin_40                  | 12475.01 | root      |               | inner join, equal:[eq(test.t.a, test.t.a) eq(test.t.b, test.t.b)] |
| ├─TableReader_61(Build)      | 9980.01  | root      |               | data:Selection_60                                                 |
| │ └─Selection_60             | 9980.01  | cop[tikv] |               | not(isnull(test.t.a)), not(isnull(test.t.b))                      |
| │   └─TableFullScan_59       | 10000.00 | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                    |
| └─TableReader_54(Probe)      | 9980.01  | root      |               | data:Selection_53                                                 |
|   └─Selection_53             | 9980.01  | cop[tikv] |               | not(isnull(test.t.a)), not(isnull(test.t.b))                      |
|     └─TableFullScan_52       | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                    |
+------------------------------+----------+-----------+---------------+-------------------------------------------------------------------+
7 rows in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21138 to release-4.0

---

… other cond

### What problem does this PR solve?

Issue Number: close #20710

### What is changed and how it works?

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- ban (index) merge join heuristically when convert equal conditions to other conditions.

### CODE REVIEW

**Comment by lzmhhh123** [comment]
Wait for https://github.com/pingcap/tidb/pull/21086 merged.

**Comment by lzmhhh123** [comment]
conflicts resolved @SunRunAway @winoros

**Review by winoros — COMMENTED** [review]
lgtm

**Review by SunRunAway — APPROVED** [review]
LGTM

**Review by SunRunAway — APPROVED** [review]
LGTM

**Pull request merged**
