### PR TITLE
set gcScanLockLimit appropriately 

### PR DESCRIPTION
**Pull request by wentaoxu**
To avoid gc worker fill the resolved lock cache full.

### CODE REVIEW

**Comment by wentaoxu** [comment]
PTAL @shenli @coocood @disksing

**Comment by coocood** [comment]
@wentaoxu 
Can we not cache the gc worker resolved locks?

**Comment by wentaoxu** [comment]
I'm not sure it is better or worse in normal case, if there is not too much locks.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
