### PR TITLE
executor: add `DROP ROLE` support

### PR DESCRIPTION
**Pull request by imtbkcat**
### What problem does this PR solve? 
add `DROP ROLE` function for parser and executor.

### What is changed and how it works?
Role is same as user, is store in `mysql.user` table. We do same action as `DROP USER` when we need to drop a role. Also, as we has added some system table for RBAC, like `mysql.role_edges` and 
 `mysql.default_role`. We have to delete information from these tables when execute `DROP ROLE`

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported variable/fields change

Side effects

 - Increased code complexity

### CODE REVIEW

**Comment by imtbkcat** [comment]
parser pr: https://github.com/pingcap/parser/pull/237

**Comment by imtbkcat** [comment]
@tiancaiamao yes, `drop role` can drop user and `drop user` can also drop role.

**Comment by tiancaiamao** [comment]
LGTM

**Comment by jackysp** [comment]
https://github.com/pingcap/parser/pull/237 is merged @imtbkcat

**Comment by imtbkcat** [comment]
PTAL @jackysp

**Pull request merged**
