### PR TITLE
expression: fix json_key not compatible with MySQL

### PR DESCRIPTION
**Pull request by b41sh**
### What problem does this PR solve? 

Fix json_key not compatible with MySQL. [#9989](https://github.com/pingcap/tidb/issues/9989)

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by crazycs520** [comment]
@XuHuaiyu PTAL

**Comment by b41sh** [comment]
@xiekeyi98 PTAL

**Comment by bb7133** [comment]
Kindly remind, you can use 'close #9989' to [automatically close issues in GitHub.](https://help.github.com/en/articles/closing-issues-using-keywords)

**Comment by b41sh** [comment]
ok, thank you @bb7133

**Pull request merged**
