### PR TITLE
go.mod: update client-go to version 20210728

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: AndreMouche

### What problem does this PR solve?
This PR update client-go to the new version 20210728

### Check List 
Tests 
- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by disksing — APPROVED** [review]

**Comment by sticnarf** [comment]
```
[2021-07-28T05:14:13.280Z] WARNING: DATA RACE
[2021-07-28T05:14:13.280Z] Write at 0x00c0195531a1 by goroutine 75:
[2021-07-28T05:14:13.280Z]   github.com/pingcap/tidb/telemetry_test.TestReport()
[2021-07-28T05:14:13.280Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/telemetry/telemetry_test.go:112 +0x104
[2021-07-28T05:14:13.280Z]   testing.tRunner()
[2021-07-28T05:14:13.280Z]       /usr/local/go/src/testing/testing.go:1193 +0x202
[2021-07-28T05:14:13.280Z] 
[2021-07-28T05:14:13.280Z] Previous read at 0x00c0195531a1 by goroutine 79:
[2021-07-28T05:14:13.280Z]   [failed to restore the stack]
[2021-07-28T05:14:13.280Z] 
[2021-07-28T05:14:13.280Z] Goroutine 75 (running) created at:
[2021-07-28T05:14:13.280Z]   testing.(*T).Run()
[2021-07-28T05:14:13.280Z]       /usr/local/go/src/testing/testing.go:1238 +0x5d7
[2021-07-28T05:14:13.280Z]   testing.runTests.func1()
[2021-07-28T05:14:13.280Z]       /usr/local/go/src/testing/testing.go:1511 +0xa6
[2021-07-28T05:14:13.280Z]   testing.tRunner()
[2021-07-28T05:14:13.280Z]       /usr/local/go/src/testing/testing.go:1193 +0x202
[2021-07-28T05:14:13.280Z]   testing.runTests()
[2021-07-28T05:14:13.280Z]       /usr/local/go/src/testing/testing.go:1509 +0x612
[2021-07-28T05:14:13.280Z]   testing.(*M).Run()
[2021-07-28T05:14:13.280Z]       /usr/local/go/src/testing/testing.go:1417 +0x3b3
[2021-07-28T05:14:13.280Z]   go.uber.org/goleak.VerifyTestMain()
[2021-07-28T05:14:13.280Z]       /nfs/cache/mod/go.uber.org/goleak@v1.1.10/testmain.go:53 +0x5e
[2021-07-28T05:14:13.280Z]   github.com/pingcap/tidb/telemetry.TestMain()
[2021-07-28T05:14:13.280Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/telemetry/main_test.go:36 +0xe4
[2021-07-28T05:14:13.280Z]   main.main()
[2021-07-28T05:14:13.280Z]       _testmain.go:67 +0x271
[2021-07-28T05:14:13.280Z] 
[2021-07-28T05:14:13.280Z] Goroutine 79 (running) created at:
[2021-07-28T05:14:13.280Z]   testing.(*T).Run()
[2021-07-28T05:14:13.280Z]       /usr/local/go/src/testing/testing.go:1238 +0x5d7
[2021-07-28T05:14:13.280Z]   github.com/pingcap/tidb/telemetry_test.TestTxnUsageInfo()
[2021-07-28T05:14:13.280Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/telemetry/data_feature_usage_test.go:36 +0x149
[2021-07-28T05:14:13.280Z]   testing.tRunner()
[2021-07-28T05:14:13.280Z]       /usr/local/go/src/testing/testing.go:1193 +0x202
```

A race test failed but it seems not really related to this PR. I guess after the testify migration https://github.com/pingcap/tidb/pull/26540 some tests begin run in parallel?

**Comment by AndreMouche** [comment]
/run-unit-test

**Comment by AndreMouche** [comment]
/run-unit-test

**Pull request merged**
