### PR TITLE
planner, executor: add stale read compatibility for temporary table

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Temporary table should not perform stale read

### What is changed and how it works?

Add member variable `ExplicitStaleness` to builder to mark if this query statement should use stale read explicitly. If the txn is staleness or query is marked staleness, temporary table read should be fail.

### Related changes

N/A

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

**Review by djshow832 — APPROVED** [review]

**Review by djshow832 — APPROVED** [review]

**Review by xhebox — COMMENTED** [review]
What about `IsStaleness` instead of `ExplicitStaleness`? I am OK to `ExplicitStaleness`, though. Will approve anyway after the response.

**Comment by lcwangchao** [comment]
> What about `IsStaleness` instead of `ExplicitStaleness`? I am OK to `ExplicitStaleness`, though. Will approve anyway after the response.

The world `Explicit` means that it uses stale read explicitly in the query statement. So ExplicitStaleness can be a false value  when we just use `START TRANSACTION READ ONLY AS OF TIMESTAMP...` which is still a stale read. I think it is a bit more clear to indicate what the variable means.

**Comment by xhebox** [comment]
@icditwang But it will be `true` in the next `begin` or `select * ..` without `as of`.

**Review by xhebox — APPROVED** [review]

**Comment by nolouch** [comment]
Does it need to pick to 5.1?

**Comment by djshow832** [comment]
> Does it need to pick to 5.1?

The temporary table is not GA in 5.1, it will be GA in 5.1.1. We are cherry-picking it to release-5.1. @nolouch

**Pull request merged**
