### PR TITLE
parser, core: Implement force_index hint in parser and TiDB

### LINKED ISSUE #15519: warning message for incorrect index name is confusion
## Development Task

create a table:
```sql
CREATE TABLE `t` (
  `a` bigint(20) DEFAULT NULL,
  `b` bigint(20) DEFAULT NULL,
  KEY `idx` (`a`)
);
```

querying that table with an index hint which uses an undefined index `aaa`:
```sql
TiDB(root@127.0.0.1:test) > select /*+ force_index(aaa) */ * from t;
Empty set, 1 warning (0.00 sec)

TiDB(root@127.0.0.1:test) > show warnings;
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                                                                                           |
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 1064 | You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use [parser:8064]Optimizer hint syntax error at line 1 column 22 near "force_index(aaa) */"  |
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

as you can see, the warning message is:
```
You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use [parser:8064]Optimizer hint syntax error at line 1 column 22 near "force_index(aaa) */"
```

It's better to let the warning message shorter and more accurate, for example:
```
force_index(aaa) is inapplicable, "aaa" is not an index of table "t"
```

## what does mysql behave?

```sql
MySQL(root@127.0.0.1:test) > select /*+ force_index(aaa) */ * from t;
Empty set, 1 warning (0.00 sec)

MySQL(root@127.0.0.1:test) > show warnings;
+---------+------+---------------------------------------------------------------------------+
| Level   | Code | Message                                                                   |
+---------+------+---------------------------------------------------------------------------+
| Warning | 1064 | Optimizer hint syntax error near 'force_index(aaa) */ * from t' at line 1 |
+---------+------+---------------------------------------------------------------------------+
1 row in set (0.00 sec)

MySQL(root@127.0.0.1:test) > select version();
+-----------+
| version() |
+-----------+
| 8.0.18    |
+-----------+
1 row in set (0.00 sec)
```

as you can see, in mysql 8.0.18, the warning message is:
```
Optimizer hint syntax error near 'force_index(aaa) */ * from t' at line 1
```

Still confusion. I think we can do better.

### PR DESCRIPTION
**Pull request by zeroslope**
<!-- Thank you for contributing to TiDB!

PR Title Format:
1. pkg [, pkg2, pkg3]: what's changed
2. *: what's changed

-->

### What problem does this PR solve?

Issue Number: 
Fix #15519 

Before:
```
TiDB(root@127.0.0.1:test) > select /*+ force_index(aaa) */ * from t;
Empty set, 1 warning (0.00 sec)

TiDB(root@127.0.0.1:test) > show warnings;
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                                                                                           |
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 1064 | You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use [parser:8064]Optimizer hint syntax error at line 1 column 22 near "force_index(aaa) */"  |
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

After:
```
mysql> select /*+ force_index(aaa) */ * from t;
Empty set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------------------------------------------------------------------------+
| Level   | Code | Message                                                                         |
+---------+------+---------------------------------------------------------------------------------+
| Warning | 1815 | force_index(test.aaa) is inapplicable, check whether the table(test.aaa) exists |
+---------+------+---------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

Problem Summary: 
The parser does not support force_index optimizer hint.

### What is changed and how it works?

What's Changed:
1. implement force_index hint in TiDB parser
2. handle force_index in pushTableHints

How it Works:

- Implement force_index in parser first. 
- The logic for processing force_index is the same as FORCE INDEX, so there is no need to implement additional logic. 
- In TiDB, force_index and use_index have the same processing logic, force_index uses the same test example as use_index.

### Related changes

- pingcap/parser https://github.com/pingcap/parser/pull/1205

### Check List <!--REMOVE the items that are not applicable-->

Tests <!-- At least one of them must be included. -->

- Integration test

Side effects

### Release note <!-- bugfixes or new feature need a release note -->

- Implement force_index hint in parser and TiDB

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Comment by tangenta** [comment]
@zeroslope Hi, could you please keep the parser dependency unchanged, or update it to the latest one?

**Comment by zeroslope** [comment]
> @zeroslope Hi, could you please keep the parser dependency unchanged, or update it to the latest one?

ok，let me try

**Comment by zeroslope** [comment]
> [2021-06-29T08:48:25.744Z] panic: test timed out after 9m0s
> [2021-06-29T08:48:25.748Z] FAIL	github.com/pingcap/tidb/executor	540.391s
The test timeout. I don not know why. can @rebelice take a look at this problem?

**Comment by rebelice** [comment]
This is a known issue and is currently being investigated. This is not caused by you.

**Review by rebelice — APPROVED** [review]

**Comment by tisonkun** [comment]
Hi @zeroslope ! I notice that you spend quite a few time on this pull request and finally we get it merged. Thanks for your contribution!

I'd like to invite you to share the experience about participant in the TiDB community, and here is my email (wander4096@gmail.com). Looking forward to your feedback.

**Pull request merged**
