### PR TITLE
infoschema: change infoschem v2 btree element from tableItem to *tableItem

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: ref #58321

Problem Summary:

### What changed and how does it work?

`byName` and `byID` both hold the `tableItem`, if we change it to `*tableItem`, the can share the object to reduce memory usage.

Before:

Image

After:

image

1M table the btree memory usage reduce from 283M to 110MB

### Check List

Tests 

- [X] Unit test

No new code added, it should be covered by the existing tests

- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
Please also check GC pressure after the change

**Comment by tiancaiamao** [comment]
> Please also check GC pressure after the change because there are more pointers need to be tracked

Before the change:

image

After the change:

image

The statistics part uses much more objects than this change, if we want to optimize object count for GC, here is not the primary concern.  @lance6716

**Review by lance6716 — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
