### PR TITLE
 executor: split "executor.go"

### PR DESCRIPTION
**Pull request by zz-jason**

### CODE REVIEW

**Comment by coocood** [comment]
@zz-jason 
Can we use the same prefix like `exec_` so all the executor files are together?

**Comment by zz-jason** [comment]
@coocood I think it's not necessary to do that, nearly every file in `executor` is a executor file.

**Comment by coocood** [comment]
Too many files make it hard to find the needed one.
Can we make prefix for several category?

**Comment by zz-jason** [comment]
you can find all the executors in **executor/builder.go**

**Pull request closed without merging**
