### PR TITLE
domain, session: clean up in BootstrapSession

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/33235

Problem Summary:

### What is changed and how it works?

- Using `createSessions` instead of a lot  of `createSession`.
- Extract the ability to update memory-related configurations and system variables into a function.
- Do tiny cleanup.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by AilinKid — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]

**Comment by hawkingrei** [comment]
@zimulala Please fix the linter.

```

[2022-03-18T13:56:30.043Z]   ✘  https://revive.run/r#exported[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check/detail/tidb_ghpr_check/55714/pipeline#step-98-log-110)  exported method Domain.LoadStatsLoop should have comment or be unexported  

[2022-03-18T13:56:30.043Z]   domain/domain.go:1278:1
```

**Comment by zimulala** [comment]
PTAL @hawkingrei

**Pull request merged**
