### PR TITLE
planner: fix redudent planID for partition table in optimizer trace

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/36759

Problem Summary:

### What is changed and how it works?

 fix redudent planID for partition table in optimizer trace

### Check List

Tests 

- [x] Unit test
- [x] Manual test (add detailed scripts or steps below)

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by time-and-fate — COMMENTED** [review]
Can we just remove this code?
https://github.com/pingcap/tidb/blob/1937a7af792864f8b4c966e148868c6552fed79b/planner/core/rule_partition_processor.go#L1443-L1446
I find the `FromID` has been removed. If we could directly remove this, it would be much simpler.

**Comment by Yisaer** [comment]
> Can we just remove this code?
> 
> https://github.com/pingcap/tidb/blob/1937a7af792864f8b4c966e148868c6552fed79b/planner/core/rule_partition_processor.go#L1443-L1446
> 
> 
> I find the `FromID` has been removed. If we could directly remove this, it would be much simpler.

updated.

**Comment by time-and-fate** [comment]
I mean, if you directly remove this line
https://github.com/pingcap/tidb/blob/1937a7af792864f8b4c966e148868c6552fed79b/planner/core/rule_partition_processor.go#L1446
You might don't need to allocate a new ID manually.

**Comment by Yisaer** [comment]
> I mean, if you directly remove this line
> 
> https://github.com/pingcap/tidb/blob/1937a7af792864f8b4c966e148868c6552fed79b/planner/core/rule_partition_processor.go#L1446
> 
> 
> You might don't need to allocate a new ID manually.

I remained this code in order not to change the result in testcase, there are too many in explain test and mysql test

**Review by time-and-fate — APPROVED** [review]
Others LGTM.
The code in this PR uses `AllocNewPlanID`, but other places are still using `s.PlanID` directly.

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
