### PR TITLE
expression: fix comparation between uint and int

### PR DESCRIPTION
**Pull request by XuHuaiyu**
Before this commit, this sql returns 1;
```sql
select 1 > 17666000000000000000
```
PTAL @winoros @zz-jason

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
CI failed

**Comment by XuHuaiyu** [comment]
#6034 will fix ci.

**Comment by zhexuany** [comment]
This PR blocks by https://github.com/pingcap/tidb/pull/6034. Please do not merge.

**Comment by shenli** [comment]
@XuHuaiyu Can we merge this now?

**Comment by XuHuaiyu** [comment]
yes

**Pull request merged**
