### PR TITLE
Revert "executor/show: show create table return utf8mb4 charset. (#8604)

### PR DESCRIPTION
**Pull request by crazycs520**
This reverts commit d69490b77e3e913d6122fa607bc29cf3eb95c498.

### What problem does this PR solve? 
The problem mentioned in #8604 already fix by #8738.
Revert PR #8604 is if the charset is binary, but show create table return charset utf8mb4, mydumper will create table with charset utf8mb4, but import data is binary, will cause error.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8782)

### CODE REVIEW

**Comment by shenli** [comment]
Please fix the CI.

**Comment by zz-jason** [comment]
@crazycs520 Please add some proper labels. For example, component, type, etc.

**Pull request merged**
