### PR TITLE
session, sessionctx/variable: add relaxed validation for global vars

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/29587

Problem Summary:

When a sysvar is set from an earlier version of TiDB, it could cause problems after upgrade to a newer version which uses different rules for validation.

We currently handle this correctly for session scoped variables, but there was a gap where global scoped variables were not handled correctly. This PR addresses GLOBAL scoped variables.

### What is changed and how it works?

When a global scoped variable is read, validation is now applied to it to make sure it uses the rules of the current TiDB server version. This helps improve consistency after upgrading from an earlier verison of TiDB.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [x] Performance regression: Consumes more CPU
Whenever a system variable is read, more CPU is consumed. It could have also been possible to validate and 'cache' system variables, but I opted not to do this because the cache is actually re-generated very frequently at current. Also, global variables are rarely read. We could review this in future if we change the sysvar cache to be less frequent. We also currently always re-run validation for session variables, which is a larger opportunity for optimization.
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
When a global scoped system variable is read, validation is now applied to it to make sure it uses the rules of the current TiDB server version. This helps improve consistency after upgrading from an earlier verison of TiDB.
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by dveeden — APPROVED** [review]

**Comment by morgo** [comment]
@bb7133 PTAL, it needs a configuration-reviewer.

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
