### PR TITLE
br: refactoring code - remove unnecessary variables

### PR DESCRIPTION
**Pull request by fengou1**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
Please add a release note, or a 'None' if it is not needed.
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]

**Review by kennytm — APPROVED** [review]

**Comment by kennytm** [comment]
/merge cancel

```
[2021-09-22T11:37:30.094Z] br/pkg/lightning/backend/local/local_test.go:352:27: too many arguments in call to openLocalWriter
[2021-09-22T11:37:30.094Z] 	have (context.Context, *backend.LocalWriterConfig, *File, number)
[2021-09-22T11:37:30.094Z] 	want (*backend.LocalWriterConfig, *File, int64)
```

**Comment by fengou1** [comment]
> /merge cancel
> 
> ```
> [2021-09-22T11:37:30.094Z] br/pkg/lightning/backend/local/local_test.go:352:27: too many arguments in call to openLocalWriter
> [2021-09-22T11:37:30.094Z] 	have (context.Context, *backend.LocalWriterConfig, *File, number)
> [2021-09-22T11:37:30.094Z] 	want (*backend.LocalWriterConfig, *File, int64)
> ```

Issue fixed, it is really strange why we can not touch this part of unit test.

**Pull request merged**
