### PR TITLE
planner: forbid prepared stale select in txn

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Problem Summary: https://github.com/pingcap/tidb/pull/25156#discussion_r649929163. Forbid prepared stale select in all txns.

### What is changed and how it works?

What's Changed:

1. Prepared stale select is forbidden in all txn.
2. Error is refined. `Unknown error!%(Extra string...`, the original error is like so. It is so ugly.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- Forbid prepared stale select in transactions

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Review by Yisaer — COMMENTED** [review]
Could you add a testcase?

**Comment by xhebox** [comment]
@Yisaer It is already included in the previous PR. Now it is changed to `c.Assert(err, NotNil)` in `stale_txn_test.go`.

**Comment by Yisaer** [comment]
> @Yisaer It is already included in the previous PR. Now it is changed to `c.Assert(err, NotNil)` in `stale_txn_test.go`.

got it.

**Review by Yisaer — APPROVED** [review]

**Pull request merged**
