### PR TITLE
ddl: add index use table scan to prune column.

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
DNM, still in test.
Currently TiDB add index use `type Storage interface` to fetch row data, this will transfer all column data.
This PR make add index use table scan to fetch necessary column data, prune redundant columns.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Code changes

 - Has exported function/method change
Side effects

Related changes

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8373)

### CODE REVIEW

**Comment by crazycs520** [comment]
@winkyao PTAL

**Comment by winoros** [comment]
Please fill the pr description

**Pull request closed without merging**
