### PR TITLE
expression, session: handle `CASE WHEN` specially when folding constant during outerJoin Simplification(#11105)

### PR DESCRIPTION
**Pull request by lovewin99**
cherry-pick ##11105 to release-3.0

### CODE REVIEW

**Comment by eurekaka** [comment]
@lovewin99 CI failed, PTAL

**Comment by lovewin99** [comment]
> @lovewin99 CI failed, PTAL

This problem is not caused by this commit. The latest code is merged and passed.

**Comment by lovewin99** [comment]
/idc-jenkins-ci-tidb/unit-test

**Pull request merged**
