### PR TITLE
infoschema: add more tests for infoschema predicate

### PR DESCRIPTION
**Pull request by CbcWestwolf**
### What problem does this PR solve?

Issue Number: ref #50305

Problem Summary:

### What changed and how does it work?

In `pkg/planner/core/memtable_infoschema_extractor_test.go` we cover testing all combinations of predicates for each infoschema table. It takes tens of seconds to run `TestMemtableInfoschemaExtractor`

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [x] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by CbcWestwolf** [comment]
PTAL @tangenta @wjhuang2016

**Review by wjhuang2016 — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
