### PR TITLE
domain: adjust the order of acquireServerID and GlobalInfoSyncerInit to fix global kill test

### LINKED ISSUE #33538: globalkilltest TestMultipleTiDB failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run `TestMultipleTiDB` in `tests/globalkilltest/global_kill_test.go`.

### 2. What did you expect to see? (Required)
The test succeeded.

### 3. What did you see instead (Required)
The test failed.

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #33538

Problem Summary:
globalkilltest `TestMultipleTiDB` failed. 

### What is changed and how it works?

When #17649 introduces global kill, in `(*Domain).Init`, we first call `do.acquireServerID` to get server ID and then call `infosync.GlobalInfoSyncerInit` to store server ID to etcd. #28945 switches the order between `do.acquireServerID` and `infosync.GlobalInfoSyncerInit` and thus we store server ID zero to etcd, which causes the failure of `TestMultipleTiDB`. The pr switches the order back to fix the test case.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test (though globalkilltest seems not to be executed in CI)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by pingyu — APPROVED** [review]
Great ! LGTM~

**Comment by pingyu** [comment]
P.S. It would be better to add ["tests/globalkilltest"](https://github.com/pingcap/tidb/tree/master/tests/globalkilltest) to CI later, to avoid similar issue again. But it seems to be not stable now and need some improvement.

**Review by AilinKid — APPROVED** [review]
LGTM

**Pull request merged**
