### PR TITLE
infosync: close body when ReadAll encounters error

### LINKED ISSUE #30464: Resource may leak when ReadAll meets error
### 1. Minimal reproduce step (Required)

https://github.com/pingcap/tidb/blob/b2ea0e66b85b448866237740818e238e2d536a95/domain/infosync/info.go#L347-L363

### 2. What did you expect to see? (Required)

The body should be closed when the error happens.

### 3. What did you see instead (Required)

The resource may leak.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by rleungx**
Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

Issue Number: close #30464 

Problem Summary: See the related issue for more details.

### What is changed and how it works?

Close response body when an error happens.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the issue that the response body doesn't close when ReadAll meets an error.
```

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by Defined2014 — APPROVED** [review]

**Comment by bb7133** [comment]
The change is simple enough.

Could make a check for the other calls of ReadAll(), and is there any way to make a check for all of them in a systematical way?

**Comment by rleungx** [comment]
> The change is simple enough.
> 
> Could make a check for the other calls of ReadAll(), and is there any way to make a check for all of them in a systematical way?

This issue can be found by `bodyclose` linter.

**Pull request merged**
