### PR TITLE
*: use testkit/testdata instead of util/testutil

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

use testkit/testdata instead of util/testutil

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
@tisonkun @time-and-fate PTAL

**Review by ichn-hu — APPROVED** [review]

**Review by time-and-fate — COMMENTED** [review]
It seems like we can call `LoadTestSuiteData()` once for each suite like we did in `main_test.go` of `util/ranger`.
Currently all usages of `(*BookKeeper).LoadTestSuiteData()` are placed in `TestMain()`

**Comment by hawkingrei** [comment]
> It seems like we can call `LoadTestSuiteData()` once for each suite like we did in `main_test.go` of `util/ranger`. Currently all usages of `(*BookKeeper).LoadTestSuiteData()` are placed in `TestMain()`.

Great, it is a good idea. I will improve it.

**Comment by hawkingrei** [comment]
> It seems like we can call `LoadTestSuiteData()` once for each suite like we did in `main_test.go` of `util/ranger`. Currently all usages of `(*BookKeeper).LoadTestSuiteData()` are placed in `TestMain()`.

But it is a problem that you cannot run one test by specifying the test name, it will not execute the ```TestMain```. It is convenient for developers to run tests.

**Comment by hawkingrei** [comment]
TestMain is a low-level primitive and should not be necessary for casual testing needs, where ordinary test functions suffice. 

https://pkg.go.dev/testing#hdr-Main

**Comment by hawkingrei** [comment]
@tison PTAL

**Review by AilinKid — APPROVED** [review]

**Comment by time-and-fate** [comment]
> > It seems like we can call `LoadTestSuiteData()` once for each suite like we did in `main_test.go` of `util/ranger`. Currently all usages of `(*BookKeeper).LoadTestSuiteData()` are placed in `TestMain()`.
> 
> But it is a problem that you cannot run one test by specifying the test name, it will not execute the `TestMain`. It is convenient for developers to run tests.

I think we are still able to run single test cases after we add `TestMain`, like the current test cases using `TestMain`.

**Comment by hawkingrei** [comment]
> > > It seems like we can call `LoadTestSuiteData()` once for each suite like we did in `main_test.go` of `util/ranger`. Currently all usages of `(*BookKeeper).LoadTestSuiteData()` are placed in `TestMain()`.
> > 
> > 
> > But it is a problem that you cannot run one test by specifying the test name, it will not execute the `TestMain`. It is convenient for developers to run tests.
> 
> I think we are still able to run single test cases after we add `TestMain`, like the current test cases using `TestMain`.

It's my problem. it have been fixed.

**Review by time-and-fate — APPROVED** [review]

**Pull request merged**
