### PR TITLE
parser: fix the error message when no `on commit delete rows` specified

### LINKED ISSUE #29842: create global temporary table whitout oncommitOpt has a  confusing error message
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create global temporary table t010(local_01 int, local_03 varchar(20));
create global temporary table t010(local_01 int, local_03 varchar(20)) on commit preserve rows;
```

### 2. What did you expect to see? (Required)
```sql
mysql test> create global temporary table t010(local_01 int, local_03 varchar(20));
(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 70 near ""GLOBAL TEMPORARY and ON COMMIT DELETE ROWS must appear together ')
```
### 3. What did you see instead (Required)
the error message says need `ON COMMIT DELETE|PRESERVE ROWS`, but when using `on commit preserve rows` report doesn't support.
```sql
mysql test> create global temporary table t010(local_01 int, local_03 varchar(20));
(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 70 near ""GLOBAL TEMPORARY and ON COMMIT DELETE|PRESERVE ROWS must appear together ')
mysql root@172.16.4.131:test> create global temporary table t010(local_01 int, local_03 varchar(20)) on commit preserve rows;
(8200, "TiDB doesn't support ON COMMIT PRESERVE ROWS for now")
```
### 4. What is your TiDB version? (Required)
release-5.3(70cbb55b502d03d86b24c84bc4)

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

Issue Number: close #29842

Problem Summary:
For now, we don't support `on commit preserve rows`, so it's better not to expose it to users.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by sylzd — COMMENTED** [review]
I've seen:
https://github.com/pingcap/tidb/blob/25ebef3f3c731e26c485e91a77fa79c1c257e7ad/parser/parser.y#L1071
and DDL worker still support `PRESERVE`, are these should be changed too? if user use `PRESERVE` directly other than see the error info

**Review by lcwangchao — APPROVED** [review]

**Comment by djshow832** [comment]
> I've seen:
> 
> https://github.com/pingcap/tidb/blob/25ebef3f3c731e26c485e91a77fa79c1c257e7ad/parser/parser.y#L1071
> 
> 
> and DDL worker still support `PRESERVE`, are these should be changed too? if user use `PRESERVE` directly other than see the error info

No, it's a decision made much earlier that the parser supports `preserve` but TiDB reports an error. You can check the error in the original issue: https://github.com/pingcap/tidb/issues/29842

**Review by tiancaiamao — APPROVED** [review]

**Comment by sylzd** [comment]
> > I've seen:
> > https://github.com/pingcap/tidb/blob/25ebef3f3c731e26c485e91a77fa79c1c257e7ad/parser/parser.y#L1071
> > 
> > and DDL worker still support `PRESERVE`, are these should be changed too? if user use `PRESERVE` directly other than see the error info
> 
> No, it's a decision made much earlier that the parser supports `preserve` but TiDB reports an error. You can check the error in the original issue: #29842
> 
> ```
> mysql root@172.16.4.131:test> create global temporary table t010(local_01 int, local_03 varchar(20)) on commit preserve rows;
> (8200, "TiDB doesn't support ON COMMIT PRESERVE ROWS for now")
> ```

got it~

**Pull request merged**
