### PR TITLE
variable: allow setting system variable lc_messages

### LINKED ISSUE #38231: `read-only` for `lc_messages` breaks compatible with `phpmyadmin`
## Bug Report

see details from https://github.com/pingcap/tidb/pull/33708#issuecomment-1260738467

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

Issue Number: close #38231

Problem Summary:

https://github.com/pingcap/tidb/pull/33708 breaks the compatibility of phpMyAdmin.

### What is changed and how it works?

Set `lc_messages` back to not read-only.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Allow setting system variable `lc_messages`.
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Review by morgo — APPROVED** [review]

**Comment by Defined2014** [comment]
/cc @bb7133 
PTAL

**Review by qw4990 — APPROVED** [review]

**Comment by jaggerwang** [comment]
@djshow832 When this PR be merged to v6.1.x? I checked the latest v6.1.2's release notes, which released at 10/24, but it not contains this fix.

**Comment by Defined2014** [comment]
Not all bug fixes will be cherry-picked into LTS version. If you didn't found it by `git log`, the answer is no. Maybe you should wait v6.5.0 instead. :( @jaggerwang

**Pull request merged**
