### PR TITLE
ddl: let `admin cancel ddl jobs` run in a new transaction

### LINKED ISSUE #24172: ddl: admin cancel ddl job may return success appearancely but actually it doesn't
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. you can build a big table with many rows and try to add a index to it (this DDL may take a long time)
2. you can mock the write conflict error for a specified query for `admin cancel ddl jobs job_id`
3. you will get a successful result for this cancel statement still

Reason:
We use the session.txn in `CancelDDLJobsExec` to do some meta check and write the canceling job state back.
```
txn, err := e.ctx.Txn(true)
if err != nil {
b.err = err
return nil
}

e.errs, b.err = admin.CancelJobs(txn, e.jobIDs)
if b.err != nil {
return nil
}
```
Then we fill the chunk with successful result in `(e *CancelDDLJobsExec) Next` and return.
```
for i := e.cursor; i < e.cursor+numCurBatch; i++ {
req.AppendString(0, fmt.Sprintf("%d", e.jobIDs[i]))
if e.errs[i] != nil {
	req.AppendString(1, fmt.Sprintf("error: %v", e.errs[i]))
} else {
	req.AppendString(1, "successful")
}
}
e.cursor += numCurBatch
```
Actually, the session.txn is not always a successful commit.
```
rs, err = s.Exec(ctx)
sessVars.TxnCtx.StatementCount++
if rs != nil {
return &execStmtResult{
	RecordSet: rs,
	sql:       s,
	se:        se,
}, err
}

err = finishStmt(ctx, se, err, s)   // skipped for now
```
As you see here above, once the rs is not null, the finishStmt will skipped temporarily.
```
func (cc *clientConn) handleStmt(ctx context.Context, stmt ast.StmtNode, warns []stmtctx.SQLWarn, lastStmt bool) (bool, error) {
	ctx = context.WithValue(ctx, execdetails.StmtExecDetailKey, &execdetails.StmtExecDetails{})
	ctx = context.WithValue(ctx, util.ExecDetailsKey, &util.ExecDetails{})
	reg := trace.StartRegion(ctx, "ExecuteStmt")
	rs, err := cc.ctx.ExecuteStmt(ctx, stmt)
	reg.End()
	// The session tracker detachment from global tracker is solved in the `rs.Close` in most cases.
	// If the rs is nil, the detachment will be done in the `handleNoDelay`.
	if rs != nil {
		defer terror.Call(rs.Close)
	}


func (rs *execStmtResult) Close() error {
	se := rs.se
	err := rs.RecordSet.Close()
	return finishStmt(context.Background(), se, err, rs.sql)
}
```
Once the upper layer drained the recordSet, the `defer terror.Call(rs.Close)` action will do the finishStmt eventually. 
The write conflict error doesn't take effect anymore and it is only logged consequently.

### 2. What did you expect to see? (Required)
Write conflict error for `admin cancel ddl jobs job_id`

### 3. What did you see instead (Required)
successful

### 4. What is your TiDB version? (Required)

master, 5.0, 4.0

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

Issue Number: close #24172

Problem Summary:
Currently, `admin cancel ddl jobs` runs in the current session transaction, which is problematic:
- `admin cancel ddl jobs` returns a `RecordSet` but also modifies data. In TiDB, statements that return `RecordSet` are read-only (to the current user transaction), statements that are not read-only do not return `RecordSet`. Otherwise, commit failure won't be reported to the client.
- `admin cancel ddl jobs` updates the metadata. When the cross-region feature is enabled in the future, metadata won't be pinned to a specific zone. Thus, only global transactions can access the metadata. However, all the user transactions are local transactions by default, so the user must specify a global transaction to run `admin cancel ddl jobs`, which is unreasonable.

### What is changed and how it works?
Read and update the metadata in another transaction. The transaction is retryable but it won't override unexpected jobs, because each time the transaction retries, it reads all the jobs again.

Actually, this is not the best solution, because retrying may still fail when the `admin cancel ddl jobs` is too slow while the adding index worker will update the job periodically, which leads to writing conflict and makes `admin cancel ddl jobs` fail again. In the end, `admin cancel ddl jobs` always fails and the adding index job cannot be cancelled.

Better solutions may be:
- `admin cancel ddl jobs` writes to another meta key, which avoids writing conflicts.
- Locks the meta key when reading the job, which makes other transactions wait and avoids writing conflicts.

Note that now `admin cancel ddl jobs` runs in another transaction, it can not be rollbacked in an explicit transaction anymore. This is a compatibility breaker but I think it's fine.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

Steps:
1. Mock the code:
  - sleep 30s in the data reorg
  - sleep 30s in the cancel ddl jobs
2. Prepare tables:
  - create table t(id int);
  - create table t1(id int);
3. In session A:
  - alter table t add index (id);     # It blocks for 30s and finally cancelled normally.
4. In session B:
  - admin show ddl jobs;
  - admin cancel ddl jobs;           # It also blocks for 30s and finally succeeds.
5. In session C:
  - alter table t1 add index (id);         # It makes conflicts and makes the cancelling retry.

Before the modification, `alter table t add index (id)` finally succeeds.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
- Fix the bug that `admin cancel ddl jobs` may fail but still report success.
```

### CODE REVIEW

**Comment by bb7133** [comment]
> it can not be rollbacked in an explicit transaction anymore.

I don't think it's a problem(nor any user tried this ever).

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Review by wjhuang2016 — APPROVED** [review]

**Comment by djshow832** [comment]
`testSerialDBSuite.TestCommitTxnWithIndexChange` failed this time. I'm investigating if it's related to this PR.

**Pull request merged**
