### PR TITLE
types: Fix issue about ineffectual assignment

### LINKED ISSUE #25837: make dev not work for master branch
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

git clone the latest tidb of master branch
make dev

### 2. What did you expect to see? (Required)
pass the test scenario

### 3. What did you see instead (Required)
INFO [runner] linters took 57.912244849s with stages: goanalysis_metalinter: 33.210289721s, unused: 24.562551138s 
types/time.go:3007:3: ineffectual assignment to `state` (ineffassign)
                state := parseStateNormal
                ^
types/time.go:3085:3: ineffectual assignment to `state` (ineffassign)
                state := parseStateNormal
                ^
INFO File cache stats: 1028 entries of total size 18.9MiB 
INFO Memory: 609 samples, avg is 2274.8MB, max is 3855.5MB 
INFO Execution took 1m7.788009602s                
make: *** [check-static] Error 1

### 4. What is your TiDB version? (Required)
commit 0e1420db12d419352b41a19085b974e8f4936dd4

Release Version: v5.2.0-alpha-182-g0e1420db1
Edition: Community
Git Commit Hash: 0e1420db12d419352b41a19085b974e8f4936dd4
Git Branch: master
UTC Build Time: 2021-06-30 03:07:55
GoVersion: go1.16.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

```
types/time.go:3007:3: ineffectual assignment to `state` (ineffassign)
                state := parseStateNormal
                ^
types/time.go:3085:3: ineffectual assignment to `state` (ineffassign)
                state := parseStateNormal
                ^
```

Issue Number: close #25837

### Release note 

- No release note

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
Thanks for your fix @dveeden ! LGTM.

I'm curious why our CI doesn't report this style issue previously.

**Comment by tisonkun** [comment]
/cc @XuHuaiyu @wjhuang2016 

PTAL

**Review by wjhuang2016 — APPROVED** [review]

**Comment by dveeden** [comment]
Fixed via cb06e116c1bfb1089c2e1df5072e889a3b7decd3 from #25912

**Pull request closed without merging**
