### PR TITLE
topsql: add exec count dedicated to sql duration

### PR DESCRIPTION
**Pull request by mornyx**
Signed-off-by: mornyx <mornyx.z@gmail.com>

Issue Number: close https://github.com/pingcap/tidb/issues/31379

### What's changed

- Add exec count dedicated to sql duration

### Related PR

- https://github.com/pingcap/tipb/pull/253
- https://github.com/pingcap/ng-monitoring/pull/96

### Check List

Tests

- [x] Unit test
- [x] Integration test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by breeswish — APPROVED** [review]

**Comment by breeswish** [comment]
Wait until https://github.com/pingcap/tipb/pull/253 is merged

**Review by zhongzc — APPROVED** [review]

**Review by breeswish — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]

**Pull request merged**
