### PR TITLE
makefile: fix upload-coverage

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Fix https://github.com/pingcap/tidb/issues/29589.

Problem Summary: tidb_ghpr_coverage has been failed for a while.

### What is changed and how it works?

According to documentation of codecov, [bash uploader is deprecated](https://docs.codecov.com/docs/about-the-codecov-bash-uploader). This PR migrate to a [new uploader](https://docs.codecov.com/docs/codecov-uploader).

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tangenta** [comment]
The coverage view page: https://codecov.io/github/pingcap/tidb/commit/65fa04a889b72d94c77a93160c0de1c79abb1b50

**Review by wjhuang2016 — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
