### PR TITLE
parser: Adjust rule precedence

### PR DESCRIPTION
**Pull request by shenli**
Fix parser conflicts

### CODE REVIEW

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by siddontang** [comment]
The branch is not merged newest master, I think the newest master has already fixed it.

**Comment by coocood** [comment]
That is a bug in our old code, the master has fixed it, you can cherry pick that commit.

**Comment by shenli** [comment]
@qiuyesuifeng Please merge master and check if the conflicts are already solved.

**Comment by qiuyesuifeng** [comment]
Sorry, i will merge master firstly.

**Pull request closed without merging**
