### PR TITLE
sessionctx, executor: make the upper limit of tidb_ddl_reorg_worker_cnt work

### LINKED ISSUE #23017: The upper limit of `tidb_ddl_reorg_worker_cnt` doesn't work
## Bug Report

Please answer these questions before submitting your issue. Thanks!

It seems that we don't set the max value to `maxDDLReorgWorkerCoun`, we can see [code](https://github.com/pingcap/tidb/blob/master/sessionctx/variable/sysvar.go#L679).
And we can update [tidb_ddl_reorg_worker_cnt]( https://docs.pingcap.com/zh/tidb/stable/system-variables#tidb_ddl_reorg_worker_cnt ) too.

### 1. Minimal reproduce step (Required)
```set @@global.tidb_ddl_reorg_worker_cnt=129;```

### 2. What did you expect to see? (Required)
```
tidb> set @@global.tidb_ddl_reorg_worker_cnt=129;
ERROR 1231 (42000): Variable 'tidb_ddl_reorg_worker_cnt' can't be set to the value of '129'
```

### 3. What did you see instead (Required)
```
tidb> set @@global.tidb_ddl_reorg_worker_cnt=129;
Query OK, 0 rows affected (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-2207-gf16801be2
Edition: Community
Git Commit Hash: f16801be23c7923816f05773b7628c176afca368
Git Branch: master
```

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #23017  

Problem Summary:

### What is changed and how it works?

What's Changed:
make the upper limit of tidb_ddl_reorg_worker_cnt work
How it Works:
Add upper limit for `tidb_ddl_reorg_worker_cnt`
### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by AilinKid — COMMENTED** [review]
/LGTM

**Comment by bb7133** [comment]
I agree that #23017 is a moderate bug and we actually have the internal check from `maxDDLReorgWorkerCount`:

https://github.com/pingcap/tidb/blob/master/sessionctx/variable/varsutil.go#L38

So I don't think we need to backport it.

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
