### PR TITLE
test: close duplicateDB when meet error halfway

### LINKED ISSUE #46682: goleak github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
coverage: 82.8% of statements

goleak: Errors on successful test run: found unexpected goroutines:

[Goroutine 2206831 in state select, with github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1 on top of the stack:

goroutine 2206831 [select]:

github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()

	external/com_github_cockroachdb_pebble/vfs/disk_health.go:63 +0xcb

created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 2206746

	external/com_github_cockroachdb_pebble/vfs/disk_health.go:58 +0x58


]

--

```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #46682

Problem Summary:

### What is changed and how it works?

try to solve a flaky test. We shall see if it won't appear in future

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by zimulala — COMMENTED** [review]
Do we need to add a test？Or we have this test(If it has this test, please add it to PR description)

**Comment by lance6716** [comment]
> Do we need to add a test？Or we have this test(If it has this test, please add it to PR description)

Updated, it's https://github.com/pingcap/tidb/issues/46682

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
