### PR TITLE
errcode: add errcode for structure, tablecodec, admin file

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve? 

Add error codes,  [parser pull request](https://github.com/pingcap/parser/pull/678)

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

Release note

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@jackysp @imtbkcat PTAL

**Comment by jackysp** [comment]
PTAL @imtbkcat

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
