### PR TITLE
util/encrypt: parallelize tests

### LINKED ISSUE #28034: Parallelize `util/encrypt` package tests
## Enhancement

Parallelize `util/encrypt` package tests. Related PR and issue - #28016 and #27816
Comments about test parallelization - https://github.com/pingcap/tidb/pull/28016#pullrequestreview-753487807 , https://github.com/pingcap/tidb/pull/28016#issuecomment-918886894

### PR DESCRIPTION
**Pull request by karuppiah7890**
### What problem does this PR solve?

Issue Number: close #28034

Problem Summary:

### What is changed and how it works?

What's Changed: `util/encrypt` package tests have been parallelized

Tests

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM. Thanks for your follow up!

**Review by mmyj — APPROVED** [review]
lgtm

**Pull request merged**
