### PR TITLE
go.mod, go.sum: upgrade automaxprocs version from v1.2.0 to v1.4.0

### PR DESCRIPTION
**Pull request by hykych**
### What problem does this PR solve?

Problem Summary: 
There is a bug in go.uber.org/automaxprocs@v1.2.0 that it couldn't process the content in /proc/$PID/cgroup correctly, hence TiDB would be failed to startup when it running in containerd v1.3.6 configured with SystemdCgroup = false

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:
automaxprocs@v1.2.0 parse cgroup content error. the log shows like this:

> [2021/05/19 05:28:06.757 +00:00] [FATAL] [terror.go:256] ["unexpected error"] [error="invalid format for CGroupSubsys: \"12:cpuset:/kubepods-besteffort-pod5f56f681_7ee0_491f_b823_c5f1ceb78805.slice:cri-containerd:76ae0b8206b5840a195b184f294a151d398fbcc784e5f40a64202754b588c248\""] [stack="github.com/pingcap/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20201130080042-c3ddfec58248/terror/terror.go:256\nmain.setGlobalVars\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/tidb-server/main.go:509\nmain.main\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/tidb-server/main.go:172\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"] [stack="github.com/pingcap/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20201130080042-c3ddfec58248/terror/terror.go:256\nmain.setGlobalVars\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/tidb-server/main.go:509\nmain.main\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/tidb-server/main.go:172\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"]

the reason for this see the following case and the code:
- Containerd cgroup format example:
`12:cpuset:/kubepods-besteffort-pod5f56f681_7ee0_491f_b823_c5f1ceb78805.slice:cri-containerd:76ae0b8206b5840a195b184f294a151d398fbcc784e5f40a64202754b588c248`

- Cgroup parsing code in automaxprocs v1.2.0
   https://github.com/uber-go/automaxprocs/blob/v1.2.0/internal/cgroups/subsys.go#L55

- Cgroup parsing code in automaxprocs v1.4.0 (latest)
https://github.com/uber-go/automaxprocs/blob/v1.4.0/internal/cgroups/subsys.go#L55

### Related changes

- PR to update `go.mod`, `go.sum`:

Tests 

- Unit test

### Release note 

- fix the bug that TiDB crash at startup in containerd v1.3.6 configured with SystemdCgroup = false

### CODE REVIEW

**Review by HunDunDM — APPROVED** [review]

**Comment by tisonkun** [comment]
Hello @hykych ! Thanks for your contribution.

Please do not cc a huge group of reviewer, which definitely creates spams.

Generally you can require review from two reviewers or committers and they will react when they are free. Everyone is volunteering their time to the community so please be patient.

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
