### PR TITLE
*: Enable gosec for implicit memory aliasing in for loop

### LINKED ISSUE #28861: Enable golangci-lint `gosec`

### PR DESCRIPTION
**Pull request by janisz**
Fixes: #28861

### What problem does this PR solve?

Issue Number: close #28861

Problem Summary: Enable gosec G601 check and fix all issues.

### What is changed and how it works?

Use index instead of range value.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tangenta** [comment]
@janisz Sorry I haven't been paying attention to this PR.

It seems we have new commits(98c7bbd36) breaking this linter, could you also update it?
```
[2021-11-05T15:12:43.792Z] executor/show_stats.go:503:61: G601: Implicit memory aliasing in for loop. (gosec)
[2021-11-05T15:12:43.792Z] 						appendTableForColumnStatsUsage(db.Name.O, tbl, false, &def)
[2021-11-05T15:12:43.792Z] 						                                                      ^
[2021-11-05T15:12:43.792Z] executor/show_stats.go:508:60: G601: Implicit memory aliasing in for loop. (gosec)
[2021-11-05T15:12:43.792Z] 					appendTableForColumnStatsUsage(db.Name.O, tbl, false, &def)
```

/hold

**Comment by janisz** [comment]
I'm sorry I was AFK for a week. I'll take a look at this ASAP

**Comment by janisz** [comment]
@tangenta Fixed

**Pull request merged**
