### PR TITLE
Makefile: make race test parallel on package level

### PR DESCRIPTION
**Pull request by tiancaiamao**
```
for dir in $$dirs 
    go test -race dir
done
```

run the test package sequentially, while

`go test -race A B C` let them parallel on package level

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by zimulala** [comment]
Does it make checking race log more difficult?

**Comment by tiancaiamao** [comment]
@zimulala 
I think it won't. Let's have a look:

1. all packages pass test, there won't be any race log, right?
2. if there is exactly one package have race problem, it would be the only output log, so it makes no difference despite parallel or not.
3. if there are several packages have race problem but they are not parallel at the same time (actually we have GOMAXPROCS package run tests parallel), this case is the same with case 2.
4. several packages have race problem and parallel... that's the only case the log would intersect and cause trouble for debug... 

but I think case 4 is rare, and if it happened, our code quality would be blamed....

**Comment by coocood** [comment]
LGTM

**Comment by zimulala** [comment]
Yep. using this code the case 1 is established.
LGTM

**Pull request merged**
