### PR TITLE
privilege,session: Match loopback connections to 'localhost' accounts (#29995)

### LINKED ISSUE #29995: TiDB behaves differently than MySQL on authentication of users with the same name and different hosts when wild card involved
### 1. Minimal reproduce step (Required)
Login as 'root' and create 2 users as follows:
create user 'test'@'%' identified by '%'
create user 'test'@'localhost' identified by 'localhost'
Try to login as 'test' from localhost with password '%'.

### 2. What did you expect to see? (Required)
MySQL will reject the login with error message like 'ERROR 1045 (28000): Access denied for user 'test'@'localhost' (using password: YES)

### 3. What did you see instead (Required)
Login succeeds, and CURRENT_USER() will be recognized as 'test'@'%'

### 4. What is your TiDB version? (Required)
v4.0.15

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #29995

Problem Summary:
loopback interface connections was not matching 'localhost' hostname.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Also maps loopback address to 'localhost' for authentication, like matching 'user'@'127.0.0.1' with 'user'@'localhost' if no 'user'@'127.0.0.1' exists
```

### CODE REVIEW

**Review by morgo — APPROVED** [review]

**Review by dveeden — APPROVED** [review]
From the issue description:
```
ERROR 1045 (28000): Access denied for user 'test'@'localhost' (using password: YES)
```

Actual error with this PR:
```
ERROR 1045 (28000): Access denied for user 'test'@'127.0.0.1' (using password: YES)
```

**Comment by mjonss** [comment]
> From the issue description:
> 
> ```
> ERROR 1045 (28000): Access denied for user 'test'@'localhost' (using password: YES)
> ```
> 
> Actual error with this PR:
> 
> ```
> ERROR 1045 (28000): Access denied for user 'test'@'127.0.0.1' (using password: YES)
> ```

I would consider that to be a different bug, i.e. show 'localhost' for '127.0.0.1' (or all loopback addresses?) in error messages and user()/current_user() function.
Do you want me to create such issue?

**Comment by mjonss** [comment]
After https://github.com/pingcap/tidb/pull/30204 was merge, it only consists of more tests, but I think it will still be useful, since it is integration tests that would prevent some regressions.

**Pull request merged**
