### PR TITLE
planner: show cast type in EXPLAIN in coptask

### LINKED ISSUE #23100: Show the casted type of `cast` in `explain`/`explain analyze` result in cop task.
## Feature Request

**Describe the feature you'd like:**
Show the casted type of `cast` in explain result.

This is an explain result:
```sql
mysql> explain select count(*) from t group by microsecond(a);
+---------------------------+----------+--------------+---------------+----------------------------------------------------------------+
| id                        | estRows  | task         | access object | operator info                                                  |
+---------------------------+----------+--------------+---------------+----------------------------------------------------------------+
| HashAgg_9                 | 8000.00  | root         |               | group by:Column#7, funcs:count(Column#8)->Column#6             |
| └─TableReader_10          | 8000.00  | root         |               | data:HashAgg_5                                                 |
|   └─HashAgg_5             | 8000.00  | cop[tiflash] |               | group by:microsecond(cast(test.t.a)), funcs:count(1)->Column#8 |
|     └─TableFullScan_8     | 10000.00 | cop[tiflash] | table:t       | keep order:false, stats:pseudo                                 |
+---------------------------+----------+--------------+---------------+----------------------------------------------------------------+
4 rows in set (0.00 sec)
```

I want to know what type `test.t.a` is converted into from the `explain` result, like `cast(test.t.a, Duration)`.

### PR DESCRIPTION
**Pull request by TszKitLo40**
Signed-off-by: alfredlu <wslzj40@gmail.com>

### What problem does this PR solve?

Issue Number: close #23100  

Problem Summary:

### What is changed and how it works?

What's Changed:
show cast type in EXPLAIN in coptask
How it Works:
Add cast type in `explainInfo`
### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by ngaut — APPROVED** [review]
/LGTM

**Review by lzmhhh123 — APPROVED** [review]

**Comment by LittleFall** [comment]
Some tests in tidb-test repo failed and need to be updated.

```sql
explain select f1 from t1 where json_extract(f1,\"$\") = \"asd\";
```

**Comment by TszKitLo40** [comment]
> Some tests in pingcap/tidb-test repo failed and need to be updated. @TszKitLo40
> 
> ```sql
> explain select f1 from t1 where json_extract(f1,\"$\") = \"asd\";
> ```

How to update it?

**Comment by LittleFall** [comment]
> How to update it?

there are some private test cases should be updated, please wait until we made the updates.

**Pull request merged**
