### PR TITLE
ddl: don't use lease when writing MDL to ETCD

### LINKED ISSUE #44014: DDL is blocked if the MDL info in ETCD is expired
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

During a DDL, a TiDB server writes the MDL info to ETCD with a lease. If this TiDB server can't connect to PD for a long time, the MDL info is expired. 
If so, the DDL is blocked.

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #44014

Problem Summary:
Using lease when writing MDL to ETCD may lead to lost MDL info.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix a bug that using lease when writing MDL to ETCD which may lead to DDL blocked
```

### CODE REVIEW

**Review by zimulala — COMMENTED** [review]
If there is no UT, can you test manually? If there are manual tests, please update them to the PR description

**Comment by wjhuang2016** [comment]
The test would be added later in endless. It's hard to test it in UT.

**Review by zimulala — APPROVED** [review]
LGTM

**Pull request merged**
