### PR TITLE
*: fix data race in the tikv_client

### LINKED ISSUE #30658: DATA RACE in the doActionOnGroupMutations
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```make race```

```
 WARNING: DATA RACE
Read at 0x00c004f9c598 by goroutine 97:
  internal/race.Read()
      /usr/local/go/src/internal/race/race.go:37 +0x206
  sync.(*WaitGroup).Add()
      /usr/local/go/src/sync/waitgroup.go:71 +0x219
  github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).doActionOnGroupMutations()
      /go/pkg/mod/github.com/tikv/client-go/v2@v2.0.0-rc.0.20211214093715-605f49d3ba50/txnkv/transaction/2pc.go:778 +0x826
  github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).doActionOnMutations()
      /go/pkg/mod/github.com/tikv/client-go/v2@v2.0.0-rc.0.20211214093715-605f49d3ba50/txnkv/transaction/2pc.go:588 +0x168
  github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).commitMutations()
      /go/pkg/mod/github.com/tikv/client-go/v2@v2.0.0-rc.0.20211214093715-605f49d3ba50/txnkv/transaction/commit.go:213 +0x109
  github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).commitTxn()
      /go/pkg/mod/github.com/tikv/client-go/v2@v2.0.0-rc.0.20211214093715-605f49d3ba50/txnkv/transaction/2pc.go:1428 +0x337
  github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).execute()
      /go/pkg/mod/github.com/tikv/client-go/v2@v2.0.0-rc.0.20211214093715-605f49d3ba50/txnkv/transaction/2pc.go:1419 +0x18e4
  github.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).Commit()
      /go/pkg/mod/github.com/tikv/client-go/v2@v2.0.0-rc.0.20211214093715-605f49d3ba50/txnkv/transaction/txn.go:399 +0x5f2
  github.com/pingcap/tidb/store/driver/txn.(*tikvTxn).Commit()
      /home/jenkins/agent/workspace/atom-ut/tidb/store/driver/txn/txn_driver.go:74 +0x64
  github.com/pingcap/tidb/session.(*LazyTxn).Commit()
      /home/jenkins/agent/workspace/atom-ut/tidb/session/txn.go:365 +0x8fc
  github.com/pingcap/tidb/session.(*session).commitTxnWithTemporaryData()
      /home/jenkins/agent/workspace/atom-ut/tidb/session/session.go:666 +0xbad
  github.com/pingcap/tidb/session.(*session).doCommit()
      /home/jenkins/agent/workspace/atom-ut/tidb/session/session.go:576 +0xce4
  github.com/pingcap/tidb/session.(*session).doCommitWithRetry()
      /home/jenkins/agent/workspace/atom-ut/tidb/session/session.go:796 +0x204
  github.com/pingcap/tidb/session.(*session).CommitTxn()
      /home/jenkins/agent/workspace/atom-ut/tidb/session/session.go:858 +0x169
  github.com/pingcap/tidb/session.autoCommitAfterStmt()
      /home/jenkins/agent/workspace/atom-ut/tidb/session/tidb.go:272 +0x4d4
  github.com/pingcap/tidb/session.finishStmt()
      /home/jenkins/agent/workspace/atom-ut/tidb/session/tidb.go:238 +0xfb
  github.com/pingcap/tidb/session.runStmt()
      /home/jenkins/agent/workspace/atom-ut/tidb/session/session.go:1805 +0x5c8
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      /home/jenkins/agent/workspace/atom-ut/tidb/session/session.go:1678 +0xcf0
  github.com/pingcap/tidb/session.(*session).ExecuteInternal()
      /home/jenkins/agent/workspace/atom-ut/tidb/session/session.go:1390 +0x284
  github.com/pingcap/tidb/table/tables.(*stateRemoteHandle).execSQL()
      /home/jenkins/agent/workspace/atom-ut/tidb/table/tables/state_remote.go:348 +0x102
  github.com/pingcap/tidb/table/tables.(*stateRemoteHandle).commitTxn()
      /home/jenkins/agent/workspace/atom-ut/tidb/table/tables/state_remote.go:292 +0x9a
  github.com/pingcap/tidb/table/tables.(*stateRemoteHandle).runInTxn()
      /home/jenkins/agent/workspace/atom-ut/tidb/table/tables/state_remote.go:323 +0x526
  github.com/pingcap/tidb/table/tables.(*stateRemoteHandle).LockForRead()
      /home/jenkins/agent/workspace/atom-ut/tidb/table/tables/state_remote.go:103 +0x16c
  github.com/pingcap/tidb/table/tables.(*cachedTable).UpdateLockForRead()
      /home/jenkins/agent/workspace/atom-ut/tidb/table/tables/cache.go:165 +0x149
  github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource.func1()
      /home/jenkins/agent/workspace/atom-ut/tidb/planner/core/logical_plan_builder.go:4209 +0xcc

Previous write at 0x00c004f9c598 by goroutine 87:
  internal/race.Write()
      /usr/local/go/src/internal/race/race.go:41 +0x125
  sync.(*WaitGroup).Wait()
      /usr/local/go/src/sync/waitgroup.go:128 +0x126
  github.com/tikv/client-go/v2/tikv.(*KVStore).Close()
      /go/pkg/mod/github.com/tikv/client-go/v2@v2.0.0-rc.0.20211214093715-605f49d3ba50/tikv/kv.go:299 +0x6b
  github.com/pingcap/tidb/store/mockstore/mockstorage.(*mockStorage).Close()
      /home/jenkins/agent/workspace/atom-ut/tidb/store/mockstore/mockstorage/storage.go:117 +0x75
  github.com/pingcap/tidb/testkit.bootstrap.func1()
      /home/jenkins/agent/workspace/atom-ut/tidb/testkit/mockstore.go:56 +0x7d
  github.com/pingcap/tidb/table/tables_test.TestCacheCondition()
      /home/jenkins/agent/workspace/atom-ut/tidb/table/tables/cache_test.go:199 +0x726
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202

Goroutine 97 (running) created at:
  github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource()
      /home/jenkins/agent/workspace/atom-ut/tidb/planner/core/logical_plan_builder.go:4204 +0x408f
  github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildResultSetNode()
      /home/jenkins/agent/workspace/atom-ut/tidb/planner/core/logical_plan_builder.go:341 +0xbd4
  github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildJoin()
      /home/jenkins/agent/workspace/atom-ut/tidb/planner/core/logical_plan_builder.go:675 +0x30c9
  github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildResultSetNode()
      /home/jenkins/agent/workspace/atom-ut/tidb/planner/core/logical_plan_builder.go:328 +0xf84
  github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildTableRefs()
      /home/jenkins/agent/workspace/atom-ut/tidb/planner/core/logical_plan_builder.go:322 +0x104
  github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect()
      /home/jenkins/agent/workspace/atom-ut/tidb/planner/core/logical_plan_builder.go:3553 +0x3e4
  github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build()
      /home/jenkins/agent/workspace/atom-ut/tidb/planner/core/planbuilder.go:714 +0x1364
  github.com/pingcap/tidb/planner.optimize()
      /home/jenkins/agent/workspace/atom-ut/tidb/planner/optimize.go:355 +0x46f
  github.com/pingcap/tidb/planner.Optimize()
      /home/jenkins/agent/workspace/atom-ut/tidb/planner/optimize.go:238 +0x1614
  github.com/pingcap/tidb/executor.(*Compiler).Compile()
      /home/jenkins/agent/workspace/atom-ut/tidb/executor/compiler.go:65 +0x411
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      /home/jenkins/agent/workspace/atom-ut/tidb/session/session.go:1656 +0x584
  github.com/pingcap/tidb/testkit.(*TestKit).Exec()
      /home/jenkins/agent/workspace/atom-ut/tidb/testkit/testkit.go:155 +0x2dc
  github.com/pingcap/tidb/testkit.(*TestKit).MustExec()
      /home/jenkins/agent/workspace/atom-ut/tidb/testkit/testkit.go:77 +0x96
  github.com/pingcap/tidb/table/tables_test.TestCacheCondition()
      /home/jenkins/agent/workspace/atom-ut/tidb/table/tables/cache_test.go:197 +0x6cb
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202

Goroutine 87 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1238 +0x5d7
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1511 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1509 +0x612
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1417 +0x3b3
  go.uber.org/goleak.VerifyTestMain()
      /go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x5e
  github.com/pingcap/tidb/table/tables_test.TestMain()
      /home/jenkins/agent/workspace/atom-ut/tidb/table/tables/main_test.go:30 +0xe4
  main.main()
      _testmain.go:189 +0x371
================== 
```

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #30658  #30651

Problem Summary:

### What is changed and how it works?

relation with https://github.com/tikv/client-go/pull/396
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by djshow832 — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]
Although it's not the best way to fix the issue from my point of view (it's not fixing the root cause), I think this is still acceptable.

**Comment by cfzjywxk** [comment]
> Although it's not the best way to fix the issue from my point of view (it's not fixing the root cause), I think this is still acceptable.

Agree we'd better to fix the root cause otherwise there could still be such cases in the future.

**Comment by hawkingrei** [comment]
I agreed too, it is a root cause that we need a mechanism to wait for all requests to stop before the store exit.

**Pull request merged**
