### PR TITLE
executor: optimize warning information when query table information_schema.cluster_config

### LINKED ISSUE #24690: Optimize warning information when query table information_schema.cluster_config
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Set up a cluster with at least one tiflash server

### 2. What did you expect to see? (Required)
```
autopilot@c3-youpin-merge-tidb01.bj(order_merge) > select * from information_schema.cluster_config where `key` = 'x';
Empty set, 2 warnings (0.01 sec)

Mon May 17 19:16:12 2021
autopilot@c3-youpin-merge-tidb01.bj(order_merge) > show warnings;
+---------+------+------------------------------------------------+
| Level   | Code | Message                                        |
+---------+------+------------------------------------------------+
| Warning | 1105 | unknown node type: tiflash(10.142.129.11:3930) |
| Warning | 1105 | unknown node type: tiflash(10.136.168.12:3930) |
+---------+------+------------------------------------------------+
2 rows in set (0.00 sec)
```
Mon May 17 19:16:17 2021

### 3. What did you see instead (Required)

node `tiflash` is a tiflash node, maybe the initial meanings was 'Can't get config from tiflash node', so we need to change the warnning infomationn like 'Currently we do not support get config from node ....'

### 4. What is your TiDB version? (Required)
master branch

### PR DESCRIPTION
**Pull request by yuqi1129**
### What problem does this PR solve?

Issue Number: close #24690 
Problem Summary: 

### What is changed and how it works?

Proposal: [Optimize warning information when query table information_schema.cluster_config](https://github.com/pingcap/tidb/pull/24691/files) 

What's Changed:
Minor change, just change warnings information when query table information_schema.cluster_config
How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
- No release node

### CODE REVIEW

**Comment by yuqi1129** [comment]
@qw4990 Can you take time to review this minor change, as i knonw there is a similar change here about the problem, i wander if there is a need to make this change. thanks

**Review by qw4990 — APPROVED** [review]

**Comment by qw4990** [comment]
PTAL @wshwsh12  one-line bugfix

**Review by wshwsh12 — APPROVED** [review]

**Pull request merged**
