### PR TITLE
session: refine error message desensitization (#19409)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19409 to release-4.0

---

Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Close https://github.com/pingcap/tidb/issues/18566#issuecomment-670277765

* Make `Duplicate entry` error message desensitization.

Below is the test SQL:

```sql
create table t (id int auto_increment, b int,  unique index (id));
insert into t values  (1,1),(1,1);
begin;
insert into t values  (1,1);
insert into t values  (1,1);
```

* change variable name from `tidb_log_desensitization ` to `tidb_redact_log `.

related log:

```sql
[2020/08/24 20:26:01.567 +08:00] [WARN] [session.go:476] ["can not retry txn"] [conn=1] [label=general] [error="[kv:1062]Duplicate entry '?' for key '?'"] [IsBatchInsert=false] [IsPessimistic=false] [InRestrictedSQL=false] [tidb_retry_limit=10] [tidb_disable_txn_auto_retry=true]
[2020/08/24 20:26:01.567 +08:00] [WARN] [session.go:492] ["commit failed"] [conn=1] ["finished txn"="Txn{state=invalid}"] [error="[kv:1062]Duplicate entry '?' for key '?'"]
[2020/08/24 20:26:01.567 +08:00] [ERROR] [conn.go:744] ["command dispatched failed"] [conn=1] [connInfo="id:1, addr:127.0.0.1:60651 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="insert into t values ( ... )"] [txn_mode=OPTIMISTIC] [err="[kv:1062]Duplicate entry '?' for key '?'"]
[2020/08/24 20:26:01.567 +08:00] [INFO] [2pc.go:717] ["2PC clean up done"] [conn=1] [txnStartTS=418977405093019648]
[2020/08/24 20:26:01.663 +08:00] [ERROR] [conn.go:744] ["command dispatched failed"] [conn=1] [connInfo="id:1, addr:127.0.0.1:60651 status:11, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:1, autocommit:1"] [sql="insert into t values ( ... )"] [txn_mode=OPTIMISTIC] [err="[kv:1062]Duplicate entry '?' for key '?'"]
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- - Breaking backward compatibility: change variable name from `tidb_log_desensitization ` to `tidb_redact_log `.

### Release note 

- Refine error message desensitization.

### CODE REVIEW

**Comment by SunRunAway** [comment]
@crazycs520 Please resolve the conflicts

**Review by jackysp — COMMENTED** [review]
LGTM

**Review by SunRunAway — APPROVED** [review]
LGTM

**Pull request merged**
