### PR TITLE
plan: check every child and rebuild their schema if necessary

### PR DESCRIPTION
**Pull request by zz-jason**
before this pr, child mat not be checked because of the short circuit

### CODE REVIEW

**Comment by hanfei1991** [comment]
Will this cause any bug ?

**Comment by zz-jason** [comment]
@hanfei1991 we use schema to build a chunk as result for every executor, if the schema is not right, take join for an example, an **index out of range** panic may be presented during the query execution.

**Comment by coocood** [comment]
Can reproduce the issue that the schema is not right in a test?

**Comment by zz-jason** [comment]
@coocood It was firstly found during the develop of https://github.com/pingcap/tidb/pull/5312, and can be reproduced in our current integration testing, but I didn't store the test case and it takes time to find that exact test case.

**Comment by zz-jason** [comment]
here is a case:
```sql
drop table if exists tab0, tab1;
CREATE TABLE tab0(pk INTEGER PRIMARY KEY, col0 INTEGER, col1 FLOAT, col2 TEXT, col3 INTEGER, col4 FLOAT, col5 TEXT);
INSERT INTO tab0 VALUES(0,30,20.40,'nztwp',16,40.7,'fapep');
INSERT INTO tab0 VALUES(1,25,54.31,'tzynq',2,2.58,'qpxlz');
INSERT INTO tab0 VALUES(2,64,21.7,'kdbxx',97,51.56,'xngtg');
INSERT INTO tab0 VALUES(3,73,97.44,'glact',65,62.85,'juskx');
INSERT INTO tab0 VALUES(4,92,30.98,'jwiwi',61,32.44,'zcrud');
INSERT INTO tab0 VALUES(5,32,51.78,'lpmjm',93,5.14,'gcxab');
INSERT INTO tab0 VALUES(6,40,89.2,'xwxub',85,75.18,'invov');
INSERT INTO tab0 VALUES(7,58,82.63,'uneya',39,99.82,'jhmtq');
INSERT INTO tab0 VALUES(8,88,85.89,'fsdyl',99,15.3,'korob');
INSERT INTO tab0 VALUES(9,57,93.6,'gkxut',11,45.4,'odgey');
CREATE TABLE tab1(pk INTEGER PRIMARY KEY, col0 INTEGER, col1 FLOAT, col2 TEXT, col3 INTEGER, col4 FLOAT, col5 TEXT);
CREATE INDEX idx_tab1_0 on tab1 (col0);
CREATE INDEX idx_tab1_1 on tab1 (col1);
CREATE INDEX idx_tab1_3 on tab1 (col3);
CREATE INDEX idx_tab1_4 on tab1 (col4);
INSERT INTO tab1 SELECT * FROM tab0;
SELECT pk FROM tab1 WHERE col4 >= 27.95 AND (col4 >= 54.22) AND (((((((((col3 IS NULL AND col1 IS NULL AND col4 > 54.18 OR col3 > 66 AND col0 IN (SELECT col3 FROM tab1 WHERE col3 IN (SELECT col0 FROM tab1 WHERE (col4 > 28.60) AND ((col1 >= 56.55))) OR col4 = 24.21)))) AND col4 IS NULL AND col0 > 98 OR (col0 >= 2 AND col3 > 56) AND (col0 > 0 AND col0 >= 18 AND (col0 BETWEEN 7 AND 35) AND col3 > 4 AND col3 >= 92 OR ((col4 < 38.98) AND (((col0 < 42))) AND col1 <= 13.31 OR (col3 < 7)) AND col1 >= 82.41 OR (col3 IS NULL)) AND col0 > 2)))) AND col3 < 20)) OR col0 < 79 AND (((col1 BETWEEN 19.74 AND 0.44)) AND col0 = 46) AND (col3 IS NULL) AND col3 <= 55;
```

the plan is:

![hehe](https://user-images.githubusercontent.com/5268763/33819560-1a9e5968-de86-11e7-91a8-a0b431ecfdc9.png)


```txt
TiDB(127.0.0.1) > desc SELECT pk FROM tab1 WHERE col4 >= 27.95 AND (col4 >= 54.22) AND (((((((((col3 IS NULL AND col1 IS NULL AND col4 > 54.18 OR col3 > 66 AND col0 IN (SELECT col3 FROM tab1 WHERE col3 IN (SELECT col0 FROM tab1 WHERE (col4 > 28.60) AND ((col1 >= 56.55))) OR col4 = 24.21)))) AND col4 IS NULL AND col0 > 98 OR (col0 >= 2 AND col3 > 56) AND (col0 > 0 AND col0 >= 18 AND (col0 BETWEEN 7 AND 35) AND col3 > 4 AND col3 >= 92 OR ((col4 < 38.98) AND (((col0 < 42))) AND col1 <= 13.31 OR (col3 < 7)) AND col1 >= 82.41 OR (col3 IS NULL)) AND col0 > 2)))) AND col3 < 20)) OR col0 < 79 AND (((col1 BETWEEN 19.74 AND 0.44)) AND col0 = 46) AND (col3 IS   NULL) AND col3 <= 55;
+----------------+---------------+-------------------------------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| id             | parents       | children                      | task | operator info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | count |
+----------------+---------------+-------------------------------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| IndexScan_17   |               |                               | cop  | table:tab1, index:col0, range:[<nil>,+inf], out of order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |     0 |
| TableScan_18   |               |                               | cop  | table:tab1, keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |     0 |
| IndexLookUp_19 | MergeJoin_14  |                               | root | index:IndexScan_17, table:TableScan_18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |     0 |
| IndexScan_39   |               |                               | cop  | table:tab1, index:col3, range:[<nil>,+inf], out of order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |     0 |
| TableScan_40   |               |                               | cop  | table:tab1, keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |     0 |
| IndexLookUp_41 | MergeJoin_27  |                               | root | index:IndexScan_39, table:TableScan_40                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |     0 |
| IndexScan_45   |               |                               | cop  | table:tab1, index:col0, range:[<nil>,+inf], out of order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |     0 |
| TableScan_46   | Selection_47  |                               | cop  | table:tab1, keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |     0 |
| Selection_47   |               | TableScan_46                  | cop  | gt(test.tab1.col4, 28.6), ge(test.tab1.col1, 56.55)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |     0 |
| IndexLookUp_48 | MergeJoin_27  |                               | root | index:IndexScan_45, table:Selection_47                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |     0 |
| MergeJoin_27   | Selection_26  | IndexLookUp_41,IndexLookUp_48 | root | left outer semi join, equal:[eq(test.tab1.col3, test.tab1.col0)], left key:test.tab1.col3, right key:test.tab1.col0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |     0 |
| Selection_26   | MergeJoin_14  | MergeJoin_27                  | root | or(8_aux_0, eq(test.tab1.col4, 24.21))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |     0 |
| MergeJoin_14   | Selection_13  | IndexLookUp_19,Selection_26   | root | left outer semi join, equal:[eq(test.tab1.col0, test.tab1.col3)], left key:test.tab1.col0, right key:test.tab1.col3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |     0 |
| Selection_13   | Projection_12 | MergeJoin_14                  | root | or(and(and(ge(test.tab1.col4, 27.95), ge(test.tab1.col4, 54.22)), and(or(and(or(and(isnull(test.tab1.col3), and(isnull(test.tab1.col1), gt(test.tab1.col4, 54.18))), and(gt(test.tab1.col3, 66), 10_aux_0)), and(isnull(test.tab1.col4), gt(test.tab1.col0, 98))), and(and(ge(test.tab1.col0, 2), gt(test.tab1.col3, 56)), and(or(and(and(gt(test.tab1.col0, 0), and(ge(test.tab1.col0, 18), ge(test.tab1.col0, 7))), and(le(test.tab1.col0, 35), and(gt(test.tab1.col3, 4), ge(test.tab1.col3, 92)))), or(and(or(and(lt(test.tab1.col4, 38.98), and(lt(test.tab1.col0, 42), le(test.tab1.col1, 13.31))), lt(test.tab1.col3, 7)), ge(test.tab1.col1, 82.41)), isnull(test.tab1.col3))), gt(test.tab1.col0, 2)))), lt(test.tab1.col3, 20))), and(and(1, and(ge(test.tab1.col1, 19.74), le(test.tab1.col1, 0.44))), and(eq(test.tab1.col0, 46), and(isnull(test.tab1.col3), le(test.tab1.col3, 55))))) |     0 |
| Projection_12  |               | Selection_13                  | root | test.tab1.pk                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |     0 |
+----------------+---------------+-------------------------------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
15 rows in set (0.00 sec)
```

in the old code, `MergeJoin_14` will first check its child 0, i.e. `IndexLookUp_19`, witch sets true to `needRebuild`, and its child 1, i.e. `Selection_26` is skipped and never checked, so we have no chance to correct the schema of `MergeJoin_27`

**Comment by zz-jason** [comment]
@hanfei1991 @coocood PTAL

**Comment by coocood** [comment]
LGTM

**Pull request merged**
