### PR TITLE
statistics: check step overflow when converting a range to points for estimation

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23625

Problem Summary:
Panic when running a query.

### What is changed and how it works?

What's Changed:

Check step overflow when converting a range to points for estimation.

How it Works:

For `datetime` type, if the upper bound of the range is much larger than the lower bound, it is possible to trigger the overflow of steps to a negative value, we should make such kind of checks.

### Related changes

N/A

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- Check step overflow when converting a range to points for estimation

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by time-and-fate — APPROVED** [review]
/lgtm

**Pull request merged**
