### PR TITLE
plan: adjust the parameter of cbo.

### PR DESCRIPTION
**Pull request by hanfei1991**
If there is a order by and between. TiDB will consider between with high priority.
@shenli @coocood @zimulala PTAL

### CODE REVIEW

**Comment by shenli** [comment]
Should we consider unique index?

**Comment by hanfei1991** [comment]
@shenli I think we'd better to change the rate of between only.

**Comment by coocood** [comment]
LGTM

**Comment by hanfei1991** [comment]
Add a test, compare the plan result before or after we use `analysis`.

**Pull request merged**
