### PR TITLE
planner: fix wrong behavior for != any() (#20058)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20058 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/20007 

Problem Summary: 
The result is unstable.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: Use max function instead of first_row function.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- Fix wrong behavior for != any()

### CODE REVIEW

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Review by eurekaka — APPROVED** [review]
LGTM. @wshwsh12 please fix the CI.

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
