### PR TITLE
*: remove useless FIXME tip in code

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary: Either `RestoreStringSingleQuotes` or `RestoreStringDoubleQuotes` can solve the issue. Doubles like `''`/`""` will be interpreted as one single character in the string.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- No release note

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
/LGTM

**Review by xiongjiwei — APPROVED** [review]

**Comment by hi-rustin** [comment]
@ti-chi-bot  update this pr branch

**Pull request merged**
