### PR TITLE
release-2.0: cherry-pick some commits

### PR DESCRIPTION
**Pull request by winoros**
#6366 #6368 #6364 #6307

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Would you please also have this https://github.com/pingcap/tidb/pull/6340 included? @winoros

**Comment by tiancaiamao** [comment]
Now https://github.com/pingcap/tidb/pull/6340 is already cherry pick to release 2.0, so it's not necessary to do it here. @winoros

**Comment by coocood** [comment]
@winoros 
Please only pick the bug fix.

**Pull request closed without merging**
