### PR TITLE
planner: label predicate_simplification as over-optimized for plan cache

### LINKED ISSUE #43405: wrong result with plan cache
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE `UK_SIGNED_19384` (
    `COL1` decimal(37,4) unsigned DEFAULT NULL COMMENT 'WITH DEFAULT',
    `COL2` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL,
    `COL4` datetime DEFAULT NULL,
    `COL3` bigint DEFAULT NULL,
    `COL5` float DEFAULT NULL,
    UNIQUE KEY `UK_COL1` (`COL1`) /*!80000 INVISIBLE */
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO `UK_SIGNED_19384` VALUES
  (729024465529090.5423,'劗驻胭毤橰亀讁陶ĉ突錌ͳ河碡祁聓兕锻觰俆','4075-07-11 12:02:57',6021562653572886552,1.93349e38),
  (492790234219503.0846,'硴皡箒嫹璞玚囑蚂身囈軔獰髴囥慍廂頚禌浖蕐','1193-09-27 12:13:40',1836453747944153034,-2.67982e38),
  (471841432147994.4981,'豻貐裝濂婝蒙蘦镢県蟎髓蓼窘搴熾臐哥递泒執','1618-01-24 05:06:44',6669616052974883820,9.38232e37);
prepare stmt from 'select/*+ tidb_inlj(t1) */ * from UK_SIGNED_19384 t1 join UK_SIGNED_19384 t2 on t1.col1 = t2.col1 where t1. col1 != ? and t2. col1 in (?, ?, ?);';
set @a=999999999999999999999999999999999.9999, @b=999999999999999999999999999999999.9999, @c=999999999999999999999999999999999.9999, @d=999999999999999999999999999999999.9999;
execute stmt using @a,@b,@c,@d;
set @a=895769331208356.9029, @b=471841432147994.4981, @c=729024465529090.5423, @d=492790234219503.0846;
execute stmt using @a,@b,@c,@d;
```

### 2. What did you expect to see? (Required)
```sql
[18:01:32]TiDB root:test> execute stmt using @a,@b,@c,@d;
+----------------------+------------------------------------------+---------------------+---------------------+--------------+----------------------+------------------------------------------+---------------------+---------------------+--------------+
| COL1                 | COL2                                     | COL4                | COL3                | COL5         | COL1                 | COL2                                     | COL4                | COL3                | COL5         |
+----------------------+------------------------------------------+---------------------+---------------------+--------------+----------------------+------------------------------------------+---------------------+---------------------+--------------+
| 729024465529090.5423 | 劗驻胭毤橰亀讁陶ĉ突錌ͳ河碡祁聓兕锻觰俆   | 4075-07-11 12:02:57 | 6021562653572886552 |  1.93349e+38 | 729024465529090.5423 | 劗驻胭毤橰亀讁陶ĉ突錌ͳ河碡祁聓兕锻觰俆   | 4075-07-11 12:02:57 | 6021562653572886552 |  1.93349e+38 |
| 492790234219503.0846 | 硴皡箒嫹璞玚囑蚂身囈軔獰髴囥慍廂頚禌浖蕐 | 1193-09-27 12:13:40 | 1836453747944153034 | -2.67982e+38 | 492790234219503.0846 | 硴皡箒嫹璞玚囑蚂身囈軔獰髴囥慍廂頚禌浖蕐 | 1193-09-27 12:13:40 | 1836453747944153034 | -2.67982e+38 |
| 471841432147994.4981 | 豻貐裝濂婝蒙蘦镢県蟎髓蓼窘搴熾臐哥递泒執 | 1618-01-24 05:06:44 | 6669616052974883820 |  9.38232e+37 | 471841432147994.4981 | 豻貐裝濂婝蒙蘦镢県蟎髓蓼窘搴熾臐哥递泒執 | 1618-01-24 05:06:44 | 6669616052974883820 |  9.38232e+37 |
+----------------------+------------------------------------------+---------------------+---------------------+--------------+----------------------+------------------------------------------+---------------------+---------------------+--------------+
```
### 3. What did you see instead (Required)
```sql
[18:02:16]TiDB root:test> execute stmt using @a,@b,@c,@d;
+----------------------+------------------------------------------+---------------------+---------------------+--------------+----------------------+------------------------------------------+---------------------+---------------------+--------------+
| COL1                 | COL2                                     | COL4                | COL3                | COL5         | COL1                 | COL2                                     | COL4                | COL3                | COL5         |
+----------------------+------------------------------------------+---------------------+---------------------+--------------+----------------------+------------------------------------------+---------------------+---------------------+--------------+
| 492790234219503.0846 | 硴皡箒嫹璞玚囑蚂身囈軔獰髴囥慍廂頚禌浖蕐 | 1193-09-27 12:13:40 | 1836453747944153034 | -2.67982e+38 | 492790234219503.0846 | 硴皡箒嫹璞玚囑蚂身囈軔獰髴囥慍廂頚禌浖蕐 | 1193-09-27 12:13:40 | 1836453747944153034 | -2.67982e+38 |
+----------------------+------------------------------------------+---------------------+---------------------+--------------+----------------------+------------------------------------------+---------------------+---------------------+--------------+
```
### 4. What is your TiDB version? (Required)
```sql
[18:03:39]TiDB root:test> select tidb_version();
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v7.1.0-rc.0                              |
| Edition: Community                                        |
| Git Commit Hash: ba71c5fcedf6da2ec68759513493b7484e2e97b5 |
| Git Branch: heads/refs/tags/v7.1.0-rc.0                   |
| UTC Build Time: 2023-04-22 10:01:11                       |
| GoVersion: go1.20.3                                       |
| Race Enabled: false                                       |
| TiKV Min Version: 6.2.0-alpha                             |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
+-----------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #43405

Problem Summary: planner: label predicate_simplification as over-optimized for plan cache

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by ghazalfamilyusa** [comment]
@qw4990 Could you add a simple explanation of the cause and fix? I am not familiar with labeling optimizations for plan cache.  Does it mean we skip the cache when these optimizations are applied or is the issue of the key for the cache?

**Review by chrysan — APPROVED** [review]

**Pull request merged**
