### PR TITLE
log: add get-latest-ts duration of async commit and 1pc into slowlog

### PR DESCRIPTION
**Pull request by you06**
### What problem does this PR solve?

Issue Number: ref #34106

Problem Summary:

Add get-latest-ts duration into slowlog.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Add Get_latest_ts_time into slowlog, which records the duration of TSO fetch in async commit and 1pc.
```

### CODE REVIEW

**Review by zyguan — APPROVED** [review]
LGTM

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by sticnarf — APPROVED** [review]
LGTM

**Comment by zyguan** [comment]
> @sticnarf: `/merge` in this pull request requires 2 approval(s).

It seems I'm not a reviewer... @cfzjywxk PTAL

**Review by xhebox — APPROVED** [review]

**Review by xhebox — COMMENTED** [review]
Just a confirmation, no release notes for users, @you06 ?

**Comment by you06** [comment]
> Just a confirmation, no release notes for users, @you06 ?

Updated, thanks for the notification.

**Comment by you06** [comment]
@sticnarf can you help me merge it again?

**Pull request merged**
