### PR TITLE
*: keep the precision of intermediate decimal result as accurate as possible

### LINKED ISSUE #26348: different result between mysql and tidb
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` sql
CREATE TABLE `t` (
`last_zccural_date` varchar(8) DEFAULT NULL,
`last_run_date` varchar(8) DEFAULT NULL,
`accr_amt` decimal(20,2) DEFAULT NULL,
`real_rate` decimal(15,8) DEFAULT NULL
);
insert into t values(20210606, 20210606, 50000.00, 5.04600000);
select last_zccural_date * accr_amt *(real_rate/36000) from t;
```

### 2. What did you expect to see? (Required)
``` sql
mysql> select last_zccural_date * accr_amt *(real_rate/36000) from t;
+-------------------------------------------------+
| last_zccural_date * accr_amt *(real_rate/36000) |
+-------------------------------------------------+
|                              141642663.71666598 |
+-------------------------------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
``` sql
tidb> select last_zccural_date * accr_amt *(real_rate/36000) from t;
+-------------------------------------------------+
| last_zccural_date * accr_amt *(real_rate/36000) |
+-------------------------------------------------+
|                               141642664.0535101 |
+-------------------------------------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

014005ab68b5c9a28795d13c1ca685cf46a3be7e

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve?

Issue Number: close #26348  

Problem Summary:

### What is changed and how it works?

What's Changed:
If the div expression is not the root node of an expression tree, we need to keep the precision of the intermediate result as accurate as possible.

How it Works:

### Check List 

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- Fix the problem that the div function may lose precision when it's a subpart of the whole expression.

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
The failed common-test and integration-common-test has nothing to do with this commit

**Review by qw4990 — APPROVED** [review]

**Review by ichn-hu — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Pull request merged**
