### PR TITLE
config: Change tidb_opt_projection_push_down default value to true | tidb-test=pr/2359

### PR DESCRIPTION
**Pull request by yibin87**
### What problem does this PR solve?

Issue Number: ref #51876 

Problem Summary:

Described in #51876 

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

benchbot test performance, no significant performance differences:
2irsq7zFnl

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Change the default value of tidb_opt_projection_push_down to true so that TIDB can choose to push down projections to TIKV to reduce network bandwith usage. 
```

### CODE REVIEW

**Comment by windtalker** [comment]
Why need to disable projection pushdown in some ut?

**Comment by yibin87** [comment]
> Why need to disable projection pushdown in some ut?

Not sure the actual meaning of these ut, disable it to keep it unchanged and pass.

**Review by winoros — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM

**Review by D3Hunter — APPROVED** [review]

**Pull request merged**
