### PR TITLE
executor, statistics: remove NULL value from column histogram created by fast analyze

### LINKED ISSUE #24171: histogram buckets has NULL value crated by fast analyze
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t (a int);
set @@tidb_enable_fast_analyze=1;
insert into t values(1), (2), (3), (NULL);
analyze table t with 0 topn, 2 buckets;
select * from mysql.stats_buckets;
```

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
```
+----------+----------+---------+-----------+-------+---------+-------------+-------------+-----+
| table_id | is_index | hist_id | bucket_id | count | repeats | upper_bound | lower_bound | ndv |
+----------+----------+---------+-----------+-------+---------+-------------+-------------+-----+
|       53 |        0 |       1 |         0 |     3 |       1 | 2           |             |   0 |
|       53 |        0 |       1 |         1 |     1 |       1 | 3           | 3           |   0 |
+----------+----------+---------+-----------+-------+---------+-------------+-------------+-----+
2 rows in set (0.002 sec)

```

### 3. What did you see instead (Required)
The `lower_bound` is not `NULL`

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
| tidb_version()                                                                                                                                                                                                                                                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-2663-gf23e34965
Edition: Community
Git Commit Hash: f23e349659582fc39cace59476a5899d6e34fdbb
Git Branch: HEAD
UTC Build Time: 2021-04-20 08:45:18
GoVersion: go1.16.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

### PR DESCRIPTION
**Pull request by rebelice**
### What problem does this PR solve?

Issue Number: close #24171 

Problem Summary:

We assume that there is no `NULL` value in `column hist`, but `fast analyze` breaks this assumption.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

Remove the `NULL` value before we build the column histogram.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- remove NULL value from column histogram created by fast analyze

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by time-and-fate — APPROVED** [review]
/lgtm

**Pull request merged**
