### PR TITLE
telemetry: resource control telemetry

### PR DESCRIPTION
**Pull request by BornChanger**
### What problem does this PR solve?

Issue Number: Ref #38825 

Problem Summary:

### What is changed and how it works?

1. Provide telemetry support for resource control
2. Fix a bug

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by BornChanger** [comment]
cc @AstroProfundis @lucklove Please take a look at this telemetry pr.

**Review by lucklove — APPROVED** [review]

**Pull request merged**
