### PR TITLE
executor, session: refine insert unsigned bigint autoIncreID (#8181)

### PR DESCRIPTION
**Pull request by XuHuaiyu**
cherry-pick #8181

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
/run-all-tests tidb-test=pr/738 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
/run-all-tests tidb-test=pr/738 tikv=release-2.1 pd=release-2.1

**Comment by XuHuaiyu** [comment]
/run-all-tests tidb-test=pr/738 tikv=release-2.1 pd=release-2.1

**Pull request merged**
