### PR TITLE
domain: initResourceGroupsController after fetching ServerID

### LINKED ISSUE #46200: Resource control can't be limited under the ru set
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
| rg3     | 10000      | MEDIUM   | NO        | NULL        | NULL       |
sysbench read write
```
image

### 4. What is your TiDB version? (Required)

Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: cf8a74bb239d070c2857419ceeebd0f6cb05f37b
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time: 2023-08-16 11:45:27
GoVersion: go1.21.0
Race Enabled: false
Check Table Before Drop: false
Store: unistore

### PR DESCRIPTION
**Pull request by CabinfeverB**
### What problem does this PR solve?

Issue Number: close #46200

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by CabinfeverB** [comment]
cc @glorv @nolouch

**Review by glorv — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
