### PR TITLE
 dumpling: fix unstable test TestDumpBlock

### LINKED ISSUE #32008: Unstable test `dump_test.TestDumpBlock`
```
=== RUN   TestDumpBlock
    dump_test.go:62:
        	Error Trace:	dump_test.go:62
        	Error:      	Target error should be in err chain:
        	            	expected: "canceling query due to user request"
        	            	in chain: "context canceled"
        	Test:       	TestDumpBlock
--- FAIL: TestDumpBlock (0.00s)
=== RUN   TestDumpBlock
    dump_test.go:62:
        	Error Trace:	dump_test.go:62
        	Error:      	Target error should be in err chain:
        	            	expected: "canceling query due to user request"
        	            	in chain: "context canceled"
        	Test:       	TestDumpBlock
--- FAIL: TestDumpBlock (0.00s)
=== RUN   TestDumpBlock
```

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve?

Issue Number: close #32008

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Ehco1996** [comment]
all tests passed could you please take another look for this pr ? thanks 🧡🧡🧡
/cc @wjhuang2016  @hawkingrei  @okJiang

**Review by hawkingrei — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
