### PR TITLE
expression, types: export "evalTp" to "EvalType" and move it to package "types"

### PR DESCRIPTION
**Pull request by zz-jason**
main change:

1. `s/evalTp/EvalType/`
2. move `EvalType` to package **types**
2. `s/tpInt/ETInt/` and so does the other `tpXXX`s
3. remove function `fieldTp2EvalTp()`
4. add function `EvalType()` to struct `FieldType`

### CODE REVIEW

**Comment by zz-jason** [comment]
@XuHuaiyu @coocood PTAL

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
