### PR TITLE
Changed FTWRL to produce error

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve? 

Many programs use `FLUSH TABLES WITH READ LOCK` (ftwrl) to create a synchronization point between multi-threaded programs.  For example, mydumper works like this:

Main thread: `FLUSH TABLES WITH READ LOCK;`
Worker threads: `START TRANSACTION WITH CONSISTENT SNAPSHOT;`
Main thread: `UNLOCK TABLES;`

Because FTWRL is parsed but ignored, these programs are not getting a synchronization point, leading to inconsistent backups.  The alternatives for these programs are:

-  Use single threaded execution (start transaction is sufficient to provide repeatable-read consistency)
- Use a tidb_snapshot read. Our fork of mydumper can do this (although it doesn't by default).  I have a PR for [mydumper upstream](https://github.com/maxbube/mydumper/pull/155).

### What is changed and how it works?

This changes FTWRL to be an error, similar to `KILL x` (not supported, but judged not safe to parse but ignore).  An alternative implimentation could be to raise a warning, but error is my first preference.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to update the documentation
 - Need to be included in the release note

**Important!** This change is not backwards compatible.  It will cause an error in existing mydumpers (both upstream and our fork).  However, mydumper also checks for warnings: so lessening the severity will not help.

Assuming the mydumper PR is pulled, we should document that TiDB requires a version of mydumper of `X.Y.Z` or greater.

### CODE REVIEW

**Comment by shenli** [comment]
@morgo This change may lead to a compatible issue. We need to consider this carefully.

**Comment by coocood** [comment]
@morgo 
Do we need to return the error if `WITH READ LOCK` is not specified?

**Comment by morgo** [comment]
@coocood No.  You are correct, it is safe for `FLUSH TABLES` (no additions) to be a no-op.

**Comment by shenli** [comment]
@morgo Should we merge this PR after the PR for mydumper upstream merged?

**Comment by shenli** [comment]
LGTM

**Comment by morgo** [comment]
@shenli Yes, that would be my preference.  The release notes can say minimum mydumper version required.

**Comment by zhexuany** [comment]
It seems that this PR is blocked by https://github.com/maxbube/mydumper/pull/155/files
but LGTM

**Comment by morgo** [comment]
@winoros I have a backup plan, which is for these two PRs to merge:
https://github.com/pingcap/mydumper/pull/4
https://github.com/pingcap/docs/pull/644

**Comment by morgo** [comment]
This PR is now unblocked and Ready for Merge.

**Pull request merged**
