### PR TITLE
planner: push StreamAgg down to IndexLookup when no group-by column

### LINKED ISSUE #36769: planner: push StreamAgg down to IndexLookup when no group-by column
## Enhancement
When there is no group-by column, the planner should push `StreamAgg` down to `IndexLookup` and generate a plan like:
```
StreamAgg
    IndexLookUp
        IndexScan
        StreamAgg
            TableScan
```
Currently, `StreamAgg` cannot be pushed down if there is no `stream_agg()` hint, so we can only get a plan like:
```
StreamAgg
    IndexLookUp
        IndexScan
        TableScan
```
wivtcusFNZ

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #36769

Problem Summary: planner: push StreamAgg down to IndexLookup when no group-by column

### What is changed and how it works?

planner: push StreamAgg down to IndexLookup when no group-by column

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by time-and-fate — APPROVED** [review]

**Comment by hawkingrei** [comment]
@qw4990 Please fix it.

```
planner/core/plan_cost_test.go:969:18: assignment mismatch: 2 variables but testkit.CreateMockStore returns 1 value
```

**Pull request closed without merging**
