### PR TITLE
domain: move UpdateStatsHealthyMetrics into updateStatsWorker

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: ref #54552

Problem Summary:

### What changed and how does it work?

move UpdateStatsHealthyMetrics into updateStatsWorker. This way, it will not compete for resources with sync statistic. because we find that sync stats will pause for too much time to sync stats as soon as possible. it will lead to miss some stats to sync.
 
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by AilinKid — APPROVED** [review]

**Comment by lance6716** [comment]
> move UpdateStatsHealthyMetrics into updateStatsWorker. This way, it will not compete for resources with sync statistic

Can you explain more about this change?

**Comment by hawkingrei** [comment]
> > move UpdateStatsHealthyMetrics into updateStatsWorker. This way, it will not compete for resources with sync statistic
> 
> Can you explain more about this change?

I updated.

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
