### PR TITLE
ddl: fix the `modify column` operation on the `bit` column

### LINKED ISSUE #11800: alter table failed with bit column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
create table t (i int, b bit);
alter table t modify b bit first;

2. What did you expect to see?
sql runs successfully.

3. What did you see instead?
SQL Error [1105] [HY000]: unsupported modify column unsigned false not match origin true

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.16
Git Commit Hash: 86ad1a96c3a626dd69d8769cd5f8f7196c0c7a56
Git Branch: HEAD
UTC Build Time: 2019-08-15 10:21:49
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve? 
Before this PR：
```
create table t (i int, b bit);
alter table t modify b bit;
ERROR 1105 (HY000): unsupported modify column unsigned false not match origin true
```
Fix #11800 

### What is changed and how it works?
Add the `UnsignedFlag` to `bit` like `add column` when doing `modify column`.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

Release note

 - Fix the `modify column` operation on the `bit` column.

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by tohghua** [comment]
> cherry pick to release-2.1 failed

What does this mean? Will the fix be merged to 2.1?

**Pull request merged**
