### PR TITLE
binlog-dev branch: add vendor for pump client

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
### What problem does this PR solve? 
add vendor for pump client

### What is changed and how it works?
add "github.com/pingcap/tidb-tools/pkg/etcd" in ignored config in Gopkg.toml
run `dep ensure -add github.com/pingcap/tidb-tools/tidb-binlog/pump_client@ a47b49eaff863a5ec3700944365c8ae50f7c354b`
 sh ./hack/clean-vendor.sh

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
@coocood @GregoryIan PTAL

**Comment by shenli** [comment]
I see the Etcd lib in the vendor is updated. @disksing PTAL

**Comment by WangXiangUSTC** [comment]
OK，I will remove useless lib

**Comment by WangXiangUSTC** [comment]
@shenli @coocood PTAL again

**Comment by coocood** [comment]
LGTM

**Pull request merged**
