### PR TITLE
*: make sessionctx.Context depend on contexts in planner and expression

### LINKED ISSUE #51149: make `sessionctx.Context` depend on contexts in planner and expression
see #51150

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #51149

### What changed and how does it work?

In this PR, we make the `sessionctx.Context` depends on the contexts in planner and expression:

```go
// in pkg/sessionctx/context.go
type Context interface {
        ...
	exprctx.EvalContext
	exprctx.BuildContext
	planctx.PlanContext
        ...
}
```

The benefit is that we can move some methods defined in `sessionctx.Context` to their separate contexts. It is more clear to identify by scene the method is used.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Review by lance6716 — COMMENTED** [review]
/approve 

for lightning part

**Pull request merged**
