### PR TITLE
ddl, executor: add error for functional index cannot refer to an auto-increment column (#20336)

### LINKED ISSUE #20317: Refine the error message for the expression index on auto-increment column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql> CREATE TABLE t1 (t1_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE INDEX idx1 ON t1 ((t1_id + t1_id));
ERROR 3109 (HY000): Generated column '' cannot refer to auto-increment column.
```

### 2. What did you expect to see? (Required)

Expression index 'idx1' cannot refer to an auto-increment column.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20336 to release-4.0

---

Signed-off-by: lihaowei <haoweili35@gmail.com>

### What problem does this PR solve?

Issue Number: close #20317

### Release note
- No release note

### CODE REVIEW

**Review by zz-jason — APPROVED** [review]
LGTM

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
The error message should be `expression index`, not `functional index`.

**Comment by zz-jason** [comment]
> The error message should be `expression index`, not `functional index`.

@wjhuang2016 PTAL this comment: https://github.com/pingcap/tidb/pull/20336#discussion_r499225295

**Comment by wjhuang2016** [comment]
> > The error message should be `expression index`, not `functional index`.
> 
> @wjhuang2016 PTAL this comment: [#20336 (comment)](https://github.com/pingcap/tidb/pull/20336#discussion_r499225295)

Because we have used `expression index` in our document, config file and so on, `expression index` is more appropriate than `functional index`.

**Review by zz-jason — APPROVED** [review]
LGTM

**Pull request merged**
