### PR TITLE
linter: enable early return

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/40786

Problem Summary:

### What is changed and how it works?

In Go it is idiomatic to minimize nesting statements, a typical example is to avoid if-then-else constructions. This rule spots constructions like

```
if cond {
  // do something
} else {
  // do other thing
  return ...
}
```

where the if condition may be inverted in order to reduce nesting:

```
if !cond {
  // do other thing
  return ...
}
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
/hold

please wait the rseult of BR/lightning CI

**Review by xhebox — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
