### PR TITLE
session, variable: invert builtinGlobalVariable from allow to deny list

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Problem Summary:

Currently the `builtinGlobalVariable` feature is a source of bugs because even though a sysvar is added, it is not automatically copied to new sessions. This behavior is also not MySQL compatible, where it is expected a sysvar of session scope should be copied on session init.

Fixing the full incompatibility is a little bit more complicated, but this takes the initial step of inverting from an allow list to a deny list, but is otherwise functionally compatible.

This also includes the fix from https://github.com/pingcap/tidb/pull/24835 should this PR supercede it.

### What is changed and how it works?

What's Changed:

A variable on the `SysVar` struct can now be set to `skipInit`. By default it will not skip for session-scope variables, which is why it is now a deny list.

However, it will always skip for noop variables, which helps keep the memory footprint of new sessions slightly lower.

### Related changes

- None
- There will need to be followup PRs to handle the specific `skipInit` variables; some probably don't need to be on this list. The global-only variables that are hard-coded into the `SkipInit()` function will also need removing.

### Check List 

Tests 

- Unit test (covered by existing tests)

Side effects

- All new sessionscoped sysvars will by default load into the session (this is a good thing)

### Release note 

- No release note

### CODE REVIEW

**Comment by morgo** [comment]
This can be tested with the following go code:
```
// test.go

package main

import (
	"fmt"

	"github.com/pingcap/tidb/sessionctx/variable"
)

var builtinGlobalVariable = []string{
	variable.AutoCommit,
	variable.SQLModeVar,
	variable.MaxAllowedPacket,
	variable.TimeZone,
	variable.BlockEncryptionMode,
	variable.WaitTimeout,
	variable.InteractiveTimeout,
	variable.MaxPreparedStmtCount,
	variable.InitConnect,
	variable.TxnIsolation,
	variable.TxReadOnly,
	variable.TransactionIsolation,
	variable.TransactionReadOnly,
	variable.NetBufferLength,
	variable.QueryCacheType,
	variable.QueryCacheSize,
	variable.CharacterSetServer,
	variable.AutoIncrementIncrement,
	variable.AutoIncrementOffset,
	variable.CollationServer,
	variable.NetWriteTimeout,
	variable.MaxExecutionTime,
	variable.InnodbLockWaitTimeout,
	variable.WindowingUseHighPrecision,
	variable.SQLSelectLimit,
	variable.DefaultWeekFormat,

	/* TiDB specific global variables: */
	variable.TiDBSkipASCIICheck,
	variable.TiDBSkipUTF8Check,
	variable.TiDBIndexJoinBatchSize,
	variable.TiDBIndexLookupSize,
	variable.TiDBIndexLookupConcurrency,
	variable.TiDBIndexLookupJoinConcurrency,
	variable.TiDBIndexSerialScanConcurrency,
	variable.TiDBHashJoinConcurrency,
	variable.TiDBProjectionConcurrency,
	variable.TiDBHashAggPartialConcurrency,
	variable.TiDBHashAggFinalConcurrency,
	variable.TiDBWindowConcurrency,
	variable.TiDBMergeJoinConcurrency,
	variable.TiDBStreamAggConcurrency,
	variable.TiDBExecutorConcurrency,
	variable.TiDBBackoffLockFast,
	variable.TiDBBackOffWeight,
	variable.TiDBConstraintCheckInPlace,
	variable.TiDBDDLReorgWorkerCount,
	variable.TiDBDDLReorgBatchSize,
	variable.TiDBDDLErrorCountLimit,
	variable.TiDBOptInSubqToJoinAndAgg,
	variable.TiDBOptPreferRangeScan,
	variable.TiDBOptCorrelationThreshold,
	variable.TiDBOptCorrelationExpFactor,
	variable.TiDBOptCPUFactor,
	variable.TiDBOptCopCPUFactor,
	variable.TiDBOptNetworkFactor,
	variable.TiDBOptScanFactor,
	variable.TiDBOptDescScanFactor,
	variable.TiDBOptMemoryFactor,
	variable.TiDBOptDiskFactor,
	variable.TiDBOptConcurrencyFactor,
	variable.TiDBDistSQLScanConcurrency,
	variable.TiDBInitChunkSize,
	variable.TiDBMaxChunkSize,
	variable.TiDBEnableCascadesPlanner,
	variable.TiDBRetryLimit,
	variable.TiDBDisableTxnAutoRetry,
	variable.TiDBEnableWindowFunction,
	variable.TiDBEnableStrictDoubleTypeCheck,
	variable.TiDBEnableTablePartition,
	variable.TiDBEnableVectorizedExpression,
	variable.TiDBEnableFastAnalyze,
	variable.TiDBExpensiveQueryTimeThreshold,
	variable.TiDBEnableNoopFuncs,
	variable.TiDBEnableIndexMerge,
	variable.TiDBTxnMode,
	variable.TiDBAllowBatchCop,
	variable.TiDBAllowMPPExecution,
	variable.TiDBOptBCJ,
	variable.TiDBBCJThresholdSize,
	variable.TiDBBCJThresholdCount,
	variable.TiDBRowFormatVersion,
	variable.TiDBEnableStmtSummary,
	variable.TiDBStmtSummaryInternalQuery,
	variable.TiDBStmtSummaryRefreshInterval,
	variable.TiDBStmtSummaryHistorySize,
	variable.TiDBStmtSummaryMaxStmtCount,
	variable.TiDBStmtSummaryMaxSQLLength,
	variable.TiDBMaxDeltaSchemaCount,
	variable.TiDBCapturePlanBaseline,
	variable.TiDBUsePlanBaselines,
	variable.TiDBEvolvePlanBaselines,
	variable.TiDBEnableExtendedStats,
	variable.TiDBIsolationReadEngines,
	variable.TiDBStoreLimit,
	variable.TiDBAllowAutoRandExplicitInsert,
	variable.TiDBEnableClusteredIndex,
	variable.TiDBPartitionPruneMode,
	variable.TiDBRedactLog,
	variable.TiDBEnableTelemetry,
	variable.TiDBShardAllocateStep,
	variable.TiDBEnableChangeColumnType,
	variable.TiDBEnableChangeMultiSchema,
	variable.TiDBEnablePointGetCache,
	variable.TiDBEnableAlterPlacement,
	variable.TiDBEnableAmendPessimisticTxn,
	variable.TiDBMemQuotaApplyCache,
	variable.TiDBEnableParallelApply,
	variable.TiDBMemoryUsageAlarmRatio,
	variable.TiDBEnableRateLimitAction,
	variable.TiDBEnableAsyncCommit,
	variable.TiDBEnable1PC,
	variable.TiDBGuaranteeLinearizability,
	variable.TiDBAnalyzeVersion,
	variable.TiDBEnableIndexMergeJoin,
	variable.TiDBTrackAggregateMemoryUsage,
	variable.TiDBMultiStatementMode,
	variable.TiDBEnableExchangePartition,
	variable.TiDBAllowFallbackToTiKV,
	variable.TiDBEnableDynamicPrivileges,
	variable.CTEMaxRecursionDepth,
	variable.TiDBDMLBatchSize,
}

func exists(val string, array []string) bool {
	for _, v := range array {
		if val == v {
			return true
		}
	}
	return false
}

func main() {

	for _, sv := range variable.GetSysVars() {

		if exists(sv.Name, builtinGlobalVariable) && sv.SkipInit() {
			fmt.Printf("err: %s is in builtinGlobals but is set to be skipped\n", sv.Name)
		}
		if !exists(sv.Name, builtinGlobalVariable) && !sv.SkipInit() {
			fmt.Printf("err: %s is NOT IN builtinGlobals but is inited\n", sv.Name)
		}
	}
}
```

The output is:

```
err: tx_read_only is in builtinGlobals but is set to be skipped
err: net_write_timeout is in builtinGlobals but is set to be skipped
err: query_cache_size is in builtinGlobals but is set to be skipped
err: net_buffer_length is in builtinGlobals but is set to be skipped
err: query_cache_type is in builtinGlobals but is set to be skipped
err: transaction_read_only is in builtinGlobals but is set to be skipped
err: character_set_server is in builtinGlobals but is set to be skipped
```

The reason for the first 6 items to be skipped here is they are noops (and should have already been skipped). The last item is skipped due to https://github.com/pingcap/tidb/pull/24835

**Review by xiongjiwei — APPROVED** [review]
lgtm

**Pull request merged**
