### PR TITLE
pkg/ddl: add `OWNERS` file

### LINKED ISSUE #47844: add `OWNERS` file for `pkg/ddl` folder

### PR DESCRIPTION
**Pull request by wuhuizuo**
### What problem does this PR solve?

Issue Number: close #47844

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [x] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by wuhuizuo** [comment]
/cc zimulala wjhuang2016 tangenta, ywqzzy Benjamin2037

PTAL

**Comment by wuhuizuo** [comment]
/cc zimulala wjhuang2016 tangenta ywqzzy Benjamin2037

PTAL

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by wuhuizuo** [comment]
/approve cancel

wait for more votes.

**Comment by wuhuizuo** [comment]
/hold

wait for more votes.

**Review by tangenta — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

**Review by ywqzzy — APPROVED** [review]

**Comment by wuhuizuo** [comment]
/unhold

enough LGTM votes

**Pull request merged**
