### PR TITLE
planner: disable mpp_outer_join_fixed_build_side by default (#25240)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25240 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25286
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25286:release-5.1-8bf35daf1a76
```

---

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

Currently, `mpp_outer_join_fixed_build_side` is enabled by default, we want to disable it by default since let the optimizer choose the build side can speed up the query in most cases.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by hanfei1991 — APPROVED** [review]

**Review by fzhedu — APPROVED** [review]
/LGTM

**Pull request merged**
