### PR TITLE
*: refactor table.IterRecord and extract some methods

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

This PR is preparation to support `admin check table` on the clustered indexes.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
- Refactor table.IterRecord to apply kv.Handle.
- Refactor `tipb.TableScan` constructor.
- Rename tiny things and add some comments.

How it Works:

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- No release note

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by tangenta** [comment]
(wake up license/cla)

**Comment by tangenta** [comment]
/run-integration-ddl-test
/run-integration-br-test
```
[FATAL] [session.go:1943] ["check bootstrapped failed"] [error="[tikv:9002]TiKV server timeout"]
```

```
java.nio.channels.ClosedChannelException
```

**Comment by tangenta** [comment]
<details><summary> Data Race </summary>
[2020-06-28T11:06:22.544Z] ==================

[2020-06-28T11:06:22.544Z] WARNING: DATA RACE

[2020-06-28T11:06:22.544Z] Read at 0x00c05f011db0 by goroutine 888:

[2020-06-28T11:06:22.544Z]   runtime.chansend()

[2020-06-28T11:06:22.544Z]       /usr/local/go/src/runtime/chan.go:142 +0x0

[2020-06-28T11:06:22.544Z]   github.com/pingcap/tidb/executor.(*innerMergeWorker).doMergeJoin.func1()

[2020-06-28T11:06:22.544Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:535 +0x344

[2020-06-28T11:06:22.544Z]   github.com/pingcap/tidb/executor.(*innerMergeWorker).doMergeJoin()

[2020-06-28T11:06:22.544Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:591 +0x99f

[2020-06-28T11:06:22.544Z]   github.com/pingcap/tidb/executor.(*innerMergeWorker).handleTask()

[2020-06-28T11:06:22.544Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:500 +0xc33

[2020-06-28T11:06:22.544Z]   github.com/pingcap/tidb/executor.(*innerMergeWorker).run()

[2020-06-28T11:06:22.544Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:420 +0x28d

[2020-06-28T11:06:22.544Z] 

[2020-06-28T11:06:22.544Z] Previous write at 0x00c05f011db0 by goroutine 235:

[2020-06-28T11:06:22.544Z]   runtime.closechan()

[2020-06-28T11:06:22.544Z]       /usr/local/go/src/runtime/chan.go:334 +0x0

[2020-06-28T11:06:22.544Z]   github.com/pingcap/tidb/executor.(*IndexLookUpMergeJoin).Close()

[2020-06-28T11:06:22.544Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:715 +0xef

[2020-06-28T11:06:22.544Z]   github.com/pingcap/tidb/executor.(*baseExecutor).Close()

[2020-06-28T11:06:22.544Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:171 +0xad

[2020-06-28T11:06:22.544Z]   github.com/pingcap/tidb/executor.(*LimitExec).Close()

[2020-06-28T11:06:22.544Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:1058 +0x6c

[2020-06-28T11:06:22.544Z]   github.com/pingcap/tidb/executor.(*baseExecutor).Close()

[2020-06-28T11:06:22.544Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:171 +0xad

[2020-06-28T11:06:22.544Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).Close()

[2020-06-28T11:06:22.544Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:317 +0x24e

[2020-06-28T11:06:22.544Z]   github.com/pingcap/tidb/executor.(*recordSet).Close()

[2020-06-28T11:06:22.544Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:151 +0x59

[2020-06-28T11:06:22.544Z]   github.com/pingcap/tidb/session.(*execStmtResult).Close()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1246 +0x7b

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:209 +0x426

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:47 +0x4a0

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:36 +0x2b1

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:35 +0x27a

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:34 +0x243

[2020-06-28T11:06:22.545Z]   github.com/pingcap/failpoint.parseTerm()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:148 +0x24d

[2020-06-28T11:06:22.545Z]   github.com/pingcap/failpoint.parse()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:125 +0xb4

[2020-06-28T11:06:22.545Z]   github.com/pingcap/failpoint.newTerms()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:97 +0x6a

[2020-06-28T11:06:22.545Z]   github.com/pingcap/failpoint.(*Failpoint).Enable()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoint.go:53 +0x53

[2020-06-28T11:06:22.545Z]   github.com/pingcap/failpoint.(*Failpoints).Enable()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoints.go:104 +0x160

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoints.go:224 +0x79

[2020-06-28T11:06:22.545Z]   runtime.call32()

[2020-06-28T11:06:22.545Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-06-28T11:06:22.545Z]   reflect.Value.Call()

[2020-06-28T11:06:22.545Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-06-28T11:06:22.545Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-06-28T11:06:22.545Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113

[2020-06-28T11:06:22.545Z] 

[2020-06-28T11:06:22.545Z] Goroutine 888 (running) created at:

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor.(*IndexLookUpMergeJoin).startWorkers()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:206 +0x638

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor.(*IndexLookUpMergeJoin).Open()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:182 +0x3ba

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor.(*baseExecutor).Open()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:159 +0xa9

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor.(*LimitExec).Open()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:1046 +0x52

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor.(*baseExecutor).Open()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:159 +0xa9

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).Open()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:84 +0x52

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:328 +0x299

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/session.runStmt()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1201 +0x2c1

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1166 +0xa6f

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:206 +0x91

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:47 +0x4a0

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:36 +0x2b1

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:35 +0x27a

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:34 +0x243

[2020-06-28T11:06:22.545Z]   github.com/pingcap/failpoint.parseTerm()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:148 +0x24d

[2020-06-28T11:06:22.545Z]   github.com/pingcap/failpoint.parse()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:125 +0xb4

[2020-06-28T11:06:22.545Z]   github.com/pingcap/failpoint.newTerms()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:97 +0x6a

[2020-06-28T11:06:22.545Z]   github.com/pingcap/failpoint.(*Failpoint).Enable()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoint.go:53 +0x53

[2020-06-28T11:06:22.545Z]   github.com/pingcap/failpoint.(*Failpoints).Enable()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoints.go:104 +0x160

[2020-06-28T11:06:22.545Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoints.go:224 +0x79

[2020-06-28T11:06:22.545Z]   runtime.call32()

[2020-06-28T11:06:22.545Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-06-28T11:06:22.545Z]   reflect.Value.Call()

[2020-06-28T11:06:22.545Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-06-28T11:06:22.545Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-06-28T11:06:22.545Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-06-28T11:06:22.546Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-06-28T11:06:22.546Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113

[2020-06-28T11:06:22.546Z] 

[2020-06-28T11:06:22.546Z] Goroutine 235 (running) created at:

[2020-06-28T11:06:22.546Z]   github.com/pingcap/check.(*suiteRunner).forkCall()

[2020-06-28T11:06:22.546Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4a3

[2020-06-28T11:06:22.546Z]   github.com/pingcap/check.(*suiteRunner).forkTest()

[2020-06-28T11:06:22.546Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x1b9

[2020-06-28T11:06:22.546Z]   github.com/pingcap/check.(*suiteRunner).doRun()

[2020-06-28T11:06:22.546Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x13a

[2020-06-28T11:06:22.546Z]   github.com/pingcap/check.(*suiteRunner).run()

[2020-06-28T11:06:22.546Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:696 +0x13f

[2020-06-28T11:06:22.546Z]   github.com/pingcap/check.Run()

[2020-06-28T11:06:22.546Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:150 +0x5a

[2020-06-28T11:06:22.546Z]   github.com/pingcap/check.RunAll()

[2020-06-28T11:06:22.546Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:136 +0x906

[2020-06-28T11:06:22.546Z]   github.com/pingcap/check.TestingT()

[2020-06-28T11:06:22.546Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:99 +0x751

[2020-06-28T11:06:22.546Z]   github.com/pingcap/tidb/executor_test.TestT()

[2020-06-28T11:06:22.546Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:96 +0x263

[2020-06-28T11:06:22.546Z]   testing.tRunner()

[2020-06-28T11:06:22.546Z]       /usr/local/go/src/testing/testing.go:909 +0x199

[2020-06-28T11:06:22.546Z] ==================
</details>

**Pull request merged**
