### PR TITLE
expression: fix wrong `Flen` when processing `Decimal` and `Int` (#12312)

### PR DESCRIPTION
**Pull request by qw4990**
cherry-pick for https://github.com/pingcap/tidb/pull/12312

### CODE REVIEW

**Comment by qw4990** [comment]
This PR can  be merged, PTAL @SunRunAway @zz-jason

**Comment by zz-jason** [comment]
@qw4990 Please fix the integration test.

**Comment by qw4990** [comment]
> @qw4990 Please fix the integration test.

This cherry-picking will cause some tricky problems, which seems that we forget to cherry-pick some other PR before this one. 
I will investigate it soon.

**Comment by zz-jason** [comment]
integration test failed, @qw4990 PTAL

**Pull request closed without merging**
