### PR TITLE
lexer: support more syntaxes regarding 'SET Syntax'

### PR DESCRIPTION
**Pull request by qazbnm456**
## What have you changed? (mandatory)

I've changed lines of the code of `lexer.go` in order to support more syntaxes regarding 'SET Syntax', which also fixes https://github.com/pingcap/tidb/issues/6990.

## What are the type of the changes (mandatory)?

Improvement.

## How has this PR been tested (mandatory)?

Manual test.

## Does this PR affect documentation (docs/docs-cn) update? (optional)

No.

## Refer to a related PR or issue link (optional)

https://github.com/pingcap/tidb/issues/6990

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Is there a MySQL document link about it? @qazbnm456

**Comment by qazbnm456** [comment]
@tiancaiamao Yup, here is it: https://dev.mysql.com/doc/refman/5.7/en/user-variables.html.

**Comment by tiancaiamao** [comment]
Are them all equal?
`@`  
`@''` 
`@""` 
```
@``
```

How about this:

```
set @ = 3;
select @'';
```

@qazbnm456

**Comment by tiancaiamao** [comment]
I mean, could this PR handle the case, in TiDB

**Comment by qazbnm456** [comment]
@tiancaiamao I just updated my comment with a picture showing that the case would be handled correctly in `TiDB`.

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
