### PR TITLE
resource_control: add grafana panel for background task control

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: ref #44517 

Problem Summary:

### What is changed and how it works?
The metrics at tikv side is added in https://github.com/tikv/tikv/pull/15195

Screen snapshot:
image
image

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by glorv** [comment]
@nolouch @BornChanger PTAL

**Review by hawkingrei — APPROVED** [review]

**Comment by HuSharp** [comment]
Do we need to check background ru?

**Comment by glorv** [comment]
> Do we need to check background ru?

@HuSharp  what do you mean?

**Comment by HuSharp** [comment]
> > Do we need to check background ru?
> 
> @HuSharp what do you mean?

I mean is the ru of the background consumption displayed in the pre-existing panel? Or create a new panel to show it?

**Comment by glorv** [comment]
> > > Do we need to check background ru?
> > 
> > 
> > @HuSharp what do you mean?
> 
> I mean is the ru of the background consumption displayed in the pre-existing panel? Or create a new panel to show it?

I'm not sure, maybe add a new panel is better

**Review by nolouch — APPROVED** [review]

**Pull request merged**
