### PR TITLE
util/logutil: migrate to testify

### LINKED ISSUE #26154: migrate test-infra to testify for `util/logutil` pkg

### PR DESCRIPTION
**Pull request by ofey404**
### What problem does this PR solve?

Issue Number: close #26154 

### What is changed and how it works?

What's Changed: Removed `pingcap/check` for `utils/logutil`, moved to testify.

### Release note 

- No release note

### CODE REVIEW

**Comment by ofey404** [comment]
There are several places I redefine variable `assert`:

```golang
assert := assert.New(s.T())
```

It will trigger a warning of goland, but the [documentation of testify](https://github.com/stretchr/testify#assert-package) do so. If I redefine the variable to something else like `a`, it may harm the readability(`a.NotNil(xxxxxx)` balabala...).

Which way is more proper?

**Comment by ofey404** [comment]
About the CI failure:
```
[2021-07-18T16:26:25.316Z] ./tools/check/check_testSuite.sh
[2021-07-18T16:26:25.885Z] testHexSuite in ./util/logutil is not enabled
[2021-07-18T16:26:25.885Z] testLogSuite in ./util/logutil is not enabled
```
I checked `./tools/check/check_testSuite.sh`, it may be some naming collision with previous definition of test suites.

Maybe I shouldn't use the same name as the original suite, would `HexTestSuite` and `LogTestSuite` be better?

**Comment by tisonkun** [comment]
Thanks for submitting this PR @ofey404 . You may take a looks at this comment https://github.com/pingcap/tidb/pull/26318#issuecomment-882031331 and we'd better avoid suite usage of testify.

The check script is for gocheck test-infra, you may modify it, work around it, or remove it if necessary. But since suite of testify suffers https://github.com/pingcap/tidb/pull/26082#issuecomment-877230972, you may think of avoiding it.

**Comment by tisonkun** [comment]
Also, `c.Assert` fails fast when assertion fails, it equals to `require` in testify, no `assert`.

**Comment by ofey404** [comment]
There is [a buffer seems never used](https://github.com/pingcap/tidb/blob/8e5dd485e7ad0d1f70eef449d77e73735973f794/util/logutil/log_test.go#L48) in the test, except in `SetUpSuite` and `SetUpTest`. What does it do?

In current commit I just simply remove it, but I'm not quite sure if it's OK to do so.

**Comment by ofey404** [comment]
The test has some goroutine leak, I'm finding out where it is.

**Comment by tisonkun** [comment]
@ofey404 I've created a patch for you https://github.com/tisonkun/tidb/commit/852979f641f5be604382015905f881f01525bb5d that you can make use of.

Today I updated some notes about best practices when migrating tests #26022 , which you may take a look at.

**Comment by tisonkun** [comment]
`"gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun"` is a known un-clean-up goroutine that you can find in `util/testleak/leaktest.go`

**Comment by ofey404** [comment]
> @ofey404 I've created a patch for you [tisonkun@852979f](https://github.com/tisonkun/tidb/commit/852979f641f5be604382015905f881f01525bb5d) that you can make use of.
> 
> Today I updated some notes about best practices when migrating tests #26022 , which you may take a look at.

Thank you very much! I know this is gonna sound really stupid, but how can I make use of this patch? It looks similar to what I've commit...

**Comment by tisonkun** [comment]
@ofey404 thanks for your updates! I provide the patch for I think code express quickly :P

**Review by tisonkun — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Comment by ofey404** [comment]
About the unit test failure, what should I do?

```
[2021-07-20T15:22:47.401Z] ok  	github.com/pingcap/tidb/expression/aggregation	(cached)

[2021-07-20T15:22:47.401Z] FAIL
```

**Comment by tisonkun** [comment]
@ofey404 it seems one of unstable tests that should not be caused by this pull request. You can take a look at https://github.com/pingcap/tidb/issues/25899 to see if it is a known unstable test, and if not, report it. We will retrigger tests and moving the merging phase.

**Comment by tisonkun** [comment]
```
[2021-07-21T01:59:57.394Z] ==================
[2021-07-21T01:59:57.394Z] WARNING: DATA RACE
[2021-07-21T01:59:57.394Z] Write at 0x0000020fb3a0 by goroutine 14:
[2021-07-21T01:59:57.394Z]   google.golang.org/grpc/grpclog.SetLoggerV2()
[2021-07-21T01:59:57.395Z]       /nfs/cache/mod/google.golang.org/grpc@v1.27.1/grpclog/loggerv2.go:68 +0x1fa
[2021-07-21T01:59:57.395Z]   github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.ReplaceGrpcLoggerV2WithVerbosity()
[2021-07-21T01:59:57.395Z]       /nfs/cache/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/logging/zap/grpclogger.go:60 +0x1ea
[2021-07-21T01:59:57.395Z]   github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.ReplaceGrpcLoggerV2()
[2021-07-21T01:59:57.395Z]       /nfs/cache/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/logging/zap/grpclogger.go:51 +0x1dc
[2021-07-21T01:59:57.395Z]   github.com/pingcap/tidb/util/logutil.InitLogger()
[2021-07-21T01:59:57.395Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/logutil/log.go:119 +0x1c5
[2021-07-21T01:59:57.395Z]   github.com/pingcap/tidb/util/logutil.TestZapLoggerWithKeys()
[2021-07-21T01:59:57.395Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/logutil/log_test.go:41 +0x15a
[2021-07-21T01:59:57.395Z]   testing.tRunner()
[2021-07-21T01:59:57.395Z]       /usr/local/go/src/testing/testing.go:1193 +0x202
[2021-07-21T01:59:57.395Z] 
[2021-07-21T01:59:57.395Z] Previous write at 0x0000020fb3a0 by goroutine 15:
[2021-07-21T01:59:57.395Z]   google.golang.org/grpc/grpclog.SetLoggerV2()
[2021-07-21T01:59:57.395Z]       /nfs/cache/mod/google.golang.org/grpc@v1.27.1/grpclog/loggerv2.go:68 +0x1fa
[2021-07-21T01:59:57.395Z]   github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.ReplaceGrpcLoggerV2WithVerbosity()
[2021-07-21T01:59:57.395Z]       /nfs/cache/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/logging/zap/grpclogger.go:60 +0x1ea
[2021-07-21T01:59:57.395Z]   github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.ReplaceGrpcLoggerV2()
[2021-07-21T01:59:57.395Z]       /nfs/cache/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/logging/zap/grpclogger.go:51 +0x1dc
[2021-07-21T01:59:57.395Z]   github.com/pingcap/tidb/util/logutil.InitLogger()
[2021-07-21T01:59:57.395Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/logutil/log.go:119 +0x1c5
[2021-07-21T01:59:57.395Z]   github.com/pingcap/tidb/util/logutil.TestSetLevel()
[2021-07-21T01:59:57.395Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/logutil/log_test.go:90 +0x119
[2021-07-21T01:59:57.395Z]   testing.tRunner()
[2021-07-21T01:59:57.395Z]       /usr/local/go/src/testing/testing.go:1193 +0x202
[2021-07-21T01:59:57.395Z] 
[2021-07-21T01:59:57.395Z] Goroutine 14 (running) created at:
[2021-07-21T01:59:57.395Z]   testing.(*T).Run()
[2021-07-21T01:59:57.395Z]       /usr/local/go/src/testing/testing.go:1238 +0x5d7
[2021-07-21T01:59:57.395Z]   testing.runTests.func1()
[2021-07-21T01:59:57.395Z]       /usr/local/go/src/testing/testing.go:1511 +0xa6
[2021-07-21T01:59:57.395Z]   testing.tRunner()
[2021-07-21T01:59:57.395Z]       /usr/local/go/src/testing/testing.go:1193 +0x202
[2021-07-21T01:59:57.395Z]   testing.runTests()
[2021-07-21T01:59:57.395Z]       /usr/local/go/src/testing/testing.go:1509 +0x612
[2021-07-21T01:59:57.396Z]   testing.(*M).Run()
[2021-07-21T01:59:57.396Z]       /usr/local/go/src/testing/testing.go:1417 +0x3b3
[2021-07-21T01:59:57.396Z]   go.uber.org/goleak.VerifyTestMain()
[2021-07-21T01:59:57.396Z]       /nfs/cache/mod/go.uber.org/goleak@v1.1.10/testmain.go:53 +0x5e
[2021-07-21T01:59:57.396Z]   github.com/pingcap/tidb/util/logutil.TestMain()
[2021-07-21T01:59:57.396Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/logutil/main_test.go:40 +0x9e
[2021-07-21T01:59:57.396Z]   main.main()
[2021-07-21T01:59:57.396Z]       _testmain.go:53 +0x271
[2021-07-21T01:59:57.396Z] 
[2021-07-21T01:59:57.396Z] Goroutine 15 (running) created at:
[2021-07-21T01:59:57.396Z]   testing.(*T).Run()
[2021-07-21T01:59:57.396Z]       /usr/local/go/src/testing/testing.go:1238 +0x5d7
[2021-07-21T01:59:57.396Z]   testing.runTests.func1()
[2021-07-21T01:59:57.396Z]       /usr/local/go/src/testing/testing.go:1511 +0xa6
[2021-07-21T01:59:57.396Z]   testing.tRunner()
[2021-07-21T01:59:57.396Z]       /usr/local/go/src/testing/testing.go:1193 +0x202
[2021-07-21T01:59:57.396Z]   testing.runTests()
[2021-07-21T01:59:57.396Z]       /usr/local/go/src/testing/testing.go:1509 +0x612
[2021-07-21T01:59:57.396Z]   testing.(*M).Run()
[2021-07-21T01:59:57.396Z]       /usr/local/go/src/testing/testing.go:1417 +0x3b3
[2021-07-21T01:59:57.396Z]   go.uber.org/goleak.VerifyTestMain()
[2021-07-21T01:59:57.396Z]       /nfs/cache/mod/go.uber.org/goleak@v1.1.10/testmain.go:53 +0x5e
[2021-07-21T01:59:57.396Z]   github.com/pingcap/tidb/util/logutil.TestMain()
[2021-07-21T01:59:57.396Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/logutil/main_test.go:40 +0x9e
[2021-07-21T01:59:57.396Z]   main.main()
[2021-07-21T01:59:57.396Z]       _testmain.go:53 +0x271
[2021-07-21T01:59:57.396Z] ==================
[2021-07-21T01:59:57.396Z]     testing.go:1092: race detected during execution of test
[2021-07-21T01:59:57.396Z] --- FAIL: TestHex (0.00s)
[2021-07-21T01:59:57.396Z] === CONT  TestZapLoggerWithKeys
[2021-07-21T01:59:57.396Z]     testing.go:1092: race detected during execution of test
[2021-07-21T01:59:57.396Z] --- FAIL: TestZapLoggerWithKeys (0.01s)
[2021-07-21T01:59:57.396Z] FAIL
[2021-07-21T01:59:57.396Z] FAIL	github.com/pingcap/tidb/util/logutil	0.048s
```

@ofey404 it seems data race happen on this PR change set. Please take a look.

**Comment by tisonkun** [comment]
As log in TiDB used as global variable, we may not run in parallel. What do you think @xhebox @tiancaiamao ?

**Comment by xhebox** [comment]
> 
> 
> As log in TiDB used as global variable, we may not run in parallel. What do you think @xhebox @tiancaiamao ?

Fine.`InitLogger` should only be called once anyway, another solution is `sync.Once`.

**Comment by tiancaiamao** [comment]
There are many global variables like that, it's one of the reason some test suite can not run parallel.
I'm OK with here not making it parallel

**Comment by tisonkun** [comment]
@tiancaiamao @xhebox I push a commit to run these tests serially. Please re-trigger `/merge` if it looks good.

@xhebox among tests, it may set `InitLogger` with different config multiple times. May we also evaluate code refactor to enable using code locally while keeping globally access functionality when integrate pingcap/log#16 .

**Comment by xhebox** [comment]
@qw4990 Why cherry pick this PR?

**Comment by tisonkun** [comment]
@xhebox I think it is because we'd like to port https://github.com/pingcap/tidb/pull/27238 to 5.1 and @xuyifangreeneyes & @qw4990 decided that we can bring also all previously PRs.

**Pull request merged**
