### PR TITLE
ddl: fix duplicate entry message report by add index (#21241)

### LINKED ISSUE #13093: should show correct duplicate entry while add index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
tidb:
```
mysql> CREATE TABLE binlog_pk_add_duplicate_uk(id INT PRIMARY KEY, a1 INT);
Query OK, 0 rows affected (0.18 sec)

mysql> INSERT INTO binlog_pk_add_duplicate_uk(id, a1) VALUES(1,1),(2,1);
Query OK, 2 rows affected (0.03 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> ALTER TABLE binlog_pk_add_duplicate_uk ADD UNIQUE INDEX aidx(a1);
ERROR 1062 (23000): Duplicate entry '' for key 'aidx'
mysql>
```

2. What did you expect to see?
mysql:
```
mysql> use test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> CREATE TABLE binlog_pk_add_duplicate_uk(id INT PRIMARY KEY, a1 INT);
Query OK, 0 rows affected (0.08 sec)

mysql> INSERT INTO binlog_pk_add_duplicate_uk(id, a1) VALUES(1,1),(2,1);
Query OK, 2 rows affected (0.03 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> ALTER TABLE binlog_pk_add_duplicate_uk ADD UNIQUE INDEX aidx(a1);
ERROR 1062 (23000): Duplicate entry '1' for key 'aidx'
```

3. What did you see instead?
Duplicate entry '' for key 'aidx'  

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
Release Version: v4.0.0-alpha-689-g11cd41d2b
Git Commit Hash: 11cd41d2b59f17055bc25dfb281262f0665f4cdf
Git Branch: master
UTC Build Time: 2019-11-03 04:53:59
GoVersion: go version go1.13 darwin/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21241 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #13093

### What is changed and how it works?
Generating the error message based on column values. But do this need to fix another bug, the encode/decode of index key-value is incorrect in `batchCheckUniqueKey`.

### Check List 

Tests 

- Unit test

### Release note 

- Display column values in duplicate entry messages reported by add index operation.

### CODE REVIEW

**Comment by bb7133** [comment]
LGTM

**Comment by bb7133** [comment]
PTAL @tangenta @wjhuang2016

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by kennytm — COMMENTED** [review]
LGTM

**Review by zz-jason — APPROVED** [review]

**Pull request merged**
