### PR TITLE
ddl: check no partitions error when create partition table (#9531)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
cherry-pick #9531,  release 2.1 only support range partition, so only cherry-pick some part code.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by crazycs520** [comment]
@tiancaiamao @winkyao PTAL

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zz-jason** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Comment by tiancaiamao** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zimulala** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Pull request merged**
