### PR TITLE
*: add global variable tidb_schema_version_cache_limit to control infoschema cache size and refine metric

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary: cherry-pick:
- #46558
- #46612

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@zyguan @you06 @ekexium 
PTAL
/cc @hihihuhu @Tema

**Review by zyguan — APPROVED** [review]

**Comment by hihihuhu** [comment]
lgtm, thanks!

**Comment by bb7133** [comment]
Failed test:

```
[2023-09-08T16:55:57.671Z]         	Error Trace:	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/br/pkg/task/restore_test.go:72
[2023-09-08T16:55:57.671Z]         	Error:      	Not equal: 
[2023-09-08T16:55:57.671Z]         	            	expected: 0x11
[2023-09-08T16:55:57.671Z]         	            	actual  : 0x10
[2023-09-08T16:55:57.671Z]         	Test:       	TestAdjustRestoreConfigForStreamRestore
```

**Pull request merged**
