### PR TITLE
*: remove non dry sysvar code

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/33896

Problem Summary:

When setting a special sysvar that requires the domain, there is duplicate code in `executor/set.go` and `domain/sysvar_cache.go`. This is because a `SetGlobal` func can not be directly used, because the domain is not available.

It is possible to workaround this by creating a noop func in variable which is overwritten when the NewDomain is created. This helps simplify the code because by being non-DRY it has a high chance of introducing future bugs if only one location is updated correctly. Because the sysvar cache code runs async, it is also unlikely that these bugs will easily be caught.

### What is changed and how it works?

Function neutral change.

### Check List

Tests 

- [x] Unit test
Covered by existing tests.
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by CbcWestwolf — APPROVED** [review]

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
Good job! I'll revert https://github.com/pingcap/tidb/pull/38227 after this PR merged :beers:

**Review by xhebox — APPROVED** [review]

**Comment by YangKeao** [comment]
@xhebox Could you help to merge this PR?

**Comment by xhebox** [comment]
> @xhebox Could you help to merge this PR?

This PR needs configuration **OWNER** to approve and merge, /cc @bb7133

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
