### PR TITLE
expressions: Support push ROUND function to TiFlash (#19616)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19616 to release-4.0

---

Signed-off-by: leiysky <leiysky@outlook.com>

### What problem does this PR solve?

Problem Summary:
Support `ROUND` function push to `TiFlash`.

### What is changed and how it works?

What's Changed:
- Enable the switcher to push `ROUND` to `TiFlash`

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test (sqllogic)

### Release note 

- Support push ROUND function to TiFlash

### CODE REVIEW

**Comment by leiysky** [comment]
@tangenta @SunRunAway PTAL

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by SunRunAway — APPROVED** [review]
LGTM

**Pull request merged**
