### PR TITLE
planner/core: fix privilege check for grant on table

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Fix https://github.com/pingcap/tidb/issues/9781

### What is changed and how it works?

In this SQL: `GRANT SELECT ON t1 TO 'nonsuper'`,
the database name of visit info should be set to current database.

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @jackysp @morgo

**Comment by morgo** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@tiancaiamao Do we need to cherry-pick this to the release-2.1?

**Comment by tiancaiamao** [comment]
/run-all-tests

Ok,I'll do it @shenli

**Pull request merged**
