### PR TITLE
metrics: add grafana panels for assertion

### PR DESCRIPTION
**Pull request by ekexium**
Signed-off-by: ekexium <ekexium@gmail.com>

### What problem does this PR solve?

Issue Number: ref #26833

Problem Summary:

Add grafana panels for assertion ~and mutation checker~ under the "Transaction" row.
image
image
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by ekexium** [comment]
I'm not sure with the mutation checker metrics. Every call to CheckDataConsistency costs less than 1us, thus monitoring the cost of single checks doesn't make much sense. I chose to monitor the total time consumed in the mutation checker in every second. It gives me a direct intuition whether the mutation checker takes too much time. What do you think? @MyonKeminta @cfzjywxk @sticnarf

**Comment by sticnarf** [comment]
> Every call to CheckDataConsistency costs less than 1us

If a single call to `CheckDataConsistency` is cheap, then I'm worrying about the cost of updating the histogram...

Do we really need to use metrics to monitoring the cpu time used by consistency check? I think sampling is more appropriate...

**Comment by ekexium** [comment]
> the cost of updating the histogram

Any empirical data on this? It can be a counter if we only care about the total duration.

> Do we really need to use metrics to monitoring the cpu time used by consistency check? I think sampling is more appropriate...

I'm open to other ideas. If the check can notably affect latency, then a grafana panel is the most easy way to observe it so users can choose to disable it.
We don't have data for the precise cost of the check. Maybe we could add the metrics and re-run some performance tests. And then we decide whether it's necessary to keep them.

**Comment by sticnarf** [comment]
> Any empirical data on this? It can be a counter if we only care about the total duration.

A binary search to find the bucket and several (usually 4) atomic adds. That's about 100ns, I think.



> If the check can notably affect latency

Is it true according to your tests and benchmarks? If a check costs less than 1us, it's hard to measure the **latency** difference.

**Comment by ekexium** [comment]
> That's about 100ns, I think.

Seems not suitable for such a cheap operation.

> Is it true according to your tests and benchmarks? If a check costs less than 1us, it's hard to measure the latency difference.

Yeah I didn't see any evidence of its bad effects in tests.
But we haven't tested large transactions with a large number of indices. The data "0-1us" comes from small transactions on a small table. Imagine the worst case 1us/row * 10000 rows = 10ms, which is notable I think.

**Comment by sticnarf** [comment]
> But we haven't tested large transactions with a large number of indices. The data "0-1us" comes from small transactions on a small table. Imagine the worst case 1us/row * 10000 rows = 10ms which is notable I think.

Writing 10000 rows may need several seconds. Then, is 10ms also ignorable?🤣

**Comment by ekexium** [comment]
> > But we haven't tested large transactions with a large number of indices. The data "0-1us" comes from small transactions on a small table. Imagine the worst case 1us/row * 10000 rows = 10ms which is notable I think.
> 
> Writing 10000 rows may need several seconds. Then, is 10ms also ignorable?🤣

Definitely. How about updating a single row for 10000 times in a transaction?

**Comment by sticnarf** [comment]
Does the cost of a single check vary greatly? If not, I think it's ok to record the number of assertions only. The cpu usage will be easily estimated.

**Comment by ekexium** [comment]
I'm fine with that. We've tested 100 indices and didn't see obvious difference in cpu usage.

**Review by sticnarf — APPROVED** [review]

**Review by MyonKeminta — APPROVED** [review]

**Pull request merged**
