### PR TITLE
Update the version of parser

### LINKED ISSUE #16700: optimize hint 'ignore_plan_cache' is not captured by a delete statement
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```sql
create table t (a int);
prepare stmt from "delete /*+ ignore_plan_cache()*/ from t where a = 1";
execute stmt;
execute stmt;
select @@last_plan_from_cache;
```

### 2. What did you expect to see?
`0`

### 3. What did you see instead?
`1`

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
```
Release Version: v4.0.0-beta.2-307-g8322e8a2e-dirty
Git Commit Hash: 8322e8a2e92d261e76fff1be263bc8ee7dfc0da4
Git Branch: master-local
UTC Build Time: 2020-04-22 02:14:58
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
```

### PR DESCRIPTION
**Pull request by lawyerphx**
### What problem does this PR solve?

Issue Number: close #16700 

Problem Summary:

### What is changed and how it works?

What's Changed:
`parser` version in `go.mod` and `go.sum` is changed.

How it Works:

### Related changes
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### CODE REVIEW

**Comment by zz-jason** [comment]
@lawyerphx do we need to cherry-pick this bug-fix to release branches?

**Comment by lawyerphx** [comment]
> @lawyerphx do we need to cherry-pick this bug-fix to release branches?

Yes, or `delete` statements' optimize hints won't be handled appropriately.

**Pull request merged**
