### PR TITLE
metrics: make batch client requests more accurate

### LINKED ISSUE #31115: Improve some metrics on Grafana
## Enhancement

- [ ] TiDB client traffic is too complex, make it simply.
- [ ] `DESC` and `EXPLAIN` are used to show columns of a table and explain a SQL which should be separated on metrics.
- [ ] Add index duration and rate are merged into one panel, which makes the user confused.
- [ ] Batch client requests are displayed as a hate map, which is difficult to decide how many to change `max-batch-size`.

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve?

Issue Number: close #31115

Problem Summary:
Because of the mechanism of getting more requests, it is possible for the batch client to get more requests than the max-batch-size, so the original metrics observe position is not very accurate and the upper limit of metrics is too low, only 128.

### What is changed and how it works?
1. metrics upper limit increase to 1024.
2. move the metrics observe after `fetchMorePendingRequests`.
3. update tidb runtime on Grafana to make it easy to know if there're some pending requests.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. start a cluster
2. run some workload and check batch client metrics of tidb runtime on Grafana
image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by jackysp** [comment]
Related to https://github.com/tikv/client-go/pull/397

**Comment by jackysp** [comment]
PTAL @bb7133 , thanks!

**Review by wjhuang2016 — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
