### PR TITLE
types: clip to zero when convert negative decimal to uint

### PR DESCRIPTION
**Pull request by LittleFall**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/41736

Problem Summary:

see https://github.com/pingcap/tidb/issues/41736#issuecomment-1449271739

### Check List

Tests 

- [x] Unit test
- [ ] Integration test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix a compare incorrect issue cause by fault convert 
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM

**Comment by hawkingrei** [comment]
```
        	Error Trace:	/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/linux-sandbox/15059/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/testkit.go:402
        	            				/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/linux-sandbox/15059/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/db_integration_test.go:3322
        	Error:      	Error message not equal:
        	            	expected: "[kv:1062]Duplicate entry '1-2020-01-01 00:00:00' for key 't.t_idx'"
        	            	actual  : "[table:1292]Incorrect timestamp value: '0000-00-00 00:00:00' for column 'exec_expired' at row 1"
        	Test:       	TestDuplicateErrorMessage
```

**Comment by LittleFall** [comment]
local run failed
```
[2023/03/01 14:20:07.809 +08:00] [INFO] [wait_group_wrapper.go:130] ["background process started"] [source=domain] [process=loadSigningCertLoop]
    testkit.go:60: 
        	Error Trace:	/Users/qizhi/p/tidb/ddl/testkit.go:60
        	            				/Users/qizhi/p/tidb/ddl/db_integration_test.go:3278
        	Error:      	Should be true
        	Test:       	TestDuplicateErrorMessage
        	Messages:   	you should add --tags=intest when to test
```

**Comment by hawkingrei** [comment]
> local run in master also failed
> 
> ```
> [2023/03/01 14:20:07.809 +08:00] [INFO] [wait_group_wrapper.go:130] ["background process started"] [source=domain] [process=loadSigningCertLoop]
>     testkit.go:60: 
>         	Error Trace:	/Users/qizhi/p/tidb/ddl/testkit.go:60
>         	            				/Users/qizhi/p/tidb/ddl/db_integration_test.go:3278
>         	Error:      	Should be true
>         	Test:       	TestDuplicateErrorMessage
>         	Messages:   	you should add --tags=intest when to test
> ```
> 
> where to add this flag?

You need to config your ide or gotest to add this flag. You can read this document for details.

 
https://pingcap.github.io/tidb-dev-guide/get-started/setup-an-ide.html

**Comment by LittleFall** [comment]
on this branch local run passed, lol

**Pull request merged**
