### PR TITLE
server: fix missing error metrics for some commands

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
Some commands, e.g. `COM_PREPARE`, do not add record to metrics.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:
Fix it.

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
Prepare many (>65535) variables for one statement by binary protocol, check the metrics. You will get error 1390.
image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
Fix missing error metrics for some commands.
```

### CODE REVIEW

**Comment by morgo** [comment]
We currently report all client errors in `infoschema` [as well](https://docs.pingcap.com/tidb/stable/client-errors-summary-global). The capture is in `writeError(ctx context.Context, e error)`:

https://github.com/pingcap/tidb/blob/5fb3cd42f7ab7460adb2b3196c62bd6c7a903823/server/conn.go#L1361-L1362

If the goal is to report all errors to prometheus, maybe we should unify this somehow?

**Comment by coocood** [comment]
> We currently report all client errors in `infoschema` [as well](https://docs.pingcap.com/tidb/stable/client-errors-summary-global). The capture is in `writeError(ctx context.Context, e error)`:
> 
> https://github.com/pingcap/tidb/blob/5fb3cd42f7ab7460adb2b3196c62bd6c7a903823/server/conn.go#L1361-L1362
> 
> If the goal is to report all errors to prometheus, maybe we should unify this somehow?

This has nothing to do with prometheus metrics.

**Review by coocood — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

**Pull request merged**
