### PR TITLE
planner: cherry-pick sql hint related PRs into release-3.1 (#12192)

### PR DESCRIPTION
**Pull request by eurekaka**
cherry-pick https://github.com/pingcap/tidb/pull/12192 to 3.1.16.

Conflicts:
	planner/core/exhaust_physical_plans.go
	planner/core/logical_plan_test.go
	planner/core/physical_plan_test.go

### CODE REVIEW

**Comment by eurekaka** [comment]
/run-all-tests tidb-test=release-3.1 pd=release-3.1 tikv=release-3.1

**Comment by eurekaka** [comment]
/run-all-tests tidb-test=release-3.0 pd=release-3.0 tikv=release-3.0

**Comment by qrr1995** [comment]
/run-integration-tests tidb-test=release-3.1 pd=release-3.1 tikv=release-3.1

**Comment by qrr1995** [comment]
/run-integration-tests tidb-test=release-3.0 pd=release-3.0 tikv=release-3.0

**Comment by qrr1995** [comment]
/run-integration-compatibility-test tidb-test=release-3.0 pd=release-3.0 tikv=release-3.0

**Comment by eurekaka** [comment]
/run-all-tests tidb-test=release-3.0 pd=release-3.0 tikv=release-3.0

**Comment by coocood** [comment]
LGTM

**Pull request merged**
