### PR TITLE
store/tikv: remove util/rowcodec,tablecodec from store/tikv

### PR DESCRIPTION
**Pull request by aierui**
### What problem does this PR solve?

Remove store/tikv's dependency on util/rowcodec,tablecodec.
Part of #22513 

### What is changed and how it works?

What's Changed:

store/tikv: remove util/rowcodec,tablecodec from store/tikv

### Check List 

Tests 

- Unit test

### Release note 
- No release note

### CODE REVIEW

**Comment by disksing** [comment]
@aierui Thanks a lot. But I think the codec package is too complicated to clone into `store/tikv`. I'll see if there is a better way to estimate dependency. If we are not able to find a better method, we can continue this PR.

**Comment by aierui** [comment]
> @aierui Thanks a lot. But I think the codec package is too complicated to clone into `store/tikv`. I'll see if there is a better way to estimate dependency. If we are not able to find a better method, we can continue this PR.

Yes, I have always felt that such changes are very redundant and not conducive to later maintenance.

**Comment by tisonkun** [comment]
@aierui @disksing is this pull request still valid?

**Comment by disksing** [comment]
It's fixed in other PRs. So we can close it now. Thanks @aierui

**Pull request closed without merging**
