### PR TITLE
types: fix type merge about bit type

### LINKED ISSUE #23832: bit column union Numeric literals select got the wrong results
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t;
create table t(a bit(20), b float, c double, d int);
insert into t values(10, 10, 10, 10), (1, -1, 2, -2), (2, -2, 1, 1), (2, 1.1, 2.1, 10.1);
select a from t union select 10;
```

### 2. What did you expect to see? (Required)
```sql
mysql> drop table if exists t;
Query OK, 0 rows affected (0.04 sec)

mysql> create table t(a bit(20), b float, c double, d int);
Query OK, 0 rows affected (0.07 sec)

mysql> insert into t values(10, 10, 10, 10), (1, -1, 2, -2), (2, -2, 1, 1), (2, 1.1, 2.1, 10.1);
Query OK, 4 rows affected (0.04 sec)
Records: 4  Duplicates: 0  Warnings: 0

mysql> select a from t union select 10;
+------+
| a    |
+------+
|   10 |
|    1 |
|    2 |
+------+
3 rows in set (0.23 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> select a from t union select 10;
+----------+
| a        |
+----------+
| 0x00000A |
| 0x3130   |
| 0x000001 |
| 0x000002 |
+----------+
4 rows in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)
master: 096281ec2f9a0b9a1e
release-4.0: 11a9254bec522
release-5.0: e2740f54b6b2

### PR DESCRIPTION
**Pull request by lzmhhh123**
Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>

### What problem does this PR solve?

Issue Number: close #23832 

### What is changed and how it works?

How it Works: make type merge infer for bit column compatible with MySQL 8.0

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- fix type merge about bit type.

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
- The `field_types_merge_rules` in TiDB is the same as that defined in MySQL 5.7
- Why the result in MySQL 5.7 can also return the same result as 8.0 but with a different type?
``` sql
mysql> select a from t union select 10;
Field   1:  `a`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  binary (63)
Length:     20
Max_length: 2
Decimals:   0
Flags:      BINARY


+------+
| a    |
+------+
| 10   |
| 1    |
| 2    |
+------+
3 rows in set (0.00 sec)
```

**Comment by lzmhhh123** [comment]
IMHO, the result of bit merge int is int looks much more reasonable. It's also the same as MySQL 8.0. We'd better not keep all consistent as MySQL 5.7 brainlessly.

**Review by ichn-hu — APPROVED** [review]

**Pull request merged**
