### PR TITLE
executor: add testcase to cover stale read and prepare stmt

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/31550

Problem Summary:

### What is changed and how it works?

The bug is fixed, this requests add a testcase to cover it.

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Comment by lcwangchao** [comment]
The testcase if fine. But it seems not resolved the issue #31550

**Comment by Yisaer** [comment]
> The testcase if fine. But it seems not resolved the issue #31550

If the sql result is ok, I think the origin issue can't be thought as a bug as users won't face it.

**Pull request merged**
