### PR TITLE
statistics: fix bad sql with many interrupted analyze jobs

### LINKED ISSUE #49724: return error when to clean analyze jobs with many interrupted analyze jobs.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

with many interrupted analyze jobs.

image

### 2. What did you expect to see? (Required)

success
### 3. What did you see instead (Required)

```
[2023/12/22 15:05:19.646 +08:00] [WARN] [domain.go:2538] ["cleanup analyze jobs on current instance failed"] [error="[tikv:1292]Truncated incorrect INTEGER value: '65819,65820,65821,65822,65823,65824,120167,240431,300255,360251,360252,360253,360254,510321,510322,510323,510324,510325,510326,570320,690137,690138,690139,690140,690141,690142,780209,780210,780211,780212,780213,780214,840321,840322,840323,840324,840325,840326,990319'"]
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #49724

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by D3Hunter — APPROVED** [review]

**Comment by hi-rustin** [comment]
Tested locally:
1. Start a cluster with 3 TiDB nodes.
2. Patch the TiDB binary with the current PR.
3. Use `go-tpc` to insert some data: `go-tpc tpcc --db test --warehouses 500 -T 50 --host xxxx --port 4000 prepare`
4. Check the order table count:
```sql
MySQL [test]> select count(*) from orders;
+----------+
| count(*) |
+----------+
| 15000000 |
+----------+
1 row in set (0.79 sec)
```
5. Check if the current node is owner:
```sql
MySQL [test]> select TIDB_IS_DDL_OWNER();
+---------------------+
| TIDB_IS_DDL_OWNER() |
+---------------------+
|                   1 |
+---------------------+
1 row in set (0.00 sec)
```
6. analyze table `stcok` and kill the owner(kill -9) at the same time (10.2.7.xxx).
7. Check the analysis jobs: `select * from mysql.analyze_jobs;`
```sql
| 90003 | 2023-12-06 15:21:55 | test         | stock      |                | analyze table all columns with 256 buckets, 500 topn, 0.0021646779966700168 samplerate      |              0 | 2023-12-06 15:21:55 | NULL                | running  | NULL                                       | 10.2.7.xxx:4000 | 2373976066 |
```
8. Wait for 20 minutes, it will be updated by the background worker.
9. check it again:
```sql
MySQL [(none)]> select * from mysql.analyze_jobs where id = '90003';
+-------+---------------------+--------------+------------+----------------+----------------------------------------------------------------------------------------+----------------+---------------------+----------+--------+--------------------------------------------------+-----------------+------------+
| id    | update_time         | table_schema | table_name | partition_name | job_info                                                                               | processed_rows | start_time          | end_time | state  | fail_reason                                      | instance        | process_id |
+-------+---------------------+--------------+------------+----------------+----------------------------------------------------------------------------------------+----------------+---------------------+----------+--------+--------------------------------------------------+-----------------+------------+
| 90003 | 2023-12-06 17:20:07 | test         | stock      |                | analyze table all columns with 256 buckets, 500 topn, 0.0021646779966700168 samplerate |              0 | 2023-12-06 15:21:55 | NULL     | failed | TiDB Server is down when running the analyze job | 10.2.7.xxxx:4000 |       NULL |
+-------+---------------------+--------------+------------+----------------+----------------------------------------------------------------------------------------+----------------+---------------------+----------+--------+--------------------------------------------------+-----------------+------------+
```

**Review by hi-rustin — APPROVED** [review]
Looks good to me. Thanks! 👍

**Comment by hi-rustin** [comment]
/hold 

I want to test it again.

**Comment by hi-rustin** [comment]
Tested with two records:
```log
tidb.log:[2023/12/22 19:29:55.903 +08:00] [INFO] [autoanalyze.go:173] ["clean up the potentially corrupted analyze jobs from current instance"] [category=stats] [jobIDs="[300001,330001]"]
```

```sql
| 300001 | 2023-12-22 19:29:55 | test         | stock      |                | analyze table all columns with 256 buckets, 500 topn, 0.0022 samplerate |              0 | 2023-12-22 19:19:04 | NULL                | failed   | TiDB Server is down when running the analyze job | 10.2.6.253:4000 |       NULL |
| 330001 | 2023-12-22 19:29:55 | test         | stock      |                | analyze table all columns with 256 buckets, 500 topn, 0.0022 samplerate |              0 | 2023-12-22 19:19:38 | NULL                | failed   | TiDB Server is down when running the analyze job | 10.2.6.253:4000 |       NULL |
+--------+---------------------+--------------+------------+----------------+-------------------------------------------------------------------------+----------------+---------------------+---------------------+----------+--------------------------------------------------+-----------------+------------+
9 rows in set (0.00 sec)
```

**Pull request merged**
