### PR TITLE
planner: migrate indexmerge_test to testify

### LINKED ISSUE #28404: migrate test-infra to testify for `planner/core/indexmerge_test.go`

### PR DESCRIPTION
**Pull request by cr0rc**
### What problem does this PR solve?

Issue Number: close #28404

### Release note
```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM.

/cc @rebelice @time-and-fate

**Review by time-and-fate — APPROVED** [review]

**Comment by tisonkun** [comment]
cc @time-and-fate @rebelice could you help on merging this PR?

**Review by disksing — APPROVED** [review]

**Pull request merged**
