### PR TITLE
executor,planner: fix 'show master status' output

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

`show master status` is wrong:
```
mysql> show master status;
+-------------+----------+--------------+------------------+-------------------+
| File        | UniqueID | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+-------------+----------+--------------+------------------+-------------------+
| tidb-binlog |        0 |              |                  |                   |
+-------------+----------+--------------+------------------+-------------------+
1 row in set (0.01 sec)
```

### What is changed and how it works?

https://github.com/pingcap/tidb/pull/7218 modify the schema "Position" to "UniqueID" by mistake
https://github.com/pingcap/tidb/pull/8260 makes the result timestamp to be "0"

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8737)

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @winoros @jackysp

**Comment by shenli** [comment]
LGTM
/cc @WangXiangUSTC

**Pull request merged**
