### PR TITLE
sessionctx: update innodb variables to 8.0

### LINKED ISSUE #9142: MySQL 8.0: Remove InnoDB variables no longer used
## Feature Request

**Is your feature request related to a problem? Please describe:**

MySQL 8.0 removes a number of InnoDB variables.  It should be safe to remove them from TiDB.

**Describe the feature you'd like:**
```
Innodb_available_undo_logs
ignore-builtin-innodb
innodb_checksums
innodb_disable_resize_buffer_pool_debug
innodb_file_format
innodb_file_format_check
innodb_file_format_max
innodb_large_prefix
innodb_locks_unsafe_for_binlog
innodb_stats_sample_pages
innodb_support_xa
innodb_undo_logs
```
**Describe alternatives you've considered:**

Should be safe to remove.  If it is proven they are useful, they could be added to https://github.com/pingcap/tidb/issues/9141

**Teachability, Documentation, Adoption, Migration Strategy:**

Should be understandable, since it is MySQL compatible.

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve? 

Fixes #9142

### What is changed and how it works?

- Remove innodb variables that no longer exist in 8.0, and are safe to remove.
- Update some obvious defaults to be the same as 8.0.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Code changes

 - Has exported variable/fields change

Side effects

 - Breaking backward compatibility (in likely meaningless ways.  I have a proposal for restoring compatibility in https://github.com/pingcap/tidb/issues/9141 , but do not plan on using it for this).

Related changes

 - Need to be included in the release note

### CODE REVIEW

**Comment by morgo** [comment]
@shenli @jackysp PTAL

**Comment by jackysp** [comment]
I added the DNM tag. I think it is better to merge it after https://github.com/pingcap/tidb/issues/9141 is finished.

**Comment by zz-jason** [comment]
@morgo @jackysp friendly ping, any update?

**Comment by zz-jason** [comment]
I added a `status/ReqChange/` label since it's conflicted with the master branch.

**Comment by zz-jason** [comment]
I'm going to close this PR due to outdated, fell free to reopen it if you are going to process it again in the future.

**Pull request closed without merging**
