### PR TITLE
*: upgrade client-go to fix pessimistic write-conflict

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/25964

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

Upgrade client-go.

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- Fix the issue that committing pessimistic transactions may report write-conflict errors.

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
/lgtm

**Comment by youjiali1995** [comment]
```
[2021-07-06T05:45:28.230Z] ----------------------------------------------------------------------
[2021-07-06T05:45:28.230Z] PANIC: db_test.go:3488: testDBSuite2.TestAddNotNullColumn
[2021-07-06T05:45:28.230Z] 
[2021-07-06T05:45:28.230Z] ... Panic: runtime error: index out of range [2] with length 2 (PC=0x10FC5D8)
[2021-07-06T05:45:28.230Z] 
[2021-07-06T05:45:28.230Z] /usr/local/go/src/runtime/panic.go:965
[2021-07-06T05:45:28.230Z]   in gopanic
[2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:332
[2021-07-06T05:45:28.230Z]   in ExecStmt.Exec.func1
[2021-07-06T05:45:28.230Z] /usr/local/go/src/runtime/panic.go:971
[2021-07-06T05:45:28.230Z]   in gopanic
[2021-07-06T05:45:28.230Z] /usr/local/go/src/runtime/panic.go:88
[2021-07-06T05:45:28.230Z]   in goPanicIndex
[2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4610
[2021-07-06T05:45:28.230Z]   in CheckUpdateList
[2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/builder.go:1905
[2021-07-06T05:45:28.230Z]   in executorBuilder.buildUpdate
[2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/builder.go:199
[2021-07-06T05:45:28.230Z]   in executorBuilder.build
[2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:799
[2021-07-06T05:45:28.230Z]   in ExecStmt.buildExecutor
[2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:380
[2021-07-06T05:45:28.230Z]   in ExecStmt.Exec
[2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1636
[2021-07-06T05:45:28.230Z]   in runStmt
[2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1531
[2021-07-06T05:45:28.230Z]   in session.ExecuteStmt
[2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:170
[2021-07-06T05:45:28.230Z]   in TestKit.Exec
[2021-07-06T05:45:28.230Z] db_test.go:3507
[2021-07-06T05:45:28.230Z]   in testDBSuite2.TestAddNotNullColumn
[2021-07-06T05:45:28.230Z] /usr/local/go/src/reflect/value.go:337
[2021-07-06T05:45:28.230Z]   in Value.Call
[2021-07-06T05:45:28.230Z] /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850
[2021-07-06T05:45:28.230Z]   in suiteRunner.forkTest.func1
[2021-07-06T05:45:28.230Z] /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739
[2021-07-06T05:45:28.230Z]   in suiteRunner.forkCall.func1
[2021-07-06T05:45:28.230Z] /usr/local/go/src/runtime/asm_amd64.s:1371
[2021-07-06T05:45:28.230Z]   in goexit
```

**Comment by sticnarf** [comment]
> ```
> [2021-07-06T05:45:28.230Z] ----------------------------------------------------------------------
> [2021-07-06T05:45:28.230Z] PANIC: db_test.go:3488: testDBSuite2.TestAddNotNullColumn
> [2021-07-06T05:45:28.230Z] 
> [2021-07-06T05:45:28.230Z] ... Panic: runtime error: index out of range [2] with length 2 (PC=0x10FC5D8)
> [2021-07-06T05:45:28.230Z] 
> [2021-07-06T05:45:28.230Z] /usr/local/go/src/runtime/panic.go:965
> [2021-07-06T05:45:28.230Z]   in gopanic
> [2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:332
> [2021-07-06T05:45:28.230Z]   in ExecStmt.Exec.func1
> [2021-07-06T05:45:28.230Z] /usr/local/go/src/runtime/panic.go:971
> [2021-07-06T05:45:28.230Z]   in gopanic
> [2021-07-06T05:45:28.230Z] /usr/local/go/src/runtime/panic.go:88
> [2021-07-06T05:45:28.230Z]   in goPanicIndex
> [2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4610
> [2021-07-06T05:45:28.230Z]   in CheckUpdateList
> [2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/builder.go:1905
> [2021-07-06T05:45:28.230Z]   in executorBuilder.buildUpdate
> [2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/builder.go:199
> [2021-07-06T05:45:28.230Z]   in executorBuilder.build
> [2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:799
> [2021-07-06T05:45:28.230Z]   in ExecStmt.buildExecutor
> [2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:380
> [2021-07-06T05:45:28.230Z]   in ExecStmt.Exec
> [2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1636
> [2021-07-06T05:45:28.230Z]   in runStmt
> [2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1531
> [2021-07-06T05:45:28.230Z]   in session.ExecuteStmt
> [2021-07-06T05:45:28.230Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:170
> [2021-07-06T05:45:28.230Z]   in TestKit.Exec
> [2021-07-06T05:45:28.230Z] db_test.go:3507
> [2021-07-06T05:45:28.230Z]   in testDBSuite2.TestAddNotNullColumn
> [2021-07-06T05:45:28.230Z] /usr/local/go/src/reflect/value.go:337
> [2021-07-06T05:45:28.230Z]   in Value.Call
> [2021-07-06T05:45:28.230Z] /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850
> [2021-07-06T05:45:28.230Z]   in suiteRunner.forkTest.func1
> [2021-07-06T05:45:28.230Z] /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739
> [2021-07-06T05:45:28.230Z]   in suiteRunner.forkCall.func1
> [2021-07-06T05:45:28.230Z] /usr/local/go/src/runtime/asm_amd64.s:1371
> [2021-07-06T05:45:28.230Z]   in goexit
> ```

I meet this panic in real workloads. So open https://github.com/pingcap/tidb/issues/25997 for it.

**Pull request merged**
