### PR TITLE
store: use MVCCLevelDB in 2pc_test.go testCommitterSuite

### PR DESCRIPTION
**Pull request by tiancaiamao**
* MVCCLevelDB is the default MVCCStore used by mocktikv, and the de facto
    local store implementation, so test code should use this one.
* Fix ResolveLock method in MVCCLevelDB

@disksing @coocood

### CODE REVIEW

**Comment by disksing** [comment]
LGTM.

**Comment by shenli** [comment]
LGTM

**Comment by ngaut** [comment]
Should we remove the implementation of MvccStore ?

**Comment by tiancaiamao** [comment]
I'll do it soon. @ngaut

**Pull request merged**
