### PR TITLE
executor: fix build union-scan for index-join on patitioned tables

### LINKED ISSUE #19152: Failed to build union-scan for index-join on patitioned tables
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t1, t2;
-- init
create table t1  (c_int int, c_str varchar(40), primary key (c_int)) partition by range (c_int) ( partition p0 values less than (10), partition p1 values less than maxvalue) ;
create table t2  (c_int int, c_str varchar(40), primary key (c_int, c_str)) partition by hash (c_int) partitions 4 ;
insert into t1 values (10, 'interesting neumann');
insert into t2 select * from t1 ;
-- txn
begin;
insert into t2 values (11, 'hopeful hoover');
select /*+ INL_JOIN(t1,t2) */  * from t1 join t2 on t1.c_int = t2.c_int and t1.c_str = t2.c_str where t1.c_int in (10, 11);
select /*+ INL_HASH_JOIN(t1,t2) */  * from t1 join t2 on t1.c_int = t2.c_int and t1.c_str = t2.c_str where t1.c_int in (10, 11);
commit;
```

### 2. What did you expect to see? (Required)

```
+-------+---------------------+-------+---------------------+
| c_int | c_str               | c_int | c_str               |
+-------+---------------------+-------+---------------------+
|    10 | interesting neumann |    10 | interesting neumann |
+-------+---------------------+-------+---------------------+
```

### 3. What did you see instead (Required)

```
mysql> select /*+ INL_JOIN(t1,t2) */  * from t1 join t2 on t1.c_int = t2.c_int and t1.c_str = t2.c_str where t1.c_int in (10, 11);
ERROR 1105 (HY000): interface conversion: executor.Executor is *executor.PartitionTableExecutor, not *executor.UnionScanExec
mysql> select /*+ INL_HASH_JOIN(t1,t2) */  * from t1 join t2 on t1.c_int = t2.c_int and t1.c_str = t2.c_str where t1.c_int in (10, 11);
ERROR 1105 (HY000): interface conversion: executor.Executor is *executor.PartitionTableExecutor, not *executor.UnionScanExec
```

### 4. What is your TiDB version? (Required)

master @ ae779e1502cf99d65511387a4e1eb171bd9eb9c7

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #19152 

Problem Summary:

### What is changed and how it works?

What's Changed:

Fix a tiny bug.

How it Works:

```
ERROR 1105 (HY000): interface conversion: executor.Executor is *executor.PartitionTableExecutor, not *executor.UnionScanExec
```

Remove the `(*UnionScanExec)` assertion.

### Check List 

Tests 

- Unit test

### Release note 

-   No release note

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @lysu @imtbkcat

**Review by lysu — COMMENTED** [review]
LGTM

**Pull request merged**
