### PR TITLE
misc: Update kvproto

### PR DESCRIPTION
**Pull request by breeswish**
Signed-off-by: Breezewish <me@breeswish.org>

### What problem does this PR solve?

Update to a KvProto that contains ScanDetailV2.

This PR **partially** cherry picks https://github.com/pingcap/tidb/pull/20966 . Only kvproto change is included.

### What is changed and how it works?

What's Changed: Update kvproto

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Comment by crazycs520** [comment]
Should merge https://github.com/pingcap/kvproto/pull/699 first

**Comment by breeswish** [comment]
@crazycs520 @qw4990  PTAL, thanks!

**Review by crazycs520 — COMMENTED** [review]
LGTM

**Comment by breeswish** [comment]
Close for https://github.com/pingcap/tidb/pull/23174

**Pull request closed without merging**
