### PR TITLE
sessionctx: remove variables tidb_enable_mpp_balance_with_continuous_region*

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary: A TiDB variable `tidb_enable_mpp_balance_with_continuous_region` that just used for internal development is exposed and may cause some confusion.

### What is changed and how it works?

Set `tidb_enable_mpp_balance_with_continuous_region`'s `hidden` property to be `true`.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by morgo** [comment]
Hi @JinheLin!  We have accepted a proposal to 'stop hiding sysvars' in https://github.com/pingcap/tidb/blob/master/docs/design/2021-07-29-hidden-sysvars.md -- even though they are internal, they are difficult for our 'internal' international employees to use, because their main source is the TiDB docs.

The proposal categorizes current hidden variables in 4 categories. Could you clarify which category `tidb_enable_mpp_balance_with_continuous_region` belongs to?

**Comment by JinheLin** [comment]
Hi @morgo ! After I discussed it with @flowbehappy , we think remove these variables is a better choice.

@fzhedu @windtalker PLAT. This PR removes variables about MPP balance.

**Comment by morgo** [comment]
> Hi @morgo ! After I discussed it with @flowbehappy , we think remove these variables is a better choice.
> 
> @fzhedu @windtalker PLAT. This PR removes variables about MPP balance.

OK sounds good. We have a way to remove variables now (and not break apps). See https://github.com/pingcap/tidb/pull/28931 for details.

**Comment by JinheLin** [comment]
@morgo These variables are not release now, I think remove them from the source code is OK?

**Comment by JinheLin** [comment]
> > Hi @morgo ! After I discussed it with @flowbehappy , we think remove these variables is a better choice.
> > @fzhedu @windtalker PLAT. This PR removes variables about MPP balance.
> 
> OK sounds good. We have a way to remove variables now (and not break apps). See #28931 for details.

What could go wrong if I just remove the variables from source code? These variables are not release now, I tnink just remove them from source code is OK?

**Comment by JinheLin** [comment]
@morgo 

What could go wrong if I just remove the variables from source code? 
These variables are not release now, I tnink just remove them from source code is OK?

**Comment by morgo** [comment]
> @morgo
> 
> What could go wrong if I just remove the variables from source code? These variables are not release now, I tnink just remove them from source code is OK?

You can just remove them then. It is for the use case that users might have been using them, but you are right - they were only added recently.

**Comment by JinheLin** [comment]
> > @morgo
> > What could go wrong if I just remove the variables from source code? These variables are not release now, I tnink just remove them from source code is OK?
> 
> You can just remove them then. It is for the use case that users might have been using them, but you are right - they were only added recently.

I have removed these variables in this PR. Please take a look and add your comment if there is any problem.

**Comment by JinheLin** [comment]
> > @morgo
> > What could go wrong if I just remove the variables from source code? These variables are not release now, I tnink just remove them from source code is OK?
> 
> You can just remove them then. It is for the use case that users might have been using them, but you are right - they were only added recently.

@morgo I have removed these variables in this PR. Please take a look and add your comment if there is any problem.

**Review by morgo — APPROVED** [review]
LGTM

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
