### PR TITLE
parser: support long varchar

### PR DESCRIPTION
**Pull request by zhexuany**
This PR supports `long varchar` which is alias of `mediumtext`.

### CODE REVIEW

**Comment by jackysp** [comment]
Please add the issue link in the description.

**Comment by coocood** [comment]
LGTM

**Comment by zhexuany** [comment]
This should fix https://github.com/pingcap/tidb/issues/5918. @shenli PTAL. If everything looks good, it now can be merged.

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@zhexuany If all the tests passed, please add the all-tests-passed label for the PR.

**Comment by shenli** [comment]
@zhexuany Please fix the CI.

**Comment by zhexuany** [comment]
Ran unit-test locally, passed. Reran all tests. /run-all-tests

**Comment by zhexuany** [comment]
merge master's changes and run all tests: /run-all-tests

**Comment by zhexuany** [comment]
@shenli PTAL

**Comment by shenli** [comment]
Could we merge this now?

**Comment by zhexuany** [comment]
Its ready to merge.

**Pull request merged**
