### PR TITLE
expression: update expr's type as ts only if one side being ts and another side being string.

### PR DESCRIPTION
**Pull request by zhexuany**
This fixes a bug bought by https://github.com/pingcap/tidb/pull/6621. As we all know, ts has max value: 2038. When we convert some datetime beyond this value to ts, a invalid time format error will be thrown. So we need use a finer coarse to update expr's type as ts. 

I will file another pr to add ts boundary related test.

### CODE REVIEW

**Comment by shenli** [comment]
@zhexuany Please add test cases in thie PR.

**Comment by shenli** [comment]
@XuHuaiyu PTAL

**Comment by lysu** [comment]
LGTM

**Comment by zhexuany** [comment]
table schema：
create table t (tp_ts timestamp, tp_dt datetime);

create table t (tp_ts timestamp, tp_dt datetime);
insert into t values('2012-01-12 00:00:00', '2102-01-12 00:00:00');

case 1:
```
mysql> select * from t where tp_ts > "2012-01-11 00:00:00";
+---------------------+---------------------+
| tp_ts               | tp_dt               |
+---------------------+---------------------+
| 2012-01-12 00:00:00 | 2102-01-12 00:00:00 |
| 2012-01-12 00:00:00 | 2102-01-12 00:00:00 |
| 2012-01-12 00:00:00 | 2102-01-12 00:00:00 |
| 2012-01-12 00:00:00 | 2102-01-12 00:00:00 |
+---------------------+---------------------+
4 rows in set (0.00 sec)
```
case 2
```
mysql> select * from t where tp_ts > "2112-01-11 00:00:00";
Empty set (0.00 sec)
```
case 3:

```
mysql> select * from t where tp_ts < "2112-01-11 00:00:00";
+---------------------+---------------------+
| tp_ts               | tp_dt               |
+---------------------+---------------------+
| 2012-01-12 00:00:00 | 2102-01-12 00:00:00 |
| 2012-01-12 00:00:00 | 2102-01-12 00:00:00 |
| 2012-01-12 00:00:00 | 2102-01-12 00:00:00 |
| 2012-01-12 00:00:00 | 2102-01-12 00:00:00 |
+---------------------+---------------------+
4 rows in set (0.00 sec)
```

Based on above cases, we can conclude that mysql's convert ts and string to datetime first and then compare them. We need to be compatible with this.

**Comment by birdstorm** [comment]
please mind the following case:

```
mysql> select * from t where tp_ts < timestamp "2112-01-11 00:00:00";
+---------------------+---------------------+
| tp_ts               | tp_dt               |
+---------------------+---------------------+
| 2012-01-12 00:00:00 | 2102-01-12 00:00:00 |
| 2012-01-12 00:00:00 | 2102-01-12 00:00:00 |
| 2012-01-12 00:00:00 | 2102-01-12 00:00:00 |
| 2012-01-12 00:00:00 | 2102-01-12 00:00:00 |
+---------------------+---------------------+
4 rows in set (0.00 sec)
```

**Comment by zhexuany** [comment]
Closing this PR since the problem is actually daylight saving time.

**Pull request closed without merging**
