### PR TITLE
ddl: fix DST times for adding index

### LINKED ISSUE #46033: Data inconsistency after adding index in ingest mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql> SET time_zone = '-06:00';
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT @@global.time_zone, @@session.time_zone, @@global.system_time_zone;
+--------------------+---------------------+---------------------------+
| @@global.time_zone | @@session.time_zone | @@global.system_time_zone |
+--------------------+---------------------+---------------------------+
| SYSTEM             | -06:00              | Asia/Shanghai             |
+--------------------+---------------------+---------------------------+
1 row in set (0.00 sec)

mysql> drop table if exists  timetest;
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> create table timetest (`src` varchar(48),`t` timestamp,`timezone` varchar(100));
Query OK, 0 rows affected (0.14 sec)

mysql> insert into timetest values('2023-07-29 23:15:30 -0600','2023-07-29 23:15:30 -0600','-6:00');
Query OK, 1 row affected (0.01 sec)

mysql> create index idx on timetest(t);

Query OK, 0 rows affected (2.95 sec)

mysql> admin check table timetest;
ERROR 8223 (HY000): data inconsistency in table: timetest, index: idx, handle: 1, index-values:"handle: 1, values: [KindMysqlTime 2023-07-30 19:15:30]" != record-values:"handle: 1, values: [KindMysqlTime 2023-07-30 13:15:30]"
mysql> admin show ddl jobs;
+--------+---------+-------------------------+------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
| JOB_ID | DB_NAME | TABLE_NAME              | JOB_TYPE               | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE  |
+--------+---------+-------------------------+------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
|    100 | test    | timetest                | add index /* ingest */ | public       |         2 |       98 |         1 | 2023-08-13 05:36:22 | 2023-08-13 05:36:22 | 2023-08-13 05:36:25 | synced |
|     99 | test    | timetest                | create table           | public       |         2 |       98 |         0 | 2023-08-13 05:36:22 | 2023-08-13 05:36:22 | 2023-08-13 05:36:22 | synced |
|     97 | mysql   | tidb_runaway_watch_done | create table           | public       |         1 |       96 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     95 | mysql   | tidb_timers             | create table           | public       |         1 |       94 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     93 | mysql   | tidb_runaway_queries    | create table           | public       |         1 |       92 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     91 | mysql   | tidb_runaway_watch      | create table           | public       |         1 |       90 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     89 | mysql   | tidb_import_jobs        | create table           | public       |         1 |       88 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     87 | mysql   | load_data_jobs          | create table           | public       |         1 |       86 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     85 | mysql   | tidb_global_task        | create table           | public       |         1 |       84 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     83 | mysql   | tidb_ttl_job_history    | create table           | public       |         1 |       82 |         0 | 2023-08-11 08:01:30 | 2023-08-11 08:01:30 | 2023-08-11 08:01:31 | synced |
+--------+---------+-------------------------+------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
10 rows in set (0.01 sec)

mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: c7c7000165aba353eb7b39a6c11371e1adc7b6b1
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time: 2023-08-10 14:55:04
GoVersion: go1.21.0
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
No error of admin check statement.

### 3. What did you see instead (Required)
error, timestamp column set the wrong timezone in index.

### 4. What is your TiDB version? (Required)
c7c7000165aba353eb7b39a6c11371e1adc7b6b1
<!-- Paste the output of SELECT tidb_version() -->

### LINKED ISSUE #47426: Daylight saving times are not properly handled during add index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql> create table t (a timestamp);
Query OK, 0 rows affected (0.14 sec)

mysql> SET time_zone = 'Asia/Shanghai';
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t values('1991-07-21 00:00:00');
Query OK, 1 row affected (0.01 sec)

mysql> alter table t add index idx(a);
Query OK, 0 rows affected (2.72 sec)

mysql> admin check table t;
ERROR 8223 (HY000): data inconsistency in table: t, index: idx, handle: 1, index-values:"handle: 1, values: [KindMysqlTime 1991-07-20 23:00:00]" != record-values:"handle: 1, values: [KindMysqlTime 1991-07-21 00:00:00]"
```

### 2. What did you expect to see? (Required)

Admin check passed.

### 3. What did you see instead (Required)

Admin check failed.

### 4. What is your TiDB version? (Required)

master 35d576516e

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #47426, ref #46033

Problem Summary:

I did not consider DST values in #46055. As a result, the timezone names are always ignored. It may cause data inconsistency when TiDB encounters DST values during adding index.

### What is changed and how it works?

- Revert the changes in #46055. I bring back timezone name because it determines whether DST rules are used. 
- On the other hand, I try another way to fix #46033: we don't return "UTC" as the default value when `GetTimeZone()` because `TimeZoneLocation.GetLocation()` could handle the empty strings properly. Thus, the priority between `time_zone_name` and `time_zone_offset` is preserved.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zimulala — APPROVED** [review]
LGTM

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Comment by tangenta** [comment]
Blocked by #47446

**Pull request merged**
