### PR TITLE
plan: fix bug in insert statement.

### PR DESCRIPTION
**Pull request by hanfei1991**
insert into t set b = a is not allowed, it should be written as insert into t set b = values(a).

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by breeswish** [comment]
@hanfei1991 @shenli 

Is "insert into t set b = a is not allowed" intentional? Seems that MySQL supports this syntax:

MySQL:

```
mysql> CREATE TABLE t(a VARCHAR(1000), b VARBINARY(1000));
Query OK, 0 rows affected (0.02 sec)

mysql> INSERT INTO t SET a = '12345', b = COMPRESS(a);
Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO t SET a = '12345', b = COMPRESS(a);
Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO t SET a = '12345', b = COMPRESS(a);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t SET a = '12345', b = a;
Query OK, 1 row affected (0.01 sec)

mysql> select * from t;
+-------+-------------------+
| a     | b                 |
+-------+-------------------+
| 12345 |    x?34261 ?    |
| 12345 |    x?34261 ?    |
| 12345 |    x?34261 ?    |
| 12345 | 12345             |
+-------+-------------------+
```

After applying this PR, in TiDB:

```
mysql> CREATE TABLE t(a VARCHAR(1000), b VARBINARY(1000));
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO t SET a = '12345', b = COMPRESS(a);
ERROR 1054 (42S22): Unknown column '' in 'field list'

mysql> INSERT INTO t SET a = '12345', b = a;
ERROR 1054 (42S22): Unknown column '' in 'field list'
```

**Comment by breeswish** [comment]
In addition, according to MySQL documentation:

> The VALUES() function is meaningful only in the ON DUPLICATE KEY UPDATE clause of INSERT statements and returns NULL otherwise.

**Comment by ngaut** [comment]
Nice catch. @breeswish

**Comment by shenli** [comment]
@breeswish we do not support this syntax. We could consider to support it in the future.

**Comment by breeswish** [comment]
@shenli Got

**Pull request merged**
