### PR TITLE
sessionctx: Support global variable tidb_replica_read

### PR DESCRIPTION
**Pull request by rahilsh**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/17650

Problem Summary:

### What is changed and how it works?

Proposal: Added Support for global variable tidb_replica_read

What's Changed: tidb_replica_read is now a global variable

How it Works: `SET GLOBAL tidb_replica_read='follower';`

### Check List

Documentation

- [x] Contains variable changes

### Release note

```release-note
Support global variable tidb_replica_read
```

### CODE REVIEW

**Review by xhebox — COMMENTED** [review]
Please add a test. I think it is a compatibility breaker and needs corresponding document updates, right, @morgo ?

**Comment by morgo** [comment]
> Please add a test. I think it is a compatibility breaker and needs corresponding document updates, right, @morgo ?

Why do you say it's a compatibility breaker? The behavior by default should be the same. It is only when the user changes the value of the variable that the new functionality applies.

**Comment by xhebox** [comment]
> 
> 
> > Please add a test. I think it is a compatibility breaker and needs corresponding document updates, right, @morgo ?
> 
> Why do you say it's a compatibility breaker? The behavior by default should be the same. It is only when the user changes the value of the variable that the new functionality applies.

Makes sense. I was concerning the scope of the variable.

**Review by morgo — CHANGES_REQUESTED** [review]
Let me know if you need help with tests. I am "Morgan Tocker (PingCAP)" on Slack.

**Review by morgo — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by xhebox** [comment]
@morgo Discussed with CI guys, you could directly remove the label to unblock the merging.

**Review by morgo — APPROVED** [review]

**Pull request merged**
