### PR TITLE
planner: propagate more possible props to enlarge search space

### PR DESCRIPTION
**Pull request by zz-jason**
### What problem does this PR solve? 

fix https://github.com/pingcap/tidb/issues/10579

```sql
create table t(a bigint, b bigint, c bigint, index idex(a, b, c));
select count(*) from t where a = 1 group by b;
```

enlarge the set of possible physical properties of data source, let the above sql be able to use stream aggregate.

### What is changed and how it works?

will be explained in detail later.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

**Comment by winoros** [comment]
What about modifying struct `Property` to add a field named `pointPrefixLen`. Then we don't need to generate too much noise. One prop can match all possible needs.

**Comment by zz-jason** [comment]
> What about modifying struct `Property` to add a field named `pointPrefixLen`. Then we don't need to generate too much noise. One prop can match all possible needs.

I'll try it tomorrow

**Pull request merged**
