### PR TITLE
binlog: update binlog status from Skippping to On when recover binlog

### PR DESCRIPTION
**Pull request by joccau**
Signed-off-by: joccau <zak.zhao@pingcap.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/32172

Problem Summary: As title

### What is changed and how it works?
It need to update binlog_status when recover binlog.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by joccau** [comment]
/hold
I need to test it, but reviewers can review code firstly.

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by jackysp — APPROVED** [review]
LGTM

**Review by kennytm — APPROVED** [review]

**Comment by kennytm** [comment]
>  Found may-affects label on bug issue pingcap/tidb#32172. 

you need to clean up the `may-affects` labels in that issue.

**Pull request merged**
