### PR TITLE
session: add a `doNotCommit` flag to transaction when `StmtCommit` fail (#8918)

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry-pick from https://github.com/pingcap/tidb/pull/8918

@winkyao @lysu @crazycs520

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8924)

### CODE REVIEW

**Comment by ciscoxll** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by tiancaiamao** [comment]
This is a cherry pick, I think it's better to keep it the same as the original one.

> Because there is no need to execute the following statements, after the txn is marked as aborted. But commit and rollback statements should be special treated

If an aborted txn is treat specially, should we check aborted state everywhere?
If an aborted txn is treat specially, is there more state involved? will it introduce potential bugs?

We should be very careful about this change.

@jackysp

**Comment by tiancaiamao** [comment]
/run-unit-test tikv=release-2.1 tidb-test=release-2.1 pd=release-2.1 gofail=pingcap

**Comment by jackysp** [comment]
OK, we could do it in another PR. The state does not need to be checked everywhere, and the state is 
 already involved.

**Comment by zhouqiang-cl** [comment]
/run-unit-test tikv=release-2.1 tidb-test=release-2.1 pd=release-2.1 gofail=pingcap

**Comment by zz-jason** [comment]
LGTM

**Pull request merged**
