### PR TITLE
executor: migrate test-infra to testify for testSuiteWithCliBaseCharset

### LINKED ISSUE #33430: migrate test-infra to testify for executor_test.go testSuiteWithCliBaseCharset

### PR DESCRIPTION
**Pull request by tisonkun**
Issue Number: close #33430

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
@tisonkun Please fix the linter.

**Comment by tisonkun** [comment]
@hawkingrei fixed.

**Review by hawkingrei — APPROVED** [review]

**Review by LittleFall — APPROVED** [review]

**Comment by purelind** [comment]
### TiDB MergeCI notify
**✅ Well Done! New fixed [1] after this pr merged.**
CI Name | Result | Duration | Compare with Parent commit
------------ | ------------- | ------------- | -------------
[idc-jenkins-ci-tidb/integration-br-test](https://ci.pingcap.net/job/tidb_ghpr_integration_br_test/8758/display/redirect) | 🟥 failed 27, success 2, total 29 | 15 min | Existing failure
[idc-jenkins-ci-tidb/common-test](https://ci.pingcap.net/job/tidb_ghpr_common_test/9456/display/redirect) | ✅ all 12 tests passed | 5 min 28 sec | Fixed
[idc-jenkins-ci/integration-cdc-test](https://ci.pingcap.net/job/tidb_ghpr_integration_cdc_test/1792/display/redirect) | 🟢 all 34 tests passed | 51 min | Existing passed
[idc-jenkins-ci-tidb/code-coverage](https://ci.pingcap.net/job/tidb_ghpr_coverage/2985/display/redirect) | 🟢 Lines coverage: 63.48% | 12 min | Existing passed
[idc-jenkins-ci-tidb/integration-common-test](https://ci.pingcap.net/job/tidb_ghpr_integration_common_test/10625/display/redirect) | 🟢 all 11 tests passed | 12 min | Existing passed
[idc-jenkins-ci-tidb/integration-copr-test](https://ci.pingcap.net/job/tidb_ghpr_integration_copr_test/9033/display/redirect) | 🟢 all 1 tests passed | 7 min 38 sec | Existing passed
[idc-jenkins-ci-tidb/sqllogic-test-2](https://ci.pingcap.net/job/tidb_ghpr_sqllogic_test_2/9120/display/redirect) | 🟢 all 28 tests passed | 5 min 44 sec | Existing passed
[idc-jenkins-ci-tidb/sqllogic-test-1](https://ci.pingcap.net/job/tidb_ghpr_sqllogic_test_1/9182/display/redirect) | 🟢 all 26 tests passed | 5 min 17 sec | Existing passed
[idc-jenkins-ci-tidb/integration-ddl-test](https://ci.pingcap.net/job/tidb_ghpr_integration_ddl_test/9245/display/redirect) | 🟢 all 6 tests passed | 5 min 13 sec | Existing passed
[idc-jenkins-ci-tidb/tics-test](https://ci.pingcap.net/job/tidb_ghpr_tics_test/8874/display/redirect) | 🟢 all 1 tests passed | 4 min 58 sec | Existing passed
[idc-jenkins-ci-tidb/mybatis-test](https://ci.pingcap.net/job/tidb_ghpr_mybatis/9044/display/redirect) | 🟢 all 1 tests passed | 3 min 9 sec | Existing passed
[idc-jenkins-ci-tidb/integration-compatibility-test](https://ci.pingcap.net/job/tidb_ghpr_integration_campatibility_test/10032/display/redirect) | 🟢 all 1 tests passed | 2 min 51 sec | Existing passed
[idc-jenkins-ci-tidb/plugin-test](https://ci.pingcap.net/job/tidb_merged_pr_build/2854/display/redirect) | 🟢 build success, plugin test success | 4min | Existing passed

**Pull request merged**
