### PR TITLE
server: Improve connection info

### LINKED ISSUE #43720: Connection info is unclear
## Enhancement

This reports `Socket` for TCP connections and `UnixSocket` for UNIX Domain Socket connections. This is a bit misleading. It also doesn't report the correct TLS info.

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #43720 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by CbcWestwolf — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Comment by dveeden** [comment]
```
dlv debug ./tidb-server -- -config <(echo -en "[security]\nauto-tls=true\n")
Type 'help' for list of commands.
(dlv) b tidb/server/server.go:733
Breakpoint 1 set at 0x6027797 for github.com/pingcap/tidb/server.(*clientConn).connectInfo() ./server/server.go:733
(dlv) c
...
```

```
mysql -h 127.0.0.1 -u root -P 4000 --ssl-mode=REQUIRED --tls-version=TLSv1.3
...
```

```
...
> github.com/pingcap/tidb/server.(*clientConn).connectInfo() ./server/server.go:733 (hits goroutine(2385):1 total:1) (PC: 0x6027797)
   728:			ServerVersion:     mysql.TiDBReleaseVersion,
   729:			SSLVersion:        sslVersion,
   730:			PID:               serverPID,
   731:			DB:                cc.dbname,
   732:		}
=> 733:		return connInfo
   734:	}
   735:	
   736:	func (s *Server) checkConnectionCount() error {
   737:		// When the value of Instance.MaxConnections is 0, the number of connections is unlimited.
   738:		if int(s.cfg.Instance.MaxConnections) == 0 {
(dlv) p connInfo
*github.com/pingcap/tidb/sessionctx/variable.ConnectionInfo {
	ConnectionID: 2199023255955,
	ConnectionType: "SSL/TLS",          
	Host: "127.0.0.1",
	ClientIP: "127.0.0.1",
	ClientPort: "55322",
	ServerID: 1,
	ServerIP: "127.0.0.1",
	ServerPort: 4000,
	Duration: 0,
	User: "root",
	ServerOSLoginUser: "Daniël van Eeden",
	OSVersion: "Linux 6.2.14-300.fc38.x86_64.x86_64",
	ClientVersion: "",
	ServerVersion: "None",
	SSLVersion: "TLSv1.3",              <----------
	PID: 576818,
	DB: "",}
(dlv) c
```

```
mysql -h 127.0.0.1 -u root -P 4000 --ssl-mode=DISABLED
```

```
> github.com/pingcap/tidb/server.(*clientConn).connectInfo() ./server/server.go:733 (hits goroutine(4918):1 total:2) (PC: 0x6027797)
   728:			ServerVersion:     mysql.TiDBReleaseVersion,
   729:			SSLVersion:        sslVersion,
   730:			PID:               serverPID,
   731:			DB:                cc.dbname,
   732:		}
=> 733:		return connInfo
   734:	}
   735:	
   736:	func (s *Server) checkConnectionCount() error {
   737:		// When the value of Instance.MaxConnections is 0, the number of connections is unlimited.
   738:		if int(s.cfg.Instance.MaxConnections) == 0 {
(dlv) p connInfo
*github.com/pingcap/tidb/sessionctx/variable.ConnectionInfo {
	ConnectionID: 2199023255957,
	ConnectionType: "TCP",                     <-----------------------------
	Host: "127.0.0.1",
	ClientIP: "127.0.0.1",
	ClientPort: "52552",
	ServerID: 1,
	ServerIP: "127.0.0.1",
	ServerPort: 4000,
	Duration: 0,
	User: "root",
	ServerOSLoginUser: "Daniël van Eeden",
	OSVersion: "Linux 6.2.14-300.fc38.x86_64.x86_64",
	ClientVersion: "",
	ServerVersion: "None",
	SSLVersion: "",
	PID: 576818,
	DB: "",}
```

**Review by hawkingrei — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by hawkingrei** [comment]
```
ERROR: /home/jenkins/agent/workspace/pingcap/tidb/ghpr_build/tidb/extension/enterprise/audit/BUILD.bazel:44:8: GoCompilePkg extension/enterprise/audit/audit_test.internal.a failed: (Exit 1): builder failed: error executing command (from target //extension/enterprise/audit:audit_test) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder_reset/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src extension/enterprise/audit/entry.go -src ... (remaining 101 arguments skipped)


Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging

extension/enterprise/audit/function_test.go:69:85: not enough arguments in call to tk.Session().Auth

	have (*"github.com/pingcap/tidb/parser/auth".UserIdentity, nil, nil)

	want (*"github.com/pingcap/tidb/parser/auth".UserIdentity, []byte, []byte, "github.com/pingcap/tidb/privilege/conn".AuthConn)

extension/enterprise/audit/function_test.go:116:85: not enough arguments in call to tk.Session().Auth

	have (*"github.com/pingcap/tidb/parser/auth".UserIdentity, nil, nil)

	want (*"github.com/pingcap/tidb/parser/auth".UserIdentity, []byte, []byte, "github.com/pingcap/tidb/privilege/conn".AuthConn)

extension/enterprise/audit/function_test.go:121:89: not enough arguments in call to tk2.Session().Auth

	have (*"github.com/pingcap/tidb/parser/auth".UserIdentity, nil, nil)

	want (*"github.com/pingcap/tidb/parser/auth".UserIdentity, []byte, []byte, "github.com/pingcap/tidb/privilege/conn".AuthConn)

extension/enterprise/audit/function_test.go:152:90: not enough arguments in call to tk2.Session().Auth

	have (*"github.com/pingcap/tidb/parser/auth".UserIdentity, nil, nil)

	want (*"github.com/pingcap/tidb/parser/auth".UserIdentity, []byte, []byte, "github.com/pingcap/tidb/privilege/conn".AuthConn)

extension/enterprise/audit/sysvar_test.go:105:84: not enough arguments in call to tk.Session().Auth

	have (*"github.com/pingcap/tidb/parser/auth".UserIdentity, nil, nil)

	want (*"github.com/pingcap/tidb/parser/auth".UserIdentity, []byte, []byte, "github.com/pingcap/tidb/privilege/conn".AuthConn)

extension/enterprise/audit/sysvar_test.go:193:85: not enough arguments in call to tk.Session().Auth

	have (*"github.com/pingcap/tidb/parser/auth".UserIdentity, nil, nil)

	want (*"github.com/pingcap/tidb/parser/auth".UserIdentity, []byte, []byte, "github.com/pingcap/tidb/privilege/conn".AuthConn)

extension/enterprise/audit/sysvar_test.go:374:85: not enough arguments in call to tk.Session().Auth

	have (*"github.com/pingcap/tidb/parser/auth".UserIdentity, nil, nil)

	want (*"github.com/pingcap/tidb/parser/auth".UserIdentity, []byte, []byte, "github.com/pingcap/tidb/privilege/conn".AuthConn)

compilepkg: error running subcommand external/go_sdk/pkg/tool/linux_amd64/compile: exit status 2

INFO: Elapsed time: 960.840s, Critical Path: 427.67s

```

We need to update the plugin.

**Pull request merged**
