### PR TITLE
br: fix br version to match tikv-server version for ci integration

### PR DESCRIPTION
**Pull request by joccau**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/32805

Problem Summary: 
As issue.

### What is changed and how it works?
Increase `br version` for 6.0 to match the `tikv-server` version.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by kennytm** [comment]
The TiFlash test failed. Legit.

```
[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10406/pipeline#step-669-log-87)[](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10406/pipeline#step-669-log-88)[2022-03-04T02:34:51.073Z] [2022/03/04 10:34:29.703 +08:00] [ERROR] [util.rs:457] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"version should compatible with version  6.0.0-alpha, got 5.5.0-alpha-161-g6ed8574\", details: [] }))"]

[2022-03-04T02:34:51.073Z] [2022/03/04 10:34:29.703 +08:00] [ERROR] [util.rs:466] ["reconnect failed"] [err_code=KV:PD:Unknown] [err="Other(\"[components/pd_client/src/util.rs:301]: cancel reconnection due to too small interval\")"]

[2022-03-04T02:34:51.073Z] [2022/03/04 10:34:30.704 +08:00] [ERROR] [util.rs:457] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"version should compatible with version  6.0.0-alpha, got 5.5.0-alpha-161-g6ed8574\", details: [] }))"]
```

**Comment by sticnarf** [comment]
> The TiFlash test failed. Legit.
> 
> https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10406/pipeline
> 
> ```
> [2022-03-04T02:34:51.073Z] [2022/03/04 10:34:29.703 +08:00] [ERROR] [util.rs:457] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"version should compatible with version  6.0.0-alpha, got 5.5.0-alpha-161-g6ed8574\", details: [] }))"]
> 
> [2022-03-04T02:34:51.073Z] [2022/03/04 10:34:29.703 +08:00] [ERROR] [util.rs:466] ["reconnect failed"] [err_code=KV:PD:Unknown] [err="Other(\"[components/pd_client/src/util.rs:301]: cancel reconnection due to too small interval\")"]
> 
> [2022-03-04T02:34:51.073Z] [2022/03/04 10:34:30.704 +08:00] [ERROR] [util.rs:457] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"version should compatible with version  6.0.0-alpha, got 5.5.0-alpha-161-g6ed8574\", details: [] }))"]
> ```

A tiflash rebuild is undergoing with the version updated.

**Review by 3pointer — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Review by fengou1 — COMMENTED** [review]
/LGTM

**Review by fengou1 — APPROVED** [review]

**Pull request merged**
