### PR TITLE
store/helper: Migrate test-infra to testify 

### LINKED ISSUE #27656: migrate test-infra to testify for `store/helper`

### PR DESCRIPTION
**Pull request by 3mard**
### What problem does this PR solve?

Issue Number: close #27656  

Problem Summary:

### What is changed and how it works?

migrate test-infra to testify for store/helper 

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
Thanks for your contribution @3mard !

I push a commit 79774afa30009f6e462ca996574d61200be236e8 for applying several best practices during the migration work. Please take a look and ask if any question.

**Comment by 3mard** [comment]
Thanks @tisonkun 
I will take note `79774af ` for the next testify migration task :)

**Review by tisonkun — APPROVED** [review]
LGTM

**Comment by mmyj** [comment]
All test cases this changed can be passed. But `check_dev_2` failed for running too long.
```

[2021-09-11T14:56:35.437Z] The following test cases take too long to finish:

[2021-09-11T14:56:35.437Z] PASS: db_test.go:2865: testSerialDBSuite.TestCreateTable	5.017s

[2021-09-11T14:56:35.437Z] PASS: db_test.go:4450: testSerialDBSuite.TestModifyColumnBetweenStringTypes	6.850s

[2021-09-11T14:56:35.437Z] --- PASS: TestModifyColumn (18.57s)

[2021-09-11T14:56:35.437Z] PASS: prepare_test.go:170: testPlanSerialSuite.TestPrepareCacheDeferredFunction	6.994s

[2021-09-11T14:56:35.437Z] PASS: point_get_plan_test.go:722: testPointGetSuite.TestUpdateWithTableReadLockWillFail	13.374s

[2021-09-11T14:56:35.437Z] PASS: prepare_test.go:606: testPrepareSerialSuite.TestConstPropAndPPDWithCache	16.275s

[2021-09-11T14:56:35.437Z] PASS: prepare_test.go:54: testPrepareSerialSuite.TestPrepareCache	7.831s

[2021-09-11T14:56:35.437Z] PASS: prepare_test.go:468: testPrepareSerialSuite.TestPrepareCacheForPartition	5.594s

[2021-09-11T14:56:35.437Z] PASS: clustered_index_test.go:587: testClusteredSerialSuite.TestPartitionTable	7.653s

[2021-09-11T14:56:35.437Z]     --- PASS: TestListInDiskWithChecksumAndEncrypt/testListInDisk (7.14s)
```

**Review by mmyj — APPROVED** [review]

**Pull request merged**
