### PR TITLE
test: make test TestTopSQLCPUProfile stable by avoid write conflict

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs <crazycs520@gmail.com>

### What problem does this PR solve?

```sql
[2021-06-22T13:08:37.235Z] ----------------------------------------------------------------------
[2021-06-22T13:08:37.235Z] FAIL: tidb_test.go:1196: tidbTestTopSQLSuite.TestTopSQLCPUProfile
[2021-06-22T13:08:37.235Z] 
[2021-06-22T13:08:37.235Z] tidb_test.go:1384:
[2021-06-22T13:08:37.235Z]     checkFn(ca.sql, ca.planRegexp)
[2021-06-22T13:08:37.235Z] tidb_test.go:1364:
[2021-06-22T13:08:37.235Z]     // since 1 sql may has many plan, check `len(stats) > 0` instead of `len(stats) == 1`.
[2021-06-22T13:08:37.235Z]     c.Assert(len(stats) > 0, IsTrue, commentf)
[2021-06-22T13:08:37.235Z] ... obtained bool = false
[2021-06-22T13:08:37.235Z] ... sql: select * from t use index(idx) where a<10;
```

### What is changed and how it works?

As the title said.

### Related changes

- N/A

### Check List 

Tests 

- No code

Side effects

- N/A

### Release note 

- No release note.

### CODE REVIEW

**Comment by crazycs520** [comment]
@AilinKid @tangenta PTAL

**Comment by tisonkun** [comment]
@crazycs520 may I ask how the original order cause write conflict and how the reorder solve the problem?

**Comment by crazycs520** [comment]
> @crazycs520 may I ask how the original order cause write conflict and how the reorder solve the problem?

1. Original conflict cause by concurrently execute following SQL:

```sql
update t set b=a where b is null limit 1;
delete from t where b is null limit 2;
```

This PR change to concurrently execute following SQL to avoid write conflict.

```sql
update t set b=a where b is null limit 1;
delete from t where b = a limit 2;
```

2. Actually this PR doesn't make sure to solve this problem. But try to make sure each SQL runs as long as possible. This will increase probability of pprof profile sampling those SQL.

**Review by AilinKid — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Comment by tisonkun** [comment]
ref #25122

**Pull request merged**
