### PR TITLE
expression: Quit builtin function SLEEP when KILLed.

### LINKED ISSUE #4378: unable to kill query
1. What did you do?
`select sleep(10);`
hit `ctrl+c` with the same session to cancel, or `kill id` in another session. 

2. What did you expect to see?
kill the sleep query.

3. What did you see instead?
with `ctrl+c` shows `^C^C -- query aborted` but blocked until the sleep query completed.
with `kill id` returned ok but nothing happened, sleep query completed.

4. What version of TiDB are you using (`tidb-server -V`)?
master

### PR DESCRIPTION
**Pull request by ladrift**
Use cancellation pattern in SLEEP function by making use of
transaction's context. But, it does not quit when Ctrl-C
pressed. Add TODO for future investigation.

Fix #4378 partially

### CODE REVIEW

**Comment by ladrift** [comment]
I have added the unit test to cover the cancellation case. I also do some changes on mock.Context so I can mock the cancellation situation.
@shenli @ngaut PTAL

**Comment by shenli** [comment]
LGTM
@tiancaiamao @coocood PTAL

**Comment by ladrift** [comment]
Ping @tiancaiamao @coocood Can this PR be considered to be merged?

**Comment by tiancaiamao** [comment]
LGTM

**Comment by shenli** [comment]
@ladrift Thanks!

**Comment by ladrift** [comment]
@shenli You are welcome. I am really happy to become a real __code__ contributor to TiDB, not only docs. :smile:

**Comment by tiancaiamao** [comment]
@ladrift `Ctrl + C` can't cancel the query, because it send an `kill session xxx` query, where xxx is session id.
Currently, TiDB supports a non-standard `kill TiDB session xxx` variant query, you can try it.

https://github.com/pingcap/tidb/blob/master/ast/misc.go#L349

**Comment by ladrift** [comment]
Thanks for your pointer! Maybe we should open a new issue and discuss it there. Can you do this? I think you can describe the problem better than me.

**Pull request merged**
