### PR TITLE
readme: Add the contributor swag form.

### PR DESCRIPTION
**Pull request by luzizhuo**
### What problem does this PR solve?

Update the readme doc. Add the contributor swag form.
Issue Number: ref #34452

### What is changed and how it works?
Update the readme doc. Add the contributor swag form.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by djshow832 — APPROVED** [review]

**Comment by xhebox** [comment]
> ### What problem does this PR solve?
> 
> Update the readme doc. Add the contributor swag form. Issue Number: ref #34452
> ### What is changed and how it works?
> 
> Update the readme doc. Add the contributor swag form.
> ### Check List
> 
> Tests
> 
>     * [ ]  Unit test
> 
>     * [ ]  Integration test
> 
>     * [ ]  Manual test (add detailed scripts or steps below)
> 
>     * [x]  No code
> 
> 
> ### Release note
> 
> Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.
> 
> ```
> None
> ```

I guess you don't want this PR to close the issue, but after all wanted PR merged.

**Comment by luzizhuo** [comment]
> @luzizhuo I guess you don't want this PR to close the issue, but after all wanted PR merged. So I've changed `close #xxx` to `ref #xxx`.

OK,thanks.

**Pull request merged**
