### PR TITLE
client-go: safeTS obtain min-resolved-ts by store list

### LINKED ISSUE #46664: client-go/safeTS: reduce `GetStoreMinResolvedTS` call
## Bug Report

Please answer these questions before submitting your issue. Thanks!

img_v2_0c514c8b-243c-411a-bcdf-a46bbfa2f4ag
related to https://github.com/tikv/client-go/issues/922

currently, we try to GetStoreMinResolvedTS for all stores from PD every 2 seconds

#### For `txn_scope`
txn_scope will be global in major situation, So we can judge @@txn_scope value which from the config:
when find is global, we can get cluster-level resolved ts to avoid using kv grpc.

If not, we need to enhance min resolved ts usage:

#### For `min resolved ts`
Nowadays we have 2 api interface for obtaining min resolved ts

- /pd/api/v1/min-resolved-ts: obtain cluster's min resolved ts
- /pd/api/v1/min-resolved-ts/{store_id}: obtain each store's min resolved ts

We can use the `approach I` to get cluster's min resolved ts when @@txn_scope is global.
For client-go's updateSafeTS, we call `approach II` for each store, which is not necessary.
We can extend the approach I params to obtain specified store via a list to reduce the cost per call after api: Extend the min-resolved-ts api to support getting the specified store  pd#6880 merged

### 1. Minimal reproduce step (Required)
For example when we have 100 tikvs and 100 tidbs, then the connections for pd/api/v1/min-resolved-ts to PD would be 100*100/2=5000 in 1 seconds.

### 2. What did you expect to see? (Required)
reduce ` pd/api/v1/min-resolved-ts` call

### 3. What did you see instead (Required)
For example when we have 100 tikvs and 100 tidbs, then the connections for pd/api/v1/min-resolved-ts to PD would be 100*100/2=5000 in 1 seconds.

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: close #46664

Problem Summary:
update https://github.com/tikv/client-go/pull/921

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
safeTS obtain min-resolved-ts by store list 
```

### CODE REVIEW

**Comment by HuSharp** [comment]
@nolouch @JmPotato PTAL, thx!

**Review by JmPotato — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Pull request merged**
