### PR TITLE
executor: add diagnosis rule to check Transparent Huge Pages(THP) enabled (#20611)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20611 to release-4.0

---

Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

related issue: https://github.com/pingcap/tidb/issues/19538

Enable Transparent Huge Pages(THP) in linux will affect the performance, This PR add a diagnose rule to check whethere THP is enabled.

example:

```sql
select * from `INSPECTION_RESULT` where rule='config';
+--------+------------------------------+------+----------------+-----------------+------------------------+------------------------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| RULE   | ITEM                         | TYPE | INSTANCE       | STATUS_ADDRESS  | VALUE                  | REFERENCE              | SEVERITY | DETAILS                                                                                                                                             |
+--------+------------------------------+------+----------------+-----------------+------------------------+------------------------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| config | transparent_hugepage_enabled | tidb | 10.0.2.15:4001 | 10.0.2.15:10081 | [always] madvise never | always madvise [never] | warning  | Transparent HugePages can cause memory allocation delays during runtime, TiDB recommends that you disable Transparent HugePages on all TiDB servers |
+--------+------------------------------+------+----------------+-----------------+------------------------+------------------------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- No

### Release note 

- add diagnosis rule to check Transparent Huge Pages(THP) enabled

### CODE REVIEW

**Comment by crazycs520** [comment]
@lonng  @breeswish PTAL

**Comment by breeswish** [comment]
Do we need to wait https://github.com/tikv/tikv/pull/8879 merged first?

**Comment by crazycs520** [comment]
@breeswish @lonng PTAL

**Review by breeswish — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]

**Comment by zz-jason** [comment]
@crazycs520 please resolve conflicts.

**Pull request closed without merging**
