### PR TITLE
util: revert util/mathutil

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve? 
Previously we created `util/mathutil` for building `tidb-wasm`. But we find it will conflict with `cznic/mathutil` and there is no way to force people to import the right path. 

### What is changed and how it works?
Remove `util/mathutil` here and replace it with customized `mathutil` in tidb-wasm repo.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change

Side effects

 - Breaking backward compatibility

### CODE REVIEW

**Comment by siddontang** [comment]
will it affect TiDB Wasm?  @5kbpers

**Comment by 5kbpers** [comment]
> will it affect TiDB Wasm? @5kbpers

Yes, I have updated TiDB WASM

**Comment by lucklove** [comment]
> will it affect TiDB Wasm? @5kbpers

@siddontang  I make this PR is because of that people always don't remember to import mathutil in the right way and it will make tidb.wasm not compile. We build a CI to force people to do so, but many people will be confused about this. So we decide to make change only on tidb-wasm repo and keep tidb repo as same as there is no tidb.wasm.

**Comment by lucklove** [comment]
LGTM

**Pull request merged**
