### PR TITLE
statistics: fix build extended stats panic when met NULL

### LINKED ISSUE #23261: building extended stats fails sometimes when met NULL
## Bug Report

```sql
create table t(a int, b int);
Query OK, 0 rows affected (0.012 sec)

alter table t add stats_extended s1 correlation(a,b);
Query OK, 0 rows affected (0.003 sec)

insert into t values(1,null), (2,null);
Query OK, 2 rows affected (0.012 sec)
Records: 2  Duplicates: 0  Warnings: 0

analyze table t;
ERROR 1105 (HY000): analyze worker panic
```

version: master

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #23261 

### What is changed and how it works?

Consider that when building extended stats, `samplesX` and `samplesY` might have different lengths because NULL values are not in the `sampleCollector`.
And make sure that if the shortest length is 0 then the result is 0, if the shortest length is 1 then the result is 1.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- no release note.

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]
/LGTM

**Pull request merged**
