### PR TITLE
fix: auto_increment id range can not exceed int64

### LINKED ISSUE #3647: auto_increment ID range can not exceed int64 now
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
create table t(a bigint unsigned auto_increment primary key);
insert into t value(18446744073709551610);
```

2. What did you expect to see?
```
Query OK, 1 row affected (0.00 sec)
```

3. What did you see instead?
```
ERROR 1690 (22003): constant 18446744073709551610 overflows bigint
```

### PR DESCRIPTION
**Pull request by kirk91**
fix #3647

### CODE REVIEW

**Comment by shenli** [comment]
@kirk91 Thanks for your PR!
@zimulala PTAL

**Comment by zimulala** [comment]
@kirk91  The reason TiDB has this bug is that TiDB's auto_increament ID type is `int64`. So this PR isn't the best way to fix the #3647. If the auto_increament column is not set to a specific value then it needs to be incremented. Its behavior is as follows:
```
mysql> create table t(a bigint unsigned auto_increment primary key, b int);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t value(18446744073709551600,1);
Query OK, 1 row affected (0.01 sec)

mysql> insert into t set b=3;
Query OK, 1 row affected (0.01 sec)

mysql> select * from t;
+----------------------+------+
| a                    | b    |
+----------------------+------+
| 18446744073709551600 |    1 |
| 18446744073709551601 |    3 |
+----------------------+------+
2 rows in set (0.01 sec)
```

**Comment by kirk91** [comment]
Do you mean that we should switch the type of auto_increment ID to `uint64` ?   If we do that, there will be a lot of changes and some compatibility. Please correct me if I am wrong. @zimulala

**Comment by zimulala** [comment]
@kirk91  Yep. So we consider fixing the issue in the future.

**Comment by kirk91** [comment]
Okay, I got it. If possible, i will attempt to fix it.

**Comment by shenli** [comment]
@kirk91 Thanks! Should we close this PR and solve this issue in the future?

**Comment by kirk91** [comment]
@shenli Do you have an ETA? We want to try `TiDB` in our environment recently, and the records of data are one hundred million per day. If `auto_increment id` type is `int64`,  we can only store 21 days data which can't meet our product demands(keep three months data).

Also, I'm attempting to change the type of `auto alloc_id` to `uint64`, but the progress is slow due to unfamiliar with codes.

**Pull request closed without merging**
