### PR TITLE
expression: don't append null when param for char() is null

### LINKED ISSUE #29755: CI Test `sql/randgen-topn/7_str_1.sql` failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_copr_test/detail/tidb_ghpr_integration_copr_test/7023/pipeline/ 
```bash
[2021-11-12T15:15:26.044Z] Test case: sql/randgen-topn/7_str_1.sql

[2021-11-12T15:15:26.044Z] Statement: #375 -  SELECT CHAR( ( ASCII( ( BIN( ( CHAR_LENGTH( ( LEFT( ( UPPER( ( EXPORT_SET( 'y', `col_bigint_unsigned`, ( `col_set_key` - ( ASCII( 'gmsvqosqhivrmieqqtezsffwvoszhezibcspbywgiimtlgserocidhwnsndkqmjjewpiqnputwvrwozpndxpckahqxvytmbdpqkaspodvsrrvbiofahdbkieqapzripqukgspdnrwknbyfqugtwuiqbjkaxpyfaqxwuqqfjqcejrsggdeskqdisizfmrvplhaiiykpbuegucqcmrgdpb' ) ) ) ) ) ) ), -19280 ) ) ) ) ) ) ) ) ) AS field1, MID( '02:44:24.022704', `col_char_255`, ( `col_tinyint` OR ( MID( ( BIN( 'g' ) ), ( `col_tinyint` REGEXP -17576 ), 6661105323857674240 ) ) ) ) AS field2 FROM `table20_int_autoinc` WHERE ( `col_timestamp_key` + `col_float_key` ) ^ 24303 ORDER BY field1, field2 LIMIT 6 /* QNO 377 CON_ID 212 */ ;

[2021-11-12T15:15:26.044Z] NoPushDown Output: 

[2021-11-12T15:15:26.044Z] field1	field2

[2021-11-12T15:15:26.044Z] NULL	NULL

[2021-11-12T15:15:26.044Z] 	NULL

[2021-11-12T15:15:26.044Z] 0	

[2021-11-12T15:15:26.044Z] 0	

[2021-11-12T15:15:26.044Z] NULL	NULL

[2021-11-12T15:15:26.044Z] 	

[2021-11-12T15:15:26.044Z] 0	NULL

[2021-11-12T15:15:26.044Z] 0	NULL

[2021-11-12T15:15:26.044Z] 

[2021-11-12T15:15:26.044Z] 

[2021-11-12T15:15:26.044Z] WithPushDown Output: 

[2021-11-12T15:15:26.044Z] Error 1105: runtime error: index out of range [1] with length 1

[2021-11-12T15:15:26.044Z] 

[2021-11-12T15:15:26.044Z] 

[2021-11-12T15:15:26.044Z] NoPushDown Plan: 

[2021-11-12T15:15:26.044Z] id	estRows	actRows	task	access object	execution info	operator info	memory	disk

[2021-11-12T15:15:26.044Z] Projection_7	6.00	8	root		time:3.58ms, loops:2, Concurrency:OFF	char_func(ascii(bin(char_length(left(upper(export_set(0, cast(push_down_test_db.table20_int_autoinc.col_bigint_unsigned, var_string(20)), cast(minus(cast(push_down_test_db.table20_int_autoinc.col_set_key, double BINARY), 103), var_string(5)))), -19280)))), <nil>)->Column#62, mid(02:44:24.022704, cast(push_down_test_db.table20_int_autoinc.col_char_255, bigint(255) BINARY), or(push_down_test_db.table20_int_autoinc.col_tinyint, istrue_with_null(cast(mid(0, regexp(cast(push_down_test_db.table20_int_autoinc.col_tinyint, var_string(20)), -17576), 6661105323857674240), double BINARY))))->Column#63	N/A	N/A

[2021-11-12T15:15:26.044Z] └─Projection_14	6.00	6	root		time:2.6ms, loops:2, Concurrency:OFF	push_down_test_db.table20_int_autoinc.col_timestamp_key, push_down_test_db.table20_int_autoinc.col_float_key, push_down_test_db.table20_int_autoinc.col_char_255, push_down_test_db.table20_int_autoinc.col_set_key, push_down_test_db.table20_int_autoinc.col_tinyint, push_down_test_db.table20_int_autoinc.col_bigint_unsigned	N/A	N/A

[2021-11-12T15:15:26.044Z]   └─TopN_8	6.00	6	root		time:2.59ms, loops:2	Column#64, Column#65, offset:0, count:6	N/A	N/A

[2021-11-12T15:15:26.045Z]     └─Projection_15	8000.00	13	root		time:2.56ms, loops:2, Concurrency:5	push_down_test_db.table20_int_autoinc.col_timestamp_key, push_down_test_db.table20_int_autoinc.col_float_key, push_down_test_db.table20_int_autoinc.col_char_255, push_down_test_db.table20_int_autoinc.col_set_key, push_down_test_db.table20_int_autoinc.col_tinyint, push_down_test_db.table20_int_autoinc.col_bigint_unsigned, char_func(ascii(bin(char_length(left(upper(export_set(0, cast(push_down_test_db.table20_int_autoinc.col_bigint_unsigned, var_string(20)), cast(minus(cast(push_down_test_db.table20_int_autoinc.col_set_key, double BINARY), 103), var_string(5)))), -19280)))), <nil>)->Column#64, mid(02:44:24.022704, cast(push_down_test_db.table20_int_autoinc.col_char_255, bigint(255) BINARY), or(push_down_test_db.table20_int_autoinc.col_tinyint, istrue_with_null(cast(mid(0, regexp(cast(push_down_test_db.table20_int_autoinc.col_tinyint, var_string(20)), -17576), 6661105323857674240), double BINARY))))->Column#65	N/A	N/A

[2021-11-12T15:15:26.045Z]       └─TableReader_13	8000.00	13	root		time:1.41ms, loops:2, cop_task: {num: 1, max: 854µs, proc_keys: 0, rpc_num: 1, rpc_time: 839.8µs, copr_cache_hit_ratio: 0.00}	data:Selection_12	N/A	N/A

[2021-11-12T15:15:26.045Z]         └─Selection_12	8000.00	13	cop[tikv]		tikv_task:{time:568µs, loops:14}	bitxor(cast(plus(cast(push_down_test_db.table20_int_autoinc.col_timestamp_key, double BINARY), push_down_test_db.table20_int_autoinc.col_float_key), bigint(20) BINARY), 24303)	N/A	N/A

[2021-11-12T15:15:26.045Z]           └─TableFullScan_11	10000.00	20	cop[tikv]	table:table20_int_autoinc	tikv_task:{time:422.9µs, loops:21}	keep order:false, stats:pseudo	N/A	N/A

[2021-11-12T15:15:26.045Z] 

[2021-11-12T15:15:26.045Z] 

[2021-11-12T15:15:26.045Z] WithPushDown Plan: 

[2021-11-12T15:15:26.045Z] Failed to get plan: invalid connection

[2021-11-12T15:15:26.045Z] 

[2021-11-12T15:15:26.045Z] 2021/11/12 23:15:12 Test fail: Outputs are not matching.

[2021-11-12T15:15:26.045Z] Test case: sql/randgen-topn/7_str_1.sql

[2021-11-12T15:15:26.045Z] Statement: #750 -  SELECT CHAR( ( SUBSTR( ( ( `col_tinyint_key` + 'l' ) * `col_tinyint_unsigned` ) FROM ( UCASE( 'kqdisizfmrvplhaiiykpbuegucqcmrgdpbzaxtyajnnsccbsfpoeihgrjqcrnahvidqzlfkcajjlyqnjcfzwnqepnfpcqusxxdirxgbpkasebaacdgvpylxwpay' ) ) ) ) ) AS field1 FROM `table1000_int_autoinc`  ORDER BY field1 LIMIT 2 /* QNO 752 CON_ID 212 */ ;

[2021-11-12T15:15:26.045Z] NoPushDown Output: 

[2021-11-12T15:15:26.045Z] field1

[2021-11-12T15:15:26.045Z] NULL

[2021-11-12T15:15:26.045Z] 

[2021-11-12T15:15:26.045Z] NULL

[2021-11-12T15:15:26.045Z] 

[2021-11-12T15:15:26.045Z] 

[2021-11-12T15:15:26.045Z] 

[2021-11-12T15:15:26.045Z] WithPushDown Output: 

[2021-11-12T15:15:26.045Z] field1

[2021-11-12T15:15:26.045Z] 

[2021-11-12T15:15:26.045Z] NULL

[2021-11-12T15:15:26.045Z] 

[2021-11-12T15:15:26.045Z] 

[2021-11-12T15:15:26.045Z] 

[2021-11-12T15:15:26.045Z] 

[2021-11-12T15:15:26.045Z] NoPushDown Plan: 

[2021-11-12T15:15:26.045Z] Failed to get plan: Error 1094: Unknown thread id: 35

[2021-11-12T15:15:26.045Z] WithPushDown Plan: 

[2021-11-12T15:15:26.045Z] Failed to get plan: Error 1094: Unknown thread id: 37

[2021-11-12T15:15:26.045Z] 

[2021-11-12T15:15:26.045Z] 2021/11/12 23:15:25 Test summary: non-matching queries: 2, success queries: 879, skipped queries: 121

[2021-11-12T15:15:26.045Z] 2021/11/12 23:15:25 Test summary(sql/randgen-topn/7_str_1.sql): Test case FAIL

[2021-11-12T15:15:26.045Z] 
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #29755 

Problem Summary: a bug, caused by #29543

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
bug fix, caused by #29543, don't append null when param for char() is null
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @wjhuang2016 @zimulala @tangenta 
PTAL

**Review by wjhuang2016 — COMMENTED** [review]
resultBytes, err := enc.Decode(resultBytes, dBytes)
		if err != nil {
			b.ctx.GetSessionVars().StmtCtx.AppendWarning(err)
			result.AppendNull()
			continue
		}

Here

**Comment by Defined2014** [comment]
> ```
> 	resultBytes, err := enc.Decode(resultBytes, dBytes)
> 	if err != nil {
> 		b.ctx.GetSessionVars().StmtCtx.AppendWarning(err)
> 		result.AppendNull()
> 		continue
> 	}
> ```
> 
> Here

It's fine. We should add `null` when decode failed. @wjhuang2016

**Review by wjhuang2016 — APPROVED** [review]

**Comment by Defined2014** [comment]
/cc @xiongjiwei 
PTAL

**Review by xiongjiwei — APPROVED** [review]

**Pull request merged**
