### PR TITLE
br/pkg/backup: migrate test-infra to testify

### LINKED ISSUE #28164: migrate test-infra to testify for `br/pkg/backup`

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

### What problem does this PR solve?

Issue Number: close #28164

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
ping @glorv @hawkingrei @YuJuncen

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
@tangenta PTAL

**Review by tangenta — APPROVED** [review]

**Pull request merged**
