### PR TITLE
executor, infoschema: fix display of on update CURRENT_TIMESTAMP with decimal (#11480)

### PR DESCRIPTION
**Pull request by tangenta**
Cherry-pick #11480. Blocked by pingcap/parser#565.

### CODE REVIEW

**Comment by bb7133** [comment]
please fiix the CI

**Comment by tangenta** [comment]
@bb7133 PTAL at pingcap/parser#565.

**Comment by zz-jason** [comment]
@tangenta please resolve conflicts

**Comment by tangenta** [comment]
@zz-jason PTAL at pingcap/parser#565.

**Comment by zz-jason** [comment]
@tangenta the PR on parser has been merged. Please update this PR so we can merge it as well.

**Pull request merged**
