### PR TITLE
executor: make insert dup on subquery return more than one row behavior compatible with MySQL

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve? 

TiDB insert on dup execution,  expressions will be calculated during expression_rewrite phase before stmt actual execution, different from MySQL behaviors.  MySQL will try to insert ,   if there's conflictions "on dup update" then error will be reported, so if the insertion succeed, MySQL does not care whether update expressions is ok, subquery expression is one that we've met.

here's some different behaviors
```
If possible, provide a recipe for reproducing the error.
CREATE TABLE t1(a INTEGER);
CREATE TABLE t11(a INTEGER primary key);
CREATE TABLE t2(b INTEGER);
INSERT INTO t2 VALUES (1),(1);

INSERT INTO t1(a) VALUES (1)
ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);

INSERT INTO t11(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);

DROP TABLE t1, t2;
What did you expect to see
MySQL behavior:
for inserting into t1

INSERT INTO t1(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
Query OK, 1 row affected (0.01 sec)
INSERT INTO t1(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
Query OK, 1 row affected (0.01 sec)

for inserting into t11
INSERT INTO t11(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
Query OK, 1 row affected (0.02 sec)

INSERT INTO t11(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
ERROR 1105 (HY000): subquery returns more than 1 row

TiDB behvaior:
for inserting into t1
mysql> INSERT INTO t1(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
ERROR 1105 (HY000): subquery returns more than 1 row
mysql> INSERT INTO t1(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
ERROR 1105 (HY000): subquery returns more than 1 row

for inserting into t11
mysql> INSERT INTO t11(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
ERROR 1105 (HY000): subquery returns more than 1 row  
```

I'm not quite sure if it's better to make this compatible
 PTAL

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Side effects

 - Increased code complexity
 - Breaking backward compatibility

Related changes

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@jackysp PTAL

**Comment by cfzjywxk** [comment]
@jackysp  PTAL

**Comment by jackysp** [comment]
This behavior is really unreasonable. I think that we could hold this PR, too.

**Comment by zz-jason** [comment]
@cfzjywxk @jackysp any update? Do we still need to process this PR?

**Comment by cfzjywxk** [comment]
> @cfzjywxk @jackysp any update? Do we still need to process this PR?

close it, repopen if needed in the future

**Pull request closed without merging**
