### PR TITLE
ddl: remove the useless function

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Problem Summary:

Remove the useless function.

### What is changed and how it works?

What's Changed:
Remove `checkJobMaxInterval`.

### Check List 

Tests 

- No code

### Release note 

- No release note

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by jackysp — COMMENTED** [review]
LGTM

**Review by tangenta — COMMENTED** [review]
/lgtm

**Review by xiongjiwei — COMMENTED** [review]
LGTM

**Review by xiongjiwei — APPROVED** [review]

**Pull request merged**
