### PR TITLE
planner, MPP: fix two bugs about group by duplicated and sort by exprs (#29363)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #29363 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/29428
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/29428:release-5.3-f77189b9735d
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tics/issues/3335,close https://github.com/pingcap/tics/issues/3337
close https://github.com/pingcap/tics/issues/3359

Problem Summary:
https://github.com/pingcap/tics/issues/3337 caused by 0 == 'gg'
https://github.com/pingcap/tics/issues/3335 caused by sort by items.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by fzhedu — APPROVED** [review]
/LGTM

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
