### PR TITLE
metrics/grafana: Remove duplicate items "Owner Watcher OPS"

### PR DESCRIPTION
**Pull request by newHE3DBer**
### What problem does this PR solve?

- Remove duplicate items "Owner Watcher OPS" from tidb grafana

Problem Summary:

- duplicate items "Owner Watcher OPS" from tidb grafana

What's Changed:

- duplicate items "Owner Watcher OPS" from tidb grafana

How it Works:

- Replace tidb.json and restart the cluster

Check List

- Replace tidb.json and restart the cluster

Release note

- Remove duplicate items "Owner Watcher OPS" from tidb grafana

### CODE REVIEW

**Comment by newHE3DBer** [comment]
@gregwebs

**Comment by newHE3DBer** [comment]
/rebuild/

**Comment by newHE3DBer** [comment]
/rebuild/

**Comment by newHE3DBer** [comment]
/rebuild/

**Comment by newHE3DBer** [comment]
image
tidb metrics/grafana: duplicate items "Owner Watcher OPS"

**Comment by newHE3DBer** [comment]
image
tidb metrics/grafana: remove duplicate items "Owner Watcher OPS"

**Comment by newHE3DBer** [comment]
Has anyone verified this department code?

**Comment by newHE3DBer** [comment]
Has anyone verified this department code?

**Review by gregwebs — APPROVED** [review]

**Review by zz-jason — COMMENTED** [review]
@newHE3DBer thanks for your contribution, could you add a test to ensure that this duplication won't happen again?

**Comment by newHE3DBer** [comment]
package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"strings"
)
type panel struct {
	Title string `json:"title"`
}

type panels struct {
	Pa []panel `json:"panels"`
}

type panels1 struct {
	Panels []panels `json:"panels"`
}
func main() {
	panels1 := panels1{}
	var count = 0
	data,_:= ioutil.ReadFile("E:/tidb.json")
	json.Unmarshal(data, &panels1)
    for _,title :=  range panels1.Panels[12].Pa{
		if strings.Compare("Owner Watcher OPS",title.Title) == 0{
			count++
		}
	}
	if count == 1{
		fmt.Print("Remove duplicate items \"Owner Watcher OPS\" from tidb grafana")
	}
}

Can you tell me which module of tidb this test code is placed in?  

/cc zz-jason

**Pull request merged**
