### PR TITLE
server: Remove rwlock in server

### PR DESCRIPTION
**Pull request by yanzhe-chen**
This is for Github issue [803](https://github.com/pingcap/tidb/issues/803).

PTAL. Thanks!

### CODE REVIEW

**Comment by siddontang** [comment]
If we remove this lock, how to guarantee concurrent access clients map safely?

**Comment by yanzhe-chen** [comment]
Different clients should have different `connectionID` so they should not conflict on clients map.

**Comment by siddontang** [comment]
A simple test here:
```
func TestMap(t *testing.T) {
	m := map[int]int{}

	var wg sync.WaitGroup

	wg.Add(2)

	n := 10000

	go func() {
		defer wg.Done()
		for i := 0; i < n; i++ {
			m[i] = i
		}
	}()

	go func() {
		defer wg.Done()
		for i := n; i < 2*n; i++ {
			m[i] = i
		}
	}()

	wg.Wait()
}
```

two different goroutine handles the map with different keys, but `go test --race` will raise DATA RACE error. it is no safe.

**Comment by yanzhe-chen** [comment]
@siddontang Oh! I misunderstand the concepts in thread-safety on map. Even the keys differ, they might still conflict on the internal meta-data. Thanks a lot! :-)

**Pull request closed without merging**
