### PR TITLE
server: prefetch for DELETE and BatchPointGet when multi-statement

### LINKED ISSUE #41367: use multi-statement to speed up SQL repllication
## Enhancement

executor can look at all statement, find if they are point-get plans or batch point-get plans, fetch all KV once.

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #41367

ref https://github.com/pingcap/tiflow/pull/8395

Problem Summary: improve replication speed when using multi-statement (Data Migration scenario)

### What is changed and how it works?

copy the prefetch logic for UPDATE, and GitHub copilot is very helpful 😆 

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

**Review by xuyifangreeneyes — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by lance6716** [comment]
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/20021/pipeline 

TestIndexMergeUpgradeFrom300To540 failed for 3 times

**Pull request merged**
