### PR TITLE
add pronounce guide in readme

### PR DESCRIPTION
**Pull request by c4pt0r**

### CODE REVIEW

**Comment by c4pt0r** [comment]
@queenypingcap

**Comment by shenli** [comment]
@queenypingcap PTAL

**Comment by coocood** [comment]
I think this should be added in FAQ.

**Comment by shenli** [comment]
LGTM
@coocood PTAL

**Comment by coocood** [comment]
I thought it was /'taɪdiːbi:/.

**Comment by c4pt0r** [comment]
done @coocood

**Comment by coocood** [comment]
LGTM

**Pull request merged**
