### PR TITLE
server: fix connection string collation

### PR DESCRIPTION
**Pull request by coocood**
fixes https://github.com/pingcap/tidb/issues/1810

### CODE REVIEW

**Comment by coocood** [comment]
@siddontang @zimulala PTAL

**Comment by zimulala** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Comment by tiancaiamao** [comment]
oh, add test case if any bug related to it.

**Comment by coocood** [comment]
@tiancaiamao It's just used for logging.

**Pull request merged**
