### PR TITLE
*: fix bug of same type plans with different plan ... (#19519)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19519 to release-4.0

---

Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

close https://github.com/pingcap/tidb/issues/19516.

### What is changed and how it works?

The cause of same type plan with different digest is:

1. The Plan ID of plan may be changed, we should ignore the plan ID when normalized plan.
2. The Column Unique ID maybe also changed, we should also ignore the column unique id when normalized column info.
3. Fix the `PhysicalIndexScan` implementation of `PhysicalIndexJoin`, `PhysicalTableReader `, `PhysicalIndexScan ` , `basePhysicalAgg`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- No

### Release note 

- Fix issue of same type plans with different plan digest.

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
@crazycs520 please resolve the conflicts.

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by tangenta — COMMENTED** [review]
LGTM

**Review by zz-jason — APPROVED** [review]
LGTM

**Pull request merged**
