### PR TITLE
*: add trace support for the `AllocAutoIncrementValue` function

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

`AllocAutoIncrementValue` may need to visit the network and be slow, add trace support for it.

```
mysql> create table xx (a int, b int key auto_increment);
Query OK, 0 rows affected (0.03 sec)
mysql> trace insert into xx (a) values (666);
```

For example, from the following image, we can see that dominant cost in `InsertExec.Next` is `AllocAutoIncrementValue`.

image

And `AllocAutoIncrementValue` is much faster after the first time it's been executed, because alloc would cache a batch of ids:

```
mysql> trace format='row' insert into xx (a) values (66);
+----------------------------------------+-----------------+------------+
| operation                              | startTS         | duration   |
+----------------------------------------+-----------------+------------+
| session.getTxnFuture                   | 11:08:11.924668 | 4.009µs    |
|   ├─session.Execute                    | 11:08:11.924660 | 940.11µs   |
|   ├─session.ParseSQL                   | 11:08:11.924717 | 33.085µs   |
|   ├─executor.Compile                   | 11:08:11.924775 | 80.327µs   |
|   ├─session.runStmt                    | 11:08:11.924876 | 669.409µs  |
|   ├─executor.handleNoDelayExecutor     | 11:08:11.924904 | 170.199µs  |
|   ├─*executor.InsertExec.Next          | 11:08:11.924913 | 142.591µs  |
|   ├─table.AllocAutoIncrementValue      | 11:08:11.924971 | 6.702µs    |
|   └─session.CommitTxn                  | 11:08:11.925113 | 396.121µs  |
+----------------------------------------+-----------------+------------+
9 rows in set (0.01 sec)
```

### What is changed and how it works?

Add those lines to `AllocAutoIncrementValue`:

```
	if span := opentracing.SpanFromContext(ctx); span != nil && span.Tracer() != nil {
		span1 := span.Tracer().StartSpan("table.AllocAutoIncrementValue", opentracing.ChildOf(span.Context()))
		defer span1.Finish()
	}
```

Tiny refactor for the `ctx` parameter in `AllocAutoIncrementValue`.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Code changes

 - Has exported function/method change

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @lysu @jackysp

**Comment by jackysp** [comment]
Great!

**Comment by tiancaiamao** [comment]
PTAL @lysu

**Pull request merged**
