### PR TITLE
statistics: change default value of tidb_analyze_version to 1

### LINKED ISSUE #31748: statistics: do not use analyze version 2 as default config for new clusters since it was an experimental feature
## Enhancement
Since a lot of customers reported OOM when they are doing analyze table due to tidb_analyze_version = 2 in v5.1 and v5.2, and as this was defined as experimental feature, so we suggest not to use version 2 by default. Let's keep  tidb_analyze_version = 1 as default set for v5.1.x and v5.2.x.

affected version: v5.1.x and v5.2.x.

### PR DESCRIPTION
**Pull request by yiwen92**
### What problem does this PR solve?

Issue Number: close #31748

Problem Summary:

### What is changed and how it works?
Set the default value for tidb_analyze_version to 1 to avoid OOM issues, because this was an experimental feature in v5.1 and v5.2
### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [X] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Set default value of tidb_analyze_version to 1 in v5.1 and v5.2
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]

**Comment by yiwen92** [comment]
I found FAIL in statistics test, tried several times but still not PASS, then ask @winoros to address this problem now.

**Comment by bb7133** [comment]
@winoros Please fix the test case

**Comment by yiwen92** [comment]
Also add doc modification for this tidb_analyze_version system variable in https://github.com/pingcap/docs/pull/7569 and https://github.com/pingcap/docs-cn/pull/8364

**Pull request merged**
