### PR TITLE
 types: fix doDivMod algorithm

### LINKED ISSUE #4873: types.DecimalDiv has a bug if the format of arg "from2" like "0.0xxx"
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
using types.MyDecimal
```
package main

import (
	"fmt"
	"github.com/pingcap/tidb/util/types"
)

func main() {
	cD := &types.MyDecimal{}
	cD.FromString([]byte("51"))
	rD := &types.MyDecimal{}
	rD.FromString([]byte("0.003430"))
	result := &types.MyDecimal{}
	err := types.DecimalDiv(cD, rD, result, 6)
	if err != nil {
		fmt.Printf("DecimalDiv err:%s", err)
		return
	}
	fmt.Printf("%v", result)
}
```
2. What did you expect to see?

expected 14868.804665
3. What did you see instead?
but 14868.000000
4. What version of TiDB are you using (`tidb-server -V`)?
git-master

### PR DESCRIPTION
**Pull request by mccxj**
fix #4873. minor diff from mysql's do_div_mod method.

### CODE REVIEW

**Comment by shenli** [comment]
@mccxj Thanks!
@XuHuaiyu @zz-jason PTAL

**Comment by shenli** [comment]
@coocood PTAL

**Comment by coocood** [comment]
LGTM

Thank you!

**Comment by mccxj** [comment]
unit tests donot look very stable.

**Comment by coocood** [comment]
@mccxj 
There is a similar bug at TiKV coprocessor
https://github.com/pingcap/tikv/blob/master/src/coprocessor/codec/mysql/decimal.rs#L594

Would you please fix that too?

**Comment by mccxj** [comment]
@coocood I 'm a Rust beginner, but I will have a try.

**Pull request merged**
