### PR TITLE
planner/core: fix range info for the inner child of index join in `explain` (#8058)

### PR DESCRIPTION
**Pull request by jarvys**
### What problem does this PR solve? 

fix issue #8058 , fix range info for the inner child of index join.

### What is changed and how it works?

Add two more fields `rangesWithFakeConds` and `keyOff2IdxOff` to struct `PhysicalIndexScan`. When the `ExplainInfo` method called, generate range info with these two fields, not only with `rangeDecidedBy`.

### Check List 

Tests 

 - Unit test: add `TestIssue8058` in cbo_test.go

Code changes

 - Has exported function/method change

Side effects

 - Nothing

Related changes

- Nothing

### CODE REVIEW

**Comment by shenli** [comment]
@jarvys Thanks! Please fix the CI.

**Comment by winoros** [comment]
Hi, thanks for your contribution.
1. please take a look at https://github.com/pingcap/tidb/pull/8471. When the index join support using `t.c > tt.c and t.c < tt.c + 100` to construct ranges. The way you used cannot show enough information.
1. And you can just pass a string information to `IndexScan` to avoid add more fields to it. IMHO, Using three fields just to construct explain information is a little expensive.
1. You can use `make dev` to make sure you pass all the unit-test and the `explain test` in `cmd/explaintest`.

**Comment by jarvys** [comment]
@winoros Thanks for code review!

**Comment by jarvys** [comment]
@winoros I have made all the test cases passed by modifying the expect result of some test cases. I don't understand how the PR #8471 works now. I'm learning it.

**Comment by jarvys** [comment]
@winoros I have made all the test cases passed by modifying the expect result of some test cases. I don't understand how the PR #8471 works now. I'm learning it. 

I find you use the `buildRangeDecidedByInformation` method to build range info :)

**Comment by jarvys** [comment]
@winoros I find issue #9562. Maybe it's better to fix it first before the problems in #8471 and #9528

**Comment by winoros** [comment]
closed since https://github.com/pingcap/tidb/pull/8471 has done the same thing.

**Pull request closed without merging**
