### PR TITLE
*: update unstable unit test case list 0412-0419

### PR DESCRIPTION
**Pull request by heibaijian**
Signed-off-by: lvhongmeng [hongmeng.lv@pingcap.com](mailto:hongmeng.lv@pingcap.com)

What problem does this PR solve?
Issue Number: ref https://github.com/pingcap/tidb/issues/32303

Problem Summary:

What is changed and how it works?
Check List
Unit test
Integration test
Manual test (add detailed scripts or steps below)
No code
Side effects

Performance regression: Consumes more CPU
Performance regression: Consumes more Memory
Breaking backward compatibility
Documentation

Affects user behaviors
Contains syntax changes
Contains variable changes
Contains experimental features
Changes MySQL compatibility

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by tiancaiamao** [comment]
The list doesn't become shorter... instead of just skipping, we need to make people fix them.

**Pull request merged**
