### PR TITLE
executor: check storage.block-cache.capacity value

### LINKED ISSUE #17925: Add SQL diagnosis rule: check the storage.block-cache.capacity value
## Introduce

The problem of https://github.com/pingcap/tidb/issues/17434 is the `storage.block-cache.capacity` config value too small.

## Task

Add diagnose rule such as :  if`storage.block-cache.capacity < 0.1 * total_server_memory / tikv_count_in_server` is true, then return an warning. 

## Refer

* You can query the `cluster_config` table to get the related config value. 
* You can refer the `configInspection` implementation in TiDB.

If you have any questions or want to discuss something, you can chat in the [sig-dashboard](https://tidbcommunity.slack.com/archives/CUQDYENTE) slack channel and @ `crazycs520`.

### PR DESCRIPTION
**Pull request by luxinle**
### What problem does this PR solve?

Issue Number: close #17925 

Problem Summary:

### What is changed and how it works?

What's Changed:
Add check the lower value of  `storage.block-cache.capacity`  in checkTiKVBlockCacheSizeConfig func in executor\inspection_result.go
How it Works:

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by zz-jason** [comment]
@crazycs520 @breeswish PTAL

**Review by crazycs520 — COMMENTED** [review]
/LGTM

**Comment by feitian124** [comment]
this pr did not merged and pending for a long time .
@luxinle are you still working on this? it may need a rebase to proceed

**Comment by zz-jason** [comment]
I'm going to close this PR since it hasn't been updated for a long time. Feel free to reopen it once you wish to advance this PR in the future.

**Pull request closed without merging**
