### PR TITLE
expression: don't set charset of RetType to binary for `date_add` and `date_sub` func

### LINKED ISSUE #31809: Return type of `DATE_ADD` is wrong
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```mysql
select DATE_ADD('2001-01-01 00:00:00.000000', INTERVAL 1 SECOND);
```

### 2. What did you expect to see? (Required)
```mysql
mysql> select DATE_ADD('2001-01-01 00:00:00.000000', INTERVAL 1 SECOND);
+-----------------------------------------------------------+
| DATE_ADD('2001-01-01 00:00:00.000000', INTERVAL 1 SECOND) |
+-----------------------------------------------------------+
| 2001-01-01 00:00:01                                       |
+-----------------------------------------------------------+
1 row in set (0.00 sec)
```
### 3. What did you see instead (Required)
```mysql
mysql> select DATE_ADD('2001-01-01 00:00:00.000000', INTERVAL 1 SECOND);
+----------------------------------------------------------------------------------------------------------------------+
| DATE_ADD('2001-01-01 00:00:00.000000', INTERVAL 1 SECOND)                                                            |
+----------------------------------------------------------------------------------------------------------------------+
| 0x323030312D30312D30312030303A30303A3031                                                                             |
+----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

7fd298d9@master

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #31809 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Don't set charset of RetType to binary for `date_add` and `date_sub` func
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @wjhuang2016 @xiongjiwei @mengxin9014
PTAL

**Review by xiongjiwei — APPROVED** [review]

**Comment by Defined2014** [comment]
/cc @tangenta 
PTAL

**Review by tangenta — APPROVED** [review]

**Comment by mengxin9014** [comment]
LGTM

**Pull request merged**
