### PR TITLE
partition: fix ExchangePartition bug when partition table with global index

### LINKED ISSUE #46165: Exchange partition should forbiden parition table with global index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `nt` (
  `a` int(11) DEFAULT NULL,
  `b` int(11) DEFAULT NULL,
  UNIQUE KEY `u_idx` (`b`)
);

CREATE TABLE `pt` (
  `a` int(11) DEFAULT NULL,
  `b` int(11) DEFAULT NULL,
  UNIQUE KEY `u_idx` (`b`)
) PARTITION BY RANGE (a) (PARTITION p0 VALUES LESS THAN (10),PARTITION p1 VALUES LESS THAN (MAXVALUE));

alter table pt exchange partition p0 with table nt;
```

### 2. What did you expect to see? (Required)

return error

### 3. What did you see instead (Required)

return success.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #46165

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by mjonss — COMMENTED** [review]
LGTM, I will just wait for the test to complete before approving.

**Review by mjonss — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
