### PR TITLE
lightning: hide sensitive log for server mode lightning

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/36374

Problem Summary:

### What is changed and how it works?
Add `HideSensitive` to filter sensitve information before printing it to log. 

### Check List

Tests 

- [x] Unit test
- [ ] Integration test

Side effects

- None

Documentation

- None

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lichunzhu** [comment]
@dsdashun PTAL

**Review by gozssky — APPROVED** [review]

**Review by dsdashun — APPROVED** [review]
LGTM

**Review by lance6716 — APPROVED** [review]

**Comment by Mini256** [comment]
/run-cherry-picker

Reference: https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/cherrypick-a-pr.html#ti-srebot

**Comment by you06** [comment]
Because 6.2 is checkout after this PR merge, this PR is already included in release-6.2

**Pull request merged**
