### PR TITLE
expression: make TIME function compatible with MySQL (#19158)

### LINKED ISSUE #19158: Incompatible TIME() with MySQL
### 1. Minimal reproduce step (Required)
```sql
select TIME(60);
```

### 2. What did you expect to see? (Required)

```
+----------+
| TIME(60) |
+----------+
| NULL     |
+----------+
```

### 3. What did you see instead (Required)

```
+----------+
| TIME(60) |
+----------+
| 00:00:00 |
+----------+
```

### 4. What is your TiDB version? (Required)
Release Version: v4.0.0-beta.2-944-gae779e150
Edition: Community
Git Commit Hash: ae779e1502cf99d65511387a4e1eb171bd9eb9c7
Git Branch: master
UTC Build Time: 2020-08-11 03:55:14
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by dragonly**
### What problem does this PR solve?

Issue Number: close #19158

Problem Summary:

### What is changed and how it works?

What's Changed:
`SELECT TIME(60);` now returns NULL

How it Works:
check parsed HHMMSS, when MM > 60 || SS > 60, caller should handle this condition differently

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

None

### Release note 

- MySQL compatibility changes

### CODE REVIEW

**Review by ichn-hu — CHANGES_REQUESTED** [review]
Perhaps add a flag `allowOverflow` to `ParseDuration` might be a better solution.

**Comment by dragonly** [comment]
> Perhaps add a flag `allowOverflow` to `ParseDuration` might be a better solution.

Then all the callers of `ParseDuration` (**over 80**) must be modified to pass `allowOverflow = false` in the parameters, or tricks must be used to provide default parameter value ([such as in this sof answer](https://stackoverflow.com/a/23650312/2497338)).

**Comment by zz-jason** [comment]
I'm going to close this PR since it hasn't been updated for a long time. feel free to reopen if you want to continue with it. thank you for your contribution.

**Pull request closed without merging**
