### PR TITLE
expression: refine built-in func truncate to support uint arg (#8000)

### LINKED ISSUE #7591: consider unsigned int for built-in function truncate
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
``` sql
CREATE TABLE `t` (
  `a` bigint(20) UNSIGNED DEFAULT NULL
);
insert into t value(cast(a as unsigned));;
```

2. What did you expect to see?
``` sql
mysql> select truncate(a, 1) from t;
+----------------------+
| truncate(a, 1)       |
+----------------------+
| 18446744073709551615 |
+----------------------+
1 row in set (0.01 sec)
```


3. What did you see instead?
``` sql
tidb> select truncate(a, 1) from t;
+----------------+
| truncate(a, 1) |
+----------------+
|           NULL |
+----------------+
1 row in set (0.00 sec)
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
``` sql
tidb> select tidb_Version();
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_Version()                                                                                                                                                                                                                                                                                                                      |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v2.1.0-rc.1-41-g3d891d9c2
Git Commit Hash: 3d891d9c2666a4812f77fc286d696f279a9e8e4c
Git Branch: master
UTC Build Time: 2018-09-03 08:14:20
GoVersion: go version go1.10.3 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

### LINKED ISSUE #7615: Wrong behavior on builtin function `truncate`
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

`select truncate(9223372036854775808, -10);`

TiDB don't handle the unsigned int case of this function.

2. What did you expect to see?

```
+------------------------------------+
| truncate(9223372036854775808, -10) |
+------------------------------------+
|                9223372030000000000 |
+------------------------------------+
```

3. What did you see instead?

```
mysql> select truncate(9223372036854775808, -10);
+------------------------------------+
| truncate(9223372036854775808, -10) |
+------------------------------------+
|                9223372043709551616 |
+------------------------------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master branch 129f499f9b5f5fe52a90c15abe4fdb858ad43e7e

### PR DESCRIPTION
**Pull request by yu34po**
### What problem does this PR solve? 
fix #7591
fix #7615

### What is changed and how it works?
1.add an builtinTruncateUintSig Function to support unsigned int truncate
2.change builtinTruncateIntSig truncate function to avoid get incorrect value

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change

Side effects

Related changes

### CODE REVIEW

**Comment by winoros** [comment]
@yu34po Please fill the pr description.

**Comment by XuHuaiyu** [comment]
@yu34po 
We need do some modification, since the input argument type if types.Row:
`func (b *builtinTruncateIntSig) evalInt(row types.Row) (int64, bool, error) {...}`

**Comment by lysu** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by WangXiangUSTC** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by zz-jason** [comment]
LGTM
@XuHuaiyu PTAL

**Pull request merged**
