### PR TITLE
lightning: support custom file listing policy

### LINKED ISSUE #38598: Lightning: Support Custom File Iteration Algorithm when Constructing MDLoader
## Enhancement
The `MDLoader` is the abstraction that stores the result of scanning the data source with file route rules and filters.  However, in some situations, we don't need to iterate ALL the data source files to construct a complete MDLoader object.  Instead, we just need to pick a few of key files in the data source to construct the information we want in MDLoader, so that the performance for generating an `MDLoader` can be boosted.

Currently, the file iteration logic cannot be customized, all we have is using the `ExternalStorage` interface, which provides a `WalkDir` method to iterate ALL the files in the data source.  We want to make the iteration logic customizable.

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: close #38598 

Problem Summary:

### What is changed and how it works?
Extract the file iteration logic as an interface (`FileIterator`), and make the current logic as the default implementation of the interface.  

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by dsdashun** [comment]
integration br test passed: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_br_test/detail/tidb_ghpr_integration_br_test/10903/pipeline

**Pull request merged**
