### PR TITLE
session: migrate test-infra to testify for isolation_test.go

### LINKED ISSUE #28324: migrate test-infra to testify for `session/isolation_test.go`

### PR DESCRIPTION
**Pull request by tisonkun**
### What problem does this PR solve?

Issue Number: close #28324 close #32069

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
/cc @hawkingrei @Defined2014 

We finally overcome `withTikv`. Thank @Defined2014 for #32260.

**Comment by tisonkun** [comment]
@hawkingrei check_dev_2 failed just on isolation_test.go when `withTikv` set to `true`...

**Comment by tisonkun** [comment]
https://github.com/PingCAP-QE/ci/blob/cfbe08427c8b4a4282c373d38f6e552b1efa7ff9/jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy#L330-L332

I guess something in PingCAP-QE/ci should be changed.

**Comment by tisonkun** [comment]
It's possibly some setting on https://github.com/PingCAP-QE/ci/blob/cfbe08427c8b4a4282c373d38f6e552b1efa7ff9/jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy#L327-L332 can be changed.

**Comment by tisonkun** [comment]
closed as I don't have enough knowledge to overcome the test.

**Comment by tisonkun** [comment]
@bb7133 I push a commit 1eae1679db7a689eaf6c599ad49cf8ed8cad7c3f to try to keep session state isolated.

**Comment by tisonkun** [comment]
Also it's possibly that pessimistic tests set session variable to avoid changing global variable or restore original state later.

**Comment by tisonkun** [comment]
Finally we overcome it. Thanks to @bb7133!

/cc @bb7133 @Defined2014 @hawkingrei

**Comment by tiancaiamao** [comment]
If we support multi tenant on shared storage, this problem can be fixed natually...
Thinking in the reverse direction, if we solve this in a right way, we're supporting multi tenant somehow.

**Comment by tisonkun** [comment]
@tiancaiamao yep. For the specific tests, I think set session variable explicit to override global variable is ok and should be stable.

Is there other change should be taken for this PR?

**Review by tiancaiamao — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
