### PR TITLE
[DNM] parser: use allocator to reduce object allocation

### PR DESCRIPTION
**Pull request by tiancaiamao**
pprof shows that parser allocates a lot of small objects, which are bad for GC.
this PR introduce an allocator for parser and reuse memory.

benchmark shows before vs after:
> insert test data finished ... elapse : 50.004219s tps:19998.312553
> insert test data finished ... elapse : 39.723894s tps:25173.765945

bench tested on memory engine, so the real boost may not that much.
but it does reduce `yyParse` allocation percentage from about 12.xx% to 4.65%.

### CODE REVIEW

**Comment by coocood** [comment]
We only need to alloc `ast.ValueExpr`, other types just used once in a statement, they don't worth the effort to use allocator.

**Comment by coocood** [comment]
Why delete 'parser_test.go' ?

**Comment by tiancaiamao** [comment]
Yes, not all types used frequently, but apart from `ast.ValueExpr`, there are FieldTypes and several other types should be added to allocator.
I'll add parser_test.go back in next commit.

**Comment by tiancaiamao** [comment]
PTAL @coocood @shenli

**Comment by tiancaiamao** [comment]
This change introduces complexity but doesn't improve performance as much as I've expected,
so I would close it until I find a much better way.

**Pull request closed without merging**
