### PR TITLE
planner: Remove redundant call to expression.ColumnSubstitute

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

Remove a redundant call to `expression.ColumnSubstitute` as the result is already calculated before.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by mmyj** [comment]
Please format the title and fill in the release note.

**Comment by yeya24** [comment]
Hello, can I get another review for this pr?

**Comment by mmyj** [comment]
PTAL @winoros

**Comment by bb7133** [comment]
Hi @yeya24 , thanks for your contribution!

**Pull request merged**
