### PR TITLE
statistics: fix merge idx hist with poped topn

### PR DESCRIPTION
**Pull request by rebelice**
### What problem does this PR solve?

fix merge index hist with poped `topn`.

Problem Summary:

### What is changed and how it works?

For different types of histograms, use different ways to decode `poped topn`.

 - index hist: []byte of Datum
 - column hist: decode to the corresponding type of Datum

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- No release note

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
/LGTM

**Review by Reminiscent — APPROVED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
