### PR TITLE
executor: fix 2nd index dup check after insert ignore on dup update primary

### LINKED ISSUE #23809: ignore dup error after insert on duplicate get wrong result in clustered index or int pk table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create nonclustered table ..insert then insert ignore ..check last table result

```
create table t2(`col_25` set('Alice','Bob','Charlie','David') NOT NULL,`col_26` date NOT NULL DEFAULT '2016-04-15', PRIMARY KEY (`col_26`) nonclustered, UNIQUE KEY `idx_9` (`col_25`,`col_26`),UNIQUE KEY `idx_10` (`col_25`));
insert into t2(col_25, col_26) values('Bob', '1989-03-23'),('Alice', '2023-11-24'), ('Charlie', '2023-12-05');
insert ignore into t2 (col_25,col_26) values ( 'Bob','1977-11-23' ) on duplicate key update col_25 = 'Alice', col_26 = '2036-12-13' ;
select * from t2;
```

rerun with clustered index table

```
create table t2(`col_25` set('Alice','Bob','Charlie','David') NOT NULL,`col_26` date NOT NULL DEFAULT '2016-04-15', PRIMARY KEY (`col_26`) clustered, UNIQUE KEY `idx_9` (`col_25`,`col_26`),UNIQUE KEY `idx_10` (`col_25`));
insert into t2(col_25, col_26) values('Bob', '1989-03-23'),('Alice', '2023-11-24'), ('Charlie', '2023-12-05');
insert ignore into t2 (col_25,col_26) values ( 'Bob','1977-11-23' ) on duplicate key update col_25 = 'Alice', col_26 = '2036-12-13' ;
select * from t2;
```

### 2. What did you expect to see? (Required)

same result

### 3. What did you see instead (Required)

non-clustered *(RIGHT)*

```
mysql> select * from t2;
+---------+------------+
| col_25  | col_26     |
+---------+------------+
| Alice   | 2023-11-24 |
| Bob     | 1989-03-23 |
| Charlie | 2023-12-05 |
+---------+------------+
3 rows in set (0.01 sec)
```

clustered

```
+---------+------------+
| col_25  | col_26     |
+---------+------------+
| Alice   | 2023-11-24 |
| Charlie | 2023-12-05 |
+---------+------------+
```

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Issue Number: close #23809 

Problem Summary:

see more detail at 

https://github.com/pingcap/tidb/issues/23809#issuecomment-811907423

### What is changed and how it works?

What's Changed, How it Works:

remove old record if new record can added

### Related changes

- Need to cherry-pick to the release branch 5.0 / 4.0?

### Check List 

Tests 

- Unit test

Side effects

- n/a

### Release note 

- Fix insert ignore on duplicate may delete wrong record

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/23814)

### CODE REVIEW

**Review by cfzjywxk — APPROVED** [review]
/lgtm

**Comment by jackysp** [comment]
Hold on @coocood @cfzjywxk .

**Pull request merged**
