### PR TITLE
plan: fix failed case when do index nested loop join

### PR DESCRIPTION
**Pull request by winoros**
Because of predicate push down, there may be a selection between join and data source, this case can also be converted to index nested loop join.
This pr is to fix this.
PTAL @shenli @hanfei1991 @coocood

### CODE REVIEW

**Comment by coocood** [comment]
@winoros 
Have you considered outer join when move selection condition to join?

`select * from t1 left join (select * from t2 where t2.c1 > 0) t2 on t1.c2 = t2.c2`

is not the same as 

`select * from t1 left join t2 on t1.c2 = t2.c2 and t2.c1 > 0`

**Comment by winoros** [comment]
The conditions' lifting up will only affect the inner table. If there is a selection between join and outer data source, lifting up won't happen. I will add this into test.

**Comment by coocood** [comment]
LGTM

**Comment by winoros** [comment]
PTAL @hanfei1991 @shenli

**Pull request merged**
