### PR TITLE
server: don't interrupt when nodelay executed

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

- no longer interrupt if no-delay has be executed
- use mysql's kill error code and msg
- make conn_test can be running again - -

### What is changed and how it works?

- just as above

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - N/A

Side effects

 - N/A

Related changes

 - Need to cherry-pick to the release 3.0?

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/11135)

### CODE REVIEW

**Comment by lysu** [comment]
duplicate with #11135

**Comment by qw4990** [comment]
How about open this PR again and use this PR to fix this problem, since this solution is better than #11138, otherwise we have to copy changes in this PR to #11138, which is unnecessary and weird 🤔 @lysu

**Comment by coocood** [comment]
LGTM

**Pull request merged**
