### PR TITLE
vendor: update etcd and goleveldb

### PR DESCRIPTION
**Pull request by tiancaiamao**
update pre-ga

1. goleveldb fix data race when close
2. etcd client bug fix https://github.com/pingcap/tidb/pull/4671

@shenli @coocood

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by tiancaiamao** [comment]
It can't run the current tidb-test as tidb-test has updated.
I think when we tag tidb, we should make a tag in tidb-test at the same time...

**Comment by shenli** [comment]
We will encourage all our customer to migrate to release-1.0. So we do not need this PR.

**Pull request closed without merging**
