### PR TITLE
executor: add log for commit work

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve? 

The original `AddRecordLd` function used in `load data` statement, will not report error to caller.

Problem:
Loading 300 millon rows in tpch lineitem table into tidb,  after loaded row counts over 50800000, the load data commit goroutine will always write zero rows processing one commit task, because of error "[autoid:1467]Failed to read auto-increment value from storage engine" from `AddRecord`. (related to #13648, need more investigation on this), add this error not reported, so  the loading process seems  got stuck

### What is changed and how it works?

- Do report error in `AddRecordLd` function if `AddRecord` failed
- Add some info log for commit processing

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below), retrying loading `tpch.lineitem` data with 300million rows

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch ?

Release note

### CODE REVIEW

**Comment by imtbkcat** [comment]
Does this pr need to be cherry-pick to release-3.0? @cfzjywxk

**Comment by cfzjywxk** [comment]
> Does this pr need to be cherry-pick to release-3.0? 
@jackysp @imtbkcat  I think so

**Pull request merged**
