### PR TITLE
session: Support getting last query info for test purpose (#21557)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21557 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25568
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25568:release-4.0-91ec971961ce
```

---

Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>

### What problem does this PR solve?

Problem Summary: When RC transactions or pessimistic RR transactions are used, there are RC behaviors, which may read data with newer ts than the transaction's start ts. To make it easier to do the consistency checking in integration tests, this PR tries to expose the information of the last query.

### What is changed and how it works?

Added a session variable `tidb_last_query_info` that exposes some information of the last executed query.

...but I'm not sure if my code works when something like retrying happens.

### Related changes

- Need to cherry-pick to the release branch
  - It can be cherry-picked to release-4.0 branch so that it can also be  used to test 4.0 branch.

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- No release note.

### CODE REVIEW

**Review by zyguan — APPROVED** [review]
LGTM

**Review by cfzjywxk — APPROVED** [review]
/lgtm

**Pull request merged**
