### PR TITLE
domain: fail fast when infoSchema is expired

### LINKED ISSUE #47377: When the schema is out of date, transactions should fail quickly.
## Enhancement
If it is determined that the schema is out of date, there is no need to repeat the check schema version for each transaction.

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve?

Issue Number: close #47377

Problem Summary:
Remove the retries.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zimulala — COMMENTED** [review]
Will the transaction failure probability increase in some scenarios?

**Comment by jackysp** [comment]
> Will the transaction failure probability increase in some scenarios?

Yes, this is expected.

**Comment by jackysp** [comment]
Do you have any more concerns about this PR? @zimulala @bb7133 @Benjamin2037

**Comment by bb7133** [comment]
> Do you have any more concerns about this PR? @zimulala @bb7133 @Benjamin2037

To be frank, I don't get the point of your code...could you make some explainations on how it work a little bit?

**Comment by jackysp** [comment]
> > Do you have any more concerns about this PR? @zimulala @bb7133 @Benjamin2037
> 
> To be frank, I don't get the point of your code...could you make some explainations on how it work a little bit?

For user sessions, if the lease is expired, the session won't retry 10 times, just return the expired schema error. But for the internal sessions, I just keep the logic as it used to be, to make some special scenarios can work, e.g. bootstrapping, upgrading, so on.

**Comment by jackysp** [comment]
> > Do you have any more concerns about this PR? @zimulala @bb7133 @Benjamin2037
> 
> To be frank, I don't get the point of your code...could you make some explainations on how it work a little bit?

For user sessions, if the lease is expired, the session won't retry 10 times, just return the expired schema error. But for the internal sessions, I just keep the logic as it used to be, to make some special scenarios can work, e.g. bootstrapping, upgrading, so on.

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request closed without merging**
