### PR TITLE
*: fix query panic when query exceeded resource group quota limitation

### LINKED ISSUE #53316: query panic when query exceeded resource group quota limitation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

see https://github.com/tikv/client-go/issues/1343

### 4. What is your TiDB version? (Required)

nightly

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #53316

Related PR: https://github.com/tikv/client-go/pull/1344

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@nolouch PTAL

**Review by MyonKeminta — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
