### PR TITLE
ddl: allow altering auto_increment to a large number (#19241)

### LINKED ISSUE #19238: alter auto_increment sql not work.
## Bug Report

Found that when auto_increment is unsigned, and alter auto_increment is larger than math.MaxInt64, it's not work well. see details below.

### 1. Minimal reproduce step (Required)
1. ```CREATE TABLE `autoid` (`auto_inc_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, UNIQUE KEY `auto_inc_id` (`auto_inc_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;```
2. ```alter table `autoid` auto_increment = 12345678901234567890;```
3. ```insert into `autoid` values ();```
4. ```select * from `autoid`;```

### 2. What did you expect to see? (Required)
```
mysql> select * from autoid;
+-----------------------+
| auto_inc_id           |
+-----------------------+
|   12345678901234567890|
+-----------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> select * from autoid;
+-------------+
| auto_inc_id |
+-------------+
|           1 |
+-------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.3
Edition: Community
Git Commit Hash: 0529b1b493e46aae71bbe34cbe24515a2eb1b47c
Git Branch: heads/refs/tags/v4.0.3
UTC Build Time: 2020-07-24 12:06:35
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19241 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #19238 

Problem Summary:

The comparison between `auto_id` should be uint64-wised.

### What is changed and how it works?

What's Changed: Omitted.

How it Works: Omitted.

### Related changes

N/A

### Check List 

Tests 

- Unit test
- Integration test

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

**Comment by qw4990** [comment]
PTAL @zimulala @AilinKid

**Review by zimulala — COMMENTED** [review]
LGTM

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
