### PR TITLE
planner: remove the useless variable `tidb_enable_point_get_cache ` 

### LINKED ISSUE #36598: Support general plan cache
## Feature Request

**Is your feature request related to a problem? Please describe:**

TP queries can get lots of performance benefits from Plan Cache, but the current [TiDB Plan Cache](https://docs.pingcap.com/tidb/dev/sql-prepared-plan-cache) can only support [Prepare](https://docs.pingcap.com/tidb/dev/sql-statement-prepare)/[Execute](https://docs.pingcap.com/tidb/v5.0/sql-statement-execute) Statements. Most of our users are still using general queries to access TiDB instead of Prepare/Execute. So if Plan Cache can support general queries, these users can gain some performance benefits as well.

**Describe the feature you'd like:**

When we execute the general query, we can skip the parser and optimizer phase to directly get the physical plan from the plan cache. That can save more time for the TP queries.

**Teachability, Documentation, Adoption, Migration Strategy:**

The detail design will be posted later.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #36598

Problem Summary: planner: remove the useless variable `tidb_enable_point_get_cache ` 

### What is changed and how it works?

planner: remove the useless variable `tidb_enable_point_get_cache ` 

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Yisaer — APPROVED** [review]

**Review by fzzf678 — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Review by dayicklp — APPROVED** [review]

**Comment by morgo** [comment]
There is a compatibility feature for removed variables here: https://github.com/pingcap/tidb/blob/master/sessionctx/variable/removed.go -- did you want to add this?

**Pull request merged**
