### PR TITLE
lightning: fix duplicate check panic (#29338)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #29338 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/29424
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/29424:release-5.3-dc2d5a4f453e
```

---

### What problem does this PR solve?
Fix duplicate iterator panic when lightning restart from import engine.

Part of #29423 

### What is changed and how it works?

- Set some missging field in `CloseEngine` to avoid nil pointer panic
- Use RestoreController.sysvars to build KvDecoder in duplicate manager
- Use a new context to stop set service GC safepoint
- Fix a typo in doc

Tests 

- [ ] Unit test
- [x] Integration test 
  - several integration tests will panic before this pr.
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by glorv** [comment]
waiting for #29425  to merge first.

**Review by glorv — APPROVED** [review]

**Review by kennytm — APPROVED** [review]

**Comment by kennytm** [comment]
@glorv #29425 has been merged

**Comment by glorv** [comment]
@gozssky do you finish manually testing?

**Pull request merged**
