### PR TITLE
config: support change resolve lock lite threshold

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Problem Summary:

port #25835 to master, need merge https://github.com/tikv/client-go/pull/291 first

maybe we need to tweak the threshold to resolve lock lite in some situations

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed, How it Works:

update client-go to https://github.com/tikv/client-go/pull/291 to support tweak resolve lite threshold

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
Support change resolve lock lite threshold by configuration file
```

### CODE REVIEW

**Comment by sticnarf** [comment]
Is it more suitable to put this config in the `tikv-client` section?

**Comment by lysu** [comment]
> Is it more suitable to put this config in the `tikv-client` section?

emmm~ it should be, maybe help merge https://github.com/tikv/client-go/pull/297 first :)

**Comment by sticnarf** [comment]
> > Is it more suitable to put this config in the `tikv-client` section?
> 
> emmm~ it should be, maybe help merge [tikv/client-go#297](https://github.com/tikv/client-go/pull/297) first :)

Okay...

**Review by youjiali1995 — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]

**Pull request merged**
