### PR TITLE
*: adapt `utf8mb4_0900_ai_ci` collation (#10183)

### PR DESCRIPTION
**Pull request by lysu**
cherry-pick #10183 to 2.1

need https://github.com/pingcap/parser/pull/296 be merged before this PR, DNM

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/10201)

### CODE REVIEW

**Comment by bb7133** [comment]
LGTM

**Comment by tiancaiamao** [comment]
https://github.com/pingcap/parser/pull/296 is merged, you can update `go.mod` now
@lysu

**Comment by lysu** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by lysu** [comment]
@tiancaiamao done~ thx

**Pull request merged**
