### PR TITLE
distsql, bench: fix the benchmark of distsql to represent the performance more accurately

### LINKED ISSUE #52371: Using `(*mock.Context).GetDistSQLCtx()` will make the benchmark slower
## Enhancement

This issue only affects the benchmark, and it doesn't affect the performance of real `tidb-server`. I'd like to fix it to make the performance of benchmark aligned with the real tidb server.

The real session cache the `distsqlctx`. We should also cache the `distsqlctx` in the `mockResponse`.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #52371

Problem Summary:

The original benchmark didn't cache the `distsqlctx`, which is not aligned with the behavior of real session.

```
Before f7d66f:
BenchmarkSelectResponseChunk_SmallResponse-16    	    2487	    457227 ns/op	  624643 B/op	    5112 allocs/op

Before:
BenchmarkSelectResponseChunk_SmallResponse-16    	    2366	    495870 ns/op	  704644 B/op	    5512 allocs/op

After:
BenchmarkSelectResponseChunk_SmallResponse-16    	    2430	    447747 ns/op	  624644 B/op	    5112 allocs/op
```

### What changed and how does it work?

This PR caches the `distsqlctx` in the `mockResponse`, so that it'll not be re-created multiple times.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

### Release note

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
@YangKeao Please fix the unit test.

**Review by zimulala — APPROVED** [review]

**Comment by YangKeao** [comment]
Close this PR, as it needs too much modification on tests, and it only affects the performance of the test. If we use the benchmark result of new codes as a baseline, I think it's fine to keep it.

**Pull request closed without merging**
