### PR TITLE
executor: fix linter --enable=deadcode check error in executor(#22979)

### PR DESCRIPTION
**Pull request by An-DJ**
### What problem does this PR solve?

Issue Number:  #22979 

Problem Summary: packages which linter `--enable=deadcode` cannot pass are as follows.

- [ ] planner
- [ ] plugin
- [ ] store
- [X] executor
- [ ] expression

### What is changed and how it works?

What's Changed: directory `executor` 
Before fix:
```
executor/adapter.go:702:6: `extractConflictCommitTS` is unused (deadcode)
func extractConflictCommitTS(errStr string) uint64 {
     ^
executor/batch_checker.go:51:6: `encodeNewRow` is unused (deadcode)
func encodeNewRow(ctx sessionctx.Context, t table.Table, row []types.Datum) ([]byte, error) {
     ^
executor/distsql.go:139:6: `handleIsExtra` is unused (deadcode)
func handleIsExtra(col *expression.Column) bool {
     ^
executor/partition_table.go:50:6: `innerNextPartition` is unused (deadcode)
type innerNextPartition interface {
     ^
executor/benchmark_test.go:1618:6: `defaultMergeJoinTestCase` is unused (deadcode)
func defaultMergeJoinTestCase() *mergeJoinTestCase {
```
These functions and types are deprecated.

How it Works: deprecated code in executor has been deleted. golang-linter --enable-deadcode in `executor`  can pass.

### Check List 

Tests 

- No code

Side effects

- none

### Release note 

- No release note

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
Approved

**Comment by An-DJ** [comment]
Did these checks error occur because of my out of date branch? Could i merge master directly?

**Comment by xhebox** [comment]
> Did these checks error occur because of my out of date branch? Could i merge master directly?

Maybe. You can merge the master, but do not merge all new commits like `coauthored with An-DJ`...

**Review by Yisaer — APPROVED** [review]
LGMT

**Pull request merged**
