### PR TITLE
server: add Uptime status counter

### LINKED ISSUE #8842: support global status like 'uptime'
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB does not support the status variable 'uptime'.  MySQL dbas use it idiomatically:
* I restart the server, I check it is the correctly rebooted.
* My client disconnected.  Was it because of a server crash?  check uptime.
* has the server freshly started?  = slow performance (not applicable to tidb, since it's stateless).

So it is not critical but helps improve 'comfort'.

**Describe the feature you'd like:**

`SHOW GLOBAL STATUS like 'Uptime'` should report uptime in seconds.

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

Compatibility with MySQL.

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve? 

Fixes #8842

### What is changed and how it works?

Uses variable infrastructure to push `Uptime` statistic.  So you can now do this, as in MySQL:
```
tidb> show global status like 'Uptime';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| Uptime        | 10    |
+---------------+-------+
1 row in set (0.00 sec)
```

### Check List 

Tests 

 - Manual test

I would like to add a test, but I wanted to check first - since the logical way to do it is to run `show global status`, sleep a second, and then run it again.  But I don't know if:
1. Sleeping for 1 second is considered acceptable since it slows down the tests.
2. It handles the race condition successfully that sleeping is never exactly 1 second.

As an alternative, I could assert that the value is greater than zero? Feedback welcome.

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change

Side effects

 - Increased code complexity

Related changes

 - Need to update the documentation (supported statuses, variables)
 - Need to be included in the release note

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8888)

### CODE REVIEW

**Comment by wuudjac** [comment]
@morgo How about testing like this:
```
server, err := NewServer(...)
// Initialization stuff...

server.startTime = server.startTime.Add(-10 * time.Second)

result, err := server.Stats(...)
// Assert `result` got is not less than 10.
```
Since you are calculating duration, so you can change the lower bound instead of the upper bound.

For case 1, it will not slow down the tests.
For case 2, you can assert result is not less than any value you set, but cannot assert the upper limit in race condition.

If you want to assert upper limit, or want exact equal assertion, maybe you need to implement a mock time producer that offers `time.Now()`

**Comment by zz-jason** [comment]
@morgo friendly ping, any update?

**Comment by zz-jason** [comment]
@jackysp Since we have monitored the `uptime` on Grafana, maybe this PR is not that necessary?

**Comment by jackysp** [comment]
This PR still has some compatibility improvements. But not so important. Maybe we can close it first? @zz-jason

**Comment by zz-jason** [comment]
I'm going to close this PR due to outdated, fell free to reopen it if you are going to process it again in the future.

**Pull request closed without merging**
