### PR TITLE
*: add support for -initialize-sql-file on first bootstrap

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/35624

Problem Summary:

Because tidb persists global variables to the cluster, setting configuration requires first waiting for TiDB to listen and then a mysql client to connect and set initial values of the variables. This requires some clumsy automation scripts. It's much easier if the server can accept a SQL file with which to specify a set of SQL commands to execute on first bootstrap only.

### What is changed and how it works?

A new option `-initialize-sql-file` is added to the tidb-server binary.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
A new option `-initialize-sql-file` is added to the tidb-server binary. This can be used as part of automation to specify an initial set of SQL commands to run on the first bootstrap of the tidb cluster.
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by CbcWestwolf** [comment]
Hi, this PR indeed helps to create some users and grant some privileges when tidb first bootstraps. It is useful on the cloud scenarios.
This requires some modification of the code. Would you like to apply this patch and resolve the conflict, moving the PR to be merged? :-)
[add-bootstrap-sql.txt](https://github.com/pingcap/tidb/files/10287117/add-bootstrap-sql.txt)

**Comment by morgo** [comment]
I agree it's useful! My understanding is that it is blocked waiting for PM approval. If you can confirm it is approved, I will fix conflicts.

**Comment by CbcWestwolf** [comment]
Yes, we have confirmed with the PM and it is approved.

**Review by CbcWestwolf — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
