### PR TITLE
expression, types: fix datetime and year comparison error (#20233)

### LINKED ISSUE #20121: datetime and year comparison error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
drop table if exists t;
create table t(a datetime, b year);
insert into t values("2000-05-03 16:44:44", 2018);
select * from t where t.a > t.b;
```

### 2. What did you expect to see? (Required)
```
mysql> select * from t where t.a > t.b;
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> select * from t where t.a > t.b;
+---------------------+------+
| a                   | b    |
+---------------------+------+
| 2000-05-03 16:44:44 | 2018 |
+---------------------+------+
1 row in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

master f6d445c7af707edd34f4f74d657d278c5aeab4d7
release-4.0 0fbe796e98399fc988911170b6711bfebf44bd46

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20233 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #20121 

Problem Summary:

### What is changed and how it works?

For Datetime vs Year, Date vs Year, Timestamp vs Year comparison, CompareTime should be used, and Year should be converted to `Time` before comparing.

What's Changed:

`expression/builtin_cast.go` 
`types/time.go`

How it Works:

For Datetime vs Year, Date vs Year, Timestamp vs Year comparison, CompareTime should be used, and Year should be converted to `Time` before comparing.

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
 

- No release note

### CODE REVIEW

**Comment by zhongzc** [comment]
Does this PR need to merge into release-4.0? @XuHuaiyu

**Review by qw4990 — COMMENTED** [review]
LGTM

**Review by lzmhhh123 — APPROVED** [review]
LGTM

**Comment by qw4990** [comment]
Need to fix coprocessor first.

**Pull request merged**
