### PR TITLE
lightning: support column starts with slash/number/non-ascii for parquet  (#36985)

### LINKED ISSUE #36980: tidb-lightning need to support fields starting with `_` when the import file type is parquet
## Bug Report

Please answer these questions before submitting your issue. Thanks!

tidb-lightning need to support fields starting with `_` when the import file type is parquet

### 1. Minimal reproduce step (Required)
1. fields starting with `_` of parquet
2. use tidb-lightning import 

### 2. What did you expect to see? (Required)
import success 
### 3. What did you see instead (Required)
```
Root cause: PreCheckFailed: TiDB schema `test`.`tbl` doesn't have column pargo_prefix__abc, please check table schema 
```
### 4. What is your TiDB version? (Required)
tidb、tidb-lightning ：v6.1.0

### LINKED ISSUE #36981: lightning: support column start with slash for parquet data file
parquet-go add [`PARGO_PREFIX_`](https://github.com/xitongsys/parquet-go/issues/387#issuecomment-859395006) prefix for column name which doesn't start with `a-zA-Z`

lightning need to use original name before import to support those columns

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #36985 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/37092
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/37092:release-5.4-e4338c1e4a6c
```

---

### What problem does this PR solve?

Issue Number: close #36980 close #36981

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
support column starts with slash/number/non-ascii for parquet file
```

### CODE REVIEW

**Review by dsdashun — APPROVED** [review]
LGTM

**Review by buchuitoudegou — APPROVED** [review]

**Comment by D3Hunter** [comment]
ci pass, merge
https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/12917/pipeline

**Pull request merged**
