### PR TITLE
*: add IsExplicitTxn in slow log

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:
It is not easy to find out if a slow log entry is from an explicit transaction or not.

### What is changed and how it works?
Add a column to show it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. Tested with `update t set j = j + sleep(1);` with begin, set autocommit = 1/0
1. Tested with `select * from information_schema.slow_query limit 1\G`
1. Tested with binary protocol with point get plan.

```
# Txn_start_ts: 18446744073709551615
# User@Host: root[root] @ 127.0.0.1 [127.0.0.1]
# Conn_ID: 11
# Query_time: 1.001333458
# Parse_time: 0
# Compile_time: 0.000296916
# Rewrite_time: 0.000101667
# Optimize_time: 0.000113292
# Wait_TS: 0
# DB: test
# Is_internal: false
# Digest: 1227bb157e3c371b17d0f681ab224a0c9d848a4658d132f24259002528d85b07
# Num_cop_tasks: 0
# Mem_max: 242
# Prepared: true
# Plan_from_cache: false
# Plan_from_binding: false
# Has_more_results: false
# KV_total: 0
# PD_total: 0.000000708
# Backoff_total: 0
# Write_sql_response_total: 0.000002625
# Result_rows: 1
# Succ: true
# IsExplicitTxn: false
# Plan: tidb_decode_plan('wQHwZTAJM180CTAJMQlwbHVzKHRlc3QudC5qLCBzbGVlcCgxKSktPkNvbHVtbiMzCTEJdGltZToxcywgbG9vcHM6MiwgQ29uY3VycmVuY3k6T0ZGCTI0MiBCeXRlcwlOL0EKMQkzNl81CQFgRHRhYmxlOnQsIGhhbmRsZToxCQ1PFDg3LjPCtS5UAFRHZXQ6e251bV9ycGM6MSwgdG90YWxfBXxAMzkuNcK1c30JTi9BCU4vQQo=')
# Plan_digest: 069ea9fb083b3898f7fe030a43bc00b0689102b5a8dc4d36f0388a76fb027983
use test;
select j+sleep(1) from t where i = ? [arguments: 1];
```

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Add IsExplicitTxn flag in slow log.
```

### CODE REVIEW

**Comment by jackysp** [comment]
PTAL @crazycs520 , I'm not sure about the effect of tidb-dashboard.

**Comment by cfzjywxk** [comment]
/cc
@MyonKeminta @longfangsong 
Any suggestions about this information？

**Comment by MyonKeminta** [comment]
> /cc @MyonKeminta @longfangsong Any suggestions about this information？

It looks good to me to show if the transaction's kind. Just wondering why not use the word `IsAutoCommit` directly 🤔

**Comment by jackysp** [comment]
> > /cc @MyonKeminta @longfangsong Any suggestions about this information？
> 
> It looks good to me to show if the transaction's kind. Just wondering why not use the word `IsAutoCommit` directly 🤔

Autocommit sometimes represents the state the session, and using IsAutoCommit could be misinterpreted to mean that the session was in the state of autocommit when the SQL was executed, rather than that it was inside an explicit transaction.

**Review by longfangsong — APPROVED** [review]
LGTM

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by MyonKeminta — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Pull request merged**
