### PR TITLE
executor: remove Next for AnalyzeExec

### PR DESCRIPTION
**Pull request by colinback**

### CODE REVIEW

**Comment by shenli** [comment]
LGTM
@colinback Thanks!

**Comment by colinback** [comment]
oops... Both #6012 & #6013 failed for unit-test. I'm going to check what's wrong.

**Comment by colinback** [comment]
@zz-jason 
I review the unit-test logging:
```
----------------------------------------------------------------------
FAIL: builtin_cast_test.go:1153: testEvaluatorSuite.TestWrapWithCastAsTime

builtin_cast_test.go:1197:
    c.Assert(res.Compare(t.res), Equals, 0)
... obtained int = 1
... expected int = 0
----------------------------------------------------------------------
FAIL: integration_test.go:2508: testIntegrationSuite.TestCompareBuiltin

integration_test.go:2606:
    result.Check(testkit.Rows(fmt.Sprintf("1 1.1 2017-08-01 12:01:01 12:01:01 %s 12:01:01 abcdef 21 1", time.Now().In(time.UTC).Format("2006-01-02"))))
/home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:48:
    res.c.Assert(got, check.Equals, need, res.comment)
... obtained string = "[[1 1.1 2017-08-01 12:01:01 12:01:01 2018-03-12 12:01:01 abcdef 21 1]]"
... expected string = "[[1 1.1 2017-08-01 12:01:01 12:01:01 2018-03-11 12:01:01 abcdef 21 1]]"
... sql:select coalesce(NULL, a), coalesce(NULL, b, a), coalesce(c, NULL, a, b), coalesce(d, NULL), coalesce(d, c), coalesce(NULL, NULL, e, 1), coalesce(f), coalesce(1, a, b, c, d, e, f) from t2, args:[]
```

However local test on my laptop is Ok. Weird...
```
tidb git:(remove_analyze_next) go test -check.f "WrapWithCastAsTime"
OK: 0 passed
PASS
ok     	github.com/pingcap/tidb	0.022s
➜  tidb git:(remove_analyze_next) go test -check.f "CompareBuiltin"
OK: 0 passed
PASS
ok     	github.com/pingcap/tidb	0.021s
```

**Comment by zz-jason** [comment]
@colinback This is a known issue, we are investigating on this, thanks for your feed back.

**Comment by zz-jason** [comment]
to #5985

**Pull request merged**
