### PR TITLE
*: fix LIKE expressions with _ following % (#17418)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #17418 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/22575
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/22575:release-4.0-b5bb0090e769
```

---

### What problem does this PR solve?

Problem Summary: TiDB assumes that pattern `%_` is equivalent to `%`, but that is not the case. The pattern `x%x` should match `xx`, `x%_x` should not. This issue is present in various code sections related to `LIKE` expressions. At least that I found:

1. `stringutil.CompilePattern` at `util/stringutil/string_util.go`
2. `stringutil.CompileLike2Regexp` at `util/stringutil/string_util.go`
3. `collate.compilePatternGeneralCI` at `util/collate/general_ci.go`

### What is changed and how it works?

- On `stringutil.CompilePattern`, `stringutil.CompileLike2Regexp` and `collate.compilePatternGeneralCI` just removed the few lines that converted `%_` to `%`.
- Added new unit tests. Although `memtable_reader_test.go` could use some more.

### Check List

- Unit tests

### Release note

* Fixed LIKE expressions when a single character (`_`) wildcard follows a multiple character wildcard (`%`).

### CODE REVIEW

**Comment by qw4990** [comment]
/run-all-tests

**Review by qw4990 — COMMENTED** [review]
LGTM

**Comment by time-and-fate** [comment]
LGTM

**Review by zz-jason — APPROVED** [review]

**Pull request merged**
