### PR TITLE
ddl: support showing label rule through information schema table

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Closes https://github.com/pingcap/tidb/issues/26694. It can be reviewed after https://github.com/pingcap/tidb/pull/26630 is merged. 

### What is changed and how it works?

This PR is going to provide a way to show the label rules through SQL.

```
mysql> create table t1 (c int);
Query OK, 0 rows affected (0.08 sec)

mysql> alter table t1 attributes="attr";
Query OK, 0 rows affected (0.07 sec)

mysql> select * from information_schema.region_label;
+----------------+-----------+--------------+--------------------------------------+--------------------------------------+
| RULE_ID        | RULE_TYPE | REGION_LABEL | START_KEY                            | END_KEY                              |
+----------------+-----------+--------------+--------------------------------------+--------------------------------------+
| schema/test/t1 | key-range | "attr"       | 7480000000000000ff355f720000000000fa | 7480000000000000ff365f720000000000fa |
+----------------+-----------+--------------+--------------------------------------+--------------------------------------+
```

What's Changed:
1. add a new memory table named region_label in information_schema to show the label rules
2. add `GetAllLabelRules` to retrieve all rules
 

### Check List 

Tests 

- [x] Unit test

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [x] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 
```release-note
None
```

### CODE REVIEW

**Comment by xhebox** [comment]
Plz reping me after the other PR merged.

**Review by Yisaer — COMMENTED** [review]
I think the `region_label` table is not proper for tidb while it is more suitable to display by PD. As `region label` is designed for table, I think it should be more proper to display label in `infoschema.table`

**Comment by xhebox** [comment]
> 
> 
> I think the `region_label` table is not proper for tidb while it is more suitable to display by PD. As `region label` is designed for table, I think it should be more proper to display label in `infoschema.table`

@rleungx Do we have an agreement on the behavior now?

**Comment by rleungx** [comment]
PTAL @Yisaer

**Review by Yisaer — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
