### PR TITLE
config: fix config experimental.allow-expression-index

### LINKED ISSUE #27038: It raises invalid configuration experimental.allow-expression-index when upgrade nightly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tiup deploy v5.1.1 cluster and set the tidb experimental.allow-expre ssion-index true
TiUP upgrade nightly
### 2. What did you expect to see? (Required)
successfully
### 3. What did you see instead (Required)
[FATAL] [terror.go:276] ["unexpected error"] [error="config file /data1/tidb-deploy11/tidb-4009/conf/tidb.toml contained invalid configuration options: experimental.allow-expre
ssion-index; check TiDB manual to make sure this option has not been deprecated and removed from your TiDB version if the option does not appear to be a typo

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #27038 

Problem Summary:
Miss the prefix `experimental.`

### What is changed and how it works?

Add prefix `experimental.`

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
 'None'
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by xiongjiwei — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]

**Comment by wjhuang2016** [comment]
run-unit-test

**Pull request merged**
