### PR TITLE
config: remove new charset config (#31291)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #31291 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/31370
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/31370:release-5.4-cfbe70846a0d
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/31236

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by djshow832** [comment]
Please resolve conflicts. @xiongjiwei

**Review by Defined2014 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Pull request merged**
