### PR TITLE
*: make tidb_replica_read work with set_var hint

### LINKED ISSUE #48472: make tidb_replica_read work with set_var hint
## Enhancement

Airbnb wants to make `tidb_replica_read` work with `set_var` hint.

### PR DESCRIPTION
**Pull request by crazycs520**
cherry-pick #48473

### What problem does this PR solve?

Issue Number: close #48472

Problem Summary: make tidb_read_staleness and tidb_replica_read work with set_var hint

### What is changed and how it works?

This PR:

```sql
mysql> select /*+ SET_VAR(tidb_replica_read = 'follower')*/ @@tidb_replica_read;
+---------------------+
| @@tidb_replica_read |
+---------------------+
| follower            |
+---------------------+
1 row in set (0.00 sec)

mysql> select  @@tidb_replica_read;
+---------------------+
| @@tidb_replica_read |
+---------------------+
| leader              |
+---------------------+
1 row in set (0.00 sec)
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by cfzjywxk — APPROVED** [review]

**Review by zyguan — COMMENTED** [review]
Setting `IsHintUpdatable` to true may not actually take effect, the value is cached in `SessionVars.stmtVars` but we still read from the field (eg `SessionVars.ReadStaleness`).

**Comment by cfzjywxk** [comment]
@crazycs520 
I think we need to merge it to the master branch too.

**Comment by cfzjywxk** [comment]
> Setting `IsHintUpdatable` to true may not actually take effect, the value is cached in `SessionVars.stmtVars` but we still read from the field (eg `SessionVars.ReadStaleness`).

Seems to be a problem, @crazycs520  PTAL

**Comment by crazycs520** [comment]
> Setting `IsHintUpdatable` to true may not actually take effect, the value is cached in `SessionVars.stmtVars` but we still read from the field (eg `SessionVars.ReadStaleness`).

Nice catch, Currently the fix is not really work. Since `SET_VAR` feature is GA on v7.4.0, the `SET_VAR` implementation is a little different between this branch(v6.5.4) and v7.4.0.  So I need another work to make tidb_read_staleness and tidb_replica_read work with set_var hint.

cc  @Tema

**Review by zyguan — APPROVED** [review]

**Pull request merged**
