### PR TITLE
privilege/privileges: improve authentication performance when there are a lot of privilege records

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Fix https://github.com/pingcap/tidb/issues/13831

### What is changed and how it works?

Use a map to accelerate the search operation.
Before this change, we have to iterate the array to find the record, the complexity is O(n).
In this PR, a map is used to locate the record, thus O(1) complexity.

Before:

> BenchmarkRequestVerification-4   	  967116	      1235 ns/op

After:

> BenchmarkRequestVerification-4   	 8377918	       144 ns/op

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @jackysp @imtbkcat

**Comment by tiancaiamao** [comment]
PTAL @jackysp @imtbkcat

**Comment by jackysp** [comment]
PTAL @imtbkcat

**Comment by jackysp** [comment]
PTAL @cfzjywxk

**Comment by cfzjywxk** [comment]
LGTM

**Pull request merged**
