### PR TITLE
tikv: remove the update leader backoff (#17541)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #17541 to release-3.0

---

Signed-off-by: Liqi Geng <gengliqiii@gmail.com>

### What problem does this PR solve?

Issue Number: https://github.com/tikv/tikv/issues/7941

Problem Summary:
When a down TiKV recovers, PD will transfer many leaders to this TiKV. I found it will cause that QPS recovers so slowly because of TiDB backoff strategy.
If a region's leader has transferred, the request to this region may get a `NotLeader` error with a correct leader in most cases. Then TiDB will backoff at least 1ms(then 2,4,8,10ms) which is very wasteful. 
In https://github.com/tikv/tikv/issues/7941, it's showed that the QPS recover time is reduced to 2-4min if we remove the update leader backoff, while the original time is 10min.

### What is changed and how it works?

What's Changed:
Remove the update leader backoff.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

No.

### Release note 
* Mitigate the impact of failure recovery on QPS.

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
@gengliqi please resolve the conflicts.

**Comment by lysu** [comment]
@gengliqi please resolve the conflicts.

**Comment by gengliqi** [comment]
> @gengliqi please resolve the conflicts.

Resolved, PTAL. 
1. unit-test failed due to data race in `TestSyncerSimple` which should be https://github.com/pingcap/tidb/issues/16449
2. check-dev failed but I don‘t know why.😂

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by disksing — APPROVED** [review]

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
