### PR TITLE
lightning: make pre-check output message clearer

### LINKED ISSUE #30395: lightning precheck message "smaller number for tikv-importer.disk-quota(8EiB)" too ambiguous when local disk space check fails
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Use lightning to import data where lightning local disk space is not enough.

### 2. What did you expect to see? (Required)
Precheck fail message should be clear, and be able to guide use to fix the issue

### 3. What did you see instead (Required)
1. "imprtestimate" should be separated as 2 words
2. "You need a smaller number for tikv-importer.disk-quota(8EiB) to finish imports" is confusing, user doesn't know how to fix the issue, smaller number than 8EiB is too ambiguous.

lightning_precheck_disk

### 4. What is your TiDB version? (Required)
Release Version: v5.4.0-nightly
Git Commit Hash: 732b7eb128ed0f251d9ce92509a3aaad63f02a80
Git Branch: heads/refs/tags/v5.4.0-nightly
Go Version: go1.16.4
UTC Build Time: 2021-12-02 08:08:09
Race Enabled: false

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #30395

Problem Summary:

### What is changed and how it works?
- make tidb-lightning storage size check output message clearer
- Only write the critical message into error message

The check result is adjusted as follow:
```
local disk space may not enough to finish import, estimate sorted data size is 249.5GiB, but local available is 58.35GiB, please set `tikv-importer.disk-quota` to a smaller value than 58.35GiB or change `mydumper.sorted-kv-dir` to another disk with enough space to finish imports
```

Return error change:
```
tidb lightning encountered error:  tidb-lightning pre-check failed: local disk space may not enough to finish import, estimate sorted data size is 249.5GiB, but local available is 58.35GiB, please set `tikv-importer.disk-quota` to a smaller value than 58.35GiB or change `mydumper.sorted-kv-dir` to another disk with enough space to finish imports
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
make tidb-lightning pre-check output message clearer
```

### CODE REVIEW

**Comment by glorv** [comment]
@sunzhaoyang @fubinzh PTAL that the new output message is ok.

**Comment by fubinzh** [comment]
> @sunzhaoyang @fubinzh PTAL that the new output message is ok.
For normal user, it looks good to me. Do we need to consider DBaaS user for this case?

**Review by gozssky — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
