### PR TITLE
*: support natural join.

### PR DESCRIPTION
**Pull request by bobotu**
TiDB doesn't support natural join now, and treat it as cross join.
This PR and #3372 are similar.

### CODE REVIEW

**Comment by shenli** [comment]
@bobotu Thanks!
@hanfei1991 @winoros PTAL

**Comment by winoros** [comment]
Maybe you can extract the same part of `buildUsingClause` and `buildNaturalJoin` out as a method.

**Comment by winoros** [comment]
@hanfei1991 PTAL

**Comment by shenli** [comment]
@bobotu Well done!

**Pull request merged**
