### PR TITLE
chore: add test lightning_drop_other_tables_halfway to script

### PR DESCRIPTION
**Pull request by purelind**
### What problem does this PR solve?
Add lightning_drop_other_tables_halfway to run_group.sh.

Issue Number: close #xxx

Problem Summary:

### Check List

Tests 

- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by 3pointer — APPROVED** [review]

**Comment by lance6716** [comment]
```
	echo "Error: "$others" is not added to any group in br/tests/run_group.sh"
```

seems it does not work?

**Comment by purelind** [comment]
> ```
> 	echo "Error: "$others" is not added to any group in br/tests/run_group.sh"
> ```
> 
> seems it does not work?

I executed the test locally in this way.
image

**Pull request merged**
