### PR TITLE
store/tikv: revert the optimization for optimistic conflicts pessimistic

### PR DESCRIPTION
**Pull request by coocood**
### What problem does this PR solve? 
The previous optimization return WriteConflict error when an optimistic transaction meets a pessimistic lock, this has the problem that optimistic transaction may reach retry limit soon and failed to resolve lock when pessimistic lock ttl is reached.

### What is changed and how it works?
Revert the optimization.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by coocood** [comment]
@jackysp PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
