### PR TITLE
lightning: Add parser db2lob when load data

### LINKED ISSUE #39002: lightning can not load csv with 打包

### PR DESCRIPTION
**Pull request by AndrewDi**
Issue Number: close #39002 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
Please fix the lint errors, you can find them in https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_build/detail/ghpr_build/6095/pipeline

```
br/pkg/lightning/mydump/csv_parser.go:547:5: should check returned error before deferring lobFileHandler.Close() (SA5001)

br/pkg/lightning/mydump/csv_parser.go:560:24: unchecked error (errcheck)

br/pkg/lightning/mydump/csv_parser.go:561:24: unchecked error (errcheck)

br/pkg/lightning/mydump/parquet_parser.go:582:1: exported: exported method ParquetParser.SetColumnTypes should have comment or be unexported (revive)

br/pkg/lightning/mydump/csv_parser.go:605:1: exported: exported method CSVParser.SetColumnTypes should have comment or be unexported (revive)

br/pkg/lightning/mydump/csv_parser.go:547:5: defer: prefer not to defer inside loops (revive)

br/pkg/lightning/mydump/parquet_parser.go:582:41: unused-parameter: parameter 'colTypes' seems to be unused, consider removing or renaming it as _ (revive)

br/pkg/lightning/mydump/parquet_parser.go:582:7: unused-receiver: method receiver 'pp' is not referenced in method's body, consider removing or renaming it as _ (revive)

br/pkg/lightning/mydump/csv_parser.go:547:5: defer: prefer not to defer inside loops (all_revive)
```

**Review by lance6716 — COMMENTED** [review]
1. I see you have only changed the csv parser, will DB2 also generate SQL-format dump file and also need this feature?
2. Since we reviewers are not familiar with this format, can you add the test files in this PR and write an unit test using them? You may refer to `TestTPCH` as an example to write unit tests.

Welcome to ask us for help!

**Comment by AndrewDi** [comment]
> SetColumnTypes
`I see you have only changed the csv parser, will DB2 also generate SQL-format dump file and also need this feature?`
no such feature...so no need to adapter.

**Comment by AndrewDi** [comment]
> Please fix the lint errors, you can find them in https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_build/detail/ghpr_build/6095/pipeline
> 
> ```
> br/pkg/lightning/mydump/csv_parser.go:547:5: should check returned error before deferring lobFileHandler.Close() (SA5001)
> 
> br/pkg/lightning/mydump/csv_parser.go:560:24: unchecked error (errcheck)
> 
> br/pkg/lightning/mydump/csv_parser.go:561:24: unchecked error (errcheck)
> 
> br/pkg/lightning/mydump/parquet_parser.go:582:1: exported: exported method ParquetParser.SetColumnTypes should have comment or be unexported (revive)
> 
> br/pkg/lightning/mydump/csv_parser.go:605:1: exported: exported method CSVParser.SetColumnTypes should have comment or be unexported (revive)
> 
> br/pkg/lightning/mydump/csv_parser.go:547:5: defer: prefer not to defer inside loops (revive)
> 
> br/pkg/lightning/mydump/parquet_parser.go:582:41: unused-parameter: parameter 'colTypes' seems to be unused, consider removing or renaming it as _ (revive)
> 
> br/pkg/lightning/mydump/parquet_parser.go:582:7: unused-receiver: method receiver 'pp' is not referenced in method's body, consider removing or renaming it as _ (revive)
> 
> br/pkg/lightning/mydump/csv_parser.go:547:5: defer: prefer not to defer inside loops (all_revive)
> ```

done

**Comment by lance6716** [comment]
You can click on these "Details" links to help yourself see the lint errors, 
image
for example

```
br/pkg/lightning/mydump/csv_parser.go:564:12: impossible condition: nil != nil (nilness)

br/pkg/lightning/mydump/csv_parser.go:568:12: impossible condition: nil != nil (nilness)
```

And please add a unit test with real data files for your PR, you can refer to `TestTPCH`

**Comment by lance6716** [comment]
Hi @AndrewDi do you need some help?

**Pull request closed without merging**
