### PR TITLE
*: Run TestCompareReservedWordsWithMySQL in CI

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: ref #48856 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by dveeden** [comment]
This will fail until the test is fixed ( #48857 )

**Comment by dveeden** [comment]
This can be done with Prow with these:
[tidb-test-reserved-words.zip](https://github.com/pingcap/tidb/files/14025621/tidb-test-reserved-words.zip)

**Review by mjonss — APPROVED** [review]

**Comment by hawkingrei** [comment]
> This can be done with Prow with these: [tidb-test-reserved-words.zip](https://github.com/pingcap/tidb/files/14025621/tidb-test-reserved-words.zip)

Can you put this file into ```build/image/parser_test```?

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
