### PR TITLE
session: extend the length of action column to fix the truncation

### LINKED ISSUE #56106: Table mysql.tidb_runaway_queries may display truncated action field
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

图片

### 2. What did you expect to see? (Required)

`switchgroup(xxx)` in the `action` column.

### 3. What did you see instead (Required)

`switchgroup(` in the `action` column.

### 4. What is your TiDB version? (Required)

8313bbc5c04c225f456c4b5e56e244b902bf6e85

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: close #56106.

### What changed and how does it work?

Extend the length of `VARCHAR` for the `action` column to fix the truncation.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)

Before:

图片

After:

图片

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by glorv — APPROVED** [review]

**Comment by JmPotato** [comment]
@nolouch PTAL

**Review by nolouch — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Review by yudongusa — APPROVED** [review]
LGTM

**Pull request merged**
