### PR TITLE
executor: fix show create table with foreign key

### LINKED ISSUE #38118: show create table with foreign key need display database name
## Dev Task

prepare:
```sql
create database test1;
create database test2;
create table test1.t1 (id int key, b int, index(b));
create table test2.t2 (id int key, b int, foreign key fk(b) references test1.t1(id));
```

```sql
show create table test2.t2\G
```
the exepect result is:

```sql
***************************[ 1. row ]***************************
Table        | t2
Create Table | CREATE TABLE `t2` (
  `id` int NOT NULL,
  `b` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk` (`b`),
  CONSTRAINT `t2_ibfk_1` FOREIGN KEY (`b`) REFERENCES `test1`.`t1` (`id`)
)
```

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Issue Number: close #38118

Problem Summary: show create table with foreign key need display database name.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lcwangchao — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Comment by hawkingrei** [comment]
@crazycs520  PTAL

```
        	Error:      	Not equal: 
        	            	expected: "[t2 CREATE TABLE `t2` (\n  `id` int(11) NOT NULL,\n  `a` int(11) DEFAULT NULL,\n  `b` int(11) DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `fk` (`a`),\n  CONSTRAINT `fk` FOREIGN KEY (`a`) REFERENCES `t2` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin]\n"
        	            	actual  : "[t2 CREATE TABLE `t2` (\n  `id` int(11) NOT NULL,\n  `a` int(11) DEFAULT NULL,\n  `b` int(11) DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `fk` (`a`),\n  CONSTRAINT `fk` FOREIGN KEY (`a`) REFERENCES `test2`.`t2` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin]\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -6,3 +6,3 @@
        	            	   KEY `fk` (`a`),
        	            	-  CONSTRAINT `fk` FOREIGN KEY (`a`) REFERENCES `t2` (`id`)
        	            	+  CONSTRAINT `fk` FOREIGN KEY (`a`) REFERENCES `test2`.`t2` (`id`)
        	            	 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin]
        	Test:       	TestRenameTableWithForeignKeyMetaInfo
        	Messages:   	sql:show create table test2.t2, args:[]
```

**Pull request merged**
