### PR TITLE
distsql/*: typo fix for `dispatches`

### PR DESCRIPTION
**Pull request by mapleFU**
### What problem does this PR solve?

No

Problem Summary:

Just a typo

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

fix a typo

How it Works:

:)

### Related changes

None

### Check List 

Tests 

- No code

Side effects

No

### Release note 

- No release note

### CODE REVIEW

**Comment by mapleFU** [comment]
/cc @zz-jason 
PTAL

**Review by qw4990 — APPROVED** [review]

**Comment by qw4990** [comment]
PTAL @wshwsh12 @XuHuaiyu

**Review by wshwsh12 — APPROVED** [review]

**Comment by hi-rustin** [comment]
@ti-chi-bot

**Comment by hi-rustin** [comment]
/hold

Please use the GitHub feature to update your base to the latest, or turn on the option and the bot or maintainer will update the base for you.

image

**Comment by mapleFU** [comment]
@hi-rustin updated

**Comment by hi-rustin** [comment]
> @hi-rustin updated

I recommend that you keep this option on at all times, otherwise the bot will not be able to help you merge PRs.  Because we are going to use base latest to test the PR.

**Comment by mapleFU** [comment]
Closed. Refer to https://github.com/pingcap/tidb/pull/25719.

**Pull request closed without merging**
