### PR TITLE
*: improve map copy

### LINKED ISSUE #34454: use Generics to improve map code

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #34454

Problem Summary:

### What is changed and how it works?

```maps.Copy``` is a convenience function that allows us to map copy.

```
// Copy copies all key/value pairs in src adding them to dst.
// When a key in src is already present in dst,
// the value in dst will be overwritten by the value associated
// with the key in src.
func Copy[M ~map[K]V, K comparable, V any](dst, src M) {
	for k, v := range src {
		dst[k] = v
	}
}
```
### Check List

Tests 

- [x] Unit test
- [x] Integration test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by bb7133** [comment]
@hawkingrei Please update the 'check list'

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by hawkingrei** [comment]
> @hawkingrei Please update the 'check list'

Updated

**Review by tisonkun — COMMENTED** [review]
@hawkingrei so what is the improvement here? Code style or performance?

I don't see an elaboration in PR desc or issue. If it's about perf, you'd better provide a report.

**Comment by hawkingrei** [comment]
> @hawkingrei so what is the improvement here? Code style or performance?
> 
> I don't see an elaboration in PR desc or issue. If it's about perf, you'd better provide a report.

just 

> @hawkingrei so what is the improvement here? Code style or performance?
> 
> I don't see an elaboration in PR desc or issue. If it's about perf, you'd better provide a report.

This is just to simplify the code. I have updated the description of PR.

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
