### PR TITLE
owner: fix the unstable test of `TestCluster`

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/37557

Problem Summary:
In `CampaignOwner`, we do `NewSession` get an error because of `context canceled`.
Screenshot 2022-09-02 at 13 10 08

### What is changed and how it works?
In `CampaignOwner` we use `go m.campaignLoop(session)`, so I think we need to use `go` to call `CampaignOwner`.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @xiongjiwei @tiancaiamao

**Review by xhebox — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
