### PR TITLE
tidb-server: migrate test-infra to testify

### LINKED ISSUE #27143: migrate test-infra to testify for `tidb-server`

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

### What problem does this PR solve?

Issue Number: close #27143 

### Release note

```release-note
None
```

### CODE REVIEW

**Review by morgo — APPROVED** [review]

**Comment by tisonkun** [comment]
/cc @disksing @mmyj 

Please take a look. Thanks!

**Review by disksing — APPROVED** [review]

**Pull request merged**
