### PR TITLE
lightning: new regionJob from needRescan has zero retry counter

### LINKED ISSUE #43682: needRescan region job should not pass `retryCount` to new jobs
https://github.com/pingcap/tidb/blob/5c31e169446f34e398dc63f34f4208d67b4186c6/br/pkg/lightning/backend/local/local.go#L1277-L1281

In a recent import task we rely on unlimited retry number for this type of error

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #43682 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
I'll think about how to add tests :joy:

**Review by D3Hunter — APPROVED** [review]

**Review by gozssky — APPROVED** [review]

**Pull request merged**
