### PR TITLE
store/tikv: make `snapshot` thread safe

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Problem Summary:

After point get executor becoming data source node, snapshot may be used concurrently.

Snapshot is a read-only object, it should be thread safe, but as it cache data, this is not the truth.

### What is changed and how it works?

What's Changed:

Add read-write lock on the cache to make snapshot thread safe.

How it Works:

### Check List 

Tests 

- Unit test

Side effects

- Performance regression

The performance impact should be negligible.

### Release note 

- No release note

### CODE REVIEW

**Comment by tiancaiamao** [comment]
/run-all-tests
PTAL @coocood @lysu

**Comment by tiancaiamao** [comment]
PTAL @coocood @lysu

**Comment by coocood** [comment]
LGTM

**Pull request merged**
