### PR TITLE
executor: also use approximate count from pd to decide the sample rate

### LINKED ISSUE #29215: two tidb oom repeatedly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run sysbench insert 
oltp_insert --tables 32 -- sysbenchThreads 512  tableSize 10000000

### 2. What did you expect to see? (Required)
workload run normally and all instance are normal

### 3. What did you see instead (Required)
two tidb oom repeatedly
image

### 4. What is your TiDB version? (Required)
master
Image:         hub-new.pingcap.net/qa/tidb:master
    Image ID:      docker-pullable://hub-new.pingcap.net/qa/tidb@sha256:999e2c9e3cfc8b5849fe16ef252dc3d10e694969bf271f3f37373aed9

### LINKED ISSUE #29287: TiDB OOM while analyzing table in TPCH, TPCDS and Join Order Benchmark with tidb_analyze_version=2
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Take TPCH for example:
```
br restore db --db=tpch50 --pd $pd:2379 --storage s3://benchmark/tpch50-release4.0 --s3.endpoint http://xxxxxxxx:9000 --send-credentials-to-tikv=true

mysql -h $tidb -P9999 -D tpch50 -e '
                        set global tidb_allow_batch_cop = 1;
                        set session tidb_opt_distinct_agg_push_down = 1;
                        set global tidb_distsql_scan_concurrency = 30;
                        set global tidb_executor_concurrency = 16;                      '
mysql -h $tidb -P9999 -D tpch50 -e 'set tidb_build_stats_concurrency=32; set tidb_distsql_scan_concurrency=30; set tidb_index_serial_scan_concurrency=32;analyze table lineitem; analyze table orders; analyze table part; analyze table partsupp; analyze table supplier; analyze table customer; analyze table region; analyze table nation;'

```

### 3. What did you see instead (Required)
```
tpch50@5.7.25-TiDB-v5.3.0-alpha-1248-g20023fe9e>show variables like '%tidb_analyze_version%';
+----------------------+-------+
| Variable_name        | Value |
+----------------------+-------+
| tidb_analyze_version | 2     |
+----------------------+-------+
1 row in set (0.01 sec)

tpch50@5.7.25-TiDB-v5.3.0-alpha-1248-g20023fe9e>set tidb_build_stats_concurrency=32; set tidb_distsql_scan_concurrency=30; set tidb_index_serial_scan_concurrency=32;
Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

tpch50@5.7.25-TiDB-v5.3.0-alpha-1248-g20023fe9e>analyze table lineitem; analyze table orders; analyze table part; analyze table partsupp; analyze table supplier; analyze table customer; analyze table region; analyze table nation;
ERROR 2013 (HY000): Lost connection to MySQL server during query
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
ERROR: 
Can't connect to the server

No connection. Trying to reconnect...
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
ERROR: 
Can't connect to the server

No connection. Trying to reconnect...
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
ERROR: 
Can't connect to the server

No connection. Trying to reconnect...
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
ERROR: 
Can't connect to the server

No connection. Trying to reconnect...
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
ERROR: 
Can't connect to the server

No connection. Trying to reconnect...
Connection id:    3
Current database: tpch50

Query OK, 0 rows affected (0.39 sec)

Query OK, 0 rows affected (0.16 sec)
```

```
tpch50@5.7.25-TiDB-v5.3.0-alpha-1248-g20023fe9e>set @@tidb_analyze_version=1;
Query OK, 0 rows affected (0.00 sec)

tpch50@5.7.25-TiDB-v5.3.0-alpha-1248-g20023fe9e>analyze table lineitem;
Query OK, 0 rows affected (3 min 26.93 sec)

tpch50@5.7.25-TiDB-v5.3.0-alpha-1248-g20023fe9e>analyze table orders;
Query OK, 0 rows affected (16.01 sec)
```

```
dmesg -T | grep tidb-server | grep 'out of memory'
[Sun Oct 31 21:45:01 2021] Memory cgroup out of memory: Kill process 120388 (tidb-server) score 965 or sacrifice child
```

### 4. What is your TiDB version? (Required)

 ```
Release Version: v5.3.0-alpha-1248-g20023fe9e
Edition: Community
Git Commit Hash: 20023fe9eaaef9a98990ce59d6409c28767d9788
Git Branch: master
UTC Build Time: 2021-10-28 11:18:05
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: to #29216 close #29215, close https://github.com/pingcap/tidb/issues/29287

Problem Summary:
In #29216, we noticed that if we build up the table by lightning, br or something else. We miss the row number from the stats_meta.

This would led to wrong sample rate.

### What is changed and how it works?

To solve it, we get the approximate key from the PD side. And use it to decide the sample rate.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Review by time-and-fate — APPROVED** [review]

**Review by xuyifangreeneyes — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Comment by winoros** [comment]
This pr would also fix https://github.com/pingcap/tidb/issues/29287

**Pull request merged**
