### PR TITLE
telemetry: interval partitioning

### LINKED ISSUE #36525: Add usage of INTERVAL partitioning to telemetry
## Enhancement

To get more insights to the new feature for INTERVAL partitioning, we want to see the usage in telemetry data.

So we should include number of times CREATE TABLE with INTERVAL partition, ALTER TABLE LAST PARTITION (add partition) and ALTER TABLE FIRST PARTITION (drop partition) statements has been issued to the telemetry.

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #36525

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Added usage of INTERVAL partitioning to telemetry (create, alter first/last partition)
```

### CODE REVIEW

**Comment by mjonss** [comment]
This is based on https://github.com/pingcap/tidb/pull/35662 and should be reviewed as an extension on-top of that PR.

**Review by ymkzpx — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
