### PR TITLE
types: fix StrToDate handling of %h and %p

### PR DESCRIPTION
**Pull request by smola**
### What problem does this PR solve?

Problem Summary: handling of `%h` in date format is not consistent with MySQL. MySQL only allows `1..12` (with or without zero padding), while TiDB allows `01..24` (with zero padding).

### What is changed and how it works?

What's Changed:
* In `types/time.go`:
  * Removed `hour24TwoDigits`, now `%h` and `%I` are synonyms.

How it Works:

### Related changes

N/A

### Check List

Tests 

- Unit test

Side effects

- `13:00:00 am`, `%h:%i:%s %p` used to be valid, now it is not, since `%h` must be in `1..12` range.
- `1:00:00 am`, `%h:%i:%s %p` used to be invalid (single digit hour), not it is.

### Release note

- `%h` in date formats should now be in 1..12 range.

### CODE REVIEW

**Comment by wjhuang2016** [comment]
@smola 
Hi, I tested it in MySQL 8.0.19
```
mysql> SELECT STR_TO_DATE('15:35:00', '%h:%i:%s');
+-------------------------------------+
| STR_TO_DATE('15:35:00', '%h:%i:%s') |
+-------------------------------------+
| NULL                                |
+-------------------------------------+
1 row in set, 2 warnings (0.01 sec)

mysql> SELECT STR_TO_DATE('15:35:00', '%H:%i:%s');
+-------------------------------------+
| STR_TO_DATE('15:35:00', '%H:%i:%s') |
+-------------------------------------+
| 15:35:00                            |
+-------------------------------------+
1 row in set (0.00 sec)
```

It seems that MySQL allows  `01..24`

**Comment by smola** [comment]
@wjhuang2016 Note you get `NULL` for `STR_TO_DATE('15:35:00', '%h:%i:%s')`.

**Pull request merged**
