### PR TITLE
*: add tidb_hashagg_partial/final_concurrency

### PR DESCRIPTION
**Pull request by XuHuaiyu**
Thank you for working on TiDB! Please read TiDB's [CONTRIBUTING](https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md) document **BEFORE** filing this PR.

## What have you changed? (mandatory)

This commit adds 2 system variables:
- tidb_hashagg_partial_concurrency: control the number of hash agg partial workers
- tidb_hashagg_final_concurrency: control the number of hash agg final workers

## What are the type of the changes (mandatory)?

The currently defined types are listed below, please pick one of the types for this PR by removing the others:
- New feature (non-breaking change which adds functionality)

## How has this PR been tested (mandatory)?

unit-test

## Does this PR affect documentation (docs/docs-cn) update? (optional)

If there is document change, please file a PR in ([docs](https://github.com/pingcap/docs) and [docs-cn](https://github.com/pingcap/docs-cn)) and add the PR number here.

## Refer to a related PR or issue link (optional)
#6658

### CODE REVIEW

**Comment by shenli** [comment]
Please fix the CI.

**Comment by jackysp** [comment]
I think we can estimate a default value for these two variables.

**Comment by zz-jason** [comment]
@jackysp 
1. the estimated values maybe not correct
2. sometimes we need to manually set these concurrency values

**Comment by jackysp** [comment]
We can also set these manually if we estimate default values for them.

**Comment by XuHuaiyu** [comment]
Ok, I've created a jira issue for it.
This should be done in an individual PR. @jackysp

**Pull request merged**
