### PR TITLE
txn: move some methods in `session_txn` to internal pacakge

### LINKED ISSUE #36033: move some methods in `session_txn` to internal pacakge

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #36033

### What is changed and how it works?

Some methods are only used by `session_txn` itself, so move them to internal package.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by you06 — COMMENTED** [review]
Is `sessiontxn/txn.go:NewOracleFuture` an internal function?

**Review by SpadeA-Tang — APPROVED** [review]

**Review by you06 — APPROVED** [review]

**Review by xhebox — COMMENTED** [review]
Maybe rename `txn.go` to  `future.go` since it only a furture.

**Review by xhebox — APPROVED** [review]

**Pull request merged**
