### PR TITLE
parser/opcode: fix format function for mod opcode (#7455)

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry-pick from https://github.com/pingcap/tidb/pull/7455 to release-2.0
This is a parser bug, but it may cause trouble for DDL

@winkyao @lysu @hicqu

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8431)

### CODE REVIEW

**Comment by tiancaiamao** [comment]
/run-all-tests tidb-test=release-2.0 pd=release-2.0 tikv=release-2.0

**Comment by zz-jason** [comment]
LGTM

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.0 pd=release-2.0 tikv=release-2.0

**Comment by zz-jason** [comment]
@lysu @jackysp PTAL

**Pull request merged**
