### PR TITLE
planner: natural join not consider rowid and null eq not propagate (#21328)

### LINKED ISSUE #17817: P1-[4.0 bug hunting]-[SQL Plan Management]-NATURAL LEFT JOIN results in incorrect result for <=> operator
Bug Hunter issue tidb-challenge-program/bug-hunting-issue#5

---

Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);
INSERT INTO t0 VALUES (0);
INSERT INTO t1 VALUES (0);
SELECT * FROM t1 NATURAL LEFT JOIN t0 WHERE NOT(t0.c0<=>t1.c0); -- expected: {}, actual: {0}
```
Unexpectedly, the `SELECT` fetches a row:
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1452
Server version: 5.7.25-TiDB-v4.0.0-beta.2-231-gc66320c46 TiDB Server (Apache License 2.0), MySQL 5.7 compatible

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE TABLE t0(c0 INT);
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE t1(c0 INT);
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO t0 VALUES (0);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (0);
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * FROM t1 NATURAL LEFT JOIN t0 WHERE NOT(t0.c0<=>t1.c0); -- expected: {}, actual: {0}
+------+
| c0   |
+------+
|    0 |
+------+
1 row in set (0.00 sec)
```

 Interestingly, the following query with the negated predicate also fetches a row, which is expected:
```sql
SELECT t1.c0 FROM t1 NATURAL LEFT JOIN t0 WHERE t0.c0<=>t1.c0 -- {0}
```
I double-checked with MySQL 8.0.19, which does not fetch a row for the first query, as expected:
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 14
Server version: 8.0.19 MySQL Community Server - GPL

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE TABLE t0(c0 INT);
Query OK, 0 rows affected (0.04 sec)

mysql> CREATE TABLE t1(c0 INT);
Query OK, 0 rows affected (0.04 sec)

mysql> INSERT INTO t0 VALUES (0);
Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO t1 VALUES (0);
Query OK, 1 row affected (0.01 sec)

mysql> SELECT * FROM t1 NATURAL LEFT JOIN t0 WHERE NOT(t0.c0<=>t1.c0); -- expected: {}, actual: {0}
Empty set (0.00 sec)
```
Environment:
```
| Release Version: v4.0.0-beta.2-231-gc66320c46
Git Commit Hash: c66320c46456c0d5b23b3b0403be6b9f8227d6d8
Git Branch: master
UTC Build Time: 2020-04-14 11:12:29
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```
I propose P0 as a bug level, since it matches the following description: `wrong results returned by the query, and inconsistent results returned by the SQL output`.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21328 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #17817

### What is changed and how it works?

How it Works: as the title says.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- natural join should not consider rowid and null eq should not propagate in outer join.

### CODE REVIEW

**Review by eurekaka — COMMENTED** [review]
@lzmhhh123 please resolve conflicts.

**Review by eurekaka — COMMENTED** [review]
LGTM

**Comment by zz-jason** [comment]
@lzmhhh123 please resolve conflicts.

**Review by qw4990 — APPROVED** [review]
LGTM

**Comment by qw4990** [comment]
```
[2021-01-27T03:55:14.366Z] PANIC: executor_test.go:183: testSuiteWithData.SetUpSuite

[2021-01-27T03:55:14.366Z] 

[2021-01-27T03:55:14.366Z] ... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0x1258381)

[2021-01-27T03:55:14.366Z] 

[2021-01-27T03:55:14.366Z] /usr/local/go/src/runtime/panic.go:679

[2021-01-27T03:55:14.366Z]   in gopanic

[2021-01-27T03:55:14.366Z] /usr/local/go/src/runtime/panic.go:199

[2021-01-27T03:55:14.366Z]   in panicmem

[2021-01-27T03:55:14.366Z] /usr/local/go/src/runtime/signal_unix.go:394

[2021-01-27T03:55:14.366Z]   in sigpanic

[2021-01-27T03:55:14.366Z] executor_test.go:158

[2021-01-27T03:55:14.366Z]   in baseTestSuite.SetUpSuite

[2021-01-27T03:55:14.366Z] executor_test.go:184

[2021-01-27T03:55:14.366Z]   in testSuiteWithData.SetUpSuite

[2021-01-27T03:55:14.366Z] /usr/local/go/src/reflect/value.go:321

[2021-01-27T03:55:14.366Z]   in Value.Call

[2021-01-27T03:55:14.366Z] /home/jenkins/agent/workspace/tidb_ghpr_check/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:799

[2021-01-27T03:55:14.366Z]   in suiteRunner.runFixture.func1

[2021-01-27T03:55:14.366Z] /home/jenkins/agent/workspace/tidb_ghpr_check/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739

[2021-01-27T03:55:14.366Z]   in suiteRunner.forkCall.func1

[2021-01-27T03:55:14.366Z] /usr/local/go/src/runtime/asm_amd64.s:1357

[2021-01-27T03:55:14.366Z]   in goexit

[2021-01-27T03:55:14.366Z] 

[2021-01-27T03:55:14.366Z] ----------------------------------------------------------------------

[2021-01-27T03:55:14.366Z] MISS: join_test.go:649: testSuiteWithData.TestNaturalJoin

[2021-01-27T03:55:14.366Z] 

[2021-01-27T03:55:14.366Z] ----------------------------------------------------------------------

[2021-01-27T03:55:14.366Z] PANIC: executor_test.go:190: testSuiteWithData.TearDownSuite

[2021-01-27T03:55:14.366Z] 

[2021-01-27T03:55:14.366Z] ... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0x1258381)

[2021-01-27T03:55:14.366Z] 

[2021-01-27T03:55:14.366Z] /usr/local/go/src/runtime/panic.go:679

[2021-01-27T03:55:14.366Z]   in gopanic

[2021-01-27T03:55:14.366Z] /usr/local/go/src/runtime/panic.go:199

[2021-01-27T03:55:14.366Z]   in panicmem

[2021-01-27T03:55:14.366Z] /usr/local/go/src/runtime/signal_unix.go:394

[2021-01-27T03:55:14.366Z]   in sigpanic

[2021-01-27T03:55:14.366Z] executor_test.go:206

[2021-01-27T03:55:14.366Z]   in baseTestSuite.TearDownSuite

[2021-01-27T03:55:14.366Z] executor_test.go:191

[2021-01-27T03:55:14.366Z]   in testSuiteWithData.TearDownSuite

[2021-01-27T03:55:14.366Z] /usr/local/go/src/reflect/value.go:321

[2021-01-27T03:55:14.366Z]   in Value.Call

[2021-01-27T03:55:14.366Z] /home/jenkins/agent/workspace/tidb_ghpr_check/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:799

[2021-01-27T03:55:14.366Z]   in suiteRunner.runFixture.func1

[2021-01-27T03:55:14.366Z] /home/jenkins/agent/workspace/tidb_ghpr_check/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739

[2021-01-27T03:55:14.366Z]   in suiteRunner.forkCall.func1

[2021-01-27T03:55:14.366Z] /usr/local/go/src/runtime/asm_amd64.s:1357

[2021-01-27T03:55:14.366Z]   in goexit
```
PTAL @lzmhhh123

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
