### PR TITLE
ddl: replace SetDDLErrorCountLimit

### LINKED ISSUE #27334: SetDDLErrorCountLimit doesn't work in tests
## Bug Report

The following code does not work in `countForPanic`.
```
TestCreateTableNoBlock
...
	save := variable.GetDDLErrorCountLimit()
	variable.SetDDLErrorCountLimit(1)
	defer func() {
		variable.SetDDLErrorCountLimit(save)
	}()
...
```

We need use `set @@global.tidb_ddl_error_count_limit = 1` instead of above code. In addition, there are quite a few places in the test where the above code is used, all of which need to be handled.

After the change, the test execution will be faster.

### PR DESCRIPTION
**Pull request by unconsolable**
Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>

### What problem does this PR solve?

Issue Number: close #27334

Problem Summary:

### What is changed and how it works?

What's Changed:
- Replace `SetDDLErrorCountLimit` to `set @@global.tidb_ddl_error_count_limit`
- Move a test from `partition_test.go` to `db_partition_test.go` to support SQL execution

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by unconsolable** [comment]
/cc @zimulala 
PTAL

**Review by tangenta — APPROVED** [review]

**Comment by unconsolable** [comment]
/cc @xiongjiwei 
PTAL

**Review by xiongjiwei — APPROVED** [review]

**Pull request merged**
