### PR TITLE
executor/metrics: distinguish desc a table and explain a SQL on metrics

### LINKED ISSUE #31115: Improve some metrics on Grafana
## Enhancement

- [ ] TiDB client traffic is too complex, make it simply.
- [ ] `DESC` and `EXPLAIN` are used to show columns of a table and explain a SQL which should be separated on metrics.
- [ ] Add index duration and rate are merged into one panel, which makes the user confused.
- [ ] Batch client requests are displayed as a hate map, which is difficult to decide how many to change `max-batch-size`.

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve?

Issue Number: close #31115

Problem Summary:
SQL like desc/explain does two things, 
1. describes the table structure, many frameworks do this automatically, 
2. outputs the execution plan of the SQL. 
TiDB needs to distinguish them in metrics.

### What is changed and how it works?
Distinguish them by labels.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. start a cluster
1. run some desc table and then some explain SQL
1. check it on Grafana
image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by coocood — APPROVED** [review]

**Comment by jackysp** [comment]
PTAL @bb7133 @wjhuang2016

**Review by wjhuang2016 — APPROVED** [review]

**Comment by hawkingrei** [comment]
Have some fail test in ci. Please fix it.

**Comment by jackysp** [comment]
Fixed @hawkingrei

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
