### PR TITLE
ddl: fix the issue that "rename column" fails when changing column type concurrently

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/31075

Problem Summary:
```
create table t(a int, b int);
```

In session 1: `alter table t change column b b double;`(DDL1)
In session 2: `alter table t rename column b to c; `(DDL2)

Decode the ModifyColumn's args:
` job.DecodeArgs(&jobParam.newCol, &jobParam.oldColName, jobParam.pos, &jobParam.modifyColumnTp, &jobParam.updatedAutoRandomBits, &jobParam.changingCol, &jobParam.changingIdxs)`

The rename column uses the ModifyColumn job. But the rename column uses 4 args.
After running DDL1, we do DDL2 need to change column type with data. So we will add `changingCol` and `changingIdxs` to args but not `updatedAutoRandomBits`. So it will return an error.

### What is changed and how it works?
Add `updatedAutoRandomBits` to the rename column operation.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the issue that "rename column" fails when changing column type concurrently.
```

### CODE REVIEW

**Review by AilinKid — APPROVED** [review]
LGTM

**Comment by zimulala** [comment]
PTAL @tangenta

**Review by tangenta — APPROVED** [review]

**Pull request merged**
