### PR TITLE
expression: Improve the compatibility of `str_to_date` (#25386)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25386 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25767
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25767:release-5.0-8434069c5f63
```

---

### What problem does this PR solve?

Issue Number: related to https://github.com/pingcap/tidb/issues/24928

Problem Summary:
* '%b'/'%M' should be case insensitive
* Improve the compatibility of parsing some input for "%r" and "%T"

### What is changed and how it works?

* Use [`strings.EqualFold`](https://golang.org/pkg/strings/#EqualFold) for case insensitive prefix comparing in `fullNameMonth`
* Make `abbreviatedMonth` case insensitive
* Make `time12Hour` and `time24Hour` accept some irregular inputs

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
- Breaking backward compatibility

### Release note 

- Improve the MySQL compatibility of `str_to_date` for `%b`/`%M`/`%r`/`%T`

### CODE REVIEW

**Comment by JaySon-Huang** [comment]
```
[2021-06-25T12:09:05.702Z] ./tools/check/check_testSuite.sh
[2021-06-25T12:09:07.604Z] tools/bin/golangci-lint run -v --disable-all --deadline=3m \
[2021-06-25T12:09:07.604Z]   --enable=misspell \
[2021-06-25T12:09:07.604Z]   --enable=ineffassign \
[2021-06-25T12:09:07.604Z]   --enable=varcheck \
...
[2021-06-25T12:09:19.085Z] level=info msg="[runner] linters took 5.641386383s with stages: goanalysis_metalinter: 5.626532342s"
[2021-06-25T12:09:19.085Z] types/time.go:3017:3: ineffectual assignment to `state` (ineffassign)
[2021-06-25T12:09:19.085Z] 		state := parseStateNormal
[2021-06-25T12:09:19.085Z] 		^
[2021-06-25T12:09:19.085Z] types/time.go:3095:3: ineffectual assignment to `state` (ineffassign)
[2021-06-25T12:09:19.085Z] 		state := parseStateNormal
[2021-06-25T12:09:19.085Z] 		^
```
Why this link check didn't apply to the master branch?

**Comment by JaySon-Huang** [comment]
@wshwsh12 @guo-shaoge  @wjhuang2016 PTAL

**Review by wshwsh12 — APPROVED** [review]

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
