### PR TITLE
expression: use encode buffer in to_binary, warp encrypt function with to_binary

### PR DESCRIPTION
**Pull request by unconsolable**
Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>

### What problem does this PR solve?

Issue Number: ref #29863 

### What is changed and how it works?
- Introduce an encode buffer in `(*builtinInternalToBinarySig) vecEvalString`
- Warp several encrypt function with `to_binary`
- Update `new_character_set_builtin.result` because there is an inconsistency between vectorization and scalar function

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]
Good job!

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by unconsolable** [comment]
/assign @zimulala 
Please help on merge, thanks.

**Pull request merged**
