### PR TITLE
*: fix a bug that the pessimistic lock doesn't work on a partition (#14921)

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry-pick https://github.com/pingcap/tidb/pull/14921

Resolve conflict because the tblID2Handle is in the Schame() in 3.0 branch

### CODE REVIEW

**Comment by tiancaiamao** [comment]
CI failure is not caused by this change.
Issue here https://github.com/pingcap/tidb/issues/15118

PTAL @coocood @winoros

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
PTAL @winoros

**Pull request merged**
