### PR TITLE
executor: refine an error log message

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Display conflict keys for the pessimistic lock conflict in the log.

Before:
```
 [2019/08/15 15:38:05.626 +08:00] [INFO] [adapter.go:464] [“pessimistic write conflict, retry statement”] [conn=46396] [txn=410479410413568034] [forUpdateTS=410479410675712001] [conflictCommitTS=410479410701926401]
```

After:

```
[2019/08/16 14:46:17.322 +08:00] [INFO] [adapter.go:475] ["single statement deadlock, retry statement"] [txn=410501245124214785] [lockTS=410501245124214784] [lockKey="dIAAAAAAAAA8X3KAAAAAAAAAAw=="] [deadlockKeyHash=1804423900836245255] [err="lock_ts:410501245124214784 lock_key:\"t\\200\\000\\000\\000\\000\\000\\000<_r\\200\\000\\000\\000\\000\\000\\000\\003\" deadlock_key_hash:1804423900836245255 "]
[2019/08/16 14:46:17.377 +08:00] [INFO] [adapter.go:488] ["pessimistic write conflict, retry statement"] [txn=410501245124214785] [forUpdateTS=410501245127098368] [conflictCommitTS=0] [err="[kv:9007]Write conflict, txnStartTS=410501245127098368, conflictStartTS=410501245127360512, conflictCommitTS=0, key={tableID=60, handle=3} primary=[]byte(nil) [try again later]"]
```

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
 - No code

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @coocood @lysu

**Comment by coocood** [comment]
The error message has duplicated information.

**Comment by tiancaiamao** [comment]
forUpdateTS ? @coocood

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
PTAL @lysu

**Pull request merged**
