### PR TITLE
expression: FROM_UNIXTIME(12.1) + 1 return wrong field type

### PR DESCRIPTION
**Pull request by louishust**
FROM_UNIXTIME(12.1) + 1 return datetime field type instead of
Decimal datetime, which is different from MySQL.

### CODE REVIEW

**Comment by louishust** [comment]
Related to issue #3047

**Comment by XuHuaiyu** [comment]
hi, @louishust 
Thank you for your PR,
but this commit may not fix the issue.

The problem is not caused by the type inferring of `from_unixtime` 
but the type inferring of `plus(+)`.

You can use [MySQL Workbench](https://dev.mysql.com/downloads/workbench/) to check the Field Types of a query. After executing a query, there will be a "Field Types" label in the result window.

**Comment by louishust** [comment]
@XuHuaiyu I have test it in Workbench and it works.

mergeArithType function is used in type interfer for binaryOperationExpr, 
and mergeArithType use the decimal to determine the ArithType.

**Comment by XuHuaiyu** [comment]
@louishust 
Ok, but the decimal of the result of `from_unixtime(val)` 
is not always MaxFsp,
it is related to `val`.

**Comment by shenli** [comment]
@louishust Could you add an unit test?

**Comment by louishust** [comment]
@shenli  add unit test done!

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by shenli** [comment]
LGTM
@louishust Thanks!

**Pull request merged**
