### PR TITLE
topsql: always clean goroutine labels for internal sql after finish execution

### LINKED ISSUE #34405: unkonw SQL in TopSQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a cluster:
```shell
tiup playground nightly --tiflash 0
```
2.  Enable TopSQL
3. Wait 1 minute.

### 2. What did you expect to see? (Required)

The SQL instead of digest.

### 3. What did you see instead (Required)

origin_img_v2_44dba912-2bfc-4233-a921-0dd0a53bc06g

### 4. What is your TiDB version? (Required)

master: b3ec891b3ce700846c8f4e0c2fcb98ee34e8bd06

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Issue Number: close #34405

### What is changed and how it works?

Always reset the goroutine label for internal sql after finish execution.

The issue is introduce by https://github.com/pingcap/tidb/pull/33861, since currently will always set the SQL digest to the goroutine, but doesn't clean labels after SQL execution finish. Some background worker in TiDB, after finish execute internal SQL, it will do other things which will consume cpu, and those cpu will calculated to the internal sql, but it is wrong, since the internal SQL is execution finished, but we doesn't clean the sql label in the goroutine.

### Check List

Tests 

- [x] Manual test (add detailed scripts or steps below)

Side effects

Documentation

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@zhongzc @mornyx PTAL

**Comment by zhongzc** [comment]
Can you provide the performance impaction report?

**Comment by crazycs520** [comment]
> Can you provide the performance impaction report?

Since I only change the code for the internal SQL execution path, it doesn't have any performance impact for the TiDB user.

**Review by zhongzc — APPROVED** [review]

**Review by mornyx — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
