### PR TITLE
cmd/ddltest: batch setup/teardown

### LINKED ISSUE #28771: integration-ddl-test failed due to timeout
Highly possibly introduced by #28423 .

Where we "pushdown" setup/teardown into cases instead of globally.

Will Prepare a hack to workaround this but hopefully we can keep the logic in the same repo as well as move the validation stage before PR merged so that we can prevent this regression.

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #28771 .

Signed-off-by: tison <wander4096@gmail.com>

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
/cc @zimulala @xhebox 

Please take a look at this fix on ddl test. Sorry to introduce this issue by wrongly setup/teardown suite.

The solution is a bit dirty. I'd prefer use a global parent tests for setup/teardown, but it will change the test name regex, which mismatches the change made in https://github.com/PingCAP-QE/ci/pull/435 .

I hope we can later gather all test config in main repo so that we don't have to do a clumsy cross repo debugging. Also `integration-ddl-test` runs only 5 minutes and it's better to be a PR merge blocker.

**Comment by tisonkun** [comment]
@zimulala `TestMain` doesn't have a `testing.T` instance and thus we should change `require` to `error` or other assertion.

A clean resolution is batch tests in `TestDDLSuite(t *testing.T)` and then:

```
func TestDDLSuite(t *testing.T) {
  s := createDDLSuite(t)
  defer s.teardown(t)

  t.Run("Xxx", SubTestXxx)
}
```

But it will change the test name which conflicts with PingCAP-QE/ci settings. That's why I comment 

> I hope we can later gather all test config in main repo so that we don't have to do a clumsy cross repo debugging.

**Comment by tisonkun** [comment]
@zimulala does the reason above convincing?

**Comment by zimulala** [comment]
> @zimulala does the reason above convincing?

Got it.

**Pull request merged**
