### PR TITLE
test: enable race for with real tikv

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close None

Problem Summary:

### What is changed and how it works?

enable the race to find the data race as soon as possible.

If enable the race for statisticstest/txntest. It takes less than 5min to complete the test cases.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
If enable the race for statisticstest/txntest. It takes less than 5min to complete the test cases.

**Review by xhebox — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Pull request merged**
