### PR TITLE
br/pkg/summary: migrate test-infra to testify

### LINKED ISSUE #28180: migrate test-infra to testify for `br/pkg/summary`

### PR DESCRIPTION
**Pull request by shadw3002**
### What problem does this PR solve?

Issue Number: close #28180 

Problem Summary: migrate test-infra to testify for br/pkg/summary

### What is changed and how it works?

What's Changed: migrate test-infra to testify for br/pkg/summary
### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by shadw3002** [comment]
/cc @tisonkun
PTAL

**Review by mmyj — APPROVED** [review]
lgtm

**Pull request merged**
