### PR TITLE
*: support certificate based authentication (#13955) 

### PR DESCRIPTION
**Pull request by lysu**
cherry-pick #13955 to 3.0

mainly conflict:

- `logutil.Bg` -> `logutil.Logger(context.Background())`
- `ExecRestrictedSQL` need pass ctx in 3.0
-  `MySQLPrivilege`'s map speed up pr doesn't cherry-pick
- `TestFastAnalyze` table name +2

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/14202)

### CODE REVIEW

**Comment by lysu** [comment]
need merge https://github.com/pingcap/parser/pull/698 before this pr

**Comment by tiancaiamao** [comment]
LGTM

**Comment by lysu** [comment]
@jackysp need remerge

**Pull request merged**
