### PR TITLE
*: show current auto_increment ID

### PR DESCRIPTION
**Pull request by spongedu**
1. Update field `AUTO_INCREMENT` in table `INFORMATION_SCHEMA.TABLES`
2. Show auto_increment id  when execute `SHOW CREATE TABLE` 

This `AUTO_INCREMENT` value and auto id `Allocator` is not revert after a transaction rollback

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/5006)

### CODE REVIEW

**Comment by coocood** [comment]
@spongedu 
Thank you, but this solution is not complete.

If we have multiple tidb-server, some of the servers may have stale auto_increment ID.

Another problem is that the `TableInfo` is always read-only, so we can have multiple goroutines read it without lock, modify it breaks the rule.

**Comment by spongedu** [comment]
Hi, @coocood:
Thanks for your review.
There's something I'm not clear yet:
1. Since I don't change the way how `autoid` is allocated(just take out the current base and store it in `TableInfo`), in my opinion,  the stale auto_increment ID problem still exists without this pr.
2.  The `SHOW CREATE TABLE` statement read details from `TableInfo` and fill in `INFORMATION_SCHEMA.TABLES`. If `TableInfo` is always read-only, how could we update it?

**Comment by coocood** [comment]
@spongedu 
1. Yes.
2. We regularly check schema change, if the schema changed, we copy the old InfoSchema to a new InfoSchema, modify the changed TableInfo and swap the pointer of InfoSchema.
You can check out the code `domain/domain.go:64`.

**Comment by coocood** [comment]
@spongedu 
I think if need to show the correct auto_id, we need to read it directly from KV instead of TableInfo.

**Comment by spongedu** [comment]
@coocood  
Thanks very much for your advise :)  I'll check how to get this done. Could you add a `WIP` tag for this pr?

**Comment by winkyao** [comment]
@coocood read from tikv will jump over all the cache autoID range that not use yet.

**Comment by zhexuany** [comment]
@spongedu please resolve conflicts

**Comment by zz-jason** [comment]
@spongedu friendly ping, any update?

**Comment by spongedu** [comment]
This pr is too old to update. I'll close this pr and try to make the modification on the current code base.

**Pull request closed without merging**
