### PR TITLE
session: Fix txn.onStmtEnd is not called when some special error occurs in ExecutePreparedStmt

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What problem does this PR solve?

Problem Summary:

In this part of code, previously it calls `onStmtStart`, calculates the result, calls `onStmtEnd`, and return the result. However later [some modification](https://github.com/pingcap/tidb/pull/25156) to this code adds some more return statements between the `onStmtStart` and `onStmtEnd` calls, which makes the `onStmtEnd` not called in some rare cases. This PR fixes it by calling `onStmtEnd` in defer statement.

### What is changed and how it works?

What's Changed: Call the `onStmtEnd` in defer stmt.

### Related changes

- Need to cherry-pick to the release branch
  - release-5.1

### Check List 

Tests 

-

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note.

### CODE REVIEW

**Review by cfzjywxk — COMMENTED** [review]
/lgtm

**Review by longfangsong — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
/lgtm

**Pull request merged**
