### PR TITLE
planner: fix the wrong range built for bit columns when reusing cached plan (#33090)

### LINKED ISSUE #33067: wrong IndexRangeScan for bit column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
drop table if exists IDT_MULTI22970;
source [test.txt](https://github.com/pingcap/tidb/files/8250040/test.txt)

prepare stmt from 'select * from IDT_MULTI22970 where col1 is not null and col2 not in (?, ?, ?) and col3 in (?, ?, ?);';
set @a=-21188, @b=26824, @c=31855, @d="5597-1-4", @e="5755-12-6", @f="1253-7-12";
execute stmt using @a,@b,@c,@d,@e,@f;
set @a=-5360, @b=-11715, @c=9399, @d="9213-09-13", @e="4705-12-24", @f="9901-06-17";
execute stmt using @a,@b,@c,@d,@e,@f;
select * from IDT_MULTI22970 where col1 is not null and col2 not in (-5360, -11715, 9399) and col3 in ("9213-09-13", "4705-12-24", "9901-06-17");

```
### 2. What did you expect to see? (Required)
```
MySQL [test]> execute stmt using @a,@b,@c,@d,@e,@f;
+--------------------------------------------------------------+------+------------+------------+
| COL1                                                         | COL2 | COL3       | COL4       |
+--------------------------------------------------------------+------+------------+------------+
| 皪禆簤笳鏽殷雁譹缪偸荸粵綃篺伾嗯覲竬莃坽 | y�   | 9213-09-13 |  654993671 |
| 嶔Ė戙纚业锈痰啵满迂撖阂蘻飮韚齳ò柹吟圳   |  �   | 4705-12-24 |  893651658 |
| 贛翆饏粢惿苧栶掹哽旴菄慉諠俄锞ņƈ姹瓩點   | >d   | 9901-06-17 | 1952622619 |
+--------------------------------------------------------------+------+------------+------------+
3 rows in set (0.00 sec)

MySQL [test]> select * from IDT_MULTI22970 where col1 is not null and col2 not in (-5360, -11715, 9399) and col3 in ("9213-09-13", "4705-12-24", "9901-06-17");
+--------------------------------------------------------------+------+------------+------------+
| COL1                                                         | COL2 | COL3       | COL4       |
+--------------------------------------------------------------+------+------------+------------+
| 皪禆簤笳鏽殷雁譹缪偸荸粵綃篺伾嗯覲竬莃坽 | y�   | 9213-09-13 |  654993671 |
| 嶔Ė戙纚业锈痰啵满迂撖阂蘻飮韚齳ò柹吟圳   |  �   | 4705-12-24 |  893651658 |
| 贛翆饏粢惿苧栶掹哽旴菄慉諠俄锞ņƈ姹瓩點   | >d   | 9901-06-17 | 1952622619 |
+--------------------------------------------------------------+------+------------+------------+
3 rows in set (0.00 sec)

```

### 3. What did you see instead (Required)
```
MySQL [test]> execute stmt using @a,@b,@c,@d,@e,@f;
+--------------------------------------------------------------+------+------------+------------+
| COL1                                                         | COL2 | COL3       | COL4       |
+--------------------------------------------------------------+------+------------+------------+
| 皪禆簤笳鏽殷雁譹缪偸荸粵綃篺伾嗯覲竬莃坽 | y�   | 9213-09-13 |  654993671 |
| 皪禆簤笳鏽殷雁譹缪偸荸粵綃篺伾嗯覲竬莃坽 | y�   | 9213-09-13 |  654993671 |
| 嶔Ė戙纚业锈痰啵满迂撖阂蘻飮韚齳ò柹吟圳   |  �   | 4705-12-24 |  893651658 |
| 贛翆饏粢惿苧栶掹哽旴菄慉諠俄锞ņƈ姹瓩點   | >d   | 9901-06-17 | 1952622619 |
| 贛翆饏粢惿苧栶掹哽旴菄慉諠俄锞ņƈ姹瓩點   | >d   | 9901-06-17 | 1952622619 |
+--------------------------------------------------------------+------+------------+------------+
5 rows in set (0.00 sec)

MySQL [test]> select * from IDT_MULTI22970 where col1 is not null and col2 not in (-5360, -11715, 9399) and col3 in ("9213-09-13", "4705-12-24", "9901-06-17");
+--------------------------------------------------------------+------+------------+------------+
| COL1                                                         | COL2 | COL3       | COL4       |
+--------------------------------------------------------------+------+------------+------------+
| 皪禆簤笳鏽殷雁譹缪偸荸粵綃篺伾嗯覲竬莃坽 | y�   | 9213-09-13 |  654993671 |
| 嶔Ė戙纚业锈痰啵满迂撖阂蘻飮韚齳ò柹吟圳   |  �   | 4705-12-24 |  893651658 |
| 贛翆饏粢惿苧栶掹哽旴菄慉諠俄锞ņƈ姹瓩點   | >d   | 9901-06-17 | 1952622619 |
+--------------------------------------------------------------+------+------------+------------+
3 rows in set (0.00 sec)

```
### 4. What is your TiDB version? (Required)

```
Release Version: v6.0.0-alpha-82-g7ca9aff
Edition: Community
Git Commit Hash: 7ca9affabb3e1ba05bb3a3b357c2bf491d9ed330
Git Branch: master
UTC Build Time: 2022-03-15 01:02:37
GoVersion: go1.17.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #33090 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/33096
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/33096:release-5.4-caad839aebf2
```

---

### What problem does this PR solve?

Issue Number: close #33067

Problem Summary: planner: fix the wrong range built for bit columns when reusing cached plan

### What is changed and how it works?

planner: fix the wrong range built for bit columns when reusing cached plan

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Please resolve conflict @qw4990

**Comment by MimeLyc** [comment]
test tirelease

**Review by chrysan — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]

**Pull request merged**
