### PR TITLE
planner, sessionctx: enable late materialization in disaggregated TiFlash

### LINKED ISSUE #40601: Support late materialization
## Feature Request

**Is your feature request related to a problem? Please describe:**

For some query like `select * from t where a == 0`;, we now scan all columns and then do filter, which is heavy and we can do better.

**Describe the feature you'd like:**

Support late materialization. We can scan column(s) at first to filter out unnecessary data segment, and then just scan the rest columns and only read necessary rows.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #40601 

Problem Summary:

### What is changed and how it works?

depends on https://github.com/pingcap/tiflash/pull/7295

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Comment by Lloyd-Pottiger** [comment]
hold, merge after #42989

**Pull request merged**
