### PR TITLE
binlog: update config for backward compatibility

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
### What problem does this PR solve? 
pr https://github.com/pingcap/tidb/pull/9625  break the backward compatibility,
this pr fix it

### What is changed and how it works?
1. change binlog.enable's type to bool as before
2. add a new config binlog.automode, if automode is true, enable binlog by global system variable 'tidb_log_bin'

### Check List 

Tests 

 - Unit test
 - Manual test (set binlog.enable and binlog.mode)

Related changes

 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Comment by jackysp** [comment]
Please fix CI.

**Comment by gregwebs** [comment]
This looks like a great solution. I have one concern: the new variable is a string with one allowed value besides empty: "auto". Can we validate this so that we reject other values?

We could instead make the "mode" a boolean so that it will be validated, but these changes show that a string is more extensible for future changes.

**Comment by WangXiangUSTC** [comment]
@gregwebs I changed `Mode` to `AutoMode`, and change type to bool

**Comment by gregwebs** [comment]
LGTM

**Pull request merged**
