### PR TITLE
statistics: split table analysis job into three different types of jobs

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/50132

close https://github.com/pingcap/tidb/issues/51534

Problem Summary:

### What changed and how does it work?

In this PR, I only did some refactorings, I haven't changed any real logic.

The main change is, I split the job into three different jobs:
1. NonPartitionedTableAnalysisJob for non-partitioned tables.
2. DynamicPartitionedTableAnalysisJob for dynamic pruned tables.
3. StaticPartitionedTableAnalysisJob for static pruned tables.

So you can focus on these three structures to review this PR.

For each job, you can focus on `Analyze` and `IsValidToAnalyze` APIs. 

`Analyze` will execute the different statements to do the analysis job.
`IsValidToAnalyze` will check if the table analysis just failed a short period of time ago.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by time-and-fate — APPROVED** [review]

**Review by elsa0520 — APPROVED** [review]
LGTM

**Pull request merged**
