### PR TITLE
server: failpoint for some integration tests

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve?

Problem Summary:

Add some necessary fail points for integration tests, which will be used in test cases, like
- [case](https://github.com/pingcap/automated-tests/pull/116)
- [case](https://github.com/pingcap/automated-tests/pull/87)

### Check List 

Tests 

- Unit test

Side effects

### CODE REVIEW

**Comment by jackysp** [comment]
Should it be backported to release-4.0?

**Comment by cfzjywxk** [comment]
> Should it be backported to release-4.0?

It's needed

**Pull request merged**
