### PR TITLE
executor: migrate test-infra to testify for executor/show_stats_test.go

### LINKED ISSUE #28611: migrate test-infra to testify for `show_stats_test.go`

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #28611

Problem Summary:

### What is changed and how it works?

migrate test-infra to testify for executor/show_stats_test.go

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM. Thank you!

**Review by Yisaer — APPROVED** [review]

**Pull request merged**
