### PR TITLE
planner/core,binloginfo: add a projection to fix 'delete from join' schema (#8805)

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry pick from https://github.com/pingcap/tidb/pull/8805

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @jackysp @lysu

**Comment by zz-jason** [comment]
LGTM

**Comment by lysu** [comment]
/run-all-test tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by jackysp** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Pull request merged**
