### PR TITLE
modularity:split eval.go into some small files

### PR DESCRIPTION
**Pull request by XuHuaiyu**
I split distsq/xeval/eval.go into small files according to operators' type.
PTAL
@hanfei1991 @coocood @zimulala @tiancaiamao @shenli

### CODE REVIEW

**Comment by hanfei1991** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Comment by ngaut** [comment]
Good job.

**Comment by tiancaiamao** [comment]
I think the commit message should changed to module name rather than refactor

**Comment by XuHuaiyu** [comment]
@tiancaiamao PTAL

**Pull request merged**
