### PR TITLE
*: prototype assertion

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

WIP..and try more, will split PR to go-client & master if done.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Why not considering check the binlog ...
It's not non-disrupting to TiDB and perhaps a better solution.

**Comment by lysu** [comment]
> Why not considering check the binlog ...
> It's not non-disrupting to TiDB and perhaps a better solution.

also investigate that in parallel~(instead of check binlog, we check 2pc mutation, because not every clustered enable binlog and binlog mutation also has some memory alloc cost.)...but it seems not easy to full check all situations from mutations, e.g. we have a put row mutation, we can check its index mutations, but it's hard to check "the commit doesn't miss delete old index"...but we still investigate that maybe we can combine those one to hint some information to help 2pc mutation check

**Pull request closed without merging**
