### PR TITLE
session: remove the mockFail field from txnFuture

### PR DESCRIPTION
**Pull request by lonng**
Signed-off-by: Lonng <heng@lonng.org>

### What problem does this PR solve? 

1. The `txnFuture` contains a field `mockFail` that is very weird. And we will check that field at every `txnFuture.wait()` call.
2. The `session.getTxnFuture` will check whether does the context contains `mockGetTSFail` in normal scenario, it not efficiency.

### What is changed and how it works?

1. Remove `mockFail` from `txnFuture` struct definition.
2. Returns the error if the error is produced by `txnFailFuture` (type assertion is very fast, see: https://godbolt.org/z/CF1Hcw).
3. Use `failpoint` to reduce the cost of checking `ctx.Value("mockGetTsFail")`.

### Check List 

Tests 

 - Unit test
 - Integration test

Release note

 - No need to add to release note.

### CODE REVIEW

**Comment by lonng** [comment]
@tiancaiamao @lysu @jackysp PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
