### PR TITLE
domain: migrate test-infra to testify (part 2)

### LINKED ISSUE #26306: migrate test-infra to testify for `domain` pkg

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

### What problem does this PR solve?

Issue Number: close #26306

split from #26307 , [2/2]

based on #26751 

```release-note
None
```

### CODE REVIEW

**Comment by xhebox** [comment]
I will review it after part1 merged.

**Review by tiancaiamao — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by tisonkun** [comment]
/merge cancel

It seems something wrong happened. Let me dig a abit.

**Comment by tisonkun** [comment]
It seems failpoints conflict with each others. Let me batch domain_test to run in serial.

**Comment by tisonkun** [comment]
/cc @xhebox @tiancaiamao 

May you give another review and move to merge?

**Comment by xhebox** [comment]
LGTM, failpoints and global config are both serial-safe, maybe mention it in the tracking issue.

**Comment by tisonkun** [comment]
@xhebox will update it.

Please help on `/merge` as I `/merge cancel` when debugging...

**Pull request merged**
