### PR TITLE
server: Fix authentication with MySQL 5.1 and older clients

### LINKED ISSUE #29725: tidb returns 'Unknown auth plugin' when some old clients to connect
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a tidb cluster
2. use mysql 5.1 client to connect the tidb
3. the client Connect success to v5.2.2, but can't connect to v5.3.0

related  #27855 #27931

### 2. What did you expect to see? (Required)

```sql
╭─tidb@localhost ~/tiup-cluster-config
╰─$ mysql --version                                                                                                                                                                    1 ↵
mysql  Ver 14.14 Distrib 5.1.73, for pc-linux-gnu (i686) using readline 5.1
╭─tidb@localhost ~/tiup-cluster-config
╰─$ mysql -u root -h 172.16.4.131 -P 4100
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 7
Server version: 5.7.25-TiDB-v5.2.2 TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible

Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```
### 3. What did you see instead (Required)
```sql
╭─tidb@localhost ~/pingcap/tidb ‹master*›
╰─$ mysql --version                                                                                                                                                                    1 ↵
mysql  Ver 14.14 Distrib 5.1.73, for pc-linux-gnu (i686) using readline 5.1
╭─tidb@localhost ~/pingcap/tidb ‹master*›
╰─$ mysql -u root -h 172.16.4.131 -P 4100
ERROR 1105 (HY000): Unknown auth plugin
```
### 4. What is your TiDB version? (Required)
release-5.3(bdc9987370d6d393cb8)

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #29725

Problem Summary:

`handleAuthPlugin` checks for the `ClientPluginAuth` capability but this didn't set the `AuthPlugin` causing `readOptionalSSLRequestAndHandshakeResponse` to return an error.

Note that this allows authentication for users that use `mysql_native_password` to work, but users using `caching_sha2_passwords` won't work.

This does now return a more specific error in case authentication with `caching_sha2_password` is used.
```
[dvaneeden@dve-carbon ~]$ ~/opt/mysql/5.1.73/bin/mysql -h 127.0.0.1 -u sha -P 4000 -psha
ERROR 1105 (HY000): ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by dveeden** [comment]
This will need careful merging with https://github.com/pingcap/tidb/pull/29577

**Comment by bb7133** [comment]
> Note that this allows authentication for users that use mysql_native_password to work, but users using caching_sha2_passwords won't work.

> This does now return a more specific error in case authentication with caching_sha2_password is used.

So your point is, if a user with `caching_sha2_password` authentication is defined, login with old MySQL client(v5.1) will not be allowed, right?

**Comment by bb7133** [comment]
Please add a test case for your change, if it can be a functional test for `handleAuthPlugin()` only, that would be great :)

**Review by djshow832 — COMMENTED** [review]
There are no such test cases in TiDB, which is the reason why there are many fix-on-a-fix problems.
Can you try to add a test case so that future modifications won't break the compatibility?

**Comment by djshow832** [comment]
Also, please add a release note so that users can figure out from the user doc that the bugfix is contained in which versions.

**Comment by djshow832** [comment]
> There are no such test cases in TiDB, which is the reason why there are many fix-on-a-fix problems. Can you try to add a test case so that future modifications won't break the compatibility?

Will any authentication test cases be ported from the MySQL test? @morgo

**Comment by dveeden** [comment]
Closing this as this is now part of #29738

**Pull request closed without merging**
