### PR TITLE
ddl: fix table attributes error

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

This fixes the arguments for this error:
```
sql> ALTER TABLE t attributes = 'merge_option=allow,merge_option=deny';
ERROR: 8237 (HY000): Invalid attributes 'conflicting attributes: 'merge_option=deny' and 'merge_option=allow'': %!s(MISSING)
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by rleungx** [comment]
After this change, it will change to `Invalid attributes '': conflicting attributes: 'merge_option=deny' and 'merge_option=allow'` which is still good enough. BTW, I notice the error for partition attributes also has the problem.

**Comment by dveeden** [comment]
> After this change, it will change to `Invalid attributes '': conflicting attributes: 'merge_option=deny' and 'merge_option=allow'` which is still not good enough. BTW, I notice the error for partition attributes also has the problem. Would you like to fix it in this PR?

In `AlterTablePartitionAttributes()` `ErrInvalidAttributesSpec.GenWithStackByArgs()` is already called with two arguments in both cases.

**Comment by rleungx** [comment]
> > After this change, it will change to `Invalid attributes '': conflicting attributes: 'merge_option=deny' and 'merge_option=allow'` which is still not good enough. BTW, I notice the error for partition attributes also has the problem. Would you like to fix it in this PR?
> 
> In `AlterTablePartitionAttributes()` `ErrInvalidAttributesSpec.GenWithStackByArgs()` is already called with two arguments in both cases.

Yes, but it's not good enough. See
`ERROR 8237 (HY000): Invalid attributes 'partition `p0` attributes='merge_option=allow,merge_option=deny'': conflicting attributes: 'merge_option=deny' and 'merge_option=allow'`

**Comment by dveeden** [comment]
@rleungx Sorry, but I don't see what's the issue with that error. Could you explain it to me? Alternatively you could suggest a solution and/or merge this commit and create a new PR for any additional issues?

**Comment by rleungx** [comment]
> @rleungx Sorry, but I don't see what's the issue with that error. Could you explain it to me? Alternatively you could suggest a solution and/or merge this commit and create a new PR for any additional issues?

The invalid attributes should not contain `partition p0`. A better way is `Invalid attributes: 'merge_option=deny' and 'merge_option=allow' are conflicted`.

**Comment by dveeden** [comment]
Updated:
```
sql> CREATE TABLE t (id INT PRIMARY KEY);
Query OK, 0 rows affected (0.0097 sec)

sql> ALTER TABLE t attributes = 'merge_option=allow,merge_option=deny';
ERROR: 8237 (HY000): Invalid attributes: 'merge_option=deny' and 'merge_option=allow' are conflicted
```

**Comment by morgo** [comment]
@dveeden  Please run `make errdoc`:
```
[2021-12-13T08:35:08.578Z] Files errors.toml and /tmp/errors.toml.before differ

[2021-12-13T08:35:08.578Z] make: *** [errdoc] Error 1

script returned exit code 2
```

Also, it looks like the test failure is related:
```
[2021-12-13T08:35:53.227Z] --- FAIL: TestAddLabels (0.00s)

[2021-12-13T08:35:53.227Z]     --- FAIL: TestAddLabels/conflict_attributes (0.00s)

[2021-12-13T08:35:53.227Z]         attributes_test.go:184: 

[2021-12-13T08:35:53.227Z]             	Error Trace:	attributes_test.go:184

[2021-12-13T08:35:53.227Z]             	Error:      	Received unexpected error:

[2021-12-13T08:35:53.227Z]             	            	'key=value' and 'key=value1' are conflicted

[2021-12-13T08:35:53.227Z]             	Test:       	TestAddLabels/conflict_attributes

[2021-12-13T08:35:53.227Z] FAIL

[2021-12-13T08:35:53.227Z] coverage: 91.1% of statements

[2021-12-13T08:35:53.227Z] FAIL	github.com/pingcap/tidb/ddl/label	0.032s

```

**Review by morgo — APPROVED** [review]

**Review by rleungx — APPROVED** [review]

**Comment by hawkingrei** [comment]
@dveeden Have an error in the test.

```
[2022-01-12T06:14:02.548Z] === FAIL: ddl/label TestAddLabels/conflict_attributes (0.00s)

[2022-01-12T06:14:02.548Z]     attributes_test.go:176: 

[2022-01-12T06:14:02.548Z]         	Error Trace:	attributes_test.go:176

[2022-01-12T06:14:02.548Z]         	Error:      	Received unexpected error:

[2022-01-12T06:14:02.548Z]         	            	'key=value' and 'key=value1' are conflicted

[2022-01-12T06:14:02.548Z]         	Test:       	TestAddLabels/conflict_attributes

[2022-01-12T06:14:02.548Z]     --- FAIL: TestAddLabels/conflict_attributes (0.00s)

[2022-01-12T06:14:02.548Z] 

[2022-01-12T06:14:02.548Z] === FAIL: ddl/label TestAddLabels (0.00s)


```

**Pull request merged**
