### PR TITLE
planner: fix indexJoin(also hash, merge) on prefixed clustered index

### LINKED ISSUE #23073: Unexpected select results when using index join with prefixed clustered index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set @@tidb_enable_clustered_index=1;
drop table if exists t1, t2;
create table t1  (c_str varchar(40), c_decimal decimal(12, 6) , primary key(c_str(8)), key(c_decimal));
create table t2  like t1 ;
insert into t1 values ('serene ramanujan', 6.383), ('frosty hodgkin', 3.504), ('stupefied spence', 5.869);
insert into t2 select * from t1 ;
select /*+ INL_JOIN(t1,t2) */ * from t1 right join t2 on t1.c_str = t2.c_str and t1.c_decimal = t2.c_decimal;
```

### 2. What did you expect to see? (Required)

```
+------------------+-----------+------------------+-----------+
| c_str            | c_decimal | c_str            | c_decimal |
+------------------+-----------+------------------+-----------+
| serene ramanujan | 6.383000  | serene ramanujan | 6.383000  |
| frosty hodgkin   | 3.504000  | frosty hodgkin   | 3.504000  |
| stupefied spence | 5.869000  | stupefied spence | 5.869000  |
+------------------+-----------+------------------+-----------+
```

### 3. What did you see instead (Required)

```
+--------+-----------+------------------+-----------+
| c_str  | c_decimal | c_str            | c_decimal |
+--------+-----------+------------------+-----------+
| <null> | <null>    | frosty hodgkin   | 3.504000  |
| <null> | <null>    | serene ramanujan | 6.383000  |
| <null> | <null>    | stupefied spence | 5.869000  |
+--------+-----------+------------------+-----------+
```

### 4. What is your TiDB version? (Required)

master (602bcd2e40c6c8bcc0eabda38d3097f42b22fbd4)

### PR DESCRIPTION
**Pull request by lysu**
Signed-off-by: lysu <sulifx@gmail.com>

### What problem does this PR solve?

Issue Number: close #23073 

Problem Summary:

{index / index merge  / index hash} join seems miss pass path info to indicate prefix col

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed, How it Works:

pass path if it's common handle

### Related changes

- n/a

### Check List 

Tests 

- Unit test

Side effects

- n/a

### Release note 

- n/a

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/23094)

### CODE REVIEW

**Comment by lysu** [comment]
@winoros @lzmhhh123  PTAL

**Comment by lysu** [comment]
@winoros @lzmhhh123 PTAL

**Review by lzmhhh123 — APPROVED** [review]

**Review by lzmhhh123 — APPROVED** [review]

**Review by coocood — APPROVED** [review]

**Comment by hi-rustin** [comment]
> /merge

If the CI test fails, you just re-trigger the test that failed and the bot will merge the PR for you after the CI passes.

**Pull request merged**
