### PR TITLE
*: support stream agg on TiKV

### PR DESCRIPTION
**Pull request by zimulala**
Relate to pingcap/tikv#2714

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by zimulala** [comment]
Using 3 TiKV, 1 PD, 1 TiDB, the 3 TiKV are on different servers.
The table schema as follows:
```
Create Table: CREATE TABLE `lineitem` (
  `L_ORDERKEY` int(11) NOT NULL,
  `L_PARTKEY` int(11) NOT NULL,
  `L_SUPPKEY` int(11) NOT NULL,
  `L_LINENUMBER` int(11) NOT NULL,
  `L_QUANTITY` decimal(15,2) NOT NULL,
  `L_EXTENDEDPRICE` decimal(15,2) NOT NULL,
  `L_DISCOUNT` decimal(15,2) NOT NULL,
  `L_TAX` decimal(15,2) NOT NULL,
  `L_RETURNFLAG` char(1) NOT NULL,
  `L_LINESTATUS` char(1) NOT NULL,
  `L_SHIPDATE` date NOT NULL,
  `L_COMMITDATE` date NOT NULL,
  `L_RECEIPTDATE` date NOT NULL,
  `L_SHIPINSTRUCT` char(25) NOT NULL,
  `L_SHIPMODE` char(10) NOT NULL,
  `L_COMMENT` varchar(44) NOT NULL,
  PRIMARY KEY (`L_ORDERKEY`,`L_LINENUMBER`),
  CONSTRAINT `LINEITEM_FK1` FOREIGN KEY (`L_ORDERKEY`) REFERENCES `orders` (`O_ORDERKEY`),
  CONSTRAINT `LINEITEM_FK2` FOREIGN KEY (`L_PARTKEY`,`L_SUPPKEY`) REFERENCES `partsupp` (`PS_PARTKEY`,`PS_SUPPKEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
```
|   | rows:6001215 && groups:1.5m && current PR | rows:6001215 && groups:1.5m && before |percentage decrease| rows:59986052 && groups:15m && current PR | rows:59986052 && groups:15m && before|percentage decrease|
|---|---|---|---|---|---|---|
|select count(L_ORDERKEY), sum(L_LINENUMBER) from lineitem group by L_ORDERKEY;| 6.43 sec  | 7.27 sec |11.6%|   31.05s | 69.76s |55.5%|
|                                                                              | 6.53 sec  | 7.36 sec |11.3% || |
|---|---|---|---|---|---|---|
|select count(L_ORDERKEY) from lineitem group by L_ORDERKEY;|4.12 sec| 4.84 sec |14.9%|19.78s |49.03s |59.7%|
|                                                           |4.22 sec| 4.61 sec |8.5% || |
|---|---|---|---|---|---|---|
|select sum(L_ORDERKEY) from lineitem group by L_ORDERKEY;| 5.00 sec |5.51 sec |9.3%|26.76s |52.55s||
|                                                         | 5.15 sec  |5.72 sec| || |
|---|---|---|---|---|---|---|
|select avg(L_LINENUMBER) from lineitem group by L_ORDERKEY;|6.04 sec| 6.21 sec |2.8%|32.26s |61.08s |49.1%|
|                                                           |6.15 sec| 6.39 sec |3.8% | ||
|---|---|---|---|---|---|---|
|select avg(L_ORDERKEY) from lineitem group by L_ORDERKEY;|5.97 sec| 6.03 sec |1.0%|35.20s |60.59s |41.9%|
|                                                         |6.20 sec| 6.30 sec |1.6% | ||
|---|---|---|---|---|---|---|

**Comment by winoros** [comment]
/run-integration-common-test tidb-test=pr/453 tidb-private-test=pr/453

**Comment by zimulala** [comment]
/run-integration-common-test tidb-test=pr/453 tidb-private-test=pr/453

**Comment by zimulala** [comment]
/run-integration-common-test tidb-test=pr/453 tidb-private-test=pr/453

**Comment by zimulala** [comment]
/run-integration-common-test tidb-test=pr/453 tidb-private-test=pr/453 tikv=pr/2762

**Comment by zimulala** [comment]
PTAL @winoros

**Pull request merged**
