### PR TITLE
util/ranger: migrate test-infra to testify

### LINKED ISSUE #26411: migrate test-infra to testify for `util/ranger` pkg

### PR DESCRIPTION
**Pull request by feitian124**
### What problem does this PR solve?

Issue Number: close #26411 

What's Changed:
`ranger_test.go` requires some structs and methods in `util/testutil`, i add them to `testkit` as needed ( in second commit).
the other changes are mainly simpe replacement.
 
### Release note
```release-note
None
```

### CODE REVIEW

**Comment by feitian124** [comment]
> /run-all-tests

```shell
[2021-08-07T15:53:37.315Z] + mysql -h 127.0.0.1 -P 4000 -u root -e 'select tidb_version()'

[2021-08-07T15:53:37.315Z] ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
```

not sure what's wrong, so retry once

**Comment by feitian124** [comment]
hi @tisonkun , i need your help.
the `check_dev_2` alway report error but give little reason
```shell

[2021-08-08T00:35:56.232Z] coverage: 93.3% of statements

[2021-08-08T00:35:56.232Z] ok  	github.com/pingcap/tidb/util/tracing	0.006s	coverage: 93.3% of statements

[2021-08-08T00:35:56.232Z] ?   	github.com/pingcap/tidb/util/versioninfo	[no test files]

[2021-08-08T00:35:56.232Z] === RUN   TestVitessHash

[2021-08-08T00:35:56.232Z] === PAUSE TestVitessHash

[2021-08-08T00:35:56.232Z] === CONT  TestVitessHash

[2021-08-08T00:35:56.232Z] --- PASS: TestVitessHash (0.00s)

[2021-08-08T00:35:56.232Z] PASS

[2021-08-08T00:35:56.232Z] coverage: 88.9% of statements

[2021-08-08T00:35:56.232Z] ok  	github.com/pingcap/tidb/util/vitess	0.008s	coverage: 88.9% of statements

[2021-08-08T00:35:56.232Z] FAIL

[2021-08-08T00:35:56.232Z] + cat test.log

[2021-08-08T00:35:56.232Z] + grep -Ev '^\[[[:digit:]]{4}(/[[:digit:]]{2}){2}'

[2021-08-08T00:35:56.232Z] + grep -A 30 '\-------'

```

**Comment by tisonkun** [comment]
```
[2021-08-08T00:35:47.652Z] /tmp/go-build3575107562/b959/executor.test flag redefined: record
[2021-08-08T00:35:47.652Z] panic: /tmp/go-build3575107562/b959/executor.test flag redefined: record
[2021-08-08T00:35:47.652Z] 
[2021-08-08T00:35:47.652Z] goroutine 1 [running]:
[2021-08-08T00:35:47.652Z] flag.(*FlagSet).Var(0xc00004e240, 0x438f1b0, 0x619fdde, 0x3d5df6c, 0x6, 0x3d990f6, 0x17)
[2021-08-08T00:35:47.652Z] 	/usr/local/go/src/flag/flag.go:871 +0x485
[2021-08-08T00:35:47.652Z] flag.BoolVar(...)
[2021-08-08T00:35:47.652Z] 	/usr/local/go/src/flag/flag.go:636
[2021-08-08T00:35:47.652Z] github.com/pingcap/tidb/testkit.init.0()
[2021-08-08T00:35:47.652Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/testkit/testdata.go:40 +0x76
[2021-08-08T00:35:47.652Z] FAIL	github.com/pingcap/tidb/executor	0.090s
```

**Comment by tisonkun** [comment]
You can download the log and grep "FAIL"

**Comment by feitian124** [comment]
> You can download the log and grep "FAIL"

thanks, find it.

- the log is for `check_dev_2` only or for all tests? 
the `flag redefined: record` error happened before in `check_dev` log in previous run,
but some how disappeard after i add license and `// +build !codes` to the file.


- i thought `check_dev_2` and `check_dev` must check different things, what's their duty? i can find none of them in makefile

**Comment by tisonkun** [comment]
> i thought check_dev_2 and check_dev must check different things, what's their duty? i can find none of them in makefile

May @zhouqiang-cl @bb7133 have ideas on this topic, we may explore more Jenkins configs in jenkinsfile instead of restricted server configs.

**Comment by tisonkun** [comment]
> can i just rename the flag? i did not fully understand how the flag is used now..

@feitian124 The workaround could be, you move "record" logic from testutil to new testkit, export a temporary `Record()` method for testutil for temporarily background compatible. After we migrate all tests based on former testdata, we can remove testutil and the `Record` method.

**Review by tisonkun — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
/cc @francis0407 @winoros 

PTAL. Thanks!

**Comment by feitian124** [comment]
/cc @xhebox @xiongjiwei @mmyj
could you also take a look at this pr? thanks

**Comment by xhebox** [comment]
@feitian124 I can, but I can not approve it. I can not make review progress. :(

**Comment by feitian124** [comment]
> @feitian124 I can, but I can not approve it. I can not make review progress. :(

ok, thanks. who can do what is still learning... i believe you can soon

**Comment by xhebox** [comment]
> 
> 
> > @feitian124 I can, but I can not approve it. I can not make review progress. :(
> 
> ok, thanks. who can do what is still learning... i believe you can soon

You could check https://github.com/pingcap/community/tree/master/special-interest-groups. Also tisonkun had a proposal https://github.com/pingcap/community/issues/516 recently.

**Review by rebelice — APPROVED** [review]

**Comment by tisonkun** [comment]
@rebelice @qw4990 could you help on merging this PR?

**Comment by tisonkun** [comment]
This patch seems wrong because we don't flush test data on the last. Will submit a follow up.

**Pull request merged**
