### PR TITLE
*: Remove tidb_enable_default_list_partition variable

### LINKED ISSUE #45700: remove tidb_enable_default_list_partition
## Enhancement
in https://github.com/pingcap/tidb/pull/41537 I introduced a new variable `tidb_enable_default_list_partition` which is not really needed, since:
- It does not restrict anyone from creating tables with default list partition, they can just use this setting.
- Such tables would fail to replicate to MySQL / older versions of TiDB regardless of setting.

So we should remove it, since it does not serve any real pupose.

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #45700

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Comment by hawkingrei** [comment]
@bb7133 @XuHuaiyu @qw4990 PTAL

/hold

Our CI has a bug that al the PR will not merge because this pr is lack of the configure reviewer's approval.

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
