### PR TITLE
server: Port missing in processlist

### LINKED ISSUE #30182: Regression, no longer host:port reported in show processlist
## Bug Report

Please answer these questions before submitting your issue. Thanks!

In https://github.com/pingcap/tidb/issues/10903 the `host:port` was added in `show processlist`, but there has been a regression, resulting it it does no longer show up.

### 1. Minimal reproduce step (Required)

See https://github.com/pingcap/tidb/issues/10903

### 4. What is your TiDB version? (Required)

Master branch 7a8c7f89cebe0e5596415a6106b1345cec9cfa27

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #30182

Problem Summary:
Regression, a second call of cc.PeerHost() was probably added, which made the port to be set to "".

### What is changed and how it works?
Fixed the return of the already set value.

### Check List

Tests 

- [X] Unit test
- [X] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fixed regression where the port part of the host in processlist disappeared
```

### CODE REVIEW

**Review by dveeden — APPROVED** [review]
The port number matches the port number reported by `ss`:
```
sql> SHOW PROCESSLIST;
+----+------+-----------------+------+---------+------+------------+------------------+
| Id | User | Host            | db   | Command | Time | State      | Info             |
+----+------+-----------------+------+---------+------+------------+------------------+
|  3 | root | 127.0.0.1:51930 | test | Query   |    0 | autocommit | SHOW PROCESSLIST |
+----+------+-----------------+------+---------+------+------------+------------------+
1 row in set (0.0009 sec)

sql> \! ss -n dport 4000
Netid       State       Recv-Q       Send-Q             Local Address:Port              Peer Address:Port      Process      
tcp         ESTAB       0            0                      127.0.0.1:51930                127.0.0.1:4000                   

```

**Review by ngaut — APPROVED** [review]
LGTM

**Pull request merged**
