### PR TITLE
[DNM] util/types: fix decimal PrecisionAndFrac function

### PR DESCRIPTION
**Pull request by tiancaiamao**
I'm not sure is that ok?
@coocood

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Try to fix:

```
mysql> create table t (c decimal(5,5));
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values (0);
ERROR 1690 (22003): DECIMAL value is out of range in '(5, 5)'
```

**Comment by XuHuaiyu** [comment]
May be closed.
Fixed in #3358

**Comment by XuHuaiyu** [comment]
@tiancaiamao

**Comment by tiancaiamao** [comment]
Good job! @XuHuaiyu

**Pull request closed without merging**
