### PR TITLE
executor: skip all test cases related to TiFlash+Partition since they are too slow (#25866)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25866 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25870
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25870:release-5.1-12cc1d038218
```

---

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary: executor: skip all test cases related to TiFlash+Partition since they are too slow

### What is changed and how it works?

executor: skip all test cases related to TiFlash+Partition since they are too slow

I will port these test cases into the `tidb-test` repo later.

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]
/LGTM

**Pull request merged**
