### PR TITLE
*: misc cleanups to variable package

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Problem Summary:

This is a refactoring PR. It fixes a few small issues, and is functionality neutral.

### What is changed and how it works?

What's Changed:

- The function `GetSessionSystemVar` is renamed to `GetSessionOrGlobalSystemVar`. If you look at the source of it, it loads both session and global scoped variables, which makes the name very confusing. To add to the confusion, the function that only loads session scope is called `GetSystemVar`! This has confused me before. I have also commented about how there is a bug in the behavior, but it can't be fixed right now due to a performance regression.
- The function `SetLocalSystemVar` is converted to `SetSession` functions on each of the variables.
- The function `ValidateGetSystemVar` is inlined, since it was only used in one place. The replacement code is easier to read, because it makes use of `HasXXXScope()` functions.
- The code `TxIsolationNames` is unused, since a list of names is already specified in the ENUM definition for the variables.
- The sysvar name `serverReadOnly` was renamed to `ReadOnly` for consistency. The comment about it not being used is redundant now, because it appears in `noop.go` and has validation to prevent unsafe usage.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test (covered by existing tests)

Side effects

- None

### Release note 

- No release note

### CODE REVIEW

**Review by xiongjiwei — APPROVED** [review]
/lgtm

**Comment by morgo** [comment]
The errors are due to the function rename, and new code introduced in the merge. I'll fix it tomorrow.

**Pull request merged**
