### PR TITLE
lightning: add back table empty check and add a switch config (#30887)

### LINKED ISSUE #27919: lightning: lightning doesn't check whether target table is empty  (behavior changed compared to 5.0.x)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Lightning 5.0.1 added a check to ensure target table is empty before import for DBaaS.
Lightning 5.1.0 removed this check due to new feature parallel import / incremental import, this changes previous product behaviors.

Steps:
1. Import a table to TiDB with lightning
2. Import the table again to TiDB again with lightning

### 2. What did you expect to see? (Required)
Lightning behavior should be consistent for 5.0.1 and 5.1.0+.

### 3. What did you see instead (Required)
For lightning 5.1.0+, lightning doesn't check target table empty or not before the import, this may result in:
- Duplicate rows inserted into the table, if the import data doesn't have PK/UK
- Import failed with checksum mismatched error, if import data has PK/UK

### 4. What is your TiDB version? (Required)
5.2.0

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #30887 to release-5.2
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/33881
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/33881:release-5.2-393415782452
```

---

### What problem does this PR solve?

Issue Number: close #27919

Problem Summary:

### What is changed and how it works?
- Add a new config `tikv-importer.incremental-import` to control whether allow lightning to import to table that already contains data
- When tikv-importer.incremental-import = false, tidb-lightning will check target tables' vacancy. If the tables already contains data, lightning will directly report an error and exit. In this mode, lightning will also avoid create and write data into  `lightning_meta` in target tidb.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility
  - Add a new config to control the `table empty check`, so this is not compatible with v5.2 and v5.3.

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Add a new config to control whether support incremental import.
```

### CODE REVIEW

**Comment by gozssky** [comment]
lint error
```
[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check/detail/tidb_ghpr_check/58657/pipeline#step-113-log-154)[2022-04-12T08:51:46.852Z] br/pkg/lightning/restore/check_info.go

[2022-04-12T08:51:46.852Z] make: *** [fmt] Error 1
```

**Comment by glorv** [comment]
@gozssky PTAL again

**Comment by gozssky** [comment]
Integration test fail. I'm not sure if it is caused by this PR.
https://ci.pingcap.net/job/br_ghpr_unit_and_integration_test/11159/display/redirect

**Comment by VelocityLight** [comment]
This pull request is closed because it's related version has closed automatic cherry-picking.
If it's still needed, you can reopen it or just regenerate it using bot,
see:
- https://prow.tidb.io/command-help#cherrypick
- https://book.prow.tidb.net/#/plugins/cherrypicker

You can find more details at:
- https://internals.tidb.io/t/topic/785

**Pull request closed without merging**
