### PR TITLE
expression: support GBK for built-in function concat()

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/28356

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by xiongjiwei** [comment]
ref https://github.com/pingcap/tidb/pull/29029

**Comment by zimulala** [comment]
@tangenta Any update

**Comment by tangenta** [comment]
This feature will be implemented by https://github.com/pingcap/tidb/pull/29905.

**Comment by xiongjiwei** [comment]
the issue will be fixed by https://github.com/pingcap/tidb/pull/29905

**Pull request closed without merging**
