### PR TITLE
plugin: fix plugin build and load with go 1.13

### LINKED ISSUE #12927: plugin can't load with `-trimpath` TiDB-server in go1.13
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Thx wph95's report

build load conn_example plugin in TiDB repo using go1.13, will meet

```
'2019/10/24 21:33:56.735 terror.go:342: [fatal] plugin.Open(~/Work/lab/tidb/plugin/out/conn_ip_example-1"): plugin was built with a different version of package internal/cpu'
```

this is introduced by https://github.com/pingcap/tidb/pull/12639 that add `-trimpath` in make file.

2. What did you expect to see?

load success

3. What did you see instead?

load failure 

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

4.0 alpha, master

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

fixes #12927

due to Go1.13's issues https://github.com/golang/go/issues/34143 and https://github.com/golang/go/issues/31278#issuecomment-541106229

we need remove `-trimpath` in tidb makefile and `-pluginpath` in plugin build tool to let plugin can work with go1.13

### What is changed and how it works?

- remove `-trimpath` from makefile
- disable `pluginpath` in pluginpkg

### Check List 

Tests 

 - Manual test 

build and load plugin

Code changes

 - change build script and build tool

Side effects

 - n/a

Related changes

 - n/a

Release note

 - fix plugin build and load with go 1.13

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/13455)

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by YIDWang** [comment]
去掉 pluginpath，是否还是支持多版本同时加载的呢？

**Pull request merged**
