### PR TITLE
planner: fine grained collation control for mpp plan

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

Currently, TiDB does not generate mpp plan if new collation is on. This means a TiDB cluster with new collation can not use mpp at all, which is un-acceptable, we need find grain collation for mpp plan, for example, when new collation is on, `select * from a join b on a.id = b.id` should be able to generate mpp plan if `id` is `integer type`.
### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

Now, only abandon mpp plan if need shuffle data based on `String` column.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- fine grained collation control for mpp plan

### CODE REVIEW

**Comment by windtalker** [comment]
/needs-cherry-pick-5.0

**Comment by windtalker** [comment]
lable needs-cherry-pick-5.0

**Review by hanfei1991 — APPROVED** [review]

**Pull request merged**
