### PR TITLE
types: migrate test-infra to testify for `format_test.go`

### LINKED ISSUE #28005: migrate test-infra to testify for `format_test.go`

### PR DESCRIPTION
**Pull request by dswij**
### What problem does this PR solve?

close #28005 

Problem Summary: N/A

### What is changed and how it works?

What's Changed: Test in `format_test.go` now uses `testify` instead

```release-note
None
```

### CODE REVIEW

**Review by djshow832 — APPROVED** [review]

**Review by mmyj — APPROVED** [review]
lgtm

**Comment by karuppiah7890** [comment]
`testTimeSuite` in https://github.com/pingcap/tidb/blob/a84ceb801fe82e931cc4a454c5081c67ba9d064c/types/time_test.go#L36 is used in https://github.com/pingcap/tidb/blob/a84ceb801fe82e931cc4a454c5081c67ba9d064c/types/format_test.go which this PR removes. I'll wait for this PR to be merged to merge the PR for the issue https://github.com/pingcap/tidb/issues/28010

**Pull request merged**
