### PR TITLE
Revert "*: upgrade go version to 1.16 (#22895)"

### PR DESCRIPTION
**Pull request by disksing**
This reverts commit ae46cda24e7fee5b173fda51fee24444e9bac458.

### What problem does this PR solve?
Upgrading Go version is risky.

### What is changed and how it works?
What's Changed:
- revert to go1.13

### Related changes
#22895 

### Check List 

Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Comment by morgo** [comment]
I think it's important to note that 1.13 is no longer receiving security fixes! See: https://golang.org/doc/devel/release.html#policy

Go's support lifecycle is even shorter than I expected. So it's totally possible that in order to support TiDB for 3 years, we will need to maintain our own golang builds :(

**Comment by disksing** [comment]
> I think it's important to note that 1.13 is no longer receiving security fixes! See: https://golang.org/doc/devel/release.html#policy
> 
> Go's support lifecycle is even shorter than I expected. So it's totally possible that in order to support TiDB for 3 years, we will need to maintain our own golang builds :(

That's really a fresh perspective! But I don't think they want to use go1.13 forever. As I was told, we need to come up with a standard procedure and a well-established checklist. Then we could be more confident to upgrade.

**Review by zz-jason — COMMENTED** [review]
/lgtm

**Review by zz-jason — COMMENTED** [review]
/LGTM

**Review by zz-jason — APPROVED** [review]

**Review by AndreMouche — APPROVED** [review]
/LGTM

**Pull request merged**
