### PR TITLE
meta/autoid: migrate test-infra to testify

### LINKED ISSUE #26741: migrate test-infra to testify for `meta/autoid` pkg

### PR DESCRIPTION
**Pull request by unconsolable**
### What problem does this PR solve?

Issue Number: close #26741 

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by unconsolable** [comment]
/cc @tisonkun 
I have broken these changes into multiple commits, PTAL. Thanks.

**Review by tisonkun — COMMENTED** [review]
Thanks for your effort @unconsolable ! The last question I'd like to ask is whether we can run these tests as parallel as possible? It seems now all in serial. We run in parallel for both better usage of CPU and reduce CI time, as well as expose bugs where we think it can be run in parallel but fail.

**Comment by unconsolable** [comment]
> The last question I'd like to ask is whether we can run these tests as parallel as possible? 

`failpoint` and global config are both serial-safe, TestConcurrentXXX may not be feasible to parallel. So maybe few tests can be parallel, I will try to add some.

**Review by tisonkun — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]

**Review by djshow832 — APPROVED** [review]

**Pull request merged**
