### PR TITLE
executor, variable: move hidden variables to struct

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Problem Summary:

This moves the hidden attribute of a feature switch to the sysvar struct. This makes it possible for plugins to also create hidden variables, which may be a nice property in the future.

I also think it is useful for noop sysvars; since for many of them if they are hidden they will pass compatibility requirements, but not confuse users. I saw a user on TiDB slack today asking about setting `innodb_log_file_size`, which is a problem of our creation.

### What is changed and how it works?

What's Changed:

Internal refactor, function neutral.

### Related changes

- There is a similar PR to move deprecation and synonyms into the struct in https://github.com/pingcap/tidb/pull/24280

### Check List 

Tests 

- Unit test (existing)

Side effects

- None

### Release note 

- No release note

### CODE REVIEW

**Review by ichn-hu — APPROVED** [review]
Nice!

**Review by xhebox — APPROVED** [review]

**Comment by morgo** [comment]
@xhebox I've added sig-sql-infra if you want to try approving again.

**Review by xhebox — APPROVED** [review]
OK. IIRC, the filter is introduced by our SIG anyway...

**Pull request merged**
