### PR TITLE
br: directly use the rewrite rule from schemaReplaces

### LINKED ISSUE #43184: br: failed to constructs the rewrite rules in the snapshot + log restore
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Start a new cluster (upstream)
2. Start a log backup task
3. Run this sqls:
```sql
create table test.A (id int, a char(20));
create table test.B (id char(20), a int);
insert into test.A (id, a) values (1, "aaa"), (2, "bbb");
insert into test.B (id, a) values ("ccc", 3), ("ddd", 4);
```
4. Do snapshot backup
5. Run this sqls:
```sql
rename table test.A to test.C;
rename table test.B to test.A;
rename table test.C to test.B;
insert into test.A (id, a) values ("yyy", 27), ("zzz", 26);
insert into test.B (id, a) values (5, "eee"), (6, "fff");
```
6. wait until the checkpoint of log backup advance
7. restore snapshot + log to another new cluster(downstream).

### 2. What did you expect to see? (Required)
success to restore
### 3. What did you see instead (Required)
Sometimes the domain has not update in time, so it would success to restore.
```sql
mysql> select * from test.B;
ERROR 1105 (HY000): invalid data type: Failed to decode row v2 data as i64
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #43184 

Problem Summary:
After finish restore the meta-kvs, we cannot use the tables' name from backupmeta to match the tables' name from downstream cluster's domain. (rename ddl)
### What is changed and how it works?
We already has an entire id-maps in the `schemaReplaces`, so just use it to construct the rewriterules.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by BornChanger — COMMENTED** [review]
Is it possible to make a case for the failure scenario?

**Comment by Leavrth** [comment]
> Is it possible to make a case for the failure scenario?

The reproduce step is in the [issue](#43184). But the error doesn't occur every time.

**Comment by BornChanger** [comment]
> > Is it possible to make a case for the failure scenario?
> 
> The reproduce step is in the [issue](#43184). But the error doesn't occur every time.

Per offline discussion, I approve the change and you will add a e2e test for the scenario.

**Review by BornChanger — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]

**Pull request merged**
