### PR TITLE
config, server: change the default value of max-server-connections

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Problem Summary:
`max-server-connections` is added in #14409, and some users may think this value is too small. 

### What is changed and how it works?

What's Changed:
 Change the default value of max-server-connections to 0, and if the value is 0, the number of connections is unlimited.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`: pingcap/docs-cn#2574
- PR to update `pingcap/tidb-ansible`:

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @jackysp

**Comment by coocood** [comment]
LGTM

**Pull request merged**
