### PR TITLE
store/tikv: not setting special ts when resolving async locks

### LINKED ISSUE #24384: Primary lock fallen back from async commit cannot be resolved
### 1. Minimal reproduce step (Required)

It is hard to reproduce the issue deterministically. So the reproduce steps contain technical details.

Commit an async-commit transaction with multiple keys. Prewriting the primary lock triggers a fallback (probably because TiKV executes the command too slow), while the secondary lock is prewritten successfully with the async-commit protocol. Then, the TiDB instance crashes without committing any key.

Now, if we meet the secondary lock of the above transaction, TiDB cannot resolve that lock so the statement will be blocked.

https://github.com/pingcap/tidb/blob/v5.0.1/store/tikv/lock_resolver.go#L489

Here we set `current_ts` to zero if the lock we first meet is an async-commit lock. Therefore, the primary lock is never rolled back in `check_txn_status`. And because the lock returned by `check_txn_status` is not an async-commit lock, the following logic does not treat this case well, the lock remains unresolved forever.

### 2. What did you expect to see? (Required)

The locks of the transaction can be successfully resolved, so the locks will not block other readers forever.

### 3. What did you see instead (Required)

The secondary lock can block other readers forever.

### 4. What is your TiDB version? (Required)

5.0.0~5.0.1

### PR DESCRIPTION
**Pull request by sticnarf**
### What problem does this PR solve?

Issue Number: close #24384

### What is changed and how it works?

TiKV always returns the lock information if it is an async-commit lock, so we don't need to set these special ts.

And after setting these timestamps, `check_txn_status` cannot roll back expired locks according to `current_ts`, which leads to issue #24384.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- Fix the bug that primary lock fallen back from async commit cannot be resolved.

### CODE REVIEW

**Review by cfzjywxk — COMMENTED** [review]
/lgtm

**Review by youjiali1995 — APPROVED** [review]

**Comment by youjiali1995** [comment]
```
[2021-04-29T18:06:15.864Z] --- FAIL: TestInfo (0.33s)
[2021-04-29T18:06:15.864Z]     domain_test.go:211: etcdserver: requested lease not found
[2021-04-29T18:06:15.864Z] FAIL
[2021-04-29T18:06:15.864Z] FAIL	github.com/pingcap/tidb/domain	1.137s
[2021-04-29T18:06:24.022Z] === RUN   TestExplainAnalyzeInvokeNextAndClose
[2021-04-29T18:06:24.022Z] --- PASS: TestExplainAnalyzeInvokeNextAndClose (0.00s)
```

**Pull request merged**
