### PR TITLE
ddl: forbidden changing decimal to int (#19645)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19645 to release-4.0

---

Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close ##17812 

Problem Summary:
Missing the check.

### What is changed and how it works?

Check type.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- forbidden changing decimal to int

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
@wjhuang2016 please fix CI.

**Comment by wjhuang2016** [comment]
@zimulala @bb7133 @xhebox PTAL

**Comment by xhebox** [comment]
LGTM

**Review by zimulala — COMMENTED** [review]
LGTM

**Review by zz-jason — APPROVED** [review]
LGTM

**Pull request merged**
