### PR TITLE
types: handle truncate error in `BinaryLiteral.ToInt`

### PR DESCRIPTION
**Pull request by coocood**
Truncate error make be treated as warning, we should handle it in `BinaryLiteral.ToInt`.

And compare BinaryLiteral directly instead of converting to uint64 because that the compare function doesn't have statement context.

### CODE REVIEW

**Comment by coocood** [comment]
@tiancaiamao @winkyao PTAL

**Comment by zhexuany** [comment]
@coocood Maybe we could upgrade `mysql` driver in our vendor. In its master branch, they are already removed `MySQLWarning` from the codebase.

**Comment by tiancaiamao** [comment]
LGTM

**Comment by coocood** [comment]
@XuHuaiyu PTAL

**Pull request merged**
