### PR TITLE
statistics: faster gzip

### LINKED ISSUE #47104: faster JSONTableToBlocks
## Enhancement

JSONTableToBlocks is slow because of gzip. we can use klauspost/compress/gzip to speed up it.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #47104

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)

in the same cluster:

before:

image

after:

image

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
Can you make a small benchmark test for the change?

**Review by qw4990 — APPROVED** [review]

**Comment by hawkingrei** [comment]
> Can you make a small benchmark test for the change?

I have added it in the PR description.

**Pull request merged**
