### PR TITLE
doamin: fix GetSnapshotInfoSchema using current TS

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve? 
If the snapshotTS's schema version and `do.infoHandle.Get().SchemaMetaVersion()` is equal in GetSnapshotInfoSchema, we will get the empty infoschema.

### What is changed and how it works?
I set `usedSchemaVersion` to `initialVersion`, then the full load is needed.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @tiancaiamao @jackysp

**Comment by tiancaiamao** [comment]
LGTM

**Comment by zimulala** [comment]
PTAL @XuHuaiyu

**Pull request merged**
