### PR TITLE
*: make Go 1.7 compatible

### PR DESCRIPTION
**Pull request by coocood**

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by coocood** [comment]
/run-all-tests tidb-test=release-1.0 tikv=release-1.0 tidb-private-test=release-1.0

**Comment by coocood** [comment]
/integration-compatibility-test tidb-test=release-1.0 tikv=release-1.0 tidb-private-test=release-1.0

**Comment by coocood** [comment]
/run-integration-compatibility-test tidb-test=release-1.0 tikv=release-1.0 tidb-private-test=release-1.0

**Comment by winkyao** [comment]
/run-integration-compatibility-test tidb-test=release-1.0 tikv=release-1.0 tidb-private-test=release-1.0

**Pull request merged**
