### PR TITLE
config: disable prepare plan cache by default

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23239

Problem Summary:

Disable prepare plan cache by default.

### What is changed and how it works?

What's Changed:

Change default config for prepare plan cache to false.

### Related changes

N/A

### Check List 

Tests 

- Unit test: current tests should cover this change

Side effects

N/A

### Release note 

- Disable prepare plan cache by default

### CODE REVIEW

**Review by Reminiscent — APPROVED** [review]
/LGTM

**Comment by morgo** [comment]
The docs PR for enabling plan cache was: https://github.com/pingcap/docs/pull/4036
A corresponding PR will be required to revert it too.

**Review by zz-jason — APPROVED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
