### PR TITLE
kv/kv.go:remove StagingHandle from package tikv

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: AndreMouche

### What problem does this PR solve?
This PR removes `kv.StagingHandle` from tikv package.
Part of https://github.com/pingcap/tidb/issues/22513

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]
lgtm

**Comment by hi-rustin** [comment]
@ti-chi-bot help me

**Comment by hi-rustin** [comment]
@ti-chi-bot help me

**Pull request merged**
