### PR TITLE
tidb: fix some case TiDB does not graceful shutdown expectly.

### PR DESCRIPTION
**Pull request by winkyao**
@tiancaiamao @shenli PTAL

### CODE REVIEW

**Comment by shenli** [comment]
Could you add some description?

**Comment by winkyao** [comment]
global variable `graceful` is used to indicate whether we should do graceful shutdown in the `cleanup` function(which call by main.), if we set `graceful` after we call `svr.Close()` in 
 https://github.com/pingcap/tidb/pull/5518/files#diff-af2c9279ed41f7023f9b6b73cba2d18fL410, the cleanup maybe don't know we ask it to shutdown gracefully. @shenli

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
This is not true. If you read `srv.Close()` carefully, you'll find that this function just close the listening port., clean up is not done there. @winkyao

**Comment by winkyao** [comment]
@tiancaiamao clean up is called caused by listening port closed, so in main func , the srv run will exit and cleanup will run.

**Comment by winkyao** [comment]
@tiancaiamao you never know who will run first in multi threads situation.

**Comment by tiancaiamao** [comment]
I see.
LGTM

**Pull request merged**
