### PR TITLE
lightning: replace router with regexpr router

### LINKED ISSUE #32970: Regexpr compatible router in Lightning
## Feature Request

**Is your feature request related to a problem? Please describe:**

ref: https://github.com/pingcap/tiflow/issues/4701
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by buchuitoudegou**
### What problem does this PR solve?

Issue Number: close #32970
ref: https://github.com/pingcap/tiflow/issues/4701

Problem Summary:

### Check List

Tests 

- [x] Unit test

Side effects

Documentation

### Release note

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]
LGTM

**Comment by fengou1** [comment]
/action/run-br-cross-platform-build

**Pull request merged**
