### PR TITLE
executor: deep copy json into partial result (#9833)

### PR DESCRIPTION
**Pull request by zz-jason**
cherry pick #9833 to release-2.1

### CODE REVIEW

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-integration-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
