### PR TITLE
(cherry pick) ddl: fix a panic when add column with insert an index column (#5877)

### PR DESCRIPTION
**Pull request by jackysp**
Cherry pick to release 1.0. PTAL @coocood @zimulala @winkyao @GregoryIan

### CODE REVIEW

**Comment by jackysp** [comment]
/run-all-tests tikv=release-1.0 tidb-test=release-1.0 tidb-private-test=release-1.0

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
We encounter the same errors in the internal test. So we should solve them before merging this PR.

**Comment by shenli** [comment]
Should we close this PR and open a new one? @jackysp

**Comment by jackysp** [comment]
Ok,  we could close it. I'll cherry pick the commits of adding and dropping columns together in one PR. @shenli

**Pull request closed without merging**
