### PR TITLE
executor: fix incorrect `ORDINAL_POSITION` for `INFORMAITON_SCHEMA`.`COLUMNS` table

### LINKED ISSUE #31200: In information schema column table ORDINAL_POSITION is different
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t1 (col1 INT, INDEX ((col1 + col1)));

SELECT COLUMN_NAME, ORDINAL_POSITION FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = "t1";

ALTER TABLE t1 ADD COLUMN col2 INT;

SELECT COLUMN_NAME, ORDINAL_POSITION FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = "t1";

```
### 2. What did you expect to see? (Required)
```sql
mysql> CREATE TABLE t1 (col1 INT, INDEX ((col1 + col1)));
Query OK, 0 rows affected (0.01 sec)

mysql> 
mysql> SELECT COLUMN_NAME, ORDINAL_POSITION FROM INFORMATION_SCHEMA.COLUMNS
    -> WHERE TABLE_NAME = "t1";
+-------------+------------------+
| COLUMN_NAME | ORDINAL_POSITION |
+-------------+------------------+
| col1        |                1 |
+-------------+------------------+
1 row in set (0.01 sec)

mysql> 
mysql> ALTER TABLE t1 ADD COLUMN col2 INT;
Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> 
mysql> SELECT COLUMN_NAME, ORDINAL_POSITION FROM INFORMATION_SCHEMA.COLUMNS
    -> WHERE TABLE_NAME = "t1";
+-------------+------------------+
| COLUMN_NAME | ORDINAL_POSITION |
+-------------+------------------+
| col1        |                1 |
| col2        |                2 |
+-------------+------------------+
2 rows in set (0.00 sec)
```
### 3. What did you see instead (Required)
```sql

mysql> CREATE TABLE t1 (col1 INT, INDEX ((col1 + col1)));
Query OK, 0 rows affected (0.01 sec)

mysql> 
mysql> SELECT COLUMN_NAME, ORDINAL_POSITION FROM INFORMATION_SCHEMA.COLUMNS
    ->   WHERE TABLE_NAME = "t1";
+-------------+------------------+
| COLUMN_NAME | ORDINAL_POSITION |
+-------------+------------------+
| col1        |                1 |
+-------------+------------------+
1 row in set (0.02 sec)

mysql> 
mysql> ALTER TABLE t1 ADD COLUMN col2 INT;
Query OK, 0 rows affected (0.01 sec)

mysql> 
mysql> SELECT COLUMN_NAME, ORDINAL_POSITION FROM INFORMATION_SCHEMA.COLUMNS
    ->   WHERE TABLE_NAME = "t1";
+-------------+------------------+
| COLUMN_NAME | ORDINAL_POSITION |
+-------------+------------------+
| col1        |                1 |
| col2        |                3 |
+-------------+------------------+
2 rows in set (0.02 sec)
```
### 4. What is your TiDB version? (Required)

```sql
| Release Version: v5.4.0-alpha-184-g51f53f337-dirty
Edition: Community
Git Commit Hash: 51f53f3376bd548b302f654d6c11096f89119145
Git Branch: master
UTC Build Time: 2021-11-23 02:51:51
GoVersion: go1.16.9
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve?

Issue Number: close #31200

### What is changed and how it works?

The root cause of #31200 is that when we calculate `ORDINAL_POSITION` for `COLUMNS`, the internally hidden columns used by 'expression index' is counted and the result will be wrong.

After this PR, hidden columns will not be counted.

### Check List

Tests 

- [x] Integration test: the test case in #31200 has been added by the internal test suites(https://github.com/pingcap/tidb-test/pull/1254): I will update the existing case and don't want to make a duplicate test in this repo.

Side effects

- [x] Breaking backward compatibility

Documentation

- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that when 'expression index' is defined, the value of `ORDINAL_POSITION` column of `INFORMAITON_SCHEMA`.`COLUMNS` table might be incorrect.
```

### CODE REVIEW

**Comment by bb7133** [comment]
PTAL @wjhuang2016 @xiongjiwei

**Review by xiongjiwei — APPROVED** [review]

**Review by CbcWestwolf — APPROVED** [review]

**Review by wjhuang2016 — COMMENTED** [review]
How about KEY_COLUMN_USAGE?

**Comment by bb7133** [comment]
> How about KEY_COLUMN_USAGE?

@wjhuang2016 It is irrelevant(https://dev.mysql.com/doc/refman/8.0/en/information-schema-key-column-usage-table.html):

> The column's position within the constraint, not the column's position within the table.
> This table provides no information about functional key parts because they are expressions and the table provides information only about columns.

The semantic of `ORDINAL_POSTITION` for `KEY_COLUMN_USAGE` is different with the one in `COLUMNS`.

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
