### PR TITLE
support `insert t () values ()`

### PR DESCRIPTION
**Pull request by siddontang**

### CODE REVIEW

**Comment by ngaut** [comment]
LGTM

**Comment by coocood** [comment]
Can we define a `ColumnNameListOpt` and use it instead?

**Comment by siddontang** [comment]
maybe not, column name is only identifier, but here can contain expression.

**Comment by coocood** [comment]
I mean
 ```
InsertRest:
 	'(' ColumnNameListOpt ')' ValueSym ExpressionListList	
```

**Comment by coocood** [comment]
`ColumnNameListOpt` is already defiend.

**Comment by siddontang** [comment]
PTAL @coocood

**Comment by coocood** [comment]
LGTM

**Pull request merged**
