### PR TITLE
executor: only cast values for modified columns in update statement

### LINKED ISSUE #4514: cannot update rows with irregular enum value
1. Insert irregular enum value in NON-STRICT MODE (e.g. value = 0).
2. Update other column in STRICT MODE.

In MySQL, the above operation is OK. In TiDB it fails.

### PR DESCRIPTION
**Pull request by breeswish**
fix #4514

@XuHuaiyu @winkyao @hicqu PTAL

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by coocood** [comment]
This is a data race in `goleveldb` which is fixed by 
https://github.com/syndtr/goleveldb/commit/e5ce663718df7509857462c00d91157583a457a9#diff-2f76daf2fb4a517abdbea03f2e025a0a

**Pull request merged**
