### PR TITLE
tablecodec: fix write wrong prefix index value when collation is ascii_bin/latin1_bin

### LINKED ISSUE #24569: value end with space's unique check doesn't works when columns be non-utf8 collation + prefix column index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table zz (x varchar(40) CHARACTER SET ascii COLLATE ascii_bin, UNIQUE KEY `uk`(`x`(4)));
insert into zz select 'abc ';
insert into zz select 'abc d';
```

### 2. What did you expect to see? (Required)

```
insert into zz select 'abc d';
mysql> insert into zz select 'abc d';
ERROR 1062 (23000): Duplicate entry 'abc ' for key 'uk'
```

### 3. What did you see instead (Required)

```
mysql> insert into zz select 'abc d';
Query OK, 1 row affected (0.01 sec)
Records: 1  Duplicates: 0  Warnings: 0
```

### 4. What is your TiDB version? (Required)

5.0.0, 5.0.1

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Issue Number: 

close #24569
info #24548 (only address https://github.com/pingcap/tidb/issues/24548#issuecomment-839423017, mainly issue seems have some other problem in tikv side)

Problem Summary:

prefix index will truncate value during insert, but for not utf8 collation, the code is wrong, it change type from string to bytes when handing truncate value to prefix len, at last, encode key will treat it as bytes and miss handling collation's trim space logic.

this issue need:

- prefix column index
- end with space after trimmed to the prefix length

the question maybe meet:

- unique index's duplicate check doesn't work for clustered or nonclustered index table
- admin check table should be fail when table is clustered index table

### What is changed and how it works?

What's Changed, How it Works:

set it as string type if before truncating it's string type.

### Related changes

- Need to cherry-pick to the release branch 5.0

### Check List 

Tests 

- Unit test

Side effects

- n/a

### Release note 

-  Fix write wrong prefix index value when collation is ascii_bin/latin1_bin

### CODE REVIEW

**Review by cfzjywxk — COMMENTED** [review]
/lgtm

**Comment by lysu** [comment]
@tangenta  PTAL

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
