### PR TITLE
expression: add warnings for logarithm functions

### LINKED ISSUE #17992: No warning for invalid usage of function LN()
## Bug Report

`LN(0)` should result in a warning or an error

### 1. Minimal reproduce step (Required)

````
select LN(0);
````

### 2. What did you expect to see? (Required)

A warning is raised or the error is returned.

```` 
-- MySQL 5.7
mysql> select LN(0);
+-------+
| LN(0) |
+-------+
|  NULL |
+-------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+--------------------------------+
| Level   | Code | Message                        |
+---------+------+--------------------------------+
| Warning | 3020 | Invalid argument for logarithm |
+---------+------+--------------------------------+
1 row in set (0.00 sec)
````

### 3. What did you see instead (Required)

````
mysql> select LN(0);
+-------+
| LN(0) |
+-------+
|  NULL |
+-------+
1 row in set (0.00 sec)
````

### 4. Affected version (Required)

````
commit 4e74d40392e9b81f2a90cbc2f7777fd35f87b2e7 (HEAD -> master, origin/master, origin/HEAD)
Author: Arenatlx <ailinsilence4@gmail.com>
Date:   Fri Jun 12 16:58:00 2020 +0800
````

### PR DESCRIPTION
**Pull request by dyzsr**
### What problem does this PR solve?

Issue Number: close #17992 

Problem Summary: No warning for invalid usage of function LN()

### What is changed and how it works?

What's Changed:
* Add warnings when logarithm functions are given invalid arguments
* Add error code (3020) for invalid argument for logarithm

### Check List 

Tests 

- Unit test

### Release note 

- bug fix for logarithm functions

### CODE REVIEW

**Comment by zz-jason** [comment]
@dyzsr Do we need to cherry-pick this PR to release branches?

**Comment by dyzsr** [comment]
> @dyzsr Do we need to cherry-pick this PR to release branches?

Maybe not, it's a tiny change and doesn't affect much. But I'm not sure about this.

**Comment by zz-jason** [comment]
> > @dyzsr Do we need to cherry-pick this PR to release branches?
> 
> Maybe not, it's a tiny change and doesn't affect much. But I'm not sure about this.

It's a bugfix, let's backport it to release changes.

**Pull request merged**
