### PR TITLE
ddl, domain: make schema correct after the execution of operations are cancelled halfway.

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve? 
onTruncateTable in ddl/table.go
```
	err = t.DropTable(schemaID, tblInfo.ID, true)
	if err != nil {
		job.State = model.JobStateCancelled
		return ver, errors.Trace(err)
	}

        ...

	err = t.CreateTable(schemaID, tblInfo)
	if err != nil {
		job.State = model.JobStateCancelled
		return ver, errors.Trace(err)
	}
```
* When the operation of "CreateTable" is failed, the "DropTable" will execute successfully and this table's data will be deleted.
Because some operations of updating meta will commit to KV after canceling jobs.
In addition to this operation, other operations will have similar problems.
* We should not delete data the truncate job is canceled.

### What is changed and how it works?
* Reset the schema changes after canceling jobs.
* Data can only be deleted when a job is successfully executed.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by winkyao** [comment]
This PR need to pick to 2.0 and 2.1

**Comment by winkyao** [comment]
@zimulala Please fix ci.

**Comment by zimulala** [comment]
PTAL @ciscoxll

**Pull request merged**
