### PR TITLE
txn: fix `invalid transaction` error when doing stale read in RC isolation level (#33653)

### LINKED ISSUE #30872: Stale read failed for read-committed isolation when autocommit=0
## Bug Report

Stale read failed for read-committed isolation

### 1. Minimal reproduce step (Required)

```
drop table if exists t1;
create table t1(id int primary key);
set tx_isolation = 'READ-COMMITTED';
set autocommit=0;
select * from t1 as of timestamp now() where id=1;
```

### 2. What did you expect to see? (Required)

```
mysql> select * from t1 as of timestamp now() where id=1;
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select * from t1 as of timestamp now() where id=1;
ERROR 8024 (HY000): invalid transaction
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #33653 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/33662
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/33662:release-5.4-ec637878d4ca
```

---

### What problem does this PR solve?

Issue Number: close #30872

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix `invalid transaction` error when doing stale read in RC isolation level
```

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @xhebox @Yisaer

**Review by xhebox — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
