### PR TITLE
ddl: check column and partition value have same type for range column partition (#12664)

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry-pick https://github.com/pingcap/tidb/pull/12664

### CODE REVIEW

**Comment by tiancaiamao** [comment]
We should bring this to v3.0.5
PTAL @jackysp @zimulala @crazycs520

**Comment by tiancaiamao** [comment]
Block by https://github.com/pingcap/tidb/pull/12718

**Comment by jackysp** [comment]
CI failed. @tiancaiamao

**Comment by tiancaiamao** [comment]
Block by https://github.com/pingcap/tidb/pull/12815

**Pull request merged**
