### PR TITLE
executor: record prepared stmt in `handle_query_duration`

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

we cannot see duration by sql_type if stmt be run as prepared stmt:

image

### What is changed and how it works?

- save StmtType in Prepared in prepare phase
- record stmtType(Select/Update/Insert) instead of "Execute" in execute phase

### Check List 

Tests 

 - Manual test

Code changes

 - N/A

Side effects

 - N/A

Related changes

 - Need to cherry-pick to the release branch

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/11753)

### CODE REVIEW

**Comment by lysu** [comment]
need merge parser pr https://github.com/pingcap/parser/pull/487 first

**Comment by cfzjywxk** [comment]
LGTM

**Comment by tiancaiamao** [comment]
https://github.com/pingcap/parser/pull/487 is merged
Would you like to update go.mod, please? @lysu

**Pull request merged**
