### PR TITLE
types: fix undefined behavior in numeric types cast (cast 1<<64 to uint64)

### PR DESCRIPTION
**Pull request by H-ZeX**
Signed-off-by: H-ZeX <hzx20112012@gmail.com>

### What problem does this PR solve? 

In [go-spec-conversions](https://golang.org/ref/spec#Conversions), there is this paragraph

> Conversions between numeric types
> ...
> In all non-constant conversions involving floating-point or complex values, **if the result type cannot represent the value the conversion succeeds but the result value is implementation-dependent.**

so, `float64(1<<64)` cast to uint64 is undefined behavor. although in current go compiler, it is `(1<<63)`, which is not same as mysql5.7 does.

### Check List 

- integration testing

Code changes

No.

Side effects

No.

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
And do we also need to cherry pick this commit to release-3.1

**Comment by lonng** [comment]
@XuHuaiyu PTAL

**Comment by lonng** [comment]
@H-ZeX Please cherry-pick this PR manually.

**Pull request merged**
