### PR TITLE
executor: ignore spill action when trigger global memory kill 

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/37816

Problem Summary:

### What is changed and how it works?

No matter what the behavior of SoftLimit and HardLimit is, when TiDB memory usage reaches the threshold, OOMAction(Panic or Log) will be triggered directly.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by XuHuaiyu — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Comment by hawkingrei** [comment]
@wshwsh12 PTAL

```
--- FAIL: TestGlobalMemoryControl2 (0.98s)

panic: runtime error: index out of range [0] with length 0 [recovered]

	panic: runtime error: index out of range [0] with length 0


goroutine 109560 [running]:

testing.tRunner.func1.2({0x4a17500, 0xc004504018})

	GOROOT/src/testing/testing.go:1396 +0x24e

testing.tRunner.func1()

	GOROOT/src/testing/testing.go:1399 +0x39f

panic({0x4a17500, 0xc004504018})

	GOROOT/src/runtime/panic.go:884 +0x212

github.com/pingcap/tidb/executor_test.TestGlobalMemoryControl2(0x3efb2c6?)

	executor/executor_test.go:6158 +0x429

testing.tRunner(0xc0070fd6c0, 0x4e75d60)

	GOROOT/src/testing/testing.go:1446 +0x10b

created by testing.(*T).Run

	GOROOT/src/testing/testing.go:1493 +0x35f

```

**Pull request merged**
