### PR TITLE
tikv: don't collapse batch resolve locks

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?
Problem Summary:
https://github.com/pingcap/tidb/pull/16838 collapses the same resolve lock requests. However, it uses `RegionId + StartVersion` as the key:
https://github.com/pingcap/tidb/blob/e3e51b4663d11aa7caaf4d2a084c793560a4d983/store/tikv/client_collapse.go#L61

When doing GC, GC worker calls `BatchResolveLocks` whose `StartVersion` is always 0. It results in unexpected collapses:
https://github.com/pingcap/tidb/blob/e3e51b4663d11aa7caaf4d2a084c793560a4d983/store/tikv/lock_resolver.go#L241

### What is changed and how it works?
What's Changed:
Don't collapse batch resolve locks.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit tests

Side effects

### Release note 
* No release note

### CODE REVIEW

**Comment by jackysp** [comment]
How did you find this bug? @youjiali1995

**Comment by youjiali1995** [comment]
> How did you find this bug? @youjiali1995

Green GC test always fails after upgrading dependency of it to latest release-4.0.

**Comment by MyonKeminta** [comment]
Does this affect data correctness? If so, it will affect legacy resolvelocks mode too

**Comment by youjiali1995** [comment]
> Does this affect data correctness? If so, it will affect legacy resolvelocks mode too

Yes. But It is not released in any version. @MyonKeminta

**Pull request merged**
