### PR TITLE
lightning: output a clearer exit message

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?
- The exit message of TiDB-Lightning "tidb lightning eixt" if somewhat confusing because user doesn't know whether is finished.
- The precheck output message is also misleading if there are some warnings
middle_img_v2_61f6f546-bdd6-441b-8c0f-4b32917e74ag

Problem Summary:

### What is changed and how it works?
- output a clearer exit mesage with `finish=true/false` 
- Remove the useless precheck summary, if the check fails, there are alrealy error messages; if there are only warnings, the detail table already contains enough information.

### Check List 

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Review by gozssky — APPROVED** [review]

**Comment by glorv** [comment]
./run-unit-test

**Pull request merged**
