### PR TITLE
executor: split range in `TableReader`

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve? 

This PR aims to solve the issue that the TiKV timeout error is caused by the too large range in one request when we don't need to keep the data to be read in order.

### What is changed and how it works?

This PR implements a new type of resultHandler, which cuts the original range slice into multiple smaller ones and sends these range segments to multiple workers for consumption.

It works well compared with rewriting the Select operation involving a large range to Union {a lot of small range select}.

Currently, it is only implemented in TableReader and only works for the situation where the data to be read does not need to be in order. In the following PRs, it will be implemented in other readers and work for the situation where the data to be read is in order.

### Check List 

Tests 

 - existing unit test with set `rangePerRequest` to 1
 - New unit test is writing.

Code changes

 - Has interface methods change

### CODE REVIEW

**Comment by CaitinChen** [comment]
Here is a suggestion for your PR description:

**What problem does this PR solve?**
This PR aims to solve the issue that the TiKV timeout error is caused by the too large range in one request when we don't need to keep the data to be read in order.

**What is changed and how it works?**
This PR implements a new type of `resultHandler`, which cuts the original range slice into multiple smaller ones and sends these range segments to multiple workers for consumption.

It works well compared with rewriting the `Select` operation involving a large range to `Union` {a lot of small range select}.

Currently, it is only implemented in `TableReader` and only works for the situation where the data to be read does not need to be in order. In the following PRs, it will be implemented in other readers and work for the situation where the data to be read is in order.

**Comment by coocood** [comment]
@winoros 
The TiKV timeout error is caused by request size too large, it exceeds the limit 10MB in TiKV.
An easier way to resolve the issue is to split the cop task by range size in `store/tikv`.`buildCopTasks`

Then we don't need to add another layer of concurrency.

**Comment by winoros** [comment]
@CaitinChen Thanks!
@coocood I'll take look into it.

**Comment by CaitinChen** [comment]
@winoros You are welcome.

**Comment by winoros** [comment]
By @coocood 's advice, i'll solve by changing the logical of sending cop task.

**Pull request closed without merging**
