### PR TITLE
executor: fix `BatchPoint` leads to tidb panic when KeyPartition column is part of multi-column index

### LINKED ISSUE #51313: `batchPoint` leads to tidb panic when `KeyPartition` column is part of multi-column index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table tkey (col1 int not null, col2 varchar(32) not null, col3 int not null, unique(col1, col2)) partition by key(col2) partitions 4;
insert into tkey values(1, 'a', 1), (2, 'b', 2);
select col1, col2, col3 from tkey where col1 = 1 and col2 = 'a' or col1 = 3 and col2 = 'c';
```

### 2. What did you expect to see? (Required)

```
mysql> select col1, col2, col3 from tkey where col1 = 1 and col2 = 'a' or col1 = 3 and col2 = 'c';
+------+------+------+
| col1 | col2 | col3 |
+------+------+------+
|    1 | a    |    1 |
+------+------+------+
1 row in set, 1 warning (0.01 sec)
```

### 3. What did you see instead (Required)

```
mysql> select col1, col2, col3 from tkey where col1 = 1 and col2 = 'a' or col1 = 3 and col2 = 'c';
ERROR 1105 (HY000): runtime error: index out of range [1] with length 1
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #51313

Problem Summary:

Fix it reference [point_get](https://github.com/pingcap/tidb/blob/961159c12f64d2ec5a11ff8c24d273d704b02f9b/pkg/planner/core/point_get_plan.go#L1930).

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Comment by Defined2014** [comment]
ref link #50210

**Review by mjonss — APPROVED** [review]

**Comment by jiyfhust** [comment]
/hold

```
time="2024-03-04T17:18:40+08:00" level=error msg="1 tests failed\n"

time="2024-03-04T17:18:40+08:00" level=error msg="run test [executor/batch_point_get] err: sql:explain format='brief' select col1, col2, col3 from tkey where col1 = 1 and col2 = 'a' or col1 = 3 and col2 = 'c';: run \"explain format='brief' select col1, col2, col3 from tkey where col1 = 1 and col2 = 'a' or col1 = 3 and col2 = 'c';\" at line 114 err, we got \nexplain format='brief' select col1, col2, col3 from tkey where col1 = 1 and col2 = 'a' or col1 = 3 and col2 = 'c';\nid\testRows\ttask\taccess object\toperator info\nIndexLookUp\t2.00\troot\tpartition:p3\t\n├─IndexRangeScan(Build)\t2.00\tcop[tikv]\ttable:tkey, index:col1(col1, col2)\trange:[1 \"a\",1 \"a\"], [3 \"c\",3 \"c\"], keep order:false, stats:pseudo\n└─TableRowIDScan(Probe)\t2.00\tcop[tikv]\ttable:tkey\tkeep order:false, stats:pseudo\n\nbut read result err EOF"
```

**Comment by jiyfhust** [comment]
> Please sync with the master branch.

Synced already.

**Comment by jiyfhust** [comment]
@tiancaiamao Can you remove the "/hod" lable after you appove this pr?

**Comment by jiyfhust** [comment]
> @tiancaiamao Can you remove the "/hod" lable after you appove this pr?

/unhold

**Pull request merged**
