### PR TITLE
server: Remove old handshake support

### LINKED ISSUE #36922: Remove old handshake support
## Enhancement

The old handshake [Protocol::HandshakeV9](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase_packets_protocol_handshake_v9.html) and [Protocol::HandshakeResponse320](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase_packets_protocol_handshake_response.html#sect_protocol_connection_phase_packets_protocol_handshake_response320) is only used with pre-4.1 MySQL clients and libraries.

This was only ever partially supported to allow old HAProxy versions to do a health check. 

Removing this helps to reduce code complexity and might also improve security.

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #36922

Problem Summary:

Remove support for:
* [`Protocol::HandshakeV9`](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase_packets_protocol_handshake_v9.html)
* [`Protocol::HandshakeResponse320`](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase_packets_protocol_handshake_response.html#sect_protocol_connection_phase_packets_protocol_handshake_response320)

This removes support for pre-4.1 MySQL clients. As TiDB doesn't support the old pre-4.1 hashing method I don't think these were ever fully supported.

See also https://dev.mysql.com/doc/refman/5.6/en/password-hashing.html

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note 

```release-note
Support for handshake support for pre-4.1 MySQL clients was removed
```

### Questions to reviewers

* Is removing this functionality that only exists there for old HAProxy versions allowed according to the compatibility policy?

### CODE REVIEW

**Comment by morgo** [comment]
@dveeden I think you are correct that it was never fully supported, but the intended use-case was strictly for HAProxy: https://github.com/pingcap/tidb/pull/8812

I believe HAProxy's MySQL protocol support does not link against a client API, hence the weird behavior. Please check and make sure it works with this removed :-)

**Comment by dveeden** [comment]
> @dveeden I think you are correct that it was never fully supported, but the intended use-case was strictly for HAProxy: #8812
> 
> I believe HAProxy's MySQL protocol support does not link against a client API, hence the weird behavior. Please check and make sure it works with this removed :-)

I'll check that. Let's set this to draft status until that's done

**Comment by dveeden** [comment]
https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#4.2-option%20mysql-check says this supports both pre-v4.1 and post-v4.1 auth and the default is post-v4.1.

See also: https://github.com/haproxy/haproxy/commit/62f79fe68a87c66e44bc172959f03f810572e4fa

I've tested with haproxy (compiled from master at bc1223be7) and it does work with the default and with the `post-41` option. With `pre-41` it fails with this commit and succeeds with tidb from current master.

**Review by lysu — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

**Review by lysu — APPROVED** [review]

**Comment by tisonkun** [comment]
@lysu I sent an invitation to respect you as a TiDB committer as the consensus in https://github.com/pingcap/community/pull/522 .

You can accept by https://github.com/orgs/pingcap/invitation and approve this PR.

**Comment by tisonkun** [comment]
@lysu oops a race happened :)

**Comment by tisonkun** [comment]
> Is removing this functionality that only exists there for old HAProxy versions allowed according to the compatibility policy?

/hold

@lysu @wjhuang2016 @morgo please be aware of the compatibility breaker and unhold merging if no further concern

**Comment by dveeden** [comment]
> > Is removing this functionality that only exists there for old HAProxy versions allowed according to the compatibility policy?
> 
> /hold
> 
> @lysu @wjhuang2016 @morgo please be aware of the compatibility breaker and unhold merging if no further concern

This breaks compatibility with HAProxy v1.4 and earlier. HAProxy v1.4 was initially released on 2010-02-26 and is EOL since 2018-02-08 (source: "Latest versions" table on https://www.haproxy.org/ )

**Comment by dveeden** [comment]
Note that with MySQL Server 8.0.26 and HAProxy with explicit `pre-41` config this happens:
```
[WARNING]  (2194795) : Server tidb/tidb1 is DOWN, reason: Layer7 wrong status, code: 1251, info: "Client does not support authentication protocol requested by server; consider upgrading MySQL client", check duration: 0ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
```

**Comment by dveeden** [comment]
Note that CentOS 7 itself comes with a very old HAProxy version: v1.5 but this is enough to support post-41. ( source: http://mirror.centos.org/centos/7/os/x86_64/Packages/ )

So this won't break the compatibility with CentOS 7 and newer as claimed on https://docs.pingcap.com/tidb/stable/hardware-and-software-requirements

**Comment by dveeden** [comment]
And for compatibility with MySQL:
" Support for pre-4.1 password hashes was removed in MySQL 5.7.5" (source: https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html)

**Comment by ThomasYYYY** [comment]
What will be the benefits if we remove pre-4.1 password hashes?

**Comment by dveeden** [comment]
> What will be the benefits if we remove pre-4.1 password hashes?

Less complexity. As this code is dealing with authentication this benefits security.

**Comment by ThomasYYYY** [comment]
> > What will be the benefits if we remove pre-4.1 password hashes?
> 
> Less complexity. As this code is dealing with authentication this benefits security.

Cannot agree more with the less complexity thing. Do we have any users using HAProxy v1.4 or earlier? 
We have to stop them from upgrading TiDB to the new version, otherwise there will be some downtime.

**Comment by dveeden** [comment]
> > > What will be the benefits if we remove pre-4.1 password hashes?
> > 
> > 
> > Less complexity. As this code is dealing with authentication this benefits security.
> 
> Cannot agree more with the less complexity thing. Do we have any users using HAProxy v1.4 or earlier?
> We have to stop them from upgrading TiDB to the new version, otherwise there will be some downtime.

1. I don't know *if* and how many users there are of HAProxy 1.4 and earlier
2. This only impacts the `mysql-check`. Using HAProxy 1.4 with a TCP or HTTP check would be fine.
3. I don't think there would be many users of HAProxy 1.4 and earlier as CentOS 7 (our recommended OS) ships with HAProxy 1.5 and is already quite old (and being replaced with CentOS 8) 
4. This should be changed in `master` and land in a new major version of TiDB (v5.x.0 or so). This is not changed as part of a minor update.
5. As this (and other important notes) should be in the release notes users should be aware of this when they do the upgrade.

**Review by morgo — APPROVED** [review]
LGTM; removing will help improve security, since an old auth mechanism like this will surely become a target.

**Pull request merged**
