### PR TITLE
*: update client-go to use resolveForRead

### LINKED ISSUE #30313: Update client-go to use resolveForRead
## Enhancement

ref https://github.com/tikv/client-go/issues/356

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?

Issue Number: close #30313

Problem Summary:

update client-go to use resolveForRead

### What is changed and how it works?

update client-go.

### Check List

Tests 
- [x] No code
Unistore doesn't support read-through-lock and the code change is small, so I don't write a test.

Side effects

Documentation

### Release note

```release-note
None
```

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by you06 — APPROVED** [review]
LGTM

**Comment by you06** [comment]
Seems there is something wrong with fileserver.

**Pull request merged**
