### PR TITLE
executor: fix bug when comparing year column with NULL

### LINKED ISSUE #23038: wrong result of "left join where year != null"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
drop table if exists t;
CREATE TABLE `t` (
  `COL1` year(4) DEFAULT NULL COMMENT 'DATE AND TIME',
  `COL2` varchar(20) DEFAULT NULL,
  KEY `UK_COL1` (`COL1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
insert into t values(1, "1");
insert into t values(1, "2");
select *  from t as t1 left join t as t2 on t1.col1 = t2.col1 where t1.col1 != NULL;
select count(*) from t as t1 left join t as t2 on t1.col1 = t2.col1 where t1.col1 != NULL;
select t1.col1, t2.col2 from t as t1 left join t as t2 on t1.col1 = t2.col1 where t1.col1 != NULL;
```

### 2. What did you expect to see? (Required)
mysql 8.0.23
```
mysql> select *  from t as t1 left join t as t2 on t1.col1 = t2.col1 where t1.col1 != NULL;
Empty set (0.04 sec)

mysql> select count(*) from t as t1 left join t as t2 on t1.col1 = t2.col1 where t1.col1 != NULL;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.04 sec)

mysql> select t1.col1, t2.col2 from t as t1 left join t as t2 on t1.col1 = t2.col1 where t1.col1 != NULL;
Empty set (0.04 sec)
```
### 3. What did you see instead (Required)
master
```
mysql> select *  from t as t1 left join t as t2 on t1.col1 = t2.col1 where t1.col1 != NULL;
Empty set (0.00 sec)

mysql> select count(*) from t as t1 left join t as t2 on t1.col1 = t2.col1 where t1.col1 != NULL;
+----------+
| count(*) |
+----------+
|        4 |
+----------+
1 row in set (0.00 sec)

mysql> select t1.col1, t2.col2 from t as t1 left join t as t2 on t1.col1 = t2.col1 where t1.col1 != NULL;
+------+------+
| col1 | col2 |
+------+------+
| 2001 | NULL |
| 2001 | NULL |
+------+------+
2 rows in set (0.00 sec)
```

release-4.0 and release-5.0-rc
```
mysql> select *  from t as t1 left join t as t2 on t1.col1 = t2.col1 where t1.col1 != NULL;
+------+------+------+------+
| COL1 | COL2 | COL1 | COL2 |
+------+------+------+------+
| 2001 | 1    | 2001 | 1    |
| 2001 | 1    | 2001 | 2    |
| 2001 | 2    | 2001 | 1    |
| 2001 | 2    | 2001 | 2    |
+------+------+------+------+
4 rows in set (0.00 sec)

mysql> select count(*) from t as t1 left join t as t2 on t1.col1 = t2.col1 where t1.col1 != NULL;
+----------+
| count(*) |
+----------+
|        4 |
+----------+
1 row in set (0.00 sec)

mysql> select t1.col1, t2.col2 from t as t1 left join t as t2 on t1.col1 = t2.col1 where t1.col1 != NULL;
+------+------+
| col1 | col2 |
+------+------+
| 2001 | 1    |
| 2001 | 2    |
| 2001 | 1    |
| 2001 | 2    |
+------+------+
4 rows in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

master dc9ceb4bba96608de2aa5ac906e9ad003fa8a46c
release-5.0-rc f41ca49fab41af6ba168e94e6eeeef517778cee1
release-4.0 8406e7f58b1d5811966a6811d7b519bcfd6020b2

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #23038 

Problem Summary: the result of comparing year_col with NULL is wrong.

    drop table t1;
    create table t1(c1 year);
    insert into t1 values(2001);
    select * from t1 where c1 != NULL;
    
    Server version: 5.7.25-TiDB-v4.0.0-beta.2-2139-g9cb9b69b6 TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible
    mysql> select * from t1 where c1 != NULL;
    +------+
    | c1   |
    +------+
    | 2001 |
    +------+
    1 row in set (0.01 sec)

### What is changed and how it works?
What's Changed: 
1. When rewrite compare expression, NULL is accidentally changed to be zero. So we change compareFunctionClass::refineArgs() to fix this.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test: tidb_test.go:TestYear()

Side effects: no side effects

### Release note 

- fix bug when comparing year column with NULL

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
Test case is needed.

**Comment by guo-shaoge** [comment]
Another bug about year type: wrong index range for column of year type[](https://github.com/pingcap/tidb/issues/23077)

**Comment by guo-shaoge** [comment]
already fixed here: https://github.com/pingcap/tidb/pull/22821

**Comment by guo-shaoge** [comment]
Forgot to update latest commit. Will fix this in another PR.

**Pull request closed without merging**
