### PR TITLE
session: fix account_locked for root

### PR DESCRIPTION
**Pull request by imtbkcat**
### What problem does this PR solve? 
There is an mistake in #9377, the `account_locked` for `root` was set to `Y` in bootstrap. Actually it is `N` .

### What is changed and how it works?
set `Account_locked` to `N` for `root`

### Check List 

Tests 

 - Unit test

Code changes

 - Has persistent data change

Side effects

### CODE REVIEW

**Comment by zz-jason** [comment]
@tiancaiamao @lysu @jackysp PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
