### PR TITLE
planner: add optimizer hint `TOPN_TO_COP()` (#19545)

### LINKED ISSUE #19288: Consider a switch to force TopN push down
## Development Task

At present, TopN pushdown to TiKV Coprocessor is controlled by the physical optimization phase. This task aims to provide a switch to force TopN pushing down. like [`agg_to_cop()`](https://docs.pingcap.com/tidb/stable/optimizer-hints#agg_to_cop), maybe we can add a `topn_to_cop()` optimizer hint.

An alternative approach is to provide an instance level variable to control whether the `TopN` operator on that tidb instance is forcibly pushed to the coprocessor.

To gain better performance, we'd better handle all the coprocessor tasks for a tikv to calculate the TopN on that tikv instance, then gather all the TopN result from all the tikv instances, calculate the final TopN result in the tidb instance.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19545 to release-4.0

---

### What problem does this PR solve?
Add sql hint for enforcing push topn to coprocessor.

Issue Number: close #19288 

### What is changed and how it works?
Add a `topn_to_cop()` optimizer hint to force TopN pushing down to TiKV Coprocessor.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- None

### Release note 

- None

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
LGTM

**Review by lzmhhh123 — APPROVED** [review]
LGTM

**Review by zz-jason — COMMENTED** [review]
@qw4990 please resolve conflicts.

**Comment by qw4990** [comment]
This feature has been picked into v4.0 manually by https://github.com/pingcap/tidb/pull/20120.

**Pull request closed without merging**
