### PR TITLE
expression: support pushing function `ROUND` to TiFlash

### PR DESCRIPTION
**Pull request by riteme**
### What problem does this PR solve?

pingcap/tics#2550

Problem Summary: enable function `ROUND` push down to TiFlash.

### What is changed and how it works?

What's Changed:

- `expression/expression.go`

How it Works:

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
support pushing function `ROUND` to TiFlash.
```

### CODE REVIEW

**Comment by fuzhe1989** [comment]
cc @zanmato1984 @LittleFall

**Review by ichn-hu — APPROVED** [review]

**Review by LittleFall — APPROVED** [review]
LGTM

**Comment by riteme** [comment]
/run-license/cla

**Pull request merged**
