### PR TITLE
parser: support LOAD DATA ... IGNORE/REPLACE

### PR DESCRIPTION
**Pull request by sundl123**
### What problem does this PR solve? 

Fixes https://github.com/pingcap/tidb/issues/9847

### What is changed and how it works?

- fix parsing error raised when `LoadDataStmt` has `IGNORE`  field
- for LoadDataStmt with `REPLACE`, it will not raise parsing error, but will still return warning message `Load Data: don't support load data with replace field"`. I will consider implement this in anther PR.

#### Tests 

- UT
- Manual test (add detailed scripts or steps below), follow test instructions descriped in pingcap/tidb#9847 (comment) , the parse error should disappear now.

#### Code changes

1. Update parser  from https://github.com/pingcap/parser/pull/312
2. add new field `OnDuplicate` both in `LoadData ` and `LoadDataExec` struct to pass the duplicate key handling option info.

#### Related changes

refer to https://github.com/pingcap/parser/pull/312

### CODE REVIEW

**Comment by shenli** [comment]
@sundl123 Please fix the CI.

**Comment by sundl123** [comment]
@shenli  

I added new unit tests and most of CI pipeline are fixed now.

 [the remaining error](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/827/pipeline) is because I did not use parser from https://github.com/pingcap/parser since https://github.com/pingcap/parser/pull/312 is not merged , need to merge that PR so the whole CI pipeline can pass, can you help with that?

**Comment by sundl123** [comment]
@shenli  all tests are passed, pls review, thank you

**Pull request merged**
