### PR TITLE
docs(task_type): rectify grammatical mistake

### PR DESCRIPTION
**Pull request by EdwardShen125**
### What problem does this PR solve?

Issue Number: None

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by hawkingrei** [comment]
> [CLA assistant check](https://cla.pingcap.net/pingcap/tidb?pullRequest=46256) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.pingcap.net/pingcap/tidb?pullRequest=46256) before we can accept your contribution.
> **沈厚桦** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.pingcap.net/check/pingcap/tidb?pullRequest=46256) it.

@EdwardShen125 Please sign the CLA.

**Comment by lance6716** [comment]
@EdwardShen125 Please sign the CLA.

**Comment by hawkingrei** [comment]
@EdwardShen125 Please sign the CLA~

**Comment by hawkingrei** [comment]
@EdwardShen125 I close this PR. If you sign CLA, please open it.

**Pull request closed without merging**
