### PR TITLE
changelog: fix broken link

### PR DESCRIPTION
**Pull request by ericsyh**
Signed-off-by: Eric Shen <ericshenyuhao@outlook.com>

### What problem does this PR solve?

Problem Summary: release notes link in changelog is broken. 

### What is changed and how it works?

What's Changed: update the release notes link in changelog.

### Related changes

- Need to cherry-pick to the release branch

### Release Note

- No release note

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

**Review by ngaut — APPROVED** [review]
/LGTM

**Pull request merged**
