### PR TITLE
ddl: fix invalid index on multi-layer virtual columns (#11260)

### PR DESCRIPTION
**Pull request by tangenta**
Cherry-pick #11260.

### CODE REVIEW

**Comment by tangenta** [comment]
randgen test keeps failing:
```
 2019/07/28 16:31:49.196 main.go:713: [fatal] run test [udaf_bitor_union] err: sql:select bit_or(`col_decimal_10_4_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned` order by a;: failed to run query
 "select bit_or(`col_decimal_10_4_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned` order by a;"
 around line 566,
 we need(245):
 select bit_or(`col_decimal_10_4_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned` order by a;
 a
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 1
 1
 1
 1
 12
 12
 13
 63
 94

 but got(245):
 select bit_or(`col_decimal_10_4_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned` order by a;
 a
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 1
 1
 1
 1
 13
 13
 13
 63
 95



```

**Comment by amyangfei** [comment]
> randgen test keeps failing:
> 

this is because https://github.com/pingcap/tidb/pull/11295 changed some mysql-test test cases, but the cherry-pick to 3.0, https://github.com/pingcap/tidb/pull/11469 has not been merged

**Comment by tangenta** [comment]
```sql

[2019-08-04T14:44:52.655Z] 2019/08/04 22:44:52.542 main.go:821: [fatal] run test [window_functions] err: sql:SELECT SUM(DISTINCT b) OVER () FROM t;: failed to run query 

[2019-08-04T14:44:52.655Z] "SELECT SUM(DISTINCT b) OVER () FROM t;" 

[2019-08-04T14:44:52.655Z]  around line 1004, 

[2019-08-04T14:44:52.655Z] we need(117):

[2019-08-04T14:44:52.655Z] SELECT SUM(DISTINCT b) OVER () FROM t;

[2019-08-04T14:44:52.655Z] Error 1235: This version of TiDB doesn't yet support '<window function>(DISTIN

[2019-08-04T14:44:52.655Z] but got(117):

[2019-08-04T14:44:52.655Z] SELECT SUM(DISTINCT b) OVER () FROM t;

[2019-08-04T14:44:52.655Z] SUM(DISTINCT b) OVER ()

[2019-08-04T14:44:52.655Z] 36

[2019-08-04T14:44:52.655Z] 36
```

**Pull request merged**
