### PR TITLE
planner: fix wrong index merge selection

### LINKED ISSUE #22807: index merge is not used as expected
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table index_testing(
id int not null,
c1 varchar(255),
c2 varchar(255),
c3 varchar(255),
c4 varchar(255),
aid bigint,
created_at timestamp,
primary key (id)
);create index aid_c1 on index_testing(aid,c1);
create index aid_c2 on index_testing(aid,c2);
create index aid_c3 on index_testing(aid,c3);
create index aid_c4 on index_testing(aid,c4);
create index testing_created on index_testing(created_at);
set @@tidb_enable_index_merge="ON";
desc select /*+ USE_INDEX_MERGE(index_testing, aid_c1, aid_c2) */ * from index_testing where (aid = 1 and c1="aaa") or (aid = 2 and c2="bbb");
+-------------------------------+---------+-----------+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| id                            | estRows | task      | access object                              | operator info                                                                                                                                  |
+-------------------------------+---------+-----------+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| IndexLookUp_11                | 8.08    | root      |                                            |                                                                                                                                                |
| ├─IndexRangeScan_8(Build)     | 10.10   | cop[tikv] | table:index_testing, index:aid_c1(aid, c1) | range:[1 "aaa",1 "aaa"], [2,2], keep order:false, stats:pseudo                                                                                 |
| └─Selection_10(Probe)         | 8.08    | cop[tikv] |                                            | or(and(eq(test.index_testing.aid, 1), eq(test.index_testing.c1, "aaa")), and(eq(test.index_testing.aid, 2), eq(test.index_testing.c2, "bbb"))) |
|   └─TableRowIDScan_9          | 10.10   | cop[tikv] | table:index_testing                        | keep order:false, stats:pseudo                                                                                                                 |
+-------------------------------+---------+-----------+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
4 rows in set, 1 warning (0.00 sec)
```
### 2. What did you expect to see? (Required)
index merge is used.
### 3. What did you see instead (Required)
indexLookUp
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #22807 

Problem Summary:

Previously we chose the index with the most columns, which is not accurate. We should use the index with the minimal estimated row count.

### What is changed and how it works?

Choose the index with the minimal estimated row count for index merge.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- fix wrong index merge selection

### CODE REVIEW

**Review by winoros — COMMENTED** [review]
lgtm

**Comment by qw4990** [comment]
@wjhuang2016 Please resolve conflicts.

**Review by qw4990 — APPROVED** [review]
/LGTM

**Pull request merged**
