### PR TITLE
tools/check/ut: support pattern matching on test names

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: ref #30822

Problem Summary: In the past, we can only specify one test case to run at a time. It is kind of inconvenient when there are a few tests, for example:
```
TestColumnTypeChangeBetweenInteger
TestColumnTypeChangeStateBetweenInteger
TestColumnTypeChangeFromIntegerToOthers
...
```

We have to run these tests one by one.

### What is changed and how it works?

```
$ ./tools/bin/ut list ddl 'TestColumnTypeChange.*'

TestColumnTypeChangeBetweenInteger
TestColumnTypeChangeStateBetweenInteger
TestColumnTypeChangeFromIntegerToOthers
TestColumnTypeChangeBetweenVarcharAndNonVarchar
TestColumnTypeChangeFromStringToOthers
TestColumnTypeChangeFromNumericToOthers
TestColumnTypeChangeIgnoreDisplayLength
TestColumnTypeChangeFromDateTimeTypeToOthers
TestColumnTypeChangeFromJsonToOthers
TestColumnTypeChangeBetweenFloatAndDouble
TestColumnTypeChangeTimestampToInt
testSerialDBSuite.TestColumnTypeChangeGenUniqueChangingName
```

```
$ ./tools/bin/ut run ddl 'TestColumnTypeChange.*'

2022/03/13 13:49:46 maxprocs: Leaving GOMAXPROCS=10: CPU quota undefined
building task finish, count=12, takes=29.051195667s
run all tasks takes 50.588586459s
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]
I've planned to add the regex support, but found it's easy to match something unexpected, so I gave up...

For example, there are 
```
TestColumnTypeChangeXXX
TestColumnTypeChangeYYY
testSerialDBSuite.TestColumnTypeChangeZZZ
```
where what I really mean '^TestColumnTypeChangeXXX'

Or ... what I mean is just the single function TestColumnTypeChangeYYY...
After supporting regex, it gives me the whole funcitons listed above.

Well... it doesn't matter, as long as one write the regexp exactly correct.

**Review by hawkingrei — APPROVED** [review]

**Comment by tangenta** [comment]
@tiancaiamao How about using a prefix like `"r:"` to recognize whether it should match with regex?

**Comment by tiancaiamao** [comment]
> @tiancaiamao How about using a prefix like `"r:"` to recognize whether it should match with regex?

That's a good idea~

**Review by tiancaiamao — APPROVED** [review]

**Comment by tangenta** [comment]
The data race is unrelated to this PR:

```
[2022-03-21T02:52:25.366Z] ==================
[2022-03-21T02:52:25.366Z] WARNING: DATA RACE
[2022-03-21T02:52:25.366Z] Read at 0x00c00611c038 by goroutine 74:
[2022-03-21T02:52:25.370Z]   github.com/pingcap/tidb/domain/infosync.(*InfoSyncer).ReportMinStartTS()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/domain/infosync/info.go:610 +0x68
[2022-03-21T02:52:25.370Z]   github.com/pingcap/tidb/domain.(*Domain).infoSyncerKeeper()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/domain/domain.go:517 +0x304
[2022-03-21T02:52:25.370Z]   github.com/pingcap/tidb/domain.(*Domain).Init.func12()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/domain/domain.go:868 +0x39
[2022-03-21T02:52:25.370Z] 
[2022-03-21T02:52:25.370Z] Previous write at 0x00c00611c038 by main goroutine:
[2022-03-21T02:52:25.370Z]   github.com/pingcap/tidb/domain/infosync.(*InfoSyncer).SetSessionManager()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/domain/infosync/info.go:213 +0x593
[2022-03-21T02:52:25.370Z]   main.createServer()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/tidb-server/main.go:695 +0x58a
[2022-03-21T02:52:25.370Z]   main.main()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/tidb-server/main.go:205 +0x604
[2022-03-21T02:52:25.370Z] 
[2022-03-21T02:52:25.370Z] Goroutine 74 (running) created at:
[2022-03-21T02:52:25.370Z]   github.com/pingcap/tidb/domain.(*Domain).Init()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/domain/domain.go:868 +0x1315
[2022-03-21T02:52:25.370Z]   github.com/pingcap/tidb/session.(*domainMap).Get.func1()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/tidb.go:83 +0x664
[2022-03-21T02:52:25.370Z]   github.com/pingcap/tidb/util.RunWithRetry()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/misc.go:65 +0x93
[2022-03-21T02:52:25.370Z]   github.com/pingcap/tidb/session.(*domainMap).Get()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/tidb.go:71 +0x38b
[2022-03-21T02:52:25.370Z]   github.com/pingcap/tidb/session.createSessionWithOpt()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:2958 +0x75
[2022-03-21T02:52:25.370Z]   github.com/pingcap/tidb/session.createSession()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:2954 +0x246
[2022-03-21T02:52:25.370Z]   github.com/pingcap/tidb/session.BootstrapSession()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:2791 +0x22f
[2022-03-21T02:52:25.370Z]   main.createStoreAndDomain()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/tidb-server/main.go:298 +0x113
[2022-03-21T02:52:25.370Z]   main.main()
[2022-03-21T02:52:25.370Z]       /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/tidb-server/main.go:204 +0x5e9
[2022-03-21T02:52:25.370Z] ==================
```

**Comment by tiancaiamao** [comment]
You can create a issue for the data race @tangenta

**Comment by tangenta** [comment]
Here is the data race issue: https://github.com/pingcap/tidb/issues/33335

**Pull request merged**
