### PR TITLE
server: fix bug https://asktug.com/t/topic/213082/11

### LINKED ISSUE #29709: Auth failed for `u1@127.%`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

This is a bug introduced by https://github.com/pingcap/tidb/pull/24991.

### 1. Minimal reproduce step (Required)

```
mysql -h127.1 -uroot -P4000
mysql> create user u1@'127.%';
Query OK, 0 rows affected (0.00 sec)
```

```
mysql -h127.1 -uu1 -P4000
ERROR 2000 (HY000): Unknown MySQL error
```

### 2. What did you expect to see? (Required)

In MySQL and older TiDB versions, `u1` can log in as usual.

### 3. What did you see instead (Required)

```
mysql -h127.1 -uu1 -P4000
ERROR 2000 (HY000): Unknown MySQL error
```

In TiDB log:
```
[2021/11/12 09:58:37.805 +08:00] [WARN] [conn.go:712] ["failed to check the user authplugin"] [conn=5] [error="Failed to get user record"]
[2021/11/12 09:58:37.806 +08:00] [ERROR] [conn.go:757] ["authSha packet read failed"] [conn=5] [error=EOF]
[2021/11/12 09:58:37.806 +08:00] [ERROR] [terror.go:307] ["encountered error"] [error=EOF] 
```

### 4. What is your TiDB version? (Required)

```
Release Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by zgcbj**
### What problem does this PR solve?

Issue Number: close #29709

See also https://asktug.com/t/topic/213082/11

Problem Summary:

Too much logs about auth plugin after upgrade tidb v5.2.2
```[WARN] [conn.go:698] [“failed to check the user authplugin”] [conn=599967] [error=“Failed to get user record”]```
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
- Fix the bug that TiDB logs many `failed to check the user authplugin` when a user connects to TiDB.
```

### CODE REVIEW

**Comment by dveeden** [comment]
/retitle server: fix bug https://asktug.com/t/topic/213082/11

**Review by dveeden — APPROVED** [review]

**Comment by bb7133** [comment]
Could you please add some test cases for your change?

**Review by djshow832 — COMMENTED** [review]
Thank you for your contribution!
Can you add a test case in `conn_test.go` to ensure:
- it works now.
- future modifications won't break the compatibility again.

**Comment by zgcbj** [comment]
OK,I will add an ut later.

**Comment by zgcbj** [comment]
@djshow832 @bb7133 PTAL

**Review by djshow832 — APPROVED** [review]

**Comment by fzhedu** [comment]
```
[2021-11-30T04:23:30.650Z] --- FAIL: TestAuthPlugin2 (1.20s)
[2021-11-30T04:23:30.650Z]     conn_test.go:1161: 
[2021-11-30T04:23:30.650Z]         	Error Trace:	conn_test.go:1161
[2021-11-30T04:23:30.650Z]         	Error:      	Not equal: 
[2021-11-30T04:23:30.650Z]         	            	expected: []byte{0x63, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x68, 0x61, 0x32, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64}
[2021-11-30T04:23:30.650Z]         	            	actual  : []byte{0x6d, 0x79, 0x73, 0x71, 0x6c, 0x5f, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64}
[2021-11-30T04:23:30.650Z]         	            	
[2021-11-30T04:23:30.650Z]         	            	Diff:
[2021-11-30T04:23:30.650Z]         	            	--- Expected
[2021-11-30T04:23:30.650Z]         	            	+++ Actual
[2021-11-30T04:23:30.650Z]         	            	@@ -1,3 +1,3 @@
[2021-11-30T04:23:30.650Z]         	            	 ([]uint8) (len=21) {
[2021-11-30T04:23:30.650Z]         	            	- 00000000  63 61 63 68 69 6e 67 5f  73 68 61 32 5f 70 61 73  |caching_sha2_pas|
[2021-11-30T04:23:30.650Z]         	            	+ 00000000  6d 79 73 71 6c 5f 6e 61  74 69 76 65 5f 70 61 73  |mysql_native_pas|
[2021-11-30T04:23:30.650Z]         	            	  00000010  73 77 6f 72 64                                    |sword|
[2021-11-30T04:23:30.650Z]         	Test:       	TestAuthPlugin2
[2021-11-30T04:23:30.650Z] [2021/11/30 12:19:51.390 +08:00] [INFO] [db.go:592] ["Memtable flushed"]
[2021-11-30T04:23:30.650Z] [2021/11/30 12:19:51.390 +08:00] [INFO] [db.go:596] ["Compaction finished"]
[2021-11-30T04:23:30.650Z] [2021/11/30 12:19:51.390 +08:00] [INFO] [db.go:615] ["BlobManager finished"]
[2021-11-30T04:23:30.650Z] [2021/11/30 12:19:51.390 +08:00] [INFO] [db.go:619] ["ResourceManager finished"]
[2021-11-30T04:23:30.650Z] [2021/11/30 12:19:51.390 +08:00] [INFO] [db.go:625] ["Waiting for closer"]
[2021-11-30T04:23:30.650Z] [2021/11/30 12:19:51.390 +08:00] [INFO] [telemetry.go:174] ["Telemetry configuration"] [endpoint=https://telemetry.pingcap.com/api/v1/tidb/report] [report_interval=6h0m0s] [enabled=true]
[2021-11-30T04:23:30.650Z] [2021/11/30 12:19:51.390 +08:00] [INFO] [telemetry.go:174] ["Telemetry configuration"] [endpoint=https://telemetry.pingcap.com/api/v1/tidb/report] [report_interval=6h0m0s] [enabled=true]
[2021-11-30T04:23:30.650Z] [2021/11/30 12:19:51.390 +08:00] [INFO] [ddl_worker.go:313] ["[ddl] add DDL jobs"] ["batch count"=1] [jobs="ID:58, Type:create table, State:none, SchemaState:queueing, SchemaID:1, TableID:57, RowCount:0, ArgLen:1, start time: 2021-11-30 12:19:51.389 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0; "]
[2021-11-30T04:23:30.650Z] [2021/11/30 12:19:51.391 +08:00] [INFO] [ddl.go:553] ["[ddl] start DDL job"] [job="ID:58, Type:create table, State:none, SchemaState:queueing, SchemaID:1, TableID:57, RowCount:0, ArgLen:1, start time: 2021-11-30 12:19:51.389 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"] [query="CREATE TABLE `test` (`iD` bigint(20) NOT NULL, `INT_TEST` int(11) DEFAULT NULL);"]
[2021-11-30T04:23:30.650Z] --- FAIL: TestHandleAuthPlugin (1.20s)
[2021-11-30T04:23:30.650Z] panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[2021-11-30T04:23:30.650Z] 	panic: runtime error: invalid memory address or nil pointer dereference
[2021-11-30T04:23:30.650Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x37116bf]
[2021-11-30T04:23:30.650Z] 
[2021-11-30T04:23:30.650Z] goroutine 504 [running]:
[2021-11-30T04:23:30.650Z] testing.tRunner.func1.2(0x3a557c0, 0x5c03590)
[2021-11-30T04:23:30.650Z] 	/usr/local/go/src/testing/testing.go:1143 +0x332
[2021-11-30T04:23:30.650Z] testing.tRunner.func1(0xc000603980)
[2021-11-30T04:23:30.650Z] 	/usr/local/go/src/testing/testing.go:1146 +0x4b6
[2021-11-30T04:23:30.650Z] panic(0x3a557c0, 0x5c03590)
[2021-11-30T04:23:30.650Z] 	/usr/local/go/src/runtime/panic.go:965 +0x1b9
[2021-11-30T04:23:30.650Z] github.com/pingcap/tidb/server.(*packetIO).readPacket(0xc1200934c0, 0x44366a0, 0xc0000520a8, 0x0, 0x0, 0x0)
[2021-11-30T04:23:30.650Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/server/packetio.go:113 +0x37f
[2021-11-30T04:23:30.650Z] github.com/pingcap/tidb/server.(*clientConn).readPacket(...)
[2021-11-30T04:23:30.650Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/server/conn.go:394
[2021-11-30T04:23:30.650Z] github.com/pingcap/tidb/server.(*clientConn).authSwitchRequest(0xc01162f6e0, 0x44366a0, 0xc0000520a8, 0xc11f3c51b9, 0x15, 0x2, 0x8, 0xc120a6b470, 0x27, 0xc01162f008)
[2021-11-30T04:23:30.650Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/server/conn.go:236 +0x806
[2021-11-30T04:23:30.650Z] github.com/pingcap/tidb/server.(*clientConn).checkAuthPlugin(0xc01162f6e0, 0x44366a0, 0xc0000520a8, 0xc01162f418, 0x7f950c6f5db8, 0x7f950c6f5db8, 0x1000, 0x1, 0xc01162f148)
[2021-11-30T04:23:30.650Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/server/conn.go:902 +0x726
[2021-11-30T04:23:30.650Z] github.com/pingcap/tidb/server.(*clientConn).handleAuthPlugin(0xc01162f6e0, 0x44366a0, 0xc0000520a8, 0xc01162f418, 0x0, 0x0)
[2021-11-30T04:23:30.650Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/server/conn.go:715 +0x8c
[2021-11-30T04:23:30.650Z] github.com/pingcap/tidb/server.TestHandleAuthPlugin(0xc000603980)
[2021-11-30T04:23:30.650Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/server/conn_test.go:1072 +0x1ef2
[2021-11-30T04:23:30.650Z] testing.tRunner(0xc000603980, 0x3fe78c8)
[2021-11-30T04:23:30.650Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef
[2021-11-30T04:23:30.650Z] created by testing.(*T).Run
[2021-11-30T04:23:30.650Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-11-30T04:23:30.650Z] FAIL	github.com/pingcap/tidb/server	25.665s
```
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/49084/pipeline
@zgcbj please check the CI error

**Comment by zgcbj** [comment]
@fzhedu  There are only 989 lines in conn_test.go in this pr，but ci shows fault in line 1161, where can i find latest code relatate to this error.

**Comment by djshow832** [comment]
This is caused by https://github.com/pingcap/tidb/pull/29738 which added more tests. /cc @dveeden

**Pull request merged**
