### PR TITLE
lightning: fix gcs max key limit

### LINKED ISSUE #30377: WalkDir of gcs only iterate at most 1000 keys
## Bug Report
ref

https://github.com/pingcap/tidb/blob/891517f23ec3443d971423d30d54feaa08fb51b3/br/pkg/storage/gcs.go#L183-L197

note `maxKeys` is 1000, and we will end the loop after iterate `maxKeys` keys
### 1. Minimal reproduce step (Required)
import data more than 1000 keys/files

### 2. What did you expect to see? (Required)
import all data under directory.
### 3. What did you see instead (Required)
only scan at most 1000 files

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #30377 

Problem Summary: `opt.ListCount` is the number of keys fetched each time for s3, instead of the limitation.

### What is changed and how it works?

ignore `opt.ListCount` in gcs and directly walk all the keys.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by july2993 — COMMENTED** [review]
consider setting page size(using `maxKeys`) explicitly?
I do not know what is the default value of pageSize internally of the iterator if using the iter directly and how is the performant affect.
ref https://github.com/googleapis/google-cloud-go/wiki/Iterator-Guidelines

**Comment by 3pointer** [comment]
> consider setting page size(using `maxKeys`) explicitly?
> I do not know what is the default value of pageSize internally of the iterator if using the iter directly and how is the performant affect.
> ref https://github.com/googleapis/google-cloud-go/wiki/Iterator-Guidelines

I agree. I think if not use pageInfo will introduce OOM issue when walk on millions objects.

**Comment by july2993** [comment]
> > consider setting page size(using `maxKeys`) explicitly?
> > I do not know what is the default value of pageSize internally of the iterator if using the iter directly and how is the performant affect.
> > ref https://github.com/googleapis/google-cloud-go/wiki/Iterator-Guidelines
> 
> I agree. I think if not use pageInfo will introduce some other issue when walk on millions objects.

Do you mean it will fetch all keys in one request for the current code? I don't think it will do it in this way, I guess there must be some default `pageSize` internally, and sometimes you call the `Next()` of iterator, it may trigger it to fire a new request to fetch more keys. 

I think setting a relatively large page size here will be quicker to fetch all keys here, and also respect  `opt.ListCount`.

**Review by glorv — APPROVED** [review]

**Comment by 3pointer** [comment]
> > > consider setting page size(using `maxKeys`) explicitly?
> > > I do not know what is the default value of pageSize internally of the iterator if using the iter directly and how is the performant affect.
> > > ref https://github.com/googleapis/google-cloud-go/wiki/Iterator-Guidelines
> > 
> > 
> > I agree. I think if not use pageInfo will introduce some other issue when walk on millions objects.
> 
> Do you mean it will fetch all keys in one request for the current code? I don't think it will do it in this way, I guess there must be some default `pageSize` internally, and sometimes you call the `Next()` of iterator, it may trigger it to fire a new request to fetch more keys.
> 
> I think setting a relatively large page size here will be quicker to fetch all keys here, and also respect `opt.ListCount`.

According to https://sourcegraph.com/github.com/googleapis/google-api-go-client/-/docs/storage/v1#ObjectsListCall.MaxResults. the page size is always less than 1000. so the default value is enough?
@july2993

**Review by july2993 — APPROVED** [review]

**Review by kennytm — APPROVED** [review]

**Pull request merged**
