### PR TITLE
util/stmtsummary: migrate test-infra to testify

### LINKED ISSUE #26420: migrate test-infra to testify for `util/stmtsummary` pkg

### PR DESCRIPTION
**Pull request by feitian124**
### What problem does this PR solve?

Issue Number: close #26420 

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by feitian124** [comment]
/cc @tisonkun
hi, please help review, thanks

**Comment by tisonkun** [comment]
@feitian124 thanks for your contribution @feitian124 ! I'll review this PR tomoroow.

**Comment by feitian124** [comment]
@tisonkun ok, thanks

**Review by tisonkun — COMMENTED** [review]
Can you separate `statement_summary_test.go` changes into another PR? This PR is too large to review.

**Comment by feitian124** [comment]
sorry, it is large and take me some time to finish...
but i am not sure how to separate them to 2 pr as they solve 1 issue， and if put them in 2 different branch the unit test will fail without aditional work.

i did reorder my commit and pushed to a new branch https://github.com/feitian124/tidb/commits/issue-26420-new,
so `statement_summary_test.go` is in an separate commit.

```diff
commit f01914e8ecf743b3a22edf81a49ed25eb9ac6c7d (HEAD -> issue-26420-new, my/issue-26420-new, issue-26420-part1)
Author: feitian124 <feitian124@gmail.com>
Date:   Tue Aug 3 13:32:11 2021 +0800

    util/stmtsummary: migrate test-infra to testify, part 2

 util/stmtsummary/evicted_test.go   | 143 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------------------------
 util/stmtsummary/main_test.go      |  26 ++++++++++++++++++++++++++
 util/stmtsummary/variables_test.go |  98 +++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------
 3 files changed, 151 insertions(+), 116 deletions(-)

commit 68a3829fefe77aa229af61963710366bfe452120
Author: feitian124 <feitian124@gmail.com>
Date:   Tue Aug 3 13:32:00 2021 +0800

    util/stmtsummary: migrate test-infra to testify, part 1

 util/stmtsummary/statement_summary_test.go | 615 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------------------------------------------------
 1 file changed, 311 insertions(+), 304 deletions(-)
```
not sure if this help. 
if this is what you want, i can create a new pr based on `issue-26420-new` and close this pr.
if this is not what you want, please give some guide.
thanks.

**Comment by tisonkun** [comment]
@feitian124 you can take a look at how we do it for domain pkg https://github.com/pingcap/tidb/issues/26306, or if you separate in multiple commits in one PR said this one, it is fine also.

**Comment by tisonkun** [comment]
Here is an example how to break diff into meaningful commits that helps on reviewing. https://github.com/apache/flink/pull/9832/commits

**Comment by feitian124** [comment]
> @feitian124 you can take a look at how we do it for domain pkg #26306, or if you separate in multiple commits in one PR said this one, it is fine also.

hi @tisonkun , i have separate them to 3 pr, hopefully can make your review easier.

**Pull request closed without merging**
