### PR TITLE
expression: fix cast real, decimal to time

### LINKED ISSUE #23993: Different behavior of error handling in CAST expression between TiDB and TiKV coprocessor
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```SQL
create table t (a double);
insert into t values(-790822912);

select a from t where cast(a as time);
# Push CAST down to TiKV, return -790822912

# Disable cast push down
insert into mysql.expr_pushdown_blacklist set name = 'cast';
admin reload expr_pushdown_blacklist;

select a from t where cast(a as time);
# Calculate CAST in TiDB, get error "Truncated incorrect time value: '-790822912'"
```

### 2. What did you expect to see? (Required)
Consistent behavior.

MySQL's behavior is consistent with TiKV coprocessor, that is return warning.

### 3. What did you see instead (Required)
Inconsistent behavior.

### 4. What is your TiDB version? (Required)

```
+-------------------------------------------------------------------+
| tidb_version()                                                    |
|-------------------------------------------------------------------|
| Release Version: v4.0.0-beta.2-2592-g2f877e803-dirty              |
| Edition: Community                                                |
| Git Commit Hash: 2f877e80301ded17ed73e23f93a0eaf8a315899c         |
| Git Branch: master                                                |
| UTC Build Time: 2021-04-09 16:22:38                               |
| GoVersion: go1.13                                                 |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Issue Number: close #23993

Problem Summary:

cast from real to time will raise error.

### What is changed and how it works?

What's Changed:

`builtinCastRealAsDurationSig.vecEvalDuration` logic is not same as `builtinCastRealAsDurationSig.evalDuration`. And copr push down will use `builtinCastRealAsDurationSig.evalDuration`, but if disable push down TiDB will use `builtinCastRealAsDurationSig.vecEvalDuration` that's why the result is different.

This PR will fix the logic difference between `vecEvalDuration` and `evalDuration`. And in MySQL if a real number cast to Time will cause `ErrTruncatedWrongVal` it will return NULL instead. This PR also fixes that.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

- No

### Release note 

- Fix cast real number to Time truncated bug.

### CODE REVIEW

**Comment by blacktear23** [comment]
@wjhuang2016 PTAL

**Comment by blacktear23** [comment]
@wjhuang2016 PTAL

**Review by wjhuang2016 — APPROVED** [review]
LGTM, It seems that we need to modify the TiKV part.

**Comment by blacktear23** [comment]
> LGTM, It seems that we need to modify the TiKV part.

@wjhuang2016 yes cast to time at TiKV side also has bug.

**Review by lzmhhh123 — APPROVED** [review]

**Comment by blacktear23** [comment]
@wjhuang2016 @lzmhhh123 we should merge this PR first, then TiKV's test can be passed.

**Pull request merged**
