### PR TITLE
ddl: args v2 for create table/view/sequence, batch create table

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: ref #53930 

Problem Summary:

### What changed and how does it work?
- args v2 for create table/view/sequence, and batch create table
- add JobArgs into JobWrapper, so we can use it directly at job_submitter/executor part, in this PR i only changed new added ones, will change existing job args later
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by D3Hunter** [comment]
ping @lance6716

**Review by tangenta — APPROVED** [review]

**Review by joccau — APPROVED** [review]
LGTM

**Pull request merged**
