### PR TITLE
test: correct TiDB-style executable comment version for auto_random

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve? 
Since the `auto_random` feature needs to be backported to TiDB release-3.1, the comment version number should be `30100` instead of `40000`.

### What is changed and how it works?
Update parser dependency pingcap/parser#748.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

Release note

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM

**Comment by tiancaiamao** [comment]
I've approved the parse PR, please update this one when it's merged. @tangenta

**Comment by tangenta** [comment]
The CI problem seems to be related to #13728.

**Comment by tiancaiamao** [comment]
Parse is wrong or test case is wrong? @tangenta

```
[2020-02-27T07:13:15.956Z] 2020/02/27 15:13:15.849  [fatal] run test [ps] err: sql:PREPARE stmt1 FROM "select _utf8 'A' collate utf8_bin = ?";: run "PREPARE stmt1 FROM "select _utf8 'A' collate utf8_bin = ?";" at line 59 err Error 1105: UnknownType: *ast.SetCollationExpr
```

**Comment by tangenta** [comment]
> Parse is wrong or test case is wrong? @tangenta
> 
> ```
> [2020-02-27T07:13:15.956Z] 2020/02/27 15:13:15.849  [fatal] run test [ps] err: sql:PREPARE stmt1 FROM "select _utf8 'A' collate utf8_bin = ?";: run "PREPARE stmt1 FROM "select _utf8 'A' collate utf8_bin = ?";" at line 59 err Error 1105: UnknownType: *ast.SetCollationExpr
> ```

This is because the updated parser contains the changes in pingcap/parser#749. After #14959 being merged, the problem should be solved.

**Pull request merged**
