### PR TITLE
add pull request template

### PR DESCRIPTION
**Pull request by zz-jason**
## What is your change? (mandatory)

add pull request template

## Why this change is made? (optional)
Improve the quality of the pull request's description

### CODE REVIEW

**Comment by zz-jason** [comment]
@shenli @coocood PTAL

**Comment by ngaut** [comment]
PTAL @queenypingcap

**Comment by shenli** [comment]
@siddontang Please pay attention to this PR.

**Comment by queenypingcap** [comment]
How about some minor changes? 
******************************************************
Thank you for working on TiDB! 

## What have you changed? (mandatory)

Please explain **in detail** what the changes are in this PR and why they are needed.

- Summarize your change (mandatory)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

Please NOTE that:

- Do not assume the code is self-evident
- Do not assume reviewers understand the original issue

## What are the type of the changes (mandatory)?

Please check the box (by putting an `x` inside the brackets) for this PR:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this PR been tested (mandatory)?
Please describe the tests that you ran to verify your changes. Have you finished unit tests, integration tests, or manual tests?

## Does this PR affect documentation (docs/docs-cn) update? (optional)

If there is document change, please file a PR and add the PR number here.

## Refer to a related PR or issue link (optional)

## Benchmark result if necessary (optional)

## Add a few positive/negative examples (optional)


Please read TiDB's [CONTRIBUTING](https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md) document **before** filing this PR.

**Comment by queenypingcap** [comment]
LGTM.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
