### PR TITLE
executor: Speed up unit tests

### PR DESCRIPTION
**Pull request by qrr1995**
### What problem does this PR solve? 
Speed up executor unit test .

### What is changed and how it works?
Change the suite distribution of slow tests.
See the statistic report:
image
Most testSuites ended in 30 seconds.
Some testSuites are too large such as `testSuite3` and `testSuite4` in y-axis, since the tests in one testSuite run parallelly.
It's ok to move some tests from "Slow Suite" to "Quick Suite"

### CODE REVIEW

**Comment by qrr1995** [comment]
As a result:
before:
```
ok  	github.com/pingcap/tidb/executor	106.273s
```
after:
```
ok      github.com/pingcap/tidb/executor    88.846s
```
The new picture looks better
image

**Comment by qrr1995** [comment]
PTAL @SunRunAway @bb7133

**Comment by ngaut** [comment]
Cool, How did you get the image? Is there any tools can generate it?

**Comment by qrr1995** [comment]
1.  I've craweled the log from Jenkins website which is  all we need.
2. Then convert the `go test` log  into csv with **pandas**  in Python.
3. Plot them with [Pcolor](https://matplotlib.org/3.1.1/gallery/images_contours_and_fields/pcolor_demo.html)  
Step 2 is the most annoying which relys on some data statistic tricks, but works for all kinds of unit test.

@ngaut

**Pull request merged**
