### PR TITLE
test: fix random "IsolationRead" fails

### LINKED ISSUE #14579: test: random "IsolationRead" fails in testAnalyzeSuite.TestIndexRead
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
[2020-01-28T06:41:04.848Z] FAIL: cbo_test.go:236: testAnalyzeSuite.TestIndexRead
[2020-01-28T06:41:04.848Z] 
[2020-01-28T06:41:04.848Z] cbo_test.go:276:
[2020-01-28T06:41:04.848Z]     c.Assert(err, IsNil)
[2020-01-28T06:41:04.848Z] ... value *errors.withStack = [planner:1815]Internal : Can not find access path matching 'tidb_isolation_read_engines'(value: '[tiflash]') and tidb-server config isolation-read(engines: 'tikv,tiflash,tidb'). Available values are 'tikv'. ("[planner:1815]Internal : Can not find access path matching 'tidb_isolation_read_engines'(value: '[tiflash]') and tidb-server config isolation-read(engines: 'tikv,tiflash,tidb'). Available values are 'tikv'.")
```

The error is shown in https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/22700/pipeline/

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve? 
fix #14579 

### What is changed and how it works?
The server-level config of isolation read affects all tests for different test suites. So I make the `testIntegrationSuite` unparallel.

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by zz-jason** [comment]
Would it increase the CI time to longer than 3 minutes?

**Comment by lzmhhh123** [comment]
> Would it increase the CI time to longer than 3 minutes?

I think it just increases a little time. Most of the tests in `testIntegrationSuite` are like `explain select ...`.

**Comment by zz-jason** [comment]
> > Would it increase the CI time to longer than 3 minutes?
> 
> I think it just increases a little time. Most of the tests in `testIntegrationSuite` are like `explain select ...`.

OK

**Pull request merged**
