### PR TITLE
statistics: fix the fomula for checking outdated stats (#26728)

### LINKED ISSUE #26282: Update the formula about judging stale statistics
## Enhancement
Update the formula to `ModifyCnt / LastAnalyzeCnt`.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #26728 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/26735
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/26735:release-5.1-4eeff54d85c6
```

---

### What problem does this PR solve?

Issue Number: close #26282 

### What is changed and how it works?

Currently, we use `(modify count/realtime row count)` to check if the stats are outdated. But the reasonable method to calculate the ratio should be `(modify count/row count when last analyze)`.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by time-and-fate** [comment]
This PR needs to be merged after https://github.com/pingcap/tidb/pull/26708.

**Review by qw4990 — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]

**Pull request merged**
