### PR TITLE
br: add error handling for group context cancel when restore file is corrupted

### LINKED ISSUE #30135: br restore hang, the dataset is backup with stats
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

restore same dataset as #29033, restore a 60GB backup with 2820 tables, --ignore-stats=false

### 2. What did you expect to see? (Required)
finished in half hour

### 3. What did you see instead (Required)
hang at 75.52% after 10 hours

### 4. What is your TiDB version? (Required)

`component br version v5.4.0-nightly-20211117 is already installed`
tidb v5.3.0

### PR DESCRIPTION
**Pull request by fengou1**
### What problem does this PR solve?

Issue Number: close #30135

Problem Summary:
When file is corrupted or some exception happened during restore file, the sync wait will block the entire restore process.
### What is changed and how it works?
Add context cancel handle, once the cancel happen, never do the sync wait
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. backup some data
2. in backup sst files, replace something within the sst file
3. do restore, observe if stuck happened.
4. issue can reproduce in MinIO data (s3://brie/cc-800G) and it verified this solution can resolved issue.
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]

**Comment by kennytm** [comment]
/run-check_dev_2

```
[2021-12-17T08:16:52.459Z] FAIL: pessimistic_test.go:1150: testPessimisticSuite.TestPessimisticLockNonExistsKey

[2021-12-17T08:16:52.459Z] 

[2021-12-17T08:16:52.459Z] pessimistic_test.go:1169:

[2021-12-17T08:16:52.459Z]     c.Check(storeerr.ErrLockAcquireFailAndNoWaitSet.Equal(err), IsTrue)

[2021-12-17T08:16:52.459Z] ... obtained bool = false

[2021-12-17T08:16:52.459Z] 

[2021-12-17T08:16:52.459Z] pessimistic_test.go:1171:

[2021-12-17T08:16:52.459Z]     c.Check(storeerr.ErrLockAcquireFailAndNoWaitSet.Equal(err), IsTrue)

[2021-12-17T08:16:52.459Z] ... obtained bool = false

[2021-12-17T08:16:52.459Z] 

[2021-12-17T08:16:52.459Z] pessimistic_test.go:1183:

[2021-12-17T08:16:52.459Z]     c.Check(storeerr.ErrLockAcquireFailAndNoWaitSet.Equal(err), IsTrue)

[2021-12-17T08:16:52.459Z] ... obtained bool = false

[2021-12-17T08:16:52.459Z] 

[2021-12-17T08:16:52.459Z] pessimistic_test.go:1185:

[2021-12-17T08:16:52.459Z]     c.Check(storeerr.ErrLockAcquireFailAndNoWaitSet.Equal(err), IsTrue)

[2021-12-17T08:16:52.459Z] ... obtained bool = false
```

**Review by kennytm — APPROVED** [review]

**Pull request merged**
