### PR TITLE
table: check duplicate row_id in insert stmt

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Problem Summary:

In #25868 we support rebase row_id to a smaller value, so it has the chance to generate duplicate row_id

this is proposal PR to check it instead of override old value

### What is changed and how it works?

What's Changed, How it Works:

current code only check PkIsHandle and ClusteredHandle's record key, after this will check all record key

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [x] Performance regression: Consumes more CPU

- it will have regression when optimistic txn with `@@tidb_constraint_check_in_place=true`, tidb need get addition key to check duplicate
- it will have little regression for default optimistic txn and pessimistic txn, tikv always need read insert key before insert https://github.com/tikv/tikv/blob/a7d836c6178739ff9d2c027af5d239cbe4524771/src/storage/txn/actions/prewrite.rs#L338-L364 it seems no addition IO cost(except the duplicated key is rollback or lock)

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
Report duplicate error for duplicate row_id that may be generated after rebasing row_id operation
```

### CODE REVIEW

**Comment by lysu** [comment]
I'm not sure whether worth adding check for this too...- - just start a discussion 

/cc @coocood @tangenta @cfzjywxk

**Comment by cfzjywxk** [comment]
Do we have an expected product definition for the duplicate row processing now?

**Review by jackysp — APPROVED** [review]
LGTM

**Comment by tangenta** [comment]
Do we need to bench the performance regression?

**Review by tangenta — APPROVED** [review]

**Pull request merged**
