### PR TITLE
types: use `mathutil.Max/mathutil.Min` instead of `myMax/myMin`

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary: just code improve, use same `max/min` func in TiDB repo

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
lol

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
/hold

CI is too busy.

**Comment by Defined2014** [comment]
/hold

we can merge it after v6.6.0 branch create.

**Comment by tisonkun** [comment]
> /hold
> 
> we can merge it after v6.6.0 branch create.

lol

**Pull request merged**
