### PR TITLE
Revert "planner: donot prune all columns for Projection (#24024)"

### LINKED ISSUE #24149: v5.0.1-pre Inconsistent select count(1)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t1;
create table t1 (c1 int primary key, c2 int, c3 int, index c2 (c2));
select count(1) from (select count(1) from (select * from t1 where c3 = 100) k) k2;
```

### 2. What did you expect to see? (Required)

```
+----------+
| count(1) |
+----------+
| 1        |
+----------+
```

### 3. What did you see instead (Required)

```
+----------+
| count(1) |
+----------+
| 0        |
+----------+
```

### 4. What is your TiDB version? (Required)

```
 Release Version: v5.0.1
Edition: Community
Git Commit Hash: 4141f837ad4655a567119db743b7b752a95f5aa2
Git Branch: heads/refs/tags/v5.0.1
UTC Build Time: 2021-04-17 04:28:49
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false 
```

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #24149 

Problem Summary:  This PR revert [this commit](https://github.com/pingcap/tidb/pull/24093) . Because it cause case regression. The corresponding issue will be reopend, and will be fixed in next version.

### What is changed and how it works?

What's Changed: revert code

### Related changes

- Need to cherry-pick to the release branch: release-5.0 is already reveted.

### Check List 

Side effects: reopened issues will be fixed later.

### Release note 

- No release note

### CODE REVIEW

**Comment by guo-shaoge** [comment]
@lzmhhh123 @winoros PTAL
Also revert in master branch.

**Review by lzmhhh123 — APPROVED** [review]

**Review by eurekaka — APPROVED** [review]
/lgtm

**Comment by guo-shaoge** [comment]
This is a cherry pick make by bot. #24202 already finished this cherry pick.

**Pull request merged**
