### PR TITLE
expression: fix Coercibility and Collation with `json` type

### LINKED ISSUE #31320: The collation of `JSON` is inconsistent with MySQL when process with builtin func
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```mysql
create table t (a char(20), b blob(100), c binary(100), d json, e timestamp, f set('a一','b二','c三','d四'), g text, h enum('a一','b二','c三','d四') default 'c三');
insert into t values ('abcABC一二三abcABC', 'abcABC一二三abcABC', 0xe2e2, '{"abcABC一二三abcABC": "abcABC一二三abcABC"}', '2018-10-13', 1, 'abcABC一二三abcABC', 'a一');
select lpad(d, 5, 0xE4B880) from t;
select rpad(d, 5, 0xE4B880) from t;
```

### 2. What did you expect to see? (Required)

``` mysql
mysql> select lpad(d, 5, 0xE4B880) from t;
+----------------------+
| lpad(d, 5, 0xE4B880) |
+----------------------+
| {"abc                |
+----------------------+
1 row in set (0.00 sec)

mysql> select rpad(d, 5, 0xE4B880) from t;
+----------------------+
| rpad(d, 5, 0xE4B880) |
+----------------------+
| {"abc                |
+----------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

``` mysql
mysql> select lpad(d, 5, 0xE4B880) from t;
+--------------------------------------------+
| lpad(d, 5, 0xE4B880)                       |
+--------------------------------------------+
| 0x7B22616263                               |
+--------------------------------------------+
1 row in set (0.00 sec)

mysql> select rpad(d, 5, 0xE4B880) from t;
+--------------------------------------------+
| rpad(d, 5, 0xE4B880)                       |
+--------------------------------------------+
| 0x7B22616263                               |
+--------------------------------------------+
1 row in set (0.00 sec)
```

### LINKED ISSUE #31541: COERCIBILITY is wrong for `json` type
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```mysql
create table t(a json, b blob);
insert into t values ('{"a": "b"}', 0x3f);
SELECT COERCIBILITY(a), COERCIBILITY(b) from t;
```

### 2. What did you expect to see? (Required)
```mysql
mysql> SELECT COERCIBILITY(a), COERCIBILITY(b) from t;
+-----------------+-----------------+
| COERCIBILITY(a) | COERCIBILITY(b) |
+-----------------+-----------------+
|               2 |               2 |
+-----------------+-----------------+
```
### 3. What did you see instead (Required)
```mysql
mysql> SELECT COERCIBILITY(a), COERCIBILITY(b) from t;
+-----------------+-----------------+
| COERCIBILITY(a) | COERCIBILITY(b) |
+-----------------+-----------------+
|               5 |               2 |
+-----------------+-----------------+
```
### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
```mysql
mysql> SELECT tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #31541, close #31320

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix Coercibility and Repertoire with json type
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @xiongjiwei @wjhuang2016 @tangenta 
PTAL

**Review by wjhuang2016 — APPROVED** [review]

**Review by xiongjiwei — APPROVED** [review]

**Comment by Defined2014** [comment]
Seems it should fix with https://github.com/pingcap/tidb/issues/31320#issuecomment-1010599311, because the mysql-test will failed.

**Comment by bb7133** [comment]
@Defined2014 Please resolve the conflicts.

**Comment by hawkingrei** [comment]
@morgo @tangenta PTAL

**Review by tangenta — APPROVED** [review]

**Pull request merged**
