### PR TITLE
store/tikv: new config TxnScope in tikv config

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: AndreMouche

### What problem does this PR solve?
This PR create a config `TxnScope` in `tikv` config
Part of https://github.com/pingcap/tidb/issues/22513

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
@AndreMouche  I think there is consistent failure. Could you please take a look?

**Comment by hi-rustin** [comment]
/hold

Silence the bot.

**Pull request merged**
