### PR TITLE
planner: fix wrong select result when using collation

### LINKED ISSUE #18638: wrong select result when using collation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(a varchar(10) collate utf8mb4_bin, b varchar(10) collate utf8mb4_general_ci);
insert into t (a, b) values ('a', 'A');

select * from t t1, t t2 where t1.a = t2.b collate utf8mb4_general_ci;
select * from t t1 left join t t2 on t1.a = t2.b collate utf8mb4_general_ci;
```

### 2. What did you expect to see? (Required)
```sql
mysql> select * from t t1, t t2 where t1.a = t2.b collate utf8mb4_general_ci;
+------+------+------+------+
| a    | b    | a    | b    |
+------+------+------+------+
| a    | A    | a    | A    |
+------+------+------+------+
1 row in set (0.01 sec)

mysql> select * from t t1 left join t t2 on t1.a = t2.b collate utf8mb4_general_ci;
+------+------+------+------+
| a    | b    | a    | b    |
+------+------+------+------+
| a    | A    | a    | A    |
+------+------+------+------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```sql
mysql> select * from t t1, t t2 where t1.a = t2.b collate utf8mb4_general_ci;
Empty set (0.00 sec)

mysql> select * from t t1 left join t t2 on t1.a = t2.b collate utf8mb4_general_ci;
+------+------+------+------+
| a    | b    | a    | b    |
+------+------+------+------+
| a    | A    | NULL | NULL |
+------+------+------+------+
1 row in set (0.04 sec)
```

### 4. Affected version (Required)
master

### 5. Root Cause Analysis
https://github.com/pingcap/tidb/blob/df60c32286fa862de1a5e321fcaec2ff02e18e45/planner/core/rule_predicate_push_down.go#L269-L274

lose coercibility information

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close #18638 

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
- Fix an issue that collation coercibility result is incorrect when the keys of `JOIN` are with different collations.

### CODE REVIEW

**Comment by bb7133** [comment]
Hi @xiongjiwei , please add a 'Release note' in the PR description, thanks!

**Comment by xiongjiwei** [comment]
@bb7133 Hi, a release note is added.

**Comment by bb7133** [comment]
@wjhuang2016 PTAL

**Pull request merged**
