### PR TITLE
privilege: use internal session to run `SET DEFAULT ROL ALL`

### PR DESCRIPTION
**Pull request by imtbkcat**
### What problem does this PR solve?
`SET DEFAULT ROLE ALL` is using context session to run internal SQL. Error will occur if user don't have `SELECT` privilege on `mysql.default_roles`

### What is changed and how it works?

using internal session to run `SET DEFAULT ALL`

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- NONE

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Is there a test to cover this?

**Comment by imtbkcat** [comment]
@tiancaiamao test has been added.

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
