### PR TITLE
planner: optimize the performance of cost trace

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: ref #35240

Problem Summary: planner: optimize the performance of cost trace

```
Before:
BenchmarkGetPlanCost-8    425649    2843 ns/op
After:
BenchmarkGetPlanCost-8   	 2345196	       499.9 ns/op
```

### What is changed and how it works?

planner: optimize the performance of cost trace

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by fixdb — APPROVED** [review]
Nice shot.

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
