### PR TITLE
[DNM]parser: move charset/collation/list fields to parser from lexer

### PR DESCRIPTION
**Pull request by tiancaiamao**
some fields can be moved to parser from lexer, such as charset information, parsed result.

this clean up would reduce the dependency of `(*lex)` type accertion in parser.y

See https://github.com/pingcap/tidb/issues/1490

goyacc changed, so this PR should be merged first https://github.com/pingcap/goyacc/pull/2

### CODE REVIEW

**Comment by shenli** [comment]
LGTM
PTAL @coocood

**Comment by zimulala** [comment]
"type accertion in parser.y" means "type assertion in parser.y"?

**Comment by zimulala** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Pull request merged**
