### PR TITLE
types: fix the variable reallocation in the function EncodeI…

### LINKED ISSUE #17831: question about the function EncodeIndexSeekKey
## General Question

The EncodeIndexSeekKey encodes an index value to kv.key. So the length of returned `kv.Key` should be equals to the length of `t+tableID+_r+idxID+columnValues`.
But now, when initial the key, we only offer the `prefixLen+len(encodedValue)` bytes capacity for the key to use. The handle will also use 8 bytes, then the capacity of the key is not enough and the space of the key will be reallocated.
So at the beginning of the function, should we initial the variable `key` with the `RecordRowKeyLen + len(encodedValue)` capacity?
The code showed as below:
```
func EncodeIndexSeekKey(tableID int64, idxID int64, encodedValue []byte) kv.Key {
	key := make([]byte, 0, RecordRowKeyLen+len(encodedValue))
	key = appendTableIndexPrefix(key, tableID)
	key = codec.EncodeInt(key, idxID)
	key = append(key, encodedValue...)
	return key
}
```

### PR DESCRIPTION
**Pull request by markjenny**
…eekKey (#17831)

### What problem does this PR solve?

Issue Number: close #17831  

Problem Summary: The key in the function EncodeIndexSeekKey will reallocate because of the idxID encoding. Initial the `key` with the `RecordRowKeyLen+len(encodedValue)` capacity would avoid reallocating.

### What is changed and how it works?

Proposal: [question about the function EncodeIndexSeekKey](https://github.com/pingcap/tidb/issues/17831) 

What's Changed:
pre:
```
key := make([]byte, 0, prefixLen+len(encodedValue))
```
now:
```
key := make([]byte, 0, RecordRowKeyLen+len(encodedValue))
```
How it Works:
If init the `key` with `RecordRowKeyLen+len(encodedValue)`, we can avoid reallocating the space for the `key`.
### Check List 

Tests 

- Unit test(using the tablecodec_test) PASS

Side effects

- Performance regression
    - Nothing
- Breaking backward compatibility
    - Nothing

### Release note 

- When using the function EncodeIndexSeekKey, the TiDB use less memory and copy operation if the changes released. It will run faster. It's significant for the system performance.

### CODE REVIEW

**Comment by markjenny** [comment]
I am sorry to trouble you that how to solve the failed unit-test job and the blocked merging.😄

**Comment by markjenny** [comment]
@ngaut PTAL

**Comment by ngaut** [comment]
run /check_dev_2

**Comment by ngaut** [comment]
run check_dev_2

**Comment by markjenny** [comment]
run check_dev2

**Comment by markjenny** [comment]
@ngaut PTAL. There may be no link bewteen the code I modified and the failed check results.

**Pull request merged**
