### PR TITLE
use lower-case of github.com/sirupsen/logrus

### PR DESCRIPTION
**Pull request by holys**
As suggested by logrus repo:

>Seeing weird case-sensitive problems? It's in the past been possible to import Logrus as both upper- and lower-case. Due to the Go package environment, this caused issues in the community and we needed a standard. Some environments experienced problems with the upper-case variant, so the lower-case was decided. Everything using logrus will need to use the lower-case: github.com/sirupsen/logrus. Any package that isn't, should be changed.

Wormhole project uses both `tidb` and `siddontang/go-mysql`, and `tidb` uses `github.com/Sirupsen/logrus` and `go-mysql` uses `github.com/sirupsen/logrus`, which makes wormhole failed to  compile.

### CODE REVIEW

**Comment by holys** [comment]
@coocood  @tiancaiamao  PTAL

**Comment by coocood** [comment]
@holys 
The `mysqlx` vendor files will be used in the future, but as it's not used right now, they are pruned by glide.
Please add those files back.

**Comment by holys** [comment]
@coocood  PTAL again

**Comment by shenli** [comment]
@holys Please resolve the conflicts.

**Comment by holys** [comment]
@shenli  PTAL again

**Comment by coocood** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Comment by holys** [comment]
ref: https://github.com/pingcap/tidb-test/pull/428

**Comment by holys** [comment]
ref: https://github.com/pingcap/tidb-private-test/pull/2

**Pull request merged**
