### PR TITLE
ddl: fix ingest checkpoint not resumed for empty partitions

### LINKED ISSUE #44265: data index inconsistent after upgrade cluster
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a cluter with 3 tidb instance 
2. create a partition table and insert some data
3. add  index for the table 
4. during add index, upgrade  the cluster 
5. after cluster upgraded, admin check  index
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
1. after upgreade, the add index  ddl will be synced
2. admin check  index ok
### 3. What did you see instead (Required)
1. add index ddl synced but admin check index failed
```log
error="[admin:8003]table count 10000800 != index(idx1) count 4666669"
```
### 4. What is your TiDB version? (Required)
before
```sql
Release Version: v7.1.0
Edition: Community
Git Commit Hash: 2fa77070730236c65e98b3356cef83c2ca7f2754
Git Branch: heads/refs/tags/v7.1.0
UTC Build Time: 2023-05-29 05:19:30
GoVersion: go1.20.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
```
after
```sql
MySQL [(none)]> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                           |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.2.0-alpha
Edition: Community
Git Commit Hash: 3b045805a7b131a635422c9d031da3241d136aeb
Git Branch: heads/refs/tags/v7.2.0-alpha
UTC Build Time: 2023-05-30 04:15:06
```
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #44265

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by tangenta** [comment]
retest

**Pull request merged**
