### PR TITLE
extension: make `RelatedTables` work when the statement fails

### LINKED ISSUE #50988: `RelatedTables` returns nothing if the statement fails to build logical plan
## Bug Report

In our audit log implementation, it uses `RelatedTables` to get the tables list for latter filtering. However, if the statement fails to build logical plan, `return e.sc.Tables` will return nothing, makes the audit log filter fail to work.

### PR DESCRIPTION
**Pull request by CbcWestwolf**
### What problem does this PR solve?

Issue Number: close #50988

Problem Summary:

### What changed and how does it work?

If the statement fails (`err != nil` in `RelatedTables`), traverse the AST to get all table names.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix a bug for audit log that table filters don't work when status_code is 0
```

### CODE REVIEW

**Comment by CbcWestwolf** [comment]
/cc winoros tiancaiamao lcwangchao
This PR would reuse and modify `extractTableList`. PTAL

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by bb7133** [comment]
PTAL @qw4990 @winoros

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
