### PR TITLE
expression: remove `InInsertOrUpdate` in `BuildExpression`

### LINKED ISSUE #52509: generated column returns an illegal timestamp value
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
> set @@sql_mode='';
> CREATE TABLE t (a datetime, b timestamp AS (a));
> insert into t (a) values('9999-01-01');
> select * from t;
```

### 2. What did you expect to see? (Required)

MySQL 8.0:

```
mysql> set @@sql_mode='';
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE t (a datetime, b timestamp AS (a));
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t(a) values('9999-01-01');
Query OK, 1 row affected, 1 warning (0.00 sec)

mysql> select * from t;
+---------------------+---------------------+
| a                   | b                   |
+---------------------+---------------------+
| 9999-01-01 00:00:00 | 0000-00-00 00:00:00 |
+---------------------+---------------------+
1 row in set, 1 warning (0.01 sec)
```

### 3. What did you see instead (Required)

In TiDB:

```
mysql> set @@sql_mode='';
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE t (a datetime, b timestamp AS (a));
Query OK, 0 rows affected (0.11 sec)

mysql>  insert into t(a) values('9999-01-01');
Query OK, 1 row affected, 1 warning (0.01 sec)

mysql> select * from t;
+---------------------+---------------------+
| a                   | b                   |
+---------------------+---------------------+
| 9999-01-01 00:00:00 | 9999-01-01 00:00:00 |
+---------------------+---------------------+
1 row in set, 1 warning (0.00 sec)
```

The column `b` returns `9999-01-01 00:00:00` which is not an legal timestamp value.

### LINKED ISSUE #52715: Remove InsertOrUpdate in expression.BuildContext
## Enhancement

`BuildContext.InsertOrUpdate` is hard to understand, we do not know what behavior it causes. It's better to remove it.

### LINKED ISSUE #52748: alter column from date to timestamp result an invalid result.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
> create table t(a date);
> insert into t values('9999-01-01');
> set @@sql_mode='ALLOW_INVALID_DATES';
> alter table t modify a timestamp;
> select * from t;
```

### 2. What did you expect to see? (Required)

In MySQL, the alter table success with changing the invalid date value to `0000-00-00`:

```
mysql> alter table t modify a timestamp;
Query OK, 1 row affected, 1 warning (0.02 sec)
Records: 1  Duplicates: 0  Warnings: 1

mysql> select * from t;
+---------------------+
| a                   |
+---------------------+
| 0000-00-00 00:00:00 |
+---------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

alter table success, but select table will always fail

```
> alter table t modify a timestamp;
Query OK, 0 rows affected
Time: 0.414s
> select * from t;
(1292, "Incorrect datetime value: '9999-01-01 00:00:00'")
```

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #52715, close #52509, close #52748

Problem Summary:

The function `table.castColumnValue` requires an argument `insertOrUpdate` to indicate whether it is called in an insert or update statement. However, I found this may be a mistake.

If we define the semantic of `CastColumnValue` as "cast a value to another to fit the column to meet the column's restriction", it is not reasonable that the select and insert statements have different behaviors. You can see the issue #52509 that there is a problem if we do not handle the datetime conversion error for a select statement.

A similar issue also exists in the alter statement, see #52748. You can see that if we do not handle the datetime error there, the table will store a wrong timestamp value.

I think it's better to remove `insertOrUpdate` argument in `castColumnValue` and it is what this PR does. All unit tests passed but caused some error message changes in DDL. But I think the changed messages are more reasonable because the type name in it is more accurate.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by YangKeao — APPROVED** [review]
LGTM :+1:

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
