### PR TITLE
infoschema, domain, ddl: fix upper cased charset names (#10272)

### PR DESCRIPTION
**Pull request by bb7133**
Cherry-pick https://github.com/pingcap/tidb/pull/10272

### CODE REVIEW

**Comment by bb7133** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by bb7133** [comment]
/run-mybatis-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
