### PR TITLE
*: stale reads compatible with prepare (#25156)

### LINKED ISSUE #24932: Make AsOf compatible with Prepare
## Background
AsOf mainly used in the stale read scenes. details in https://github.com/pingcap/tidb/issues/21094. we need to let it compatible with Prepare. 

As Prepare will cache the `Plan` and also cache the `schema version`.  we may use the As Of such as :
```
"PREPARE mystmt SELECT * FROM table t AS OF TIMESTAMP NOW() - 2 SECOND where id=?";
```
If the schema is changed we should rebuild the prepare object in the cache.
## Details Implement
Currently, the prepare process already has the check schema version step:
https://github.com/pingcap/tidb/blob/e87d0359373f261d50106a29f0a9dd3d8de46214/planner/core/common_plans.go#L258-L273

We need to use the schema in the paste (define in the as of) to compare, do not use the latest schema. we may need to cache the as of Expr, then calculate the snapshots and the relative schema.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25156 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25371
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25371:release-5.1-9189ec66ac47
```

---

### What problem does this PR solve?

Issue Number: close #24932

Problem Summary: Prepare is now compatible with stale reads.

### What is changed and how it works?

What's Changed:

`snapshotTS != 0` is used to indicate that it is a stale read.

1. `CachedPrepareStmt` has a new field `SnapshotTS` to store the result of preprocessing in `PrepareExec`.
2. `newExecutorBuilder` has a new parameter, `snapshotTS`. It is passed from `session.ExecutePreparedStmt`, along `cachedPlanExec` or `CompileExecutePreparedStmt`. The one in session comes from `CachedPrepareStmt`.
3. Skip infoschema check in `IsCachedExecOk` and `OptimizePreparedPlan`, if `snapshotTS != 0`.
4. `plannercore.Execute` plan has a new field `SnapshotTS` to store the timestamp from `CachedPrepareStmt`.
5. `executorExec.buildExecute` will assign `snapshotTS` from `plannercore.Execute` plan to `executorBuilder`.

1-3 covered the prepared execution directly from session/mysql-protocol, and 4-5 covered the execution from plain SQL.

*NEW CHANGES*: to support dynamic timestamp like `NOW() - INTERVAL 1 SECOND`:

1. `CachedPrepareStmt` do not store infoschema anymore. You need to recheck infoschema before execute to ensure consistency anyway.
2. `As Of` statements evaluation is stored/prepared as a closure to support dynamic re-evaluation. For non-prepare statements, they can use `LastSnapshotTS` to avoid re-evaluation.

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

### Release note 

- Support prepare stale reads SQL

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Review by nolouch — APPROVED** [review]

**Comment by nolouch** [comment]
@Yisaer needs one more approval.

**Review by Yisaer — APPROVED** [review]
lgtm

**Pull request merged**
