### PR TITLE
compact restore: use closure to initial snapshot restore checkpoint

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve?

Issue Number:  close https://github.com/pingcap/tidb/issues/58237

Problem Summary:
The previous of checkpoint runner initial logic has a bug. which makes the snapshot checkpoint cannot proper be used.
This PR try to fix it and enhance the test case.

### What changed and how does it work?
Use a closure to make sure the restorer has the correct checkpoint logic.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]

**Comment by 3pointer** [comment]
/test unit-test

[31m[1mFAILED: [0m//pkg/executor/test/issuetest:issuetest_test (Summary)

**Pull request merged**
