### PR TITLE
Add create view support

### PR DESCRIPTION
**Pull request by AndrewDi**
### What problem does this PR solve? 
Implement view support, support following grammar:  
1. create or replace view as SelectStmt ...
2. drop table ...
3. show full tables
4. show create table viewname
5. select from view

issue ref [https://github.com/pingcap/tidb/issues/7974](https://github.com/pingcap/tidb/issues/7974)
Part of the code reference from [https://github.com/pingcap/tidb/pull/4874](https://github.com/pingcap/tidb/pull/4874)

### What is changed and how it works?
Use tableinfo to store view select statement

### Check List 

Tests 

 - Unit test

Code changes

 - Has interface methods change
Add CreateView interface to ddl/ddl.go
 - Has persistent data change

Side effects

Related changes

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8001)

### CODE REVIEW

**Comment by ngaut** [comment]
Well done.

**Comment by AndrewDi** [comment]
Do some commit clean...

**Comment by XuHuaiyu** [comment]
@AndrewDi will file a proposal for the details of supporting View these days.

**Comment by AndrewDi** [comment]
I will implement this feature with independent PRs.

**Comment by morgo** [comment]
How is the SQL mode handled with views - I assume it is dependent on the session executing the view?

(The MySQL compatible behavior is to capture the SQL mode when the view is created.)

**Comment by XuHuaiyu** [comment]
@morgo 
Yes, we need to take SQL_MODE into consideration.

A minor case of view in MySQL, it seems that everything is frozen after CREATE_VIEW:
``` sql
mysql> create view v as select "a" from t;
Query OK, 0 rows affected (0.03 sec)

mysql> select "a" from t;
+---+
| a |
+---+
| a |
+---+
1 row in set (0.00 sec)

mysql> select * from v;
+---+
| a |
+---+
| a |
+---+
1 row in set (0.00 sec)

mysql> set @@sql_mode='ANSI_QUOTES';                                                Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> select "a" from t
    -> ;
+------+
| a    |
+------+
| NULL |
+------+
1 row in set (0.00 sec)

mysql> select * from v;
+---+
| a |
+---+
| a |
+---+
1 row in set (0.00 sec)
```

**Comment by XuHuaiyu** [comment]
@morgo 
We decided to implement the most basic features of view in TiDB,
as the task with P1 priority mentioned in this proposal https://github.com/pingcap/tidb/pull/8416.

SQL_MODE in view may be listed as a P2 priority task.

**Pull request closed without merging**
