### PR TITLE
server: change the compatibility of tidb_sm3_password

### PR DESCRIPTION
**Pull request by CbcWestwolf**
### What problem does this PR solve?

Issue Number: ref #36192

Problem Summary:

In https://github.com/pingcap/tidb/pull/36193, for compatibility, we change the authentication plugin to `caching_sha2_password` in the handshake. This would be a inconvenience if in the future, we enhance the `caching_sha2_password` or `tidb_sm3_password` by introducing more ways of handshake.

### What is changed and how it works?

Use `tidb_sm3_password` to handshake.

### Check List

Tests 

- [x] Unit test (existent UT)
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by CbcWestwolf** [comment]
/cc bb7133 dveeden 

PTAL.

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by xiongjiwei — APPROVED** [review]

**Comment by hawkingrei** [comment]
@CbcWestwolf Please fix the unit test.

**Pull request merged**
