### PR TITLE
session: rollback the transaction on Compile error

### PR DESCRIPTION
**Pull request by coocood**
We should rollback the transaction on error to make sure the next statement starts a new transaction with the latest InfoSchema.
This is handled in `executeStatement` but not in `Compile` and `Parse`.

### CODE REVIEW

**Comment by coocood** [comment]
@shenli @winkyao @zz-jason PTAL

**Comment by zimulala** [comment]
Could we deal with this issue in a unified way? If you do not have a description, we do not know that it handles in `executeStatement`.

**Comment by coocood** [comment]
@zimulala 
That changes too much, it requires a refactor.

**Comment by shenli** [comment]
Could we renew the infoschema handle when meet error?

**Comment by coocood** [comment]
@shenli 
Rollback is the simplest way to renew the infoschema handle.
And we also need to renew the transaction TS. If the user execute a statement 10 minutes later, he doesn't want the start TS to be 10 minitues ago.

**Comment by jackysp** [comment]
LGTM

**Pull request merged**
