### PR TITLE
metrics: replace histogram with counter for packet IO

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve?

Issue Number: ref #32075 

Problem Summary:

### What is changed and how it works?
As stated in the title and the related issue.

### Check List

Tests 

- [x] Manual test (add detailed scripts or steps below)
The metrics shown in Grafana are the same as the previous one: verified by a local env with `tiup playground`:

image

Side effects

- [x] Performance improvement: Consumes less CPU

Documentation

- NA

### Release note

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by bb7133** [comment]
PTAL @jackysp

**Review by jackysp — APPROVED** [review]
LGTM

**Pull request merged**
