### PR TITLE
ddl: fix column type change won't cast the default value to new one

### LINKED ISSUE #24971: After executing `add column`, conversion `blob` to `int` is inconsistent with MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set global tidb_enable_change_column_type = 1;

drop table tbl_1;
create table tbl_1 (col int);
insert into tbl_1 values (9790);
alter table tbl_1 add column col1 blob(6) collate binary not null;

select * from tbl_1;
alter table tbl_1 change column col1 col2 int;
select * from tbl_1;
```

### 2. What did you expect to see? (Required)
```
mysql> select * from tbl_1;
+------+------+
| col  | col1 |
+------+------+
| 9790 |      |
+------+------+
1 row in set (0.00 sec)

mysql> alter table tbl_1 change column col1 col2 int;
ERROR 1366 (HY000): Incorrect integer value: '' for column 'col2' at row 1

mysql> select * from tbl_1;
+------+------+
| col  | col1 |
+------+------+
| 9790 |      |
+------+------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)
```
tidb> select * from tbl_1;
+------+------+
| col  | col1 |
+------+------+
| 9790 |      |
+------+------+
1 row in set (0.00 sec)

tidb> alter table tbl_1 change column col1 col2 int;
select * from tbl_1;
Query OK, 0 rows affected (2.52 sec)

tidb> select * from tbl_1;
+------+------+
| col  | col2 |
+------+------+
| 9790 | NULL |
+------+------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
 Release Version: v4.0.0-beta.2-2957-g4000975ad
Edition: Community
Git Commit Hash: 4000975ad1785fbc4c0e5175407e8486c0cef763
Git Branch: master
```

### PR DESCRIPTION
**Pull request by AilinKid**
Signed-off-by: AilinKid <314806019@qq.com>

### What problem does this PR solve?

Issue Number: close #24971, #24973, #24971

### What is changed and how it works?

Add the decoded default datum into the rowMap since the CTC will fetch the target datum from the decoder.rowMap

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- ddl: fix column type change won't cast the default value to new one

### CODE REVIEW

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by zimulala** [comment]
PTAL @tangenta

**Review by tangenta — APPROVED** [review]

**Pull request merged**
