### PR TITLE
types: improve test coverage in types/json

### PR DESCRIPTION
**Pull request by xiekeyi98**
### What problem does this PR solve? 

Improve test coverage

### What is changed and how it works?

Add more test functions.

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by zz-jason** [comment]
LGTM

**Comment by xiekeyi98** [comment]
```
xiekeyi@ubuntu:~/gopath/src/github.com/pingcap/tidb/types/json$ go test -cover
OK: 12 passed
PASS
coverage: 81.4% of statements
ok  	github.com/pingcap/tidb/types/json	0.009s
xiekeyi@ubuntu:~/gopath/src/github.com/pingcap/tidb/types/json$ git checkout testCoverInType 
切换到分支 'testCoverInType'
您的分支与上游分支 'origin/testCoverInType' 一致。
xiekeyi@ubuntu:~/gopath/src/github.com/pingcap/tidb/types/json$ go test -cover
OK: 17 passed
PASS
coverage: 84.7% of statements
ok  	github.com/pingcap/tidb/types/json	0.026s
```

This PR make the test coverage in types/json up 3%.

I will continue to work in this next work.

**Pull request merged**
