### PR TITLE
build(deps): update client-go to fit witness

### LINKED ISSUE #40437: fit witness
## Enhancement
Update client-go https://github.com/tikv/client-go/pull/633 to fit witness

### PR DESCRIPTION
**Pull request by ethercflow**
ref tikv/tikv#12876

Signed-off-by: Wenbo Zhang <ethercflow@gmail.com>

### What problem does this PR solve?

Issue Number: close #40437 

Problem Summary: build(deps): update client-go to fit witness

### What is changed and how it works?

Update go.mod 

### Check List

Tests 

- [x] Manual test (add detailed scripts or steps below)
       - sysbench prepare

Side effects

- None

Documentation

- None

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by ethercflow** [comment]
@sticnarf PTAL, thanks!

**Review by sticnarf — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by ethercflow** [comment]
Hi @hawkingrei All tests passed now, would you please help me to merge it? Thanks!

**Comment by hawkingrei** [comment]
image
@ethercflow I think someone has helped you upgrade it.

**Pull request closed without merging**
