### PR TITLE
ddl: fix unstable test TestCreateDropCreateTable

### LINKED ISSUE #50061: flaky test `TestCreateDropCreateTable`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
--- FAIL: TestCreateDropCreateTable (5.46s)
    ddl_api_test.go:214: 
        	Error Trace:	/home/prow/go/src/github.com/pingcap/tidb/pkg/ddl/ddl_api_test.go:214
        	Error:      	"446773575105380352" is not less than "446773574582665216"
        	Test:       	TestCreateDropCreateTable
        	Messages:   	second create should finish after drop
```

https://prow.tidb.net/view/gs/prow-tidb-logs/logs/periodic-daily-tidb-unit-test/1742606910567223296

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #50061

Problem Summary:

There is a gap between `runningJobs.remove()` and next `runningJobs.add()`. If `getJob()` is invoked during this gap, DDL worker may execute the second `create table` job first.

### What changed and how does it work?

This PR distinguishes the concept between "processing" jobs and "unfinished" jobs:

- Processing jobs: activatly running by a DDL worker.
- Unfinished jobs: the jobs whose state is NOT `synced`, `done`, or `rollback done`.

For `checkRunnable()`, we should use "unfinished jobs" to determine the dependency.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by tangenta** [comment]
@wuhuizuo I need to trigger CI to reproduce the issue.

**Review by wjhuang2016 — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
