### PR TITLE
util: add GoVersion info for tidb_version

### PR DESCRIPTION
**Pull request by XuHuaiyu**
add build platform for tidb_version
PTAL @shenli @coocood

### CODE REVIEW

**Comment by jackysp** [comment]
tidb-server -V has already show Go version with build platform. I think this modification is not necessary.

```
Release Version: v1.1.0-alpha.1-91-geaef520
Git Commit Hash: eaef52063422a84e0640b37b940b02f3b6239734
Git Commit Branch: master
UTC Build Time:  2018-02-08 07:58:39
GoVersion:  go version go1.9.2 linux/amd64
```

**Comment by XuHuaiyu** [comment]
I added go version into tidb_version. 
PTAL @jackysp @coocood

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
