### PR TITLE
[WIP] add foreign key constraints to SHOW CREATE TABLE

### PR DESCRIPTION
**Pull request by gregwebs**
### What problem does this PR solve? 

#8349 
We need to wait for other changes to foreign key checks that will help make this backwards compatible.

### Check List 

Tests 

 - [ ] Unit test
 - [ ] Integration test
 - [ ] Manual test (add detailed scripts or steps below)

Code changes

- No public changes

Side effects

 - No compatibility issues if we wait for #8349 to settle (thus why this is WIP)

Related changes

 - Need to update the documentation
 - Need to be included in the release note

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8359)

### CODE REVIEW

**Comment by morgo** [comment]
I think you can print the foreign keys regardless.  MySQL will print them irrespective of  `foreign_key_checks=0`.

**Comment by gregwebs** [comment]
There is a difference though that in MySQL one may assume that settings are the same on backup and restore. However when going from TiDB to MySQL with the defaults one would go from not checking to checking.

I think it is a feature if a restore fails due to a row not satisfying the foreign key reference in the original DB (where it wasn't being checked). The main problem in my mind is if restore fails due to the ordering of table imports. This failure could be either in DDL or on insert.

### DDL

I think a more sophisticated restore would first apply create table statements without foreign keys and then to apply alter table statements to add foreign keys if they don't exists (I am doing this myself right now for my schema creation).
However, if the original database verified the foreign key DDL then the DDL restore should be trustworthy with `foreign_key_checks=0` unless it is only restoring a subset of the tables.

### Insert

In the general case, there are circular constraints and foreign keys cannot be validated during import insertion. Tooling to perform these checks after insertion of multiple tables would be very helpful.

### IMHO

We can print this out and force the user to set `foreign_key_checks=0` during restore.

**Comment by gregwebs** [comment]
From the [docs](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html):

>  mysqldump automatically includes a statement in the dump output to set foreign_key_checks to 0.

**Comment by zz-jason** [comment]
@winkyao @zimulala PTAL

**Comment by morgo** [comment]
We need to add mydumper, myloader, loader, mysqldump to the manual tests to make sure it still works.  Restorability should be the highest priority, since users have trouble understanding the errors - or have a large backup file and can't reasonable edit for all cases.

**Comment by gregwebs** [comment]
I was able to use this patch to generate an entity relationship diagram. I used up my TiDB time with this yesterday though, so I won't get back to testing this more until December. I am happy to have others take up the cause in the mean time.

**Comment by morgo** [comment]
Can we clean this up, and merge it?  My suggestions:
- Always show foreign key info. It should not depend on the value of any settings.
- It has to show the name of the constraint, this is required for dropping successfully.

There shouldn't be any compatibility issues because TiDB already parses and imports FK information, it is just buried in `information_schema`.  This fix would make sure that logical constraint information is not dropped in a dump+restore.  Because `foreign_key_checks=0` users also have some expectation it won't work for DML.

**Comment by zz-jason** [comment]
@gregwebs friendly ping, any update?

**Comment by gregwebs** [comment]
Sorry, I haven't had time to push this through. If this doesn't cause any compatibility issues (testing needed) then we should merge it.

**Pull request closed without merging**
