### PR TITLE
expression: use a relax json comparison cast rule

### LINKED ISSUE #37403: Cast other types to JSON when compared with JSON value
## Enhancement

In MySQL 5.7:

```
1149   if (type != ROW_RESULT &&
1150       (((*a)->result_type() == STRING_RESULT &&
1151         (*a)->field_type() == MYSQL_TYPE_JSON) ||
1152        ((*b)->result_type() == STRING_RESULT &&                                                                                                                                     
1153         (*b)->field_type() == MYSQL_TYPE_JSON)))
1154   {
1155     // Use the JSON comparator if at least one of the arguments is JSON.
1156     is_nulls_eq= is_owner_equal_func();
1157     func= &Arg_comparator::compare_json;
1158     return 0;
1159   }
```

If one of the compare args is json value, the other should be casted to json.

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #37403 

Problem Summary:

### What is changed and how it works?

If one of the compare args is json value, the other should be casted to json.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

```
select cast('{ }' as json) < 1;
```

### Release note

```release-note
Fix the issue that the comparison between json and other value is not compatible with MySQL
```

### CODE REVIEW

**Comment by ngaut** [comment]
Please add test cases.

**Review by xiongjiwei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
