### PR TITLE
planner: fix the risk of integer overflow when locating partitions

### LINKED ISSUE #25598: runtime: out of memory
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `UK_HP16726` (
  `COL1` bigint(16) DEFAULT NULL,
  `COL2` varchar(20) DEFAULT NULL,
  `COL4` datetime DEFAULT NULL,
  `COL3` bigint(20) DEFAULT NULL,
  `COL5` float DEFAULT NULL,
  UNIQUE KEY `UK_COL1` (`COL1`) /*!80000 INVISIBLE */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY HASH( `COL1` )
PARTITIONS 25;
select t1. col1, t2. col1 from UK_HP16726 as t1 inner join UK_HP16726 as t2 on t1.col1 = t2.col1 where t1.col1 > -9223372036854775808 group by t1.col1, t2.col1 having t1.col1 != 9223372036854775807;
```
### 2. What did you expect to see? (Required)
```
mysql> select t1. col1, t2. col1 from UK_HP16726 as t1 inner join UK_HP16726 as t2 on t1.col1 = t2.col1 where t1.col1 > -9223372036854775808 group by t1.col1, t2.col1 having t1.col1 != 9223372036854775807;
Empty set (0.00 sec)
```
### 3. What did you see instead (Required)
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x373b01b, 0x16)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sysMap(0xc350000000, 0x11c000000, 0x57acf90)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x5791760, 0x118c00000, 0x10ed317, 0x5791768)
	/usr/local/go/src/runtime/malloc.go:729 +0x1e5
runtime.(*mheap).grow(0x5791760, 0x8c479, 0x0)
	/usr/local/go/src/runtime/mheap.go:1346 +0x85
runtime.(*mheap).allocSpan(0x5791760, 0x8c479, 0x1100100, 0xc010563200)
	/usr/local/go/src/runtime/mheap.go:1173 +0x609
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:910 +0x59
runtime.systemstack(0x1132774)
	/usr/local/go/src/runtime/asm_amd64.s:379 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1246
```
### 4. What is your TiDB version? (Required)

```
Release Version: v5.1.0-alpha-230-gcb4235356
Edition: Community
Git Commit Hash: cb4235356756b1fdf66468c704737c1f8a7222a8
Git Branch: release-5.1
UTC Build Time: 2021-06-21 06:47:15
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?
Issue Number: close #25598 

Problem Summary: planner: fix the risk of integer overflow when locating partitions

When locating partitions for integers, TiDB may subtract an integer's highest and lowest values, where the risk of interger overflow might appear.

### Check List 

Tests 

- Unit test

### Release note 

- planner: fix the risk of integer overflow when locating partitions

### CODE REVIEW

**Review by lysu — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Review by lysu — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Comment by qw4990** [comment]
/merge

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
