### PR TITLE
plan, stats: remove unnecessary clone

### PR DESCRIPTION
**Pull request by lamxTyler**
By doing `PushDownNot` first, we can avoid repeated work and unnecessary clone.

### CODE REVIEW

**Comment by coocood** [comment]
@lamxTyler 
Can we do `PushDonwNot` in `logicalOptimize`?

**Comment by lamxTyler** [comment]
@coocood I think `PushDonwNot` is not an optimization, it is just used for range calculation.

**Comment by coocood** [comment]
Is it safe to permanently pushed down NOT?
Or are there any reason we don't do it in `expressionRewritter`?

**Comment by lamxTyler** [comment]
@coocood  I think they are equivalent. Since it is only used for range calculation, not every expression needs push down `not`, so do it in `expressionRewriter` may introduce some extra work.

**Comment by coocood** [comment]
LGTM

**Comment by coocood** [comment]
@hanfei1991 PTAL

**Comment by hanfei1991** [comment]
LGTM

**Pull request merged**
