### PR TITLE
*: use the latest independent resource group manager client

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Issue Number: ref #38825.

Problem Summary:

### What is changed and how it works?

- Update client-go to make sure https://github.com/tikv/client-go/pull/691 take effect.
- Use the latest independent resource group manager client.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)

Before:

图片

After:

图片

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by JmPotato** [comment]
PTAL

/cc @nolouch @glorv @BornChanger @CabinfeverB

**Review by glorv — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by BornChanger — APPROVED** [review]

**Pull request merged**
