### PR TITLE
timeutil: do not use system files to verify timezone

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve? 
Use some system files to verify timezone making TiDB not portable.

### What is changed and how it works?
Use time.LoadLocation to verify the timezone.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by Deardrops** [comment]
For getting system's time zone, You could use `time.Local` in `"time"` std pkg.
It does the same thing with `InferSystemTZ` function for getting system's time zone.
Also, time.Local.String() will return the string we need returned by `InferSystemTZ`.


related PR #13614

**Comment by jackysp** [comment]
Thanks for your suggestion, @Deardrops ! But I think it is not the key point of `InferSystemTZ`. I'm also confused about the current implementation. I need some help from the author.

**Comment by coocood** [comment]
@breeswish PTAL

**Pull request merged**
