### PR TITLE
util: redact log for expensive sqls (#20852)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20852 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/20891 

Problem Summary: 

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Format expensive sql if `tidb_redact_log` is true.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

- No release note

### CODE REVIEW

**Comment by wshwsh12** [comment]
Wait for https://github.com/pingcap/tidb/pull/20436 cherry-pick

**Comment by wshwsh12** [comment]
@crazycs520 @SunRunAway  PTAL

**Review by crazycs520 — COMMENTED** [review]
LGTM

**Review by SunRunAway — APPROVED** [review]
LGTM

**Pull request merged**
