### PR TITLE
statistics/scalar_test: migrate test-infra to testify

### LINKED ISSUE #28119: migrate test-infra to testify for `statistics/scalar_test.go`

### PR DESCRIPTION
**Pull request by xiaoyong-z**
Signed-off-by: Xiaoyong Zhao <xiaoyong99z@163.com>

### What problem does this PR solve?

Issue Number: close #28119

```release-note
None
```

### CODE REVIEW

**Review by mmyj — APPROVED** [review]
lgtm

**Comment by mmyj** [comment]
> [CLA assistant check](https://cla-assistant.io/pingcap/tidb?pullRequest=28224)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/pingcap/tidb?pullRequest=28224) before we can accept your contribution.
> **1** out of **2** committers have signed the CLA.
> 
> ✅ xiaoyong-z
> ❌ Xiaoyong Zhao
> 
> **Xiaoyong Zhao** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pingcap/tidb?pullRequest=28224) it.

It seems that you need to reset the username of the commit `68e9622862b6d5d78b81657491a76a1eaca836c5` to `xiaoyong-z`.

**Review by tisonkun — APPROVED** [review]
LGTM.

Pushed a follow up to fix go fmt and precise matcher `InDelta`.

**Pull request merged**
