### PR TITLE
executor : remove unnecessary alloc in insert path

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve? 

remove unnecessary memory allocate and copy during main insert path

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by lysu** [comment]
@cfzjywxk Go can optimize this, https://github.com/golang/go/wiki/CompilerOptimizations#map-lookup-by-byte, so we don't need stirng.hack for this case

**Comment by cfzjywxk** [comment]
> @cfzjywxk Go can optimize this, https://github.com/golang/go/wiki/CompilerOptimizations#map-lookup-by-byte, so we don't need string.hack for this case

seems golang already done this,   a bit little confusing when will golang alloc or not.
do we need to make it clear in  app code ?  @lysu @jackysp

**Comment by tiancaiamao** [comment]
This change is unnecessary, the Go compiler could optimize the case.

**Comment by ngaut** [comment]
#https://github.com/pingcap/tidb/issues/11588

**Pull request closed without merging**
