### PR TITLE
parser: grant select on test.* to 'test'

### PR DESCRIPTION
**Pull request by tiancaiamao**
fix issue https://github.com/pingcap/tidb/issues/2654
grant select on test.* to 'test' is the same as
grant select on test.* to 'test'@'%'

### CODE REVIEW

**Comment by tiancaiamao** [comment]
ref https://github.com/pingcap/tidb/issues/2654

**Comment by shenli** [comment]
LGTM
@zimulala @coocood PTAL

**Comment by zimulala** [comment]
Add a test for the parser .

**Comment by coocood** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
