### PR TITLE
executor: support trace with tikv exec details

### PR DESCRIPTION
**Pull request by zyguan**
Signed-off-by: zyguan <zhongyangguan@gmail.com>

### What problem does this PR solve?

Issue Number: ref #34106

Problem Summary: as described in https://github.com/tikv/client-go/pull/559.

### What is changed and how it works?

Enable `TraceExecDetails` when executing trace statements. Require https://github.com/tikv/client-go/pull/559 be merged.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@zyguan 
We could merge it into master first.

**Comment by zyguan** [comment]
> @zyguan We could merge it into master first.

updated.

**Review by cfzjywxk — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]

**Pull request merged**
