### PR TITLE
statistics: collect FMSketch when processing index analyze tasks

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary: statistics: collect FMSketch when processing index analyze tasks

### What is changed and how it works?

statistics: collect FMSketch when processing index analyze tasks

### Check List 

Tests 

- Unit test

### Release note 

- statistics: collect FMSketch when processing index analyze tasks

### CODE REVIEW

**Comment by Reminiscent** [comment]
@qw4990 Please fix the failed tests.

**Comment by qw4990** [comment]
fixed, PTAL @Reminiscent

**Review by Reminiscent — APPROVED** [review]
/LGTM

**Pull request merged**
