### PR TITLE
ddl: allow more charset/collation modifications for database/table (#10958)

### PR DESCRIPTION
**Pull request by bb7133**
Cherry-pick https://github.com/pingcap/tidb/pull/10958

### CODE REVIEW

**Comment by zimulala** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by bb7133** [comment]
/run-ddl-test tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by bb7133** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by bb7133** [comment]
/run-all-tests tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by zz-jason** [comment]
/run-integration-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1
/run-integration-ddl-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
/run-integration-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1
/run-integration-ddl-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
