### PR TITLE
plans: join filter must use origin result fields

### LINKED ISSUE #363: Where between use null error.
```
drop table if exists t;
create table t (c int);
insert into t values (1);
select a.c from t as a where c between null and 2;
error: unknown field a.c
```

### PR DESCRIPTION
**Pull request by siddontang**
Fix #363
e,g, `select * from t as a`
The plan phase in from is table plan -> join plan, and we can only get
the alias name in join plan, so if we return origin table plan directly
in join Filter, we may get wrong result fields.

@qiuyesuifeng  @coocood

### CODE REVIEW

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by shenli** [comment]
Any testcase?

**Comment by siddontang** [comment]
PTAL

**Comment by shenli** [comment]
LGTM

**Pull request merged**
