### PR TITLE
expression/agg: remove useless code.

### PR DESCRIPTION
**Pull request by winoros**
Avg with distinct checker won't push down.
PTAL @zz-jason @XuHuaiyu

### CODE REVIEW

**Comment by shenli** [comment]
Can not understand your description. Could you be more specific?

**Comment by zimulala** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
Please edit the title more explicit.

**Comment by winoros** [comment]
@shenli The `updateAvg` will be called only when calculating the partial result from the partial aggregation. 
But if the aggregation is to calculate the distinct value(e.g. `avg(distinct a)`), it won't be split to final aggregation and the partial aggregation. 
So we never go into this code.

**Pull request merged**
