### PR TITLE
statistics: reorder key and value generic parameters of the heap

### PR DESCRIPTION
**Pull request by Rustin170506**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/55906

Problem Summary:

### What changed and how does it work?

Just reorder the generic parameters of the heap. <V,K> -> <K,V>.

When I wrote this code, I thought it didn't matter, but it was kind of annoying when I tried to use it. So it's better to keep it like any other normal heap.

Also, I added `main_test` to check the goroutine leak.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by AilinKid — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Review by elsa0520 — APPROVED** [review]
LGTM

**Comment by Rustin170506** [comment]
Thanks for your review!  💚 💙 💜 💛 ❤️

**Pull request merged**
