### PR TITLE
ddl: year type should not has unsigned flag

### PR DESCRIPTION
**Pull request by winkyao**
## What have you changed? (mandatory)

Remove unsigned flag of mysql.YearType in create table statement.

Before this PR, we got error from:

```
mysql> create table abc(y year, x int, primary key(y));
Query OK, 0 rows affected (0.12 sec)

mysql> show create table abc;
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                             |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| abc   | CREATE TABLE `abc` (
  `y` year UNSIGNED NOT NULL,
  `x` int(11) DEFAULT NULL,
  PRIMARY KEY (`y`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
 
mysql> CREATE TABLE `abc` (
    ->   `y` year UNSIGNED NOT NULL,
    ->   `x` int(11) DEFAULT NULL,
    ->   PRIMARY KEY (`y`)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ERROR 1105 (HY000): line 2 column 20 near " NOT NULL,
  `x` int(11) DEFAULT NULL,
  PRIMARY KEY (`y`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin" (total length 152)
```

Because `show create table` output the column y as 

```
`y` year UNSIGNED NOT NULL,
```

## What are the type of the changes (mandatory)?

Bug fix

## How has this PR been tested (mandatory)?

unit tests

### CODE REVIEW

**Comment by shenli** [comment]
We need to add a condition check [here](https://github.com/pingcap/tidb/blob/master/table/column.go#L203). So we could get correct result for the already table with year column.

**Comment by winkyao** [comment]
@shenli Done, PTAL

**Comment by shenli** [comment]
LGTM

**Pull request merged**
