### PR TITLE
session, executor: skip some frequent unstable test cases (#24003)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #24003 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/24025
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/24025:release-5.0-46aca1ad0c86
```

---

### What problem does this PR solve?

There some test unstable cases that fail with high frequency, so we can skip them temporarily.
Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

N/A

### Check List 

Tests 

N/A

Side effects

N/A
### Release note 

- No release note

### CODE REVIEW

**Review by eurekaka — APPROVED** [review]
/lgtm

**Review by winoros — APPROVED** [review]

**Pull request merged**
