### PR TITLE
*: support go modules

### PR DESCRIPTION
**Pull request by oiooj**
Add go.mod and go.sum to support go modules, we need to replace `dep` step by step. This PR only add this two files, we need change `Makefile` after this, but we also need time to let users move to go1.11.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Well, last weekend I had a try.
There are more things involves to change to go1.11 module. @oiooj 

- [ ] We have to upgrade Go to v1.11 first https://github.com/pingcap/tidb/pull/7491
- [ ] tipb and kvproto sames use an incompatible version, if it's not resolved, unit test would fail @liukun4515 
- [ ] `github.com/pingcap/tidb/parser` package is generated by Makefile, go mod can't get it
- [ ] Makefile needs to be updated, of course.

**Comment by liukun4515** [comment]
Will upgrading the go version affect the `kvproto`？
@tiancaiamao

**Comment by tiancaiamao** [comment]
Upgrade the go version does not affect the `kvproto`.
It seems `tipb` and `kvproto` are using an incompatible version, I meet "Analyze" error in the unit test.
@liukun4515

**Comment by tiancaiamao** [comment]
Hi, @oiooj 
I close this PR because we're not ready for Go module yet.
I plan to move parser to another repo, and when conditions are mature, feel free to contribute us a PR if you'd like.
Thanks.

**Comment by gregwebs** [comment]
This effort is underway now: https://github.com/pingcap/parser

**Comment by gregwebs** [comment]
#7922

**Pull request closed without merging**
