### PR TITLE
*: make Backoff perceive the Killed flag to fix MAX_EXECUTION_TIME

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Previously we check the killed flag in each executor.Next() call, but if the query current executing Backoff(), we can't terminate the query.

In some cases such as TiKV is crash/recovering, the backoff would last for a long time.
And kill the query doesn't work because the killed flag is not checked during backoff.

Similar issue: https://github.com/pingcap/tidb/pull/12852

### What is changed and how it works?

Pass the `killed` flag to `backoffer` and check the value during backoff.

### Check List 

Tests 

 - Unit test

Release note

 - Fix a bug `MAX_EXECUTION_TIME` doesn't take effect in some cases

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @jackysp @lonng

**Comment by tiancaiamao** [comment]
```
[2020-01-20T07:25:32.212Z] WARNING: DATA RACE
[2020-01-20T07:25:32.212Z] Read at 0x00c0021be740 by goroutine 130:
[2020-01-20T07:25:32.212Z]   github.com/pingcap/tidb/store/tikv/gcworker.(*mergeLockScanner).Start.func1()
[2020-01-20T07:25:32.212Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/tikv/gcworker/gc_worker.go:1813 +0x208
[2020-01-20T07:25:32.212Z] 
[2020-01-20T07:25:32.212Z] Previous write at 0x00c0021be740 by goroutine 107:
[2020-01-20T07:25:32.212Z]   github.com/pingcap/tidb/store/tikv/gcworker.(*mergeLockScanner).Start()
[2020-01-20T07:25:32.212Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/tikv/gcworker/gc_worker.go:1803 +0x202
[2020-01-20T07:25:32.212Z]   github.com/pingcap/tidb/store/tikv/gcworker.(*testGCWorkerSuite).makeMergedMockClient.func2()
[2020-01-20T07:25:32.212Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/tikv/gcworker/gc_worker_test.go:925 +0x78
```

CI fixed in https://github.com/pingcap/tidb/pull/14554

**Comment by imtbkcat** [comment]
there is a race at `TestKillFlagInBackoff ` @tiancaiamao

**Comment by bb7133** [comment]
hi @tiancaiamao , would you please update the release note in your PR description? Thanks.

**Comment by tiancaiamao** [comment]
I've fixed the data race in the unit test and updated the "Release note" description.
PTAL @imtbkcat @bb7133

**Pull request merged**
