### PR TITLE
config: add a test for `config.toml.example`

### LINKED ISSUE #23765: config: add a test to ensure that there is no hidden config in `config.toml.example`
## Feature Request

For unprepared features， we need to hide their config. But we don't have a test to ensure that there is no hidden config in `config.toml.example`. We need to add it.

### PR DESCRIPTION
**Pull request by rebelice**
### What problem does this PR solve?

Issue Number: close #23765 

Add a test to ensure that there is no hidden config in `config.toml.example`

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
/LGTM

**Pull request merged**
