### PR TITLE
session: fix set session variable make tidb_snapshot unwork (#28677)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #28677 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/28682
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/28682:release-5.1-417c7358ef31
```

---

Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

`tidb_snapshot` won't work after setting any session variable

### What is changed and how it works?

fix set session variable make tidb_snapshot unwork

### Check List 

Tests 

- [x] Unit test

### Release note 

```release-note
Fix the bug that setting any session variable will make `tidb_snapshot` unwork.
```

### CODE REVIEW

**Comment by xhebox** [comment]
@Yisaer PTAL

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by xhebox** [comment]
to #35515

**Comment by xhebox** [comment]
/hold

waiting for CI fix

**Pull request merged**
