### PR TITLE
store, kv: Add information about async commit/1pc to tidb_last_txn_info (#23833)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23833 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23868
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23868:release-5.0-0402268a166b
```

---

### What problem does this PR solve?

Problem Summary:
This PR adds some more information to the `tidb_last_txn_info` system variable, so it can expose the commit protocol of the previously finished transaction (2pc, async_commit or 1pc), as well as whether fallback occurred.

By the way, a new failpoint "beforePrewrite" is added. I want to block it there and split the region, so that 1PC fallback can be precisely triggered in tests.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

Added these new fields to `TxnInfo` struct. Fallbacks are determined by checking the final async commit/1pc flag and their initial value to see if it's changed during the commiting procedure.

### Related changes

- Need to cherry-pick to the release branch
  - Maybe 5.0, after the recent release.

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- No release note

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@MyonKeminta 
There are conflicts in the auto pick.

**Review by zyguan — APPROVED** [review]
LGTM

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Pull request merged**
