### PR TITLE
*: add ci image

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: ref #31716

Problem Summary:

### What is changed and how it works?

- add Jenkins dockerfile
- fix the bazel config in the br and update makefile

Q: Why do we need to add CI Dockerfile to TiDB repo?
A: I want to give developers more abilities to control CI. so we just update the Dockerfile( environment) and makefile (logic) to change the CI and they can debug the CI problem or update in the local machine.

### Check List

Tests 

- [x] Unit test
- [x] Integration test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by WizardXiao — COMMENTED** [review]
LGTM about lightning's change, but here maybe needs other dev take a look about the image's change.

**Comment by hawkingrei** [comment]
> LGTM about lightning's change, but here maybe needs other dev take a look about the image's change.

OK

**Review by xhebox — COMMENTED** [review]
LGTM, but I can not really build the docker file since it is internal.

**Review by bb7133 — COMMENTED** [review]
Please add some comments to describe that this is used internally.

**Review by xhebox — APPROVED** [review]

**Pull request closed without merging**
