### PR TITLE
infoschema: improve performance (#25536)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25536 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25554
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25554:release-5.1-979f5356d361
```

---

Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Problem Summary: Reported and suggested by @sticnarf , `GetLatest` is on hotpath, and metrics caused some performance degradation in 5.1. This PR tries to init the counter first.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Review by nolouch — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
lgtm

**Review by JmPotato — APPROVED** [review]

**Comment by hi-rustin** [comment]
@ti-chi-bot

**Pull request merged**
