### PR TITLE
test: make rand test stable

### PR DESCRIPTION
**Pull request by coocood**
### What problem does this PR solve? 
Fixes https://github.com/pingcap/tidb/issues/15225

### What is changed and how it works?
Make the check condition less strict.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by coocood** [comment]
@tiancaiamao @SunRunAway PTAL

**Comment by coocood** [comment]
@bobotu PTAL

**Comment by bobotu** [comment]
Do we really need this case in unit tests? Because this algorithm has already [passed](
https://github.com/golang/go/blob/b5c66de0892d0e9f3f59126eeebc31070e79143b/src/runtime/stubs.go#L115) some kind of statistical testing of uniform random number generators.

**Comment by coocood** [comment]
@bobotu 
We implemented RandN ourself, it's not exactly the same as the runtime.fastrand.

**Comment by tiancaiamao** [comment]
I also meet this problem and change the test to check bits:

https://github.com/pingcap/tidb/pull/15227/files#diff-b2845f617f8f5e0311c5cc4db400e1b5R38

**Comment by coocood** [comment]
@zyguan PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
