### PR TITLE
*: rename variable tidb_kv_read_timeout to tikv_client_read_timeout and remove tidb_kv_read_timeout stmt hint

### LINKED ISSUE #46713: rename variable tidb_kv_read_timeout to tikv_client_read_timeout and remove tidb_kv_read_timeout stmt hint
## Enhancement

@easonn7 recommends the following suggestions about `tidb_kv_read_timeout` which introduced by #45601:
- Rename session variable `tidb_kv_read_timeout` to `tikv_client_read_timeout`, which is more semantic.
- Remove the `/*+ tidb_kv_read_timeout(50) */` statement hint and use `/*+ set_var(tikv_client_read_timeout=50) */` hint to achieve the same effect, in order to converge the hint keyword.

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #46713

Problem Summary: rename variable tidb_kv_read_timeout to tikv_client_read_timeout and remove tidb_kv_read_timeout stmt hint

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- N/A

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@hihihuhu PTAL

**Comment by cfzjywxk** [comment]
/cc @Tema
PTAL

**Review by ekexium — APPROVED** [review]

**Review by you06 — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

**Comment by crazycs520** [comment]
wait https://github.com/pingcap/tidb/issues/46888 fix first

**Review by zyguan — COMMENTED** [review]
Just a kind reminder: this is the first tidb-specified sys var that starts with `tikv_`, all others start with `tidb_`.

**Comment by crazycs520** [comment]
> Just a kind reminder: this is the first tidb-specified sys var that starts with `tikv_`, all others start with `tidb_`.

Yes, but are already have some system var that starts with `tiflash_`:

```sql
> show variables like 'tiflash_%';
+-------------------------------------------+-----------------+
| Variable_name                             | Value           |
+-------------------------------------------+-----------------+
| tiflash_compute_dispatch_policy           | consistent_hash |
| tiflash_enable_pipeline_model             | ON              |
| tiflash_fastscan                          | OFF             |
| tiflash_fine_grained_shuffle_batch_size   | 8192            |
| tiflash_fine_grained_shuffle_stream_count | 0               |
| tiflash_mem_quota_query_per_node          | 0               |
| tiflash_query_spill_ratio                 | 0.7             |
| tiflash_replica_read                      | all_replicas    |
+-------------------------------------------+-----------------+
```

**Pull request merged**
