### PR TITLE
*: don't check unused code in lint

### PR DESCRIPTION
**Pull request by sticnarf**
### What problem does this PR solve?

There are too many false positives when checking unused code. And lots of them cannot be solved, such as https://github.com/pingcap/tidb/blob/35534ae7520c609092c02e2999a0e554f16454cd/executor/executor_pkg_test.go#L524

Actually, the readme of https://github.com/golang/lint says:

> ..., this tool is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process

### What is changed and how it works?

Let's not check unused code in lint.

### Check List 

Tests 

- CI tests

### Release note 

- No release note.

### CODE REVIEW

**Review by tangenta — COMMENTED** [review]
/LGTM

**Review by AilinKid — APPROVED** [review]
LGTM

**Comment by tangenta** [comment]
@sticnarf  The linter only checks the new code introduced in the PR. Perhaps these should be annotated with `nolint` explicitly?

**Comment by sticnarf** [comment]
> @sticnarf The linter only checks the new code introduced in the PR. Perhaps these should be annotated with `nolint` explicitly?

Golint does not support code level "nolint".

**Comment by tangenta** [comment]
https://golangci-lint.run/usage/false-positives/#nolint

**Comment by sticnarf** [comment]
Sorry I think I was referring the wrong linter... Golangci-lint can supress warnings.

**Pull request closed without merging**
