### PR TITLE
explaintest: move IT in `types/const_test` to explaintest

### LINKED ISSUE #46513: Move IT in `types/` to explaintest, files number 24

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #46513

Problem Summary:

I will rename it to `integration_test` later. Avoid always change the ci pipeline.

It could reduce the time of `github.com/pingcap/tidb/types` test from 46s to 0.1s and it only costs 1.3s in explaintest. So it speed up about 30x for test cases. (Total moved cases number is 14, every `CreateMockStore` needs 3.29s)

Before PR
```
/usr/local/go/bin/go test -timeout 90s -tags intest,deadlock github.com/pingcap/tidb/types
ok      github.com/pingcap/tidb/types   46.082s
```
After PR
```
/usr/local/go/bin/go test -timeout 90s -tags intest,deadlock github.com/pingcap/tidb/types
ok      github.com/pingcap/tidb/types   0.074s

./t/types/const.test: ok! 143 test cases passed, take time 1.310917162 s
```

Another way, with https://github.com/pingcap/tidb/pull/42521
```
/usr/local/go/bin/go test -timeout 90s -tags intest,deadlock github.com/pingcap/tidb/types
ok      github.com/pingcap/tidb/types   26.934s
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by bb7133** [comment]
> /hold

@Defined2014 It's weird to put `types/const_test` in `explaintest`. How about creating a new directory like `mysql_test`?

**Comment by Defined2014** [comment]
> > /hold
> 
> @Defined2014 It's weird to put `types/const_test` in `explaintest`. How about creating a new directory like `mysql_test`?

I will do it later. If we create a new directory, we need change the ci pipeline.

**Pull request merged**
