### PR TITLE
statistics: add the analysis worker

### PR DESCRIPTION
**Pull request by Rustin170506**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/55618

Problem Summary:

### What changed and how does it work?

This PR split from the https://github.com/pingcap/tidb/pull/55621.

It introduced a new analysis worker to help us maintain the currently running jobs.

If you want to know how to use it, please check https://github.com/pingcap/tidb/pull/55621.

It also added a new API for the analysis job, because we need to add a unique identifier to avoid adding the same table or job again.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by hawkingrei — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
