### PR TITLE
*: make expression index as experimental feature

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

make expression index as experimental feature

### What is changed and how it works?

make expression index as experimental feature
add variable `tidb_allow_function_for_expression_index` to show all allowed function.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
'None' 
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Comment by kennytm** [comment]
wut.

it should be added back `br/tests/config/tidb.toml` as well, otherwise the `lightning_generated_columns` test which contains an expression index schema may fail.

**Pull request merged**
