### PR TITLE
executor: fix load data panic if the data is broken at escape character (#30868)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #30868 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/31773
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/31773:release-5.3-65365628b7e2
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/31589

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
fix load data will panic in some case
```

### CODE REVIEW

**Comment by guo-shaoge** [comment]
@xiongjiwei please remember to fix the conflicts.

**Review by Defined2014 — APPROVED** [review]

**Review by youjiali1995 — APPROVED** [review]

**Pull request merged**
