### PR TITLE
br: Fix compiling on FreeBSD

### LINKED ISSUE #36589: Compiling on FreeBSD fails
## Bug Report

```
dveeden@nas:~/dev/pingcap/tidb % gmake server
CGO_ENABLED=1 GO111MODULE=on go build  -tags codes  -ldflags '-X "github.com/pingcap/tidb/parser/mysql.TiDBReleaseVersion=v5.4.0-alpha-2231-g1b848f40e" -X "github.com/pingcap/tidb/util/versioninfo.TiDBBuildTS=2022-07-26 11:01:56" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitHash=1b848f40e2eebfb4133e92886efc220bc68e8bea" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitBranch=master" -X "github.com/pingcap/tidb/util/versioninfo.TiDBEdition=Community" ' -o bin/tidb-server tidb-server/main.go
# github.com/pingcap/tidb/br/pkg/lightning/common
br/pkg/lightning/common/storage_unix.go:59:19: invalid operation: stat.Bavail * bSize (mismatched types int64 and uint64)
gmake: *** [Makefile:150: server] Error 2
```

This is with master @ 1b848f40e2eebfb4133e92886efc220bc68e8bea

```
% go version
go version go1.18.4 freebsd/amd64
% freebsd-version
13.0-RELEASE-p11
```

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #36589

Problem Summary:

Fix compiling of tidb on FreeBSD

See also https://github.com/pingcap/br/pull/1070

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Not adding a release note as FreeBSD is not an officially supported platform.

```release-note
None
```

### CODE REVIEW

**Review by ngaut — APPROVED** [review]

**Review by Defined2014 — APPROVED** [review]

**Comment by Defined2014** [comment]
Seems ci failed, may need to ignore `unconvert` check.

**Comment by hawkingrei** [comment]
> Seems ci failed, may need to ignore `unconvert` check.

I have ignored it.

**Comment by hawkingrei** [comment]
I suggest it can be implemented by the build tag. because TiDB ci has no FreeBSD environment. it is possible for the other to remove it again. They are not able to find this problem.

**Pull request merged**
