### PR TITLE
execution: fix dayofweek('0000-00-00') behavior

### LINKED ISSUE #21374: dayofweek('0000-00-00') behavior is inconsistent with mysql
## Bug Report

DDL
```mysql
> `mysql> show create table t;
> +-------+--------------------------------------------------------------------------------------------------------------+
> | Table | Create Table                                                                                                 |
> +-------+--------------------------------------------------------------------------------------------------------------+
> | t     | CREATE TABLE `t` (
>   `a` bigint(20) DEFAULT NULL
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
> +-------+--------------------------------------------------------------------------------------------------------------+
> 1 row in set (0.01 sec)`
```

in TiDB
```mysql
> mysql> insert into t values(dayofweek('0000-00-00'));
> ERROR 1366 (HY000): Incorrect bigint value: '' for column 'a' at row 1
```

in MySQL
```mysql
> mysql> insert into t values(dayofweek('0000-00-00'));
> ERROR 1292 (22007): Incorrect datetime value: '0000-00-00'
```

### 1. Minimal reproduce step (Required)

As above

### 2. What did you expect to see? (Required)

Behave the same as `mysql` , At least single quotes should not be empty .

### 3. What did you see instead (Required)

As above

### 4. What is your TiDB version? (Required)

*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.8
Edition: Community
Git Commit Hash: 66ac9fc31f1733e5eb8d11891ec1b38f9c422817
Git Branch: heads/refs/tags/v4.0.8
UTC Build Time: 2020-10-30 08:21:16
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.01 sec)

## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

300

## Mentor

- @lzmhhh123

### PR DESCRIPTION
**Pull request by b41sh**
### What problem does this PR solve?

Issue Number: close #21374 

Problem Summary:
fix error message of `insert into t values(dayofweek('0000-00-00'));` for MySQL compatibility.

What's Changed:
return correct error. 

How it Works:

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- fix dayofweek('0000-00-00') behavior for MySQL compatibility

### CODE REVIEW

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Comment by b41sh** [comment]
PTAL @XuHuaiyu @SunRunAway

**Review by qw4990 — APPROVED** [review]
LGTM

**Pull request merged**
