### PR TITLE
expression: some builtin functions can be folded

### PR DESCRIPTION
**Pull request by zz-jason**
- sysdate
- curdate
- current_date
- utc_date
- utc_timestamp
- unix_timestamp 
- database
- current_user
- user
- connection_id
- last_insert_id
- version

### CODE REVIEW

**Comment by coocood** [comment]
What about `utc_date`, `curdate`, etc?

**Comment by zz-jason** [comment]
@coocood @XuHuaiyu PTAL

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Pull request merged**
