### PR TITLE
*: fix 'duplicate entry' error when using br to restore AUTO_ID_CACHE=1 tables

### LINKED ISSUE #44716: Duplicate entry when using BR to restore a AUTO_ID_CACHE=1 table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
tiup playground --tiflash 0
mysql -h 127.0.0.1 -u root -P 4000
create table t (a int primary key auto_increment, b int) AUTO_ID_CACHE 1;
insert into t(b) values (1),(2),(3),(4),(5),(6),(7),(8),(9);
insert into t(b) values (11),(21),(31),(41),(51),(61),(71),(81),(91);
...

tiup br backup full --pd=127.0.0.1:2379 -s local:///tmp/tidb/backup/tidb-test
# Ctrl + C to kill the playground cluster, and start a new one
tiup playground --tiflash 0

tiup br restore full --pd=127.0.0.1:2379 -s local:///tmp/tidb/backup/tidb-test

# insert data to the BR restored table
mysql -h 127.0.0.1 -u root -P 4000
use test
insert into t (b)  values  (666)
```

### 2. What did you expect to see? (Required)

No error

### 3. What did you see instead (Required)

```
mysql> insert into t (b) values (666);
ERROR 1062 (23000): Duplicate entry '1' for key 't.PRIMARY'
```

### 4. What is your TiDB version? (Required)

7.1

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #44716, ref #38442

Problem Summary:

https://github.com/pingcap/tidb/pull/39041 use separate allocator for row id and auto id.
That is some kind of  compatibility-break, although it handle the backword-compatibility carefully in the tidb side, I still miss something in the br component.

When br backup a table with auto increment column, it get the row id allocator from the meta key. It should have used the auto increment id allocator after https://github.com/pingcap/tidb/pull/39041

### What is changed and how it works?

The auto increment meta key of a table with AUTO_ID_CACHE=1 option is a separated one, rather than the row ID meta key.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)

The steps descripted in https://github.com/pingcap/tidb/issues/44716
I do think some integration test is necessory for this commit.

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by xhebox — CHANGES_REQUESTED** [review]
``` FAILED  ddl.TestAutoIncrementForceAutoIDCache ```

**Comment by bb7133** [comment]
PTAL @tangenta @3pointer

**Review by xhebox — APPROVED** [review]

**Review by Leavrth — APPROVED** [review]

**Comment by tiancaiamao** [comment]
/retest unit-test 

CI unit test fail on https://github.com/pingcap/tidb/issues/44800

**Pull request merged**
