### PR TITLE
store/tikv:mv kv.ReplicaReadType to tikv

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: AndreMouche

### What problem does this PR solve?
This PR moves `ReplicaReadType` from kv to tikv since it is only used in tikv
Part of https://github.com/pingcap/tidb/issues/22513

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by disksing — APPROVED** [review]
I will be more LGTM if you could come up with a better alias other than `tikvstore`.

**Comment by AndreMouche** [comment]
> I will be more LGTM if you could come up with a better alias other than `tikvstore`.

Any suggestion?

**Pull request merged**
