### PR TITLE
store/copr: set low concurrency for keep order coprocessor requests

### LINKED ISSUE #35974: scan full table using "order by" consume a lot of memory
## Enhancement

```
mysql> select count(*) from ens_rb.fm_acct_client_relation;
+----------+
| count(*) |
+----------+
| 50000000 |
+----------+
1 row in set (2.55 sec)
```

```
CREATE TABLE `fm_acct_client_relation` (
  `CLIENT_NO` varchar(20) DEFAULT NULL,
  `BASE_ACCT_NO` varchar(150) DEFAULT NULL,
  `INTERNAL_KEY` decimal(15,0) DEFAULT NULL,
  `CARD_NO` varchar(50) DEFAULT NULL,
  `BRANCH` varchar(20) DEFAULT NULL,
  `COMPANY` varchar(20) DEFAULT NULL,
  `SHARD_ID` varchar(10) DEFAULT NULL,
  `TRAN_TIMESTAMP` datetime DEFAULT NULL,
  `PROD_TYPE` varchar(50) DEFAULT NULL,
  `CCY` varchar(3) DEFAULT NULL,
  `ACCT_SEQ_NO` varchar(8) DEFAULT NULL,
  `CLIENT_TYPE` varchar(3) DEFAULT NULL,
  `ACCT_NATURE` varchar(4) DEFAULT NULL,
  `ACCT_CLASS` varchar(2) DEFAULT NULL,
  `SOURCE_TYPE` varchar(10) DEFAULT NULL,
  `ACCT_STATUS` varchar(3) DEFAULT NULL,
  `ACCT_REAL_FLAG` varchar(1) DEFAULT NULL,
  `ACCT_NAME` varchar(200) DEFAULT NULL,
  `REASON_CODE` varchar(200) DEFAULT NULL,
  `IS_CARD` varchar(1) DEFAULT NULL,
  `LEAD_ACCT_FLAG` varchar(1) DEFAULT NULL,
  `PARENT_INTERNAL_KEY` decimal(15,0) DEFAULT NULL,
  `DEFAULT_SETTLE_ACCT` varchar(1) DEFAULT NULL,
  `DOCUMENT_TYPE` varchar(3) DEFAULT NULL,
  `IS_INDIVIDUAL` varchar(1) DEFAULT NULL,
  `DOCUMENT_ID` varchar(40) DEFAULT NULL,
  `ACTUAL_ACCT_NO` varchar(150) DEFAULT NULL,
  `APP_FLAG` varchar(1) DEFAULT NULL,
  `IS_CORP_SETTLE_CARD` varchar(1) DEFAULT NULL,
  `loginid` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`loginid`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `UN_IDX_RELATION` (`CARD_NO`,`ACCT_SEQ_NO`,`PROD_TYPE`,`BASE_ACCT_NO`,`CCY`),
  KEY `FACR_IND1` (`CLIENT_NO`),
  KEY `FACR_IND2` (`BASE_ACCT_NO`),
  KEY `FACR_IND3` (`CARD_NO`),
  KEY `FACR_IND4` (`INTERNAL_KEY`),
  KEY `FACR_IND5` (`ACTUAL_ACCT_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=50100001
```

With 'order by'

```
time mysql -h 127.0.0.1 -u root -P 4000 -B ens_rb -e 'set @@tidb_enable_paging = 1; select * from ens_rb.fm_acct_client_relation order by loginid' > /dev/null

real	2m30.225s
user	1m33.578s
sys	0m8.454s
```

Without 'order by'

```
time mysql -h 127.0.0.1 -u root -P 4000 -B ens_rb -e 'set @@tidb_enable_paging = 1; select * from ens_rb.fm_acct_client_relation' > /dev/null

real	2m32.847s
user	1m37.531s
sys	0m7.384s
```

4.86G  vs 2.17G ... 
as you can see, 'order by' takes much more memory than without it.

image

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #35974

Problem Summary:

keep order requests consume much more memory than normal cases.
That's because we use a high coprocessor concurrency for it, but with the existance of 'order by',
the cop responses have to be handled one by one ... most of the cop responses are just wasting memory.

### What is changed and how it works?

We don't need high concurrency for keep order coprocessor requests.

```
time mysql -h 127.0.0.1 -u root -P 4000 -B ens_rb -e 'set @@tidb_enable_paging = 1; select * from ens_rb.fm_acct_client_relation order by loginid' > /dev/null
```

=====================

**The performance do not decrease with lower concurrency!**

Before:

```
real	2m30.225s
user	1m33.578s
sys	0m8.454s
```

After:

```
real	2m32.266s
user	1m35.731s
sys	0m7.367s
```

=====================

The memory consumption reduced:

image

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Set a low concurrency value for coprocessor requests with 'keep order' property, this change can dramatically reduce the memory usage in a full table scan with 'order by' scenario 
```

### CODE REVIEW

**Review by XuHuaiyu — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Comment by tiancaiamao** [comment]
Testing with non-paging protocol, the conclusion is the same, high concurrency is useless here.

```
time mysql -h [127.0.0.1](http://127.0.0.1/) -u root -P 4000 -B ens_rb -e 'set @@tidb_enable_paging = 0; select * from ens_rb.fm_acct_client_relation order by loginid' > /dev/null

real	2m28.491s
user	1m35.039s
sys	0m7.399s

time mysql -h [127.0.0.1](http://127.0.0.1/) -u root -P 4000 -B ens_rb -e 'set @@tidb_enable_paging = 0; select * from ens_rb.fm_acct_client_relation order by loginid' > /dev/null

real	2m28.764s
user	1m35.245s
sys	0m7.526s
```

image

**Review by wshwsh12 — APPROVED** [review]
LGTM

**Pull request merged**
