### PR TITLE
drop foreign key that does not exist error

### PR DESCRIPTION
**Pull request by Zhoubirdblue**
drop foreign key that does not exist will cause this ddl job block ddl work

### CODE REVIEW

**Comment by ngaut** [comment]
Thank you @Zhoubirdblue
Please sign the CLA by clicking the CLA button.

**Comment by zimulala** [comment]
Please add some tests.

**Comment by zimulala** [comment]
The test you can use the function of `doDDLJobErr` . The detail you can refer to [TestIndexError](https://github.com/pingcap/tidb/blob/master/ddl/ddl_worker_test.go#L163)

**Comment by Zhoubirdblue** [comment]
Same as I thought, I intended to use checkJobCancelled. I will add the test later. 
Are you a girl? Me too ;)

**Comment by zimulala** [comment]
Do it according to your understanding.  
Thank you @Zhoubirdblue  :)

**Comment by hanfei1991** [comment]
You should use go fmt to format your code in order to pass ci test @Zhoubirdblue

**Comment by ngaut** [comment]
PTAL

**Comment by zimulala** [comment]
LGTM

**Comment by Zhoubirdblue** [comment]
Thanks @ngaut

**Comment by ngaut** [comment]
PTAL @coocood

**Comment by coocood** [comment]
LGTM
@Zhoubirdblue 
Thank you!

**Pull request merged**
