### PR TITLE
br: fix-panic, call close(chan) before waitgroup.done()

### PR DESCRIPTION
**Pull request by joccau**
Signed-off-by: joccau <zak.zhao@pingcap.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/29489

Problem Summary: close(chan) for twice because CPU schedule to other go-routine 

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]
LGTM.
BTW, the restore side avoid this problem by never close the error channel(`errCh` is usually a mpsc channel... However Go forces us to choose a producer to close the channel, maybe we need some techniques like `Arc`?).

**Pull request merged**
