### PR TITLE
*: Bug Fix/CLUSTER_INFO system table may not work after PD is scaled-in (#19355)

### LINKED ISSUE #18990: CLUSTER_INFO system table may not work after PD is scaled-in
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Scale-in PD.

### 2. What did you expect to see? (Required)

Successfully query INFORMATION_SCHEMA.CLUSTER_INFO

### 3. What did you see instead (Required)

It tries to access a PD that no longer exists. dial tcp xxxx: connect: connection refused

### 4. Affected version (Required)

v4.0.4

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19355 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #18990

Problem Summary:
CLUSTER_INFO system table may not work after PD is scaled-in

### What is changed and how it works?
What's Changed:
Changed the EtcdAddrs() to get correct pd members info
Changed the GetPDServerInfo function, add rpc GetMember() in pd and TiDB use grpc to get the pd members info.
How it Works:
Use grpc to get the pd members url, then use pd-api `/pd/api/v1/config/cluster-version` and `/pd/api/v1/config/status` to get member version githash info

### Related changes
- PR to update `pingcap/tidb/infoschema/tables.go` and `pingcap/tidb/util/pdapi/const.go`:
- Need to cherry-pick to the release branch

### Check List 

Tests 
- Unit test
- Manual test (add detailed scripts or steps below)
steps:
use tiup playground scale-out --pd 2 to scale out pd
use mysql to connect TiDB
`select * from  INFORMATION_SCHEMA.CLUSTER_INFO; `to test scale out and scale in

Side effects

- Performance regression
    - Consumes more CPU

### Release note 
- Bug fix:CLUSTER_INFO system table may not work after PD is scaled-in or out

### CODE REVIEW

**Comment by Yisaer** [comment]
plz DNM this request as we found that the newly added pdclient interface `GetMemberInfo`'s name needs to be revised. We will fix it before v4.0.7 released.

**Comment by HunDunDM** [comment]
We also need to change the hash of the PD.

**Comment by breeswish** [comment]
@Yisaer What's the status? We have multiple customers met this bug on production environment now and I think we must carry it in 4.0.7.

**Comment by jyz0309** [comment]
@breeswish @crazycs520 PTAL

**Comment by jyz0309** [comment]
@wjhuang2016 PTAL

**Review by breeswish — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]
lgtm

**Comment by jyz0309** [comment]
@breeswish PTAL, maybe can merge?

**Comment by breeswish** [comment]
@lzmhhh123 Please help merge this PR, thanks!

**Comment by bb7133** [comment]
Thanks for your contribution! @jyz0309

**Pull request merged**
