### PR TITLE
lightning_web: mute the alert

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve?

Problem Summary: github reports security issue, this PR try to mute it.

### What is changed and how it works?
update pakcage-lock.json 

### Check List

Tests 

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by lonng — APPROVED** [review]
LGTM

**Review by ngaut — APPROVED** [review]

**Comment by hawkingrei** [comment]
@3pointer Please fix the linter.

**Pull request merged**
