### PR TITLE
server: ping the server to make sure the server is online to make CI stable

### LINKED ISSUE #30297: IT Unstable case `TestSumAvg`
## Bug Report

Please answer these questions before submitting your issue. Thanks!
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_coverage/detail/tidb_ghpr_coverage/1416/pipeline/
```bash
2021-12-01T02:26:54.531Z] --- FAIL: TestSumAvg (1.39s)
[2021-12-01T02:26:54.531Z]     dbtestkit.go:81: 
[2021-12-01T02:26:54.531Z]         	Error Trace:	dbtestkit.go:81
[2021-12-01T02:26:54.531Z]         	            				server_test.go:1864
[2021-12-01T02:26:54.531Z]         	            				server_test.go:117
[2021-12-01T02:26:54.531Z]         	            				server_test.go:1853
[2021-12-01T02:26:54.531Z]         	            				tidb_test.go:1114
[2021-12-01T02:26:54.531Z]         	Error:      	Received unexpected error:
[2021-12-01T02:26:54.531Z]         	            	No Pem data found, data: #28000Access denied for user 'root'@'127.0.0.1' (using password: YES)
[2021-12-01T02:26:54.531Z]         	Test:       	TestSumAvg
[2021-12-01T02:26:54.531Z]         	Messages:   	sql:select avg(a), avg(b), avg(c) from sumavg, args:[]
```

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

This PR might fix #30297, #30249, #30303, #30256, #30286, but I'm not very sure. It at least solves the test case mentioned in https://github.com/pingcap/tidb/pull/30306#issuecomment-984244857

Problem Summary: 
In `waitUntilServerCanConnect`, `sql.Open()` doesn't actually indicate that the connection is established, so we need another `db.Ping()` to verify that.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by djshow832** [comment]
I ran the CI 4 times and they all succeeded.

**Comment by hawkingrei** [comment]
But It still has some problems. it is not related to ```Ping```. It looks like this: 


```
[2021-12-02T03:30:02.107Z] --- FAIL: TestCollateHashJoin2 (0.55s)
[2021-12-02T03:30:02.107Z]     testkit.go:91:
[2021-12-02T03:30:02.107Z]         	Error Trace:	testkit.go:91
[2021-12-02T03:30:02.107Z]         	            				integration_serial_test.go:482
[2021-12-02T03:30:02.107Z]         	Error:      	Received unexpected error:
[2021-12-02T03:30:02.107Z]         	            	[schema:1146]Table 'test.t1' doesn't exist
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/errors.AddStack
[2021-12-02T03:30:02.107Z]         	            		/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226aaa3/errors.go:174
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/errors.(*Error).GenWithStackByArgs
[2021-12-02T03:30:02.107Z]         	            		/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226aaa3/normalize.go:159
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/infoschema.(*infoSchema).TableByName
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/infoschema/infoschema.go:189
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/planner/core.(*preprocessor).tableByName
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:398
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/planner/core.(*preprocessor).handleTableName
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:1421
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/planner/core.(*preprocessor).Leave
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:499
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/parser/ast.(*TableName).Accept
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/parser/ast/dml.go:439
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/parser/ast.(*TableSource).Accept
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/parser/ast/dml.go:592
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/parser/ast.(*Join).Accept
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/parser/ast/dml.go:234
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/parser/ast.(*Join).Accept
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/parser/ast/dml.go:234
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/parser/ast.(*TableRefsClause).Accept
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/parser/ast/dml.go:791
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/parser/ast.(*SelectStmt).Accept
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/parser/ast/dml.go:1429
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/planner/core.Preprocess
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:117
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/executor.(*Compiler).Compile
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/compiler.go:60
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/session.(*session).ExecuteStmt
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1560
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/testkit.(*TestKit).Exec
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/testkit/testkit.go:145
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/testkit.(*TestKit).MustQuery
[2021-12-02T03:30:02.107Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/testkit/testkit.go:90
[2021-12-02T03:30:02.107Z]         	            	github.com/pingcap/tidb/expression_test.TestCollateHashJoin2
[2021-12-02T03:30:02.108Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/expression/integration_serial_test.go:482
[2021-12-02T03:30:02.108Z]         	            	testing.tRunner
[2021-12-02T03:30:02.108Z]         	            		/usr/local/go/src/testing/testing.go:1193
[2021-12-02T03:30:02.108Z]         	            	runtime.goexit
[2021-12-02T03:30:02.108Z]         	            		/usr/local/go/src/runtime/asm_amd64.s:1371
[2021-12-02T03:30:02.108Z]         	Test:       	TestCollateHashJoin2
[2021-12-02T03:30:02.108Z]         	Messages:   	sql:select /*+ TIDB_HJ(t1, t2) */ * from t1, t2 where t1.v=t2.v order by t1.id, args:[]
[2021-12-02T03:30:02.128Z] --- FAIL: TestCollateMergeJoin2 (0.46s)
[2021-12-02T03:30:02.128Z]     testkit.go:91:
[2021-12-02T03:30:02.128Z]         	Error Trace:	testkit.go:91
[2021-12-02T03:30:02.128Z]         	            				integration_serial_test.go:520
[2021-12-02T03:30:02.128Z]         	Error:      	Received unexpected error:
[2021-12-02T03:30:02.128Z]         	            	[schema:1146]Table 'test.t1' doesn't exist
[2021-12-02T03:30:02.128Z]         	            	github.com/pingcap/errors.AddStack
[2021-12-02T03:30:02.128Z]         	            		/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226aaa3/errors.go:174
[2021-12-02T03:30:02.128Z]         	            	github.com/pingcap/errors.(*Error).GenWithStackByArgs
[2021-12-02T03:30:02.128Z]         	            		/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226aaa3/normalize.go:159
[2021-12-02T03:30:02.128Z]         	            	github.com/pingcap/tidb/infoschema.(*infoSchema).TableByName
[2021-12-02T03:30:02.128Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/infoschema/infoschema.go:189
[2021-12-02T03:30:02.128Z]         	            	github.com/pingcap/tidb/planner/core.(*preprocessor).tableByName
[2021-12-02T03:30:02.128Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:398
[2021-12-02T03:30:02.128Z]         	            	github.com/pingcap/tidb/planner/core.(*preprocessor).handleTableName
[2021-12-02T03:30:02.128Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:1421
[2021-12-02T03:30:02.128Z]         	            	github.com/pingcap/tidb/planner/core.(*preprocessor).Leave
[2021-12-02T03:30:02.128Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:499
[2021-12-02T03:30:02.128Z]         	            	github.com/pingcap/tidb/parser/ast.(*TableName).Accept
[2021-12-02T03:30:02.128Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/parser/ast/dml.go:439
[2021-12-02T03:30:02.128Z]         	            	github.com/pingcap/tidb/parser/ast.(*TableSource).Accept
[2021-12-02T03:30:02.128Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/parser/ast/dml.go:592
[2021-12-02T03:30:02.128Z]         	            	github.com/pingcap/tidb/parser/ast.(*Join).Accept
[2021-12-02T03:30:02.128Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/parser/ast/dml.go:234
[2021-12-02T03:30:02.128Z]         	            	github.com/pingcap/tidb/parser/ast.(*Join).Accept
[2021-12-02T03:30:02.128Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/parser/ast/dml.go:234
[2021-12-02T03:30:02.128Z]         	            	github.com/pingcap/tidb/parser/ast.(*TableRefsClause).Accept
[2021-12-02T03:30:02.128Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/parser/ast/dml.go:791
[2021-12-02T03:30:02.129Z]         	            	github.com/pingcap/tidb/parser/ast.(*SelectStmt).Accept
[2021-12-02T03:30:02.129Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/parser/ast/dml.go:1429
[2021-12-02T03:30:02.129Z]         	            	github.com/pingcap/tidb/planner/core.Preprocess
[2021-12-02T03:30:02.129Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:117
[2021-12-02T03:30:02.129Z]         	            	github.com/pingcap/tidb/executor.(*Compiler).Compile
[2021-12-02T03:30:02.129Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/compiler.go:60
[2021-12-02T03:30:02.129Z]         	            	github.com/pingcap/tidb/session.(*session).ExecuteStmt
[2021-12-02T03:30:02.129Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1560
[2021-12-02T03:30:02.129Z]         	            	github.com/pingcap/tidb/testkit.(*TestKit).Exec
[2021-12-02T03:30:02.129Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/testkit/testkit.go:145
[2021-12-02T03:30:02.129Z]         	            	github.com/pingcap/tidb/testkit.(*TestKit).MustQuery
[2021-12-02T03:30:02.129Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/testkit/testkit.go:90
[2021-12-02T03:30:02.129Z]         	            	github.com/pingcap/tidb/expression_test.TestCollateMergeJoin2
[2021-12-02T03:30:02.129Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/expression/integration_serial_test.go:520
[2021-12-02T03:30:02.129Z]         	            	testing.tRunner
[2021-12-02T03:30:02.129Z]         	            		/usr/local/go/src/testing/testing.go:1193
[2021-12-02T03:30:02.129Z]         	            	runtime.goexit
[2021-12-02T03:30:02.129Z]         	            		/usr/local/go/src/runtime/asm_amd64.s:1371
[2021-12-02T03:30:02.129Z]         	Test:       	TestCollateMergeJoin2
[2021-12-02T03:30:02.129Z]         	Messages:   	sql:select /*+ TIDB_SMJ(t1, t2) */ * from t1, t2 where t1.v=t2.v order by t1.id, args:[]
[2021-12-02T03:30:02.294Z] --- FAIL: TestNewCollationBinaryFlag (0.41s)
[2021-12-02T03:30:02.294Z]     integration_serial_test.go:953:
[2021-12-02T03:30:02.294Z]         	Error Trace:	integration_serial_test.go:953
[2021-12-02T03:30:02.294Z]         	Error:      	"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin" does not contain "CREATE TABLE `t` (\n  `a` varchar(10) DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin"
[2021-12-02T03:30:02.294Z]         	Test:       	TestNewCollationBinaryFlag
```

**Comment by hawkingrei** [comment]
I am trying it in #30306 by adding more ```Ping``` and setting some config.

**Pull request closed without merging**
