### PR TITLE
lightning: add back integration test lightning_error_summary

### LINKED ISSUE #29177: CI: lightning_error_summary test case failed.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/7834/pipeline

ERRORCODE is 0 but expect not.

This case expect to return checksum mismatch error. because it insert some data before lightning local backend starts.
I think the reason is lightning calculate the wrong checksum or missing some data.

### 2. What did you expect to see? (Required)
test passed.
### 3. What did you see instead (Required)
test failed.
### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #29177

Problem Summary:

### What is changed and how it works?
Add back lightning integration test `lightning_error_summary`

The `lightning_error_summary` case fails because the original duplicate detection algorithm is `record` which will emit the checksum errors. As we already changed the default to `none`, thus this case should not fail then.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by glorv** [comment]
I'm not sure what is the root cause of case `lightning_error_summary`'s failure because the original running log is lost. This test can pass both in my local environment and in our CI. So I think we can enable it again. I will investigate the root cause if it fails in the future. 
/cc @3pointer @gozssky

**Review by gozssky — APPROVED** [review]

**Review by kennytm — APPROVED** [review]

**Pull request merged**
