### PR TITLE
br: adaption for keyspace feature

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

PR deps:
- [x] client-go: https://github.com/tikv/client-go/pull/666
- [x] TiKV: https://github.com/tikv/tikv/pull/14046

### What problem does this PR solve?

Issue Number: ref #40531

Problem Summary:

### What is changed and how it works?

1. Makes BR produce rewrite rules that include keyspace prefixes.

In the old versions of BR, the rewrite rules' old prefix and new prefix are of the same length:

```
RewriteRule {
    OldPrefix: "t321"
    NewPrefix: "t123",
}
```

For the new format of `RewriteRule`, it could be
```
RewriteRule {
    OldPrefix: "t321"
    NewPrefix: "x001t123",
}
```
or
```
RewriteRule {
    OldPrefix: "x001t321"
    NewPrefix: "t123",
}
```
etc.

This might require BR to send plain SST meta and rewrite rules for TiKV SST import services while sending `DownloadSST` request to TiKV.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
br: adaption for keyspace feature
```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]

**Review by ystaticy — APPROVED** [review]
LGTM~

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
