### PR TITLE
planner: fix expression rewrite makes between expr infers wrong collation.

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/27146

`a between b and c` expression will be rewritten to `a>=b and a<=c`, which makes infer wrong collation, the collation of `between` expression should be inferred as a whole.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
fix expression rewrite makes between expr infers wrong collation.
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by wjhuang2016 — COMMENTED** [review]
Please fix the CI

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
