### PR TITLE
resource_control: use const default resource group name

### PR DESCRIPTION
**Pull request by Connor1996**
### What problem does this PR solve?

Issue Number: Ref #43691 

Problem Summary:

### What is changed and how it works?

Use const default resource group name

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Connor1996** [comment]
PTAL @CabinfeverB @glorv

**Review by glorv — APPROVED** [review]

**Review by CabinfeverB — APPROVED** [review]

**Comment by CabinfeverB** [comment]
need to run `make bazel_prepare`

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
