### PR TITLE
infoschema: refine common part for builder

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: ref #50959

Problem Summary:

### What changed and how does it work?
Extract some common part for v1 and v2 for future development.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — COMMENTED** [review]
Please make sure 

```
func init() {
	enableV2.Store(true)
}
```

tidb-server start up does not panic, otherwise this is broken PR

**Comment by ywqzzy** [comment]
> Please make sure
> 
> ```
> func init() {
> 	enableV2.Store(true)
> }
> ```
> 
> tidb-server start up does not panic, otherwise this is broken PR

OK

**Comment by tiancaiamao** [comment]
Please resolve conflict @ywqzzy

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
