### PR TITLE
session: check redact when log compile error

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #41831

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

```
[2023/03/01 20:14:09.452 +08:00] [WARN] [session.go:2208] ["compile SQL failed"] [conn=2199023255955] [error="[schema:1146]Table 'test.test' doesn't exist"] [SQL="load data infile ? into table `test` . `test`"]
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by okJiang — APPROVED** [review]

**Review by Defined2014 — APPROVED** [review]

**Comment by Defined2014** [comment]
@lance6716 maybe need merge master

**Comment by lance6716** [comment]
> @lance6716 maybe need merge master to pass mysql-test

This PR already include #41823

```
*   bb9f786e1 (HEAD -> redact, origin/redact) Merge branch 'master' of github.com:pingcap/tidb into redact
|\
| * 227b461fe planner: optimize `ifnull(not-null-column, ...)` to a cast instead of eliminating it. tidb-test=pr/2098 (#41823)
```

**Pull request merged**
