### PR TITLE
planner: add test case for sql binding in the local temporary

### LINKED ISSUE #25941: Forbid SQL binding in local temporary tables

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: close #25941  

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

**Comment by tiancaiamao** [comment]
B.T.W, would you like to take a look at this one?  @sylzd 
https://github.com/pingcap/tidb/issues/26377

**Comment by sylzd** [comment]
> B.T.W, would you like to take a look at this one? @sylzd
> #26377

okay~

**Review by lcwangchao — APPROVED** [review]

**Review by djshow832 — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Comment by djshow832** [comment]
I've recorded the data race in https://github.com/pingcap/tidb/issues/27307 and I'm retrying the CI...

**Pull request merged**
