### PR TITLE
*: add Trigger_priv column to mysql.user

### PR DESCRIPTION
**Pull request by tiancaiamao**
May conflict with https://github.com/pingcap/tidb/pull/2994

### CODE REVIEW

**Comment by hanfei1991** [comment]
Why not merge these two PRs in order to use same upgrade version?

**Comment by tiancaiamao** [comment]
Once upon a time, I push a request that add all missing privileges.... but it's rejected.
So I've changed the strategy, add them one by one, and just add those really claimed by our customers.
@hanfei1991

**Comment by hanfei1991** [comment]
@tiancaiamao sad story... LGTM

**Comment by tiancaiamao** [comment]
PTAL @coocood

**Comment by coocood** [comment]
LGTM

**Pull request merged**
