### PR TITLE
config: remove async commit configs from example

### PR DESCRIPTION
**Pull request by sticnarf**
### What is changed and how it works?

We don't expect to expose any async-commit configurations to the user. But we still keep these configurations in TiDB, so they can be modified by advanced users.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`: https://github.com/pingcap/docs-cn/pull/5607

### Check List 

Tests 

- No code

### Release note 

- No release note.

### CODE REVIEW

**Review by youjiali1995 — COMMENTED** [review]
/LGTM

**Review by AndreMouche — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
@ti-chi-bot update this pr branch

**Pull request merged**
