### PR TITLE
distsql: fix goroutine/memory leak for streaming when query is cancelled

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Close https://github.com/pingcap/tidb/issues/27353

### What is changed and how it works?

It's was caused by `streamResult.Close` doesn't close the `kv.Response`.

### Check List 

Tests 

- [x] Manual test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@XuHuaiyu @wshwsh12 PTAL

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by tiancaiamao — APPROVED** [review]

**Review by lysu — APPROVED** [review]

**Pull request merged**
