### PR TITLE
planner: encode insert/delete/update executor plan ... (#19176)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19176 to release-4.0

---

### What problem does this PR solve?

Before this PR, TiDB doesn't record the `insert/update/delete` executor plan information in the `Plan` field of slow-log file.

here is some example of `Plan` field in slow-log file:

```sql
# Time: 2020-08-13T17:06:21.386092+08:00
...
# Plan: tidb_decode_plan('ONwwCTI3XzEJMAkwCU4vQQkwCXRpbWU6My4wMjE1NDVtcywgbG9vcHM6MQkyMTUgQnl0ZXMJTi9BCg==')
insert into t values (1,1);
# Time: 2020-08-13T17:06:21.388531+08:00
...
# Plan: tidb_decode_plan('3gLYMAkyOF80CTAJMAlOL0EJMAl0aW1lOjUzNC40NDnCtXMsIGxvb3BzOjEJMS4wODk4NDM3NSBLQgEtPAoxCTMxXzgJMAkyLjY1ODYdAUw1CWRhdGE6U2VsZWN0aW9uXzcJMQlaFDQ4MC44OS5aADAyLCBycGMgbnVtOiAxCQwFhAA0AYQAMwkqkHByb2Mga2V5czo3CTIyNCBCeXRlcwlOL0EKMgkxXzcJMV8wCTJGhQA4bHQodGVzdC50LmEsIDEwBQEAKRGKCDBzLBXcAfsBThQzCTEwXzYFT6A4CXRhYmxlOnQsIGtlZXAgb3JkZXI6ZmFsc2UsIHN0YXRzOnBzZXVkb25QAA==')
update t set b=b+1 where a < 1000000;
# Time: 2020-08-13T17:06:21.390418+08:00
...
# Plan: tidb_decode_plan('2QLYMAkyOV80CTAJMAlOL0EJMAl0aW1lOjQwNS41NznCtXMsIGxvb3BzOjEJMS4xNDQ1MzEyNSBLQgEtPAoxCTMxXzgJMAkyLjY1ODYdAUw1CWRhdGE6U2VsZWN0aW9uXzcJMQlaFDM3NC4zMi5aADAyLCBycGMgbnVtOiAxCQwFhBQzNDAuODUJKohwcm9jIGtleXM6NwkyMjIgQnl0ZXMJTi9BCjIJMV83CTFfME6FADxsdCh0ZXN0LnQuYSwgMTApEYUEMHMZ1wH2AUkUMwkxMF82BUqgOAl0YWJsZTp0LCBrZWVwIG9yZGVyOmZhbHNlLCBzdGF0czpwc2V1ZG9uUAA=')
delete from t where a<10;

```

```sql
test> select tidb_decode_plan('ONwwCTI3XzEJMAkwCU4vQQkwCXRpbWU6My4wMjE1NDVtcywgbG9vcHM6MQkyMTUgQnl0ZXMJTi9BCg==');
+--------------------------------------------------------------------------------------------------------------+
| tidb_decode_plan('ONwwCTI3XzEJMAkwCU4vQQkwCXRpbWU6My4wMjE1NDVtcywgbG9vcHM6MQkyMTUgQnl0ZXMJTi9BCg==')         |
+--------------------------------------------------------------------------------------------------------------+
|     id          task    estRows    operator info    actRows    execution info              memory       disk |
|     Insert_1    root    0          N/A              0          time:3.021545ms, loops:1    215 Bytes    N/A  |
+--------------------------------------------------------------------------------------------------------------+
1 row in set
Time: 0.011s
test> select tidb_decode_plan('3gLYMAkyOF80CTAJMAlOL0EJMAl0aW1lOjUzNC40NDnCtXMsIGxvb3BzOjEJMS4wODk4NDM3NSBLQgEtPAoxCTMxXzgJMAkyLjY1ODYdAUw1CWRhdGE6U2VsZWN0aW9uXzcJMQlaFDQ4MC44OS5aADAyLCBycGMgbnVtOiAxCQwFhAA0AYQAMwkqkHByb2Mga2V5czo3CTIyNCBCeXRlcwlOL0EKMgkxXzcJMV8wCTJGhQA4bHQodGVzdC50LmEsIDEwBQEAKRGKCDBzLBXcAfsBThQzCTEwXzYFT6A4CXRhYmxlOnQsIGtlZXAgb3JkZXI6ZmFsc2UsIHN0YXRzOnBzZXVkb25QAA==');
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_decode_plan('3gLYMAkyOF80CTAJMAlOL0EJMAl0aW1lOjUzNC40NDnCtXMsIGxvb3BzOjEJMS4wODk4NDM3NSBLQgEtPAoxCTMxXzgJMAkyLjY1ODYdAUw1CWRhdGE6U2VsZWN0aW9uXzcJMQlaFDQ4MC44OS5aADAyLCBycGMgbnVtOiAxCQwFhAA0AYQAMwkqkHByb2Mga2V5czo3CTIyNCBCeXRlcwlOL0EKMgkxXzcJMV8wCTJGhQ |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|     id                   task         estRows               operator info                              actRows    execution info                                                            memory           disk                                                |
|     Update_4             root         0                     N/A                                        0          time:534.449µs, loops:1                                                  1.08984375 KB    N/A                                                  |
|     └─TableReader_8      root         2.6586666666666665    data:Selection_7                           1          time:480.899µs, loops:2, rpc num: 1, rpc time:434.439µs, proc keys:7    224 Bytes        N/A                                                   |
|       └─Selection_7      cop[tikv]    2.6586666666666665    lt(test.t.a, 1000000)                      1          time:0s, loops:1                                                          N/A              N/A                                                 |
|         └─TableScan_6    cop[tikv]    8                     table:t, keep order:false, stats:pseudo    1          time:0s, loops:1                                                          N/A              N/A                                                 |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set
Time: 0.011s
test> select tidb_decode_plan('2QLYMAkyOV80CTAJMAlOL0EJMAl0aW1lOjQwNS41NznCtXMsIGxvb3BzOjEJMS4xNDQ1MzEyNSBLQgEtPAoxCTMxXzgJMAkyLjY1ODYdAUw1CWRhdGE6U2VsZWN0aW9uXzcJMQlaFDM3NC4zMi5aADAyLCBycGMgbnVtOiAxCQwFhBQzNDAuODUJKohwcm9jIGtleXM6NwkyMjIgQnl0ZXMJTi9BCjIJMV83CTFfME6FADxsdCh0ZXN0LnQuYSwgMTApEYUEMHMZ1wH2AUkUMwkxMF82BUqgOAl0YWJsZTp0LCBrZWVwIG9yZGVyOmZhbHNlLCBzdGF0czpwc2V1ZG9uUAA=');
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_decode_plan('2QLYMAkyOV80CTAJMAlOL0EJMAl0aW1lOjQwNS41NznCtXMsIGxvb3BzOjEJMS4xNDQ1MzEyNSBLQgEtPAoxCTMxXzgJMAkyLjY1ODYdAUw1CWRhdGE6U2VsZWN0aW9uXzcJMQlaFDM3NC4zMi5aADAyLCBycGMgbnVtOiAxCQwFhBQzNDAuODUJKohwcm9jIGtleXM6NwkyMjIgQnl0ZXMJTi9BCjIJMV83CTFfME6FAD |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|     id                   task         estRows               operator info                              actRows    execution info                                                            memory           disk                                                |
|     Delete_4             root         0                     N/A                                        0          time:405.579µs, loops:1                                                  1.14453125 KB    N/A                                                  |
|     └─TableReader_8      root         2.6586666666666665    data:Selection_7                           1          time:374.329µs, loops:2, rpc num: 1, rpc time:340.859µs, proc keys:7    222 Bytes        N/A                                                   |
|       └─Selection_7      cop[tikv]    2.6586666666666665    lt(test.t.a, 10)                           1          time:0s, loops:1                                                          N/A              N/A                                                 |
|         └─TableScan_6    cop[tikv]    8                     table:t, keep order:false, stats:pseudo    1          time:0s, loops:1                                                          N/A              N/A                                                 |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

#### Attention

**Currently, the `insert/update/delete` executor runtime information doesn't contain the transaction commit duration**

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

-  planner: encode insert/delete/update plan in slow log plan field.

### CODE REVIEW

**Review by AilinKid — COMMENTED** [review]
pls resolve the conflicts

**Review by zz-jason — COMMENTED** [review]
@crazycs520 please resolve conflicts and fix CI.

**Review by tangenta — COMMENTED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]
LGTM

**Pull request merged**
