### PR TITLE
metrics: rename `CriticalErrorCount` metrics to `BinlogErrorCount`

### PR DESCRIPTION
**Pull request by imtbkcat**
### What problem does this PR solve? 
`CriticalErrorCount` will increase only when there is some error with binlog. So, rename it to `BinlogErrorCount` is better.

### What is changed and how it works?

Rename `CriticalErrorCount` to `BinlogErrorCount`

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported variable/fields change

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the `tidb-ansible` repository

Release note

### CODE REVIEW

**Comment by shenli** [comment]
Do we need to update the alert rule and document?

**Comment by imtbkcat** [comment]
@shenli yes

**Comment by imtbkcat** [comment]
tidb-ansible pr: https://github.com/pingcap/tidb-ansible/pull/1005

**Comment by jackysp** [comment]
PM said that he changed his mind and only wanted to change the panel title of grafana, fearing compatibility issues. @imtbkcat @shenli

**Pull request closed without merging**
