### PR TITLE
search logs: update sysutil to support search logs include invalid lines (#18579)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #18579 to release-4.0

---

Signed-off-by: baurine <2008.hbl@gmail.com>

### What problem does this PR solve?

Related issues and PRs:

- https://github.com/pingcap-incubator/tidb-dashboard/issues/665
- https://github.com/pingcap/sysutil/pull/19
- https://github.com/tikv/tikv/pull/8224

Problem Summary:

- If the log files include invalid lines in the beginning or end, it will be skipped.
- If the log files include invalid lines in the middle, the lines will be ignored.

### What is changed and how it works?

What's Changed:

- Check at most 10 lines in the beginning or end to find the first valid line
- Treat the invalid line in the middle as a normal log with pre valid log time and level

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- Support search the log file even it includes some invalid lines

### CODE REVIEW

**Comment by breeswish** [comment]
@baurine Please resolve conflicts

**Comment by baurine** [comment]
> @baurine Please resolve conflicts

done!

**Comment by baurine** [comment]
weird, not sure why, I can't merge `pingcap:release-4.0` to `ti-srebot:release-4.0-b72e47e6db88` in my local, and I even can't checkout to `pingcap:release-4.0` branch by `git merge origin/release-4.0`, it told me:

```shell
> git remote -v
baurine git@github.com:baurine/tidb.git (fetch)
baurine git@github.com:baurine/tidb.git (push)
origin  git@github.com:pingcap/tidb.git (fetch)
origin  git@github.com:pingcap/tidb.git (push)
robot   git@github.com:ti-srebot/tidb.git (fetch)
robot   git@github.com:ti-srebot/tidb.git (push)

> git merge origin/release-4.0
merge: origin/release-4.0 - not something we can merge

> gcb tt origin/release-4.0
fatal: 'origin/release-4.0' is not a commit and a branch 'tt' cannot be created from it
```

**Comment by baurine** [comment]
Resolve it by adding a new https mode remote `upstream`:

```shell
> git remote add upstream https://github.com/pingcap/tidb.git
> git remote -v
baurine git@github.com:baurine/tidb.git (fetch)
baurine git@github.com:baurine/tidb.git (push)
origin  git@github.com:pingcap/tidb.git (fetch)
origin  git@github.com:pingcap/tidb.git (push)
robot   git@github.com:ti-srebot/tidb.git (fetch)
robot   git@github.com:ti-srebot/tidb.git (push)
upstream        https://github.com/pingcap/tidb.git (fetch)
upstream        https://github.com/pingcap/tidb.git (push)
> git fetch upstream
> git merge upstream/release-4.0
```

**Pull request merged**
