### PR TITLE
parser: merge back with history

### LINKED ISSUE #28454: parser migration: create the sub module
## Enhancement

refer to #28257

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #28454 

Problem Summary: Merge parser back with all history. Successor of #28455, which is closed by accident. All commits before https://github.com/pingcap/parser/commit/687005894c4edbc38a1bbf4e02c0c63127dfd209

Refer https://github.com/kubernetes/test-infra/pull/11979/files for `tide/merge-method-rebase` label, which will rebase all commits instead of squashing into one.

Repo generation scripts:

```
a.py:

msg = commit.message.decode("utf-8")
if msg.startswith("parser/"):
  msg = msg[7:]
msg = msg.lstrip()
msg = "[parser] " + msg
commit.message = msg.encode("utf-8")
```

```
git filter-repo --commit-callback "`cat ../a.py`" --to-subdirectory-filter  parser
```

Then git rebase pingcap/tidb#master will results in such a history.

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by xhebox** [comment]
/cc @zhouqiang-cl 

need the permission to allow tide to merge by rebase :thinking:

**Comment by xhebox** [comment]
/hold

Depends on pingcap/errors#39

**Comment by xhebox** [comment]
Depends on PingCAP-QE/ci#436, which remove the parser replace check in CI.

**Comment by Mini256** [comment]
@ti-chi-bot

**Comment by feitian124** [comment]
image

looks good, downloads 46M when pull.

**Pull request merged**
