### PR TITLE
stmtsummary: cache digest for prepared stmt and cached plan

### PR DESCRIPTION
**Pull request by bobotu**
### What problem does this PR solve?
图片

StatementSummary waste CPU to calculate the digest for prepared statements.

### What is changed and how it works?
Cache the normalized SQL and SQL digest for a prepared statement. If we enable plan cache it will also reuse the calculated digest for a cached plan.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM

**Comment by siddontang** [comment]
IMO, we should post a benchmark result or a new flame graph after the optimization here.

I am a little surprised that we merged this PR without these.

**Comment by bobotu** [comment]
@siddontang posted at https://github.com/pingcap/tidb/pull/15464#issuecomment-600963668

**Pull request merged**
