### PR TITLE
planner: fix partition table getting error result when select `TIKV_REGION_STATUS` with `table_id`.

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/37436

Problem Summary:
The partition table has multiple partition IDs, so only using the table ID isn't enough.

### What is changed and how it works?
Using all partition IDs to fix it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
```
CREATE TABLE employees (
    id INT NOT NULL,
    fname VARCHAR(30),
    lname VARCHAR(30),
    hired DATE NOT NULL DEFAULT '1970-01-01',
    separated DATE DEFAULT '9999-12-31',
    job_code INT,
    store_id INT NOT NULL
)

PARTITION BY RANGE (store_id) (
    PARTITION p0 VALUES LESS THAN (6),
    PARTITION p1 VALUES LESS THAN (11),
    PARTITION p2 VALUES LESS THAN (16),
    PARTITION p3 VALUES LESS THAN (21)
);

select * from INFORMATION_SCHEMA.TIKV_REGION_STATUS where table_id=68;
+-----------+--------------------------------------+--------------------------------------+----------+---------+------------+----------+----------+------------+----------------+---------------+---------------+------------+------------------+------------------+-------------------------+---------------------------+
| REGION_ID | START_KEY                            | END_KEY                              | TABLE_ID | DB_NAME | TABLE_NAME | IS_INDEX | INDEX_ID | INDEX_NAME | EPOCH_CONF_VER | EPOCH_VERSION | WRITTEN_BYTES | READ_BYTES | APPROXIMATE_SIZE | APPROXIMATE_KEYS | REPLICATIONSTATUS_STATE | REPLICATIONSTATUS_STATEID |
+-----------+--------------------------------------+--------------------------------------+----------+---------+------------+----------+----------+------------+----------------+---------------+---------------+------------+------------------+------------------+-------------------------+---------------------------+
|        72 | 7480000000000000FF4600000000000000F8 | 7480000000000000FF4700000000000000F8 |       68 | test    | employees  |        0 |     NULL | NULL       |              1 |            36 |             0 |          0 |                1 |                0 | NULL                    |                      NULL |
|        74 | 7480000000000000FF4700000000000000F8 | 7480000000000000FF4800000000000000F8 |       68 | test    | employees  |        0 |     NULL | NULL       |              1 |            37 |             0 |          0 |                1 |                0 | NULL                    |                      NULL |
|      8001 | 7480000000000000FF4800000000000000F8 | 7480000000000000FF4A00000000000000F8 |       68 | test    | employees  |        0 |     NULL | NULL       |              1 |            38 |             0 |          0 |                1 |                0 | NULL                    |                      NULL |
|        70 | 7480000000000000FF4500000000000000F8 | 7480000000000000FF4600000000000000F8 |       68 | test    | employees  |        0 |     NULL | NULL       |              1 |            35 |             0 |          0 |                1 |                0 | NULL                    |                      NULL |
+-----------+--------------------------------------+--------------------------------------+----------+---------+------------+----------+----------+------------+----------------+---------------+---------------+------------+------------------+------------------+-------------------------+---------------------------+
4 rows in set (0.01 sec)
```
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
planner: fix partition table getting error result when select `TIKV_REGION_STATUS` with `table_id`.
```

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @Yisaer @crazycs520

**Review by tiancaiamao — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]

**Pull request merged**
