### PR TITLE
executor: log when setting a global variable

### LINKED ISSUE #17091: UCP: print a log when setting global variable.
## Description

```mysql
mysql> set session max_execution_time=0;
Query OK, 0 rows affected (0.00 sec)
```

tidb-server prints a log.

```
[2020/05/11 16:16:09.210 +08:00] [INFO] [set.go:207] ["set session var"] [conn=1] [name=max_execution_time] [val=0]
```

But, 
```mysql
set global max_execution_time=0;
```

tidb-server prints nothing in log.

## Score

* 50

## Mentor(s)

* @SunRunAway 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* skills 1
* skills 1

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

### PR DESCRIPTION
**Pull request by niedhui**
### What problem does this PR solve?

Issue Number: close #17091 

Problem Summary:  log when setting a global variable

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
```
mysql> set session max_execution_time=0;
Query OK, 0 rows affected (0.00 sec)

mysql> set global max_execution_time=0;
Query OK, 0 rows affected (0.00 sec)
```

```
[2020/07/09 14:02:06.367 +08:00] [INFO] [set.go:216] ["set session var"] [conn=1] [name=max_execution_time] [val=0]
[2020/07/09 14:02:13.505 +08:00] [INFO] [set.go:216] ["set global var"] [conn=1] [name=max_execution_time] [val=0]

```

### Release note 

- No release note

### CODE REVIEW

**Comment by niedhui** [comment]
@sre-bot /run-all-tests

**Comment by niedhui** [comment]
@ti-srebot /run-all-tests

**Comment by kolbe** [comment]
I think logging all session variables is unnecessary and will lead to a lot of log spam, but I think logging changes to global variables is a good idea.

**Comment by nullnotnil** [comment]
> I think logging all session variables is unnecessary and will lead to a lot of log spam, but I think logging changes to global variables is a good idea.

Yeah, I might have misread the patch. Many connectors do this, it will create log spam for sure.

**Comment by SunRunAway** [comment]
> > I think logging all session variables is unnecessary and will lead to a lot of log spam, but I think logging changes to global variables is a good idea.
> 
> Yeah, I might have misread the patch. Many connectors do this, it will create log spam for sure.

Hi, I'm not sure if it's a real problem, I suggest we could open a new issue and paste some log from some real environment to prove it.
@nullnotnil @kolbe

**Comment by SunRunAway** [comment]
Because this PR only adds a log for global variable changing, I'll merge it firstly.

**Pull request merged**
