### PR TITLE
ddl: add missing ErrorCount++ when update Error

### PR DESCRIPTION
**Pull request by zhiqiangxu**
Just a missing bit of code.

### CODE REVIEW

**Comment by Deardrops** [comment]
@zhiqiangxu thanks for your contributing, could you add a test case in this PR?

**Comment by zhiqiangxu** [comment]
> @zhiqiangxu thanks for your contributing, could you add a test case in this PR?

It seems there's no test for `ErrorCount` yet, no idea how to test it -_-b

**Comment by Deardrops** [comment]
@zhiqiangxu zhiqiangxu/tidb#1 PTAL

**Comment by zhiqiangxu** [comment]
> @zhiqiangxu [zhiqiangxu#1](https://github.com/zhiqiangxu/tidb/pull/1) PTAL

wow, that's cool !

**Comment by Deardrops** [comment]
Here are some problem with run test cases parallel, I will take a look.

**Pull request merged**
