### PR TITLE
server: increase test coverage

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve? 
This PR increases test coverage of `server` package(from 57% to 62%), as well as fixes a tiny bug.

### What is changed and how it works?
 * fixed a potential panic in conn.go
 * added more tests in conn_test.go/util_test.go
 * added column_test.go/packetio_test.go

### Check List 

Tests 
 - Unit test
 - Integration test

### CODE REVIEW

**Comment by bb7133** [comment]
PTAL @lysu @tiancaiamao

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
