### PR TITLE
avoid very slow structure to interface type converation

### PR DESCRIPTION
**Pull request by ngaut**
## What is the type of the changes? (mandatory)
- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)
- Exist tests

##Does this PR affect documentation (docs/docs-cn) update? (mandatory)
- No

##Does this PR affect tidb-ansible update? (mandatory)
- No

##Does this PR need to be added to the release notes? (mandatory)
- No

## Benchmark result if necessary (optional)

go test -bench .
goos: linux
goarch: amd64
BenchmarkRowPointer-12        2000000000             0.65 ns/op
BenchmarkRow-12               50000000            33.4 ns/op
PASS

### CODE REVIEW

**Comment by ngaut** [comment]
```go

type IRow interface {
	Len() int
}

// Row represents a row of data, can be used to assess values.
type Row struct {
	c   *int
	idx int
}

// Len returns the number of values in the row.
func (r Row) Len() int {
	return 0
}

// Row represents a row of data, can be used to assess values.
type RowPointer struct {
	c   *int
	idx int
}

// Len returns the number of values in the row.
func (r *RowPointer) Len() int {
	return 0
}

var iface IRow
var row = Row{}
var rowpointer = &RowPointer{}

func BenchmarkRow(b *testing.B) {
	for i := 0; i < b.N; i++ {
		iface = row
	}
}

func BenchmarkRowPointer(b *testing.B) {
	for i := 0; i < b.N; i++ {
		iface = rowpointer
	}
}
```

**Comment by zz-jason** [comment]
@XuHuaiyu PTAL

**Comment by zz-jason** [comment]
LGTM

**Pull request merged**
