### PR TITLE
expression, types: "Flen" and "Decimal" of "TypeNewDecimal" should not be -1

### PR DESCRIPTION
**Pull request by zz-jason**
to #5522

### CODE REVIEW

**Comment by shenli** [comment]
Could you add a test case for the PR?

**Comment by coocood** [comment]
Please add the panic case in the mentioned issue.

**Comment by zz-jason** [comment]
@coocood It's already in sqllogical test, after this pr merged, https://github.com/pingcap/tidb/pull/5244 should not fail on that case

**Comment by coocood** [comment]
LGTM

**Pull request merged**
