### PR TITLE
server: set 'clientConn.ctx = nil' to clean the context when changeUser.

### LINKED ISSUE #33699: server: session variables was not changed when execute the mysql command 'ComChangeUser'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
- set some session variable 
- execute 'ComChangeUser'
- show the session variable , the values was the previous session setted(not the default values)

### 2. What did you expect to see? (Required)
show session variable should the default values.

### 3. What did you see instead (Required)
the values was the previous session setted

### 4. What is your TiDB version? (Required)

v5.3.0

### PR DESCRIPTION
**Pull request by knull-cn**
### What problem does this PR solve?

Issue Number: close #33699 

Problem Summary: session variable was not clean when changeUser.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by knull-cn** [comment]
/idc-jenkins-ci-tidb/check_dev_2

**Comment by knull-cn** [comment]
/run-idc-jenkins-ci-tidb/check_dev_2

**Review by jackysp — APPROVED** [review]
LGTM

**Comment by knull-cn** [comment]
@bb7133 PTAL
especially unit-test

**Review by youjiali1995 — APPROVED** [review]

**Comment by tiancaiamao** [comment]
This fix may introduce another bug https://github.com/pingcap/tidb/issues/33892 which is fixed by https://github.com/pingcap/tidb/pull/33894, so #33894 must be cherry-pick together with this one.

**Pull request merged**
