### PR TITLE
server: Return VECTOR as LONGTEXT for clients

### PR DESCRIPTION
**Pull request by EricZequan**
### What problem does this PR solve?

Issue Number: ref #54245 

Problem Summary:

### What changed and how does it work?
Some clients will throw errors when meeting unknown field types, like [go-sql-driver/mysql](https://github.com/go-sql-driver/mysql/blob/52c1917d99904701db2b0e4f14baffa948009cd7/packets.go#L1329). This PR makes VECTOR type return as LONGTEXT to maximize compatibility.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by breezewish** [comment]
Can you rebase this PR and exclude changes of https://github.com/pingcap/tidb/pull/55134 and https://github.com/pingcap/tidb/pull/55151? I think these PRs can be reviewed concurrently.

If you cannot make this PR atomic, i.e. only includes the changes of what it describes, then it cannot be reviewed.

**Review by breezewish — APPROVED** [review]
Good!

**Review by tangenta — APPROVED** [review]

**Pull request merged**
