### PR TITLE
topsql: improve performance in sysbench

### PR DESCRIPTION
**Pull request by breezewish**
### What problem does this PR solve?

Issue Number: ref #33377

Problem Summary: There are multiple string allocations in the hot path that causes performance to degrade.

### What is changed and how it works?

Use hack.String to reduce allocations in hot path.

**Benchmark:**

```shell
sysbench oltp_point_select run --mysql-host=127.0.0.1 --mysql-port=4000 --mysql-user=root --db-driver=mysql --mysql-db=test --threads=400 --time=1800 --report-interval=10
```

**Result:**

Performance impact: Reduced sysbench PointSelect from 9.74% to 8.95% (± 0.1%)

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

Manually tested with these payloads:

```shell
bin/loadgen payload normal-oltp --rows 1000000
bin/loadgen payload normal-oltp --db test2 --rows 1000000
# moments later, simulate an index drop to cause high load:
alter table t_normal_oltp drop index idx1;
alter table t_normal_oltp drop index idx0;
```
  
- [ ] No code  

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by zhongzc — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]

**Review by ngaut — APPROVED** [review]

**Review by ngaut — APPROVED** [review]

**Comment by breeswish** [comment]
I will re-test and re-bench this PR for the recent updates. After that, we can drive the merge of this PR.

**Review by zhongzc — APPROVED** [review]

**Comment by breeswish** [comment]
- Test and benchmark is finished, remove "hold" label.

- Currently this PR does not notably improves performance, and it involves with `hack.Xxx` functions, so that I also removed "cherry pick 6.0" label. Let's test it more carefully in the master branch.

@crazycs520 PTAL again.

I believe a better way is to move the `BinaryDigest` type into `parser` and use `BinaryDigest` everywhere in the Top SQL. In this way, the hacking transition can be reduced. cc @mornyx

**Comment by mornyx** [comment]
> I believe a better way is to move the `BinaryDigest` type into `parser` and use `BinaryDigest` everywhere in the Top SQL. In this way, the hacking transition can be reduced. cc @mornyx

It's reasonable, I'll handle it.

**Comment by breeswish** [comment]
> > I believe a better way is to move the `BinaryDigest` type into `parser` and use `BinaryDigest` everywhere in the Top SQL. In this way, the hacking transition can be reduced. cc @mornyx
> 
> It's reasonable, I'll handle it.

@mornyx I created a follow up PR for this in https://github.com/pingcap/tidb/pull/33520. I discovered one more allocation to reduce thanks to this refactoring..

**Pull request closed without merging**
