### PR TITLE
copr: Fix bug that mpp node availability detect does not work in some corner cases

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close pingcap/tics#3118 

Problem Summary:
As described in the issue.
### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:
The root cause is we detect the TiFlash node's availability in `balanceBatchCopTask`, but here is a shortcut in `balanceBatchCopTask` that if there is only one batchCopTask, it will return directly without balancing, which means the availability check is also skipped.
https://github.com/pingcap/tidb/blob/3c9c01e960cf9f0ebca59da14289e3f49375c561/store/copr/batch_coprocessor.go#L107-L111

This pr fix this by not trigger the shortcut if the query is mpp query.

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 
```release-note 
Fix bug that mpp node availability detect does not work in some corner cases
```

### CODE REVIEW

**Review by fzhedu — APPROVED** [review]
/LGTM

**Review by hanfei1991 — APPROVED** [review]

**Pull request merged**
