### PR TITLE
*: fix the flen type datetime for union/case-when/control-funcs (#30588)

### LINKED ISSUE #29498: concat(ifnull(time(3)) returns different results from MySQL
## Bug Report
SET TIMESTAMP doesn't take effect. 

### 1. Minimal reproduce step (Required)
```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (t3 TIME(3), d DATE);
INSERT INTO t1 VALUES ('00:00:00.567', '2002-01-01');
SELECT CONCAT(IFNULL(t3, d)) AS col1 FROM t1;
```
### 2. What did you expect to see? (Required)
```sql
+-------------------------+
| col1                    |
+-------------------------+
| 2019-03-11 00:00:00.567 |
+-------------------------+
```

### 3. What did you see instead (Required)
```sql
+----------------+
| col1           |
+----------------+
| 2021-11-04 00: |
+----------------+
```
### 4. What is your TiDB version? (Required)
```sql
+-------------------------+--------------------------------------------------------------------------+
| Variable_name           | Value                                                                    |
+-------------------------+--------------------------------------------------------------------------+
| innodb_version          | 5.6.25                                                                   |
| protocol_version        | 10                                                                       |
| tidb_analyze_version    | 2                                                                        |
| tidb_row_format_version | 2                                                                        |
| tls_version             | TLSv1,TLSv1.1,TLSv1.2                                                    |
| version                 | 5.7.25-TiDB-v5.2.2                                                       |
| version_comment         | TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible |
| version_compile_machine | x86_64                                                                   |
| version_compile_os      | osx10.8                                                                  |
+-------------------------+--------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #30588 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/30833
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/30833:release-5.3-8e11e0367f02
```

---

### What problem does this PR solve?

Issue Number: close #29498

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
bugfix: concat(ifnull(time(3)) returns different results from MySQL
```
<https://github.com/pingcap/tidb/issues/29498>

### CODE REVIEW

**Comment by guo-shaoge** [comment]
@bestwoody maybe it's time to merge this pr. A new version is about to release in a few days. Thanks!

**Review by guo-shaoge — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
