### PR TITLE
expression: fix data race when simpleRewriter rewrite ast.ColumnNameExpr concurrently

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Problem Summary:

```
[2020-05-22T01:32:46.732Z] ==================
[2020-05-22T01:32:46.732Z] WARNING: DATA RACE
[2020-05-22T01:32:46.732Z] Read at 0x00c00eacc170 by goroutine 431:
[2020-05-22T01:32:46.732Z]   github.com/pingcap/parser/ast.(*ColumnNameExpr).Accept(
[2020-05-22T01:32:46.732Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20200521064712-8dc0fb6ce6f4/ast/expressions.go:588 +0x99
[2020-05-22T01:32:46.732Z]   github.com/pingcap/tidb/expression.RewriteSimpleExprWithNames()
[2020-05-22T01:32:46.732Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/simple_rewriter.go:150 +0x182
[2020-05-22T01:32:46.732Z]   github.com/pingcap/tidb/planner/core.makeRangeColumnPruner()
[2020-05-22T01:32:46.732Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:768 +0x20a
[2020-05-22T01:32:46.732Z]   github.com/pingcap/tidb/planner/core.(*partitionProcessor).pruneRangeColumnsPartition()
[2020-05-22T01:32:46.732Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:750 +0x137
[2020-05-22T01:32:46.732Z]   github.com/pingcap/tidb/planner/core.(*partitionProcessor).pruneRangePartition()
[2020-05-22T01:32:46.732Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:340 +0x6ba
[2020-05-22T01:32:46.732Z]   github.com/pingcap/tidb/planner/core.(*partitionProcessor).prune()
[2020-05-22T01:32:46.732Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:161 +0x116
[2020-05-22T01:32:46.732Z]   github.com/pingcap/tidb/planner/core.(*partitionProcessor).rewriteDataSource()
[2020-05-22T01:32:46.733Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:57 +0xa22
[2020-05-22T01:32:46.733Z]   github.com/pingcap/tidb/planner/core.(*partitionProcessor).rewriteDataSource()
[2020-05-22T01:32:46.733Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:85 +0x130
[2020-05-22T01:32:46.733Z]   github.com/pingcap/tidb/planner/core.(*partitionProcessor).rewriteDataSource()
[2020-05-22T01:32:46.733Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:85 +0x130
[2020-05-22T01:32:46.733Z]   github.com/pingcap/tidb/planner/core.(*partitionProcessor).optimize()
[2020-05-22T01:32:46.733Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:50 +0x56
[2020-05-22T01:32:46.733Z]   github.com/pingcap/tidb/planner/core.logicalOptimize()
[2020-05-22T01:32:46.733Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:159 +0x1de
[2020-05-22T01:32:46.733Z]   github.com/pingcap/tidb/planner/core.DoOptimize()
[2020-05-22T01:32:46.733Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:128 +0x9b
[2020-05-22T01:32:46.733Z]   github.com/pingcap/tidb/planner.optimize()
[2020-05-22T01:32:46.733Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/optimize.go:189 +0x7d4
[2020-05-22T01:32:46.733Z]   github.com/pingcap/tidb/planner.Optimize()
[2020-05-22T01:32:46.733Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/optimize.go:63 +0x307
[2020-05-22T01:32:46.733Z]   github.com/pingcap/tidb/executor.(*Compiler).Compile()
[2020-05-22T01:32:46.733Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/compiler.go:61 +0x298
[2020-05-22T01:32:46.733Z]   github.com/pingcap/tidb/session.(*session).execute()
[2020-05-22T01:32:46.733Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1129 +0x887
[2020-05-22T01:32:46.733Z]   github.com/pingcap/tidb/session.(*session).Execute()
...

[2020-05-22T01:32:46.735Z] Previous write at 0x00c00eacc170 by goroutine 384:
[2020-05-22T01:32:46.735Z]   github.com/pingcap/parser/ast.(*ColumnNameExpr).Accept()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20200521064712-8dc0fb6ce6f4/ast/expressions.go:592 +0xfa
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/expression.RewriteSimpleExprWithNames()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/simple_rewriter.go:150 +0x182
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/planner/core.makeRangeColumnPruner()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:768 +0x20a
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/planner/core.(*partitionProcessor).pruneRangeColumnsPartition()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:750 +0x137
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/planner/core.(*partitionProcessor).pruneRangePartition()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:340 +0x6ba
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/planner/core.(*partitionProcessor).prune()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:161 +0x116
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/planner/core.(*partitionProcessor).rewriteDataSource()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:57 +0xa22
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/planner/core.(*partitionProcessor).rewriteDataSource()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:85 +0x130
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/planner/core.(*partitionProcessor).optimize()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/rule_partition_processor.go:50 +0x56
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/planner/core.logicalOptimize()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:159 +0x1de
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/planner/core.DoOptimize()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:128 +0x9b
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDelete()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:3625 +0xa70
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/planbuilder.go:471 +0xeeb
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/planner.optimize()
[2020-05-22T01:32:46.735Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/optimize.go:150 +0x224
[2020-05-22T01:32:46.735Z]   github.com/pingcap/tidb/planner.Optimize()
```

This data race is introduced by the performance optimization https://github.com/pingcap/tidb/pull/17249

### What is changed and how it works?

What's Changed:

How it Works:

`simpleRewriter.Accept(ast.Node)` is not thread safe.

~~At least, I want it to be thread safe for `ColumnNameExpr`, because partition expression depends on it.~~   ... avoid using it.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

I'm not including the test code in this PR but I've verified this change:

```
+func (s *testPartitionPruningSuite) TestXXX(c *C) {
+       p := parser.New()
+        stmt, err := p.ParseOneStmt("create table t (a int, b int)", "", "")
+        c.Assert(err, IsNil)
+        sctx := mock.NewContext()
+        tblInfo, err := ddl.BuildTableInfoFromAST(stmt.(*ast.CreateTableStmt))
+        c.Assert(err, IsNil)
+        columns, names := expression.ColumnInfos2ColumnsAndNames(sctx, model.NewCIStr("t"), tblInfo.Name, tblInfo.Columns)
+        schema := expression.NewSchema(columns...)
+
+       col, err := parseExpr(p, "a")
+       c.Assert(err, IsNil)
+
+       var wg sync.WaitGroup   
+       wg.Add(10)
+       for i:=0; i<10; i++ {
+               go func() {
+                       for j :=0; j<200; j++ {
+                               expression.RewriteSimpleExprWithNames(sctx, col, schema, names)
+                       }
+                       wg.Done()
+               }()
+       }
+       wg.Wait()
+}
+
+func parseExpr(p *parser.Parser, exprStr string) (ast.ExprNode, error) {
+       exprStr = "select " + exprStr
+       stmts, _, err := p.Parse(exprStr, "", "")
+       if err != nil {
+               return nil, err
+       }
+       fields := stmts[0].(*ast.SelectStmt).Fields.Fields
+       return fields[0].Expr, nil
+}
```

### Release note 

- No release note

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @XuHuaiyu @imtbkcat

**Comment by XuHuaiyu** [comment]
1. Why not copy `rangeColumnPruner.partCol` in `makeRangeColumnPruner`
2. We need to rename `makeRangeColumnPruner` to `makeRangeColumnsPruner`

**Comment by tiancaiamao** [comment]
> 1. Why not copy `rangeColumnPruner.partCol` in `makeRangeColumnPruner`

Because `partCol` is a ast.Node and doesn't have a `Clone()` method @XuHuaiyu

**Comment by tiancaiamao** [comment]
https://github.com/pingcap/tidb/issues/16369

/rebuild

**Pull request merged**
