### PR TITLE
statistics: hide the `tidb_analyze_version` before it's GA (#23327)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23327 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23333
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23333:release-5.0-23227ea4a026
```

---

### What problem does this PR solve?

Problem Summary: hide the variable before it's GA

### Check List 

Tests 

- Unit test

### Release note 

- `No release note`

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]
/LGTM

**Pull request merged**
