### PR TITLE
ddl: refactor bundle[2/2] [6/6]

### LINKED ISSUE #22414: ddl: refactor placement package
### Background

There are always lots of regressions in DDL placement packages and it usages. Placement rules in SQL heavily relies on manual test due to the lack of PD in unit tests. It is really bad at tests.

### Solutions

Refactor the whole placement package:

1. Move more code into the placement package, thus reduce the tests that needs to be manually verified.
2. Add more unit tests.

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #22414

Problem Summary: This PR refactor the placement packages in a way that is describe in Solutions section of the issue.

After separated, the modification is:

1. `GetLeaderDCByBundle` is moved as a method of `Bundle`.
2. `ObjectIDFromGroupID` is moved as a method of `Bundle`.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Comment by xhebox** [comment]
LGT3 is removed, due to this PR is splitted into 6 parts. And the other 5 parts has been merged. Now there are only 300 lines left.

**Review by djshow832 — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]
LGTM

**Pull request merged**
