### PR TITLE
ddl: fix panic when ddl close if ddl never started

### LINKED ISSUE #32309: connected to TiDB after TiDB closed cause TiDB panic
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I meet this in some test case, see following TiDB log:

```sql
[2022/02/14 13:11:19.752 +08:00] [INFO] [domain.go:1171] ["TelemetryReportLoop exited."]
[2022/02/14 13:11:19.752 +08:00] [INFO] [handle_hist.go:143] ["SubLoadWorker exited."]
[2022/02/14 13:11:19.752 +08:00] [INFO] [domain.go:1138] ["handleEvolvePlanTasksLoop exited."]
[2022/02/14 13:11:19.752 +08:00] [INFO] [handle_hist.go:143] ["SubLoadWorker exited."]
[2022/02/14 13:11:19.752 +08:00] [INFO] [domain.go:1788] ["renew lease goroutine exited."]
[2022/02/14 13:11:19.752 +08:00] [INFO] [handle_hist.go:143] ["SubLoadWorker exited."]
[2022/02/14 13:11:19.752 +08:00] [INFO] [domain.go:1223] ["PlanReplayerLoop exited."]
[2022/02/14 13:11:19.752 +08:00] [INFO] [domain.go:535] ["globalConfigSyncerKeeper exited."]
[2022/02/14 13:11:19.752 +08:00] [INFO] [domain.go:1017] ["LoadSysVarCacheLoop exited."]
[2022/02/14 13:11:19.752 +08:00] [INFO] [domain.go:1095] ["globalBindHandleWorkerLoop exited."]
[2022/02/14 13:11:19.752 +08:00] [INFO] [domain.go:558] ["topologySyncerKeeper exited."]
[2022/02/14 13:11:19.752 +08:00] [INFO] [domain.go:510] ["infoSyncerKeeper exited."]
[2022/02/14 13:11:19.752 +08:00] [INFO] [domain.go:967] ["loadPrivilegeInLoop exited."]
[2022/02/14 13:11:19.752 +08:00] [INFO] [domain.go:716] ["domain closed"] ["take time"=197.28µs]
[2022/02/14 13:11:19.752 +08:00] [INFO] [server.go:457] ["setting tidb-server to report unhealthy (shutting-down)"]
[2022/02/14 13:11:19.752 +08:00] [INFO] [tidb.go:72] ["new domain"] [store=f45630fe-aa4e-4736-9d29-6975deb6701f] ["ddl lease"=0s] ["stats lease"=-1ns] ["index usage sync lease"=0s]
[2022/02/14 13:11:19.752 +08:00] [ERROR] [http_status.go:475] ["start status/rpc server error"] [error="accept tcp 127.0.0.1:63041: use of closed network connection"] [stack="github.com/pingcap/tidb/server.(*Server).startStatusServerAndRPCServer\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/server/http_status.go:475\ngithub.com/pingcap/tidb/server.(*Server).start
HTTPServer\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/server/http_status.go:446"]
[2022/02/14 13:11:19.752 +08:00] [ERROR] [http_status.go:465] ["grpc server error"] [error="mux: listener closed"] [stack="github.com/pingcap/tidb/server.(*Server).startStatusServerAndRPCServer.func1\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/server/http_status.go:465\ngithub.com/pingcap/tidb/util.WithRecovery\n\t/Users/cs/code/goread/src/github.com/pingcap/ti
db/util/misc.go:100"]
[2022/02/14 13:11:19.752 +08:00] [ERROR] [http_status.go:470] ["http server error"] [error="http: Server closed"] [stack="github.com/pingcap/tidb/server.(*Server).startStatusServerAndRPCServer.func2\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/server/http_status.go:470\ngithub.com/pingcap/tidb/util.WithRecovery\n\t/Users/cs/code/goread/src/github.com/pingcap/tid
b/util/misc.go:100"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x559fe17]

goroutine 6989 [running]:
github.com/pingcap/tidb/ddl.(*ddl).close(0xc00791e700)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/ddl/ddl.go:421 +0x77
github.com/pingcap/tidb/ddl.(*ddl).Stop(0xc00791e700, 0x0, 0x0)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/ddl/ddl.go:346 +0x8a
github.com/pingcap/tidb/domain.(*Domain).Close(0xc00730e500)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/domain/domain.go:695 +0x377
github.com/pingcap/tidb/session.(*domainMap).Get.func1(0xc0055be2d0, 0x0, 0x72d18e0)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/session/tidb.go:86 +0x69e
github.com/pingcap/tidb/util.RunWithRetry(0x1e, 0x1f4, 0xc007c729e0, 0x24, 0x90ea0a0)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/util/misc.go:65 +0x7f
github.com/pingcap/tidb/session.(*domainMap).Get(0x90ad250, 0x73647f0, 0xc00080c2c0, 0xc00730e500, 0x0, 0x0)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/session/tidb.go:71 +0x1f0
github.com/pingcap/tidb/session.createSessionWithOpt(0x73647f0, 0xc00080c2c0, 0x0, 0xc004fa3cc0, 0x4b, 0x1)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/session/session.go:2923 +0x59
github.com/pingcap/tidb/session.CreateSessionWithOpt(0x73647f0, 0xc00080c2c0, 0x0, 0x687f260, 0xa695088, 0xc007cb1e10, 0xc000a6ecb0)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/session/session.go:2656 +0x45
github.com/pingcap/tidb/session.CreateSession(...)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/session/session.go:2650
github.com/pingcap/tidb/server.(*TiDBDriver).OpenCtx(0xc006c0f640, 0x4b, 0x2d000aa28d, 0xc007c0170c, 0x4, 0x0, 0x690fa80, 0x203002, 0x400ec3b)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/driver_tidb.go:184 +0x45
github.com/pingcap/tidb/server.(*clientConn).openSession(0xc008066c80, 0x40889c6, 0x408af60)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:798 +0x92
github.com/pingcap/tidb/server.(*clientConn).checkAuthPlugin(0xc008066c80, 0x7328b90, 0xc008513560, 0xc007c73578, 0x7328b90, 0xc008513560, 0xc007c0b8b0, 0x41, 0x41)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:850 +0xd7b
github.com/pingcap/tidb/server.(*clientConn).handleAuthPlugin(0xc008066c80, 0x7328b90, 0xc008513560, 0xc007c73578, 0x41, 0x41)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:718 +0x7c
github.com/pingcap/tidb/server.(*clientConn).readOptionalSSLRequestAndHandshakeResponse(0xc008066c80, 0x7328b90, 0xc008513560, 0x0, 0x0)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:692 +0x289
github.com/pingcap/tidb/server.(*clientConn).handshake(0xc008066c80, 0x7328b90, 0xc008513560, 0x7328b90, 0xc008513560)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:265 +0x41a
github.com/pingcap/tidb/server.(*Server).onConn(0xc006ad1930, 0xc008066c80)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/server.go:500 +0xa9
created by github.com/pingcap/tidb/server.(*Server).startNetworkListener
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/server.go:451 +0x91c
exit status 2
FAIL    github.com/pingcap/tidb/server  5.211s
```

### 4. What is your TiDB version? (Required)

```
master: c0244a380b2e0f63c1f9a813011ce87f97740ac4
```

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Issue Number: close #32309

```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x559fe17]

goroutine 6989 [running]:
github.com/pingcap/tidb/ddl.(*ddl).close(0xc00791e700)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/ddl/ddl.go:421 +0x77
github.com/pingcap/tidb/ddl.(*ddl).Stop(0xc00791e700, 0x0, 0x0)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/ddl/ddl.go:346 +0x8a
github.com/pingcap/tidb/domain.(*Domain).Close(0xc00730e500)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/domain/domain.go:695 +0x377
github.com/pingcap/tidb/session.(*domainMap).Get.func1(0xc0055be2d0, 0x0, 0x72d18e0)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/session/tidb.go:86 +0x69e
github.com/pingcap/tidb/util.RunWithRetry(0x1e, 0x1f4, 0xc007c729e0, 0x24, 0x90ea0a0)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/util/misc.go:65 +0x7f
github.com/pingcap/tidb/session.(*domainMap).Get(0x90ad250, 0x73647f0, 0xc00080c2c0, 0xc00730e500, 0x0, 0x0)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/session/tidb.go:71 +0x1f0
github.com/pingcap/tidb/session.createSessionWithOpt(0x73647f0, 0xc00080c2c0, 0x0, 0xc004fa3cc0, 0x4b, 0x1)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/session/session.go:2923 +0x59
github.com/pingcap/tidb/session.CreateSessionWithOpt(0x73647f0, 0xc00080c2c0, 0x0, 0x687f260, 0xa695088, 0xc007cb1e10, 0xc000a6ecb0)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/session/session.go:2656 +0x45
github.com/pingcap/tidb/session.CreateSession(...)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/session/session.go:2650
github.com/pingcap/tidb/server.(*TiDBDriver).OpenCtx(0xc006c0f640, 0x4b, 0x2d000aa28d, 0xc007c0170c, 0x4, 0x0, 0x690fa80, 0x203002, 0x400ec3b)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/driver_tidb.go:184 +0x45
github.com/pingcap/tidb/server.(*clientConn).openSession(0xc008066c80, 0x40889c6, 0x408af60)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:798 +0x92
github.com/pingcap/tidb/server.(*clientConn).checkAuthPlugin(0xc008066c80, 0x7328b90, 0xc008513560, 0xc007c73578, 0x7328b90, 0xc008513560, 0xc007c0b8b0, 0x41, 0x41)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:850 +0xd7b
github.com/pingcap/tidb/server.(*clientConn).handleAuthPlugin(0xc008066c80, 0x7328b90, 0xc008513560, 0xc007c73578, 0x41, 0x41)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:718 +0x7c
github.com/pingcap/tidb/server.(*clientConn).readOptionalSSLRequestAndHandshakeResponse(0xc008066c80, 0x7328b90, 0xc008513560, 0x0, 0x0)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:692 +0x289
github.com/pingcap/tidb/server.(*clientConn).handshake(0xc008066c80, 0x7328b90, 0xc008513560, 0x7328b90, 0xc008513560)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:265 +0x41a
github.com/pingcap/tidb/server.(*Server).onConn(0xc006ad1930, 0xc008066c80)
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/server.go:500 +0xa9
created by github.com/pingcap/tidb/server.(*Server).startNetworkListener
        /Users/cs/code/goread/src/github.com/pingcap/tidb/server/server.go:451 +0x91c
```

Tests 

- N/A

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@zimulala @tangenta PTAL

**Review by tangenta — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
