### PR TITLE
lightning: recover status from checkpoint after index engine closed

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

https://github.com/pingcap/tiflow/pull/7702#issuecomment-1325974954

### What is changed and how it works?

Seems in all logic, both tidb backend and local backend, we treat data or data engine write to TiKV as finished. So when recover from checkpoint, if the whole table fails after finish data part and we are resumed from checkpoint, add all data size to finished size

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by D3Hunter — APPROVED** [review]

**Comment by okJiang** [comment]
fix here? https://github.com/pingcap/tiflow/blob/e0bce5e400144a499ae08f39f4eae7ba3f2f38e1/engine/test/integration_tests/dm_full_mode/run.sh#L67-L68

**Comment by lance6716** [comment]
> fix here? https://github.com/pingcap/tiflow/blob/e0bce5e400144a499ae08f39f4eae7ba3f2f38e1/engine/test/integration_tests/dm_full_mode/run.sh#L67-L68

yes

**Comment by okJiang** [comment]
> > fix here? [pingcap/tiflow@`e0bce5e`/engine/test/integration_tests/dm_full_mode/run.sh#L67-L68](https://github.com/pingcap/tiflow/blob/e0bce5e400144a499ae08f39f4eae7ba3f2f38e1/engine/test/integration_tests/dm_full_mode/run.sh#L67-L68)
> 
> yes

But you still kept this TODO. Please remove it in this pr.

**Comment by lance6716** [comment]
> > > fix here? [pingcap/tiflow@`e0bce5e`/engine/test/integration_tests/dm_full_mode/run.sh#L67-L68](https://github.com/pingcap/tiflow/blob/e0bce5e400144a499ae08f39f4eae7ba3f2f38e1/engine/test/integration_tests/dm_full_mode/run.sh#L67-L68)
> > 
> > 
> > yes
> 
> But you still kept this TODO. Please remove it in this pr.

that's two repo, tidb and tiflow

**Comment by okJiang** [comment]
> > > > fix here? [pingcap/tiflow@`e0bce5e`/engine/test/integration_tests/dm_full_mode/run.sh#L67-L68](https://github.com/pingcap/tiflow/blob/e0bce5e400144a499ae08f39f4eae7ba3f2f38e1/engine/test/integration_tests/dm_full_mode/run.sh#L67-L68)
> > > 
> > > 
> > > yes
> > 
> > 
> > But you still kept this TODO. Please remove it in this pr.
> 
> that's two repo, tidb and tiflow

I am sorry I mixed them😂.

**Review by okJiang — APPROVED** [review]

**Pull request merged**
