### PR TITLE
planner: fix the issue that UnionScan returns wrong results in dynamic mode

### LINKED ISSUE #26719: union scan result error when using dynamic mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
drop table if exists t;
set tidb_partition_prune_mode=dynamic;

CREATE TABLE t( id INT NOT NULL, store_id INT NOT NULL) PARTITION BY RANGE (store_id) ( 
  PARTITION p0 VALUES LESS THAN (6), 
  PARTITION p1 VALUES LESS THAN (11), 
  PARTITION p2 VALUES LESS THAN (16));

insert into t values(1,1), (5,5);
insert into t values(-1,-10), (10,10), (11, 12);
begin;
delete from t where id in(1);
insert into t values(1, 1);
delete from t where id in(1);
select * from t PARTITION(p0) order by id;
commit;
```

### 2. What did you expect to see? (Required)
```
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> delete from t where id in(1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t values(1, 1);
Query OK, 1 row affected (0.00 sec)

mysql> delete from t where id in(1);
Query OK, 2 rows affected (0.00 sec)

mysql> select * from t PARTITION(p0) order by id;
+----+----------+
| id | store_id |
+----+----------+
| -1 |      -10 |
|  5 |        5 |
+----+----------+
2 rows in set (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.00 sec)
```

### 3. What did you see instead (Required)
release-5.0 & release-5.1 & master
```
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> delete from t where id in(1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t values(1, 1);
Query OK, 1 row affected (0.00 sec)

mysql> delete from t where id in(1);
Query OK, 2 rows affected (0.00 sec)

mysql> select * from t PARTITION(p0) order by id;
+----+----------+
| id | store_id |
+----+----------+
| -1 |      -10 |
|  1 |        1 |
|  5 |        5 |
+----+----------+
3 rows in set (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.1.0-66-g797bddd25
Edition: Community
Git Commit Hash: 797bddd25310ed42f0791c8eccb78be8cce2f502
Git Branch: release-5.1
UTC Build Time: 2021-07-29 03:28:11
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #26719 

Problem Summary: planner: fix the issue that UnionScan returns wrong results in dynamic mode

### What is changed and how it works?

planner: fix the issue that UnionScan returns wrong results in dynamic mode

Please see https://github.com/pingcap/tidb/issues/26719 for more details.

### Check List 

Tests 

- [x] Unit test

### Release note 

```release-note
planner: fix the issue that UnionScan returns wrong results in dynamic mode
```

### CODE REVIEW

**Comment by tiancaiamao** [comment]
/LGTM

This issue is first fixed in https://github.com/pingcap/tidb/pull/8871 in the static partition prune mode
The key point is that the `UnionScan` should follow the `TableReader`, instead of `PartitionUnion`...

**Review by tiancaiamao — APPROVED** [review]

**Review by rebelice — APPROVED** [review]

**Comment by qw4990** [comment]
wait for https://github.com/pingcap/tidb/pull/26839

**Review by Reminiscent — APPROVED** [review]

**Pull request merged**
