### PR TITLE
load data: time and log for different phase, use err group in chunk_process

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: ref #42930 

Problem Summary:

### What is changed and how it works?
- time and log each sub phase
- use error group in chunk_process

### Check List

Tests 

existing ut is enough
- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  - return err on encode or deliver loop, make sure encoder do exist with err
  - return err and check log
  - normal run check log
```log
[2023/04/20 16:43:11.388 +08:00] [INFO] [backend.go:347] ["import start"] [engineTag=`load_data`.`t`:-1] [engineUUID=4c983745-cf08-5412-9f4a-17b9f1b1e2e3] [retryCnt=0]
[2023/04/20 16:43:11.388 +08:00] [INFO] [backend.go:362] ["cleanup start"] [engineTag=`load_data`.`t`:-1] [engineUUID=4c983745-cf08-5412-9f4a-17b9f1b1e2e3]
[2023/04/20 16:43:11.403 +08:00] [INFO] [table_import.go:298] ["post process start"] [table=`load_data`.`t`]
[2023/04/20 16:43:11.403 +08:00] [INFO] [table_import.go:310] ["checksum start"] [table=`load_data`.`t`]
```
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by D3Hunter** [comment]
@lance6716 @GMHDBJD

**Comment by D3Hunter** [comment]
@lance6716 @GMHDBJD

**Comment by D3Hunter** [comment]
@lance6716

**Comment by D3Hunter** [comment]
@gozssky ptal

**Review by gozssky — APPROVED** [review]

**Pull request merged**
