### PR TITLE
planner: Fix problem that MPP query cannot work with STATEMENT_SUMMARY properly

### PR DESCRIPTION
**Pull request by leiysky**
### What problem does this PR solve?
Problem Summary:
Query with ExchangeReceiver and ExchangeSender operators, that is MPP query, cannot display in STATEMENT_SUMMARY

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
- Add mapping from `TypeString` to `PhysicalID` for `ExchangeReceiver` and `ExchangeSender`

How it Works:

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Comment by leiysky** [comment]
@crazycs520 PTAL

**Review by crazycs520 — COMMENTED** [review]
LGTM

**Pull request merged**
