### PR TITLE
*: refine some error messages

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Problem Summary:
If redact log is enabled, we shouldn't output errors related to the record.

### What is changed and how it works?

Refine some error messages.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

### Release note 

- refine some error messages

### CODE REVIEW

**Review by AilinKid — COMMENTED** [review]
/lgtm

**Review by tangenta — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
