### PR TITLE
*: remove useless ExprType

### PR DESCRIPTION
**Pull request by zz-jason**
Since we never use these ExprType, the following things are changed in this PR:
1. remove `distFuncs` and `newDistSQLFunction` in file *expression/distsql_builtin.go*
2. rewrite `ExpressionsToPB`
3. remove useless ExprType in `supportExpr`

### CODE REVIEW

**Comment by zz-jason** [comment]
another related PR is opened in tipb: https://github.com/pingcap/tipb/pull/82

**Comment by zz-jason** [comment]
@winoros @XuHuaiyu @zimulala PTAL

**Comment by coocood** [comment]
LGTM

**Pull request merged**
