### PR TITLE
expression: check max_allowed_packet constraint for function insert (…

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve? 
Return `NULL` and a warning when the result of function `insert` exceeds `max_allowed_packet`.

Before this PR, `SELECT INSERT('abc', 1, -1, 'abcd');` would return result `'abcd'` even if  `@@global.max_allowed_packet` is set `3`.

After this PR:
```
mysql> select @@max_allowed_packet;
+----------------------+
| @@max_allowed_packet |
+----------------------+
| 3                    |
+----------------------+
1 row in set (0.00 sec)

mysql> select insert('abc', 1, -1, 'abc');
+-----------------------------+
| insert('abc', 1, -1, 'abc') |
+-----------------------------+
| abc                         |
+-----------------------------+
1 row in set (0.00 sec)

mysql> select insert('abc', 1, -1, 'abcd');
+------------------------------+
| insert('abc', 1, -1, 'abcd') |
+------------------------------+
| NULL                         |
+------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-----------------------------------------------------------------------+
| Level   | Code | Message                                                               |
+---------+------+-----------------------------------------------------------------------+
| Warning | 1301 | Result of insert() was larger than max_allowed_packet (3) - truncated |
+---------+------+-----------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### What is changed and how it works?
* check result length in `valString` method of `builtinInsertSig` and `builtinInsertBinarySig` against `max_allowed_packet`;

### Check List 

Tests 

 - Unit test

Related changes

 - Need to be included in the release note

### CODE REVIEW

**Comment by zz-jason** [comment]
LGTM
@XuHuaiyu @lamxTyler PTAL

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by eurekaka** [comment]
@zz-jason PTAL, cherry-picked from master branch

**Comment by eurekaka** [comment]
/run-unit-test tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by lamxTyler** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Pull request merged**
