### PR TITLE
executor: Fix "Truncated incorrect DOUBLE value" bug

### LINKED ISSUE #38577: Error: Truncated incorrect DOUBLE value
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create table tbl_1 ( col_1 set ( 'Alice','Bob','Charlie','David' )   not null default 'Alice' ,col_2 tinyint  unsigned ,col_3 decimal ( 34 , 3 )   not null default 79 ,col_4 bigint  unsigned not null ,col_5 bit ( 12 )   not null , unique key idx_1 ( col_2 ) ,unique key idx_2 ( col_2 ) ) charset utf8mb4 collate utf8mb4_bin ;
create table tbl_2 ( col_6 text ( 52 ) collate utf8_unicode_ci  not null ,col_7 int  unsigned not null ,col_8 blob ( 369 ) ,col_9 bit ( 51 ) ,col_10 decimal ( 38 , 16 ) , unique key idx_3 ( col_7 ) ,unique key idx_4 ( col_7 ) ) charset utf8 collate utf8_unicode_ci ;
create table tbl_3 ( col_11 set ( 'Alice','Bob','Charlie','David' )   not null ,col_12 bigint  unsigned not null default 1678891638492596595 ,col_13 text ( 18 ) ,col_14 set ( 'Alice','Bob','Charlie','David' )   not null default 'Alice' ,col_15 mediumint , key idx_5 ( col_12 ) ,unique key idx_6 ( col_12 ) ) charset utf8mb4 collate utf8mb4_general_ci ;
create table tbl_4 ( col_16 set ( 'Alice','Bob','Charlie','David' )   not null ,col_17 tinyint  unsigned ,col_18 int  unsigned not null default 4279145838 ,col_19 varbinary ( 210 )   not null ,col_20 timestamp , primary key  ( col_18 ) /*T![clustered_index] nonclustered */ ,key idx_8 ( col_19 ) ) charset utf8mb4 collate utf8mb4_unicode_ci ;
create table tbl_5 ( col_21 bigint ,col_22 set ( 'Alice','Bob','Charlie','David' ) ,col_23 blob ( 311 ) ,col_24 bigint  unsigned not null default 3415443099312152509 ,col_25 time , unique key idx_9 ( col_21 ) ,unique key idx_10 ( col_21 ) ) charset gbk collate gbk_bin ;
insert into tbl_1 values ( 'Bob',null,0.04,2650749963804575036,4044 );
insert into tbl_1 values ( 'Alice',171,1838.2,6452757231340518222,1190 );
insert into tbl_1 values ( 'Bob',202,2.962,4304284252076747481,2112 );
insert into tbl_1 values ( 'David',155,32610.05,5899651588546531414,104 );
insert into tbl_1 values ( 'Charlie',52,4219.7,6151233689319516187,1246 );
insert into tbl_1 values ( 'Bob',55,3963.11,3614977408465893392,1188 );
insert into tbl_1 values ( 'Alice',203,72.01,1553550133494908281,1658 );
insert into tbl_1 values ( 'Bob',40,871.569,8114062926218465773,1397 );
insert into tbl_1 values ( 'Alice',165,7765,4481202107781982005,2089 );
insert into tbl_1 values ( 'David',79,7.02,993594504887208796,514 );
insert into tbl_2 values ( 'iB_%7c&q!6-gY4bkvg',2064909882,'dLN52t1YZSdJ',2251679806445488,32 );
insert into tbl_2 values ( 'h_',1478443689,'EqP+iN=',180492371752598,0.1 );
insert into tbl_2 values ( 'U@U&*WKfPzil=6YaDxp',4271201457,'QWuo24qkSSo',823931105457505,88514 );
insert into tbl_2 values ( 'FR4GA=',505128825,'RpEmV6ph5Z7',568030123046798,609381 );
insert into tbl_2 values ( '3GsU',166660047,'',1061132816887762,6.4605 );
insert into tbl_2 values ( 'BA4hPRD0lm*pbg#NE',3440634757,'7gUPe2',288001159469205,6664.9 );
insert into tbl_2 values ( '+z',2117152318,'WTkD(N',215697667226264,7.88 );
insert into tbl_2 values ( 'x@SPhy9lOomPa4LF',2881759652,'ETUXQQ0b4HnBSKgTWIU',153379720424625,null );
insert into tbl_2 values ( '',2075177391,'MPae!9%ufd',115899580476733,341.23 );
insert into tbl_2 values ( '~udi',1839363347,'iQj$$YsZc5ULTxG)yH',111454353417190,6.6 );
insert into tbl_3 values ( 'Alice',7032411265967085555,'P7*KBZ159','Alice',7516989 );
insert into tbl_3 values ( 'David',486417871670147038,'','Charlie',-2135446 );
insert into tbl_3 values ( 'Charlie',5784081664185069254,'7V_&YzKM~Q','Charlie',5583839 );
insert into tbl_3 values ( 'David',6346366522897598558,')Lp&$2)SC@','Bob',2522913 );
insert into tbl_3 values ( 'Charlie',224922711063053272,'gY','David',6624398 );
insert into tbl_3 values ( 'Alice',4678579167560495958,'fPIXY%R8WyY(=u&O','David',-3267160 );
insert into tbl_3 values ( 'David',8817108026311573677,'Cs0dZW*SPnKhV1','Alice',2359718 );
insert into tbl_3 values ( 'Bob',3177426155683033662,'o2=@zv2qQDhKUs)4y','Bob',-8091802 );
insert into tbl_3 values ( 'Bob',2543586640437235142,'hDa*CsOUzxmjf2m','Charlie',-8091935 );
insert into tbl_3 values ( 'Charlie',6204182067887668945,'DX-!=)dbGPQO','David',-1954600 );
insert into tbl_4 values ( 'David',167,576262750,'lX&x04W','2035-09-28' );
insert into tbl_4 values ( 'Charlie',236,2637776757,'92OhsL!w%7','2036-02-08' );
insert into tbl_4 values ( 'Bob',68,1077999933,'M0l','1997-09-16' );
insert into tbl_4 values ( 'Charlie',184,1280264753,'FhjkfeXsK1Q(','2030-03-16' );
insert into tbl_4 values ( 'Alice',10,2150711295,'Eqip)^tr*MoL','2032-07-02' );
insert into tbl_4 values ( 'Bob',108,2421602476,'Eul~~Df_Q8s&I3Y-7','2019-06-10' );
insert into tbl_4 values ( 'Alice',36,2811198561,'%XgRou0#iKtn*','2022-06-13' );
insert into tbl_4 values ( 'Charlie',115,330972286,'hKeJS','2000-11-15' );
insert into tbl_4 values ( 'Alice',6,2958326555,'c6+=1','2001-02-11' );
insert into tbl_4 values ( 'Alice',99,387404826,'figc(@9R*k3!QM_Vve','2036-02-17' );
insert into tbl_5 values ( -401358236474313609,'Charlie','4J$',701059766304691317,'08:19:10.00' );
insert into tbl_5 values ( 2759837898825557143,'Bob','E',5158554038674310466,'11:04:03.00' );
insert into tbl_5 values ( 273910054423832204,'Alice',null,8944547065167499612,'08:02:30.00' );
insert into tbl_5 values ( 2875669873527090798,'Alice','4^SpR84',4072881341903432150,'18:24:55.00' );
insert into tbl_5 values ( -8446590100588981557,'David','yBj8',8760380566452862549,'09:01:10.00' );
insert into tbl_5 values ( -1075861460175889441,'Charlie','ti11Pl0lJ',9139997565676405627,'08:30:14.00' );
insert into tbl_5 values ( 95663565223131772,'Alice','6$',8467839300407531400,'23:31:42.00' );
insert into tbl_5 values ( -5661709703968335255,'Charlie','',8122758569495329946,'19:36:24.00' );
insert into tbl_5 values ( 3338588216091909518,'Bob','',6558557574025196860,'15:22:56.00' );
insert into tbl_5 values ( 8918630521194612922,'David','I$w',5981981639362947650,'22:03:24.00' );
insert ignore into tbl_1 set col_1 = 'David', col_2 = 110, col_3 = 37065, col_4 = 8164500960513474805, col_5 = 1264 on duplicate key update col_3 = 22151.5, col_4 = 6266058887081523571, col_5 = 3254, col_2 = 59, col_1 = 'Bob';
insert  into tbl_4 (col_16,col_17,col_18,col_19,col_20) values ( 'Charlie',34,2499970462,'Z','1978-10-27' ) ,( 'David',217,1732485689,'*)~@@Q8ryi','2004-12-01' ) ,( 'Charlie',40,1360558255,'H(Y','1998-06-25' ) ,( 'Alice',108,2973455447,'%CcP4$','1979-03-28' ) ,( 'David',9,3835209932,'tdKXUzLmAzwFf$','2009-03-03' ) ,( 'David',68,163270003,'uimsclz@FQJN','1988-09-11' ) ,( 'Alice',76,297067264,'BzFF','1989-01-05' ) on duplicate key update col_16 = 'Charlie', col_17 = 14, col_18 = 4062155275, col_20 = '2002-03-07', col_19 = 'tmvchLzp*o8';
delete from tbl_3 where tbl_3.col_13 in ( null ,'' ,'g8EEzUU7LQ' ,'~fC3&B*cnOOx_' ,'%RF~AFto&x' ,'NlWkMWG^00' ,'e^4o2Ji^q_*Fa52Z' ) ;
delete from tbl_5 where not( tbl_5.col_21 between -1075861460175889441 and 3338588216091909518 ) ;
replace into tbl_1 (col_1,col_2,col_3,col_4,col_5) values ( 'Alice',83,8.33,4070808626051569664,455 ) ,( 'Alice',53,2.8,2763362085715461014,1912 ) ,( 'David',178,4242.8,962727993466011464,1844 ) ,( 'Alice',16,650054,5638988670318229867,565 ) ,( 'Alice',76,89783.1,3968605744540056024,2563 ) ,( 'Bob',120,0.89,1003144931151245839,2670 );
delete from tbl_5 where col_24 is null ;
delete from tbl_3 where tbl_3.col_11 in ( 'Alice' ,'Bob' ,'Alice' ) ;
insert  into tbl_3 set col_11 = 'Bob', col_12 = 5701982550256146475, col_13 = 'Hhl)yCsQ2K3cfc^', col_14 = 'Alice', col_15 = -3718868 on duplicate key update col_15 = 7210750, col_12 = 6133680876296985245, col_14 = 'Alice', col_11 = 'David', col_13 = 'F+RMGE!_2^Cfr3Fw';
insert ignore into tbl_5 set col_21 = 2439343116426563397, col_22 = 'Charlie', col_23 = '~Spa2YzRFFom16XD', col_24 = 5571575017340582365, col_25 = '13:24:38.00' ;
update tbl_4 set tbl_4.col_20 = '2006-01-24' where tbl_4.col_18 in ( select col_11 from tbl_3 where IsNull( tbl_4.col_16 ) or not( tbl_4.col_19 in ( select col_3 from tbl_1 where tbl_4.col_16 between 'Alice' and 'David' and tbl_4.col_19 <= '%XgRou0#iKtn*' ) ) ) ;
```

### 3. What did you see instead (Required)
```
err="[types:1292]Truncated incorrect DOUBLE value: '%XgRou0#iKtn*'
```
### 4. What is your TiDB version? (Required)
```
| Release Version: v6.4.0-alpha-91-g22b85b9b3
Edition: Community
Git Commit Hash: 22b85b9b3e93b3af8f79dceabb7e92d31c6cd389
Git Branch: HEAD
UTC Build Time: 2022-10-20 08:46:32
GoVersion: go1.19
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |
```

### PR DESCRIPTION
**Pull request by wxbty**
Signed-off-by: x-shadow-man <1494445739@qq.com>

### What problem does this PR solve?

When querying with tables, if one side of the filter condition is a varbinary field and the other side is decimal, the error "Truncated incorrect DOUBLE value" will be returned when the update is executed. 
Issue Number: close #38577

### What is changed and how it works?

After inspection, the select operation will use warn instead of error under the current conditions. 
In order to maintain consistency with mysq, it is modified to remove the judgment condition. This type of error report uses warn instead of error.

The following steps can be used instead of issue #38577 verification
create table tbl_1 ( col_1 decimal (34, 3) not null default 79 );
create table tbl_2 (col_2 varbinary (210) not null );
insert into tbl_1 values (7.02);
insert into tbl_2 values ('hKeJS11' );
UPDATE tbl_2 SET tbl_2.col_2 = 'Bob' WHERE tbl_2.col_2 IN(SELECT col_1 FROM tbl_1);

### Check List

Tests
- [ TestIssue38577 ] Unit test

Side effects

none

Documentation

none

### Release note

```release-note
None
```

### CODE REVIEW

**Review by dveeden — COMMENTED** [review]
I think the statements for the testcase are more than the minimal set.

**Comment by dveeden** [comment]
Without this PR:
```
sql> create table tbl_1 ( col_1 decimal (34, 3) not null default 79 );
Query OK, 0 rows affected (0.0182 sec)

sql> create table tbl_2 (col_2 varbinary (210) not null );
Query OK, 0 rows affected (0.0184 sec)

sql> insert into tbl_1 values (7.02);
Query OK, 1 row affected (0.0007 sec)

sql> insert into tbl_2 values ('hKeJS11' );
Query OK, 1 row affected (0.0006 sec)

sql> UPDATE tbl_2 SET tbl_2.col_2 = 'Bob' WHERE tbl_2.col_2 IN(SELECT col_1 FROM tbl_1);
ERROR: 1292 (22007): Truncated incorrect DOUBLE value: 'hKeJS11'
```

With this PR:
```
sql> create table tbl_1 ( col_1 decimal (34, 3) not null default 79 );
Query OK, 0 rows affected (0.0323 sec)

sql> create table tbl_2 (col_2 varbinary (210) not null );
Query OK, 0 rows affected (0.0155 sec)

sql> insert into tbl_1 values (7.02);
Query OK, 1 row affected (0.0006 sec)

sql> insert into tbl_2 values ('hKeJS11' );
Query OK, 1 row affected (0.0005 sec)

sql> UPDATE tbl_2 SET tbl_2.col_2 = 'Bob' WHERE tbl_2.col_2 IN(SELECT col_1 FROM tbl_1);
Query OK, 0 rows affected, 1 warning (0.0047 sec)

Rows matched: 0  Changed: 0  Warnings: 1
Warning (code 1292): Truncated incorrect DOUBLE value: 'hKeJS11'
```

MySQL 8.0.31:
```
sql> create table tbl_1 ( col_1 decimal (34, 3) not null default 79 );
Query OK, 0 rows affected (0.0468 sec)

sql> create table tbl_2 (col_2 varbinary (210) not null );
Query OK, 0 rows affected (0.0396 sec)

sql> insert into tbl_1 values (7.02);
Query OK, 1 row affected (0.0060 sec)

sql> insert into tbl_2 values ('hKeJS11' );
Query OK, 1 row affected (0.0068 sec)

sql> UPDATE tbl_2 SET tbl_2.col_2 = 'Bob' WHERE tbl_2.col_2 IN(SELECT col_1 FROM tbl_1);
ERROR: 1292 (22007): Truncated incorrect DOUBLE value: 'hKeJS11'
```

MySQL 8.0.31 with strict SQL mode disabled:
```
sql> SELECT @@sql_mode;
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.0006 sec)

sql> SET sql_mode='';
Query OK, 0 rows affected (0.0006 sec)

sql> create table tbl_1 ( col_1 decimal (34, 3) not null default 79 );
Query OK, 0 rows affected (0.0571 sec)

sql> create table tbl_2 (col_2 varbinary (210) not null );
Query OK, 0 rows affected (0.0424 sec)

sql> insert into tbl_1 values (7.02);
Query OK, 1 row affected (0.0077 sec)

sql> insert into tbl_2 values ('hKeJS11' );
Query OK, 1 row affected (0.0064 sec)

sql> UPDATE tbl_2 SET tbl_2.col_2 = 'Bob' WHERE tbl_2.col_2 IN(SELECT col_1 FROM tbl_1);
Query OK, 0 rows affected, 1 warning (0.0011 sec)

Rows matched: 0  Changed: 0  Warnings: 1
Warning (code 1292): Truncated incorrect DOUBLE value: 'hKeJS11'
```

Is this expected? The behaviour that the version without this PR has matches the default behaviour of MySQL. If we change this we should follow the `STRICT_ALL_TABLES` sql_mode (and `STRICT_TRANS_TABLES`?).

**Comment by xhebox** [comment]
> If we change this we should follow the STRICT_ALL_TABLES sql_mode (and STRICT_TRANS_TABLES?).

Yes, this PR did not follow `SQL_MODE`.

**Comment by wxbty** [comment]
Thanks for your reply,  @dveeden .maybe there is something wrong with the mysql5.7 I refer to. I did not test mysql8.0

MySQL 5.7.40:

    mysql> select @@version;
    +-----------+
    | @@version |
    +-----------+
    | 5.7.40    |
    +-----------+
    1 row in set (0.02 sec)
    
    mysql> select @@session.sql_mode;
    +-------------------------------------------------------------------------------------------------------------------------------------------+
    | @@session.sql_mode                                                                                                                        |
    +-------------------------------------------------------------------------------------------------------------------------------------------+
    | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
    +-------------------------------------------------------------------------------------------------------------------------------------------+
    1 row in set (0.04 sec)
    
    mysql> create table tbl_1 ( col_1 decimal (34, 3) not null default 79 );
    Query OK, 0 rows affected (0.05 sec)
    
    mysql> create table tbl_2 (col_2 varbinary (210) not null );
    Query OK, 0 rows affected (0.06 sec)
    
    mysql> insert into tbl_1 values (7.02);
    Query OK, 1 row affected (0.03 sec)
    
    mysql> insert into tbl_2 values ('hKeJS11' );
    Query OK, 1 row affected (0.17 sec)
    
    mysql> UPDATE tbl_2 SET tbl_2.col_2 = 'Bob' WHERE tbl_2.col_2 IN(SELECT col_1 FROM tbl_1);
    Query OK, 0 rows affected (0.02 sec)
    Rows matched: 0  Changed: 0  Warnings: 0

MySQL 8.0.31:

same result as your test.

In the two mysql versions, the sql_mode of STRICT_TRANS_TABLES is used(default), but the performance is different.

If STRICT_TRANS_TABLES is removed from sql_mode, both versions will not report an error, mysql8 is converted to warning, and mysql5.7 has nothing

In mysql5.7, the update operation (innodb table) did not report an error, not even a warning. Obviously, the data has been converted into a format, which is inconsistent with the content of the document. 

https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-changes

https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sql-mode-strict

Both versions describe the same thing:

"For transactional tables, an error occurs for invalid or missing values in a data-change statement when either STRICT_ALL_TABLES or STRICT_TRANS_TABLES is enabled. The statement is aborted and rolled back."

mysql8.0 fixed this problem, and tidb（master） is consistent with mysql8.0, 

 now I think this is not a bug. what do you think?

**Comment by dveeden** [comment]
There are some failures in the CI checks.

```
$ make explaintest 
GO111MODULE=on go build  -tags codes  -ldflags '-X "github.com/pingcap/tidb/parser/mysql.TiDBReleaseVersion=v6.4.0-alpha-92-gaaee1d049" -X "github.com/pingcap/tidb/util/versioninfo.TiDBBuildTS=2022-10-26 05:58:08" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitHash=aaee1d049b91c5fb73c06f16a272d7660f7b617b" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitBranch=bugfix-upd-mp" -X "github.com/pingcap/tidb/util/versioninfo.TiDBEdition=Community" -X "github.com/pingcap/tidb/config.checkBeforeDropLDFlag=1"' -o bin/tidb-server tidb-server/main.go
extracting statistics: s
skip building tidb-server, using existing binary: ../../bin/tidb-server
building portgenerator binary: ./portgenerator
building explain-test binary: ./explain_test
start tidb-server, log file: ./explain-test.out
tidb-server(PID: 323813) started
run all explain test cases (disabled new collation)
[2022/10/26 13:58:33.010 +08:00] [FATAL] [main.go:765] ["run test"] [test=collation_agg_func] [error="sql:insert into tt values (\"b\", \"b\", \"b\", JSON_OBJECT(\"b\", \"b\"));: run \"insert into tt values (\"b\", \"b\", \"b\", JSON_OBJECT(\"b\", \"b\"));\" at line 53 err, we need:\nError 1265: Data truncated for column 'b' at row 1\ninsert into\nbut got:\ninsert into tt values (\"b\", \"b\", \"b\", JSON_OBJECT(\"b\", \"b\"));\n\n"] [errorVerbose="run \"insert into tt values (\"b\", \"b\", \"b\", JSON_OBJECT(\"b\", \"b\"));\" at line 53 err, we need:\nError 1265: Data truncated for column 'b' at row 1\ninsert into\nbut got:\ninsert into tt values (\"b\", \"b\", \"b\", JSON_OBJECT(\"b\", \"b\"));\n\n\nmain.(*tester).execute\n\t/home/dvaneeden/dev/pingcap/tidb/cmd/explaintest/main.go:392\nmain.(*tester).Run\n\t/home/dvaneeden/dev/pingcap/tidb/cmd/explaintest/main.go:165\nmain.main\n\t/home/dvaneeden/dev/pingcap/tidb/cmd/explaintest/main.go:764\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/lib/golang/src/runtime/asm_amd64.s:1594\nsql:insert into tt values (\"b\", \"b\", \"b\", JSON_OBJECT(\"b\", \"b\"));"] [stack="main.main\n\t/home/dvaneeden/dev/pingcap/tidb/cmd/explaintest/main.go:765\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:250"]
make: *** [Makefile:106: explaintest] Error 1
```

https://github.com/pingcap/tidb/blob/9d56ee97b10ecaa53229bc66cc8c145533f40905/cmd/explaintest/t/collation_agg_func.test#L53

```
run "insert into tt values ("b", "b", "b", JSON_OBJECT("b", "b"));" at line 53 err, we need:
Error 1265: Data truncated for column 'b' at row 1
insert into
but got:
insert into tt values ("b", "b", "b", JSON_OBJECT("b", "b"));


main.(*tester).execute
	/home/dvaneeden/dev/pingcap/tidb/cmd/explaintest/main.go:392
main.(*tester).Run
	/home/dvaneeden/dev/pingcap/tidb/cmd/explaintest/main.go:165
main.main
	/home/dvaneeden/dev/pingcap/tidb/cmd/explaintest/main.go:764
runtime.main
	/usr/lib/golang/src/runtime/proc.go:250
runtime.goexit
	/usr/lib/golang/src/runtime/asm_amd64.s:1594
sql:insert into tt values ("b", "b", "b", JSON_OBJECT("b", "b"));

```

**Comment by wxbty** [comment]
I noticed the CI test, maybe it was affected, if this is not a bug, I will close the pr.

**Comment by wxbty** [comment]
Can you help me to confirm if issue #38577 is a bug?  @dveeden  @xhebox

**Comment by xhebox** [comment]
> Can you help me to confirm if issue #38577 is a bug? @dveeden @xhebox

It is essentially a mysql bug. Let me ask the reporter of the issue.

**Comment by xhebox** [comment]
> Can you help me to confirm if issue #38577 is a bug? @dveeden @xhebox

@wxbty Hi, the reporter of the issue decided that we can skip this issue. Anyway, thanks for your contribution on triaging the issue.

**Comment by wxbty** [comment]
ok

**Pull request closed without merging**
