### PR TITLE
store/tikv: make failpoints without code generations

### PR DESCRIPTION
**Pull request by disksing**
### What problem does this PR solve?

store/tikv will be migrated to a separate directory as a library and TiDB tests will not be able to use code generation to open failpoints.

Part of https://github.com/pingcap/tidb/issues/22513

### What is changed and how it works?

What's Changed:
- Replace `failpoint.Inject` with `failpoint.Eval` (`util.EvalFailpoint()`)
- Change failpoint path to `tikvclient`
- Revert some variable style failpoints

Without code generation, it may introduce performance regression. We can improve it by introducing a global option to make the impact minor.

### Related changes

- Need to update jepsen, tiacid, utf

### Check List 

Tests 
- Unit test

Side effects
- Performance regression
    - Consumes more CPU

### Release note 

- No release note

### CODE REVIEW

**Review by AndreMouche — APPROVED** [review]
LGTM

**Comment by disksing** [comment]
CI failed due to env problem.

**Review by zyguan — APPROVED** [review]
LGTM

**Pull request merged**
