### PR TITLE
*: Change stmt summary and capture plan baselines to GLOBAL only

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: part of https://github.com/pingcap/tidb/issues/30557

Problem Summary:

In https://github.com/pingcap/tidb/issues/30557 it is proposed that we implement `INSTANCE` scope for system variables using a simplified proposal (instance and global are mutually exclusive). This addresses all the pre-requisite behavior changes, which are related to stmt summary and capture plan baseslines (the features are related).

Merging this PR is predicated on the proposal for simplified `INSTANCE` scope being approved. If we don't approve the proposal, this PR does not make sense.

Yes, this is a breaking change! It has been approved by @easonn7 

### What is changed and how it works?

The change is unfortunately quite large, this is because:
- If it is no longer instance scope, the tie-in to config is obsolete.
- stmt summary predated sysvar validation (and performed its own validation). When refactoring, it made sense in making the changes that it would switch to using sysvar validation and use the correct types in the internal API.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
I manually tested that the starting of sysvar cache loop correctly sets the global variablse for stmt summary. If you `set global tidb_enable_stmt_summary = 0` and restart the tidb server, it will be off.
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Configuration for Statement Summary and Capture Plan Baselines is now only available on a GLOBAL basis. This simplifies configuration from earlier versions of TiDB where it was configurable on an INSTANCE of GLOBAL basis.
```

### CODE REVIEW

**Review by djshow832 — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]
The `capture plan baselines` part LGTM.

**Comment by Reminiscent** [comment]
Another question is if we execute the `set tidb_capture_plan_baselines = 1;`.  The default scope should be transferred from `SESSION` to `GLOBAL`. We should update the doc to remind the user.

**Comment by morgo** [comment]
> Another question is if we execute the `set tidb_capture_plan_baselines = 1;`. The default scope should be transferred from `SESSION` to `GLOBAL`. We should update the doc to remind the user.

Sorry, just to clarify: did you mean that (a) we should allow `session` to be specified for compatibiliity, or (b) update the docs so that it correctly lists scope?

For (b) I have [a script ]([url](https://github.com/pingcap/docs/pull/5720))that auto-generates the correct docs which I then use to create PRs. See https://github.com/pingcap/docs/pull/6838 for an example where I detected changes and updated the docs (I typically run this script every 2 weeks, so it will be caught before GA).

**Comment by Reminiscent** [comment]
> > Another question is if we execute the `set tidb_capture_plan_baselines = 1;`. The default scope should be transferred from `SESSION` to `GLOBAL`. We should update the doc to remind the user.
> 
> Sorry, just to clarify: did you mean that (a) we should allow `session` to be specified for compatibiliity, or (b) update the docs so that it correctly lists scope?
> 
> For (b) I have [a script ](https://github.com/pingcap/docs/pull/5720) that auto-generates the correct docs which I then use to create PRs. See [pingcap/docs#6838](https://github.com/pingcap/docs/pull/6838) for an example where I detected changes and updated the docs (I typically run this script every 2 weeks, so it will be caught before GA).

I mean plan b, thanks for the answer. In fact, what I mean is that when we do not explicitly specify the scope of the query. For example, the original `set tidb_capture_plan_baselines = 1;` is equivalent to `set session tidb_capture_plan_baselines = 1;`. When tidb_capture_plan_baselines only supports global scope, `set tidb_capture_plan_baselines = 1;` is equivalent to `set global tidb_capture_plan_baselines = 1;`. We need to remind users of this behavior change in the document.

**Comment by morgo** [comment]
> When `tidb_capture_plan_baselines` only supports global scope, `set tidb_capture_plan_baselines = 1;` is equivalent to `set global tidb_capture_plan_baselines = 1;`.

Unfortunately this is not the case. `SET` has a default scope of session, so the user will get an error.

I am hessitant to allow `SET SESSION` to redirect to global scope in this context, because if a user did not intend for this to execute globally it could cause problems. At least they will get an error message and can check the manual, and it is not typically application sessions which will be eecuting this query but DBAs.

(In a different context in https://github.com/pingcap/tidb/pull/30558 I proposed we allow both for backward compatibility. But this is slightly different because it very strictly ensures the previous behavior and it does not propagate to peers).

> We need to remind users of this behavior change in the document. So I think plan B is OK:)

Yes, the docs team will also catch it from the `compatibility-breaker` label. There is a section in each `.0` release which covers defaults and variable changes.

**Comment by Reminiscent** [comment]
> > When `tidb_capture_plan_baselines` only supports global scope, `set tidb_capture_plan_baselines = 1;` is equivalent to `set global tidb_capture_plan_baselines = 1;`.
> 
> Unfortunately this is not the case. `SET` has a default scope of session, so the user will get an error.
> 
> I am hessitant to allow `SET SESSION` to redirect to global scope in this context, because if a user did not intend for this to execute globally it could cause problems. At least they will get an error message and can check the manual, and it is not typically application sessions which will be eecuting this query but DBAs.
> 
> (In a different context in #30558 I proposed we allow both for backward compatibility. But this is slightly different because it very strictly ensures the previous behavior and it does not propagate to peers).
> 
> > We need to remind users of this behavior change in the document. So I think plan B is OK:)
> 
> Yes, the docs team will also catch it from the `compatibility-breaker` label. There is a section in each `.0` release which covers defaults and variable changes.

@qw4990 PTAL.
I think is reasonable to report the error. But I'm not sure it's reasonable for others. So it may need more discussion.

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
