### PR TITLE
planner: fix wrong TableDual plans caused by comparing Binary and Bytes incorrectly

### LINKED ISSUE #23846: The execution result of using TableDual plan is not correct
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(a varbinary(10),UNIQUE KEY(a));
insert into t values(0x00A4EEF4FA55D6706ED5);
select count(*) from t where a=0x00A4EEF4FA55D6706ED5; -- 1
desc select * from t where a=0x00A4EEF4FA55D6706ED5; -- TableDual_2 plan
select * from t where a=0x00A4EEF4FA55D6706ED5; -- Empty result
```
### 2. What did you expect to see? (Required)
0x00A4EEF4FA55D6706ED5
### 3. What did you see instead (Required)
Empty result
### 4. What is your TiDB version? (Required)

Release Version: v4.0.0-beta.2-2561-g9c75cfa4e
Edition: Community
Git Commit Hash: 9c75cfa4e2bbb854ab90562ecec0409f84a989b0
Git Branch: master
UTC Build Time: 2021-04-05 07:39:46
GoVersion: go1.15.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #23846 

Problem Summary: planner: fix wrong TableDual plans caused by comparing Binary and Bytes incorrectly

### What is changed and how it works?

planner: fix wrong TableDual plans caused by comparing Binary and Bytes incorrectly

### Check List 

Tests 

- Unit test

### Release note 

- planner: fix wrong TableDual plans caused by comparing Binary and Bytes incorrectly

### CODE REVIEW

**Review by winoros — COMMENTED** [review]
lgtm

**Review by winoros — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]
/LGTM

**Pull request merged**
