### PR TITLE
infoschema: support multiple quantile query in metrics_schema.

### LINKED ISSUE #40615: Support more quantiles in metric tables from metrics_schema
## Enhancement

The `TiDB built-in SQL Diagnostics` feature(ref: https://github.com/pingcap/tidb/issues/13567) introduces the `metrics_schema`, which collects many metrics of tidb cluster, including the prometheus data.

In the metric table definition, it only defines one quantile for histogram data. https://github.com/pingcap/tidb/blob/03e192b6c448ab1224c1251fd022923d90a4e91a/infoschema/metrics_schema.go#L64-L69

However when analyzing metrics, in many times we need to **observe multiple quantiles and compare them together**. For example, when we use TiCDC to write data to TiDB with different workloads, one has high idle time in TiCDC workers and the other one has busy worker load, we can observe the `P90 not-in-txn connection idle duration` are quite similar, but `P99 not-in-txn connection idle duration` diffs a lot.

## Request

We can replace the quantile definition in metric table from `float64` to `[]float64`, and support more quantiles in metric tables.

## Compatibility

It is compatible with previous version, since it doesn't change the column definition of metric table, but only adds more rows with different quantiles.

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: close #40615

Problem Summary:

### What is changed and how it works?

- Change quantile of `MetricTableDef` from `float64` to `[]float64`, and support to define multiple quantiles in histogram data of metric table.
- Add `0.99` quantile to `tidb_connection_idle_duration`, since this metric is important when we distinguish whether tidb has performance bottleneck, ref: https://docs.pingcap.com/tidb/dev/performance-tuning-methods#is-tidb-the-bottleneck

### Check List

Tests 

- [x] Unit test
- [x] Manual test (add detailed scripts or steps below)

```mysql
mysql> select * from tidb_connection_idle_duration where time > '2023-01-16 18:36:18';
+----------------------------+------------------+--------+----------+-----------------------+
| time                       | instance         | in_txn | quantile | value                 |
+----------------------------+------------------+--------+----------+-----------------------+
| 2023-01-16 18:36:18.001000 | 10.2.6.127:11080 | 0      |      0.9 |   0.25114744211093165 |
| 2023-01-16 18:37:18.001000 | 10.2.6.127:11080 | 0      |      0.9 |    0.2360618223760093 |
| 2023-01-16 18:38:18.001000 | 10.2.6.127:11080 | 0      |      0.9 |   0.24404850444624093 |
| 2023-01-16 18:36:18.001000 | 10.2.6.127:11080 | 1      |      0.9 | 0.0004864260595130749 |
| 2023-01-16 18:37:18.001000 | 10.2.6.127:11080 | 1      |      0.9 | 0.0004945325247470902 |
| 2023-01-16 18:38:18.001000 | 10.2.6.127:11080 | 1      |      0.9 | 0.0004893802491445838 |
| 2023-01-16 18:36:18.001000 | 10.2.6.127:11080 | 0      |     0.99 |   0.48401989189189143 |
| 2023-01-16 18:37:18.001000 | 10.2.6.127:11080 | 0      |     0.99 |    0.4635652830188679 |
| 2023-01-16 18:38:18.001000 | 10.2.6.127:11080 | 0      |     0.99 |    0.4736653061224492 |
| 2023-01-16 18:36:18.001000 | 10.2.6.127:11080 | 1      |     0.99 | 0.0015577958236658853 |
| 2023-01-16 18:37:18.001000 | 10.2.6.127:11080 | 1      |     0.99 | 0.0017157868383404864 |
| 2023-01-16 18:38:18.001000 | 10.2.6.127:11080 | 1      |     0.99 | 0.0015319716494845313 |
+----------------------------+------------------+--------+----------+-----------------------+
12 rows in set (0.01 sec)
```

Side effects

- None

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by amyangfei** [comment]
Would you please to take a look @hawkingrei @wjhuang2016 , thanks!

**Comment by crazycs520** [comment]
You can specify quantile in query condition, just like following, Does this meet your needs?

```sql
> select * from metrics_schema.tidb_connection_idle_duration where time > '2023-01-18 16:55:30' and quantile in (0.8,0.9,0.99);
+----------------------------+-----------------+--------+----------+------------------------+
| time                       | instance        | in_txn | quantile | value                  |
+----------------------------+-----------------+--------+----------+------------------------+
| 2023-01-18 16:55:30.001000 | 127.0.0.1:10080 | 0      | 0.8      |   0.009851166194091278 |
| 2023-01-18 16:56:30.001000 | 127.0.0.1:10080 | 0      | 0.8      |  11.468800000000003    |
| 2023-01-18 16:57:30.001000 | 127.0.0.1:10080 | 0      | 0.8      |  14.745600000000001    |
| 2023-01-18 16:58:30.001000 | 127.0.0.1:10080 | 0      | 0.8      |  78.64320000000001     |
| 2023-01-18 16:55:30.001000 | 127.0.0.1:10080 | 1      | 0.8      | <null>                 |
| 2023-01-18 16:56:30.001000 | 127.0.0.1:10080 | 1      | 0.8      | <null>                 |
| 2023-01-18 16:57:30.001000 | 127.0.0.1:10080 | 1      | 0.8      | <null>                 |
| 2023-01-18 16:58:30.001000 | 127.0.0.1:10080 | 1      | 0.8      | <null>                 |
| 2023-01-18 16:55:30.001000 | 127.0.0.1:10080 | 0      | 0.9      |   2.5218985456873653   |
| 2023-01-18 16:56:30.001000 | 127.0.0.1:10080 | 0      | 0.9      |  13.9264               |
| 2023-01-18 16:57:30.001000 | 127.0.0.1:10080 | 0      | 0.9      |  15.5648               |
| 2023-01-18 16:58:30.001000 | 127.0.0.1:10080 | 0      | 0.9      | 104.85759999999999     |
| 2023-01-18 16:55:30.001000 | 127.0.0.1:10080 | 1      | 0.9      | <null>                 |
| 2023-01-18 16:56:30.001000 | 127.0.0.1:10080 | 1      | 0.9      | <null>                 |
| 2023-01-18 16:57:30.001000 | 127.0.0.1:10080 | 1      | 0.9      | <null>                 |
| 2023-01-18 16:58:30.001000 | 127.0.0.1:10080 | 1      | 0.9      | <null>                 |
| 2023-01-18 16:55:30.001000 | 127.0.0.1:10080 | 0      | 0.99     |   7.467579709137471    |
| 2023-01-18 16:56:30.001000 | 127.0.0.1:10080 | 0      | 0.99     |  16.138240000000003    |
| 2023-01-18 16:57:30.001000 | 127.0.0.1:10080 | 0      | 0.99     |  16.30208              |
| 2023-01-18 16:58:30.001000 | 127.0.0.1:10080 | 0      | 0.99     | 128.45056000000002     |
| 2023-01-18 16:55:30.001000 | 127.0.0.1:10080 | 1      | 0.99     | <null>                 |
| 2023-01-18 16:56:30.001000 | 127.0.0.1:10080 | 1      | 0.99     | <null>                 |
| 2023-01-18 16:57:30.001000 | 127.0.0.1:10080 | 1      | 0.99     | <null>                 |
| 2023-01-18 16:58:30.001000 | 127.0.0.1:10080 | 1      | 0.99     | <null>                 |
+----------------------------+-----------------+--------+----------+------------------------+
```

**Comment by amyangfei** [comment]
> You can specify quantile in query condition, just like following, Does this meet your needs?
> 
> ```sql
> > select * from metrics_schema.tidb_connection_idle_duration where time > '2023-01-18 16:55:30' and quantile in (0.8,0.9,0.99);
> +----------------------------+-----------------+--------+----------+------------------------+
> | time                       | instance        | in_txn | quantile | value                  |
> +----------------------------+-----------------+--------+----------+------------------------+
> | 2023-01-18 16:55:30.001000 | 127.0.0.1:10080 | 0      | 0.8      |   0.009851166194091278 |
> | 2023-01-18 16:56:30.001000 | 127.0.0.1:10080 | 0      | 0.8      |  11.468800000000003    |
> | 2023-01-18 16:57:30.001000 | 127.0.0.1:10080 | 0      | 0.8      |  14.745600000000001    |
> | 2023-01-18 16:58:30.001000 | 127.0.0.1:10080 | 0      | 0.8      |  78.64320000000001     |
> | 2023-01-18 16:55:30.001000 | 127.0.0.1:10080 | 1      | 0.8      | <null>                 |
> | 2023-01-18 16:56:30.001000 | 127.0.0.1:10080 | 1      | 0.8      | <null>                 |
> | 2023-01-18 16:57:30.001000 | 127.0.0.1:10080 | 1      | 0.8      | <null>                 |
> | 2023-01-18 16:58:30.001000 | 127.0.0.1:10080 | 1      | 0.8      | <null>                 |
> | 2023-01-18 16:55:30.001000 | 127.0.0.1:10080 | 0      | 0.9      |   2.5218985456873653   |
> | 2023-01-18 16:56:30.001000 | 127.0.0.1:10080 | 0      | 0.9      |  13.9264               |
> | 2023-01-18 16:57:30.001000 | 127.0.0.1:10080 | 0      | 0.9      |  15.5648               |
> | 2023-01-18 16:58:30.001000 | 127.0.0.1:10080 | 0      | 0.9      | 104.85759999999999     |
> | 2023-01-18 16:55:30.001000 | 127.0.0.1:10080 | 1      | 0.9      | <null>                 |
> | 2023-01-18 16:56:30.001000 | 127.0.0.1:10080 | 1      | 0.9      | <null>                 |
> | 2023-01-18 16:57:30.001000 | 127.0.0.1:10080 | 1      | 0.9      | <null>                 |
> | 2023-01-18 16:58:30.001000 | 127.0.0.1:10080 | 1      | 0.9      | <null>                 |
> | 2023-01-18 16:55:30.001000 | 127.0.0.1:10080 | 0      | 0.99     |   7.467579709137471    |
> | 2023-01-18 16:56:30.001000 | 127.0.0.1:10080 | 0      | 0.99     |  16.138240000000003    |
> | 2023-01-18 16:57:30.001000 | 127.0.0.1:10080 | 0      | 0.99     |  16.30208              |
> | 2023-01-18 16:58:30.001000 | 127.0.0.1:10080 | 0      | 0.99     | 128.45056000000002     |
> | 2023-01-18 16:55:30.001000 | 127.0.0.1:10080 | 1      | 0.99     | <null>                 |
> | 2023-01-18 16:56:30.001000 | 127.0.0.1:10080 | 1      | 0.99     | <null>                 |
> | 2023-01-18 16:57:30.001000 | 127.0.0.1:10080 | 1      | 0.99     | <null>                 |
> | 2023-01-18 16:58:30.001000 | 127.0.0.1:10080 | 1      | 0.99     | <null>                 |
> +----------------------------+-----------------+--------+----------+------------------------+
> ```

Cool! It meets my requirements.

**Comment by amyangfei** [comment]
Close this PR since we can use where condition to meet requirements.

**Pull request closed without merging**
