### PR TITLE
executor: migrate test-infra to testify for slow_query_test.go

### LINKED ISSUE #28615: migrate test-infra to testify for `slow_query_test.go`

### PR DESCRIPTION
**Pull request by mashenjun**
Signed-off-by: Shenjun <mashenjun0902@gmail.com>

### What problem does this PR solve?

Issue Number: close #28615

Problem Summary: replace `pingcap/check` with `stretchr/testify` in `slow_query_test.go`

### What is changed and how it works?
use testify in test case under `slow_query_test.go`
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
@tangenta PTAL

**Review by wjhuang2016 — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Pull request merged**
