### PR TITLE
*: upgrade go1.20.7

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by dveeden** [comment]
Doesn't this conflict with #45634 ?

**Review by dveeden — APPROVED** [review]

**Comment by wuhuizuo** [comment]
/review how to make it upgrade automatic by renovate, please give me a detail configuration guide to reach it.

**Comment by hawkingrei** [comment]
> Should any of the other go 1.20.* versions be upgraded as well?
> 
> ```
> Dockerfile:ENV GOLANG_VERSION 1.20.5
> Dockerfile.enterprise:ENV GOLANG_VERSION 1.20.5
> WORKSPACE:    version = "1.20.6",
> WORKSPACE.patchgo:        "darwin_amd64": ("go1.20.5.darwin-amd64.tar.gz", "4524fac6858f8170941bb023d218c4a322a38c6b565d7b83f8a80f525c507079"),
> WORKSPACE.patchgo:        "darwin_arm64": ("go1.20.5.darwin-arm64.tar.gz", "9bb1564c241e97d9c254a61136601da8a241e11aaa4ff70e5ad2505c5d1e27d1"),
> WORKSPACE.patchgo:        "linux_amd64": ("go1.20.5.linux-amd64.tar.gz", "22ddd3f4fa13b55dbccce1b8d6e86907aaae624f71caaf6524da1f382c055a03"),
> WORKSPACE.patchgo:        "linux_arm64": ("go1.20.5.linux-arm64.tar.gz", "b0372223fa83123df4166bcfb7c03a30bea20fa226b8c2a8c53aeb61060800d6"),
> WORKSPACE.patchgo:    version = "1.20.5",
> br/web/package-lock.json:      "version": "1.20.0",
> br/web/package-lock.json:      "resolved": "https://registry.npmjs.org/resolve/-/resolve-1.20.0.tgz",
> br/web/package-lock.json:      "version": "1.20.0",
> br/web/package-lock.json:      "resolved": "https://registry.npmjs.org/resolve/-/resolve-1.20.0.tgz",
> build/image/base:ENV GOLANG_VERSION 1.20.6
> go.sum:google.golang.org/grpc v1.20.1/go.mod h1:10oTOabMzJvdu6/UiuZezV6QK5dSlG84ov/aaiqXj38=
> go.sum:google.golang.org/protobuf v1.20.1-0.20200309200217-e05f789c0967/go.mod h1:A+miEFZTKqfCUM6K7xSMQL9OKL/b6hQv+e19PK+JZNE=
> parser/terror/terror_test.go:           //   /Users/pingcap/.gvm/gos/go1.20.1/src/testing/testing.go:1576
> parser/terror/terror_test.go:           //       /Users/pingcap/.gvm/gos/go1.20.1/src/runtime/asm_arm64.s:1172
> tests/globalkilltest/Dockerfile:ENV GOLANG_VERSION 1.20.5
> tools/patch-go/Dockerfile:ENV GOLANG_VERSION 1.20.5
> tools/patch-go/build.sh:GOVERS=1.20.5
> ```

@mjonss  This has been a long-standing issue, and I'm thinking about how to consolidate it into one place.

**Comment by hawkingrei** [comment]
@mjonss I have been updated.

**Review by mjonss — APPROVED** [review]

**Pull request merged**
