### PR TITLE
server: Improve compatibility with MySQL 5.5 and 5.6 clients

### LINKED ISSUE #32334: using MySQL 5.5 and 5.6 clients connecting with a passwordless account to tidb fail
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. download 5.5 and 5.6 version MySQL client
dbdeployer downloads get-unpack mysql-5.5.62.tar.xz
dbdeployer downloads get-unpack mysql-5.6.44.tar.xz 
2. create use nopw with no password,
CREATE USER 'nopw'@'%' IDENTIFIED WITH mysql_native_password
3. use 5.5 and 5.6 MySQL client connect to tidb nightly version(v5.5.0-nightly-20220208) with this "nopw" user

### 2. What did you expect to see? (Required)
connect successully
### 3. What did you see instead (Required)
root@wkload-0:/upgrade-test# /root/opt/mysql/5.5.62/bin/mysql -u nopw -h tiup-peer -P3390
ERROR 2012 (HY000): Error in server handshake

### 4. What is your TiDB version? (Required)

v5.5.0-nightly-20220208

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #32334

Problem Summary:

With a MySQL 5.5 or MySQL 5.6 client connecting to an account in TiDB that uses `mysql_native_password`,
as authentication plugin but doesn't have a password set results in connection failures.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

```release-note
Compatibility with MySQL 5.5 and MySQL 5.6 and passwordless accounts was improved.
```

### CODE REVIEW

**Comment by dveeden** [comment]
# Without this PR
```
TiDB Client Test
Connected to:
	Release Version: v5.5.0-alpha-326-g2d9394421
	Edition: Community
	Git Commit Hash: 2d93944210c460dacce66900de21b23c838092fb
	Git Branch: master
	UTC Build Time: 2022-02-14 15:00:40
	GoVersion: go1.16.13
	Race Enabled: false
	TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
	Check Table Before Drop: false
Clients:
	/home/dvaneeden/opt/mysql/5.1.73/bin/mysql
	/home/dvaneeden/opt/mysql/5.5.62/bin/mysql
	/home/dvaneeden/opt/mysql/5.6.44/bin/mysql
	/home/dvaneeden/opt/mysql/5.7.31/bin/mysql
	/home/dvaneeden/opt/mysql/5.7.36/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.22/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.25/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.26/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.27/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.28/bin/mysql
-----------------------------------------------
Test results for test with mysql_native_password as default authentication format
auth    	native	native	native	native	sha2	sha2	socket	socket
user    	nopw	nopw	native	native	sha2	sha2	socket	socket
connection	TCP	socket	TCP	socket	TCP	socket	TCP	socket
5.1.73  	✅	✅	✅	✅	✔️	✔️	✔️	✔️
5.5.62  	✅	✅	✅	✅	✔️	✔️	✔️	✅
5.6.44  	✅	✅	✅	✅	✔️	✔️	✔️	✅
5.7.31  	✅	✅	✅	✅	✅	✅	✔️	✅
5.7.36  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.22  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.25  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.26  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.27  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.28  	✅	✅	✅	✅	✅	✅	✔️	✅
-----------------------------------------------
❌	  Command '/home/dvaneeden/opt/mysql/5.5.62/bin/mysql -u nopw -h 127.0.0.1 -P 4000 -e QUIT' returned 1.
ERROR 2012 (HY000): Error in server handshake

❌	  Command '/home/dvaneeden/opt/mysql/5.5.62/bin/mysql -u nopw -S /tmp/tidb.sock -e QUIT' returned 1.
ERROR 2012 (HY000): Error in server handshake

❌	  Command '/home/dvaneeden/opt/mysql/5.5.62/bin/mysql -u socket -S /tmp/tidb.sock -pdvaneeden -e QUIT' returned 1.
ERROR 2012 (HY000): Error in server handshake

❌	  Command '/home/dvaneeden/opt/mysql/5.6.44/bin/mysql -u nopw -h 127.0.0.1 -P 4000 -e QUIT' returned 1.
ERROR 2012 (HY000): Error in server handshake

❌	  Command '/home/dvaneeden/opt/mysql/5.6.44/bin/mysql -u nopw -S /tmp/tidb.sock -e QUIT' returned 1.
ERROR 2012 (HY000): Error in server handshake

❌	  Command '/home/dvaneeden/opt/mysql/5.6.44/bin/mysql -u socket -S /tmp/tidb.sock -pdvaneeden -e QUIT' returned 1.
Warning: Using a password on the command line interface can be insecure.
ERROR 2012 (HY000): Error in server handshake

Test results for test with caching_sha2_password as default authentication format
auth    	native	native	native	native	sha2	sha2	socket	socket
user    	nopw	nopw	native	native	sha2	sha2	socket	socket
connection	TCP	socket	TCP	socket	TCP	socket	TCP	socket
5.1.73  	✅	✅	✅	✅	✔️	✔️	✔️	✔️
5.5.62  	❌	❌	✅	✅	✔️	✔️	✔️	❌
5.6.44  	❌	❌	✅	✅	✔️	✔️	✔️	❌
5.7.31  	✅	✅	✅	✅	✅	✅	✔️	✅
5.7.36  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.22  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.25  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.26  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.27  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.28  	✅	✅	✅	✅	✅	✅	✔️	✅
```

# With this PR
```
TiDB Client Test
Connected to:
	Release Version: v5.5.0-alpha-328-g416b3ed1e
	Edition: Community
	Git Commit Hash: 416b3ed1ebf5ee70b717f7f6e658d89efd52e08e
	Git Branch: old_nopw_client
	UTC Build Time: 2022-02-14 15:02:08
	GoVersion: go1.16.13
	Race Enabled: false
	TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
	Check Table Before Drop: false
Clients:
	/home/dvaneeden/opt/mysql/5.1.73/bin/mysql
	/home/dvaneeden/opt/mysql/5.5.62/bin/mysql
	/home/dvaneeden/opt/mysql/5.6.44/bin/mysql
	/home/dvaneeden/opt/mysql/5.7.31/bin/mysql
	/home/dvaneeden/opt/mysql/5.7.36/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.22/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.25/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.26/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.27/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.28/bin/mysql
-----------------------------------------------
Test results for test with mysql_native_password as default authentication format
auth    	native	native	native	native	sha2	sha2	socket	socket
user    	nopw	nopw	native	native	sha2	sha2	socket	socket
connection	TCP	socket	TCP	socket	TCP	socket	TCP	socket
5.1.73  	✅	✅	✅	✅	✔️	✔️	✔️	✔️
5.5.62  	✅	✅	✅	✅	✔️	✔️	✔️	✅
5.6.44  	✅	✅	✅	✅	✔️	✔️	✔️	✅
5.7.31  	✅	✅	✅	✅	✅	✅	✔️	✅
5.7.36  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.22  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.25  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.26  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.27  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.28  	✅	✅	✅	✅	✅	✅	✔️	✅
-----------------------------------------------
❌	  Command '/home/dvaneeden/opt/mysql/5.5.62/bin/mysql -u socket -S /tmp/tidb.sock -pdvaneeden -e QUIT' returned 1.
ERROR 2012 (HY000): Error in server handshake

❌	  Command '/home/dvaneeden/opt/mysql/5.6.44/bin/mysql -u socket -S /tmp/tidb.sock -pdvaneeden -e QUIT' returned 1.
Warning: Using a password on the command line interface can be insecure.
ERROR 2012 (HY000): Error in server handshake

Test results for test with caching_sha2_password as default authentication format
auth    	native	native	native	native	sha2	sha2	socket	socket
user    	nopw	nopw	native	native	sha2	sha2	socket	socket
connection	TCP	socket	TCP	socket	TCP	socket	TCP	socket
5.1.73  	✅	✅	✅	✅	✔️	✔️	✔️	✔️
5.5.62  	✅	✅	✅	✅	✔️	✔️	✔️	❌
5.6.44  	✅	✅	✅	✅	✔️	✔️	✔️	❌
5.7.31  	✅	✅	✅	✅	✅	✅	✔️	✅
5.7.36  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.22  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.25  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.26  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.27  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.28  	✅	✅	✅	✅	✅	✅	✔️	✅
```

**Review by mjonss — APPROVED** [review]
LGTM

**Review by seiya-annie — APPROVED** [review]

**Comment by dveeden** [comment]
With my latest commit added:
```
TiDB Client Test
Connected to:
	Release Version: v5.5.0-alpha-374-gc55ff5018
	Edition: Community
	Git Commit Hash: c55ff5018c9027e50cc3d55b863c2e7902d4e848
	Git Branch: old_nopw_client
	UTC Build Time: 2022-02-18 14:39:04
	GoVersion: go1.18rc1
	Race Enabled: false
	TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
	Check Table Before Drop: false
Clients:
	/home/dvaneeden/opt/mysql/5.1.73/bin/mysql
	/home/dvaneeden/opt/mysql/5.5.62/bin/mysql
	/home/dvaneeden/opt/mysql/5.6.44/bin/mysql
	/home/dvaneeden/opt/mysql/5.7.31/bin/mysql
	/home/dvaneeden/opt/mysql/5.7.36/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.22/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.25/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.26/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.27/bin/mysql
	/home/dvaneeden/opt/mysql/8.0.28/bin/mysql
-----------------------------------------------
Test results for test with mysql_native_password as default authentication format
auth    	native	native	native	native	sha2	sha2	socket	socket
user    	nopw	nopw	native	native	sha2	sha2	socket	socket
connection	TCP	socket	TCP	socket	TCP	socket	TCP	socket
5.1.73  	✅	✅	✅	✅	✔️	✔️	✔️	✔️
5.5.62  	✅	✅	✅	✅	✔️	✔️	✔️	✅
5.6.44  	✅	✅	✅	✅	✔️	✔️	✔️	✅
5.7.31  	✅	✅	✅	✅	✅	✅	✔️	✅
5.7.36  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.22  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.25  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.26  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.27  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.28  	✅	✅	✅	✅	✅	✅	✔️	✅
-----------------------------------------------
Test results for test with caching_sha2_password as default authentication format
auth    	native	native	native	native	sha2	sha2	socket	socket
user    	nopw	nopw	native	native	sha2	sha2	socket	socket
connection	TCP	socket	TCP	socket	TCP	socket	TCP	socket
5.1.73  	✅	✅	✅	✅	✔️	✔️	✔️	✔️
5.5.62  	✅	✅	✅	✅	✔️	✔️	✔️	✅
5.6.44  	✅	✅	✅	✅	✔️	✔️	✔️	✅
5.7.31  	✅	✅	✅	✅	✅	✅	✔️	✅
5.7.36  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.22  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.25  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.26  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.27  	✅	✅	✅	✅	✅	✅	✔️	✅
8.0.28  	✅	✅	✅	✅	✅	✅	✔️	✅
```

**Comment by hawkingrei** [comment]
Have some error in the linter. Please fix it.

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
