### PR TITLE
planner: set schema column be the same with new expr one

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tics/issues/1695 

Problem Summary: 

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: set schema column be the same with new expr one

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by hanfei1991 — APPROVED** [review]

**Review by lzmhhh123 — APPROVED** [review]

**Review by ilovesoup — CHANGES_REQUESTED** [review]
please add ut.

**Pull request merged**
