### PR TITLE
executor: forbid SFU on view

### LINKED ISSUE #21335: `select for update` doesn't seem to work on views in some cases
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
/* init */ drop table if exists t;
/* init */ drop view if exists v;
/* init */ create table t(a int primary key, b int);
/* init */ create view v as select a, b from t;
/* init */ insert into t values(1,2),(2,3);

/* t1 */ begin;
/* t2 */ begin;
/* t1 */ update t set b = 12 where a = 1;
/* t2 */ select * from v where a < 2 for update; -- range-scan on view, not blocked
# /* t2 */ select * from v where a = 1 for update; -- point-get on view, blocked
# /* t2 */ select * from t where a < 2 for update; -- range-scan on table, blocked
# /* t2 */ select * from t where a = 1 for update; -- point-get on table, blocked
/* t1 */ commit;
/* t2 */ commit;
```

### 2. What did you expect to see? (Required)

`select * from v where a < 2 for update;` should be blocked by t1.

### 3. What did you see instead (Required)

It's not blocked. 

### 4. What is your TiDB version? (Required)

release-4.0 (1e73c51515e123e3066fa5abeb14430551d00758)

### PR DESCRIPTION
**Pull request by lysu**
Signed-off-by: lysu <sulifx@gmail.com>

### What problem does this PR solve?

Issue Number: close #21335

Problem Summary:

just as issue said

### What is changed and how it works?

What's Changed, How it Works:

check SFU on view in ast -> plan stage

### Related changes

- Need to cherry-pick to the release branch 5.1

### Check List 

Tests 

- Unit test

Side effects

- n/a

### Release note 

- forbid SELECT FOR UPDATE on view

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/22146)

### CODE REVIEW

**Comment by you06** [comment]
`select * from t where c1 in (select * from v) for update` should be executed but got fail.

**Comment by lysu** [comment]
> `select * from t where c1 in (select c1 from v) for update` should be executed but got fail.

good catch, and added more test case, ptal if free~

**Review by you06 — COMMENTED** [review]
LGTM

**Review by tangenta — APPROVED** [review]
LGTM

**Comment by zz-jason** [comment]
@lysu It's a major bug-fix, no need to cherry-pick to 5.o-rc.

**Review by winoros — APPROVED** [review]

**Comment by qw4990** [comment]
Can we merge it? @lysu

**Comment by zz-jason** [comment]
I'm going to close this PR since it hasn't been updated for a long time. Feel free to reopen it once you wish to advance this PR in the future.

**Pull request closed without merging**
