### PR TITLE
executor: push some flags down to coprocessor

### PR DESCRIPTION
**Pull request by XuHuaiyu**
This commit pushes some flags to the coprocessor,
for further supporting handling warnings in the coprocessor.

PTAL @coocood @zz-jason @AndreMouche

### CODE REVIEW

**Comment by tiancaiamao** [comment]
CI failed @XuHuaiyu

**Comment by coocood** [comment]
@XuHuaiyu 
The ordering affects the values for constants init by `iota`.
And the flag values should not change when it's used persists in TiKV.

**Comment by XuHuaiyu** [comment]
PTAL @coocood @zz-jason

**Pull request merged**
