### PR TITLE
printer: update 'TiKVMinVersion' to '2.1.0-alpha.1'

### PR DESCRIPTION
**Pull request by zz-jason**
Thank you for working on TiDB! Please read TiDB's [CONTRIBUTING](https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md) document **BEFORE** filing this PR.

## What have you changed? (mandatory)

Update TiKV min version to "2.1.0-alpha.1" for the following reasons:
1. We have pushed some builtin functions to TiKV in master branch
2. TiKV also have some bugfixes about some builtin functions 

## What are the type of the changes (mandatory)?

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested (mandatory)?

- unit test

## Does this PR affect documentation (docs/docs-cn) update? (optional)

No.

## Add a few positive/negative examples (optional)

### CODE REVIEW

**Comment by shenli** [comment]
@zz-jason We need to add exact githash in the minversion. Because `2.1.0-alpha.1` is not a fixed version.

**Comment by shenli** [comment]
@BusyJay @siddontang PTAL

**Comment by zz-jason** [comment]
@shenli Done

**Comment by shenli** [comment]
LGTM
@BusyJay PTAL

**Pull request merged**
