### PR TITLE
test: test new bot

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

-

### CODE REVIEW

**Comment by hi-rustin** [comment]
lgtm

**Review by Mini256 — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
merge

**Comment by hi-rustin** [comment]
Your PR was out of date, I have automatically updated it for you.
At the same time I will also trigger all tests for you:
/run-all-tests
If the CI test fails, you just re-trigger the test that failed and the bot will merge the PR for you after the CI passes.

**Comment by hi-rustin** [comment]
Your PR was out of date, I have automatically updated it for you.
At the same time I will also trigger all tests for you:
/run-all-tests
If the CI test fails, you just re-trigger the test that failed and the bot will merge the PR for you after the CI passes.

**Pull request closed without merging**
