### PR TITLE
executor: change read slow-log file module to concurrent

### LINKED ISSUE #20890: Change read slow-log file module to concurrent
## Description
Currently, reading the slow-log is a serial operation, which greatly reduces the efficiency of the slow log query, so we can change the read operation to a concurrent mode to speed up it.
IMO, We can try to use multiple threads to read one slow log file, which I think will greatly speed up the slow log file reading speed.

**You can see `/executor/slow_query.go` to know more.**

## Score

- 300

## Mentor

- @jyz0309
- @crazycs520 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go

## Learning Materials
* [慢查询文档](https://pingcap.com/docs-cn/dev/how-to/maintain/identify-abnormal-queries/identify-slow-queries/)
* use `slowQueryRetriever` search in TiDB code to see related implemention code.
* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

### PR DESCRIPTION
**Pull request by pengdaqian2020**
### What problem does this PR solve?

Issue Number: close #20890

Problem Summary:

### What is changed and how it works?

What's Changed:

concurrent read slow-log file

How it Works:

concurrent read slow-log file

### Check List

Tests

- No code

Side effects

- Performance regression
    - Consumes more CPU
No
    - Consumes more MEM
No
- Breaking backward compatibility
No

### Release note 

- change read slow-log file module to concurrent

### CODE REVIEW

**Comment by pengdaqian2020** [comment]
@jyz0309
@crazycs520
PLAT

**Comment by jyz0309** [comment]
please add some test for this pr. And add the slow log query speed comparison chart modified by this pull request in your comment

**Comment by jyz0309** [comment]
And also I think you can try to use multiple go routines to read one single slow log file.Not only use go routines to read Multiple slow-log files

**Comment by pengdaqian2020** [comment]
> Please add the slow log query speed comparison chart modified by this pull request in your comment

It means I need a flag to control whether read concurrent, right ?

**Comment by jyz0309** [comment]
> > Please add the slow log query speed comparison chart modified by this pull request in your comment
> 
> It means I need a flag to control whether read concurrent, right ?

I mean you can add how much performance has been improved by this pr In your pr description, you can see this pr description as a example [tidb/pull/19139](https://github.com/pingcap/tidb/pull/19139)

**Comment by pengdaqian2020** [comment]
> And also I think you can try to use multiple go routines to read one single slow log file.Not only use go routines to read Multiple slow-log files

`use multiple go routines to read one single slow log file`
How can I do this ?
the `getBatchLog` can be disorderly ?

**Comment by pengdaqian2020** [comment]
> use multiple go routines to read one single slow log file.

use multiple go routines to read one single slow log file means what ?
use multiple go routines to read one single slow log file means I should change `getBatchLog` ?

**Comment by jyz0309** [comment]
> > use multiple go routines to read one single slow log file.
> 
> use multiple go routines to read one single slow log file means what ?
> use multiple go routines to read one single slow log file means I should change `getBatchLog` ?

yeah, and you can try to concurrency with keep log order refer to [this](https://www.zenlife.tk/concurrency-with-keep-order.md)

**Comment by pengdaqian2020** [comment]
It seems that `getAllFiles` will use multiple go routines to read multiple files.
and then `parseSlowLog` will use single go routine read logfile **line by line** and **one by one** (invoke `getBatchLog`) (use another go routines parse log).
`use multiple go routines to read one single slow log file` means I should **use multiple go routines read lines concurrently** instead of **line by line** ? How can I do this ?
Or it means I should **read file concurrently** ( I should read from file concurrently, now it's serial, read file **one by one** )
If I do like this,  because of `getBatchLog` has `num` limit. How many files to read?

**Comment by jyz0309** [comment]
> It seems that `getAllFiles` will use multiple go routines to read multiple files.
> and then `parseSlowLog` will use single go routine read logfile **line by line** and **one by one** (invoke `getBatchLog`) (use another go routines parse log).
> `use multiple go routines to read one single slow log file` means I should **use multiple go routines read lines concurrently** instead of **line by line** ? How can I do this ?
> Or it means I should **read file concurrently** ( I should read from file concurrently, now it's serial, read file **one by one** )
> If I do like this, because of `getBatchLog` has `num` limit. How many files to read?

You can try to divide a slow-log file into several blocks evenly, and then specify a go routine to read each block. Also, currently read-slow-log is to read 64 logs one time, you can try to read 1600 lines each time instead, and then divide the 1600 lines into quarters, and read 400 lines for each go routine.

**Comment by zz-jason** [comment]
I'm going to close this PR since it hasn't been updated for a long time. feel free to reopen if you want to continue with it. thank you for your contribution.

**Pull request closed without merging**
