### PR TITLE
executor: add column character sets when show create table

### PR DESCRIPTION
**Pull request by ciscoxll**
Cherry pick #8866

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8464)

### CODE REVIEW

**Comment by ciscoxll** [comment]
@winkyao @crazycs520 PTAL.

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by winkyao** [comment]
@ciscoxll tidb-test need to cherry-pick.

**Pull request merged**
