### PR TITLE
move CONTRIBUTING to root

### PR DESCRIPTION
**Pull request by astaxie**
fix the issue https://github.com/pingcap/tidb/issues/845

### CODE REVIEW

**Comment by ngaut** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
I think we should update `CONTRIBUTING.md` link in README.

**Comment by astaxie** [comment]
@qiuyesuifeng good catch. Here we go https://github.com/astaxie/tidb/commit/2ca2c8e61b150ff09b89cfd8a6ba4f9343580960

**Comment by qiuyesuifeng** [comment]
@astaxie  Thanks.
LGTM

**Comment by disksing** [comment]
Hi @astaxie 
There are links in `CONTRIBUTING.md` need to be updated too :)

**Comment by astaxie** [comment]
@disksing :see_no_evil: updated

**Comment by disksing** [comment]
Thanks! @astaxie 
LGTM

**Pull request merged**
