### PR TITLE
ddl: make TestTransactionOnAddDropColumn and  TestTransactionWithWriteOnlyColumn  stable

### LINKED ISSUE #16485: db_test.go:testDBSuite2.TestTransactionOnAddDropColumn failed
db_test.go:testDBSuite2.TestTransactionOnAddDropColumn

Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/32659/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/32658/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/32613/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/32578/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/32628/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/32661/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/32553/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/32677/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/32665/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/32546/display/redirect

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?
Issue Number: close #16485 and #16488, and it may handle #13641 

```
[2020-04-16T10:24:51.537Z] ----------------------------------------------------------------------
[2020-04-16T10:24:51.537Z] FAIL: db_test.go:3379: testDBSuite2.TestTransactionOnAddDropColumn
[2020-04-16T10:24:51.537Z]
[2020-04-16T10:24:51.537Z] db_test.go:3431:
[2020-04-16T10:24:51.537Z]     c.Assert(checkErr, IsNil)
[2020-04-16T10:24:51.537Z] ... value *errors.fundamental = err: previous statement: update t1 set b=1 where a=1: [domain:8028]Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later], sql: commit, job schema state: write only ("err: previous statement: update t1 set b=1 where a=1: [domain:8028]Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later], sql: commit, job schema state: write only")
[2020-04-16T10:24:51.537Z]
```

Issue Number: close #16485 

Problem Summary:
For adding column operation, when the job with the schema state of `write only` put to `OnJobRunBeforeExported`, but the current TiDB doesn't load the schema(the new column is write-only state). Then we begin a transaction and do some operations. After that, we may load the schema. When we commit this transaction, we will find the schema is changed.

WeChatWorkScreenshot_ce18f7ae-8909-458f-a3b7-24b02e5aa510

### What is changed and how it works?

What's Changed:
Increase the value of DDL lease. 

The test execution speed has remained basically unchanged. Using `go test -v -vet=off -p 20 -timeout 3m -race  -check.f testDBSuite` to check. The following are the results of two executions：
Before this PR
`--- PASS: TestT (52.01s)`
`--- PASS: TestT (44.07)`
After this PR
`--- PASS: TestT (47.06s)`
`--- PASS: TestT (44.86s)`

How it Works:
Make TiDB has more time to load schema.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 
- No code

### Release note 
Make TestTransactionOnAddDropColumn stable

### CODE REVIEW

**Comment by zimulala** [comment]
run-integration-copr-test

**Comment by wjhuang2016** [comment]
run-integration-copr-test

**Pull request merged**
