### PR TITLE
*: Fix the wrong usage of go.mod replace

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

### What problem does this PR solve?

Fix the wrong usage of go.mod replace.

`replace` in `go.mod` only affects current modules build and other modules that depend on this module will not be effected.

### What is changed and how it works?

In this PR, I finished the following work:

- Specify the version directly instead of `replace` it.

### Check List

Tests

- Unit test
- Integration test

### Release note

- No release note

### CODE REVIEW

**Comment by Xuanwo** [comment]
ping @ichn-hu for a reivew.

**Review by leiysky — APPROVED** [review]
LGTM

**Review by ichn-hu — APPROVED** [review]

**Pull request merged**
