### PR TITLE
util/mock: optimize mock.NewContext

### PR DESCRIPTION
**Pull request by coocood**
### What problem does this PR solve? 
This function takes 6.5% of the CPU usage in faketikv in sysbench index update workload.
This PR optimize the performance of `mock.NewContext`. It can also speed up unit-test.

Performance improvement is 77x:

From
20000	     75189 ns/op	   85596 B/op	      42 allocs/op

To
2000000	       972 ns/op	    2016 B/op	      15 allocs/op

### What is changed and how it works?
Do not create a map and set every global variable to that map.
We never need to set the global variable with mock context.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by coocood** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
