### PR TITLE
infoschema: set collate and charset to null for non-varchar column type

### PR DESCRIPTION
**Pull request by zhexuany**
TiDB's behavior is inconsistent with mysql. Below is a reproduce guide.

```
use test;
create table t (c1 int, s1 varchar(10));
select table_name, column_name, column_type, character_set_name FROM information_schema.COLUMNS WHERE table_schema = 'test';
```
In TiDB, it returns:
```
+------------+-------------+-------------+--------------------+
| table_name | column_name | column_type | character_set_name |
+------------+-------------+-------------+--------------------+
| t          | c1          | int(11)     | binary              |
| t          | s1          | varchar(10) | utf8               |
+------------+-------------+-------------+--------------------+
2 rows in set (0.00 sec)
```
In mysql, it returns:
```
+------------+-------------+-------------+--------------------+
| table_name | column_name | column_type | character_set_name |
+------------+-------------+-------------+--------------------+
| t          | c1          | int(11)     | NULL               |
| t          | s1          | varchar(10) | utf8               |
+------------+-------------+-------------+--------------------+
2 rows in set (0.00 sec)
```

### CODE REVIEW

**Comment by zhexuany** [comment]
@zimulala anywhere to add tests? Tried to add some tests but fail to find correct place to add.

**Comment by zhexuany** [comment]
@zimulala PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Comment by zhexuany** [comment]
@zz-jason @tiancaiamao PTAL again, I made new changes.

**Pull request merged**
