### PR TITLE
Revert "expression: push down mod() to TiFlash (#26494) (#27865)"

### PR DESCRIPTION
**Pull request by windtalker**
This reverts commit d4cd12fe422fb18b6012607ee18b6acca40d9225.

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
This reverts commit d4cd12fe422fb18b6012607ee18b6acca40d9225.
```

### CODE REVIEW

**Review by fzhedu — APPROVED** [review]
/LGTM

**Review by rebelice — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
@ti-chi-bot

**Pull request merged**
