### PR TITLE
ddl: delay before changing column from null to not null (#23364)

### LINKED ISSUE #23363: Risk of breaking consistency when changing column from null to not null
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Initial table:

```sql
CREATE TABLE t (id INT PRIMARY KEY, v INT);
INSERT INTO t VALUES (0, 0);
```
Change the value to `NULL` and change the value to not null concurrently.

```sql
-- Session 1
BEGIN;

-- Session 2 (Concurrently)
ALTER TABLE t MODIFY COLUMN v INT NOT NULL;

-- Session 1 (Concurrently)
UPDATE t SET v = NULL WHERE ID = 0;
COMMIT;
```

### 2. What did you expect to see? (Required)

Either the DDL or the transaction fails.

### 3. What did you see instead (Required)

I think it is possible that both the DDL and the transaction succeed. Because under async commit, there is no check after the not null flag is added.

Then, the table contains NULL, but the column schema is NOT NULL.

I'm still trying to create a test case that can reproduce it.

### 4. What is your TiDB version? (Required)

5.0/nightly

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23364 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23424
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23424:release-5.0-e79ac3d978cf
```

---

### What problem does this PR solve?

Issue Number: close #23363

### What is changed and how it works?

Before the double check of changing null to not null, we should delay like the reorg to make async commit safe.

After the delay, if an async commit writes a NULL, the double null check must detect it.

### Check List 

Tests 

- Integration test

### Release note 

- No release note.

### CODE REVIEW

**Comment by cfzjywxk** [comment]
LGTM

**Comment by sticnarf** [comment]
PTAL @wjhuang2016 @AilinKid

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
