### PR TITLE
sessionctx/variable: small refactor (split large file)

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Problem Summary:

This is a functionality neutral refactor. It moves the framework for variables to `variable.go`, leaving the default sysvars in `sysvar.go`. The logic for doing this is as follows:

* The `sysvar.go` file has grown massively as we've moved validation into it.
* I would like to suggest in future (not in this PR) we relax reviewer requirements for the variable framework, but still require review for `sysvar.go` or `noop.go`. This allows bugs to be fixed, but keeps strict review on our externally facing API, since once a sysvar is introduced it could be compatibility breaking to remove it.

In addition, one small function is moved to `varsutil.go` which is where most existing helper funcs are located.

### What is changed and how it works?

Small refactor (code moved). Completely function neutral.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code
No code changes, and existing tests pass.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility
- [x] Breaking merges
As with any refactors, there might be slightly more work with cherry picking PRs. However in most cases changes are to the default variables not the framework.

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by xhebox** [comment]
@bb7133 Need an approve from the configuration owner

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
