### PR TITLE
ddl: Disable RENAME COLUMN for partitioning columns | tidb-test=pr/2054

### LINKED ISSUE #40150: Rename column for partition columns give different error from MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

My main issue with this is that it should be prohibited even before sent to the DDL Queue, since it is not supported in MySQL. Now it will fail internally while processing the DDL queue, due to verification of the intermediate table.

Related to #40147

### 1. Minimal reproduce step (Required)

```
create table t (a int) partition by hash(a) partitions 2;
alter table t rename column a to b;
```

### 2. What did you expect to see? (Required)
```sql
mysql> create table t (a int) partition by hash(a) partitions 2;
Query OK, 0 rows affected (0,04 sec)

mysql> alter table t rename column a to b;
ERROR 3855 (HY000): Column 'a' has a partitioning function dependency and cannot be dropped or renamed.
```

### 3. What did you see instead (Required)
```sql
tidb> create table t (a int) partition by hash(a) partitions 2;
Query OK, 0 rows affected (0.06 sec)

tidb> alter table t rename column a to b;
ERROR 1054 (42S22): Unknown column 'a' in 'expression'
```

### 4. What is your TiDB version? (Required)

```
tidb_version(): Release Version: v6.6.0-alpha-71-g014159df0a
Edition: Community
Git Commit Hash: 014159df0a22c29d6cf15e026dcca3fddabad13e
Git Branch: master
UTC Build Time: 2022-12-23 12:06:22
GoVersion: go1.19
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
```

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #40150

Problem Summary:
There were no check for renaming a partitioning column, so it queued the DDL and got an errror during validation of the new table instead.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Comment by wuhuizuo** [comment]
> /test mysql-test tidb-test=pr/2054

@mjonss 
Could you retitle it to: `ddl: Disable RENAME COLUMN for partitioning columns | tidb-test=pr/2054` , and then comment with `/retest`.
I try to fix it by: https://github.com/PingCAP-QE/ci/pull/1670

All PR jobs in this repo were converted to prow job style(triggered by bot), it does not support setting branch of peer repo in comment to run jobs anymore.

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
