### PR TITLE
session, sessionctx/variable: fix validation recursion bug

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/30255

Problem Summary:

This fixes a regression introduced by https://github.com/pingcap/tidb/pull/29594

It is not safe to call validation functions that load global variables because the load could trigger validation recursion.

While it is likely possible that we could fix the offending validation function, a simpler approach is taken which is to only do type validation instead. This still solves the [original issue](https://github.com/pingcap/tidb/issues/29587), but has lower risk of future regressions. This is because it is expected that other validation functions might want to load other global variables.

This only affects master (no release note).

### What is changed and how it works?

TiDB now only validates global values for type consistency when loading them, and does not run the validation function.

### Check List

Tests 

- [x] Unit test
Covered by existing test introduced in https://github.com/pingcap/tidb/pull/29594
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
OK, LGTM

**Review by dveeden — APPROVED** [review]
```
sql> REPLACE INTO mysql.global_variables (variable_name, variable_value) VALUES ('tidb_enable_noop_functions', '1'); DO SLEEP(30); SHOW GLOBAL VARIABLES LIKE 'tidb_enable_noop_functions';
Query OK, 1 row affected (0.0014 sec)
Query OK, 0 rows affected (30.0104 sec)
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| tidb_enable_noop_functions | ON    |
+----------------------------+-------+
1 row in set (0.0060 sec)

sql> REPLACE INTO mysql.global_variables (variable_name, variable_value) VALUES ('tidb_enable_noop_functions', '0');DO SLEEP(30);SHOW GLOBAL VARIABLES LIKE 'tidb_enable_noop_functions';
Query OK, 2 rows affected (0.0020 sec)
Query OK, 0 rows affected (30.0021 sec)
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| tidb_enable_noop_functions | OFF   |
+----------------------------+-------+
1 row in set (0.0055 sec)

sql> REPLACE INTO mysql.global_variables (variable_name, variable_value) VALUES ('tidb_enable_noop_functions', 'maybe');DO SLEEP(30);SHOW GLOBAL VARIABLES LIKE 'tidb_enable_noop_functions';
Query OK, 2 rows affected (0.0027 sec)
Query OK, 0 rows affected (30.0023 sec)
ERROR: 1231 (42000): Variable 'tidb_enable_noop_functions' can't be set to the value of 'maybe'

sql> REPLACE INTO mysql.global_variables (variable_name, variable_value) VALUES ('tidb_enable_noop_functions', '2');DO SLEEP(30);SHOW GLOBAL VARIABLES LIKE 'tidb_enable_noop_functions';
Query OK, 2 rows affected (0.0020 sec)
Query OK, 0 rows affected (30.0015 sec)
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| tidb_enable_noop_functions | WARN  |
+----------------------------+-------+
1 row in set (0.0060 sec)

sql> SELECT variable_name, variable_value FROM mysql.global_variables WHERE variable_name='tidb_enable_noop_functions';
+----------------------------+----------------+
| variable_name              | variable_value |
+----------------------------+----------------+
| tidb_enable_noop_functions | 2              |
+----------------------------+----------------+
1 row in set (0.0011 sec)

sql> REPLACE INTO mysql.global_variables (variable_name, variable_value) VALUES ('tidb_enable_noop_functions', '666');DO SLEEP(30);SHOW GLOBAL VARIABLES LIKE 'tidb_enable_noop_functions';
Query OK, 2 rows affected (0.0022 sec)
Query OK, 0 rows affected (30.0018 sec)
ERROR: 1231 (42000): Variable 'tidb_enable_noop_functions' can't be set to the value of '666'

sql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.4.0-alpha-276-gb448e477c
Edition: Community
Git Commit Hash: b448e477c02f775652b1bf6dfc28c8ca0f0603d3
Git Branch: fix-global-validation
UTC Build Time: 2021-12-01 08:39:51
GoVersion: go1.16.8
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.0012 sec)
```

**Comment by bb7133** [comment]
Could you add a test case for #30255?

**Comment by morgo** [comment]
> Could you add a test case for #30255?

Addressed in https://github.com/pingcap/tidb/pull/30293/commits/f4698db02525ecb8c63e718517d8ebbdc691cc51 PTAL again, thx!

**Review by djshow832 — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
