### PR TITLE
tidb: err should rollback in auto commit or DDL.

### PR DESCRIPTION
**Pull request by siddontang**
@shenli  @coocood

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by coocood** [comment]
In `FinishTxn`, if rollback, the `resetHistory` is not called.
The history is reset when the next time `GetTxn` method is call, as `txn` is nil, the history is reset.

I think we can move the `resetHistory` from `GetTxn` to `FinishTxn`, put it in defer clause, so the same logic will not be scattered in two places.

**Comment by siddontang** [comment]
PTAL @coocood

**Comment by coocood** [comment]
LGTM

**Pull request merged**
