### PR TITLE
planner: enrich diagnosis info for plan-cache

### LINKED ISSUE #39147: planner: enrich diagnosis info for plan-cache
## Enhancement
Output reasons why some queries cannot use plan-cache through warnings.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #39147

Problem Summary: planner: enrich diagnosis info for plan-cache

### What is changed and how it works?

Output why this query or plan cannot use plan-cache.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Reminiscent — APPROVED** [review]

**Review by fzzf678 — APPROVED** [review]

**Comment by winoros** [comment]
@ti-chi-bot

**Pull request merged**
