### PR TITLE
config: add GOGC under performance section (#20872)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20872 to release-4.0

---

### What is changed and how it works?
Add a new config item to the change GOGC setting. https://github.com/pingcap/tidb/pull/20247 already allows change this setting dynamically.

### Release note 

- Allow set GOGC in config file.

### CODE REVIEW

**Review by jackysp — COMMENTED** [review]
LGTM

**Comment by lysu** [comment]
LGTM

**Comment by zz-jason** [comment]
@bobotu please resolve conflicts.

**Review by jackysp — APPROVED** [review]

**Pull request merged**
