### PR TITLE
planner: create new column slice in PreparePossibleProperties

### LINKED ISSUE #24281: out of index[-1] for ColumnIndex
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
`func (s *Schema) ColumnIndex(col *Column) int` [this func](https://github.com/pingcap/tidb/blob/642527d740a981f898360b14358e9c1f731311da/expression/schema.go#L121) return -1 if cannot find a column, but this case does not hold for calling functions, such as func (p *LogicalProjection) [TryToGetChildProp](https://github.com/pingcap/tidb/blob/05bb31b81120197681196c6f54f8ac262f0d97c5/planner/core/exhaust_physical_plans.go#L1925). please fix all these bugs.

### 2. What did you expect to see? (Required)
https://asktug.com/t/topic/69881/4
### 4. What is your TiDB version? (Required)
5.0

### PR DESCRIPTION
**Pull request by francis0407**
### What problem does this PR solve?

Issue Number: close #24281 

Problem Summary:

Actually, the root cause of the issue is that the `LogicalAggregation.possibleProperties` is modified by `(p *LogicalProjection) PreparePossibleProperties`, which is unexpected. Hence, the Aggregation generates a wrong `requiredProperty` for its child.

### What is changed and how it works?

What's Changed:

This PR just creates a new slice for the `possibleProperties` instead of a in-place update.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

### Release note 

- fix "index out of range" error when a SQL contains both group by and union.

### CODE REVIEW

**Comment by francis0407** [comment]
cc @lzmhhh123

**Review by lzmhhh123 — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Pull request merged**
