### PR TITLE
executor: fix format of bit default value on INFORMATION_SCHEMA.COLUMNS

### LINKED ISSUE #32655: Format of bit default value on `INFORMATION_SCHEMA.COLUMNS` is wrong/inconsistent
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```SQL
test=> create table "bug" ("bit" bit(10) DEFAULT b'100');
CREATE TABLE
test=> show create table bug;
 Table |                        Create Table                         
-------+-------------------------------------------------------------
 bug   | CREATE TABLE "bug" (                                       +
       |   "bit" bit(10) DEFAULT b'100'                             +
       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin 
(1 row)
test=> SELECT COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'bug';
 COLUMN_DEFAULT 
----------------
 \x04 
(1 row)
```

### 2. What did you expect to see? (Required)
The following is MySQL output:
```SQL
test=> CREATE TABLE "bug" ("tBit" bit(10) DEFAULT b'100');
CREATE TABLE
test=> SELECT COLUMN_DEFAULT FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE TABLE_NAME = 'bug';
 COLUMN_DEFAULT 
----------------
 b'100' 
(1 row)
```

### 3. What did you see instead (Required)
```SQL
test=> SELECT COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'bug';
 COLUMN_DEFAULT 
----------------
 \x04 
(1 row)
```
### 4. What is your TiDB version? (Required)

```SQL
test=> SELECT tidb_version();
tidb_version()                          
-------------------------------------------------------------------
 Release Version: v5.4.0                                          
 Edition: Community                                               
 Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872        
 Git Branch: heads/refs/tags/v5.4.0                               
 UTC Build Time: 2022-01-25 08:39:26                              
 GoVersion: go1.16.4                                             
 Race Enabled: false                                              
 TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
 Check Table Before Drop: false 
(1 row)
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #32655

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix format of bit default value on INFORMATION_SCHEMA.COLUMNS
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @zimulala 
PTAL

**Review by zimulala — APPROVED** [review]
LGTM

**Pull request merged**
