### PR TITLE
table, executor: handle the column's version when it's greater than ColumnInfoVersion1 (#9488)

### PR DESCRIPTION
**Pull request by zimulala**
Cherry-pick #9488 to v2.1

### CODE REVIEW

**Comment by zimulala** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by cwen0** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
