### PR TITLE
store/tikv:move mockCommitErrorEnable from kv to tikv since it is only used in tikv

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: AndreMouche

### What problem does this PR solve?
This PR moves `mockCommitErrorEnable` from kv to tikv since it is only used in tikv
Part of https://github.com/pingcap/tidb/issues/22513

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by sticnarf — COMMENTED** [review]
/lgtm

**Review by sticnarf — APPROVED** [review]

**Pull request merged**
