### PR TITLE
server: fix no response when execute 0 statment

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs <crazycs520@gmail.com>

### What problem does this PR solve?

fix https://github.com/pingcap/tidb/issues/16758

### What is changed and how it works?

Should write a response when executing 0 statment.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Side effects

- No

### Release note 
 - Fix no response when execute `--` statment.

### CODE REVIEW

**Comment by bb7133** [comment]
Please:
1. add cherry-pick label
2. add 'release-note'

**Comment by crazycs520** [comment]
@lysu @tiancaiamao  PTAL

**Pull request merged**
