### PR TITLE
br: fix the --with-sys-table prompt

### LINKED ISSUE #50240: prompt not accurate when br restore with non-compatible system table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. run br restore to restore full backup of previous version of tidb cluster, which has uncompatible system tables.

### 2. What did you expect to see? (Required)
1. Restore should failed, with accurate prompt to let me to skip restore of system table.

### 3. What did you see instead (Required)
There prompt "you can remove 'with-sys-table' flag to skip restoring system tables" is not accurate, I need to specify --with-sys-table=false explicitely. 

image

### 4. What is your TiDB version? (Required)
br v7.6.0

### PR DESCRIPTION
**Pull request by BornChanger**
### What problem does this PR solve?

Issue Number: close #50240

Problem Summary:

1. Fix the prompt message on restore sys tables failure.
2. Fix an integration case

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by BornChanger** [comment]
ok-to-test

**Review by YuJuncen — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
