### PR TITLE
Travis-CI: Speed it up.

### PR DESCRIPTION
**Pull request by xiekeyi98**
### What problem does this PR solve? 

Now the Travis-CI is too slow.
And the IDC-dev is the same with Travis-CI.
Therefore, We could delete`make dev` in Travis-CI.
But now, I'm not sure the IDC-code-coverage works well, it is not time to delete Travis-CI.

### What is changed and how it works?

Now, Travis-CI only does something about code-coverage.
And because of [fast finish](https://docs.travis-ci.com/user/build-matrix/#fast-finishing), I think it will make Travis-CI speed up much.

### Check List 

Tests 
 - No code

Relate PR: https://github.com/pingcap/tidb/pull/9598
But the PR above is changed too much, I think now we should change it little by little is better.

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/9926)

### CODE REVIEW

**Comment by zz-jason** [comment]
@zhouqiang-cl Seems travis CI can be abandoned now?

**Comment by zhouqiang-cl** [comment]
@zz-jason we can have a try, maybe there is still something not works well in coverage。if it not work, then I and @xiekeyi98 will try to fix it

**Comment by xiekeyi98** [comment]
Merge this PR &&  abandon the Travis-CI is not contradictory.

-------

At the last weekly meeting, I think to abandon the Travis-CI in Ching Ming holidays is better.
Shall we abandon Travis-CI now @zz-jason ?
Abandon Travis-CI need the privilege of  @shenli .

**Comment by xiekeyi98** [comment]
@zz-jason  @winkyao  PTAL.

**Comment by winkyao** [comment]
@bb7133 PTAL

**Pull request merged**
