### PR TITLE
tidb: move tidb/*.go to session directory

### PR DESCRIPTION
**Pull request by tiancaiamao**
As suggested by @ngaut , we already have so many files (like Makefile LICENSE *.sh *.md) in tidb directory.
This change makes our top level directory cleaner.

PTAL @coocood

### CODE REVIEW

**Comment by tiancaiamao** [comment]
/run-integration-common-test tidb-test=pr/472 tidb-private-test=pr/7

**Comment by tiancaiamao** [comment]
/run-integration-common-test tidb-test=pr/472 tidb-private-test=pr/7

**Comment by tiancaiamao** [comment]
/run-integration-common-test tidb-test=pr/472 tidb-private-test=pr/7

**Comment by ngaut** [comment]
Please fix CI

**Comment by shenli** [comment]
@tiancaiamao Please fix the CI and resolve the conflicts.

**Comment by tiancaiamao** [comment]
/run-integration-common-test tidb-test=pr/472 tidb-private-test=pr/7

**Comment by tiancaiamao** [comment]
Fix data race for unit test here https://github.com/pingcap/tidb/pull/6096

**Comment by ngaut** [comment]
Good job.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
