### PR TITLE
bindinfo: fix the bind fields with quotes or slashes

### LINKED ISSUE #11708: Fields parsing with quotes or slash failed in `create global binding`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
tidb> show create table t;
+-------+-----------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                      |
+-------+-----------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` varchar(512) DEFAULT NULL,
  KEY `idx` (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-----------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
```
CREATE GLOBAL BINDING FOR  select * from t where a BETWEEN "a" and "b" USING select * from t use index(idx) where a BETWEEN "a" and "c";
```

2. What did you expect to see?
The statement executed successfully.

3. What did you see instead?
```
tidb>  CREATE GLOBAL BINDING FOR  select * from t where a BETWEEN "a" and "b" USING select * from t use index(idx) where a BETWEEN "a" and "c";
ERROR 1105 (HY000): line 1 column 48 near "\"a\" and \"c\""
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
tag: v3.0.2

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve? 
Fix #11708
```
tidb>  CREATE TABLE t (a varchar(512) DEFAULT NULL, KEY idx (a));
Query OK, 0 rows affected (0.01 sec)

tidb> CREATE GLOBAL BINDING FOR  select * from t where a BETWEEN "a" and "b" USING select * from t use index(idx) where a BETWEEN "a" and "c";
ERROR 1105 (HY000): line 1 column 48 near "\"a\" and \"c\""
```

### What is changed and how it works?
Remove the function of `getEscapeCharacter `.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by qw4990** [comment]
@zimulala Please fix the CI problem~

**Comment by zimulala** [comment]
PTAL @qw4990

**Comment by zz-jason** [comment]
Data race in the test is a known issue, will be fixed by https://github.com/pingcap/tidb/pull/11639.

**Pull request merged**
