### PR TITLE
*: clear delta info when roll back transaction (#5390)

### PR DESCRIPTION
**Pull request by lamxTyler**
This is a cherry pick.

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
/run-all-tests tidb-test=release-1.0 tidb-private-test=release-1.0

**Comment by coocood** [comment]
/run-all-tests tidb-test=release-1.0 tidb-private-test=release-1.0

**Comment by iamxy** [comment]
/run-all-tests tidb-test=release-1.0 tidb-private-test=release-1.0

**Comment by coocood** [comment]
/run-common-test tidb-test=release-1.0 tidb-private-test=release-1.0

**Pull request merged**
