### PR TITLE
statistics: fix unstable test

### LINKED ISSUE #29845: statistics: unstable test
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

make test

### 2. What did you expect to see? (Required)

passed

### 3. What did you see instead (Required)

=== RUN   TestStatistics/SubTestBuild
    statistics_serial_test.go:166: 
        	Error Trace:	statistics_serial_test.go:166
        	Error:      	Not equal: 
        	            	expected: 100000
        	            	actual  : 0
        	Test:       	TestStatistics/SubTestBuild
    --- FAIL: TestStatistics/SubTestBuild (1.12s)

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #29845 

Problem Summary:

### What is changed and how it works?

fix unstable tests by Independently using middleware.

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by rebelice — APPROVED** [review]

**Comment by winoros** [comment]
do we need to create an issue and link it? :joy:

**Comment by hawkingrei** [comment]
> do we need to create an issue and link it? 😂

I have created. PTAL.

**Review by winoros — APPROVED** [review]

**Pull request merged**
