### PR TITLE
test: fix unstable `TestIndexChange ` and `TestAlterAddConstraintStateChange3`

### LINKED ISSUE #49825: panic in the TestAlterAddConstraintStateChange3
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
panic: runtime error: index out of range [0] with length 0
goroutine 80540 [running]:
github.com/pingcap/tidb/pkg/ddl_test.TestAlterAddConstraintStateChange3.func1(0xc011fc5e00)
	pkg/ddl/constraint_test.go:235 +0x5af
github.com/pingcap/tidb/pkg/ddl/util/callback.(*TestDDLCallback).OnJobUpdated(0xc013e23e30, 0xc011fc5e00?)
	pkg/ddl/util/callback/callback.go:124 +0x1dd
github.com/pingcap/tidb/pkg/ddl.(*ddl).delivery2worker.func1()
	pkg/ddl/job_table.go:439 +0x171b
github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1()
	pkg/util/wait_group_wrapper.go:157 +0x87
created by github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run in goroutine 79460
	pkg/util/wait_group_wrapper.go:155 +0xe5 
```

### LINKED ISSUE #50079: flaky test TestIndexChange
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
     index_change_test.go:75: 
        	Error Trace:	pkg/ddl/index_change_test.go:75
        	            				pkg/ddl/util/callback/callback.go:124
        	            				pkg/ddl/job_table.go:439
        	            				pkg/util/wait_group_wrapper.go:157
        	            				src/runtime/asm_amd64.s:1650
        	Error:      	Not equal: 
        	            	expected: 3
        	            	actual  : 0
        	Test:       	TestIndexChange
        	Messages:   	job's row count 0 != 3 
```

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #50079, close #49825

Problem Summary:

To make the tests easy to reproduce:

```
--- a/pkg/ddl/job_table.go
+++ b/pkg/ddl/job_table.go
@@ -434,6 +434,9 @@ func (d *ddl) delivery2worker(wk *worker, pool *workerPool, job *model.Job) {
                                d.mu.hook.OnSchemaStateChanged(schemaVer)
                                d.mu.RUnlock()
                        }
+                       if job.SchemaState == model.StatePublic && job.State == model.JobStateSynced && job.TableName == "t" && job.Type == model.ActionCreateTable {
+                               time.Sleep(3000 * time.Millisecond)
+                       }
 
                        d.mu.RLock()
                        d.mu.hook.OnJobUpdated(job)
``` 

This pr:
1. Solve the unstable test.
2. Clean some useless code and make some enhencement.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Comment by Defined2014** [comment]
/cc @tangenta
PTAL

**Review by zimulala — APPROVED** [review]

**Pull request merged**
