### PR TITLE
ddl: support range partition in show table status

### PR DESCRIPTION
**Pull request by ciscoxll**
## What have you changed? (mandatory)

* Support ` show table status ` command shows whether table types for the partition table.
* Fix `show table status` display `Create_time` is wrong.

* master branch
```sql
mysql> show table status;
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+-----------------+----------+----------------+---------+
| Name | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time         | Check_time          | Collation       | Checksum | Create_options | Comment |
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+-----------------+----------+----------------+---------+
| t1   | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | utf8_general_ci |          |                |         |
| t3   | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | utf8_general_ci |          |                |         |
| t4   | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | utf8_general_ci |          |                |         |
| t7   | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | utf8_general_ci |          |                |         |
| t9   | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | utf8_general_ci |          |                |         |
| test | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | utf8_general_ci |          |                |         |
| tp   | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | 2018-07-27 16:42:53 | utf8_general_ci |          |                |         |
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+-----------------+----------+----------------+---------+
7 rows in set (0.00 sec)
```
* show-table-status branch
```sql
mysql> show table status;
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+-----------------------------------+---------------------+---------------------+-----------------+----------+----------------+---------+
| Name | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time                       | Update_time         | Check_time          | Collation       | Checksum | Create_options | Comment |
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+-----------------------------------+---------------------+---------------------+-----------------+----------+----------------+---------+
| t1   | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-26 00:37:16.248 +0800 CST | 2018-07-27 16:39:28 | 2018-07-27 16:39:28 | utf8_general_ci |          |                |         |
| t3   | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-25 15:34:15.243 +0800 CST | 2018-07-27 16:39:28 | 2018-07-27 16:39:28 | utf8_general_ci |          |                |         |
| t4   | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-26 00:37:32.066 +0800 CST | 2018-07-27 16:39:28 | 2018-07-27 16:39:28 | utf8_general_ci |          |                |         |
| t7   | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-25 14:58:42.896 +0800 CST | 2018-07-27 16:39:28 | 2018-07-27 16:39:28 | utf8_general_ci |          |                |         |
| t9   | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-26 10:11:30.711 +0800 CST | 2018-07-27 16:39:28 | 2018-07-27 16:39:28 | utf8_general_ci |          |                |         |
| test | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-25 15:10:38.861 +0800 CST | 2018-07-27 16:39:28 | 2018-07-27 16:39:28 | utf8_general_ci |          |                |         |
| tp   | InnoDB |      10 | Compact    |  100 |            100 |         100 |             100 |          100 |       100 |            100 | 2018-07-27 16:38:46.328 +0800 CST | 2018-07-27 16:39:28 | 2018-07-27 16:39:28 | utf8_general_ci |          | partitioned    |         |
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+-----------------------------------+---------------------+---------------------+-----------------+----------+----------------+---------+
```

## What is the type of the changes? (mandatory)

New feature
- New feature (non-breaking change which adds functionality)
- Improvement (non-breaking change which is an improvement to an existing feature)
- Bug fix (non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this PR been tested? (mandatory)
 No

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

## Does this PR need to be added to the release notes? (mandatory)
No

### CODE REVIEW

**Comment by shenli** [comment]
Is it the same with MySQL?

**Comment by shenli** [comment]
Please add labels for the PR.

**Comment by ciscoxll** [comment]
@shenli Yes, it's the same as mysql.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
