### PR TITLE
types: check values equals to NaN or Inf when convert to float

### LINKED ISSUE #29015: Incorrectly insert invalid float value NaN
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
use test;
create table t(a double);
```

Run the following golang code:
```
package main

import (
    "database/sql"
    _ "github.com/go-sql-driver/mysql"
    "log"
    "math"
)

func main() {
   db, err := sql.Open("mysql",
     "root:@tcp(127.0.0.1:4000)/test")
   if err != nil {
     log.Fatal(err)
   }
   defer db.Close()

   prepareStmt, err := db.Prepare("insert into t values(?)")
   if err != nil {
     log.Fatal(err)
   }

   var fo uint64 = 0xFFF0000000000001
   f := math.Float64frombits(fo)
   _, err = prepareStmt.Exec(f)
   if err != nil {
     log.Fatal(err)
   }
}
```
We should prohibit inserting Nan into TiDB in any way.

### 2. What did you expect to see? (Required)
```
Error 1264: Out of range value for column 'a' at row 1
```
### 3. What did you see instead (Required)
4.0
```
[tidb]> select * from t;
+------+
| a    |
+------+
|  NaN |
+------+
1 row in set (0.001 sec)
```

master
```
[tidb]> select a, a = 0, hex(a) from t;
+------+-------+------------------+
| a    | a = 0 | hex(a)           |
+------+-------+------------------+
|    0 |     0 | 8000000000000000 |
+------+-------+------------------+
1 row in set (0.001 sec)
```
hex(a) = 8000000000000000 and it is NaN
### 4. What is your TiDB version? (Required)
4.0 , 5.0, master

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #29015

Problem Summary: check values equals to NaN or Inf when convert to float

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Check for inf and NaN value when inserting float value
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @wshwsh12 @kennytm @SunRunAway @lzmhhh123 @yiwen92 @xhebox @wjhuang2016 
PTAL

**Comment by yiwen92** [comment]
LGTM. Could  you please add a capture picture for the test in related issue? Thx

**Review by yiwen92 — APPROVED** [review]

**Comment by Defined2014** [comment]
> LGTM. Could you please add a capture picture for the test in related issue? Thx

Use the test code from #29015, the result is shown below
image

**Review by xhebox — APPROVED** [review]

**Comment by Defined2014** [comment]
/cc @morgo
PTAL

**Comment by bb7133** [comment]
LGTM

**Comment by bb7133** [comment]
@Defined2014 Please update the "Release note" in your PR description.

**Comment by Defined2014** [comment]
> @Defined2014 Please update the "Release note" in your PR description.

Done, PTAL @bb7133

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
