### PR TITLE
*: Spelling, change ture to true

### LINKED ISSUE #36519: There are misspellings in the source code
## Bug Report

Some comments etc have misspellings.

Example: "ture" instead of "true"

Link for GitHub Codesearch: https://cs.github.com/?q=org%3Apingcap+%2F[^a-z]ture[^a-z]%2F (query: `org:pingcap /[^a-z]ture[^a-z]/`)

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: closes #36519

Problem Summary: Fix spelling of "true"

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by dveeden** [comment]
This is to split this out from #34753

**Review by xhebox — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
