### PR TITLE
planner: support new syntax for Index Advisor

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: ref #12303

Problem Summary: support new syntax for Index Advisor

### What changed and how does it work?

A few new syntax:
1. `recommend index run [for <SQL>]`;
2. `recommend index show`;
3. `recommend index set <option> = <value>`;
4. `recommend index ignore <ID>`;
5. `recommend index apply <ID>`;

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by elsa0520 — APPROVED** [review]
LGTM

**Comment by D3Hunter** [comment]
/approve

parser part lgtm

**Review by yudongusa — APPROVED** [review]
LGTM for new syntax

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
