### PR TITLE
meta,executor: fix show create table panic for temporary table with auto_increment columns

### PR DESCRIPTION
**Pull request by tiancaiamao**
<!-- Thank you for contributing to TiDB!

PR Title Format:
1. pkg [, pkg2, pkg3]: what's changed
2. *: what's changed

-->

### What problem does this PR solve?



Problem Summary:

When calling `show create table` on a temporary table with auto_increment columns, I get this panic:

```
[autoid:8026]not implemented                                                                                                                                                                                       
github.com/pingcap/errors.AddStack                                                                                                                                                                                 
        /home/genius/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174                                                                                                      
github.com/pingcap/errors.(*Error).GenWithStackByArgs                                                                                                                                                              
        /home/genius/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/normalize.go:156                                                                                                   
github.com/pingcap/tidb/meta/autoid.(*inMemoryAllocator).NextGlobalAutoID                                                                                                                                          
        /home/genius/project/src/github.com/pingcap/tidb/meta/autoid/memid.go:67                                                                                                                                   
github.com/pingcap/tidb/executor.ConstructResultOfShowCreateTable                                                                                                                                                  
        /home/genius/project/src/github.com/pingcap/tidb/executor/show.go:987                                                                                                                                      
github.com/pingcap/tidb/executor.(*ShowExec).fetchShowCreateTable                                                                                                                                                  
        /home/genius/project/src/github.com/pingcap/tidb/executor/show.go:1112                                                                                                                                     
github.com/pingcap/tidb/executor.(*ShowExec).fetchAll                                                                                                                                                              
        /home/genius/project/src/github.com/pingcap/tidb/executor/show.go:138                                                                                                                                      
github.com/pingcap/tidb/executor.(*ShowExec).Next                                                                                                                                                                  
        /home/genius/project/src/github.com/pingcap/tidb/executor/show.go:101                                                                                                                                      
github.com/pingcap/tidb/executor.Next                                                                                                                                                                              
        /home/genius/project/src/github.com/pingcap/tidb/executor/executor.go:286                                                                                                                                  
github.com/pingcap/tidb/executor.(*recordSet).Next                                                                                                                                                                 
        /home/genius/project/src/github.com/pingcap/tidb/executor/adapter.go:145                                                                                                                                   
github.com/pingcap/tidb/server.(*tidbResultSet).Next                                                                                                                                                               
        /home/genius/project/src/github.com/pingcap/tidb/server/driver_tidb.go:304                                                                                                                                 
github.com/pingcap/tidb/server.(*clientConn).writeChunks                                                                                                                                                           
        /home/genius/project/src/github.com/pingcap/tidb/server/conn.go:1875                                                                                                                                       
github.com/pingcap/tidb/server.(*clientConn).writeResultset                                                                                                                                                        
        /home/genius/project/src/github.com/pingcap/tidb/server/conn.go:1823                                                                                                                                       
github.com/pingcap/tidb/server.(*clientConn).handleStmt                                                                                                                                                            
        /home/genius/project/src/github.com/pingcap/tidb/server/conn.go:1717                                                                                                                                       
github.com/pingcap/tidb/server.(*clientConn).handleQuery                                                                                                                                                           
        /home/genius/project/src/github.com/pingcap/tidb/server/conn.go:1563                                                                                                                                       
github.com/pingcap/tidb/server.(*clientConn).dispatch                                                                                                                                                              
        /home/genius/project/src/github.com/pingcap/tidb/server/conn.go:1097                                                                                                                                       
github.com/pingcap/tidb/server.(*clientConn).Run                                                                                                                                                                   
        /home/genius/project/src/github.com/pingcap/tidb/server/conn.go:860                                                                                                                                        
github.com/pingcap/tidb/server.(*Server).onConn                                                                                                                                                                    
        /home/genius/project/src/github.com/pingcap/tidb/server/server.go:482                                                                                                                                      
runtime.goexit                                                                                                                                                                                                     
        /snap/go/7696/src/runtime/asm_amd64.s:1371  
```

### What is changed and how it works?

What's Changed:

How it Works:

Do not return the 'not implemented' error.



### Check List <!--REMOVE the items that are not applicable-->

Tests <!-- At least one of them must be included. -->

- Unit test



### Release note <!-- bugfixes or new feature need a release note -->

- No release note

### CODE REVIEW

**Review by djshow832 — APPROVED** [review]

**Review by djshow832 — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Comment by hi-rustin** [comment]
@ti-chi-bot Help!

**Pull request merged**
