### PR TITLE
*: use DatumRow for DML executors

### PR DESCRIPTION
**Pull request by jackysp**
Prepare for refactoring batch-check in the DML executors.

1. convert Datum slice to DatumRow for DML executors to make the style uniform.
2. simplify some code of DML executors

PTAL @zimulala @coocood

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by ngaut** [comment]
Please add description for your purpose.

**Comment by jackysp** [comment]
PTAL @ngaut

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
