### PR TITLE
ddl: enable fast create table on default

### LINKED ISSUE #57214: enable fast create table on default
## Enhancement
we plan to GA fast create table in 8.5, so will open it on default. if upgrade from older version, and it's not enabled, will enable automatically

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #57214

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

bootstrap new cluster, it should be enabled
upgrade from 8.1.1, it's keep old value after upgrade

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by yudongusa — APPROVED** [review]

**Comment by D3Hunter** [comment]
/hold

for a while,

**Review by Leavrth — APPROVED** [review]

**Pull request merged**
