### PR TITLE
planner,executor: use new table partition implementation and fix CI

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Use the new partition implementation as the default one, and fix unit test.

Problem Summary:

### What is changed and how it works?

What's Changed:

`tryNewPartitionImplementation` is change to `tryOldPartitionImplementation`, 
it means the code run the new implementation as default.

Fix bugs to make all the unit test pass.

- Point Get
- Partition selection
- UnionScan

### Check List 

Tests 

- Unit test

### Release note 

-  No release note

Wait for https://github.com/pingcap/tidb/pull/18862

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @imtbkcat  @lysu

**Comment by imtbkcat** [comment]
@tiancaiamao I think there are some mysql-test cases need to be fixed, rest LGTM

**Comment by tiancaiamao** [comment]
PTAL @lysu @imtbkcat

**Comment by tiancaiamao** [comment]
/rebuild

Seems it's still using the old tidb-test

**Pull request merged**
