### PR TITLE
expression: do not set ParseToJSONFlag to a JSON column (#8564)

### PR DESCRIPTION
**Pull request by XuHuaiyu**
cherry-pick #8564

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8662)

### CODE REVIEW

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=pr/687 tikv=release-2.0 pd=release-2.0

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=pr/687 tikv=release-2.0 pd=release-2.0

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=pr/687 tikv=release-2.0 pd=release-2.0

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=pr/687 tikv=release-2.0 pd=release-2.0

**Comment by XuHuaiyu** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Pull request merged**
