### PR TITLE
parser,executor: add tidb_current_tso() function

### LINKED ISSUE #37035: use sql to retrive current_tso
## Enhancement
We can only use `show variables like 'tidb_current_ts'` to retrive current tso, can we add scalar function like `current_tso()` for common use.

### PR DESCRIPTION
**Pull request by AndrewDi**
### What problem does this PR solve?
Issue Number: close #37035 

Problem Summary:

### What is changed and how it works?
Add new scalar function `current_tso()`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

```sql
begin;
select tidb_current_tso();
commit;
```

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Add a tidb specific builtin function `tidb_current_tso()`
```

### CODE REVIEW

**Review by ngaut — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]
Please resolve conflict.

**Comment by AndrewDi** [comment]
@tiancaiamao mysql-test fail....I didn't touch this one

**Comment by tiancaiamao** [comment]
PTAL @bb7133

**Comment by SunRunAway** [comment]
@AndrewDi 
Refer to https://docs.pingcap.com/tidb/dev/tidb-functions, cloud you name it "tidb_current_tso"? Thanks.

**Comment by AndrewDi** [comment]
> @AndrewDi Refer to https://docs.pingcap.com/tidb/dev/tidb-functions, cloud you name it "tidb_current_tso"? Thanks.

I think `select current_tso()` would be more close to the mysql original ecosystem...

**Comment by SunRunAway** [comment]
> > @AndrewDi Refer to https://docs.pingcap.com/tidb/dev/tidb-functions, cloud you name it "tidb_current_tso"? Thanks.
> 
> I think `select current_tso()` would be more close to the mysql original ecosystem...

I don't get why it is more close to the mysql original ecosystem. Could you explain more?

IMO, it is a TiDB-specific function, and we already have many functions named starting with "tidb_", such as "TIDB_PARSE_TSO(num)" (see https://docs.pingcap.com/tidb/dev/tidb-functions). 
It is more intuitive for the user to first use "**TIDB**_CURRENT_TSO" to get the TSO, and then use "**TIDB**_PARSE_TSO" to parse the TSO.

**Comment by AndrewDi** [comment]
@SunRunAway rename to tidb_current_tso

**Comment by AndrewDi** [comment]
/run-all/test

**Comment by AndrewDi** [comment]
@SunRunAway PTAL...

**Review by SunRunAway — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
