### PR TITLE
util/goroutine_pool: change the recycle stratege from queue to stack

### PR DESCRIPTION
**Pull request by tiancaiamao**
## What have you changed? (mandatory)

Change the pool struct from queue to stack.
If the pool organized as a queue, in a first in last out manner, all goroutines tend to exist longer.
Organize the pool as a stack maybe result in less goroutines and be more friendly to runtime scheduler.

## What are the type of the changes (mandatory)?

- Improvement (non-breaking change which is an improvement to an existing feature)

@coocood

### CODE REVIEW

**Comment by ngaut** [comment]
Any comparisons?

**Comment by tiancaiamao** [comment]
I can construct cases to prove that the FIFO style would caches more goroutines in the pool, but I'm not sure the user's scenario would fit into the pattern. If the goroutines are always hot, there will be no difference.

Anyway, this change would not be worse the before. @ngaut

**Comment by shenli** [comment]
Please post the benchmark result of sysbench/tpc-c .

**Comment by coocood** [comment]
@shenli I  think this doesn't affect the benchmark result.

@tiancaiamao 
We can construct a workload to prove this change results in less number of goroutines.

**Comment by lysu** [comment]
How about use `deque` instead of `stack`, get/put goroutine from `front`, check idle from `end`(which will be more like to be idle)

**Comment by winkyao** [comment]
Or we can add a prev pointer in goroutine, and when the goroutine is dead, removes self in the idle list.

**Comment by tiancaiamao** [comment]
Here is a example:

```
func dummy() {
	time.Sleep(20 * time.Millisecond)
}

func TestGoroutineCount(t *testing.T) {
	gp := New(100 * time.Second)
	for i := 0; i < 100; i++ {
		gp.Go(dummy)
	}

	ticker := time.NewTicker(time.Second)
	for {
		select {
		case <-ticker.C:
			gp.Go(dummy)
			gp.Lock()
			fmt.Println(len(gp.stack))
			gp.Unlock()
		}
	}
}
```

Run the test after 3 minutes, before this PR, it print:

```
99
99
99
99
99
99
99
99
99
99
99
99
99
99
99
99
99
99
99
99
99
99
99
99
```

After this PR:
```
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
```

**Comment by coocood** [comment]
LGTM

**Pull request merged**
