### PR TITLE
ddl: ignore integer zerofill size attribute when changing the column types (#20862)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20862 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/20529

#### how does it work? 
Like int(3), bigint(2), the number enclosed will be stored as `flen` in the field type, while it shouldn't be concerned when we make column type change from int(3) to(2) . Because bigint is quite larger than int, there is no need to take a reorg process.

#### what is changed
We should use the default `flen` of the specified field type rather than the origin `flen`.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- ddl: ignore integer zerofill size attribute when changing the column types

### CODE REVIEW

**Comment by bb7133** [comment]
@AilinKid Please resolve the conflicts.

**Comment by zz-jason** [comment]
@AilinKid please fix the build:

```
[2020-11-11T07:23:49.371Z] # github.com/pingcap/tidb/ddl

[2020-11-11T07:23:49.371Z] ddl/column.go:355:1: syntax error: non-declaration statement outside function body

[2020-11-11T07:23:49.371Z] ddl/column.go:363:1: syntax error: unexpected ==, expecting }

[2020-11-11T07:23:49.371Z] ddl/column.go:441:1: syntax error: unexpected >>, expecting }

[2020-11-11T07:23:49.371Z] ddl/column.go:441:98: invalid character U+0023 '#'

[2020-11-11T07:23:49.371Z] make: *** [importer] Error 2

[2020-11-11T07:23:49.933Z] # github.com/pingcap/tidb/ddl

[2020-11-11T07:23:49.933Z] ddl/column.go:355:1: syntax error: non-declaration statement outside function body

[2020-11-11T07:23:49.933Z] ddl/column.go:363:1: syntax error: unexpected ==, expecting }

[2020-11-11T07:23:49.933Z] ddl/column.go:441:1: syntax error: unexpected >>, expecting }

[2020-11-11T07:23:49.933Z] ddl/column.go:441:98: invalid character U+0023 '#'

[2020-11-11T07:23:49.933Z] make: *** [server] Error 2

[2020-11-11T07:23:49.933Z] # github.com/pingcap/tidb/ddl

[2020-11-11T07:23:49.933Z] ddl/column.go:355:1: syntax error: non-declaration statement outside function body

[2020-11-11T07:23:49.933Z] ddl/column.go:363:1: syntax error: unexpected ==, expecting }

[2020-11-11T07:23:49.933Z] ddl/column.go:441:1: syntax error: unexpected >>, expecting }

[2020-11-11T07:23:49.933Z] ddl/column.go:441:98: invalid character U+0023 '#'

[2020-11-11T07:23:49.933Z] make: *** [server] Error 2
```

**Review by bb7133 — COMMENTED** [review]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
lgtm

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
