### PR TITLE
ddl: split partition region when add a new partition (#16537)

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Cherry-pick https://github.com/pingcap/tidb/pull/16537 to release-3.0

### Release note 

-   Split partition region when adding a new partition

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @zimulala @crazycs520

**Comment by bb7133** [comment]
```
 1778 [2020-06-05T02:41:01.810Z] ----------------------------------------------------------------------
 1779 [2020-06-05T02:41:01.810Z] FAIL: lock_test.go:206: testLockSuite.TestCheckTxnStatusTTL
 1780 [2020-06-05T02:41:01.810Z] 
 1781 [2020-06-05T02:41:01.810Z] lock_test.go:218:
 1782 [2020-06-05T02:41:01.810Z]     c.Assert(status.ttl, Greater, uint64(0))
 1783 [2020-06-05T02:41:01.810Z] ... compare_one uint64 = 0x0                                              1784 [2020-06-05T02:41:01.810Z] ... compare_two uint64 = 0x0
 1785 [2020-06-05T02:41:01.810Z] 
```
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/38798/pipeline

**Pull request merged**
