### PR TITLE
*: fixed a mistake whileing adding sqrt math func

### PR DESCRIPTION
**Pull request by zhexuany**

### CODE REVIEW

**Comment by hanfei1991** [comment]
also change the test of sqrt function.

**Comment by zhexuany** [comment]
@hanfei1991 DONE.

**Comment by hanfei1991** [comment]
LGTM

**Comment by hanfei1991** [comment]
@coocood @shenli @tiancaiamao PTAL

**Comment by coocood** [comment]
LGTM

**Pull request merged**
