### PR TITLE
statistics: add an analysis job factory

### PR DESCRIPTION
**Pull request by Rustin170506**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/55906

Problem Summary:

### What changed and how does it work?

An analysis job factory was added to create different analysis jobs. This would help use to reuse code when we implement the new priority queue.

1. The job-related code has been moved to the job factory. 
3. The corresponding test has been relocated to the job factory tests. 
3. Additional tests have been added for the auto-analyze window.

Check out https://github.com/pingcap/tidb/pull/55889/files#r1758531218 to see how I used it in my new PR.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by AilinKid — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Comment by Rustin170506** [comment]
Conflicts resolved and rebased on the master branch.

**Pull request merged**
