### PR TITLE
*: fix mpp explain analyze wrong when mpp err recovery happens

### LINKED ISSUE #50221: mpp explain analyze is wrong when mpp err recovery happens in disaggregate mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. setup tidb cluster with **disaggregated and AutoScaler**(or set up tidb cluster with [these failpoints](https://github.com/pingcap/tidb/blob/master/pkg/executor/test/tiflashtest/tiflash_test.go#L1896C76-L1896C105)(mpp_recovery_test_mock_enable, mpp_recovery_test_ignore_recovery_err and mpp_recovery_test_max_err_times) enabled)
2. run the following sql:
```
drop table if exists t1;
create table t1(c1 int);
insert into t1 values(1), (2);
alter table t1 set tiflash replica 1;
explain select * from t1;
```

### 2. What did you expect to see? (Required)
actRows of explain analyze is `2` 
### 3. What did you see instead (Required)
actRows of explain analyze is `4`
### 4. What is your TiDB version? (Required)
```
Release Version: v7.6.0-alpha-dirty
Edition: Community
Git Commit Hash: c21846e2c848ca17c1a47f0ebf5f692be1eccbbf
Git Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time: 2024-01-08 14:00:30
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
```

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #50221

Problem Summary: 
When an 'mpp err recovery' occurs, 'actRows' records all the rows returned by all retry of the MPPTask. Sso if the table has 2 rows, and retry happens n times, tha actRows will be 2 + 2*n, which is unexpected.

This bug is because the logic of recording the execution summary is placed within the 'distsql' layer and directly recorded into the query-level StmtCtx structure when MPPGather retry.

### What changed and how does it work?
In selectResult, add an addition of runtime stats structure for TiFlash. During MPPTask retries, only the runtime stats for the final successful selectResult are recorded in StmtCtx.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test: endless: https://github.com/PingCAP-QE/endless/pull/2168
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by XuHuaiyu — APPROVED** [review]

**Comment by guo-shaoge** [comment]
fix here: https://github.com/pingcap/tidb/pull/50234

**Pull request closed without merging**
