### PR TITLE
executor: fix `show table status` for the database with upper-cased name

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
`show table status` does not work for a database with upper-cased name.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:
Fix it. Introduced by https://github.com/pingcap/tidb/pull/22644

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- fix `show table status` for the database with upper-cased name.

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
LGTM

**Comment by jackysp** [comment]
PTAL @morgo , thx!

**Review by xiongjiwei — APPROVED** [review]

**Comment by morgo** [comment]
/LGTM

Long term this should be implemented with collations of course.

**Comment by jackysp** [comment]
Seems CI/bot is stopped.

**Comment by jackysp** [comment]
```
[2021-04-11T14:32:13.821Z] FAIL: explainfor_test.go:73: testSerialSuite.TestExplainFor
[2021-04-11T14:32:13.821Z] 
[2021-04-11T14:32:13.821Z] explainfor_test.go:121:
[2021-04-11T14:32:13.821Z]     check()
[2021-04-11T14:32:13.821Z] explainfor_test.go:114:
[2021-04-11T14:32:13.821Z]     c.Assert(buf.String(), Matches, ""+
[2021-04-11T14:32:13.821Z]         "TableReader_5 10000.00 0 root  time:.*, loops:1, cop_task: {num:.*, max:.*, proc_keys: 0, rpc_num: 1, rpc_time:.*} data:TableFullScan_4 N/A N/A\n"+
[2021-04-11T14:32:13.821Z]         "└─TableFullScan_4 10000.00 0 cop.* table:t1 tikv_task:{time:.*, loops:0} keep order:false, stats:pseudo N/A N/A")
[2021-04-11T14:32:13.821Z] ... value string = "" +
[2021-04-11T14:32:13.821Z] ...     "TableReader_5 10000.00 0 root  time:3.03ms, loops:1, cop_task: {num: 1, max: 1.68ms, proc_keys: 0, tot_proc: 1ms, rpc_num: 1, rpc_time: 1.27ms, copr_cache_hit_ratio: 0.00} data:TableFullScan_4 N/A N/A\n" +
[2021-04-11T14:32:13.821Z] ...     "└─TableFullScan_4 10000.00 0 cop[tikv] table:t1 tikv_task:{time:0s, loops:0} keep order:false, stats:pseudo N/A N/A"
[2021-04-11T14:32:13.821Z] ... regex string = "" +
[2021-04-11T14:32:13.821Z] ...     "TableReader_5 10000.00 0 root  time:.*, loops:1, cop_task: {num:.*, max:.*, proc_keys: 0, rpc_num: 1, rpc_time:.*} data:TableFullScan_4 N/A N/A\n" +
[2021-04-11T14:32:13.821Z] ...     "└─TableFullScan_4 10000.00 0 cop.* table:t1 tikv_task:{time:.*, loops:0} keep order:false, stats:pseudo N/A N/A"
```
Test failed, not related to this PR.

**Pull request merged**
