### PR TITLE
planner: check the `ignore-plan-cache` hint in insert-stmt

### LINKED ISSUE #40079: planner: ignore-plan-cache hint cannot work for insert-stmt
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table t (a int);
Query OK, 0 rows affected (0.04 sec)

mysql> prepare st from 'insert /*+ ignore_plan_cache() */ t values (1)';
Query OK, 0 rows affected (0.01 sec)

mysql> execute st;
Query OK, 1 row affected (0.01 sec)

mysql> execute st;
Query OK, 1 row affected (0.00 sec)

mysql> select @@last_plan_from_cache;
+------------------------+
| @@last_plan_from_cache |
+------------------------+
|                      1 |
+------------------------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
The result of `@@last_plan_from_cache` should be 0 since there is an `ignore-plan-cache` hint.

### 3. What did you see instead (Required)
It's 1.

### 4. What is your TiDB version? (Required)

```
mysql> select version();
+-----------------------------------------+
| version()                               |
+-----------------------------------------+
| 5.7.25-TiDB-v6.6.0-alpha-40-g030c50604a |
+-----------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #40079, ref #39717

Problem Summary: planner: check the `ignore-plan-cache` hint in insert-stmt

### What is changed and how it works?

planner: check the `ignore-plan-cache` hint in insert-stmt

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by fzzf678 — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]

**Comment by hawkingrei** [comment]
@qw4990 PTAL

image

**Pull request merged**
