### PR TITLE
statistics: fix old bucket4Merging to merge new data

### LINKED ISSUE #49168: mergePartitionBuckets will reuse the old data to merge new struct
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

it cannot clean the all data when to release.

image

image

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #49168 

Problem Summary:

### What changed and how does it work?

it need to clean the old data when to release bucket4Merging

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
Could you please add a test for it?

**Comment by hawkingrei** [comment]
> Could you please add a test for it?

I add some assertion. it will panic when to meet the problem duration of the test.

**Review by winoros — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
