### PR TITLE
executor: fillDefaultValues store casted default values

### PR DESCRIPTION
**Pull request by winkyao**
```
func (e *InsertValues) getColDefaultValue(idx int, col *table.Column) (d types.Datum, err error) {
	if e.colDefaultVals != nil && e.colDefaultVals[idx].valid {
		return e.colDefaultVals[idx].val, nil
	}

	defaultVal, err := table.GetColDefaultValue(e.ctx, col.ToInfo())
	if err != nil {
		return types.Datum{}, errors.Trace(err)
	}
	if initialized := e.lazilyInitColDefaultValBuf(); initialized {
		e.colDefaultVals[idx].val = defaultVal
		e.colDefaultVals[idx].valid = true
	}

	return defaultVal, nil
}
```

the getColDefaultValue will saved the casted defaults value, so when exec a multi rows insert statement, it is more efficient.

@zimulala @zz-jason  PTAL

### CODE REVIEW

**Comment by zz-jason** [comment]
please add some test and description to this pr

**Comment by winkyao** [comment]
@zz-jason this pr ref #5549

**Comment by zimulala** [comment]
Please  add a simple description.

**Comment by zimulala** [comment]
LGTM

**Comment by zz-jason** [comment]
@winkyao any benchmark ?

**Pull request merged**
