### PR TITLE
variable: small cleanups

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Problem Summary:

This is a small cleanup following the merge of https://github.com/pingcap/tidb/pull/24914 - and then the removal of this from tidb-tests.

I have also changed the default "socket"; it gets overwritten during TiDB startup, but by changing it to empty string we can use it to auto-generate docs.

### What is changed and how it works?

What's Changed:

Minor cleanup

### Related changes

- None

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Side effects

- None

### Release note 

- No release note

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by jackysp — APPROVED** [review]
LGTM

**Comment by morgo** [comment]
It looks like there is still code in tidb-test that tries to enable the option that this PR removes. I'll take a look tomorrow.

**Pull request merged**
