### PR TITLE
*: refine some error code

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Make the error code explicable when it's returned to MySQL client.

### What is changed and how it works?

Define some customized mysql.ErrCode in the parser and use them for the following packages:

* server
* meta/autoid
* sessionctx/variable
* privilege/privileges

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @jackysp @imtbkcat

**Comment by jackysp** [comment]
Please resolve the conflicts, @tiancaiamao .

**Comment by tiancaiamao** [comment]
Done @jackysp

**Comment by jackysp** [comment]
The test failed,  @tiancaiamao .

**Pull request merged**
