### PR TITLE
errors: release-7.5 bump errors package to the latest commit hash

### LINKED ISSUE #53517: release-7.5 branch bump https://github.com/pingcap/errors to the latest commit hash
## Enhancement

tiflow release-7.5 bump tidb dependency to the commit-hash `9d27eef90bbb`, the `github.com/pingcap/errors` is bumped to `v0.11.5-0.20240318064555-6bd07397691f` automatically.

but on the tidb release-7.5 branch `9d27eef90bbb`, the `errors` package commit-hash is `v0.11.5-0.20221009092201-b66cddb77c32`, they are inconsistent.

Error reported:
```
# github.com/pingcap/tidb/br/pkg/redact
../pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20240522064147-9d27eef90bbb/br/pkg/redact/redact.go:14:32: cannot use redactLog (variable of type bool) as string value in argument to errors.RedactLogEnabled.Store
../pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20240522064147-9d27eef90bbb/br/pkg/redact/redact.go:19:9: cannot use errors.RedactLogEnabled.Load() (value of type string) as bool value in return statement
```

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #53517 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by lance6716 — APPROVED** [review]

**Comment by 3AceShowHand** [comment]
close this by #53526

**Pull request closed without merging**
