### PR TITLE
tikv: fix out-of-index in split-region

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

simple fix "out of index" error when split reponse's region num be zero and want to write info log.

x1

### What is changed and how it works?

check region num and avoid out of index error

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - n/a

Side effects

 - n/a

Related changes

 - n/a

Release note

 - n/a

/cc @breeswish

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/12265)

### CODE REVIEW

**Comment by july2993** [comment]
@lysu need pick to release-3.0, I encounter this with 3.0.5 and the latest release-3.0 still not fixed.

**Comment by crazycs520** [comment]
@lysu  need cherry-pick to 3.1?

**Pull request merged**
