### PR TITLE
ddl: make the column type change switch transparent (#25213)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25213 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25251
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25251:release-5.1-75388187f386
```

---

Signed-off-by: AilinKid <314806019@qq.com>

### What problem does this PR solve?

Problem Summary: ddl: make the column type change switch transparent

### What is changed and how it works?

What's Changed:

ddl: make the column type change switch transparent

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

### Release note 

- ddl: make the column type change switch transparent

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by wjhuang2016 — CHANGES_REQUESTED** [review]
If upgrading from 5.0, then tidb_enable_change_column_type is false.

**Comment by AilinKid** [comment]
> If upgrading from 5.0, then tidb_enable_change_column_type is false.

I think it's ok. setting it back in bootstrap is heavy.

**Comment by AilinKid** [comment]
DO NOT MERGE

**Pull request closed without merging**
