### PR TITLE
expression: fix comparing json with string (#21903)

### LINKED ISSUE #11883: unexpect invalid json text error when query with `json_extract`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
create table t1(f1 json);
insert into t1(f1) values ('"asd"'),('"asdf"'),('"asasas"');
select f1 from t1 where json_extract(f1,"$") in ("asd","asasas","asdf");
```

2. What did you expect to see?

image

3. What did you see instead?

image

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

image

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @XuHuaiyu

### LINKED ISSUE #13710: Incompatible issue related to JSON functions
## Bug Report

Seems there's an incompatible issue related to JSON functions

1. What did you do?
```
select json_extract("\"asd\"","$") in ("asd","abcd");
```

2. What did you expect to see?

in MySQL:5.7
```
mysql> select json_extract("\"asd\"","$") in ("asd","abcd");
+----------------------------------------------+
| json_extract("\"asd\"","$") in ("asd","abc") |
+----------------------------------------------+
|                                            0 |
+----------------------------------------------+
1 row in set, 1 warning (0.00 sec)
```

in MySQL:8
```
mysql> select json_extract("\"asd\"","$") in ("asd","abcd");
+-----------------------------------------------+
| json_extract("\"asd\"","$") in ("asd","abcd") |
+-----------------------------------------------+
|                                             1 |
+-----------------------------------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?
```
MySQL [(none)]> select json_extract("\"asd\"","$") in ("asd","abcd");
ERROR 3140 (22032): Invalid JSON text: The document root must not be followed by other values.
MySQL [(none)]>
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
Release Version: v4.0.0-alpha-940-g92e774913
Git Commit Hash: 92e774913a2f6166b104d3d8eaed5513733f1830
Git Branch: master
UTC Build Time: 2019-11-24 03:10:38
GoVersion: go version go1.13.1 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21903 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #11883 , also close #13710

Problem Summary:

### What is changed and how it works?

What's Changed: remove Parse json tag

How it Works:

MySQL won't implicitly cast string to JSON during comparison.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test
Side effects

### Release note 

- No release note.

### CODE REVIEW

**Comment by ichn-hu** [comment]
@XuHuaiyu @lzmhhh123 PTAL

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by zz-jason — APPROVED** [review]

**Comment by qw4990** [comment]
Please resolve conflicts. @ichn-hu

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
