### PR TITLE
expression: fix wrong EqualByExprAndID

### LINKED ISSUE #26803: mysql test error in gcol_select
## Bug Report
```
2021-08-02T09:37:40.822Z] time="2021-08-02T17:37:40+08:00" level=fatal msg="run test [gcol_select] err: sql:SELECT\ntable1.pk AS field1 ,\ntable1.col_datetime_key AS field2\nFROM\n( a AS table1 LEFT JOIN ( ( c AS table2 STRAIGHT_JOIN (  SELECT\nSUBQUERY1_t1.* FROM ( c AS SUBQUERY1_t1 INNER JOIN ( c AS SUBQUERY1_t2\nSTRAIGHT_JOIN c AS SUBQUERY1_t3 ON (SUBQUERY1_t3.col_varchar_key =\nSUBQUERY1_t2.col_varchar_key  ) )\nON (SUBQUERY1_t3.pk = SUBQUERY1_t2.col_int_key\nOR SUBQUERY1_t1.col_int_key <> 1 ) )\nWHERE SUBQUERY1_t2.pk >= 9 ) AS table3\nON (table3.col_int_key = table2.col_int_key  ) ) )\nON (table3.col_int_nokey = table2.pk  ) )\nGROUP BY field1, field2;: failed to run query \n\"SELECT\ntable1.pk AS field1 ,\ntable1.col_datetime_key AS field2\nFROM\n( a AS table1 LEFT JOIN ( ( c AS table2 STRAIGHT_JOIN (  SELECT\nSUBQUERY1_t1.* FROM ( c AS SUBQUERY1_t1 INNER JOIN ( c AS SUBQUERY1_t2\nSTRAIGHT_JOIN c AS SUBQUERY1_t3 ON (SUBQUERY1_t3.col_varchar_key =\nSUBQUERY1_t2.col_varchar_key  ) )\nON (SUBQUERY1_t3.pk = SUBQUERY1_t2.col_int_key\nOR SUBQUERY1_t1.col_int_key <> 1 ) )\nWHERE SUBQUERY1_t2.pk >= 9 ) AS table3\nON (table3.col_int_key = table2.col_int_key  ) ) )\nON (table3.col_int_nokey = table2.pk  ) )\nGROUP BY field1, field2;\" \n around line 165, \nwe need(581):\nSELECT\ntable1.pk AS field1 ,\ntable1.col_datetime_key AS field2\nFROM\n( a AS table1 LEFT JOIN ( ( c AS table2 STRAIGHT_JOIN (  SELECT\nSUBQUERY1_t1.* FROM ( c AS SUBQUERY1_t1 INNER JOIN ( c AS SUBQUERY1_t2\nSTRAIGHT_JOIN c AS SUBQUERY1_t3 ON (SUBQUERY1_t3.col_varchar_key =\nSUBQUERY1_t2.col_varchar_key  ) )\nON (SUBQUERY1_t3.pk = SUBQUERY1_t2.col_int_key\nOR SUBQUERY1_t1.col_int_key <> 1 ) )\nWHERE SUBQUERY1_t2.pk >= 9 ) AS table3\nON (table3.col_int_key = table2.col_int_key  ) ) )\nON (table3.col_int_nokey = table2.pk  ) )\nGROUP BY field1, field2;\nfield1\tfield2\n1\t2001-11-04 23:15:57\n\nbut got(581):\nSELECT\ntable1.pk AS field1 ,\ntable1.col_datetime_key AS field2\nFROM\n( a AS table1 LEFT JOIN ( ( c AS table2 STRAIGHT_JOIN (  SELECT\nSUBQUERY1_t1.* FROM ( c AS SUBQUERY1_t1 INNER JOIN ( c AS SUBQUERY1_t2\nSTRAIGHT_JOIN c AS SUBQUERY1_t3 ON (SUBQUERY1_t3.col_varchar_key =\nSUBQUERY1_t2.col_varchar_key  ) )\nON (SUBQUERY1_t3.pk = SUBQUERY1_t2.col_int_key\nOR SUBQUERY1_t1.col_int_key <> 1 ) )\nWHERE SUBQUERY1_t2.pk >= 9 ) AS table3\nON (table3.col_int_key = table2.col_int_key  ) ) )\nON (table3.col_int_nokey = table2.pk  ) )\nGROUP BY field1, field2;\nfield1\tfield2\n1\t0000-01-06 02:52:50\n\n"

[2021-08-02T09:37:40.822Z] tidb-server(PID: 233) stopped
```

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/5785/pipeline/87

### 4. What is your TiDB version? (Required)
master

it cause commit between in https://github.com/pingcap/tidb/commit/d7bddb8ba4f453f1d4f3949ffbeff440f2d32da7 and https://github.com/pingcap/tidb/commit/17523d3da8fe863979ae93277424f4ac5f0e9aa6

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #26803

We need to check if the type of column and expression are equal. Otherwise, for this case:
```
CREATE TABLE `a` (
  `pk` int(11) NOT NULL AUTO_INCREMENT,
  `col_datetime_nokey` datetime NOT NULL,
  `col_time_nokey` time NOT NULL,
  `col_datetime_key` datetime GENERATED ALWAYS AS (addtime(`col_datetime_nokey`, `col_time_nokey`)) VIRTUAL,
  `col_time_key` time GENERATED ALWAYS AS (addtime(`col_datetime_nokey`, `col_time_nokey`)) VIRTUAL,
  `col_varchar_nokey` varchar(1) NOT NULL,
  `col_varchar_key` varchar(2) GENERATED ALWAYS AS (concat(`col_varchar_nokey`, `col_varchar_nokey`)) VIRTUAL,
  PRIMARY KEY (`pk`) /*T![clustered_index] CLUSTERED */,
  KEY `col_varchar_key` (`col_varchar_key`),
  KEY `col_time_key` (`col_time_key`),
  KEY `col_datetime_key` (`col_datetime_key`),
  KEY `col_varchar_key_2` (`col_varchar_key`,`col_time_key`,`col_datetime_key`)
)
```
`select col_datetime_key from a` would choose index col_time_key. Then it will get the wrong data because their types are different.

### What is changed and how it works?

Add check expr.RetType.Equal(newCol.RetType).

### Check List 

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
'None' 
```

### CODE REVIEW

**Review by guo-shaoge — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
@ti-chi-bot

**Comment by zhouqiang-cl** [comment]
@ti-chi-bot

**Pull request merged**
