### PR TITLE
telemetry: add copr-cache, tiflash, cluster index, async commit (#23454)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23454 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23489
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23489:release-5.0-5243049e18ff
```

---

Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>

### What problem does this PR solve?

Problem Summary: as title says

### What is changed and how it works?

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
`admin show telemetry`

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- telemetry: add copr-cache, tiflash, cluster index, async commit

### CODE REVIEW

**Review by youjiali1995 — APPROVED** [review]

**Comment by breeswish** [comment]
This PR is not tested yet, let's hold to be merged together with https://github.com/pingcap/tidb/pull/23470

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
