### PR TITLE
go.mod: update badger to 20210831

### PR DESCRIPTION
**Pull request by unconsolable**
Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>

### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

Update dependency `pingcap/badger` to 20210831

This version includes pr pingcap/badger#221 which fixes issue pingcap/badger#220

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Comment by tisonkun** [comment]
@unconsolable I'd prefer to link to the change set (PR) interested in pingcap/badger so that we know what we'd like to bring and how it changes things.

Otherwise you're asking reviewers to review a black box which bump version but unsure what to change.

**Comment by unconsolable** [comment]
> @unconsolable I'd prefer you link to the change set (PR) interested in pingcap/badger so that we know what to bring and how it changes things.
> 
> Otherwise you're asking reviewers to review a black box which bump version but unsure what changes.

Updated, Thanks.

**Comment by unconsolable** [comment]
I think it may be better to upgrade the dependency with the migrated tests. This issue will be closed.

**Comment by unconsolable** [comment]
I think it may be better to upgrade the dependency with the migrated tests. This PR will be closed.

**Pull request closed without merging**
