### PR TITLE
statistics: migrate test-infra to testify for fmsketch_test.go

### LINKED ISSUE #28121: migrate test-infra to testify for `statistics/fmsketch_test.go`

### PR DESCRIPTION
**Pull request by feitian124**
### What problem does this PR solve?

Issue Number: close #28121

since `samples` in `testStatisticsSuite` have 100000 items, after migrate also use shared suite for performance,
which is init in `main_test.go`.

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
You may just use a subtests pattern and pass the suite as a parameter. Then we don't leak concept globally.

**Comment by feitian124** [comment]
> You may just use a subtests pattern and pass the suite as a parameter. Then we don't leak concept globally.

like what you did in `domain/main_test.go`?

the usage of testStatisticsSuite:
6 in cmsketch_test.go
5 in histogram_test.go
8 in statistic_test.go

so i have 2 choices:
1. make the whole 19 tests as subtests. ( too much change, close coupled)
2. group them by file. (need init 3 times)

which one you prefer?

and the global variable is package level and in test file, is it not fine?

**Comment by feitian124** [comment]
@tisonkun could you see my above reply?

**Comment by tisonkun** [comment]
@feitian124 you can do bookkeeping in main_test.go or anyone of the file. you don't have to migrate all 19 tests, but batch and batch.

**Comment by tisonkun** [comment]
You can take a look at https://github.com/feitian124/tidb/pull/1

**Comment by feitian124** [comment]
> You can take a look at [feitian124#1](https://github.com/feitian124/tidb/pull/1)

thank you for your code example, it look better

**Review by tisonkun — APPROVED** [review]
LGTM

**Review by winoros — APPROVED** [review]

**Pull request merged**
