### PR TITLE
executor, planner: Server side help, powered by OpenAI ChatGPT

### LINKED ISSUE #33609: CLI help ---  ERROR 8108 (HY000): Unsupported type *ast.HelpStmt

### PR DESCRIPTION
**Pull request by dveeden**
This requires the user to set a `OPENAI_API_KEY` environment variable.

### What problem does this PR solve?

Issue Number: close #33609

Problem Summary:

This adds support for server side help: e.g. `HELP 'select'`. This make it easier to lookup documentation for statements, etc. This uses ChatGPT.

- https://dev.mysql.com/doc/refman/8.0/en/mysql-server-side-help.html
- https://dev.mysql.com/doc/refman/8.0/en/help.html

A more classical implementation is in #25485

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [x] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Server side powered by ChatGPT was added.
```

### CODE REVIEW

**Comment by dveeden** [comment]
```
mysql> help 'AUTO_RANDOM';
Name: 'AUTO_RANDOM'
Description:
AUTO_RANDOM is a feature in TiDB SQL that automatically generates a random number as the value for a specified column in a table. This feature is typically used when you need to assign a random value to a column during the insertion of a new row.

For example, suppose we have a table named `users` with columns `id` and `name`. And we want to assign a random number for the `id` column when inserting a new row. We can define the `id` column as an AUTO_RANDOM column.

```sql
CREATE TABLE users (
  id BIGINT AUTO_RANDOM PRIMARY KEY,
  name VARCHAR(50)
);
```

Now, every time we insert a new row into the `users` table without specifying a value for the `id` column, TiDB will automatically generate a random number for it.

```sql
INSERT INTO users (name) VALUES ('John Doe');
```

The resulting row in the `users` table might look like this:

```
+----+----------+
| id | name     |
+----+----------+
| 5  | John Doe |
+----+----------+
```

Note that the specific value of the `id` column will differ each time due to the random generation
```

**Comment by dveeden** [comment]
Another example:
````
mysql> help 'query hints for tiflash';
Name: 'query hints for tiflash'
Description:
Query hints in TiDB SQL allow you to provide suggestions to the query optimizer for how it should execute a specific SQL query. One use case for query hints is to specify that a particular table should be queried using TiFlash, which is a columnar storage engine in TiDB for faster analytical queries.

To use query hints for TiFlash, you can add the `tiflash` hint as a comment in your SQL query. Here is an example:

```sql
SELECT /*+ read_from_storage(tiflash[t1]) */ * FROM t1;
```

In this example, the `read_from_storage(tiflash[t1])` hint is added as a comment in the query. It instructs the optimizer to read the table `t1` from the TiFlash storage engine. This hint is particularly useful when there are multiple replicas of a table, and you want to explicitly specify which one to use.

Note that query hints are optional, and the TiDB optimizer will automatically choose the best execution plan based on statistics and cost estimations. Query hints should only be used when you have specific knowledge or requirements about the execution plan.
````

This is how this looks:
image

**Comment by okJiang** [comment]
very cool~

**Comment by dveeden** [comment]
While this is interesting, I don't think this is the way forward. Instead we should have reviewed documentation from the docs repo for this

**Pull request closed without merging**
