### PR TITLE
parser: add new analyze option `SAMPLERATE`

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: to https://github.com/pingcap/tidb/issues/28960 

Problem Summary:

Modify parser to support the new analyze option.

### What is changed and how it works?

Since the new option needs float value, we not only modified the parser, but also modified the structure of the AnalyzeOption.

### Check List 

Tests 

- [x] Unit test

Documentation

- [ ] Affects user behaviors
- [x] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by kennytm** [comment]
> Since the new option needs float value, we not only modified the parser, but also modified the structure of the AnalyzeOption.

Technically you could use `math.Float64bits`/`math.Float64frombits` to support floats 🙃

**Comment by winoros** [comment]
> Technically you could use `math.Float64bits`/`math.Float64frombits` to support floats 🙃
@kennytm 
Oh you mean, we use it to store the rate as uint64 in the `map[Option]uint64` and convert back to float64 when using it?

**Comment by kennytm** [comment]
@winoros yes. though this bit-twiddling hack won't work if in the future you need an option with string value.

**Comment by time-and-fate** [comment]
Also please resolve the conflicts.

**Pull request merged**
