### PR TITLE
docs: remove interpreter part in QUICKSTART.md

### PR DESCRIPTION
**Pull request by XuHuaiyu**
Interpreter has been removed, this commit remove the introduction of QUICKSTART.md.
PTAL @shenli @ngaut

### CODE REVIEW

**Comment by tiancaiamao** [comment]
should we give some equivalent description, such as 

```
mysql -h 127.0.0.1 -P 4000 -u root
```

**Comment by XuHuaiyu** [comment]
I don't quite understand you.
The item ` Run as MySQL protocol server` gives user the way to use TiDB as what you mentioned. @tiancaiamao

**Comment by tiancaiamao** [comment]
okay... I just see part of the change in this PR...

LGTM

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
