### PR TITLE
br: enable some checks for br

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve?

Problem Summary:
In order to merge BR into TiDB, we disable the `make check` of BR due to lint is different with TiDB. but we can enable some other checks.

### What is changed and how it works?

What's Changed:
enable `fmt, tidy, testSuite, errdoc` checks for br/pkg

How it Works:

### Check List 

Tests 

- [ ] Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM

**Review by YuJuncen — APPROVED** [review]

**Review by kennytm — APPROVED** [review]

**Comment by 3pointer** [comment]
/needs-cherry-pick-5.2

**Pull request merged**
