### PR TITLE
binlog: use `node.Restore()` to add TiDB-specified feature comments

### LINKED ISSUE #31147: binlog: use `node.Restore()` to add TiDB-specified feature comments
## Enhancement

For TiDB-specified features like `AUTO_RANDOM` attributes, we comment them in [TiDB-specified comments](https://docs.pingcap.com/tidb/stable/comment-syntax/#tidb-specific-comment-syntax) for binlog-based replication(deprecated, but still used by some customers) and TiCDC.

After https://github.com/pingcap/tiflow/issues/3755, TiCDC used the [`node.Restore()`](https://github.com/pingcap/tidb/blob/0af4b77b6be0adf970a6b0bc79d62985deda69c5/parser/ast/ast.go#L30) method from `parser` to add the comments in https://github.com/pingcap/tiflow/pull/3845, rather than the regex-based way for binlog.

Although using `node.Restore()` is slower than regex, IMO it's better to adopt `node.Restore()` to replace the regex implementation for basically 2 reasons:
- It is robust.
- It makes consistent results for both binlog and TiCDC replications.

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve?

Issue Number: close #31147

### What is changed and how it works?

As is described in the issue.

### Check List

Tests 

- [x] Unit test

Side effects

- [x] Performance regression: Consumes more CPU

Documentation

- NA

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tangenta** [comment]
I think we can remove the file `types/parser_driver/special_cmt_ctrl.go`.

**Review by djshow832 — APPROVED** [review]

**Comment by bb7133** [comment]
@tangenta @Defined2014 PTAL again.

**Review by Defined2014 — APPROVED** [review]

**Review by Defined2014 — CHANGES_REQUESTED** [review]
Seems have some problems with UT

**Review by Defined2014 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Pull request merged**
