### PR TITLE
executor: move testShowStatsSuite into SerialSuites

### LINKED ISSUE #14931: unstable unit test: testShowStatsSuite.TestShowAnalyzeStatus
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Found in https://github.com/pingcap/tidb/pull/14834

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/25191/pipeline

2. What did you expect to see?

All test passed

3. What did you see instead?

```
[2020-02-25T06:32:20.031Z] ----------------------------------------------------------------------
[2020-02-25T06:32:20.031Z] FAIL: show_stats_test.go:181: testShowStatsSuite.TestShowAnalyzeStatus
[2020-02-25T06:32:20.031Z]
[2020-02-25T06:32:20.031Z] show_stats_test.go:191:
[2020-02-25T06:32:20.031Z]     c.Assert(len(result.Rows()), Equals, 2)
[2020-02-25T06:32:20.031Z] ... obtained int = 3
[2020-02-25T06:32:20.031Z] ... expected int = 2
[2020-02-25T06:32:20.031Z]
[2020-02-25T06:32:20.031Z] query: select _tidb_rowid from t1 where a=5
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master

### PR DESCRIPTION
**Pull request by SunRunAway**
### What problem does this PR solve? 

Fixes #14931

### What is changed and how it works?

move testShowStatsSuite into SerialSuites

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM

**Comment by SunRunAway** [comment]
PTAL~

**Comment by glorv** [comment]
LGTM

**Pull request merged**
