### PR TITLE
server: fix panic when using cursorfetch

### LINKED ISSUE #30896: mysql.ComStmtFetch occurs index out of range
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```java
   public static void main(String[] args) throws ClassNotFoundException, SQLException {

        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:4000/test?useServerPrepStmts=true&cachePrepStmts=true&useCursorFetch=true", "root", "");

        conn.setAutoCommit(false);
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, 1);
        ps.setFetchSize(1000);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            System.out.println(rs.getString("id"));
        }
        rs.close();
        ps.close();
        conn.close();
    }
```

```sql
mysql> show create table t;
+-------+------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                               |
+-------+------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select * from t;
+------+
| id   |
+------+
|    1 |
|    2 |
+------+
2 rows in set (0.00 sec)
```

### 2. What did you expect to see? (Required)

`1`

### 3. What did you see instead (Required)

```java
Exception in thread "main" java.sql.SQLException: runtime error: index out of range [0] with length 0
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.result.ResultSetImpl.next(ResultSetImpl.java:1753)
	at prepared.Prepared.main(Prepared.java:18)
```

### 4. What is your TiDB version? (Required)

`Master`

I guess the panic is caused by this line of code:  https://github.com/pingcap/tidb/blob/master/server/conn.go#L2211

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Issue Number: close #30896 

Problem Summary: Chunk can not be reset, it must be freed by golang gc since chunk is used for a long period of time. We must allocate a new buffer every iteration.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
refer pingcap/tidb-test#1449
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix panic when using large cursor fetch size
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

**Comment by tiancaiamao** [comment]
This is a fix-on-fix already, is there a way add test and prevent regression in the future? @xhebox

**Comment by xhebox** [comment]
> This is a fix-on-fix already, is there a way add test and prevent regression in the future? @xhebox

I added another test in pingcap/tidb-test#1499, see the description.

**Review by bb7133 — COMMENTED** [review]
Please add a test for the change.

**Comment by xhebox** [comment]
> Please add a test for the change.

Hard to test in tidb, it is added in tidb-test.

**Review by xiongjiwei — APPROVED** [review]

**Pull request merged**
