### PR TITLE
*: refine the `trace format='json' ...` result to a url

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Before this PR, `trace format='json' ...` outputs some data in the json format:

```
 [{"ID":{"Trace":"4bb68d621595cf59","Span":"56191f0df46ee6c1","Parent":"0000000000000000"},"Annotations":[{"Key":"Name","Value":"dHJhY2U="},{"Key":"_schema:name","Value":null},{"Key":"Msg","Value":"ZXhlY3V0ZSBkb25lLCBtb2RpZnkgcm93OiAw"},{"Key":"Time","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTQ4NzA5MSswODowMA=="},{"Key":"_schema:log","Value":null},{"Key":"Span.Start","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTExMzE3MDMrMDg6MDA="},{"Key":"Span.End","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTQ4NzI4OTkrMDg6MDA="},{"Key":"_schema:Timespan","Value":null}],"Sub":[{"ID":{"Trace":"4bb68d621595cf59","Span":"2ce7f10c03d36b4a","Parent":"56191f0df46ee6c1"},"Annotations":[{"Key":"Name","Value":"c2Vzc2lvbi5FeGVjdXRl"},{"Key":"_schema:name","Value":null},{"Key":"Msg","Value":"ZXhlY3V0ZTogdXBkYXRlIHQgc2V0IGlkPWlkKzEsIGEgPSBhKzEsIGI9YisxLCBjPWMrMSwgZD1kKzEgd2hlcmUgaWQgPSA4Mw=="},{"Key":"Time","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTExNjQyOCswODowMA=="},{"Key":"_schema:log","Value":null},{"Key":"Span.Start","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTExNDc0MjYrMDg6MDA="},{"Key":"Span.End","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTQ4MjM1MDErMDg6MDA="},{"Key":"_schema:Timespan","Value":null}],"Sub":[{"ID":{"Trace":"4bb68d621595cf59","Span":"15c4d0b3fdc7cd74","Parent":"2ce7f10c03d36b4a"},"Annotations":[{"Key":"Name","Value":"c2Vzc2lvbi5QYXJzZVNRTA=="},{"Key":"_schema:name","Value":null},{"Key":"Span.End","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTE0OTU0ODQrMDg6MDA="},{"Key":"Span.Start","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTEzMzM4NjYrMDg6MDA="},{"Key":"_schema:Timespan","Value":null}],"Sub":null},{"ID":{"Trace":"4bb68d621595cf59","Span":"534b9ac13c3720dc","Parent":"2ce7f10c03d36b4a"},"Annotations":[{"Key":"Name","Value":"ZXhlY3V0b3IuQ29tcGlsZQ=="},{"Key":"_schema:name","Value":null},{"Key":"Span.Start","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTE1NjM3OCswODowMA=="},{"Key":"Span.End","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTE4NDkwMzErMDg6MDA="},{"Key":"_schema:Timespan","Value":null}],"Sub":null},{"ID":{"Trace":"4bb68d621595cf59","Span":"33b071da2f182e98","Parent":"2ce7f10c03d36b4a"},"Annotations":[{"Key":"Name","Value":"c2Vzc2lvbi5ydW5TdG10"},{"Key":"_schema:name","Value":null},{"Key":"Msg","Value":"eyJzcWwiOiJ1cGRhdGUgdCBzZXQgaWQ9aWQrMSwgYSA9IGErMSwgYj1iKzEsIGM9YysxLCBkPWQrMSB3aGVyZSBpZCA9IDgzIn0="},{"Key":"Time","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTE5NDU4MjcrMDg6MDA="},{"Key":"_schema:log","Value":null},{"Key":"Span.Start","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTE5MzY4MjcrMDg6MDA="},{"Key":"Span.End","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTQ3NDc2MzYrMDg6MDA="},{"Key":"_schema:Timespan","Value":null}],"Sub":[{"ID":{"Trace":"4bb68d621595cf59","Span":"0dc91e9968f4d20b","Parent":"33b071da2f182e98"},"Annotations":[{"Key":"Name","Value":"ZXhlY3V0b3IuaGFuZGxlTm9EZWxheUV4ZWN1dG9y"},{"Key":"_schema:name","Value":null},{"Key":"Span.Start","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTIwODU1ODIrMDg6MDA="},{"Key":"Span.End","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTQ1OTY2NTIrMDg6MDA="},{"Key":"_schema:Timespan","Value":null}],"Sub":[{"ID":{"Trace":"4bb68d621595cf59","Span":"1df3c8bde4f70aff","Parent":"0dc91e9968f4d20b"},"Annotations":[{"Key":"Name","Value":"KmV4ZWN1dG9yLlVwZGF0ZUV4ZWMuTmV4dA=="},{"Key":"_schema:name","Value":null},{"Key":"Span.Start","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTIxMDAyMTUrMDg6MDA="},{"Key":"Span.End","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTQ1Njc3MTIrMDg6MDA="},{"Key":"_schema:Timespan","Value":null}],"Sub":[{"ID":{"Trace":"4bb68d621595cf59","Span":"25c173997426305a","Parent":"1df3c8bde4f70aff"},"Annotations":[{"Key":"Name","Value":"KmV4ZWN1dG9yLlBvaW50R2V0RXhlY3V0b3IuTmV4dA=="},{"Key":"_schema:name","Value":null},{"Key":"Msg","Value":"bG9hZCByZWdpb24gMzAwMSBmcm9tIHBkLCBkdWUgdG8gY2FjaGUtbWlzcw=="},{"Key":"Time","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTMxMzk3MDkrMDg6MDA="},{"Key":"_schema:log","Value":null},{"Key":"Msg","Value":"c2VuZCBHZXQgcmVxdWVzdCB0byByZWdpb24gMzAwMSBhdCAxMjcuMC4wLjE6MjAxNjA="},{"Key":"Time","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTMxODQyNTYrMDg6MDA="},{"Key":"_schema:log","Value":null},{"Key":"Span.Start","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTIxMTk3 |
| NjQrMDg6MDA="},{"Key":"Span.End","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTQ1MTg0OTErMDg6MDA="},{"Key":"_schema:Timespan","Value":null}],"Sub":[{"ID":{"Trace":"4bb68d621595cf59","Span":"35995799d0036c7c","Parent":"25c173997426305a"},"Annotations":[{"Key":"Name","Value":"cnBjQ2xpZW50LlNlbmRSZXF1ZXN0"},{"Key":"_schema:name","Value":null},{"Key":"Time","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTQzNjM4OTMrMDg6MDA="},{"Key":"Msg","Value":"cmVjZWl2ZSAqdGlrdnBiLkJhdGNoQ29tbWFuZHNSZXNwb25zZV9SZXNwb25zZV9HZXQgcmVzcG9uc2Ugd2l0aCBvdGhlciAxIGJhdGNoZWQgcmVxdWVzdHMgZnJvbSAxMjcuMC4wLjE6MjAxNjA="},{"Key":"_schema:log","Value":null},{"Key":"Span.Start","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTMxOTQzNjIrMDg6MDA="},{"Key":"Span.End","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTQ0MTQ0MSswODowMA=="},{"Key":"_schema:Timespan","Value":null}],"Sub":null}]}]}]},{"ID":{"Trace":"4bb68d621595cf59","Span":"511e35cf428c0a66","Parent":"33b071da2f182e98"},"Annotations":[{"Key":"Name","Value":"c2Vzc2lvbi5Db21taXRUeG4="},{"Key":"_schema:name","Value":null},{"Key":"Span.Start","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTQ2NDU0MTYrMDg6MDA="},{"Key":"Span.End","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTQ3MTk2NjQrMDg6MDA="},{"Key":"_schema:Timespan","Value":null}],"Sub":[{"ID":{"Trace":"4bb68d621595cf59","Span":"093d7cb09f3e25b5","Parent":"511e35cf428c0a66"},"Annotations":[{"Key":"Name","Value":"c2Vzc2lvbi5kb0NvbW1pdFdpdFJldHJ5"},{"Key":"_schema:name","Value":null},{"Key":"Span.Start","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTQ2Njg0NDgrMDg6MDA="},{"Key":"Span.End","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTQ2NzU4MjkrMDg6MDA="},{"Key":"_schema:Timespan","Value":null}],"Sub":null}]}]},{"ID":{"Trace":"4bb68d621595cf59","Span":"2a64dbd8d41b36ac","Parent":"2ce7f10c03d36b4a"},"Annotations":[{"Key":"Name","Value":"c2Vzc2lvbi5nZXRUeG5GdXR1cmU="},{"Key":"_schema:name","Value":null},{"Key":"Span.Start","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTExNzA3ODcrMDg6MDA="},{"Key":"Span.End","Value":"MjAxOS0wOC0xM1QyMToxNDoxMi44NTExOTkwMjcrMDg6MDA="},{"Key":"_schema:Timespan","Value":null}],"Sub":null}]}]}]
```
We have to paste it to the web trace viewer to see the result, and we have to adjust the data as there are newlines.

Now I let it directly output the URL:

```
mysql> trace format='json' update t set id=id+1, a = a+1, b=b+1, c=c+1, d=d+1 where id = 83;                                                                                                          +---------------------------------------------------------------------------+
| url                                                                       |
+---------------------------------------------------------------------------+
| http://127.0.0.1:10080/web/trace/traces/710fa35abfc1ca3d/3a8d1e00b86b0ac0 |
+---------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### What is changed and how it works?

Introduce a global `appdash.MemoryStore` and use it for the trace result.
Before this PR, we create a temporary `appdash.MemoryStore` every time, and extract data from it.
The `appdash.MemoryStore` is wrapped with a `RecentStore`, so I don't need to worry about recycling of the memory.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @lysu @jackysp

**Comment by ngaut** [comment]
What happened if mysql client is using a load balancer to connect tidb?

**Comment by lysu** [comment]
I think we should deploy a "trace display" service in a public address? for example https://pingcap.github.io/sqltrace(just like https://pingcap.github.io/sqlgram) but it just parses the tracing result and we need to take care security problem.

For the user under non-internet env, they still need to paste compressed json string

**Comment by ngaut** [comment]
So we do need native json output. "trace display" service is a good idea, we can keep json and add a new web format, which can use the "trace display" service.

**Comment by tiancaiamao** [comment]
Closed as nobody current actively working on this.

**Pull request closed without merging**
