### PR TITLE
expression: implement vectorized evaluation for `builtinUnaryNot*` series of functions

### PR DESCRIPTION
**Pull request by k-ye**
### What problem does this PR solve? 

Implement vectorized evaluation for the series of unary not functions:

- `builtinUnaryNotRealSig`
- `builtinUnaryNotDecimalSig`
- `builtinUnaryNotIntSig`

Issue: #12103 

### What is changed and how it works?

For `builtinUnaryNotRealSig`, about 8 times faster:

```
BenchmarkVectorizedBuiltinOpFunc/builtinUnaryNotRealSig-VecBuiltinFunc-4    	  500000	      3111 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinOpFunc/builtinUnaryNotRealSig-NonVecBuiltinFunc-4 	  100000	     24126 ns/op	       0 B/op	       0 allocs/op
```

For `builtinUnaryNotDecimalSig`, about 3 times faster:

```
BenchmarkVectorizedBuiltinOpFunc/builtinUnaryNotDecimalSig-VecBuiltinFunc-4 	  200000	      8971 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinOpFunc/builtinUnaryNotDecimalSig-NonVecBuiltinFunc-4         	   50000	     27541 ns/op	       0 B/op	       0 allocs/op
```

For `builtinUnaryNotIntSig`, about 8 times faster:

```
BenchmarkVectorizedBuiltinOpFunc/builtinUnaryNotIntSig-VecBuiltinFunc-4                	  500000	      2996 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinOpFunc/builtinUnaryNotIntSig-NonVecBuiltinFunc-4             	   50000	     25370 ns/op	       0 B/op	       0 allocs/op
```

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by k-ye** [comment]
Would be happy to split this into three PRs, if that is more compliant with the contribution rules!

**Comment by qw4990** [comment]
> Would be happy to split this into three PRs, if that is more compliant with the contribution rules!

I think it's ok since these three functions are relatively simple.

**Pull request merged**
