### PR TITLE
ddl: make `jobCtx` maintained by `ddlCtx`

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/34980

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by crazycs520 — APPROVED** [review]

**Comment by Defined2014** [comment]
> /cc @Defined2014 @zimulala

What's the propose for this PR? Does it related with the concurrent DDL?

**Comment by xiongjiwei** [comment]
> > /cc @Defined2014 @zimulala
> 
> What's the propose for this PR? Does it related with the concurrent DDL or just code clean?

for concurrent DDL, also code clean. 

previously, the job ctx is maintained by worker, which means this worker can not run another job before the current job has been done, the concurrent DDL cannot guarantee it. In concurrent DDL, a job can be run by different workers.

Also, it is not reasonable for DDL worker to maintain it.

**Review by Defined2014 — APPROVED** [review]

**Comment by you06** [comment]
> In concurrent DDL, a job can be run by different workers.

@xiongjiwei I'm currently editing the DDL code for some resources tracing, and have a question about your design. You mentioned a job could be run by different workers, that makes sense, and can I have another conclusion that a worker can only process one ddl job? If so, I'm going to add the [`JobContext`](https://github.com/pingcap/tidb/blob/738f681d6110c0e0ee50a412a0f54d977e1574f5/ddl/ddl_worker.go#L100-L107) into backfillers.

**Comment by xiongjiwei** [comment]
@you06 yes, a worker can only process one ddl job at a time.

**Pull request merged**
