### PR TITLE
br/restore: fixed restore sys tables

### LINKED ISSUE #38538: BR: br restore system table mysql.* fail for global id exceeds the limit
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. br backup full include system table
2. br restore all table to master cluster 

### 2. What did you expect to see? (Required)
restore success

### 3. What did you see instead (Required)
```code
Detail BR log in /tmp/br.log.2022-10-19T02.59.04Z
Full Restore <-----------------------------------------------------------------------------> 100.00%Error: global id
:281474976710655 exceeds the limit:281474976709655
[2022/10/19 02:59:05.136 +00:00] [INFO] [collector.go:69] ["Full Restore failed summary"] [total-ranges=0] [ranges-s
ucceed=0] [ranges-failed=0] [split-region=54.236µs] [restore-ranges=34]
2022-10-19T02:59:05.204Z        INFO    host/host.go:37 Execute command error   {"command": " /br  restore  full \"-
s\" \"s3://tmp/br-backup-basic42b2ad84-ffbe-4647-b709-053efbef3977?access-key=minioadmin&secret-access-key=minioadmi
n&endpoint=http%3a%2f%[2fminio.pingcap.net](http://2fminio.pingcap.net/)%3a9000&force-path-style=true\" \"-u\" \"http://downstream-pd.brie-acceptan/
ce-tps-1299310-1-962:2379\" \"-f\" \"mysql.*\" \"--with-sys-table\"", "exit code": 1, "stdout": "[2022/10/19 02:59:0
5.136 +00:00] [INFO] [collector.go:69] [\"Full Restore failed summary\"] [total-ranges=0] [ranges-succeed=0] [ranges
-failed=0] [split-region=54.236µs] [restore-ranges=34]\n", "stderr": "Detail BR log in /tmp/br.log.2022-10-19T02.59.
04Z \nFull Restore <-----------------------------------------------------------------------------> 100.00%Error: glo
bal id:281474976710655 exceeds the limit:281474976709655\n", "error": "command terminated with exit code 1"}
11:10
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by YuJuncen**
Signed-off-by: hillium <yujuncen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #38538

Problem Summary:

### What is changed and how it works?
After this PR, we would give up for keeping table ID if table ID is greater than `MaxUInt32`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
image
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

(This bug was introduced only in the master branch.)
```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
If the cluster to be restored has the same version with backup cluster, we might let itself create the special tables. Because the table ID for these tables are hardcoded in TiDB, restore them to another table ID may cause problems.

When the cluster version is different, these tables has no effects and no need to be restored.

**Comment by YuJuncen** [comment]
@lance6716 Yep, but once the user wants to restore `mysql.*`, we would try to restore those tables and we are going to try to advance the global ID to the insane ID, which leads to a failed restoration.

**Review by fengou1 — APPROVED** [review]
ship it

**Pull request merged**
