### PR TITLE
expression: fix unused code in util.go

### PR DESCRIPTION
**Pull request by HuGanghui**
### What problem does this PR solve?

Ref: ：https://github.com/pingcap/tidb/issues/23013  https://github.com/pingcap/tidb/issues/22979

Problem Summary:

fix unused code in file expression/util.go

### What is changed and how it works?

make the lint unused pass in the expression/util.go file

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Release note
- No release note

### CODE REVIEW

**Comment by HuGanghui** [comment]
release note added.

**Comment by xiongjiwei** [comment]
close and reopen PR can trigger `check_release_note`

**Review by wshwsh12 — COMMENTED** [review]
Why not remove the unused code?

**Comment by HuGanghui** [comment]
> Why not remove the unused code?

yes, considering that it is introduced in https://github.com/pingcap/tidb/pull/6432 just for simple_writer, and now simple_writer does not need it any more. 

I have removed the unused code.

**Pull request merged**
