### PR TITLE
ddl: put the non-reorg jobs back to general queue (#31461)

### LINKED ISSUE #31460: Adding index blocks the upgrade procedure
## Enhancement

https://github.com/pingcap/tidb/pull/27748 moves all of the `ModifyColumn` jobs to adding index queue. If there is a running "ADD INDEX" job, the upgrade procedures like `upgradeToVer75` can be blocked:

https://github.com/pingcap/tidb/blob/088a2444dff5c2239f47529dd6218cbd0771a943/session/bootstrap.go#L1614-L1623

`ALTER TABLE mysql.user MODIFY COLUMN Host CHAR(255)` is blocked by adding index.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #31461 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/31557
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/31557:release-5.4-aa9f530d152c
```

---

### What problem does this PR solve?

Issue Number: close #31460

### What is changed and how it works?

This PR puts the non-reorg jobs back to general queue.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by djshow832 — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]

**Comment by djshow832** [comment]
`testDDLSuite.TestParallelDDL` also fails for this cherry-pick.

**Pull request merged**
