### PR TITLE
[DNM] store/tikv: support columns

### PR DESCRIPTION
**Pull request by disksing**

### CODE REVIEW

**Comment by shenli** [comment]
There are four concepts in this PR: Row, RowKey, Key and RowValue. We should make them clear. I see they are mixed used in a few places.

**Comment by disksing** [comment]
@shenli @coocoood PTAL.

**Comment by shenli** [comment]
Can we close this PR? @disksing

**Comment by disksing** [comment]
We are not going to merge the feature in Beta.

**Pull request closed without merging**
