### PR TITLE
planner: fix topn wrongly pushed to index scan side when it's a prefix index (#29778)

### LINKED ISSUE #29711: order by + limit + utf8_unicode_ci，return error record
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
new_collations_enabled_on_first_bootstrap = true
CREATE TABLE `tbl_39` (
  `col_250` text COLLATE utf8_unicode_ci NOT NULL,
  `col_251` enum('Alice','Bob','Charlie','David') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Charlie',
  PRIMARY KEY (`col_251`,`col_250`(1)) NONCLUSTERED
);

insert into tbl_39 values("gugNSTjqWSrACj","Bob");    
insert into tbl_39 values("HaaRdwkoeFCH"  ,"Charlie");
insert into tbl_39 values("HbLx"          ,"David"); 
insert into tbl_39 values("kL"            ,"Bob");    
insert into tbl_39 values("mvbA"          ,"Bob");    
insert into tbl_39 values("ogdMlMqsYQ"    ,"Charlie");
insert into tbl_39 values("oUHNKUlSt"     ,"Bob");    
insert into tbl_39 values("PiPcLwhtwIAEa" ,"David");  
insert into tbl_39 values("smCLRW"        ,"David");  
insert into tbl_39 values("WIVqt"         ,"Charlie");
insert into tbl_39 values("xtGixNnzTa"    ,"Bob"); 

select col_250,col_251 from tbl_39 where tbl_39.col_251 between 'Bob' and 'David' order by tbl_39.col_250,tbl_39.col_251 limit 6; ---check
```

### 2. What did you expect to see? (Required)

```
mysql> select col_250,col_251 from tbl_39 where tbl_39.col_251 between 'Bob' and 'David' order by tbl_39.col_250,tbl_39.col_251 limit 6;
+----------------+---------+
| col_250        | col_251 |
+----------------+---------+
| gugNSTjqWSrACj | Bob     |
| HaaRdwkoeFCH   | Charlie |
| HbLx           | David   |
| kL             | Bob     |
| mvbA           | Bob     |
| ogdMlMqsYQ     | Charlie |
+----------------+---------+
6 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select col_250,col_251 from tbl_39 where tbl_39.col_251 between 'Bob' and 'David' order by tbl_39.col_250,tbl_39.col_251 limit 6;
+----------------+---------+
| col_250        | col_251 |
+----------------+---------+
| gugNSTjqWSrACj | Bob     |
| HaaRdwkoeFCH   | Charlie |
| HbLx           | David   |
| kL             | Bob     |
| mvbA           | Bob     |
| oUHNKUlSt      | Bob     |
+----------------+---------+
6 rows in set (0.01 sec)

mysql> select col_250,col_251 from tbl_39 where tbl_39.col_251 between 'Bob' and 'David' order by tbl_39.col_250,tbl_39.col_251;
+----------------+---------+
| col_250        | col_251 |
+----------------+---------+
| gugNSTjqWSrACj | Bob     |
| HaaRdwkoeFCH   | Charlie |
| HbLx           | David   |
| kL             | Bob     |
| mvbA           | Bob     |
| ogdMlMqsYQ     | Charlie |
| oUHNKUlSt      | Bob     |
| PiPcLwhtwIAEa  | David   |
| smCLRW         | David   |
| WIVqt          | Charlie |
| xtGixNnzTa     | Bob     |
+----------------+---------+
11 rows in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.2.2
Edition: Community
Git Commit Hash: da1c21fd45a4ea5900ac16d2f4a248143f378d18
Git Branch: heads/refs/tags/v5.2.2
UTC Build Time: 2021-10-29 02:43:57
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #29778 to release-5.2
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/29799
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/29799:release-5.2-a0d3f4fe540c
```

---

### What problem does this PR solve?

Issue Number: close #29711

Problem Summary:

When the `IndexScan` is using a prefix index, and the `TopN.ByItems` used the prefix column, the `TopN` is wrongly pushed to `indexPlan`.

### What is changed and how it works?

Check and push `TopN` to `tablePlan` in the above case.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]
lgtm, solve the conflict(

**Review by xuyifangreeneyes — APPROVED** [review]

**Pull request merged**
