### PR TITLE
store, metrics: update SafeTS metrics and grafana panels

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Update SafeTS metrics and grafana panels. PTAL at tikv/client-go#83 also.

### What is changed and how it works?

image

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

### Release note 

- `Add SafeTS metrics and Grafana panels for Stale Read`.

### CODE REVIEW

**Review by xhebox — COMMENTED** [review]
LGTM, but tikv-client is not updated yet.

**Review by xhebox — APPROVED** [review]
Maybe add a release note, it is visible to users.

**Review by nolouch — APPROVED** [review]

**Pull request merged**
