### PR TITLE
*: hide the config `global-kill` and session var `tidb_enable_index_merge_join`

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

What's Changed:

The features `global-kill` and `index merge join` are experimental features, thus we need to hide the config and session variables.

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`: 
  https://github.com/pingcap/docs-cn/pull/5770
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- N/A

### CODE REVIEW

**Review by lzmhhh123 — APPROVED** [review]

**Comment by XuHuaiyu** [comment]
The failed test has nothing to do with this commit:
``` sql
[2021-03-18T08:53:38.469Z] WARNING: DATA RACE
[2021-03-18T08:53:38.469Z] Read at 0x00c0b7aa6c20 by goroutine 654:
[2021-03-18T08:53:38.469Z]   github.com/pingcap/tidb/session.(*session).StoreQueryFeedback()
[2021-03-18T08:53:38.469Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:372 +0x92e
[2021-03-18T08:53:38.469Z]   github.com/pingcap/tidb/executor.(*TableReaderExecutor).Close()
[2021-03-18T08:53:38.469Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/table_reader.go:226 +0x121
[2021-03-18T08:53:38.469Z]   github.com/pingcap/tidb/executor.(*ParallelNestedLoopApplyExec).Close()
[2021-03-18T08:53:38.469Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/parallel_apply.go:162 +0xa8
[2021-03-18T08:53:38.469Z]   github.com/pingcap/tidb/executor.(*baseExecutor).Close()
[2021-03-18T08:53:38.469Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:172 +0xad
[2021-03-18T08:53:38.469Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).Close()
[2021-03-18T08:53:38.469Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:320 +0x255
[2021-03-18T08:53:38.469Z]   github.com/pingcap/tidb/executor.(*recordSet).Close()
[2021-03-18T08:53:38.469Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:165 +0x59
[2021-03-18T08:53:38.469Z]   github.com/pingcap/tidb/session.(*execStmtResult).Close()
[2021-03-18T08:53:38.469Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1570 +0x7b
[2021-03-18T08:53:38.469Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).QueryToErr()
[2021-03-18T08:53:38.469Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:306 +0x56a
[2021-03-18T08:53:38.469Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestApplyGoroutinePanic()
[2021-03-18T08:53:38.469Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/parallel_apply_test.go:587 +0x546
[2021-03-18T08:53:38.469Z]   runtime.call32()
[2021-03-18T08:53:38.469Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a
[2021-03-18T08:53:38.469Z]   reflect.Value.Call()
[2021-03-18T08:53:38.469Z]       /usr/local/go/src/reflect/value.go:321 +0xd3
[2021-03-18T08:53:38.469Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2021-03-18T08:53:38.469Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa
[2021-03-18T08:53:38.469Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2021-03-18T08:53:38.469Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113
[2021-03-18T08:53:38.470Z] 
[2021-03-18T08:53:38.470Z] Previous write at 0x00c0b7aa6c20 by goroutine 876:
[2021-03-18T08:53:38.470Z]   github.com/pingcap/tidb/statistics.(*QueryFeedback).Update()
[2021-03-18T08:53:38.470Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/feedback.go:256 +0x8e4
[2021-03-18T08:53:38.470Z]   github.com/pingcap/tidb/distsql.(*selectResult).fetchResp()
[2021-03-18T08:53:38.470Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/distsql/select_result.go:153 +0xaae
[2021-03-18T08:53:38.470Z]   github.com/pingcap/tidb/distsql.(*selectResult).Next()
[2021-03-18T08:53:38.470Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/distsql/select_result.go:180 +0x2b3
[2021-03-18T08:53:38.470Z]   github.com/pingcap/tidb/executor.(*tableResultHandler).nextChunk()
[2021-03-18T08:53:38.470Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/table_reader.go:329 +0xaa
[2021-03-18T08:53:38.470Z]   github.com/pingcap/tidb/executor.(*TableReaderExecutor).Next()
[2021-03-18T08:53:38.470Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/table_reader.go:206 +0x21e
[2021-03-18T08:53:38.470Z]   github.com/pingcap/tidb/executor.Next()
[2021-03-18T08:53:38.470Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:277 +0x27d
[2021-03-18T08:53:38.470Z]   github.com/pingcap/tidb/executor.(*ParallelNestedLoopApplyExec).outerWorker()
[2021-03-18T08:53:38.470Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/parallel_apply.go:202 +0x5a9
```

**Pull request merged**
