### PR TITLE
ddl: remove unnecessary locking when adding an index

### LINKED ISSUE #29793: Optimize adding index by remove unnecessary locking
## Enhancement
https://github.com/pingcap/tidb/blob/9c683d3f67c88ef3d96a5dfe4c2ab62c584a5001/ddl/index.go#L1332-L1341

We don't need to lock the key when adding an index. And it can cause hot-point.

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #29793

Problem Summary:
We don't need to lock the key when adding an index. And it can cause hot-point.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Optimize adding index by removing the unnecessary lockKey
```

### CODE REVIEW

**Review by zimulala — COMMENTED** [review]
Could you give us a comparison of the performance test?  To give us an idea of the optimized performance

**Comment by wjhuang2016** [comment]
According to the test(sysbench read-write, 32 tables, 10 000 000 rows per table, and add index on one table)
```
                   Before this PR            After this PR
add index time       4min 30sec                4min 10 sec 
min QPS                60K                          65K
```

**Review by zimulala — APPROVED** [review]
LGTM

**Review by bb7133 — APPROVED** [review]

**Comment by bb7133** [comment]
LGTM

**Comment by bb7133** [comment]
Talked with @wjhuang2016 as well as other engineers:

- The lock is [introduced in old days](https://github.com/pingcap/tidb/commit/a882fb52d77a0e148f2eff77ff05e6968d5bf20c)(2015), at which time the transaction model of TiDB is quite different from what it is now.
- For now, `LockKeys` is functional only for pessimistic transactions, while backfilling works in optimistic mode and we do not have a plan to change it(even for pessimistic transactions the locks are handled already).
- For the test cases that are merged with 'LockKeys' codes, they runs fine without the locks.

**Comment by cfzjywxk** [comment]
@bb7133 @wjhuang2016 

@MyonKeminta finds a case if the conflict dml transaction is committing in pessimistic mode with async commit, there could still be situations rowkey and index key become inconsistent, maybe we could revert this change and optimize it latter investigating more.

**Pull request merged**
