### PR TITLE
docs: fix 'enable_global_index' to 'enable-global-index'

### PR DESCRIPTION
**Pull request by mychoxin**
docs: fix 'enable_global_index' to 'enable-global-index'

### What problem does this PR solve?
make 'enable-global-index' consistent with definition in config.Config

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
@mychoxin Please solve the cla.

**Review by xhebox — APPROVED** [review]

**Pull request merged**
