### PR TITLE
*: fix typo interger -> integer

### PR DESCRIPTION
**Pull request by tuziemon**
### What problem does this PR solve?

Issue Number: NA

Problem Summary:

Fix typo in function name `IntergerSignedLowerBound`.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- NA

Documentation

- NA

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by bb7133** [comment]
Thanks for your contribution!

**Review by ngaut — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM

**Review by tangenta — APPROVED** [review]

**Pull request merged**
