### PR TITLE
executor: fix get var expr when session var is hex literal (#23241)

### LINKED ISSUE #22949: the result of prepare is different from that of direct query
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
use test;
DROP TABLE IF EXISTS `IDT_MC10146`;
CREATE TABLE `IDT_MC10146` (
  `COL1` bit(4) DEFAULT NULL,
  `COL2` bit(4) DEFAULT NULL,
  `COL3` bit(4) DEFAULT NULL,
  KEY `U_M_COL` (`COL1`,`COL2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO `IDT_MC10146` VALUES (0x0F, 0x00, 0x08);
prepare stmt from 'select * from IDT_MC10146 where col1 in (?);';
set @a=0x3135;
execute stmt using@a;
select * from IDT_MC10146 where col1 in (0x3135);
```

### 2. What did you expect to see? (Required)
```
MySQL [test]> prepare stmt from 'select * from IDT_MC10146 where col1 in (?);';
Query OK, 0 rows affected (0.001 sec)
Statement prepared

MySQL [test]> set @a=0x3135;
Query OK, 0 rows affected (0.000 sec)

MySQL [test]> execute stmt using@a;
Empty set (0.000 sec)

MySQL [test]> select * from IDT_MC10146 where col1 in (0x3135);
Empty set (0.001 sec)
```

### 3. What did you see instead (Required)
```
mysql> prepare stmt from 'select * from IDT_MC10146 where col1 in (?);';
Query OK, 0 rows affected (0.00 sec)

mysql> set @a=0x3135;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using@a;
+------------+------------+------------+
| COL1       | COL2       | COL3       |
+------------+------------+------------+
| 0x0F       | 0x00       | 0x08       |
+------------+------------+------------+
1 row in set (0.00 sec)

mysql> select * from IDT_MC10146 where col1 in (0x3135);
Empty set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master 745d20aa64395916060a8f716cdecf9cad9b6957
release-5.0-rc  64994e96c38a2f963f684763a5ff7c5da701056b
release-4.0 8e683506235d2497f725c0bf23d9b0372e37905d

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23241 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23373
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23373:release-5.0-2890a8f62c32
```

---

Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #22949

Problem Summary:  

    use test;
    DROP TABLE IF EXISTS `IDT_MC10146`;
    CREATE TABLE `IDT_MC10146` (
      `COL1` bit(4) DEFAULT NULL,
      `COL2` bit(4) DEFAULT NULL,
      `COL3` bit(4) DEFAULT NULL,
      KEY `U_M_COL` (`COL1`,`COL2`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
    INSERT INTO `IDT_MC10146` VALUES (0x0F, 0x00, 0x08);
    prepare stmt from 'select * from IDT_MC10146 where col1 in (?);';
    set @a=0x3135;
    execute stmt using@a;

GetVar expr(@sess_var) return string type when session_var is hex literal(eg: @sess_var = 0x3135), which is converted to '15'. Actually we should return BinaryLiteral type, but we dont have BinaryLiteral eval type.

### What is changed and how it works?

What's Changed: 
1. When UsingVar is GetVar expr and this session var is BinaryLiteral, we convert the result of GetVar (string) back to BinaryLiteral.
2. Before rewrite IN expr to EQ expr, check if contain mutalbe variables.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test: expression.TestGetVarExprWithHexLiteral()

- Side effects: no

### Release note 

- fix get var expr when session var is hex literal

### CODE REVIEW

**Comment by guo-shaoge** [comment]
This [PR](https://github.com/pingcap/tidb/pull/26481/files) fixed a unstable case. Looks like not cherry pick.

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
