### PR TITLE
topsql: use atomic.Pointer to replace with atomic.Value

### PR DESCRIPTION
**Pull request by krishnaduttPanchagnula**
### What problem does this PR solve?

Issue Number: ref #44736 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
I think you need to run ```go fmt ./...``` to fix linter.

**Review by hawkingrei — APPROVED** [review]

**Review by dveeden — APPROVED** [review]

**Pull request merged**
