### PR TITLE
planner: copy the field Column in dataSource when create partition union. (#20559)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20559 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/20558 

Problem Summary: panic/wrong result when using partition union and prune columns optimize.
1. Create datasouce when build partition union.
     Eg, datasource1, datasource2. They have the same address for field `columns` [column1,column2,column3,column4]
2. Use prune columns optimization for each datasource. In prune columns optimization, it use schema(not `columns`, because it assume the schema is same to columns.) to check whether the columns is used. 
    Assume column2 is useless.
     1. prune columns for datasource1.  
        The columns in datasource1 has changed to [column1, column3, column4]
        The columns in datasource2 has changed to [column1, column3, column4, column4]
     2. prune columns for datasource2.
       The columns in datasoucres1 has changed to [column1, column4, column4]
       The columns in datasoucres1 has changed to [column1, column4, column4]
3. Wrong columns info will build a wrong request and wrong result. After geting data from TiKV, it get panic when decoding.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
copy the field Column in dataSource when create partition union.

How it Works:

### Related changes

- Need to cherry-pick to the release branch 4.0

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- Fix unexpected panic when using partition tables.

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
Please fix the ci @wshwsh12

**Review by lzmhhh123 — APPROVED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Pull request merged**
