### PR TITLE
server: support binary time type

### PR DESCRIPTION
**Pull request by jackysp**
Support binary time and timestamp types for prepare/execute statement. PTAL @coocood @XuHuaiyu

### CODE REVIEW

**Comment by jackysp** [comment]
PTAL @coocood @XuHuaiyu

**Comment by jackysp** [comment]
Add test cases to guarantee the golang driver logic.

**Comment by jackysp** [comment]
PTAL @coocood , unit test case added.

**Comment by coocood** [comment]
LGTM

**Comment by jackysp** [comment]
PTAL @XuHuaiyu

**Comment by shenli** [comment]
LGTM

**Pull request merged**
