### PR TITLE
partition: fix hash partition with not between condition get wrong result (#22914)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #22914 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23524
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23524:release-4.0-47749a156ae9
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/22892

Tests 

- Unit test

### Release note 

- fix a bug that result of hash partition is wrong if where condition is `not between`

### CODE REVIEW

**Review by Reminiscent — APPROVED** [review]
/LGTM

**Review by winoros — APPROVED** [review]

**Review by zz-jason — APPROVED** [review]

**Pull request closed without merging**
