### PR TITLE
executor: allocate handles on demand when build table tasks

### PR DESCRIPTION
**Pull request by zyguan**
### What problem does this PR solve?

Issue Number: ref #56649

Problem Summary: `indexWorker.extractTaskHandles` will allocate a lot of memory even when there are a few handles.

Let prepare sysbench oltp data with `--secondary` option and run oltp_point_select workload. The cpu and heap profiles are shown as the following. When calling `extractTaskHandles`, it's always pre-allocate a large slice for task handles.

image
image

### What changed and how does it work?

Simply delay the slice allocation and use the first chunk size as the init capacity.

Here are the benchmark results:

| Threads | Baseline | This PR  | Diff  |
| ------- | -------- | -------- | ----- |
| 15      | 11490.40 | 11649.00 | 1.38% |
| 30      | 19087.55 | 19508.61 | 2.21% |
| 90      | 23289.24 | 24352.31 | 4.56% |

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by cfzjywxk — APPROVED** [review]
Good finding

**Review by crazycs520 — APPROVED** [review]

**Pull request merged**
