### PR TITLE
store/tikv: make TestCoprocessorStreamRecvTimeout more stable

### LINKED ISSUE #16958: unit test TestCoprocessorStreamRecvTimeout unstable
FAIL: sql_fail_test.go:106: testSQLSuite.TestCoprocessorStreamRecvTimeout

## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

Run CI

```
[2020-04-30T09:39:23.807Z] ----------------------------------------------------------------------

[2020-04-30T09:39:23.807Z] FAIL: sql_fail_test.go:106: testSQLSuite.TestCoprocessorStreamRecvTimeout

[2020-04-30T09:39:23.807Z] 

[2020-04-30T09:39:23.807Z] sql_fail_test.go:111:

[2020-04-30T09:39:23.807Z]     tk.MustExec(fmt.Sprintf("insert into t values (%d)", i))

[2020-04-30T09:39:23.807Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:183:

[2020-04-30T09:39:23.807Z]     tk.c.Assert(err, check.IsNil, check.Commentf("sql:%s, %v, error stack %v", sql, args, errors.ErrorStack(err)))

[2020-04-30T09:39:23.807Z] ... value *errors.withStack = [domain:8027]Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV ("[domain:8027]Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV")

[2020-04-30T09:39:23.807Z] ... sql:insert into t values (12), [], error stack [domain:8027]Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV

[2020-04-30T09:39:23.807Z] github.com/pingcap/errors.AddStack

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/errors.go:174

[2020-04-30T09:39:23.807Z] github.com/pingcap/errors.Trace

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/juju_adaptor.go:15

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).checkSchemaValid

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:1380

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).execute

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:1300

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/store/tikv.(*tikvTxn).Commit

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/txn.go:273

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/session.(*TxnState).Commit

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/txn.go:277

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/session.(*session).doCommit

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:434

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/session.(*session).doCommitWithRetry

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:454

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/session.(*session).CommitTxn

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:513

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/session.finishStmt

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/tidb.go:211

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/session.runStmt

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/tidb.go:293

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/session.(*session).executeStatement

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1040

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/session.(*session).execute

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1240

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/session.(*session).Execute

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1083

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/util/testkit.(*TestKit).Exec

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:144

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:182

[2020-04-30T09:39:23.807Z] github.com/pingcap/tidb/store/tikv_test.(*testSQLSuite).TestCoprocessorStreamRecvTimeout

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/sql_fail_test.go:111

[2020-04-30T09:39:23.807Z] reflect.Value.call

[2020-04-30T09:39:23.807Z] 	/usr/local/go/src/reflect/value.go:460

[2020-04-30T09:39:23.807Z] reflect.Value.Call

[2020-04-30T09:39:23.807Z] 	/usr/local/go/src/reflect/value.go:321

[2020-04-30T09:39:23.807Z] github.com/pingcap/check.(*suiteRunner).forkTest.func1

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850

[2020-04-30T09:39:23.807Z] github.com/pingcap/check.(*suiteRunner).forkCall.func1

[2020-04-30T09:39:23.807Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739

[2020-04-30T09:39:23.807Z] runtime.goexit

[2020-04-30T09:39:23.807Z] 	/usr/local/go/src/runtime/asm_amd64.s:1357
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

https://github.com/pingcap/tidb/pull/16920

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #16958 

Problem Summary:

### What is changed and how it works?

When the unit test runs parallelly with others, the table schema `t` may be changed.

How it Works:

Rename `t` to `cop_stream_timeout` to get rid of other tests' affect.

### Check List 

Tests 

- Unit test

### Release note 

-  No release note

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @SunRunAway

**Comment by wjhuang2016** [comment]
Does it need cherry-pick to 4.0?

**Comment by tiancaiamao** [comment]
> Does it need cherry-pick to 4.0?

If 4.0 meet the same error, I think we can.
This seems not a frequent CI error

**Comment by tiancaiamao** [comment]
/run-all-tests
PTAL @SunRunAway

**Pull request merged**
