### PR TITLE
types: fix err check

### PR DESCRIPTION
**Pull request by Tjianke**
### What problem does this PR solve?

Issue Number: #22979  

Problem Summary:

### What is changed and how it works?

What's Changed: added err check

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Review by djshow832 — APPROVED** [review]

**Comment by djshow832** [comment]
PTAL at the e2e-test (https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_e2e_tests/detail/tidb_e2e_tests/2986/pipeline):

```FAIL: global_kill_test.go:422: TestGlobalKillSuite.TestLostConnection
global_kill_test.go:479:
    c.Assert(r.err, NotNil)
    value = nil
```
@Tjianke

**Comment by Tjianke** [comment]
> https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_e2e_tests/detail/tidb_e2e_tests/2986/pipeline

Last time I checked, this error seems to happen in most recently merged PRs. Any Chance the test itself needs fixing?

check this #20220 for instance.

**Pull request merged**
