### PR TITLE
executor: fix AnalyzeStatus unit test data race

### LINKED ISSUE #15477: race found in unit tests
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Data race found in unit tests

```
[2020-03-19T01:44:18.803Z] ==================
[2020-03-19T01:44:18.803Z] WARNING: DATA RACE
[2020-03-19T01:44:18.803Z] Read at 0x00c0110d9f68 by goroutine 721:
[2020-03-19T01:44:18.803Z]   github.com/pingcap/tidb/statistics.GetAllAnalyzeJobs.func1()
[2020-03-19T01:44:18.803Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/analyze_jobs.go:89 +0x94
[2020-03-19T01:44:18.803Z]   sort.insertionSort_func()
[2020-03-19T01:44:18.803Z]       /usr/local/go/src/sort/zfuncversion.go:12 +0xbb
[2020-03-19T01:44:18.803Z]   sort.quickSort_func()
[2020-03-19T01:44:18.803Z]       /usr/local/go/src/sort/zfuncversion.go:158 +0x205
[2020-03-19T01:44:18.803Z]   sort.Slice()
[2020-03-19T01:44:18.803Z]       /usr/local/go/src/sort/slice.go:17 +0x11e
[2020-03-19T01:44:18.803Z]   github.com/pingcap/tidb/statistics.GetAllAnalyzeJobs()
[2020-03-19T01:44:18.803Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/analyze_jobs.go:89 +0x3bf
[2020-03-19T01:44:18.803Z]   github.com/pingcap/tidb/executor.dataForAnalyzeStatusHelper()
[2020-03-19T01:44:18.803Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:1213 +0xc2
[2020-03-19T01:44:18.803Z]   github.com/pingcap/tidb/executor.(*memtableRetriever).retrieve()
[2020-03-19T01:44:18.803Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:1239 +0x101a
[2020-03-19T01:44:18.803Z]   github.com/pingcap/tidb/executor.(*MemTableReaderExec).Next()
[2020-03-19T01:44:18.803Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/memtable_reader.go:110 +0x6fe
[2020-03-19T01:44:18.803Z]   github.com/pingcap/tidb/executor.Next()
[2020-03-19T01:44:18.803Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:213 +0x167
[2020-03-19T01:44:18.803Z]   github.com/pingcap/tidb/executor.(*SelectionExec).Next()
[2020-03-19T01:44:18.803Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:1144 +0x6e5
[2020-03-19T01:44:18.803Z]   github.com/pingcap/tidb/executor.Next()
[2020-03-19T01:44:18.803Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:213 +0x167
[2020-03-19T01:44:18.803Z]   github.com/pingcap/tidb/executor.(*recordSet).Next()
[2020-03-19T01:44:18.803Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:126 +0x110
[2020-03-19T01:44:18.803Z]   github.com/pingcap/tidb/session.GetRows4Test()
[2020-03-19T01:44:18.803Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:338 +0x35a
[2020-03-19T01:44:18.803Z]   github.com/pingcap/tidb/session.ResultSetToStringSlice()
[2020-03-19T01:44:18.803Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:356 +0xb8
[2020-03-19T01:44:18.803Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).ResultSetToResultWithCtx()
[2020-03-19T01:44:18.803Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:287 +0xa8
[2020-03-19T01:44:18.803Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustQuery()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:282 +0x4e4
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/executor_test.(*testInfoschemaTableSuite).TestForAnalyzeStatus()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader_test.go:486 +0x7ad
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/executor_test.(*testInfoschemaTableSuite).TestForAnalyzeStatus()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader_test.go:479 +0x62c
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/executor_test.(*testInfoschemaTableSuite).TestForAnalyzeStatus()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader_test.go:460 +0x166
[2020-03-19T01:44:18.804Z]   runtime.call32()
[2020-03-19T01:44:18.804Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a
[2020-03-19T01:44:18.804Z]   reflect.Value.Call()
[2020-03-19T01:44:18.804Z]       /usr/local/go/src/reflect/value.go:321 +0xd3
[2020-03-19T01:44:18.804Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa
[2020-03-19T01:44:18.804Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113
[2020-03-19T01:44:18.804Z] 
[2020-03-19T01:44:18.804Z] Previous write at 0x00c0110d9f68 by goroutine 270:
[2020-03-19T01:44:18.804Z]   [failed to restore the stack]
[2020-03-19T01:44:18.804Z] 
[2020-03-19T01:44:18.804Z] Goroutine 721 (running) created at:
[2020-03-19T01:44:18.804Z]   github.com/pingcap/check.(*suiteRunner).forkCall()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4a3
[2020-03-19T01:44:18.804Z]   github.com/pingcap/check.(*suiteRunner).forkTest()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x1b9
[2020-03-19T01:44:18.804Z]   github.com/pingcap/check.(*suiteRunner).doRun()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x13a
[2020-03-19T01:44:18.804Z]   github.com/pingcap/check.(*suiteRunner).asyncRun.func1()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:650 +0xf7
[2020-03-19T01:44:18.804Z] 
[2020-03-19T01:44:18.804Z] Goroutine 270 (running) created at:
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/executor.(*AnalyzeExec).Next()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze.go:86 +0x1b0
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/executor.Next()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:213 +0x167
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:516 +0x38e
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:395 +0x1a2
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:363 +0x3bc
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/session.runStmt()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:281 +0x36d
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/session.(*session).executeStatement()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1035 +0x112
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/session.(*session).execute()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1138 +0xb29
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/session.(*session).Execute()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1074 +0xee
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:144 +0x103
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:182 +0x91
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/executor_test.(*testSuite1).testAnalyzeIncremental()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze_test.go:372 +0x11e
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/executor_test.(*testSuite1).testAnalyzeIncremental()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze_test.go:371 +0xe7
[2020-03-19T01:44:18.804Z]   github.com/pingcap/tidb/executor_test.(*testSuite1).TestAnalyzeIncremental()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze_test.go:358 +0x127
[2020-03-19T01:44:18.804Z]   runtime.call32()
[2020-03-19T01:44:18.804Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a
[2020-03-19T01:44:18.804Z]   reflect.Value.Call()
[2020-03-19T01:44:18.804Z]       /usr/local/go/src/reflect/value.go:321 +0xd3
[2020-03-19T01:44:18.804Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa
[2020-03-19T01:44:18.804Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2020-03-19T01:44:18.804Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113
```

2. What did you expect to see?

No race

3. What did you see instead?

`AnalyzeJob.updateTime` needs to be synchronized

[link](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/28111/pipeline)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master

### PR DESCRIPTION
**Pull request by reafans**
### What problem does this PR solve?

Issue Number: close #15477 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### CODE REVIEW

**Comment by zz-jason** [comment]
would it impact the UT time?

**Comment by zz-jason** [comment]
@glorv PTAL

**Comment by glorv** [comment]
> would it impact the UT time?

This test is fast, so the impact isn't notable much. BTW, there are upto 13 serial suite in executor tests, sometimes, they will cost more than 30s， like [build#28127](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/28127/pipeline/67), and [build#28124](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/28124/pipeline/67). Maybe we need to take some effort to optimize package executor's tests.

**Comment by glorv** [comment]
A long cost test time cost by test suite looks like this:(from [build@28127](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/28127/pipeline/67)):
image

**Comment by reafans** [comment]
@zz-jason @glorv  Synchronized the AnalyzeJob.updateTime which caused the race. And change this UT back to parallel.

**Pull request merged**
