### PR TITLE
*: enable the predicate columns feature by default | tidb-test=pr/2361

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/53567

Problem Summary:

### What changed and how does it work?

I have enabled the predicate columns feature by default. However, this caused a lot of test cases to break because we updated them to collect predicate columns' statistics. Here's how I tackled updating these cases: 
1. For unit tests, especially those related to statistics, I added a new function called TriggerPredicateColumnsCollection to help collect the predicate columns. This allowed us to fix those tests.
2. For test cases in other modules, I first tried adding the index. If adding the index fixed the test without changing the test output, then I simplified it by adding the index. Otherwise, I used the 'all columns' syntax to ensure that this update wouldn't change the test logic for those cases.

We need to find a way to collect the predicate columns without having to wait for the stats usage dumping process during integration tests. I'll address this after completing all the testing work for this feature. In the meantime, we can always use all the columns as a workaround.

At the same time, I added the upgradeToVer210 function to ensure that we don't change the behavior of columns collecting(all columns) if the users upgrade the TiDB cluster from a lower version.

You can find the benchmark result here: http://perf.pingcap.net/d/iarAjGo7z/benchbot-overview?orgId=1&var-email=example%40pingcap.cn&var-testbed=benchbot-oltp-001-tps-7598610-1-822&from=now-30d&to=now (PingCAP internally only) No regression from the benchmark result.

I will do more tests after this PR is merged.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] [Manual test](https://github.com/pingcap/tidb/pull/54440#issuecomment-2224717988)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
统计信息收集默认只收集 predicate 列
Analyze only analyzes predicate columns by default
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
Test locally:

Upgrade
1. Start a low version TiDB: `tiup cluster deploy upstream v7.5.0 upstream.yaml -p && tiup cluster start upstream`
2. Patch the cluster: `tiup cluster patch upstream ../../../tidb/bin/tidb-hotfix-linux-amd64.tar.gz -N 10.2.6.161:4000,10.2.6.253:4000,10.2.7.158:4000 -R tidb`
3. Check the @@tidb_analyze_column_options:
```sql
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> select @@tidb_analyze_column_options;
+-------------------------------+
| @@tidb_analyze_column_options |
+-------------------------------+
| ALL                           |
+-------------------------------+
1 row in set (0.00 sec)
```

New cluster:
1. Start a new cluster with the patch: `tiup playground nightly  --db.binpath /Volumes/t7/code/tidb/bin/tidb-server`
2. Check the @@tidb_analyze_column_options:
```sql
mysql> select @@tidb_analyze_column_options;
+-------------------------------+
| @@tidb_analyze_column_options |
+-------------------------------+
| PREDICATE                     |
+-------------------------------+
1 row in set (0.01 sec)
```

**Review by hi-rustin — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by Leavrth — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM for DDL part

**Pull request merged**
