### PR TITLE
lightning: fix ipv6 address

### LINKED ISSUE #35880: lightning failed to connect to tidb when using ipv6 host
## Bug Report

like https://github.com/pingcap/tiflow/issues/6135, we should use [net.JoinHostPort](https://pkg.go.dev/net#JoinHostPort) in:

https://github.com/pingcap/tidb/blob/ea5b0ff8df5bbe8b9c9cc9eccf5770803d821925/br/pkg/lightning/common/util.go#L60

**PS: we cannot workaround by add square brace to host since when connecting to tidb status port we uses `net.JoinHostPort`, in which case it'll add square brace twice**
https://github.com/pingcap/tidb/blob/323411dda4efc7e760725ce6f35e22cae79ca370/br/pkg/lightning/config/config.go#L157

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #35880

Problem Summary:

### What is changed and how it works?
see issue description

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix connect to tidb when using ipv6 host
```

### CODE REVIEW

**Review by buchuitoudegou — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]
tidb-tools has been moved to TiDB repo, does it also have this problem?

**Comment by D3Hunter** [comment]
> ~tidb-tools has been moved to TiDB repo, does it also have this problem?~

there're a lot of places joining host and port manually in tidb repo. in which case we can workaround by add square brace manually if they uses same way to join.

lightning join them using both ways

**Comment by D3Hunter** [comment]
br i t passed
https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/12223/pipeline

**Pull request merged**
