### PR TITLE
executor: fix prepared stale read statement not work (#25746)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25746 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25800
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25800:release-5.1-0376dc0c5410
```

---

Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

The prepared stale read statement won't work in the following case:

```sql
1. prepare s from 'select * from t as of timestamp ts`
2. execute s (the request didn't have stale_read flag and with no local stale read ability)
```

```sql
1. prepare s from 'select * from t`
2. start transaction read only as of timestamp ts
3. execute s  (should be stale read while it isn't)
```

```sql
1. prepare s from 'select * from t`
2. set transaction read only as of timestamp ts
3. execute s  (should be stale read while it isn't)
```

### What is changed and how it works?

Fixed these problems.

- Unit test

### Release note 

- Make Stale Read fully support prepare statement

### CODE REVIEW

**Review by nolouch — APPROVED** [review]

**Comment by nolouch** [comment]
@Yisaer  please fix the conflicts.

**Review by xhebox — APPROVED** [review]

**Pull request merged**
