### PR TITLE
*: use mv instead of create soft link for vendor directory.

### PR DESCRIPTION
**Pull request by coocood**
Fix the issue that log level always use debug.

### CODE REVIEW

**Comment by shenli** [comment]
If  build failed, should we move vendor dir back manually?

**Comment by coocood** [comment]
We need to move vendor dir back manually if we failed to build and we need to commit.

**Comment by zimulala** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
