### PR TITLE
planner: Fix rebuild range for prepared plan

### LINKED ISSUE #23290: the result of prepare execute is incorrect
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE t (  `COL102` mediumint(25) DEFAULT NULL,  `COL103` mediumint(25) DEFAULT NULL,  `COL1` mediumint(25) GENERATED ALWAYS AS (`COL102` / 10) STORED NOT NULL,  `COL2` varchar(20) DEFAULT NULL,  `COL4` datetime DEFAULT NULL,  `COL3` bigint(20) DEFAULT NULL,  `COL5` float DEFAULT NULL,  PRIMARY KEY (`COL1`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

insert into t (COL102,COL103,COL2,COL4,COL3,COL5) values(11,19,"abcd","9289\-01\-03\ 22:36:43",-7766341800212896104,2.335516840459477e+38); 
insert into t (COL102,COL103,COL2,COL4,COL3,COL5) values(22,12,"abcd","0335\-11\-19\ 22:51:03",-4154892179550291056,-3.23035740051128e+38); 
insert into t (COL102,COL103,COL2,COL4,COL3,COL5) values(33,9,"abcd","5703\-06\-21\ 10:01:55",-8469066621231379353,1.478085071191862e+38);    
prepare stmt from 'select col1, col2 from t where col1 between ? and ?;';
set @a=1, @b=1;
execute stmt using@a,@b;
set @a=1, @b=10;
execute stmt using@a,@b;

```

### 2. What did you expect to see? (Required)
```sql
mysql > set @a=1, @b=1;
Query OK, 0 rows affected
Time: 0.044s
mysql > execute stmt using@a,@b;
+------+------+
| col1 | col2 |
+------+------+
| 1    | abcd |
+------+------+

1 row in set
Time: 0.054s
mysql > set @a=1, @b=10;
Query OK, 0 rows affected
Time: 0.053s
mysql > execute stmt using@a,@b;
+------+------+
| col1 | col2 |
+------+------+
| 1    | abcd |
| 2    | abcd |
| 3    | abcd |
+------+------+
```
### 3. What did you see instead (Required)
```sql
mysql > prepare stmt from 'select col1, col2 from t where col1 between ? and ?;';
Query OK, 0 rows affected
Time: 0.001s
mysql > set @a=1, @b=1;
Query OK, 0 rows affected
Time: 0.001s
mysql > execute stmt using@a,@b;
+------+------+
| col1 | col2 |
+------+------+
| 1    | abcd |
+------+------+

1 row in set
Time: 0.008s
mysql > set @a=1, @b=10;
Query OK, 0 rows affected
Time: 0.001s
mysql root@127.0.0.1:test> execute stmt using@a,@b;
+--------+--------+
| COL102 | COL103 |
+--------+--------+
| 1      | abcd   |
+--------+--------+

```
### 4. What is your TiDB version? (Required)

release-4.0:  122ee4d8fc9cf
master:  b42a6f449a4
5.0-rc: fd4437dde44

### LINKED ISSUE #23304: The result of executing prepare is wrong
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```mysql
mysql> CREATE TABLE t1(col102 bigint(20),col1 bigint(20) GENERATED ALWAYS AS (col102 ^ 10) STORED NOT NULL,PRIMARY KEY (col1) USING BTREE);
Query OK, 0 rows affected (0.10 sec)

mysql> INSERT INTO `t1` VALUES (11111, DEFAULT);
INSERT INTO `t1` VALUES (22222, DEFAULT);
INSERT INTO `t1` VALUES (33333, DEFAULT);
Query OK, 1 row affected (0.01 sec)

Query OK, 1 row affected (0.10 sec)

Query OK, 1 row affected (0.00 sec)

mysql> select * from t1;
+--------+-------+
| col102 | col1  |
+--------+-------+
|  11111 | 11117 |
|  22222 | 22212 |
|  33333 | 33343 |
+--------+-------+
3 rows in set (0.04 sec)
```

### 2. What did you expect to see? (Required)
```mysql
mysql> prepare stmt from 'select col1 from t1 where col1 in (?, ?, ?);';
Query OK, 0 rows affected (0.00 sec)

mysql> set @a=11117, @b=11117, @c=11117;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using@a,@b,@c;
+-------+
| col1  |
+-------+
| 11117 |
+-------+
1 row in set (0.05 sec)

mysql> set @a=11117, @b=22212, @c=33343;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using@a,@b,@c;
+-------+
| col1  |
+-------+
| 11117 |
| 22212 |
| 33343 |
+-------+
3 rows in set (0.04 sec)
```
### 3. What did you see instead (Required)
```mysql
mysql> prepare stmt from 'select col1 from t1 where col1 in (?, ?, ?);';
Query OK, 0 rows affected (0.00 sec)

mysql> set @a=11117, @b=11117, @c=11117;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using@a,@b,@c;
+-------+
| col1  |
+-------+
| 11117 |
+-------+
1 row in set (0.05 sec)

mysql> set @a=11117, @b=22212, @c=33343;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using@a,@b,@c;
+--------+
| col102 |
+--------+
|  11117 |
+--------+
1 row in set (0.05 sec)

```
### 4. What is your TiDB version? (Required)
```mysql
Release Version: v4.0.0-beta.2-2302-gb42a6f449-dirty
Edition: Community
Git Commit Hash: b42a6f449a49e6a68360b607a5de497a2f64faa8
Git Branch: master
UTC Build Time: 2021-03-08 12:03:16
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Issue Number: close #23304   close #23290 

Problem Summary:

### What is changed and how it works?
What's Changed:
Rebuild ranges for the prepared plan may get the wrong result. This PR will fix the BatchPointGet plan's Handle array to fix newly variables bind and will try to convert BatchPointGet to PointGet when newly variables will only have one handle, and it also can transform PointGet convert to BatchPointGet when variables may generate more than 1 handle.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- Fix prepared plan will get wrong result when variables changed.

### CODE REVIEW

**Comment by zz-jason** [comment]
we need to cherry-pick this critical bug to release 3.0, 4.0, and 5.0

**Review by winoros — APPROVED** [review]

**Comment by blacktear23** [comment]
@zz-jason this PR will not works with master branch. But it may work in 4.0 branch. The root cause for fail at master branch still need investigating.

**Comment by blacktear23** [comment]
If comments https://github.com/pingcap/tidb/blob/e56ef477317e7b9f2ee7428d5e7d898e08ab504b/planner/core/common_plans.go#L413 cases below. Then PointGetPlan will not cached, this PR will work correctly.

**Comment by XuHuaiyu** [comment]
If this commit can also fix #23290, we may also add this issue number in the PR description. @blacktear23

**Comment by blacktear23** [comment]
@zz-jason After review release-4.0 branch, the code is not same as current master, I think we should create a new PR for other release branches. And I found the code for special process PointGetPlan cache maybe the base cause for those Bugs. The cached PointGetPlan cannot update AccessConditions, so it will generate wrong ranges when variables changes. So I think disable special PointGetPlan cache logic maybe the best way to fix.

**Comment by eurekaka** [comment]
I thinks https://github.com/pingcap/tidb/pull/23238 can fix both https://github.com/pingcap/tidb/issues/23304 and https://github.com/pingcap/tidb/issues/23290 as well.

**Comment by blacktear23** [comment]
@eurekaka After read your PR, it will fix not cache PointGetPlan, but if enable prepared plan cache and BatchPointGet plan got cached, I think `rebuildRange` function also has bugs on `Handles` array rebuild.

**Comment by eurekaka** [comment]
> @eurekaka After read your PR, it will fix not cache PointGetPlan, but if enable prepared plan cache and BatchPointGet plan got cached, I think `rebuildRange` function also has bugs on `Handles` array rebuild.

Could you please manufacture a test case that would fail after applying #23238 ?

**Comment by blacktear23** [comment]
> > @eurekaka After read your PR, it will fix not cache PointGetPlan, but if enable prepared plan cache and BatchPointGet plan got cached, I think `rebuildRange` function also has bugs on `Handles` array rebuild.
> 
> Could you please manufacture a test case that would fail after applying #23238 ?

After I do the test on your feature branch, yes it cannot reproduce now. But your PR just disables PreparedPlanCache for statements with variables. Is that what we expected?

**Comment by eurekaka** [comment]
> just disables PreparedPlanCache for statements with variables

How does this come? #23238 prevents plans with aggressive optimizations from being cached, because those aggressive optimizations **may** depend on the user variables.

**Comment by blacktear23** [comment]
> > just disables PreparedPlanCache for statements with variables
> 
> How does this come? #23238 prevents plans with aggressive optimizations from being cached, because those aggressive optimizations **may** depend on the user variables.

In my test I see `OptimDependOnMutableConst` is always `true`, so even BatchPointGet plan still cannot be cached. Or is there has any way to let BatchPointGet can be cached?

**Comment by zz-jason** [comment]
I'm going to close this PR since it hasn't been updated for a long time. Feel free to reopen it once you wish to advance this PR in the future.

**Pull request closed without merging**
