### PR TITLE
executor: fix common handle index lookup in union scan

### LINKED ISSUE #19092: Got wrong result in a transaction when using clustered index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set @@tidb_enable_clustered_index=1;
drop table if exists t;
-- init
create table t ( c_int int, c_str varchar(40), c_datetime datetime, c_timestamp timestamp, c_double double, c_decimal decimal(12, 6), primary key(c_str), key(c_int), key(c_str), unique key(c_decimal), key(c_datetime), key(c_timestamp) );
insert into t values (6, 'great satoshi', '2020-02-19 09:06:26', '2020-04-06 20:36:16', 90.462320, 2.458);
-- txn
begin;
update t set c_int = c_int + 10, c_str = 'elegant lovelace' where c_int = 6;
select c_int, c_str, c_double, c_decimal, c_datetime, c_timestamp from t where c_int = 16;  -- c_str is null
commit;
select c_int, c_str, c_double, c_decimal, c_datetime, c_timestamp from t where c_int = 16;  -- c_str is 'elegant lovelace'
```

### 2. What did you expect to see? (Required)

The two select statements should return same result.

### 3. What did you see instead (Required)

```
mysql> begin;
Query OK, 0 rows affected (0.06 sec)

mysql> update t set c_int = c_int + 10, c_str = 'elegant lovelace' where c_int = 6;
Query OK, 1 row affected (0.07 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select c_int, c_str, c_double, c_decimal, c_datetime, c_timestamp from t where c_int = 16;  -- c_str is null
+-------+-------+----------+-----------+---------------------+---------------------+
| c_int | c_str | c_double | c_decimal | c_datetime          | c_timestamp         |
+-------+-------+----------+-----------+---------------------+---------------------+
|    16 | NULL  | 90.46232 |  2.458000 | 2020-02-19 09:06:26 | 2020-04-06 20:36:16 |
+-------+-------+----------+-----------+---------------------+---------------------+
1 row in set (0.05 sec)

mysql> commit;
Query OK, 0 rows affected (0.06 sec)

mysql> select c_int, c_str, c_double, c_decimal, c_datetime, c_timestamp from t where c_int = 16;  -- c_str is 'elegant lovelace'
+-------+------------------+----------+-----------+---------------------+---------------------+
| c_int | c_str            | c_double | c_decimal | c_datetime          | c_timestamp         |
+-------+------------------+----------+-----------+---------------------+---------------------+
|    16 | elegant lovelace | 90.46232 |  2.458000 | 2020-02-19 09:06:26 | 2020-04-06 20:36:16 |
+-------+------------------+----------+-----------+---------------------+---------------------+
1 row in set (0.07 sec)

```

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-921-gb75a30fda
Edition: Community
Git Commit Hash: b75a30fda8eef5962e2fde1c6254ff02f330fd21
Git Branch: master
UTC Build Time: 2020-08-09 02:54:26
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #19092 

Problem Summary:

The minimal reproducible case:
```sql
set @@tidb_enable_clustered_index=1;
drop table if exists t;
create table t (a int, pk char(10), c int, primary key(pk), key(a));
insert into t values (1, '111', 3);

begin;
update t set a = a + 1, pk = '222' where a = 1;
select pk, c from t where a = 2;
commit;
select pk, c from t where a = 2;
```

In `memIndexLookUpReader`, the `handleColIDs` field of row decoder should be initialized with primary key IDs. 

### What is changed and how it works?

What's Changed: Omitted.

How it Works: Omitted.

### Related changes

N/A

### Check List 

Tests 

- Unit test
- Integration test

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by tangenta** [comment]
/run-integration-ddl-test
```
[ERROR] [util.rs:468] ["connect failed"] [err="Grpc(RpcFailure(RpcStatus { status: 14-UNAVAILABLE, details: Some(\"failed to connect to all addresses\") }))"] [endpoints=http://127.0.0.1:2379]
```

**Pull request merged**
