### PR TITLE
expression: fix unstable test TestExprOnlyPushDownToFlash

### PR DESCRIPTION
**Pull request by LittleFall**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/25584 

Problem Summary:  see https://github.com/pingcap/tidb/issues/25584#issuecomment-873951010

### What is changed and how it works?

What's Changed: make these tests serial.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`: no need
- Need to cherry-pick to the release branch: no need

### Check List 

Tests 

- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by fzhedu — APPROVED** [review]
/LGTM

**Review by lzmhhh123 — APPROVED** [review]

**Comment by LittleFall** [comment]
The result of the attempt shows: test suite with bootstrap such as `testIntegrationSuiteBase` will initialize the blacklist, and will not eliminate it after teardown.

If the suite tested of `TestExprOnlyPushDownToFlash` is set to serial, then this error will inevitably occur. The minimum recurrence is: `go test -v ./expression/... -check.f "TestExprPushdownBlacklist|TestExprOnlyPushDownToFlash"`. 

Another solution is to manually eliminate the blacklist when every suite is tearing down.
```
	tk := testkit.NewTestKit(c, s.store)
	tk.MustExec("use mysql")
	tk.MustExec("delete from expr_pushdown_blacklist")
	tk.MustExec("admin reload expr_pushdown_blacklist")
```
but it is too stupid.

**Pull request merged**
