### PR TITLE
*: add sys var tidb_enable_global_temporary_table to open global temp table

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

add a sys var `tidb_enable_global_temporary_table` to open global temporary table

### What is changed and how it works?

use `set global tidb_enable_global_temporary_table=true` or `set tidb_enable_global_temporary_table=true `to open global temporary table, and set it to `false` if you want to close it.

### Related changes

- N/A

### Check List 

Tests 

- Unit test

Side effects

- N/A

### Release note 

- N/A

### CODE REVIEW

**Review by djshow832 — COMMENTED** [review]
You don't have test cases to cover the variable itself.
Say, Is the global temporary table forbidden if the switch is off? Is it shown in `show variables`? (We don't want to show it).

**Review by djshow832 — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
