### PR TITLE
infoschema: add VIEWS and ROUTINES table

### PR DESCRIPTION
**Pull request by tiancaiamao**
```
mysql> show tables;
+------------------------------+
| Tables_in_information_schema |
+------------------------------+
| CHARACTER_SETS               |
| COLLATIONS                   |
| COLUMNS                      |
| ENGINES                      |
| FILES                        |
| KEY_COLUMN_USAGE             |
| PARTITIONS                   |
| PLUGINS                      |
| PROFILING                    |
| REFERENTIAL_CONSTRAINTS      |
| SCHEMATA                     |
| SESSION_VARIABLES            |
| STATISTICS                   |
| TABLES                       |
| TABLE_CONSTRAINTS            |
| TRIGGERS                     |
| USER_PRIVILEGES              |
| VIEWS                        |
+------------------------------+
18 rows in set (0.00 sec)

mysql> select * from VIEWS;
Empty set (0.01 sec)
```

PTAL @shenli @zimulala @coocood  @hanfei1991 @XuHuaiyu @winoros @lamxTyler

### CODE REVIEW

**Comment by coocood** [comment]
@tiancaiamao 
Any tests for `select * from information_schema.views`?

**Comment by tiancaiamao** [comment]
As TiDB doesn't support view, so VIEWS is a empty table.
There is a test that checks VIEWS table exists in the schema. @coocood

**Comment by coocood** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
