### PR TITLE
*: upgrade to go 1.12

### PR DESCRIPTION
**Pull request by mahjonp**
### What problem does this PR solve? 

This pr fixes the problem of building docker image on release-2.1

``` bash
Sending build context to Docker daemon  352.9MB
Step 1/10 : FROM golang:1.10.1-alpine as builder
1.10.1-alpine: Pulling from library/golang
ff3a5c916c92: Pull complete
f32d2ea73378: Pull complete
c6678747892c: Pull complete
16b5f22d8b23: Pull complete
Digest: sha256:356aea725be911d52e0f2f0344a17ac3d97c54c74d50b8561f58eae6cc0871bf
Status: Downloaded newer image for golang:1.10.1-alpine
 ---> 52d894fca6d4
Step 2/10 : RUN apk add --no-cache     make     git
 ---> Running in e223ed448cda
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/6) Installing libssh2 (1.8.2-r0)
(2/6) Installing libcurl (7.61.1-r2)
(3/6) Installing expat (2.2.5-r0)
(4/6) Installing pcre2 (10.30-r0)
(5/6) Installing git (2.15.3-r0)
(6/6) Installing make (4.2.1-r0)
Executing busybox-1.27.2-r7.trigger
OK: 19 MiB in 18 packages
Removing intermediate container e223ed448cda
 ---> 07b518fa58ec
Step 3/10 : COPY . /go/src/github.com/pingcap/tidb
 ---> 7a091bc1f42c
Step 4/10 : WORKDIR /go/src/github.com/pingcap/tidb/
 ---> Running in 026c12e4d39b
Removing intermediate container 026c12e4d39b
 ---> 2375828dd587
Step 5/10 : RUN make
 ---> Running in d4b880f07f35
CGO_ENABLED=1 GO111MODULE=on go build   -ldflags '-X "github.com/pingcap/parser/mysql.TiDBReleaseVersion=v2.1.8-21-g0f6621d05f" -X "github.com/pingcap/tidb/util/printer.TiDBBuildTS=2019-04-29 10:37:03" -X "github.com/pingcap/tidb/util/printer.TiDBGitHash=0f6621d05fc50dbe5ee1af1765de04f13c11224d" -X "github.com/pingcap/tidb/util/printer.TiDBGitBranch=HEAD" -X "github.com/pingcap/tidb/util/printer.GoVersion=go version go1.10.1 linux/amd64" ' -o bin/tidb-server tidb-server/main.go
config/config.go:24:2: cannot find package "github.com/BurntSushi/toml" in any of:
        /usr/local/go/src/github.com/BurntSushi/toml (from $GOROOT)
        /go/src/github.com/BurntSushi/toml (from $GOPATH)
server/server.go:48:2: cannot find package "github.com/blacktear23/go-proxyprotocol" in any of:
        /usr/local/go/src/github.com/blacktear23/go-proxyprotocol (from $GOROOT)
        /go/src/github.com/blacktear23/go-proxyprotocol (from $GOPATH)
ddl/ddl.go:25:2: cannot find package "github.com/coreos/etcd/clientv3" in any of:
        /usr/local/go/src/github.com/coreos/etcd/clientv3 (from $GOROOT)
        /go/src/github.com/coreos/etcd/clientv3 (from $GOPATH)
ddl/syncer.go:26:2: cannot find package "github.com/coreos/etcd/clientv3/concurrency" in any of:
        /usr/local/go/src/github.com/coreos/etcd/clientv3/concurrency (from $GOROOT)
        /go/src/github.com/coreos/etcd/clientv3/concurrency (from $GOPATH)
owner/manager.go:27:2: cannot find package "github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes" in any of:
        /usr/local/go/src/github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes (from $GOROOT)
        /go/src/github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes (from $GOPATH)
owner/manager.go:28:2: cannot find package "github.com/coreos/etcd/mvcc/mvccpb" in any of:
        /usr/local/go/src/github.com/coreos/etcd/mvcc/mvccpb (from $GOROOT)
        /go/src/github.com/coreos/etcd/mvcc/mvccpb (from $GOPATH)
ddl/ddl_api.go:26:2: cannot find package "github.com/cznic/mathutil" in any of:
        /usr/local/go/src/github.com/cznic/mathutil (from $GOROOT)
        /go/src/github.com/cznic/mathutil (from $GOPATH)
statistics/cmsketch.go:20:2: cannot find package "github.com/cznic/sortutil" in any of:
        /usr/local/go/src/github.com/cznic/sortutil (from $GOROOT)
        /go/src/github.com/cznic/sortutil (from $GOPATH)
store/mockstore/mocktikv/analyze.go:17:2: cannot find package "github.com/golang/protobuf/proto" in any of:
        /usr/local/go/src/github.com/golang/protobuf/proto (from $GOROOT)
        /go/src/github.com/golang/protobuf/proto (from $GOPATH)
store/tikv/region_cache.go:23:2: cannot find package "github.com/google/btree" in any of:
        /usr/local/go/src/github.com/google/btree (from $GOROOT)
        /go/src/github.com/google/btree (from $GOPATH)
server/http_handler.go:31:2: cannot find package "github.com/gorilla/mux" in any of:
        /usr/local/go/src/github.com/gorilla/mux (from $GOROOT)
        /go/src/github.com/gorilla/mux (from $GOPATH)
store/tikv/client.go:24:2: cannot find package "github.com/grpc-ecosystem/go-grpc-middleware" in any of:
        /usr/local/go/src/github.com/grpc-ecosystem/go-grpc-middleware (from $GOROOT)
        /go/src/github.com/grpc-ecosystem/go-grpc-middleware (from $GOPATH)
store/tikv/client.go:25:2: cannot find package "github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing" in any of:
        /usr/local/go/src/github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing (from $GOROOT)
        /go/src/github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing (from $GOPATH)
store/tikv/client.go:26:2: cannot find package "github.com/grpc-ecosystem/go-grpc-prometheus" in any of:
        /usr/local/go/src/github.com/grpc-ecosystem/go-grpc-prometheus (from $GOROOT)
        /go/src/github.com/grpc-ecosystem/go-grpc-prometheus (from $GOPATH)
ddl/ddl.go:26:2: cannot find package "github.com/ngaut/pools" in any of:
        /usr/local/go/src/github.com/ngaut/pools (from $GOROOT)
        /go/src/github.com/ngaut/pools (from $GOPATH)
domain/domain.go:27:2: cannot find package "github.com/ngaut/sync2" in any of:
        /usr/local/go/src/github.com/ngaut/sync2 (from $GOROOT)
        /go/src/github.com/ngaut/sync2 (from $GOPATH)
executor/trace.go:19:2: cannot find package "github.com/opentracing/basictracer-go" in any of:
        /usr/local/go/src/github.com/opentracing/basictracer-go (from $GOROOT)
        /go/src/github.com/opentracing/basictracer-go (from $GOPATH)
tidb-server/main.go:26:2: cannot find package "github.com/opentracing/opentracing-go" in any of:
        /usr/local/go/src/github.com/opentracing/opentracing-go (from $GOROOT)
        /go/src/github.com/opentracing/opentracing-go (from $GOPATH)
tidb-server/main.go:27:2: cannot find package "github.com/pingcap/errors" in any of:
        /usr/local/go/src/github.com/pingcap/errors (from $GOROOT)
        /go/src/github.com/pingcap/errors (from $GOPATH)
kv/memdb_buffer.go:22:2: cannot find package "github.com/pingcap/goleveldb/leveldb" in any of:
        /usr/local/go/src/github.com/pingcap/goleveldb/leveldb (from $GOROOT)
        /go/src/github.com/pingcap/goleveldb/leveldb (from $GOPATH)
kv/memdb_buffer.go:23:2: cannot find package "github.com/pingcap/goleveldb/leveldb/comparer" in any of:
        /usr/local/go/src/github.com/pingcap/goleveldb/leveldb/comparer (from $GOROOT)
        /go/src/github.com/pingcap/goleveldb/leveldb/comparer (from $GOPATH)
kv/memdb_buffer.go:24:2: cannot find package "github.com/pingcap/goleveldb/leveldb/iterator" in any of:
        /usr/local/go/src/github.com/pingcap/goleveldb/leveldb/iterator (from $GOROOT)
        /go/src/github.com/pingcap/goleveldb/leveldb/iterator (from $GOPATH)
kv/memdb_buffer.go:25:2: cannot find package "github.com/pingcap/goleveldb/leveldb/memdb" in any of:
        /usr/local/go/src/github.com/pingcap/goleveldb/leveldb/memdb (from $GOROOT)
        /go/src/github.com/pingcap/goleveldb/leveldb/memdb (from $GOPATH)
store/mockstore/mocktikv/mvcc_leveldb.go:24:2: cannot find package "github.com/pingcap/goleveldb/leveldb/opt" in any of:
        /usr/local/go/src/github.com/pingcap/goleveldb/leveldb/opt (from $GOROOT)
        /go/src/github.com/pingcap/goleveldb/leveldb/opt (from $GOPATH)
store/mockstore/mocktikv/mvcc_leveldb.go:25:2: cannot find package "github.com/pingcap/goleveldb/leveldb/storage" in any of:
        /usr/local/go/src/github.com/pingcap/goleveldb/leveldb/storage (from $GOROOT)
        /go/src/github.com/pingcap/goleveldb/leveldb/storage (from $GOPATH)
kv/memdb_buffer.go:26:2: cannot find package "github.com/pingcap/goleveldb/leveldb/util" in any of:
        /usr/local/go/src/github.com/pingcap/goleveldb/leveldb/util (from $GOROOT)
        /go/src/github.com/pingcap/goleveldb/leveldb/util (from $GOPATH)
store/tikv/client.go:28:2: cannot find package "github.com/pingcap/kvproto/pkg/coprocessor" in any of:
        /usr/local/go/src/github.com/pingcap/kvproto/pkg/coprocessor (from $GOROOT)
        /go/src/github.com/pingcap/kvproto/pkg/coprocessor (from $GOPATH)
store/tikv/region_request.go:20:2: cannot find package "github.com/pingcap/kvproto/pkg/errorpb" in any of:
        /usr/local/go/src/github.com/pingcap/kvproto/pkg/errorpb (from $GOROOT)
        /go/src/github.com/pingcap/kvproto/pkg/errorpb (from $GOPATH)
store/tikv/2pc.go:24:2: cannot find package "github.com/pingcap/kvproto/pkg/kvrpcpb" in any of:
        /usr/local/go/src/github.com/pingcap/kvproto/pkg/kvrpcpb (from $GOROOT)
        /go/src/github.com/pingcap/kvproto/pkg/kvrpcpb (from $GOPATH)
store/tikv/pd_codec.go:18:2: cannot find package "github.com/pingcap/kvproto/pkg/metapb" in any of:
        /usr/local/go/src/github.com/pingcap/kvproto/pkg/metapb (from $GOROOT)
        /go/src/github.com/pingcap/kvproto/pkg/metapb (from $GOPATH)
store/tikv/client.go:29:2: cannot find package "github.com/pingcap/kvproto/pkg/tikvpb" in any of:
        /usr/local/go/src/github.com/pingcap/kvproto/pkg/tikvpb (from $GOROOT)
        /go/src/github.com/pingcap/kvproto/pkg/tikvpb (from $GOPATH)
tidb-server/main.go:28:2: cannot find package "github.com/pingcap/log" in any of:
        /usr/local/go/src/github.com/pingcap/log (from $GOROOT)
        /go/src/github.com/pingcap/log (from $GOPATH)
sessionctx/stmtctx/stmtctx.go:22:2: cannot find package "github.com/pingcap/parser" in any of:
        /usr/local/go/src/github.com/pingcap/parser (from $GOROOT)
        /go/src/github.com/pingcap/parser (from $GOPATH)
ddl/column.go:21:2: cannot find package "github.com/pingcap/parser/ast" in any of:
        /usr/local/go/src/github.com/pingcap/parser/ast (from $GOROOT)
        /go/src/github.com/pingcap/parser/ast (from $GOPATH)
sessionctx/variable/session.go:28:2: cannot find package "github.com/pingcap/parser/auth" in any of:
        /usr/local/go/src/github.com/pingcap/parser/auth (from $GOROOT)
        /go/src/github.com/pingcap/parser/auth (from $GOPATH)
ddl/ddl_api.go:29:2: cannot find package "github.com/pingcap/parser/charset" in any of:
        /usr/local/go/src/github.com/pingcap/parser/charset (from $GOROOT)
        /go/src/github.com/pingcap/parser/charset (from $GOPATH)
ddl/callback.go:17:2: cannot find package "github.com/pingcap/parser/model" in any of:
        /usr/local/go/src/github.com/pingcap/parser/model (from $GOROOT)
        /go/src/github.com/pingcap/parser/model (from $GOPATH)
tidb-server/main.go:29:2: cannot find package "github.com/pingcap/parser/mysql" in any of:
        /usr/local/go/src/github.com/pingcap/parser/mysql (from $GOROOT)
        /go/src/github.com/pingcap/parser/mysql (from $GOPATH)
ddl/partition.go:26:2: cannot find package "github.com/pingcap/parser/opcode" in any of:
        /usr/local/go/src/github.com/pingcap/parser/opcode (from $GOROOT)
        /go/src/github.com/pingcap/parser/opcode (from $GOPATH)
tidb-server/main.go:30:2: cannot find package "github.com/pingcap/parser/terror" in any of:
        /usr/local/go/src/github.com/pingcap/parser/terror (from $GOROOT)
        /go/src/github.com/pingcap/parser/terror (from $GOPATH)
types/errors.go:19:2: cannot find package "github.com/pingcap/parser/types" in any of:
        /usr/local/go/src/github.com/pingcap/parser/types (from $GOROOT)
        /go/src/github.com/pingcap/parser/types (from $GOPATH)
tidb-server/main.go:31:2: cannot find package "github.com/pingcap/pd/client" in any of:
        /usr/local/go/src/github.com/pingcap/pd/client (from $GOROOT)
        /go/src/github.com/pingcap/pd/client (from $GOPATH)
executor/show.go:32:2: cannot find package "github.com/pingcap/tidb-tools/pkg/etcd" in any of:
        /usr/local/go/src/github.com/pingcap/tidb-tools/pkg/etcd (from $GOROOT)
        /go/src/github.com/pingcap/tidb-tools/pkg/etcd (from $GOPATH)
executor/show.go:33:2: cannot find package "github.com/pingcap/tidb-tools/pkg/utils" in any of:
        /usr/local/go/src/github.com/pingcap/tidb-tools/pkg/utils (from $GOROOT)
        /go/src/github.com/pingcap/tidb-tools/pkg/utils (from $GOPATH)
sessionctx/binloginfo/binloginfo.go:26:2: cannot find package "github.com/pingcap/tidb-tools/tidb-binlog/node" in any of:
        /usr/local/go/src/github.com/pingcap/tidb-tools/tidb-binlog/node (from $GOROOT)
        /go/src/github.com/pingcap/tidb-tools/tidb-binlog/node (from $GOPATH)
tidb-server/main.go:32:2: cannot find package "github.com/pingcap/tidb-tools/tidb-binlog/pump_client" in any of:
        /usr/local/go/src/github.com/pingcap/tidb-tools/tidb-binlog/pump_client (from $GOROOT)
        /go/src/github.com/pingcap/tidb-tools/tidb-binlog/pump_client (from $GOPATH)
sessionctx/context.go:25:2: cannot find package "github.com/pingcap/tipb/go-binlog" in any of:
        /usr/local/go/src/github.com/pingcap/tipb/go-binlog (from $GOROOT)
        /go/src/github.com/pingcap/tipb/go-binlog (from $GOPATH)
util/mock/client.go:18:2: cannot find package "github.com/pingcap/tipb/go-tipb" in any of:
        /usr/local/go/src/github.com/pingcap/tipb/go-tipb (from $GOROOT)
        /go/src/github.com/pingcap/tipb/go-tipb (from $GOPATH)
metrics/ddl.go:16:8: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
        /usr/local/go/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
        /go/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
tidb-server/main.go:55:2: cannot find package "github.com/prometheus/client_golang/prometheus/push" in any of:
        /usr/local/go/src/github.com/prometheus/client_golang/prometheus/push (from $GOROOT)
        /go/src/github.com/prometheus/client_golang/prometheus/push (from $GOPATH)
util/logutil/log.go:28:2: cannot find package "github.com/sirupsen/logrus" in any of:
        /usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)
        /go/src/github.com/sirupsen/logrus (from $GOPATH)
table/tables/tables.go:44:2: cannot find package "github.com/spaolacci/murmur3" in any of:
        /usr/local/go/src/github.com/spaolacci/murmur3 (from $GOROOT)
        /go/src/github.com/spaolacci/murmur3 (from $GOPATH)
expression/builtin_miscellaneous.go:30:2: cannot find package "github.com/twinj/uuid" in any of:
        /usr/local/go/src/github.com/twinj/uuid (from $GOROOT)
        /go/src/github.com/twinj/uuid (from $GOPATH)
config/config.go:27:2: cannot find package "github.com/uber/jaeger-client-go/config" in any of:
        /usr/local/go/src/github.com/uber/jaeger-client-go/config (from $GOROOT)
        /go/src/github.com/uber/jaeger-client-go/config (from $GOPATH)
util/logutil/log.go:29:2: cannot find package "go.uber.org/zap" in any of:
        /usr/local/go/src/go.uber.org/zap (from $GOROOT)
        /go/src/go.uber.org/zap (from $GOPATH)
statistics/update.go:18:2: cannot find package "go.uber.org/zap/zapcore" in any of:
        /usr/local/go/src/go.uber.org/zap/zapcore (from $GOROOT)
        /go/src/go.uber.org/zap/zapcore (from $GOPATH)
store/tikv/oracle/oracle.go:19:2: cannot find package "golang.org/x/net/context" in any of:
        /usr/local/go/src/golang.org/x/net/context (from $GOROOT)
        /go/src/golang.org/x/net/context (from $GOPATH)
util/charset/encoding_table.go:19:2: cannot find package "golang.org/x/text/encoding" in any of:
        /usr/local/go/src/golang.org/x/text/encoding (from $GOROOT)
        /go/src/golang.org/x/text/encoding (from $GOPATH)
util/charset/encoding_table.go:20:2: cannot find package "golang.org/x/text/encoding/charmap" in any of:
        /usr/local/go/src/golang.org/x/text/encoding/charmap (from $GOROOT)
        /go/src/golang.org/x/text/encoding/charmap (from $GOPATH)
util/charset/encoding_table.go:21:2: cannot find package "golang.org/x/text/encoding/japanese" in any of:
        /usr/local/go/src/golang.org/x/text/encoding/japanese (from $GOROOT)
        /go/src/golang.org/x/text/encoding/japanese (from $GOPATH)
util/charset/encoding_table.go:22:2: cannot find package "golang.org/x/text/encoding/korean" in any of:
        /usr/local/go/src/golang.org/x/text/encoding/korean (from $GOROOT)
        /go/src/golang.org/x/text/encoding/korean (from $GOPATH)
util/charset/encoding_table.go:23:2: cannot find package "golang.org/x/text/encoding/simplifiedchinese" in any of:
        /usr/local/go/src/golang.org/x/text/encoding/simplifiedchinese (from $GOROOT)
        /go/src/golang.org/x/text/encoding/simplifiedchinese (from $GOPATH)
util/charset/encoding_table.go:24:2: cannot find package "golang.org/x/text/encoding/traditionalchinese" in any of:
        /usr/local/go/src/golang.org/x/text/encoding/traditionalchinese (from $GOROOT)
        /go/src/golang.org/x/text/encoding/traditionalchinese (from $GOPATH)
util/charset/encoding_table.go:25:2: cannot find package "golang.org/x/text/encoding/unicode" in any of:
        /usr/local/go/src/golang.org/x/text/encoding/unicode (from $GOROOT)
        /go/src/golang.org/x/text/encoding/unicode (from $GOPATH)
expression/builtin_string.go:42:2: cannot find package "golang.org/x/text/transform" in any of:
        /usr/local/go/src/golang.org/x/text/transform (from $GOROOT)
        /go/src/golang.org/x/text/transform (from $GOPATH)
expression/util.go:31:2: cannot find package "golang.org/x/tools/container/intsets" in any of:
        /usr/local/go/src/golang.org/x/tools/container/intsets (from $GOROOT)
        /go/src/golang.org/x/tools/container/intsets (from $GOPATH)
owner/manager.go:36:2: cannot find package "google.golang.org/grpc" in any of:
        /usr/local/go/src/google.golang.org/grpc (from $GOROOT)
        /go/src/google.golang.org/grpc (from $GOPATH)
store/tikv/region_request.go:29:2: cannot find package "google.golang.org/grpc/codes" in any of:
        /usr/local/go/src/google.golang.org/grpc/codes (from $GOROOT)
        /go/src/google.golang.org/grpc/codes (from $GOPATH)
store/tikv/client.go:37:2: cannot find package "google.golang.org/grpc/credentials" in any of:
        /usr/local/go/src/google.golang.org/grpc/credentials (from $GOROOT)
        /go/src/google.golang.org/grpc/credentials (from $GOPATH)
store/tikv/client.go:38:2: cannot find package "google.golang.org/grpc/keepalive" in any of:
        /usr/local/go/src/google.golang.org/grpc/keepalive (from $GOROOT)
        /go/src/google.golang.org/grpc/keepalive (from $GOPATH)
store/mockstore/mocktikv/cop_handler_dag.go:42:2: cannot find package "google.golang.org/grpc/metadata" in any of:
        /usr/local/go/src/google.golang.org/grpc/metadata (from $GOROOT)
        /go/src/google.golang.org/grpc/metadata (from $GOPATH)
util/logutil/log.go:30:2: cannot find package "gopkg.in/natefinch/lumberjack.v2" in any of:
        /usr/local/go/src/gopkg.in/natefinch/lumberjack.v2 (from $GOROOT)
        /go/src/gopkg.in/natefinch/lumberjack.v2 (from $GOPATH)
make: *** [Makefile:157: server] Error 1
The command '/bin/sh -c make' returned a non-zero code: 2

```

### What is changed and how it works?

also see: #9299 #9138

### CODE REVIEW

**Comment by mahjonp** [comment]
PTAL @zz-jason @tiancaiamao

**Comment by shenli** [comment]
Why not use golang 1.12?

**Comment by zz-jason** [comment]
LGTM

**Comment by mahjonp** [comment]
PTAL again @zz-jason @tiancaiamao

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
go1.12 have go mod issues

**Comment by mahjonp** [comment]
@zyguan would you please help to resolve the go mod issue.  😂

**Comment by zyguan** [comment]
/run-all-tests tidb-test=pr/797 tikv=release-2.1 pd=release-2.1

**Comment by zyguan** [comment]
/run-common-test tidb-test=pr/797 tikv=release-2.1 pd=release-2.1

**Comment by zyguan** [comment]
/run-integration-common-test tidb-test=pr/797 tikv=release-2.1 pd=release-2.1

**Comment by tiancaiamao** [comment]
LGTM

**Comment by ngaut** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zyguan** [comment]
/run-all-tests tidb-test=pr/797 tikv=release-2.1 pd=release-2.1

**Pull request merged**
