### PR TITLE
br: Update web deps and README

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Problem Summary:

Close: https://github.com/pingcap/tidb/security/dependabot/53
Close: https://github.com/pingcap/tidb/security/dependabot/28
Update the README to reflect changes after BR was merged into pingcap/tidb

Related:
- #40333 
- #42228

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Security updates for the TiDB Lightning web interface were applied
```

### CODE REVIEW

**Comment by dveeden** [comment]
```
[dvaneeden@dve-carbon web]$ npm audit
# npm audit report

json5  2.0.0 - 2.2.1
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
fix available via `npm audit fix`
node_modules/json5

webpack  5.0.0 - 5.75.0
Severity: high
Cross-realm object access in Webpack 5 - https://github.com/advisories/GHSA-hc6q-2mpp-qw7j
fix available via `npm audit fix`
node_modules/webpack

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix
[dvaneeden@dve-carbon web]$ npm audit fix

added 1 package, removed 4 packages, changed 38 packages, and audited 252 packages in 5s

31 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by hawkingrei** [comment]
In fact, bazel can be used in the front project. Have you interested to support bazel for front code?

**Comment by hawkingrei** [comment]
> In fact, bazel can be used in the front project. Have you interested to support bazel for front code?

so that we can check the front code in the CI.

**Review by hawkingrei — APPROVED** [review]

**Comment by dveeden** [comment]
@hawkingrei That's an interesting option.

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
