### PR TITLE
fixed warning when executing `glide install`

### PR DESCRIPTION
**Pull request by zhexuany**
The warning is the following 

~~~
[WARN]	Your setup appears to be for the previous version of Glide.
Previously, vendor packages were stored in _vendor/src/ and
_vendor was set as your GOPATH. As of Go 1.5 the go tools
recognize the vendor directory as a location for these
files. Glide has embraced this. Please remove the _vendor
directory or move the _vendor/src/ directory to vendor/.
~~~

### CODE REVIEW

**Comment by zhexuany** [comment]
https://github.com/gojp/goreportcard/issues/158

**Comment by coocood** [comment]
@zhexuany 
Thank you for your effort!
We have considered vendor path before.
For now, we prefer to use GOPATH and ignore the warning.
It doesn't mean vendor path is not better, maybe we will change it in the future, but not now.

**Comment by zhexuany** [comment]
@coocood I noticed that every time in Makefile, you have to remove `vendor` first and rename `_vendor` to `vendor`. The only drawback of changing `_vendor` to `vendor` is `golint`. `golint` does not recognize `vendor` and scan such directory. It often causes `CI` unhappy. By skipping `vendor`, everything works just fine. Maybe this is a good time to reconsider this. This is just suggestion. If the team does not like this approach, I gonna closed this PR and reopen it in future if team decide to take this approach.

**Comment by coocood** [comment]
@zhexuany 
use `vendor` package on root directory have problems when other repositories need to depend on tidb package.

If we take 'vendor' approach, we would put it under a subdirectory instead of the root directory.

And we have to evaluate this change doesn't affect other repos that depend on TiDB.

**Comment by zhexuany** [comment]
I did not consider this. closing this PR.

**Pull request closed without merging**
