### PR TITLE
store/tikv: increase batch split region limit

### PR DESCRIPTION
**Pull request by nolouch**
Signed-off-by: nolouch <nolouch@gmail.com>

### What problem does this PR solve?

Ref: https://github.com/pingcap/tidb/issues/22969
Problem Summary:
Splitting and Scattering at the same time will cause multiple conflicts on the same region.
image

### What is changed and how it works?

How it Works: increase the split regions' limit in 4.0.

### Check List 

Tests 

- Make the time consuming of `split table` more stable 
```
I have run multiple times  to split 4000 regions, and the time is stale about `1m30s`
split single sql result: [map[SCATTER_FINISH_RATIO:1 TOTAL_SPLIT_REGION:2001]]
split all sql run total cost: 1m28.908304306s
split all sql run success!!!
```
### Release note 

- Increasing the split region limit makes the `split table` and `pre split` more stable

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]
/lgtm

**Pull request merged**
