### PR TITLE
store/tikv: do not backoff when PessimisticLock return locked error (#13110)

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry-pick https://github.com/pingcap/tidb/pull/13110

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @coocood @lysu

**Comment by coocood** [comment]
LGTM

**Comment by coocood** [comment]
@cfzjywxk PTAL

**Comment by cfzjywxk** [comment]
LGTM

**Pull request merged**
