### PR TITLE
*: remove returning error of RollbackTxn

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve? 
It is hard to handle the error of `RollbackTxn`, mostly we print a log for it.

### What is changed and how it works?
The error is not necessary for `RollbackTxn`, just remove it.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

### CODE REVIEW

**Comment by tiancaiamao** [comment]
I guess tidb-test should be update...

/run-all-tests

**Comment by jackysp** [comment]
PTAL @tiancaiamao

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
