### PR TITLE
executor: support forbid tiflash for stale read (#25828)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25828 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25985
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25985:release-5.1-59d835eac5ed
```

---

Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/25827

Problem Summary:

see issue

### What is changed and how it works?
Support statement read flag in statement context and forbid tiflash during stale read in planner

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]
/mege

**Pull request merged**
