### PR TITLE
parser: make some char constant do not restore with charset prefix

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23027

Problem Summary:

https://github.com/pingcap/tidb/pull/20347 has been cherry-picked to release-4.0. But its related PR in `parser` does not. it causes the problem.
https://github.com/pingcap/parser/pull/1180 do the cherry-pick job in `parser`

### Check List 

Tests 

- Unit test

### Release note 

- fix create view success but failed when using it

### CODE REVIEW

**Review by AilinKid — COMMENTED** [review]
/lgtm

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
