### PR TITLE
executor: explain analyze panic when processing `explain analyze insert ... select ...` 

### LINKED ISSUE #11036: explain analyze panic when insert select
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
mysql> create table test (i int);
Query OK, 0 rows affected (0.01 sec)

mysql> explain analyze insert into test select 1;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

2. What did you expect to see?
I think insert is not supported by explain analyze, so it should return an error. Or we could explain the select part for this SQL.

3. What did you see instead?
Got a panic
```
[2019/07/02 20:32:34.950 +08:00] [ERROR] [conn.go:599] ["connection running loop panic"] [conn=390] [lastCmd="explain analyze insert into t1 select 1"] [err="\"invalid memory address or nil pointer dereference\""] [stack="goroutine 13837 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x56d4040, 0xc060035020, 0xc000193ad0)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:597 +0xee\npanic(0x52076e0, 0x6742740)\n\t/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset.func1(0x0, 0x56e6220, 0xc05afd6460, 0xc003fa3778, 0x56d4040, 0xc060035020, 0xc000193ad0)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:1255 +0x5a9\npanic(0x52076e0, 0x6742740)\n\t/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5\ngithub.com/pingcap/tidb/session.(*TxnState).SetOption(0xc1425c32d0, 0x1, 0x0, 0x0)\n\t<autogenerated>:1 +0x2e\ngithub.com/pingcap/tidb/executor.(*InsertValues).addRecord(0xc0001528c0, 0xc0a5cdc840, 0x1, 0x1, 0xc1425c32d0, 0x0, 0xc03d1b4ba0)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/insert_common.go:582 +0x221\ngithub.com/pingcap/tidb/executor.(*InsertExec).exec(0xc03d1b4b70, 0x56d4040, 0xc060035020, 0xc000696000, 0x1, 0x20, 0x0, 0x0)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/insert.go:71 +0x167\ngithub.com/pingcap/tidb/executor.(*InsertValues).insertRowsFromSelect(0xc0001528c0, 0x56d4040, 0xc060035020, 0xc003fa33b8, 0x0, 0x0)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/insert_common.go:339 +0x622\ngithub.com/pingcap/tidb/executor.(*InsertExec).Next(0xc03d1b4b70, 0x56d4040, 0xc060035020, 0xc03d1b4c60, 0x0, 0xc003fa34b0)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/insert.go:139 +0xf4\ngithub.com/pingcap/tidb/executor.(*ExplainExec).generateExplainInfo(0xc05b5d00b0, 0x56d4040, 0xc060035020, 0xc003fa3470, 0x60, 0x70, 0x40e2748, 0xc0000c6008)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/explain.go:77 +0x154\ngithub.com/pingcap/tidb/executor.(*ExplainExec).Next(0xc05b5d00b0, 0x56d4040, 0xc060035020, 0xc03d1b4c00, 0x4, 0xc09a8fff18)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/explain.go:52 +0x42e\ngithub.com/pingcap/tidb/executor.Next(0x56d4040, 0xc060035020, 0x56da380, 0xc05b5d00b0, 0xc03d1b4c00, 0x0, 0x0)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/executor.go:198 +0x119\ngithub.com/pingcap/tidb/executor.(*recordSet).Next(0xc05afd6410, 0x56d4040, 0xc060035020, 0xc03d1b4c00, 0xc05afd6410, 0xc03d1b4c00)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/adapter.go:104 +0x5a\ngithub.com/pingcap/tidb/server.(*tidbResultSet).Next(0xc05afd6460, 0x56d4040, 0xc060035020, 0xc03d1b4c00, 0x4, 0x400)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/driver_tidb.go:365 +0x51\ngithub.com/pingcap/tidb/server.(*clientConn).writeChunks(0xc000193ad0, 0x56d4040, 0xc060035020, 0x56e6220, 0xc05afd6460, 0xc000003700, 0x56d4040, 0xc060035020)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:1302 +0x319\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc000193ad0, 0x56d4040, 0xc060035020, 0x56e6220, 0xc05afd6460, 0xc000001f00, 0x0, 0x0, 0x0)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:1268 +0x1a1\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc000193ad0, 0x56d4040, 0xc060035020, 0xc04239ec61, 0x27, 0x0, 0x0)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:1185 +0x212\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch(0xc000193ad0, 0x56d4040, 0xc060035020, 0xc04239ec61, 0x28, 0x28, 0x0, 0x0)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:895 +0x5c6\ngithub.com/pingcap/tidb/server.(*clientConn).Run(0xc000193ad0, 0x56d4040, 0xc060035020)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:650 +0x258\ngithub.com/pingcap/tidb/server.(*Server).onConn(0xc0007c7280, 0xc000193ad0)\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/server.go:441 +0x481\ncreated by github.com/pingcap/tidb/server.(*Server).Run\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/server.go:358 +0x75d\n"] [stack="github.com/pingcap/tidb/server.(*clientConn).Run.func1\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:599\nruntime.gopanic\n\t/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset.func1\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:1255\nruntime.gopanic\n\t/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522\nruntime.panicmem\n\t/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:82\nruntime.sigpanic\n\t/usr/local/Cellar/go/1.12.6/libexec/src/runtime/signal_unix.go:390\ngithub.com/pingcap/tidb/session.(*TxnState).SetOption\n\t<autogenerated>:1\ngithub.com/pingcap/tidb/executor.(*InsertValues).addRecord\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/insert_common.go:582\ngithub.com/pingcap/tidb/executor.(*InsertExec).exec\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/insert.go:71\ngithub.com/pingcap/tidb/executor.(*InsertValues).insertRowsFromSelect\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/insert_common.go:339\ngithub.com/pingcap/tidb/executor.(*InsertExec).Next\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/insert.go:139\ngithub.com/pingcap/tidb/executor.(*ExplainExec).generateExplainInfo\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/explain.go:77\ngithub.com/pingcap/tidb/executor.(*ExplainExec).Next\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/explain.go:52\ngithub.com/pingcap/tidb/executor.Next\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/executor.go:198\ngithub.com/pingcap/tidb/executor.(*recordSet).Next\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/executor/adapter.go:104\ngithub.com/pingcap/tidb/server.(*tidbResultSet).Next\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/driver_tidb.go:365\ngithub.com/pingcap/tidb/server.(*clientConn).writeChunks\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:1302\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:1268\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:1185\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:895\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/conn.go:650\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/Users/yusp/work/goprojects/src/github.com/pingcap/tidb/server/server.go:441"]
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
ff82b62b973915b0820d1bfcec2e4aa0a1986437

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve? 
Fix #11036;
Panic when processing `explain analyze insert ... select ...`;

### What is changed and how it works?
SQLs like `explain analyze insert ...` should be handled in a no-delayed manner, since there is write operation in it. 

But All explain statements are handled in a delayed manner now because we don't check `ExplainExec` rightly when handing no delayed executors.

In this PR, we check:
1. if the explain-executor has an analyze flag, and
2. if the internal executor of the explain-executor should be handled in a no-delayed manner;

If all conditions 1) and 2) are true, we should handle this explain without delay. 

This PR should be merged after https://github.com/pingcap/parser/pull/381.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by qw4990** [comment]
After `git rebase` to the latest master branch without any change, all CI problems have been resolved, and please approve this PR again. @lysu @jackysp

**Comment by cyliu0** [comment]
@qw4990 Do we need to cherry pick this one to release-3.1? And it has been labeled with `needs-cherry-pick-3.0`, plz cherry pick it to release-3.0

**Pull request merged**
