### PR TITLE
executor: remove useless code for cte

### LINKED ISSUE #31029: Remove useless code for CTE.iterOutTbl
## Enhancement
https://github.com/pingcap/tidb/blob/5ea46eaf22b8ac8529f29bf95c4aa903ea11c5f1/executor/builder.go#L4619

unexpected new variable

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #31029

Problem Summary: Got some useless code for initialization of `cte.iterOutTbl` . 

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]

**Comment by guo-shaoge** [comment]
Will be fixed in #31256

**Pull request closed without merging**
