### PR TITLE
planner/core: derive `StatsInfo` lazily.

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve? 

Join reorder will call `deriveStats`. So make `deriveStats` lazy to reduce the stats building cost.

Note: in this way, join reorder should be the last rule of Logical Optimization.

### What is changed and how it works?

Add the following code of each `deriveStats` method
```
	if p.stats != nil {
		return p.stats, nil
	}
```

Also, i removed all `err.Trace` function call in `stats.go`.

### Check List 

Tests 

 - existing tests.

### CODE REVIEW

**Comment by eurekaka** [comment]
> Note: in this way, join reorder should be the last rule of Logical Optimization.

BTW, this seems make join reorder harder to be integrated with new Cascades planner?

**Comment by winoros** [comment]
@eurekaka Yeah, how to integrated join reorder into cascade optimizer is still in draft status. I'll open a discussion about it later.

**Pull request merged**
