### PR TITLE
go.mod: update parser to fix panic on connection verification #23532

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Cherry-pick https://github.com/pingcap/tidb/pull/23532 to the release 4.0 branch

### Release note 

- No release note

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
Looks good to me.

**Comment by tiancaiamao** [comment]
The HEAD of the 4.0 branch now use `20210303062609-d1d977c9ceed`, so it should have used the updated parser.
This PR is not needed any more.

**Pull request closed without merging**
