### PR TITLE
parser: parse "select 1 order by 1" statement

### PR DESCRIPTION
**Pull request by qazbnm456**
This is the valid grammar that can be parsed by MySQL: http://sqlfiddle.com/#!9/9eecb/14389. Therefore, I add lines of code and some tests in this PR. 😄

### CODE REVIEW

**Comment by shenli** [comment]
@qazbnm456 Thanks! Please fix the CI.

**Comment by qazbnm456** [comment]
@shenli Thanks, I'll try to fix that CI. 😕

**Comment by qazbnm456** [comment]
@shenli CI is happy now. PTAL. 😃

**Comment by shenli** [comment]
@qazbnm456 Great!

**Comment by shenli** [comment]
LGTM
@coocood @tiancaiamao @winkyao PTAL

**Pull request merged**
