### PR TITLE
store: avoid sessions of GC being affected by global variables (#24975)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #24975 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25449
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25449:release-5.1-47f6ba21f441
```

---

Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/24976

Problem Summary:
The sessions of GC will be affected by global variables, if the user `set global autocommit = 0`, then `saveValueToSysTable` will not commit the transaction automatically, which will make the safe point could not go forward.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
`se.GetSessionVars().CommonGlobalLoaded = true` for the sessions of GC.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
1. start a cluster
2. `set global autocommit = 0`
3. `show status` or `select variable_value from mysql.tidb where variable_name = 'tikv_gc_safe_point';` to check the safe point go forward or not.

### Release note 

- avoid sessions of GC being affected by global variables

### CODE REVIEW

**Review by jackysp — APPROVED** [review]
LGTM

**Comment by jackysp** [comment]
PTAL @lysu @MyonKeminta

**Review by MyonKeminta — APPROVED** [review]

**Comment by lysu** [comment]
@zhouqiang-cl please help give a label

**Pull request merged**
