### PR TITLE
*: set charset and collate for string literals correctly

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve? 
Make constant get the right charset and collation. Related PR: [#761](https://github.com/pingcap/parser/pull/761)

### What is changed and how it works?
In NewValueExpr, set the charset and collate for string literals.
The charset and collate are from parser, which is the connection charset and connection collation.
See also https://dev.mysql.com/doc/refman/8.0/en/charset-literal.html

### Check List 

Tests 

 
 - Integration test

Code changes

 - Has interface methods change

Side effects

Related changes

Release note

### CODE REVIEW

**Comment by bb7133** [comment]
Please notice that word "literal" is an adjective.

**Comment by wjhuang2016** [comment]
> Please notice that word "literal" is an adjective.

Thanks, already fixed.

**Comment by bb7133** [comment]
Please deal with the conflict files.

**Pull request merged**
