### PR TITLE
executor: let select into outfile has affected rows return

### LINKED ISSUE #31131: When execute select into outfile, affected rows always show 0
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Execute following sql:
```mysql
select * from mysql.tidb into outfile '/tmp/test.csv';
```

### 2. What did you expect to see? (Required)
`Query OK, 4 rows affected`

### 3. What did you see instead (Required)
`Query OK, 0 rows affected`

### 4. What is your TiDB version? (Required)
master branch

### PR DESCRIPTION
**Pull request by AndrewDi**
### What problem does this PR solve?

Issue Number: close #31131

Problem Summary:

After write chunk to file, update affected rows.

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
Support "Affected Rows" for `SELECT ... OUTFILE` grammer.
```

### CODE REVIEW

**Comment by zhouqiang-cl** [comment]
CI Fail
```
1-12-29T10:33:25.824Z] ----------------------------------------------------------------------
[2021-12-29T10:33:25.824Z] FAIL: select_into_test.go:101: testSuite1.TestSelectIntoOutfileFromTable
[2021-12-29T10:33:25.824Z] 
[2021-12-29T10:33:25.824Z] select_into_test.go:119:
[2021-12-29T10:33:25.824Z]     c.Assert(tk.Se.GetSessionVars().StmtCtx.AffectedRows(), Equals, 4)
[2021-12-29T10:33:25.824Z] ... obtained uint64 = 0x4
[2021-12-29T10:33:25.824Z] ... expected int = 4
```
in https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_unit_test/runs/27668/nodes/52/steps/57/log/?start=0

**Comment by AndrewDi** [comment]
@zhouqiang-cl already fix it

**Review by tiancaiamao — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
