### PR TITLE
store/tikv: add and fix some metrics for the new retry logic (#25123)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25123 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25212
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25212:release-5.1-840494dc1380
```

---

### What is changed and how it works?

The exit cause of the replica selector is recorded in the metrics. The retry time of a request is recorded in a histogram.

The commit backoff time is improved. Because prewrite is mostly parallel, we only record the max total sleep of all backoffs in prerwite. (But this is not the real time spent on prewrite because of the concurrency limit.)

The backoff time of the commit phase is not counted in the batch executor. `commitTxn` adds the time to the final commit backoff time.

### Check List 

Tests 

- No code

### Release note 

- `No release note`

### CODE REVIEW

**Comment by lysu** [comment]
@zhouqiang-cl it seems 5.1 branch doesn't use Go 1.16~?

**Comment by zhouqiang-cl** [comment]
> @zhouqiang-cl it seems 5.1 branch doesn't use Go 1.16~?

we are working on it now

**Review by lysu — APPROVED** [review]

**Review by youjiali1995 — APPROVED** [review]

**Pull request merged**
