### PR TITLE
misc: Upgrade failpoint to support golang 1.16

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?
What's Changed:
Upgrade failpoint to support golang 1.16

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 
- No code

Side effects

- No
### Release note 

- Upgrade failpoint to support golang 1.16

### CODE REVIEW

**Comment by wjhuang2016** [comment]
lgtm

**Comment by winoros** [comment]
Hope it can be merged into 5.0...
I don't want to build the failpoint by hand every time...

**Comment by winoros** [comment]
@blacktear23 Seems your changes is wrongly cleaned up?

**Comment by winoros** [comment]
Oh, some pr updated the failpoint yesterday.

**Comment by blacktear23** [comment]
> Oh, some pr updated the failpoint yesterday.

Shall I just close this PR?

**Comment by blacktear23** [comment]
other pr already update failpoint，just close this one

**Pull request closed without merging**
