### PR TITLE
server: use max_allowed_packet to limit the packet size.

### LINKED ISSUE #31422: max_allowed_packet length is set to 1024 but its not working for string length.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set global max_allowed_packet=100;
set global net_buffer_length=100;  # change session
select @@net_buffer_length, @@max_allowed_packet;
SELECT length("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") as len;

```
### 2. What did you expect to see? (Required)
```sql
mysql> select @@net_buffer_length, @@max_allowed_packet;
+---------------------+----------------------+
| @@net_buffer_length | @@max_allowed_packet |
+---------------------+----------------------+
|                1024 |                 1024 |
+---------------------+----------------------+
1 row in set (0.00 sec)

mysql> SELECT length("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") as len;
ERROR 1153 (08S01): Got a packet bigger than 'max_allowed_packet' bytes
```
### 3. What did you see instead (Required)
```sql
mysql> select @@net_buffer_length, @@max_allowed_packet;
+---------------------+----------------------+
| @@net_buffer_length | @@max_allowed_packet |
+---------------------+----------------------+
| 100                 |                 1024 |
+---------------------+----------------------+
1 row in set (0.00 sec)

mysql> SELECT length("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") as len;
+------+
| len  |
+------+
| 1024 |
+------+
1 row in set (0.00 sec)

```
### 4. What is your TiDB version? (Required)

```sql
| Release Version: v5.5.0-alpha-21-g722303bca-dirty
Edition: Community
Git Commit Hash: 722303bca8d279ff7c9d87e942095d320499f47e
Git Branch: master
UTC Build Time: 2022-01-05 19:11:01
GoVersion: go1.16.9
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

```

### PR DESCRIPTION
**Pull request by CbcWestwolf**
### What problem does this PR solve?

Issue Number: close #31422

Problem Summary:

The `max_allowed_packet` exists but did not work on previous versions.

### What is changed and how it works?

Check the length of `data` in `dispatch` function.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by dveeden — CHANGES_REQUESTED** [review]
On first glance this looks wrong to me. It looks like a full packet is read and then discarded if it is bigger than `max_allowed_packet`. I think the right thing is abort before reading a packet that is too large.

In `readOnePacket()` the reading is done in two steps, it first reads the header and then gets the `length` from the header. I think this is where we should check for `max_allowed_packet`.

https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_basic_packets.html#sect_protocol_basic_packets_packet for how the header looks.

Looks like data of >16MiB might be send with multiple packets. If that's indeed the case we should bail out as soon as the buffer is more than `max_allowed_packet`. But we should also verify what MySQL does in this case... does it allow say a 512M blob to be sent multiplexed over multiple 8MiB packets? https://dev.mysql.com/doc/c-api/8.0/en/mysql-stmt-send-long-data.html might allow one to do that.

**Comment by dveeden** [comment]
Looks like the behavior between TiDB and MySQL 8.0 is slightly different:
```
[dvaneeden@dve-carbon ~]$ ./max_allowed_packet.py 
Using 127.0.0.1:4000
  Testing with REPEAT("x", 100)
  Testing with client side payload of 100)
  Testing with REPEAT("x", 8192)
  Testing with client side payload of 8192)
  Testing with REPEAT("x", 16384)
  Testing with client side payload of 16384)
    Insert failed: 2013 (HY000): Lost connection to MySQL server during query
  Database connection failure on ping(): Connection to MySQL is not available
  Forcing reconnection
  Testing with REPEAT("x", 3232768)
    Insert failed: 1301 (HY000): Result of repeat() was larger than max_allowed_packet (16385) - truncated
  Testing with client side payload of 3232768)
    Insert failed: 2013 (HY000): Lost connection to MySQL server during query
Using 127.0.0.1:8028
  Testing with REPEAT("x", 100)
  Testing with client side payload of 100)
  Testing with REPEAT("x", 8192)
  Testing with client side payload of 8192)
  Testing with REPEAT("x", 16384)
  Testing with client side payload of 16384)
    Insert failed: 1153 (08S01): Got a packet bigger than 'max_allowed_packet' bytes
  Database connection failure on ping(): Connection to MySQL is not available
  Forcing reconnection
  Testing with REPEAT("x", 3232768)
    Insert failed: 1301 (HY000): Result of repeat() was larger than max_allowed_packet (16384) - truncated
  Testing with client side payload of 3232768)
    Insert failed: 1153 (08S01): Got a packet bigger than 'max_allowed_packet' bytes
```

The contents of `max_allowed_packet.py `:

```python3
#!/bin/python3
import mysql.connector

configs = [
    {
        "host": "127.0.0.1",
        "port": 4000,
        "user": "root",
        "database": "test",
    },
    {
        "host": "127.0.0.1",
        "port": 8028,
        "user": "msandbox",
        "password": "msandbox",
        "database": "test",
    },
]

for config in configs:
    print(f"Using {config['host']}:{config['port']}")
    con = mysql.connector.connect(**config)
    c = con.cursor()
    c.execute("DROP TABLE IF EXISTS t1")
    c.execute(
        "CREATE TABLE t1 (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, payload LONGBLOB)"
    )
    c.execute("SET GLOBAL max_allowed_packet=16385")

    for size in [100, 8192, 16384, 3232768]:
        try:
            con.ping()
        except mysql.connector.Error as e:
            print(f"  Database connection failure on ping(): {e}")
            print(f"  Forcing reconnection")
            con.ping(reconnect=True)

        try:
            print(f'  Testing with REPEAT("x", {size})')
            c.execute(f'INSERT INTO t1(payload) VALUES (REPEAT("x", {size}))')
            con.commit()
        except mysql.connector.Error as e:
            print(f"    Insert failed: {e}")

        try:
            con.ping()
        except mysql.connector.Error as e:
            print(f"  Database connection failure on ping(): {e}")
            print(f"  Forcing reconnection")
            con.ping(reconnect=True)

        try:
            print(f"  Testing with client side payload of {size})")
            c.execute("INSERT INTO t1(payload) VALUES(%s)", ("y" * size,))
            con.commit()
        except mysql.connector.Error as e:
            print(f"    Insert failed: {e}")

    c.close()
    con.close()
```

**Comment by dveeden** [comment]
With MYSQL 8.0.28:
```
mysql> set global max_allowed_packet=16385;
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-------------------------------------------------------+
| Level   | Code | Message                                               |
+---------+------+-------------------------------------------------------+
| Warning | 1292 | Truncated incorrect max_allowed_packet value: '16385' |
+---------+------+-------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select @@global.max_allowed_packet;
+-----------------------------+
| @@global.max_allowed_packet |
+-----------------------------+
|                       16384 |
+-----------------------------+
1 row in set (0.00 sec)
```

**Comment by CbcWestwolf** [comment]
@dveeden This PR is closed when I did a force-push operation. So I create another PR #33651 with the same code.

Now the truncation of `max_allowed_packet` is implemented. And the behavior between TiDB and MySQL 8.0 using your Python script is the same.

PTAL. Thank you!

**Pull request closed without merging**
