### PR TITLE
tidb: minor typo corrections

### PR DESCRIPTION
**Pull request by nieyy**
First attempt trying to be a Tidb contributor, :)

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Comment by coocood** [comment]
Thank you for your contribution!

**Comment by nieyy** [comment]
Welcome, :), we have several members working on using TiDB as a MySQL-compatible distributed SQL engine for our own storage, will have more contributions later.

**Comment by shenli** [comment]
@nieyy Happy to hear that!

**Comment by c4pt0r** [comment]
@nieyy  Cool, looking forward!

**Pull request merged**
