### PR TITLE
variable: make backoff weight could be 0

### LINKED ISSUE #32592: Make TiDB to report errors quickly
## Enhancement
TiDB always uses backoff to resolve some internal errors, e.g., node failures, but in some cases a fast failure may be a better choice because it will give the user a clear ack quickly, rather than looking like it hung.

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close #32592

Problem Summary:
TiDB always uses backoff to resolve some internal errors, e.g., node failures, but in some cases a fast failure may be a better choice because it will give the user a clear ack quickly, rather than looking like it hung.

### What is changed and how it works?
Allow `tidb_backoff_weight` to be set to 0 to turn off backoff mechanism.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. run some sysbench benchmark on a cluster and `set global tidb_backoff_weight = 0`
2. the cluster run as normal with no node failure.
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by djshow832 — COMMENTED** [review]
Please add tests to verify that the retrying mechanism still works fine when the weight is set to 0.

**Comment by jackysp** [comment]
PTAL @djshow832 @bb7133

**Comment by jackysp** [comment]
PTAL @djshow832 @bb7133

**Review by morgo — APPROVED** [review]

**Pull request merged**
