### PR TITLE
ddl: add check when create table with foreign key. (#7885)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
cherry-pick from #7885.

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8410)

### CODE REVIEW

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.0 pd=release-2.0 tikv=release-2.0

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.0 pd=release-2.0 tikv=release-2.0

**Comment by crazycs520** [comment]
@zimulala @winkyao @ciscoxll PTAL

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.0 pd=release-2.0 tikv=release-2.0

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.0 pd=release-2.0 tikv=release-2.0

**Comment by zz-jason** [comment]
LGTM

**Pull request merged**
