### PR TITLE
lightning: fix unstable test for conflict detection

### PR DESCRIPTION
**Pull request by lyzx2001**
### What problem does this PR solve?

Issue Number: ref #52306 

Problem Summary:

### What changed and how does it work?
Fix unstable test for lightning_duplicate_resolution_merge.
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_lightning_integration_test/detail/pull_lightning_integration_test/691/pipeline/

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
please find the root cause rather than remove the test. There should be PK of 1,2,3,4,5,6,13,14,15,16 which is 10 records.

**Comment by lyzx2001** [comment]
> please find the root cause rather than remove the test. There should be 10 records of PK 1,2,3,4,5,6,13,14,15,16.

In log we can see that lightning 2 exited at 16:21:41.696, but lightning 1 met error "Table "lightning_metadata.task_meta_v2' doesn't exist" at 16:21:41.702, where we may infer lightning 2 deleted the table too soon. So the solution can be manually adding sleep time to extend the import time.

**Review by lance6716 — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]

**Pull request merged**
