### PR TITLE
store/tikv, config: increase pessimistic lock ttl

### PR DESCRIPTION
**Pull request by coocood**
### What problem does this PR solve? 
Make the pessimistic transactions less likely to timeout.

### What is changed and how it works?
- Increase pessimistic TTL hard limit to 120s
- Increase default pessimistic TTL to 40s
- Add elapsed time to TTL when LockKeys is called for the first time.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by coocood** [comment]
@jackysp @lysu @tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
