### PR TITLE
sessionctx/variable: fix range check for @@timestamp

### LINKED ISSUE #31585: Tidb SET TIMESTAMP=3147483698 out of range is not compatible with mysql.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
SET TIMESTAMP=3147483698;
SELECT UTC_TIMESTAMP();
```

### 2. What did you expect to see? (Required)
```sql
mysql> SET TIMESTAMP=3147483698;
ERROR 1231 (42000): Variable 'timestamp' can't be set to the value of '3147483698'
-- Retain previously set  timestamp
```
### 3. What did you see instead (Required)
```sql
mysql> SET TIMESTAMP=3147483698;
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> SELECT UTC_TIMESTAMP();
+---------------------+
| UTC_TIMESTAMP()     |
+---------------------+
| 2038-01-19 03:14:07 |
+---------------------+
1 row in set (0.00 sec)
-- Just a warning and resetting timestamp to max value
```
### 4. What is your TiDB version? (Required)

```sql
| Release Version: v5.4.0-alpha-264-g6efa36df6
Edition: Community
Git Commit Hash: 6efa36df6cff325106f67ecfe3d79816ba37ca6a
Git Branch: master
UTC Build Time: 2021-12-28 02:03:55
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve?

Issue Number: close #31585

Problem Summary:

### What is changed and how it works?

This PR generally follows the [suggestion](https://github.com/pingcap/tidb/issues/31585#issuecomment-1010515766) from @morgo in #31585.

### Check List

Tests 

- [x] Unit test
- [x] Manual test (add detailed scripts or steps below)
As shown in #31585:

```
mysql> SET TIMESTAMP=3147483698;
ERROR 1231 (42000): Variable 'timestamp' can't be set to the value of '3147483698'
-- Retain previously set  timestamp
```

Side effects

- [x] Performance regression: Consumes more CPU
- [x] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [x] Contains variable changes
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that when setting a timestamp that is larger than `MAXINT32`, TiDB doesn't report an error like MySQL.
```

### CODE REVIEW

**Comment by bb7133** [comment]
PTAL @morgo @CbcWestwolf @xhebox

**Review by ngaut — APPROVED** [review]

**Review by CbcWestwolf — APPROVED** [review]

**Review by morgo — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
