### PR TITLE
docs: change all the MySQL version from 5.7.10 to 5.7.25

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve? 
Change all the MySQL version from 5.7.10 to 5.7.25.
related PR: https://github.com/pingcap/parser/pull/231

### What is changed and how it works?
N/A

### Check List 

Tests 

 - Manual test
Start a new tidb-server and connect to it from MySQL-client:
```
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.7.25-TiDB-v3.0.0-beta-152-g5ad33c88d-dirty MySQL Community Server
(Apache License 2.0)
...
```

Code changes

N/A

Side effects

Related changes

N/A

### CODE REVIEW

**Comment by zz-jason** [comment]
LGTM

Please fix `go mod tidy`

**Comment by jackysp** [comment]
This case `testInnodbTablespaceEncryption` failed in jdbc test.
Because we upgrade the version and this check passed,
```
if (!versionMeetsMinimum(5, 7, 11)) {
            return;
}
```
but, TiDB doesn't support
```
CREATE TABLE testInnodbTablespaceEncryption (id INT) ENCRYPTION='y'
```
this statement.

**Pull request merged**
