### PR TITLE
executor: fix wrong convert from bit to string when do projection

### LINKED ISSUE #23287: union bit column got different result between clustered and nonclustered table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(k1 int, v bit(34) DEFAULT b'111010101111001001100111101111111', primary key(k1) clustered);
create table t1(k1 int, v bit(34) DEFAULT b'111010101111001001100111101111111', primary key(k1) nonclustered);
insert into t(k1) select 1;
insert into t1(k1) select 1;
```

```
(select * from t where false) union(select * from t for update);
(select * from t1 where false) union(select * from t1 for update);
```

### 2. What did you expect to see? (Required)

get same result

### 3. What did you see instead (Required)

```
MySQL [test]> (select * from t where false) union(select * from t for update);
+----+----+-------+
| k1 | k3 | v     |
+----+----+-------+
|  1 |  2 | ���    |
+----+----+-------+

MySQL [test]> (select * from t1 where false) union(select * from t1 for update);
+----+----+------------+
| k1 | k3 | v          |
+----+----+------------+
|  1 |  2 | 7883509631 |
+----+----+------------+
```

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #23287 

Problem Summary: Results of same SQL for different tables(one with clusted index, another is not) are different. 
Why: see my comments in issue page.

### What is changed and how it works?

What's Changed: When do `Projection` for bit column, will not convert it to string. So the `HashAgg` exec can see the origin bit value instead string value which is converted by `Projection` exec.

But it will affects `coalesce(col_bit)`, it's a bug of MySQL, no need to be compatible with MySQL. [coalesce(col_bit) bug report](https://bugs.mysql.com/bug.php?id=103289&thanks=4)
### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects: no

### Release note 

- fix wrong convert from bit to string when do projection

### CODE REVIEW

**Review by lzmhhh123 — APPROVED** [review]

**Comment by guo-shaoge** [comment]
/need-cherry-to-5.0

**Pull request merged**
