### PR TITLE
*: remove SchemaVersion in TransactionContext

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

The main issue: #24233 

Problem Summary: Follow #24230, the bug is that when `set @@tidb_snapshot="xxxx"`, `SchemaVersion` is not updated to the old schema version.

Since the update of `SchemaVersion` and `InfoSchema` is messy(there are multiple setters for `Infoschema`, `SchemaVersion` and `SnapshotInfoschema`), I removed `SchemaVersion` completely and rely on the previous `GetInfoSchema`(which will get snapshot if there is one, then the current schema) to retrieve schema version.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- Another fix for ineffectual tidb_snapshot in some cases

### CODE REVIEW

**Comment by bb7133** [comment]
Please resolve the conflicts @xhebox .

**Comment by xhebox** [comment]
/hold
should merge #24230 first, conflicts will be resolved later, @bb7133

**Comment by xhebox** [comment]
Have merged the previous PR, continue to merge
/merge

**Pull request merged**
