### PR TITLE
mocktikv: avoid sorting multiple times with unstable order

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/15767

Problem Summary:
The all tuples in TopN doesn't to be sorted multiple times but resulting into unstable order, so Next() does not fetch all tuples in the same order.

### What is changed and how it works?
after all tuples from its child are fetched, sort them immedrately. Then fetch data from the ordered data. 

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
Do we need to cherry-pick this to 2.1, 3.0, 3.1, 4.0 ?

**Comment by fzhedu** [comment]
/run-unit

> Do we need to cherry-pick this to 2.1, 3.0, 3.1, 4.0 ?

yes

**Pull request merged**
