### PR TITLE
server: ConnectionEvent error from plugins should not make TiDB exit

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

When I am testing whitelist plugin, I find that whitelist check fail makes tidb exit. That completely unreasonable.

### What is changed and how it works?

`ConnectionEvent` error from plugins should not make TiDB exit

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

@lysu

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @jackysp

**Comment by gregwebs** [comment]
It looks like the error is completely discarded. Should it be logged first?

**Comment by tiancaiamao** [comment]
It's already logged here https://github.com/pingcap/tidb/pull/9889/files#diff-91bbeda7eb98a7adc57b9e47e2cf5c2bR346
@gregwebs

**Comment by gregwebs** [comment]
oh, good! It would be best to log the error where it is being dropped though.

**Pull request merged**
