### PR TITLE
*: refine panic log

### LINKED ISSUE #46852: The panic log doesn't contain the panic reason information
## Enhancement

same issue with https://github.com/tikv/client-go/issues/966

```log
[2023/09/08 15:02:56.261 +08:00] [ERROR] [client_batch.go:303] [batchSendLoop] [r={}] [stack="github.com/tikv/client-go/v2/internal/client.(*batchConn).batchSendLoop.func1 . . . 
```

I can't known the panic reason from the log, since `r={}`.

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: ref #46852

Problem Summary: refine panic log

### What is changed and how it works?

Following is a tiny test:

Before this PR:

```go
func TestLog(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			logutil.BgLogger().Warn("recover panic", zap.Reflect("r", r))
		}
	}()
	s := []int{}
	s[0] = 1
}
```

You will get the following log:

```log
[2023/09/11 14:36:19.797 +08:00] [WARN] [client_test.go:729] ["recover panic"] [r={}]
```

This PR, use `zap.Any` instead of `zap.Reflect`, You will get the following log:

```log
[2023/09/11 14:36:49.106 +08:00] [WARN] [client_test.go:729] ["recover panic"] [r="runtime error: index out of range [0] with length 0"]
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- N/A

Documentation

- N/A
### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by MyonKeminta — APPROVED** [review]

**Review by ekexium — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Review by you06 — APPROVED** [review]
Please also update client-go to include tikv/client-go#967

**Pull request merged**
