### PR TITLE
test: fix unstable TestIssue20658

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/24311 

Problem Summary: 

- The table structure is `create table t (a int, b int);`.
- The data contains 1000 records, each record is consist of 2 random number selected from `[0, 99]`.
- The query is `select /*+ stream_agg() */ samp_var(a) from t group by b;`

For the built-in function `samp_var()`, if there is only one element to aggregate, the result is `NULL`. The test `TestIssue20658` incorrectly assumes the result must be a float number.

### What is changed and how it works?

Allow the result to be "NULL".

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

NA

### Release note 

- No release note

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by AilinKid — COMMENTED** [review]
/lgtm

**Pull request merged**
