### PR TITLE
*: parse and ignore REPLICATION CLIENT/SLAVE, USAGE privileges in grant statement

### PR DESCRIPTION
**Pull request by tiancaiamao**
Fix https://github.com/pingcap/tidb/issues/4865

Parse `Replication Client`, `Replication Slave`, `Usage` privileges, but ignore them.
This change introduced `PrivilegeType(0)`, it need to be skipped somewhere.

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@coocood @winkyao PTAL

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
