### PR TITLE
planner: add a dedicated source file for plan cache

### LINKED ISSUE #36537: Add a source file for plan cache code
## Enhancement
In the past few versions，the code of plan cache is a little confusion and hard to read. We would like to refactor this part of TiDB and maybe add some new features, so we need a source file to  place our code.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #36537

Problem Summary: planner: add a dedicated source file for plan cache

### What is changed and how it works?

No logical change, just refactor:
1. add a dedicated source file for plan cache
2. decouple plan cache from `Execute`(exec-stmt)

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by qw4990** [comment]
Current existing test cases can cover this PR so I didn't introduce new tests.

**Review by Reminiscent — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
