### PR TITLE
expression: Add json_array push down support for tiflash

### LINKED ISSUE #48350: Support 'json_array' function push down to TiFlash
## Enhancement

https://dev.mysql.com/doc/refman/8.0/en/json-creation-functions.html
https://github.com/pingcap/tiflash/issues/8308

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #48350

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by SeaRise** [comment]
/hold
wait for https://github.com/pingcap/tiflash/pull/8329

**Comment by SeaRise** [comment]
> /hold wait for [pingcap/tiflash#8329](https://github.com/pingcap/tiflash/pull/8329)

merged.

**Review by windtalker — APPROVED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
