### PR TITLE
statistics: fix err check

### PR DESCRIPTION
**Pull request by Tjianke**
### What problem does this PR solve?

Issue Number:  #22979  

Problem Summary:

### What is changed and how it works?

What's Changed: added err check

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Review by djshow832 — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]
/lgtm

**Comment by tisonkun** [comment]
This pull request seems ready to merge. @Tjianke would you like to merge master and @djshow832 could you please trigger the merge process?

**Pull request merged**
