### PR TITLE
kv: make txn entry size limit configurable

### PR DESCRIPTION
**Pull request by bobotu**
### What problem does this PR solve?
Make txn entry size limit configurable

Due to the limitation in `memdb`, the upper limit of this option is set to 120Mb

### Release note 

-  make txn entry size limit configurable

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by coocood** [comment]
@bobotu failure is not random

**Comment by bobotu** [comment]
@coocood Fixed

**Pull request merged**
