### PR TITLE
*: fix rolling_update_fail when using Arrow format.

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve? 

In https://github.com/pingcap/tipb/pull/135 , I change the photo and use the same number to indicate it. It will cause a compatibility problem, and rolling_update will fail.

### What is changed and how it works?

Use a new number to indicate the new field.

### Check List 

Tests 

 - Integration test

Code changes

Side effects

Related changes

Release note

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
/run-all-tests tikv=release-3.0 tidb-test=release-3.0 pd=release-3.0

**Comment by wshwsh12** [comment]
/run-all-tests tikv=release-3.0 tidb-test=release-3.0 pd=release-3.0

**Comment by breeswish** [comment]
CI failed?

**Comment by XuHuaiyu** [comment]
@breeswish The fail case in CI has nothing to do with this commit.

**Pull request merged**
