### PR TITLE
ci: Delete circle.yml

### PR DESCRIPTION
**Pull request by tisonkun**
### What problem does this PR solve?

We don't use CircleCI any more. Even if we later move back to CircleCI, this script is far from up-to-date.

### Release note

```release-note
None
```

### CODE REVIEW

**Review by ngaut — APPROVED** [review]
LGTM

**Review by tangenta — APPROVED** [review]

**Comment by tisonkun** [comment]
Thanks for your review @ngaut & @tangenta ! Would you mind to trigger the merging phase?

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Pull request merged**
