### PR TITLE
parser: Make STATS_EXTENDED a non-reserved keyword.

### LINKED ISSUE #39573: `stats_extended` unexpectedly became a reserved word
## Bug Report

```
$ tiup playground v6.1.2 --db 2 --pd 3 --kv 3 --tiflash 2
```

```
$ tiup client ...

my:root@127.0.0.1:4000=> select 1,'stats_extended' as stats_extended from dual;
error: mysql: 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 44 near "stats_extended from dual;"

my:root@127.0.0.1:4000=> select 1,'stats_extended' as `stats_extended` from dual;
 1 | stats_extended
---+----------------
 1 | stats_extended
(1 row)

my:root@127.0.0.1:4000=> select * from mysql.stats_extended limit 10;
(0 rows)

my:root@127.0.0.1:4000=> use mysql;
USE

my:root@127.0.0.1:4000=> select * from stats_extended limit 10;
error: mysql: 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 29 near "stats_extended limit 10;"
```

### PR DESCRIPTION
**Pull request by wddevries**
### What problem does this PR solve?

Issue Number: close #39573

Problem Summary:
STATS_EXTENDED should not be a reserved keyword.

This patch adds STATS_EXTENDED to the TiDBKeyword list, and sets the precedence of STATS_EXTENDED to resolve shift/reduce conflicts between:

1. `"ADD" ColumnKeywordOpt IfNotExists ColumnDef ColumnPosition` and
2. `"ADD" "STATS_EXTENDED" IfNotExists Identifier StatsType '(' ColumnNameList ')'`

and between:

1. `"DROP" "STATS_EXTENDED" IfExists Identifier` and
2. `"DROP" ColumnKeywordOpt IfExists ColumnName RestrictOrCascadeOpt`

It also removes the following unused nonterminals:

- AssignmentListOpt
- ColumnDefList
- TableNameListOpt2
- CommaOpt

### Check List

Tests 

- [X] Unit test (for the parser package)
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [X] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
STATS_EXTENDED is no longer a reserved keyword.
```

### CODE REVIEW

**Review by mjonss — APPROVED** [review]
Looks good, please update the keywords by:
```
cd pkg/parser
make generate
make test
```
and update the failing test.
Note that there is a table INFORMATION_SCHEMA.KEYWORDS that should reflect the [Reserved] keywords.

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by easonn7** [comment]
/approve

LGTM, this behavior should be consistent with MySQL 
https://dev.mysql.com/doc/refman/8.4/en/keywords.html#keywords-new-in-current-series

**Pull request merged**
