### PR TITLE
metrics: update resource manager panel

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: ref #38825

Problem Summary:

### What is changed and how it works?
CPU time for per-query panel is unnecessary, so this pr removes per-query panel  and modify `SQL CPU panel`'s unit from `bits` to `ms`.
before
E7DrhE7h76

after
image

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by HuSharp** [comment]
@JmPotato @nolouch PLTA, thx!

**Comment by JmPotato** [comment]
> There is no need to keep per query panel, so this pr removes per query panel and modify SQL CPU unit from bits to ms

Maybe you mean the per-query panel for CPU times is unnecessary?

**Comment by HuSharp** [comment]
> Maybe you mean the per-query panel for CPU times is unnecessary?

Oh, it was a problem with my expression, it has been updated.

**Review by JmPotato — APPROVED** [review]

**Comment by HuSharp** [comment]
Can update the refresh metrics for 1 min.

**Comment by HuSharp** [comment]
@glorv @nolouch PTAL, thx!

**Review by glorv — APPROVED** [review]
LGTM

**Pull request merged**
