### PR TITLE
store/tikv: remove dependency on kv.StoreType

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?
remove dependency on kv.StoreType.

Part of https://github.com/pingcap/tidb/issues/22513

### What is changed and how it works?
What's Changed:
- add tikvrpc.EndpointType
- replace tikv.StoreType and kv.StoreType with tikvrpc.EndpointType
- add function to convert kv.StoreType to tikvrpc.EndpointType

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by AndreMouche — APPROVED** [review]
LGTM

**Review by sticnarf — APPROVED** [review]
/lgtm

**Pull request merged**
