### PR TITLE
executor: fix issue 5384 (#5414)

### PR DESCRIPTION
**Pull request by jackysp**
PTAL @shenli

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
/run-all-test -tidb-test=release-1.0 -tidb-private-test=release-1.0

**Comment by shenli** [comment]
/run-all-tests -tidb-test=release-1.0 -tidb-private-test=release-1.0

**Comment by jackysp** [comment]
I think tidb-test will be failed.

**Pull request merged**
