### PR TITLE
store/tikv: forward requests by BatchCommands

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?

Problem Summary:

Support forwarding requests by `BatchCommands`. Based on https://github.com/pingcap/tidb/pull/23362.

### What is changed and how it works?
What's Changed:

Create a `BatchCommands` for each forwarded host in a single connection.

How it Works:

### Related changes

* Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Review by tiancaiamao — COMMENTED** [review]
If "forwardedHost" is set, the request is sent to that host, instead of the node specified by the "addr"?

So why not simply modify the `SendRequest` function:

```
func (c *RPCClient) SendRequest(ctx context.Context, addr string, req *tikvrpc.Request, timeout time.Duration) (*tikvrpc.Response, error) {
     if req.ForwardedHost != nil {
        return originalSendRequest(ctx, req.ForwardedHost, ...)
     }
     originalSendRequest(ctx, addr, ...) 
}
```

Add  `forwardedClients map[string]*batchCommandsStream` to `batchCommandsClient`  to gain the ability to send requests to other(any) nodes looks weird.

**Comment by youjiali1995** [comment]
> If "forwardedHost" is set, the request is sent to that host, instead of the node specified by the "addr"?

No. The request is sent to the node with the address at "addr". If "forwardedHost" is set, the request will be forwarded to the "forwardedHost" by the node as a proxy, i.e. TiDB -> TiKV(addr) -> TiKV(forwardedHost) @tiancaiamao 

BTW, I will split this PR into 2. One is to forward requests by unary-calls and the second is to forward requests by BatchCommands. The second one lacks tests and I will add it today.

**Comment by tiancaiamao** [comment]
/LGTM

I have to point out that the complexity of supporting the batch mode maybe not worth its value.
There might be a huge burden for future maintenance work.

**Review by MyonKeminta — APPROVED** [review]
LGTM

**Comment by youjiali1995** [comment]
```
[2021-03-18T15:13:37.242Z] ----------------------------------------------------------------------
[2021-03-18T15:13:37.242Z] FAIL: simple_test.go:606: testSuite3.TestDropPartitionStats
[2021-03-18T15:13:37.242Z] 
[2021-03-18T15:13:37.242Z] simple_test.go:631:
[2021-03-18T15:13:37.242Z]     tk.MustExec("analyze table t")
[2021-03-18T15:13:37.242Z] /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:217:
[2021-03-18T15:13:37.242Z]     tk.c.Assert(err, check.IsNil, check.Commentf("sql:%s, %v, error stack %v", sql, args, errors.ErrorStack(err)))
[2021-03-18T15:13:37.242Z] ... value *errors.withStack = [stats]: some partition level statistics are not in statistics version 2, please set tidb_analyze_version to 2 and analyze the this table ("[stats]: some partition level statistics are not in statistics version 2, please set tidb_analyze_version to 2 and analyze the this table")
[2021-03-18T15:13:37.242Z] ... sql:analyze table t, [], error stack [stats]: some partition level statistics are not in statistics version 2, please set tidb_analyze_version to 2 and analyze the this table
[2021-03-18T15:13:37.242Z] github.com/pingcap/errors.AddStack
[2021-03-18T15:13:37.242Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174
[2021-03-18T15:13:37.242Z] github.com/pingcap/errors.Trace
[2021-03-18T15:13:37.242Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/juju_adaptor.go:15
[2021-03-18T15:13:37.242Z] github.com/pingcap/tidb/util/testkit.(*TestKit).Exec
[2021-03-18T15:13:37.242Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:176
[2021-03-18T15:13:37.242Z] github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec
[2021-03-18T15:13:37.242Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:216
[2021-03-18T15:13:37.242Z] github.com/pingcap/tidb/executor_test.(*testSuite3).TestDropPartitionStats
[2021-03-18T15:13:37.242Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/simple_test.go:631
[2021-03-18T15:13:37.242Z] reflect.Value.call
[2021-03-18T15:13:37.242Z] 	/usr/local/go/src/reflect/value.go:460
[2021-03-18T15:13:37.242Z] reflect.Value.Call
[2021-03-18T15:13:37.242Z] 	/usr/local/go/src/reflect/value.go:321
[2021-03-18T15:13:37.242Z] github.com/pingcap/check.(*suiteRunner).forkTest.func1
[2021-03-18T15:13:37.242Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850
[2021-03-18T15:13:37.242Z] github.com/pingcap/check.(*suiteRunner).forkCall.func1
[2021-03-18T15:13:37.242Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739
[2021-03-18T15:13:37.242Z] runtime.goexit
[2021-03-18T15:13:37.242Z] 	/usr/local/go/src/runtime/asm_amd64.s:1357
[2021-03-18T15:13:37.242Z] 
```

**Pull request merged**
