### PR TITLE
statistics: fix the panic when analyze with collation enabled (#21262)

### LINKED ISSUE #20874: clustered index + new collation + analyze panic
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```
mysql> show create table t;
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                                                                  |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` char(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `b` char(20) COLLATE utf8mb4_general_ci NOT NULL,
  `c` int(11) NOT NULL,
  PRIMARY KEY (`a`,`b`,`c`),
  KEY `idx` (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

insert into t values ('#', 'C', 10), ('$', 'c', 20), ('a', 'a', 10);

mysql> select * from t;
+---+---+----+
| a | b | c  |
+---+---+----+
| # | C | 10 |
| $ | c | 20 |
| a | a | 10 |
+---+---+----+
3 rows in set (0.00 sec)

mysql> analyze table t;
ERROR 1105 (HY000): analyze worker panic
```

### 2. What did you expect to see? (Required)
No panic
### 3. What did you see instead (Required)
Panic
### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

master

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21262 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #20874  

Problem Summary:

The histogram stores the sort key representation if there's collation. But we compare it as original string. This will compute the sort key from the sort key which would cause panic for some collation.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

Don't compuate the sort key again.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- Fix the panic when analyze with collation enabled

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Comment by bb7133** [comment]
@winoros Do we need this in 4.0, really?

**Review by XuHuaiyu — APPROVED** [review]

**Comment by winoros** [comment]
@bb7133 I fixed the issue description. The panic still exists without clustered index.

**Comment by winoros** [comment]
4.0 currently only has `utf8mb4_xxxx` collations, which would not cause panic.
The panic would be triggered by unicode collation or gb18030 collation. So close this pr first. Waiting for the problematic collation added to the 4.0 branch

**Comment by xiongjiwei** [comment]
the panic will be triggered by general ci collation now, we need to merge this PR. @winoros

**Review by winoros — APPROVED** [review]

**Comment by xiongjiwei** [comment]
this PR changes the `newCollationEnabled` variables but does not use the `SerialSuites`, please pay attention

**Pull request merged**
