### PR TITLE
br: refactor test to use wait checkpoint method

### LINKED ISSUE #57609: br: refactor test wait for checkpoint to advance
## Enhancement
currently every test is copying the same code block which is not tedious and unreadable, we can just make it a method

### PR DESCRIPTION
**Pull request by Tristan1900**
### What problem does this PR solve?

Issue Number: close #57609

Problem Summary:

### What changed and how does it work?

Extract the wait for checkpoint to advance logic in integration test to a method

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by BornChanger** [comment]
This is a good refactoring that follows the DRY (Don't Repeat Yourself) principle and makes the test codebase more maintainable.

**Review by BornChanger — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]

**Pull request merged**
