### PR TITLE
expression, planner: exclude concat_ws from aggresive folding constant

### LINKED ISSUE #36888: Unexpected Result by CONCAT_WS
## Bug Report

`CONCAT_WS(t0.c0, t1.c0)`  is evaluated `NULL` at the second SELECT and the first SELECT shows the result is not empty, so the third SELECT should not return empty result.

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);
INSERT INTO t0 VALUES (NULL);

SELECT t0.c0 FROM t0 LEFT JOIN t1 ON t0.c0>=t1.c0; -- {NULL}
SELECT CONCAT_WS(t0.c0, t1.c0) FROM t0 LEFT JOIN t1 ON t0.c0>=t1.c0; -- {NULL}
SELECT t0.c0 FROM t0 LEFT JOIN t1 ON t0.c0>=t1.c0 WHERE (CONCAT_WS(t0.c0, t1.c0) IS NULL); -- {}
```

### 2. What did you expect to see? (Required)
The third SELECT should return `NULL`.

### 3. What did you see instead (Required)
The third SELECT returns empty result.

### 4. What is your TiDB version? (Required)

| Release Version: v6.2.0-alpha-612-g28d08a94f
Edition: Community
Git Commit Hash: 28d08a94ff5e46856b976adf02c8fca1e63149f4
Git Branch: master
UTC Build Time: 2022-08-04 06:23:25
GoVersion: go1.18.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore |

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #36888

Problem Summary:

The left join with `concat_ws` is optimized to inner join, which is incorrect, because `concat_ws(1, NULL)` and `concat_ws(NULL, NULL)` have different values (`''` and `NULL`).

This function in MySQL helps in joining two or more strings along with a separator. The separator must be specified by the user and it can also be a string. If the separator is NULL, then the result will also be NULL.

```
Syntax:
CONCAT_WS(separator, string1, string2, ...)
```

### What is changed and how it works?

Don't try to aggressively fold the expression  `concat_ws(expression, NULL)`.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
Fix the issue that the `concat_ws` in predicates is pushed down without considering the NULL argument
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
@wshwsh12 @AilinKid PTAL

**Comment by hawkingrei** [comment]
@YangKeao Please fix conflicting.

**Comment by YangKeao** [comment]
> @YangKeao Please fix conflicting.

Fixed. PTAL @wshwsh12 @AilinKid

**Review by wshwsh12 — APPROVED** [review]

**Comment by YangKeao** [comment]
@hawkingrei PTAL. (Don't know why your approve has lost).

**Review by hawkingrei — APPROVED** [review]

**Comment by YangKeao** [comment]
@wshwsh12 @hawkingrei Could you help me to `/merge` this PR?

**Review by AilinKid — APPROVED** [review]
/merge

**Pull request merged**
