### PR TITLE
planner,session: add Reload and File privilege, check Reload for the flush statement

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Fix https://github.com/pingcap/tidb/issues/14213

### What is changed and how it works?

The Flush statements should check the RELOAD privilege. RELOAD is not in our mysql.user table yet.

This PR add RELOAD and FILE columns to the user table, and it checks RELOAD for the flush statements.

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)

Manual check the upgrade process and see things like show / grant works right.

Code changes

 - Has persistent data change

Side effects

 - Breaking backward compatibility
Add new columns to `mysql.user`

### CODE REVIEW

**Comment by tiancaiamao** [comment]
https://github.com/pingcap/tidb/pull/14319/files#diff-4a9e9120daccf5fc0d249b976f057938R1002
https://github.com/pingcap/tidb/pull/14319/files#diff-4a9e9120daccf5fc0d249b976f057938R927

Parser PR:

**Comment by tangenta** [comment]
Please fix the unit tests.

**Comment by imtbkcat** [comment]
@tiancaiamao yes, i think set `RELOAD` and `FILE` to true for those have `SUPER` privilege is better.

**Comment by tiancaiamao** [comment]
PTAL @imtbkcat @lysu

**Comment by tiancaiamao** [comment]
This should be merged together with https://github.com/pingcap/parser/pull/708

**Pull request merged**
