### PR TITLE
ddl, transaction: DDL won't affect transactions

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### What is changed and how it works?

When a transaction executes a DDL, relatedPhysicalTableIDs is nil.
When a transaction only contains DML, relatedPhysicalTableIDs is [].

### Check List

Tests 

- [x] Manual test (add detailed scripts or steps below)

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by time-and-fate — APPROVED** [review]

**Comment by djshow832** [comment]
> When a transaction only contains DML on temporary tables, relatedPhysicalTableIDs is [].

There is no temporary table in v4.0. It's been supported since 5.3. It must be another problem if you encountered it in v4.0.

**Review by time-and-fate — APPROVED** [review]

**Comment by time-and-fate** [comment]
> > When a transaction only contains DML on temporary tables, relatedPhysicalTableIDs is [].
> 
> There is no temporary table in v4.0. It's been supported since 5.3. It must be another problem if you encountered it in v4.0.

The actual issue of this hotfix is https://github.com/pingcap/tidb/issues/37555.

**Review by jackysp — APPROVED** [review]

**Pull request merged**
