### PR TITLE
ddl: Allow create timestamp default 0 without sql_mode NO_ZERO_DATE (#30305)

### LINKED ISSUE #30305: IT mysqltest failed with timestamp using 0 as default value
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_common_test/detail/tidb_ghpr_integration_common_test/8074/pipeline/
```
[2021-12-01T03:34:15.035Z] time="2021-12-01T11:34:14+08:00" level=error msg="run test [show] err: sql:create table t (id int, c1 timestamp null default 0);: run \"create table t (id int, c1 timestamp null default 0);\" at line 48 err Error 1067: Invalid default value for 'c1'"
2021-12-01T03:34:15.035Z] time="2021-12-01T11:34:14+08:00" level=error msg="run test [timestamp_insert] err: sql:create table t (id int, c1 timestamp default 0);: run \"create table t (id int, c1 timestamp default 0);\" at line 121 err Error 1067: Invalid default value for 'c1'"

[2021-12-01T03:34:15.035Z] time="2021-12-01T11:34:14+08:00" level=error msg="run test [type_timestamp] err: sql:CREATE TABLE t1 (c1 TIMESTAMP DEFAULT 0);: run \"CREATE TABLE t1 (c1 TIMESTAMP DEFAULT 0);\" at line 308 err Error 1067: Invalid default value for 'c1'"

[2021-12-01T03:34:15.035Z] time="2021-12-01T11:34:14+08:00" level=error msg="run test [datetime_insert] err: sql:create table t (id int, c1 datetime default 0);: run \"create table t (id int, c1 datetime default 0);\" at line 44 err Error 1067: Invalid default value for 'c1'"
[2021-12-01T03:34:15.035Z] time="2021-12-01T11:34:14+08:00" level=error msg="run test [infoschema] err: sql:CREATE TABLE t2 (c1 timestamp default CURRENT_TIMESTAMP, c2 timestamp null default 0, c3 timestamp null, c4 timestamp not null);: run \"CREATE TABLE t2 (c1 timestamp default CURRENT_TIMESTAMP, c2 timestamp null default 0, c3 timestamp null, c4 timestamp not null);\" at line 9 err Error 1067: Invalid default value for 'c2'"


```

similar issues #https://github.com/pingcap/tidb/issues/29795

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #30305 

Problem Summary:
create table t (ts timestamp default 0) was not allowed if `sql_mode` did not include `NO_ZERO_DATE`

### What is changed and how it works?
Allow to create and alter it.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by bb7133** [comment]
This change looks good to me, but the CI failed:

```
[2021-12-08T00:31:27.730Z] FAIL: column_type_change_test.go:2153: testColumnTypeChangeSuite.TestCastFromZeroIntToTimeError
[2021-12-08T00:31:27.730Z] 
[2021-12-08T00:31:27.730Z] column_type_change_test.go:2190:
[2021-12-08T00:31:27.730Z]     tk.MustGetErrCode("alter table t modify column a date;", mysql.ErrTruncatedWrongValue)
[2021-12-08T00:31:27.730Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:402:
[2021-12-08T00:31:27.730Z]     tk.c.Assert(err, check.NotNil)
[2021-12-08T00:31:27.730Z] ... value = nil
```

#30305 is a regression introduced by #25728, @tangenta please give some suggestions on the fix.

**Comment by tangenta** [comment]
MySQL's behavior of column-type-change is controlled by the "strict" mode. Even `NO_ZERO_DATE` is specified, the date can be zero...

```sql
set @@sql_mode = 'STRICT_TRANS_TABLES';
drop table if exists t;
create table t (a int);
insert into t values (0);
alter table t modify column a date;
-- ERROR 1292 (22007): Incorrect date value: '0' for column 'a' at row 1


set @@sql_mode = 'NO_ZERO_DATE';
drop table if exists t;
create table t (a int);
insert into t values (0);
alter table t modify column a date;
-- Query OK, 1 row affected, 1 warning (0.11 sec)
-- Records: 1  Duplicates: 0  Warnings: 1
```

**Comment by tangenta** [comment]
https://github.com/pingcap/tidb/blob/28446605c2e019e84e934602f4bd136294a61ff3/ddl/backfilling.go#L614-L616

Adding

```go
sessCtx.GetSessionVars().StmtCtx.NoZeroDate = sqlMode.HasStrictMode()
```
here should fix the test.

**Review by bb7133 — COMMENTED** [review]
LGTM

**Review by bb7133 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Pull request merged**
