### PR TITLE
br: update permission, so tikv can write to folder when backup to local

### PR DESCRIPTION
**Pull request by fengou1**
### What problem does this PR solve?
run br with root, if tikv run by other users, backup will failure
Issue Number: close #xxx

Problem Summary:

### What is changed and how it works?
br create a local folder by br user, and tikv backup file by tikv user.
tikv user can not write to backup folder.
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. create a cluster with user br_ou
2. run br with root user
3. backup success
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by sylzd — APPROVED** [review]

**Comment by sylzd** [comment]
LGTM~

**Review by YuJuncen — APPROVED** [review]

**Pull request merged**
