### PR TITLE
executor: add sequence info for infoschema

### LINKED ISSUE #26889: SEQUENCE is not in the INFORMATION_SCHEMA.TABLES
### 1. Minimal reproduce step (Required)

```
use test;
create sequence test_seq;
SELECT TABLE_TYPE, TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = "test_seq"
```

### 2. What did you expect to see? (Required)

in the mariadb  10.6.3 
```
+------------+------------+
| TABLE_TYPE | TABLE_NAME |
+------------+------------+
| SEQUENCE   | test_seq   |
+------------+------------+
```

### 3. What did you see instead (Required)

```
+------------+------------+
| TABLE_TYPE | TABLE_NAME |
+------------+------------+
+------------+------------+
```

### 4. What is your TiDB version? (Required)

Release Version: v5.2.0-alpha-478-gdf0999bbc
Edition: Community
Git Commit Hash: df0999bbcc76331b8788308283f7992e8eb53732
Git Branch: master
UTC Build Time: 2021-08-03 10:05:04
GoVersion: go1.16.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #26889 

Problem Summary:

### What is changed and how it works?

add SEQUENCE info at the inforschema

### Check List 

Tests 

- [x] Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by tangenta** [comment]
cc @lichunzhu

**Comment by lichunzhu** [comment]
> cc @lichunzhu

Should we also update the result for `show table status`?
```sql
mysql> show tables;
+----------------+
| Tables_in_test |
+----------------+
| s              |
+----------------+
1 row in set (0.00 sec)

mysql> show full tables;
+----------------+------------+
| Tables_in_test | Table_type |
+----------------+------------+
| s              | SEQUENCE   |
+----------------+------------+
1 row in set (0.00 sec)

mysql> show table status;
Empty set (0.01 sec)

mysql> select tidb_version();
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                          |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.2.0-alpha-562-ge539f9d62
Edition: Community
Git Commit Hash: e539f9d62f8755f7b1894848f8bd8c7bb83db3ca
Git Branch: HEAD
UTC Build Time: 2021-08-09 12:39:50
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by lichunzhu** [comment]
BTW, here is the result of mariaDB.
```sql

mysql> show tables;
+----------------+
| Tables_in_test |
+----------------+
| s              |
+----------------+
1 row in set (0.00 sec)

mysql> show full tables;
+----------------+------------+
| Tables_in_test | Table_type |
+----------------+------------+
| s              | SEQUENCE   |
+----------------+------------+
1 row in set (0.00 sec)

mysql> show table status;
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+--------------------+----------+----------------+---------+------------------+-----------+
| Name | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation          | Checksum | Create_options | Comment | Max_index_length | Temporary |
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+--------------------+----------+----------------+---------+------------------+-----------+
| s    | InnoDB |      10 | Fixed      |    1 |          16384 |       16384 |               0 |            0 |         0 |           NULL | 2021-08-11 08:52:27 | NULL        | NULL       | utf8mb4_general_ci |     NULL |                |         |                0 | N         |
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+--------------------+----------+----------------+---------+------------------+-----------+
1 row in set (0.00 sec)

mysql> select version();
+-------------------------------------+
| version()                           |
+-------------------------------------+
| 10.6.4-MariaDB-1:10.6.4+maria~focal |
+-------------------------------------+
1 row in set (0.00 sec)
```

**Comment by hawkingrei** [comment]
> BTW, here is the result of mariaDB.
> 
> ```sql
> mysql> show tables;
> +----------------+
> | Tables_in_test |
> +----------------+
> | s              |
> +----------------+
> 1 row in set (0.00 sec)
> 
> mysql> show full tables;
> +----------------+------------+
> | Tables_in_test | Table_type |
> +----------------+------------+
> | s              | SEQUENCE   |
> +----------------+------------+
> 1 row in set (0.00 sec)
> 
> mysql> show table status;
> +------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+--------------------+----------+----------------+---------+------------------+-----------+
> | Name | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation          | Checksum | Create_options | Comment | Max_index_length | Temporary |
> +------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+--------------------+----------+----------------+---------+------------------+-----------+
> | s    | InnoDB |      10 | Fixed      |    1 |          16384 |       16384 |               0 |            0 |         0 |           NULL | 2021-08-11 08:52:27 | NULL        | NULL       | utf8mb4_general_ci |     NULL |                |         |                0 | N         |
> +------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+--------------------+----------+----------------+---------+------------------+-----------+
> 1 row in set (0.00 sec)
> 
> mysql> select version();
> +-------------------------------------+
> | version()                           |
> +-------------------------------------+
> | 10.6.4-MariaDB-1:10.6.4+maria~focal |
> +-------------------------------------+
> 1 row in set (0.00 sec)
> ```

OK, I will create a new PR for this function.

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]
LGTM

**Review by djshow832 — APPROVED** [review]

**Review by djshow832 — APPROVED** [review]

**Pull request merged**
