### PR TITLE
ddl: use the correct timezone to encode record for adding index

### LINKED ISSUE #46033: Data inconsistency after adding index in ingest mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql> SET time_zone = '-06:00';
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT @@global.time_zone, @@session.time_zone, @@global.system_time_zone;
+--------------------+---------------------+---------------------------+
| @@global.time_zone | @@session.time_zone | @@global.system_time_zone |
+--------------------+---------------------+---------------------------+
| SYSTEM             | -06:00              | Asia/Shanghai             |
+--------------------+---------------------+---------------------------+
1 row in set (0.00 sec)

mysql> drop table if exists  timetest;
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> create table timetest (`src` varchar(48),`t` timestamp,`timezone` varchar(100));
Query OK, 0 rows affected (0.14 sec)

mysql> insert into timetest values('2023-07-29 23:15:30 -0600','2023-07-29 23:15:30 -0600','-6:00');
Query OK, 1 row affected (0.01 sec)

mysql> create index idx on timetest(t);

Query OK, 0 rows affected (2.95 sec)

mysql> admin check table timetest;
ERROR 8223 (HY000): data inconsistency in table: timetest, index: idx, handle: 1, index-values:"handle: 1, values: [KindMysqlTime 2023-07-30 19:15:30]" != record-values:"handle: 1, values: [KindMysqlTime 2023-07-30 13:15:30]"
mysql> admin show ddl jobs;
+--------+---------+-------------------------+------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
| JOB_ID | DB_NAME | TABLE_NAME              | JOB_TYPE               | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE  |
+--------+---------+-------------------------+------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
|    100 | test    | timetest                | add index /* ingest */ | public       |         2 |       98 |         1 | 2023-08-13 05:36:22 | 2023-08-13 05:36:22 | 2023-08-13 05:36:25 | synced |
|     99 | test    | timetest                | create table           | public       |         2 |       98 |         0 | 2023-08-13 05:36:22 | 2023-08-13 05:36:22 | 2023-08-13 05:36:22 | synced |
|     97 | mysql   | tidb_runaway_watch_done | create table           | public       |         1 |       96 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     95 | mysql   | tidb_timers             | create table           | public       |         1 |       94 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     93 | mysql   | tidb_runaway_queries    | create table           | public       |         1 |       92 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     91 | mysql   | tidb_runaway_watch      | create table           | public       |         1 |       90 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     89 | mysql   | tidb_import_jobs        | create table           | public       |         1 |       88 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     87 | mysql   | load_data_jobs          | create table           | public       |         1 |       86 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     85 | mysql   | tidb_global_task        | create table           | public       |         1 |       84 |         0 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | 2023-08-11 08:01:31 | synced |
|     83 | mysql   | tidb_ttl_job_history    | create table           | public       |         1 |       82 |         0 | 2023-08-11 08:01:30 | 2023-08-11 08:01:30 | 2023-08-11 08:01:31 | synced |
+--------+---------+-------------------------+------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
10 rows in set (0.01 sec)

mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: c7c7000165aba353eb7b39a6c11371e1adc7b6b1
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time: 2023-08-10 14:55:04
GoVersion: go1.21.0
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
No error of admin check statement.

### 3. What did you see instead (Required)
error, timestamp column set the wrong timezone in index.

### 4. What is your TiDB version? (Required)
c7c7000165aba353eb7b39a6c11371e1adc7b6b1
<!-- Paste the output of SELECT tidb_version() -->

### LINKED ISSUE #46053: Data inconsistency after adding index in another timezone
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
SET time_zone = '-06:00';
create table t (`src` varchar(48),`t` timestamp,`timezone` varchar(100));
insert into t values('2000-07-29 23:15:30 -0600','2000-07-29 23:15:30 -0600','-6:00');
alter table t add index idx(t);
admin check table t;
```

### 2. What did you expect to see? (Required)

No error.

### 3. What did you see instead (Required)

```
ERROR 8223 (HY000): data inconsistency in table: t, index: idx, handle: 1, index-values:"handle: 1, values: [KindMysqlTime 2000-07-30 19:15:30]" != record-values:"handle: 1, values: [KindMysqlTime 2000-07-30 13:15:30]"
```

### 4. What is your TiDB version? (Required)

c34f6fc

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #46033

Problem Summary:

Normally, TiDB converts `timestamp` values to UTC before writing them to the storage, and converts them back when reading. For adding index, we

1. Read the table records from storage.
2. Encode the index records.
3. Write/Ingest the index records to storage.

In step 1, the datum returned by `extractDatumByOffsets()` is in UTC timezone. It is converted to UTC **again** in step 2. As a result, index timestamp is converted twice.

Unistore DAG request decoding:
https://github.com/pingcap/tidb/blob/3846e80fc8521e0c28185efd88640abb933ceb08/store/mockstore/unistore/cophandler/cop_handler.go#L298-L308

TiKV DAG request decoding:
https://github.com/tikv/tikv/blob/14dd8cce96e064a029e58de8cf832c35d44e09a5/components/tidb_query_datatype/src/expr/ctx.rs#L86-L94

For Unistore and TiKV, the **time zone name** is always considered first, and the time zone offset second.

Thus, the way to `buildDAGPB` is wrong:

https://github.com/pingcap/tidb/blob/3846e80fc8521e0c28185efd88640abb933ceb08/ddl/index_cop.go#L487

We assigned both name and offset to `UTC` and `-0600` respectively. `UTC` is kept but `-0600` is discarded during parsing the DAG request.

### What is changed and how it works?

Assign the time zone offset in `buildDAGPB`, and leave time zone name to be empty.

```go
// Zone computes the time zone in effect at time t, returning the abbreviated
// name of the zone (such as "CET") and its offset in seconds east of UTC.
func (t Time) Zone() (name string, offset int) {
	name, offset, _, _, _ = t.loc.lookup(t.unixSec())
	return
}
```

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by tiancaiamao** [comment]
> This PR temporarily set the timezone to UTC before encoding the index(step 2).

How about handle the fix in step1?  @tangenta 

> 1. Read the table records from storage.

As you know, all the data stored in tikv is in UTC+0, and after the data is loaded into tidb, it's converted according to the session's timezone, so the convention is not break.

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
some tests failed

```
        	Error Trace:	tests/realtikvtest/addindextest/common.go:310
        	            				tests/realtikvtest/addindextest/common.go:406
        	            				tests/realtikvtest/addindextest/multi_schema_change_test.go:73
        	Error:      	Received unexpected error:
        	            	[admin:8223]data inconsistency in table: t1, index: idx0, handle: 50, index-values:"handle: 50, values: [KindInt64 2 KindMysqlTime 2001-01-02 19:11:12]" != record-values:"handle: 50, values: [KindInt64 2 KindMysqlTime 2001-01-02 11:11:12]"
        	            	github.com/pingcap/errors.AddStack
        	            		external/com_github_pingcap_errors/errors.go:174
        	            	github.com/pingcap/errors.(*Error).GenWithStackByArgs
        	            		external/com_github_pingcap_errors/normalize.go:164
        	            	github.com/pingcap/tidb/util/logutil/consistency.(*Reporter).ReportAdminCheckInconsistent
        	            		util/logutil/consistency/reporter.go:293
        	            	github.com/pingcap/tidb/executor.(*checkIndexWorker).HandleTask
        	            		executor/executor.go:2667
        	            	github.com/pingcap/tidb/resourcemanager/pool/workerpool.(*WorkerPool[...]).handleTaskWithRecover
        	            		resourcemanager/pool/workerpool/workerpool.go:104
        	            	github.com/pingcap/tidb/resourcemanager/pool/workerpool.(*WorkerPool[...]).runAWorker.func1
        	            		resourcemanager/pool/workerpool/workerpool.go:116
        	            	github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1
        	            		util/wait_group_wrapper.go:154
        	            	runtime.goexit
        	            		src/runtime/asm_amd64.s:1650
        	Test:       	TestMultiSchemaChangeMultiColsIndex
```

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Pull request merged**
