### PR TITLE
disttask: Add history table for global task

### LINKED ISSUE #47180: disttask: add history table for global task
## Enhancement
Add history table for global task.
We want to move rows in tidb_global_task to reduce the stress for it.

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: ref #46258 close #47180

Problem Summary:

### What is changed and how it works?
1. limit the running task count to 1.
2. add new system table: `tidb_global_task_history`
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by lichunzhu — APPROVED** [review]

**Review by yudongusa — APPROVED** [review]
LGTM after checked with @Benjamin2037 on its impact on the new TiDB version upgrade and downgrade.

**Review by XuHuaiyu — APPROVED** [review]

**Review by LittleFall — COMMENTED** [review]
LGTM

**Pull request merged**
