### PR TITLE
Revert "executor: fix show global variables return session variables also (#19341)"

### LINKED ISSUE #24326: show session variables is very slow on first run
## Bug Report

This is reported here:

https://asktug.com/t/topic/69586
https://asktug.com/t/topic/69767
https://asktug.com/t/topic/69699

### 1. Minimal reproduce step (Required)

`SHOW VARIABLES` in a new session

### 2. What did you expect to see? (Required)

It should always be fast.

### 3. What did you see instead (Required)

The first execution is slow.

### 4. What is your TiDB version? (Required)

Verified against master:
```sql
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-2748-g8b0305aa2-dirty
Edition: Community
Git Commit Hash: 8b0305aa2af38f201c893fe9ce8c9af4201ebbc8
Git Branch: master
UTC Build Time: 2021-04-27 14:20:08
GoVersion: go1.13.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by bb7133**
This reverts commit cc7a38327fca12df5dacbaa959f6f44dfe32c85a..

### What problem does this PR solve?

Issue Number: close #24326 for TiDB v5.0

Problem Summary:

- [x] Manual test (add detailed scripts or steps below)

The following code is used to do the tests:
```
       Class.forName("com.mysql.jdbc.Driver").newInstance();    
        String url = "jdbc:mysql://address=(protocol=tcp)(host=127.0.0.1)(port=4000)(user=root)/test?allowMultiQueries=true";    
        Connection conn = DriverManager.getConnection(url, "", "");    
        DatabaseMetaData meta = conn.getMetaData();    
        System.out.println("Driver version: " + meta.getDriverVersion());  

        int connId = 0;    
        while (connId < 20) {    
            try {    
                long startTime = System.currentTimeMillis();    
                conn = DriverManager.getConnection(url, "", "");    
                long duration = System.currentTimeMillis() - startTime;    
                System.out.println("Time for onConnection #" + connId + ": " + duration);    
                connId ++;    
            } catch (Exception e) {    
                System.out.println("Exception: "+e);    
                e.printStackTrace();    
            } finally {    
                conn.close();
            }
        }
```

After reverting the commit, duration of connection reduced.

Side effects

- This PR brings #18517 back.

Documentation

- To be added

### Release note 

- Revert #19341 to avoid #24326.

### CODE REVIEW

**Review by djshow832 — APPROVED** [review]

**Comment by bb7133** [comment]
PTAL @morgo , the revert work is not trivial because of some succeeding PRs(#21988, #22284...)

**Review by morgo — APPROVED** [review]
LGTM, but I've added the compatibility breaker tag. I think we should change the compatibility message to:

- The output of `SHOW VARIABLES` now only includes session scoped variables. This change was introduced to address a performance issue; in TiDB 5.1 and above the output of `SHOW VARIABLES` returns all variables again.

**Comment by bb7133** [comment]
> LGTM, but I've added the compatibility breaker tag. I think we should change the compatibility message to:
> 
> * The output of `SHOW VARIABLES` now only includes session scoped variables. This change was introduced to address a performance issue; in TiDB 5.1 and above the output of `SHOW VARIABLES` returns all variables again.

Thank you!

**Pull request merged**
