### PR TITLE
planner, executor: set new child after injecting Project operator (#9684)

### PR DESCRIPTION
**Pull request by zz-jason**
cherry-pick #9684 to release 2.1

### CODE REVIEW

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by eurekaka** [comment]
@zz-jason CI failed, PTAL

**Comment by eurekaka** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
