### PR TITLE
executor,planner: make used stats info thread safe

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/50835

Problem Summary:

### What changed and how does it work?

Introduced by https://github.com/pingcap/tidb/pull/50643/files

Make usedStatsInfo thread-safe and also use CAS to init it.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
The call to `Len`, `Keys` and `Values` are slow / heavy, and the caller will iterate through the map multiple times.

However, given the assumption that a single statement will not query too many tables, the performance impaction should be fine. Therefore, I think this PR is good enough.

**Review by hawkingrei — APPROVED** [review]

**Review by hi-rustin — COMMENTED** [review]
🔢 Self-check

**Comment by hi-rustin** [comment]
> The call to `Len`, `Keys` and `Values`

I dropped the `Len` API.

**Review by AilinKid — APPROVED** [review]

**Pull request merged**
