### PR TITLE
br: fix the missing retry for pd batch scan error

### LINKED ISSUE #33419: scan region retry not work as expected.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
we had a retry in https://github.com/pingcap/tidb/blob/4e69c0705e5dc5369f962f7d38f5cca6213efe01/br/pkg/restore/split.go#L108-L111, to retry the error in CheckRegionConsistency. but it's not work as expected.
because the multerr is not equal to origin error.
see the test.
image

### 2. What did you expect to see? (Required)
retry at least  32 * 3 times when region not consistency.

### 3. What did you see instead (Required)
only 3 times retry.
image

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve?

Issue Number: close #33419 

Problem Summary:
current BR doesn't not retry ErrPDBatchScanRegion enough.
### What is changed and how it works?
replace the multierr with the `ErrPDBatchScanRegion`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the issue that BR not retry enough when region not consistency during restoration.
```

### CODE REVIEW

**Review by gozssky — APPROVED** [review]

**Review by joccau — APPROVED** [review]
LGTM～

**Review by gozssky — APPROVED** [review]

**Review by glorv — APPROVED** [review]

**Review by zhouqiang-cl — APPROVED** [review]

**Pull request merged**
