### PR TITLE
table/tables: ensure the column id unique for partition pruning expression

### LINKED ISSUE #42135: planner: wrong empty results when joining two partitioning tables
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->

```
CREATE TABLE `tx1`  (
  `ID` varchar(13),
  `a` varchar(13),
  `b` varchar(4000),
  `ltype` int(5) NOT NULL
);

CREATE TABLE `tx2`  (
  `ID` varchar(13),
  `rid` varchar(12),
  `a` varchar(9),
  `b` varchar(8),
  `c` longtext,
  `d` varchar(12),
  `ltype` int(5) NOT NULL
) PARTITION BY LIST (`ltype`)
(PARTITION `p1` VALUES IN (501),
PARTITION `p2` VALUES IN (502));

insert into tx1 values(1,1,1,501);
insert into tx2 values(1,1,1,1,1,1,501);

select * from tx1 inner join tx2 on tx1.ID=tx2.ID and tx1.ltype=tx2.ltype where tx2.rid='1'; 
```

### 2. What did you expect to see? (Required)
The query should return some rows.

### 3. What did you see instead (Required)
The query returns an empty result.

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.7.0-alpha-246-g145b7cdf72-dirty
Edition: Community
Git Commit Hash: 145b7cdf72feeecf7f2b0b3e01693c603712dce5
Git Branch: master
UTC Build Time: 2023-03-13 05:15:10
GoVersion: go1.19.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #42135

Problem Summary:

### What is changed and how it works?

The UniqueID of a column expression should be unique.
For user's connection, this UniqueID is generated by keeping a variable++ in SessionVars.
But for the partition pruning expression, it use a mocked session context, so the id may conflict with the others.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by qw4990** [comment]
Do we need to pick this PR back to v5.4/v6.1/v6.5?

**Review by qw4990 — APPROVED** [review]

**Comment by mjonss** [comment]
@tiancaiamao I created an alternative fix, https://github.com/pingcap/tidb/pull/42193, not sure I fully understood how this PR fixes the issue?

**Review by winoros — DISMISSED** [review]
I think it can work. So approve first.

**Comment by tiancaiamao** [comment]
Fixed by https://github.com/pingcap/tidb/pull/42193

**Pull request closed without merging**
