### PR TITLE
*: update client-go to improve availability on tikv failure

### LINKED ISSUE #34906: Recover time may be very long if TiKV enables hibernate region
## Enhancement

Considering one TiKV is unhealthy, all requests sending to that store will timeout. But due to hibernate region, the regions whose leaders are on the unhealthy store will not be re-elected until a request is sent to the follower.

If there are thousands of such regions, every time we are accessing a new region, it will send a request to the original leader on the unhealthy TiKV because the leader definitely does not change. And then, the user will always experience very long request duration until all regions are touched and elect new leaders.

We can use the health check service of TiKV to get the serving status of TiKV. By filtering out healthy nodes, we can recover from TiKV failure more quickly.

### PR DESCRIPTION
**Pull request by sticnarf**
Signed-off-by: Yilin Chen <sticnarf@gmail.com>

### What problem does this PR solve?

Issue Number: close #34906

### What is changed and how it works?

See https://github.com/tikv/client-go/pull/503

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Prevent sending requests to unhealthy TiKV nodes to improve availability.
```

### CODE REVIEW

**Review by youjiali1995 — APPROVED** [review]

**Review by ngaut — APPROVED** [review]

**Comment by sticnarf** [comment]
Bazel file updated
cc @hawkingrei

**Comment by sticnarf** [comment]
The failed test is related to the client-go update. Let me check...

**Comment by hawkingrei** [comment]
> The failed test is related to the client-go update. Let me check...

Great, 

> The failed test is related to the client-go update. Let me check...

/merge  It passed. so I merged it.

**Pull request merged**
