### PR TITLE
*: supports setting global/meta range placement policy

### PR DESCRIPTION
**Pull request by nolouch**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/29677 ref https://github.com/pingcap/tidb/issues/45384

Problem Summary:

### What is changed and how it works?

unify the entry of placement rule to tidb. supports setting global/meta range placement policy by tidb. Example:
```
// policy about 5 replicas
create placement policy `mypolicy` FOLLOWERS=4;

// set global range to 5 replicas
ALTER RANGE global PLACEMENT POLICY mypolicy
// set meta range to 5 replicas
ALTER RANGE meta PLACEMENT POLICY mypolicy
// remove and reset to default
ALTER RANGE global PLACEMENT POLICY default
```

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test 

### step 1:
image
image

### step 2

image
image

### Step 3
image

### Step 4 
image

Documentation

- [x] Affects user behaviors

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
*: supports setting global/meta range placement policy
```

### CODE REVIEW

**Review by CabinfeverB — APPROVED** [review]

**Comment by nolouch** [comment]
ptal @xhebox @lcwangchao

**Review by xhebox — APPROVED** [review]

**Pull request merged**
