### PR TITLE
planner: change `redundantSchema` to `fullSchema` to correctly handle natural and "using" joins

### LINKED ISSUE #29481: NATURAL JOIN with multiple tables(4) resulting extra column in TiDB
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t1,t2,t3,t4,t5,t6;
create table t1 (c int, b int);
create table t2 (a int, b int);
create table t3 (b int, c int);
create table t4 (y int, c int);

insert into t1 values (10,1);
insert into t1 values (3 ,1);
insert into t1 values (3 ,2);
insert into t2 values (2, 1);
insert into t3 values (1, 3);
insert into t3 values (1,10);
insert into t4 values (11,3);
insert into t4 values (2, 3);

select t1.*, t2.*, t3.*, t4.* from (t1  natural join t2) natural join (t3 natural  join t4);
```

### 2. What did you expect to see? (Required)
```sql
mysql> select t1.*, t2.*, t3.*, t4.* from (t1  natural join t2) natural join (t3 natural  join t4);
+------+------+------+------+------+------+------+------+
| c    | b    | a    | b    | b    | c    | y    | c    |
+------+------+------+------+------+------+------+------+
|    3 |    1 |    2 |    1 |    1 |    3 |    2 |    3 |
|    3 |    1 |    2 |    1 |    1 |    3 |   11 |    3 |
+------+------+------+------+------+------+------+------+
2 rows in set (0.00 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> select t1.*, t2.*, t3.*, t4.* from (t1  natural join t2) natural join (t3 natural  join t4);
+------+------+------+------+------+------+------+------+------+
| b    | c    | a    | b    | c    | b    | y    | c    | y    |
+------+------+------+------+------+------+------+------+------+
|    1 |    3 |    2 |    1 |    3 |    1 |    2 |    3 |    2 |
|    1 |    3 |    2 |    1 |    3 |    1 |   11 |    3 |   11 |
+------+------+------+------+------+------+------+------+------+
2 rows in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)
```sql
+-------------------------+--------------------------------------------------------------------------+
| Variable_name           | Value                                                                    |
+-------------------------+--------------------------------------------------------------------------+
| innodb_version          | 5.6.25                                                                   |
| protocol_version        | 10                                                                       |
| tidb_analyze_version    | 2                                                                        |
| tidb_row_format_version | 2                                                                        |
| tls_version             | TLSv1,TLSv1.1,TLSv1.2                                                    |
| version                 | 5.7.25-TiDB-v5.2.2                                                       |
| version_comment         | TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible |
| version_compile_machine | x86_64                                                                   |
| version_compile_os      | osx10.8                                                                  |
+-------------------------+--------------------------------------------------------------------------+
9 rows in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #29481 

Problem Summary:

Our current handling of the schema of natural join or "using" join is not correct. Specifically, the content and usage of the `redundantSchema` are not correct.
Currently, every time we meet a natural or "using" join, we put the schema from the inner side into `redundantSchema`. (Please see `buildJoin()` and `coalesceCommonColumns()` for more details)
But for such cases:
```sql
create table t1(a int, b int);
create table t2(c int, d int);
create table t3(c int, b int);
select t1.*, t2.*, t3.* from t1 natural join (t2 natural join t3);
```
The `redundantSchema` is wrong.
After `t2 natural join t3`: `redundant schema: [t3.c, t3.b]`; `schema: [t2.c, t2.d, t3.b]`.
After `t1 natural join (t2 natural join t3)`: `redundant schema: [t3.c, t3.b, t2.c, t2.d, t3.b]`; `schema: [t1.b, t1.a, t2.c, t2.d]`.

When handling select fields like `t1.*`, we will collect the columns from the `redundantSchema` if we can find more columns from there than from the `Schema`. In the case above, the result columns and order are all wrong. (Please see `(*PlanBuilder).unfoldWildStar` for the more details)

Examples of wrong results can be found in #29481.

### What is changed and how it works?

I change the `redundantSchema` to `fullSchema` to try to make the concept more clear and make its content more predictable.
Please read the comments In the code for the details.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]
Doesn't find anything to comment(

**Review by Reminiscent — APPROVED** [review]

**Pull request merged**
