### PR TITLE
expression, executor: rewrite the builtin func ascii using new methods

### PR DESCRIPTION
**Pull request by SteveZhangBit**
Rewrite the builtin func `ascii` using baseIntBuiltinFunc.

### CODE REVIEW

**Comment by hanfei1991** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
cc @AndreMouche @hhkbp2

**Comment by XuHuaiyu** [comment]
cc @AndreMouche @hhkbp2 @lishihai9017

**Pull request merged**
