### PR TITLE
planner: add explain information for slow_query extractor (#17110)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #17110 to release-4.0

---

Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Close https://github.com/pingcap/tidb/issues/15385

eg
```sql
mysql>desc select max(time) from `SLOW_QUERY` where time > "2020-05-12 10:06:00.999" and time<"2020-05-12 11:06:00.999"
+-----------------------+----------+------+------------------+-----------------------------------------------------------------------------+
| id                    | estRows  | task | access object    | operator info                                                               |
+-----------------------+----------+------+------------------+-----------------------------------------------------------------------------+
| StreamAgg_14          | 1.00     | root |                  | funcs:max(Column#1)->Column#48                                              |
| └─TopN_17             | 1.00     | root |                  | Column#1:desc, offset:0, count:1                                            |
|   └─Selection_21      | 8000.00  | root |                  | not(isnull(Column#1))                                                       |
|     └─MemTableScan_22 | 10000.00 | root | table:SLOW_QUERY | start_time:2020-05-12 10:06:01.000000, end_time:2020-05-12 11:06:00.998000  |
+-----------------------+----------+------+------------------+-----------------------------------------------------------------------------+
4 rows in set
Time: 0.009s
mysql>desc select max(time) from `SLOW_QUERY`
+-----------------------+----------+------+------------------+-------------------------------------------------+
| id                    | estRows  | task | access object    | operator info                                   |
+-----------------------+----------+------+------------------+-------------------------------------------------+
| StreamAgg_13          | 1.00     | root |                  | funcs:max(Column#1)->Column#48                  |
| └─TopN_16             | 1.00     | root |                  | Column#1:desc, offset:0, count:1                |
|   └─Selection_20      | 8000.00  | root |                  | not(isnull(Column#1))                           |
|     └─MemTableScan_21 | 10000.00 | root | table:SLOW_QUERY | only search in the current 'tidb-slow.log' file |
+-----------------------+----------+------+------------------+-------------------------------------------------+

```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- No

### Release note 

- Add explain information for slow_query extractor.

### CODE REVIEW

**Comment by crazycs520** [comment]
@djshow832 @AilinKid PTAL

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by djshow832 — COMMENTED** [review]
LGTM

**Comment by djshow832** [comment]
LGTM

**Review by crazycs520 — APPROVED** [review]

**Review by djshow832 — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]

**Review by djshow832 — APPROVED** [review]

**Review by SunRunAway — APPROVED** [review]

**Review by breeswish — APPROVED** [review]
/merge

**Pull request merged**
