### PR TITLE
plugin: migrate test-infra to testify

### LINKED ISSUE #26744: migrate test-infra to testify for `plugin` pkg

### PR DESCRIPTION
**Pull request by unconsolable**
Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>

### What problem does this PR solve?

Issue Number: close #26744 

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — CHANGES_REQUESTED** [review]
Thanks for your contribution! This PR goes in a good direction. Here are two suggestions：

1. `require` fails short-circuit and fit better than `assert`.
2. You may reduce a lot of comment as they are now recorded by testify framework; for example

```go
assert.Equalf(t, value, key.String(), "kind %s != %s", key.String(), value)
```

can be 

```go
require.Equal(t, value, key.String())
```

**Review by tisonkun — APPROVED** [review]
Thanks for your contribution @unconsolable ! LGTM

**Comment by tisonkun** [comment]
/cc @xhebox @morgo 

May you take a look at this PR, thanks!

**Review by xhebox — APPROVED** [review]
Well done

**Review by morgo — APPROVED** [review]

**Pull request merged**
