### PR TITLE
*: clear delta info when roll back transaction

### PR DESCRIPTION
**Pull request by lamxTyler**
PTAL @coocood @hanfei1991 @winoros

### CODE REVIEW

**Comment by hanfei1991** [comment]
LGTM

**Comment by shenli** [comment]
You should clean the delta data in session.go. https://github.com/pingcap/tidb/blob/master/session.go#L389

**Comment by lamxTyler** [comment]
It is already cleaned when we [PrepareTxnCtx](https://github.com/pingcap/tidb/blob/master/session.go#L409).

**Comment by coocood** [comment]
LGTM

**Pull request merged**
