### PR TITLE
session: add session scope for tidb_enable_clustered_index (#23704)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23704 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23711
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23711:release-5.0-3cf2bf912074
```

---

### What problem does this PR solve?

Problem Summary: To keep consistent between v5.0 and v5.0-rc, we should reserve the session scope of variable `tidb_enable_clustered_index`.

### What is changed and how it works?

What's Changed:

Add bootstrap version 68, upgrade the global variable `tidb_enable_clustered_index` value from `OFF` to `INT_ONLY`.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:!
- Need to cherry-pick to the release branch!

### Check List 

Tests 

- Unit test
- Integration test

Side effects

NA

### Release note 

- No release note

### CODE REVIEW

**Comment by morgo** [comment]
I noticed an issue in this PR :
```
{Scope: ScopeGlobal | ScopeSession, Name: TiDBEnableClusteredIndex, Value: IntOnly, Type: TypeEnum, PossibleValues: []string{Off, On, IntOnly, "1", "0"}},
```
It should be:
```
[]string{Off, On, IntOnly}
```

The sysvar system has normalization with enums, and 0/1 will get converted to the ordinal values of: OFF, ON.

**Comment by morgo** [comment]
It looks like the Enum was introduced in https://github.com/pingcap/tidb/pull/23529 by @lysu - maybe we can let this merge, and I will try and submit an improvement for master.

**Comment by lysu** [comment]
> It looks like the Enum was introduced in #23529 by @lysu - maybe we can let this merge, and I will try and submit an improvement for master.

ok thanks, my fault @morgo

**Comment by morgo** [comment]
For the thread, my followup PR is https://github.com/pingcap/tidb/pull/23719 
Because it will only be for master I refactored some related code as well.

**Comment by lysu** [comment]
> For the thread, my followup PR is #23719
> Because it will only be for master I refactored some related code as well.

thanks @morgo, maybe we will review later~(maybe in night because we are focus on GA testing and bugfix)

**Pull request merged**
