### PR TITLE
*: change field name 'password' to 'authentication_string' in mysql.user

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve? 
Fix a part of #9655.

### What is changed and how it works?
Change field name `password` to `authentication_string` in `mysql.user`.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has persistent data change

Side effects

 - __Breaking forward compatibility__: Running old version TiDB with new data will complain
```
["load mysql.user fail"] [error="[planner:1054]Unknown column 'password' in 'field list'"]
```

Related changes

 - Need to update the documentation

Release note

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM

**Comment by bb7133** [comment]
Hi @tangenta , please update the release note in this PR Description.

**Comment by tiancaiamao** [comment]
Please address conflicts @tangenta

**Comment by tiancaiamao** [comment]
LGTM

**Comment by siddontang** [comment]
@GregoryIan 

Does DM have the problem if sync MySQL 5.6/5.7 to the newest TiDB?

**Pull request merged**
