### PR TITLE
executor: add diagnosis rule to check Transparent Huge Pages(THP) enabled

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

related issue: https://github.com/pingcap/tidb/issues/19538

Enable Transparent Huge Pages(THP) in linux will affect the performance, This PR add a diagnose rule to check whethere THP is enabled.

example:

```sql
select * from `INSPECTION_RESULT` where rule='config';
+--------+------------------------------+------+----------------+-----------------+------------------------+------------------------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| RULE   | ITEM                         | TYPE | INSTANCE       | STATUS_ADDRESS  | VALUE                  | REFERENCE              | SEVERITY | DETAILS                                                                                                                                             |
+--------+------------------------------+------+----------------+-----------------+------------------------+------------------------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| config | transparent_hugepage_enabled | tidb | 10.0.2.15:4001 | 10.0.2.15:10081 | [always] madvise never | always madvise [never] | warning  | Transparent HugePages can cause memory allocation delays during runtime, TiDB recommends that you disable Transparent HugePages on all TiDB servers |
+--------+------------------------------+------+----------------+-----------------+------------------------+------------------------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- No

### Release note 

- add diagnosis rule to check Transparent Huge Pages(THP) enabled

### CODE REVIEW

**Comment by crazycs520** [comment]
@breeswish @lonng PTAL

**Review by lonng — DISMISSED** [review]
LGTM

**Review by breeswish — APPROVED** [review]

**Comment by breeswish** [comment]
Do we need cherry pick?

**Pull request merged**
