### PR TITLE
session,executor: tiny clean up the runStmt function

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Problem Summary:

Tiny clean up code after https://github.com/pingcap/tidb/pull/17678

### What is changed and how it works?

What's Changed:

- Clean up the old `runStmt`, use `runStmtWrap` to replace it.
- rename `CommonExec` to `preparedStmtExec` which is only used by ExecPreparedStmt
- unexport `CachedPlanExec` which is not used outside the session package

How it Works:

Clean up

### Check List 

Tests 

- No code

### Release note 

-  No release note

### CODE REVIEW

**Comment by tiancaiamao** [comment]
/run-all-tests

After a series of refactoring PRs, I am now satisified with the current `Execute*` API  in the session package.

PTAL @jackysp @coocood @lysu

**Comment by coocood** [comment]
LGTM

**Pull request merged**
