### PR TITLE
util/stmtsummary: remove import package tikv

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: AndreMouche

### What problem does this PR solve?
This PR  removes importing package "github.com/pingcap/tidb/store/tikv" in util/stmtsummary 

Part of https://github.com/pingcap/tidb/issues/22513

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Comment by zimulala** [comment]
Test failed issue: https://github.com/pingcap/tidb/issues/24787.

**Pull request merged**
