### PR TITLE
*: fix a bug causes indexed virtual generated column return wrong value and refine admin check table (#18408)

### LINKED ISSUE #17989: create index with multi-layer virtual generated column return wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql> create table t(a int, b tinyint as(a+1), c int as(b+1));
Query OK, 0 rows affected (0.01 sec)

mysql> set sql_mode="";
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t(a) values(2000);
Query OK, 1 row affected, 1 warning (0.01 sec)

mysql> create index idx on t(c);
Query OK, 0 rows affected (0.02 sec)

mysql> select c from t;
+------+
| c    |
+------+
| 2002 |
+------+
1 row in set (0.00 sec)

mysql> select * from t;
+------+------+------+
| a    | b    | c    |
+------+------+------+
| 2000 |  127 |  128 |
+------+------+------+
1 row in set, 1 warning (0.00 sec)
```

### 2. What did you expect to see? (Required)

```
mysql> select c from t;
+------+
| c    |
+------+
| 128 |
+------+
1 row in set (0.00 sec)
```
### 3. What did you see instead (Required)
2002
### 4. Affected version (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #17989 

Problem Summary:
1. Previously, we try to use `column substitution` to decode a multi-level virtual generated column, which is buggy. 
2. Since `admin check table` uses tableReader, and tableReader can output rows with a virtual generated column already, we don't need to compute it again. Besides, the previous implementation also suffered the above problem.
I’m 
### What is changed and how it works?

1. Build virtual expression for virtual generated column in `ColumnInfos2ColumnsAndNames`.
2. Remove `genExprs` in `checkIndexValue`.
3. In `compareData`, don't compute the virtual generated column again.
4. Export a function `rewriteAstExpr`, so that we can use `rewrite` in package expression.
5. Refine `buildPhysicalIndexLookUpReader`, make it simple.
6. Move ` table/tables/gen_expr_test.go → util/generatedexpr/gen_expr_test.go`. to avoid circular reference.

What's Changed:

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- Fix a bug causes indexed virtual generated column return wrong value and refine admin check table

### CODE REVIEW

**Comment by bb7133** [comment]
Please fix the CI

**Comment by djshow832** [comment]
Any conflicts?

**Comment by wjhuang2016** [comment]
> Any conflicts?

Cherry-pick from a middle commit. Because the previous commit contains clustered indexes stuffs.

**Pull request merged**
