### PR TITLE
Support JOIN hint for UPDATE/DELETE statements

### PR DESCRIPTION
**Pull request by coocood**
Cherry-picked from #6592 and #6626 
The first commit is included to avoid conflict.

### CODE REVIEW

**Comment by zz-jason** [comment]
@coocood we'd better cherry pick each commit in a single PR.

**Comment by coocood** [comment]
@zz-jason this is a special case

**Comment by coocood** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by zz-jason** [comment]
Why?

**Comment by coocood** [comment]
@zz-jason because the first commit doesn't worth a single cherry-pick.

**Comment by zz-jason** [comment]
.........

**Pull request merged**
