### PR TITLE
statistics: always tracking predicate columns

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/53567

Problem Summary:

### What changed and how does it work?

You can find the more detailed design here: https://github.com/pingcap/tidb/pull/53511

- Marked TiDBEnableColumnTracking and TiDBDisableColumnTrackingTime as deprecated.
- Always enable predicate column tracking.
- Removed use of EnableColumnTracking and TiDBDisableColumnTrackingTime.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] [Manual test](https://github.com/pingcap/tidb/pull/54152#issuecomment-2182123874)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Comment by hi-rustin** [comment]
Tested locally:
1. Start the TiDB cluster with patch: `tiup playground v8.1.0  --db.binpath /Volumes/t7/code/tidb/bin/tidb-server`
2. Try to set TiDBEnableColumnTracking: `set global tidb_enable_column_tracking = 0`
```sql
mysql> set global tidb_enable_column_tracking = 0
    -> ;
Query OK, 0 rows affected, 1 warning (0.01 sec)

mysql> show warnings;
+---------+------+----------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                |
+---------+------+----------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 1681 | The 'tidb_enable_column_tracking' variable is deprecated and will be removed in future versions of TiDB. It is always set to 'ON' now. |
+---------+------+----------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
3. Check its value: 
```sql
mysql> select @@tidb_enable_column_tracking;
+-------------------------------+
| @@tidb_enable_column_tracking |
+-------------------------------+
|                             1 |
+-------------------------------+
1 row in set (0.00 sec)
```
4. Create a table:
```sql
use test;
create table t(a int);
```
5. Select from the table: `select * from t where a = 1`
6. Check the predicate columns table:
```sql
select * from mysql.column_stats_usage;
mysql> select * from mysql.column_stats_usage;
+----------+-----------+---------------------+------------------+
| table_id | column_id | last_used_at        | last_analyzed_at |
+----------+-----------+---------------------+------------------+
|      104 |         1 | 2024-06-21 14:52:57 | NULL             |
+----------+-----------+---------------------+------------------+
1 row in set (0.01 sec)
```
7. Analyze the table: `analyze table t`
```sql
mysql> select * from mysql.analyze_jobs;
+----+---------------------+--------------+------------+----------------+--------------------------------------------------------------------+----------------+---------------------+---------------------+----------+-------------+----------------+------------+
| id | update_time         | table_schema | table_name | partition_name | job_info                                                           | processed_rows | start_time          | end_time            | state    | fail_reason | instance       | process_id |
+----+---------------------+--------------+------------+----------------+--------------------------------------------------------------------+----------------+---------------------+---------------------+----------+-------------+----------------+------------+
|  1 | 2024-06-21 14:55:13 | test         | t          |                | analyze table all columns with 256 buckets, 100 topn, 1 samplerate |              0 | 2024-06-21 14:55:13 | 2024-06-21 14:55:13 | finished | NULL        | 127.0.0.1:4000 |       NULL |
+----+---------------------+--------------+------------+----------------+--------------------------------------------------------------------+----------------+---------------------+---------------------+----------+-------------+----------------+------------+
1 row in set (0.00 sec)
```

**Review by hi-rustin — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by hi-rustin — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by qw4990 — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Review by fixdb — APPROVED** [review]
+1

**Pull request merged**
