### PR TITLE
server: try to make test TestAllServerInfo stable

### LINKED ISSUE #19075: http_handler_test.go:HTTPHandlerTestSerialSuite.TestAllServerInfo failed
http_handler_test.go:HTTPHandlerTestSerialSuite.TestAllServerInfo

```
[2020-08-07T04:29:16.678Z] ----------------------------------------------------------------------
[2020-08-07T04:29:16.678Z] FAIL: http_handler_test.go:1072: HTTPHandlerTestSerialSuite.TestAllServerInfo
[2020-08-07T04:29:16.678Z]
[2020-08-07T04:29:16.678Z] http_handler_test.go:1073:
[2020-08-07T04:29:16.678Z]     ts.startServer(c)
[2020-08-07T04:29:16.678Z] http_handler_test.go:369:
[2020-08-07T04:29:16.678Z]     c.Assert(err, IsNil)
[2020-08-07T04:29:16.678Z] ... value *errors.withStack = listen tcp 0.0.0.0:18506: bind: address already in use ("listen tcp 0.0.0.0:18506: bind: address already in use")
[2020-08-07T04:29:16.678Z]
```

 Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_check_2/44401/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/45618/display/redirect

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

fix #19075

image

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- No

### CODE REVIEW

**Comment by tangenta** [comment]
The function `newTestServerClient` does bind to port 0 internally.

**Comment by crazycs520** [comment]
> Suggest binding to port 0 (https://eklitzke.org/binding-on-port-zero) for a randomized port number, to solve this problem completely.
Great catch, but the test need to know the listening port to send requests. Binding to port `0` is ok, but it is a little bit hard to get the listening port for the test client.

**Pull request merged**
