### PR TITLE
binloginfo: fix CI in unit test TestMaxRecvSize

### PR DESCRIPTION
**Pull request by tiancaiamao**
`TestMaxRecvSize` failed because of some unexpected concurrency logic.
I adjust the test `TestIgnoreError` to avoid it.

```
Exec("insert...")   ...  it fails because we mock fail   @1

// our test begin
setIgnoreError()
MustExec("insert...")   ....  

// test finish, clean up
binloginfo.DisableSkipBinlogFlag()

// Well, there is a background 2pc clean up goroutine asynchronously, left by @1
// it set skipBinlog again !!
// Then TestMaxRecvSize fails
```

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL  @coocood

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
PTAL @zz-jason

**Pull request merged**
