### PR TITLE
executor: use MySQL compatible truncate error code

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
One error code had been changed from 1292 to 1525 in https://github.com/pingcap/tidb/pull/13300, to be consistent with its error message. But it may cause some compatibility issue.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Make the error code to be 1292 again.

How it Works:

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by jackysp** [comment]
All test passed with https://github.com/pingcap/tidb-test/pull/1005

**Comment by coocood** [comment]
LGTM

**Pull request merged**
