### PR TITLE
ddl: uncomment TODO lists in tests.

### LINKED ISSUE #18141: Make TestCancelJobByErrorCountLimit pass normally
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Uncomment TODO lines in TestCancelJobByErrorCountLimit, this test will be failed after the [#18003](https://github.com/pingcap/tidb/pull/18003).

### 2. What did you expect to see? (Required)

Pass this test.

### 3. What did you see instead (Required)

This test will be failed.

### 4. Affected version (Required)

After merge [#18003](https://github.com/pingcap/tidb/pull/18003).

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: close #18141, #18142, #18139, #18138, #18137, #18135, #18140 

Problem Summary:
After #18003 some tests are comment out. But some of these tests, because of, don't enable `failpoint`.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:
Uncomment these tests.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

-

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @tangenta @wjhuang2016

**Comment by tangenta** [comment]
Ok. Perhaps we should write a doc about "how to test a specific function" :sweat_smile:

**Comment by wjhuang2016** [comment]
> Ok. Perhaps we should write a doc about "how to test a specific function" 😅

Sure, most of the contributors don't know the command `make failpoint-enable`.

**Comment by zimulala** [comment]
> Ok. Perhaps we should write a doc about "how to test a specific function" 😅

Yes, I wanted to write a document before, but I don’t know where to put it.

**Pull request merged**
