### PR TITLE
parser: Add bytebase/bytebase as a user (#1360)

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: ref #28257

Problem Summary: There is only one commit to sync from the old parser repo.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
@xhebox I think the CLA check requires @tianzhou to sign the CLA in this repo?

**Comment by xhebox** [comment]
> @xhebox I think the CLA check requires @tianzhou to sign the CLA in this repo?

Yes, I missed that, but I want to keep the original author. @tianzhou, could you please sign the CLA?

**Comment by tianzhou** [comment]
Done

**Review by Defined2014 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
