### PR TITLE
*: add builtin function greatest

### PR DESCRIPTION
**Pull request by tiancaiamao**
https://github.com/pingcap/tidb/issues/1380

### CODE REVIEW

**Comment by shenli** [comment]
Do not forget handle greatest function in plan/typeinferer.go.

**Comment by tiancaiamao** [comment]
PTAL @shenli @zimulala  @coocood

**Comment by shenli** [comment]
LGTM
@zimulala @coocood PTAL

**Comment by coocood** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
