### PR TITLE
sessionctx/variable: fix potential timezone bugs

### PR DESCRIPTION
**Pull request by Rustin-Liu**
### What problem does this PR solve? 
#13626

### Check List 

Tests 

None

Code changes

None

Side effects

None

Related changes

None

Release note

None

### CODE REVIEW

**Comment by sticnarf** [comment]
//integration-common-test

**Comment by Rustin-Liu** [comment]
@sre-bot  /run-all-tests

**Comment by reafans** [comment]
lgtm

**Comment by Rustin-Liu** [comment]
@sre-bot  /run-integration-common-test

**Comment by Rustin-Liu** [comment]
@reafans It seems CI broken, PTAL~

**Comment by reafans** [comment]
@Rustin-Liu CI fixd.

**Comment by reafans** [comment]
@tangenta PTAL

**Comment by Rustin-Liu** [comment]
@sre-bot /run-all-tests

**Comment by Rustin-Liu** [comment]
@sre-bot /auto-merge

**Comment by Rustin-Liu** [comment]
@sre-bot /merge

**Comment by Rustin-Liu** [comment]
@sre-bot /run-auto-merge

**Comment by Rustin-Liu** [comment]
@sre-bot /run-all-tests

**Pull request merged**
