### PR TITLE
planner: migrate test-infra to testify for plan_stats_test

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: ref #26857

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by chrysan — APPROVED** [review]
LGTM

**Comment by hawkingrei** [comment]
@tisonkun PTAL

**Review by tisonkun — APPROVED** [review]
LGTM.

It seems a new test file out of tracked. But we can overcome it as long as we migrate tests faster than new tests introduced. However, it's better to notify the committers work on planner module to be aware of it.

**Review by winoros — APPROVED** [review]

**Review by AilinKid — COMMENTED** [review]
/merge

**Pull request merged**
