### PR TITLE
expression: get_lock/release_lock max len is chars

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/34639 close https://github.com/pingcap/tidb/issues/34735

Problem Summary:

The max len for get-lock should be based on char length, not byte length.
A NULL timeout was treated as the maximum timeout. This is incorrect, it should be the minimum.

### What is changed and how it works?

Fixes a bug for a developing feature. Improves mysql compatibility

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by morgo** [comment]
I have added a fix for https://github.com/pingcap/tidb/issues/34735 as well. It's a minor change, I must have observed the behavior wrong.

**Pull request merged**
