### PR TITLE
ebs-br: change command line flags of restore (#38027)

### LINKED ISSUE #38011: br: parameter rename for ebs snapshot backup and restore
## Bug Report
current implement for ebs snapshot backup restore for tide-operator
```
br backup full --type=aws-ebs/gcp-ps // backup from various snapshot
br restore full --meta-phase // restore metadata
br restore full --data-phase // restore cluster data
```

suggest change to 
```
br backup full --type=aws-ebs/gcp-ps // backup from various snapshot
br restore full --type=aws-ebs --prepare // i.e. current phase one
br restore full --type=aws-ebs // restore cluster data
```

we would like to remove phase concepts for  the feature
Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

kubectl logs backup_pod

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #38027 to release-6.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/38064
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/38064:release-6.3-0e3e44001b36
```

---

### What problem does this PR solve?

Issue Number: close #38011

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by fengou1 — APPROVED** [review]
/LGTM

**Review by 3pointer — APPROVED** [review]
LGTM

**Pull request merged**
