### PR TITLE
mockstore: fix typo

### PR DESCRIPTION
**Pull request by YKG**
Signed-off-by: YKG <yekaige2010@gmail.com>

### What problem does this PR solve?

Fix typo

Problem Summary:

### What is changed and how it works?

N/A

### Related changes

N/A

### Check List 

Tests 

- No code

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

**Review by AilinKid — COMMENTED** [review]
LGTM

**Comment by zz-jason** [comment]
thanks for your contribution, please fix go fmt to let this PR get merged.

**Comment by zz-jason** [comment]
@YKG please fix go fmt, you can run `make check` to quickly fix it.

**Comment by YKG** [comment]
Sorry but I can't make `make check` happy. When I switched to the current master branch(62354d04b7d94fc44d912b80cf7d433fb26abfd8) and run `make check`, I got:

```
azureuser@tidb:~/tidb$ make check
gofmt (simplify)
errcheck
unconvert check
linting
go mod tidy
./tools/check/check-tidy.sh
testSuite
./tools/check/check_testSuite.sh
tools/bin/golangci-lint run -v --disable-all --deadline=3m \
  --enable=misspell \
  --enable=ineffassign \
  $(go list ./...| grep -vE "cmd|github.com\/pingcap\/tidb\/tests" | sed 's|github.com/pingcap/tidb/||')
INFO [config_reader] Config search paths: [./ /home/azureuser/tidb/bindinfo /home/azureuser/tidb /home/azureuser /home /]
INFO [lintersdb] Active 2 linters: [ineffassign misspell]
INFO [loader] Go packages loading at mode 575 (compiled_files|deps|name|exports_file|files|imports|types_sizes) took 1.764007503s
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 234.331904ms
INFO [linters context/goanalysis] analyzers took 0s with no stages
INFO [runner] processing took 17.101µs with stages: nolint: 13.201µs, max_same_issues: 1.1µs, max_from_linter: 400ns, skip_dirs: 300ns, uniq_by_line: 300ns, path_prefixer: 200ns, max_per_file_from_linter: 200ns, path_prettifier: 200ns, diff: 200ns, filename_unadjuster: 200ns, skip_files: 100ns, path_shortener: 100ns, severity-rules: 100ns, autogenerated_exclude: 100ns, exclude-rules: 100ns, identifier_marker: 100ns, exclude: 100ns, cgo: 100ns, sort_results: 0s, source_code: 0s
INFO [runner] linters took 190.673656ms with stages: goanalysis_metalinter: 190.606155ms
INFO File cache stats: 0 entries of total size 0B
INFO Memory: 23 samples, avg is 89.1MB, max is 140.5MB
INFO Execution took 2.199225467s
vet
GO111MODULE=on go vet -all $(go list ./...| grep -vE "cmd|github.com\/pingcap\/tidb\/tests") 2>&1 | awk '{ print } END { if (NR > 0) { exit 1 } }'
# github.com/pingcap/tidb/util/hack
util/hack/hack.go:42:13: possible misuse of reflect.StringHeader
Makefile:83: recipe for target 'vet' failed
make: *** [vet] Error 1
azureuser@tidb:~/tidb$
```

**Pull request closed without merging**
