### PR TITLE
br: fix integration test cases with `--with-sys-table`

### LINKED ISSUE #39692: br_ghpr_unit_and_integration_test fails for v6.5.0
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/14331/pipeline/

### 2. What did you expect to see? (Required)
pass
### 3. What did you see instead (Required)
failed
### 4. What is your TiDB version? (Required)
v6.5.0

### PR DESCRIPTION
**Pull request by MoCuishle28**
Signed-off-by: zhanggaoming <gaoming.zhang@pingcap.com>

### What problem does this PR solve?

Issue Number: close #39692

Problem Summary:

### What is changed and how it works?
Fix integration test cases with `--with-sys-table`.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Manual test
case 1:
- br backup full
- In restore cluster, execute `alter table mysql.user add column xx int;`
- br restore full
- success

case 2:
- In backup cluster, execute `alter table mysql.user add column xx int;`
- br backup full
- br restore full
- failed, `Error: missing column in cluster data, table: user, col: xx int(11): [BR:Restore:ErrRestoreIncompatibleSys]incompatible system table`

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by MoCuishle28** [comment]
Integration test report:
```
tidb lightning encountered error: [Lightning:Restore:ErrRestoreTable]restore table `fail_fast`.`tb` failed: Error 1062 (23000): Duplicate entry '1-1' for key 'tb.uq'
```
Could this issue be introduced by `lightning`?

**Review by 3pointer — APPROVED** [review]

**Comment by fengou1** [comment]
LGTM

**Review by fengou1 — APPROVED** [review]

**Pull request merged**
