### PR TITLE
[FIX] Cleanup code

### PR DESCRIPTION
**Pull request by im-kulikov**

### CODE REVIEW

**Comment by im-kulikov** [comment]
Hm.. I can't understand, where is mistake.. 
Strangely. I didn't edit the files where there was an error on Travis side.

**Comment by im-kulikov** [comment]
@zhexuany hi. Can you help me with this errors - https://travis-ci.org/pingcap/tidb/builds/339899824?utm_source=github_status&utm_medium=notification

**Comment by im-kulikov** [comment]
@winoros oh.. thanks 🙏

**Comment by im-kulikov** [comment]
Is it any changes for merging?

**Comment by ngaut** [comment]
Sure @im-kulikov

**Comment by im-kulikov** [comment]
Yeah) tests passed

**Comment by im-kulikov** [comment]
Looks like all is fine..
@ngaut What should I do next?

**Comment by im-kulikov** [comment]
any updates?

**Comment by shenli** [comment]
@im-kulikov The unit-test failed. I got this from the circleci:
```
----------------------------------------------------------------------
FAIL: builtin_cast_test.go:227: testEvaluatorSuite.TestCastFuncSig

builtin_cast_test.go:743:
    c.Assert(res.String(), Equals, t.after.String())
... obtained string = "2018-02-12 12:59:59"
... expected string = "2018-02-11 12:59:59"
----------------------------------------------------------------------
```
I thought this is related with timezone. Which timezone are you in? @tiancaiamao Please help kulikov to solve this.

**Comment by shenli** [comment]
@im-kulikov We just fixed an issue in the unit test. I re-run the CI.

**Comment by im-kulikov** [comment]
@shenli as I see, tests passed?

**Comment by im-kulikov** [comment]
> I thought this is related with timezone. Which timezone are you in? 

Europe/Moscow (Saint Petersburg)..

**Comment by tiancaiamao** [comment]
Files in vendor directory is from other projects, do not edit them. @im-kulikov

**Comment by im-kulikov** [comment]
@tiancaiamao I'm not edit any vendor-files.. just run dep ensure...

**Comment by tiancaiamao** [comment]
Maybe we forget to specify some of the package version in Gopkg.toml.
We make small changes to ensure each PR is viewable, and we usually update vendor in a separate PR.
You can try `git checkout master vendor` to revert those unrelated changes.

**Comment by im-kulikov** [comment]
@tiancaiamao hm.. okay

**Comment by tiancaiamao** [comment]
LGTM

**Comment by im-kulikov** [comment]
my first so slowest PR 🙂

**Comment by shenli** [comment]
LGTM
@im-kulikov Sorry for the late review. It is Chinese Spring Festival now. So most of us are on vacation.

**Comment by im-kulikov** [comment]
@shenli oh.. no problem 🙂

Congratulate you with "Chinese Spring Festival"  🎉🎉🎉

**Comment by shenli** [comment]
@im-kulikov Thanks for your PR and Thanks for your greetings. :)

**Comment by im-kulikov** [comment]
@shenli  😉

**Pull request merged**
