### PR TITLE
ddl: support truncate partition for label rules 

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/26836

### What is changed and how it works?

What's Changed: 

- update label rules for the truncated partitions

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (https://github.com/pingcap/endless/pull/38/commits/777adb6914dae91ffa02c10f24dd289e5392024d)
- [ ] No code

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [x] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]
lgtm

**Review by xhebox — APPROVED** [review]
Same as https://github.com/pingcap/tidb/pull/27102#pullrequestreview-742386183, the PR LGTM, but may need further refactor.

**Pull request merged**
