### PR TITLE
planner/core: fix privilege check for grant on table (#9828)

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry pick from https://github.com/pingcap/tidb/pull/9828

### CODE REVIEW

**Comment by tiancaiamao** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

PTAL @shenli @jackysp

**Comment by tiancaiamao** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by jackysp** [comment]
Please fix CI.

**Comment by tiancaiamao** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
