### PR TITLE
test: fix unit test and make test running serially.

### LINKED ISSUE #16328: executor_test.go:testSuiteP2.TestCurrentTimestampValueSelection failed
executor_test.go:testSuiteP2.TestCurrentTimestampValueSelection

Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/31713/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_check_2/31223/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_check_2/31152/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/31697/display/redirect

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve?

Issue Number: close #16328 

Problem Summary: UT fails. Root cause is running unit test parallelly (some prepare plan cache test.)

### What is changed and how it works?

What's Changed:  Run test serially.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### CODE REVIEW

**Comment by wshwsh12** [comment]
> `preparedPlanCache` is in session level, each test is supposed to use a new TestKit, which would have its own session, why would they interfere with each other?

`preparedPlanCacheEnabledValue` is used for all session.  If one test changes the value, the other session will be affected.

**Comment by zz-jason** [comment]
@wshwsh12 Does the release branches have this issue?

**Comment by zz-jason** [comment]
Would it impact the UT testing speed? cc @glorv

**Comment by glorv** [comment]
> Would it impact the UT testing speed? cc @glorv

These tests are fast, so the impact is small and acceptable

**Pull request merged**
