### PR TITLE
statistics: reduce small obj alloc for PreCalculateScalar

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/52343

Problem Summary:

We don't need to re-alloc anything since we only read from the chunk, no modification after reading it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
I'm not very familiar with these structures.
Is it safe to reuse? Are there other places that use it in this way?
If it is, please add some comments to note that we trying to rescue it to save memory here.

**Comment by winoros** [comment]
> I'm not very familiar with these structures. Is it safe to reuse? Are there other places that use it in this way? If it is, please add some comments to note that we trying to rescue it to save memory here.

You can jump into the func `convertDatumToScalar`, which calculates a float64 score for the datum. So the datum is read-only before it's destroyed.

**Review by hi-rustin — APPROVED** [review]
/hold

Please add some comments to it.

**Pull request merged**
