### PR TITLE
docs: update roadmap

### PR DESCRIPTION
**Pull request by ran-huang**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary: mark **Optimize resource isolation in heavy (batch) write scenarios** as a delivered feature in roadmap

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by yiwen92** [comment]
thx for update, LGTM

**Review by SunRunAway — APPROVED** [review]

**Pull request merged**
