### PR TITLE
ddl: fix drop multiple partitions with global index

### LINKED ISSUE #46907: ddl: drop multiple partitions for a table with global index causes ddl panic
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
use test;
drop table if exists test_global;
create table test_global ( a int, b int, c int)
	partition by range( a ) (
		partition p1 values less than (10),
		partition p2 values less than (20),
		partition p3 values less than (30)
	);
Alter Table test_global Add Unique Index idx_b (b);
INSERT INTO test_global VALUES (1, 1, 1), (2, 2, 2), (11, 3, 3), (12, 4, 4), (21, 21, 21), (29, 29, 29);
alter table test_global drop partition p1, p2;  -- ddl panic here
```

### 2. What did you expect to see? (Required)
execute success
### 3. What did you see instead (Required)
ddl panic
image

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by L-maple**
### What problem does this PR solve?

Issue Number: close #46907

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by okJiang — APPROVED** [review]

**Review by mjonss — APPROVED** [review]

**Comment by mjonss** [comment]
@L-maple could you please try the tests TestDistFrameworkMeta, TestFailSchemaSyncer?
it seems like they are failing (both in CI and on my environment).

**Comment by L-maple** [comment]
> @L-maple could you please try the tests TestDistFrameworkMeta, TestFailSchemaSyncer? it seems like they are failing (both in CI and on my environment).
TestDistFrameworkMeta, TestFailSchemaSyncer are ok on my mac and have nothing related with my PR.

I see the test TestMemTracker4InsertAndReplaceExec  failed in CI. But It seems have nothing related with my PR, and it fails on my previous PR. 
image

**Comment by okJiang** [comment]
@L-maple Maybe you can pull the latest code and retest. If you encounter some unstable test cases not related to your pr, you can comment `/retest` to trigger test.

**Comment by mjonss** [comment]
@L-maple please merge the latest pingcap/master branch, it contains some test updates that is currently failing CI in this branch.

**Pull request merged**
