### PR TITLE
planner: fix wrong request data type when pushing down avg aggfuncs

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve? 

When runing two `avg()` in one sql, the request types of aggfuncs in DAGRequest maybe wrong. (Now tikv can work well, because of it has type deduction and ignore the wrong infomation.)

### What is changed and how it works?

Add a  cursor to choose the right schema column.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

### CODE REVIEW

**Comment by winoros** [comment]
Is it hard to add unit test?

**Comment by wshwsh12** [comment]
> Is it hard to add unit test?

Yes, I don't know how to add unit test. Any idea?

**Comment by XuHuaiyu** [comment]
We can build the plan refer to [this](https://github.com/pingcap/tidb/blob/master/planner/core/physical_plan_test.go#L700-L705).
Then iterate the plan tree and fetch the aggregation operator.

**Comment by wshwsh12** [comment]
I add unit test . PTAL @zz-jason @winoros @lzmhhh123

**Pull request merged**
