### PR TITLE
ddl: check tablename if end with em space

### PR DESCRIPTION
**Pull request by zhaoxiaojie0415**
### What problem does this PR solve? 
fix issue #7764 

### What is changed and how it works?
check if tablename end with em space

### Check List 

Tests 

 - Unit test
 

Code changes

 - Has exported function/method change
 
Related changes

### CODE REVIEW

**Comment by jackysp** [comment]
Thanks @zhaoxiaojie0415 ! Please sign the CLA first and then fix CI.
/ok-to-test

**Comment by jackysp** [comment]
I think the current TiDB behavior is compatible with MySQL. It seems we do not need to fix it.
Please try it yourself in MySQL. @zhaoxiaojie0415

**Comment by jackysp** [comment]
I think the current TiDB behavior is compatible with MySQL. It seems we do not need to fix it.
Please try it yourself in MySQL. @zhaoxiaojie0415

**Comment by zhaoxiaojie0415** [comment]
> I think the current TiDB behavior is compatible with MySQL. It seems we do not need to fix it.
> Please try it yourself in MySQL. @zhaoxiaojie0415

Indeed as you say, In MySQL we can create a empty table by using em space as name.

**Comment by jackysp** [comment]
@zhaoxiaojie0415 , I'll close this pr. Thanks for your contribution!

**Pull request closed without merging**
