### PR TITLE
show: fix variable scope error

### PR DESCRIPTION
**Pull request by mccxj**
tidb
```
MySQL [(none)]>  set session sql_select_limit=100000000000;
Query OK, 0 rows affected (0.00 sec)

MySQL [(none)]> show global variables  where variable_name='sql_select_limit';
+------------------+--------------+
| Variable_name    | Value        |
+------------------+--------------+
| sql_select_limit | 100000000000 |
+------------------+--------------+
1 row in set (0.00 sec)

MySQL [(none)]> show session variables  where variable_name='sql_select_limit';
+------------------+--------------+
| Variable_name    | Value        |
+------------------+--------------+
| sql_select_limit | 100000000000 |
+------------------+--------------+
1 row in set (0.00 sec)

```

mysql
```
MySQL [(none)]> set session sql_select_limit=100000000000
    -> ;
Query OK, 0 rows affected (0.00 sec)

MySQL [(none)]> show session variables  where variable_name='sql_select_limit';
+------------------+--------------+
| Variable_name    | Value        |
+------------------+--------------+
| sql_select_limit | 100000000000 |
+------------------+--------------+
1 row in set, 1 warning (0.01 sec)

MySQL [(none)]> show global variables  where variable_name='sql_select_limit';
+------------------+----------------------+
| Variable_name    | Value                |
+------------------+----------------------+
| sql_select_limit | 18446744073709551615 |
+------------------+----------------------+
1 row in set, 1 warning (0.01 sec)
```

### CODE REVIEW

**Comment by shenli** [comment]
@mccxj Thanks!

**Comment by mccxj** [comment]
When I was working on issue #5126, I found that the globalscope flag is missed by mistake. 

some variables have both globalscope and sessionscope are stored at one location(system map object), it seems chaos.

**Comment by XuHuaiyu** [comment]
hi, @mccxj 
Are you working on issue #5126 ?
I'm working on this now, and the PR can be pushed today.

**Comment by mccxj** [comment]
@XuHuaiyu Please go on.

**Comment by shenli** [comment]
@mccxj CI is fixed. Please add a unit test case for this PR.

**Comment by XuHuaiyu** [comment]
refer #5297

**Comment by zimulala** [comment]
Please add some unit tests to `TestGlobalVarAccessor` in new_session_test.go

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
