### PR TITLE
store: migrate test-infra to testify

### LINKED ISSUE #27655: migrate test-infra to testify for `store_test.go` & `batch_coprocessor_test.go`

### LINKED ISSUE #27855: tidb returns 'Unknown auth plugin' when some old clients didn't set auth plugin in login request
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Use a mysql 5.1 client to connect tidb 5.2

### 2. What did you expect to see? (Required)

Connect success

### 3. What did you see instead (Required)

TiDB returns "1105 Unknown auth plugin" error.

### 4. What is your TiDB version? (Required)
v5.2.0

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

### What problem does this PR solve?

Issue Number: close #27655 

### Release note

```release-note
None
```

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by tisonkun** [comment]
/assign @disksing 

could you please help on merging this PR?

**Pull request merged**
