### PR TITLE
expression: fix week func format (#9685)

### PR DESCRIPTION
**Pull request by zyycj**
### What problem does this PR solve? 

Cherry-pick #9685 to Release-2.1

### What is changed and how it works?

See #9685 

### Check List

Tests

 - Unit test
 - Integration test
 - Manual test

### CODE REVIEW

**Comment by zyycj** [comment]
Checksum `go.sum` failed in my local env. So I rm the file and rebuild it again, and works fine on my laptop. But it seems that can't pass the CI test.

**Comment by morgo** [comment]
@zyycj what is your local go version?  TiDB 2.1 is intended to be built with 1.11.3.

If you remove `go.sum` and `tools/check/go.sum` from your commit it should work.

**Comment by zyycj** [comment]
@morgo My go version is 1.12. I remove the files and it seems to work.

**Comment by erjiaqing** [comment]
Question:
Can we merge `builtinWeekWithModeSig` and `builtinWeekWithoutModeSig` into one single function?

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
