### PR TITLE
resource_control: update static calibrate params

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: ref #43212

Problem Summary:

### Check List

Tests 

- [x] Unit test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
- The previous test data due to non-exclusive hard disk, io bandwidth is not full, so the tikv is not the bottleneck, the bottleneck is tidb.
But because tidb is easy to expand, tikv is more difficult to expand, so generally tikv is easy to bottleneck
Now the test data are basically playing full tikv, may be slightly more accurate
- cpu formula is ms, the previous calculation forgot to multiply by 1000
```

### CODE REVIEW

**Comment by HuSharp** [comment]
@glorv @CabinfeverB @nolouch PTAL, thx!

**Review by nolouch — COMMENTED** [review]
Why need change them?

**Comment by HuSharp** [comment]
> Why need change them?

- The previous test data due to non-exclusive hard disk, io bandwidth is not full, so the tikv is not the bottleneck, the bottleneck is tidb.
	But because tidb is easy to expand, tikv is more difficult to expand, so generally tikv is easy to bottleneck.
	Now the test data are basically playing full tikv, may be slightly more accurate.
- cpu formula is ms, the previous calculation forgot to multiply by 1000. @nolouch

**Comment by HuSharp** [comment]
maybe stale data

**Pull request closed without merging**
