### PR TITLE
executor: fix aggregating enum zero value gets different results from mysql 

### LINKED ISSUE #26885: Aggregating enum zero value gets different results from mysql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
drop table t1;
CREATE TABLE t1 (c1 ENUM('a', '', 'b'));
INSERT INTO t1 (c1) VALUES ('b');
INSERT INTO t1 (c1) VALUES ('');
INSERT INTO t1 (c1) VALUES (0);
INSERT INTO t1 (c1) VALUES ('');
SELECT c1 + 0, COUNT(c1) FROM t1 GROUP BY c1 order by c1;
```
This situation can only occur with the following conditions:
1. Enum type has '' name field.
2. Illegal value/zero value is inserted in the data.
So I think this problem is not very serious..

### 2. What did you expect to see? (Required)
```
MySQL [test]> SELECT c1 + 0, COUNT(c1) FROM t1 GROUP BY c1 order by c1;
+--------+-----------+
| c1 + 0 | COUNT(c1) |
+--------+-----------+
|      0 |         1 |
|      2 |         2 |
|      3 |         1 |
+--------+-----------+
3 rows in set (0.000 sec)
```
### 3. What did you see instead (Required)
```
[tidb]> SELECT c1 + 0, COUNT(c1) FROM t1 GROUP BY c1 order by c1;
+--------+-----------+
| c1 + 0 | COUNT(c1) |
+--------+-----------+
|      2 |         3 |
|      3 |         1 |
+--------+-----------+
2 rows in set (0.001 sec)
```

// Different insert order will get different result. If I insert values(0) first, the result will be following:
```
[tidb]> SELECT c1 + 0, COUNT(c1) FROM t1 GROUP BY c1 order by c1;
+--------+-----------+
| c1 + 0 | COUNT(c1) |
+--------+-----------+
|      0 |         3 |
|      3 |         1 |
+--------+-----------+
2 rows in set (0.001 sec)
```
### 4. What is your TiDB version? (Required)
master, v5.0 v5.1, v4.0

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: close #26885

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by ywqzzy** [comment]
changes in mysql-test: https://github.com/pingcap/tidb-test/pull/1896

**Review by wshwsh12 — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Pull request merged**
