### PR TITLE
ddl: fix concurrent access to `do.infoHandle` has a data race error

### PR DESCRIPTION
**Pull request by ciscoxll**
Cherry pick #8287

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8464)

### CODE REVIEW

**Comment by winkyao** [comment]
This PR  need to cherry-pick to 2.0?

**Comment by ciscoxll** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by ciscoxll** [comment]
@crazycs520 PTAL

**Pull request merged**
