### PR TITLE
ddl/ddl_test.go: refactor testNewDDLAndStart to return error

### PR DESCRIPTION
**Pull request by clovis1122**
By returning an error instead of performing assertion, it allows the calleer to decide how to handle the errors.

This is also helpful when the caller wants more flexibility with the assertion (using check Vs require).

### What problem does this PR solve?

Issue Number:

Problem Summary:

### What is changed and how it works?
It refactors `testNewDDLAndStart` so that it no longer accept a check argument. Instead, it will return an error.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by clovis1122** [comment]
@tisonkun can I get a review on this?

**Review by xhebox — APPROVED** [review]

**Comment by xhebox** [comment]
> @tisonkun can I get a review on this?

Much easier. It is really hard to review that large PR.

**Comment by bb7133** [comment]
Thanks for your contribution!

**Comment by bb7133** [comment]
LGTM

**Review by bb7133 — APPROVED** [review]

**Comment by clovis1122** [comment]
Ah looks like the same test is failing with the following error:

```
[2021-11-21T20:35:07.606Z]         	Test:       	TestAdminCheckTable

[2021-11-21T20:35:07.606Z]         	Messages:   	sql:admin check table t1, [], error stack failpoint panic: ERROR 1105 (HY000): Out Of Memory Quota![conn_id=1]
```

Doesn't sound like a code-related change... what should I do?

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
