### PR TITLE
executor: fix data race

### PR DESCRIPTION
**Pull request by hanfei1991**
we should close result and set null after fetch handles has done.

@shenli @coocood @zimulala PTAL

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
@hanfei1991 What you do in this PR is not the same with the description.

**Comment by zhexuany** [comment]
I am confused too. fixed data race is not the description for this PR.

**Comment by shenli** [comment]
@hanfei1991 Any update?

**Comment by hanfei1991** [comment]
`result.Close` is called after task channel has closed. @shenli

**Comment by shenli** [comment]
LGTM

**Pull request merged**
