### PR TITLE
executor: fix incorrect result of enum type merge join

### LINKED ISSUE #24473: The result of inl_merge_join with the enum type join column is wrong
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE `x` (
  `a` enum('y','b','1','x','0','null') DEFAULT NULL,
  KEY `a` (`a`)
);
insert into x values("x"),("x"),("b"),("y");
SELECT /*+ inl_merge_join (t2,t3) */ t2.a,t3.a FROM x t2 inner join x t3 on t2.a = t3.a;
```
The plan is
```
+-----------------------------+---------+-----------+----------------------+-----------------------------------------------------------------------+
| id                          | estRows | task      | access object        | operator info                                                         |
+-----------------------------+---------+-----------+----------------------+-----------------------------------------------------------------------+
| IndexMergeJoin_18           | 5.00    | root      |                      | inner join, inner:IndexReader_16, outer key:rs.x.a, inner key:rs.x.a  |
| ├─IndexReader_31(Build)     | 4.00    | root      |                      | index:IndexFullScan_30                                                |
| │ └─IndexFullScan_30        | 4.00    | cop[tikv] | table:t2, index:a(a) | keep order:false, stats:pseudo                                        |
| └─IndexReader_16(Probe)     | 1.25    | root      |                      | index:Selection_15                                                    |
|   └─Selection_15            | 1.25    | cop[tikv] |                      | not(isnull(rs.x.a))                                                   |
|     └─IndexRangeScan_14     | 1.25    | cop[tikv] | table:t3, index:a(a) | range: decided by [eq(rs.x.a, rs.x.a)], keep order:true, stats:pseudo |
+-----------------------------+---------+-----------+----------------------+-----------------------------------------------------------------------+
```
### 2. What did you expect to see? (Required)
```
+------+------+
| a    | a    |
+------+------+
| y    | y    |
| b    | b    |
| x    | x    |
| x    | x    |
| x    | x    |
| x    | x    |
+------+------+
```
### 3. What did you see instead (Required)
```
+------+------+
| a    | a    |
+------+------+
| y    | y    |
+------+------+
```
### 4. What is your TiDB version? (Required)

Release Version: v4.0.0-beta.2-2807-g289dcfefd-dirty
Edition: Community
Git Commit Hash: 289dcfefdd159345972f71cf42c9d6e594255290
Git Branch: master
UTC Build Time: 2021-05-06 15:11:16
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: close #24473  

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
- executor/index_lookup_merge_join_test.go
- expression/builtin_compare.go

How it Works:
fix wrong compare func to enum type.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects
Maybe fix parser is a better way, but i'm not sure what's that means:
```go
	case mysql.TypeEnum, mysql.TypeSet:
		if ft.Flag&mysql.EnumSetAsIntFlag > 0 {
			return ETInt
		}
	}
```

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by wshwsh12** [comment]
Please add an test case. 
```
drop table t1,t2;

create table t1(e enum("a"),index idx(e));
create table t2(e enum("b"),index idx(e));
insert into t1 values(1);
insert into t2 values(1);
desc select /*+ merge_join(t1,t2) */ * from t1, t2 where t1.e=t2.e;
```

**Comment by sylzd** [comment]
It’s literally  conflic with #18850 in logical, what do we do? @winoros  @wshwsh12

**Comment by sylzd** [comment]
> Please add a test case.
> 
> ```
> drop table t1,t2;
> 
> create table t1(e enum("a"),index idx(e));
> create table t2(e enum("b"),index idx(e));
> insert into t1 values(1);
> insert into t2 values(1);
> desc select /*+ merge_join(t1,t2) */ * from t1, t2 where t1.e=t2.e;
> ```

yeah, it's the similar issue with #18850

**Review by winoros — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]

**Pull request merged**
