### PR TITLE
executor: fix data race in oomtest

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### What is changed and how it works?

fix data race in oomtest

```
 WARNING: DATA RACE
Write at 0x00c000698cd0 by goroutine 61:
  github.com/pingcap/tidb/executor/oomtest.(*oomCapture).Write()
      /go/tidb/executor/oomtest/oom_serial_test.go:199 +0xb4
  go.uber.org/zap/zapcore.(*CheckedEntry).Write()
      /home/prow/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/entry.go:220 +0x2ba
  go.uber.org/zap.(*Logger).Info()
      /home/prow/go/pkg/mod/go.uber.org/zap@v1.19.1/logger.go:192 +0x6a
  github.com/pingcap/tidb/ddl.(*ddl).addBatchDDLJobs()
      /go/tidb/ddl/ddl_worker.go:313 +0x73c
  github.com/pingcap/tidb/ddl.(*ddl).limitDDLJobs()
      /go/tidb/ddl/ddl_worker.go:271 +0x1b8
  github.com/pingcap/tidb/ddl.(*ddl).Start·dwrap·12()
      /go/tidb/ddl/ddl.go:351 +0x39
Previous read at 0x00c000698cd0 by goroutine 63:
  github.com/pingcap/tidb/executor/oomtest.TestMemTracker4UpdateExec()
      /go/tidb/executor/oomtest/oom_serial_test.go:65 +0x284
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47 
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
@time-and-fate @tisonkun @tangenta @wjhuang2016 PTAL

**Review by qw4990 — APPROVED** [review]

**Review by time-and-fate — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]
/merge

**Pull request merged**
