### PR TITLE
br/lightning: add basicConstraints to test ca

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/50150

Problem Summary:

### What changed and how does it work?
- v3 CA requires basic constraints ext `CA:TRUE` exists for self-signed root ca, else it reports `x509: invalid signature: parent certificate cannot sign this kind of certificate`
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [x] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by D3Hunter** [comment]
/hold
wait ci

**Comment by D3Hunter** [comment]
pass https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_lightning_integration_test/detail/pull_lightning_integration_test/18/pipeline

**Comment by Benjamin2037** [comment]
Whether this pr related any issue?

**Comment by Benjamin2037** [comment]
> > Whether this pr related any issue?
> 
> without this, we cannot run lightning ci locally

What I mean is which GitHub issue related to the PR？

**Comment by lance6716** [comment]
@Benjamin2037 updated, PTAL

**Comment by D3Hunter** [comment]
@GMHDBJD ptal

**Review by YuJuncen — APPROVED** [review]

**Pull request merged**
