### PR TITLE
br: Fix typo in br

### PR DESCRIPTION
**Pull request by joccau**
### What problem does this PR solve?
Fix typo

Tests 

- [x] Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Comment by kennytm** [comment]
(what is the definition of `size/XS` 🌚 how is this PR not `size/XS` 🌚)

**Comment by joccau** [comment]
> (what is the definition of `size/XS` 🌚 how is this PR not `size/XS` 🌚)

Previously I think that it indicates the size of the clothes, like S/M/L/XL/XXL/XXXL. 
But I doubt it Now~

**Comment by tisonkun** [comment]
@kennytm @joccau the rules come from [here](https://book.prow.tidb.io/#/plugins/size). But I don't like these tags actually. One line change could be significant, while size/XXL can be global find and replace. It provides false positive and actually well tagged `component` labels plus PR title should help reviewers to find interesting PRs.

**Review by tangenta — APPROVED** [review]

**Pull request merged**
