### PR TITLE
tidb: add a metric for logging system time backward jump

### PR DESCRIPTION
**Pull request by overvenus**
Add a metric for logging system time backward jump. Also remove a `log.Error()`, package systimemon logs the error too.

PTAL @shenli @siddontang

### CODE REVIEW

**Comment by shenli** [comment]
Should we keep the log? Not all users will deploy metrics system.

**Comment by overvenus** [comment]
@shenli systimemon logs the error already. https://github.com/ngaut/systimemon/blob/405356dee987ebcee88c8b18bac79e471a096a03/systime_mon.go#L19

**Comment by shenli** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Pull request merged**
