### PR TITLE
CI: adjust the codecov statuses to make it not affect the PR or branch commit status

### PR DESCRIPTION
**Pull request by wuhuizuo**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### What is changed and how it works?

- update ignore paths for coverage.
- make the codecov results just as informations in github statuses on components and flags level, will not failed the statuses.

Total project level was disabled before(ref #46232).

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [x] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by wuhuizuo** [comment]
Test results
===

## For PR
### Before
image

### After
image

## For branch pushing

### Before
image

### After
image

**Comment by wuhuizuo** [comment]
/cc @bb7133 
PTAL

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by Defined2014 — APPROVED** [review]

**Comment by wuhuizuo** [comment]
The repository [setting](https://app.codecov.io/gh/pingcap/tidb/settings) will be updated delayed for several hours by codecov.io server.

**Pull request merged**
