### PR TITLE
privileges: grant privilege identified by password should be hash string

### LINKED ISSUE #4196: grant privilege identified by password should be hash string
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

In MySQL, it's invalid:

```
mysql> grant select on *.* to 'genius'@'%' identified by password '0101001';
ERROR 1827 (HY000): The password hash doesn't have the expected format. Check if the correct password algorithm is being used with the PASSWORD() function.
```

2. What did you expect to see?

According to [mysql document](https://dev.mysql.com/doc/refman/5.7/en/grant.html#grant-accounts-passwords), grant privilege identified by password should be hash string.

3. What did you see instead?

TiDB accept the input `grant select on *.* to 'genius'@'%' identified by password '0101001';`

4. What version of TiDB are you using (`tidb-server -V`)?

### PR DESCRIPTION
**Pull request by buggithubs**
fix #4196 

PTAL  @tiancaiamao 

### test case

The test is consistent with version 5.7 of MySQL

```
grant select on *.* to 'genius1'@'%' identified by password '123123'; 	
ERROR 1827 (HY000): The password hash doesn't have the expected format. Check if the correct password algorithm is being used with the PASSWORD() function.
```

```
grant select on *.* to 'genius2'@'%' identified by password '*E56A114692FE0DE073F9A1DD68A00EEB9703F3F';
ERROR 1827 (HY000): The password hash doesn't have the expected format. Check if the correct password algorithm is being used with the PASSWORD() function
```

```
grant select on *.* to 'genius3'@'%' identified by password '*E56A114692FE0DE073F9A1DD68A00EEB9703F3F1'; 
Query OK, 0 rows affected, 2 warnings (0.01 sec)
```

```
grant select on *.* to 'genius4'@'%' identified by password '0E56A114692FE0DE073F9A1DD68A00EEB9703F3F9'; 
ERROR 1827 (HY000): The password hash doesn't have the expected format. Check if the correct password algorithm is being used with the PASSWORD() function.
```

```
grant select on *.* to 'genius5'@'%' identified by password '*E56A114692FE0DE073F9A1DD68A00EEB9703F3XX'; 
Query OK, 0 rows affected, 2 warnings (0.01 sec)
```

### CODE REVIEW

**Comment by zz-jason** [comment]
@buggithubs you can run `make check` to format the code

**Comment by shenli** [comment]
@buggithubs Please fix CI.

**Comment by buggithubs** [comment]
@zz-jason Thanks for reminding
@shenli  Complete repair

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
