### PR TITLE
expression: handle max_allowed_packet warnings for to_base64 function.

### PR DESCRIPTION
**Pull request by supernan1994**
### What problem does this PR solve? 
cherrypick #7266 (from commit 016006f) to release-2.0

### What is changed and how it works?
Return NULL and a warning when the result of to_base64 exceeds max_allowed_packetbs.

### Check List 

Tests 
 - Unit test

Related changes
 - Need to be included in the release note
```
release note:
handle `max_allowed_packet` warnings for `TO_BASE64` function
```

### CODE REVIEW

**Comment by supernan1994** [comment]
/run-all-tests tikv=release-2.0 pd=release-2.0 tidb-test=release-2.0

**Comment by supernan1994** [comment]
@zz-jason PTAL

**Comment by zz-jason** [comment]
@supernan1994 LGTM! Thanks for your contribution!

**Comment by zz-jason** [comment]
@crazycs520 @XuHuaiyu PTAL

**Pull request merged**
