### PR TITLE
fix `str_to_date` func compatible issues 9773

### PR DESCRIPTION
**Pull request by b41sh**
### What problem does this PR solve? 
Fix the problem that `str_to_date` is not compatible with MySQL

fix [#9773](https://github.com/pingcap/tidb/issues/9773)

### What is changed and how it works?

keep format '%H' without '%p'

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by b41sh** [comment]
@zz-jason Already added

**Comment by zz-jason** [comment]
@b41sh Could you help us to cherry pick this change to release 2.1?

**Comment by b41sh** [comment]
ok

**Pull request merged**
