### PR TITLE
executor: fix panic when granting privilege to a non-exists user

### LINKED ISSUE #35310: runtime error: invalid memory address or nil pointer dereference (Maybe not a bug)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
SET sql_mode="";
GRANT ALL PRIVILEGES ON *.* to '???';
```

### 2. What did you expect to see? (Required)

```
Query OK, 0 rows affected (0.00 sec)
ERROR 1410 (42000): You are not allowed to create a user with GRANT
```

### 3. What did you see instead (Required)

```
Query OK, 0 rows affected (0.00 sec)
ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference
```

### 4. What is your TiDB version? (Required)

```
Release Version: v6.2.0-alpha-97-g06737ecd2
Edition: Community
Git Commit Hash: 06737ecd29b0ae633d9ac89b0660e7a43939c88d
Git Branch: master
UTC Build Time: 2022-06-11 07:47:16
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
Store: unistore
```

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

Issue Number: close #35310

Problem Summary:

When `sql_mode` doesn't contain `NO_AUTO_CREATE_USER` and the grant statement doesn't contain a password, TiDB will panic because of a previous PR that supports auth-plugin.

### What is changed and how it works?

Check nil.

### Check List

Tests 

- [x] Unit test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by zimulala** [comment]
PTAL @tiancaiamao

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
