### PR TITLE
planner: refactor 'Can't find column' panic to error

### PR DESCRIPTION
**Pull request by zz-jason**
### What problem does this PR solve? 

A tiny refactor, as the title said.

### What is changed and how it works?

Return the error to client if a column can not be found in a schema instead of just panic.

Once the client received this error, it's probably that the TiDB planner works incorrectly. Returning error reveals this problem to the client, keeps the session unbroken.

### Check List 

Tests 

 - Unit test ~TODO: add gofail test in `getUsedList()`~ done.

Code changes

 - Has exported function/method change

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by eurekaka** [comment]
@zz-jason Please fix CI.

**Comment by zz-jason** [comment]
@eurekaka Fixed, PTAL again.

**Pull request merged**
