### PR TITLE
executor: migrate test-infra to testify for aggregate_test.go

### LINKED ISSUE #28563: migrate test-infra to testify for `aggregate_test.go`

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #28563

Problem Summary:

### What is changed and how it works?

migrate test-infra to testify for aggregate_test.go

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
@tisonkun @AilinKid PTAL

**Comment by tisonkun** [comment]
IIRC directly export testdatasuite variable has several issues. Maybe the failure is not about unstable tests.

**Comment by hawkingrei** [comment]
> IIRC directly export testdatasuite variable has several issues. Maybe the failure is not about unstable tests. Do you verify the code locally?

I find ```TestAggInDisk``` is vulnerable to other tasks, so I make it serial. After changing, I find the unstable tests are  from other tests. I will check the problem of testdatasuite.

**Review by lcwangchao — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
