### PR TITLE
planner: fix bug when unfolding wildcard in view definiton (#25226)

### LINKED ISSUE #24933: view returns unexpected error when containing count(*)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
drop table if exists t1;
CREATE TABLE `t1` (
  `a` int(11) DEFAULT NULL,
  `b` varchar(32) DEFAULT NULL
);
create view v3 as select * from (select a, count(*) from t1 where b >= 'c' group by a) qn;
select * from v3;
```

### 2. What did you expect to see? (Required)

No error

### 3. What did you see instead (Required)
```
mysql> select * from v3;
ERROR 1356 (HY000): View 'test.v3' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
```
### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25226 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/26036
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/26036:release-4.0-ad0f654fcb81
```

---

Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #24933 

Problem Summary: When wildcard and subquery(e.g. select some_expr/agg/win_func from xxx) is used in view definition. We got unknown column error.

For example:

```
create view v as select * from (select count(*) from t1) s;
select * from v; // got error
create view v as select * from (select c1 or 0 from t1) s;
select * from v; // got error
```

**Why**: check the result of show create view. The `*` is unfolded to be `s.count(*)`, but in the subquery, the select field is `count(1)`. The column name is not same. (**PS**: This problem exists for other agg func/window func ...)

    SELECT `s`.`count(*)` AS `count(*)` FROM (SELECT COUNT(1) AS `count(*)` FROM `test`.`t1`) AS `s`

### What is changed and how it works?

What's Changed: **Add alias name for select filed when create view**. So the view definition will be:

    SELECT `s`.`count(*)` FROM (SELECT COUNT(1) AS `count(*)` FROM `test`.`t1`) AS `s`

How it works:
1. After `buildProjection()` in `buildSelect()`, we add alias name for each select field. The new added function assumes there is a **one-to-one mapping** between select fields and proj.OutputNames().

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects: None

### Release note 

- planner: fix bug when unfolding wildcard in view definiton

### CODE REVIEW

**Comment by tisonkun** [comment]
@guo-shaoge why do we hold this PR since it is already approved?

**Comment by guo-shaoge** [comment]
> @guo-shaoge why do we hold this PR since it is already approved?

It's my mistake. I found a bug casused by this fix. #25929

This bug exists since day 1 and found when we test CTE. So I think it's not a big problem.

To be safe, I think it's  better to hold it.

**Comment by tisonkun** [comment]
/uncc @qw4990 @winoros 

@guo-shaoge then we don't have to request reviewers at this moment.

**Comment by guo-shaoge** [comment]
I don't think it's a critical bug, and it exists since day 1. So only fixed in master.

**Pull request closed without merging**
