### PR TITLE
lightning: save status checkpoint synchronously

### PR DESCRIPTION
**Pull request by gozssky**
### What problem does this PR solve?

Close https://github.com/pingcap/br/issues/1372.
Same as https://github.com/pingcap/br/pull/1304.

We save status checkpoint after import finished, and then clean up the engine. 
https://github.com/pingcap/tidb/blob/550c7d04debe59011b6dcbdca9982be8405dd39c/br/pkg/lightning/restore/table_restore.go#L853-L858
But `saveStatusCheckpoint`  saves checkpoint asynchronously, an engine may be cleaned up successfully but exit before update checkpoint. After restart, `verifyLocalFile` will fail.
https://github.com/pingcap/tidb/blob/550c7d04debe59011b6dcbdca9982be8405dd39c/br/pkg/lightning/restore/restore.go#L827

To solve this issue, we can save status synchronously. An engine can only be cleaned up after the checkpoint has been successfully saved. Since we don't change the status of the engine very often, I think synchronously saving status checkpoint is acceptable and it can also avoid some unusual situations.

Related unstable integration test: [lightning_checkpoint_engines_order](https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/5389/pipeline). 

### What is changed and how it works?

Save save status checkpoint synchronously.

### Check List 

Tests 

- [x] Unit test
- [x] Integration test

### Release note 

```release-note
lightning: save status checkpoint synchronously
```

### CODE REVIEW

**Comment by glorv** [comment]
```
[2021-08-12T17:40:18.849Z] FAIL: restore_test.go:1001: tableRestoreSuite.TestSaveStatusCheckpoint

[2021-08-12T17:40:18.849Z] 

[2021-08-12T17:40:18.849Z] restore_test.go:1025:

[2021-08-12T17:40:18.849Z]     c.Assert(elapsed, GreaterEqual, time.Millisecond*100)

[2021-08-12T17:40:18.849Z] ... compare_one time.Duration = 77689 ("77.689µs")

[2021-08-12T17:40:18.849Z] ... compare_two time.Duration = 100000000 ("100ms")

```

@gozssky

**Comment by gozssky** [comment]
> ```
> [2021-08-12T17:40:18.849Z] FAIL: restore_test.go:1001: tableRestoreSuite.TestSaveStatusCheckpoint
> 
> [2021-08-12T17:40:18.849Z] 
> 
> [2021-08-12T17:40:18.849Z] restore_test.go:1025:
> 
> [2021-08-12T17:40:18.849Z]     c.Assert(elapsed, GreaterEqual, time.Millisecond*100)
> 
> [2021-08-12T17:40:18.849Z] ... compare_one time.Duration = 77689 ("77.689µs")
> 
> [2021-08-12T17:40:18.849Z] ... compare_two time.Duration = 100000000 ("100ms")
> ```
> 
> @gozssky

@glorv  Fixed.

**Review by glorv — APPROVED** [review]

**Review by kennytm — APPROVED** [review]

**Pull request merged**
