### PR TITLE
 plan: fix a bug in `topn_push_down` rule.

### LINKED ISSUE #6864: order by IFNULL and limit throw error 'runtime error: index out of range'
```SQL
CREATE TABLE `tB` (
  `ReplyTime` datetime(3) NOT NULL,
  `Pid` bigint(20) NOT NULL,
  `Id` bigint(20) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `tA` (
  `SendTime` datetime(3) NOT NULL,
  `Id` bigint(20) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```
```SQL
  select ifnull(b.ReplyTime,a.SendTime)
  from tA a left join tB b on a.id=b.PId
  order by ifnull(b.ReplyTime,a.SendTime) desc
  limit 10
```

> 2018-06-20T03:54:32.604973000Z 2018/06/20 03:54:32.603 column.go:315: [error] Can't find column b.replytime in schema Column: [a.sendtime,a.id] Unique key: [[a.id]]
2018-06-20T03:54:32.605294000Z 2018/06/20 03:54:32.603 column.go:315: [error] Can't find column b.replytime in schema Column: [a.sendtime,a.id] Unique key: [[a.id]]
2018-06-20T03:54:32.610886000Z panic: runtime error: index out of range

### PR DESCRIPTION
**Pull request by winoros**
## What have you changed? (mandatory)

`ColumnIndices` will return `nil` if not all column in the schema.
So here will perform wrong action if the by item contains column from both sides.

## What are the type of the changes (mandatory)?

The currently defined types are listed below, please pick one of the types for this PR by removing the others:

- Bug fix

## How has this PR been tested (mandatory)?

unit test.

## Refer to a related PR or issue link (optional)

fix #6864

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
Do we need to cherry-pick this to the release-2.0?

**Comment by winoros** [comment]
@shenli Yes, we'd better pick it.

**Pull request merged**
