### PR TITLE
*: enable flaky test for all test

### LINKED ISSUE #36404: enable flaky test to all tests
## Enhancement

We have many unstable tests in the tidb repo and we will create many unstable tests the everyday. In history, we put more attention on fixing the unstable test. and we find many unstable tests due to the bad design of test cases. All of us feel upset and take more time to wait to fixing the unstable test and speed more money to bug more machines to fight the unstable tests. we need to change our minds. we should retry unstable tests and report them to the dashboard. then to make the people fix the unstable test to clear the dashboard.

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #36404

Problem Summary:

### Check List

Tests 

- [x] Unit test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by hawkingrei** [comment]
/hold

update config again

**Pull request merged**
