### PR TITLE
config: enable TxnLocalLatches in default

### PR DESCRIPTION
**Pull request by AndreMouche**
## What have you changed? (mandatory)

This PR enables TxnLocalLatches  as default value.

## What are the type of the changes (mandatory)?

The currently defined types are listed below, please pick one of the types for this PR by removing the others:

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested (mandatory)?

The stability test has been run one week with no error

## Does this PR affect documentation (docs/docs-cn) update? (optional)

no

@coocood @tiancaiamao PTAL

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Comment by shenli** [comment]
LGTM
Do not forget to update the docs and ansible.

**Pull request merged**
