### PR TITLE
executor: stable test not to automatically gc

### LINKED ISSUE #32519: Unstable test TestPBMemoryLeak
@hawkingrei it seems that the migrated tests aren't stable. See also https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/36799/pipeline.

```
[2022-02-21T15:19:41.205Z] --- FAIL: TestPBMemoryLeak (116.22s)
[2022-02-21T15:19:41.205Z]     assertion_compare.go:332: 
[2022-02-21T15:19:41.205Z]         	Error Trace:	memory_test.go:67
[2022-02-21T15:19:41.205Z]         	Error:      	"62439424" is not less than "53687091"
[2022-02-21T15:19:41.205Z]         	Test:       	TestPBMemoryLeak
[2022-02-21T15:19:41.205Z]         	Messages:   	[]
```

_Originally posted by @tisonkun in https://github.com/pingcap/tidb/issues/28595#issuecomment-1047033550_

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #32519

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

**Review by guo-shaoge — APPROVED** [review]

**Comment by tangenta** [comment]
```
[2022-02-22T08:14:53.348Z] runtime: gp: gp=0xc00018a2ff, goid=8704, gp->atomicstatus=1024
[2022-02-22T08:14:53.348Z] runtime:  g:  g=0xc0004fcd80, goid=0,  g->atomicstatus=0
[2022-02-22T08:14:53.348Z] fatal error: invalid g status
[2022-02-22T08:14:53.348Z] 
[2022-02-22T08:14:53.348Z] runtime stack:
[2022-02-22T08:14:53.348Z] runtime.throw(0x4220c24, 0x10)
[2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/panic.go:1117 +0x72
[2022-02-22T08:14:53.348Z] runtime.suspendG(0xc00018a2ff, 0xc000060000, 0x0)
[2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/preempt.go:135 +0x5b7
[2022-02-22T08:14:53.348Z] runtime.markroot.func1()
[2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/mgcmark.go:225 +0x79
[2022-02-22T08:14:53.348Z] runtime.markroot(0xc00006b698, 0xc000000047)
[2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/mgcmark.go:206 +0x33e
[2022-02-22T08:14:53.348Z] runtime.gcDrain(0xc00006b698, 0xb)
[2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/mgcmark.go:1014 +0x118
[2022-02-22T08:14:53.348Z] runtime.gcBgMarkWorker.func2()
[2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/mgc.go:2001 +0x19a
[2022-02-22T08:14:53.348Z] runtime.systemstack(0x0)
[2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/asm_amd64.s:379 +0x66
[2022-02-22T08:14:53.348Z] runtime.mstart()
[2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/proc.go:1246
```

**Comment by tiancaiamao** [comment]
> ```
> [2022-02-22T08:14:53.348Z] runtime: gp: gp=0xc00018a2ff, goid=8704, gp->atomicstatus=1024
> [2022-02-22T08:14:53.348Z] runtime:  g:  g=0xc0004fcd80, goid=0,  g->atomicstatus=0
> [2022-02-22T08:14:53.348Z] fatal error: invalid g status
> [2022-02-22T08:14:53.348Z] 
> [2022-02-22T08:14:53.348Z] runtime stack:
> [2022-02-22T08:14:53.348Z] runtime.throw(0x4220c24, 0x10)
> [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/panic.go:1117 +0x72
> [2022-02-22T08:14:53.348Z] runtime.suspendG(0xc00018a2ff, 0xc000060000, 0x0)
> [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/preempt.go:135 +0x5b7
> [2022-02-22T08:14:53.348Z] runtime.markroot.func1()
> [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/mgcmark.go:225 +0x79
> [2022-02-22T08:14:53.348Z] runtime.markroot(0xc00006b698, 0xc000000047)
> [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/mgcmark.go:206 +0x33e
> [2022-02-22T08:14:53.348Z] runtime.gcDrain(0xc00006b698, 0xb)
> [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/mgcmark.go:1014 +0x118
> [2022-02-22T08:14:53.348Z] runtime.gcBgMarkWorker.func2()
> [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/mgc.go:2001 +0x19a
> [2022-02-22T08:14:53.348Z] runtime.systemstack(0x0)
> [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/asm_amd64.s:379 +0x66
> [2022-02-22T08:14:53.348Z] runtime.mstart()
> [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/proc.go:1246
> ```

This kinds of error seems to be caused by data race?

**Comment by hawkingrei** [comment]
> > ```
> > [2022-02-22T08:14:53.348Z] runtime: gp: gp=0xc00018a2ff, goid=8704, gp->atomicstatus=1024
> > [2022-02-22T08:14:53.348Z] runtime:  g:  g=0xc0004fcd80, goid=0,  g->atomicstatus=0
> > [2022-02-22T08:14:53.348Z] fatal error: invalid g status
> > [2022-02-22T08:14:53.348Z] 
> > [2022-02-22T08:14:53.348Z] runtime stack:
> > [2022-02-22T08:14:53.348Z] runtime.throw(0x4220c24, 0x10)
> > [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/panic.go:1117 +0x72
> > [2022-02-22T08:14:53.348Z] runtime.suspendG(0xc00018a2ff, 0xc000060000, 0x0)
> > [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/preempt.go:135 +0x5b7
> > [2022-02-22T08:14:53.348Z] runtime.markroot.func1()
> > [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/mgcmark.go:225 +0x79
> > [2022-02-22T08:14:53.348Z] runtime.markroot(0xc00006b698, 0xc000000047)
> > [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/mgcmark.go:206 +0x33e
> > [2022-02-22T08:14:53.348Z] runtime.gcDrain(0xc00006b698, 0xb)
> > [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/mgcmark.go:1014 +0x118
> > [2022-02-22T08:14:53.348Z] runtime.gcBgMarkWorker.func2()
> > [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/mgc.go:2001 +0x19a
> > [2022-02-22T08:14:53.348Z] runtime.systemstack(0x0)
> > [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/asm_amd64.s:379 +0x66
> > [2022-02-22T08:14:53.348Z] runtime.mstart()
> > [2022-02-22T08:14:53.348Z] 	/usr/local/go/src/runtime/proc.go:1246
> > ```
> 
> This kinds of error seems to be caused by data race?

I saw this error messenger yesterday. it can create an issue to tracker.

**Pull request merged**
