### PR TITLE
util: improve stack message in the panic log

### LINKED ISSUE #34356: improve stack message in the panic log
## Enhancement

Now we have two methods to get stack when to panic. ```util.GetStack``` and ```zap.Stack```.

but  ```util.GetStak``` it will have some rubbish message like ```goroutine 740 [running]:\ngithub.com/pingcap/tidb/util.GetStack(...)\n\t```.  ```zap.Stack``` is without useless message. so we need to replace ```util.GetStack``` with ```zap.Stack```.

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #34356

Problem Summary:

before improvement:

```
[2022/05/03 00:23:20.820 +08:00] [ERROR] [main.go:22] ["recover panic"] [buffer="goroutine 1 [running]:\nmain.GetStack(...)\n\t/Users/hawkingrei/tmp/gomain/main.go:13\nmain.main.func1()\n\t/Users/hawkingrei/tmp/gomain/main.go:21 +0x59\npanic({0x117e360, 0x11f0890})\n\t/usr/local/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838 +0x207\nmain.main()\n\t/Users/hawkingrei/tmp/gomain/main.go:25 +0x49\n"] [stack="main.main.func1\n\t/Users/hawkingrei/tmp/gomain/main.go:22\nruntime.gopanic\n\t/usr/local/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838\nmain.main\n\t/Users/hawkingrei/tmp/gomain/main.go:25\nruntime.main\n\t/usr/local/Cellar/go/1.18.1/libexec/src/runtime/proc.go:250"]
```

after improvement:

```
[2022/05/03 00:23:51.027 +08:00] [ERROR] [main.go:12] ["recover panic"] [buffer="main.main.func1\n\t/Users/hawkingrei/tmp/gomain/main.go:12\nruntime.gopanic\n\t/usr/local/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838\nmain.main\n\t/Users/hawkingrei/tmp/gomain/main.go:15\nruntime.main\n\t/usr/local/Cellar/go/1.18.1/libexec/src/runtime/proc.go:250"] [stack="main.main.func1\n\t/Users/hawkingrei/tmp/gomain/main.go:12\nruntime.gopanic\n\t/usr/local/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838\nmain.main\n\t/Users/hawkingrei/tmp/gomain/main.go:15\nruntime.main\n\t/usr/local/Cellar/go/1.18.1/libexec/src/runtime/proc.go:250"]
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by ngaut — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
@hawkingrei you may help on reviewing this PR https://github.com/pingcap/log/pull/26.

**Comment by hawkingrei** [comment]
> @hawkingrei you may help on reviewing this PR [pingcap/log#26](https://github.com/pingcap/log/pull/26).

LGTM, So merged it.

**Pull request merged**
