### PR TITLE
executor: make hashjoin using executor_concurrency

### PR DESCRIPTION
**Pull request by niedhui**
### What problem does this PR solve?

Issue Number:  part of #15428

### What is changed and how it works?

What's Changed:  make `tidb_hash_join_concurrency` using `tidb_executor_concurrency`

This PR also changed `DefExecutorConcurrency` to **5**, equals to `DefTiDBHashJoinConcurrency `. There's no performance regression due to the benchmark results.

There's no warning when setting `tidb_hash_join_concurrency` for the time being, since it will break the integration-test. 
After this PR and https://github.com/pingcap/mysql-tester/pull/4 is merged, I'll add the warning back.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

No release note

### CODE REVIEW

**Comment by niedhui** [comment]
@sre-bot /run-all-tests

**Comment by niedhui** [comment]
@sre-bot /run-all-tests

**Comment by niedhui** [comment]
@sre-bot /bench

**Comment by niedhui** [comment]
@sre-bot /bench +tpcc +sysbench

**Comment by SunRunAway** [comment]
@sre-bot /bench +tpch

**Comment by niedhui** [comment]
@sre-bot /bench +tpcc +sysbench

**Comment by niedhui** [comment]
@sre-bot /bench +tpch +sysbench

**Comment by niedhui** [comment]
@sre-bot /run-all-tests

**Comment by niedhui** [comment]
@sre-bot /run-all-tests

**Comment by niedhui** [comment]
@sre-bot /run-all-tests

**Comment by niedhui** [comment]
@sre-bot  /run-integration-br-test

**Comment by niedhui** [comment]
@SunRunAway PTAL

**Comment by SunRunAway** [comment]
@sre-bot /merge

**Comment by niedhui** [comment]
@sre-bot /run-check_dev_2

**Comment by niedhui** [comment]
@sre-bot run-unit-test

**Comment by niedhui** [comment]
@sre-bot /run-all-tests

**Pull request merged**
