### PR TITLE
metrics: distinguish transactions by mode

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/17377 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Use "pessimistic" and "optimistic" to distinguish transactions.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
* start a new cluster with this branch
* check out the metrics

### Release note 
* No release note
-

### CODE REVIEW

**Comment by lysu** [comment]
maybe we still need LblInternal to explain some problem for our customer(e.g. why I do nothing but it running stmt?)

**Comment by jackysp** [comment]
> maybe we still need LblInternal to explain some problem for our customer(e.g. why I do nothing but it running stmt?)

We have already added the internal label in SQL level, I think it provides enough info for the user.

**Pull request merged**
