### PR TITLE
planner: Fix runtime error occurs when illegal mix collate in subquery

### LINKED ISSUE #24705: subquery with any，the connection field uses a different character set，occur runtime error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t1  (c_int int, c_str varchar(40) character set utf8 collate utf8_general_ci);
create table t2  (c_int int, c_str varchar(40) character set utf8 collate utf8_unicode_ci);
select * from t1 where c_str < any (select c_str from t2 where c_int between 6 and 9);

### 2. What did you expect to see? (Required)

sucessfull

### 3. What did you see instead (Required)

occur runtime error
mysql> select * from t1 where c_str < any (select c_str from t2 where c_int between 6 and 9);
ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference

log：
[2021/05/18 03:54:59.690 +00:00] [ERROR] [terror.go:291] ["encountered error"] [error="[expression:1267]Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation 'lt'"] [stack="github.com/pingcap/parser/terror.Log\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210325072920-0d17053a8a69/terror/terror.go:291\ngithub.com/pingcap/tidb/expression.NewFunctionInternal\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/expression/scalar_function.go:261\ngithub.com/pingcap/tidb/planner/core.(*expressionRewriter).handleOtherComparableSubq\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:611\ngithub.com/pingcap/tidb/planner/core.(*expressionRewriter).handleCompareSubquery\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:570\ngithub.com/pingcap/tidb/planner/core.(*expressionRewriter).Enter\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:366\ngithub.com/pingcap/parser/ast.(*CompareSubqueryExpr).Accept\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210325072920-0d17053a8a69/ast/expressions.go:439\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteExprNode\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:194\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteWithPreprocess\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:141\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).rewrite\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:109\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelection\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:948\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:3377\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).Build\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/planbuilder.go:626\ngithub.com/pingcap/tidb/planner.optimize\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/optimize.go:234\ngithub.com/pingcap/tidb/planner.Optimize\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/optimize.go:124\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/compiler.go:62\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/session/session.go:1404\ngithub.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/driver_tidb.go:218\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmt\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1630\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1503\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1037\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:795\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/server.go:477"]
[2021/05/18 03:54:59.691 +00:00] [ERROR] [conn.go:736] ["connection running loop panic"] [conn=6005] [lastSQL="select * from t1 where c_str < any (select c_str from t2 where c_int between 6 and 9)"] [err="runtime error: invalid memory address or nil pointer dereference"] [stack="goroutine 16382773 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x4004660, 0xc007ae5bc0, 0xc007939400)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:734 +0xee\npanic(0x3597a40, 0x59111a0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/pingcap/tidb/expression.wrapWithIsTrue(0x405dc80, 0xc001c443c0, 0x1, 0x0, 0x0, 0xc0024c3100, 0x135dab8, 0xb0, 0x35f7e20, 0xc00a18d401)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/expression/expression.go:1319 +0x37\ngithub.com/pingcap/tidb/expression.(*logicOrFunctionClass).getFunction(0xc00030a7e0, 0x405dc80, 0xc001c443c0, 0xc003dcab20, 0x2, 0x2, 0x2, 0x2, 0x5, 0xc0024c33e8)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/expression/builtin_op.go:123 +0xb7\ngithub.com/pingcap/tidb/expression.newFunctionImpl(0x405dc80, 0xc001c443c0, 0x1, 0x399df08, 0x2, 0xc0032e78c0, 0xc0024c3510, 0x2, 0x2, 0xc0024c3490, ...)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/expression/scalar_function.go:214 +0x2fb\ngithub.com/pingcap/tidb/expression.NewFunction(...)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/expression/scalar_function.go:245\ngithub.com/pingcap/tidb/expression.NewFunctionInternal(0x405dc80, 0xc001c443c0, 0x399df08, 0x2, 0xc0032e78c0, 0xc0024c3510, 0x2, 0x2, 0xc0042beaa0, 0xc0024c3878)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/expression/scalar_function.go:260 +0x96\ngithub.com/pingcap/tidb/expression.composeConditionWithBinaryOp(0x405dc80, 0xc001c443c0, 0xc0024c37b8, 0x2, 0x2, 0x399df08, 0x2, 0x3, 0x408a060)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/expression/expression.go:695 +0x242\ngithub.com/pingcap/tidb/expression.ComposeDNFCondition(...)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/expression/expression.go:709\ngithub.com/pingcap/tidb/planner/core.(*expressionRewriter).buildQuantifierPlan(0xc007e6e1a0, 0xc001f1f540, 0x0, 0x0, 0x4089ca0, 0xc001c7c500, 0x4089ca0, 0xc001c7cc80, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:660 +0x18dc\ngithub.com/pingcap/tidb/planner/core.(*expressionRewriter).handleOtherComparableSubq(0xc007e6e1a0, 0x4089ca0, 0xc001c7c500, 0x4089ca0, 0xc001c7cc80, 0x40594a0, 0xc007ea6c40, 0x0, 0x399dee4, 0x2, ...)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:612 +0x580\ngithub.com/pingcap/tidb/planner/core.(*expressionRewriter).handleCompareSubquery(0xc007e6e1a0, 0x4004660, 0xc005eb77d0, 0xc0055e62c0, 0xc001d23c20, 0x135d246, 0xc00233ec80)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:570 +0xc49\ngithub.com/pingcap/tidb/planner/core.(*expressionRewriter).Enter(0xc007e6e1a0, 0x4021460, 0xc0055e62c0, 0xc001d23c88, 0x137f18a, 0xc0017d8f00)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:366 +0x1124\ngithub.com/pingcap/parser/ast.(*CompareSubqueryExpr).Accept(0xc0055e62c0, 0x3fcbde0, 0xc007e6e1a0, 0xc0017d8f00, 0xc001d23d58, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210325072920-0d17053a8a69/ast/expressions.go:439 +0x4b\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteExprNode(0xc00080a840, 0xc007e6e1a0, 0x403ccc0, 0xc0055e62c0, 0xc0017d8f00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:194 +0x8e\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteWithPreprocess(0xc00080a840, 0x4004660, 0xc00"]

### 4. What is your TiDB version? (Required)

Release Version: v5.0.1
Edition: Community
Git Commit Hash: 1145e347d3469d8e89f88dce86f6926ca44b3cd8
Git Branch: heads/refs/tags/v5.0.1
UTC Build Time: 2021-04-23 05:51:17
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: close #24705  

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
planner/core/expression_rewriter.go

How it Works:
judge different collate in sub query

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
Maybe `in` subquery also has this problem?

**Comment by sylzd** [comment]
> Maybe `in` subquery also has this problem?

yeah, I am not sure if it can fix it all.
I tried like this, it worked.
```sql
select * from t1 where c_str in (select c_str from t2 where c_int between 6 and 9);
```

**Review by tangenta — APPROVED** [review]

**Pull request merged**
