### PR TITLE
domain: add negative testing for SendTask()

### LINKED ISSUE #54115: add negative testing for SendTask()
## Enhancement

When I checked with codecov, I found one part of SendTask() that is not COVERED. The purpose of this issue is to improve the coverage of SendTask().

image

### PR DESCRIPTION
**Pull request by ei-sugimoto**
### What problem does this PR solve?

Issue Number: close #54115

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
/ok-to-test

@ei-sugimoto Hi, please sign CLA as bot said

**Review by hawkingrei — APPROVED** [review]

**Comment by ei-sugimoto** [comment]
sign CLA

**Comment by ei-sugimoto** [comment]
@sre-bot sign CLA

**Comment by lance6716** [comment]
Here's the error from CI

> Please run `make bazel_prepare` to update `.bazel` files, or just apply the following git diff (run `git apply -` and paste following contents):

```diff
diff --git a/pkg/domain/BUILD.bazel b/pkg/domain/BUILD.bazel
index 8b4f659c35..abead8a809 100644
--- a/pkg/domain/BUILD.bazel
+++ b/pkg/domain/BUILD.bazel
@@ -132,7 +132,7 @@ go_test(
     ],
     embed = [":domain"],
     flaky = True,
-    shard_count = 27,
+    shard_count = 28,
     deps = [
         "//pkg/config",
         "//pkg/ddl",
```

**Comment by ei-sugimoto** [comment]
@hawkingrei Thanks, Review!!
@lance6716 Thanks, Review and I sign CLA .

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
