### PR TITLE
domain: do not start Auto Analyze Worker until statistics initialization is complete

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/52346

Problem Summary:

We shouldn't start the auto-analyze worker before we complete the stats initialization. Otherwise, we might have started the auto-analysis before the initialization of the stats was complete without [force init](https://docs.pingcap.com/tidb/stable/tidb-configuration-file#force-init-stats-new-in-v657-and-v710) turned on. This could waste a lot of resources.

### What changed and how does it work?

Wait for the initialization to be finished.

It is important to wait for it in a separate goroutine to avoid blocking the entire bootstrap process.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
修复 TiDB 在统计信息初始化完成前就进行自动分析的问题
Fix TiDB auto-analysis before initialization of statistics is complete
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Comment by hi-rustin** [comment]
/hold

We need to test it.

**Comment by winoros** [comment]
The http service seems to be alive after the auto analyze.
so the 10080 port is not alive until the init stats is finished after this pr.
it may be unexpected.

**Review by hawkingrei — APPROVED** [review]

**Comment by hi-rustin** [comment]
Tested again locally:
1. Set `force-init-stats = true` and `lite-init-stats = true`
2. Restart the TiDB cluster
3. Check the metrics and logs:
image
image

```logs
oom_record  slowquery  tidb-2024-04-07T13-39-33.439.log  tidb-2024-04-08T15-27-51.423.log  tidb-2024-04-09T19-55-21.815.log  tidb.log
[root@tc-upstream-tidb-0 log]# tail -f tidb.log 
[2024/04/11 08:04:58.798 +00:00] [INFO] [notifier.go:140] ["new etcd watcher created to watch timer events"] [EtcdKey=/tidb/timer/cluster/1/notify/98a3ba0f-bb5d-4f55-a5be-791505a8c3ff] [watcherID=c5bd0b9c-8d8b-4839-aa36-4bd066342a5d]
[2024/04/11 08:04:58.805 +00:00] [INFO] [slots.go:205] ["initialize slot capacity"] [capacity=8]
[2024/04/11 08:04:58.807 +00:00] [INFO] [scheduler_manager.go:200] ["schedule task loop start"]
[2024/04/11 08:04:58.807 +00:00] [INFO] [scheduler_manager.go:453] ["collect loop start"]
[2024/04/11 08:04:58.807 +00:00] [INFO] [scheduler_manager.go:373] ["cleanup loop start"]
[2024/04/11 08:04:58.807 +00:00] [INFO] [scheduler_manager.go:312] ["subtask table gc loop start"]
[2024/04/11 08:04:59.761 +00:00] [INFO] [info.go:1142] [SetTiFlashGroupConfig]
[2024/04/11 08:05:38.442 +00:00] [INFO] [manager.go:364] ["get owner"] ["owner info"="[log-backup] /tidb/br-stream/owner ownerManager 066c65f2-761c-4510-b0d7-086e3122c686"] ["owner key"=/tidb/br-stream/owner/707b8ea796a75cfa] [ownerID=066c65f2-761c-4510-b0d7-086e3122c686] [op=none]
[2024/04/11 08:05:38.442 +00:00] [INFO] [manager.go:364] ["get owner"] ["owner info"="[bindinfo] /tidb/bindinfo/owner ownerManager 6e2ab1b1-fa73-44f0-be87-7b81673af539"] ["owner key"=/tidb/bindinfo/owner/707b8ea796a75d00] [ownerID=6e2ab1b1-fa73-44f0-be87-7b81673af539] [op=none]
[2024/04/11 08:05:38.442 +00:00] [INFO] [manager.go:364] ["get owner"] ["owner info"="[stats] /tidb/stats/owner ownerManager 6e2ab1b1-fa73-44f0-be87-7b81673af539"] ["owner key"=/tidb/stats/owner/707b8ea796a75d04] [ownerID=6e2ab1b1-fa73-44f0-be87-7b81673af539] [op=none]
[2024/04/11 08:05:45.763 +00:00] [INFO] [owner_daemon.go:56] ["daemon became owner"] [id=066c65f2-761c-4510-b0d7-086e3122c686] [daemon-id=LogBackup::Advancer]
[2024/04/11 08:05:45.763 +00:00] [INFO] [advancer.go:513] ["Subscription handler spawned."] [category="log backup subscription manager"]
[2024/04/11 08:09:03.593 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1074912712] [quota=1073741824]
[2024/04/11 08:09:12.135 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1073969624] [quota=1073741824]
[2024/04/11 08:09:20.231 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1078369784] [quota=1073741824]
[2024/04/11 08:09:28.320 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1076892782] [quota=1073741824]
[2024/04/11 08:09:36.664 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1080952141] [quota=1073741824]
[2024/04/11 08:09:44.982 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1077954586] [quota=1073741824]
[2024/04/11 08:09:51.298 +00:00] [INFO] [domain.go:2872] ["refreshServerIDTTL succeed"] [serverID=309] ["lease id"=707b8ea796a75cd8]
[2024/04/11 08:09:53.185 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1080002579] [quota=1073741824]
[2024/04/11 08:10:01.564 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1078624365] [quota=1073741824]
[2024/04/11 08:10:10.022 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1074501804] [quota=1073741824]
[2024/04/11 08:10:18.663 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1080887748] [quota=1073741824]
[2024/04/11 08:10:27.314 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1076839651] [quota=1073741824]
[2024/04/11 08:10:35.614 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1077619557] [quota=1073741824]
[2024/04/11 08:10:43.842 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1074967358] [quota=1073741824]
[2024/04/11 08:10:52.505 +00:00] [INFO] [sort_spill.go:59] ["memory exceeds quota, spill to disk now."] [consumed=1074530865] [quota=1073741824]
```

**Review by zimulala — APPROVED** [review]

**Pull request merged**
