### PR TITLE
*: extend the semantic of mem-quota-query to mem-quota-session

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/38429

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
I do not know why this test failed.

```
    result.go:49: 
        	Error Trace:	/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/linux-sandbox/7057/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/concurrentddltest/concurrentddltest_test_/concurrentddltest_test.runfiles/__main__/ddl/concurrentddltest/result.go:49
        	            				/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/linux-sandbox/7057/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/concurrentddltest/concurrentddltest_test_/concurrentddltest_test.runfiles/__main__/ddl/concurrentddltest/switch_test.go:113
        	Error:      	Not equal: 
        	            	expected: "[0]\n"
        	            	actual  : "[11]\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-[0]
        	            	+[11]
        	            	 
        	Test:       	TestConcurrentDDLSwitch
        	Messages:   	sql:select count(*) from mysql.tidb_ddl_job, args:[]
```

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
