### PR TITLE
executor: LOAD DATA use VisibleCols to skip hidden columns

### LINKED ISSUE #42446: load data import data to the table with multi-valued index will fail
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql> CREATE TABLE test.t (`pk` bigint(20) NOT NULL AUTO_INCREMENT,`j` json DEFAULT NULL,`i` int(11) DEFAULT NULL,`c` char(64) DEFAULT NULL, PRIMARY KEY (`pk`) ,KEY `j` ((cast(json_extract(`j`, _utf8mb4'$.number[*]') as signed array)))) 
    -> ;
Query OK, 0 rows affected (0.09 sec)

mysql> 
mysql> 
mysql> LOAD DATA INFILE 's3://brie/mvindex/sql/test.t.000000001.sql?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%2fminio.pingcap.net%3a9001&force-path-style=true' format 'sql file' INTO TABLE test.t;
ERROR 8067 (HY000): Load data: unmatched columns
```

### 2. What did you expect to see? (Required)
import successfully
### 3. What did you see instead (Required)
import fail
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #42446

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
ping @D3Hunter @hawkingrei

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
Does it also affect 7.0? Should we cherry-pick this fix to release 7.0?

**Comment by lance6716** [comment]
> Does it also affect 7.0? Should we cherry-pick this fix to release 7.0?

The issue author says it's an experimental feature, no need to cherry-pick

**Comment by YangKeao** [comment]
> > Does it also affect 7.0? Should we cherry-pick this fix to release 7.0?
> 
> The issue author says it's an experimental feature, no need to cherry-pick

OK. Actually we planned to GA at 7.0, but it seems failed :facepalm:, so it's still an experimental feature now.

It's fine to not cherry pick. Thanks for confirmation.

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
