### PR TITLE
executor, sessionctx/variable: convert some system variables to different builtin types

### LINKED ISSUE #35048: Use sysvar Type correctly for automatic validation / docs
## Enhancement

Some system variables either have no type (default: TypeString) or use TypeString when they could use a different builtin type (TypeInt, TypeEnum, TypeBool) that is more suited. Here is what I found from manual inspection:

| Variable Name  | Notes |
| ------------- | ------------- |
| block_encryption_mode | The type is not defined, but if you look in the code it should be TypeEnum. The possible values are `"aes-128-ecb","aes-192-ecb","aes-256-ecb","aes-128-cbc","aes-192-cbc","aes-256-cbc","aes-128-ofb","aes-192-ofb","aes-256-ofb","aes-128-cfb","aes-192-cfb","aes-256-cfb"`  |
| ddl_slow_threshold | The type should be TypeInt with a MinValue of 0, MaxValue needs to be determined. |
| have_openssl, have_ssl | The type should be TypeBool |
| last_insert_id/identity | The type should be TypeInt, but it might also require `AllowEmpty: true` set. | 
| tidb_build_stats_concurrency | Needs to be TypeInt. For MaxValue use `MaxConfigurableConcurrency` constant |
| tidb_checksum_table_concurrency | Needs to be TypeInt. For MaxValue use `MaxConfigurableConcurrency` constant |
| tidb_current_ts | Needs to be TypeInt. might also require `AllowEmpty: true` set. |
| tidb_ddl_reorg_priority | Should be TypeEnum. PossibleValues: `PRIORITY_LOW,PRIORITY_NORMAL,PRIORITY_HIGH`. |
| tidb_force_priority | Should be TypeEnum. PossibleValues: `NO_PRIORITY, LOW_PRIORITY, HIGH_PRIORITY, DELAYED` |
| tidb_opt_write_row_id | Should be a TypeBool |
| tidb_partition_prune_mode | Should be TypeEnum. Possible values: `static, dynamic, static-only, dynamic-only.` |

### What does "Type" do?

The name is a bit misleading, since Type is mainly used for validation purposes only (see exception). Internally, all values are stored in `mysql.global_variables` as strings, and the API uses string for values.

(Exception) Type information is also used in `SELECT @@varname` context, since booleans are expected to return "0" here versus "OFF" in `SHOW VARIABLES LIKE 'varname'` context. See relevant code here: https://github.com/pingcap/tidb/blob/45a67585aa6fb2d8db6373894682857586b7b614/sessionctx/variable/variable.go#L491-L508

### Why do this?

The advantage is that the documentation is auto-generated to show Possible Values for enums. Another advantage is that the validation becomes more consistent. For example, `tidb_partition_prune_mode` appears to be case-sensitive, but normally for ENUM values MySQL is insensitive.

### PR DESCRIPTION
**Pull request by gogim1**
### What problem does this PR solve?

Issue Number: close #35048

Problem Summary:

Change some system variables to different builtin types (TypeInt, TypeEnum, TypeBool). Invalid values now return an error. 

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility
tidb_force_priority now validates options are set correctly.

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
- ddl_slow_threshold
- block_encryption_mode
- tidb_force_priority
- tidb_ddl_reorg_priority
- tidb_opt_write_row_id 
- tidb_checksum_table_concurrency
- tidb_build_stats_concurrency 
- tidb_partition_prune_mode 
Previously, when system variables listed above be set with invalid values, there are no errors be raised. Now it would returns errors.
```

### CODE REVIEW

**Comment by GoGim1** [comment]
/cc tisonkun 
/cc morgo 
Please take a look. I hope I do the right thing. Maybe more system variables listed in #35048 could be assign to me after this.

**Comment by morgo** [comment]
LGTM

This obsoletes https://github.com/pingcap/tidb/pull/35049 - please also note that it causes a minor incompatibility because invalid values for tidb-force-priority are treated differently.

**Comment by Ehco1996** [comment]
> /cc Ehco1996

can you tell me why you choose me to review this part code ? I am actually not very familiar with this part 🤣

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by bb7133** [comment]
Since the type of `tidb_checksum_table_concurrency` and `tidb_current_ts` are changed and they are potentially relied on by ecosystem tools. I would like to invite another reviewer for it:

PTAL @3pointer

**Comment by morgo** [comment]
@3pointer if you are not familiar with "Type" in the sysvar API, see https://github.com/pingcap/tidb/issues/35048 heading: `What does "Type" do?`

**Comment by GoGim1** [comment]
> LGTM
> 
> This obsoletes #35049 - please also note that it causes a minor incompatibility because invalid values for tidb-force-priority are treated differently.

done

**Comment by GoGim1** [comment]
> > /cc Ehco1996
> 
> can you tell me why you choose me to review this part code ? I am actually not very familiar with this part 🤣

Sorry to bother you.  
/uncc Ehco1996  
/uncc tisonkun

**Comment by GoGim1** [comment]
/cc 3pointer 
Hi! Please take a look when you are free. Thanks.😃

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
