### PR TITLE
planner: enforce projection push down (#25450)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25450 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25741
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25741:release-5.1-9ca449b8bd3a
```

---

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary: if enforced MPP, we push down projection to tiflash.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

### Release note 

- No release note

### CODE REVIEW

**Review by lzmhhh123 — APPROVED** [review]

**Review by LittleFall — APPROVED** [review]
LGTM

**Review by fzhedu — APPROVED** [review]
/LGTM

**Pull request merged**
