### PR TITLE
executor: add concurrency limit on union executor (#19827)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19827 to release-3.0

---

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
1. Use system variable tidb_executor_concurrency to control the concurrency on union executor.
2. Create n worker to pull result from executors.
3. Close children executors that has been opened.

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch 4.0

### Check List 

Tests 

- Unit test

Side effects

- Performance regression

### Release note 

- Support adjust the concurrency on union executor.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Please address conflict @wshwsh12

**Comment by tiancaiamao** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
LGTM

**Review by XuHuaiyu — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
