### PR TITLE
session: don't retry in BatchInsert mode

### PR DESCRIPTION
**Pull request by tiancaiamao**
We got some error log like this, but miss the detail:

```
2018/01/23 21:26:42.170 conn.go:428: [warning] [328] dispatch error:
id:328, addr:10.9.189.208:54476 status:2, collation:utf8_general_ci, user:tidb
"insert into insight.gad_source_data_20180123 select * from insight.gad_source_data where ds='2018-01-21'"
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/executor/write.go:756: [executor:10]BatchInsert failed with error: [variable:1]cannot get valid auto-increment id in retry
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/executor/adapter.go:236: 
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/tidb.go:172: 
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:667: 
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:747: 
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/server/conn.go:739:
```

BatchInsert is true, the InsertExec auto commit the transaction, and meet this error when it retry.
There may be a potential problem here, we'd better log more details so that it's easier to trace the next time.

@shenli @hicqu

### CODE REVIEW

**Comment by tiancaiamao** [comment]
The TiDB version is v1.0.5

**Comment by zimulala** [comment]
The error message is too large. I think we'd better put the error stack to log.

**Comment by shenli** [comment]
I think we should disable automatic retry when BatchInsert is ON.

**Comment by tiancaiamao** [comment]
> I think we should disable automatic retry when BatchInsert is ON.

Why?

**Comment by winkyao** [comment]
>I think we should disable automatic retry when BatchInsert is ON.

I think we should figure out what happen, then we decide how to solve it.

**Comment by shenli** [comment]
@winkyao When using BatchInsert mode, insert statement will not be retryable. For example, running `Insert into t from select * from t1;`. Let's say that there are 100k rows in t1, and the statement meet a retryable error after the second batch (which means 20k rows has already inserted into t). If we retry is in session.go, we will try to insert the whole t1 table into t again. Which means there will be 120k rows.
We should return the error to the user and let the user do the cleanup job.

**Comment by tiancaiamao** [comment]
PTAL @shenli @winkyao

**Comment by coocood** [comment]
LGTM

**Pull request merged**
