### PR TITLE
store/tikv: export RunGCJob

### PR DESCRIPTION
**Pull request by nolouch**
for https://github.com/pingcap/tidb/issues/3426
export RunGCJob for testing purpose. 
PTAL @disksing @coocood @tiancaiamao

### CODE REVIEW

**Comment by siddontang** [comment]
How does MVCC stability test use this? Any API? Why do we still need gcworker if we want to control GC explicitly?

**Comment by nolouch** [comment]
we will use RunGCJob directly in test ,like https://github.com/pingcap/tidb/pull/3439/files#diff-31a838530193eba6c96ed8d7a7dff61eR279

**Comment by disksing** [comment]
I think it has data race if we create a _GCWorker_, _Start_ it, then manually run a GC job.

**Comment by siddontang** [comment]
I think we don't need to start a GC worker and can use the GC API directly.

**Comment by tiancaiamao** [comment]
This can't guarantee just one instance run GC.
PTAL @zimulala

**Comment by nolouch** [comment]
PTAL @tiancaiamao @siddontang @disksing

**Comment by disksing** [comment]
LGTM.

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
