### PR TITLE
executor: do not show extended stats for dropped columns

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23667

Problem Summary:

`show stats_extended` returns confusing results.

### What is changed and how it works?

What's Changed:

Do not return extended stats for dropped columns.

### Related changes

N/A

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- Do not show extended stats for dropped columns

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by time-and-fate — APPROVED** [review]
/lgtm

**Review by time-and-fate — APPROVED** [review]
/lgtm

**Pull request merged**
