### PR TITLE
metrics: add topsql grafana pannel

### LINKED ISSUE #32832: add topsql related metric in grafana
## Enhancement

As the title said.

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Issue Number: close #32832

Add TopSQL metrics in grafana.

image

### Check List

Tests 

- [ ] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Review by breeswish — APPROVED** [review]

**Comment by zhongzc** [comment]
we can add tikv-related metrics to the `Report Data Count Per Minute` and `Ignore Event Per Minute`

**Review by zhongzc — APPROVED** [review]

**Comment by joccau** [comment]
run-unit-test

**Pull request merged**
