### PR TITLE
executor: fix execute failed when table schema changed

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #33509 

Problem Summary:

### What is changed and how it works?

revert some changes in #12388 that will cause some panic

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

resultSet's columns cache is disabled for different query that will cause a tiny performance down.

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix bug #33509
```

### CODE REVIEW

**Review by cfzjywxk — APPROVED** [review]
We could use the bench bot to verify if there's regression risk.

**Review by tiancaiamao — APPROVED** [review]
LGTM

Do we have a schema version together with the ColumnInfo so we can still reuse the objects and at the same time avoid the bug?

**Comment by lcwangchao** [comment]
> LGTM
> 
> Do we have a schema version together with the ColumnInfo so we can still reuse the objects and at the same time avoid the bug?

I did not found it. Theoretically yes, we can add it but it will be more complicated and may cause some potential bugs

**Pull request merged**
