### PR TITLE
parser/parser.y: add StringType OptCharset OptCollate support

### PR DESCRIPTION
**Pull request by winkyao**
to support sql like "Create Table test(a CHAR(10) CHARACTER SET utf8)", see details:
"https://dev.mysql.com/doc/refman/5.0/en/create-table.html",
data_type:
    ...
    | CHAR[(length)] [BINARY]
      [CHARACTER SET charset_name] [COLLATE collation_name]

### CODE REVIEW

**Comment by ngaut** [comment]
Thank you @winkyao 
Please sign the CLA.

Click the "detail" button on the right side of the line " clahub — Not all contributors have signed the Contributor License Agreement.".

**Comment by winkyao** [comment]
I have signed the CLA now.

**Comment by ngaut** [comment]
LGTM

**Comment by shenli** [comment]
LGTM
Thank you very much! @winkyao

**Pull request merged**
