### PR TITLE
Fixed 386 build

### PR DESCRIPTION
**Pull request by luckcolors**
See #2584.

### CODE REVIEW

**Comment by shenli** [comment]
@luckcolors Thanks! 
The CI is failed: https://travis-ci.org/pingcap/tidb/builds/198371842

**Comment by coocood** [comment]
@luckcolors 
How about defining the constant as int64 type instead?

**Comment by luckcolors** [comment]
Ok i'll test that.

**Comment by luckcolors** [comment]
```gofmt
 (simplify)
./util/types/time.go
make: *** [check] Error 1
```

All tests passed.

**Comment by tiancaiamao** [comment]
`go fmt github.com/pingcap/tidb/util/types` would fix it, or you can try `make check` twice.
@luckcolors

**Comment by coocood** [comment]
@luckcolors 
Any update?

**Comment by luckcolors** [comment]
Sorry about the wait.
Now it's fixed. :)

**Comment by coocood** [comment]
LGTM

@luckcolors 
Thank you for your contribution!

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
