### PR TITLE
README: resize logo, use markdown img syntax

### PR DESCRIPTION
**Pull request by andelf**
- use markdown syntax to include pic
- resize logo image to *x100px
- fix trailing whitespace
- will fix bad logo link on https://hub.docker.com/r/pingcap/tidb/

### CODE REVIEW

**Comment by andelf** [comment]
After this PR is merged, another PR to update image url using service from http://rawgit.com/ .

**Comment by c4pt0r** [comment]
LGTM

**Comment by c4pt0r** [comment]
@ngaut @shenli @iamxy PTAL

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
