### PR TITLE
*: fix ci lint

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs <crazycs520@gmail.com>

### What problem does this PR solve?

```go
executor/executor.go:1671:4: ineffectual assignment to `goCtx` (ineffassign)
                        goCtx = topsql.AttachSQLInfo(goCtx, prepareStmt.NormalizedSQL, prepareStmt.SQLDigest, "", nil)
                        ^
session/session.go:1394:4: ineffectual assignment to `ctx` (ineffassign)
                        ctx = topsql.AttachSQLInfo(ctx, normalized, digest, "", nil)
                        ^
util/execdetails/execdetails.go:738:2: S1023: redundant `return` statement (gosimple)
        return
        ^

```

### Check List 

Tests 

- No code

Side effects

- N/A

### Release note 

- No release note

### CODE REVIEW

**Review by guo-shaoge — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Comment by hi-rustin** [comment]
> /merge

You only need /merge once, and if the test fails, just trigger the failed test. We don't need to /merge as often, and we don't need to rerun all the tests every time, we can just run whichever one fails.

**Pull request merged**
