### PR TITLE
store/tikv: add 1PC grafana panel and lower 1PC log level

### PR DESCRIPTION
**Pull request by sticnarf**
### What problem does this PR solve?

1PC counter is missing from the grafana panel. This PR adds it.

And it's too verbose to print all 1PC commits using INFO level, this PR lowers it to DEBUG.

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

The grafana panel is like 
图片

### Release note 

- No release note

### CODE REVIEW

**Review by youjiali1995 — COMMENTED** [review]
/LGTM

**Review by AndreMouche — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
@ti-chi-bot help me

**Comment by hi-rustin** [comment]
> /run-tics-test

God bless 🙏

**Pull request merged**
