### PR TITLE
variable: Add support for mock globalvars

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Problem Summary:

The tests use a `MockGlobalAcessor`, but the implementation never really worked, and so the tests avoided testing sysvars which needed to use the `GlobalVarAccessor`.

This increases code coverage from 50.5% to 51.7%

### What is changed and how it works?

What's Changed:

This fixes the `MockGlobalAccessor` to work correctly. This only affects tests.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by xiongjiwei — APPROVED** [review]

**Comment by morgo** [comment]
I can't explain why yet, but it looks like this PR is causing tests to fail.

**Comment by morgo** [comment]
The test `TestVecEvalBool` consistently failed because calls to `NewMockGlobalAccessor()` are considerably longer after this PR merges. Most of the time increase is because of the loop on `GetSysVars()` to initialize the variable values.

**Comment by morgo** [comment]
The unstable test is: https://github.com/pingcap/tidb/issues/22212 - it should be unrelated to this PR.

**Comment by morgo** [comment]
This was failing because it make some unstable already tests take longer. But it was not strictly related to this PR. I've not made any changes, but CI is now passing, which is great!

So I am going to go ahead and change it back to mergable.

**Comment by tiancaiamao** [comment]
This commit cause a performance regression, see [here](http://www.zenlife.tk:18081/)
image

**Comment by tisonkun** [comment]
@saowiangJj1994 may I ask what are you doing by quoting a number of commits?

**Pull request merged**
