### PR TITLE
executor: fix hash join sqllogic test block, data race.

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
chery-pick #8374 

### What is changed and how it works?

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8392)

### CODE REVIEW

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by zz-jason** [comment]
Uh, why not cherry-pick https://github.com/pingcap/tidb/pull/8374?

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by zz-jason** [comment]
@lysu @XuHuaiyu @lamxTyler PTAL

**Pull request merged**
