### PR TITLE
*: Annotations and fixes related to gosec

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Follow-up for #26899 

Remove excludes for gosec and annotate and/or fix the issues it found

### Check List 

Side effects

- None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by disksing** [comment]
I'm wondering what impact the TLS versioning requirements will have at the product level. Will it affect some of the older cluster upgrades?

**Comment by dveeden** [comment]
> I'm wondering what impact the TLS versioning requirements will have at the product level. Will it affect some of the older cluster upgrades?

MySQL has deprecated TLSv1.0 and TLSv1.1 in [MySQL 8.0.26](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-26.html) and MySQL 5.7.35 to follow [Deprecating TLSv1.0 and TLSv1.1](https://tools.ietf.org/id/draft-ietf-tls-oldversions-deprecate-02.html) by the IETF.

As TiDB and related tools use Go's crypto/tls which has had good TLS support for ages I don't expect any real issues with TiDB directly.

However there are compatibility issues with some older versions of MySQL software:

- MySQL 5.7.27 and older client libraries (libmysqlclient) and clients (only the Community Edition). This is because those versions used YaSSL instead of OpenSSL and YaSSL doesn't have TLSv1.2 support.
- MySQL Connector/J 8.0.18 and earlier. These versions did support TLSv1.2, but this wasn't enabled by default. See the [note on this page](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html).

PCI-DSS prohibits the use of TLSv1.0 and recommends TLSv1.2 or higher.

**Comment by dveeden** [comment]
Changed the minimum TLS version to TLSv1.1 as that should have a lot less compatibility issues:

- TLSv1.1 is supported by YaSSL
- MySQL 5.6 and older (including clients and client libraries) don't support anything else than TLSv1.0, this still breaks
- All MySQL 5.7 versions should work now (including the ones with YaSSL)
- All MySQL Connector/J versions should work now.

Still good to get rid of TLSv1.1 eventually, but that's too big of a step right now, let's first remove TLSv1.0.

**Comment by disksing** [comment]
@dveeden Thank you for the detailed explanation. I'd like to suggest moving the TLS minimum version changes to a separate Pull Request to make it easier to distinguish changes that affect compatibility from those that don't matter. (we can just suppress the warning in this one)

Also regarding the incompatibility issue, I'm thinking if we can add a configure option in case user really does need to use a lower version of the client.

**Comment by dveeden** [comment]
> @dveeden Thank you for the detailed explanation. I'd like to suggest moving the TLS minimum version changes to a separate Pull Request to make it easier to distinguish changes that affect compatibility from those that don't matter. (we can just suppress the warning in this one)
Yes, agreed. Let's split this out in a separate PR

**Review by disksing — APPROVED** [review]

**Comment by disksing** [comment]
I've updated the description to remove TLS stuff.
Please help to take a look. /cc @jackysp @kennytm

**Review by jackysp — APPROVED** [review]
LGTM

**Comment by dveeden** [comment]
Who else should should review this before this can get merged?

**Comment by disksing** [comment]
Please take a look. @pingcap/sql-infra-reviewers

**Review by xhebox — APPROVED** [review]

**Pull request merged**
