### PR TITLE
config, server: Add graceful shutdown option (#20649)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20649 to release-4.0

---

### What problem does this PR solve?

Issue Number: Fixes https://github.com/pingcap/tidb/issues/20619

Problem Summary:

Shutting down the server immediately is problematic in load balancing scenarios. The load balancer may not detect the instance has shutdown fast enough and continue to route stray requests. Requests already in flight may also be terminated.

This PR adds a server configuration option to start returning "unhealthy" to the load balancer health check. It will wait `N` seconds before starting the shutdown procedure (default: 0, maintains compatibility).

### What is changed and how it works?

What's Changed:

A configuration option has been added for `GracefulWaitBeforeShutdown`.

How it Works:

If `GracefulWaitBeforeShutdown` > 0, the server will set the load balancer status to unhealthy and then wait this many seconds before starting the shutdown procedure.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

Side effects

- Slower test suite (it needs to sleep 2-3 seconds to realistically test the feature).

### Release note 

- TiDB now supports the ability to gracefully remove instances from behind a load balancer. The configuration setting `graceful-wait-before-shutdown` allows you to specify the number of seconds to wait before starting the shutdown procedure.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM

**Review by aylei — APPROVED** [review]
lgtm

**Review by tiancaiamao — APPROVED** [review]

**Comment by nullnotnil** [comment]
sorry, I just had to fix a conflict. It will need another LGTM for approval.

**Review by zz-jason — APPROVED** [review]
LGTM

**Pull request merged**
