### PR TITLE
statistics: remove existing deleted extended stats when add a new one

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23107

Problem Summary:

`alter table add stats_extended` cannot work after `alter table drop stats_extended`.

### What is changed and how it works?

What's Changed:

Remove existing extended stats record with 'deleted' status in `alter table add stats_extended`. Also, remove the cache item and bump the stats version.

How it Works:

### Related changes

N/A

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- Remove existing deleted extended stats when add a new one

### CODE REVIEW

**Review by time-and-fate — COMMENTED** [review]
Others OK.

**Review by time-and-fate — APPROVED** [review]
/lgtm

**Review by Reminiscent — APPROVED** [review]
/LGTM

**Comment by Reminiscent** [comment]
@eurekaka Please solve the conflicts.

**Pull request merged**
