### PR TITLE
config: show tidb_force_priority should be same as config (#9342)

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve? 
Cherry-pick #9342 to release 2.1.

### CODE REVIEW

**Comment by jackysp** [comment]
/run-all-tests tidb-test=release-2.1 tikv-release-2.1 pd=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
