### PR TITLE
executor: grant privilege to table now check table existence use case insensitive (#36778)

### LINKED ISSUE #34610: `GRANT` is not case insensitive in GRANT SELECT ON tablename
### 1. Minimal reproduce step 
```sql
DROP DATABASE IF EXISTS d1; 

CREATE DATABASE d1;
USE d1;
CREATE USER user_1@localhost;
CREATE TABLE T1(f1 INT);
CREATE TABLE t1(f1 INT);
GRANT SELECT ON T1 to user_1@localhost;
GRANT SELECT ON t1 to user_1@localhost;

DROP DATABASE d1;
DROP USER user_1@localhost;
```
### 2. What did you expect to see? 
```sql
mysql> CREATE TABLE T1(f1 INT);
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE t1(f1 INT);
ERROR 1050 (42S01): Table 't1' already exists

mysql> GRANT SELECT ON T1 to user_1@localhost;
Query OK, 0 rows affected (0.00 sec)

mysql> GRANT SELECT ON t1 to user_1@localhost;
Query OK, 0 rows affected (0.00 sec)
```

### 3. What did you see instead
```sql
tidb> CREATE TABLE T1(f1 INT);
Query OK, 0 rows affected (0.00 sec)

tidb> CREATE TABLE t1(f1 INT);
ERROR 1050 (42S01): Table 'd1.t1' already exists

tidb> GRANT SELECT ON T1 to user_1@localhost;
Query OK, 0 rows affected (0.01 sec)

tidb> GRANT SELECT ON t1 to user_1@localhost;  -- not case insesitive, Table 'd1.t1' already exists
ERROR 1146 (42S02): Table 'd1.t1' doesn't exist     
```

### 4. What is your TiDB version? 
```
tidb_version(): Release Version: v6.1.0-alpha-391-g901f042d5
Edition: Community
Git Commit Hash: 901f042d5d3cca6c52e8d4921e109b2b6f14f594
Git Branch: master
UTC Build Time: 2022-05-12 03:19:29
GoVersion: go1.18.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #36778 to release-6.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/36798
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/36798:release-6.1-671fe7087607
```

---

### What problem does this PR solve?

Issue Number: close #34610

Problem Summary:

### What is changed and how it works?

The default behaviour of checking table existence is case sensitive in mysql.
But in mysql the default value for `lower_case_table_names` is 0.

In TiDB, that value is 2, and the behaviour should be non-compatible too.
According to https://docs.pingcap.com/zh/tidb/dev/mysql-compatibility and https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
When `lower_case_table_names = 2`, table name comparison should use lower case.

After this change, the issues/34610 seems more reasonable.

```
tidb> CREATE TABLE T1(f1 INT);
Query OK, 0 rows affected (0.00 sec)

tidb> CREATE TABLE t1(f1 INT);
ERROR 1050 (42S01): Table 'd1.t1' already exists

tidb> GRANT SELECT ON T1 to user_1@localhost;
Query OK, 0 rows affected (0.01 sec)

tidb> GRANT SELECT ON t1 to user_1@localhost;
Query OK, 0 rows affected (0.01 sec)
```

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Grant privilege of a table to an user checks the target table exist first, in the past, the table name comparison works in a case sensitive manner, now it's changed to case insensitive.
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by tiancaiamao** [comment]
Don't cherry-pick this one because:
1. it's nothing serious and even vague to be defined as a bug
2. there is a tiny behaviour change

**Pull request merged**
