### PR TITLE
server: tiny refactor, more go style

### PR DESCRIPTION
**Pull request by ngaut**
**What problem does this PR solve?**
tiny refactor, use native go style

**What is changed and how it works?**
Remove redundant default value initialization.

### CODE REVIEW

**Comment by shenli** [comment]
@ngaut Please keep and fill the PR template.

**Comment by ngaut** [comment]
I have no idea why the unit test failed, can someone take a look?

**Comment by zz-jason** [comment]
```

**Comment by zz-jason** [comment]
@jackysp PTAL

**Comment by ngaut** [comment]
There is a failed unit test. Sound like it's batch processing related.

FAIL: region_request_test.go:92: testRegionRequestSuite.TestOnSendFailedWithCloseKnownStoreThenUseNewOne

region_request_test.go:127:
    c.Assert(err, IsNil)
... value *errors.withStack = [tikv:9002]TiKV server timeout ("[tikv:9002]TiKV server timeout")



**There are lots of messages like these:**
[2019/07/29 05:39:56.119 +00:00] [ERROR] [client_batch.go:255] ["batchRecvLoop re-create streaming fail"] [target=localhost:56341] [error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:56341: connect: connection refused\""] [stack="github.com/pingcap/tidb/store/tikv.(*batchCommandsClient).reCreateStreamingClientOnce\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:255\ngithub.com/pingcap/tidb/store/tikv.(*batchCommandsClient).reCreateStreamingClient\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:327\ngithub.com/pingcap/tidb/store/tikv.(*batchCommandsClient).batchRecvLoop\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:285"]
[2019/07/29 05:39:56.119 +00:00] [ERROR] [client_batch.go:255] ["batchRecvLoop re-create streaming fail"] [target=localhost:56341] [error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:56341: connect: connection refused\""] [stack="github.com/pingcap/tidb/store/tikv.(*batchCommandsClient).reCreateStreamingClientOnce\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:255\ngithub.com/pingcap/tidb/store/tikv.(*batchCommandsClient).reCreateStreamingClient\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:327\ngithub.com/pingcap/tidb/store/tikv.(*batchCommandsClient).batchRecvLoop\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:285"]
[2019/07/29 05:39:56.192 +00:00] [ERROR] [client_batch.go:255] ["batchRecvLoop re-create streaming fail"] [target=localhost:56341] [error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:56341: connect: connection refused\""] [stack="github.com/pingcap/tidb/store/tikv.(*batchCommandsClient).reCreateStreamingClientOnce\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:255\ngithub.com/pingcap/tidb/store/tikv.(*batchCommandsClient).reCreateStreamingClient\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:327\ngithub.com/pingcap/tidb/store/tikv.(*batchCommandsClient).batchRecvLoop\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:285"]
[2019/07/29 05:39:56.196 +00:00] [INFO] [region_cache.go:557] ["switch region leader to specific leader due to kv return NotLeader"] [regionID=3] [currIdx=1] [leaderStoreID=1]
[2019/07/29 05:39:56.197 +00:00] [ERROR] [client_batch.go:255] ["batchRecvLoop re-create streaming fail"] [target=localhost:56341] [error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:56341: connect: connection refused\""] [stack="github.com/pingcap/tidb/store/tikv.(*batchCommandsClient).reCreateStreamingClientOnce\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:255\ngithub.com/pingcap/tidb/store/tikv.(*batchCommandsClient).reCreateStreamingClient\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:327\ngithub.com/pingcap/tidb/store/tikv.(*batchCommandsClient).batchRecvLoop\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:285"]
[2019/07/29 05:39:56.198 +00:00] [WARN] [backoff.go:313] ["updateLeader backoffer.maxSleep 100ms is exceeded, errors:\nsend tikv request error: connection refused, ctx: region ID: 3, meta: id:3 region_epoch:<conf_ver:1 > peers:<id:2 store_id:1 > peers:<id:5 store_id:4 > , peer: id:2 store_id:1 , addr: store1, idx: 0, try next peer later at 2019-07-29T05:39:56.196118644Z\nnot leader: region_id:3 leader:<id:2 store_id:1 > , ctx: region ID: 3, meta: id:3 region_epoch:<conf_ver:1 > peers:<id:2 store_id:1 > peers:<id:5 store_id:4 > , peer: id:5 store_id:4 , addr: store4, idx: 1 at 2019-07-29T05:39:56.198394785Z"]
[2019/07/29 05:39:56.199 +00:00] [ERROR] [client_batch.go:255] ["batchRecvLoop re-create streaming fail"] [target=localhost:56341] [error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:56341: connect: connection refused\""] [stack="github.com/pingcap/tidb/store/tikv.(*batchCommandsClient).reCreateStreamingClientOnce\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:255\ngithub.com/pingcap/tidb/store/tikv.(*batchCommandsClient).reCreateStreamingClient\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:327\ngithub.com/pingcap/tidb/store/tikv.(*batchCommandsClient).batchRecvLoop\n\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:285"]

**Comment by ngaut** [comment]
One more flaky test.

FAIL: update_test.go:78: testUpdateSuite.TestUpdateGenColInTxn

update_test.go:86:
    tk.MustExec(`commit;`)
/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:182:
    tk.c.Assert(err, check.IsNil, check.Commentf("sql:%s, %v, error stack %v", sql, args, errors.ErrorStack(err)))
... value *errors.withStack = [kv:6]Error: KV error safe to retry %s [try again later] ("[kv:6]Error: KV error safe to retry %s [try again later]")
... sql:commit;, [], error stack [kv:6]Error: KV error safe to retry %s [try again later]
github.com/pingcap/errors.AddStack
	/go/pkg/mod/github.com/pingcap/errors@v0.11.4/errors.go:174
github.com/pingcap/errors.Trace
	/go/pkg/mod/github.com/pingcap/errors@v0.11.4/juju_adaptor.go:15
github.com/pingcap/tidb/util/testkit.(*TestKit).Exec
	/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:147
github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec
	/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:181
github.com/pingcap/tidb/executor_test.(*testUpdateSuite).TestUpdateGenColInTxn
	/go/src/github.com/pingcap/tidb/executor/update_test.go:86

**Comment by jackysp** [comment]
@lysu is investigating it. @ngaut

**Comment by ngaut** [comment]
PTAL

**Pull request merged**
