### PR TITLE
domain: migrate test-infra to testify (part 0)

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

### What problem does this PR solve?

Issue Number: ref #26306

split from #26307 , [0/2]

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by mmyj — APPROVED** [review]
lgtm

**Comment by b41sh** [comment]
LGTM, but I am not a reviewer of `sql-infra`

**Comment by tisonkun** [comment]
> LGTM, but I am not a reviewer of `sql-infra`

sorry to bother you. I think we should break the barrier within a single repo though...

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
