### PR TITLE
server: add sql to com_exec/com_fetch dispatch error log

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

More and more user use prepare stmt, but current dispatch error log we only can see packet binary info, we don't know which sql meet error.

### What is changed and how it works?

add sql to error thrown in handleStmtExec and handleStmtFetch

after this PR, we can got

```
[2019/09/12 15:38:43.715 +08:00] [WARN] [conn.go:669] ["command dispatched failed"] [conn=1] [connInfo="id:1, addr:127.0.0.1:43540 status:2, collation:utf8_general_ci, user:root"] [command=Fetch] [sql="\u0001\u0000\u0000\u0000\u0001\u0000\u0000\u0000"] [err="12121\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmtFetch\n\t/home/robi/code/go/src/github.com/pingcap/tidb/server/conn_stmt.go:239\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/robi/code/go/src/github.com/pingcap/tidb/server/conn.go:914\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/robi/code/go/src/github.com/pingcap/tidb/server/conn.go:653\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/robi/code/go/src/github.com/pingcap/tidb/server/server.go:438\nruntime.goexit\n\t/home/robi/runtime/go/src/runtime/asm_amd64.s:1337\nselect 1"]
```

("select 1" now is in last, we can modify pingcap/errors to let be in front, but we need add msg first)

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - wrap error message with sql

Side effects

 - N/A

Related changes

 - Need to cherry-pick to the release branch

Release note

 - server: add sql to com_exec/com_fetch dispatch error log

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/12174)

### CODE REVIEW

**Comment by ngaut** [comment]
Could you remove the stack error message, it feels like noise.

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
