### PR TITLE
ddl/ddl_test.go: refactor testSchemaInfo to return error #29964

### PR DESCRIPTION
**Pull request by clovis1122**
By returning an error instead of performing an assertion, it allows the caller to decide how to handle the errors.

This is also helpful when the caller wants more flexibility with the assertion (using check Vs require).

### What problem does this PR solve?

Issue Number:

Problem Summary:

### What is changed and how it works?

It refactors `testSchemaInfo` so that it no longer accept a check argument. Instead, it will return an error.

Related: #29964

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by clovis1122** [comment]
@xhebox @bb7133 @tisonkun hey guys! Can I get a review for this one?

**Review by xhebox — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
