### PR TITLE
executor: merge ApplyExec and NestedLoopJoin into NestedLoopApply.

### PR DESCRIPTION
**Pull request by coocood**
NestedLoopJoin is only used in ApplyJoinExec and ApplyJoinExec only has NestedLoopJoin.
Merge them into one simplifies the logic.

### CODE REVIEW

**Comment by coocood** [comment]
@zz-jason @winoros PTAL

**Comment by zz-jason** [comment]
support rebuilding small child in another pr ?

**Comment by coocood** [comment]
@zz-jason 
Yes, after chunk is supported.

**Comment by zz-jason** [comment]
LGTM

**Pull request merged**
