### PR TITLE
*: set `TIDB_EDITION` when build enterprise tidb

### LINKED ISSUE #43683: support build right enterprise version
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

The build script should build tidb enterprise version with right envrionment variables

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: ref #42188 close #43683

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

It works after `make enterprise-server`

```
./bin/tidb-server -V
Release Version: v7.2.0-alpha-125-g5c31e1694-dirty
Edition: Enterprise
Git Commit Hash: 5c31e169446f34e398dc63f34f4208d67b4186c6
Git Branch: master
UTC Build Time: 2023-05-10 07:05:02
GoVersion: go1.20.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
```

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by wuhuizuo** [comment]
/hold
Need to test new build and test jobs(WIP)

**Review by CbcWestwolf — APPROVED** [review]

**Pull request merged**
