### PR TITLE
store/tikv: Expose all fields of TxnStatus struct

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What problem does this PR solve?

This PR exposes all fields of the `TxnStatus` struct. As a public API, `GetTxnStatus` method of `LockResolver` returns a instance of `TxnStatus` to represent the result. However if the `TxnStatus` doesn't expose all its information, it makes the API not so useful.

I submitted this PR because this helps me in implementing Large Transaction support for CDC.

### Related changes

- Need to cherry-pick to the release branch
  - release-4.0

### Check List 

Tests 

- No code

Side effects

- No

### Release note 
* No release note

### CODE REVIEW

**Comment by MyonKeminta** [comment]
@coocood @overvenus  PTAL thanks!

**Comment by MyonKeminta** [comment]
Can anyone help me label this PR need-cherry-pick-4.0? I don't have permission...

**Comment by coocood** [comment]
LGTM

**Comment by MyonKeminta** [comment]
?
/merge

**Pull request merged**
