### PR TITLE
*: Run errcheck and staticcheck via golangci-lint

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number:  https://github.com/pingcap/tidb/issues/22979#issuecomment-892434602

Problem Summary:

- Run `errcheck` and `staticcheck` via `golangci-lint`
- Cleanup `gometalinter`, `gosec` from `Makefile`
- Move `golangci-lint` config to `.golangci.yml`
- Add `stylecheck` and `gosec` to the golangci-lint config

Running everything under a single framework might speed up things and gives a more consistent result.

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by dveeden** [comment]
I created https://github.com/pingcap/tidb/pull/26907/commits/12e1617065c4f79f70b47304382a0e04c67091eb (Draft PR: #26907) to remove some gosec excludes and use annotations instead and/or fix the issues gosec found.

**Review by ngaut — APPROVED** [review]
LGTM

**Pull request merged**
