### PR TITLE
infoschema: Add new columns for information_schema.tiflash_tables (#25678)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25678 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25709
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25709:release-5.1-b0b01a9ef16e
```

---

Signed-off-by: JaySon-Huang <tshent@qq.com>

### What problem does this PR solve?

Issue Number: related to https://github.com/pingcap/tics/pull/2229

Problem Summary: Suspicious that some TiFlash tasks hold snapshot for a long time, prevent PageStorage from GCing old PageFiles. We add some information about the oldest snapshot in TiFlash system tables and want to access them by TiDB system table `information_schema.tiflash_tables`.

### What is changed and how it works?

Add column `STORAGE_{STABLE,DELTA,META}_OLDEST_SNAPSHOT_LIFETIME` and `STORAGE_{STABLE,DELTA,META}_OLDEST_SNAPSHOT_THREAD_ID` for `information_schema.tiflash_tables`

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch: 4.0, 5.0, 5.1

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
  - Deploy a TiFlash contains that commit
  - Deploy a TiDB contains this commit
  - Check the query result of `select * from information_schema.tiflash_tables limit 1`

Side effects

- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]
LGTM

**Comment by JaySon-Huang** [comment]
@zhouqiang-cl PTAL

**Pull request merged**
