### PR TITLE
store/tikv: fix rpc runtime stats collect (#20014)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20014 to release-4.0

---

Signed-off-by: crazycs <crazycs520@gmail.com>

### What problem does this PR solve?

* The rpc runtime stats maybe contain the time of backoff time, but it is not expected.
* The cop runtime stats maybe doesn't contain some rpc stats when cop-worker re-send cop tasks.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test

Side effects

- No

### Release note 

- No.

### CODE REVIEW

**Comment by crazycs520** [comment]
@qw4990 @wjhuang2016 PTAL

**Review by qw4990 — COMMENTED** [review]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by SunRunAway — APPROVED** [review]

**Pull request merged**
