### PR TITLE
planner: don't push down null sensitive join conditions (#19620)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #19620 to release-4.0

---

### What problem does this PR solve?

Issue Number: 

- close https://github.com/pingcap/tidb/issues/3773
- close https://github.com/pingcap/tidb/issues/13743
- close https://github.com/pingcap/tidb/issues/13389
- close https://github.com/pingcap/tidb/issues/12074 as well. A related closed PR: https://github.com/pingcap/tidb/pull/12075.
- close https://github.com/pingcap/tidb/issues/20403

Problem Summary:

- Wong result for some LeftOuterSemiJoin / AntiSemiJoin / AntiLeftOuterSemiJoin queries.

### What is changed and how it works?

What's Changed:

- Correctly maintain NotNull flag for aggregation result columns;
- Mark column arguments of `RowFunc` as `InOperand`;
- Don't push down join conditions containing `InOperand` columns;

How it Works:

- Those filters are kept as `OtherConditions` of join, and can be correctly evaluated then.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- Fix wrong results for some semi join queries.

### CODE REVIEW

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by SunRunAway — APPROVED** [review]
LGTM

**Comment by lzmhhh123** [comment]
Should merge https://github.com/pingcap/tidb-test/pull/1102 first.

**Pull request merged**
