### PR TITLE
Cherry pick follower read to TiDB (#11347)

### PR DESCRIPTION
**Pull request by shldreams**
cherry pick #11347 to 3.1

Fix code conflicts from 4.0 to 3.1. Users can use `tidb_replica_read` session variable to choose reading from leader or follower. To make it consistent with existing behavior, leader will be used by default unless follower is explicitly specified otherwise.

Add a session scope variable `tidb_replica_read` to specify if TiDB should read data from leader or follower.

### CODE REVIEW

**Comment by shldreams** [comment]
@sunxiaoguang  Please help check.

**Comment by sunxiaoguang** [comment]
> /run-common-test tidb-test=pr/906

Looks like build.sh is trying to verify kvproto version which caused common test to fail. What can we do about this? @qrr1995

**Pull request merged**
