### PR TITLE
ddl: show more jobs in the tidb_mdl_view

### LINKED ISSUE #40838: Blocked `alter table <table name> change` statement  does not appear at `mysql.tidb_mdl_view`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Open a TiDB Connection and create t1 table
```sql
mysql -h $TIDB_SERVER1 -P 4000 -u root test
CREATE TABLE t1 (id int not null primary key AUTO_INCREMENT, col1 INT);
```
2. Open another TiDB connection and begin transaction to insert into t1
```sql
begin;
INSERT INTO t1 (col1) VALUES (1),(2),(3),(4),(5);
```
3. Keep the transaction open. Do not commit or rollback
4. Open another TiDB connection and execute `ALTER TABLE t1` to see how metadata lock works

```sql
mysql -h $TIDB_SERVER1 -P 4000 -u root test
ALTER TABLE t1 CHANGE col1 col2 INT;
```

### 2. What did you expect to see? (Required)
`ALTER TABLE t1 CHANGE col1 col2 INT;` is blocked and `mysql.tidb_mdl_view` shows blocked DDL.

### 3. What did you see instead (Required)
`ALTER TABLE t1 CHANGE col1 col2 INT;` is blocked , however no `mysql.tidb_mdl_view` rows returned.

```sql
MySQL [test]> SELECT * FROM mysql.tidb_mdl_view\G
Empty set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

```sql
MySQL [(none)]> SELECT tidb_version() \G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.5.0
Edition: Community
Git Commit Hash: 706c3fa3c526cdba5b3e9f066b1a568fb96c56e3
Git Branch: heads/refs/tags/v6.5.0
UTC Build Time: 2022-12-27 03:50:44
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
1 row in set (0.00 sec)

MySQL [(none)]>
```

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #40838

Problem Summary:

Don't only show the `running` jobs in the `mysql.tidb_mdl_view`. Any DDL jobs which have not been `synced` or `cancelled` can be blocked by the MDL.

### What is changed and how it works?

Modify the where clause in the `tidb_mdl_view`.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Open three connections, in the first one:

```
CREATE TABLE t1 (id int not null primary key AUTO_INCREMENT, col1 INT);
begin;
INSERT INTO t1 (col1) VALUES (1),(2),(3),(4),(5);
```

Then, in the second one:

```
ALTER TABLE t1 CHANGE col1 col2 INT;
```

This statement will be blocked.

Then in the third one:

```
SELECT * FROM mysql.tidb_mdl_view\G
```

We can see the ddl job blocked by the transaction.

### Release note

```release-note
Fix the issue that `mysql.tidb_mdl_view` doesn't contain `done` DDL job which is also blocked by the MDL.
```

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
You can refer to TestMDLView

**Comment by YangKeao** [comment]
> You can refer to TestMDLView

Done. I rewrote the `TestMDLView` to make it suitable to add more cases.

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
