### PR TITLE
store/driver: update client-go and errors

### LINKED ISSUE #29294: Update tikv/client-go with errors changes
## Enhancement

`client-go` has migrated from `pingcap/errors` to `pkg/errors`. Now we can use standard `errors.Is` and `errors.As` to infer error types.

Develop plan:
- update client-go dependency
- replace `errors.Equal` usages with `errors.Is` and `errors.As`.

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?

Issue Number: close #29294

### What is changed and how it works?
- update client-go dependency
- update `pingcap/errors` to latest version
- replace errors.Equal usages with errors.Is and errors.As

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by iosmanthus — APPROVED** [review]
LGTM

**Comment by disksing** [comment]
/wip
investigate some test errors.

**Comment by disksing** [comment]
Investigated the CI error and found that the failing test was introduced by the previous client errors feature (https://github.com/pingcap/tidb/pull/22382). In that PR, `errors.As` was [used to check the type of the error](https://github.com/pingcap/tidb/pull/22382/files#diff-412615e1c1d4c6ae11a7885a11c879778bf401e0967c9c13c4b9dfd1f13ed29aR1106-R1110). 

Unfortunately, previous versions of `pingcap/errors` did not support the `Unwrap` function required by std `errors.{Is, As}` until https://github.com/pingcap/errors/pull/35. 

This PR happens to have upgraded `pingcap/errors`, which will cause cases that previously failed with `errors.As` conversion to now succeed.

It looks like extracting `errors.Error` from the wrap-over errors is the result we want. So I think we should change the expect result of test here, please help to confirm /cc @morgo

**Comment by morgo** [comment]
> Investigated the CI error and found that the failing test was introduced by the previous client errors feature (#22382). In that PR, `errors.As` was [used to check the type of the error](https://github.com/pingcap/tidb/pull/22382/files#diff-412615e1c1d4c6ae11a7885a11c879778bf401e0967c9c13c4b9dfd1f13ed29aR1106-R1110).

Yes, specifically it is only used by this code:

```
		if cc.ctx != nil && cc.ctx.WarningCount() > 0 {
			for _, err := range cc.ctx.GetWarnings() {
				var warn *errors.Error
				if ok := goerr.As(err.Err, &warn); ok {
					code := uint16(warn.Code())
					errno.IncrementWarning(code, cc.user, cc.peerHost)
				}
			}
		}
```

It only needs to extract the code as a uint16 from each warning.  I will confess I don't understand the error code types that well. If you can simplify this code, it will still work fine.

**Review by ngaut — APPROVED** [review]
LGTM

**Comment by disksing** [comment]
> > Investigated the CI error and found that the failing test was introduced by the previous client errors feature (#22382). In that PR, `errors.As` was [used to check the type of the error](https://github.com/pingcap/tidb/pull/22382/files#diff-412615e1c1d4c6ae11a7885a11c879778bf401e0967c9c13c4b9dfd1f13ed29aR1106-R1110).
> 
> Yes, specifically it is only used by this code:
> 
> ```
> 		if cc.ctx != nil && cc.ctx.WarningCount() > 0 {
> 			for _, err := range cc.ctx.GetWarnings() {
> 				var warn *errors.Error
> 				if ok := goerr.As(err.Err, &warn); ok {
> 					code := uint16(warn.Code())
> 					errno.IncrementWarning(code, cc.user, cc.peerHost)
> 				}
> 			}
> 		}
> ```
> 
> It only needs to extract the code as a uint16 from each warning. I will confess I don't understand the error code types that well. If you can simplify this code, it will still work fine.

I didn't mean to change this code here, but upgrading of `pingcap/errors` caused `errors.As` to behave differently than before. This means that some scenarios where `errors.Error` could not be extracted before, can now be extracted via `errors.As`. I'm wonder if this change is acceptable.

**Comment by morgo** [comment]
> I didn't mean to change this code here, but upgrading of `pingcap/errors` caused `errors.As` to behave differently than before. This means that some scenarios where `errors.Error` could not be extracted before, can now be extracted via `errors.As`. I'm wonder if this change is acceptable.

Yes, this is an improvement! If errors could not be extracted before it would mean that some warnings would not publish to the infoschema table. Having them there now is great (it's actually a bug fix; the code might not have tested all scenarios correctly.)

**Comment by disksing** [comment]
> > I didn't mean to change this code here, but upgrading of `pingcap/errors` caused `errors.As` to behave differently than before. This means that some scenarios where `errors.Error` could not be extracted before, can now be extracted via `errors.As`. I'm wonder if this change is acceptable.
> 
> Yes, this is an improvement! If errors could not be extracted before it would mean that some warnings would not publish to the infoschema table. Having them there now is great (it's actually a bug fix; the code might not have tested all scenarios correctly.)

Thanks for your reply. I'll update the tests.

**Review by JmPotato — APPROVED** [review]

**Pull request merged**
