### PR TITLE
executor: make sure "plan.GlobalPlanCache" is initialized before "plan.PlanCacheEnabled" set to true

### LINKED ISSUE #5706: UT failed with panic
discovered in: http://45.249.247.133:8080/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/1193/pipeline
```
goroutine 105 [running]:

github.com/pingcap/tidb/util/kvcache.(*ShardedLRUCache).Put(0xc42084bc50, 0x0, 0x0, 0x10a2f80, 0xc4215a9860)
	/home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/kvcache/sharded_lru.go:53 +0x26
github.com/pingcap/tidb.(*session).Execute(0xc420b98fa0, 0x7fb5a716e080, 0xc420014110, 0xc4203b8300, 0x73, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session.go:808 +0xdff
github.com/pingcap/tidb/ddl/util.LoadDeleteRanges(0x1b211e0, 0xc420b98fa0, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/util/util.go:48 +0x1e0
github.com/pingcap/tidb/ddl.(*delRange).doDelRangeWork(0xc4209b39c0, 0x0, 0x0)
	/home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/delete_range.go:137 +0x242
github.com/pingcap/tidb/ddl.(*delRange).startEmulator(0xc4209b39c0)
	/home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/delete_range.go:121 +0xaf
created by github.com/pingcap/tidb/ddl.(*delRange).start
	/home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/delete_range.go:99 +0x74
```

### PR DESCRIPTION
**Pull request by zz-jason**
fix #5706

### CODE REVIEW

**Comment by zz-jason** [comment]
@winkyao PTAL

**Comment by shenli** [comment]
LGTM

**Comment by coocood** [comment]
@zz-jason Set it back to false after the test?

**Pull request merged**
