### PR TITLE
executor: pessimistic lock on the temporary table should not be written to TiKV

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Avoid any kind of (pessimistic) lock on the temporary table been written to TiKV

Problem Summary:

### What is changed and how it works?

The concept of "lock" is complex.

1. select ... for update 

Basically, **it means lock for the read operation**.
We use MVCC and the transaction isolation level is actually "snapshot isolation", there are locks for the write operation but no locks for the read operation.
"write skew" is problem in "snapshot isolation". To overcome it, we provide "select ... for update" which also lock for read and can be used to fix the "write skew" problem.

2. pessimistic / optimistic

From TiDB 3.0, we start to support the pessimistic transaction mode.
Pessimistic transaction differs from the optimistic transaction that it write locks to the TiKV immediately, instead of caching the changes in memory and write to TiKV until commit.

3. (batch) point get / coprocessor

(batch) point get is a special code path for performance optimization.
With two different implementation, we have to take special care to maintain the  different code path. 
And for the pessimistic transaction, there are some minor behaviour differences between point get /  non-point get request.

**Under any circumstance, operations on the temporary table should not write locks to the TiKV**. 

In https://github.com/pingcap/tidb/pull/24540 we cover the point get and batch point get.
However, there are `2*2*2` = 8 combinations in total, to cover them all, I chose the common code path.

What's Changed:

Filter out the keys belong to the temporary table in `doLockKeys()`, all the pessimistic mode lock goes through this code path.

How it Works:

All the optimistic mode lock should have already been filtered before the 2PC commit in PR https://github.com/pingcap/tidb/pull/24196.

So all the cases are covered after this PR.

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Comment by coocood** [comment]
can we revert https://github.com/pingcap/tidb/pull/24540 now?

**Comment by tiancaiamao** [comment]
> can we revert #24540 now?

I think that would hurt our contributor's feeling or at least discourage their enthusiasm for contribution.
#24540 is not introducing a bug or something wrong, it's just not solve all the cases in one PR.  @coocood

**Comment by coocood** [comment]
> > can we revert #24540 now?
> 
> I think that would hurt our contributor's feeling or at least discourage their enthusiasm for contribution.
> #24540 is not introducing a bug or something wrong, it's just not solve all the cases in one PR. @coocood

Or just remove the code that done duplicated calculation to save CPU?

**Comment by tiancaiamao** [comment]
https://github.com/pingcap/tidb/pull/24540 is reverted, PTAL @coocood

**Pull request merged**
