### PR TITLE
*: add clustered index info in `show index from` stmt

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Problem Summary:

support show index's clustered property in `show index from tbl` stmt

### What is changed and how it works?

What's Changed, How it Works:

add `Clustered` column to `show index from tbl`'s result

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- n/a

### Release note 

- n/a

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/23329)

### CODE REVIEW

**Comment by coocood** [comment]
Seems not a release-blocking feature, can we leave this improvement for the next version?

**Review by tangenta — APPROVED** [review]

**Pull request merged**
