### PR TITLE
server, types: rule out JSON types from new charset framework

### LINKED ISSUE #31366: The inserted result is different with json type in gbk
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set names gbk;
set character_set_connection = utf8mb4;
drop table t;
create table t(a varchar(32), b blob(32), t text(32), j json, d datetime, f set('你好','世界'), e enum('红色','橙色'), index idx(b(16), d)) CHARSET=gbk COLLATE=gbk_bin;
insert into t values("\t","\t","\t",'{"点赞": "你好"}',"2018-10-13", "世界", "红色");
select * from t;

set names gbk;
set character_set_client = utf8mb4;
drop table t1;
create table t1(a varchar(32), b blob(32), t text(32), j json, d datetime, f set('你好','世界'), e enum('红色','橙色'), index idx(b(16), d)) CHARSET=gbk COLLATE=gbk_bin;
insert into t1 values("\t","\t","\t",'{"点赞": "你好"}',"2018-10-13", "世界", "红色");
select * from t1;
```

### 2. What did you expect to see? (Required)
```
mysql> select * from t;
+------+------+------+----------------------+---------------------+--------+--------+
| a    | b    | t    | j                    | d                   | f      | e      |
+------+------+------+----------------------+---------------------+--------+--------+
| 	    | 	    | 	    | {"点赞": "你好"}     | 2018-10-13 00:00:00 | 世界   | 红色   |
+------+------+------+----------------------+---------------------+--------+--------+
1 row in set (0.00 sec)

mysql> select * from t1;
+------+------+------+------------------+---------------------+------+------+
| a    | b    | t    | j                | d                   | f    | e    |
+------+------+------+------------------+---------------------+------+------+
| 	    | 	    | 	    | {"����": "���"}         | 2018-10-13 00:00:00 | ����     | ��ɫ    |
+------+------+------+------------------+---------------------+------+------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)
```
tidb> select * from t;
+------+------+------+----------------------------+---------------------+--------+--------+
| a    | b    | t    | j                          | d                   | f      | e      |
+------+------+------+----------------------------+---------------------+--------+--------+
| 	    | 	    | 	    | {"鐐硅禐": "浣犲ソ"}       | 2018-10-13 00:00:00 | 世界   | 红色   |
+------+------+------+----------------------------+---------------------+--------+--------+
1 row in set (0.00 sec)

tidb> select * from t1;
+------+------+------+----------------------------------+---------------------+------+------+
| a    | b    | t    | j                                | d                   | f    | e    |
+------+------+------+----------------------------------+---------------------+------+------+
| 	    | 	    | 	    | {"����": "����"}                 | 2018-10-13 00:00:00 | ����     | ��ɫ    |
+------+------+------+----------------------------------+---------------------+------+------+
1 row in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

```
| Release Version: v5.5.0-alpha-27-g9acb2c2ad-dirty
Edition: Community
Git Commit Hash: 9acb2c2ad5a3891fd9fb9de27befb986bcc243a7
Git Branch: master
UTC Build Time: 2022-01-05 08:16:38
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #31366.

Problem Summary:
```sql
drop table if exists t;
set names gbk;
set @@character_set_connection = utf8mb4;
create table t(j json);
insert into t values('{"测试": "你好"}');
select j from t;
```

TiDB:
```console
mysql> select j from t;
+----------------------------+
| j                          |
+----------------------------+
| {"娴嬭瘯": "浣犲ソ"}       |
+----------------------------+
```

MySQL:
```console
+----------------------+
| j                    |
+----------------------+
| {"测试": "你好"}     |
+----------------------+
```

In the current procedure of TiDB, the data flow for `{"测试": "你好"}` is as follows:

1. `{"测试": "你好"}` the parser decode it from `@@character_set_client`(gbk) to utf-8, and set `datum.collate` to `@@character_set_connection`(utf8mb4_bin)
2. `{"娴嬭瘯": "浣犲ソ"}` `ConvertTo()` sees the collation of JSON type is `binary`, it encodes the string to `datum.collate`(utf8mb4)
3. `{"娴嬭瘯": "浣犲ソ"}` is stored to JSON column. Before returning the select result to client, because the collation of JSON type is `binary`, no additional conversion is needed.
4. `{"娴嬭瘯": "浣犲ソ"}` is seen finally.

This procedure works well(it is compatible with MySQL) in all other string types like `varchar`, `char`, `text` and `blob`. Only `JSON` is an exception.

From [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/json.html#:~:text=MySQL%20handles%20strings%20used%20in%20JSON%20context%20using%20the%20utf8mb4%20character%20set%20and%20utf8mb4_bin%20collation.%20Strings%20in%20other%20character%20sets%20are%20converted%20to%20utf8mb4%20as%20necessary.):
> MySQL handles strings used in JSON context using the utf8mb4 character set and utf8mb4_bin collation. Strings in other character sets are converted to utf8mb4 as necessary.

### What is changed and how it works?

This PR rules JSON type out of the new character framework, including the the special binary literal handling.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by xiongjiwei — APPROVED** [review]

**Comment by Defined2014** [comment]
Please try this, seems the behaviour of blob also been changed.
https://github.com/pingcap/tidb/issues/31366#issuecomment-1006325335

**Review by Defined2014 — APPROVED** [review]

**Pull request merged**
