### PR TITLE
*: support clustered index table produce binlog

### LINKED ISSUE #24133: Support binlog for clustered index table
## Development Task

- [x] [tidb]support create table when binlog enabled
- [x] [tidb]only add extCol for PKIsHandle
- [x] [tidb]shouldWriteBinlog => true
- [x] [binlog]insert datums
- [x] [binlog]delete datums
- [x] [binlog]update datums
- [x] [binlog]replica prefix primary key

## Test Task

- [ ] Extend Binlog Intergration Test
  - [x] Regression none clustered index table works well
  - [ ] Clustered Index SQL Replica Test
    - [ ] Config
      - [x] ~Row format~(should always be old format) 
      - [x] Combined with collation 
    - [ ] Scheme:
      - [x] 1/2/3 combined PK
      - [ ] PK column in shuffle in table column order
      - [ ] same / shuffle PK column in table column order 
      - [x] prefix columns in PK
    - [x] Operation
      - [x] INSERT
      - [x] UPDATE - change PK or not
      - [x] DELETE 
- [x] Tools Test
  - [x]  With Kafka
  - [x]  Without Kafka
- [ ] Upgrade
  - [ ]  Need upgrade tidb-binlog first then tidb should better.

## Doc or Notice

- need upgrade pump/drainer before upgrade tidb-server

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Issue Number: close #24133

Problem Summary:

### What is changed and how it works?

support output binlog for clustered index table

What's Changed, How it Works:

- support create clustered index when binlog enabled
- shouldn't add ext `__tidb_rowid` for clustered index table

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test in https://github.com/pingcap/tidb-binlog/pull/1040
- Manual test

Side effects

- n/a

### Release note 

- support clustered index table produce binlog 

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/24135)

### CODE REVIEW

**Comment by lysu** [comment]
need merge https://github.com/pingcap/tidb-binlog/pull/1040 first

**Review by tangenta — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
/lgtm

**Pull request merged**
