### PR TITLE
executor: fix `set names` with `default_collation_for_utf8mb4` vars

### LINKED ISSUE #56439: `SET NAMES utf8mb4` does not change `collation_connection` when `default_collation_for_utf8mb4` is modified
## Bug Report

`SET NAMES utf8mb4` does not change `collation_connection` when `default_collation_for_utf8mb4` is modified. 

### 1. Minimal reproduce step (Required)

- Startup tiup playground v8.3.0
```sql
% mysql --comments --host 127.0.0.1 --port 4000 -u root
```
- Confirm the default value of `default_collation_for_utf8mb4`
```sql
mysql> show variables like 'default_collation_for_utf8mb4';
+-------------------------------+-------------+
| Variable_name                 | Value       |
+-------------------------------+-------------+
| default_collation_for_utf8mb4 | utf8mb4_bin |
+-------------------------------+-------------+
1 row in set (0.00 sec)
```
- Confirm the default value of `collation_connection`
```sql
mysql> show variables like 'collation_connection';
+----------------------+--------------------+
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | utf8mb4_general_ci |
+----------------------+--------------------+
1 row in set (0.00 sec)
```
- Change the `default_collation_for_utf8mb4` value to `utf8mb4_general_ci`
```sql
mysql> set default_collation_for_utf8mb4 = 'utf8mb4_general_ci';
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> show variables like 'default_collation_for_utf8mb4';
+-------------------------------+--------------------+
| Variable_name                 | Value              |
+-------------------------------+--------------------+
| default_collation_for_utf8mb4 | utf8mb4_general_ci |
+-------------------------------+--------------------+
1 row in set (0.00 sec)
```

- Execute `SET NAMES utf8mb4`
```sql
mysql> SET NAMES utf8mb4;
Query OK, 0 rows affected (0.00 sec)
```
- Validate the `collation_connection` value after `default_collation_for_utf8mb4` has been modified to `utf8mb4_general_ci`.
```sql
mysql> show variables like 'collation_connection';
+----------------------+-------------+
| Variable_name        | Value       |
+----------------------+-------------+
| collation_connection | utf8mb4_bin |
+----------------------+-------------+
1 row in set (0.00 sec)

mysql>
```

### 2. What did you expect to see? (Required)
The last `collation_connection` value should show `utf8mb4_general_ci` as `default_collation_for_utf8mb4` modified to `utf8mb4_general_ci`

### 3. What did you see instead (Required)
The last `collation_connection` value shows `utf8mb4_bin`.

```
mysql> show variables like 'default_collation_for_utf8mb4';
+-------------------------------+-------------+
| Variable_name                 | Value       |
+-------------------------------+-------------+
| default_collation_for_utf8mb4 | utf8mb4_bin |
+-------------------------------+-------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```sql
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v8.3.0
Edition: Community
Git Commit Hash: 1a0c3ac3292fff7742faa0c00a662ccb66ba40db
Git Branch: HEAD
UTC Build Time: 2024-08-20 10:23:00
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv
1 row in set (0.00 sec)

mysql>
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #56439

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by dveeden — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Comment by yahonda** [comment]
Thank you for the fix. Would you consider to backport this change to 7.5 and 8.1 LTS versions?

**Pull request merged**
