### PR TITLE
executor: fix point get null values

### PR DESCRIPTION
**Pull request by zz-jason**
### What problem does this PR solve? 

Fix the "index out of range" panic caused by point getting all null values.

Let's say we have the following table:
```sql
drop table if exists t;
create table t(a bigint primary key, b bigint, c bigint);
insert into t values(1, NULL, NULL);
```

In master branch, the following query can reach a panic:
```sql
select * from t where a = 1;
```

This PR fixes the above problem.

### What is changed and how it works?

if the length of the returned column values is smaller than the column offset, that indicates the value of that column is null or should be covered by the default value.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by zz-jason** [comment]
@XuHuaiyu @coocood PTAL

**Comment by coocood** [comment]
@zz-jason 
I think the way in mocktikv is easier to understand.
https://github.com/pingcap/tidb/blob/master/store/mockstore/mocktikv/executor.go#L633

Another approach is more safe which is to modify `CutRowNew` to always return `row` with the same length as `colIDs`, then we don't need to make the slice on the caller side.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
