### PR TITLE
*: update test cases to support new collation enabled by default

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve?

This PR provides a way('__TIDB_TEST_NEW_COLLATION_ENABLED = 1') to run all tests with enabled "new collation" configuration.

It will be helpful for us to cover more cases for the new collation tests.

Some of the test cases are updated to fit the enabled new collation; if the new collation is not enabled, existing cases kept the same generally. 

### Release note 

- No release note

### CODE REVIEW

**Comment by bb7133** [comment]
Failed test case: 
* https://github.com/pingcap/tidb/issues/19695
* https://github.com/pingcap/tidb/issues/19697

**Comment by zz-jason** [comment]
I'm going to close this PR since it hasn't been updated for a long time. feel free to reopen if you want to continue with it. thanks for your contribution.

**Pull request closed without merging**
