### PR TITLE
case: make CTE case be stable

### LINKED ISSUE #25034: case unstable:  CTETestSuite.TestSpillToDisk
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

 CTETestSuite.TestSpillToDisk is unstable
### 2. What did you expect to see? (Required)
Be stable
### 3. What did you see instead (Required)
[2021-06-01T09:09:35.522Z] ----------------------------------------------------------------------
[2021-06-01T09:09:35.522Z] FAIL: cte_test.go:110: CTETestSuite.TestSpillToDisk
[2021-06-01T09:09:35.522Z] 
[2021-06-01T09:09:35.522Z] cte_test.go:137:
[2021-06-01T09:09:35.522Z]     c.Assert(diskTracker.MaxConsumed(), check.Greater, int64(0))
[2021-06-01T09:09:35.522Z] ... compare_one int64 = 0
[2021-06-01T09:09:35.522Z] ... compare_two int64 = 0
### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #25034 

Problem Summary: CTETestSuite.TestSpillToDisk is unstable. 

### What is changed and how it works?

What's Changed: 
1. Change CTETestSuite.TestSpillToDisk to CTE**Serial**TestSuite.TestSpillToDisk
2. change code: Wait for the end of iterOutTbl's spilling to disk.
3. On my local machine, run this test for 1000 times, the result looks good. `go test . -test.count 1000 -check.f CTESerialTestSuite.TestSpillToDisk`

### Check List 

Side effects: no, just change case

### Release note 

- No Release not

### CODE REVIEW

**Review by AilinKid — COMMENTED** [review]
/LGTM

**Review by wjhuang2016 — APPROVED** [review]

**Review by ichn-hu — APPROVED** [review]

**Comment by hi-rustin** [comment]
@ti-chi-bot Help!

**Comment by wjhuang2016** [comment]
run-integration-ddl-test

**Comment by guo-shaoge** [comment]
> /run-unit-test

Looks like we got race conditions. I will open an issur for this.

**Pull request merged**
