### PR TITLE
br: Add comment to filterRestoreFiles function

### LINKED ISSUE #33352: br: there is no comment of function filterRestoreFiles
## Enhancement

We need add more comments to br.

### PR DESCRIPTION
**Pull request by WangLe1321**
### What problem does this PR solve?

Issue Number: close #33352

Problem Summary:

### What is changed and how it works?

This adds a comment to `filterRestoreFiles` function, to explain it's effect.

### Check List

Tests 

- [x] No code

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by joccau — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
@WangLe1321 Your commits have different usernames. so you should keep it consistent.

**Pull request merged**
