### PR TITLE
*: add stats version in slow_query and slow log. (#10082)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
cherry-pick #10082

### What is changed and how it works

### CODE REVIEW

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zz-jason** [comment]
LGTM

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by crazycs520** [comment]
Em.. the test was failed because of other reasons, the PR https://github.com/pingcap/tidb/pull/9520 fix this but hasn't cherry pick to 2.1.

**Comment by qw4990** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Pull request merged**
