### PR TITLE
*: fix timestamp conversion

### PR DESCRIPTION
**Pull request by peakji**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/36707

Problem Summary:

This PR fixes inaccurate timestamp conversion algorithms that appeared in various packages.

From the perspective of dimensional analysis, the following algorithm does not hold:

```go
time.Now().UnixNano() / int64(time.Millisecond)
```

> The above calculation doesn't really make sense. You don't divide nanoseconds by miliseconds. It happens to be the case that golang choses to represent times down to nanosecond and the constant 'Millisecond' is 1,000,000. Mathematically speaking, calculation should be: time.Now().UnixNano() * (time.Nanosecond / time.Millisecond).

Reference:  https://stackoverflow.com/a/24122933

I've scanned the code base and implemented a corrected version based on [time.UnixMilli](https://cs.opensource.google/go/go/+/go1.18.4:src/time/time.go;l=1349) and [time.UnixMicro](https://cs.opensource.google/go/go/+/go1.18.4:src/time/time.go;l=1355), which were introduced to the standard library in go 1.17.

Note that [util.TSOToRoughTime](https://github.com/pingcap/tidb/blob/master/util/tso.go) is intentionally unmodified.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by peakji** [comment]
Unit tests are now passing after reverting the resolution change in tests. @hawkingrei please trigger a `\merge`, thanks!

**Pull request merged**
