### PR TITLE
planner: Fix the problem that `PlanBuilder.buildWindowFunctions` may change sub operator's schema.

### PR DESCRIPTION
**Pull request by LittleFall**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/27148 

Problem Summary: `buildWindowFunctions` will use sub operator's schema as itself's, for example, [here](https://github.com/pingcap/tidb/blob/v5.1.1/planner/core/logical_plan_builder.go#L5091-L5095)
```golang
		switch newArg.(type) {
		case *expression.Column, *expression.Constant:
			newArgList = append(newArgList, newArg)
			continue
		}
```
obtains the sub operator's schema, and then changed them [here](https://github.com/pingcap/tidb/blob/v5.1.1/expression/aggregation/base_func.go#L431-L438)
```golang
		if col, ok := a.Args[i].(*expression.Column); ok {
			col.RetType = types.NewFieldType(col.RetType.Tp)
		}
		// originTp is used when the the `Tp` of column is TypeFloat32 while
		// the type of the aggregation function is TypeFloat64.
		originTp := a.Args[i].GetType().Tp
		*(a.Args[i].GetType()) = *(a.RetTp)
		a.Args[i].GetType().Tp = originTp
```

This may cause some unexpected behaviors, for example in mpp query, making the schema of exchangeReceiver and exchangeSender not equal and then throw errors as the issue said.

for example, it will build a plan like:
```
Proj <- Proj <- Window       <- Proj   <- Proj <- Agg  <- DataSource
47,1    47,1    47,1            47,1              47,1
        25,1    25,1            3,1              sum, arg=3,1, ret=25,1
                3,1
                sum
                retTp=47,1
                argTp=47,1
```
the (3,1), (25,1), (47,1) means output schema's attribute `flen` and `decimal` in `typeDecimal`, but the excepted is 
```
Proj <- Proj <- Window       <- Proj   <- Proj <- Agg  <- DataSource
47,1    47,1    47,1            25,1              25,1
        25,1    25,1            3,1              sum, arg=3,1, ret=25,1
                3,1
                sum
                retTp=47,1
                argTp=25,1
```

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: let it obtain a column's clone.

Are there any suggestions for fixing it better?

### Check List 

Tests 

- [x] Integration test
- [x] Manual test (issue fixed.)

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by LittleFall** [comment]
[2021-08-12T20:04:28.602Z] cd tools/check; \

[2021-08-12T20:04:28.602Z] GO111MODULE=on go build -o ../bin/failpoint-ctl github.com/pingcap/failpoint/failpoint-ctl

[2021-08-12T20:04:33.881Z] /bin/sh: Rewrite: command not found

[2021-08-12T20:04:33.881Z] make: *** [failpoint-enable] Error 127

**Review by winoros — APPROVED** [review]

**Comment by LittleFall** [comment]
[2021-08-13T06:22:47.994Z] FAIL

[2021-08-13T06:22:47.994Z] + cat test.log

[2021-08-13T06:22:47.994Z] + grep -Ev '^\[[[:digit:]]{4}(/[[:digit:]]{2}){2}'

[2021-08-13T06:22:47.994Z] + grep -A 30 '\-------'

[2021-08-13T06:22:47.994Z] + grep -A 29 '^FAIL:'

[2021-08-13T06:22:47.994Z] FAIL: ddl_test.go:1302: testSuite6.TestSetDDLErrorCountLimit

[2021-08-13T06:22:47.994Z] 

[2021-08-13T06:22:47.994Z] ddl_test.go:1324:

[2021-08-13T06:22:47.994Z]     c.Assert(variable.GetDDLErrorCountLimit(), Equals, int64(100))

[2021-08-13T06:22:47.994Z] ... obtained int64 = 512

[2021-08-13T06:22:47.994Z] ... expected int64 = 100

**Review by lzmhhh123 — APPROVED** [review]

**Comment by LittleFall** [comment]
[2021-08-13T07:43:16.286Z] + grep -A 29 '^FAIL:'

[2021-08-13T07:43:16.286Z] FAIL: infoschema_reader_test.go:561: testInfoschemaTableSuite.TestForAnalyzeStatus

[2021-08-13T07:43:16.286Z] 

[2021-08-13T07:43:16.286Z] infoschema_reader_test.go:595:

[2021-08-13T07:43:16.286Z]     c.Assert(len(resultT1.Rows()), Greater, 0)

[2021-08-13T07:43:16.286Z] ... compare_one int = 0

[2021-08-13T07:43:16.286Z] ... compare_two int = 0

[2021-08-13T07:43:16.286Z] 

[2021-08-13T07:43:16.286Z] PASS: write_test.go:2076: testSuite4.TestIssue18681	0.034s

[2021-08-13T07:43:16.286Z] PASS: adm

**Comment by LittleFall** [comment]
[2021-08-13T07:57:19.451Z] 

[2021-08-13T07:57:19.451Z] handle_test.go:947:

[2021-08-13T07:57:19.451Z]     s.checkForGlobalStatsWithOpts(c, tk, "test_gstats_opt", "p1", ca.topn, ca.buckets)

[2021-08-13T07:57:19.451Z] handle_test.go:911:

[2021-08-13T07:57:19.451Z]     // since the hist-building algorithm doesn't stipulate the final bucket number to be equal to the expected number exactly,

[2021-08-13T07:57:19.451Z]     // we have to check the results by a range here.

[2021-08-13T07:57:19.451Z]     c.Assert(numBuckets >= buckets-delta, IsTrue)

[2021-08-13T07:57:19.451Z] ... obtained bool = false

**Comment by LittleFall** [comment]
[2021-08-13T08:08:30.284Z] PASS: restart_test.go:143: testStatSuite.TestStat	5.533s

[2021-08-13T08:08:30.284Z] PASS: schema_test.go:125: testSchemaSuite.TestSchema	5.545s

[2021-08-13T08:08:30.284Z] --- PASS: TestDomainSerial (9.10s)

[2021-08-13T08:08:30.284Z] --- PASS: TestSingle (5.06s)

[2021-08-13T08:08:30.284Z] + cat test.log

[2021-08-13T08:08:30.284Z] + grep -A 30 '\-------'

[2021-08-13T08:08:30.284Z] + grep -Ev '^\[[[:digit:]]{4}(/[[:digit:]]{2}){2}'

[2021-08-13T08:08:30.284Z] + grep -A 29 '^FAIL:'

**Comment by LittleFall** [comment]
[2021-08-13T07:57:19.451Z] FAIL: handle_test.go:916: testStatsSuite.TestAnalyzeGlobalStatsWithOpts

[2021-08-13T07:57:19.451Z] 

[2021-08-13T07:57:19.451Z] handle_test.go:947:

[2021-08-13T07:57:19.451Z]     s.checkForGlobalStatsWithOpts(c, tk, "test_gstats_opt", "p1", ca.topn, ca.buckets)

[2021-08-13T07:57:19.451Z] handle_test.go:911:

[2021-08-13T07:57:19.451Z]     // since the hist-building algorithm doesn't stipulate the final bucket number to be equal to the expected number exactly,

[2021-08-13T07:57:19.451Z]     // we have to check the results by a range here.

[2021-08-13T07:57:19.451Z]     c.Assert(numBuckets >= buckets-delta, IsTrue)

[2021-08-13T07:57:19.451Z] ... obtained bool = false

[2021-08-13T07:57:19.451Z]

**Comment by LittleFall** [comment]
[2021-08-13T08:08:30.284Z] grep 'PASS:' gotest.log | go run tools/check/check-timeout.go || { $(find $PWD/ -type d | grep -vE "(\.git|tools)" | xargs tools/bin/failpoint-ctl disable); exit 1; }

[2021-08-13T08:08:30.284Z] The following test cases take too long to finish:

[2021-08-13T08:08:30.284Z] PASS: table_split_test.go:35: testDDLTableSplitSuite.TestTableSplit	5.525s

[2021-08-13T08:08:30.284Z] PASS: restart_test.go:143: testStatSuite.TestStat	5.533s

[2021-08-13T08:08:30.284Z] PASS: schema_test.go:125: testSchemaSuite.TestSchema	5.545s

[2021-08-13T08:08:30.284Z] --- PASS: TestDomainSerial (9.10s)

[2021-08-13T08:08:30.284Z] --- PASS: TestSingle (5.06s)

[2021-08-13T08:08:30.284Z] + cat test.log

[2021-08-13T08:08:30.284Z] + grep -A 30 '\-------'

[2021-08-13T08:08:30.284Z] + grep -Ev '^\[[[:digit:]]{4}(/[[:digit:]]{2}){2}'

[2021-08-13T08:08:30.284Z] + grep -A 29 '^FAIL:'

**Pull request merged**
