### PR TITLE
planner: don't push down topN above outer join when topN refer scalar subquery expression (#20099)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20099 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/20104 

Problem Summary:

topN should not push down it refer columns not belong to outer join's inner side

### What is changed and how it works?

What's Changed, How it Works:

don't push down when ref non-table columns

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

-  n/a

### Release note 

- Fix topN push down rule bug when topN refer scalar subquery column

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/20099)

### CODE REVIEW

**Review by lzmhhh123 — COMMENTED** [review]
@lysu Please fix the test.

```bash
[2020-11-09T03:55:26.904Z] integration_test.go:852:

[2020-11-09T03:55:26.904Z]     tk.MustQuery(tt).Check(testkit.Rows(output[i].Plan...))

[2020-11-09T03:55:26.904Z] /home/jenkins/agent/workspace/tidb_ghpr_check/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:62:

[2020-11-09T03:55:26.904Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)

[2020-11-09T03:55:26.904Z] ... obtained string = "" +

[2020-11-09T03:55:26.904Z] ...     "[Projection_11 1.00 root  test.t.a]\n" +

[2020-11-09T03:55:26.904Z] ...     "[└─Projection_20 1.00 root  test.t.a, test.t.b, Column#8]\n" +

[2020-11-09T03:55:26.904Z] ...     "[  └─TopN_14 1.00 root  Column#10:asc, offset:0, count:1]\n" +

[2020-11-09T03:55:26.904Z] ...     "[    └─Projection_21 10000.00 root  test.t.a, test.t.b, Column#8, and(eq(test.t.b, 1), Column#8)->Column#10]\n" +

[2020-11-09T03:55:26.904Z] ...     "[      └─HashJoin_15 10000.00 root  left outer semi join, equal:[eq(test.t.b, test.t.b)]]\n" +

[2020-11-09T03:55:26.904Z] ...     "[        ├─TableReader_19(Build) 10000.00 root  data:TableFullScan_18]\n" +

[2020-11-09T03:55:26.904Z] ...     "[        │ └─TableFullScan_18 10000.00 cop[tikv] table:t2 keep order:false, stats:pseudo]\n" +

[2020-11-09T03:55:26.904Z] ...     "[        └─TableReader_17(Probe) 10000.00 root  data:TableFullScan_16]\n" +

[2020-11-09T03:55:26.904Z] ...     "[          └─TableFullScan_16 10000.00 cop[tikv] table:t1 keep order:false, stats:pseudo]\n"

[2020-11-09T03:55:26.904Z] ... expected string = "" +

[2020-11-09T03:55:26.904Z] ...     "[Projection_11 1.00 root  test.t.a]\n" +

[2020-11-09T03:55:26.904Z] ...     "[└─Projection_20 1.00 root  test.t.a, test.t.b, Column#8]\n" +

[2020-11-09T03:55:26.904Z] ...     "[  └─TopN_14 1.00 root  Column#10, offset:0, count:1]\n" +

[2020-11-09T03:55:26.904Z] ...     "[    └─Projection_21 10000.00 root  test.t.a, test.t.b, Column#8, and(eq(test.t.b, 1), Column#8)->Column#10]\n" +

[2020-11-09T03:55:26.904Z] ...     "[      └─HashJoin_15 10000.00 root  left outer semi join, equal:[eq(test.t.b, test.t.b)]]\n" +

[2020-11-09T03:55:26.904Z] ...     "[        ├─TableReader_19(Build) 10000.00 root  data:TableFullScan_18]\n" +

[2020-11-09T03:55:26.904Z] ...     "[        │ └─TableFullScan_18 10000.00 cop[tikv] table:t2 keep order:false, stats:pseudo]\n" +

[2020-11-09T03:55:26.904Z] ...     "[        └─TableReader_17(Probe) 10000.00 root  data:TableFullScan_16]\n" +

[2020-11-09T03:55:26.904Z] ...     "[          └─TableFullScan_16 10000.00 cop[tikv] table:t1 keep order:false, stats:pseudo]\n"

[2020-11-09T03:55:26.904Z] ... sql:desc select t1.a from t t1 order by (t1.b = 1 and exists (select 1 from t t2 where t1.b = t2.b)) limit 1, args:[]
```

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by zz-jason — APPROVED** [review]
LGTM

**Pull request merged**
