### PR TITLE
statistics: add more test cases for global-stats with different analysis options

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary: statistics: add more test cases for global-stats with different analysis options

### What is changed and how it works?
statistics: add more test cases for global-stats with different analysis options

### Check List 

Tests 

- Unit test

### Release note 

- statistics: add more test cases for global-stats with different analysis options

### CODE REVIEW

**Review by rebelice — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]
/LGTM

**Pull request merged**
