### PR TITLE
parser: support some table options, only in parser.

### PR DESCRIPTION
**Pull request by siddontang**

### CODE REVIEW

**Comment by qiuyesuifeng** [comment]
An golint error `parser/coldef/opt.go:137:2: comment on exported const TblOptDataDirectory should be of the form "TblOptDataDirectory ..."`

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM @shenli

**Comment by shenli** [comment]
LGTM

**Pull request merged**
