### PR TITLE
parser: add support [NO_WRITE_TO_BINLOG | LOCAL] syntax in the ANALYZE statement

### LINKED ISSUE #49235: Invalid parsing of the ANALYZE statement with [NO_WRITE_TO_BINLOG | LOCAL]
### 1. Minimal reproduce step (Required)

```go
package main

import (
	"fmt"
	"log"

	"github.com/pingcap/tidb/pkg/parser"
	"github.com/pingcap/tidb/pkg/parser/ast"
	_ "github.com/pingcap/tidb/pkg/types/parser_driver"
)

func main() {
	p := parser.New()
	stmt, warn, err := p.ParseSQL("analyze NO_WRITE_TO_BINLOG table t")
	if err != nil {
		log.Fatalln(err)
	}
	fmt.Println(ast.GetStmtLabel(stmt[0]), warn)
}
```

### 2. What did you expect to see? (Required)
```shell
ub-3@local:~$ go run test.go 
AnalyzeTable []
```
### 3. What did you see instead (Required)
```shell
ub-3@local:~$ go run test.go 
2023/12/09 16:15:57 line 1 column 26 near "NO_WRITE_TO_BINLOG table t" 
exit status 1
```
### 4. What is your TiDB version? (Required)
```
github.com/pingcap/tidb v1.1.0-beta.0.20231208120617-d23e1c379a52
github.com/pingcap/tidb/pkg/parser v0.0.0-20231208120617-d23e1c379a52
```

### PR DESCRIPTION
**Pull request by ub-3**
### What problem does this PR solve?

Issue Number: close #49235 

Problem Summary: There is no support for the `[NO_WRITE_TO_BINLOG | LOCAL]` parameter in the ANALYZE statement

### What changed and how does it work?

Parsing of the `ANALYZE` statement with the `[NO_WRITE_TO_BINLOG | LOCAL]` parameter is now supported.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [x] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Add support [NO_WRITE_TO_BINLOG | LOCAL] syntax in the ANALYZE statement.
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
ptal @Defined2014 @mjonss @bb7133

**Review by Defined2014 — APPROVED** [review]

**Comment by easonn7** [comment]
/approve

The parser correctly parses "ANALYZE [NO_WRITE_TO_BINLOG | LOCAL] TABLE," and it aligns with MySQL syntax. Meanwhile, the planner can generate an error message to inform the client that TiDB does not currently support this feature, preventing any misunderstanding. So LGTM

**Review by tangenta — APPROVED** [review]

**Pull request merged**
