### PR TITLE
executor, tests: move some test cases from `ddl_test.go`, `split_table_test.go` and `write_test.go` to `integrationtest`

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: ref #47076

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Comment by Defined2014** [comment]
```
time="2023-09-28T21:30:30+08:00" level=error msg="run test [planner/core/integration] err: sql:select a from deci union ALL select b from deci;: failed to run query \n\"select a from deci union ALL select b from deci;\" \n around line 1909, \nwe need(160):\nselect a from deci union ALL select b from deci;\na\n1234567890.123456789012345678901234567890\n99999999999999999999999999999999999.999999999999999999999999999999\n\nbut got(160):\nselect a from deci union ALL select b from deci;\na\n99999999999999999999999999999999999.999999999999999999999999999999\n1234567890.123456789012345678901234567890\n\n"
```

@YangKeao Found an unstable tests, need add `--sorted_result` for this sql.

**Review by hawkingrei — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
