### PR TITLE
planner: refine the explain message of expression (#16276) (#20410)

### LINKED ISSUE #16276: UCP: Refine the explain message of expression
## Description

```
TiDB(root@127.0.0.1:test) > create index expr_idx on t((lower(a)));
Query OK, 0 rows affected (0.02 sec)

TiDB(root@127.0.0.1:test) > explain select lower(a) from t where lower(a) = 'a';
+------------------------+---------+-----------+-----------------------------------------+-------------------------------------------------+
| id                     | estRows | task      | access object                           | operator info                                   |
+------------------------+---------+-----------+-----------------------------------------+-------------------------------------------------+
| IndexReader_6          | 10.00   | root      |                                         | index:IndexRangeScan_5                          |
| └─IndexRangeScan_5     | 10.00   | cop[tikv] | table:t, index:expr_idx(_V$_expr_idx_0) | range:["a","a"], keep order:false, stats:pseudo |
+------------------------+---------+-----------+-----------------------------------------+-------------------------------------------------+
2 rows in set (0.00 sec)
```

index:expr_idx(_V$_expr_idx_0)

The `_V$_expr_idx_0` is used internally and should be output as the expression of the index.

## Score

* 300

## Mentor(s)

* @wjhuang2016 

Contact the mentors: **#sig-planner** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang

## Learning Materials

* Chinese: [表达式索引](https://pingcap.com/docs-cn/stable/reference/sql/statements/create-index/#create-index)
* English: [expression index](https://pingcap.com/docs/stable/reference/sql/statements/create-index/#create-index)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20410 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #16276 

Problem Summary:
The _V$_expr_idx_0 is used internally and should be output as the expression of the index.

### What is changed and how it works?

What's Changed:
`_V$_expr_idx_0` replace to expression index name

How it Works:
When columns.Hidden is true, show columns.GeneratedExprString

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- explain command uses expression index name

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
LGTM

**Review by SunRunAway — APPROVED** [review]
LGTM

**Comment by tiancaiamao** [comment]
Waiting for https://github.com/pingcap/tidb/pull/21270 to fix the leak test

**Pull request merged**
