### PR TITLE
doc: dep cleanup

### PR DESCRIPTION
**Pull request by Darren**
The pr just fixes some minor oversights in dep switch  #5558

1. mention about dep usage in CONTRIBUTING.md
2. remove broken symbolic files in vendor

### CODE REVIEW

**Comment by winkyao** [comment]
@zhexuany PTAL

**Comment by zhexuany** [comment]
LGTM 
@coocood PTAL

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@Darren Thanks!

**Pull request merged**
