### PR TITLE
tidb-server:Fix misspell

### PR DESCRIPTION
**Pull request by xiekeyi98**
### What problem does this PR solve? 

Fix misspell.
"seperated" is a misspelling of "separated" (misspell)

### What is changed and how it works?

Just change only a word.

### CODE REVIEW

**Comment by xiekeyi98** [comment]
@dcalvin Hi, I am not very sure this is a misspell(Maybe it’s just the difference between American English and British English).
I was wondering if you could help me confim it ?

**Comment by dcalvin** [comment]
> @dcalvin Hi, I am not very sure this is a misspell(Maybe it’s just the difference between American English and British English).
> I was wondering if you could help me confim it ?

The correction is right - it was a mis-spell earlier.

**Comment by zimulala** [comment]
Please cherry-pick this PR to v2.1

**Comment by xiekeyi98** [comment]
v2.1 has no effect in this PR.
https://github.com/pingcap/tidb/blob/release-2.1/tidb-server/main.go

**Comment by zimulala** [comment]
@xiekeyi98

**Comment by zimulala** [comment]
Got it.

**Pull request merged**
