### PR TITLE
br: fix DATA RACE in the TestRunServer

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

fix DATA RACE in the TestRunServer

```
WARNING: DATA RACE
Read at 0x00c0005d9090 by goroutine 76:
  github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).handlePostTask()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning.go:467 +0x19c
  github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).handleTask()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning.go:403 +0x59c
  github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).handleTask-fm()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning.go:384 +0x68
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  net/http.StripPrefix.func1()
      /usr/local/go/src/net/http/server.go:2112 +0x535
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  net/http.(*ServeMux).ServeHTTP()
      /usr/local/go/src/net/http/server.go:2448 +0xaf
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2887 +0xca
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1952 +0x87d

Previous write at 0x00c0005d9090 by goroutine 73:
  github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).RunServer()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning.go:205 +0x1e5
  github.com/pingcap/tidb/br/pkg/lightning.TestRunServer.func1()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning_server_serial_test.go:86 +0x4b

Goroutine 76 (running) created at:
  net/http.(*Server).Serve()
      /usr/local/go/src/net/http/server.go:3013 +0x644
  github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).goServe.func2()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning.go:179 +0x8d

Goroutine 73 (running) created at:
  github.com/pingcap/tidb/br/pkg/lightning.TestRunServer()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning_server_serial_test.go:85 +0x68b
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202
==================
==================
WARNING: DATA RACE
Read at 0x00c0001423c0 by goroutine 76:
  github.com/pingcap/tidb/br/pkg/lightning/config.(*List).Push()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/config/configlist.go:51 +0xcc
  github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).handlePostTask()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning.go:499 +0x5fc
  github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).handleTask()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning.go:403 +0x59c
  github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).handleTask-fm()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning.go:384 +0x68
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  net/http.StripPrefix.func1()
      /usr/local/go/src/net/http/server.go:2112 +0x535
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  net/http.(*ServeMux).ServeHTTP()
      /usr/local/go/src/net/http/server.go:2448 +0xaf
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2887 +0xca
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1952 +0x87d
  net/http.(*ServeMux).ServeHTTP()
      /usr/local/go/src/net/http/server.go:2448 +0xaf
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2887 +0xca
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1952 +0x87d

Previous write at 0x00c0001423c0 by goroutine 73:
  github.com/pingcap/tidb/br/pkg/lightning/config.NewConfigList()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/config/configlist.go:41 +0x144
  github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).RunServer()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning.go:205 +0x1c7
  github.com/pingcap/tidb/br/pkg/lightning.TestRunServer.func1()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning_server_serial_test.go:86 +0x4b

Goroutine 76 (running) created at:
  net/http.(*Server).Serve()
      /usr/local/go/src/net/http/server.go:3013 +0x644
  github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).goServe.func2()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning.go:179 +0x8d

Goroutine 73 (running) created at:
  github.com/pingcap/tidb/br/pkg/lightning.TestRunServer()
      /home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning_server_serial_test.go:85 +0x68b
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202
```

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
@3pointer @amyangfei @overvenus @fengou1 PTAL

**Review by overvenus — APPROVED** [review]

**Review by kennytm — APPROVED** [review]

**Comment by kennytm** [comment]
why are the actions still "skipped" 😅

**Comment by 3pointer** [comment]
> why are the actions still "skipped" 😅

maybe '/merge' triggers push event not include label event.🤔

**Pull request merged**
