### PR TITLE
sessionctx: Fix tidb_gc_scan_lock_mode sysvar doesn't show correct default value on new clusters

### LINKED ISSUE #25100: in v5.0.2, tidb_gc_scan_lock_mode default value is different in  scratch installed server and upgrade server
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in scratch install server, the default value for tidb_gc_scan_lock_mode is PHYSICAL
but in the upgraded server(don't change this param before upgrade), the default value is LEGACY

MySQL [(none)]> 

### 3. What did you see instead (Required)
MySQL [(none)]> show variables like '%tidb_gc_scan_lock_mode%'
    -> ;
+------------------------+----------+
| Variable_name          | Value    |
+------------------------+----------+
| tidb_gc_scan_lock_mode | PHYSICAL |
+------------------------+----------+
1 row in set (0.38 sec)

[tidb@centos76_vm 501]$ diff 501_systemvar.txt 502_systemvar.txt 
548c548
< tidb_gc_scan_lock_mode	PHYSICAL
---
> tidb_gc_scan_lock_mode	LEGACY
650c650

### 4. What is your TiDB version? (Required)

| Release Version: v5.0.2
Edition: Community
Git Commit Hash: f610f8bd01b09790f9915fd174bd191b8148f26e
Git Branch: heads/refs/tags/v5.0.2
UTC Build Time: 2021-06-02 02:00:45
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What problem does this PR solve?

Issue Number: close #25100 

Problem Summary: When a new cluster is deployed and it has never run GC, the `tikv_gc_scan_lock_mode` doesn't exist. In this case, `select @@global.tidb_gc_scan_lock_mode` will return the default value defined in sysvar.go. However, it's inconsistent with the actual default config, so it returns "PHYSICAL" while the actual mode is "LEGACY".

### What is changed and how it works?

What's Changed: Changed the default value of  sysvar `global.tidb_gc_scan_lock_mode` to "LEGACY".

### Related changes

- Need to cherry-pick to the release branch
  - release-5.0

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
  * Deploy the cluster by tiup playground and run "select @@global.tidb_gc_scan_lock_mode" immediately, an it returns "LEGACY".

Side effects

- None

### Release note 

- Fix a bug that a new cluster's "tidb_gc_scan_lock_mode" global variable shows "PHYSICAL" instead of the actual default mode "LEGACY".

### CODE REVIEW

**Review by youjiali1995 — APPROVED** [review]

**Comment by bb7133** [comment]
So the point is, we changed the default value back to 'legacy'(https://github.com/pingcap/docs/pull/5136) so the sys vars should be updated accordingly, right?

**Comment by bb7133** [comment]
lgtm and cc @morgo

**Review by bb7133 — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]
LGTM

**Comment by MyonKeminta** [comment]
> So the point is, we changed the default value back to 'legacy'([pingcap/docs#5136](https://github.com/pingcap/docs/pull/5136)) so the sys vars should be updated accordingly, right?

Currently, yes.

**Pull request merged**
