### PR TITLE
planner: remove useless string.ToLower in the Explain

### LINKED ISSUE #53896: remove useless strings.ToLower in the (*Explain).RenderResult
## Enhancement

remove useless strings.ToLower in the (*Explain).RenderResult. although it is very small. it still can be found in the pprof.

image

https://flamegraph.com/share/ce8f8cd2-2654-11ef-aba3-6a3d1814cbe4

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #53896

Problem Summary:

### What changed and how does it work?

remove useless strings.ToLower in the (*Explain).RenderResult. although it is very small. it still can be found in the pprof.

image

https://flamegraph.com/share/ce8f8cd2-2654-11ef-aba3-6a3d1814cbe4

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by AilinKid — APPROVED** [review]

**Review by time-and-fate — COMMENTED** [review]
Looks like `buildExplainFor` also needs to be updated?

**Comment by hawkingrei** [comment]
> Looks like `buildExplainFor` also needs to be updated?

Thanks, I have updated it.

**Review by time-and-fate — APPROVED** [review]

**Pull request merged**
