### PR TITLE
*: don't allocate SessionIndexUsageCollector when indexUsageLease equals 0 (#23861)

### LINKED ISSUE #23856: IndexUsageCollector will consume memory much and mucher when its closed.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Relase & New the session quickly.

### 2. What did you expect to see? (Required)

The memory usage is smooth.

### 3. What did you see instead (Required)

Memory goes higher, and the `IndexUsageCollector` consumes a lot.

Lark20210406-141650

### 4. What is your TiDB version? (Required)

current master.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23861 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23883
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23883:release-5.0-6cff35892c2c
```

---

### What problem does this PR solve?

Issue Number: close #23856 

Problem Summary:

### What is changed and how it works?

When `index-usage-sync-lease` is 0, we don't dump index usage information to KV, but we also will allocate `SessionIndexUsageCollector`. The bad thing is that we only recycle unneeded `SessionIndexUsageCollector` when we dump index usage information. That means we have no GC when `index-usage-sync-lease`. This causes unexpected memory usage.

Proposal: [xxx](url) 

What's Changed:

We modified the behavior.
Before allocate `SessionIndexUsageCollector`, we must confirm that `index-usage-sync-lease` is not 0.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- don't allocate SessionIndexUsageCollector when indexUsageLease equals 0

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by coocood — APPROVED** [review]

**Comment by coocood** [comment]
need update unit test

**Pull request merged**
