### PR TITLE
server: Improve failure message for unix socket issues

### LINKED ISSUE #30663: Different users can't start tidb because of the permission issue of sock file
## Bug Report

On ubuntu 18.04 , I found example tidb cluster cannot work well

### 1. Minimal reproduce step (Required)
1. install tiup ,according to [guide](https://docs.pingcap.com/tidb/stable/quick-start-with-tidb#Linux)，create topo.yaml and edit ip to 127.0.0.1
2. run `tiup cluster deploy xxx 5.3.0 ./topo.yaml --user root -p` 
3.  run `tiup cluster start xxx ` 

### 2. What did you expect to see? (Required)
 After running  ` tiup cluster display xxx ` , all nodes' status should be up
### 3. What did you see instead (Required)
But tidb's status is always down

### 4. What is your TiDB version? (Required)
5.3.0

### 5. appendix
1. system info： ` Linux version 4.15.0-96-generic (buildd@lgw01-amd64-004) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 `
2. ufw  firewall has been stopped and disabled

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #30663 

Problem Summary: Instead of a warning and a failure this now only gives a failure with a better error.

```
[2022/01/12 17:25:04.409 +01:00] [FATAL] [main.go:665] ["failed to create the server"] [error="failed to cleanup stale Unix socket file /tmp/tidb-4000.sock: dial unix /tmp/tidb-4000.sock: connect: permission denied"] [stack="main.createServer\n\t/home/dvaneeden/dev/pingcap/tidb/tidb-server/main.go:665\nmain.main\n\t/home/dvaneeden/dev/pingcap/tidb/tidb-server/main.go:203\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:225"] [stack="main.createServer\n\t/home/dvaneeden/dev/pingcap/tidb/tidb-server/main.go:665\nmain.main\n\t/home/dvaneeden/dev/pingcap/tidb/tidb-server/main.go:203\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:225"]
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by morgo — APPROVED** [review]
LGTM. This is now the last line in my log file, and it's correctly a `FATAL` message:
```
[2022/01/12 10:33:02.628 -07:00] [INFO] [db.go:625] ["Waiting for closer"]
[2022/01/12 10:33:02.628 -07:00] [FATAL] [main.go:665] ["failed to create the server"] [error="the specified socket file /tmp/tidb-4000.sock is a -rw-r--r-- instead of a socket file"] [stack="main.createServer\n\t/home/morgo/go/src/github.com/morgo/tidb/tidb-server/main.go:665\nmain.main\n\t/home/morgo/go/src/github.com/morgo/tidb/tidb-server/main.go:203\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"] [stack="main.createServer\n\t/home/morgo/go/src/github.com/morgo/tidb/tidb-server/main.go:665\nmain.main\n\t/home/morgo/go/src/github.com/morgo/tidb/tidb-server/main.go:203\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"]
```

**Comment by zimulala** [comment]
/run-mysql-test tidb-test=pr/1497
Sorry, I use it for mysql-test

**Comment by dveeden** [comment]
> LGTM. This is now the last line in my log file, and it's correctly a `FATAL` message:
> 
> ```
> [2022/01/12 10:33:02.628 -07:00] [INFO] [db.go:625] ["Waiting for closer"]
> [2022/01/12 10:33:02.628 -07:00] [FATAL] [main.go:665] ["failed to create the server"] [error="the specified socket file /tmp/tidb-4000.sock is a -rw-r--r-- instead of a socket file"] [stack="main.createServer\n\t/home/morgo/go/src/github.com/morgo/tidb/tidb-server/main.go:665\nmain.main\n\t/home/morgo/go/src/github.com/morgo/tidb/tidb-server/main.go:203\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"] [stack="main.createServer\n\t/home/morgo/go/src/github.com/morgo/tidb/tidb-server/main.go:665\nmain.main\n\t/home/morgo/go/src/github.com/morgo/tidb/tidb-server/main.go:203\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"]
> ```

Note that this the error message for when `/tmp/tidb-4000.sock` is not a socket file. The error for a stale socket file looks slightly different.

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
