### PR TITLE
*: hide txn scope setting

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Problem Summary: It is not a release feature, should be hidden.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Review by Yisaer — COMMENTED** [review]
Add a unit test to ensure it?

**Review by JmPotato — APPROVED** [review]

**Comment by xhebox** [comment]
> Add a unit test to ensure it?

I don't think it is needed. There is no unit test for `show variables` actually. But I add a comment for it.

**Review by Yisaer — APPROVED** [review]

**Pull request merged**
