### PR TITLE
*: Update the schema lease to 10s

### PR DESCRIPTION
**Pull request by zimulala**

### CODE REVIEW

**Comment by shenli** [comment]
LGTM
@coocood PTAL

**Comment by coocood** [comment]
FAIL: gc_worker_test.go:63: testGCWorkerSuite.TestPrepareGC

gc_worker_test.go:89:
    c.Assert(err, IsNil)
... value *errors.Err = &errors.Err{message:"", cause:(*terror.Error)(0xc42024ea00), previous:(*errors.Err)(0xc49f09c5a0), file:"github.com/pingcap/tidb/store/tikv/_test/_obj_test/gc_worker.go", line:245} ("[domain:1]Information schema is out of date.")

**Comment by disksing** [comment]
Maybe related to https://github.com/pingcap/tidb/pull/2800?

**Comment by zimulala** [comment]
https://github.com/pingcap/tidb/pull/2800/files#diff-383483267e198cd997e4bd7c70028d12R166
This line can't make sure the Bootstrapped function is finished，so the domain may not be closed yet.
GCWorker may use Bootstrapped Domain to create a session, the domain will close after finishing the bootstrap operation.

**Pull request closed without merging**
