### PR TITLE
lightning_web: update web package dependency

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve?

Problem Summary:
normally update web package for lightning web.

### What is changed and how it works?
run `npm audit fix` and `make data_parsers`
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
run `npm install && npm run build`
image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by buchuitoudegou — APPROVED** [review]
Not that familiar with this part of stuff. Plz let @gozssky take a look.

**Review by D3Hunter — APPROVED** [review]

**Pull request merged**
