### PR TITLE
session: read local dc replicas automatically for stale read (#25525)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #25525 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/25567
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/25567:release-5.1-799591a06fad
```

---

### What is changed and how it works?

In previous, we should use `txn_scope` to enable read local dc replicas for stale read which may expose the local transaction feature while it is not GA yet.

This request also updated tikcClient, see https://github.com/tikv/client-go/pull/89

What's Changed:

Read local dc replicas automatically for stale read by detecting the `zone` label configuration for the tidb-server.

Also the `select as of timestamp` statement is not supported local stale read, this request make it supported.

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Review by nolouch — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by youjiali1995** [comment]
@Yisaer @nolouch It imported `client-go/v2` in this version which is not expected.

**Comment by nolouch** [comment]
@Yisaer , We may need to remove it.

**Pull request merged**
