### PR TITLE
config: make the test `TestPDConfHandler` stable

### LINKED ISSUE #15330: The test `TestPDConfHandler` is unstable
config_handler_test.go:testConfigSuite.TestPDConfHandler

## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
[2020-03-12T07:37:32.939Z] FAIL: config_handler_test.go:78: testConfigSuite.TestPDConfHandler
[2020-03-12T07:37:32.939Z] 
[2020-03-12T07:37:32.939Z] config_handler_test.go:136:
[2020-03-12T07:37:32.939Z]     c.Assert(ch.GetConfig().Performance.MaxMemory, Equals, uint64(123))
[2020-03-12T07:37:32.939Z] ... obtained uint64 = 0xe9
[2020-03-12T07:37:32.939Z] ... expected uint64 = 0x7b
```

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #15330 

Problem Summary: make the test `TestPDConfHandler` stable

### What is changed and how it works?
The root cause is that the config manager updates the global config pointer after finishing reload:
```
    ...
    ch.reloadFunc(oldConf, mergedConf)
    ch.curConf.Store(mergedConf)
    ...
```
But in `TestPDConfHandler`, we will check the global config immediately after reloading in another goroutine, and at that time, the update operation `Store(conf)` may not be processed.

```
reloadFunc = fund() {
    ...
    reloadWg.Done()
}
NewConfManager(reloadFunc)
...
reloadWg.Wait()
Check the config ...
```

|  time   | conf manager goroutine  | test goroutine |
|  ----  | ----  | ---- |
| 1  | reload | |
| 2  |  | check << fail |
| 3  | store | |

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by qw4990** [comment]
PTAL @XuHuaiyu @SunRunAway

**Comment by SunRunAway** [comment]
I think `ch.curConf.Store(mergedConf)` should be part of `reloadFunc`.

**Comment by qw4990** [comment]
> I think `ch.curConf.Store(mergedConf)` should be part of `reloadFunc`.

It's weird to do that since the current config is an **internal** object maintained by `ConfHandler` while the `reloadFunc` is a callback-function created by users.

**Comment by SunRunAway** [comment]
But this PR makes `TestPDConfHandler` meaningless, could you find a way to check the eventual correctness of reloading result?

**Comment by qw4990** [comment]
> But this PR makes `TestPDConfHandler` meaningless, could you find a way to check the eventual correctness of reloading result?

Yes, we can't check the correctness of the eventual result, but there are some other cases we can check in this test, for example, the correctness of reloading (https://github.com/pingcap/tidb/pull/15604/files#diff-f83766918bb8ed6ab335eec0cd1bb404L127).

**Comment by qw4990** [comment]
> > But this PR makes `TestPDConfHandler` meaningless, could you find a way to check the eventual correctness of reloading result?
> 
> Yes, we can't check the correctness of the eventual result, but there are some other cases we can check in this test, for example, the correctness of reloading (https://github.com/pingcap/tidb/pull/15604/files#diff-f83766918bb8ed6ab335eec0cd1bb404L127).

Or change it to:
```
ok := false;
for I := 0; I < 3; i++ {
    if ch.GetConfig().Performance.MaxMemory == 123 { ok = true; break;}
    sleep(1)
}
c.Assert(ok)
```
It's tricky and ugly but more stable than now... @SunRunAway

**Comment by SunRunAway** [comment]
> > > But this PR makes `TestPDConfHandler` meaningless, could you find a way to check the eventual correctness of reloading result?
> > 
> > 
> > Yes, we can't check the correctness of the eventual result, but there are some other cases we can check in this test, for example, the correctness of reloading (https://github.com/pingcap/tidb/pull/15604/files#diff-f83766918bb8ed6ab335eec0cd1bb404L127).
> 
> Or change it to:
> 
> ```
> ok := false;
> for I := 0; I < 3; i++ {
>     if ch.GetConfig().Performance.MaxMemory == 123 { ok = true; break;}
>     sleep(1)
> }
> c.Assert(ok)
> ```
> 
> It's tricky and ugly but more stable than now... @SunRunAway

Could we wait for another run of `reloadFunc`?

**Comment by qw4990** [comment]
@SunRunAway All checks passed, please help me to approve this PR.

**Pull request merged**
