### PR TITLE
store/copr: support retry for mpp query (#26462)

### PR DESCRIPTION
**Pull request by hanfei1991**
### What problem does this PR solve?

cherry-pick #26462 to release-5.0

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- store/copr: support retry for mpp query

### CODE REVIEW

**Review by lysu — APPROVED** [review]

**Review by fzhedu — APPROVED** [review]
/LGTM

**Pull request merged**
