### PR TITLE
log: support reloading tidb-query-max-log-len after modified

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve? 
improve the usability for the `tidb-query-max-log-len`

### What is changed and how it works?
change the default value of `tidb-query-max-log-len`from 2048 to 4096, and support reloading `tidb-query-max-log-len` after modified in the config file. 

### Check List 

Tests 

- Manual test

step 1: select the current value: `select @@tidb_query_log_max_len;`

step 2: change the value of `tidb-query-max-log-len` in the config file

step 3: reload the config `curl -X GET  http://127.0.0.1:10080/reload-config`

step 4: re-select the value: `select @@tidb_query_log_max_len;`

Code changes

 - Update global variables

Release note

 - [function] Change the default value of `tidb-query-max-log-len`from 2048 to 4096, and support reloading `tidb-query-max-log-len` after modified in the config file.

### CODE REVIEW

**Comment by zz-jason** [comment]
@fzhedu Thanks for your contribution! Please follow the [Commit Message and Pull Request Style](https://github.com/pingcap/community/blob/master/commit-message-pr-style.md) guide to reformat the PR title. BTW, you can use the keywords described in the [Closing issues using keywords](https://help.github.com/en/articles/closing-issues-using-keywords) guide to close the related issue when this PR is merged.

**Comment by zz-jason** [comment]
@fzhedu please remove all the irrelevant changes.

**Comment by SunRunAway** [comment]
Should we add it into the release note?

**Comment by fzhedu** [comment]
> Should we add it into the release note?

@zz-jason ?

**Pull request merged**
