### PR TITLE
executor: add some test cases about partition-table dynamic mode with view

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: related to #24150 

Problem Summary: executor: add some test cases about partition-table dynamic mode with view

### What is changed and how it works?

No logical change, just add some test cases about partition-table dynamic mode with view

### Check List 

Tests 

- Unit test

### Release note 

- executor: add some test cases about partition-table dynamic mode with view

### CODE REVIEW

**Comment by qw4990** [comment]
PTAL @rebelice @time-and-fate

**Review by rebelice — APPROVED** [review]
/lgtm

**Pull request merged**
