### PR TITLE
sessionctx/binloginfo: fix goroutine leak in test

### LINKED ISSUE #31963: Resolve goroutine leak for `sessionctx/binloginfo`

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?

Issue Number: close #31963

### Check List

Tests 
- [x] Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]

**Comment by morgo** [comment]
The tests failed because of `no space left on device` :-)

**Pull request merged**
