### PR TITLE
*: Add more info into TableInfo and fix bug in show create table

### PR DESCRIPTION
**Pull request by shenli**
Fix: https://github.com/pingcap/tidb/issues/1061

@zimulala @coocood

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Comment by shenli** [comment]
@coocood @zimulala PTAL

**Comment by coocood** [comment]
LGTM

**Comment by zimulala** [comment]
LGTM

**Pull request merged**
