### PR TITLE
*: move roadmap to docs.pingcap.com

### PR DESCRIPTION
**Pull request by ran-huang**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/42830

Problem Summary: move roadmap to docs.pingcap.com. 

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by ran-huang** [comment]
@hawkingrei can you help merge this PR? thanks.

**Comment by ran-huang** [comment]
@hawkingrei Could you help merge this PR? Thanks a lot!

**Review by lilin90 — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
