### PR TITLE
*: Auto refresh PD addrs for `PDPlacementManager`, `PDLabelManager`, `TiFlashPDPlacementManager` (#33909)

### LINKED ISSUE #33908: PlacementManager addrs will not update when PD member changes
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Setup tidb cluster
2. change PD members and remove all old members

### 2. What did you expect to see? (Required)

The PlacementManager's PD addresses should be changed

### 3. What did you see instead (Required)

The PlacementManager's PD addresses should not changed

### 4. What is your TiDB version? (Required)

After 5.4

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #33909 to release-6.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/33915
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/33915:release-6.0-14f4888fb3d7
```

---

…`TiFlashPDPlacementManager`

### What problem does this PR solve?

Issue Number: close #33908

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  1. start a tidb cluster with 1 pd 
  2. tiup playground scale-out --pd 2
  3. tiup playground scale-in --pid <first-pd-pid>
  4. Execute DDL: `create placement policy p1 followers=1;create table t1(a int) placement policy p1`
  5. DDL successed
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix bug ddl will not work well when PD member changed
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]

**Comment by xhebox** [comment]
Closed, since it is DMN version.
/close

**Pull request closed without merging**
