### PR TITLE
parser: update doc links to tidb repo

### PR DESCRIPTION
**Pull request by gozssky**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/28257

Problem Summary:

The parser has been merged into TiDB repo since v5.3.0. However, some links still point to the parser repo. I think we should update these links to TiDB repo.

### What is changed and how it works?

Update doc links and remove redundant https://github.com/pingcap/tidb/blob/master/parser/docs/update-parser-for-tidb.md.
Rendered [Readme](https://github.com/gozssky/tidb/blob/link/parser/README.md) and [quickstart.md](https://github.com/gozssky/tidb/blob/link/parser/docs/quickstart.md).

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
Nice work

**Review by Defined2014 — APPROVED** [review]

**Pull request merged**
