### PR TITLE
ddl: migrate test-infra to testify for db_change_test.go

### LINKED ISSUE #28633: migrate test-infra to testify for `ddl/db_change_test.go`

### PR DESCRIPTION
**Pull request by tisonkun**
Issue Number: close #28633 

```release-note
None
```

### CODE REVIEW

**Comment by tisonkun** [comment]
@tiancaiamao can you reproduce test failure of unit-test locally? I don't run into failure locally on the changes, or it may take some time but exceed the timeout settings.

**Comment by tisonkun** [comment]
`TestStateChange` really takes near 2 minutes in my local env so it's possible exceed the timeout of settings. But it's a suite contains multiple subtests and each of them take no more than a few of seconds to finish. I don't know whether the timeout killer kills it incorrectly.

**Review by hawkingrei — APPROVED** [review]

**Review by xiongjiwei — APPROVED** [review]

**Pull request merged**
