### PR TITLE
ddl: prevent returning zero schema version for alter sequence (#36277)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #36277 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/36414
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/36414:release-5.3-1bc13cd18f85
```

---

Signed-off-by: AilinKid <314806019@qq.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/36276

Problem Summary:

### Check List

Tests 

- [] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
ddl: fix alter sequence will generate schemaVer=0 when alter options are the same as the old
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by xhebox** [comment]
https://github.com/pingcap/tidb/pull/36971

**Pull request merged**
