### PR TITLE
expression: Support cast decimal as real push down to TiFlash

### PR DESCRIPTION
**Pull request by leiysky**
### What problem does this PR solve?
Related to https://github.com/pingcap/tics/issues/1990
Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
Should we add some test cases?

**Comment by leiysky** [comment]
> Should we add some test cases?

Well, this PR is obsolete now, I think we can just close it...

**Pull request closed without merging**
