### PR TITLE
planner: avoid change the type of the input of sum/avg

### LINKED ISSUE #36371: The planner should not change the type of the input for sum/avg
## Enhancement
In [`WrapCastForAggArgs`](https://github.com/pingcap/tidb/blob/6256c347a705410a8a1b7267c021477db71e9252/expression/aggregation/base_func.go#L439), it changes the type of input for sum/avg to the return type, but it makes no sense to do so, we should refine the code to avoid this.

### PR DESCRIPTION
**Pull request by windtalker**
Signed-off-by: xufei <xufeixw@mail.ustc.edu.cn>

### What problem does this PR solve?

Issue Number: close #36371

Problem Summary:

### What is changed and how it works?

In #7860, it saved the return type of `sum/avg` to its input argument, this is actually a workaround as the review comments shows:

Screen Shot 2022-07-20 at 5 45 37 PM

The only reason to do so is that `baseAvgDecimal` does not have the return type, however, after #30010, `baseAvgDecimal` do have the return type information, so we can use the return type information directly, and it makes no sense to save the return type in the input argument anymore. 

This pr remove the related codes. 
### Check List
Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by XuHuaiyu — APPROVED** [review]

**Comment by windtalker** [comment]
Also need to update the test reference in `tidb-test` repo: https://github.com/pingcap/tidb-test/pull/1895

**Review by wshwsh12 — APPROVED** [review]

**Pull request merged**
