### PR TITLE
cmd: add tests for CTE

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Problem Summary:
Add tests for CTE
### What is changed and how it works?

This PR is based on https://github.com/pingcap/tidb/pull/24809 now
### Check List 

Tests 

- Unit test

Side effects

### Release note 

- No release note

### CODE REVIEW

**Comment by tisonkun** [comment]
The review link could be `https://github.com/pingcap/tidb/pull/24907/commits/8c574564456919d45ddac53a72958f579b544642` and comment shown on PR, not in the dev branch.

**Comment by bb7133** [comment]
Is this PR ready to merge?

**Comment by tisonkun** [comment]
@bb7133 this pr is based on https://github.com/pingcap/tidb/pull/24809 . But keep open so that we can review them as a whole.

**Comment by guo-shaoge** [comment]
lgtm

**Review by xiongjiwei — APPROVED** [review]

**Review by guo-shaoge — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Pull request merged**
