### PR TITLE
store: fix region request have no backoff in some retry situation

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

The `dataNotReady` and `dataNotIntialized` error for region request, we retry the request with no backoff, which may let tidb got stuck in that session.

### What is changed and how it works?

Add backoff checking for it.

### Release note 
- No release note`

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by nolouch** [comment]
How do you found and test it?

**Review by xhebox — COMMENTED** [review]
Fix the format please. Rest LGTM.

**Comment by Yisaer** [comment]
> Fix the format please. Rest LGTM.

updated.

**Comment by Yisaer** [comment]
> How do you found and test it?

found during tipocket test

**Review by xhebox — APPROVED** [review]

**Pull request merged**
