### PR TITLE
config: increase the default lease.

### PR DESCRIPTION
**Pull request by coocood**
Reduce the risk of `schema out of date` error.

### CODE REVIEW

**Comment by ngaut** [comment]
The lease is too long, are you solving the issue that does not related with lease？

**Comment by shenli** [comment]
20s or 25s is long enough.

**Comment by zimulala** [comment]
Update it to 45s?

**Comment by coocood** [comment]
@zimulala PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Comment by coocood** [comment]
@ngaut 
The lease 45s is set to be longer than twice of TiKV election timeout.

**Pull request merged**
