### PR TITLE
txn: introduce `kv.SnapshotInterceptor` to intercept txn read operations

### LINKED ISSUE #27917: A simpler implement for snapshot custom retriever
Considering comments in #27854 , we want some simpler implement for custom data retrieving in snapshot. The new implement have several considerations:

- Make a simple code in snapshot to avoid potential bugs.
- If possible, code in snapshot should be abstract enough for future extension.
- We can suppose snapshot data is empty for custom retriever's ranges to reduce design complexity （avioding oneByOneIter）

A preliminary proposal:

Firstly introduce a new interface `txn.SnapshotInterceptor` to snapshot. The definition is:

```
type SnapshotInterceptor interface {
    OnGet(ctx context.Context, snapshot kv.Snapshot, key kv.Key) ([]byte, error)
    OnBatchGet(ctx context.Context, snapshot kv.Snapshot, keys []kv.Key) (map[string][]byte, error)
    OnIter(ctx context.Context, snapshot kv.Snapshot, k []kv.Key, upper []kv.Key) (kv.Iterator, error)
    OnIterReverse(ctx context.Context, snapshot kv.Snapshot, k []kv.Key) (kv.Iterator, error)
}
```

We can set a interceptor to snapshot like this:

```
snapshot.SetOption(kv.SnapshotInterceptor, interceptor)
```

Take `Get` as example，the inner `tikvSnapshot` code is:

```
func (s *tikvSnapshot) Get(ctx context.Context, k kv.Key) ([]byte, error) {
        if s.interceptor != nil {
            return s.interceptor.OnGet(ctx, NewSnapshot(s.KVSnapshot), k)
        }

	data, err := s.KVSnapshot.Get(ctx, k)
	return data, extractKeyErr(err)
}
```

It means that if an interceptor is set,  snapshot will delegate its read to the interceptor passing a `kv.Snapshot` parameter to it. Then the interceptor can do any thing to read the data.

For temporary table case, we can create a interceptor called `TemporaryTableSnapshotInteceptor` and its `OnGet` looks like this:

```
func (i *TemporaryTableSnapshotInteceptor) OnGet(ctx context.Context, snapshot kv.Snapshot, key kv.Key) ([]byte, error) {
    if tblInfo, ok := i.getAccessTableInfoFromKey(key); ok {
        if tblInfo.TempTableType == model.TempTableGlobal {
            return nil, kv.ErrNotExist
        }

        if tblInfo.TempTableType == model.TempTableLocal {
            val, err := i.memBuffer.Get(key)
            if err == nil && len(val) == 0 {
                return nil, kv.ErrNotExist
            }
            return val, err
        }
    }

    // fallback to snapshot read if the key is not a temporary table key
    return snapshot.Get(ctx, key)
}
```

It checks if it is accessing a temporary table's key. If it is, get data from memory otherwise fallback to default snapshot

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #27917

introduce `kv.SnapshotInterceptor` to intercept txn read operations

### What is changed and how it works?

introduce `kv.SnapshotInterceptor` to intercept txn read operations

### Check List 

Tests 

- [x] Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by disksing** [comment]
I don't really like the idea of introducing the concept of `Interceptor`. Can we use a wrap technique to wrap the snapshot so that the original snapshot doesn't have to be changed?

**Comment by lcwangchao** [comment]
> I don't really like the idea of introducing the concept of `Interceptor`. Can we use a wrap technique to wrap the snapshot so that the original snapshot doesn't have to be changed?

Or we can make the interface to this ?

```
type SnapshotDecorator {
    func DecorateSnapshot(snap kv.Snapshot) (kv.Snapshot, error)
}
```

and set the deocorator by:

```
snap.SetOption(kv.SnapDecorator, myDecorator)
```

**Comment by disksing** [comment]
em, now I think the original PR is better. Going to approve it.

**Review by disksing — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Comment by tiancaiamao** [comment]
What we really want is, for the temporary table, it's also confirm to the `snapshot + retriver` transaction semantic.  With this unified abstraction, the caller do not need to write specific logic to handle the temporary table.

There are two ways, one of them is provide a new `Snapshot` implementation which also handle the temporary table data. This is nothing wrong but the original implementation use a complex way to do it.
And in this commit, `SnapshotInterceptor` is introduced, and it's another way.

Which way to choose is an implementation detail (it's better to leave the choices for the author himself), the user just see the `Snapshot` abstraction. This one is simpler now, IMO.

**Pull request merged**
