### PR TITLE
plan: not build dual for AntiSemiJoin when condition is constant false

### PR DESCRIPTION
**Pull request by eurekaka**
cherry-pick https://github.com/pingcap/tidb/pull/8648

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8730)

### CODE REVIEW

**Comment by eurekaka** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by eurekaka** [comment]
@zz-jason @winoros @lamxTyler PTAL

**Comment by lamxTyler** [comment]
Do we need to cherry pick the test?

**Comment by eurekaka** [comment]
@lamxTyler release-2.1 branch does not contain this patch: https://github.com/pingcap/tidb/pull/7842, so the test result is different, hence I dropped it.

**Pull request merged**
