### PR TITLE
store/tikv: retry TSO RPC (#24682)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #24682 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/24733
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/24733:release-5.0-3ec8c8bae798
```

---

Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?

Problem Summary:

Should use `getTimestampWithRetry` instead of `GetTimestamp`.

### What is changed and how it works?

What's Changed:

Replace all `getTimestampWithRetry` by `GetTimestamp`.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

### Release note 

- No release note.

### CODE REVIEW

**Comment by youjiali1995** [comment]
@sticnarf @cfzjywxk PTAL

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
