### PR TITLE
session: reorganize session unit test suite

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Make sesssion unit test run faster by spliting time-costly test suite

### What is changed and how it works?
reorganize `testSessionSuite` and `testSessionSuite2` to 3 test suites so that test case will distribute more evenly thus make unit test run much faster.

Test Result:
before:
```
$ go test -v -vet=off -p 20 -timeout 7m -race github.com/pingcap/tidb/session -check.p true
ok  	github.com/pingcap/tidb/session	108.061s
```
image

after:
```
$ go test -v -vet=off -p 20 -timeout 7m -race github.com/pingcap/tidb/session -check.p true
ok  	github.com/pingcap/tidb/session	61.064s
```
image

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by glorv** [comment]
@tiancaiamao @bb7133 PTAL

**Comment by tiancaiamao** [comment]
LGTM
/run-all-tests

**Comment by glorv** [comment]
@zz-jason @SunRunAway  PTAL

**Pull request merged**
