### PR TITLE
*: avoid the generation of mysql.TypeNewDate

### LINKED ISSUE #5703: union with date cause runtime error
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
(select tp_date from full_data_type_table where tp_date < 0) union (select tp_date from full_data_type_table where tp_date > 0) order by tp_date;
```

2. What did you expect to see?
```
mysql> (select tp_date from full_data_type_table where tp_date < 0) union (select tp_date from full_data_type_table where tp_date > 0) order by tp_date;
+------------+
| tp_date    |
+------------+
| 1970-04-11 |
| 1970-06-19 |
| 1970-06-27 |
| 1970-07-01 |
| 1970-07-02 |
| 1970-08-12 |
| 1970-09-01 |
| 1970-11-19 |
| 1971-01-10 |
| 1971-04-14 |
| 1971-05-27 |
......
```

3. What did you see instead?

```
mysql> (select tp_date from full_data_type_table where tp_date < 0) union (select tp_date from full_data_type_table where tp_date > 0) order by tp_date;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    16898
Current database: tispark_test

ERROR 2013 (HY000): Lost connection to MySQL server during query
```

TiDB log:
```
2018/01/22 18:30:25.775 conn.go:410: [error] lastCmd (select tp_date from full_data_type_table where tp_date < 0) union (select tp_date from full_data_type_table where tp_date > 0) order by tp_date, runtime error: index out of range, goroutine 386301 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc422a50dd0, 0xc421c35e0f)
	/Users/birdstorm/go/src/github.com/pingcap/tidb/server/conn.go:408 +0x10e
panic(0x1d0ee60, 0x28d8070)
	/usr/local/Cellar/go/1.9.1/libexec/src/runtime/panic.go:491 +0x283
github.com/pingcap/tidb/util/chunk.(*Chunk).AppendPartialRow(0xc420d939a0, 0x0, 0xc420d939c0, 0x0)
	/Users/birdstorm/go/src/github.com/pingcap/tidb/util/chunk/chunk.go:183 +0x68c
github.com/pingcap/tidb/util/chunk.(*Chunk).AppendRow(0xc420d939a0, 0xc420d939c0, 0x0)
	/Users/birdstorm/go/src/github.com/pingcap/tidb/util/chunk/chunk.go:169 +0x48
github.com/pingcap/tidb/executor.(*SortExec).NextChunk(0xc422b9cf20, 0x2dae150, 0xc421d0b940, 0xc420d939a0, 0x1, 0x1)
	/Users/birdstorm/go/src/github.com/pingcap/tidb/executor/sort.go:176 +0x5b
github.com/pingcap/tidb/executor.(*recordSet).NextChunk(0xc421d13f80, 0x2dae150, 0xc421d0b940, 0xc420d939a0, 0xc421d13f80, 0xc420d939a0)
	/Users/birdstorm/go/src/github.com/pingcap/tidb/executor/adapter.go:103 +0x56
github.com/pingcap/tidb/server.(*tidbResultSet).NextChunk(0xc422bc04e0, 0x2dae150, 0xc421d0b940, 0xc420d939a0, 0x4, 0x400)
	/Users/birdstorm/go/src/github.com/pingcap/tidb/server/driver_tidb.go:307 +0x51
github.com/pingcap/tidb/server.(*clientConn).writeChunks(0xc422a50dd0, 0x2dae150, 0xc421d0b940, 0x26c9840, 0xc422bc04e0, 0x0, 0xc422bc04e0, 0x1)
	/Users/birdstorm/go/src/github.com/pingcap/tidb/server/conn.go:936 +0x3ef
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc422a50dd0, 0x2dae150, 0xc421d0b940, 0x26c9840, 0xc422bc04e0, 0xc420670000, 0x0, 0x0)
	/Users/birdstorm/go/src/github.com/pingcap/tidb/server/conn.go:861 +0x668
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc422a50dd0, 0x2dae150, 0xc421d0b940, 0xc420d7e501, 0x90, 0x0, 0x0)
	/Users/birdstorm/go/src/github.com/pingcap/tidb/server/conn.go:810 +0x115
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc422a50dd0, 0xc420d7e501, 0x91, 0x91, 0x0, 0x0)
	/Users/birdstorm/go/src/github.com/pingcap/tidb/server/conn.go:592 +0x595
github.com/pingcap/tidb/server.(*clientConn).Run(0xc422a50dd0)
	/Users/birdstorm/go/src/github.com/pingcap/tidb/server/conn.go:452 +0x1b8
github.com/pingcap/tidb/server.(*Server).onConn(0xc420dbe300, 0x26cc480, 0xc4202efc50)
	/Users/birdstorm/go/src/github.com/pingcap/tidb/server/server.go:316 +0x144
created by github.com/pingcap/tidb/server.(*Server).Run
	/Users/birdstorm/go/src/github.com/pingcap/tidb/server/server.go:262 +0x496
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> select tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v1.1.0-alpha-451-gc5c0714cd
Git Commit Hash: c5c0714cdea270e5d0aa41130c21fd447f17de43
Git Branch: master
UTC Build Time: 2018-01-18 05:49:21 |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by XuHuaiyu**
According to https://lists.mysql.com/internals/37677

`MYSQL_TYPE_NEWDATE` is an internal type of MySQL.
MySQL can handle both `MYSQL_TYPE_NEWDATE` and `MYSQL_TYPE_DATE`,
The only difference is that `MYSQL_TYPE_DATE` takes 4 bytes while
`MYSQL_TYPE_NEWDATE` takes 3 bytes to store. 

In TiDB, we only consider mysql.TypeDate,
so we should avoid the generation of mysql.TypeNewDate.

fix #5703 

PTAL @coocood @zz-jason

### CODE REVIEW

**Comment by winoros** [comment]
So can we remove `mysql.TypeNewDate`?

**Comment by coocood** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
I think we'd better it now,
it can be regarded that TiDB takes a different implementation. @winoros

**Pull request merged**
