### PR TITLE
executor: add a benchmark test for union scan reading

### LINKED ISSUE #32433: UnionScan is extremely inefficient on reading
## Enhancement

Scan 8000+ rows take 20ms! 

I first found this issue when testing cached table https://github.com/pingcap/tidb/issues/25293.

Without cache, less than 10ms:

```
mysql> SELECT   `process_code`,   `sweep_contract`,   `can_sweep`,   `operator_no`,   `area_code`,   DATE_FORMAT(`busi_date`, '%Y-%m-%d') FROM   pm_acc_trans_sweep WHERE   `process_code` = 'GDEP0071';
+--------------+----------------+-----------+-------------+-----------+--------------------------------------+
| process_code | sweep_contract | can_sweep | operator_no | area_code | DATE_FORMAT(`busi_date`, '%Y-%m-%d') |
+--------------+----------------+-----------+-------------+-----------+--------------------------------------+
| GDEP0071     | 0009           | 0         | 000000      | 7518      | 2014-05-08                           |
+--------------+----------------+-----------+-------------+-----------+--------------------------------------+
1 row in set (0.00 sec)
```

With cache, it takes 20ms:

```
mysql> SELECT   `process_code`,   `sweep_contract`,   `can_sweep`,   `operator_no`,   `area_code`,   DATE_FORMAT(`busi_date`, '%Y-%m-%d') FROM   pm_acc_trans_sweep WHERE   `process_code` = 'GDEP0071';
+--------------+----------------+-----------+-------------+-----------+--------------------------------------+
| process_code | sweep_contract | can_sweep | operator_no | area_code | DATE_FORMAT(`busi_date`, '%Y-%m-%d') |
+--------------+----------------+-----------+-------------+-----------+--------------------------------------+
| GDEP0071     | 0009           | 0         | 000000      | 7518      | 2014-05-08                           |
+--------------+----------------+-----------+-------------+-----------+--------------------------------------+
1 row in set (0.02 sec)
```

The data rows is 8000:

```
mysql> SELECT  count(*) from pm_acc_trans_sweep;
+----------+
| count(*) |
+----------+
|     8912 |
+----------+
1 row in set (0.00 sec)
```

It's quite counterintuitive that reading data from cache in TiDB slower than get the data from TiKV.
So I dig into it, and find the reason.

UnionScan is extremely inefficient when reading data from membuffer!

```
func BenchmarkUnionScanRead(b *testing.B) {
	store, clean := testkit.CreateMockStore(b)
	defer clean()

	tk := testkit.NewTestKit(b, store)
	tk.MustExec("use test")
	tk.MustExec(`create table t_us (
c1 varchar(10),
c2 varchar(30),
c3 varchar(1),
c4 varchar(12),
c5 varchar(10),
c6 datetime);`)
	tk.MustExec(`begin;`)
	for i:=0; i<8000; i++ {
		tk.MustExec("insert into t_us values ('54321', '1234', '1', '000000', '7518', '2014-05-08')")
	}

	b.ReportAllocs()
	b.ResetTimer()
	for i:=0; i<b.N; i++ {
		tk.MustQuery("select * from t_us where c1 = '12345'").Check(testkit.Rows())
	}
	b.StopTimer()
}
```

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #32433
(not really close it... I haven't figure out how to fix, add the benchmark test first)

Problem Summary:

### What is changed and how it works?

Add a benchmark test and run it daily

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)

go test -run TestXXX -bench BenchmarkUnionScanRead -cpuprofile cpu.out -memprofile mem.out -benchtime 30s

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by Defined2014** [comment]
Maybe ref https://github.com/pingcap/tidb/issues/32433 is better, just keep issue open.

**Review by Defined2014 — APPROVED** [review]

**Comment by tiancaiamao** [comment]
> Maybe ref #32433 is better, just keep issue open.

I can reopen it later~

**Pull request merged**
