### PR TITLE
expression: fix retType of buitin func with JSON

### LINKED ISSUE #32281: The result of `collation(concat(binary, json))` not correct.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t (a binary, b json);
insert into t values (0x61,'{"a":"c"}');
select collation(concat(a, b)) from t;
```
### 2. What did you expect to see? (Required)
```
mysql> select collation(concat(a, b)) from t;
+-------------------------+
| collation(concat(a, b)) |
+-------------------------+
| binary                  |
+-------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> select collation(concat(a, b)) from t;
+-------------------------+
| collation(concat(a, b)) |
+-------------------------+
| utf8mb4_bin             |
+-------------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #32281

Problem Summary: fix retType of buitin func with JSON

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix retType of buitin func with JSON
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @wjhuang2016 @xiongjiwei @tangenta 
PTAL

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by zimulala** [comment]
PTAL @tangenta @xiongjiwei

**Review by xiongjiwei — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
