### PR TITLE
util/filesort: migrate test-infra to testify

### LINKED ISSUE #26178: migrate test-infra to testify for `util/filesort` pkg

### PR DESCRIPTION
**Pull request by tisonkun**
### What problem does this PR solve?

Issue Number: close #26178

based on #26946

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by kevgeo** [comment]
@tisonkun Thank you for taking over this PR. This looks great.

**Review by tangenta — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Pull request merged**
