### PR TITLE
planner: make `var_samp` can be used as a window function

### PR DESCRIPTION
**Pull request by hi-rustin**
<!--

Thank you for contributing to TiDB!

PR Title Format:
1. pkg [, pkg2, pkg3]: what's changed
2. *: what's changed

-->

### What problem does this PR solve?
<!--

Please create an issue first to describe the problem.

There MUST be one line starting with "Issue Number:  " and
linking the relevant issues via the "close" or "ref".

For more info, check https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#referring-to-an-issue.

-->

Issue Number: close https://github.com/pingcap/tidb/issues/52933

Problem Summary:

### What changed and how does it work?

From the MySQL plan:
```sql
mysql> explain analyze select var_samp(c1) over (partition by c1) from t1;
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| EXPLAIN                                                                                                                                                                                                                                                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -> Window aggregate with buffering: var_samp(t1.c1) OVER (PARTITION BY t1.c1 )   (cost=0 rows=1) (actual time=0.139..0.139 rows=0 loops=1)
    -> Sort: t1.c1  (cost=0.35 rows=1) (actual time=0.133..0.133 rows=0 loops=1)
        -> Table scan on t1  (cost=0.35 rows=1) (actual time=0.116..0.116 rows=0 loops=1)
 |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

- Made `var_samp` can be used as a window function.
- Added a test case for https://github.com/pingcap/tidb/issues/52933.

### Check List

Tests <!-- At least one of them must be included. -->

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > <!-- Or your custom  "No need to test" reasons -->

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

<!-- compatibility change, improvement, bugfix, and new feature need a release note -->

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Make `var_samp` can be used as a window function.
使 `var_samp` 可以用作窗口函数。
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
Tested locally:
1. Start the cluster: `tiup playground v8.0.0  --db.binpath /Users/hi-rustin/vsc/tidb/bin/tidb-server`
2. Create the table and run the query:
```sql
mysql> use test;
msqll> create table t1 (c1 int)
mysql> select c1, var_samp(c1) over (partition by c1) from t1;
Empty set (0.00 sec)

mysql> explain select c1, var_samp(c1) over (partition by c1) from t1;
+-------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------+
| id                            | estRows  | task      | access object | operator info                                                                     |
+-------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------+
| Shuffle_11                    | 10000.00 | root      |               | execution info: concurrency:5, data sources:[TableReader_9]                       |
| └─Window_7                    | 10000.00 | root      |               | var_samp(cast(test.t1.c1, double BINARY))->Column#4 over(partition by test.t1.c1) |
|   └─Sort_10                   | 10000.00 | root      |               | test.t1.c1                                                                        |
|     └─ShuffleReceiver_12      | 10000.00 | root      |               |                                                                                   |
|       └─TableReader_9         | 10000.00 | root      |               | data:TableFullScan_8                                                              |
|         └─TableFullScan_8     | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                    |
+-------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------+
6 rows in set (0.00 sec)

mysql> explain select c1, sum(c1) over (partition by c1) from t1;
+-------------------------------+----------+-----------+---------------+-------------------------------------------------------------------------------------+
| id                            | estRows  | task      | access object | operator info                                                                       |
+-------------------------------+----------+-----------+---------------+-------------------------------------------------------------------------------------+
| Shuffle_11                    | 10000.00 | root      |               | execution info: concurrency:5, data sources:[TableReader_9]                         |
| └─Window_7                    | 10000.00 | root      |               | sum(cast(test.t1.c1, decimal(10,0) BINARY))->Column#4 over(partition by test.t1.c1) |
|   └─Sort_10                   | 10000.00 | root      |               | test.t1.c1                                                                          |
|     └─ShuffleReceiver_12      | 10000.00 | root      |               |                                                                                     |
|       └─TableReader_9         | 10000.00 | root      |               | data:TableFullScan_8                                                                |
|         └─TableFullScan_8     | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                      |
+-------------------------------+----------+-----------+---------------+-------------------------------------------------------------------------------------+
6 rows in set (0.01 sec)
```

**Review by hi-rustin — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by qw4990 — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Pull request merged**
