### PR TITLE
*: Minor changes for better clarity in roadmap file

### LINKED ISSUE #42231: Update the time frame wording for roadmap
## Enhancement
minor change for better clarity

### PR DESCRIPTION
**Pull request by lucifinil**
### What problem does this PR solve?

Issue Number: close #42231

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lucifinil** [comment]
@ran-huang PTAL. Thanks!

**Review by ran-huang — APPROVED** [review]
LGTM

**Comment by lucifinil** [comment]
/assign @bb7133 @dveeden
kindly help review and help merge. thanks!

**Review by dveeden — APPROVED** [review]

**Review by v01dstar — APPROVED** [review]
LGTM

**Review by mjonss — APPROVED** [review]

**Pull request merged**
