### PR TITLE
planner: choose left side as build in semi and anti semi join

### LINKED ISSUE #58325: Choose left side as build in semi and anti semi join in optimizer
## Enhancement

Currently, hash join can only choose right side as build table in semi and anti-semi join. For example, for the sql `select * from t1 where exists (select 1 from t2 where t1.col0 = t2.col0) order by t1.col0, t1.col1;`, if t2 has 1000w rows, t1 has 1000 rows. It's obvious that choose t1 as build table is better, but we don't support to build table for left side in previous hash join implementation. After [#57658](https://github.com/pingcap/tidb/pull/57658) and [#57971](https://github.com/pingcap/tidb/pull/57971) merge, hash join v2 could support left side as build table.  So we need to make optimizer enable to choose left side as build table when necessary.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #58325

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
choose left side as build in semi and anti semi join

支持可以选择 left side，来构建 semi join 和 anti semi join
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Review by elsa0520 — COMMENTED** [review]
Please check the doc if any update

**Pull request merged**
