### PR TITLE
br: disable the batch ddl by default

### LINKED ISSUE #31835: br, ddl: BR restore failure - incremental restore a backup contains primary key and unique key
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. on nightly build, create a cluster
2. execute sql
`drop schema if exists db;`
`create schema db;`
`create table db.t1 (a int primary key nonclustered, b int unique);`
`insert into db.t1 values (42, 42);`

3. take backup 1
`backup --pd $PD_ADDR backup db --db "db" -s "local:///temp/db"`
4. execute sql 
`create table db.t1inc (a int primary key nonclustered, b int unique);`
`insert into db.t1inc values (42, 42);`
`alter table db.t1inc drop primary key;`
`drop table db.t1inc;`
`create table db.t1inc like db.t1;`
`insert into db.t1inc values (42, 42);`
5. take backup 2
`backup --pd $PD_ADDR backup db --db "db" -s "local:///temp/dbinc"`
6. execute sql
`drop schema db;`
7. restore backup 1
`br --pd $PD_ADDR restore db --db "db" -s "local:///temp/db`
8. restore backup 2
`br --pd $PD_ADDR restore db --db "$DB" -s "local:///temp/dbinc`
### 2. What did you expect to see? (Required)
the second restore of step 8 shall succeed.
### 3. What did you see instead (Required)
the second restore of step 8 is failure, key failure log:
`[2022-01-17T10:00:42.962Z] [2022/01/17 18:00:42.868 +08:00] [DEBUG] [txn.go:479] ["[kv] rollback txn"] [txnStartTS=430548881992581126]
[2022-01-17T10:00:42.962Z] [2022/01/17 18:00:42.868 +08:00] [WARN] [glue.go:167] ["batch create table from tidb failure"] [error="[meta:1146]table doesn't exist"] [errorVerbose="[meta:1146]table doesn't exist\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:155\ngithub.com/pingcap/tidb/meta.(*Meta).checkTableExists\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/meta/meta.go:272\ngithub.com/pingcap/tidb/meta.(*autoIDAccessor).Inc\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/meta/meta_autoid.go:63\ngithub.com/pingcap/tidb/meta/autoid.(*allocator).rebase4Signed.func2\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/meta/autoid/autoid.go:358\ngithub.com/pingcap/tidb/kv.RunInNewTxn\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/kv/txn.go:49\ngithub.com/pingcap/tidb/meta/autoid.(*allocator).rebase4Signed\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/meta/autoid/autoid.go:333\ngithub.com/pingcap/tidb/meta/autoid.(*allocator).Rebase\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/meta/autoid/autoid.go:419\ngithub.com/pingcap/tidb/ddl.(*ddl).handleAutoIncID\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/ddl/ddl_api.go:2519\ngithub.com/pingcap/tidb/ddl.(*ddl).createTableWithInfoPost\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/ddl/ddl_api.go:2117\ngithub.com/pingcap/tidb/ddl.(*ddl).BatchCreateTableWithInfo\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/ddl/ddl_api.go:2251\ngithub.com/pingcap/tidb/br/pkg/gluetidb.(*tidbSession).CreateTables\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/gluetidb/glue.go:162\ngithub.com/pingcap/tidb/br/pkg/restore.(*DB).CreateTables\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/restore/db.go:192\ngithub.com/pingcap/tidb/br/pkg/restore.(*Client).createTables\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/restore/client.go:427\ngithub.com/pingcap/tidb/br/pkg/restore.(*Client).createTablesInWorkerPool.func1\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/restore/client.go:618\ngithub.com/pingcap/tidb/br/pkg/utils.(*WorkerPool).ApplyWithIDInErrorGroup.func1\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/br/pkg/utils/worker.go:82\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"]`
### 4. What is your TiDB version? (Required)
Only nightly build / master branch

nightly build

it is possible to be introduced by batch create table (batch ddl)

### PR DESCRIPTION
**Pull request by fengou1**
### What problem does this PR solve?
When we run incremental restore with pk or uk, It looks there is an issue when we enabled the batch ddl.

Issue Number: close #31835

Problem Summary:
When increment restore pk or uk, we rebase the auto ID and then we found table does not existed while the table we just created.
### What is changed and how it works?
just disabled the batch ddl by default until we root cause the issue.
### Check List

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by joccau — APPROVED** [review]
LGTM.
It is a template plan.

**Review by YuJuncen — APPROVED** [review]

**Pull request merged**
