### PR TITLE
*: introduce new API ParseWithParams (#22499)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #22499 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/22548
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/22548:release-4.0-ae0057da714e
```

---

### What problem does this PR solve?

Problem Summary: This PR adds a new API `ParseWithParams` to help process unsafe arguments than just `fmt.Sprintf`. Also a helper API `ExecuteInternal` that is using `ParseWithParams` and `ExecuteStmt`.

I did not use `PrepareStmt` since it is not possible to use placeholder like `select * from t where c in ?`. But we do have such [requirement](https://github.com/pingcap/tidb/blob/master/session/session.go#L2484-L2492).

`ExecuteInternal` is redefined to use `ParseWithParams` and always use utf8 charset for safety. But it is still needed to modify cases like `ExecuteInternal(fmt.Sprintf(...))`.

`ExecRestrictedSQL` is too large, thus it is both annoying and duplicated to write a new `RestrictedSQLExecutor` based on `ParseWithParams`. From the git history, this is a very legacy API that is 4 or 5 years old. It should be removed/refactored in further works. So the current plan is, write like `ExecRestrictedSQL(session.EscapeSQL(sql, args...))`. And it will goes to the modified `ExecuteInternal` eventually to use utf8 charset to prevent attacks based on charsets.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Comment by morgo** [comment]
LGTM

**Comment by morgo** [comment]
LGTM

**Review by bb7133 — APPROVED** [review]

**Comment by bb7133** [comment]
LGTM

**Review by AilinKid — APPROVED** [review]
LGTM

**Comment by xhebox** [comment]
> LGTM

Is this branch merge-able now?

**Comment by tiancaiamao** [comment]
> > LGTM
> 
> Is this branch merge-able now?

It depends on whether the 4.0 branch is still frozen

**Pull request merged**
