### PR TITLE
planner: generate correct query block name and offset for update / delete (#21823)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21823 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/21822

Problem Summary:

Baseline capture fails for update containing subquery.

### What is changed and how it works?

What's Changed:
- Don't check `NodeType` when getting offset for a query block name, because the node type is just the outer most node type, e.g, the top node type is update, while the embedded node type is select;
- Enforce the restriction that `selectOffset` for Update / Delete must be 0, and adjust `GenerateQBName`;
- Don't generate join hint with empty table name;

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- Fix baseline capture failure for update containing subquery

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
LGTM

**Comment by qw4990** [comment]
PTAL @Reminiscent @lzmhhh123

**Review by Reminiscent — APPROVED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
