### PR TITLE
excutor: fix the date precision of `builtinCastDurationAsStringSig.vecEvalString` #23314 #23286

### LINKED ISSUE #23314: The result of GROUP_CONCAT(time) is incorrect
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```mysql
create table t1(col1 time(2) NOT NULL);
insert into t1 values("16:40:20.01");
```

### 2. What did you expect to see? (Required)
```mysql
mysql> select GROUP_CONCAT(col1) from t1 group by col1;
+--------------------+
| GROUP_CONCAT(col1) |
+--------------------+
| 16:40:20.01        |
+--------------------+
1 row in set (0.05 sec)

```
### 3. What did you see instead (Required)
```mysql
mysql> select GROUP_CONCAT(col1) from t1 group by col1;
+--------------------+
| GROUP_CONCAT(col1) |
+--------------------+
| 16:40:20           |
+--------------------+
1 row in set (0.05 sec)

```
### 4. What is your TiDB version? (Required)
```mysql
Release Version: v4.0.11
Edition: Community
Git Commit Hash: 058e52ad7c1b477147dcb933b3f1b3b2be31e998
Git Branch: heads/refs/tags/v4.0.11
UTC Build Time: 2021-02-25 04:33:58
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by Howie59**
### What problem does this PR solve?

Issue Number: close #23314 #23286

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- fix date precision

### CODE REVIEW

**Comment by mmyj** [comment]
LGTM

**Comment by mmyj** [comment]
#23286 had been fixed also.

**Comment by Howie59** [comment]
@XuHuaiyu PTAL

**Review by lzmhhh123 — APPROVED** [review]

**Comment by wzru** [comment]
/needs-cherry-pick-4.0

**Pull request merged**
