### PR TITLE
ddl: fix error that pd rules are not deleted when alter TiFlash replica count to 0

### LINKED ISSUE #32190: PD rules are not removed when `alter table set tiflash replica 0`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
ref https://github.com/pingcap/tics/issues/3982

When removing a TiFlash replica, we need to delete its pd rule. Though we can delete a rule by setting count=0 through pd-ctl, we can't do that by Pd's HTTP API. It will cause some rules that will not be gc-ed.

This bug won't affect any previous version.

### PR DESCRIPTION
**Pull request by CalvinNeo**
Signed-off-by: CalvinNeo <calvinneo1995@gmail.com>

### What problem does this PR solve?

Issue Number: close #32190

Problem Summary:
When remove a TiFlash replica, we need to delete its pd rule. Though we can delete a rule by setting `count=0` through pd-ctl, we can't do that by Pd's HTTP API. It will cause some rules not be gc-ed.

This PR will solve this problem by deleting related rules directly.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix error that pd rules are not deleted when alter TiFlash replica count to 0
```

### CODE REVIEW

**Comment by CalvinNeo** [comment]
This bug is critical, but it won't affect any previous version.
/cc @xhebox @lcwangchao

**Review by xhebox — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Pull request merged**
