### PR TITLE
table, executor: set a real enum as the default enum value (#8469)

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve? 
Cherry pick #8469 to release 2.1

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8474)

### CODE REVIEW

**Comment by jackysp** [comment]
PTAL @lysu @crazycs520

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
/run-integration-common-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
