### PR TITLE
*: add a "context.Context" parameter for "NextChunk"

### PR DESCRIPTION
**Pull request by winkyao**
@coocood @zz-jason @XuHuaiyu PTAL

### CODE REVIEW

**Comment by shenli** [comment]
What's the benefit of this PR?

**Comment by coocood** [comment]
LGTM

**Comment by winkyao** [comment]
@shenli executor.Next() has a context param, if we wanna use NextChunk to replace it, we need to use the context in some case.

**Comment by zz-jason** [comment]
@shenli the benefit is open tracing.

**Pull request merged**
