### PR TITLE
Makefile: fix 'errcheck' after github.com/kisielk/errcheck is updated

### PR DESCRIPTION
**Pull request by zz-jason**
Since the branch "master" differs too much to the branch "release-1.0", I rewritten the code in https://github.com/pingcap/tidb/pull/6574 to "release-1.0" manually.

### CODE REVIEW

**Comment by shenli** [comment]
/run-all-tests tidb-test=release-1.0 tikv=release-1.0 tidb-private-test=release-1.0

**Comment by coocood** [comment]
LGTM

**Comment by zz-jason** [comment]
/run-common-test tidb-test=pr/539 tikv=release-1.0 tidb-private-test=release-1.0
/run-integration-common-test tidb-test=pr/539 tikv=release-1.0 tidb-private-test=release-1.0

**Comment by zz-jason** [comment]
@shenli PTAL

**Comment by shenli** [comment]
LGTM

**Pull request merged**
