### PR TITLE
planner/core: migrate cacheable_checker_test.go test infra to testify

### LINKED ISSUE #28387: migrate test-infra to testify for `planner/core/cacheable_checker_test.go`

### PR DESCRIPTION
**Pull request by tarnar114**
### What problem does this PR solve?

Issue Number: close #28387 

Problem Summary: migrate test infra to testify

### What is changed and how it works?

What's Changed: planner/core/cacheable_checker_test.go

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by tarzan114** [comment]
/cc @tisonkun 
hi can you pls review this 
*also for some reason ddl/db_partition_test.go was giving weird issues for check_dev_2 any reason for that

**Comment by tisonkun** [comment]
/cc @xhebox @breeswish 

Could you also take a look at this PR?

**Pull request merged**
