### PR TITLE
ddl: Refine the error message to compatible with MySQL when drop a partition table partition key column

### LINKED ISSUE #38739: Drop partition table's partition-key column error message not compatible with MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

mysql> create table t1 (a tinyint, b char) partition by range (a) ( partition p0 values less than (10) );
mysql> alter table t1 drop column a;

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)


mysql> create table t1 (a tinyint, b char) partition by range (a) ( partition p0 values less than (10) );
Query OK, 0 rows affected (0.04 sec)

mysql> alter table t1 drop column a;
ERROR 3855 (HY000): Column 'a' has a partitioning function dependency and cannot be dropped or renamed.

### 3. What did you see instead (Required)

mysql> create table t1 (a tinyint, b char) partition by range (a) ( partition p0 values less than (10) );
Query OK, 0 rows affected (0.11 sec)

mysql> alter table t1 drop column a;
ERROR 1054 (42S22): Unknown column 'a' in 'expression'

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

mysql> SELECT tidb_version(); 
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                       |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.4.0-alpha-75-g61eed5c-dirty
Edition: Community
Git Commit Hash: 61eed5c362048c69771e9476c54fcb6411381670
Git Branch: newsql
UTC Build Time: 2022-10-29 05:13:10
GoVersion: go1.19.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #38739 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by mjonss — APPROVED** [review]
LGTM

**Comment by mjonss** [comment]
@jiyfhust please run `make check` and update the errors.toml file accordingly

It seems like the CI fails and needs this change:

```diff
diff --git a/errors.toml b/errors.toml
index 0c5f5765d1..5e6b9080da 100644
--- a/errors.toml
+++ b/errors.toml
@@ -1176,6 +1176,11 @@ error = '''
 Column '%s' has an expression index dependency and cannot be dropped or renamed
 '''
 
+["ddl:3885"]
+error = '''
+Column '%s' has a partitioning function dependency and cannot be dropped or renamed
+'''
+
 ["ddl:4135"]
 error = '''
 Sequence '%-.64s.%-.64s' has run out
```

**Review by CbcWestwolf — APPROVED** [review]

**Comment by jiyfhust** [comment]
> @jiyfhust please run `make check` and update the errors.toml file accordingly

Thx @mjonss ，i have fixed it as you adviced.

**Pull request merged**
