### PR TITLE
metrics: add grafana template and display metrics by instance

### LINKED ISSUE #34510: Display metrics by instance
## Enhancement

The current TiDB displays metrics in an aggregated form, in some cases, the latency increases in some specific TiDB nodes, and the aggregated metrics may block the investigation. This issue suggests adding a template in grafana like what TiKV did.

image

### PR DESCRIPTION
**Pull request by you06**
### What problem does this PR solve?

Issue Number: close #34510, #34514

Problem Summary:

Add grafana template and display metrics by instance.

image

### What is changed and how it works?

The metrics stored in Prometheus contain the instance label, when the specific instance is selected, the instance condition will be added to the Prometheus query.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Add grafana template and display metrics by instance
```

### CODE REVIEW

**Review by cfzjywxk — APPROVED** [review]

**Review by ekexium — APPROVED** [review]
The "by-instance" in tidb-summary doesn't work in my M1 mac. Some panels don't have any data (e.g. uptime).
image

But I think it is unrelated to this PR.

**Pull request merged**
