### PR TITLE
ranger: fix the range construction behavior when the column's type is `YEAR` (#23559)

### LINKED ISSUE #23508: “ Unexpected ExprType Float64 and EvalType Int” while using cluster index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE `PK_S_MULTI_42_2` (  `COL1` year(4) NOT NULL,  `COL2` year(4) NOT NULL,  `COL3` year(4) DEFAULT NULL,  PRIMARY KEY (`COL1`,`COL2`) clustered);
select * from PK_S_MULTI_42 where col2 between 2154 and 2154 AND col3 > 2153;
```

### 2. What did you expect to see? (Required)
execute  successfully without error 
### 3. What did you see instead (Required)
```sql
mysql > CREATE TABLE `PK_S_MULTI_42_2` (  `COL1` year(4) NOT NULL,  `COL2` year(4) NOT NULL,  `COL3` year(4) DEFAULT NULL,  PRIMARY KEY (`COL1`,`COL2`) clustered);
Query OK, 0 rows affected
Time: 0.282s
mysql > select * from PK_S_MULTI_42_2 where col2 between 2154 and 2154 AND col3 > 2153;
(1105, 'other error: [components/tidb_query_expr/src/types/expr_builder.rs:357]: Unexpected ExprType Float64 and EvalType Int')

mysql > CREATE TABLE `PK_S_MULTI_42_1` (  `COL1` year(4) NOT NULL,  `COL2` year(4) NOT NULL,  `COL3` year(4) DEFAULT NULL,  PRIMARY KEY (`COL1`,`COL2`) nonclustered);
Query OK, 0 rows affected
Time: 0.305s
mysql > select * from PK_S_MULTI_42_1 where col2 between 2154 and 2154 AND col3 > 2153;
+------+------+------+
| COL1 | COL2 | COL3 |
+------+------+------+
```
### 4. What is your TiDB version? (Required)
master: fd706ab76bd09ac859

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23559 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/24018
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/24018:release-5.0-670b5fbcf5ad
```

---

Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #23508 

Problem Summary:

The type of year should be int, not double.

### What is changed and how it works?

Use ConvertToMysqlYear() to adjust the year constant, and handle some corner cases.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

- Manual test (add detailed scripts or steps below)

Start a tidb cluster.
CREATE TABLE `PK_S_MULTI_42_2` (  `COL1` year(4) NOT NULL,  `COL2` year(4) NOT NULL,  `COL3` year(4) DEFAULT NULL,  PRIMARY KEY (`COL1`,`COL2`) clustered);
mysql> select * from PK_S_MULTI_42_2 where col2 between 2154 and 2154 AND col3 > 2153;
Empty set (0.00 sec)

Side effects

### Release note 

- fix wrong year type

### CODE REVIEW

**Comment by eurekaka** [comment]
@wjhuang2016 please take a look at the failed CI.

**Review by qw4990 — COMMENTED** [review]
Please resolve conflicts @wjhuang2016

**Comment by lysu** [comment]
Please resolve conflicts @wjhuang2016 🤣 ... too many test cases false-fail everyday in 5.0

**Comment by eurekaka** [comment]
Not critical enough to be merged into 5.0.

**Pull request closed without merging**
