### PR TITLE
kv : Remove engine.Snapshot interface.

### PR DESCRIPTION
**Pull request by c4pt0r**
Because we implemented MVCC, we don't need engine.Snapshot to provide isolation
guarantee.

### CODE REVIEW

**Comment by c4pt0r** [comment]
@ngaut 
@siddontang 
PTAL

**Comment by shenli** [comment]
LGTM

**Comment by siddontang** [comment]
Seem boltdb creating iterator will still block write operation. Should we fix it later?

**Comment by c4pt0r** [comment]
I tested it on Linux platform, it's OK. Can you reproduce on your environment?

**Comment by siddontang** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Comment by ngaut** [comment]
@siddontang

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
