### PR TITLE
go.mod: update BR dependency to the latest (#23429)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23429 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23431
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23431:release-5.0-96a0cda96ea0
```

---

### What problem does this PR solve?

Problem Summary: This is a follow-up patch for https://github.com/pingcap/tidb/pull/23270.

### What is changed and how it works?

What's Changed: update BR dependency and remove alter-primary-key completely.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

NA

### Release note 

- The configuration alter-primary-key is deprecated. Use NONCLUSTERED instead.

### CODE REVIEW

**Comment by lysu** [comment]
@tangenta need update version point to https://github.com/pingcap/br/pull/897

**Comment by lysu** [comment]
need cherry-pick https://github.com/pingcap/br/pull/902 first to avoid introduce dirty dependency

**Review by jackysp — APPROVED** [review]
LGTM

**Pull request merged**
