### PR TITLE
Fix issue #612

### PR DESCRIPTION
**Pull request by hhkbp2**
Hi there,

This PR would fix issue #612, it adds setting for PATH in Makefile to avoid manual setup.
For `make` version after 4.0, simply adding GOPATH/bin into PATH would work. But for version before 4.0, `make` fail to use modified PATH to search these commands godep/golex/goyacc/golint, which are installed in GOPATH/bin. So we need to specify these commands with full path.

It passes tests under `make` 4.0(Debian Linux), 3.81, 4.1(Mac OS X).

### CODE REVIEW

**Comment by shenli** [comment]
@hhkbp2 There is an error in ci. 
make: /home/travis/gopath/src/github.com/pingcap/tidb/Godeps/_workspace:/home/travis/gopath/bin/goyacc: Command not found
make: *** [parser] Error 127
See: https://travis-ci.org/pingcap/tidb/builds/92393132

**Comment by hhkbp2** [comment]
@shenli It's fixed. I forgot that GOPATH could contain multiple paths.

**Comment by ngaut** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
@hhkbp2  Thanks very much.
LGTM

**Pull request merged**
