### PR TITLE
Pure TiKV client

### PR DESCRIPTION
**Pull request by youjiali1995**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

Only for review

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

-

### CODE REVIEW

**Comment by sticnarf** [comment]
Now I remove the exported functions that shouldn't be called instead of panicking.

**Comment by ngaut** [comment]
Can we import tikv as a package instead of code?

**Comment by sticnarf** [comment]
> Can we import tikv as a package instead of code?

This branch is a transition state. We provide this branch because the TiKV client in TiDB is not suitable for pure KV users and https://github.com/tikv/client-go is out-of-date and lacks maintenance.

We are making plans to extract the current TiKV client in TiDB to update `tikv/client-go`. Then, we can import that package in TiDB.

**Comment by ngaut** [comment]
Thanks.

**Comment by jackysp** [comment]
> > Can we import tikv as a package instead of code?
> 
> This branch is a transition state. We provide this branch because the TiKV client in TiDB is not suitable for pure KV users and https://github.com/tikv/client-go is out-of-date and lacks maintenance.
> 
> We are making plans to extract the current TiKV client in TiDB to update `tikv/client-go`. Then, we can import that package in TiDB.

Not easy, good luck!

**Pull request closed without merging**
