### PR TITLE
*: fix BIN test and check error for QUARTER.

### PR DESCRIPTION
**Pull request by coocood**
The BIN test puts a datum slice into a datum, which is an unknown datum type, `eval` returns error.

### CODE REVIEW

**Comment by coocood** [comment]
@tiancaiamao @zimulala PTAL

**Comment by coocood** [comment]
This fixes CI for https://github.com/pingcap/tidb/pull/3178

**Comment by tiancaiamao** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
