### PR TITLE
executor: add foreign keys to SHOW CREATE TABLE

### LINKED ISSUE #8349: SHOW CREATE TABLE should show added foreign keys
## Bug Report

See #8303: I do not know how to create a proper Entity-Relationship diagram with TiDB due to this issue.
Additionally, it may not be possible to retrieve the name of an added foreign key (needed for dropping it).

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Created a table, then as a separate step added foreign keys, then ran `SHOW CREATE <table>`.

2. What did you expect to see?

Foreign keys among the output.

3. What did you see instead?

No foreign keys.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

pingcap/tidb:v2.1.0-rc.4

### PR DESCRIPTION
**Pull request by nullnotnil**
### What problem does this PR solve?

Fixes #8349
Closes #8359 (alternative implementation)

Relates to #18209 (does not enforce foreign keys via DML)

Problem Summary:

TiDB currently parses and stores foreign key meta data, and makes it available in information schema. 

### What is changed and how it works?

This PR extends it to show the foreign key output in `SHOW CREATE TABLE`.

It is backwards compatible, due to the way TiDB handles foreign keys. The tests included verify that a child table can be created before a parent table, which ensures out of order restore for programs like mysqldump (which for mysql will `set foreign_key_checks=0` to have this behavior - TiDB does it by default).

#### MySQL Restore Compatibility

This PR is also safe when creating a backup of TiDB that restores on MySQL. The reason for this, is `mysqldump` sets `foreign_key_checks=0`, ensuring the restore does not worry about order. In the case of dumpling (which generates mydumper format), the restore is handled by loader. It is loader which [sets `foreign_key_checks=0`](https://github.com/maxbube/mydumper/blob/master/myloader.c#L175-L177) instead of including this line in each of the files.

#### MySQL Application Compatibility

There is a potential incompatibility based on an unlikely scenario:
- An application is first created with TiDB, and uses tables that have foreign keys.
- The database is then migrated to MySQL (it will succeed because restore compatibility is ensured)
- The application has logic errors with how it handles foreign keys, and DML statements fail because mysql defaults to enforcing DML.

This is similar to how the sql mode `ONLY_FULL_GROUP_BY` is less strict in TiDB than in MySQL. The problem can be summarized as "applications that were designed for TiDB may need to set global foreign_key_checks=0 when migrating to MySQL. This is because TiDB's foreign key handling is less strict than MySQL".

### Check List 

Tests 

- Unit test

Side effects

- Format of SHOW CREATE TABLE now differs

### Release note 

- SHOW CREATE TABLE now includes foreign key information

### CODE REVIEW

**Comment by gregwebs** [comment]
Code LGTM. I was a little worried about a scenario where someone transitions from TiDB to MySQL and then their restore fails due to foreign key checks and wanted to make sure this patch can be achieved with mydumper.

**Comment by nullnotnil** [comment]
> Code LGTM. I was a little worried about a scenario where someone transitions from TiDB to MySQL and then their restore fails due to foreign key checks and wanted to make sure this patch can be achieved with mydumper.

See the note in the description 'MySQL Restore Compatibility'. The issue would be the same mysql -> mysql, and is already handled by mydumper (and mysqldump, but differently).

**Comment by gregwebs** [comment]
That's good. Lets add a note about foreign keys now showing up so that after restore foreign key constraints will get checked in MySQL (when they are being used) and could fail.

**Comment by wangggong** [comment]
LGTM~

**Pull request merged**
