### PR TITLE
executor/infoschema_reader.go: skip the unidentifiable table-attributes

### LINKED ISSUE #33665: Checks for the region label id should be more robust
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```bash
➜  curl -X POST http://127.0.0.1:2379/pd/api/v1/config/region-label/rule -H "Content-Type: application/json" --data-binary @- <<DATA
{ "id": "tidb/meta/basic",
   "labels": [{"key": "data-type", "value": "meta"}],
   "rule_type": "key-range",
    "data": [{
         "start_key": "6d00000000000000f8",
         "end_key": "6e00000000000000f8"
   }]
}
DATA

➜  curl -X POST http://127.0.0.1:2379/pd/api/v1/config/region-label/rule -H "Content-Type: application/json" --data-binary @- <<DATA
{ "id": "tidb/meta",
   "labels": [{"key": "data-type", "value": "meta"}],
   "rule_type": "key-range",
    "data": [{
         "start_key": "6d00000000000000f8",
         "end_key": "6e00000000000000f8"
   }]
}
DATA
```

Run the following command from the mysql client:
```SQL
select * from information_schema.attributes;
ERROR 1105 (HY000): invalid label rule ID: tidb/meta
ERROR:
```

### 2. What did you expect to see? (Required)
```
+-----------------+-----------+------------------+------------------------------------------+
| ID              | TYPE      | ATTRIBUTES       | RANGES                                   |
+-----------------+-----------+------------------+------------------------------------------+
| tidb/meta/basic | key-range | "data-type=meta" | [6d00000000000000f8, 6e00000000000000f8] |
| tidb/meta       | key-range | "data-type=meta" | [6d00000000000000f8, 6e00000000000000f8] |
+-----------------+-----------+------------------+------------------------------------------+
```
or something like
```
+-----------------+-----------+------------------+------------------------------------------+
| ID              | TYPE      | ATTRIBUTES       | RANGES                                   |
+-----------------+-----------+------------------+------------------------------------------+
| tidb/meta/basic | key-range | "data-type=meta" | [6d00000000000000f8, 6e00000000000000f8] |
+-----------------+-----------+------------------+------------------------------------------+
WARNING: invalid label rule ID: tidb/meta
```

### 3. What did you see instead (Required)
```
ERROR 1105 (HY000): invalid label rule ID: tidb/meta
ERROR:
```
### 4. What is your TiDB version? (Required)

```bash
Release Version: v5.4.0
Edition: Community
Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-25 08:41:03
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: shirly <AndreMouche@126.com>

### What problem does this PR solve?

Issue Number: close #33665 

Problem Summary:
TiDB uses `region-rule` to store the attributes of the table,  and TiDB returns error when it can not identify the `region-rule`(which is not created by TiDB). This PR will skip and leave a warning log when meet the unidentifiable rule(table-attributes).

### Check List

Tests 

- [x] Unit test

- [x] Manual test (add detailed scripts or steps below)

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by nolouch** [comment]
cc @rleungx

**Comment by rleungx** [comment]
I think another option is we record the source, if the source is not TiDB, we can omit this check and give a warning.

**Comment by rleungx** [comment]
But just giving a warning is ok to me.

**Review by rleungx — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
