### PR TITLE
client-go: safeTS obtain min-resolved-ts by store list(hotfix)

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: ref #46664
cherry-pick #46661

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by HuSharp** [comment]
@nolouch @JmPotato PTAL, thx!

**Comment by HuSharp** [comment]
updated client-go with https://github.com/tikv/client-go/pull/956

**Review by nolouch — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Pull request merged**
