### PR TITLE
executor, cmd: refine HashJoinExec for specific JoinType if outer/inner is nil (#8296)

### PR DESCRIPTION
**Pull request by XuHuaiyu**
cherry-pick #8296

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
LGTM

**Comment by zz-jason** [comment]
@XuHuaiyu CI failed:
```
----------------------------------------------------------------------
FAIL: join_test.go:925: testSuite.TestHashJoin

join_test.go:961:
    c.Assert(len(row), Equals, 5)
... obtained int = 7
... expected int = 5
```

**Comment by XuHuaiyu** [comment]
release-2.1 does not contain this commit https://github.com/pingcap/tidb/pull/7842.
So the plan of `not exists` is different from the master branch.

**Comment by XuHuaiyu** [comment]
/run-unit-test tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by zz-jason** [comment]
/run-all-tests tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by crazycs520** [comment]
Maybe merge this cherry pick first. https://github.com/pingcap/tidb/pull/8331

**Pull request merged**
