### PR TITLE
executor: return error as expected when indexHashJoin occur error or panic in handleTask (#31323)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #31323 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/31446
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/31446:release-5.1-c27f8f697fc5
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/31129

Problem Summary:

### What is changed and how it works?
As the description in https://github.com/pingcap/tidb/issues/31129 mentioned.
And another bug is also fixed in this commit: when panic happen in `handleHashJoinInnerWorkerPanic`, error can not be returned successfully if keepOrder is true.

### Check List

Tests 

- [x] Integration test

Side effects

N/A

Documentation
N/A

### Release note

```release-note
Fix the bug that indexHashJoin may return the error `send on closed channel`.
```

### CODE REVIEW

**Review by guo-shaoge — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]

**Comment by wshwsh12** [comment]
Please fix the CI.

**Review by guo-shaoge — APPROVED** [review]

**Pull request merged**
