### PR TITLE
*: pass make race

### PR DESCRIPTION
**Pull request by shenli**
1. Fix bug founded in make race.
2. Fix make race run too long problem.

### CODE REVIEW

**Comment by shenli** [comment]
@coocood @tiancaiamao PTAL

**Comment by shenli** [comment]
@coocood PTAL

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
@tiancaiamao PTAL

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
