### PR TITLE
Dockerfile: Fix error while running `make server`

### PR DESCRIPTION
**Pull request by hzmangel**
The `LDFLAGS` in Makefile tries to get git commit hash while building
server component, but default COPY command does not put *.git* directory
into docker container, which causes the fatal error while executing
command `git rev-parse HEAD`.

This fix remove *.git* directory from *.dockerignore* file, then the git
command can be executed successfully in container.

### CODE REVIEW

**Comment by shenli** [comment]
@hzmangel Thanks for your PR!  Please sign the CLA.
@iamxy PTAL

**Comment by hzmangel** [comment]
@shenli Sorry, haven't noticed it yesterday. I have signed the CLA just now.

**Comment by iamxy** [comment]
This is really a flaw. thanks to @hzmangel !
LGTM

**Comment by shenli** [comment]
LGTM
Thanks @hzmangel

**Pull request merged**
