### PR TITLE
br: add `OWNERS` file

### LINKED ISSUE #47130: add `OWNERS` file for `br` folder

### PR DESCRIPTION
**Pull request by wuhuizuo**
Fixes #47130

### What problem does this PR solve?

Issue Number: close #47130

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [x] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

/type enhancement
/component br

### CODE REVIEW

**Comment by wuhuizuo** [comment]
/hold

It need tests for full config with a default regex route.

**Comment by wuhuizuo** [comment]
/cc  BornChanger  3pointer YuJuncen Leavrth

/cc sig-critical-approvers-tidb-lightning
for approving on `OWNERS` file.

**Review by BornChanger — APPROVED** [review]

**Comment by easonn7** [comment]
/approve

There is no sysvar change.

**Comment by okJiang** [comment]
I think https://github.com/pingcap/tidb/tree/master/br/pkg/lightning can be excluded. https://github.com/pingcap/tidb/tree/master/br/pkg/storage can be jointly maintained

**Comment by wuhuizuo** [comment]
> I think https://github.com/pingcap/tidb/tree/master/br/pkg/lightning can be excluded. https://github.com/pingcap/tidb/tree/master/br/pkg/storage can be jointly maintained

Thanks `br/pkg/lightning` I will create another PR to add `OWNERS` file, it's in task lists #46911

**Comment by wuhuizuo** [comment]
/unhold

It's solved.

> /hold
> 
> It need tests for full config with a default regex route.

**Review by YuJuncen — APPROVED** [review]

**Comment by YuJuncen** [comment]
Also note that `lightning` is still in `br/pkg`, will this give all br forks the permission in `tidb-lightning`?

**Comment by wuhuizuo** [comment]
> Also note that `lightning` is still in `br/pkg`, will this give all br forks the permission in `tidb-lightning`?

Next PR for br/pkg/lightning is coming.

**Pull request merged**
