### PR TITLE
sli: move small read duration metrics to store/tikv

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?
Found new PR introduces dependency and prevents us to move `store/tikv` to standalone repo.

Part of https://github.com/pingcap/tidb/issues/22513

### What is changed and how it works?
What's Changed:
- move metrics to store/tikv/metrics

### Check List 
Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by AndreMouche — APPROVED** [review]
LGTM

**Comment by sticnarf** [comment]
cc @crazycs520

**Review by crazycs520 — APPROVED** [review]
LGTM

**Pull request merged**
