### PR TITLE
types: fix converting decimal to datetime and timestamp

### PR DESCRIPTION
**Pull request by Debiancc**
### What problem does this PR solve? <!--add issue link with summary if exists-->
fix https://github.com/pingcap/tidb/issues/9770

### What is changed and how it works?
In Datum.convertToMysqlTime function add `KindMysqlDecimal` switch case, and convert decimal to string then parse to Time

### Check List <!--REMOVE the items that are not applicable-->

Tests <!-- At least one of them must be included. -->
 - Unit Test
 - Manual test (https://github.com/pingcap/tidb/issues/9770)

```
mysql> INSERT INTO t1 VALUES (20010101100000.1234566);
Query OK, 1 row affected (0.00 sec)

mysql> select * from t1;
+----------------------------+
| a                          |
+----------------------------+
| 2001-01-01 10:00:00.123456 |
| 2001-01-01 10:00:00.123457 |
| 2001-01-01 10:00:00.123457 |
+----------------------------+
3 rows in set (0.00 sec)

mysql> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                             |
| Release Version: v3.0.0-beta-251-gb4cc3e489-dirty
Git Commit Hash: b4cc3e48934afaefbf6d5f65b5414b8b65117234
Git Branch: master
UTC Build Time: 2019-03-26 07:10:09
GoVersion: go version go1.12.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |

1 row in set (0.00 sec)
```

Side effects

 - Possible performance regression

### CODE REVIEW

**Comment by qw4990** [comment]
```
CREATE TABLE t2(a TIMESTAMP);
INSERT INTO t2 VALUES (20010101100000.1234567);
```
And besides `MysqlTime`, when TiDB converts a `Decimal` to `Timestamp`, it will generate a similar error like `ERROR 1105 (HY000): cannot convert datum from decimal to type timestamp.`.

This problem should have the same reason with `MysqlTime`.
Could you please fix this problem 😺

**Comment by Debiancc** [comment]
> ```
> CREATE TABLE t2(a TIMESTAMP);
> INSERT INTO t2 VALUES (20010101100000.1234567);
> ```
> And besides `MysqlTime`, when TiDB converts a `Decimal` to `Timestamp`, it will generate a similar error like `ERROR 1105 (HY000): cannot convert datum from decimal to type timestamp.`.
> 
> This problem should have the same reason with `MysqlTime`.
> Could you please fix this problem 😺

Sure, i will fix that and cover test later.

**Comment by qw4990** [comment]
@Debiancc There are some CI problems, but it seems that they are not caused by this PR.
Could you please resolve these conflicts and rebase this PR to the latest Master branch.

**Comment by zz-jason** [comment]
@Debiancc please cherry pick this change to release 2.1

**Pull request merged**
