### PR TITLE
executor: migrate test-infra to testify for explain_unit_test.go

### LINKED ISSUE #28579: migrate test-infra to testify for `explain_unit_test.go`

### PR DESCRIPTION
**Pull request by tisonkun**
### What problem does this PR solve?

Issue Number: close #28579 

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by tisonkun** [comment]
cc @hi-rustin @Mini256 it seems @ti-chi-bot just doesn't work...

**Pull request merged**
