### PR TITLE
ddl: add Test Case for /*T![placement] when create table

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: related to https://github.com/pingcap/parser/pull/1334

Problem Summary:

### What is changed and how it works?

How it Works:
Make changes of https://github.com/pingcap/parser/pull/1334 take effects.

### Check List 

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by AilinKid — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by djshow832** [comment]
Please fill the `Check List` in the PR description.

**Comment by djshow832** [comment]
I have submitted an issue related to the failed test case: https://github.com/pingcap/tidb/issues/28099

**Pull request merged**
