### PR TITLE
ddl: implement `ALTER DATABASE` to alter charset/collation (#10393)

### PR DESCRIPTION
**Pull request by bb7133**
Cherry-pick https://github.com/pingcap/tidb/pull/10393

Related parser PR: https://github.com/pingcap/parser/pull/327

### CODE REVIEW

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by bb7133** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by winkyao** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Pull request merged**
