### PR TITLE
ddl: Reduce the unnecessary memory allocation and make code clearer

### PR DESCRIPTION
**Pull request by zimulala**
Add the column's meta-information to save column information when adding column
Use `kvIndex` instead of indexInfo
Above operations can reduce the unnecessary memory allocation and make code clearer.

After This PR, I will push a PR to speed up the phase of adding columns and indices.

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by zimulala** [comment]
PTAL @tiancaiamao @shenli @hanfei1991

**Comment by shenli** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
