### PR TITLE
parser: make normalization more aggressive

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/43409

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Merge multiple placeholder lists into one to make SQL normalization more aggressive, in order to avoid meaningless distinctions that eliminate other meaningful SQLs.
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — COMMENTED** [review]
TestExtensionStmtEvents failed.

**Review by xhebox — APPROVED** [review]

**Pull request merged**
