### PR TITLE
ranger: handle decimal overflow properly when building index ranges (#23535)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23535 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23551
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23551:release-5.0-1915517c0c0d
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23483

Problem Summary:

Planner reports error for a query.

### What is changed and how it works?

What's Changed: Ignore the overflow error for decimal type in ranger.

How it Works: `zeroMyDecimal` would be returned if overflow error occurs, so `convertPoint` would adjust the `excl` of the boundary accordingly, and impossible ranges would be removed by consequent `validIntervals()`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- Handle decimal overflow properly when building index ranges

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by time-and-fate — APPROVED** [review]
/lgtm

**Pull request merged**
