### PR TITLE
executor: fix batchGet/PointGet overflow result in clustered index (#23516)

### LINKED ISSUE #23510: cluster index table Error: key not exist
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE `PK_S_MULTI_31_1` (  `COL1` tinyint(11) NOT NULL,  `COL2` tinyint(11) NOT NULL,  `COL3` tinyint(11) DEFAULT NULL,  PRIMARY KEY (`COL1`,`COL2`) /*T![clustered_index] CLUSTERED */);
select * from PK_S_MULTI_31_1 where col2 = -129 and col1 = 1;
```

### 2. What did you expect to see? (Required)
execute successfully without error
### 3. What did you see instead (Required)
```sql
mysql root@127.0.0.1:test>   CREATE TABLE `PK_S_MULTI_31_1` (  `COL1` tinyint(11) NOT NULL,  `COL2` tinyint(11) NOT NULL,  `COL3` tinyint(11) DEFAULT NULL,  PRIMARY KEY (`COL1`,`COL2`) /*T![clustered_index] CLUSTERED */);
Query OK, 0 rows affected
Time: 0.006s
mysql root@127.0.0.1:test> select * from PK_S_MULTI_31_1 where col2 = -129 and col1 = 1;
(8021, 'Error: key not exist')
```
### 4. What is your TiDB version? (Required)
master: b1b375e7ef0

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23516 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23533
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23533:release-5.0-a51d20027f08
```

---

### What problem does this PR solve?

Issue Number: close #23510 

Problem Summary:

point-get/batch-get with a overflow value will be treated as ErrNotExist

clustered index logic should return empty just like non-clustered code path.

### What is changed and how it works?

What's Changed, How it Works:

return empty if ErrNotExist

### Related changes

- Need to cherry-pick to the release branch 5.0

### Check List 

Tests 

- Unit test

Side effects

- n/a

### Release note 

- n/a

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/23516)

### CODE REVIEW

**Comment by lysu** [comment]
@coocood  PTAL

**Review by zz-jason — APPROVED** [review]

**Pull request merged**
