### PR TITLE
test: fix unstable test TestStaleReadProcessorWithSelectTable

### LINKED ISSUE #37228: unstable test TestStaleReadProcessorWithSelectTable
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

make race 

```
 --- FAIL: TestStaleReadProcessorWithSelectTable (5.81s)
    processor_test.go:149: 
        	Error Trace:	/go/tidb/sessiontxn/staleread/processor_test.go:149
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 3
        	Test:       	TestStaleReadProcessorWithSelectTable
FAIL
```

https://prow.pingcap.net/view/gs/pingcapprow/logs/tidb_race/1560423889782181888

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #37228

Problem Summary:

If the test takes more than 5 seconds to run, it will fail.

### What is changed and how it works?

Extend the staleness in the test. The threshold is now extended to 100 seconds (just a random big number)

### CODE REVIEW

**Comment by YangKeao** [comment]
I cannot read the test log (as it's 404 now :facepalm: ). It's just a guess :thinking: .

**Review by xhebox — APPROVED** [review]

**Comment by tangenta** [comment]
@YangKeao Here is the new failed [test log](https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/8585/tests/).

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
here is new log. https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/ghpr_unit_test/runs/9739/nodes/49/steps/54/log/?start=0

**Comment by YangKeao** [comment]
> @YangKeao here is new log. https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/ghpr_unit_test/runs/9739/nodes/49/steps/54/log/?start=0

Yes. After reading the log, I'm quite sure it would be fixed by this PR :smile: . Thanks for providing the information.

**Pull request merged**
