### PR TITLE
*: Use go.etcd.io/etcd instead of github.com/coreos/etcd

### PR DESCRIPTION
**Pull request by hewenyang**
Match etcd's package name changes. Does not actually change any code or logic. Related to #8774.

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8775)

### CODE REVIEW

**Comment by shenli** [comment]
@hewenyang Thanks!
Please keep the PR template and fill it and please fix the CI.
/cc @disksing

**Comment by disksing** [comment]
```
owner/manager.go:151: cannot use etcdCli (type *"go.etcd.io/etcd/clientv3".Client) as type *"github.com/coreos/etcd/clientv3".Client in argument to concurrency.NewSession
```
It doesn't seem to be completely updated.

**Comment by hewenyang** [comment]
After some more investigation I figured out that etcd has not yet published a release after rename:
https://github.com/etcd-io/etcd/commit/2ac04381a262dda58ce8fc8f8f85961da3be9e92
The commit is not merged into 3.3.10, only in master. Have to wait for another release before the package name can be changed.

**Comment by guzhenping** [comment]
@admin  l want to build tidb source. but meet this bug....

why not fix ... that's easy

**Comment by winoros** [comment]
@guzhenping What the failure did you met?

**Comment by zz-jason** [comment]
@hewenyang Thanks your your contribution, could you merge the latest master branch and resolve the conflicts?

**Comment by zz-jason** [comment]
I'm going to close this PR due to outdated, fell free to reopen it if you are going to process it again in the future.

**Pull request closed without merging**
