### PR TITLE
*: move config file option enable-batch-dml to sysvar

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/33769

Problem Summary:

The option `enable-batch-dml` has historically been a config option. But based on requirements from cloud & PM it should instead be a sysvar.

### What is changed and how it works?

This does the minimum work to convert `enable-batch-dml`  to a global (cluster-wide) sysvar, and removes the config option (placing it in the previously deprecated list).

### Check List

Tests 

- [x] Unit test (convert existing tests)
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility
This might be a bit confusing during upgrade for users who have previously set `enable-batch-dml` (most users haven't). It needs to be documented in the release notes that it has been replaced with the system variable `tidb_enable_batch_dml`.

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
The TiDB configuration file option `enable-batch-dml` has been replaced by the system variable `tidb_enable_batch_dml`. This change makes it easier to modify this setting on a cluster wide basis.
```

### CODE REVIEW

**Comment by bb7133** [comment]
> This might be a bit confusing during upgrade for users who have previously set enable-batch-dml (most users haven't). It needs to be documented in the release notes that it has been replaced with the system variable tidb_enable_batch_dml.

It's really a big risk for the upgraded cluster: when the users upgraded TiDB from v6.0 to v6.1, the behavior of the cluster will be changed(`enable-batch-dml` became `false`) unless they read the release note.

Could we add a `upgradeToVerXXX` function in bootstrap step, set the sysvar using the configuration to make sure that upgraded clusteres keeps the original behavior?

**Comment by morgo** [comment]
> Could we add a `upgradeToVerXXX` function in bootstrap step, set the sysvar using the configuration to make sure that upgraded clusteres keeps the original behavior?

I had considered that, but the reason why I did not, was that it would only be able to read the configuration value from one tidb server (the one that runs the bootstrap upgrade process) and not all TiDB servers. My concern with that specifically, is it is not quite deterministic (you might have more than one server, with more than one config, once the bootstrap is run, it's done.)

I am happy to change it to this if you consider it more correct however.

**Comment by bb7133** [comment]
> it would only be able to read the configuration value from one tidb server (the one that runs the bootstrap upgrade process) and not all TiDB servers

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by bb7133** [comment]
PTAL @hawkingrei @xhebox @tiancaiamao

**Review by xhebox — APPROVED** [review]

**Comment by hawkingrei** [comment]
@morgo Please fix it.

```
[2022-05-13T08:04:04.681Z] session/nontransactional.go:116:18: undefined: config

```

**Comment by cfzjywxk** [comment]
The batch DML is to be [deprecated](https://github.com/pingcap/tidb/pull/13081) in the future, I think we don't need to make it [public](https://github.com/pingcap/docs/pull/8689/files#diff-ec2cbb115cc58fe3afe2862eb5148732d323cbf7ae35dea97bd381a1f8d0e8a0R778) to the users again instead non-transactional DML is suggested to be used.
/cc @jackysp @ekexium @zhangjinpeng1987

**Comment by ekexium** [comment]
> The batch DML is to be [deprecated](https://github.com/pingcap/tidb/pull/13081) in the future, I think we don't need to make it [public](https://github.com/pingcap/docs/pull/8689/files#diff-ec2cbb115cc58fe3afe2862eb5148732d323cbf7ae35dea97bd381a1f8d0e8a0R778) to the users again instead non-transactional DML is suggested to be used. /cc @jackysp @ekexium @zhangjinpeng1987 @TomShawn

There are users using this feature and they keep asking how to enable it in the past months. I'm not sure if it's the right time to hide it

**Pull request merged**
