### PR TITLE
br: skip compatibility check for the mysql.user table when restoring

### LINKED ISSUE #38785: BR: 6.2.0 system table mysql.user can't be restored to 6.4.0
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
tidb changed mysql.user schema in 6.4.0
version95	add a column `User_attributes` to `mysql.user`
version98	add a column `Token_issuer` to `mysql.user`

when restore 6.2.0 mysql.user to 6.4.0 will report :
Error: column count mismatch, table: user, col in cluster: 38, col in backup: 37: [BR:Restore:ErrR

### 2. What did you expect to see? (Required)
restore success
### 3. What did you see instead (Required)
Error: column count mismatch, table: user, col in cluster: 38, col in backup: 37: [BR:Restore:ErrR
### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by MoCuishle28**
Signed-off-by: zhanggaoming <gaoming.zhang@pingcap.com>

### What problem does this PR solve?

Issue Number: close #38785

Problem Summary:
TiDB changed mysql.user schema in higher version
e.g.,
`version95` add a column `User_attributes` to `mysql.user`
`version98` add a column `Token_issuer` to `mysql.user`

when restore 6.2.0 mysql.user to 6.4.0 will report :
`Error: column count mismatch`

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Manual Test
- insert record into mysql.user in v5.1.0 cluster
- run full backup
- restore to v6.4.0 cluster
- success

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix a bug that caused: When restoring a low-version system table to a high-version cluster, it fails due to missing columns.
```

### CODE REVIEW

**Comment by MoCuishle28** [comment]
> Let's comment a warning [here](https://github.com/pingcap/tidb/blob/master/session/bootstrap.go#L63) like:
> 
> > WARNING: There are some limitations on altering the schema of mysql.user table. Adding columns that are nullable or have default values is permitted. But operations like dropping or renaming columns may break the compatibility with BR.
> > REFERENCE ISSUE: #38785

Done.

**Review by 3pointer — APPROVED** [review]

**Comment by CbcWestwolf** [comment]
PTAL @qw4990 @jackysp

**Review by lance6716 — APPROVED** [review]
resolve this "tide Pending — Not mergeable. PullRequest is missing sufficient approving GitHub review(s)"

**Comment by lance6716** [comment]
Oh it's lacking tidb-configuration-reviewer

**Review by qw4990 — APPROVED** [review]

**Pull request merged**
