### PR TITLE
expression: fix last_day function

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve? 
For #9731 

### What is changed and how it works?
Retun `NULL` as long as the month is 0.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by qw4990** [comment]
@wjhuang2016 thanks for your contribution.
Could you please cherry-pick this PR into branch `release 2.1` after it's merged.

**Comment by wjhuang2016** [comment]
> @wjhuang2016 thanks for your contribution.
> Could you please cherry-pick this PR into branch `release 2.1` after it's merged.

Please tell me how to do it, I'm not familiar with git.

**Comment by qw4990** [comment]
> > @wjhuang2016 thanks for your contribution.
> > Could you please cherry-pick this PR into branch `release 2.1` after it's merged.
> 
> Please tell me how to do it, I'm not familiar with git.

Pull branch `release-2.1` to your local and then cherry-pick this PR into branch `release-2.1` locally, then submit a new PR into TiDB `release-2.1` 😺

**Pull request merged**
