### PR TITLE
expression: speed up the test TestIssue16697

### LINKED ISSUE #17399: Speed up the test TestIssue16697
## Development Task
Now the test `TestIssue16697` costs 40+s in our data race test, so we need to speed up it.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #17399 

Problem Summary: the test `TestIssue16697` costs 40+s in our data race test, so we need to speed up it.

### What is changed and how it works?
Using `varchar(1024)` with a few rows to construct memory usage in `Projection` instead of using `Join` to generate lots of rows.

### Check List 

Tests 

- Unit test

### Release note 
- Speed up the test `TestIssue16697`

### CODE REVIEW

**Comment by zz-jason** [comment]
what's the performance inprovement of this PR?

**Comment by qw4990** [comment]
> what's the performance inprovement of this PR?

This PR changes the way to construct memory usage in `ProjectionExec`, which reduces the time cost of `TestIssue16697`.
```
old: [2020-05-26T02:55:02.174Z] PASS: integration_test.go:6393: testIntegrationSuite.TestIssue16697	48.792s
new: [2020-05-26T03:19:37.023Z] PASS: integration_test.go:6393: testIntegrationSuite.TestIssue16697	0.356s
```

**Pull request merged**
