### PR TITLE
txn: tidb_constraint_check_in_place_pessimistic should not be global scoped

### LINKED ISSUE #38766: `tidb_constraint_check_in_place_pessimistic` should not be global scope
## Enhancement
Changing this variable can lead to unexpected results. Internals sessions shouldn't be affected by it as well, e.g. the imeplementation of `get_lock()` depends on `tidb_contraint_check_in_place_pessimistic=1`to work.
We should only allow sessions that are aware of its effects use it.

### PR DESCRIPTION
**Pull request by ekexium**
### What problem does this PR solve?

Issue Number: close #38766

Problem Summary:

Changing this variable can lead to unexpected results. Internals sessions shouldn't be affected by it as well, e.g. the imeplementation of `get_lock()` depends on `tidb_contraint_check_in_place_pessimistic=1` to work.
We should only allow sessions that are aware of its effects to use it.

### What is changed and how it works?

- Change the scope of `tidb_constraint_check_in_place_pessimistic` to session only.
- Add a config item `pessimistic-txn.constraint_check_in_place_pessimistic` to control the default value of the session variable.
- Don't let it take effect in restricted SQLs.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Manually tested the config can affect the default value of the variable.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Variable `tidb_constraint_check_in_place_pessimistic` is made session scope only.
Add a new config item `pessimistic-txn.constraint_check_in_place_pessimistic` to control the default value of the variable.
```

### CODE REVIEW

**Comment by ekexium** [comment]
cc @bob34007, @songrijie 
Could you help confirm that potential users can accept this change?

**Comment by you06** [comment]
I think the issue of `get_lock` is caused by uninitialized [here](https://github.com/pingcap/tidb/blob/65a318fcb5ea6f7790fc65439faf182d2e579794/sessionctx/variable/session.go#L1475).

**Comment by ekexium** [comment]
According to by @bob34007 's requirement, it is made a instance level variable now. And we make sure in every single transaction, the value cannot change.

**Comment by ekexium** [comment]
> I think the issue of `get_lock` is caused by `SessionVars.ConstraintCheckInPlacePessimistic` is uninitialized [here](https://github.com/pingcap/tidb/blob/65a318fcb5ea6f7790fc65439faf182d2e579794/sessionctx/variable/session.go#L1475).

I think the value would be overridden by the global setting before a statement executes?

**Comment by ekexium** [comment]
We are making it a session variable with the default value specified by a config item now.

**Comment by ekexium** [comment]
PTAL @you06 @sticnarf

**Review by you06 — APPROVED** [review]

**Review by sticnarf — COMMENTED** [review]
Should we always set `ConstraintCheckInPlacePessimistic` to true for internal sessions?

**Comment by ekexium** [comment]
> Should we always set `ConstraintCheckInPlacePessimistic` to true for internal sessions?

Is there a perfect way to distinguish internal sessions?

**Comment by sticnarf** [comment]
> Is there a perfect way to distinguish internal sessions?

Internal sessions are typically fetched from the internal session pool. The sessions of the pool are created using the factory function `session.createSessionFunc` or `session.createSessionWithDomainFunc`.

**Comment by ekexium** [comment]
> > Is there a perfect way to distinguish internal sessions?
> 
> Internal sessions are typically fetched from the internal session pool. The sessions of the pool are created using the factory function `session.createSessionFunc` or `session.createSessionWithDomainFunc`.

Well looks like that's it. They're not explicitly marked for creating internal sessions though.
And nothing stops people from randomly creating sessions in whatever ways they like
https://github.com/pingcap/tidb/blob/3baebdba630ab355c4f993f2b36bd79fbd512107/session/session.go#L1814-L1819

This is totally a mess. Let's just keep both the check of restrictedSQL and the initial value setting and hope there won't be problems.

**Comment by sticnarf** [comment]
> This is totally a mess. Let's just keep both the check of restrictedSQL and the initial value setting and hope there won't be problems.

Yes... We cannot prevent people from creating an internal session and not setting `InRestrictedSQL` as well.

Emm, maybe `ConnectionID` is also something we can use to know whether it's an internal session...

**Comment by you06** [comment]
> And nothing stops people from randomly creating sessions in whatever ways they like

That's bad usage, IMO the `get_lock` function needs to be redesigned, it's better to implement the function using the sessions from the pool. To avoid the loss of pessimistic locks, a row needs to be inserted into the lock table instead.

**Review by sticnarf — APPROVED** [review]

**Comment by ekexium** [comment]
@sticnarf could you help merge it?

**Review by sticnarf — APPROVED** [review]
LGTM

**Comment by sticnarf** [comment]
@cfzjywxk Seems it requires an approve from "tidb-configuration-reviewer". Could you take a look?

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
