### PR TITLE
table: fix lazy check key condition in index.Create and AddRecord

### PR DESCRIPTION
**Pull request by ekexium**
### What problem does this PR solve?

Issue Number: ref #50215

Problem Summary:

`INSERT IGNORE ... ON DUPLICATE UPDATE ...` could return a `Duplicate entry` error for a Pipelined-DML, because it does lazy checks in the places modified by this PR, and the error is returned when committing. It does not break data constraints, but we expect that such error should be ignored because we specify `IGNORE`, as in a normal DML.

### What changed and how does it work?

Change the condition of lazy check: do not let pipelined DML enforce lazy checks. If the executor think this is the place to do `txn.Get`, then do it.
Note that we enforce Pipelined-DML to have `tidb_constraint_check_in_place=false`.
https://github.com/pingcap/tidb/blob/e34945121bc4b365c87454f69296775dee8760bf/pkg/session/session.go#L4346-L4349

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by cfzjywxk — APPROVED** [review]

**Review by you06 — COMMENTED** [review]
The insert statement will get each unique/primary key in `AddRecord` then, shall we manually set `PresumeKeyNotExists` for simple insert statement?

Rest LGTM.

**Comment by cfzjywxk** [comment]
> The insert statement will get each unique/primary key in `AddRecord` then, shall we manually set `PresumeKeyNotExists` for simple insert statement?
> 
> Rest LGTM.

@you06  Do you mean simple `INSERT` statement using pipelined-dml mode?

**Comment by you06** [comment]
> @you06 Do you mean simple `INSERT` statement using pipelined-dml mode?

@cfzjywxk sorry mistake, it happens in insert-on-duplicate-key-update, run `go test ./tests/realtikvtest/pipelineddmltest --tags=intest -run TestPipelinedDMLInsertRPC ` can fail now.

**Comment by ekexium** [comment]
Won't fix this because it will inevitably introduce notable performance overhead. We may have to keep this behavior for pipelined DML

**Pull request closed without merging**
