### PR TITLE
*: replace os.MkdirTemp with t.TempDir

### LINKED ISSUE #32070: testing: use t.TempDir instead of os.MkdirTemp
## Enhancement

`t.TempDir` (or `c.MkDir`) is useful in test because we do not need to care about cleanup.

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?

Issue Number: close #32070

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Comment by siddontang** [comment]
if the test failed, can this automatically cleanup the tmp directory?

**Comment by tisonkun** [comment]
@siddontang No. And you don't have to. It creates a temp dir based on OS env and OS will periodically clean up temp dir and temp files. See also https://en.wikipedia.org/wiki/Temporary_folder

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
