### PR TITLE
domain: make TestSchemaValidator stable (#8334)

### PR DESCRIPTION
**Pull request by zimulala**
Cherry-pick #8334

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8408)

### CODE REVIEW

**Comment by zimulala** [comment]
/run-all-tests tidb-test=release-2.1 tidb-private-test=release-2.1 tikv=release-2.1

**Comment by zimulala** [comment]
PTAL @XuHuaiyu @tiancaiamao

**Comment by XuHuaiyu** [comment]
PTAL @zz-jason

**Pull request merged**
