### PR TITLE
*: Log SQL statement when coprocessor encounteres lock (#27735)

### LINKED ISSUE #27718: Show information about SQL statement in the debug log about coprocessor encountering lock
## Enhancement

When coprocessor reading meets lock, TiDB will print a [debug log](https://github.com/pingcap/tidb/blob/477593e31f281d57d66319a66d56326baf809c1a/store/copr/coprocessor.go#L885). However it shows nothing about the related SQL statements, and there's not anywhere else that shows the statements that's affected by the lock. If this log can print the statement, it will be helpful for diagnose some problems. Of course, the statement in the log should be redacted according to the security options.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #27735 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/27926
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/27926:release-4.0-649ed6abc979
```

---

### What problem does this PR solve?

Issue Number: close #27718

Problem Summary: The debug log on coprocessor encounters lock doesn't print out the statement, which makes it difficult to know what statement was affected by the lock. This PR tries to add the log.

### What is changed and how it works?

What's Changed: Added a callback parameter to the `Send` method of `kv.Client` that accepts a new TransactionEvent object. This avoids to pass the SQL statement deep down to the coprocessor client part. And I think this callback and events can also be reused by Lock View.

How it Works:

### Check List 

Tests 

- [ ] Manual test (add detailed scripts or steps below) (TODO)

Side effects

- [ ] Performance regression: Consumes more CPU

Documentation

- None

### Release note 

```release-note
None.
```

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@MyonKeminta 
Do we need to pick to v4.0.x ?

**Comment by MyonKeminta** [comment]
> @MyonKeminta
> Do we need to pick to v4.0.x ?

I'm asked to do so. But I'll hold it until these PRs are confirmed can be merged in these release branches, since it's quite annoying to resolve the conflicts.

**Review by cfzjywxk — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]

**Pull request merged**
