### PR TITLE
*: update tikv/client-go and fix stale read metrics in grafana

### LINKED ISSUE #45339: refine stale read metrics

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

cherry-pick #45340

Issue Number: close #45339

related PR: https://github.com/tikv/client-go/pull/889

Problem Summary:

### What is changed and how it works?

image

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by crazycs520** [comment]
@you06 @cfzjywxk PTAL

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
