### PR TITLE
dumpling : add err message for dumpling

### PR DESCRIPTION
**Pull request by docsir**
### What problem does this PR solve?

Issue Number: close #https://github.com/pingcap/dumpling/issues/370

Problem Summary: dumpling should report error if --consistency is lock and --snapshot parameter is provided

### What is changed and how it works?
Add error message when --consistency is lock and --snapshot parameter is provided.

### Check List

Tests 

- [ ] Unit test
- [ ] Manual test (add detailed scripts or steps below)

### Release note

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by lichunzhu — APPROVED** [review]

**Comment by lichunzhu** [comment]
waiting for dumpling sync_diff configuration update

**Pull request merged**
