### PR TITLE
add default value of Password Validation Variables

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
add default value of Password Validation Variables, according to this mysql's documents:
[https://dev.mysql.com/doc/refman/5.7/en/validate-password-options-variables.html#sysvar_validate_password_length](url)

### CODE REVIEW

**Comment by ngaut** [comment]
Thank you for your PR, please sign the CLA.

**Comment by WangXiangUSTC** [comment]
done

**Comment by shenli** [comment]
LGTM
Thanks! @WangXiangUSTC

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
