### PR TITLE
txn: deprecate the transaction auto retry and related statement count limit

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve?

Issue Number: ref #50350 

Problem Summary:
Related to https://github.com/pingcap/docs-cn/pull/16010/, deprecate the `tidb_disable_txn_auto_retry` system variable.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Deprecate the `tidb_disable_txn_auto_retry` system variable and `stmt-count-limit` in the configuration file.
```

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@easonn7 @benmaoer
PTAL

**Comment by cfzjywxk** [comment]
@joey-yez
PTAL

**Review by zyguan — APPROVED** [review]

**Comment by cfzjywxk** [comment]
@wjhuang2016 @tangenta @zimulala 
Please take a look if this change may introduce any risks for the internal transction usages, thanks.

**Review by tangenta — APPROVED** [review]
lgtm for ddl part

**Pull request merged**
