### PR TITLE
executor: add unit test for aggfuncs

### PR DESCRIPTION
**Pull request by Xuanwo**
### What problem does this PR solve?

https://github.com/pingcap/tidb/issues/7042

### What is changed and how it works?

This pr split unit tests to corresponding file so that we can organize tests better and adds test for `min` aggfuns.

### CODE REVIEW

**Comment by Xuanwo** [comment]
@XuHuaiyu This pr has been split into this and https://github.com/pingcap/tidb/pull/7993 , PTAL

**Comment by zz-jason** [comment]
@Xuanwo #7993 was merged. Please resolve conflicts

**Comment by Xuanwo** [comment]
@zz-jason Conflicts resolved.

**Pull request merged**
