### PR TITLE
store/tikv: make function TestCheckTxnStatus more stable in CI

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

Sometime the CI fail like this:

```
[2019-10-29T01:59:11.316Z] 
[2019-10-29T01:59:11.316Z] ----------------------------------------------------------------------
[2019-10-29T01:59:11.316Z] FAIL: lock_test.go:271: testLockSuite.TestCheckTxnStatus
[2019-10-29T01:59:11.317Z] 
[2019-10-29T01:59:11.317Z] lock_test.go:287:
[2019-10-29T01:59:11.317Z]     c.Assert(status.ttl, Greater, uint64(0))
[2019-10-29T01:59:11.317Z] ... compare_one uint64 = 0x0
[2019-10-29T01:59:11.317Z] ... compare_two uint64 = 0x0
[2019-10-29T01:59:11.317Z] 
[2019-10-29T01:59:11.317Z] 
[2019-10-29T01:59:11.317Z] ----------------------------------------------------------------------
```

This may happen when lock TTL is too small, and during a network roundtrip after obtaining the tso, the lock is gone.

### What is changed and how it works?

Increase lock TTL to make CI more stable.

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @coocood

**Comment by coocood** [comment]
@tiancaiamao Does it increase test time?

**Comment by tiancaiamao** [comment]
> @tiancaiamao Does it increase test time?

No.

The logic here is:
1. write a lock
2. check lock exist
3. rollback the lock
4. check lock doesn't exist

Those steps don't involve waiting for TTL expire, so it doesn't increase test time.

**Pull request merged**
