### PR TITLE
executor: fix lost insert row when insert multi rows on duplicate key update

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve? 
Fix the same bug on release-2.0 as https://github.com/pingcap/tidb/pull/7675.
When the table has two or more unique index and its primary key is int type, the statement with three rows, the second and third rows conflict with the first one but with different indices. The second row will update the first row, but it deletes the dupKV map with itself by mistake. It will cause a fake update instead of insert without conflicts. See the test case in this PR as an example.

### What is changed and how it works?
Delete the correct keys in dupKV map.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

 - Increased code complexity

PTAL @coocood

### CODE REVIEW

**Comment by shenli** [comment]
Could you please paste the original PR link here?

**Comment by coocood** [comment]
/run-all-test tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by coocood** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by coocood** [comment]
LGTM

**Comment by zhexuany** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Comment by coocood** [comment]
/run-all-tests tidb-test=release-2.0 tikv=release-2.0 pd=release-2.0

**Pull request merged**
