### PR TITLE
br: run `UpdateTableStatsLoop` when domain is not bootstrapped

### LINKED ISSUE #44490: br: TiDB panic during restoring data with runtime error: invalid memory address or nil pointer dereference
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Restore data of bank workload from minio

### 2. What did you expect to see? (Required)
The data restore successfully
### 3. What did you see instead (Required)
```
DataBase Restore <---------------------------------------\\..................................> 53.28%DataBase Restore <-----------------------
----------------|..................................> 53.28%panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1
addr=0x0 pc=0x3ab0170]\n\ngoroutine 760 [running]:\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).SaveStatsToStorage(0x0, 0xc7, 0x186a0, 0x0?, 0x0, 0xc0047b46c0, 0x1d12aeb?, 0
x0?, 0x55a4de0?, 0x1, ...)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/statistics/handle/handle.go:1555 +0x130\ngithub.com/pingcap/tidb/statistics/han
dle.(*Handle).loadStatsFromJSON(0xc001c86cd0?, 0xc001c86c08?, 0x4?, 0xc001c86c08?)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/statistics/handle/dump.
go:382 +0x112\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).LoadStatsFromJSON(0xc000524a80?, {0x634b6e8, 0xc001d6c000}, 0xc000eb52d0)\n\t/home/jenkins/agent/workspace/build-c
ommon/go/src/github.com/pingcap/br/statistics/handle/dump.go:347 +0x14f\ngithub.com/pingcap/tidb/br/pkg/restore.(*Client).updateMetaAndLoadStats(0xc000c1bd40, {0x6314ad0, 0xc000e2ef
f0}, 0xc00267d320)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/restore/client.go:1777 +0x6c5\ngithub.com/pingcap/tidb/br/pkg/restore.(*Client).
GoValidateChecksum.func1()\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/restore/client.go:1626 +0x68\ncreated by github.com/pingcap/tidb/br/pkg/
restore.(*Client).GoValidateChecksum\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/restore/client.go:1624 +0x185"]
```

The last few lines of br.log
```
[2023/06/07 20:35:50.412 +08:00] [INFO] [pipeline_items.go:394] ["restore batch done"] [ranges="{total=128,ranges=\"[\\\"[7480000000000000BB5F69800000000000000100, 7480000000000000BB5F698000000000000001040DE0B6B3A7767169040000000000000065)\\\",\\\"(skip 126)\\\",\\\"[7480000000000000BD5F698000000000000001040DE0B6B3A876DFB9040000000000000065040000000000000001, 7480000000000000BD5F698000000000000001040DE0B6B3A8890785040000000000000065040000000000000001)\\\"]\",totalFiles=129,totalKVs=119203973,totalBytes=7324266166,totalSize=7324266166}"]
[2023/06/07 20:35:50.412 +08:00] [INFO] [pipeline_items.go:118] ["restore table done"] [tables="[`bank`.`inner_bill`,`bank`.`account_verify`,`bank`.`account_deposit_aggreement`,`bank`.`currency`]"]
[2023/06/07 20:35:50.412 +08:00] [WARN] [client.go:1686] ["table has no checksum, skipping checksum"] [db=bank] [table=account_verify]
[2023/06/07 20:35:50.412 +08:00] [WARN] [client.go:1686] ["table has no checksum, skipping checksum"] [db=bank] [table=inner_bill]
[2023/06/07 20:35:50.414 +08:00] [INFO] [client.go:1744] ["success in validate checksum"] [db=bank] [table=currency]
[2023/06/07 20:35:50.418 +08:00] [INFO] [client.go:1772] ["start loads analyze after validate checksum"] ["old id"=201] ["new id"=201]
```
### 4. What is your TiDB version? (Required)

| Release Version: v7.2.0-alpha
Edition: Community
Git Commit Hash: aedbcd085bb4ea5777699eac7d25dfd42222b8e5
Git Branch: heads/refs/tags/v7.2.0-alpha
UTC Build Time: 2023-06-07 10:42:08
GoVersion: go1.20.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv |

### LINKED ISSUE #44496: br restore report "panic: runtime error: invalid memory address or nil pointer dereference"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

br restore data to cluster

### 2. What did you expect to see? (Required)
restore successfully
### 3. What did you see instead (Required)
```
61.25%Full Restore <------------------------------------------------..............................> 61.25%Full Restore <-----------------
------------------------------\\..............................> 61.38%Full Restore <-----------------------------------------------|......
........................> 61.38%panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation vio
lation code=0x1 addr=0x0 pc=0x3ab0210]\n\ngoroutine 1356 [running]:\[ngithub.com/pingcap/tidb/statistics/handle.(*Handle).SaveStatsToStorag](http://ngithub.com/pingcap/tidb/statistics/handle.(*Handle).SaveStatsToStorag)
e(0x0, 0x72, 0x989680, 0x0?, 0x0, 0xc00407d560, 0x1d12b8b?, 0x0?, 0x55a5020?, 0x1, ...)\n\t/home/jenkins/agent/workspace/build-common/go/s
rc/[github.com/pingcap/br/statistics/handle/handle.go:1555](http://github.com/pingcap/br/statistics/handle/handle.go:1555) +0x130\[ngithub.com/pingcap/tidb/statistics/handle.(*Handle).loadStatsFromJSON](http://ngithub.com/pingcap/tidb/statistics/handle.(*Handle).loadStatsFromJSON)(0x
c008d71a80?, 0xc008d71a68?, 0x4?, 0xc008d71a68?)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/statistics/han](http://github.com/pingcap/br/statistics/han)
dle/dump.go:382 +0x112\[ngithub.com/pingcap/tidb/statistics/handle.(*Handle).LoadStatsFromJSON](http://ngithub.com/pingcap/tidb/statistics/handle.(*Handle).LoadStatsFromJSON)(0xc00199a000?, {0x634b9c8, 0xc00a2b5f80}, 0x
c008647650)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/statistics/handle/dump.go:347](http://github.com/pingcap/br/statistics/handle/dump.go:347) +0x14f\[ngithub.com/pi](http://ngithub.com/pi)
ngcap/tidb/br/pkg/restore.(*Client).updateMetaAndLoadStats(0xc000859b00, {0x6314db0, 0xc001118780}, 0xc002929f80)\n\t/home/jenkins/agent/w
orkspace/build-common/go/src/[github.com/pingcap/br/br/pkg/restore/client.go:1777](http://github.com/pingcap/br/br/pkg/restore/client.go:1777) +0x6c5\[ngithub.com/pingcap/tidb/br/pkg/restore.(*Client)](http://ngithub.com/pingcap/tidb/br/pkg/restore.(*Client)).
GoValidateChecksum.func1()\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/restore/client.go:1626](http://github.com/pingcap/br/br/pkg/restore/client.go:1626) +0x68\
ncreated by [github.com/pingcap/tidb/br/pkg/restore.(*Client).GoValidateChecksum\n\t/home/jenkins/agent/workspace/build-common/go/src/githu](http://github.com/pingcap/tidb/br/pkg/restore.(*Client).GoValidateChecksum/n/t/home/jenkins/agent/workspace/build-common/go/src/githu)
[b.com/pingcap/br/br/pkg/restore/client.go:1624](http://b.com/pingcap/br/br/pkg/restore/client.go:1624) +0x185\n", "error": "command terminated with exit code 2"}
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #44496, close #44490

Problem Summary:

https://github.com/pingcap/tidb/pull/44338 add a goroutine to detect exit signal for `UpdateTableStatsLoop`. It breaks the test `TestIsOnline` because it runs `UpdateTableStatsLoop` twice. #44338 removes the loop from glue, resulting in failures of BR's integration tests.

### What is changed and how it works?

Check if the domain exists and run `UpdateTableStatsLoop` only if necessary.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]
/lgtm

**Review by Leavrth — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]

**Pull request merged**
