### PR TITLE
admin: only check public index (#8748)

### PR DESCRIPTION
**Pull request by crazycs520**
cherry-pick https://github.com/pingcap/tidb/pull/8748

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8749)

### CODE REVIEW

**Comment by crazycs520** [comment]
/run-all-tests tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by crazycs520** [comment]
/run-unit-test -tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by winkyao** [comment]
/run-unit-test -tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by crazycs520** [comment]
/run-unit-test -tidb-test=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by crazycs520** [comment]
/run-all-tests tikv=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Pull request merged**
