### PR TITLE
planner, util: move FastIntSet to util

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

This pull moves the `FastIntSet` from the `planner`'s subpackage to the util.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by elsa0520 — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Comment by winoros** [comment]
After some discussion, we have another way to fix the potential panic. This pull is not needed. Close it first.

**Comment by winoros** [comment]
Wrong operation(

**Pull request merged**
