### PR TITLE
metrics: Add a new performance overview dashboard

### LINKED ISSUE #31676: Need a Peroformance overview dashboard
## Enhancement
Currently, to identified a performance issue from top-down. User need to go through multiple dashboard/panels
1. to identify if the performance issue is inside or outside TiDB cluster.
2. to identify the resource usage of TiDB/TiKV/PD nodes.
3. to identify the query duration bottleneck
4. to identify if there is slow query
5. to identify if there is hot spot across the stores.
6. many more ....

There is no good start point and general approach for user to drill down performance issues.
I'll propose to add a performance overview dashboard, to show the core performance metrics on the typical critical path in one dashboard and make the metric analysis on TiDB much easier.

### PR DESCRIPTION
**Pull request by dbsid**
### What problem does this PR solve?

Issue Number: close #31676

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [x] No code

import the dashboard to existing grafana and enjoy the strait-forward metrics

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
add a performance overview dashboard, to show the core performance metrics on the typical critical path in one dashboard and make the metric analysis on TiDB much easier
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]
Why does CI need to run the build/golint/test for changing the metrics dashboard? What a waste of resources.

**Comment by hawkingrei** [comment]
> /assign @hawkingrei @breeswish

Sorry, I have no access to merge.

**Comment by hawkingrei** [comment]
@tangenta @breeswish @tisonkun @AilinKid  PTAL

**Review by breeswish — APPROVED** [review]

**Pull request merged**
