### PR TITLE
*: support go:build lines for go1.17

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Issue Number: None

Problem Summary:

Since go1.17, there is a new build constraint line introduced, see [Bug-resistant build constraints — Draft Design](https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md) for more details.

### What is changed and how it works?

Support the new `go:build` lines for go1.17.

### Check List

Tests 

- [x] Unit test
- [x] Integration test

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by JmPotato** [comment]
/cc @disksing @morgo
PTAL, thx!

**Comment by kennytm** [comment]
duplicate of #28784

**Comment by disksing** [comment]
Better to close this one and merge the old one.

**Comment by JmPotato** [comment]
Close due to #28784.

**Pull request closed without merging**
