### PR TITLE
ddl: reorder flags checking

### LINKED ISSUE #23473: `NO_DEFAULT_VALUE` disappeared after altering primary key
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Execute following sql via mysql command with `--column-type-info`.
```sql
drop table if exists t;
create table t (k int primary key, v int);
select * from t;
alter table t change column k k bigint;
select * from t;
```
It may lead to a failure of amend txn at the first time of altering primary key.

Note that if we create table as `create table t (k int auto_increment primary key, v int)`, there is no `NO_DEFAULT_VALUE`.

### 2. What did you expect to see? (Required)

The flags of column keep unchanged.

### 3. What did you see instead (Required)

```
MySQL [test]> create table t (k int primary key , v int);
Query OK, 0 rows affected (0.126 sec)

MySQL [test]> select * from t;
Field   1:  `k`
Catalog:    `def`
Database:   `test`
Table:      `t`
Org_table:  `t`
Type:       LONG
Collation:  binary (63)
Length:     11
Max_length: 0
Decimals:   0
Flags:      NOT_NULL PRI_KEY NO_DEFAULT_VALUE NUM 

Field   2:  `v`
Catalog:    `def`
Database:   `test`
Table:      `t`
Org_table:  `t`
Type:       LONG
Collation:  binary (63)
Length:     11
Max_length: 0
Decimals:   0
Flags:      NUM 


0 rows in set (0.058 sec)

MySQL [test]> alter table t change column k k bigint;
Query OK, 0 rows affected (0.114 sec)

MySQL [test]> select * from t;
Field   1:  `k`
Catalog:    `def`
Database:   `test`
Table:      `t`
Org_table:  `t`
Type:       LONGLONG
Collation:  binary (63)
Length:     20
Max_length: 0
Decimals:   0
Flags:      NOT_NULL PRI_KEY NUM 

Field   2:  `v`
Catalog:    `def`
Database:   `test`
Table:      `t`
Org_table:  `t`
Type:       LONG
Collation:  binary (63)
Length:     11
Max_length: 0
Decimals:   0
Flags:      NUM 


0 rows in set (0.046 sec)

```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #23473 

Problem Summary: The `NoDefault` flag, which is set by `processColumnOptions->processDefaultValue->setNoDefaultValueFlag`, depends on `NotNull` flag, which is set by the code after `processColumnOptions`.

That is, `setNoDefaultValueFlag` will never found the needed `NotNull` flag: it is set after the invocation of `setNoDefaultValueFlag`. This PR is a quick fix.

But I believe there is more bugs due to the incorrect order of flag processing. I am checking the source of mysql. I will try to do a cleanup and complete tests in the next PR.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

**Review by djshow832 — COMMENTED** [review]
I don't see why moving this block can solve the problem. Can you describe the reason and add test cases?

**Comment by xhebox** [comment]
/cc @djshow832  @zimulala 

Modified the description a little.

**Pull request merged**
