### PR TITLE
sessionctx: fix a deadlock when set `tidb_restricted_read_only = true`

### LINKED ISSUE #53822: POTENTIAL DEADLOCK: Recursive locking TestAutoCommitRespectsReadOnly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
see https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/ghpr_unit_test/runs/10712/nodes/63/steps/69/log/?start=0

```
POTENTIAL DEADLOCK: Recursive locking:
current goroutine 123 lock 0xc007ef60c8
pkg/domain/sysvar_cache.go:120 domain.(*Domain).rebuildSysVarCache ??? <<<<<
pkg/domain/sysvar_cache.go:119 domain.(*Domain).rebuildSysVarCache ???
pkg/domain/domain.go:2639 domain.(*Domain).NotifyUpdateSysVarCache ???
pkg/session/session.go:1283 session.(*session).replaceGlobalVariablesTableValue ???
pkg/session/session.go:1344 session.(*session).SetGlobalSysVar ???
pkg/sessionctx/variable/sysvar.go:823 variable.glob..func164 ???
pkg/domain/sysvar_cache.go:146 domain.(*Domain).rebuildSysVarCache ???
pkg/domain/domain.go:2639 domain.(*Domain).NotifyUpdateSysVarCache ???
pkg/session/session.go:1283 session.(*session).replaceGlobalVariablesTableValue ???
pkg/session/session.go:1344 session.(*session).SetGlobalSysVar ???
pkg/executor/set.go:155 executor.(*SetExecutor).setSysVariable ???
pkg/executor/set.go:104 executor.(*SetExecutor).Next ???
pkg/executor/internal/exec/executor.go:409 exec.Next ???
pkg/executor/adapter.go:1212 executor.(*ExecStmt).next ???
pkg/executor/adapter.go:960 executor.(*ExecStmt).handleNoDelayExecutor ???
pkg/executor/adapter.go:794 executor.(*ExecStmt).handleNoDelay ???
pkg/executor/adapter.go:558 executor.(*ExecStmt).Exec ???
pkg/session/session.go:2284 session.runStmt ???
pkg/session/session.go:2162 session.(*session).ExecuteStmt ???
pkg/testkit/testkit.go:394 testkit.(*TestKit).ExecWithContext ???
external/com_github_pingcap_errors/juju_adaptor.go:112 errors.ErrorStack ???
pkg/testkit/testkit.go:150 testkit.(*TestKit).MustExec ???
pkg/session/test/txn/txn_test.go:298 txn_test.TestAutoCommitRespectsReadOnly ???

Previous place where the lock was grabbed (same goroutine)
pkg/domain/sysvar_cache.go:120 domain.(*Domain).rebuildSysVarCache ??? <<<<<
pkg/domain/sysvar_cache.go:119 domain.(*Domain).rebuildSysVarCache ???
pkg/domain/domain.go:2639 domain.(*Domain).NotifyUpdateSysVarCache ???
pkg/session/session.go:1283 session.(*session).replaceGlobalVariablesTableValue ???
pkg/session/session.go:1344 session.(*session).SetGlobalSysVar ???
pkg/executor/set.go:155 executor.(*SetExecutor).setSysVariable ???
pkg/executor/set.go:104 executor.(*SetExecutor).Next ???
pkg/executor/internal/exec/executor.go:409 exec.Next ???
pkg/executor/adapter.go:1212 executor.(*ExecStmt).next ???
pkg/executor/adapter.go:960 executor.(*ExecStmt).handleNoDelayExecutor ???
pkg/executor/adapter.go:794 executor.(*ExecStmt).handleNoDelay ???
pkg/executor/adapter.go:558 executor.(*ExecStmt).Exec ???
pkg/session/session.go:2284 session.runStmt ???
pkg/session/session.go:2162 session.(*session).ExecuteStmt ???
pkg/testkit/testkit.go:394 testkit.(*TestKit).ExecWithContext ???
external/com_github_pingcap_errors/juju_adaptor.go:112 errors.ErrorStack ???
pkg/testkit/testkit.go:150 testkit.(*TestKit).MustExec ???
pkg/session/test/txn/txn_test.go:298 txn_test.TestAutoCommitRespectsReadOnly ???

```

### 4. What is your TiDB version? (Required)
master

### LINKED ISSUE #55373: small probability recursive lock (deadlock) when setting `tidb_restricted_read_only`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sh
count=0
while true; do
mysql -h 127.0.0.1 -P 4000 -u root -e "set global tidb_restricted_read_only = 1;set global tidb_restricted_read_only = 0;";
count=$((count+1))
echo "$count"
done
```

I tried several times, in most times it can be triggered before the count reaches 5000.

### 2. What did you expect to see? (Required)

The SET statement above blocks forever, and any following SET GLOBAL statements will block forever.

### 3. What did you see instead (Required)

Execute and finish successfully.

### 4. What is your TiDB version? (Required)

I'm using v8.2.0 and master, but I believe many versions have this bug.

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #55373, close #53822, 

Problem Summary: follow https://github.com/pingcap/tidb/pull/40283

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

run shell below, reach more than 10000
```shell
count=0
while true; do
mysql -h 127.0.0.1 -P 4000 -u root -e "set global tidb_restricted_read_only = 1;set global tidb_restricted_read_only = 0;";
count=$((count+1))
echo "$count"
done
```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by CbcWestwolf — APPROVED** [review]

**Comment by YangKeao** [comment]
This bug may happen when setting any global variables after setting `tidb_restricted_read_only`. Therefore, I'll cherry-pick it back to all LTS versions.

**Pull request merged**
