### PR TITLE
*: fix aggregation bug in new plan.

### PR DESCRIPTION
**Pull request by hanfei1991**
There are two bugs in new plan:
1. Distinct agg shouldn't be pushed.
2. Avg function should push both partial results to bytes slice in TiKV.

@shenli @zimulala @coocood PTAL

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by winoros** [comment]
add a test in dag_plan_test.go about distinct?

**Comment by zimulala** [comment]
LGTM

**Comment by hanfei1991** [comment]
@winoros PTAL

**Pull request merged**
