### PR TITLE
executor: split aggregate.go into several files

### LINKED ISSUE #46487: aggregate.go file needs to be split
## Enhancement

Many data structs are all put in this file which make the code complexity and be hard to read.

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #46487

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by XuHuaiyu — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM

**Comment by hawkingrei** [comment]
If you want to refactor it, Please split it into new package.

**Review by hawkingrei — APPROVED** [review]

**Pull request merged**
