### PR TITLE
distsql: fix goroutine/memory leak for streaming when query is cancelled (#27354)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #27354 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/27380
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/27380:release-5.1-7ac584391ec5
```

---

Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Close https://github.com/pingcap/tidb/issues/27353

### What is changed and how it works?

It's was caused by `streamResult.Close` doesn't close the `kv.Response`.

### Check List 

Tests 

- [x] Manual test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

**Review by lysu — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
@ti-chi-bot

**Pull request merged**
