### PR TITLE
server: fix ComStmtSendLongData when data length is 0

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve? 
`setCharacterStream(1, new StringReader(""), 0);` this API in JDBC will use `ComStmtSendLongData` to send a long string. When the data length is 0, TiDB cannot distinguish whether there is a parameter with no data or there is no parameter at all. 

### What is changed and how it works?
This pr appends an extra 0 at the end of the bound parameter. In ComStmtExecute, we use it to distinguish if there is a parameter or not.
(How does MySQL deal with this? 
MySQL set the length of the parameter as len(data - 6), which 6 is the length of the header of the request.)

### Check List 

Tests 

 - Integration test (JDBC test cases)

Code changes

 - Has exported function/method change

Side effects

 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch

PTAL @coocood

### CODE REVIEW

**Comment by coocood** [comment]
@jackysp 

This is a way to solve the problem, but may not the best.
The problem is that a nil slice appending a zero-length slice is still nil slice.

We can make it work like this in `TiDBStatement`
```
	if len(data) == 0 {
		ts.boundParams[paramID] = []byte{}
	} else {
		ts.boundParams[paramID] = append(ts.boundParams[paramID], data...)
	}
```

**Comment by jackysp** [comment]
PTAL @coocood

**Comment by coocood** [comment]
LGTM

**Pull request merged**
