### PR TITLE
store/tikv: Add a test that checks prewrites properly set secondaries for async commit transactions

### PR DESCRIPTION
**Pull request by MyonKeminta**
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>

### What is changed and how it works?

What's Changed: Adds a unit test that tries to checks that `prewrite` of async commit transactions has properly set the `secondaries` field for primary lock.

This can be merged after https://github.com/pingcap/tidb/pull/20150 so that the test can be moved to `async_commit_fail_test.go`.

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- No release note

### CODE REVIEW

**Review by sticnarf — COMMENTED** [review]
LGTM

**Comment by cfzjywxk** [comment]
LGTM

**Comment by MyonKeminta** [comment]
```
[2020-09-24T14:37:31.255Z] panic: runtime error: invalid memory address or nil pointer dereference

[2020-09-24T14:37:31.255Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2acf822]

[2020-09-24T14:37:31.255Z] 

[2020-09-24T14:37:31.255Z] goroutine 15008 [running]:

[2020-09-24T14:37:31.255Z] github.com/pingcap/tidb/util/execdetails.(*BasicRuntimeStats).GetTime(...)

[2020-09-24T14:37:31.255Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/execdetails/execdetails.go:555

[2020-09-24T14:37:31.255Z] github.com/pingcap/tidb/executor.(*insertRuntimeStat).String(0xc029462a60, 0x3aca300, 0xc0293d5c80)

[2020-09-24T14:37:31.255Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/insert_common.go:1072 +0x1d2

[2020-09-24T14:37:31.255Z] github.com/pingcap/tidb/util/execdetails.(*RootRuntimeStats).String(0xc0092429c0, 0x1, 0xc0092429c0)

[2020-09-24T14:37:31.255Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/execdetails/execdetails.go:530 +0x235

[2020-09-24T14:37:31.255Z] github.com/pingcap/tidb/planner/core.getRuntimeInfo(0x3b0f2a0, 0xc008031590, 0x3af8b60, 0xc00f494600, 0xc00939f620, 0xc00939f5f0, 0x203002, 0x203002, 0x203002, 0xc00939f530, ...)

[2020-09-24T14:37:31.255Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/common_plans.go:1069 +0x38b

[2020-09-24T14:37:31.255Z] github.com/pingcap/tidb/planner/core.(*planEncoder).encodePlan(0xc014d49740, 0x3af8b60, 0xc00f494600, 0x1, 0x0)

[2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/encode.go:64 +0xaa

[2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/planner/core.(*planEncoder).encodePlanTree(0xc014d49740, 0x3af8b60, 0xc00f494600, 0x0, 0x2)

[2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/encode.go:58 +0x84

[2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/planner/core.EncodePlan(0x3af8b60, 0xc00f494600, 0x0, 0x0)

[2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/encode.go:52 +0x123

[2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/executor.getPlanTree(0x3af8b60, 0xc00f494600, 0x3af8b60, 0xc00f494600)

[2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:955 +0x87

[2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/executor.(*ExecStmt).LogSlowQuery(0xc0091f6840, 0x5d30230faec0014, 0x3ac0000)

[2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:899 +0x456

[2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/executor.(*ExecStmt).FinishExecuteStmt(0xc0091f6840, 0x5d30230faec0014, 0xc008030000)

[2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:810 +0xeb

[2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/session.runStmt(0x3ac77c0, 0xc000062070, 0xc008031590, 0x3ae5f40, 0xc0091f6840, 0x0, 0x0, 0x3a6bb20, 0xc0293f0920)

[2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1235 +0x446

[2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc008031590, 0x3ac77c0, 0xc000062070, 0x3ad08c0, 0xc00917d790, 0x0, 0x0, 0x0, 0x0)

[2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1171 +0x7b9

[2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/util/testkit.(*TestKit).Exec(0xc0090b6480, 0x3566ad0, 0x1d, 0x0, 0x0, 0x0, 0xc02935b4f0, 0xc009519260, 0x0, 0x0)

[2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x215

[2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/session_test.(*testPessimisticSuite).TestPointGetKeyLock.func2(0xc0090b6480, 0xc0080313b0, 0xc01501f3e0)

[2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/pessimistic_test.go:306 +0x89

[2020-09-24T14:37:31.256Z] created by github.com/pingcap/tidb/session_test.(*testPessimisticSuite).TestPointGetKeyLock

[2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/pessimistic_test.go:304 +0x434

[2020-09-24T14:37:31.512Z] exit status 2

[2020-09-24T14:37:31.512Z] FAIL	github.com/pingcap/tidb/session	63.717s
```
Seems it doesn't look like caused by this PR?

**Comment by cfzjywxk** [comment]
> ```
> [2020-09-24T14:37:31.255Z] panic: runtime error: invalid memory address or nil pointer dereference
> 
> [2020-09-24T14:37:31.255Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2acf822]
> 
> [2020-09-24T14:37:31.255Z] 
> 
> [2020-09-24T14:37:31.255Z] goroutine 15008 [running]:
> 
> [2020-09-24T14:37:31.255Z] github.com/pingcap/tidb/util/execdetails.(*BasicRuntimeStats).GetTime(...)
> 
> [2020-09-24T14:37:31.255Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/execdetails/execdetails.go:555
> 
> [2020-09-24T14:37:31.255Z] github.com/pingcap/tidb/executor.(*insertRuntimeStat).String(0xc029462a60, 0x3aca300, 0xc0293d5c80)
> 
> [2020-09-24T14:37:31.255Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/insert_common.go:1072 +0x1d2
> 
> [2020-09-24T14:37:31.255Z] github.com/pingcap/tidb/util/execdetails.(*RootRuntimeStats).String(0xc0092429c0, 0x1, 0xc0092429c0)
> 
> [2020-09-24T14:37:31.255Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/execdetails/execdetails.go:530 +0x235
> 
> [2020-09-24T14:37:31.255Z] github.com/pingcap/tidb/planner/core.getRuntimeInfo(0x3b0f2a0, 0xc008031590, 0x3af8b60, 0xc00f494600, 0xc00939f620, 0xc00939f5f0, 0x203002, 0x203002, 0x203002, 0xc00939f530, ...)
> 
> [2020-09-24T14:37:31.255Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/common_plans.go:1069 +0x38b
> 
> [2020-09-24T14:37:31.255Z] github.com/pingcap/tidb/planner/core.(*planEncoder).encodePlan(0xc014d49740, 0x3af8b60, 0xc00f494600, 0x1, 0x0)
> 
> [2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/encode.go:64 +0xaa
> 
> [2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/planner/core.(*planEncoder).encodePlanTree(0xc014d49740, 0x3af8b60, 0xc00f494600, 0x0, 0x2)
> 
> [2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/encode.go:58 +0x84
> 
> [2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/planner/core.EncodePlan(0x3af8b60, 0xc00f494600, 0x0, 0x0)
> 
> [2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/encode.go:52 +0x123
> 
> [2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/executor.getPlanTree(0x3af8b60, 0xc00f494600, 0x3af8b60, 0xc00f494600)
> 
> [2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:955 +0x87
> 
> [2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/executor.(*ExecStmt).LogSlowQuery(0xc0091f6840, 0x5d30230faec0014, 0x3ac0000)
> 
> [2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:899 +0x456
> 
> [2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/executor.(*ExecStmt).FinishExecuteStmt(0xc0091f6840, 0x5d30230faec0014, 0xc008030000)
> 
> [2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:810 +0xeb
> 
> [2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/session.runStmt(0x3ac77c0, 0xc000062070, 0xc008031590, 0x3ae5f40, 0xc0091f6840, 0x0, 0x0, 0x3a6bb20, 0xc0293f0920)
> 
> [2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1235 +0x446
> 
> [2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc008031590, 0x3ac77c0, 0xc000062070, 0x3ad08c0, 0xc00917d790, 0x0, 0x0, 0x0, 0x0)
> 
> [2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1171 +0x7b9
> 
> [2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/util/testkit.(*TestKit).Exec(0xc0090b6480, 0x3566ad0, 0x1d, 0x0, 0x0, 0x0, 0xc02935b4f0, 0xc009519260, 0x0, 0x0)
> 
> [2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x215
> 
> [2020-09-24T14:37:31.256Z] github.com/pingcap/tidb/session_test.(*testPessimisticSuite).TestPointGetKeyLock.func2(0xc0090b6480, 0xc0080313b0, 0xc01501f3e0)
> 
> [2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/pessimistic_test.go:306 +0x89
> 
> [2020-09-24T14:37:31.256Z] created by github.com/pingcap/tidb/session_test.(*testPessimisticSuite).TestPointGetKeyLock
> 
> [2020-09-24T14:37:31.256Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/pessimistic_test.go:304 +0x434
> 
> [2020-09-24T14:37:31.512Z] exit status 2
> 
> [2020-09-24T14:37:31.512Z] FAIL	github.com/pingcap/tidb/session	63.717s
> ```
> 
> Seems it doesn't look like caused by this PR?

We could create an issue for this, it's another bug...

**Comment by MyonKeminta** [comment]
Ok.

**Pull request merged**
