### PR TITLE
export: support dataflow engine metrics factory

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #34948

Problem Summary:

### What is changed and how it works?

added an interface, so for standalone dumpling and injected scenario, the logic is more unified.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lichunzhu — APPROVED** [review]
LGTM
do we need some unit tests for this new interface?

**Comment by lance6716** [comment]
> LGTM do we need some unit tests for this new interface?

This is done at dataflow engine side. https://github.com/pingcap/tiflow/tree/master/engine/pkg/promutil

**Review by gozssky — APPROVED** [review]

**Pull request merged**
