### PR TITLE
expression: ECB/CBC modes with 128/192/256-bit key length for AES (#7425)

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 
#cherry-pick https://github.com/pingcap/tidb/pull/7425
This is a patch for client. DNM.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

Related changes

### CODE REVIEW

**Comment by crazycs520** [comment]
@zz-jason @lysu PTAL

**Comment by lysu** [comment]
LGTM

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.0 tidb-private-test=release-2.0 tikv=release-2.0

**Comment by crazycs520** [comment]
/run-all-tests tidb-test=release-2.0 tidb-private-test=release-2.0 tikv=release-2.0

**Comment by crazycs520** [comment]
@zz-jason Let's merge this to release2.0

**Pull request merged**
