### PR TITLE
execdetails: remove useless `lmSkipRows`

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### What changed and how does it work?

`dmfileLmFilterScannedRows` and `dmfileLmFilterSkippedRows` are enough.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zimulala — COMMENTED** [review]
Could you briefly describe the meaning of this variable(`lmSkipRows`) and the variables that can replace it?

**Comment by Lloyd-Pottiger** [comment]
> Could you briefly describe the meaning of this variable(`lmSkipRows`) and the variables that can replace it?

`lmSkipRows` means the rows skipped by late materialization, which is the same as `dmfileLmFilterSkippedRows` now, so remove it.

**Review by xzhangxian1008 — APPROVED** [review]
LGTM

**Comment by JaySon-Huang** [comment]
Related tiflash PR: https://github.com/pingcap/tiflash/pull/9709

**Review by JaySon-Huang — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

**Review by zanmato1984 — APPROVED** [review]

**Pull request merged**
