### PR TITLE
util/systimemon: migrate test-infra to testify

### LINKED ISSUE #26424: migrate test-infra to testify for `util/systimemon` pkg

### PR DESCRIPTION
**Pull request by yedamao**
### What problem does this PR solve?

Issue Number: close #26424 

### Release note 

```release-note
None.
```

### CODE REVIEW

**Review by tisonkun — CHANGES_REQUESTED** [review]
Thanks for your contribution @yedamao !

You'd need call `goleak.VerifyTestMain(m)` in `main_test.go` for really executing the tests.

See `util/arena/main_test.go` for example.

**Comment by tisonkun** [comment]
I'll do you a favor now : P

**Review by tisonkun — APPROVED** [review]
LGTM.

testify has fruitful checkers, confirmed.

**Comment by tisonkun** [comment]
cc @mmyj

**Review by xhebox — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
