### PR TITLE
session: refine record execution duration metric

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

image

Before, the `Execution Duration` of Select was not right, it almost only records the time duration of `executor.Open`.  

### What is changed and how it works?

Refine record execution duration metric.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test
- No new code.

Side effects

- No.

### Release note 

- Fix the  execution duration metric of `SELECT` statement.

### CODE REVIEW

**Comment by crazycs520** [comment]
@tiancaiamao @lysu  PTAL

**Comment by tiancaiamao** [comment]
LGTM

**Comment by zz-jason** [comment]
@crazycs520 should we cherry pick this PR to release 4.0?

**Pull request merged**
