### PR TITLE
statistics: dump FMSketch to KV only for partition table with dynamic prune mode (#24453)

### LINKED ISSUE #24401: Write FM Sketch data to KV even if the table isn't partition table or in static partition prune mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```
create table t(a int, index(a));
insert into t values (1), (2), (3);
analyze table t;
select * from mysql.stats_fm_sketch;
```

### 2. What did you expect to see? (Required)

Empty set.

### 3. What did you see instead (Required)

```
+----------+----------+---------+------------------------------------+
| table_id | is_index | hist_id | value                              |
+----------+----------+---------+------------------------------------+
|       53 |        0 |       1 | �񎇹Ȫ�!������՚����������                         |
|       53 |        1 |       1 | ��������"눭�����O�ֻ�����▒                        |
+----------+----------+---------+------------------------------------+
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
```
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-2751-ga1d4d9d02
Edition: Community
Git Commit Hash: a1d4d9d02843c50c1c8c67f58597ca61b77a2bac
Git Branch: HEAD
UTC Build Time: 2021-04-30 10:04:16
GoVersion: go1.16.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #24453 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/24539
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/24539:release-5.0-3fed33fc1735
```

---

### What problem does this PR solve?

Issue Number: close #24401 

Problem Summary:

### What is changed and how it works?

What's Changed:

We only dump FMSketch to KV for partition table with dynamic prune mode.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- statistics: dump FMSketch to KV only for partition table with dynamic prune mode

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Comment by eurekaka** [comment]
Not critical enough, this PR will not be merged into 5.0.

**Pull request closed without merging**
