### PR TITLE
*: Add support for MAX_EXECUTION_TIME (#10541) (#10963)

### PR DESCRIPTION
**Pull request by tiancaiamao**
Cherry-pick https://github.com/pingcap/tidb/pull/10541 and  https://github.com/pingcap/tidb/pull/10963

10541 adds support for MAX_EXECUTION_TIME, and 10963 is a tiny fix (2 line changes) for 10541, so I merge them into this one.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @crazycs520 @qw4990

**Comment by zz-jason** [comment]
It's better to cherry pick PRs one by one, no matter how small a PR is.

**Comment by tiancaiamao** [comment]
MAX_EXECUTION_TIME is a newly introduced feature. If we don't cherry pick the first PR, there is no need to cherry-pick the bug fix, so it's better for them to be together.
One additional advantage is that it cost less energy to address conflicts during the cherry-pick.
If we split it into two PRs, we have to cherry-pick twice, address conflicts twice, and the second one has to wait for the first one to be merged.... even it's only two lines change. @zz-jason

**Comment by tiancaiamao** [comment]
I agree that 

> It's better to cherry pick PRs one by one

But it's stubborn to always follow this rule.

**Comment by tiancaiamao** [comment]
/run-all-tests tidb-test=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by tiancaiamao** [comment]
Waiting for https://github.com/pingcap/tidb/pull/11048

**Comment by tiancaiamao** [comment]
/run-all-tests tidb-test=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by zz-jason** [comment]
@tiancaiamao Please fix the conflicts

**Comment by tiancaiamao** [comment]
Conflicts are fixed @zz-jason

**Comment by tiancaiamao** [comment]
/run-all-tests tidb-test=release-3.0 tikv=release-3.0 pd=release-3.0

**Pull request merged**
