### PR TITLE
sessionctx: set default val of EnableOuterJoinReorder to true

### LINKED ISSUE #39504: re-enable the outer join reorder
## Enhancement
We've supplemented some new tests. So we enable it.

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #39504 

Problem Summary:

### What is changed and how it works?

Just as the issue said.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by winoros** [comment]
@ti-chi-bot

**Pull request merged**
