### PR TITLE
server: fix format for select constant

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve? 
For #9463 

### What is changed and how it works?
Add `NotNullFlag` before return column info to Mysql-client.
It seems that `NotNullFlag` is needed for column which has `BinaryFlag`

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by wjhuang2016** [comment]
It didn't work for `select -1;` or `select 1+1;`.
I think it's because the flag get lost when doing constant fold, I try to add the flag in foldConstant in expression/constan_fold.go. It works but when tests it failed for some errors I can't understand.

**Comment by XuHuaiyu** [comment]
> It works but when tests it failed for some errors I can't understand.
Hi, @wjhuang2016  
What do you mean by this, which test failed?

**Comment by wjhuang2016** [comment]
> > It works but when tests it failed for some errors I can't understand.
> > Hi, @wjhuang2016
> > What do you mean by this, which test failed?

Some DDLs, and the error log is so long I can't find anything useful.
When `make dev`,
After  `github.com/pingcap/tidb/config	(cached)`
It take a long time to wait for `github.com/pingcap/tidb/ddl` to complete.
Finaly, it failed and print a long log.

**Comment by wjhuang2016** [comment]
I find the use of NotNullFlag, It seems that no statements use it in way may cause error, so the test failing really confuse me.

**Comment by wjhuang2016** [comment]
@XuHuaiyu PTAL

**Comment by zz-jason** [comment]
@wjhuang2016 Please add some tests

**Comment by wjhuang2016** [comment]
> @wjhuang2016 Please add some tests

The change involes responsing to client like #7417 , maybe we need a integration test.

**Comment by wjhuang2016** [comment]
> How about add some integration unit tests in `integration_test.go`?

I don't know how to test it in `integration_test.go`.
The problem here is a little complicated.
I think the problem is that we need to send a `NotNullFlag` to Mysql-client, it's a protocal problem. So simplely test the flag in server side maybe not a good test.
And I can't make sure that sending a `NotNullFlag` to Mysql-client is the right solution, maybe we need to compare the Mysql data packet?

**Comment by XuHuaiyu** [comment]
It seems that we can add a test case like `sever/tidb-test.go: TestCreateTableFlen` to check the Flag of the result.

**Comment by qw4990** [comment]
Almost LGTM, but please fix the unit test `ConnTestSuite.TestDispatch` when it's convenient for you @wjhuang2016 .

**Pull request merged**
