### PR TITLE
store/tikv: remove unused failpoints

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?
Some failpoints in `store/tikv` are not used.

### What is changed and how it works?

Remove them.

Note: There are some failpoints that are not used in the code that are marked as being able to be set via HTTP, but I have not found a place to use them and all the tests can pass. I'll delete them here and add them back if something goes wrong.

### Check List 

Tests 
- Unit test

### Release note 
- No release note

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

**Comment by youjiali1995** [comment]
Some of them are used in the integration tests. /cc @MyonKeminta

**Comment by MyonKeminta** [comment]
Many of your removed failpoints are used in UTF test cases and other manual injections. Please refer to our internal document [here](https://docs.google.com/document/d/1tRpHnv_Q5kxc8INQ1qzqNcTgJoZSPdAv3C3m38wry2k/edit#heading=h.rp0b82p9bu9r).

**Comment by disksing** [comment]
> Many of your removed failpoints are used in UTF test cases and other manual injections. Please refer to our internal document [here](https://docs.google.com/document/d/1tRpHnv_Q5kxc8INQ1qzqNcTgJoZSPdAv3C3m38wry2k/edit#heading=h.rp0b82p9bu9r).

Do we have any code references that are using these failpoints?

**Comment by MyonKeminta** [comment]
> > Many of your removed failpoints are used in UTF test cases and other manual injections. Please refer to our internal document [here](https://docs.google.com/document/d/1tRpHnv_Q5kxc8INQ1qzqNcTgJoZSPdAv3C3m38wry2k/edit#heading=h.rp0b82p9bu9r).
> 
> Do we have any code references that are using these failpoints?

Some of them are used in https://github.com/pingcap/automated-tests , some of them are used in other places that I don't know if it's in any repo (maybe @zyguan knows more), and some of them are prepared for future usages

**Comment by zyguan** [comment]
Yes, the following test cases also use them:
- [jepsen](https://github.com/zyguan/tidb-jepsen/blob/a5da735d19a53ec1627f2f064b6c2bbea037a83e/tidb/src/tidb/util.clj#L51-L70)
- [tiacid](https://github.com/PingCAP-QE/tiacid/pull/17/files#diff-8336a448069d08163da12eb90ea1fe6327bc3b1db6f7ea176726f9f24cd430f0)

**Comment by disksing** [comment]
Thanks @youjiali1995 @MyonKeminta @zyguan for providing information.
As store/tikv is going to be migrated to a separate directory, I will be making some adjustments to the failpoint implementation. I will try to find a way to keep the original HTTP interface available. But afterwards I will need your help to run these external tests to make sure they are OK.
Closing this PR.

**Pull request closed without merging**
